// HP Patwari Full Mock 6 — 100 questions (30 HP GK, 20 GK, 15 Reasoning, 15 Maths, 15 Hindi/English, 5 Revenue/Computer).

import { q, type PatwariQuestion } from "./types";

export const mock6: PatwariQuestion[] = [
  // ───────── Section 0: Himachal GK (30) ─────────
  q(0, "hp-gk", "history", "H", 2,
    ["The town of Nurpur in Kangra district, earlier called Dhameri, was renamed by the Mughal emperor Jahangir after:", ["His mother", "His daughter", "Nur Jahan", "A Rajput queen of Nurpur"], "Jahangir renamed Dhameri as Nurpur in honour of his wife Nur Jahan."],
    ["कांगड़ा जिले के नूरपुर कस्बे का पुराना नाम धमेरी था। मुगल सम्राट जहाँगीर ने इसका नाम किसके नाम पर रखा?", ["अपनी माँ", "अपनी पुत्री", "नूरजहाँ", "नूरपुर की एक राजपूत रानी"], "जहाँगीर ने अपनी पत्नी नूरजहाँ के सम्मान में धमेरी का नाम नूरपुर रखा।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["The devastating earthquake that destroyed Kangra and Dharamshala, killing about 20,000 people, struck in:", ["1897", "1905", "1934", "1950"], "The Kangra earthquake of 4 April 1905 ruined the Kangra fort, Jwalamukhi and Dharamshala."],
    ["कांगड़ा और धर्मशाला को तबाह करने वाला विनाशकारी भूकंप, जिसमें लगभग 20,000 लोग मारे गए, किस वर्ष आया?", ["1897", "1905", "1934", "1950"], "4 अप्रैल 1905 के कांगड़ा भूकंप ने कांगड़ा किले, ज्वालामुखी और धर्मशाला को बर्बाद कर दिया।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["Which British Viceroy of India died at Dharamshala in 1863 and is buried in the churchyard of St John in the Wilderness?", ["Lord Canning", "Lord Dalhousie", "Lord Mayo", "Lord Elgin"], "Lord Elgin, Viceroy from 1862, died of a heart attack at Dharamshala in November 1863 during a tour and was buried at St John in the Wilderness."],
    ["भारत के किस ब्रिटिश वायसराय की 1863 में धर्मशाला में मृत्यु हुई और उन्हें सेंट जॉन इन द विल्डरनेस के कब्रिस्तान में दफ़नाया गया?", ["लॉर्ड कैनिंग", "लॉर्ड डलहौज़ी", "लॉर्ड मेयो", "लॉर्ड एल्गिन"], "1862 से वायसराय लॉर्ड एल्गिन की नवंबर 1863 में दौरे के दौरान धर्मशाला में हृदयाघात से मृत्यु हुई और उन्हें सेंट जॉन इन द विल्डरनेस में दफ़नाया गया।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["The Central Tibetan Administration (the Tibetan government in exile) has been based at Dharamshala since:", ["1960", "1947", "1971", "1985"], "After the Dalai Lama fled Tibet in 1959, the Tibetan exile government moved to McLeodganj, Dharamshala, in 1960."],
    ["केंद्रीय तिब्बती प्रशासन (निर्वासित तिब्बती सरकार) धर्मशाला में किस वर्ष से स्थित है?", ["1960", "1947", "1971", "1985"], "1959 में दलाई लामा के तिब्बत छोड़ने के बाद निर्वासित सरकार 1960 में धर्मशाला के मैक्लोडगंज आ गई।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["Himachal Day is celebrated every year on:", ["26 January", "1 November", "15 April", "25 January"], "Himachal Pradesh came into being on 15 April 1948 and the day is celebrated as Himachal Day; statehood day is 25 January."],
    ["हिमाचल दिवस प्रतिवर्ष किस तिथि को मनाया जाता है?", ["26 जनवरी", "1 नवंबर", "15 अप्रैल", "25 जनवरी"], "हिमाचल प्रदेश का गठन 15 अप्रैल 1948 को हुआ और इस दिन हिमाचल दिवस मनाया जाता है; पूर्ण राज्य दिवस 25 जनवरी है।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["Guru Ghantal, believed to be the oldest monastery of Lahaul, is situated near:", ["Keylong", "Tandi", "Kardang", "Sissu"], "The Guru Ghantal (Tupchiling) monastery stands on a hill near Tandi, where the Chandra and Bhaga meet."],
    ["लाहौल का सबसे प्राचीन माना जाने वाला मठ गुरु घंटाल किसके निकट स्थित है?", ["केलांग", "तांदी", "कारदंग", "सिस्सू"], "गुरु घंटाल (तुपचिलिंग) मठ तांदी के पास पहाड़ी पर है, जहाँ चंद्रा और भागा मिलती हैं।"]),
  q(0, "hp-gk", "geography", "H", 3,
    ["The elevation of Himachal Pradesh ranges from about 350 metres to about:", ["4,500 metres", "5,200 metres", "8,000 metres", "6,975 metres"], "The state's altitude varies from about 350 m in the Shivalik foothills to about 6,975 m in the high Himalaya."],
    ["हिमाचल प्रदेश की ऊँचाई लगभग 350 मीटर से लगभग कितने मीटर तक है?", ["4,500 मीटर", "5,200 मीटर", "8,000 मीटर", "6,975 मीटर"], "राज्य की ऊँचाई शिवालिक की तलहटी में लगभग 350 मी से ऊँचे हिमालय में लगभग 6,975 मी तक है।"]),
  q(0, "hp-gk", "geography", "H", 0,
    ["Churdhar (about 3,647 m), the highest peak of the outer Himalayan (lower) ranges of the state, lies in:", ["Sirmaur", "Solan", "Shimla", "Chamba"], "Churdhar, sacred to Shirgul Maharaj, is the highest peak of Sirmaur and of the outer Himalaya in Himachal."],
    ["चूड़धार (लगभग 3,647 मी), जो राज्य की बाह्य हिमालयी (निचली) श्रेणियों की सबसे ऊँची चोटी है, कहाँ स्थित है?", ["सिरमौर", "सोलन", "शिमला", "चंबा"], "शिरगुल महाराज को समर्पित चूड़धार सिरमौर की और हिमाचल की बाह्य हिमालय की सबसे ऊँची चोटी है।"]),
  q(0, "hp-gk", "geography", "H", 2,
    ["The Kunzum Pass (about 4,500 m) connects which two regions of Himachal Pradesh?", ["Kullu and Lahaul", "Kinnaur and Spiti", "Spiti and Lahaul", "Chamba and Lahaul"], "Kunzum La links the Spiti valley with the Chandra valley of Lahaul and is closed by snow in winter."],
    ["कुंजुम दर्रा (लगभग 4,500 मी) हिमाचल प्रदेश के किन दो क्षेत्रों को जोड़ता है?", ["कुल्लू और लाहौल", "किन्नौर और स्पीति", "स्पीति और लाहौल", "चंबा और लाहौल"], "कुंजुम ला स्पीति घाटी को लाहौल की चंद्रा घाटी से जोड़ता है और सर्दियों में बर्फ़ से बंद रहता है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["The Pin Valley National Park, known for the snow leopard and the Siberian ibex, is in:", ["Kinnaur", "Spiti", "Chamba", "Kullu"], "Pin Valley National Park lies in the cold desert of Spiti, Lahaul and Spiti district."],
    ["हिम तेंदुए और साइबेरियन आइबेक्स के लिए प्रसिद्ध पिन वैली नेशनल पार्क कहाँ है?", ["किन्नौर", "स्पीति", "चंबा", "कुल्लू"], "पिन वैली नेशनल पार्क लाहौल एवं स्पीति जिले के स्पीति के ठंडे रेगिस्तान में है।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["Hatu Peak, famous for the temple of Hatu Mata and views of the snow ranges, is near:", ["Kufri", "Narkanda", "Chail", "Kasauli"], "Hatu Peak (about 3,400 m) rises above Narkanda on the Hindustan–Tibet road in Shimla district."],
    ["हाटू माता के मंदिर और हिमाच्छादित श्रेणियों के दृश्य के लिए प्रसिद्ध हाटू चोटी किसके निकट है?", ["कुफरी", "नारकंडा", "चैल", "कसौली"], "हाटू चोटी (लगभग 3,400 मी) शिमला जिले में हिंदुस्तान–तिब्बत सड़क पर नारकंडा के ऊपर है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 3,
    ["Suraj Tal, a lake near the Baralacha Pass, is the source of which river?", ["Chandra", "Spiti", "Ravi", "Bhaga"], "The Bhaga river rises from Suraj Tal near the Baralacha La; it joins the Chandra at Tandi."],
    ["बारालाचा दर्रे के पास स्थित सूरज ताल किस नदी का स्रोत है?", ["चंद्रा", "स्पीति", "रावी", "भागा"], "भागा नदी बारालाचा ला के पास सूरज ताल से निकलती है; वह तांदी में चंद्रा से मिलती है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["In ancient texts the river Ravi was known as:", ["Iravati (Parushni)", "Vipasha", "Shatadru", "Asikni"], "The Ravi is the Iravati or Parushni of the Vedic and later texts; Vipasha is the Beas, Shatadru the Sutlej and Asikni the Chenab."],
    ["प्राचीन ग्रंथों में रावी नदी किस नाम से जानी जाती थी?", ["इरावती (परुष्णी)", "विपाशा", "शतद्रु", "असिक्नी"], "रावी वैदिक और बाद के ग्रंथों की इरावती या परुष्णी है; विपाशा ब्यास, शतद्रु सतलुज और असिक्नी चिनाब है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 2,
    ["The Tirthan river, a tributary of the Beas famous for trout fishing, flows through the valley near:", ["Keylong", "Reckong Peo", "Banjar", "Chamba"], "The Tirthan rises in the Great Himalayan National Park area and flows through Banjar in Kullu to join the Beas."],
    ["ट्राउट मछली पकड़ने के लिए प्रसिद्ध ब्यास की सहायक नदी तीर्थन किसके निकट की घाटी से बहती है?", ["केलांग", "रिकांग पियो", "बंजार", "चंबा"], "तीर्थन ग्रेट हिमालयन नेशनल पार्क क्षेत्र से निकलकर कुल्लू के बंजार से बहती हुई ब्यास में मिलती है।"]),
  q(0, "hp-gk", "districts", "H", 1,
    ["Which district of Himachal Pradesh had the highest literacy rate in the 2011 Census?", ["Kangra", "Hamirpur", "Una", "Bilaspur"], "Hamirpur recorded the highest literacy rate (about 89%); Chamba had the lowest."],
    ["2011 की जनगणना में हिमाचल प्रदेश के किस जिले की साक्षरता दर सबसे अधिक थी?", ["कांगड़ा", "हमीरपुर", "ऊना", "बिलासपुर"], "हमीरपुर की साक्षरता दर सबसे अधिक (लगभग 89%) थी; चंबा की सबसे कम थी।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["Which is the most populous district of Himachal Pradesh?", ["Kangra", "Mandi", "Shimla", "Solan"], "Kangra, with about 15 lakh people in 2011, is the most populous district; Lahaul and Spiti is the least populous."],
    ["हिमाचल प्रदेश का सबसे अधिक जनसंख्या वाला जिला कौन-सा है?", ["कांगड़ा", "मंडी", "शिमला", "सोलन"], "2011 में लगभग 15 लाख आबादी वाला कांगड़ा सबसे अधिक आबादी वाला जिला है; लाहौल एवं स्पीति सबसे कम आबादी वाला है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["'Thoda' is a traditional sport of Himachal Pradesh involving:", ["Wrestling", "Horse racing", "Stone throwing", "Archery"], "Thoda is a traditional archery game of the Sirmaur, Solan and Shimla hills, played between two teams (Pashi and Saathi) in a festive spirit."],
    ["'ठोड़ा' हिमाचल प्रदेश का पारंपरिक खेल है, जिसमें क्या होता है?", ["कुश्ती", "घुड़दौड़", "पत्थर फेंकना", "तीरंदाज़ी"], "ठोड़ा सिरमौर, सोलन और शिमला की पहाड़ियों का पारंपरिक तीरंदाज़ी खेल है, जो उत्सव की भावना से दो दलों (पाशी और साठी) के बीच खेला जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The Sair festival, celebrated on the first day of the Ashvin (Asauj) month, marks:", ["The wheat sowing", "The New Year", "The end of the rainy season and the start of the harvest", "The birth of Lord Krishna"], "Sair (Saza) is a harvest festival that celebrates the end of the monsoon; offerings of new crops are made to deities."],
    ["आश्विन (असौज) मास के प्रथम दिन मनाया जाने वाला सायर उत्सव किसका सूचक है?", ["गेहूँ की बुवाई", "नववर्ष", "वर्षा ऋतु की समाप्ति और कटाई की शुरुआत", "भगवान कृष्ण का जन्म"], "सायर (सज़ा) कटाई का उत्सव है जो मानसून की समाप्ति का उत्सव मनाता है; देवताओं को नई फसल अर्पित की जाती है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Gochi festival of Lahaul is celebrated by:", ["Families that have been blessed with a baby boy in the past year", "All Buddhist monks", "Farmers after harvest", "Traders returning from Tibet"], "Gochi is a Lahauli festival in which families that had a son in the previous year give a feast and make offerings."],
    ["लाहौल का गोची उत्सव कौन मनाता है?", ["वे परिवार जिनके यहाँ पिछले वर्ष पुत्र जन्म हुआ हो", "सभी बौद्ध भिक्षु", "कटाई के बाद किसान", "तिब्बत से लौटे व्यापारी"], "गोची लाहौल का उत्सव है, जिसमें पिछले वर्ष पुत्र पाने वाले परिवार भोज देते हैं और अर्पण करते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The Shikari Devi temple of Mandi district is unusual because it:", ["Floats on a lake", "Has no roof", "Is carved inside a cave", "Is made entirely of silver"], "Shikari Devi, at about 2,850 m, is a roofless shrine; legend says snow never accumulates on the idol."],
    ["मंडी जिले का शिकारी देवी मंदिर किस कारण अनोखा है?", ["झील पर तैरता है", "इसकी छत नहीं है", "गुफा के भीतर तराशा गया है", "पूरी तरह चाँदी का बना है"], "लगभग 2,850 मी पर स्थित शिकारी देवी छतविहीन मंदिर है; मान्यता है कि मूर्ति पर बर्फ़ कभी नहीं जमती।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["At the Bijli Mahadev temple in Kullu, the Shivling is said to be struck every year by:", ["A flood", "An avalanche", "Lightning", "A landslide"], "The temple, on a hill above the Beas–Parvati confluence near Kullu, is famed for lightning striking its Shivling, which the priests then restore with butter."],
    ["कुल्लू के बिजली महादेव मंदिर में शिवलिंग पर हर वर्ष क्या गिरने की मान्यता है?", ["बाढ़", "हिमस्खलन", "आकाशीय बिजली", "भूस्खलन"], "ब्यास–पार्वती संगम के ऊपर पहाड़ी पर स्थित यह मंदिर शिवलिंग पर बिजली गिरने के लिए प्रसिद्ध है, जिसे पुजारी बाद में मक्खन से जोड़ देते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The ancient Hateshwari temple at Hatkoti stands on the bank of the river:", ["Giri", "Tons", "Sutlej", "Pabbar"], "Hatkoti, in Jubbal tehsil of Shimla district, is on the Pabbar river and is known for the Hateshwari temple of the Pratihara period."],
    ["हाटकोटी का प्राचीन हाटेश्वरी मंदिर किस नदी के तट पर है?", ["गिरि", "टोंस", "सतलुज", "पब्बर"], "शिमला जिले की जुब्बल तहसील का हाटकोटी पब्बर नदी पर है और प्रतिहार काल के हाटेश्वरी मंदिर के लिए जाना जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Bhimakali temple, built in the Kath-Kuni style with Hindu and Buddhist features, is at:", ["Sarahan", "Chitkul", "Naggar", "Chamba"], "The Bhimakali temple at Sarahan, in the Rampur Bushahr area of Shimla district, was the family deity's seat of the Bushahr rulers."],
    ["हिंदू और बौद्ध विशेषताओं वाला, काठ-कुणी शैली में बना भीमाकाली मंदिर कहाँ है?", ["सराहन", "छितकुल", "नग्गर", "चंबा"], "शिमला जिले के रामपुर बुशहर क्षेत्र में सराहन का भीमाकाली मंदिर बुशहर शासकों की कुलदेवी का स्थान था।"]),
  q(0, "hp-gk", "economy", "H", 0,
    ["Himachal Pradesh became the first state in India to achieve 100 per cent electrification of its villages in:", ["1988", "1971", "1999", "2005"], "Himachal Pradesh declared all its villages electrified in 1988, the first state in India to do so."],
    ["हिमाचल प्रदेश अपने गाँवों का 100 प्रतिशत विद्युतीकरण करने वाला भारत का पहला राज्य किस वर्ष बना?", ["1988", "1971", "1999", "2005"], "हिमाचल प्रदेश ने 1988 में अपने सभी गाँवों को विद्युतीकृत घोषित किया, ऐसा करने वाला भारत का पहला राज्य।"]),
  q(0, "hp-gk", "economy", "H", 3,
    ["The Dehar power house of the Beas–Sutlej Link Project is located in which district?", ["Mandi", "Kullu", "Una", "Bilaspur"], "The Beas–Sutlej Link diverts Beas water from Pandoh through a tunnel and channel to the Dehar power house (990 MW) at Slapper in Bilaspur."],
    ["ब्यास–सतलुज लिंक परियोजना का देहर विद्युत गृह किस जिले में है?", ["मंडी", "कुल्लू", "ऊना", "बिलासपुर"], "ब्यास–सतलुज लिंक पंडोह से ब्यास का जल सुरंग और नहर से बिलासपुर के स्लैपर स्थित देहर विद्युत गृह (990 मेगावाट) तक ले जाता है।"]),
  q(0, "hp-gk", "economy", "M", 1,
    ["The 'Prakritik Kheti Khushhal Kisan Yojana', launched by Himachal in 2018, promotes:", ["Large dams", "Zero Budget Natural Farming", "Greenhouse tourism", "Dairy cooperatives"], "The scheme encourages farmers to adopt Subhash Palekar's Zero Budget Natural Farming and reduce chemical inputs."],
    ["हिमाचल द्वारा 2018 में शुरू की गई 'प्राकृतिक खेती खुशहाल किसान योजना' किसे बढ़ावा देती है?", ["बड़े बाँध", "शून्य लागत प्राकृतिक खेती", "ग्रीनहाउस पर्यटन", "डेयरी सहकारी समितियाँ"], "यह योजना किसानों को सुभाष पालेकर की शून्य लागत प्राकृतिक खेती अपनाने और रासायनिक आदानों को घटाने के लिए प्रेरित करती है।"]),
  q(0, "hp-gk", "polity-administration", "H", 2,
    ["The Himachal Pradesh Public Service Commission (HPPSC) has its headquarters at:", ["Dharamshala", "Mandi", "Shimla", "Solan"], "The HPPSC, which recruits for state services, is headquartered at Shimla."],
    ["हिमाचल प्रदेश लोक सेवा आयोग (HPPSC) का मुख्यालय कहाँ है?", ["धर्मशाला", "मंडी", "शिमला", "सोलन"], "राज्य सेवाओं की भर्ती करने वाले HPPSC का मुख्यालय शिमला में है।"]),
  q(0, "hp-gk", "polity-administration", "H", 1,
    ["Seats reserved for women in the panchayats of Himachal Pradesh are:", ["33%", "50%", "25%", "40%"], "Himachal amended its Panchayati Raj Act in 2008 to raise the reservation for women in panchayat bodies from one-third to 50%."],
    ["हिमाचल प्रदेश की पंचायतों में महिलाओं के लिए आरक्षित सीटें हैं:", ["33%", "50%", "25%", "40%"], "हिमाचल ने 2008 में अपने पंचायती राज अधिनियम में संशोधन कर पंचायत निकायों में महिला आरक्षण एक-तिहाई से बढ़ाकर 50% किया।"]),
  q(0, "hp-gk", "personalities", "H", 3,
    ["Shyam Saran Negi of Kalpa in Kinnaur is remembered as:", ["The first Chief Minister of Himachal", "A Param Vir Chakra winner", "The founder of the Kinnaur Praja Mandal", "The first voter of independent India"], "Shyam Saran Negi, a teacher from Kalpa, cast the first vote of independent India in October 1951, when Kinnaur voted early because of snow."],
    ["किन्नौर के कल्पा के श्याम सरन नेगी को किस रूप में याद किया जाता है?", ["हिमाचल के पहले मुख्यमंत्री", "परमवीर चक्र विजेता", "किन्नौर प्रजा मंडल के संस्थापक", "स्वतंत्र भारत के पहले मतदाता"], "कल्पा के शिक्षक श्याम सरन नेगी ने अक्टूबर 1951 में स्वतंत्र भारत का पहला मत डाला, जब बर्फ़बारी के कारण किन्नौर में मतदान पहले हुआ।"]),
  q(0, "hp-gk", "personalities", "H", 2,
    ["Four Param Vir Chakra awardees belong to Himachal Pradesh. Which of the following is NOT from Himachal Pradesh?", ["Captain Vikram Batra", "Major Somnath Sharma", "Captain Manoj Kumar Pandey", "Rifleman Sanjay Kumar"], "Somnath Sharma, Dhan Singh Thapa, Vikram Batra and Sanjay Kumar are from Himachal. Manoj Kumar Pandey was from Uttar Pradesh."],
    ["हिमाचल प्रदेश के चार परमवीर चक्र विजेता हैं। निम्न में से कौन हिमाचल प्रदेश का नहीं है?", ["कैप्टन विक्रम बत्रा", "मेजर सोमनाथ शर्मा", "कैप्टन मनोज कुमार पांडेय", "राइफलमैन संजय कुमार"], "सोमनाथ शर्मा, धन सिंह थापा, विक्रम बत्रा और संजय कुमार हिमाचल के हैं। मनोज कुमार पांडेय उत्तर प्रदेश के थे।"]),

  // ───────── Section 1: General Knowledge (20) ─────────
  q(1, "general-studies", "indian-history", "M", 0,
    ["The Grand Trunk Road from Sonargaon to the Indus was rebuilt and improved by:", ["Sher Shah Suri", "Akbar", "Shah Jahan", "Alauddin Khalji"], "Sher Shah Suri rebuilt the old highway as the Sadak-e-Azam, with sarais, wells and trees along it."],
    ["सोनारगाँव से सिंधु तक की ग्रैंड ट्रंक रोड का पुनर्निर्माण और सुधार किसने कराया?", ["शेरशाह सूरी", "अकबर", "शाहजहाँ", "अलाउद्दीन खिलजी"], "शेरशाह सूरी ने पुराने राजमार्ग को सड़क-ए-आज़म के रूप में बनवाया, जिसके किनारे सराय, कुएँ और पेड़ लगे थे।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["The Cabinet Mission that came to India in 1946 was headed by:", ["Stafford Cripps", "Lord Wavell", "Pethick-Lawrence", "Clement Attlee"], "The three-member Cabinet Mission (Pethick-Lawrence, Stafford Cripps and A.V. Alexander) was led by Lord Pethick-Lawrence, the Secretary of State for India."],
    ["1946 में भारत आए कैबिनेट मिशन के अध्यक्ष कौन थे?", ["स्टैफ़ोर्ड क्रिप्स", "लॉर्ड वेवेल", "पेथिक-लॉरेंस", "क्लेमेंट एटली"], "तीन सदस्यीय कैबिनेट मिशन (पेथिक-लॉरेंस, स्टैफ़ोर्ड क्रिप्स और ए.वी. अलेक्जेंडर) का नेतृत्व भारत के राज्य सचिव लॉर्ड पेथिक-लॉरेंस ने किया।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["The famous Buddhist centre of learning at Nalanda was destroyed around 1193 by:", ["Mahmud of Ghazni", "Muhammad Ghori", "Timur", "Bakhtiyar Khilji"], "Bakhtiyar Khilji, a general of Qutb-ud-din Aibak, sacked Nalanda and other Bihar monasteries."],
    ["नालंदा का प्रसिद्ध बौद्ध शिक्षा केंद्र लगभग 1193 में किसने नष्ट किया?", ["महमूद गज़नवी", "मुहम्मद गोरी", "तैमूर", "बख्तियार खिलजी"], "कुतुबुद्दीन ऐबक के सेनापति बख्तियार खिलजी ने नालंदा और बिहार के अन्य मठों को लूटा और नष्ट किया।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["The Partition of Bengal, announced by Lord Curzon, took effect on:", ["16 July 1904", "16 October 1905", "1 January 1906", "12 December 1911"], "Bengal was partitioned on 16 October 1905, which sparked the Swadeshi and Boycott movement; the partition was annulled in 1911."],
    ["लॉर्ड कर्ज़न द्वारा घोषित बंगाल विभाजन कब प्रभावी हुआ?", ["16 जुलाई 1904", "16 अक्टूबर 1905", "1 जनवरी 1906", "12 दिसंबर 1911"], "बंगाल का विभाजन 16 अक्टूबर 1905 को हुआ, जिससे स्वदेशी और बहिष्कार आंदोलन भड़का; 1911 में यह रद्द कर दिया गया।"]),
  q(1, "general-studies", "indian-history", "H", 0,
    ["Which Mughal emperor introduced the Mansabdari system as the basis of his military and civil administration?", ["Akbar", "Humayun", "Jahangir", "Aurangzeb"], "Akbar introduced the Mansabdari system in 1570–71, ranking officers by a numerical mansab."],
    ["किस मुगल सम्राट ने अपने सैन्य और नागरिक प्रशासन के आधार के रूप में मनसबदारी प्रथा शुरू की?", ["अकबर", "हुमायूँ", "जहाँगीर", "औरंगज़ेब"], "अकबर ने 1570–71 में मनसबदारी प्रथा शुरू की, जिसमें अधिकारियों को संख्यात्मक मनसब से श्रेणीबद्ध किया जाता था।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Untouchability is abolished and its practice in any form is forbidden by:", ["Article 15", "Article 17", "Article 19", "Article 23"], "Article 17 abolishes 'untouchability' and makes its practice an offence."],
    ["अस्पृश्यता का अंत किया गया है और किसी भी रूप में उसका आचरण किस अनुच्छेद द्वारा निषिद्ध है?", ["अनुच्छेद 15", "अनुच्छेद 17", "अनुच्छेद 19", "अनुच्छेद 23"], "अनुच्छेद 17 'अस्पृश्यता' का अंत करता है और उसके आचरण को अपराध बनाता है।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["The superintendence, direction and control of elections to Parliament and State Legislatures is vested in the Election Commission under:", ["Article 280", "Article 315", "Article 148", "Article 324"], "Article 324 vests the control of elections in the Election Commission of India."],
    ["संसद और राज्य विधानमंडलों के चुनावों का अधीक्षण, निदेशन और नियंत्रण किस अनुच्छेद के अंतर्गत निर्वाचन आयोग में निहित है?", ["अनुच्छेद 280", "अनुच्छेद 315", "अनुच्छेद 148", "अनुच्छेद 324"], "अनुच्छेद 324 चुनावों का नियंत्रण भारत के निर्वाचन आयोग में निहित करता है।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["A joint sitting of both Houses of Parliament to resolve a deadlock on an ordinary bill is provided for in:", ["Article 85", "Article 100", "Article 108", "Article 123"], "Article 108 allows the President to summon a joint sitting, presided over by the Lok Sabha Speaker, if the Houses disagree on a bill."],
    ["किसी साधारण विधेयक पर गतिरोध सुलझाने के लिए संसद के दोनों सदनों की संयुक्त बैठक का प्रावधान किस अनुच्छेद में है?", ["अनुच्छेद 85", "अनुच्छेद 100", "अनुच्छेद 108", "अनुच्छेद 123"], "अनुच्छेद 108 के तहत सदनों में विधेयक पर असहमति होने पर राष्ट्रपति संयुक्त बैठक बुला सकते हैं, जिसकी अध्यक्षता लोकसभा अध्यक्ष करते हैं।"]),
  q(1, "general-studies", "indian-polity", "H", 1,
    ["The Governor's power to grant pardons, reprieves and remissions in respect of offences against state laws is under:", ["Article 72", "Article 161", "Article 213", "Article 226"], "Article 161 gives the Governor a pardoning power for state matters, though not for death sentences by courts martial."],
    ["राज्य के कानूनों के विरुद्ध अपराधों में क्षमा, प्रविलंबन और परिहार देने की राज्यपाल की शक्ति किस अनुच्छेद के अंतर्गत है?", ["अनुच्छेद 72", "अनुच्छेद 161", "अनुच्छेद 213", "अनुच्छेद 226"], "अनुच्छेद 161 राज्यपाल को राज्य के मामलों में क्षमादान की शक्ति देता है, पर सैन्य न्यायालय के मृत्युदंड के लिए नहीं।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["The Drafting Committee of the Constituent Assembly was chaired by:", ["B.R. Ambedkar", "Rajendra Prasad", "Jawaharlal Nehru", "Sardar Patel"], "Dr. B.R. Ambedkar chaired the seven-member Drafting Committee; Rajendra Prasad presided over the Assembly."],
    ["संविधान सभा की प्रारूप समिति के अध्यक्ष कौन थे?", ["बी.आर. अंबेडकर", "राजेंद्र प्रसाद", "जवाहरलाल नेहरू", "सरदार पटेल"], "डॉ. बी.आर. अंबेडकर सात सदस्यीय प्रारूप समिति के अध्यक्ष थे; संविधान सभा के अध्यक्ष राजेंद्र प्रसाद थे।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["The Narmada river, unlike most peninsular rivers, flows westwards because it:", ["Starts in the Western Ghats", "Is a seasonal river", "Joins the Tapi at its source", "Flows through a rift valley"], "The Narmada and Tapi flow in rift valleys between the Vindhya–Satpura ranges and drain into the Arabian Sea."],
    ["अधिकांश प्रायद्वीपीय नदियों के विपरीत नर्मदा पश्चिम की ओर क्यों बहती है?", ["यह पश्चिमी घाट से शुरू होती है", "यह मौसमी नदी है", "यह उद्गम पर ही ताप्ती से मिल जाती है", "यह भ्रंश घाटी में बहती है"], "नर्मदा और ताप्ती विंध्य–सतपुड़ा श्रेणियों के बीच भ्रंश घाटियों में बहकर अरब सागर में गिरती हैं।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["Guru Shikhar, the highest peak of the Aravalli range, is in:", ["Gujarat", "Haryana", "Rajasthan", "Madhya Pradesh"], "Guru Shikhar (about 1,722 m) rises near Mount Abu in Rajasthan."],
    ["अरावली श्रेणी की सबसे ऊँची चोटी गुरु शिखर कहाँ है?", ["गुजरात", "हरियाणा", "राजस्थान", "मध्य प्रदेश"], "गुरु शिखर (लगभग 1,722 मी) राजस्थान में माउंट आबू के पास है।"]),
  q(1, "general-studies", "indian-geography", "H", 1,
    ["The Jog Falls, one of India's highest waterfalls, are on the river:", ["Kaveri", "Sharavati", "Netravati", "Tungabhadra"], "The Sharavati river drops over the Jog Falls in Karnataka's Western Ghats."],
    ["भारत के सबसे ऊँचे जलप्रपातों में से एक जोग प्रपात किस नदी पर है?", ["कावेरी", "शरावती", "नेत्रावती", "तुंगभद्रा"], "शरावती नदी कर्नाटक के पश्चिमी घाट में जोग प्रपात बनाकर गिरती है।"]),
  q(1, "general-studies", "indian-economy", "H", 0,
    ["SEBI, the regulator of the securities market, was given statutory powers in:", ["1992", "1988", "1999", "2005"], "SEBI was set up in 1988 and given statutory status by the SEBI Act, 1992."],
    ["प्रतिभूति बाज़ार के नियामक SEBI को वैधानिक अधिकार किस वर्ष मिले?", ["1992", "1988", "1999", "2005"], "SEBI की स्थापना 1988 में हुई और SEBI अधिनियम, 1992 से इसे वैधानिक दर्जा मिला।"]),
  q(1, "general-studies", "indian-economy", "M", 3,
    ["The MGNREGA, enacted in 2005, guarantees at least how many days of wage employment per year to a rural household?", ["50 days", "75 days", "120 days", "100 days"], "MGNREGA guarantees 100 days of unskilled manual wage employment per year to every rural household that asks for it."],
    ["2005 में बने मनरेगा के अंतर्गत प्रत्येक ग्रामीण परिवार को वर्ष में कम से कम कितने दिन मज़दूरी रोज़गार की गारंटी है?", ["50 दिन", "75 दिन", "120 दिन", "100 दिन"], "मनरेगा हर उस ग्रामीण परिवार को वर्ष में 100 दिन के अकुशल शारीरिक मज़दूरी रोज़गार की गारंटी देता है जो इसकी माँग करे।"]),
  q(1, "general-studies", "general-science", "H", 0,
    ["The most abundant metal in the Earth's crust is:", ["Aluminium", "Iron", "Calcium", "Sodium"], "Aluminium makes up about 8% of the Earth's crust, the most abundant metal; oxygen and silicon are the most abundant elements."],
    ["पृथ्वी की पर्पटी में सबसे अधिक पाई जाने वाली धातु कौन-सी है?", ["एल्युमिनियम", "लोहा", "कैल्सियम", "सोडियम"], "एल्युमिनियम पृथ्वी की पर्पटी का लगभग 8% है और सबसे प्रचुर धातु है; ऑक्सीजन और सिलिकॉन सबसे प्रचुर तत्व हैं।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["Penicillin, the first antibiotic, was discovered by:", ["Louis Pasteur", "Robert Koch", "Edward Jenner", "Alexander Fleming"], "Alexander Fleming noticed in 1928 that the mould Penicillium killed bacteria in his culture dish."],
    ["पहली प्रतिजैविक दवा पेनिसिलिन की खोज किसने की?", ["लुई पाश्चर", "रॉबर्ट कोच", "एडवर्ड जेनर", "अलेक्जेंडर फ्लेमिंग"], "अलेक्जेंडर फ्लेमिंग ने 1928 में देखा कि पेनिसिलियम फफूँद उनकी कल्चर डिश में बैक्टीरिया को मार रही थी।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["Which acid is mainly present in lemon and other citrus fruits?", ["Acetic acid", "Tartaric acid", "Citric acid", "Lactic acid"], "Citric acid gives lemons and oranges their sour taste; acetic acid is in vinegar and lactic acid in curd."],
    ["नींबू और अन्य खट्टे फलों में मुख्य रूप से कौन-सा अम्ल पाया जाता है?", ["ऐसीटिक अम्ल", "टार्टरिक अम्ल", "साइट्रिक अम्ल", "लैक्टिक अम्ल"], "साइट्रिक अम्ल नींबू और संतरे को खट्टा स्वाद देता है; ऐसीटिक अम्ल सिरके में और लैक्टिक अम्ल दही में होता है।"]),
  q(1, "general-studies", "general-science", "H", 1,
    ["The pituitary gland is called the 'master gland' because it:", ["Is the largest gland", "Controls the activity of many other endocrine glands", "Produces digestive enzymes", "Is found in the abdomen"], "The pituitary secretes hormones that regulate the thyroid, adrenals, gonads and other endocrine glands."],
    ["पीयूष ग्रंथि को 'मास्टर ग्रंथि' क्यों कहा जाता है?", ["यह सबसे बड़ी ग्रंथि है", "यह कई अन्य अंतःस्रावी ग्रंथियों की क्रिया को नियंत्रित करती है", "यह पाचक एंज़ाइम बनाती है", "यह उदर में पाई जाती है"], "पीयूष ग्रंथि ऐसे हार्मोन स्रावित करती है जो थायरॉइड, अधिवृक्क, जनन ग्रंथियों और अन्य अंतःस्रावी ग्रंथियों का नियमन करते हैं।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["Which vitamin is produced in the human skin on exposure to sunlight?", ["Vitamin A", "Vitamin B12", "Vitamin D", "Vitamin E"], "Ultraviolet rays in sunlight convert a cholesterol derivative in the skin into vitamin D."],
    ["सूर्य के प्रकाश के संपर्क में आने पर मानव त्वचा में कौन-सा विटामिन बनता है?", ["विटामिन A", "विटामिन B12", "विटामिन D", "विटामिन E"], "सूर्य के प्रकाश की पराबैंगनी किरणें त्वचा में कोलेस्ट्रॉल के एक व्युत्पन्न को विटामिन D में बदल देती हैं।"]),

  // ───────── Section 2: Reasoning (15) ─────────
  q(2, "reasoning", "series", "M", 3,
    ["Find the next term: 2, 3, 5, 9, 17, ?", ["25", "29", "31", "33"], "The differences are 1, 2, 4, 8, so the next difference is 16: 17 + 16 = 33."],
    ["अगला पद ज्ञात कीजिए: 2, 3, 5, 9, 17, ?", ["25", "29", "31", "33"], "अंतर 1, 2, 4, 8 हैं, इसलिए अगला अंतर 16 है: 17 + 16 = 33।"], "17+16"),
  q(2, "reasoning", "series", "H", 0,
    ["Find the next term: 4, 9, 25, 49, 121, ?", ["169", "144", "196", "225"], "These are the squares of consecutive primes: 2², 3², 5², 7², 11², so the next is 13² = 169."],
    ["अगला पद ज्ञात कीजिए: 4, 9, 25, 49, 121, ?", ["169", "144", "196", "225"], "ये क्रमागत अभाज्य संख्याओं के वर्ग हैं: 2², 3², 5², 7², 11², अतः अगला 13² = 169 है।"], "13*13"),
  q(2, "reasoning", "coding-decoding", "H", 1,
    ["In a certain code, KING is written as IGLE. How is QUEEN written in that code?", ["OSCCM", "OSCCL", "OSDDL", "PTDDM"], "Each letter moves two places back: K→I, I→G, N→L, G→E. So Q→O, U→S, E→C, E→C, N→L."],
    ["किसी कूट में KING को IGLE लिखा जाता है। उसी कूट में QUEEN कैसे लिखा जाएगा?", ["OSCCM", "OSCCL", "OSDDL", "PTDDM"], "प्रत्येक अक्षर दो स्थान पीछे जाता है: K→I, I→G, N→L, G→E। अतः Q→O, U→S, E→C, E→C, N→L।"]),
  q(2, "reasoning", "coding-decoding", "M", 2,
    ["If A = 2, B = 4, C = 6 and so on (each letter is twice its alphabet position), then the value of FACE is:", ["24", "28", "30", "32"], "F = 12, A = 2, C = 6, E = 10, and 12 + 2 + 6 + 10 = 30."],
    ["यदि A = 2, B = 4, C = 6 और इसी प्रकार (प्रत्येक अक्षर का मान वर्णमाला में उसकी स्थिति का दोगुना) हो, तो FACE का मान है:", ["24", "28", "30", "32"], "F = 12, A = 2, C = 6, E = 10, और 12 + 2 + 6 + 10 = 30।"], "12+2+6+10"),
  q(2, "reasoning", "blood-relations", "M", 2,
    ["A is the father of B. B is the sister of C. C is the mother of D. How is A related to D?", ["Father", "Uncle", "Grandfather", "Brother"], "B and C are A's daughters. C is D's mother, so A is D's maternal grandfather."],
    ["A, B का पिता है। B, C की बहन है। C, D की माँ है। A का D से क्या संबंध है?", ["पिता", "चाचा/मामा", "नाना", "भाई"], "B और C, A की पुत्रियाँ हैं। C, D की माँ है, अतः A, D का नाना है।"]),
  q(2, "reasoning", "blood-relations", "H", 3,
    ["Pointing to a girl in a photograph, Amit said, 'Her mother's brother is the only son of my mother.' How is the girl related to Amit?", ["Sister", "Cousin", "Daughter", "Niece"], "The only son of Amit's mother is Amit himself. So the girl's mother's brother is Amit, which makes the girl's mother Amit's sister and the girl his niece."],
    ["फ़ोटो में एक लड़की की ओर संकेत करके अमित ने कहा, 'इसकी माँ का भाई मेरी माँ का इकलौता पुत्र है।' लड़की का अमित से क्या संबंध है?", ["बहन", "चचेरी बहन", "पुत्री", "भतीजी/भांजी"], "अमित की माँ का इकलौता पुत्र स्वयं अमित है। अतः लड़की की माँ का भाई अमित है, यानी लड़की की माँ अमित की बहन है और लड़की उसकी भांजी।"]),
  q(2, "reasoning", "syllogism", "H", 1,
    ["Statements: No flower is a tree. All trees are plants.\nConclusions: I. No flower is a plant.  II. Some plants are not flowers.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "Trees are plants, and no tree is a flower, so some plants (the trees) are not flowers (II). Flowers could still be plants in another way, so I need not hold."],
    ["कथन: कोई फूल वृक्ष नहीं है। सभी वृक्ष पौधे हैं।\nनिष्कर्ष: I. कोई फूल पौधा नहीं है।  II. कुछ पौधे फूल नहीं हैं।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न तो I और न ही II अनुसरण करता है"], "वृक्ष पौधे हैं और कोई वृक्ष फूल नहीं है, इसलिए कुछ पौधे (वृक्ष) फूल नहीं हैं (II)। फूल किसी अन्य प्रकार से पौधे हो सकते हैं, अतः I आवश्यक नहीं।"]),
  q(2, "reasoning", "direction-sense", "M", 0,
    ["A man walks 6 km south, then 8 km west and then 6 km north. How far is he from the starting point?", ["8 km", "10 km", "12 km", "14 km"], "The south and north legs cancel, leaving him 8 km west of the starting point."],
    ["एक व्यक्ति 6 किमी दक्षिण, फिर 8 किमी पश्चिम और फिर 6 किमी उत्तर चलता है। वह प्रारंभिक बिंदु से कितनी दूर है?", ["8 किमी", "10 किमी", "12 किमी", "14 किमी"], "दक्षिण और उत्तर की दूरियाँ कट जाती हैं, इसलिए वह प्रारंभिक बिंदु से 8 किमी पश्चिम में है।"]),
  q(2, "reasoning", "puzzles", "H", 2,
    ["Five friends A, B, C, D and E sit in a row facing north. A sits to the right of C but to the left of B. D sits to the right of B and to the left of E. Who sits in the middle?", ["A", "C", "B", "D"], "A is right of C and left of B, so the order is C, A, B. D is right of B and left of E, so B, D, E. The row is C A B D E, and B is in the middle."],
    ["पाँच मित्र A, B, C, D और E उत्तर की ओर मुख करके एक पंक्ति में बैठे हैं। A, C के दाईं ओर लेकिन B के बाईं ओर बैठा है। D, B के दाईं ओर और E के बाईं ओर बैठा है। बीच में कौन बैठा है?", ["A", "C", "B", "D"], "A, C के दाएँ और B के बाएँ है, अतः क्रम C, A, B है। D, B के दाएँ और E के बाएँ है, अतः B, D, E। पंक्ति C A B D E है और बीच में B है।"]),
  q(2, "reasoning", "ranking", "H", 3,
    ["In a queue, Ravi is 14th from the front and 19th from the back. How many people are in the queue?", ["31", "33", "34", "32"], "Total = 14 + 19 − 1 = 32."],
    ["एक कतार में रवि आगे से 14वाँ और पीछे से 19वाँ है। कतार में कुल कितने लोग हैं?", ["31", "33", "34", "32"], "कुल = 14 + 19 − 1 = 32।"], "14+19-1"),
  q(2, "reasoning", "clock-calendar", "M", 1,
    ["If today is Monday, what day of the week will it be after 100 days?", ["Tuesday", "Wednesday", "Thursday", "Friday"], "100 = 14 weeks + 2 days, so the day moves two ahead of Monday: Wednesday."],
    ["यदि आज सोमवार है, तो 100 दिन बाद सप्ताह का कौन-सा दिन होगा?", ["मंगलवार", "बुधवार", "गुरुवार", "शुक्रवार"], "100 = 14 सप्ताह + 2 दिन, इसलिए दिन सोमवार से दो आगे, यानी बुधवार होगा।"]),
  q(2, "reasoning", "analogy", "M", 0,
    ["Ornithology : Birds :: Entomology : ?", ["Insects", "Fossils", "Fishes", "Plants"], "Ornithology is the study of birds; entomology is the study of insects."],
    ["पक्षी-विज्ञान : पक्षी :: कीट-विज्ञान : ?", ["कीट", "जीवाश्म", "मछलियाँ", "पौधे"], "ऑर्निथोलॉजी पक्षियों का अध्ययन है; एंटोमोलॉजी कीटों का अध्ययन है।"]),
  q(2, "reasoning", "odd-one-out", "M", 3,
    ["Find the odd one out: Kangra, Una, Mandi, Dalhousie", ["Kangra", "Una", "Mandi", "Dalhousie"], "Kangra, Una and Mandi are districts of Himachal Pradesh; Dalhousie is a hill town in Chamba district."],
    ["विषम चुनिए: कांगड़ा, ऊना, मंडी, डलहौज़ी", ["कांगड़ा", "ऊना", "मंडी", "डलहौज़ी"], "कांगड़ा, ऊना और मंडी हिमाचल प्रदेश के जिले हैं; डलहौज़ी चंबा जिले का पहाड़ी नगर है।"]),
  q(2, "reasoning", "inequality", "H", 2,
    ["Statement: A ≥ B > C ≥ D\nConclusions: I. A > D  II. B > D", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "B > C ≥ D gives B > D, so II holds. A ≥ B > D gives A > D, so I holds."],
    ["कथन: A ≥ B > C ≥ D\nनिष्कर्ष: I. A > D  II. B > D", ["केवल I सत्य है", "केवल II सत्य है", "I और II दोनों सत्य हैं", "न तो I और न ही II सत्य है"], "B > C ≥ D से B > D, अतः II सत्य है। A ≥ B > D से A > D, अतः I सत्य है।"]),
  q(2, "reasoning", "math-operations", "H", 1,
    ["If 8 @ 3 = 55 and 7 @ 2 = 45, then 9 @ 4 = ?", ["63", "65", "67", "72"], "The rule is a² − b²: 64 − 9 = 55 and 49 − 4 = 45. So 9 @ 4 = 81 − 16 = 65."],
    ["यदि 8 @ 3 = 55 और 7 @ 2 = 45 है, तो 9 @ 4 = ?", ["63", "65", "67", "72"], "नियम a² − b² है: 64 − 9 = 55 और 49 − 4 = 45। अतः 9 @ 4 = 81 − 16 = 65।"], "81-16"),

  // ───────── Section 3: Mathematics (15) ─────────
  q(3, "quant", "percentage", "M", 2,
    ["If 30% of a number is 90, then 45% of the number is:", ["120", "125", "135", "150"], "The number is 90 ÷ 0.3 = 300, and 45% of 300 = 135."],
    ["यदि किसी संख्या का 30% 90 है, तो उस संख्या का 45% है:", ["120", "125", "135", "150"], "संख्या 90 ÷ 0.3 = 300 है और 300 का 45% = 135।"], "90/0.3*0.45"),
  q(3, "quant", "percentage", "H", 0,
    ["A's income is 25% more than B's. B's income is less than A's by:", ["20%", "25%", "15%", "30%"], "If B = 100, A = 125. B is less by 25 on 125, which is 20%."],
    ["A की आय B की आय से 25% अधिक है। B की आय A की आय से कितने प्रतिशत कम है?", ["20%", "25%", "15%", "30%"], "यदि B = 100, तो A = 125। B, A से 25 कम है, यानी 125 का 20%।"], "(1-1/1.25)*100"),
  q(3, "quant", "profit-loss", "H", 3,
    ["An article sold at a loss of 10% fetches ₹900. At what price should it be sold to gain 10%?", ["₹990", "₹1,000", "₹1,200", "₹1,100"], "Cost price = 900 ÷ 0.9 = ₹1,000. For a 10% gain, the selling price = ₹1,100."],
    ["10% हानि पर बेचने से एक वस्तु ₹900 में बिकती है। 10% लाभ के लिए उसे किस मूल्य पर बेचना चाहिए?", ["₹990", "₹1,000", "₹1,200", "₹1,100"], "क्रय मूल्य = 900 ÷ 0.9 = ₹1,000। 10% लाभ के लिए विक्रय मूल्य = ₹1,100।"], "900/0.9*1.1"),
  q(3, "quant", "profit-loss", "M", 1,
    ["Two successive discounts of 20% and 10% are equal to a single discount of:", ["30%", "28%", "25%", "32%"], "Net price factor = 0.8 × 0.9 = 0.72, so the single discount is 28%."],
    ["20% और 10% की दो क्रमागत छूटें किस एकल छूट के बराबर हैं?", ["30%", "28%", "25%", "32%"], "शुद्ध मूल्य गुणक = 0.8 × 0.9 = 0.72, अतः एकल छूट 28% है।"], "(1-0.8*0.9)*100"),
  q(3, "quant", "time-work", "M", 2,
    ["Pipe A can fill a tank in 20 minutes and pipe B in 30 minutes. Opened together, they will fill the tank in:", ["10 minutes", "15 minutes", "12 minutes", "25 minutes"], "Per-minute work = 1/20 + 1/30 = 1/12, so they take 12 minutes."],
    ["नल A किसी टंकी को 20 मिनट में और नल B 30 मिनट में भर सकता है। दोनों साथ खोलने पर टंकी कितने समय में भरेगी?", ["10 मिनट", "15 मिनट", "12 मिनट", "25 मिनट"], "प्रति मिनट कार्य = 1/20 + 1/30 = 1/12, अतः 12 मिनट लगेंगे।"], "1/(1/20+1/30)"),
  q(3, "quant", "interest", "H", 1,
    ["The compound interest on a sum for 2 years at 10% per annum is ₹210. The simple interest on the same sum at the same rate for the same period is:", ["₹180", "₹200", "₹205", "₹220"], "CI for 2 years at 10% is 21% of the principal, so P = 210 ÷ 0.21 = ₹1,000. SI = 1,000 × 10 × 2 ÷ 100 = ₹200."],
    ["किसी धनराशि पर 10% वार्षिक दर से 2 वर्ष का चक्रवृद्धि ब्याज ₹210 है। उसी राशि पर उसी दर और अवधि का साधारण ब्याज है:", ["₹180", "₹200", "₹205", "₹220"], "10% पर 2 वर्ष का चक्रवृद्धि ब्याज मूलधन का 21% होता है, अतः मूलधन = 210 ÷ 0.21 = ₹1,000। साधारण ब्याज = 1,000 × 10 × 2 ÷ 100 = ₹200।"], "210/0.21*0.2"),
  q(3, "quant", "average", "M", 3,
    ["The average of the first 10 natural numbers is:", ["4.5", "5", "6", "5.5"], "The sum of the first 10 natural numbers is 55, so the average is 55 ÷ 10 = 5.5."],
    ["पहली 10 प्राकृत संख्याओं का औसत है:", ["4.5", "5", "6", "5.5"], "पहली 10 प्राकृत संख्याओं का योग 55 है, अतः औसत 55 ÷ 10 = 5.5।"], "55/10"),
  q(3, "quant", "speed-distance", "M", 1,
    ["A car moves at 54 km/h. Its speed in metres per second is:", ["12 m/s", "15 m/s", "18 m/s", "20 m/s"], "54 km/h = 54 × 5/18 = 15 m/s."],
    ["एक कार 54 किमी/घंटा की चाल से चलती है। उसकी चाल मीटर प्रति सेकंड में है:", ["12 मी/से", "15 मी/से", "18 मी/से", "20 मी/से"], "54 किमी/घंटा = 54 × 5/18 = 15 मी/से।"], "54*5/18"),
  q(3, "quant", "speed-distance", "H", 0,
    ["Two trains, each 150 m long, run in opposite directions at 54 km/h and 36 km/h. They will cross each other in:", ["12 seconds", "10 seconds", "15 seconds", "8 seconds"], "Relative speed = 90 km/h = 25 m/s. Distance = 150 + 150 = 300 m, so time = 300 ÷ 25 = 12 s."],
    ["150 मी लंबी दो रेलगाड़ियाँ विपरीत दिशाओं में 54 किमी/घंटा और 36 किमी/घंटा की चाल से चलती हैं। वे एक-दूसरे को कितने समय में पार करेंगी?", ["12 सेकंड", "10 सेकंड", "15 सेकंड", "8 सेकंड"], "सापेक्ष चाल = 90 किमी/घंटा = 25 मी/से। दूरी = 150 + 150 = 300 मी, अतः समय = 300 ÷ 25 = 12 से।"], "300/((54+36)*5/18)"),
  q(3, "quant", "mensuration", "H", 2,
    ["The area of a triangle with sides 13 cm, 14 cm and 15 cm is:", ["72 cm²", "78 cm²", "84 cm²", "90 cm²"], "Semi-perimeter s = 21. Area = √(21 × 8 × 7 × 6) = √7056 = 84 cm²."],
    ["13 सेमी, 14 सेमी और 15 सेमी भुजाओं वाले त्रिभुज का क्षेत्रफल है:", ["72 सेमी²", "78 सेमी²", "84 सेमी²", "90 सेमी²"], "अर्ध-परिमाप s = 21। क्षेत्रफल = √(21 × 8 × 7 × 6) = √7056 = 84 सेमी²।"], "Math.sqrt(21*8*7*6)"),
  q(3, "quant", "mensuration", "H", 3,
    ["The perimeter of a semicircle of radius 7 cm is (take π = 22/7):", ["22 cm", "28 cm", "44 cm", "36 cm"], "Perimeter = πr + 2r = 22 + 14 = 36 cm."],
    ["7 सेमी त्रिज्या वाले अर्धवृत्त का परिमाप है (π = 22/7 लें):", ["22 सेमी", "28 सेमी", "44 सेमी", "36 सेमी"], "परिमाप = πr + 2r = 22 + 14 = 36 सेमी।"], "22/7*7+14"),
  q(3, "quant", "ratio-proportion", "H", 0,
    ["If A : B = 2 : 3 and B : C = 4 : 5, then A : B : C is:", ["8 : 12 : 15", "2 : 3 : 5", "4 : 6 : 5", "8 : 15 : 12"], "Make B equal: A : B = 8 : 12 and B : C = 12 : 15, so A : B : C = 8 : 12 : 15."],
    ["यदि A : B = 2 : 3 और B : C = 4 : 5 है, तो A : B : C है:", ["8 : 12 : 15", "2 : 3 : 5", "4 : 6 : 5", "8 : 15 : 12"], "B बराबर करने पर A : B = 8 : 12 और B : C = 12 : 15, अतः A : B : C = 8 : 12 : 15।"], "2*4"),
  q(3, "quant", "hcf-lcm", "M", 1,
    ["The HCF of 36, 48 and 60 is:", ["6", "12", "18", "24"], "36 = 2²×3², 48 = 2⁴×3, 60 = 2²×3×5. Common factors give 2² × 3 = 12."],
    ["36, 48 और 60 का म.स.प. है:", ["6", "12", "18", "24"], "36 = 2²×3², 48 = 2⁴×3, 60 = 2²×3×5। उभयनिष्ठ गुणनखंडों से 2² × 3 = 12।"], "2*2*3"),
  q(3, "quant", "number-system", "H", 3,
    ["The remainder when 2¹⁰ is divided by 7 is:", ["1", "3", "4", "2"], "2³ = 8 ≡ 1 (mod 7), so 2¹⁰ = (2³)³ × 2 ≡ 2. Check: 1024 = 7 × 146 + 2."],
    ["2¹⁰ को 7 से भाग देने पर शेषफल है:", ["1", "3", "4", "2"], "2³ = 8 ≡ 1 (mod 7), अतः 2¹⁰ = (2³)³ × 2 ≡ 2। जाँच: 1024 = 7 × 146 + 2।"], "1024%7"),
  q(3, "quant", "simplification", "M", 2,
    ["The value of √50 × √8 is:", ["10", "16", "20", "25"], "√50 × √8 = √(50 × 8) = √400 = 20."],
    ["√50 × √8 का मान है:", ["10", "16", "20", "25"], "√50 × √8 = √(50 × 8) = √400 = 20।"], "Math.sqrt(50*8)"),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "hindi", "muhavare", "M", 1,
    ["'आस्तीन का साँप' मुहावरे का अर्थ है:", ["बहुत डरपोक व्यक्ति", "कपटी मित्र जो भीतर से शत्रु हो", "बहुत विषैला जीव", "लापरवाह व्यक्ति"], "'आस्तीन का साँप' उस व्यक्ति को कहते हैं जो मित्र बनकर साथ रहे पर भीतर से हानि पहुँचाए।"],
    ["'आस्तीन का साँप' मुहावरे का अर्थ है:", ["बहुत डरपोक व्यक्ति", "कपटी मित्र जो भीतर से शत्रु हो", "बहुत विषैला जीव", "लापरवाह व्यक्ति"], "'आस्तीन का साँप' उस व्यक्ति को कहते हैं जो मित्र बनकर साथ रहे पर भीतर से हानि पहुँचाए।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["लोकोक्ति 'ऊँट के मुँह में जीरा' का अर्थ है:", ["बहुत अधिक मात्रा", "बहुत स्वादिष्ट वस्तु", "आवश्यकता से बहुत कम वस्तु", "असंभव कार्य"], "ऊँट जैसे बड़े पशु के लिए जीरा ऊँट के मुँह में नगण्य है; इसी तरह यह आवश्यकता से बहुत कम मिलने को दर्शाता है।"],
    ["लोकोक्ति 'ऊँट के मुँह में जीरा' का अर्थ है:", ["बहुत अधिक मात्रा", "बहुत स्वादिष्ट वस्तु", "आवश्यकता से बहुत कम वस्तु", "असंभव कार्य"], "ऊँट जैसे बड़े पशु के लिए जीरा ऊँट के मुँह में नगण्य है; इसी तरह यह आवश्यकता से बहुत कम मिलने को दर्शाता है।"]),
  q(4, "hindi", "vyakaran", "H", 3,
    ["'वह ज़ोर से हँसा' वाक्य में 'ज़ोर से' पद है:", ["संज्ञा", "सर्वनाम", "विशेषण", "क्रियाविशेषण"], "'ज़ोर से' यह बताता है कि हँसने की क्रिया कैसे हुई, इसलिए यह रीतिवाचक क्रियाविशेषण है।"],
    ["'वह ज़ोर से हँसा' वाक्य में 'ज़ोर से' पद है:", ["संज्ञा", "सर्वनाम", "विशेषण", "क्रियाविशेषण"], "'ज़ोर से' यह बताता है कि हँसने की क्रिया कैसे हुई, इसलिए यह रीतिवाचक क्रियाविशेषण है।"]),
  q(4, "hindi", "vyakaran", "M", 0,
    ["'कवि' शब्द का स्त्रीलिंग रूप है:", ["कवयित्री", "कवि", "कविता", "कवियानी"], "कवि का स्त्रीलिंग कवयित्री होता है।"],
    ["'कवि' शब्द का स्त्रीलिंग रूप है:", ["कवयित्री", "कवि", "कविता", "कवियानी"], "कवि का स्त्रीलिंग कवयित्री होता है।"]),
  q(4, "hindi", "shuddh-vartani", "M", 1,
    ["शुद्ध वर्तनी वाला शब्द है:", ["श्रीमति", "श्रीमती", "श्रिमती", "श्रीमत्ती"], "सही वर्तनी 'श्रीमती' है।"],
    ["शुद्ध वर्तनी वाला शब्द है:", ["श्रीमति", "श्रीमती", "श्रिमती", "श्रीमत्ती"], "सही वर्तनी 'श्रीमती' है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["निम्नलिखित में से 'आकाश' का पर्यायवाची शब्द नहीं है:", ["गगन", "नभ", "अंबर", "अवनि"], "गगन, नभ और अंबर आकाश के पर्याय हैं; अवनि का अर्थ पृथ्वी है।"],
    ["निम्नलिखित में से 'आकाश' का पर्यायवाची शब्द नहीं है:", ["गगन", "नभ", "अंबर", "अवनि"], "गगन, नभ और अंबर आकाश के पर्याय हैं; अवनि का अर्थ पृथ्वी है।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["'ग्राह्य' का विलोम शब्द है:", ["अग्राह्य", "ग्राहक", "ग्रहण", "विग्रह"], "'ग्राह्य' का अर्थ ग्रहण करने योग्य है और उसका विलोम अग्राह्य (न ग्रहण करने योग्य) है।"],
    ["'ग्राह्य' का विलोम शब्द है:", ["अग्राह्य", "ग्राहक", "ग्रहण", "विग्रह"], "'ग्राह्य' का अर्थ ग्रहण करने योग्य है और उसका विलोम अग्राह्य (न ग्रहण करने योग्य) है।"]),
  q(4, "hindi", "alankar-ras", "H", 0,
    ["'पीपर पात सरिस मन डोला' पंक्ति में कौन-सा अलंकार है?", ["उपमा", "रूपक", "यमक", "श्लेष"], "यहाँ मन के डोलने की तुलना पीपल के पत्ते से 'सरिस' (समान) वाचक शब्द द्वारा की गई है, इसलिए उपमा अलंकार है।"],
    ["'पीपर पात सरिस मन डोला' पंक्ति में कौन-सा अलंकार है?", ["उपमा", "रूपक", "यमक", "श्लेष"], "यहाँ मन के डोलने की तुलना पीपल के पत्ते से 'सरिस' (समान) वाचक शब्द द्वारा की गई है, इसलिए उपमा अलंकार है।"]),
  q(4, "english", "grammar", "M", 0,
    ["Fill in the blank: She is very good ___ music.", ["at", "in", "on", "with"], "The adjective 'good' takes the preposition 'at' when we speak of skill: good at music."],
    ["रिक्त स्थान भरिए: She is very good ___ music.", ["at", "in", "on", "with"], "कौशल की बात करते समय विशेषण 'good' के साथ preposition 'at' आता है: good at music।"]),
  q(4, "english", "grammar", "H", 2,
    ["Choose the correct option: If I ___ you, I would accept the offer.", ["am", "was", "were", "be"], "In a hypothetical (second-type) conditional, 'were' is used for all persons: If I were you."],
    ["सही विकल्प चुनिए: If I ___ you, I would accept the offer.", ["am", "was", "were", "be"], "काल्पनिक (द्वितीय प्रकार की) शर्त में सभी पुरुषों के लिए 'were' आता है: If I were you।"]),
  q(4, "english", "error-spotting", "M", 3,
    ["Choose the grammatically correct sentence.", ["He did not came to office yesterday.", "He does not came to office yesterday.", "He not came to office yesterday.", "He did not come to office yesterday."], "After 'did not' the main verb takes its base form: 'come'."],
    ["व्याकरण की दृष्टि से सही वाक्य चुनिए।", ["He did not came to office yesterday.", "He does not came to office yesterday.", "He not came to office yesterday.", "He did not come to office yesterday."], "'did not' के बाद मुख्य क्रिया अपने मूल रूप में आती है: 'come'।"]),
  q(4, "english", "voice-speech", "H", 1,
    ["Change into indirect speech: He said, 'I am happy.'", ["He said that I am happy.", "He said that he was happy.", "He said that he is happy.", "He said that he had been happy."], "In indirect speech the present tense 'am' changes to the past 'was' and 'I' becomes 'he'."],
    ["अप्रत्यक्ष कथन में बदलिए: He said, 'I am happy.'", ["He said that I am happy.", "He said that he was happy.", "He said that he is happy.", "He said that he had been happy."], "अप्रत्यक्ष कथन में वर्तमान काल 'am' भूतकाल 'was' में और 'I' 'he' में बदल जाता है।"]),
  q(4, "english", "idioms", "M", 2,
    ["The idiom 'to beat about the bush' means:", ["To hunt in a forest", "To clean the garden", "To avoid coming to the point", "To work very hard"], "To beat about the bush is to talk around a subject without saying the main thing directly."],
    ["मुहावरे 'to beat about the bush' का अर्थ है:", ["जंगल में शिकार करना", "बगीचा साफ़ करना", "मुख्य बात पर आने से बचना", "बहुत मेहनत करना"], "Beat about the bush का अर्थ मुख्य बात सीधे न कहकर इधर-उधर की बातें करना है।"]),
  q(4, "english", "vocabulary", "H", 1,
    ["The word 'VERBOSE' means:", ["Silent", "Using more words than necessary", "Clear and brief", "Speaking in a loud voice"], "A verbose speaker or writer uses more words than are needed."],
    ["शब्द 'VERBOSE' का अर्थ है:", ["मौन", "आवश्यकता से अधिक शब्दों का प्रयोग करने वाला", "स्पष्ट और संक्षिप्त", "ऊँची आवाज़ में बोलने वाला"], "Verbose वक्ता या लेखक आवश्यकता से अधिक शब्दों का प्रयोग करता है।"]),
  q(4, "english", "synonyms-antonyms", "H", 3,
    ["Choose the word closest in meaning to 'METICULOUS':", ["Careless", "Hasty", "Casual", "Careful"], "Meticulous means showing great attention to detail; careful is the closest."],
    ["'METICULOUS' का निकटतम अर्थ वाला शब्द चुनिए:", ["Careless", "Hasty", "Casual", "Careful"], "Meticulous का अर्थ बारीकियों पर बहुत ध्यान देना है; careful सबसे निकट है।"]),

  // ───────── Section 5: Revenue & Computer (5) ─────────
  q(5, "hp-gk", "revenue", "H", 0,
    ["Which land record is also known as the 'Record of Rights' showing owners, tenants and shares?", ["Jamabandi", "Girdawari", "Tatima", "Intkal"], "The Jamabandi (Record of Rights) lists the owners and cultivators of each holding with their shares and is updated periodically."],
    ["किस भू-अभिलेख को 'अधिकार अभिलेख' भी कहा जाता है, जिसमें स्वामी, काश्तकार और उनके हिस्से दर्ज होते हैं?", ["जमाबंदी", "गिरदावरी", "ततीमा", "इंतकाल"], "जमाबंदी (अधिकार अभिलेख) प्रत्येक जोत के स्वामियों और काश्तकारों को उनके हिस्सों सहित दर्ज करती है और समय-समय पर अद्यतन होती है।"]),
  q(5, "hp-gk", "revenue", "H", 2,
    ["In Himachal Pradesh, land is traditionally measured in bigha and biswa. One bigha equals how many biswas?", ["10", "16", "20", "100"], "1 bigha = 20 biswa and 1 biswa = 20 biswansi."],
    ["हिमाचल प्रदेश में भूमि पारंपरिक रूप से बीघा और बिस्वा में मापी जाती है। एक बीघा कितने बिस्वा के बराबर होता है?", ["10", "16", "20", "100"], "1 बीघा = 20 बिस्वा और 1 बिस्वा = 20 बिस्वांसी।"]),
  q(5, "hp-gk", "revenue", "M", 1,
    ["The area of the village for which one Patwari is responsible is called a:", ["Tehsil", "Patwar circle (halqa)", "Block", "Sub-division"], "A Patwari looks after the records of one Patwar circle (halqa), consisting of a few villages."],
    ["गाँवों का वह क्षेत्र जिसके लिए एक पटवारी उत्तरदायी होता है, कहलाता है:", ["तहसील", "पटवार मंडल (हलका)", "खंड", "उपमंडल"], "पटवारी कुछ गाँवों वाले एक पटवार मंडल (हलका) के अभिलेखों की देखरेख करता है।"]),
  q(5, "computer", "ms-office", "M", 3,
    ["In MS Excel, which function returns the largest value in a range of cells?", ["SUM", "AVERAGE", "COUNT", "MAX"], "MAX returns the largest number in a range; SUM adds, AVERAGE gives the mean and COUNT counts numeric cells."],
    ["MS Excel में कौन-सा फ़ंक्शन सेल की किसी श्रेणी में सबसे बड़ा मान देता है?", ["SUM", "AVERAGE", "COUNT", "MAX"], "MAX किसी श्रेणी की सबसे बड़ी संख्या देता है; SUM जोड़ता है, AVERAGE माध्य देता है और COUNT संख्यात्मक सेल गिनता है।"]),
  q(5, "computer", "dbms", "M", 2,
    ["SQL, the language used to query databases, stands for:", ["Simple Query Language", "Sequential Question List", "Structured Query Language", "Standard Quick Logic"], "SQL stands for Structured Query Language and is used to create, read, update and delete data in relational databases."],
    ["डेटाबेस से पूछताछ की भाषा SQL का पूरा रूप क्या है?", ["Simple Query Language", "Sequential Question List", "Structured Query Language", "Standard Quick Logic"], "SQL का अर्थ Structured Query Language है और इसका प्रयोग संबंधपरक डेटाबेस में डेटा बनाने, पढ़ने, बदलने और हटाने के लिए होता है।"]),
];
