// HP Patwari Full Mock 5 — 100 questions (30 HP GK, 20 GK, 15 Reasoning, 15 Maths, 15 Hindi/English, 5 Revenue/Computer).

import { q, type PatwariQuestion } from "./types";

export const mock5: PatwariQuestion[] = [
  // ───────── Section 0: Himachal GK (30) ─────────
  q(0, "hp-gk", "history", "H", 1,
    ["Raja Sahil Varman founded the town of Chamba around 920 AD and named it after his daughter:", ["Chandravati", "Champavati", "Padmavati", "Sukanya"], "Sahil Varman (Sahil Verma) shifted his capital from Brahmapura (Bharmour) to the Ravi valley and named the new town Chamba after his daughter Champavati."],
    ["राजा साहिल वर्मन ने लगभग 920 ई. में चंबा नगर बसाया और उसका नाम अपनी पुत्री के नाम पर रखा। वह पुत्री थीं:", ["चंद्रावती", "चंपावती", "पद्मावती", "सुकन्या"], "साहिल वर्मन ने राजधानी ब्रह्मपुर (भरमौर) से रावी घाटी में स्थानांतरित की और नए नगर का नाम अपनी पुत्री चंपावती के नाम पर चंबा रखा।"]),
  q(0, "hp-gk", "history", "H", 2,
    ["The Kangra fort (Nagarkot) was captured in 1809 by:", ["The Gurkhas under Amar Singh Thapa", "The Mughals under Jahangir", "Maharaja Ranjit Singh", "The British under Lord Hastings"], "After the Gurkhas were pressed back, Maharaja Ranjit Singh took the Kangra fort in 1809, ending the Gurkha siege and ending Katoch control for years."],
    ["कांगड़ा का किला (नगरकोट) 1809 में किसने जीत लिया?", ["अमर सिंह थापा के नेतृत्व में गोरखों ने", "जहाँगीर के नेतृत्व में मुगलों ने", "महाराजा रणजीत सिंह ने", "लॉर्ड हेस्टिंग्स के नेतृत्व में अंग्रेज़ों ने"], "गोरखों को पीछे हटाने के बाद महाराजा रणजीत सिंह ने 1809 में कांगड़ा किला ले लिया, जिससे गोरखा घेराबंदी समाप्त हुई और कटोच नियंत्रण कई वर्षों के लिए छिन गया।"]),
  q(0, "hp-gk", "history", "H", 0,
    ["The town of Mandi was founded in 1527 by Raja:", ["Ajbar Sen", "Bahu Sen", "Siddh Sen", "Suraj Sen"], "Raja Ajbar Sen founded the town of Mandi in 1527 on the banks of the Beas; the state is named after it."],
    ["मंडी नगर की स्थापना 1527 में किस राजा ने की?", ["अजबर सेन", "बाहु सेन", "सिद्ध सेन", "सूरज सेन"], "राजा अजबर सेन ने 1527 में ब्यास के किनारे मंडी नगर बसाया; रियासत का नाम इसी पर पड़ा।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["Raja Jagat Singh of Kullu (1637–72) is credited with bringing the idol of Lord Raghunath from:", ["Mathura", "Haridwar", "Puri", "Ayodhya"], "Raja Jagat Singh brought the Raghunath idol from Ayodhya through Damodar Das and installed it at Sultanpur, making Raghunath the presiding deity of Kullu."],
    ["कुल्लू के राजा जगत सिंह (1637–72) को भगवान रघुनाथ की मूर्ति कहाँ से लाने का श्रेय दिया जाता है?", ["मथुरा", "हरिद्वार", "पुरी", "अयोध्या"], "राजा जगत सिंह दामोदर दास के माध्यम से अयोध्या से रघुनाथ की मूर्ति लाए और उसे सुल्तानपुर में स्थापित किया, जिससे रघुनाथ कुल्लू के अधिष्ठाता देवता बने।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["The Shimla Agreement between India and Pakistan was signed in:", ["1965", "1971", "1972", "1999"], "Indira Gandhi and Zulfikar Ali Bhutto signed the Shimla Agreement on 2 July 1972 after the 1971 war."],
    ["भारत और पाकिस्तान के बीच शिमला समझौते पर हस्ताक्षर किस वर्ष हुए?", ["1965", "1971", "1972", "1999"], "1971 के युद्ध के बाद इंदिरा गांधी और ज़ुल्फ़िकार अली भुट्टो ने 2 जुलाई 1972 को शिमला समझौते पर हस्ताक्षर किए।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["Which tribe of Chamba district inhabits the remote Pangi valley and is known as the Pangwal?", ["Gaddi", "Gujjar", "Lahaula", "Pangwala"], "The people of the Pangi valley are called Pangwals (Pangwala); the Gaddis live mainly around Bharmour and the Kangra side."],
    ["चंबा जिले की दूरस्थ पांगी घाटी में कौन-सी जनजाति रहती है, जिसे पंगवाल कहा जाता है?", ["गद्दी", "गुज्जर", "लाहौला", "पंगवाला"], "पांगी घाटी के निवासी पंगवाल (पंगवाला) कहलाते हैं; गद्दी मुख्यतः भरमौर और कांगड़ा क्षेत्र में रहते हैं।"]),
  q(0, "hp-gk", "geography", "H", 0,
    ["Chandra Tal, the 'Moon Lake', lies at an altitude of about:", ["4,300 m", "3,200 m", "2,100 m", "5,400 m"], "Chandra Tal is a crescent-shaped lake in Spiti, roughly 4,270–4,300 m above sea level, and is a Ramsar site."],
    ["'चंद्रमा की झील' कहलाने वाली चंद्रताल लगभग कितनी ऊँचाई पर है?", ["4,300 मी", "3,200 मी", "2,100 मी", "5,400 मी"], "चंद्रताल स्पीति में अर्धचंद्राकार झील है, जो समुद्र तल से लगभग 4,270–4,300 मी ऊँचाई पर है और रामसर स्थल है।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["Manimahesh Lake, the venue of an annual pilgrimage in Bhadon, is in which district?", ["Kullu", "Chamba", "Kinnaur", "Mandi"], "Manimahesh Lake lies at about 4,080 m at the foot of Manimahesh Kailash in Bharmour tehsil of Chamba."],
    ["भादों में वार्षिक तीर्थयात्रा के स्थल मणिमहेश झील किस जिले में है?", ["कुल्लू", "चंबा", "किन्नौर", "मंडी"], "मणिमहेश झील चंबा की भरमौर तहसील में मणिमहेश कैलाश की तलहटी में लगभग 4,080 मी की ऊँचाई पर है।"]),
  q(0, "hp-gk", "geography", "H", 2,
    ["The Indrahar Pass crosses the Dhauladhar range and connects Kangra with:", ["Kullu", "Mandi", "Chamba", "Shimla"], "The Indrahar Pass (about 4,300 m) is a popular trek that links the McLeodganj–Dharamshala side of Kangra with the Chamba (Lahaul) side."],
    ["इंद्रहार दर्रा धौलाधार श्रेणी को पार करके कांगड़ा को किससे जोड़ता है?", ["कुल्लू", "मंडी", "चंबा", "शिमला"], "इंद्रहार दर्रा (लगभग 4,300 मी) लोकप्रिय ट्रेक है जो कांगड़ा के मैक्लोडगंज–धर्मशाला क्षेत्र को चंबा (लाहौल) की ओर से जोड़ता है।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["Which town of Himachal is the site of the Pasteur Institute, set up in 1900?", ["Dagshai", "Sabathu", "Dalhousie", "Kasauli"], "The Central Research Institute at Kasauli began as the Pasteur Institute in 1900 for producing the anti-rabies vaccine."],
    ["1900 में स्थापित पाश्चर संस्थान हिमाचल के किस नगर में है?", ["डगशाई", "सबाथू", "डलहौज़ी", "कसौली"], "कसौली का केंद्रीय अनुसंधान संस्थान 1900 में रेबीज़-रोधी टीका बनाने के लिए पाश्चर संस्थान के रूप में शुरू हुआ था।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 2,
    ["The river Ravi rises near Bara Bhangal in the:", ["Pir Panjal range of Kullu", "Zanskar range of Spiti", "Dhauladhar range", "Shivalik range"], "The Ravi rises in the Dhauladhar range near Bara Bhangal and flows through Chamba before entering Punjab."],
    ["रावी नदी बड़ा भंगाल के निकट किस श्रेणी से निकलती है?", ["कुल्लू की पीर पंजाल श्रेणी", "स्पीति की ज़ांस्कर श्रेणी", "धौलाधार श्रेणी", "शिवालिक श्रेणी"], "रावी धौलाधार श्रेणी में बड़ा भंगाल के पास से निकलती है और चंबा से बहकर पंजाब में प्रवेश करती है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 3,
    ["The Spiti river joins the Sutlej near:", ["Rampur", "Karcham", "Kalpa", "Khab"], "The Spiti river meets the Sutlej at Khab in Kinnaur district, a little below Shipki La."],
    ["स्पीति नदी सतलुज में किसके निकट मिलती है?", ["रामपुर", "करछम", "कल्पा", "खाब"], "स्पीति नदी किन्नौर जिले के खाब में सतलुज से मिलती है, जो शिपकी ला से थोड़ा नीचे है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["Rewalsar Lake, sacred to Hindus, Buddhists and Sikhs and known for its floating reed islands, is in:", ["Mandi", "Kangra", "Sirmaur", "Hamirpur"], "Rewalsar (Tso Pema) in Mandi district is linked with Guru Padmasambhava and with Guru Gobind Singh."],
    ["हिंदुओं, बौद्धों और सिखों के लिए पवित्र तथा तैरते सरकंडा द्वीपों के लिए प्रसिद्ध रिवालसर झील कहाँ है?", ["मंडी", "कांगड़ा", "सिरमौर", "हमीरपुर"], "मंडी जिले का रिवालसर (त्सो पेमा) गुरु पद्मसंभव और गुरु गोबिंद सिंह दोनों से जुड़ा है।"]),
  q(0, "hp-gk", "districts", "M", 3,
    ["The district headquarters of Kinnaur is:", ["Kalpa", "Sangla", "Nichar", "Reckong Peo"], "Reckong Peo is the district headquarters of Kinnaur, with Kalpa a short distance above it."],
    ["किन्नौर का जिला मुख्यालय कौन-सा है?", ["कल्पा", "सांगला", "निचार", "रिकांग पियो"], "रिकांग पियो किन्नौर का जिला मुख्यालय है, जिससे थोड़ा ऊपर कल्पा है।"]),
  q(0, "hp-gk", "districts", "H", 1,
    ["Which is the smallest district of Himachal Pradesh by area?", ["Una", "Hamirpur", "Bilaspur", "Solan"], "Hamirpur, about 1,118 sq km, is the smallest district by area; Lahaul and Spiti is the largest."],
    ["क्षेत्रफल की दृष्टि से हिमाचल प्रदेश का सबसे छोटा जिला कौन-सा है?", ["ऊना", "हमीरपुर", "बिलासपुर", "सोलन"], "लगभग 1,118 वर्ग किमी वाला हमीरपुर क्षेत्रफल में सबसे छोटा जिला है; लाहौल एवं स्पीति सबसे बड़ा है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The Kullvi Nati was entered in the Guinness World Records in 2016 as the:", ["Longest folk song", "Oldest folk dance", "Largest folk dance", "Largest dance on a hill"], "In December 2016 thousands of performers danced the Kullvi Nati together at Kullu, setting a Guinness record for the largest folk dance."],
    ["कुल्लवी नाटी 2016 में गिनीज़ विश्व रिकॉर्ड में किस रूप में दर्ज हुई?", ["सबसे लंबा लोकगीत", "सबसे पुराना लोकनृत्य", "सबसे बड़ा लोकनृत्य", "पहाड़ी पर सबसे बड़ा नृत्य"], "दिसंबर 2016 में कुल्लू में हज़ारों कलाकारों ने एक साथ कुल्लवी नाटी की, जिससे सबसे बड़े लोकनृत्य का गिनीज़ रिकॉर्ड बना।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Halda festival, celebrated with burning torches of cedar twigs to drive away evil spirits, belongs to:", ["Lahaul", "Kinnaur", "Pangi", "Bharmour"], "Halda is a winter festival of Lahaul in which villagers carry blazing cedar torches and gather at a bonfire."],
    ["देवदार की टहनियों की जलती मशालों से बुरी शक्तियाँ भगाने वाला हाल्डा उत्सव किस क्षेत्र का है?", ["लाहौल", "किन्नौर", "पांगी", "भरमौर"], "हाल्डा लाहौल का शीतकालीन उत्सव है, जिसमें ग्रामीण जलती देवदार मशालें लेकर अलाव के पास जुटते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The Naina Devi temple, a Shaktipeeth, is in which district?", ["Kangra", "Una", "Solan", "Bilaspur"], "Naina Devi, on a hill above Anandpur Sahib's side in Bilaspur district, is where Sati's eyes are believed to have fallen."],
    ["शक्तिपीठ नैना देवी मंदिर किस जिले में है?", ["कांगड़ा", "ऊना", "सोलन", "बिलासपुर"], "बिलासपुर जिले में पहाड़ी पर स्थित नैना देवी वह स्थान माना जाता है जहाँ सती के नेत्र गिरे थे।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The ancient Baijnath temple of Kangra, dedicated to Shiva as Vaidyanath, was built in 1204 AD by two merchant brothers named:", ["Rama and Lakshman", "Ahuka and Manyuka", "Sansar and Ghamand", "Sahil and Maru"], "The Baijnath temple (1204 AD) was built by the brothers Ahuka and Manyuka, as recorded in its inscriptions."],
    ["कांगड़ा का प्राचीन बैजनाथ मंदिर, जो शिव को वैद्यनाथ रूप में समर्पित है, 1204 ई. में किन दो व्यापारी भाइयों ने बनवाया?", ["राम और लक्ष्मण", "अहुक और मन्युक", "संसार और घमंड", "साहिल और मारू"], "शिलालेखों के अनुसार बैजनाथ मंदिर (1204 ई.) भाइयों अहुक और मन्युक ने बनवाया।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The Gurdwara Paonta Sahib in Sirmaur was established by Guru Gobind Singh, who stayed there for about:", ["One year", "Two years", "Three years", "Four years"], "Guru Gobind Singh built the gurdwara on the Yamuna bank in 1685 and stayed in Paonta for about four years."],
    ["सिरमौर का गुरुद्वारा पांवटा साहिब गुरु गोबिंद सिंह ने स्थापित किया, जहाँ वे लगभग कितने समय रहे?", ["एक वर्ष", "दो वर्ष", "तीन वर्ष", "चार वर्ष"], "गुरु गोबिंद सिंह ने 1685 में यमुना तट पर गुरुद्वारा बनवाया और पांवटा में लगभग चार वर्ष रहे।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["'Karyala' is a traditional form of:", ["Wall painting", "Folk theatre", "Wood carving", "Folk music instrument"], "Karyala is an open-air folk theatre of the Shimla, Solan and Sirmaur hills, performed at night around festivals."],
    ["'करियाला' किसकी पारंपरिक विधा है?", ["भित्ति चित्रकला", "लोक रंगमंच", "काष्ठ-कला", "लोक वाद्य"], "करियाला शिमला, सोलन और सिरमौर की पहाड़ियों का खुला लोक रंगमंच है, जो उत्सवों के दौरान रात में खेला जाता है।"]),
  q(0, "hp-gk", "economy", "H", 1,
    ["The Kol Dam hydroelectric project (800 MW), built by NTPC, is on which river?", ["Beas", "Sutlej", "Ravi", "Chenab"], "Kol Dam is on the Sutlej in Bilaspur district, built by NTPC with an installed capacity of 800 MW."],
    ["NTPC द्वारा निर्मित कोल बाँध जलविद्युत परियोजना (800 मेगावाट) किस नदी पर है?", ["ब्यास", "सतलुज", "रावी", "चिनाब"], "कोल बाँध बिलासपुर जिले में सतलुज पर है, जिसे NTPC ने 800 मेगावाट की स्थापित क्षमता के साथ बनाया है।"]),
  q(0, "hp-gk", "economy", "H", 0,
    ["The first hydroelectric project of Himachal Pradesh, the Shanan power house, is in:", ["Joginder Nagar (Mandi)", "Bhakra (Bilaspur)", "Chamba", "Manikaran (Kullu)"], "The Shanan power house at Joginder Nagar in Mandi district, commissioned in 1932 on the Uhl river, was built by Colonel Battye."],
    ["हिमाचल प्रदेश की पहली जलविद्युत परियोजना शानन विद्युत गृह कहाँ है?", ["जोगिंदर नगर (मंडी)", "भाखड़ा (बिलासपुर)", "चंबा", "मणिकर्ण (कुल्लू)"], "मंडी जिले के जोगिंदर नगर में ऊहल नदी पर 1932 में चालू शानन विद्युत गृह कर्नल बैटी ने बनवाया था।"]),
  q(0, "hp-gk", "economy", "M", 2,
    ["Which of the following is the main kharif crop of Himachal Pradesh?", ["Wheat", "Barley", "Maize", "Mustard"], "Maize is the principal kharif cereal of the state, while wheat is the principal rabi crop."],
    ["निम्नलिखित में से हिमाचल प्रदेश की मुख्य खरीफ फसल कौन-सी है?", ["गेहूँ", "जौ", "मक्का", "सरसों"], "मक्का राज्य का प्रमुख खरीफ अनाज है, जबकि गेहूँ प्रमुख रबी फसल है।"]),
  q(0, "hp-gk", "economy", "M", 3,
    ["The Himachal Road Transport Corporation (HRTC) has its headquarters at:", ["Hamirpur", "Kangra", "Mandi", "Shimla"], "HRTC was set up in 1974 and is headquartered at Shimla."],
    ["हिमाचल पथ परिवहन निगम (HRTC) का मुख्यालय कहाँ है?", ["हमीरपुर", "कांगड़ा", "मंडी", "शिमला"], "HRTC की स्थापना 1974 में हुई थी और इसका मुख्यालय शिमला में है।"]),
  q(0, "hp-gk", "polity-administration", "H", 0,
    ["The Panchayati Raj system of Himachal Pradesh has how many tiers?", ["Three: Gram Panchayat, Panchayat Samiti, Zila Parishad", "Two: Gram Panchayat and Zila Parishad", "Four, including a Block Assembly", "One: Gram Panchayat only"], "Under the HP Panchayati Raj Act, 1994, there are three tiers: Gram Panchayat at village level, Panchayat Samiti at block level and Zila Parishad at district level."],
    ["हिमाचल प्रदेश की पंचायती राज प्रणाली में कितने स्तर हैं?", ["तीन: ग्राम पंचायत, पंचायत समिति, ज़िला परिषद", "दो: ग्राम पंचायत और ज़िला परिषद", "चार, जिनमें खंड सभा भी शामिल है", "एक: केवल ग्राम पंचायत"], "हिमाचल पंचायती राज अधिनियम, 1994 के तहत तीन स्तर हैं: गाँव स्तर पर ग्राम पंचायत, खंड स्तर पर पंचायत समिति और ज़िला स्तर पर ज़िला परिषद।"]),
  q(0, "hp-gk", "polity-administration", "M", 1,
    ["How many Lok Sabha seats does Himachal Pradesh have?", ["3", "4", "5", "6"], "Himachal Pradesh sends 4 members to the Lok Sabha, from Kangra, Mandi, Hamirpur and Shimla (SC)."],
    ["हिमाचल प्रदेश की लोकसभा में कितनी सीटें हैं?", ["3", "4", "5", "6"], "हिमाचल प्रदेश से लोकसभा में 4 सदस्य जाते हैं: कांगड़ा, मंडी, हमीरपुर और शिमला (अनुसूचित जाति)।"]),
  q(0, "hp-gk", "polity-administration", "H", 3,
    ["Panchayat elections in Himachal Pradesh are conducted by the:", ["Election Commission of India", "Deputy Commissioner", "Panchayati Raj Director", "State Election Commission"], "Under Article 243K, a State Election Commission superintends and conducts panchayat elections."],
    ["हिमाचल प्रदेश में पंचायत चुनाव कौन करवाता है?", ["भारत निर्वाचन आयोग", "उपायुक्त", "पंचायती राज निदेशक", "राज्य निर्वाचन आयोग"], "अनुच्छेद 243K के अंतर्गत राज्य निर्वाचन आयोग पंचायत चुनावों का अधीक्षण और संचालन करता है।"]),
  q(0, "hp-gk", "personalities", "H", 1,
    ["Dhan Singh Thapa, who won the Param Vir Chakra in the 1962 war with China, was born in:", ["Kangra", "Shimla", "Bilaspur", "Una"], "Major Dhan Singh Thapa of 1/8 Gorkha Rifles, born in Shimla, defended the Sirijap post on the Pangong Lake and received the PVC."],
    ["1962 के चीन युद्ध में परमवीर चक्र पाने वाले धन सिंह थापा का जन्म कहाँ हुआ था?", ["कांगड़ा", "शिमला", "बिलासपुर", "ऊना"], "1/8 गोरखा राइफल्स के मेजर धन सिंह थापा, जिनका जन्म शिमला में हुआ, ने पैंगोंग झील पर सिरिजाप चौकी की रक्षा की और उन्हें परमवीर चक्र मिला।"]),
  q(0, "hp-gk", "personalities", "H", 2,
    ["The Russian painter and philosopher Nicholas Roerich made his home at which place in Himachal Pradesh?", ["Manali", "Naggar", "Dalhousie", "Kasauli"], "Nicholas Roerich settled at Naggar in the Kullu valley, where the Roerich Art Gallery and the Urusvati Himalayan Research Institute stand."],
    ["रूसी चित्रकार और दार्शनिक निकोलस रोएरिक ने हिमाचल प्रदेश में किस स्थान को अपना घर बनाया?", ["मनाली", "नग्गर", "डलहौज़ी", "कसौली"], "निकोलस रोएरिक कुल्लू घाटी के नग्गर में बस गए, जहाँ रोएरिक आर्ट गैलरी और उरुस्वती हिमालयन अनुसंधान संस्थान हैं।"]),

  // ───────── Section 1: General Knowledge (20) ─────────
  q(1, "general-studies", "indian-history", "H", 1,
    ["In the Battle of Buxar (1764), the East India Company defeated the combined forces of Mir Qasim, Shuja-ud-Daula and:", ["Hyder Ali", "Shah Alam II", "Siraj-ud-Daulah", "Tipu Sultan"], "The Company's army under Hector Munro defeated the allied forces of Mir Qasim, the Nawab of Awadh and the Mughal emperor Shah Alam II."],
    ["बक्सर के युद्ध (1764) में ईस्ट इंडिया कंपनी ने मीर कासिम, शुजाउद्दौला और किसकी संयुक्त सेनाओं को हराया?", ["हैदर अली", "शाह आलम द्वितीय", "सिराजुद्दौला", "टीपू सुल्तान"], "हेक्टर मुनरो के नेतृत्व में कंपनी की सेना ने मीर कासिम, अवध के नवाब और मुगल बादशाह शाह आलम द्वितीय की संयुक्त सेनाओं को हराया।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["The Simon Commission, boycotted in India because it had no Indian member, arrived in:", ["1919", "1925", "1928", "1931"], "The all-white Simon Commission reached India in 1928 and was met with 'Simon Go Back' protests."],
    ["साइमन कमीशन, जिसमें कोई भारतीय सदस्य नहीं था और इसलिए भारत में उसका बहिष्कार हुआ, किस वर्ष भारत आया?", ["1919", "1925", "1928", "1931"], "सभी श्वेत सदस्यों वाला साइमन कमीशन 1928 में भारत पहुँचा और 'साइमन गो बैक' के नारों के साथ उसका विरोध हुआ।"]),
  q(1, "general-studies", "indian-history", "H", 0,
    ["The Harappan site of Lothal in Gujarat is famous for its:", ["Dockyard", "Great Bath", "Granary", "Citadel with a stadium"], "Lothal has the world's earliest known artificial dockyard, linked to Harappan sea trade."],
    ["गुजरात का हड़प्पा स्थल लोथल किसके लिए प्रसिद्ध है?", ["गोदी (डॉकयार्ड)", "विशाल स्नानागार", "अन्नागार", "स्टेडियम वाला दुर्ग"], "लोथल में विश्व का सबसे पुराना ज्ञात कृत्रिम गोदी है, जो हड़प्पा के समुद्री व्यापार से जुड़ा था।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["The Rigveda is divided into how many Mandalas (books)?", ["4", "8", "12", "10"], "The Rigveda has 10 Mandalas containing 1,028 hymns; Mandalas 2 to 7 are the 'family books'."],
    ["ऋग्वेद कितने मंडलों (पुस्तकों) में विभाजित है?", ["4", "8", "12", "10"], "ऋग्वेद में 10 मंडल हैं जिनमें 1,028 सूक्त हैं; मंडल 2 से 7 'वंश मंडल' कहलाते हैं।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["The Quit India Movement was launched on:", ["8 August 1942", "9 August 1942", "26 January 1942", "15 August 1942"], "The AICC passed the Quit India resolution on 8 August 1942 at Gowalia Tank, Bombay; leaders were arrested the next day."],
    ["भारत छोड़ो आंदोलन कब शुरू किया गया?", ["8 अगस्त 1942", "9 अगस्त 1942", "26 जनवरी 1942", "15 अगस्त 1942"], "अखिल भारतीय कांग्रेस समिति ने 8 अगस्त 1942 को बंबई के गोवालिया टैंक में भारत छोड़ो प्रस्ताव पारित किया; अगले दिन नेता गिरफ़्तार हुए।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["The Right to Education (age 6–14) became a Fundamental Right under Article 21A through the:", ["42nd Amendment", "86th Amendment", "73rd Amendment", "91st Amendment"], "The 86th Amendment Act, 2002 inserted Article 21A, making free and compulsory education a Fundamental Right for children aged 6 to 14."],
    ["शिक्षा का अधिकार (6–14 वर्ष) किस संशोधन द्वारा अनुच्छेद 21क के अंतर्गत मौलिक अधिकार बना?", ["42वाँ संशोधन", "86वाँ संशोधन", "73वाँ संशोधन", "91वाँ संशोधन"], "86वें संशोधन अधिनियम, 2002 ने अनुच्छेद 21क जोड़ा, जिससे 6 से 14 वर्ष के बच्चों के लिए निःशुल्क और अनिवार्य शिक्षा मौलिक अधिकार बनी।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["The Anti-Defection Law is contained in which Schedule of the Constitution?", ["Eighth", "Ninth", "Tenth", "Eleventh"], "The Tenth Schedule, added by the 52nd Amendment in 1985, deals with disqualification on grounds of defection."],
    ["दल-बदल विरोधी कानून संविधान की किस अनुसूची में है?", ["आठवीं", "नौवीं", "दसवीं", "ग्यारहवीं"], "1985 में 52वें संशोधन द्वारा जोड़ी गई दसवीं अनुसूची दल-बदल के आधार पर अयोग्यता से संबंधित है।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["The Comptroller and Auditor General of India is provided for in which Article?", ["Article 76", "Article 124", "Article 280", "Article 148"], "Article 148 provides for the CAG, appointed by the President and removable like a Supreme Court judge."],
    ["भारत के नियंत्रक एवं महालेखा परीक्षक का प्रावधान किस अनुच्छेद में है?", ["अनुच्छेद 76", "अनुच्छेद 124", "अनुच्छेद 280", "अनुच्छेद 148"], "अनुच्छेद 148 CAG का प्रावधान करता है, जिसकी नियुक्ति राष्ट्रपति करते हैं और जिसे सर्वोच्च न्यायालय के न्यायाधीश की तरह हटाया जा सकता है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["Under Article 356, the President can impose President's Rule in a state on the failure of:", ["The constitutional machinery", "The monsoon", "The Finance Commission", "The Public Service Commission"], "Article 356 allows President's Rule when the Governor reports that the state government cannot be carried on according to the Constitution."],
    ["अनुच्छेद 356 के अंतर्गत राष्ट्रपति किसके विफल होने पर राज्य में राष्ट्रपति शासन लगा सकते हैं?", ["संवैधानिक तंत्र", "मानसून", "वित्त आयोग", "लोक सेवा आयोग"], "जब राज्यपाल रिपोर्ट दें कि राज्य सरकार संविधान के अनुसार नहीं चल सकती, तब अनुच्छेद 356 राष्ट्रपति शासन की अनुमति देता है।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["The Vice-President of India is the ex-officio Chairman of the:", ["Lok Sabha", "Planning Commission", "Rajya Sabha", "Election Commission"], "Under Article 89 the Vice-President is the ex-officio Chairman of the Rajya Sabha."],
    ["भारत का उपराष्ट्रपति पदेन किसका सभापति होता है?", ["लोकसभा", "योजना आयोग", "राज्यसभा", "निर्वाचन आयोग"], "अनुच्छेद 89 के अनुसार उपराष्ट्रपति पदेन राज्यसभा का सभापति होता है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Anamudi, the highest peak of the Western Ghats and of peninsular India, is in:", ["Karnataka", "Kerala", "Tamil Nadu", "Maharashtra"], "Anamudi (about 2,695 m) stands in the Anamalai range in Kerala."],
    ["पश्चिमी घाट और प्रायद्वीपीय भारत की सबसे ऊँची चोटी अनामुडी कहाँ है?", ["कर्नाटक", "केरल", "तमिलनाडु", "महाराष्ट्र"], "अनामुडी (लगभग 2,695 मी) केरल में अनामलाई श्रेणी में है।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["Which strait separates India from Sri Lanka?", ["Malacca Strait", "Bass Strait", "Hormuz Strait", "Palk Strait"], "The Palk Strait lies between Tamil Nadu and Sri Lanka and connects the Bay of Bengal with the Palk Bay."],
    ["कौन-सी जलसंधि भारत को श्रीलंका से अलग करती है?", ["मलक्का जलसंधि", "बास जलसंधि", "होर्मुज़ जलसंधि", "पाक जलसंधि"], "पाक जलसंधि तमिलनाडु और श्रीलंका के बीच है और बंगाल की खाड़ी को पाक खाड़ी से जोड़ती है।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["The highest mountain peak in India is:", ["Kangchenjunga", "Nanda Devi", "K2", "Kamet"], "Kangchenjunga (8,586 m) is India's highest peak; K2 is higher but lies in Pakistan-administered territory."],
    ["भारत की सबसे ऊँची पर्वत चोटी कौन-सी है?", ["कंचनजंघा", "नंदा देवी", "K2", "कामेत"], "कंचनजंघा (8,586 मी) भारत की सबसे ऊँची चोटी है; K2 अधिक ऊँची है पर पाकिस्तान-प्रशासित क्षेत्र में है।"]),
  q(1, "general-studies", "indian-economy", "M", 2,
    ["NITI Aayog replaced the Planning Commission on:", ["1 April 2012", "26 January 2014", "1 January 2015", "15 August 2016"], "NITI Aayog was set up by a Cabinet resolution on 1 January 2015, replacing the Planning Commission."],
    ["NITI आयोग ने योजना आयोग का स्थान कब लिया?", ["1 अप्रैल 2012", "26 जनवरी 2014", "1 जनवरी 2015", "15 अगस्त 2016"], "NITI आयोग की स्थापना 1 जनवरी 2015 को मंत्रिमंडल के प्रस्ताव से हुई, जिसने योजना आयोग का स्थान लिया।"]),
  q(1, "general-studies", "indian-economy", "H", 1,
    ["Fiscal deficit of the government is equal to:", ["Total revenue minus total expenditure", "Total expenditure minus total receipts excluding borrowings", "Revenue expenditure minus revenue receipts", "Imports minus exports"], "Fiscal deficit = total expenditure − (revenue receipts + non-debt capital receipts), that is, the amount the government must borrow."],
    ["सरकार का राजकोषीय घाटा किसके बराबर होता है?", ["कुल राजस्व घटा कुल व्यय", "कुल व्यय घटा उधार को छोड़कर कुल प्राप्तियाँ", "राजस्व व्यय घटा राजस्व प्राप्तियाँ", "आयात घटा निर्यात"], "राजकोषीय घाटा = कुल व्यय − (राजस्व प्राप्तियाँ + गैर-ऋण पूँजीगत प्राप्तियाँ), यानी वह राशि जो सरकार को उधार लेनी पड़ती है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["Chlorophyll, the green pigment of plants, contains which metal at its centre?", ["Iron", "Copper", "Calcium", "Magnesium"], "A magnesium atom sits at the centre of the chlorophyll molecule; haemoglobin has iron."],
    ["पौधों के हरे वर्णक क्लोरोफिल के केंद्र में कौन-सी धातु होती है?", ["लोहा", "तांबा", "कैल्सियम", "मैग्नीशियम"], "क्लोरोफिल अणु के केंद्र में मैग्नीशियम परमाणु होता है; हीमोग्लोबिन में लोहा होता है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["Insulin, the hormone that controls blood sugar, is secreted by the:", ["Liver", "Thyroid", "Pancreas", "Adrenal gland"], "Beta cells of the islets of Langerhans in the pancreas secrete insulin; its lack causes diabetes mellitus."],
    ["रक्त शर्करा को नियंत्रित करने वाला हार्मोन इंसुलिन किसके द्वारा स्रावित होता है?", ["यकृत", "थायरॉइड", "अग्न्याशय", "अधिवृक्क ग्रंथि"], "अग्न्याशय की लैंगरहैंस द्वीपिकाओं की बीटा कोशिकाएँ इंसुलिन स्रावित करती हैं; इसकी कमी से मधुमेह होता है।"]),
  q(1, "general-studies", "general-science", "H", 0,
    ["How many bones are there in the adult human body?", ["206", "212", "300", "250"], "An adult human skeleton has 206 bones, while a newborn has about 300 that fuse over time."],
    ["वयस्क मानव शरीर में कितनी हड्डियाँ होती हैं?", ["206", "212", "300", "250"], "वयस्क मानव कंकाल में 206 हड्डियाँ होती हैं, जबकि नवजात में लगभग 300 होती हैं जो समय के साथ जुड़ जाती हैं।"]),
  q(1, "general-studies", "general-science", "H", 1,
    ["Rickets in children is caused by the deficiency of:", ["Vitamin C", "Vitamin D", "Vitamin A", "Vitamin K"], "Lack of vitamin D (or calcium) prevents proper bone mineralisation, causing soft, bent bones known as rickets."],
    ["बच्चों में रिकेट्स किसकी कमी से होता है?", ["विटामिन C", "विटामिन D", "विटामिन A", "विटामिन K"], "विटामिन D (या कैल्सियम) की कमी से हड्डियों का खनिजीकरण ठीक से नहीं होता, जिससे मुलायम, मुड़ी हड्डियाँ बनती हैं जिसे रिकेट्स कहते हैं।"]),
  q(1, "general-studies", "general-science", "H", 0,
    ["A concave mirror is used as a reflector in vehicle headlights because it:", ["Produces a parallel beam when the bulb is at its focus", "Always forms a virtual image", "Reduces the brightness of the bulb", "Spreads the light in all directions"], "A source at the focus of a concave mirror sends out parallel rays after reflection, giving a strong straight beam."],
    ["वाहनों की हेडलाइट में परावर्तक के रूप में अवतल दर्पण का उपयोग इसलिए होता है क्योंकि वह:", ["बल्ब के फ़ोकस पर होने पर समानांतर किरण-पुंज देता है", "सदैव आभासी प्रतिबिंब बनाता है", "बल्ब की चमक घटाता है", "प्रकाश को सभी दिशाओं में फैलाता है"], "अवतल दर्पण के फ़ोकस पर रखा स्रोत परावर्तन के बाद समानांतर किरणें भेजता है, जिससे तेज़ सीधा प्रकाश-पुंज मिलता है।"]),

  // ───────── Section 2: Reasoning (15) ─────────
  q(2, "reasoning", "series", "M", 3,
    ["Find the next term: 5, 11, 23, 47, 95, ?", ["189", "190", "195", "191"], "Each term is double the previous plus 1: 95 × 2 + 1 = 191."],
    ["अगला पद ज्ञात कीजिए: 5, 11, 23, 47, 95, ?", ["189", "190", "195", "191"], "प्रत्येक पद पिछले पद का दोगुना जमा 1 है: 95 × 2 + 1 = 191।"], "95*2+1"),
  q(2, "reasoning", "series", "H", 2,
    ["Find the next term: 1, 2, 6, 24, 120, ?", ["240", "600", "720", "840"], "The terms are factorials: 1!, 2!, 3!, 4!, 5!, so the next is 6! = 720."],
    ["अगला पद ज्ञात कीजिए: 1, 2, 6, 24, 120, ?", ["240", "600", "720", "840"], "पद क्रमगुणित हैं: 1!, 2!, 3!, 4!, 5!, अतः अगला 6! = 720 है।"], "6*5*4*3*2*1"),
  q(2, "reasoning", "coding-decoding", "H", 0,
    ["In a certain code, BOOK is written as ELLN. How is PAGE written in that code?", ["SXDH", "SZDH", "SXDG", "SXEH"], "The letters alternately move +3 and −3: B→E (+3), O→L (−3), O→L (−3), K→N (+3). So P→S (+3), A→X (−3), G→D (−3), E→H (+3)."],
    ["किसी कूट में BOOK को ELLN लिखा जाता है। उसी कूट में PAGE कैसे लिखा जाएगा?", ["SXDH", "SZDH", "SXDG", "SXEH"], "अक्षर क्रमशः +3 और −3 खिसकते हैं: B→E (+3), O→L (−3), O→L (−3), K→N (+3)। अतः P→S (+3), A→X (−3), G→D (−3), E→H (+3)।"]),
  q(2, "reasoning", "coding-decoding", "M", 1,
    ["If in a code language 'MANGO' is written as 'NBOHP', then 'APPLE' will be written as:", ["BQQMG", "BQQMF", "BPQMF", "CQQMF"], "Every letter moves one step forward: A→B, P→Q, P→Q, L→M, E→F."],
    ["यदि किसी कूट भाषा में 'MANGO' को 'NBOHP' लिखा जाता है, तो 'APPLE' कैसे लिखा जाएगा?", ["BQQMG", "BQQMF", "BPQMF", "CQQMF"], "प्रत्येक अक्षर एक स्थान आगे बढ़ता है: A→B, P→Q, P→Q, L→M, E→F।"]),
  q(2, "reasoning", "blood-relations", "H", 3,
    ["Showing a photograph, Ravi says, 'She is the daughter of my grandfather's only son.' How is the girl in the photograph related to Ravi?", ["Cousin", "Aunt", "Mother", "Sister"], "The grandfather's only son is Ravi's father, so his daughter is Ravi's sister."],
    ["एक फ़ोटो दिखाते हुए रवि कहता है, 'यह मेरे दादा के इकलौते पुत्र की पुत्री है।' फ़ोटो वाली लड़की का रवि से क्या संबंध है?", ["चचेरी बहन", "बुआ", "माँ", "बहन"], "दादा का इकलौता पुत्र रवि का पिता है, अतः उसकी पुत्री रवि की बहन है।"]),
  q(2, "reasoning", "blood-relations", "M", 2,
    ["X is the father of Y, and Y is the father of Z. Z has a sister W. How is W related to X?", ["Daughter", "Sister", "Granddaughter", "Niece"], "Z's sister W is also Y's daughter, and Y is X's son, so W is X's granddaughter."],
    ["X, Y का पिता है और Y, Z का पिता है। Z की एक बहन W है। W का X से क्या संबंध है?", ["बेटी", "बहन", "पोती", "भतीजी"], "Z की बहन W भी Y की पुत्री है, और Y, X का पुत्र है, अतः W, X की पोती है।"]),
  q(2, "reasoning", "syllogism", "H", 0,
    ["Statements: Some doctors are teachers. All teachers are singers.\nConclusions: I. Some doctors are singers.  II. All singers are teachers.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "The doctors who are teachers are also singers, so I follows. Singers may include people who are not teachers, so II does not follow."],
    ["कथन: कुछ डॉक्टर शिक्षक हैं। सभी शिक्षक गायक हैं।\nनिष्कर्ष: I. कुछ डॉक्टर गायक हैं।  II. सभी गायक शिक्षक हैं।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न तो I और न ही II अनुसरण करता है"], "जो डॉक्टर शिक्षक हैं वे गायक भी हैं, अतः I अनुसरण करता है। गायकों में ऐसे लोग हो सकते हैं जो शिक्षक नहीं हैं, अतः II अनुसरण नहीं करता।"]),
  q(2, "reasoning", "direction-sense", "H", 0,
    ["Rahul faces north. He turns 90° clockwise, then 135° anticlockwise, and finally 45° clockwise. Which direction is he facing now?", ["North", "North-east", "North-west", "East"], "North → East (90° clockwise) → 135° anticlockwise from East points to North-west → 45° clockwise from North-west is North."],
    ["राहुल का मुख उत्तर की ओर है। वह 90° दक्षिणावर्त घूमता है, फिर 135° वामावर्त, और अंत में 45° दक्षिणावर्त घूमता है। अब उसका मुख किस दिशा में है?", ["उत्तर", "उत्तर-पूर्व", "उत्तर-पश्चिम", "पूर्व"], "उत्तर → पूर्व (90° दक्षिणावर्त) → पूर्व से 135° वामावर्त घूमने पर उत्तर-पश्चिम → उत्तर-पश्चिम से 45° दक्षिणावर्त घूमने पर उत्तर।"]),
  q(2, "reasoning", "ranking", "H", 3,
    ["Neha ranks 7th from the top and 28th from the bottom in a class. How many students are there in the class?", ["33", "35", "36", "34"], "Total = 7 + 28 − 1 = 34."],
    ["एक कक्षा में नेहा ऊपर से 7वें और नीचे से 28वें स्थान पर है। कक्षा में कितने विद्यार्थी हैं?", ["33", "35", "36", "34"], "कुल = 7 + 28 − 1 = 34।"], "7+28-1"),
  q(2, "reasoning", "clock-calendar", "H", 1,
    ["How many times do the hands of a clock coincide in a day (24 hours)?", ["24", "22", "21", "23"], "The hands coincide 11 times in every 12 hours, so 22 times in 24 hours."],
    ["एक दिन (24 घंटे) में घड़ी की दोनों सुइयाँ कितनी बार एक-दूसरे पर आती हैं?", ["24", "22", "21", "23"], "हर 12 घंटे में सुइयाँ 11 बार एक-दूसरे पर आती हैं, अतः 24 घंटे में 22 बार।"]),
  q(2, "reasoning", "clock-calendar", "H", 3,
    ["The calendar of the year 2015 will be exactly the same as the calendar of the year:", ["2020", "2021", "2025", "2026"], "From 2015 to 2026 there are 11 years including 3 leap years (2016, 2020, 2024), giving 14 odd days, which is 0 modulo 7, and 2026 itself is not a leap year."],
    ["वर्ष 2015 का कैलेंडर किस वर्ष के कैलेंडर के बिल्कुल समान होगा?", ["2020", "2021", "2025", "2026"], "2015 से 2026 तक 11 वर्ष हैं जिनमें 3 अधिवर्ष (2016, 2020, 2024) आते हैं, इससे 14 अतिरिक्त दिन होते हैं जो 7 से पूर्णतः विभाज्य हैं, और 2026 स्वयं अधिवर्ष नहीं है।"]),
  q(2, "reasoning", "analogy", "M", 2,
    ["Tributary : River :: Branch : ?", ["Leaf", "Root", "Tree", "Fruit"], "A tributary flows into a river as a branch grows from a tree."],
    ["सहायक नदी : नदी :: शाखा : ?", ["पत्ती", "जड़", "वृक्ष", "फल"], "जैसे सहायक नदी किसी नदी में मिलती है, वैसे ही शाखा वृक्ष से निकलती है।"]),
  q(2, "reasoning", "odd-one-out", "H", 3,
    ["Find the odd one out: ACE, BDF, CEG, DFI, EGI", ["ACE", "BDF", "EGI", "DFI"], "Each group has letters two places apart: ACE, BDF, CEG, DFH, EGI. DFI breaks the pattern."],
    ["विषम पद ज्ञात कीजिए: ACE, BDF, CEG, DFI, EGI", ["ACE", "BDF", "EGI", "DFI"], "प्रत्येक समूह में अक्षर दो स्थान के अंतर पर हैं: ACE, BDF, CEG, DFH, EGI। DFI इस क्रम को तोड़ता है।"]),
  q(2, "reasoning", "dice-cube", "H", 1,
    ["A cube painted red on all faces is cut into 64 equal small cubes. How many small cubes have exactly one face painted?", ["16", "24", "32", "8"], "For n = 4 the cubes with exactly one painted face are 6 × (n − 2)² = 6 × 4 = 24."],
    ["सभी फलकों पर लाल रंग से रंगे एक घन को 64 समान छोटे घनों में काटा जाता है। कितने छोटे घनों का ठीक एक फलक रंगीन होगा?", ["16", "24", "32", "8"], "n = 4 के लिए ठीक एक रंगीन फलक वाले घन 6 × (n − 2)² = 6 × 4 = 24 होते हैं।"], "6*(4-2)**2"),
  q(2, "reasoning", "math-operations", "H", 2,
    ["If + means −, − means ×, × means ÷ and ÷ means +, then 12 + 8 − 3 × 6 ÷ 2 = ?", ["6", "8", "10", "12"], "Replace the signs: 12 − 8 × 3 ÷ 6 + 2. Then 8 × 3 ÷ 6 = 4, so 12 − 4 + 2 = 10."],
    ["यदि + का अर्थ −, − का अर्थ ×, × का अर्थ ÷ और ÷ का अर्थ + हो, तो 12 + 8 − 3 × 6 ÷ 2 = ?", ["6", "8", "10", "12"], "चिह्न बदलने पर: 12 − 8 × 3 ÷ 6 + 2। तब 8 × 3 ÷ 6 = 4, अतः 12 − 4 + 2 = 10।"], "12-8*3/6+2"),

  // ───────── Section 3: Mathematics (15) ─────────
  q(3, "quant", "percentage", "H", 2,
    ["In an election between two candidates, the winner gets 55% of the total votes and wins by 2,000 votes. The total number of votes is:", ["10,000", "15,000", "20,000", "25,000"], "The winner leads by 55% − 45% = 10% of the votes, so 10% of the total = 2,000 and the total = 20,000."],
    ["दो उम्मीदवारों के बीच चुनाव में विजेता को कुल मतों के 55% मिलते हैं और वह 2,000 मतों से जीतता है। कुल मतों की संख्या है:", ["10,000", "15,000", "20,000", "25,000"], "विजेता 55% − 45% = 10% मतों से आगे है, अतः कुल का 10% = 2,000 और कुल = 20,000।"], "2000/0.1"),
  q(3, "quant", "percentage", "M", 0,
    ["A salary is first raised by 20% and then by 10%. The overall increase is:", ["32%", "30%", "31%", "34%"], "1.2 × 1.1 = 1.32 times the original, a 32% increase."],
    ["किसी वेतन में पहले 20% और फिर 10% की वृद्धि की जाती है। कुल वृद्धि है:", ["32%", "30%", "31%", "34%"], "1.2 × 1.1 = 1.32, यानी मूल वेतन का 1.32 गुना, अतः 32% की वृद्धि।"], "(1.2*1.1-1)*100"),
  q(3, "quant", "profit-loss", "H", 3,
    ["If the cost price of 40 articles equals the selling price of 25 articles, the gain percent is:", ["40%", "50%", "55%", "60%"], "Let each article cost ₹1, so the cost of 25 articles is ₹25 and the selling price of 25 articles is ₹40. Gain = 15 on 25 = 60%."],
    ["यदि 40 वस्तुओं का क्रय मूल्य 25 वस्तुओं के विक्रय मूल्य के बराबर हो, तो लाभ प्रतिशत है:", ["40%", "50%", "55%", "60%"], "मान लें प्रत्येक वस्तु का क्रय मूल्य ₹1 है, तो 25 वस्तुओं का क्रय मूल्य ₹25 और विक्रय मूल्य ₹40 है। लाभ = 25 पर 15 = 60%।"], "(40/25-1)*100"),
  q(3, "quant", "profit-loss", "H", 1,
    ["A shopkeeper marks his goods 25% above cost and allows a discount of 12%. His profit percent is:", ["8%", "10%", "12%", "15%"], "Selling price = 1.25 × 0.88 = 1.10 of the cost, so profit = 10%."],
    ["एक दुकानदार वस्तुओं का मूल्य क्रय मूल्य से 25% अधिक अंकित करता है और 12% छूट देता है। उसका लाभ प्रतिशत है:", ["8%", "10%", "12%", "15%"], "विक्रय मूल्य = 1.25 × 0.88 = क्रय मूल्य का 1.10 गुना, अतः लाभ = 10%।"], "(1.25*0.88-1)*100"),
  q(3, "quant", "time-work", "M", 2,
    ["12 men can complete a work in 15 days. In how many days will 20 men complete the same work?", ["6", "8", "9", "10"], "Total work = 12 × 15 = 180 man-days. With 20 men: 180 ÷ 20 = 9 days."],
    ["12 आदमी एक काम 15 दिन में पूरा कर सकते हैं। 20 आदमी वही काम कितने दिन में पूरा करेंगे?", ["6", "8", "9", "10"], "कुल कार्य = 12 × 15 = 180 आदमी-दिन। 20 आदमियों के साथ: 180 ÷ 20 = 9 दिन।"], "12*15/20"),
  q(3, "quant", "interest", "H", 1,
    ["At simple interest, a sum of money doubles itself in 8 years. The rate of interest per annum is:", ["10%", "12.5%", "8%", "15%"], "Interest equals the principal in 8 years, so rate = 100 ÷ 8 = 12.5% per annum."],
    ["साधारण ब्याज पर कोई धनराशि 8 वर्ष में दोगुनी हो जाती है। वार्षिक ब्याज दर है:", ["10%", "12.5%", "8%", "15%"], "8 वर्ष में ब्याज मूलधन के बराबर होता है, अतः दर = 100 ÷ 8 = 12.5% वार्षिक।"], "100/8"),
  q(3, "quant", "speed-distance", "M", 0,
    ["A boat's speed in still water is 12 km/h and the stream flows at 3 km/h. The time taken to go 45 km downstream is:", ["3 hours", "4 hours", "5 hours", "3.75 hours"], "Downstream speed = 12 + 3 = 15 km/h, so time = 45 ÷ 15 = 3 hours."],
    ["शांत जल में नाव की चाल 12 किमी/घंटा है और धारा 3 किमी/घंटा की चाल से बहती है। धारा के अनुकूल 45 किमी जाने में कितना समय लगेगा?", ["3 घंटे", "4 घंटे", "5 घंटे", "3.75 घंटे"], "धारा के अनुकूल चाल = 12 + 3 = 15 किमी/घंटा, अतः समय = 45 ÷ 15 = 3 घंटे।"], "45/(12+3)"),
  q(3, "quant", "speed-distance", "H", 3,
    ["A man covers a certain distance at 40 km/h and returns the same distance at 60 km/h. His average speed for the whole journey is:", ["50 km/h", "52 km/h", "45 km/h", "48 km/h"], "Average speed for equal distances = 2xy/(x + y) = 2 × 40 × 60 ÷ 100 = 48 km/h."],
    ["एक व्यक्ति कोई दूरी 40 किमी/घंटा से तय करता है और उतनी ही दूरी 60 किमी/घंटा से लौटता है। पूरी यात्रा की औसत चाल है:", ["50 किमी/घंटा", "52 किमी/घंटा", "45 किमी/घंटा", "48 किमी/घंटा"], "समान दूरियों के लिए औसत चाल = 2xy/(x + y) = 2 × 40 × 60 ÷ 100 = 48 किमी/घंटा।"], "2*40*60/(40+60)"),
  q(3, "quant", "mensuration", "H", 1,
    ["The perimeter of a rectangle is 56 m and its length and breadth are in the ratio 4 : 3. Its area is:", ["168 m²", "192 m²", "196 m²", "208 m²"], "Length + breadth = 28 m, so with ratio 4 : 3 they are 16 m and 12 m. Area = 16 × 12 = 192 m²."],
    ["एक आयत का परिमाप 56 मी है और उसकी लंबाई व चौड़ाई का अनुपात 4 : 3 है। उसका क्षेत्रफल है:", ["168 मी²", "192 मी²", "196 मी²", "208 मी²"], "लंबाई + चौड़ाई = 28 मी, अनुपात 4 : 3 से वे 16 मी और 12 मी हैं। क्षेत्रफल = 16 × 12 = 192 मी²।"], "16*12"),
  q(3, "quant", "mensuration", "M", 2,
    ["The total surface area of a cube of side 6 cm is:", ["144 cm²", "180 cm²", "216 cm²", "256 cm²"], "Total surface area = 6a² = 6 × 36 = 216 cm²."],
    ["6 सेमी भुजा वाले घन का कुल पृष्ठीय क्षेत्रफल है:", ["144 सेमी²", "180 सेमी²", "216 सेमी²", "256 सेमी²"], "कुल पृष्ठीय क्षेत्रफल = 6a² = 6 × 36 = 216 सेमी²।"], "6*6*6"),
  q(3, "quant", "partnership", "H", 0,
    ["A invests ₹6,000 and B invests ₹9,000 in a business for the same period. If the profit is ₹7,500, A's share is:", ["₹3,000", "₹3,500", "₹4,000", "₹4,500"], "Profit is shared in the ratio 6 : 9 = 2 : 3, so A gets 2/5 of 7,500 = ₹3,000."],
    ["A ₹6,000 और B ₹9,000 एक व्यवसाय में समान अवधि के लिए लगाते हैं। यदि लाभ ₹7,500 है, तो A का हिस्सा है:", ["₹3,000", "₹3,500", "₹4,000", "₹4,500"], "लाभ 6 : 9 = 2 : 3 के अनुपात में बँटता है, अतः A को 7,500 का 2/5 = ₹3,000 मिलेगा।"], "7500*6/15"),
  q(3, "quant", "mixture-alligation", "H", 3,
    ["A 40-litre mixture of milk and water has milk and water in the ratio 3 : 1. How much water must be added to make the ratio 1 : 1?", ["10 litres", "15 litres", "25 litres", "20 litres"], "Milk = 30 L and water = 10 L. For a 1 : 1 ratio water must also be 30 L, so add 20 L."],
    ["40 लीटर के दूध और पानी के मिश्रण में दूध और पानी का अनुपात 3 : 1 है। अनुपात 1 : 1 करने के लिए कितना पानी मिलाना होगा?", ["10 लीटर", "15 लीटर", "25 लीटर", "20 लीटर"], "दूध = 30 ली और पानी = 10 ली। 1 : 1 अनुपात के लिए पानी भी 30 ली होना चाहिए, अतः 20 ली मिलाएँ।"], "30-10"),
  q(3, "quant", "simplification", "M", 1,
    ["The value of 15% of 240 + 25% of 160 is:", ["72", "76", "80", "84"], "15% of 240 = 36 and 25% of 160 = 40, so the total is 76."],
    ["240 का 15% + 160 का 25% का मान है:", ["72", "76", "80", "84"], "240 का 15% = 36 और 160 का 25% = 40, अतः कुल 76।"], "0.15*240+0.25*160"),
  q(3, "quant", "algebra", "H", 2,
    ["If x + 1/x = 5, then the value of x² + 1/x² is:", ["21", "25", "23", "27"], "Squaring, x² + 2 + 1/x² = 25, so x² + 1/x² = 23."],
    ["यदि x + 1/x = 5 है, तो x² + 1/x² का मान है:", ["21", "25", "23", "27"], "वर्ग करने पर x² + 2 + 1/x² = 25, अतः x² + 1/x² = 23।"], "25-2"),
  q(3, "quant", "ages", "H", 3,
    ["The ratio of the present ages of A and B is 4 : 5. After 5 years the ratio will be 5 : 6. A's present age is:", ["15 years", "16 years", "18 years", "20 years"], "Let the ages be 4k and 5k. (4k + 5)/(5k + 5) = 5/6 gives 24k + 30 = 25k + 25, so k = 5 and A = 20 years."],
    ["A और B की वर्तमान आयु का अनुपात 4 : 5 है। 5 वर्ष बाद अनुपात 5 : 6 हो जाएगा। A की वर्तमान आयु है:", ["15 वर्ष", "16 वर्ष", "18 वर्ष", "20 वर्ष"], "आयु 4k और 5k मानें। (4k + 5)/(5k + 5) = 5/6 से 24k + 30 = 25k + 25, अतः k = 5 और A = 20 वर्ष।"], "4*5"),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "hindi", "muhavare", "M", 1,
    ["'नौ दो ग्यारह होना' मुहावरे का अर्थ है:", ["बहुत धनी होना", "भाग जाना", "गणित में कुशल होना", "बहुत प्रसन्न होना"], "'नौ दो ग्यारह होना' का अर्थ है चुपचाप भाग जाना या गायब हो जाना।"],
    ["'नौ दो ग्यारह होना' मुहावरे का अर्थ है:", ["बहुत धनी होना", "भाग जाना", "गणित में कुशल होना", "बहुत प्रसन्न होना"], "'नौ दो ग्यारह होना' का अर्थ है चुपचाप भाग जाना या गायब हो जाना।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["लोकोक्ति 'अधजल गगरी छलकत जाय' का भाव है:", ["कम पानी बहुत भारी होता है", "घड़ा आधा ही भरना चाहिए", "अल्पज्ञानी अधिक दिखावा करता है", "धीरे-धीरे काम करना चाहिए"], "आधा भरा घड़ा चलते समय छलकता है; इसी प्रकार कम ज्ञान वाला व्यक्ति अधिक दिखावा करता है।"],
    ["लोकोक्ति 'अधजल गगरी छलकत जाय' का भाव है:", ["कम पानी बहुत भारी होता है", "घड़ा आधा ही भरना चाहिए", "अल्पज्ञानी अधिक दिखावा करता है", "धीरे-धीरे काम करना चाहिए"], "आधा भरा घड़ा चलते समय छलकता है; इसी प्रकार कम ज्ञान वाला व्यक्ति अधिक दिखावा करता है।"]),
  q(4, "hindi", "vyakaran", "H", 3,
    ["हिंदी व्याकरण में सर्वनाम के कितने भेद माने जाते हैं?", ["तीन", "चार", "पाँच", "छह"], "सर्वनाम के छह भेद हैं: पुरुषवाचक, निश्चयवाचक, अनिश्चयवाचक, संबंधवाचक, प्रश्नवाचक और निजवाचक।"],
    ["हिंदी व्याकरण में सर्वनाम के कितने भेद माने जाते हैं?", ["तीन", "चार", "पाँच", "छह"], "सर्वनाम के छह भेद हैं: पुरुषवाचक, निश्चयवाचक, अनिश्चयवाचक, संबंधवाचक, प्रश्नवाचक और निजवाचक।"]),
  q(4, "hindi", "ek-shabd", "M", 0,
    ["'जो पहले कभी न हुआ हो' के लिए एक शब्द है:", ["अभूतपूर्व", "अनुपम", "अनादि", "अद्भुत"], "जो पहले कभी न हुआ हो उसे अभूतपूर्व कहते हैं। अनुपम का अर्थ बेजोड़ और अनादि का अर्थ जिसका आरंभ न हो होता है।"],
    ["'जो पहले कभी न हुआ हो' के लिए एक शब्द है:", ["अभूतपूर्व", "अनुपम", "अनादि", "अद्भुत"], "जो पहले कभी न हुआ हो उसे अभूतपूर्व कहते हैं। अनुपम का अर्थ बेजोड़ और अनादि का अर्थ जिसका आरंभ न हो होता है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["निम्नलिखित में से 'पृथ्वी' का पर्यायवाची शब्द नहीं है:", ["धरा", "भूमि", "वसुधा", "किरण"], "धरा, भूमि और वसुधा पृथ्वी के पर्याय हैं; किरण सूर्य या प्रकाश से संबंधित शब्द है।"],
    ["निम्नलिखित में से 'पृथ्वी' का पर्यायवाची शब्द नहीं है:", ["धरा", "भूमि", "वसुधा", "किरण"], "धरा, भूमि और वसुधा पृथ्वी के पर्याय हैं; किरण सूर्य या प्रकाश से संबंधित शब्द है।"]),
  q(4, "hindi", "paryay-vilom", "H", 1,
    ["'आरोह' का विलोम शब्द है:", ["अवनति", "अवरोह", "आरोहण", "उतार-चढ़ाव"], "आरोह का अर्थ चढ़ाव है और उसका विलोम अवरोह (उतार) है।"],
    ["'आरोह' का विलोम शब्द है:", ["अवनति", "अवरोह", "आरोहण", "उतार-चढ़ाव"], "आरोह का अर्थ चढ़ाव है और उसका विलोम अवरोह (उतार) है।"]),
  q(4, "hindi", "sandhi-samas", "M", 2,
    ["'अत्यंत' शब्द का सही संधि-विच्छेद और संधि का प्रकार है:", ["अत्य + अंत, दीर्घ संधि", "अति + अंत, गुण संधि", "अति + अंत, यण संधि", "अत + यंत, व्यंजन संधि"], "अति + अंत में इ का य् हो जाता है और अ से मिलकर 'या' बनता है; इसलिए यह यण संधि है।"],
    ["'अत्यंत' शब्द का सही संधि-विच्छेद और संधि का प्रकार है:", ["अत्य + अंत, दीर्घ संधि", "अति + अंत, गुण संधि", "अति + अंत, यण संधि", "अत + यंत, व्यंजन संधि"], "अति + अंत में इ का य् हो जाता है और अ से मिलकर 'या' बनता है; इसलिए यह यण संधि है।"]),
  q(4, "hindi", "sandhi-samas", "H", 0,
    ["'नवरात्र' शब्द में कौन-सा समास है?", ["द्विगु", "कर्मधारय", "बहुव्रीहि", "अव्ययीभाव"], "नौ रातों का समूह होने से संख्यावाचक पूर्वपद वाला द्विगु समास है।"],
    ["'नवरात्र' शब्द में कौन-सा समास है?", ["द्विगु", "कर्मधारय", "बहुव्रीहि", "अव्ययीभाव"], "नौ रातों का समूह होने से संख्यावाचक पूर्वपद वाला द्विगु समास है।"]),
  q(4, "english", "grammar", "M", 0,
    ["Fill in the blank: He has been working in this office ___ 2015.", ["since", "for", "from", "during"], "'Since' is used with a point in time such as a year; 'for' is used with a period of time."],
    ["रिक्त स्थान भरिए: He has been working in this office ___ 2015.", ["since", "for", "from", "during"], "'Since' का प्रयोग समय-बिंदु (जैसे वर्ष) के साथ होता है; 'for' का प्रयोग अवधि के साथ होता है।"]),
  q(4, "english", "grammar", "H", 2,
    ["Choose the correct option: Each of the girls ___ given a prize.", ["were", "have been", "was", "are"], "'Each' is singular, so it takes a singular verb: 'was given'."],
    ["सही विकल्प चुनिए: Each of the girls ___ given a prize.", ["were", "have been", "was", "are"], "'Each' एकवचन है, इसलिए एकवचन क्रिया 'was given' आती है।"]),
  q(4, "english", "voice-speech", "M", 1,
    ["Change into passive voice: 'She writes a letter.'", ["A letter was written by her.", "A letter is written by her.", "A letter is being written by her.", "A letter has been written by her."], "The simple present active 'writes' becomes 'is written' in the passive voice."],
    ["कर्मवाच्य में बदलिए: 'She writes a letter.'", ["A letter was written by her.", "A letter is written by her.", "A letter is being written by her.", "A letter has been written by her."], "सामान्य वर्तमान काल की क्रिया 'writes' कर्मवाच्य में 'is written' बन जाती है।"]),
  q(4, "english", "idioms", "M", 3,
    ["The idiom 'a blessing in disguise' means:", ["A hidden curse", "A religious ceremony", "A well-planned trick", "Something that seems bad but turns out good"], "A blessing in disguise is something that looks unfortunate at first but later proves beneficial."],
    ["मुहावरे 'a blessing in disguise' का अर्थ है:", ["छिपा हुआ श्राप", "एक धार्मिक अनुष्ठान", "सुनियोजित चाल", "जो बुरा लगे पर बाद में अच्छा निकले"], "Blessing in disguise वह चीज़ है जो पहले दुर्भाग्य जैसी लगे पर बाद में लाभदायक सिद्ध हो।"]),
  q(4, "english", "vocabulary", "H", 1,
    ["Choose the word closest in meaning to 'PRAGMATIC':", ["Idealistic", "Practical", "Emotional", "Theoretical"], "A pragmatic person deals with things sensibly and realistically, focusing on practical results."],
    ["'PRAGMATIC' का निकटतम अर्थ वाला शब्द चुनिए:", ["Idealistic", "Practical", "Emotional", "Theoretical"], "Pragmatic व्यक्ति चीज़ों को समझदारी और यथार्थ से देखता है और व्यावहारिक परिणामों पर ध्यान देता है।"]),
  q(4, "english", "one-word", "H", 2,
    ["One word for 'a person who hates mankind':", ["Misogynist", "Philanthropist", "Misanthrope", "Cynic"], "A misanthrope dislikes or distrusts people in general; a misogynist hates women and a philanthropist loves mankind."],
    ["'मानव जाति से घृणा करने वाला व्यक्ति' के लिए एक शब्द:", ["Misogynist", "Philanthropist", "Misanthrope", "Cynic"], "Misanthrope सामान्यतः लोगों को नापसंद या अविश्वास करता है; misogynist स्त्रियों से घृणा करता है और philanthropist मानव-प्रेमी होता है।"]),
  q(4, "english", "synonyms-antonyms", "M", 3,
    ["Choose the word opposite in meaning to 'SCARCE':", ["Rare", "Limited", "Meagre", "Abundant"], "Scarce means in short supply; its opposite is abundant, meaning plentiful."],
    ["'SCARCE' का विलोम शब्द चुनिए:", ["Rare", "Limited", "Meagre", "Abundant"], "Scarce का अर्थ कम उपलब्ध है; इसका विलोम abundant, यानी प्रचुर, है।"]),

  // ───────── Section 5: Revenue & Computer (5) ─────────
  q(5, "hp-gk", "revenue", "M", 2,
    ["In land records, a 'Khasra' is:", ["The owner's family tree", "The tax receipt", "A field-wise register in which every plot has its own number", "The village boundary map"], "The Khasra register lists each field (plot) of the village by its unique Khasra number along with its area, owner and cultivator."],
    ["भू-अभिलेखों में 'खसरा' क्या है?", ["स्वामी का वंशवृक्ष", "कर की रसीद", "खेत-वार रजिस्टर जिसमें हर भूखंड का अपना नंबर होता है", "गाँव की सीमा का नक्शा"], "खसरा रजिस्टर गाँव के प्रत्येक खेत (भूखंड) को उसके अद्वितीय खसरा नंबर, क्षेत्रफल, स्वामी और काश्तकार के साथ दर्ज करता है।"]),
  q(5, "hp-gk", "revenue", "H", 0,
    ["In Himachal Pradesh, 'Nautor' land refers to:", ["Government land granted to landless persons for cultivation", "Land owned by temples", "Common village land", "Land under forest"], "Nautor is government (new-broken) land that is allotted to landless or poor persons for cultivation under the Nautor rules."],
    ["हिमाचल प्रदेश में 'नौतोड़' भूमि से क्या अभिप्राय है?", ["भूमिहीन व्यक्तियों को खेती के लिए दी गई सरकारी भूमि", "मंदिरों की भूमि", "गाँव की साझा भूमि", "वन के अधीन भूमि"], "नौतोड़ वह सरकारी (नई तोड़ी गई) भूमि है जो नौतोड़ नियमों के अंतर्गत भूमिहीन या गरीब व्यक्तियों को खेती के लिए आवंटित की जाती है।"]),
  q(5, "hp-gk", "revenue", "H", 1,
    ["In the revenue hierarchy, the Kanungo is the officer who:", ["Collects the tax from farmers", "Supervises the work of the Patwaris of his circle", "Hears appeals against the Collector", "Surveys the forests"], "The Kanungo (Girdawar Kanungo) supervises a group of Patwaris and checks their records of mutation and crop inspection."],
    ["राजस्व पदानुक्रम में कानूनगो वह अधिकारी है जो:", ["किसानों से कर वसूलता है", "अपने मंडल के पटवारियों के कार्य का पर्यवेक्षण करता है", "कलेक्टर के विरुद्ध अपीलें सुनता है", "वनों का सर्वेक्षण करता है"], "कानूनगो (गिरदावर कानूनगो) पटवारियों के समूह का पर्यवेक्षण करता है और उनके नामांतरण तथा फसल निरीक्षण के अभिलेखों की जाँच करता है।"]),
  q(5, "computer", "fundamentals", "H", 3,
    ["The CPU of a computer is made up mainly of the:", ["Monitor and keyboard", "RAM and hard disk", "Motherboard and power supply", "Arithmetic Logic Unit and Control Unit"], "The CPU consists of the Arithmetic Logic Unit (ALU), the Control Unit (CU) and registers."],
    ["कंप्यूटर का CPU मुख्यतः किससे बना होता है?", ["मॉनिटर और कीबोर्ड", "रैम और हार्ड डिस्क", "मदरबोर्ड और पावर सप्लाई", "अंकगणित-तर्क इकाई और नियंत्रण इकाई"], "CPU में अंकगणित-तर्क इकाई (ALU), नियंत्रण इकाई (CU) और रजिस्टर होते हैं।"]),
  q(5, "computer", "security", "H", 1,
    ["Phishing is:", ["A hardware fault in the network", "A fraud in which fake messages or sites trick users into giving personal information", "A method of speeding up the internet", "A way of compressing files"], "Phishing uses fake e-mails, texts or websites that imitate trusted bodies to steal passwords, card numbers and other data."],
    ["फ़िशिंग (Phishing) क्या है?", ["नेटवर्क में हार्डवेयर की खराबी", "ऐसी धोखाधड़ी जिसमें नकली संदेशों या साइटों से उपयोगकर्ता से निजी जानकारी ली जाती है", "इंटरनेट की गति बढ़ाने की विधि", "फ़ाइलें संपीड़ित करने का तरीका"], "फ़िशिंग में विश्वसनीय संस्थाओं की नकल करने वाले नकली ई-मेल, संदेश या वेबसाइटों से पासवर्ड, कार्ड नंबर आदि चुराए जाते हैं।"]),
];
