// HP TET (TGT Arts) — Full Mock 1, written fresh: Child Development & Pedagogy 30, Hindi 30, English 30,
// History & Civics 30, Geography, Economics & Himachal GK 30 (sections as in ./index.ts).

import { q, type PatwariQuestion } from "../patwari/types";

export const artsMock1: PatwariQuestion[] = [
  // ───────── Section 0: Child Development & Pedagogy (30) ─────────
  q(0, "pedagogy", "child-development", "M", 2,
    ["The stage of adolescence is generally taken to cover the age range of about:", ["6 to 10 years", "8 to 12 years", "12 to 19 years", "20 to 30 years"], "Adolescence runs from puberty at about 12 until the late teens."],
    ["किशोरावस्था को सामान्यतः लगभग किस आयु-वर्ग में माना जाता है?", ["6 से 10 वर्ष", "8 से 12 वर्ष", "12 से 19 वर्ष", "20 से 30 वर्ष"], "किशोरावस्था लगभग 12 वर्ष की यौवनारंभ आयु से किशोरावस्था के अंत तक चलती है।"]),
  q(0, "pedagogy", "child-development", "H", 0,
    ["A teenager who feels that everyone is watching and judging her appearance shows what David Elkind called the:", ["Imaginary audience", "Personal fable only", "Object permanence", "Animism"], "The imaginary audience is an adolescent form of egocentrism."],
    ["जो किशोरी यह महसूस करती है कि सब उसके रूप-रंग को देख और परख रहे हैं, उसमें डेविड एल्काइंड के अनुसार क्या दिखता है?", ["काल्पनिक दर्शक", "केवल व्यक्तिगत कल्पित कथा", "वस्तु स्थायित्व", "जीववाद"], "काल्पनिक दर्शक किशोरों की आत्म-केंद्रितता का रूप है।"]),
  q(0, "pedagogy", "child-development", "H", 3,
    ["In Marcia's identity statuses, an adolescent who has explored alternatives and then made a firm commitment is in:", ["Identity diffusion", "Foreclosure", "Moratorium", "Identity achievement"], "Exploration followed by commitment is identity achievement."],
    ["मार्शिया की पहचान-स्थितियों में जिस किशोर ने विकल्प खोजे और फिर दृढ़ प्रतिबद्धता कर ली, वह किस स्थिति में है?", ["पहचान-विसरण", "पूर्व-निर्धारण", "स्थगन", "पहचान-उपलब्धि"], "खोज के बाद प्रतिबद्धता पहचान-उपलब्धि है।"]),
  q(0, "pedagogy", "child-development", "H", 1,
    ["Carol Gilligan criticised Kohlberg's moral theory because it:", ["Used too many children", "Overlooked an 'ethic of care' more common in women", "Ignored all stages", "Was based on animals"], "Gilligan argued that Kohlberg's scheme favoured a justice orientation."],
    ["कैरल गिलिगन ने कोहलबर्ग के नैतिक सिद्धांत की आलोचना क्यों की?", ["उसमें बहुत अधिक बच्चे लिए गए", "उसने महिलाओं में अधिक पाई जाने वाली 'देखभाल की नैतिकता' को अनदेखा किया", "उसने सभी चरणों को अनदेखा किया", "वह पशुओं पर आधारित था"], "गिलिगन ने कहा कि कोहलबर्ग की योजना न्याय-उन्मुखता का पक्ष लेती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["The Secondary Education Commission of 1952–53 was headed by:", ["D. S. Kothari", "S. Radhakrishnan", "A. Lakshmanaswami Mudaliar", "Ishwarbhai Patel"], "The Mudaliar Commission reviewed secondary education."],
    ["1952–53 के माध्यमिक शिक्षा आयोग के अध्यक्ष कौन थे?", ["डी. एस. कोठारी", "एस. राधाकृष्णन", "ए. लक्ष्मणस्वामी मुदलियार", "ईश्वरभाई पटेल"], "मुदलियार आयोग ने माध्यमिक शिक्षा की समीक्षा की।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["The 10 + 2 + 3 pattern of education was recommended by the:", ["Kothari Commission (1964–66)", "Hunter Commission", "Sadler Commission", "Wood's Despatch"], "The Kothari Commission proposed the common 10+2+3 structure."],
    ["10 + 2 + 3 की शिक्षा-प्रणाली की सिफ़ारिश किसने की?", ["कोठारी आयोग (1964–66)", "हंटर आयोग", "सैडलर आयोग", "वुड का घोषणा-पत्र"], "कोठारी आयोग ने सामान्य 10+2+3 संरचना का प्रस्ताव दिया।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["The Rashtriya Madhyamik Shiksha Abhiyan (RMSA) was launched in:", ["1995", "2001", "2005", "2009"], "RMSA began in March 2009 to universalise secondary education."],
    ["राष्ट्रीय माध्यमिक शिक्षा अभियान (रमसा) कब शुरू हुआ?", ["1995", "2001", "2005", "2009"], "रमसा मार्च 2009 में माध्यमिक शिक्षा के सार्वभौमीकरण के लिए शुरू हुआ।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["NEP 2020 sets the target of a Gross Enrolment Ratio in higher education of:", ["30% by 2025", "50% by 2035", "75% by 2030", "100% by 2040"], "NEP 2020 aims for 50% GER in higher education by 2035."],
    ["एनईपी 2020 उच्च शिक्षा में सकल नामांकन अनुपात का क्या लक्ष्य रखती है?", ["2025 तक 30%", "2035 तक 50%", "2030 तक 75%", "2040 तक 100%"], "एनईपी 2020 का लक्ष्य 2035 तक उच्च शिक्षा में 50% सकल नामांकन अनुपात है।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["The taxonomy of the affective domain of educational objectives was developed by:", ["Bloom alone", "Simpson", "Krathwohl and others", "Gagné"], "Krathwohl, Bloom and Masia produced the affective domain taxonomy in 1964."],
    ["शैक्षिक उद्देश्यों के भावात्मक क्षेत्र का वर्गीकरण किसने विकसित किया?", ["केवल ब्लूम ने", "सिम्पसन ने", "क्रेथवोल और अन्य ने", "गैग्ने ने"], "क्रेथवोल, ब्लूम और मासिया ने 1964 में भावात्मक क्षेत्र का वर्गीकरण बनाया।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["Which taxonomy of the psychomotor domain, from perception to origination, was prepared by:", ["Simpson", "Krathwohl", "Mager", "Skinner"], "E. J. Simpson proposed the psychomotor taxonomy in 1972."],
    ["अवबोध से मौलिक सृजन तक का मनोगत्यात्मक क्षेत्र का वर्गीकरण किसने तैयार किया?", ["सिम्पसन", "क्रेथवोल", "मेजर", "स्किनर"], "ई. जे. सिम्पसन ने 1972 में मनोगत्यात्मक वर्गीकरण दिया।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["Objectives written as observable behaviour, with conditions and a standard of performance, are associated with:", ["Piaget", "Dewey", "Montessori", "Mager"], "Robert Mager popularised behavioural objectives."],
    ["अवलोकन योग्य व्यवहार, परिस्थितियों और निष्पादन-मानक के साथ लिखे उद्देश्य किससे जुड़े हैं?", ["पियाजे", "ड्यूई", "मॉन्टेसरी", "मेजर"], "रॉबर्ट मेजर ने व्यवहारगत उद्देश्यों को लोकप्रिय बनाया।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["The formal steps of lesson planning — preparation, presentation, association, generalisation, application — come from:", ["Montessori", "Herbart", "Bruner", "Froebel"], "Herbart's five formal steps shaped lesson plans."],
    ["पाठ-योजना के औपचारिक चरण — प्रस्तावना, प्रस्तुतीकरण, तुलना, सामान्यीकरण, प्रयोग — किससे आए हैं?", ["मॉन्टेसरी", "हरबर्ट", "ब्रूनर", "फ्रोबेल"], "हरबर्ट के पाँच औपचारिक चरणों ने पाठ-योजना को आकार दिया।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["Micro-teaching, a skill-based training technique, was first developed at Stanford University by:", ["Skinner", "Bloom", "Dwight Allen", "Thorndike"], "Dwight Allen and colleagues developed it in the 1960s."],
    ["कौशल-आधारित प्रशिक्षण तकनीक सूक्ष्म शिक्षण सबसे पहले स्टैनफ़ोर्ड विश्वविद्यालय में किसने विकसित की?", ["स्किनर", "ब्लूम", "ड्वाइट एलन", "थॉर्नडाइक"], "ड्वाइट एलन और साथियों ने इसे 1960 के दशक में विकसित किया।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["An 'advance organiser', introduced before a lesson to link new ideas to old, is a concept of:", ["David Ausubel", "Jerome Bruner", "Edward Tolman", "John Watson"], "Ausubel's meaningful verbal learning uses advance organisers."],
    ["'अग्रिम व्यवस्थापक', जो पाठ से पहले नए विचारों को पुराने से जोड़ने के लिए दिया जाता है, किसकी अवधारणा है?", ["डेविड ऑसुबेल", "जेरोम ब्रूनर", "एडवर्ड टॉलमैन", "जॉन वॉटसन"], "ऑसुबेल का सार्थक शाब्दिक अधिगम अग्रिम व्यवस्थापकों का प्रयोग करता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["The 'jigsaw' technique of cooperative learning, in which each group member teaches part of a topic, was devised by:", ["Vygotsky", "Bandura", "Kilpatrick", "Elliot Aronson"], "Aronson created the jigsaw classroom in 1971."],
    ["सहकारी अधिगम की 'जिग-सॉ' तकनीक, जिसमें प्रत्येक सदस्य विषय का एक भाग सिखाता है, किसने बनाई?", ["वायगोत्स्की", "बंडूरा", "किलपैट्रिक", "इलियट एरोनसन"], "एरोनसन ने 1971 में जिग-सॉ कक्षा बनाई।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["The constructivist 5E instructional model consists of Engage, Explore, Explain, Elaborate and:", ["Examine", "Evaluate", "Exempt", "Express"], "The last E stands for Evaluate."],
    ["रचनावादी 5E शिक्षण मॉडल में Engage, Explore, Explain, Elaborate और क्या है?", ["Examine", "Evaluate", "Exempt", "Express"], "अंतिम E का अर्थ Evaluate है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["In inquiry-based learning the teacher mainly:", ["Dictates the conclusions", "Stops all questions", "Poses problems and guides pupils to investigate", "Gives only tests"], "Pupils find answers through guided investigation."],
    ["जिज्ञासा-आधारित अधिगम में शिक्षक मुख्यतः क्या करता है?", ["निष्कर्ष लिखवाता है", "सभी प्रश्न बंद कर देता है", "समस्याएँ रखता है और विद्यार्थियों को खोजबीन के लिए निर्देशित करता है", "केवल परीक्षा लेता है"], "विद्यार्थी निर्देशित खोजबीन से उत्तर ढूँढते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["Blended learning refers to a combination of:", ["Face-to-face teaching and online learning", "Two textbooks", "Two school boards", "Morning and evening shifts"], "It mixes classroom and digital learning."],
    ["मिश्रित अधिगम (ब्लेंडेड लर्निंग) का अर्थ किसका संयोजन है?", ["आमने-सामने शिक्षण और ऑनलाइन अधिगम का", "दो पाठ्यपुस्तकों का", "दो विद्यालय बोर्डों का", "प्रातः और सायं पालियों का"], "यह कक्षा और डिजिटल अधिगम को मिलाता है।"]),
  q(0, "pedagogy", "inclusive-education", "H", 2,
    ["Universal Design for Learning (UDL) suggests that lessons should offer:", ["One fixed route for all", "Only printed text", "Multiple means of engagement, representation and expression", "Separate classes for each learner"], "UDL plans for learner variability from the start."],
    ["सीखने की सार्वभौमिक डिज़ाइन (यूडीएल) के अनुसार पाठों में क्या उपलब्ध होना चाहिए?", ["सबके लिए एक निश्चित मार्ग", "केवल मुद्रित पाठ", "जुड़ाव, प्रस्तुति और अभिव्यक्ति के कई साधन", "प्रत्येक शिक्षार्थी के लिए अलग कक्षा"], "यूडीएल आरंभ से ही शिक्षार्थियों की विविधता की योजना बनाता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["Comparing a pupil's score with a fixed standard of mastery, not with other pupils, is called:", ["Norm-referenced testing", "Ranking", "Percentile ranking", "Criterion-referenced testing"], "Criterion-referenced tests judge against a defined standard."],
    ["विद्यार्थी के अंकों की तुलना अन्य विद्यार्थियों से नहीं बल्कि निपुणता के निश्चित मानक से करना क्या कहलाता है?", ["मानक-संदर्भित परीक्षण", "क्रमांकन", "शतांशिक क्रमांकन", "कसौटी-संदर्भित परीक्षण"], "कसौटी-संदर्भित परीक्षण निर्धारित मानक के आधार पर आँकते हैं।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["Dividing a test into two halves (odd and even items) and correlating the scores is a method of finding its:", ["Validity", "Reliability", "Difficulty", "Usability"], "The split-half method estimates reliability."],
    ["किसी परीक्षण को दो भागों (विषम और सम प्रश्न) में बाँटकर अंकों का सहसंबंध निकालना उसकी किस बात को जानने की विधि है?", ["वैधता", "विश्वसनीयता", "कठिनता", "उपयोगिता"], "अर्द्ध-विभाजन विधि विश्वसनीयता का अनुमान देती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["In item analysis, a question answered correctly by 90% of the pupils is:", ["Very difficult", "Moderately difficult", "Easy", "Invalid"], "A high percentage of correct answers means an easy item."],
    ["प्रश्न-विश्लेषण में जिस प्रश्न का सही उत्तर 90% विद्यार्थी देते हैं वह है:", ["बहुत कठिन", "मध्यम कठिन", "सरल", "अवैध"], "सही उत्तरों का उच्च प्रतिशत सरल प्रश्न दर्शाता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["A short, dated note on an incident in a pupil's behaviour, written by a teacher, is called an:", ["Achievement test", "Anecdotal record", "Sociogram", "Aptitude score"], "Anecdotal records capture significant observed incidents."],
    ["शिक्षक द्वारा लिखा गया विद्यार्थी के व्यवहार की किसी घटना का संक्षिप्त, दिनांकित विवरण क्या कहलाता है?", ["उपलब्धि परीक्षण", "घटना-वृत्त (एनेकडोटल रिकॉर्ड)", "समाजमिति", "अभिक्षमता अंक"], "घटना-वृत्त देखी गई महत्त्वपूर्ण घटनाओं को दर्ज करते हैं।"]),
  q(0, "pedagogy", "child-development", "H", 3,
    ["Frank Parsons, who set up the Vocational Bureau in Boston in 1908, is known as the father of:", ["Intelligence testing", "Programmed learning", "Kindergarten", "Vocational guidance"], "Parsons founded the vocational guidance movement."],
    ["1908 में बोस्टन में व्यावसायिक ब्यूरो स्थापित करने वाले फ्रैंक पार्सन्स किसके जनक माने जाते हैं?", ["बुद्धि परीक्षण के", "अभिक्रमित अधिगम के", "किंडरगार्टन के", "व्यावसायिक निर्देशन के"], "पार्सन्स ने व्यावसायिक निर्देशन आंदोलन की स्थापना की।"]),
  q(0, "pedagogy", "child-development", "M", 0,
    ["Carl Rogers's counselling approach, in which the counsellor shows unconditional positive regard, is called:", ["Client-centred", "Directive", "Eclectic only", "Behaviour-shaping"], "Rogers developed client-centred (non-directive) counselling."],
    ["कार्ल रोजर्स का वह परामर्श-उपागम, जिसमें परामर्शदाता बिना शर्त सकारात्मक सम्मान दिखाता है, कहलाता है:", ["सेवार्थी-केंद्रित", "निर्देशात्मक", "केवल समन्वयात्मक", "व्यवहार-आकारण"], "रोजर्स ने सेवार्थी-केंद्रित (अनिर्देशात्मक) परामर्श विकसित किया।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["Which body prescribes norms and standards for teacher education programmes in India?", ["UGC", "CBSE", "NCTE", "AICTE"], "The National Council for Teacher Education regulates teacher education."],
    ["भारत में शिक्षक-शिक्षा कार्यक्रमों के मानदंड और मानक कौन-सी संस्था निर्धारित करती है?", ["यूजीसी", "सीबीएसई", "एनसीटीई", "एआईसीटीई"], "राष्ट्रीय अध्यापक शिक्षा परिषद शिक्षक-शिक्षा को विनियमित करती है।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["The National Council for Teacher Education was given statutory status in:", ["1986", "1995", "2005", "2010"], "The NCTE Act of 1993 came into force in 1995."],
    ["राष्ट्रीय अध्यापक शिक्षा परिषद को वैधानिक दर्जा किस वर्ष मिला?", ["1986", "1995", "2005", "2010"], "एनसीटीई अधिनियम 1993 का 1995 में प्रवर्तन हुआ।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["A teacher who studies her own classroom problem systematically and tries solutions to improve practice is doing:", ["Survey research", "Historical research", "Case-law study", "Action research"], "Action research aims at improving practice in one's own setting."],
    ["जो शिक्षक अपनी कक्षा की समस्या का व्यवस्थित अध्ययन कर सुधार के लिए समाधान आज़माता है, वह क्या कर रहा है?", ["सर्वेक्षण अनुसंधान", "ऐतिहासिक अनुसंधान", "विधि-प्रकरण अध्ययन", "क्रियात्मक अनुसंधान"], "क्रियात्मक अनुसंधान अपने परिवेश में व्यवहार सुधारने का प्रयास है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["Positive discipline in school is best described as discipline that is:", ["Based on respect, clear limits and guidance", "Based on fear", "Absent", "Imposed by outsiders only"], "Positive discipline teaches self-control without humiliation."],
    ["विद्यालय में सकारात्मक अनुशासन का सबसे अच्छा वर्णन कौन-सा है?", ["सम्मान, स्पष्ट सीमाओं और मार्गदर्शन पर आधारित", "भय पर आधारित", "अनुपस्थित", "केवल बाहरी लोगों द्वारा थोपा गया"], "सकारात्मक अनुशासन अपमान के बिना आत्म-नियंत्रण सिखाता है।"]),
  q(0, "pedagogy", "inclusive-education", "M", 2,
    ["The 'Beti Bachao Beti Padhao' scheme was launched in:", ["2010", "2012", "2015", "2018"], "It was launched from Panipat in January 2015."],
    ["'बेटी बचाओ बेटी पढ़ाओ' योजना कब शुरू हुई?", ["2010", "2012", "2015", "2018"], "इसे जनवरी 2015 में पानीपत से शुरू किया गया।"]),

  // ───────── Section 1: Hindi (30) ─────────
  q(1, "hindi", "sahitya", "M", 1,
    ["Who wrote the novel 'गोदान'?", ["जयशंकर प्रसाद", "प्रेमचंद", "यशपाल", "अज्ञेय"], "गोदान (1936) is Premchand's last complete novel."],
    ["उपन्यास 'गोदान' के लेखक कौन हैं?", ["जयशंकर प्रसाद", "प्रेमचंद", "यशपाल", "अज्ञेय"], "गोदान (1936) प्रेमचंद का अंतिम पूर्ण उपन्यास है।"]),
  q(1, "hindi", "sahitya", "M", 3,
    ["'कामायनी' is a famous epic poem by:", ["निराला", "महादेवी वर्मा", "पंत", "जयशंकर प्रसाद"], "कामायनी (1936) is Jaishankar Prasad's masterpiece."],
    ["'कामायनी' किसका प्रसिद्ध महाकाव्य है?", ["निराला", "महादेवी वर्मा", "पंत", "जयशंकर प्रसाद"], "कामायनी (1936) जयशंकर प्रसाद की श्रेष्ठ कृति है।"]),
  q(1, "hindi", "sahitya", "H", 0,
    ["Which of these poets is NOT counted among the four pillars (chhayavad) of Hindi poetry?", ["दिनकर", "प्रसाद", "पंत", "महादेवी वर्मा"], "The four chhayavadi poets are Prasad, Pant, Nirala and Mahadevi Verma."],
    ["इनमें से किस कवि की गिनती छायावाद के चार स्तंभों में नहीं होती?", ["दिनकर", "प्रसाद", "पंत", "महादेवी वर्मा"], "छायावाद के चार कवि प्रसाद, पंत, निराला और महादेवी वर्मा हैं।"]),
  q(1, "hindi", "sahitya", "M", 2,
    ["'मधुशाला' was written by:", ["सुमित्रानंदन पंत", "अज्ञेय", "हरिवंश राय बच्चन", "नागार्जुन"], "मधुशाला (1935) is Harivansh Rai Bachchan's best-known work."],
    ["'मधुशाला' के रचयिता कौन हैं?", ["सुमित्रानंदन पंत", "अज्ञेय", "हरिवंश राय बच्चन", "नागार्जुन"], "मधुशाला (1935) हरिवंश राय बच्चन की सबसे प्रसिद्ध रचना है।"]),
  q(1, "hindi", "sahitya", "H", 1,
    ["The 'Bhakti Kaal' of Hindi literature is generally dated to:", ["1000–1375 CE", "1375–1700 CE", "1700–1900 CE", "1900–1950 CE"], "Bhakti Kaal is 1375–1700 in the usual scheme."],
    ["हिंदी साहित्य के 'भक्ति काल' की सामान्य अवधि मानी जाती है:", ["1000–1375 ई.", "1375–1700 ई.", "1700–1900 ई.", "1900–1950 ई."], "सामान्य विभाजन में भक्ति काल 1375–1700 ई. है।"]),
  q(1, "hindi", "sahitya", "M", 0,
    ["'रामचरितमानस' was composed by:", ["तुलसीदास", "सूरदास", "कबीर", "रहीम"], "Tulsidas wrote Ramcharitmanas in Awadhi."],
    ["'रामचरितमानस' की रचना किसने की?", ["तुलसीदास", "सूरदास", "कबीर", "रहीम"], "तुलसीदास ने रामचरितमानस अवधी में रचा।"]),
  q(1, "hindi", "sahitya", "H", 2,
    ["The 'Sursagar' is mainly devoted to the childhood and pastimes of:", ["Rama", "Shiva", "Krishna", "Hanuman"], "Surdas's Sursagar is centred on Krishna."],
    ["'सूरसागर' मुख्यतः किसकी बाल-लीलाओं और क्रीड़ाओं पर केंद्रित है?", ["राम", "शिव", "कृष्ण", "हनुमान"], "सूरदास का सूरसागर कृष्ण पर केंद्रित है।"]),
  q(1, "hindi", "sahitya", "M", 3,
    ["Who is regarded as the father of modern Hindi literature (Khari Boli)?", ["कबीर", "चंद्रबरदाई", "विद्यापति", "भारतेंदु हरिश्चंद्र"], "Bharatendu Harishchandra is called the father of modern Hindi."],
    ["आधुनिक हिंदी साहित्य (खड़ी बोली) का जनक किसे माना जाता है?", ["कबीर", "चंद्रबरदाई", "विद्यापति", "भारतेंदु हरिश्चंद्र"], "भारतेंदु हरिश्चंद्र को आधुनिक हिंदी का जनक कहा जाता है।"]),
  q(1, "hindi", "sandhi-samas", "M", 2,
    ["Split the word 'सूर्यास्त' into sandhi parts:", ["सूरी + अस्त", "सूर्य + आस्त", "सूर्य + अस्त", "सूर्या + स्त"], "अ + अ = आ (dirgha sandhi): सूर्य + अस्त."],
    ["'सूर्यास्त' का संधि-विच्छेद कीजिए:", ["सूरी + अस्त", "सूर्य + आस्त", "सूर्य + अस्त", "सूर्या + स्त"], "अ + अ = आ (दीर्घ संधि): सूर्य + अस्त।"]),
  q(1, "hindi", "sandhi-samas", "H", 1,
    ["Split the word 'पवित्र' as a sandhi: 'पो + इत्र'. Which sandhi is this (ओ + इ = अव् + इ)?", ["गुण संधि", "अयादि संधि", "वृद्धि संधि", "यण संधि"], "ओ followed by a vowel changes to अव्: ayadi sandhi."],
    ["'पवित्र' (पो + इत्र) में ओ + इ = अव् + इ हुआ है। यह कौन-सी संधि है?", ["गुण संधि", "अयादि संधि", "वृद्धि संधि", "यण संधि"], "ओ के बाद स्वर आने पर वह अव् हो जाता है: अयादि संधि।"]),
  q(1, "hindi", "sandhi-samas", "H", 3,
    ["Split the word 'पुनर्जन्म' into sandhi parts:", ["पुना + र्जन्म", "पुनर + जन्म", "पुन + र्जन्म", "पुनः + जन्म"], "Visarg (ः) before a voiced consonant becomes र्: पुनः + जन्म."],
    ["'पुनर्जन्म' का संधि-विच्छेद कीजिए:", ["पुना + र्जन्म", "पुनर + जन्म", "पुन + र्जन्म", "पुनः + जन्म"], "घोष व्यंजन से पहले विसर्ग का र् हो जाता है: पुनः + जन्म।"]),
  q(1, "hindi", "sandhi-samas", "M", 0,
    ["'त्रिभुवन' (तीन भुवनों का समाहार) is an example of:", ["द्विगु समास", "तत्पुरुष समास", "द्वंद्व समास", "बहुव्रीहि समास"], "A number as the first word with a group meaning: dvigu."],
    ["'त्रिभुवन' (तीन भुवनों का समाहार) किसका उदाहरण है?", ["द्विगु समास", "तत्पुरुष समास", "द्वंद्व समास", "बहुव्रीहि समास"], "पहला पद संख्या का और अर्थ समूह का: द्विगु समास।"]),
  q(1, "hindi", "sandhi-samas", "H", 2,
    ["'दशरथ' (दस हैं रथ जिसके, अर्थात् राम के पिता) is an example of:", ["द्विगु समास", "कर्मधारय समास", "बहुव्रीहि समास", "तत्पुरुष समास"], "The compound names another person, so it is bahuvrihi."],
    ["'दशरथ' (दस हैं रथ जिसके, अर्थात् राम के पिता) किसका उदाहरण है?", ["द्विगु समास", "कर्मधारय समास", "बहुव्रीहि समास", "तत्पुरुष समास"], "यह किसी अन्य व्यक्ति का नाम बताता है, इसलिए बहुव्रीहि समास है।"]),
  q(1, "hindi", "paryay-vilom", "M", 1,
    ["Choose the synonym of 'अश्व':", ["गज", "घोड़ा", "ऊँट", "बैल"], "अश्व, तुरंग and हय mean horse."],
    ["'अश्व' का पर्यायवाची चुनिए:", ["गज", "घोड़ा", "ऊँट", "बैल"], "अश्व, तुरंग और हय का अर्थ घोड़ा है।"]),
  q(1, "hindi", "paryay-vilom", "H", 3,
    ["Choose the synonym of 'कानन':", ["नदी", "पर्वत", "सागर", "वन"], "कानन, अरण्य and विपिन mean forest."],
    ["'कानन' का पर्यायवाची चुनिए:", ["नदी", "पर्वत", "सागर", "वन"], "कानन, अरण्य और विपिन का अर्थ जंगल है।"]),
  q(1, "hindi", "paryay-vilom", "H", 0,
    ["Choose the antonym of 'वरदान':", ["अभिशाप", "आशीर्वाद", "उपहार", "कृपा"], "वरदान is a boon; अभिशाप is a curse."],
    ["'वरदान' का विलोम चुनिए:", ["अभिशाप", "आशीर्वाद", "उपहार", "कृपा"], "वरदान का अर्थ आशीष है; अभिशाप का अर्थ श्राप है।"]),
  q(1, "hindi", "paryay-vilom", "M", 2,
    ["Choose the antonym of 'सरल':", ["सीधा", "आसान", "जटिल", "सुगम"], "सरल is simple; जटिल is complicated."],
    ["'सरल' का विलोम चुनिए:", ["सीधा", "आसान", "जटिल", "सुगम"], "सरल का अर्थ सीधा है; जटिल का अर्थ उलझा हुआ है।"]),
  q(1, "hindi", "ek-shabd", "M", 1,
    ["Which single word means 'जो कम बोलता हो'?", ["वाचाल", "मितभाषी", "वक्ता", "मौन"], "मितभाषी speaks little and to the point."],
    ["'जो कम बोलता हो' के लिए एक शब्द कौन-सा है?", ["वाचाल", "मितभाषी", "वक्ता", "मौन"], "मितभाषी कम और सारगर्भित बोलता है।"]),
  q(1, "hindi", "ek-shabd", "H", 3,
    ["Which single word means 'जिसे जीतना कठिन हो'?", ["अजेय", "अपराजित", "विजेता", "दुर्जेय"], "दुर्जेय means difficult to conquer."],
    ["'जिसे जीतना कठिन हो' के लिए एक शब्द कौन-सा है?", ["अजेय", "अपराजित", "विजेता", "दुर्जेय"], "दुर्जेय का अर्थ है जिसे जीतना कठिन हो।"]),
  q(1, "hindi", "ek-shabd", "M", 0,
    ["Which single word means 'जो बहुत दिनों तक जीवित रहे'?", ["चिरंजीवी", "अमर", "दीर्घायु", "सजीव"], "चिरंजीवी is long-lived."],
    ["'जो बहुत दिनों तक जीवित रहे' के लिए एक शब्द कौन-सा है?", ["चिरंजीवी", "अमर", "दीर्घायु", "सजीव"], "चिरंजीवी का अर्थ है चिरकाल तक जीने वाला।"]),
  q(1, "hindi", "muhavare", "M", 2,
    ["Meaning of the idiom 'आँखों में धूल झोंकना':", ["धूल उड़ाना", "आँख धोना", "धोखा देना", "रोना"], "The idiom means to deceive someone."],
    ["मुहावरे 'आँखों में धूल झोंकना' का अर्थ है:", ["धूल उड़ाना", "आँख धोना", "धोखा देना", "रोना"], "इस मुहावरे का अर्थ है किसी को धोखा देना।"]),
  q(1, "hindi", "muhavare", "H", 1,
    ["Meaning of the proverb 'थोथा चना बाजे घना':", ["चना सस्ता होना", "गुणहीन व्यक्ति अधिक डींग मारता है", "बाज़ार में शोर", "चना भूनना"], "An empty vessel makes the most sound."],
    ["लोकोक्ति 'थोथा चना बाजे घना' का अर्थ है:", ["चना सस्ता होना", "गुणहीन व्यक्ति अधिक डींग मारता है", "बाज़ार में शोर", "चना भूनना"], "खोखला पात्र अधिक आवाज़ करता है।"]),
  q(1, "hindi", "muhavare", "M", 3,
    ["Meaning of the idiom 'सिर पर पाँव रखकर भागना':", ["तेज़ दौड़ना सीखना", "सिर दर्द होना", "पैर पर चोट लगना", "बहुत तेज़ी से भाग जाना"], "The idiom means to flee in great haste."],
    ["मुहावरे 'सिर पर पाँव रखकर भागना' का अर्थ है:", ["तेज़ दौड़ना सीखना", "सिर दर्द होना", "पैर पर चोट लगना", "बहुत तेज़ी से भाग जाना"], "इस मुहावरे का अर्थ है बहुत जल्दी में भाग निकलना।"]),
  q(1, "hindi", "shuddh-vartani", "H", 2,
    ["Pick the correctly spelt word meaning 'poverty':", ["दरिद्रता", "दारिद्र्य", "दारिद्रय", "दरिद्र्ता"], "The standard form is दारिद्र्य."],
    ["'ग़रीबी' अर्थ वाला शुद्ध वर्तनी का शब्द चुनिए:", ["दरिद्रता", "दारिद्रय", "दारिद्र्य", "दरिद्र्ता"], "मानक रूप दारिद्र्य है।"]),
  q(1, "hindi", "shuddh-vartani", "M", 0,
    ["Pick the correct spelling:", ["संन्यासी", "सन्यासी", "संनयासी", "संन्यासि"], "The standard form is संन्यासी."],
    ["शुद्ध वर्तनी चुनिए:", ["संन्यासी", "सन्यासी", "संनयासी", "संन्यासि"], "मानक रूप संन्यासी है।"]),
  q(1, "hindi", "vyakaran", "H", 3,
    ["In 'पानी में मछली रहती है', the case marker 'में' shows which kaarak?", ["कर्म कारक", "करण कारक", "संप्रदान कारक", "अधिकरण कारक"], "'में' indicates the place or location: adhikaran."],
    ["'पानी में मछली रहती है' में 'में' कौन-सा कारक दर्शाता है?", ["कर्म कारक", "करण कारक", "संप्रदान कारक", "अधिकरण कारक"], "'में' स्थान या आधार दर्शाता है: अधिकरण कारक।"]),
  q(1, "hindi", "vyakaran", "M", 1,
    ["In 'वह कलम से लिखता है', the marker 'से' shows which kaarak?", ["कर्म", "करण", "अपादान", "संबंध"], "'से' shows the instrument: karan."],
    ["'वह कलम से लिखता है' में 'से' कौन-सा कारक दर्शाता है?", ["कर्म", "करण", "अपादान", "संबंध"], "'से' साधन दर्शाता है: करण कारक।"]),
  q(1, "hindi", "vyakaran", "H", 2,
    ["Which of these sentences has a correct use of gender?", ["मेरा बहन आई है।", "मेरे बहन आई है।", "मेरी बहन आई है।", "मेरी बहन आया है।"], "The possessive and the verb must agree with the feminine noun 'बहन'."],
    ["इनमें से किस वाक्य में लिंग का सही प्रयोग है?", ["मेरा बहन आई है।", "मेरे बहन आई है।", "मेरी बहन आई है।", "मेरी बहन आया है।"], "संबंधबोधक और क्रिया को स्त्रीलिंग संज्ञा 'बहन' के अनुसार चलना चाहिए।"]),
  q(1, "hindi", "alankar-ras", "M", 0,
    ["The sthayi bhav of 'हास्य रस' is:", ["हास", "रति", "शोक", "उत्साह"], "Haas (laughter) is the sthayi bhav of hasya ras."],
    ["'हास्य रस' का स्थायी भाव है:", ["हास", "रति", "शोक", "उत्साह"], "हास्य रस का स्थायी भाव हास है।"]),
  q(1, "hindi", "alankar-ras", "H", 1,
    ["'मुख मानो चंद्रमा है' – this line uses which figure of speech?", ["उपमा", "उत्प्रेक्षा", "यमक", "श्लेष"], "The word 'मानो' marks an imagined comparison: utpreksha."],
    ["'मुख मानो चंद्रमा है' इस पंक्ति में कौन-सा अलंकार है?", ["उपमा", "उत्प्रेक्षा", "यमक", "श्लेष"], "'मानो' शब्द कल्पित तुलना बताता है: उत्प्रेक्षा।"]),

  // ───────── Section 2: English (30) ─────────
  q(2, "english", "literature", "M", 1,
    ["Who wrote the play 'Hamlet'?", ["Christopher Marlowe", "William Shakespeare", "George Bernard Shaw", "Ben Jonson"], "Hamlet is a tragedy by Shakespeare."],
    ["नाटक 'Hamlet' किसने लिखा?", ["क्रिस्टोफ़र मार्लो", "विलियम शेक्सपियर", "जॉर्ज बर्नार्ड शॉ", "बेन जॉनसन"], "हैमलेट शेक्सपियर की एक त्रासदी है।"]),
  q(2, "english", "literature", "M", 3,
    ["'Gitanjali', for which Rabindranath Tagore won the Nobel Prize, is a collection of:", ["Short stories", "Plays", "Essays", "Poems"], "Gitanjali is a collection of poems; the Prize came in 1913."],
    ["'गीतांजलि', जिस पर रवींद्रनाथ टैगोर को नोबेल पुरस्कार मिला, किसका संग्रह है?", ["कहानियों का", "नाटकों का", "निबंधों का", "कविताओं का"], "गीतांजलि कविताओं का संग्रह है; पुरस्कार 1913 में मिला।"]),
  q(2, "english", "literature", "H", 0,
    ["The poem 'The Road Not Taken' is by:", ["Robert Frost", "Walt Whitman", "T. S. Eliot", "William Blake"], "It is a famous poem by the American poet Robert Frost."],
    ["कविता 'The Road Not Taken' किसकी है?", ["रॉबर्ट फ़्रॉस्ट", "वॉल्ट व्हिटमैन", "टी. एस. एलियट", "विलियम ब्लेक"], "यह अमेरिकी कवि रॉबर्ट फ़्रॉस्ट की प्रसिद्ध कविता है।"]),
  q(2, "english", "literature", "H", 2,
    ["'Paradise Lost' is an epic poem by:", ["Chaucer", "Spenser", "John Milton", "Pope"], "Milton published Paradise Lost in 1667."],
    ["'Paradise Lost' किसका महाकाव्य है?", ["चॉसर", "स्पेंसर", "जॉन मिल्टन", "पोप"], "मिल्टन ने पैराडाइज़ लॉस्ट 1667 में प्रकाशित किया।"]),
  q(2, "english", "grammar", "M", 3,
    ["Fill in the blank: 'The scientist, together with her assistants, ___ the experiment.'", ["are conducting", "have conducted", "were conducting", "is conducting"], "The verb agrees with the singular subject 'scientist'."],
    ["रिक्त स्थान भरिए: 'The scientist, together with her assistants, ___ the experiment.'", ["are conducting", "have conducted", "were conducting", "is conducting"], "क्रिया एकवचन कर्ता 'scientist' के अनुसार आती है।"]),
  q(2, "english", "grammar", "H", 1,
    ["Which sentence correctly expresses a wish about an unreal present situation?", ["I wish I was taller.", "I wish I were taller.", "I wish I am taller.", "I wish I will be taller."], "A wish about an unreal present takes the subjunctive 'were'."],
    ["सही वाक्य चुनिए (इच्छा व्यक्त करने वाला)।", ["I wish I was taller.", "I wish I were taller.", "I wish I am taller.", "I wish I will be taller."], "अवास्तविक वर्तमान की इच्छा में subjunctive 'were' आता है।"]),
  q(2, "english", "grammar", "M", 2,
    ["Fill in the blank: 'She has lived in Shimla ___ ten years.'", ["since", "from", "for", "by"], "'For' is used with a period of time."],
    ["रिक्त स्थान भरिए: 'She has lived in Shimla ___ ten years.'", ["since", "from", "for", "by"], "अवधि के साथ 'for' आता है।"]),
  q(2, "english", "grammar", "H", 0,
    ["Choose the word that correctly fills the blank: 'The book, ___ cover is torn, is mine.'", ["whose", "who", "which", "whom"], "'Whose' shows possession and can refer to things."],
    ["सही शब्द से रिक्त स्थान भरिए: 'The book, ___ cover is torn, is mine.'", ["whose", "who", "which", "whom"], "'Whose' स्वामित्व दर्शाता है और वस्तुओं के लिए भी आ सकता है।"]),
  q(2, "english", "grammar", "M", 1,
    ["Fill in the blank: 'I would rather ___ at home than go out in this rain.'", ["to stay", "stay", "staying", "stayed"], "'Would rather' is followed by the base form."],
    ["रिक्त स्थान भरिए: 'I would rather ___ at home than go out in this rain.'", ["to stay", "stay", "staying", "stayed"], "'Would rather' के बाद क्रिया का मूल रूप आता है।"]),
  q(2, "english", "error-spotting", "H", 3,
    ["Find the part with an error: 'No sooner (A) did the teacher enter (B) than (C) the students stood up. (D)' If there is no error, choose D.", ["A", "B", "C", "No error"], "The sentence is correct."],
    ["त्रुटि वाला भाग चुनिए: 'No sooner (A) did the teacher enter (B) than (C) the students stood up. (D)' यदि त्रुटि न हो तो 'No error' चुनिए।", ["A", "B", "C", "No error"], "वाक्य सही है।"]),
  q(2, "english", "error-spotting", "M", 2,
    ["Find the part with an error: 'The committee (A) has submitted (B) their reports (C) yesterday. (D)'", ["A", "B", "D", "C"], "A single report by one committee: 'its report'."],
    ["त्रुटि वाला भाग चुनिए: 'The committee (A) has submitted (B) their reports (C) yesterday. (D)'", ["A", "B", "D", "C"], "एक समिति की एक रिपोर्ट: 'its report'।"]),
  q(2, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'He suggested (A) me (B) to take (C) a taxi. (D)'", ["A", "B", "C", "D"], "'Suggest' is not followed by an object plus 'to': 'suggested that I take'."],
    ["त्रुटि वाला भाग चुनिए: 'He suggested (A) me (B) to take (C) a taxi. (D)'", ["A", "B", "C", "D"], "'Suggest' के बाद कर्म और 'to' नहीं आता: 'suggested that I take'।"]),
  q(2, "english", "voice-speech", "H", 0,
    ["Change to the passive: 'People say that honesty is the best policy.'", ["It is said that honesty is the best policy.", "It was said honesty is the best policy.", "Honesty said to be the best policy.", "It says that honesty is best policy."], "The impersonal passive uses 'It is said that …'."],
    ["Passive में बदलिए: 'People say that honesty is the best policy.'", ["It is said that honesty is the best policy.", "It was said honesty is the best policy.", "Honesty said to be the best policy.", "It says that honesty is best policy."], "अवैयक्तिक passive 'It is said that …' से बनता है।"]),
  q(2, "english", "voice-speech", "M", 3,
    ["Change to the indirect speech: 'He said, \"Do you know the way?\"'", ["He said that did I know the way.", "He asked me that if I know the way.", "He asked if I know the way.", "He asked me if I knew the way."], "A yes/no question is reported with 'if' in statement order."],
    ["Indirect speech में बदलिए: 'He said, \"Do you know the way?\"'", ["He said that did I know the way.", "He asked me that if I know the way.", "He asked if I know the way.", "He asked me if I knew the way."], "हाँ/ना प्रश्न को 'if' और कथन-क्रम से बताया जाता है।"]),
  q(2, "english", "vocabulary", "H", 2,
    ["Which word is nearest in meaning to 'EPHEMERAL'?", ["Eternal", "Heavy", "Short-lived", "Ancient"], "Ephemeral means lasting a very short time."],
    ["'EPHEMERAL' के निकटतम अर्थ वाला शब्द कौन-सा है?", ["Eternal", "Heavy", "Short-lived", "Ancient"], "Ephemeral का अर्थ बहुत थोड़े समय तक रहने वाला है।"]),
  q(2, "english", "synonyms-antonyms", "H", 1,
    ["The antonym of 'FRUGAL' is:", ["Thrifty", "Extravagant", "Careful", "Poor"], "Frugal means economical; extravagant is the opposite."],
    ["'FRUGAL' का विलोम है:", ["Thrifty", "Extravagant", "Careful", "Poor"], "Frugal का अर्थ मितव्ययी है; extravagant उसका उलटा है।"]),
  q(2, "english", "synonyms-antonyms", "M", 0,
    ["The antonym of 'OPTIMISTIC' is:", ["Pessimistic", "Hopeful", "Cheerful", "Confident"], "An optimist expects the best; a pessimist the worst."],
    ["'OPTIMISTIC' का विलोम है:", ["Pessimistic", "Hopeful", "Cheerful", "Confident"], "आशावादी सर्वोत्तम की आशा रखता है; निराशावादी सबसे बुरे की।"]),
  q(2, "english", "idioms", "H", 3,
    ["The idiom 'to cut corners' means to:", ["Make a square shape", "Walk quickly", "Hurt oneself", "Do something in the easiest or cheapest way, sacrificing quality"], "It means to save effort or cost at the expense of quality."],
    ["मुहावरे 'to cut corners' का अर्थ है:", ["वर्ग का आकार बनाना", "तेज़ चलना", "स्वयं को चोट पहुँचाना", "गुणवत्ता की क़ीमत पर काम को सबसे आसान या सस्ते ढंग से करना"], "इसका अर्थ है गुणवत्ता की क़ीमत पर प्रयास या खर्च बचाना।"]),
  q(2, "english", "idioms", "M", 1,
    ["'To pull someone's leg' means to:", ["Hurt him", "Tease him playfully", "Help him walk", "Defeat him"], "The idiom means to joke with someone."],
    ["'To pull someone's leg' का अर्थ है:", ["उसे चोट पहुँचाना", "उसके साथ मज़ाक करना", "उसे चलने में मदद करना", "उसे हराना"], "इस मुहावरे का अर्थ है किसी से हँसी-मज़ाक करना।"]),
  q(2, "english", "one-word", "H", 2,
    ["Which single word means 'a person who is indifferent to pleasure and pain'?", ["Epicure", "Hedonist", "Stoic", "Cynic"], "A stoic bears pleasure and pain with calm."],
    ["'सुख-दुख के प्रति उदासीन व्यक्ति' के लिए एक शब्द कौन-सा है?", ["Epicure", "Hedonist", "Stoic", "Cynic"], "Stoic सुख-दुख को शांति से सहता है।"]),
  q(2, "english", "one-word", "M", 0,
    ["Which single word means 'a person who writes poetry'?", ["Poet", "Novelist", "Playwright", "Essayist"], "A poet writes poems."],
    ["'कविता लिखने वाला व्यक्ति' के लिए एक शब्द कौन-सा है?", ["Poet", "Novelist", "Playwright", "Essayist"], "Poet कविताएँ लिखता है।"]),
  q(2, "english", "one-word", "H", 1,
    ["Which single word means 'fit to be eaten'?", ["Edible", "Eligible", "Legible", "Audible"], "Edible means safe to eat."],
    ["'खाने योग्य' के लिए एक शब्द कौन-सा है?", ["Eligible", "Edible", "Legible", "Audible"], "Edible का अर्थ खाने के लिए सुरक्षित है।"]),
  q(2, "english", "spelling", "H", 3,
    ["Select the correct spelling of the noun meaning 'a gathering of friends or colleagues':", ["Acquaintence", "Aquaintance", "Acquaintanse", "Acquaintance"], "The word is acquaintance."],
    ["'मित्रों या सहकर्मियों के जमावड़े/परिचित' अर्थ वाले संज्ञा की सही वर्तनी चुनिए:", ["Acquaintence", "Aquaintance", "Acquaintanse", "Acquaintance"], "सही शब्द acquaintance है।"]),
  q(2, "english", "comprehension", "M", 2,
    ["In teaching English as a second language, the 'communicative approach' emphasises:", ["Rote translation", "Grammar drills only", "Using language for real communication", "Silent reading"], "It focuses on meaning and interaction."],
    ["अंग्रेज़ी को द्वितीय भाषा के रूप में पढ़ाने में 'संप्रेषणात्मक उपागम' किस पर बल देता है?", ["रटकर अनुवाद पर", "केवल व्याकरण अभ्यास पर", "वास्तविक संप्रेषण में भाषा-प्रयोग पर", "मौन पठन पर"], "यह अर्थ और अंतःक्रिया पर केंद्रित होता है।"]),
  q(2, "english", "comprehension", "H", 0,
    ["The 'grammar-translation method' of language teaching mainly relies on:", ["Translation and explicit grammar rules", "Free conversation", "Songs and games", "Immersion"], "It teaches the target language through translation and rules."],
    ["भाषा-शिक्षण की 'व्याकरण-अनुवाद विधि' मुख्यतः किस पर निर्भर करती है?", ["अनुवाद और स्पष्ट व्याकरणिक नियमों पर", "स्वतंत्र बातचीत पर", "गीतों और खेलों पर", "निमज्जन पर"], "यह लक्ष्य भाषा को अनुवाद और नियमों से सिखाती है।"]),
  q(2, "english", "comprehension", "M", 1,
    ["Which skill is the main aim of a 'role play' on 'at a railway station' in an English class?", ["Handwriting", "Speaking and interaction", "Spelling", "Copying"], "Role play gives practice in real-life speaking."],
    ["अंग्रेज़ी कक्षा में 'रेलवे स्टेशन पर' भूमिका-अभिनय का मुख्य उद्देश्य कौन-सा कौशल है?", ["लिखावट", "बोलना और अंतःक्रिया", "वर्तनी", "नक़ल करना"], "भूमिका-अभिनय वास्तविक जीवन में बोलने का अभ्यास कराता है।"]),
  q(2, "english", "grammar", "H", 2,
    ["Choose the sentence in which the verb is intransitive:", ["She wrote a letter.", "He broke the glass.", "The baby smiled.", "They built a house."], "'Smiled' takes no object."],
    ["वह वाक्य चुनिए जिसमें क्रिया अकर्मक (intransitive) है:", ["She wrote a letter.", "He broke the glass.", "The baby smiled.", "They built a house."], "'Smiled' का कोई कर्म नहीं है।"]),

  q(2, "english", "grammar", "H", 2,
    ["What is the plural of the noun 'criterion'?", ["Criterions", "Criterias", "Criteria", "Criterium"], "Criterion is a Greek-origin noun with the plural 'criteria'."],
    ["संज्ञा 'criterion' का बहुवचन क्या है?", ["Criterions", "Criterias", "Criteria", "Criterium"], "Criterion यूनानी मूल का शब्द है जिसका बहुवचन 'criteria' है।"]),
  q(2, "english", "synonyms-antonyms", "H", 1,
    ["Which word is nearest in meaning to 'MAGNANIMOUS'?", ["Petty", "Generous in forgiving", "Cruel", "Timid"], "Magnanimous means noble and generous, especially towards a rival."],
    ["'MAGNANIMOUS' के निकटतम अर्थ वाला शब्द कौन-सा है?", ["Petty", "Generous in forgiving", "Cruel", "Timid"], "Magnanimous का अर्थ उदार, विशेषकर प्रतिद्वंद्वी के प्रति, है।"]),
  q(2, "english", "grammar", "M", 0,
    ["Fill in the blank: 'Her elder sister is married ___ a doctor.'", ["to", "with", "by", "from"], "The phrase is 'married to'."],
    ["रिक्त स्थान भरिए: 'Her elder sister is married ___ a doctor.'", ["to", "with", "by", "from"], "सही प्रयोग 'married to' है।"]),

  // ───────── Section 3: History & Civics (30) ─────────
  q(3, "general-studies", "indian-history", "M", 0,
    ["The Harappan city of Mohenjo-daro is best known for its:", ["Great Bath", "Iron pillar", "Rock-cut caves", "Stupa"], "The Great Bath is a famous structure at Mohenjo-daro."],
    ["हड़प्पा नगर मोहनजोदड़ो किसके लिए सबसे अधिक प्रसिद्ध है?", ["विशाल स्नानागार", "लौह स्तंभ", "शैलकृत गुफाएँ", "स्तूप"], "विशाल स्नानागार मोहनजोदड़ो की प्रसिद्ध संरचना है।"]),
  q(3, "general-studies", "indian-history", "H", 2,
    ["Who was the founder of the Maurya dynasty?", ["Bindusara", "Ashoka", "Chandragupta Maurya", "Dasharatha"], "Chandragupta Maurya founded the dynasty about 321 BCE with Chanakya's help."],
    ["मौर्य वंश के संस्थापक कौन थे?", ["बिंदुसार", "अशोक", "चंद्रगुप्त मौर्य", "दशरथ"], "चंद्रगुप्त मौर्य ने चाणक्य की सहायता से लगभग 321 ई.पू. में वंश की स्थापना की।"]),
  q(3, "general-studies", "indian-history", "M", 1,
    ["The Gupta period is often called the 'Golden Age' mainly because of progress in:", ["Naval wars", "Art, science and literature", "Colonial trade", "Printing"], "Gupta rule saw advances in arts, mathematics and literature."],
    ["गुप्त काल को प्रायः 'स्वर्ण युग' मुख्यतः किस कारण कहा जाता है?", ["नौसैनिक युद्धों के", "कला, विज्ञान और साहित्य में प्रगति के", "औपनिवेशिक व्यापार के", "मुद्रण के"], "गुप्त काल में कला, गणित और साहित्य में उन्नति हुई।"]),
  q(3, "general-studies", "indian-history", "H", 3,
    ["The Chola kings are famous for their temple at Thanjavur, the:", ["Sun Temple", "Kailasa Temple", "Lingaraj Temple", "Brihadeeswara Temple"], "Rajaraja I built the Brihadeeswara Temple around 1010 CE."],
    ["चोल शासक तंजावुर के किस मंदिर के लिए प्रसिद्ध हैं?", ["सूर्य मंदिर", "कैलास मंदिर", "लिंगराज मंदिर", "बृहदेश्वर मंदिर"], "राजराज प्रथम ने लगभग 1010 ई. में बृहदेश्वर मंदिर बनवाया।"]),
  q(3, "general-studies", "indian-history", "M", 2,
    ["The first Sultan of the Delhi Sultanate (Slave dynasty) was:", ["Iltutmish", "Balban", "Qutb-ud-din Aibak", "Razia"], "Aibak became Sultan in 1206."],
    ["दिल्ली सल्तनत (ग़ुलाम वंश) का पहला सुल्तान कौन था?", ["इल्तुतमिश", "बलबन", "कुतुबुद्दीन ऐबक", "रज़िया"], "ऐबक 1206 में सुल्तान बना।"]),
  q(3, "general-studies", "indian-history", "H", 0,
    ["Which Sultan introduced the market-control measures and a permanent army with the 'dagh' (branding) system?", ["Alauddin Khalji", "Muhammad bin Tughlaq", "Firoz Shah Tughlaq", "Sikandar Lodi"], "Alauddin Khalji regulated markets and branded horses."],
    ["किस सुल्तान ने बाज़ार-नियंत्रण उपाय और 'दाग़' प्रथा के साथ स्थायी सेना की व्यवस्था लागू की?", ["अलाउद्दीन ख़िलजी", "मुहम्मद बिन तुग़लक़", "फ़िरोज़ शाह तुग़लक़", "सिकंदर लोदी"], "अलाउद्दीन ख़िलजी ने बाज़ार नियंत्रित किए और घोड़ों को दागा।"]),
  q(3, "general-studies", "indian-history", "M", 3,
    ["The Vijayanagara Empire, founded in 1336, had its capital at:", ["Bijapur", "Golconda", "Madurai", "Hampi"], "Harihara and Bukka founded it; Hampi was the capital."],
    ["1336 में स्थापित विजयनगर साम्राज्य की राजधानी कहाँ थी?", ["बीजापुर", "गोलकुंडा", "मदुरै", "हम्पी"], "हरिहर और बुक्का ने इसे स्थापित किया; हम्पी राजधानी थी।"]),
  q(3, "general-studies", "indian-history", "H", 1,
    ["Who wrote the 'Akbarnama'?", ["Badauni", "Abul Fazl", "Ferishta", "Amir Khusrau"], "Abul Fazl was Akbar's court historian."],
    ["'अकबरनामा' किसने लिखा?", ["बदायूँनी", "अबुल फ़ज़ल", "फ़रिश्ता", "अमीर ख़ुसरो"], "अबुल फ़ज़ल अकबर के दरबारी इतिहासकार थे।"]),
  q(3, "general-studies", "indian-history", "M", 2,
    ["The Battle of Haldighati (1576) was fought between Akbar's forces and:", ["Shivaji", "Rana Sanga", "Maharana Pratap", "Hemu"], "Maharana Pratap of Mewar resisted the Mughal army."],
    ["हल्दीघाटी का युद्ध (1576) अकबर की सेना और किसके बीच हुआ?", ["शिवाजी", "राणा सांगा", "महाराणा प्रताप", "हेमू"], "मेवाड़ के महाराणा प्रताप ने मुग़ल सेना का सामना किया।"]),
  q(3, "general-studies", "indian-history", "M", 0,
    ["Shivaji was crowned Chhatrapati at Raigad in:", ["1674", "1648", "1707", "1761"], "His coronation took place in 1674."],
    ["शिवाजी का छत्रपति के रूप में राज्याभिषेक रायगढ़ में कब हुआ?", ["1674", "1648", "1707", "1761"], "उनका राज्याभिषेक 1674 में हुआ।"]),
  q(3, "general-studies", "indian-history", "H", 3,
    ["In 1761 at Panipat, the Maratha army was defeated by the forces of:", ["The British", "The Sikhs", "The Mughals", "Ahmad Shah Abdali"], "Abdali defeated the Marathas in 1761."],
    ["पानीपत का तृतीय युद्ध (1761) मराठों और किसके बीच हुआ?", ["अंग्रेज़ों", "सिखों", "मुग़लों", "अहमद शाह अब्दाली"], "अब्दाली ने 1761 में मराठों को हराया।"]),
  q(3, "general-studies", "indian-history", "M", 1,
    ["The Revolt of 1857 began at which place?", ["Delhi", "Meerut", "Kanpur", "Jhansi"], "The sepoys at Meerut rose on 10 May 1857."],
    ["1857 का विद्रोह किस स्थान से शुरू हुआ?", ["दिल्ली", "मेरठ", "कानपुर", "झाँसी"], "मेरठ के सिपाहियों ने 10 मई 1857 को विद्रोह किया।"]),
  q(3, "general-studies", "indian-history", "H", 2,
    ["The Indian National Congress was founded in 1885 with the help of:", ["Lord Curzon", "Lord Ripon", "A. O. Hume", "Lord Dufferin as president"], "Allan Octavian Hume helped found the Congress."],
    ["1885 में भारतीय राष्ट्रीय कांग्रेस की स्थापना में किसने सहायता की?", ["लॉर्ड कर्ज़न", "लॉर्ड रिपन", "ए. ओ. ह्यूम", "लॉर्ड डफ़रिन (अध्यक्ष के रूप में)"], "ए. ओ. ह्यूम ने कांग्रेस की स्थापना में सहयोग किया।"]),
  q(3, "general-studies", "indian-history", "M", 3,
    ["The partition of Bengal, announced by Lord Curzon, took effect in:", ["1885", "1919", "1930", "1905"], "The partition was carried out in October 1905."],
    ["लॉर्ड कर्ज़न द्वारा घोषित बंगाल विभाजन किस वर्ष लागू हुआ?", ["1885", "1919", "1930", "1905"], "विभाजन अक्टूबर 1905 में लागू हुआ।"]),
  q(3, "general-studies", "indian-history", "M", 0,
    ["The Jallianwala Bagh massacre took place at which city in 1919?", ["Amritsar", "Lahore", "Delhi", "Ludhiana"], "General Dyer ordered the firing on 13 April 1919."],
    ["1919 में जलियाँवाला बाग हत्याकांड किस नगर में हुआ?", ["अमृतसर", "लाहौर", "दिल्ली", "लुधियाना"], "जनरल डायर ने 13 अप्रैल 1919 को गोली चलवाई।"]),
  q(3, "general-studies", "indian-history", "H", 1,
    ["Subhas Chandra Bose formed the Azad Hind Fauj (INA) in Southeast Asia in:", ["1939", "1943", "1946", "1930"], "He took command of the INA in 1943."],
    ["सुभाष चंद्र बोस ने दक्षिण-पूर्व एशिया में आज़ाद हिंद फ़ौज (आईएनए) का गठन कब किया?", ["1939", "1943", "1946", "1930"], "उन्होंने 1943 में आईएनए की कमान संभाली।"]),
  q(3, "general-studies", "indian-history", "M", 2,
    ["The Cabinet Mission Plan was sent to India in:", ["1930", "1935", "1946", "1950"], "The Cabinet Mission arrived in March 1946."],
    ["कैबिनेट मिशन भारत कब भेजा गया?", ["1930", "1935", "1946", "1950"], "कैबिनेट मिशन मार्च 1946 में आया।"]),
  q(3, "general-studies", "indian-history", "H", 0,
    ["Independent India's first Governor-General, before the Republic, was:", ["Lord Mountbatten", "C. Rajagopalachari", "Lord Wavell", "Rajendra Prasad"], "Mountbatten served until June 1948, then Rajaji."],
    ["स्वतंत्र भारत के प्रथम गवर्नर-जनरल कौन थे?", ["लॉर्ड माउंटबैटन", "सी. राजगोपालाचारी", "लॉर्ड वेवेल", "राजेंद्र प्रसाद"], "माउंटबैटन जून 1948 तक रहे, फिर राजाजी बने।"]),
  q(3, "general-studies", "indian-polity", "M", 2,
    ["The Constituent Assembly of India held its first meeting in:", ["1945", "1946", "1946 (December)", "1950"], "It first met on 9 December 1946."],
    ["भारत की संविधान सभा की पहली बैठक कब हुई?", ["1945", "1946 (अगस्त)", "1946 (दिसंबर)", "1950"], "इसकी पहली बैठक 9 दिसंबर 1946 को हुई।"]),
  q(3, "general-studies", "indian-polity", "M", 1,
    ["The Preamble of the Constitution begins with the words:", ["We, the Government of India", "We, the People of India", "In the name of God", "India, that is Bharat"], "It begins 'We, the People of India'."],
    ["संविधान की प्रस्तावना किन शब्दों से शुरू होती है?", ["हम, भारत की सरकार", "हम, भारत के लोग", "ईश्वर के नाम पर", "इंडिया, अर्थात् भारत"], "यह 'हम, भारत के लोग' से शुरू होती है।"]),
  q(3, "general-studies", "indian-polity", "H", 3,
    ["Which Article empowers the President to proclaim a National Emergency?", ["Article 352", "Article 356", "Article 360", "Article 368"], "Article 352 deals with national emergency; 356 with state emergency."],
    ["कौन-सा अनुच्छेद राष्ट्रपति को राष्ट्रीय आपातकाल की घोषणा की शक्ति देता है?", ["अनुच्छेद 352", "अनुच्छेद 356", "अनुच्छेद 360", "अनुच्छेद 368"], "अनुच्छेद 352 राष्ट्रीय आपातकाल से जुड़ा है; 356 राज्य आपातकाल से।"]),
  q(3, "general-studies", "indian-polity", "M", 0,
    ["The minimum age to become a member of the Lok Sabha is:", ["25 years", "21 years", "30 years", "35 years"], "A candidate must be at least 25."],
    ["लोकसभा का सदस्य बनने की न्यूनतम आयु है:", ["25 वर्ष", "21 वर्ष", "30 वर्ष", "35 वर्ष"], "उम्मीदवार की आयु कम से कम 25 वर्ष होनी चाहिए।"]),
  q(3, "general-studies", "indian-polity", "H", 1,
    ["The Supreme Court's power to issue writs for enforcing Fundamental Rights comes from Article:", ["Article 21", "Article 32", "Article 226", "Article 136"], "Article 32 is the 'heart and soul' of the Constitution (Ambedkar)."],
    ["मौलिक अधिकारों के प्रवर्तन के लिए रिट जारी करने की सर्वोच्च न्यायालय की शक्ति किस अनुच्छेद से आती है?", ["अनुच्छेद 21", "अनुच्छेद 32", "अनुच्छेद 226", "अनुच्छेद 136"], "अंबेडकर ने अनुच्छेद 32 को संविधान की 'आत्मा और हृदय' कहा।"]),
  q(3, "general-studies", "indian-polity", "M", 3,
    ["The Election Commission of India is a:", ["Statutory body only", "Temporary committee", "Part of the Lok Sabha", "Constitutional body"], "Article 324 establishes it."],
    ["भारत का निर्वाचन आयोग है:", ["केवल वैधानिक निकाय", "अस्थायी समिति", "लोकसभा का भाग", "संवैधानिक निकाय"], "अनुच्छेद 324 इसकी स्थापना करता है।"]),
  q(3, "general-studies", "indian-polity", "H", 2,
    ["The Right to Education was made a Fundamental Right through the:", ["42nd Amendment", "44th Amendment", "86th Amendment", "91st Amendment"], "The 86th Amendment, 2002, inserted Article 21A."],
    ["शिक्षा का अधिकार किस संशोधन द्वारा मौलिक अधिकार बनाया गया?", ["42वाँ संशोधन", "44वाँ संशोधन", "86वाँ संशोधन", "91वाँ संशोधन"], "86वें संशोधन, 2002, ने अनुच्छेद 21क जोड़ा।"]),
  q(3, "general-studies", "indian-polity", "M", 1,
    ["Under the Constitution, the Governor of an Indian state is appointed by the:", ["Chief Minister", "President", "Prime Minister", "Chief Justice"], "The President appoints the Governor."],
    ["भारत में राज्य के राज्यपाल की नियुक्ति कौन करता है?", ["मुख्यमंत्री", "राष्ट्रपति", "प्रधानमंत्री", "मुख्य न्यायाधीश"], "राज्यपाल की नियुक्ति राष्ट्रपति करता है।"]),
  q(3, "general-studies", "indian-polity", "M", 2,
    ["How many Schedules does the Constitution of India now have?", ["8", "10", "12", "14"], "There are 12 Schedules."],
    ["भारत के संविधान में वर्तमान में कितनी अनुसूचियाँ हैं?", ["8", "10", "12", "14"], "संविधान में 12 अनुसूचियाँ हैं।"]),
  q(3, "general-studies", "indian-polity", "H", 0,
    ["The concept of the 'Rule of Law' in the Indian Constitution has been borrowed from:", ["Britain", "USA", "Ireland", "Canada"], "The rule of law concept comes from British constitutional practice."],
    ["भारतीय संविधान में 'विधि के शासन' की अवधारणा किस देश से ली गई है?", ["ब्रिटेन", "अमेरिका", "आयरलैंड", "कनाडा"], "विधि के शासन की अवधारणा ब्रिटिश संवैधानिक व्यवहार से आई है।"]),

  q(3, "general-studies", "indian-history", "M", 3,
    ["Who founded the Khalsa Panth in 1699?", ["Guru Nanak", "Guru Arjan", "Guru Tegh Bahadur", "Guru Gobind Singh"], "Guru Gobind Singh created the Khalsa at Anandpur Sahib."],
    ["1699 में खालसा पंथ की स्थापना किसने की?", ["गुरु नानक", "गुरु अर्जन", "गुरु तेग बहादुर", "गुरु गोबिंद सिंह"], "गुरु गोबिंद सिंह ने आनंदपुर साहिब में खालसा की स्थापना की।"]),
  q(3, "general-studies", "indian-polity", "H", 1,
    ["Untouchability is abolished and its practice forbidden by which Article?", ["Article 15", "Article 17", "Article 19", "Article 21"], "Article 17 abolishes untouchability and forbids its practice."],
    ["संविधान का कौन-सा अनुच्छेद अस्पृश्यता का अंत करता है?", ["अनुच्छेद 15", "अनुच्छेद 17", "अनुच्छेद 19", "अनुच्छेद 21"], "अनुच्छेद 17 अस्पृश्यता का अंत करता है और उसके आचरण को निषिद्ध करता है।"]),

  // ───────── Section 4: Geography, Economics & Himachal GK (30) ─────────
  q(4, "general-studies", "indian-geography", "M", 1,
    ["The Western Ghats are also known in the south as the:", ["Aravalli", "Sahyadri", "Vindhya", "Satpura"], "In Maharashtra the Western Ghats are called the Sahyadri."],
    ["पश्चिमी घाट को दक्षिण-पश्चिम भारत में किस नाम से भी जाना जाता है?", ["अरावली", "सह्याद्रि", "विंध्य", "सतपुड़ा"], "महाराष्ट्र में पश्चिमी घाट को सह्याद्रि कहते हैं।"]),
  q(4, "general-studies", "indian-geography", "H", 3,
    ["The highest peak of the Western Ghats, Anamudi, is in:", ["Karnataka", "Tamil Nadu", "Maharashtra", "Kerala"], "Anamudi (2,695 m) is in the Anamalai hills of Kerala."],
    ["पश्चिमी घाट की सबसे ऊँची चोटी अनामुडी कहाँ है?", ["कर्नाटक", "तमिलनाडु", "महाराष्ट्र", "केरल"], "अनामुडी (2,695 मी) केरल की अन्नामलाई पहाड़ियों में है।"]),
  q(4, "general-studies", "indian-geography", "M", 0,
    ["The Thar Desert lies mainly in the state of:", ["Rajasthan", "Gujarat", "Haryana", "Punjab"], "The Great Indian Desert is mostly in Rajasthan."],
    ["थार मरुस्थल मुख्यतः किस राज्य में स्थित है?", ["राजस्थान", "गुजरात", "हरियाणा", "पंजाब"], "भारत का विशाल मरुस्थल अधिकांशतः राजस्थान में है।"]),
  q(4, "general-studies", "indian-geography", "H", 2,
    ["Which Indian river forms the world's largest river island, Majuli?", ["Ganga", "Mahanadi", "Brahmaputra", "Godavari"], "Majuli lies in the Brahmaputra in Assam."],
    ["विश्व का सबसे बड़ा नदी-द्वीप माजुली किस भारतीय नदी में बना है?", ["गंगा", "महानदी", "ब्रह्मपुत्र", "गोदावरी"], "माजुली असम में ब्रह्मपुत्र नदी में स्थित है।"]),
  q(4, "general-studies", "indian-geography", "M", 1,
    ["Which type of forest is found in the Sundarbans?", ["Tropical evergreen", "Mangrove", "Alpine", "Thorn"], "Sundarbans is the largest mangrove forest."],
    ["सुंदरबन में किस प्रकार के वन मिलते हैं?", ["उष्णकटिबंधीय सदाबहार", "मैंग्रोव", "अल्पाइन", "कँटीले"], "सुंदरबन सबसे बड़ा मैंग्रोव वन है।"]),
  q(4, "general-studies", "indian-geography", "M", 3,
    ["The 'Mawsynram' region, known for very heavy rainfall, is in:", ["Kerala", "Assam", "Odisha", "Meghalaya"], "Mawsynram in the Khasi Hills is among the wettest places on Earth."],
    ["अत्यधिक वर्षा के लिए प्रसिद्ध 'मौसिनराम' क्षेत्र कहाँ है?", ["केरल", "असम", "ओडिशा", "मेघालय"], "खासी पहाड़ियों में मौसिनराम पृथ्वी के सबसे नम स्थानों में है।"]),
  q(4, "general-studies", "indian-geography", "H", 0,
    ["The Equator passes through which of these continents and not the others? Choose the one it crosses:", ["Africa", "Europe", "Australia", "Antarctica"], "The Equator crosses Africa, South America and Asia (islands)."],
    ["इनमें से किस महाद्वीप से भूमध्य रेखा गुज़रती है?", ["अफ़्रीका", "यूरोप", "ऑस्ट्रेलिया", "अंटार्कटिका"], "भूमध्य रेखा अफ़्रीका, दक्षिण अमेरिका और एशिया (द्वीपों) से गुज़रती है।"]),
  q(4, "general-studies", "indian-geography", "M", 2,
    ["The longest river in the world by most measures is the:", ["Amazon", "Yangtze", "Nile", "Mississippi"], "The Nile is usually given as about 6,650 km."],
    ["अधिकांश मापों के अनुसार विश्व की सबसे लंबी नदी कौन-सी है?", ["अमेज़न", "यांग्त्ज़े", "नील", "मिसिसिपी"], "नील की लंबाई सामान्यतः लगभग 6,650 किमी बताई जाती है।"]),
  q(4, "general-studies", "indian-geography", "M", 1,
    ["The Deccan Plateau is mostly made of which kind of rock, giving black soil?", ["Limestone", "Basalt", "Sandstone", "Granite only"], "Weathering of Deccan basalt produces black soil."],
    ["दक्कन का पठार अधिकांशतः किस प्रकार की चट्टान से बना है, जिससे काली मिट्टी बनती है?", ["चूना पत्थर", "बेसाल्ट", "बलुआ पत्थर", "केवल ग्रेनाइट"], "दक्कन के बेसाल्ट के अपक्षय से काली मिट्टी बनती है।"]),
  q(4, "general-studies", "indian-geography", "H", 3,
    ["Choose the name of the channel that separates the Indian mainland from Sri Lanka:", ["Malacca Strait", "Bering Strait", "Strait of Hormuz", "Palk Strait"], "The Palk Strait lies between Tamil Nadu and Sri Lanka."],
    ["भारत को श्रीलंका से कौन-सी जलसंधि अलग करती है?", ["मलक्का जलसंधि", "बेरिंग जलसंधि", "होर्मुज़ जलसंधि", "पाक जलसंधि"], "पाक जलसंधि तमिलनाडु और श्रीलंका के बीच है।"]),
  q(4, "general-studies", "indian-geography", "M", 0,
    ["Which is the smallest continent by area?", ["Australia", "Europe", "Antarctica", "South America"], "Australia (Oceania) is the smallest continent."],
    ["क्षेत्रफल की दृष्टि से सबसे छोटा महाद्वीप कौन-सा है?", ["ऑस्ट्रेलिया", "यूरोप", "अंटार्कटिका", "दक्षिण अमेरिका"], "ऑस्ट्रेलिया (ओशिआनिया) सबसे छोटा महाद्वीप है।"]),
  q(4, "general-studies", "indian-geography", "M", 2,
    ["Which gas makes up most of the Earth's atmosphere?", ["Oxygen", "Hydrogen", "Nitrogen", "Argon"], "Nitrogen is about 78%."],
    ["पृथ्वी के वायुमंडल का अधिकांश भाग कौन-सी गैस है?", ["ऑक्सीजन", "हाइड्रोजन", "नाइट्रोजन", "आर्गन"], "नाइट्रोजन लगभग 78% है।"]),
  q(4, "general-studies", "indian-economy", "M", 3,
    ["GDP stands for:", ["General Domestic Profit", "Gross Domestic Price", "Government Development Plan", "Gross Domestic Product"], "GDP is the total value of goods and services produced in a country."],
    ["जीडीपी का पूर्ण रूप है:", ["जनरल डोमेस्टिक प्रॉफ़िट", "ग्रॉस डोमेस्टिक प्राइस", "गवर्नमेंट डेवलपमेंट प्लान", "सकल घरेलू उत्पाद"], "जीडीपी किसी देश में उत्पादित वस्तुओं और सेवाओं का कुल मूल्य है।"]),
  q(4, "general-studies", "indian-economy", "H", 1,
    ["Which institution issues currency notes of ₹2 and above in India (other than the one-rupee note)?", ["SBI", "Reserve Bank of India", "Finance Ministry", "NABARD"], "The RBI issues notes of ₹2 and above; the one-rupee note is issued by the Ministry of Finance."],
    ["भारत में ₹2 और उससे ऊपर के नोट (एक रुपये के नोट को छोड़कर) कौन-सी संस्था जारी करती है?", ["एसबीआई", "भारतीय रिज़र्व बैंक", "वित्त मंत्रालय", "नाबार्ड"], "₹2 और उससे ऊपर के नोट आरबीआई जारी करता है; एक रुपये का नोट वित्त मंत्रालय जारी करता है।"]),
  q(4, "general-studies", "indian-economy", "M", 0,
    ["Inflation means a sustained rise in the:", ["General price level", "Population", "Exports", "Interest on deposits only"], "Inflation is a continuing increase in prices."],
    ["मुद्रास्फीति का अर्थ किसमें निरंतर वृद्धि है?", ["सामान्य मूल्य-स्तर", "जनसंख्या", "निर्यात", "केवल जमा पर ब्याज"], "मुद्रास्फीति कीमतों में लगातार बढ़ोतरी है।"]),
  q(4, "general-studies", "indian-economy", "H", 2,
    ["India's first Five Year Plan (1951–56) gave the highest priority to:", ["Heavy industry", "Defence", "Agriculture and irrigation", "Foreign trade"], "The first plan, based on the Harrod–Domar model, stressed agriculture."],
    ["भारत की प्रथम पंचवर्षीय योजना (1951–56) ने सर्वाधिक प्राथमिकता किसे दी?", ["भारी उद्योग", "रक्षा", "कृषि और सिंचाई", "विदेशी व्यापार"], "हैरोड–डोमर मॉडल पर आधारित पहली योजना ने कृषि पर बल दिया।"]),
  q(4, "general-studies", "indian-economy", "M", 1,
    ["NABARD was set up in 1982 mainly to support:", ["Stock markets", "Agriculture and rural development", "Foreign trade", "Railways"], "NABARD is the apex bank for agriculture and rural credit."],
    ["नाबार्ड की स्थापना 1982 में मुख्यतः किसे सहयोग देने के लिए हुई?", ["शेयर बाज़ारों को", "कृषि और ग्रामीण विकास को", "विदेशी व्यापार को", "रेलवे को"], "नाबार्ड कृषि और ग्रामीण ऋण का शीर्ष बैंक है।"]),
  q(4, "general-studies", "indian-economy", "M", 3,
    ["The sector providing the largest share of India's GDP in recent years is the:", ["Agriculture sector", "Mining sector", "Manufacturing sector alone", "Services sector"], "Services contribute more than half of GDP."],
    ["हाल के वर्षों में भारत के जीडीपी में सबसे बड़ा हिस्सा किस क्षेत्र का है?", ["कृषि क्षेत्र", "खनन क्षेत्र", "केवल विनिर्माण क्षेत्र", "सेवा क्षेत्र"], "सेवाएँ जीडीपी में आधे से अधिक योगदान देती हैं।"]),
  q(4, "general-studies", "indian-economy", "H", 0,
    ["Which tax is levied by the Central Government on the income of individuals?", ["Income tax", "Property tax", "Road tax", "Entertainment tax"], "Income tax is a central levy."],
    ["व्यक्तियों की आय पर केंद्र सरकार कौन-सा कर लगाती है?", ["आयकर", "संपत्ति कर", "सड़क कर", "मनोरंजन कर"], "आयकर केंद्रीय कर है।"]),

  q(4, "hp-gk", "rivers-lakes", "M", 1,
    ["The Kullu valley, called the 'Valley of the Gods', lies on the banks of the river:", ["Satluj", "Beas", "Ravi", "Chenab"], "The Beas flows through the Kullu valley."],
    ["'देवताओं की घाटी' कही जाने वाली कुल्लू घाटी किस नदी के किनारे बसी है?", ["सतलुज", "ब्यास", "रावी", "चिनाब"], "कुल्लू घाटी में ब्यास नदी बहती है।"]),
  q(4, "hp-gk", "geography", "M", 0,
    ["The Dhauladhar range lies mainly in the district of:", ["Kangra", "Kinnaur", "Sirmaur", "Una"], "The Dhauladhar rises above Dharamshala in Kangra."],
    ["धौलाधार श्रेणी मुख्यतः किस ज़िले में स्थित है?", ["कांगड़ा", "किन्नौर", "सिरमौर", "ऊना"], "धौलाधार कांगड़ा में धर्मशाला के ऊपर उठी है।"]),
  q(4, "hp-gk", "geography", "H", 3,
    ["The Shivalik hills in Himachal Pradesh form which of the three main ranges of the Himalaya?", ["Himadri", "Himachal", "Trans-Himalaya", "Outer Himalaya"], "The Shivaliks are the outer Himalaya."],
    ["हिमाचल प्रदेश की शिवालिक पहाड़ियाँ हिमालय की तीन मुख्य श्रेणियों में से किसका भाग हैं?", ["हिमाद्रि", "हिमाचल", "ट्रांस-हिमालय", "बाह्य हिमालय"], "शिवालिक बाह्य हिमालय है।"]),
  q(4, "hp-gk", "rivers-lakes", "M", 1,
    ["The Chenab river is formed by the joining of the Chandra and Bhaga at:", ["Keylong", "Tandi", "Kaza", "Manali"], "The two streams meet at Tandi in Lahaul."],
    ["चंद्रा और भागा नदियाँ मिलकर चिनाब बनाती हैं। यह संगम कहाँ है?", ["केलांग", "तांदी", "काज़ा", "मनाली"], "दोनों धाराएँ लाहौल के तांदी में मिलती हैं।"]),
  q(4, "hp-gk", "culture-festivals", "M", 2,
    ["The Kullu Dussehra begins on the day when most of India's Dussehra celebrations:", ["Start", "Are being planned", "End", "Are cancelled"], "It starts on Vijayadashami, when Dussehra ends elsewhere."],
    ["कुल्लू दशहरा उस दिन शुरू होता है जब भारत के अधिकांश भागों में दशहरा उत्सव:", ["शुरू होते हैं", "योजनाबद्ध होते हैं", "समाप्त होते हैं", "रद्द होते हैं"], "यह विजयादशमी पर शुरू होता है, जब अन्यत्र दशहरा समाप्त होता है।"]),
  q(4, "hp-gk", "culture-festivals", "H", 1,
    ["The 'Chamba rumal', a famed craft, is a type of:", ["Wood carving", "Embroidery", "Stone carving", "Pottery"], "The Chamba rumal is a needlework craft of fine embroidery."],
    ["प्रसिद्ध शिल्प 'चंबा रूमाल' किस प्रकार का काम है?", ["काष्ठ-नक़्क़ाशी", "कढ़ाई", "पत्थर की नक़्क़ाशी", "मृदभांड"], "चंबा रूमाल महीन कढ़ाई का सुईकारी शिल्प है।"]),
  q(4, "hp-gk", "economy", "M", 3,
    ["Which district is the largest apple-producing district of Himachal Pradesh?", ["Una", "Bilaspur", "Hamirpur", "Shimla"], "Shimla district has the largest apple production."],
    ["हिमाचल प्रदेश का सबसे बड़ा सेब उत्पादक ज़िला कौन-सा है?", ["ऊना", "बिलासपुर", "हमीरपुर", "शिमला"], "शिमला ज़िले में सेब का उत्पादन सबसे अधिक है।"]),
  q(4, "hp-gk", "polity-administration", "M", 0,
    ["The High Court of Himachal Pradesh is at:", ["Shimla", "Dharamshala", "Mandi", "Solan"], "The HP High Court sits at Shimla."],
    ["हिमाचल प्रदेश उच्च न्यायालय कहाँ स्थित है?", ["शिमला", "धर्मशाला", "मंडी", "सोलन"], "हिमाचल उच्च न्यायालय शिमला में है।"]),
  q(4, "hp-gk", "culture-festivals", "H", 2,
    ["The famed Kangra school of miniature painting flourished especially under Raja Sansar Chand, ruler of:", ["Chamba", "Mandi", "Kangra", "Bilaspur"], "Sansar Chand Katoch patronised the Kangra Kalam in the late 18th century."],
    ["लघुचित्रों की प्रसिद्ध कांगड़ा शैली विशेष रूप से राजा संसार चंद के संरक्षण में फली-फूली। वे किस रियासत के शासक थे?", ["चंबा", "मंडी", "कांगड़ा", "बिलासपुर"], "संसार चंद कटोच ने 18वीं सदी के अंत में कांगड़ा कलम को संरक्षण दिया।"]),
  q(4, "hp-gk", "districts", "M", 1,
    ["Which district headquarters is known as the 'Chhoti Kashi' of Himachal Pradesh?", ["Kullu", "Mandi", "Chamba", "Solan"], "Mandi has many ancient temples and is called Chhoti Kashi."],
    ["हिमाचल प्रदेश में किस ज़िला मुख्यालय को 'छोटी काशी' कहा जाता है?", ["कुल्लू", "मंडी", "चंबा", "सोलन"], "मंडी में अनेक प्राचीन मंदिर हैं और इसे छोटी काशी कहा जाता है।"]),
  q(4, "hp-gk", "geography", "H", 1,
    ["Which pass links Lahaul with Ladakh along the Manali–Leh route?", ["Rohtang Pass", "Baralacha La", "Shipki La", "Jalori Pass"], "Baralacha La (4,890 m) lies between Lahaul and Ladakh."],
    ["मनाली–लेह मार्ग पर कौन-सा दर्रा लाहौल को लद्दाख से जोड़ता है?", ["रोहतांग दर्रा", "बारालाचा ला", "शिपकी ला", "जलोड़ी दर्रा"], "बारालाचा ला (4,890 मी) लाहौल और लद्दाख के बीच है।"]),
];
