// HP TET (TGT Arts) — Full Mock 2, written fresh: Child Development & Pedagogy 30, Hindi 30, English 30,
// History & Civics 30, Geography, Economics & Himachal GK 30 (sections as in ./index.ts).

import { q, type PatwariQuestion } from "../patwari/types";

export const artsMock2: PatwariQuestion[] = [
  // ───────── Section 0: Child Development & Pedagogy (30) ─────────
  q(0, "pedagogy", "child-development", "M", 1,
    ["According to Erikson, the central crisis of young adulthood is:", ["Identity versus role confusion", "Intimacy versus isolation", "Integrity versus despair", "Industry versus inferiority"], "Young adults seek close, committed relationships."],
    ["एरिक्सन के अनुसार युवावस्था का केंद्रीय संकट कौन-सा है?", ["पहचान बनाम भूमिका-भ्रम", "घनिष्ठता बनाम अलगाव", "सत्यनिष्ठा बनाम निराशा", "उद्यमिता बनाम हीनता"], "युवा गहरे, प्रतिबद्ध संबंध खोजते हैं।"]),
  q(0, "pedagogy", "child-development", "H", 2,
    ["A boy helps a classmate mainly because he wants to be seen as 'a good boy' by others. In Kohlberg's scheme this is:", ["Stage 1", "Stage 2", "Stage 3", "Stage 6"], "Stage 3 is the 'good boy–nice girl' orientation of the conventional level."],
    ["एक लड़का सहपाठी की मदद मुख्यतः इसलिए करता है कि दूसरे उसे 'अच्छा लड़का' समझें। कोहलबर्ग की योजना में यह है:", ["चरण 1", "चरण 2", "चरण 3", "चरण 6"], "चरण 3 परंपरागत स्तर का 'अच्छा लड़का–अच्छी लड़की' अभिविन्यास है।"]),
  q(0, "pedagogy", "child-development", "H", 0,
    ["Conformity to peer-group norms is generally strongest in:", ["Early adolescence", "Infancy", "Old age", "Middle childhood only"], "Susceptibility to peer influence rises in early adolescence."],
    ["साथी-समूह के मानकों के अनुरूप चलने की प्रवृत्ति सामान्यतः किस काल में सबसे प्रबल होती है?", ["प्रारंभिक किशोरावस्था में", "शैशवावस्था में", "वृद्धावस्था में", "केवल मध्य बाल्यावस्था में"], "साथियों के प्रभाव की संवेदनशीलता प्रारंभिक किशोरावस्था में बढ़ती है।"]),
  q(0, "pedagogy", "child-development", "H", 3,
    ["The James–Lange theory of emotion holds that:", ["Emotion comes before any body change", "Emotion and body change never occur together", "Thoughts alone create emotion", "We feel an emotion after perceiving our bodily response"], "We feel afraid because we tremble, not the reverse."],
    ["संवेग का जेम्स–लांगे सिद्धांत मानता है कि:", ["संवेग किसी भी शारीरिक परिवर्तन से पहले आता है", "संवेग और शारीरिक परिवर्तन कभी साथ नहीं होते", "केवल विचार संवेग पैदा करते हैं", "हम अपनी शारीरिक प्रतिक्रिया को देखने के बाद संवेग अनुभव करते हैं"], "हम काँपते हैं इसलिए डरते हैं, इसका उलटा नहीं।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["In Bandura's observational learning, which set lists the four processes correctly?", ["Perception, reward, punishment, rest", "Attention, retention, reproduction, motivation", "Sensation, memory, speech, action", "Trial, error, success, repetition"], "The four processes are attention, retention, reproduction and motivation."],
    ["बंडूरा के अवलोकनात्मक अधिगम में चार प्रक्रियाओं की सही सूची कौन-सी है?", ["प्रत्यक्षण, पुरस्कार, दंड, विश्राम", "ध्यान, धारण, पुनरुत्पादन, अभिप्रेरणा", "संवेदना, स्मृति, वाणी, क्रिया", "प्रयास, त्रुटि, सफलता, पुनरावृत्ति"], "चार प्रक्रियाएँ हैं ध्यान, धारण, पुनरुत्पादन और अभिप्रेरणा।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["In Maslow's hierarchy, the need that comes immediately after esteem needs is:", ["Safety", "Love and belonging", "Physiological", "Self-actualisation"], "Self-actualisation is at the top, above esteem."],
    ["मैस्लो के पदानुक्रम में सम्मान की आवश्यकताओं के ठीक बाद कौन-सी आवश्यकता आती है?", ["सुरक्षा", "प्रेम और संबद्धता", "शारीरिक", "आत्म-सिद्धि"], "आत्म-सिद्धि शीर्ष पर है, सम्मान से ऊपर।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["When a child who enjoyed drawing loses interest after being paid for every drawing, psychologists call this the:", ["Halo effect", "Pygmalion effect", "Overjustification effect", "Placebo effect"], "Excessive external reward can reduce intrinsic motivation."],
    ["जब चित्रकारी में आनंद लेने वाला बच्चा हर चित्र पर पैसे मिलने के बाद रुचि खो देता है, तो मनोवैज्ञानिक इसे क्या कहते हैं?", ["हेलो प्रभाव", "पिग्मैलियन प्रभाव", "अति-औचित्य प्रभाव", "प्लेसीबो प्रभाव"], "अत्यधिक बाह्य पुरस्कार आंतरिक अभिप्रेरणा को घटा सकता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["The Atkinson–Shiffrin model describes memory as passing through:", ["Sensory, short-term and long-term stores", "Only one store", "Three languages", "Four senses"], "Information moves from the sensory register to short-term and then long-term memory."],
    ["एटकिंसन–शिफ़्रिन मॉडल स्मृति को किन चरणों से गुज़रता बताता है?", ["संवेदी, अल्पकालिक और दीर्घकालिक भंडार", "केवल एक भंडार", "तीन भाषाएँ", "चार इंद्रियाँ"], "सूचना संवेदी रजिस्टर से अल्पकालिक और फिर दीर्घकालिक स्मृति में जाती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["According to George Miller, the capacity of short-term memory is about:", ["2 items", "4 items", "7 ± 2 items", "20 items"], "Miller's 'magical number seven, plus or minus two'."],
    ["जॉर्ज मिलर के अनुसार अल्पकालिक स्मृति की क्षमता लगभग कितनी होती है?", ["2 मद", "4 मद", "7 ± 2 मद", "20 मद"], "मिलर की 'जादुई संख्या सात, घटा-बढ़ाकर दो'।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["Grouping a phone number as 98-1234-5678 helps memory through:", ["Rote repetition only", "Chunking", "Extinction", "Imprinting"], "Chunking combines items into larger meaningful units."],
    ["फ़ोन नंबर को 98-1234-5678 के समूहों में बाँटना स्मृति में किस प्रक्रिया से मदद करता है?", ["केवल रटकर दोहराने से", "खंडीकरण (चंकिंग)", "विलोपन", "छापन"], "खंडीकरण मदों को बड़ी अर्थपूर्ण इकाइयों में जोड़ता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["Learning a new phone number makes it harder to recall the old one. This forgetting is due to:", ["Proactive inhibition", "Decay only", "Repression", "Retroactive inhibition"], "New learning interfering with older memories is retroactive inhibition."],
    ["नया फ़ोन नंबर सीखने से पुराना नंबर याद करना कठिन हो जाता है। यह विस्मरण किसके कारण है?", ["अग्रोन्मुख अवरोध", "केवल क्षय", "दमन", "पश्चोन्मुख अवरोध"], "नया सीखना पुरानी स्मृतियों में बाधा डाले तो वह पश्चोन्मुख अवरोध है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["A mental shortcut or rule of thumb used in problem solving is called a:", ["Heuristic", "Algorithm", "Reflex", "Schema"], "A heuristic is a quick, not always exact, strategy."],
    ["समस्या-समाधान में प्रयुक्त मानसिक शॉर्टकट या अनुमान-नियम को क्या कहते हैं?", ["अनुमानी (ह्यूरिस्टिक)", "एल्गोरिद्म", "प्रतिवर्त", "स्कीमा"], "ह्यूरिस्टिक एक त्वरित, पर सदैव सटीक नहीं, युक्ति है।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["The term 'metacognition', meaning awareness and control of one's own thinking, was introduced by:", ["Piaget", "John Flavell", "Skinner", "Gardner"], "Flavell coined the term in the 1970s."],
    ["'मेटाकॉग्निशन', यानी अपने चिंतन की जागरूकता और नियंत्रण, शब्द किसने दिया?", ["पियाजे", "जॉन फ़्लेवेल", "स्किनर", "गार्डनर"], "फ़्लेवेल ने 1970 के दशक में यह शब्द गढ़ा।"]),
  q(0, "pedagogy", "child-development", "H", 2,
    ["Learners who find it hard to separate a figure from its background and prefer group settings are called, in Witkin's terms:", ["Field-independent", "Reflective", "Field-dependent", "Convergent"], "Field-dependent learners are influenced by the surrounding context."],
    ["जो शिक्षार्थी आकृति को उसकी पृष्ठभूमि से अलग करने में कठिनाई पाते हैं और समूह परिवेश पसंद करते हैं, उन्हें विटकिन की भाषा में क्या कहते हैं?", ["क्षेत्र-स्वतंत्र", "चिंतनशील", "क्षेत्र-निर्भर", "अभिसारी"], "क्षेत्र-निर्भर शिक्षार्थी आसपास के संदर्भ से प्रभावित होते हैं।"]),
  q(0, "pedagogy", "inclusive-education", "M", 3,
    ["Which of these is listed as a specific learning disability under the RPwD Act, 2016?", ["Asthma", "Obesity", "Short height", "Dyslexia"], "The Act lists dyslexia, dysgraphia, dyscalculia and dyspraxia."],
    ["दिव्यांगजन अधिकार अधिनियम 2016 में विशिष्ट अधिगम अक्षमता के रूप में इनमें से क्या सूचीबद्ध है?", ["दमा", "मोटापा", "छोटा कद", "डिस्लेक्सिया"], "अधिनियम में डिस्लेक्सिया, डिस्ग्राफ़िया, डिस्कैल्कुलिया और डिस्प्रैक्सिया सूचीबद्ध हैं।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["The 1993 report 'Learning Without Burden' was prepared by a committee chaired by:", ["Yash Pal", "D. S. Kothari", "S. Radhakrishnan", "Acharya Ramamurti"], "The Yash Pal Committee urged less rote learning and curriculum load."],
    ["1993 की रिपोर्ट 'बिना बोझ के शिक्षा' किस समिति ने तैयार की, जिसके अध्यक्ष थे:", ["यशपाल", "डी. एस. कोठारी", "एस. राधाकृष्णन", "आचार्य राममूर्ति"], "यशपाल समिति ने रटंत और पाठ्यक्रम-बोझ घटाने की बात कही।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["NEP 2020 describes the 'Foundational Stage' of school education as covering the ages of:", ["2 to 4", "3 to 8", "6 to 11", "11 to 14"], "The 5-year foundational stage covers ages 3 to 8."],
    ["एनईपी 2020 विद्यालयी शिक्षा के 'आधारभूत चरण' को किस आयु-वर्ग का बताती है?", ["2 से 4", "3 से 8", "6 से 11", "11 से 14"], "5 वर्ष का आधारभूत चरण 3 से 8 वर्ष की आयु को समेटता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["NEP 2020 proposes a '360-degree, multidimensional' report card to record:", ["Only marks in exams", "Attendance alone", "Holistic progress of the learner", "Teacher's salary"], "The holistic progress card covers cognitive, social and emotional growth."],
    ["एनईपी 2020 '360 डिग्री, बहुआयामी' प्रगति-पत्र किसे दर्ज करने के लिए प्रस्तावित करती है?", ["केवल परीक्षा के अंक", "केवल उपस्थिति", "शिक्षार्थी की समग्र प्रगति", "शिक्षक का वेतन"], "समग्र प्रगति-पत्र संज्ञानात्मक, सामाजिक और भावनात्मक विकास को दर्ज करता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["NEP 2020 recommends that vocational education and internships begin from:", ["Class 6", "Class 1", "Class 11 only", "College"], "Students are to get exposure to vocational skills from Class 6."],
    ["एनईपी 2020 की अनुशंसा है कि व्यावसायिक शिक्षा और इंटर्नशिप किस कक्षा से शुरू हो?", ["कक्षा 6", "कक्षा 1", "केवल कक्षा 11", "महाविद्यालय"], "विद्यार्थियों को कक्षा 6 से व्यावसायिक कौशलों का अनुभव मिलना है।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["PARAKH, proposed under NEP 2020, is a national centre for:", ["Teacher recruitment", "School construction", "Mid-day meals", "Assessment, review and analysis of holistic development"], "PARAKH is a standard-setting body for assessment."],
    ["एनईपी 2020 के अंतर्गत प्रस्तावित 'परख' किसका राष्ट्रीय केंद्र है?", ["शिक्षक भर्ती का", "विद्यालय निर्माण का", "मध्याह्न भोजन का", "समग्र विकास के मूल्यांकन, समीक्षा और विश्लेषण का"], "परख मूल्यांकन के मानक तय करने वाली संस्था है।"]),
  q(0, "pedagogy", "inclusive-education", "M", 2,
    ["Samagra Shiksha treats school education as a continuum from:", ["Class 1 to 5", "Class 6 to 8", "Pre-school to Class 12", "Class 9 to 12"], "It covers pre-school to senior secondary."],
    ["समग्र शिक्षा विद्यालयी शिक्षा को किस सातत्य के रूप में देखती है?", ["कक्षा 1 से 5", "कक्षा 6 से 8", "पूर्व-विद्यालय से कक्षा 12 तक", "कक्षा 9 से 12"], "यह पूर्व-विद्यालय से वरिष्ठ माध्यमिक तक को समेटती है।"]),
  q(0, "pedagogy", "inclusive-education", "H", 1,
    ["The PM SHRI scheme, launched in 2022, aims to develop:", ["New universities", "Model, exemplar schools across the country", "Private coaching centres", "Sports stadiums only"], "PM SHRI schools showcase the NEP 2020 vision."],
    ["2022 में शुरू की गई पीएम श्री योजना का उद्देश्य किसे विकसित करना है?", ["नए विश्वविद्यालय", "देश भर में आदर्श, अनुकरणीय विद्यालय", "निजी कोचिंग केंद्र", "केवल क्रीड़ा स्टेडियम"], "पीएम श्री विद्यालय एनईपी 2020 की दृष्टि को दर्शाते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["DIKSHA is a national platform for:", ["Banking", "Railway booking", "Tax filing", "School education e-content"], "DIKSHA offers digital content for learners and teachers."],
    ["दीक्षा (DIKSHA) किसके लिए राष्ट्रीय मंच है?", ["बैंकिंग", "रेलवे आरक्षण", "कर-विवरणी", "विद्यालयी शिक्षा की ई-सामग्री"], "दीक्षा शिक्षार्थियों और शिक्षकों के लिए डिजिटल सामग्री देता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["A chief limitation of the pure lecture method is that it:", ["Makes pupils passive listeners", "Is too interactive", "Needs no preparation", "Always involves games"], "It gives little room for pupil participation."],
    ["शुद्ध व्याख्यान विधि की एक प्रमुख सीमा यह है कि वह:", ["विद्यार्थियों को निष्क्रिय श्रोता बना देती है", "बहुत अधिक अंतःक्रियात्मक है", "किसी तैयारी की माँग नहीं करती", "सदा खेलों पर आधारित होती है"], "इसमें विद्यार्थियों की भागीदारी के लिए कम अवसर होते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["Which method is considered most suitable for teaching a science concept through a live experiment in front of the class?", ["Dictation", "Demonstration", "Recitation", "Story telling only"], "Demonstration shows the process to the whole class."],
    ["पूरी कक्षा के सामने जीवंत प्रयोग द्वारा विज्ञान की संकल्पना पढ़ाने के लिए कौन-सी विधि सबसे उपयुक्त मानी जाती है?", ["श्रुतलेख", "प्रदर्शन", "सस्वर पाठ", "केवल कथा-वाचन"], "प्रदर्शन पूरी कक्षा को प्रक्रिया दिखाता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["The Socratic method of teaching relies mainly on:", ["Long notes", "Punishment", "Questioning and dialogue", "Silent copying"], "Socrates taught through a series of guiding questions."],
    ["शिक्षण की सुकराती विधि मुख्यतः किस पर निर्भर करती है?", ["लंबे नोट्स", "दंड", "प्रश्नोत्तर और संवाद", "मौन नक़ल"], "सुकरात मार्गदर्शक प्रश्नों की श्रृंखला से पढ़ाते थे।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["In team teaching, a lesson is planned and delivered by:", ["One teacher always", "Pupils alone", "Visitors only", "Two or more teachers working together"], "Teachers share planning and presentation."],
    ["सामूहिक शिक्षण (टीम टीचिंग) में पाठ की योजना और प्रस्तुति कौन करता है?", ["हमेशा एक शिक्षक", "केवल विद्यार्थी", "केवल आगंतुक", "दो या अधिक शिक्षक मिलकर"], "शिक्षक योजना और प्रस्तुति साझा करते हैं।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["Edgar Dale's 'Cone of Experience' ranks teaching experiences from:", ["Direct, purposeful experiences to verbal symbols", "Easy to hard exams", "Young to old pupils", "Short to long lessons"], "The cone moves from concrete experiences to abstract symbols."],
    ["एडगर डेल का 'अनुभव का शंकु' शिक्षण-अनुभवों को किस क्रम में रखता है?", ["प्रत्यक्ष, उद्देश्यपूर्ण अनुभवों से शाब्दिक प्रतीकों तक", "सरल से कठिन परीक्षाओं तक", "छोटे से बड़े विद्यार्थियों तक", "छोटे से लंबे पाठों तक"], "शंकु मूर्त अनुभवों से अमूर्त प्रतीकों की ओर बढ़ता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["An 'exit ticket', a brief response pupils give before leaving class, is a tool of:", ["Summative testing", "Formative assessment", "Admission testing", "Rank listing"], "It tells the teacher what pupils understood."],
    ["'एग्ज़िट टिकट', जिसमें विद्यार्थी कक्षा छोड़ने से पहले संक्षिप्त प्रतिक्रिया देते हैं, किसका साधन है?", ["योगात्मक परीक्षण", "रचनात्मक मूल्यांकन", "प्रवेश परीक्षण", "क्रम-सूची"], "इससे शिक्षक को पता चलता है कि विद्यार्थियों ने क्या समझा।"]),
  q(0, "pedagogy", "child-development", "M", 2,
    ["Which quality of a teacher most helps in building a trusting relationship with adolescent students?", ["Strictness only", "Distance", "Empathy and respect", "Sarcasm"], "Adolescents respond to being understood and respected."],
    ["किशोर विद्यार्थियों के साथ विश्वासपूर्ण संबंध बनाने में शिक्षक का कौन-सा गुण सबसे अधिक सहायक है?", ["केवल कठोरता", "दूरी", "सहानुभूति और सम्मान", "व्यंग्य"], "किशोर समझे और सम्मानित किए जाने पर अनुकूल प्रतिक्रिया देते हैं।"]),

  // ───────── Section 1: Hindi (30) ─────────
  q(1, "hindi", "sahitya", "M", 0,
    ["'राम की शक्तिपूजा' is a famous long poem by:", ["निराला", "प्रसाद", "बच्चन", "दिनकर"], "Nirala wrote Ram ki Shaktipuja in 1936."],
    ["'राम की शक्तिपूजा' किसकी प्रसिद्ध लंबी कविता है?", ["निराला", "प्रसाद", "बच्चन", "दिनकर"], "निराला ने 1936 में राम की शक्तिपूजा लिखी।"]),
  q(1, "hindi", "sahitya", "M", 2,
    ["'रश्मिरथी', a Khand-kavya about Karna, was written by:", ["मैथिलीशरण गुप्त", "सुभद्राकुमारी चौहान", "रामधारी सिंह 'दिनकर'", "अज्ञेय"], "Dinkar's Rashmirathi (1952) retells Karna's life."],
    ["कर्ण पर आधारित खंडकाव्य 'रश्मिरथी' किसने लिखा?", ["मैथिलीशरण गुप्त", "सुभद्राकुमारी चौहान", "रामधारी सिंह 'दिनकर'", "अज्ञेय"], "दिनकर की रश्मिरथी (1952) कर्ण के जीवन को फिर से कहती है।"]),
  q(1, "hindi", "sahitya", "H", 3,
    ["The novel 'तमस', based on the Partition riots, was written by:", ["यशपाल", "अमृतलाल नागर", "राही मासूम रज़ा", "भीष्म साहनी"], "Bhisham Sahni's Tamas (1973) won the Sahitya Akademi Award."],
    ["विभाजन के दंगों पर आधारित उपन्यास 'तमस' किसने लिखा?", ["यशपाल", "अमृतलाल नागर", "राही मासूम रज़ा", "भीष्म साहनी"], "भीष्म साहनी के तमस (1973) को साहित्य अकादमी पुरस्कार मिला।"]),
  q(1, "hindi", "sahitya", "M", 1,
    ["'पूस की रात' is a well-known short story by:", ["जैनेंद्र", "प्रेमचंद", "अज्ञेय", "फणीश्वरनाथ रेणु"], "Premchand's story shows a poor farmer, Halku."],
    ["'पूस की रात' किसकी प्रसिद्ध कहानी है?", ["जैनेंद्र", "प्रेमचंद", "अज्ञेय", "फणीश्वरनाथ रेणु"], "प्रेमचंद की इस कहानी में निर्धन किसान हल्कू का चित्रण है।"]),
  q(1, "hindi", "sahitya", "H", 0,
    ["'साकेत', an epic centred on Urmila's suffering, is by:", ["मैथिलीशरण गुप्त", "जयशंकर प्रसाद", "माखनलाल चतुर्वेदी", "पंत"], "Maithili Sharan Gupt wrote Saket (1932)."],
    ["उर्मिला की व्यथा पर केंद्रित महाकाव्य 'साकेत' किसकी रचना है?", ["मैथिलीशरण गुप्त", "जयशंकर प्रसाद", "माखनलाल चतुर्वेदी", "पंत"], "मैथिलीशरण गुप्त ने 1932 में साकेत लिखा।"]),
  q(1, "hindi", "sahitya", "H", 2,
    ["'तार सप्तक' (1943), which began the Prayogvad movement in Hindi poetry, was edited by:", ["दिनकर", "नागार्जुन", "अज्ञेय", "बच्चन"], "Agyeya edited Tar Saptak."],
    ["'तार सप्तक' (1943), जिसने हिंदी कविता में प्रयोगवाद की शुरुआत की, का संपादन किसने किया?", ["दिनकर", "नागार्जुन", "अज्ञेय", "बच्चन"], "अज्ञेय ने तार सप्तक का संपादन किया।"]),
  q(1, "hindi", "sahitya", "H", 1,
    ["Bihari's famous 'सतसई' belongs to which period of Hindi literature?", ["आदिकाल", "रीतिकाल", "भक्तिकाल", "आधुनिक काल"], "Bihari Satsai is a landmark of the Reeti period."],
    ["बिहारी की प्रसिद्ध 'सतसई' हिंदी साहित्य के किस काल की है?", ["आदिकाल", "रीतिकाल", "भक्तिकाल", "आधुनिक काल"], "बिहारी सतसई रीतिकाल की उल्लेखनीय कृति है।"]),
  q(1, "hindi", "sahitya", "M", 3,
    ["'बीजक', the collection of sayings of a saint-poet, is associated with:", ["सूरदास", "तुलसीदास", "रैदास", "कबीर"], "Bijak is the main compilation of Kabir's sayings."],
    ["संत-कवि की वाणियों का संग्रह 'बीजक' किससे संबद्ध है?", ["सूरदास", "तुलसीदास", "रैदास", "कबीर"], "बीजक कबीर की वाणियों का मुख्य संकलन है।"]),
  q(1, "hindi", "sandhi-samas", "M", 1,
    ["Split the word 'विद्यार्थी' into sandhi parts:", ["विद्या + र्थी", "विद्या + अर्थी", "विद् + यार्थी", "विद्य + अर्थी"], "आ + अ = आ (dirgha sandhi): विद्या + अर्थी."],
    ["'विद्यार्थी' का संधि-विच्छेद कीजिए:", ["विद्या + र्थी", "विद्या + अर्थी", "विद् + यार्थी", "विद्य + अर्थी"], "आ + अ = आ (दीर्घ संधि): विद्या + अर्थी।"]),
  q(1, "hindi", "sandhi-samas", "H", 3,
    ["Split the word 'उन्नति' into sandhi parts:", ["उन + नति", "उ + न्नति", "उन् + अति", "उत् + नति"], "त् before न becomes न्: उत् + नति = उन्नति."],
    ["'उन्नति' का संधि-विच्छेद कीजिए:", ["उन + नति", "उ + न्नति", "उन् + अति", "उत् + नति"], "न से पहले त् का न् हो जाता है: उत् + नति = उन्नति।"]),
  q(1, "hindi", "sandhi-samas", "M", 2,
    ["Split the word 'गणेश' into sandhi parts:", ["गण + ईश", "गणा + ईश", "गण + इश", "गणे + श"], "अ + ई = ए (gun sandhi): गण + ईश."],
    ["'गणेश' का संधि-विच्छेद कीजिए:", ["गण + ईश", "गणा + ईश", "गण + इश", "गणे + श"], "अ + ई = ए (गुण संधि): गण + ईश।"]),
  q(1, "hindi", "sandhi-samas", "M", 0,
    ["'चरणकमल' (कमल के समान चरण) is an example of:", ["कर्मधारय समास", "द्वंद्व समास", "द्विगु समास", "अव्ययीभाव समास"], "A comparison between the two parts: karmadharay."],
    ["'चरणकमल' (कमल के समान चरण) किसका उदाहरण है?", ["कर्मधारय समास", "द्वंद्व समास", "द्विगु समास", "अव्ययीभाव समास"], "दोनों पदों में उपमान-उपमेय संबंध है: कर्मधारय।"]),
  q(1, "hindi", "sandhi-samas", "H", 3,
    ["'चतुर्भुज' (चार हैं भुजाएँ जिसकी, अर्थात् विष्णु) is an example of:", ["द्विगु समास", "तत्पुरुष समास", "कर्मधारय समास", "बहुव्रीहि समास"], "When the meaning points to Vishnu, a third entity, it is bahuvrihi."],
    ["'चतुर्भुज' (चार हैं भुजाएँ जिसकी, अर्थात् विष्णु) किसका उदाहरण है?", ["द्विगु समास", "तत्पुरुष समास", "कर्मधारय समास", "बहुव्रीहि समास"], "अर्थ विष्णु, तीसरे व्यक्ति, की ओर संकेत करे तो बहुव्रीहि समास होता है।"]),
  q(1, "hindi", "paryay-vilom", "M", 2,
    ["Choose the synonym of 'वृक्ष':", ["लता", "पुष्प", "तरु", "घास"], "वृक्ष, तरु and पादप mean tree."],
    ["'वृक्ष' का पर्यायवाची चुनिए:", ["लता", "पुष्प", "तरु", "घास"], "वृक्ष, तरु और पादप का अर्थ पेड़ है।"]),
  q(1, "hindi", "paryay-vilom", "M", 1,
    ["Choose the synonym of 'विद्युत':", ["मेघ", "बिजली", "वर्षा", "आँधी"], "विद्युत, तड़ित and दामिनी mean lightning."],
    ["'विद्युत' का पर्यायवाची चुनिए:", ["मेघ", "बिजली", "वर्षा", "आँधी"], "विद्युत, तड़ित और दामिनी का अर्थ बिजली है।"]),
  q(1, "hindi", "paryay-vilom", "H", 0,
    ["Choose the antonym of 'आदि':", ["अंत", "प्रारंभ", "मूल", "शुरू"], "आदि means beginning; अंत means end."],
    ["'आदि' का विलोम चुनिए:", ["अंत", "प्रारंभ", "मूल", "शुरू"], "आदि का अर्थ आरंभ है; अंत का अर्थ समाप्ति है।"]),
  q(1, "hindi", "paryay-vilom", "M", 3,
    ["Choose the antonym of 'लाभ':", ["फ़ायदा", "प्राप्ति", "मुनाफ़ा", "हानि"], "लाभ is profit; हानि is loss."],
    ["'लाभ' का विलोम चुनिए:", ["फ़ायदा", "प्राप्ति", "मुनाफ़ा", "हानि"], "लाभ का अर्थ फ़ायदा है; हानि का अर्थ नुकसान है।"]),
  q(1, "hindi", "ek-shabd", "M", 1,
    ["Which single word means 'जो अपने देश से प्रेम करे'?", ["विदेशी", "देशभक्त", "देशद्रोही", "प्रवासी"], "देशभक्त loves his country."],
    ["'जो अपने देश से प्रेम करे' के लिए एक शब्द कौन-सा है?", ["विदेशी", "देशभक्त", "देशद्रोही", "प्रवासी"], "देशभक्त अपने देश से प्रेम करता है।"]),
  q(1, "hindi", "ek-shabd", "H", 2,
    ["Which single word means 'जो कुछ भी न जानता हो'?", ["सर्वज्ञ", "अल्पज्ञ", "अज्ञ", "विज्ञ"], "अज्ञ knows nothing."],
    ["'जो कुछ भी न जानता हो' के लिए एक शब्द कौन-सा है?", ["सर्वज्ञ", "अल्पज्ञ", "अज्ञ", "विज्ञ"], "अज्ञ कुछ नहीं जानता।"]),
  q(1, "hindi", "ek-shabd", "M", 0,
    ["Which single word means 'जिसमें दया न हो'?", ["निर्दय", "दयालु", "कृपालु", "उदार"], "निर्दय is merciless."],
    ["'जिसमें दया न हो' के लिए एक शब्द कौन-सा है?", ["निर्दय", "दयालु", "कृपालु", "उदार"], "निर्दय का अर्थ दयाहीन है।"]),
  q(1, "hindi", "muhavare", "M", 3,
    ["Meaning of the idiom 'आग में घी डालना':", ["खाना पकाना", "रोशनी करना", "सेवा करना", "क्रोध को और भड़काना"], "The idiom means to make an angry situation worse."],
    ["मुहावरे 'आग में घी डालना' का अर्थ है:", ["खाना पकाना", "रोशनी करना", "सेवा करना", "क्रोध को और भड़काना"], "इस मुहावरे का अर्थ है बिगड़ी स्थिति को और बिगाड़ना।"]),
  q(1, "hindi", "muhavare", "H", 0,
    ["Meaning of the proverb 'ऊँची दुकान फीका पकवान':", ["बाहरी दिखावा अधिक पर वास्तविकता कम", "दुकान ऊँची होना", "पकवान महँगा होना", "स्वादिष्ट भोजन"], "Big show, little substance."],
    ["लोकोक्ति 'ऊँची दुकान फीका पकवान' का अर्थ है:", ["बाहरी दिखावा अधिक पर वास्तविकता कम", "दुकान ऊँची होना", "पकवान महँगा होना", "स्वादिष्ट भोजन"], "दिखावा बड़ा, सार थोड़ा।"]),
  q(1, "hindi", "muhavare", "M", 2,
    ["Meaning of the idiom 'काया पलट देना':", ["शरीर देखना", "वस्त्र बदलना", "रूप पूरी तरह बदल देना", "घर बनाना"], "The idiom means to transform completely."],
    ["मुहावरे 'काया पलट देना' का अर्थ है:", ["शरीर देखना", "वस्त्र बदलना", "रूप पूरी तरह बदल देना", "घर बनाना"], "इस मुहावरे का अर्थ है पूरी तरह रूपांतरित कर देना।"]),
  q(1, "hindi", "shuddh-vartani", "H", 1,
    ["Pick the standard Sanskrit-derived spelling of the honorific for a gentleman:", ["श्रीमान्", "श्रीमान", "श्रिमान्", "श्री मान"], "The Sanskrit-derived form is श्रीमान्, though श्रीमान is common."],
    ["शुद्ध वर्तनी (संस्कृत रूप) चुनिए:", ["श्रीमान", "श्रीमान्", "श्रिमान्", "श्री मान"], "संस्कृत से निकला रूप श्रीमान् है, यद्यपि श्रीमान भी प्रचलित है।"]),
  q(1, "hindi", "shuddh-vartani", "M", 3,
    ["Pick the correct spelling of the word meaning 'resolve':", ["संकलप", "संकल्प्", "सन्कल्प", "संकल्प"], "The correct form is संकल्प."],
    ["'दृढ़ निश्चय' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["संकलप", "संकल्प्", "सन्कल्प", "संकल्प"], "शुद्ध रूप संकल्प है।"]),
  q(1, "hindi", "vyakaran", "M", 0,
    ["The tense of 'वह कल दिल्ली जाएगा' is:", ["सामान्य भविष्यत् काल", "सामान्य वर्तमान काल", "सामान्य भूतकाल", "आसन्न भूतकाल"], "The ending -एगा marks the simple future."],
    ["'वह कल दिल्ली जाएगा' का काल है:", ["सामान्य भविष्यत् काल", "सामान्य वर्तमान काल", "सामान्य भूतकाल", "आसन्न भूतकाल"], "-एगा प्रत्यय सामान्य भविष्य दर्शाता है।"]),
  q(1, "hindi", "vyakaran", "H", 2,
    ["Which word is an 'अव्यय' (indeclinable)?", ["लड़का", "सुंदर", "और", "खाना"], "'और' never changes form: it is an avyaya (conjunction)."],
    ["इनमें से कौन-सा शब्द 'अव्यय' है?", ["लड़का", "सुंदर", "और", "खाना"], "'और' का रूप कभी नहीं बदलता: यह अव्यय (योजक) है।"]),
  q(1, "hindi", "vyakaran", "M", 1,
    ["The feminine of 'विद्वान' is:", ["विद्वानी", "विदुषी", "विद्वा", "विद्वानिका"], "विदुषी is the feminine form."],
    ["'विद्वान' का स्त्रीलिंग रूप है:", ["विद्वानी", "विदुषी", "विद्वा", "विद्वानिका"], "विदुषी स्त्रीलिंग रूप है।"]),
  q(1, "hindi", "alankar-ras", "H", 3,
    ["'वह दीपक की लौ-सा था' — the figure of speech here is:", ["अनुप्रास", "यमक", "श्लेष", "उपमा"], "'सा' marks a direct comparison: upama."],
    ["'वह दीपक की लौ-सा था' में कौन-सा अलंकार है?", ["अनुप्रास", "यमक", "श्लेष", "उपमा"], "'सा' प्रत्यक्ष तुलना बताता है: उपमा।"]),
  q(1, "hindi", "alankar-ras", "M", 2,
    ["The sthayi bhav of 'भयानक रस' is:", ["उत्साह", "जुगुप्सा", "भय", "विस्मय"], "Bhay (fear) is the sthayi bhav of bhayanak ras."],
    ["'भयानक रस' का स्थायी भाव है:", ["उत्साह", "जुगुप्सा", "भय", "विस्मय"], "भयानक रस का स्थायी भाव भय है।"]),

  // ───────── Section 2: English (30) ─────────
  q(2, "english", "literature", "M", 0,
    ["Who wrote the poem 'I Wandered Lonely as a Cloud' (Daffodils)?", ["William Wordsworth", "John Keats", "P. B. Shelley", "Lord Byron"], "Wordsworth wrote it in 1807."],
    ["कविता 'I Wandered Lonely as a Cloud' (डैफ़ोडिल्स) किसने लिखी?", ["विलियम वर्ड्सवर्थ", "जॉन कीट्स", "पी. बी. शेली", "लॉर्ड बायरन"], "वर्ड्सवर्थ ने इसे 1807 में लिखा।"]),
  q(2, "english", "literature", "M", 2,
    ["'Oliver Twist' is a novel by:", ["Thomas Hardy", "George Eliot", "Charles Dickens", "Jane Austen"], "Dickens published it in 1838."],
    ["'Oliver Twist' उपन्यास किसका है?", ["थॉमस हार्डी", "जॉर्ज इलियट", "चार्ल्स डिकेंस", "जेन ऑस्टिन"], "डिकेंस ने इसे 1838 में प्रकाशित किया।"]),
  q(2, "english", "literature", "H", 1,
    ["'Malgudi Days' is a collection of stories by:", ["Mulk Raj Anand", "R. K. Narayan", "Raja Rao", "Khushwant Singh"], "R. K. Narayan's fictional town is Malgudi."],
    ["'Malgudi Days' किसकी कहानियों का संग्रह है?", ["मुल्क राज आनंद", "आर. के. नारायण", "राजा राव", "खुशवंत सिंह"], "आर. के. नारायण का काल्पनिक नगर मालगुडी है।"]),
  q(2, "english", "literature", "H", 3,
    ["'Pride and Prejudice' was written by:", ["Emily Brontë", "Charlotte Brontë", "Mary Shelley", "Jane Austen"], "Jane Austen published it in 1813."],
    ["'Pride and Prejudice' किसने लिखा?", ["एमिली ब्रॉन्टी", "शार्लट ब्रॉन्टी", "मैरी शेली", "जेन ऑस्टिन"], "जेन ऑस्टिन ने इसे 1813 में प्रकाशित किया।"]),
  q(2, "english", "literature", "H", 2,
    ["George Orwell's '1984' is best described as a:", ["Romantic comedy", "Historical epic", "Dystopian novel", "Travel diary"], "It depicts a totalitarian society."],
    ["जॉर्ज ऑरवेल का '1984' सबसे उपयुक्त रूप से क्या है?", ["रोमांटिक हास्य", "ऐतिहासिक महाकाव्य", "डिस्टोपियाई उपन्यास", "यात्रा-वृत्तांत"], "इसमें अधिनायकवादी समाज का चित्रण है।"]),
  q(2, "english", "grammar", "M", 3,
    ["Choose the correct conditional: 'If it rains tomorrow, we ___ the picnic.'", ["cancelled", "would cancel", "have cancelled", "will cancel"], "A real future condition uses 'will' in the main clause."],
    ["सही conditional चुनिए: 'If it rains tomorrow, we ___ the picnic.'", ["cancelled", "would cancel", "have cancelled", "will cancel"], "वास्तविक भविष्य की शर्त में मुख्य उपवाक्य में 'will' आता है।"]),
  q(2, "english", "grammar", "H", 0,
    ["Choose the correct inverted sentence: 'Not only ___ late, but he also forgot his books.'", ["did he arrive", "he arrived", "he did arrive", "arrived he"], "After 'Not only' at the start, the auxiliary comes before the subject."],
    ["सही व्युत्क्रमित वाक्य चुनिए: 'Not only ___ late, but he also forgot his books.'", ["did he arrive", "he arrived", "he did arrive", "arrived he"], "आरंभ में 'Not only' आने पर सहायक क्रिया कर्ता से पहले आती है।"]),
  q(2, "english", "grammar", "M", 1,
    ["Fill in the blank: 'The number of applicants ___ increased this year.'", ["have", "has", "are", "were"], "'The number of' takes a singular verb."],
    ["रिक्त स्थान भरिए: 'The number of applicants ___ increased this year.'", ["have", "has", "are", "were"], "'The number of' के साथ एकवचन क्रिया आती है।"]),
  q(2, "english", "grammar", "H", 2,
    ["Fill in the blank: 'He insisted ___ paying the bill.'", ["in", "for", "on", "at"], "'Insist on' is the correct phrase."],
    ["रिक्त स्थान भरिए: 'He insisted ___ paying the bill.'", ["in", "for", "on", "at"], "'Insist on' सही प्रयोग है।"]),
  q(2, "english", "grammar", "M", 0,
    ["Fill in the blank: 'The patient had died before the doctor ___.'", ["arrived", "arrives", "has arrived", "was arriving"], "The later past action takes the simple past; the earlier takes the past perfect."],
    ["रिक्त स्थान भरिए: 'The patient had died before the doctor ___.'", ["arrived", "arrives", "has arrived", "was arriving"], "बाद की भूतकालीन क्रिया simple past और पहले की past perfect में आती है।"]),
  q(2, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'He is (A) senior than (B) me (C) by two years. (D)'", ["A", "B", "C", "D"], "'Senior' takes 'to', not 'than'."],
    ["त्रुटि वाला भाग चुनिए: 'He is (A) senior than (B) me (C) by two years. (D)'", ["A", "B", "C", "D"], "'Senior' के बाद 'to' आता है, 'than' नहीं।"]),
  q(2, "english", "error-spotting", "M", 3,
    ["Find the part with an error: 'Many a (A) boy (B) have (C) failed in this test. (D)'", ["A", "B", "D", "C"], "'Many a' takes a singular verb: 'has'."],
    ["त्रुटि वाला भाग चुनिए: 'Many a (A) boy (B) have (C) failed in this test. (D)'", ["A", "B", "D", "C"], "'Many a' के साथ एकवचन क्रिया 'has' आती है।"]),
  q(2, "english", "error-spotting", "H", 0,
    ["Find the part with an error: 'Hardly (A) he had left (B) when (C) the phone rang. (D)'", ["A", "B", "C", "D"], "After 'Hardly', the auxiliary precedes the subject: 'Hardly had he left'."],
    ["त्रुटि वाला भाग चुनिए: 'Hardly (A) he had left (B) when (C) the phone rang. (D)'", ["A", "B", "C", "D"], "'Hardly' के बाद सहायक क्रिया कर्ता से पहले आती है: 'Hardly had he left'।"]),
  q(2, "english", "voice-speech", "M", 2,
    ["Change to the passive voice: 'They will complete the project by May.'", ["The project will complete by May.", "The project is completed by May.", "The project will be completed by May.", "The project would be completed by May."], "Future passive: will be + past participle."],
    ["Passive voice में बदलिए: 'They will complete the project by May.'", ["The project will complete by May.", "The project is completed by May.", "The project will be completed by May.", "The project would be completed by May."], "भविष्यत् passive: will be + past participle।"]),
  q(2, "english", "voice-speech", "H", 1,
    ["Change to indirect speech: 'The teacher said, \"Honesty is the best policy.\"'", ["The teacher said that honesty was the best policy.", "The teacher said that honesty is the best policy.", "The teacher told that honesty has been the best policy.", "The teacher said honesty would be the best policy."], "A universal truth keeps the present tense in reported speech."],
    ["Indirect speech में बदलिए: 'The teacher said, \"Honesty is the best policy.\"'", ["The teacher said that honesty was the best policy.", "The teacher said that honesty is the best policy.", "The teacher told that honesty has been the best policy.", "The teacher said honesty would be the best policy."], "सार्वभौमिक सत्य reported speech में present tense में ही रहता है।"]),
  q(2, "english", "vocabulary", "H", 3,
    ["Which word is nearest in meaning to 'OBSOLETE'?", ["Modern", "Useful", "Fashionable", "Out of date"], "Obsolete means no longer in use."],
    ["'OBSOLETE' के निकटतम अर्थ वाला शब्द कौन-सा है?", ["Modern", "Useful", "Fashionable", "Out of date"], "Obsolete का अर्थ अब प्रयोग में न रहने वाला है।"]),
  q(2, "english", "synonyms-antonyms", "M", 1,
    ["The antonym of 'VOLUNTARY' is:", ["Willing", "Compulsory", "Free", "Eager"], "Voluntary is by choice; compulsory is required."],
    ["'VOLUNTARY' का विलोम है:", ["Willing", "Compulsory", "Free", "Eager"], "Voluntary इच्छा से होता है; compulsory अनिवार्य होता है।"]),
  q(2, "english", "synonyms-antonyms", "H", 2,
    ["The antonym of 'VERBOSE' is:", ["Wordy", "Talkative", "Concise", "Lengthy"], "Verbose means using too many words; concise is the opposite."],
    ["'VERBOSE' का विलोम है:", ["Wordy", "Talkative", "Concise", "Lengthy"], "Verbose का अर्थ अत्यधिक शब्दों वाला है; concise उसका उलटा है।"]),
  q(2, "english", "idioms", "M", 0,
    ["The idiom 'to call it a day' means to:", ["Stop working for the time being", "Name a day", "Start early", "Make a phone call"], "It means to stop an activity for now."],
    ["मुहावरे 'to call it a day' का अर्थ है:", ["फ़िलहाल काम रोक देना", "कोई दिन तय करना", "जल्दी शुरू करना", "फ़ोन करना"], "इसका अर्थ है किसी गतिविधि को अभी के लिए रोक देना।"]),
  q(2, "english", "idioms", "H", 3,
    ["To 'have a chip on one's shoulder' is to:", ["Carry a heavy bag", "Eat snacks", "Be physically strong", "Hold a grudge or feel resentful"], "The idiom describes ongoing resentment."],
    ["'have a chip on one's shoulder' का अर्थ है:", ["भारी थैला उठाना", "नाश्ता खाना", "शारीरिक रूप से बलवान होना", "मन में द्वेष या नाराज़गी रखना"], "यह मुहावरा निरंतर रोष का वर्णन करता है।"]),
  q(2, "english", "one-word", "M", 2,
    ["Which single word means 'a person who has no money'?", ["Affluent", "Miser", "Pauper", "Tycoon"], "A pauper is extremely poor."],
    ["'धनहीन व्यक्ति' के लिए एक शब्द कौन-सा है?", ["Affluent", "Miser", "Pauper", "Tycoon"], "Pauper अत्यंत निर्धन व्यक्ति होता है।"]),
  q(2, "english", "one-word", "H", 1,
    ["Which single word means 'a medicine that cures all diseases'?", ["Antidote", "Panacea", "Placebo", "Tonic"], "A panacea is a cure-all."],
    ["'सब रोगों को ठीक करने वाली औषधि' के लिए एक शब्द कौन-सा है?", ["Antidote", "Panacea", "Placebo", "Tonic"], "Panacea सर्वरोगहर उपाय है।"]),
  q(2, "english", "one-word", "M", 3,
    ["Which single word means 'a place where bread is baked'?", ["Dairy", "Laundry", "Pantry", "Bakery"], "A bakery bakes and sells bread."],
    ["'जहाँ रोटी/ब्रेड सेंकी जाती है' उस स्थान के लिए एक शब्द कौन-सा है?", ["Dairy", "Laundry", "Pantry", "Bakery"], "Bakery में ब्रेड सेंकी और बेची जाती है।"]),
  q(2, "english", "spelling", "H", 0,
    ["Select the correct spelling of the noun meaning 'a person who is in charge of a school':", ["Principal", "Principle", "Principel", "Princeple"], "'Principal' is the head of a school; 'principle' is a rule."],
    ["'विद्यालय का प्रमुख' अर्थ वाले संज्ञा की सही वर्तनी चुनिए:", ["Principal", "Principle", "Principel", "Princeple"], "'Principal' विद्यालय का प्रमुख होता है; 'principle' नियम को कहते हैं।"]),
  q(2, "english", "spelling", "M", 2,
    ["Select the correct spelling of the word meaning 'a regular beat in music or speech':", ["Rythm", "Rhythem", "Rhythm", "Rhythmn"], "The word is rhythm."],
    ["'संगीत या वाणी की नियमित लय' अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Rythm", "Rhythem", "Rhythm", "Rhythmn"], "सही शब्द rhythm है।"]),
  q(2, "english", "comprehension", "M", 1,
    ["The main purpose of teaching a poem in an English class at the secondary stage is to:", ["Make pupils memorise the poet's biography", "Develop appreciation of language and imagination", "Test spelling only", "Teach map reading"], "Poetry builds sensitivity to language and imagery."],
    ["माध्यमिक स्तर पर अंग्रेज़ी कक्षा में कविता पढ़ाने का मुख्य उद्देश्य है:", ["विद्यार्थियों को कवि की जीवनी रटाना", "भाषा-बोध और कल्पना की सराहना विकसित करना", "केवल वर्तनी की जाँच", "मानचित्र पढ़ना सिखाना"], "कविता भाषा और बिंब के प्रति संवेदनशीलता बनाती है।"]),
  q(2, "english", "comprehension", "H", 0,
    ["A teacher gives learners a gapped passage to fill in with suitable words. This is a:", ["Cloze test", "Dictation", "Précis", "Debate"], "A cloze test removes words from a passage for learners to supply."],
    ["शिक्षक शिक्षार्थियों को रिक्त स्थानों वाला अनुच्छेद देता है जिसे उपयुक्त शब्दों से भरना है। यह कौन-सा अभ्यास है?", ["क्लोज़ टेस्ट", "श्रुतलेख", "सार-लेखन", "वाद-विवाद"], "क्लोज़ टेस्ट में अनुच्छेद से शब्द हटाकर शिक्षार्थियों से भरवाए जाते हैं।"]),
  q(2, "english", "comprehension", "M", 3,
    ["Which of these best develops the writing skill of secondary-level pupils?", ["Only copying", "Silent staring", "Rote learning of essays", "Guided composition with drafting and feedback"], "Process writing with feedback improves writing."],
    ["माध्यमिक स्तर के विद्यार्थियों के लेखन-कौशल को सबसे अच्छा किससे विकसित किया जा सकता है?", ["केवल नक़ल से", "टकटकी लगाकर देखने से", "निबंध रटने से", "प्रारूप-लेखन और प्रतिक्रिया के साथ निर्देशित रचना से"], "प्रतिक्रिया सहित प्रक्रिया-लेखन लेखन को सुधारता है।"]),

  q(2, "english", "synonyms-antonyms", "H", 1,
    ["Which word is opposite in meaning to 'AMBIGUOUS'?", ["Vague", "Clear", "Doubtful", "Obscure"], "Ambiguous means open to more than one meaning; clear is the opposite."],
    ["'AMBIGUOUS' का विलोम शब्द कौन-सा है?", ["Vague", "Clear", "Doubtful", "Obscure"], "Ambiguous का अर्थ एक से अधिक अर्थ वाला है; clear उसका उलटा है।"]),
  q(2, "english", "grammar", "M", 2,
    ["Fill in the blank: 'The Himalayas ___ a majestic mountain range.'", ["is", "was", "are", "has"], "'The Himalayas' is plural in form and takes 'are'."],
    ["रिक्त स्थान भरिए: 'The Himalayas ___ a majestic mountain range.'", ["is", "was", "are", "has"], "'The Himalayas' बहुवचन रूप है और 'are' लेता है।"]),

  // ───────── Section 3: History & Civics (30) ─────────
  q(3, "general-studies", "indian-history", "M", 1,
    ["The oldest of the four Vedas is the:", ["Samaveda", "Rigveda", "Yajurveda", "Atharvaveda"], "The Rigveda is the earliest."],
    ["चारों वेदों में सबसे प्राचीन कौन-सा है?", ["सामवेद", "ऋग्वेद", "यजुर्वेद", "अथर्ववेद"], "ऋग्वेद सबसे पुराना है।"]),
  q(3, "general-studies", "indian-history", "M", 3,
    ["Mahavira is regarded as the ______ Tirthankara of Jainism.", ["First", "Fifteenth", "Twentieth", "Twenty-fourth"], "Mahavira was the 24th and last Tirthankara."],
    ["महावीर को जैन धर्म का ______ तीर्थंकर माना जाता है।", ["पहला", "पंद्रहवाँ", "बीसवाँ", "चौबीसवाँ"], "महावीर 24वें और अंतिम तीर्थंकर थे।"]),
  q(3, "general-studies", "indian-history", "H", 0,
    ["Gautama Buddha delivered his first sermon at:", ["Sarnath", "Bodh Gaya", "Kushinagar", "Lumbini"], "The first sermon, Dharmachakra Pravartana, was at Sarnath."],
    ["गौतम बुद्ध ने अपना पहला उपदेश कहाँ दिया?", ["सारनाथ", "बोधगया", "कुशीनगर", "लुंबिनी"], "प्रथम उपदेश (धर्मचक्र प्रवर्तन) सारनाथ में हुआ।"]),
  q(3, "general-studies", "indian-history", "H", 2,
    ["Megasthenes, the Greek ambassador, wrote the 'Indica' during the reign of:", ["Ashoka", "Bindusara", "Chandragupta Maurya", "Harsha"], "Megasthenes lived at Chandragupta's court."],
    ["यूनानी राजदूत मेगस्थनीज़ ने 'इंडिका' किसके शासनकाल में लिखी?", ["अशोक", "बिंदुसार", "चंद्रगुप्त मौर्य", "हर्ष"], "मेगस्थनीज़ चंद्रगुप्त के दरबार में रहा।"]),
  q(3, "general-studies", "indian-history", "M", 1,
    ["The Sangam literature belongs to which region?", ["Bengal", "Tamil country", "Punjab", "Kashmir"], "The Sangam works are in classical Tamil."],
    ["संगम साहित्य किस क्षेत्र का है?", ["बंगाल", "तमिल प्रदेश", "पंजाब", "कश्मीर"], "संगम रचनाएँ शास्त्रीय तमिल में हैं।"]),
  q(3, "general-studies", "indian-history", "M", 2,
    ["Which Bhakti saint, a weaver by profession, preached through 'dohas' against idol worship and caste?", ["Tulsidas", "Surdas", "Kabir", "Mirabai"], "Kabir was a weaver-poet of the 15th century."],
    ["कौन-सा भक्ति संत, जो पेशे से जुलाहा था, 'दोहों' के माध्यम से मूर्ति-पूजा और जातिवाद के विरुद्ध उपदेश देता था?", ["तुलसीदास", "सूरदास", "कबीर", "मीराबाई"], "कबीर 15वीं सदी के जुलाहा-कवि थे।"]),
  q(3, "general-studies", "indian-history", "H", 3,
    ["The founder of the Sikh faith, Guru Nanak, was born at:", ["Amritsar", "Anandpur", "Patna", "Talwandi (Nankana Sahib)"], "Guru Nanak was born in 1469 at Talwandi."],
    ["सिख धर्म के संस्थापक गुरु नानक का जन्म कहाँ हुआ था?", ["अमृतसर", "आनंदपुर", "पटना", "तलवंडी (ननकाना साहिब)"], "गुरु नानक का जन्म 1469 में तलवंडी में हुआ।"]),
  q(3, "general-studies", "indian-history", "M", 0,
    ["Which Mughal emperor built the Red Fort at Delhi?", ["Shah Jahan", "Akbar", "Humayun", "Jahangir"], "Shah Jahan had it built in the 1640s."],
    ["दिल्ली का लाल क़िला किस मुग़ल सम्राट ने बनवाया?", ["शाहजहाँ", "अकबर", "हुमायूँ", "जहाँगीर"], "शाहजहाँ ने इसे 1640 के दशक में बनवाया।"]),
  q(3, "general-studies", "indian-history", "H", 1,
    ["The Battle of Buxar (1764) was fought between the British and the combined forces of Mir Qasim, Shuja-ud-Daula and:", ["Tipu Sultan", "Shah Alam II", "Haider Ali", "Nana Saheb"], "The Mughal emperor Shah Alam II was with the allied forces."],
    ["बक्सर का युद्ध (1764) अंग्रेज़ों और मीर क़ासिम, शुजाउद्दौला तथा किसकी संयुक्त सेना के बीच हुआ?", ["टीपू सुल्तान", "शाह आलम द्वितीय", "हैदर अली", "नाना साहब"], "मुग़ल सम्राट शाह आलम द्वितीय संयुक्त सेना के साथ था।"]),
  q(3, "general-studies", "indian-history", "M", 3,
    ["Who was known as 'Tiger of Mysore'?", ["Haider Ali", "Nizam Ali", "Raja Rammohan", "Tipu Sultan"], "Tipu Sultan was nicknamed the Tiger of Mysore."],
    ["'मैसूर का शेर' किसे कहा जाता था?", ["हैदर अली", "निज़ाम अली", "राजा राममोहन", "टीपू सुल्तान"], "टीपू सुल्तान को मैसूर का शेर कहा जाता था।"]),
  q(3, "general-studies", "indian-history", "H", 2,
    ["The Doctrine of Lapse was a policy associated with the Governor-General:", ["Lord Cornwallis", "Lord Wellesley", "Lord Dalhousie", "Lord Canning"], "Dalhousie annexed states under the doctrine in 1848–56."],
    ["व्यपगत का सिद्धांत किस गवर्नर-जनरल की नीति से जुड़ा था?", ["लॉर्ड कॉर्नवालिस", "लॉर्ड वेलेज़्ली", "लॉर्ड डलहौज़ी", "लॉर्ड कैनिंग"], "डलहौज़ी ने 1848–56 में इस सिद्धांत से राज्य मिलाए।"]),
  q(3, "general-studies", "indian-history", "M", 0,
    ["Who led the revolt at Jhansi in 1857?", ["Rani Lakshmibai", "Begum Hazrat Mahal", "Nana Saheb", "Kunwar Singh"], "Rani Lakshmibai led the rebels at Jhansi."],
    ["1857 में झाँसी में विद्रोह का नेतृत्व किसने किया?", ["रानी लक्ष्मीबाई", "बेगम हज़रत महल", "नाना साहब", "कुँवर सिंह"], "रानी लक्ष्मीबाई ने झाँसी में विद्रोहियों का नेतृत्व किया।"]),
  q(3, "general-studies", "indian-history", "M", 1,
    ["Swami Dayananda Saraswati started which reform society in Bombay in 1875?", ["Brahmo Samaj", "Arya Samaj", "Prarthana Samaj", "Ramakrishna Mission"], "Dayananda founded the Arya Samaj at Bombay."],
    ["स्वामी दयानंद सरस्वती ने 1875 में बंबई में किस सुधार समाज की शुरुआत की?", ["ब्रह्म समाज", "आर्य समाज", "प्रार्थना समाज", "रामकृष्ण मिशन"], "दयानंद ने बंबई में आर्य समाज की स्थापना की।"]),
  q(3, "general-studies", "indian-history", "H", 3,
    ["Bal Gangadhar Tilak's famous slogan was:", ["Do or Die", "Jai Hind", "Dilli Chalo", "Swaraj is my birthright"], "Tilak declared 'Swaraj is my birthright and I shall have it'."],
    ["बाल गंगाधर तिलक का प्रसिद्ध नारा था:", ["करो या मरो", "जय हिंद", "दिल्ली चलो", "स्वराज मेरा जन्मसिद्ध अधिकार है"], "तिलक ने कहा था 'स्वराज मेरा जन्मसिद्ध अधिकार है और मैं इसे लेकर रहूँगा'।"]),
  q(3, "general-studies", "indian-history", "M", 2,
    ["The Champaran Satyagraha (1917) was Gandhi's first satyagraha in India, on behalf of:", ["Mill workers", "Salt makers", "Indigo farmers", "Railway workers"], "Gandhi supported the indigo cultivators of Champaran."],
    ["चंपारण सत्याग्रह (1917) भारत में गांधीजी का पहला सत्याग्रह था, जो किसके पक्ष में था?", ["मिल मज़दूरों के", "नमक बनाने वालों के", "नील किसानों के", "रेलवे कर्मचारियों के"], "गांधीजी ने चंपारण के नील उत्पादक किसानों का साथ दिया।"]),
  q(3, "general-studies", "indian-history", "H", 0,
    ["The Poona Pact (1932) was signed between Gandhi and:", ["B. R. Ambedkar", "Jinnah", "Nehru", "Tilak"], "It settled the question of seats for the Depressed Classes."],
    ["पूना समझौता (1932) गांधीजी और किसके बीच हुआ?", ["बी. आर. अंबेडकर", "जिन्ना", "नेहरू", "तिलक"], "इसने दलित वर्गों के लिए सीटों का प्रश्न सुलझाया।"]),
  q(3, "general-studies", "indian-history", "M", 3,
    ["India became independent on:", ["26 January 1947", "15 August 1950", "26 January 1950", "15 August 1947"], "Independence came at midnight on 14–15 August 1947."],
    ["भारत स्वतंत्र हुआ:", ["26 जनवरी 1947 को", "15 अगस्त 1950 को", "26 जनवरी 1950 को", "15 अगस्त 1947 को"], "स्वतंत्रता 14–15 अगस्त 1947 की मध्यरात्रि को मिली।"]),
  q(3, "general-studies", "indian-history", "H", 1,
    ["Who is known as the 'Iron Man of India' for integrating the princely states?", ["Jawaharlal Nehru", "Sardar Vallabhbhai Patel", "C. Rajagopalachari", "Maulana Azad"], "Patel unified over 560 princely states."],
    ["रियासतों के एकीकरण के कारण 'भारत का लौह पुरुष' किसे कहा जाता है?", ["जवाहरलाल नेहरू", "सरदार वल्लभभाई पटेल", "सी. राजगोपालाचारी", "मौलाना आज़ाद"], "पटेल ने 560 से अधिक रियासतों का एकीकरण किया।"]),
  q(3, "general-studies", "indian-polity", "M", 2,
    ["After each general election, who elects the presiding officer of the Lok Sabha?", ["The President", "The Prime Minister", "Members of the Lok Sabha", "The Rajya Sabha"], "Lok Sabha members elect the Speaker from among themselves."],
    ["प्रत्येक आम चुनाव के बाद लोकसभा के पीठासीन अधिकारी का चुनाव कौन करता है?", ["राष्ट्रपति", "प्रधानमंत्री", "लोकसभा के सदस्य", "राज्यसभा"], "लोकसभा सदस्य अपने में से अध्यक्ष चुनते हैं।"]),
  q(3, "general-studies", "indian-polity", "H", 3,
    ["A Money Bill can be introduced only in the:", ["Rajya Sabha", "Either House", "Joint sitting", "Lok Sabha"], "Article 110 and 109 give the Lok Sabha primacy over money bills."],
    ["धन विधेयक केवल किस सदन में पेश किया जा सकता है?", ["राज्यसभा", "किसी भी सदन में", "संयुक्त बैठक में", "लोकसभा"], "अनुच्छेद 110 और 109 धन विधेयकों पर लोकसभा को प्राथमिकता देते हैं।"]),
  q(3, "general-studies", "indian-polity", "M", 2,
    ["Articles 36 to 51 of the Constitution of India together form which Part?", ["Part II", "Part III", "Part IV", "Part V"], "Part IV (Articles 36–51) contains the Directive Principles."],
    ["भारत के संविधान के अनुच्छेद 36 से 51 मिलकर कौन-सा भाग बनाते हैं?", ["भाग II", "भाग III", "भाग IV", "भाग V"], "भाग IV (अनुच्छेद 36–51) में नीति निदेशक तत्व हैं।"]),
  q(3, "general-studies", "indian-polity", "H", 0,
    ["The power of courts to declare laws void if they violate the Constitution is called:", ["Judicial review", "Judicial activism only", "Writ of mandamus", "Contempt"], "Judicial review checks laws against the Constitution."],
    ["न्यायालयों द्वारा संविधान का उल्लंघन करने वाले कानूनों को अमान्य घोषित करने की शक्ति क्या कहलाती है?", ["न्यायिक पुनर्विलोकन", "केवल न्यायिक सक्रियता", "परमादेश रिट", "अवमानना"], "न्यायिक पुनर्विलोकन कानूनों को संविधान की कसौटी पर परखता है।"]),
  q(3, "general-studies", "indian-polity", "M", 3,
    ["The Right to Information Act was passed in:", ["1995", "2000", "2002", "2005"], "The RTI Act came in 2005."],
    ["सूचना का अधिकार अधिनियम किस वर्ष पारित हुआ?", ["1995", "2000", "2002", "2005"], "आरटीआई अधिनियम 2005 में आया।"]),
  q(3, "general-studies", "indian-polity", "M", 2,
    ["The Gram Sabha consists of:", ["Only the sarpanch", "Only women", "All registered voters of the village", "Only landowners"], "All adult voters on the village electoral roll form the Gram Sabha."],
    ["ग्राम सभा किससे बनती है?", ["केवल सरपंच से", "केवल महिलाओं से", "गाँव के सभी पंजीकृत मतदाताओं से", "केवल भूस्वामियों से"], "गाँव की मतदाता-सूची के सभी वयस्क मतदाता ग्राम सभा बनाते हैं।"]),
  q(3, "general-studies", "indian-polity", "H", 1,
    ["The Lokpal and Lokayuktas Act, which created the anti-corruption ombudsman, was passed in:", ["2005", "2013", "2016", "1999"], "Parliament passed the Act in 2013."],
    ["भ्रष्टाचार-रोधी लोकपाल की स्थापना करने वाला लोकपाल और लोकायुक्त अधिनियम किस वर्ष पारित हुआ?", ["2005", "2013", "2016", "1999"], "संसद ने यह अधिनियम 2013 में पारित किया।"]),
  q(3, "general-studies", "indian-polity", "M", 0,
    ["The tenure of the President of India is:", ["5 years", "4 years", "6 years", "7 years"], "The President holds office for five years."],
    ["भारत के राष्ट्रपति का कार्यकाल कितना होता है?", ["5 वर्ष", "4 वर्ष", "6 वर्ष", "7 वर्ष"], "राष्ट्रपति पाँच वर्ष के लिए पद धारण करता है।"]),
  q(3, "general-studies", "indian-polity", "H", 2,
    ["Which Article provides for the impeachment of the President?", ["Article 52", "Article 74", "Article 61", "Article 79"], "Article 61 lays down the procedure for impeachment."],
    ["कौन-सा अनुच्छेद राष्ट्रपति पर महाभियोग का प्रावधान करता है?", ["अनुच्छेद 52", "अनुच्छेद 74", "अनुच्छेद 61", "अनुच्छेद 79"], "अनुच्छेद 61 महाभियोग की प्रक्रिया बताता है।"]),

  q(3, "general-studies", "indian-polity", "H", 0,
    ["The Vice-President of India is elected by an electoral college made up of:", ["Members of both Houses of Parliament", "Elected members of State Assemblies", "Only the Lok Sabha", "Members of Parliament and State Assemblies"], "Unlike the President, the Vice-President is elected by members of both Houses of Parliament."],
    ["भारत के उपराष्ट्रपति का चुनाव किस निर्वाचक मंडल द्वारा होता है?", ["संसद के दोनों सदनों के सदस्य", "राज्य विधानसभाओं के निर्वाचित सदस्य", "केवल लोकसभा", "संसद और राज्य विधानसभाओं के सदस्य"], "राष्ट्रपति के विपरीत उपराष्ट्रपति को संसद के दोनों सदनों के सदस्य चुनते हैं।"]),
  q(3, "general-studies", "indian-history", "M", 1,
    ["The Indus Valley Civilization is also known as the:", ["Vedic civilization", "Harappan civilization", "Mauryan civilization", "Gupta civilization"], "It is named after its first-discovered site, Harappa."],
    ["सिंधु घाटी सभ्यता को और किस नाम से जाना जाता है?", ["वैदिक सभ्यता", "हड़प्पा सभ्यता", "मौर्य सभ्यता", "गुप्त सभ्यता"], "इसका नाम इसके पहले खोजे गए स्थल हड़प्पा पर पड़ा।"]),
  q(3, "general-studies", "indian-history", "H", 2,
    ["Most of Ashoka's rock edicts in India were inscribed in which script?", ["Kharosthi", "Devanagari", "Brahmi", "Tamil"], "The Brahmi script was used for most edicts; Kharosthi in the north-west."],
    ["भारत में अशोक के अधिकांश शिलालेख किस लिपि में उत्कीर्ण हैं?", ["खरोष्ठी", "देवनागरी", "ब्राह्मी", "तमिल"], "अधिकांश शिलालेख ब्राह्मी लिपि में हैं; उत्तर-पश्चिम में खरोष्ठी का प्रयोग हुआ।"]),

  // ───────── Section 4: Geography, Economics & Himachal GK (30) ─────────
  q(4, "general-studies", "indian-geography", "M", 2,
    ["The Amazon river basin lies mainly in which country?", ["Argentina", "Chile", "Brazil", "Peru only"], "Most of the Amazon basin is in Brazil."],
    ["अमेज़न नदी-बेसिन मुख्यतः किस देश में है?", ["अर्जेंटीना", "चिली", "ब्राज़ील", "केवल पेरू"], "अमेज़न बेसिन का अधिकांश भाग ब्राज़ील में है।"]),
  q(4, "general-studies", "indian-geography", "H", 0,
    ["The cold ocean current that flows along the west coast of South America is the:", ["Peru (Humboldt) Current", "Gulf Stream", "Kuroshio", "Agulhas"], "The Humboldt or Peru Current is cold."],
    ["दक्षिण अमेरिका के पश्चिमी तट के साथ बहने वाली ठंडी महासागरीय धारा कौन-सी है?", ["पेरू (हम्बोल्ट) धारा", "गल्फ़ स्ट्रीम", "कुरोशियो", "अगुल्हास"], "हम्बोल्ट या पेरू धारा ठंडी है।"]),
  q(4, "general-studies", "indian-geography", "M", 3,
    ["Which soil is formed by the deposition of rivers and is the most fertile in India?", ["Black soil", "Red soil", "Laterite", "Alluvial soil"], "Alluvial soil covers the Indo-Gangetic plain."],
    ["नदियों के निक्षेप से बनी और भारत की सबसे उपजाऊ मिट्टी कौन-सी है?", ["काली मिट्टी", "लाल मिट्टी", "लैटेराइट", "जलोढ़ मिट्टी"], "जलोढ़ मिट्टी सिंधु-गंगा मैदान में फैली है।"]),
  q(4, "general-studies", "indian-geography", "H", 1,
    ["The river Krishna rises in the Western Ghats near:", ["Nasik", "Mahabaleshwar", "Amarkantak", "Brahmagiri"], "The Krishna rises at Mahabaleshwar in Maharashtra."],
    ["कृष्णा नदी पश्चिमी घाट में किस स्थान के निकट से निकलती है?", ["नासिक", "महाबलेश्वर", "अमरकंटक", "ब्रह्मगिरि"], "कृष्णा महाराष्ट्र के महाबलेश्वर से निकलती है।"]),
  q(4, "general-studies", "indian-geography", "M", 0,
    ["Which state is the largest producer of iron ore in India?", ["Odisha", "Kerala", "Punjab", "Assam"], "Odisha leads in iron ore production."],
    ["भारत में लौह-अयस्क का सबसे बड़ा उत्पादक राज्य कौन-सा है?", ["ओडिशा", "केरल", "पंजाब", "असम"], "लौह-अयस्क उत्पादन में ओडिशा अग्रणी है।"]),
  q(4, "general-studies", "indian-geography", "M", 2,
    ["The Tropic of Capricorn passes through which continent?", ["North America", "Europe", "South America", "Asia"], "It crosses South America, Africa and Australia."],
    ["मकर रेखा किस महाद्वीप से गुज़रती है?", ["उत्तर अमेरिका", "यूरोप", "दक्षिण अमेरिका", "एशिया"], "यह दक्षिण अमेरिका, अफ़्रीका और ऑस्ट्रेलिया से गुज़रती है।"]),
  q(4, "general-studies", "indian-geography", "H", 3,
    ["Which is the deepest known point of the oceans?", ["Puerto Rico Trench", "Java Trench", "Tonga Trench", "Mariana Trench"], "The Challenger Deep in the Mariana Trench is about 11 km deep."],
    ["महासागरों का ज्ञात सबसे गहरा बिंदु कौन-सा है?", ["प्यूर्टो रिको गर्त", "जावा गर्त", "टोंगा गर्त", "मारियाना गर्त"], "मारियाना गर्त का चैलेंजर डीप लगभग 11 किमी गहरा है।"]),
  q(4, "general-studies", "indian-geography", "M", 1,
    ["The Sundarbans delta is formed by the Ganga and the:", ["Mahanadi", "Brahmaputra", "Godavari", "Narmada"], "The Ganga–Brahmaputra delta is the world's largest."],
    ["सुंदरबन डेल्टा गंगा और किस नदी से बना है?", ["महानदी", "ब्रह्मपुत्र", "गोदावरी", "नर्मदा"], "गंगा–ब्रह्मपुत्र डेल्टा विश्व का सबसे बड़ा डेल्टा है।"]),
  q(4, "general-studies", "indian-geography", "H", 0,
    ["The Coriolis force causes winds in the Northern Hemisphere to be deflected to the:", ["Right", "Left", "North", "South"], "In the Northern Hemisphere, moving air deflects to the right."],
    ["कोरिओलिस बल के कारण उत्तरी गोलार्ध में पवनें किस ओर विक्षेपित होती हैं?", ["दाईं ओर", "बाईं ओर", "उत्तर की ओर", "दक्षिण की ओर"], "उत्तरी गोलार्ध में गतिमान वायु दाईं ओर मुड़ती है।"]),
  q(4, "general-studies", "indian-geography", "M", 3,
    ["India's longest national highway, NH 44, runs from Srinagar to:", ["Mumbai", "Chennai", "Kolkata", "Kanyakumari"], "NH 44 runs from Srinagar to Kanyakumari."],
    ["भारत का सबसे लंबा राष्ट्रीय राजमार्ग एनएच 44 श्रीनगर से कहाँ तक जाता है?", ["मुंबई", "चेन्नई", "कोलकाता", "कन्याकुमारी"], "एनएच 44 श्रीनगर से कन्याकुमारी तक जाता है।"]),
  q(4, "general-studies", "indian-geography", "M", 1,
    ["The Great Barrier Reef lies off the coast of:", ["Brazil", "Australia", "Indonesia", "Madagascar"], "It is off Queensland, Australia."],
    ["ग्रेट बैरियर रीफ किस देश के तट के पास है?", ["ब्राज़ील", "ऑस्ट्रेलिया", "इंडोनेशिया", "मेडागास्कर"], "यह ऑस्ट्रेलिया के क्वींसलैंड तट के पास है।"]),
  q(4, "general-studies", "indian-geography", "H", 2,
    ["The planet's largest hot desert is the:", ["Gobi", "Kalahari", "Sahara", "Thar"], "The Sahara covers much of North Africa."],
    ["विश्व का सबसे बड़ा गर्म मरुस्थल कौन-सा है?", ["गोबी", "कालाहारी", "सहारा", "थार"], "सहारा उत्तरी अफ़्रीका के बड़े भाग में फैला है।"]),
  q(4, "general-studies", "indian-economy", "M", 1,
    ["The Indian government's financial year ends on:", ["31 December", "31 March", "30 June", "30 September"], "The Indian financial year is April–March."],
    ["भारत सरकार का वित्तीय वर्ष किस तिथि को समाप्त होता है?", ["31 दिसंबर", "31 मार्च", "30 जून", "30 सितंबर"], "भारतीय वित्तीय वर्ष अप्रैल से मार्च तक होता है।"]),
  q(4, "general-studies", "indian-economy", "H", 2,
    ["Fiscal deficit equals total expenditure minus:", ["Total tax revenue only", "Revenue expenditure", "Total receipts excluding borrowings", "Capital expenditure"], "Fiscal deficit = total expenditure – (revenue receipts + non-debt capital receipts)."],
    ["राजकोषीय घाटा कुल व्यय में से किसे घटाने पर प्राप्त होता है?", ["केवल कुल कर-राजस्व", "राजस्व व्यय", "उधारी को छोड़कर कुल प्राप्तियाँ", "पूँजीगत व्यय"], "राजकोषीय घाटा = कुल व्यय – (राजस्व प्राप्तियाँ + गैर-ऋण पूँजीगत प्राप्तियाँ)।"]),
  q(4, "general-studies", "indian-economy", "M", 3,
    ["The rate at which the RBI lends short-term funds to commercial banks is called the:", ["CRR", "SLR", "Bank rate only", "Repo rate"], "The repo rate is the key policy rate for lending to banks."],
    ["आरबीआई जिस दर पर वाणिज्यिक बैंकों को अल्पकालिक ऋण देता है, उसे क्या कहते हैं?", ["सीआरआर", "एसएलआर", "केवल बैंक दर", "रेपो दर"], "रेपो दर बैंकों को उधार देने की प्रमुख नीतिगत दर है।"]),
  q(4, "general-studies", "indian-economy", "H", 1,
    ["The Cash Reserve Ratio (CRR) is the share of a bank's deposits that must be kept:", ["In government bonds", "With the RBI as cash", "In gold", "In foreign banks"], "Banks must hold a portion of net demand and time liabilities with the RBI."],
    ["नकद आरक्षित अनुपात (सीआरआर) बैंक की जमाओं का वह हिस्सा है जिसे रखना होता है:", ["सरकारी बॉन्डों में", "आरबीआई के पास नकद के रूप में", "सोने में", "विदेशी बैंकों में"], "बैंकों को अपनी शुद्ध माँग और सावधि देयताओं का एक भाग आरबीआई के पास रखना होता है।"]),
  q(4, "general-studies", "indian-economy", "M", 2,
    ["In economics, when the price of a normal good rises, its quantity demanded generally:", ["Rises", "Stays the same", "Falls", "Doubles"], "This is the law of demand."],
    ["अर्थशास्त्र में किसी सामान्य वस्तु का मूल्य बढ़ने पर उसकी माँग की मात्रा सामान्यतः:", ["बढ़ती है", "वही रहती है", "घटती है", "दुगुनी हो जाती है"], "यह माँग का नियम है।"]),
  q(4, "general-studies", "indian-economy", "H", 0,
    ["Poverty in India is officially estimated by which body, using expenditure data?", ["NITI Aayog / NSO-based committees", "SEBI", "Election Commission", "UGC"], "Poverty estimates are based on NSO consumption expenditure surveys."],
    ["भारत में निर्धनता का आधिकारिक आकलन व्यय-आँकड़ों के आधार पर किसके माध्यम से होता है?", ["नीति आयोग / एनएसओ-आधारित समितियाँ", "सेबी", "निर्वाचन आयोग", "यूजीसी"], "निर्धनता के अनुमान एनएसओ के उपभोग व्यय सर्वेक्षणों पर आधारित हैं।"]),
  q(4, "general-studies", "indian-economy", "M", 3,
    ["Which of these is a direct tax?", ["GST", "Customs duty", "Excise duty", "Income tax"], "Income tax is paid directly by the person on whom it is levied."],
    ["इनमें से कौन-सा प्रत्यक्ष कर है?", ["जीएसटी", "सीमा शुल्क", "उत्पाद शुल्क", "आयकर"], "आयकर वह व्यक्ति सीधे देता है जिस पर यह लगाया गया है।"]),
  q(4, "general-studies", "indian-economy", "M", 1,
    ["The 'Jan Dhan Yojana', launched in 2014, aims at:", ["Free electricity", "Financial inclusion through bank accounts", "Housing loans only", "Crop insurance"], "PMJDY opens basic bank accounts for all households."],
    ["2014 में शुरू की गई 'जन धन योजना' का उद्देश्य है:", ["निःशुल्क बिजली", "बैंक खातों द्वारा वित्तीय समावेशन", "केवल आवास ऋण", "फ़सल बीमा"], "पीएमजेडीवाई सभी परिवारों के लिए मूल बैंक खाते खुलवाती है।"]),

  q(4, "hp-gk", "history", "H", 2,
    ["The Treaty of Sugauli (1816), signed after the Anglo-Gorkha War, was between the British East India Company and:", ["The Sikh Empire", "The Mughal emperor", "Nepal", "Tibet"], "The treaty ended the war with Nepal and led to British control of hill territories."],
    ["आंग्ल–गोरखा युद्ध के बाद 1816 की सुगौली संधि अंग्रेज़ी ईस्ट इंडिया कंपनी और किसके बीच हुई?", ["सिख साम्राज्य", "मुग़ल सम्राट", "नेपाल", "तिब्बत"], "इस संधि ने नेपाल के साथ युद्ध समाप्त किया और पहाड़ी क्षेत्रों पर अंग्रेज़ों का नियंत्रण स्थापित किया।"]),
  q(4, "hp-gk", "geography", "M", 1,
    ["The Rohtang Tunnel, also called Atal Tunnel, connects Manali with:", ["Kinnaur", "Lahaul valley (Sissu)", "Spiti valley", "Shimla"], "It opened in 2020 and links Manali with Lahaul."],
    ["रोहतांग सुरंग, जिसे अटल सुरंग भी कहते हैं, मनाली को किससे जोड़ती है?", ["किन्नौर", "लाहौल घाटी (सिस्सू)", "स्पीति घाटी", "शिमला"], "यह 2020 में खुली और मनाली को लाहौल से जोड़ती है।"]),
  q(4, "hp-gk", "rivers-lakes", "H", 3,
    ["In which district of Himachal Pradesh is the famous Prashar Lake situated?", ["Kullu", "Chamba", "Sirmaur", "Mandi"], "Prashar Lake is a famous high-altitude lake in Mandi district."],
    ["हिमाचल की प्रसिद्ध पराशर झील किस ज़िले में है?", ["कुल्लू", "चंबा", "सिरमौर", "मंडी"], "पराशर झील मंडी ज़िले की प्रसिद्ध ऊँचाई पर स्थित झील है।"]),
  q(4, "hp-gk", "rivers-lakes", "M", 0,
    ["Which lake in Himachal Pradesh, sacred to Hindus, Buddhists and Sikhs, is known for its floating reed islands?", ["Rewalsar Lake", "Chandratal", "Dal Lake", "Gobind Sagar"], "Rewalsar has floating reed islands and is sacred to Hindus, Buddhists and Sikhs."],
    ["हिमाचल प्रदेश की कौन-सी झील तैरते द्वीपों के लिए प्रसिद्ध है और हिंदुओं, बौद्धों व सिखों के लिए पवित्र है?", ["रिवालसर झील", "चंद्रताल", "डल झील", "गोबिंद सागर"], "रिवालसर में तैरते सरकंडा द्वीप हैं और यह तीन धर्मों के लिए पवित्र है।"]),
  q(4, "hp-gk", "culture-festivals", "M", 2,
    ["The 'Minjar' fair of Chamba is held in the month of:", ["Chaitra", "Magh", "Shravan", "Kartik"], "Minjar is celebrated in the Shravan month, usually July–August."],
    ["चंबा का 'मिंजर' मेला किस मास में लगता है?", ["चैत्र", "माघ", "श्रावण", "कार्तिक"], "मिंजर श्रावण मास में, प्रायः जुलाई–अगस्त में, मनाया जाता है।"]),
  q(4, "hp-gk", "culture-festivals", "H", 1,
    ["The traditional dance 'Nati' is associated with which region of Himachal Pradesh?", ["Kangra plains", "Kullu and Shimla hills", "Una", "Hamirpur"], "Nati is a folk dance of Kullu and the Shimla hills."],
    ["पारंपरिक नृत्य 'नाटी' हिमाचल के किस क्षेत्र से जुड़ा है?", ["कांगड़ा के मैदान", "कुल्लू और शिमला की पहाड़ियाँ", "ऊना", "हमीरपुर"], "नाटी कुल्लू और शिमला की पहाड़ियों का लोक-नृत्य है।"]),
  q(4, "hp-gk", "economy", "M", 3,
    ["Which district of Himachal Pradesh is known for its cement industry around Rajban and Nalagarh?", ["Kullu", "Chamba", "Kinnaur", "Sirmaur and Solan"], "Cement plants stand at Rajban (Sirmaur) and Nalagarh (Solan)."],
    ["हिमाचल प्रदेश का कौन-सा क्षेत्र राजबन और नालागढ़ के सीमेंट उद्योग के लिए जाना जाता है?", ["कुल्लू", "चंबा", "किन्नौर", "सिरमौर और सोलन"], "राजबन (सिरमौर) और नालागढ़ (सोलन) में सीमेंट संयंत्र हैं।"]),
  q(4, "hp-gk", "polity-administration", "H", 0,
    ["The Himachal Pradesh Public Service Commission has its headquarters at:", ["Shimla", "Hamirpur", "Mandi", "Dharamshala"], "HPPSC is at Shimla; HPRCA is at Hamirpur."],
    ["हिमाचल प्रदेश लोक सेवा आयोग का मुख्यालय कहाँ है?", ["शिमला", "हमीरपुर", "मंडी", "धर्मशाला"], "एचपीपीएससी शिमला में है; एचपीआरसीए हमीरपुर में है।"]),
  q(4, "hp-gk", "districts", "M", 2,
    ["Which district of Himachal Pradesh does NOT share a border with Punjab?", ["Una", "Kangra", "Kinnaur", "Hamirpur"], "Kinnaur borders Tibet (China), not Punjab."],
    ["हिमाचल प्रदेश का कौन-सा ज़िला पंजाब के साथ सीमा साझा नहीं करता?", ["ऊना", "कांगड़ा", "किन्नौर", "हमीरपुर"], "किन्नौर की सीमा तिब्बत (चीन) से लगती है, पंजाब से नहीं।"]),
  q(4, "hp-gk", "personalities", "M", 1,
    ["Who is known as the founder (architect) of Himachal Pradesh?", ["Shanta Kumar", "Dr Y. S. Parmar", "Virbhadra Singh", "Prem Kumar Dhumal"], "Dr Parmar is regarded as the architect of Himachal Pradesh."],
    ["हिमाचल प्रदेश का निर्माता (शिल्पी) किसे माना जाता है?", ["शांता कुमार", "डॉ. वाई. एस. परमार", "वीरभद्र सिंह", "प्रेम कुमार धूमल"], "डॉ. परमार को हिमाचल प्रदेश का निर्माता माना जाता है।"]),
];
