// HP TET (TGT Medical) — Full Mock 2, written fresh: Child Development & Pedagogy 30, Hindi 30, English 30,
// Biology 30, Physics & Chemistry 30 (sections as in ./index.ts).

import { q, type PatwariQuestion } from "../patwari/types";

export const medicalMock2: PatwariQuestion[] = [
  // ───────── Section 0: Child Development & Pedagogy (30) ─────────
  q(0, "pedagogy", "child-development", "M", 1,
    ["The stage of language in which a child uses one word to express a whole idea, such as 'milk' for 'I want milk', is the:", ["Babbling stage", "Holophrastic stage", "Telegraphic stage", "Cooing stage"], "One-word sentences appear at about 12–18 months."],
    ["भाषा-विकास की वह अवस्था जिसमें बच्चा एक शब्द से पूरा विचार व्यक्त करता है, जैसे 'दूध' का अर्थ 'मुझे दूध चाहिए', कौन-सी है?", ["बलबलाने की अवस्था", "एक-शब्द वाक्य की अवस्था", "तारवत् (टेलीग्राफ़िक) अवस्था", "कूकने की अवस्था"], "एक-शब्द वाक्य लगभग 12–18 माह में आते हैं।"]),
  q(0, "pedagogy", "child-development", "H", 2,
    ["Noam Chomsky criticised Skinner's view of language acquisition by arguing that:", ["Children learn language only by imitation", "Language needs no brain", "Children have an inborn capacity for grammar", "Language is learnt only at school"], "Chomsky proposed an innate language faculty."],
    ["नोआम चॉम्स्की ने भाषा-अर्जन पर स्किनर के विचार की आलोचना यह कहकर की कि:", ["बच्चे भाषा केवल अनुकरण से सीखते हैं", "भाषा के लिए मस्तिष्क आवश्यक नहीं", "बच्चों में व्याकरण की जन्मजात क्षमता होती है", "भाषा केवल विद्यालय में सीखी जाती है"], "चॉम्स्की ने जन्मजात भाषा-क्षमता का प्रस्ताव दिया।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["Thorndike's experiments on cats in a puzzle box led him to the theory of:", ["Trial-and-error learning (connectionism)", "Classical conditioning", "Insight learning", "Observational learning"], "Thorndike called it connectionism."],
    ["पहेली-पिंजरे में बिल्लियों पर थॉर्नडाइक के प्रयोगों से कौन-सा सिद्धांत निकला?", ["प्रयास-त्रुटि अधिगम (संबंधवाद)", "शास्त्रीय अनुबंधन", "अंतर्दृष्टि अधिगम", "अवलोकनात्मक अधिगम"], "थॉर्नडाइक ने इसे संबंधवाद कहा।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["A 'plateau' on a learning curve shows a period when:", ["Learning is fastest", "Learning is complete", "Learning has been forgotten", "Progress temporarily stops although effort continues"], "Plateaus occur between phases of improvement."],
    ["अधिगम वक्र पर 'पठार' (प्लैटो) उस काल को दर्शाता है जब:", ["सीखना सबसे तेज़ होता है", "सीखना पूरा हो जाता है", "सीखा हुआ भूल जाता है", "प्रयास जारी रहने पर भी प्रगति अस्थायी रूप से रुक जाती है"], "सुधार के चरणों के बीच पठार आते हैं।"]),
  q(0, "pedagogy", "child-development", "M", 2,
    ["Raven's Progressive Matrices is a:", ["Verbal intelligence test", "Personality inventory", "Non-verbal intelligence test", "Achievement test"], "It uses shapes and patterns, not words."],
    ["रैवन प्रोग्रेसिव मैट्रिसेज़ क्या है?", ["शाब्दिक बुद्धि परीक्षण", "व्यक्तित्व सूची", "अशाब्दिक बुद्धि परीक्षण", "उपलब्धि परीक्षण"], "यह आकृतियों और प्रतिरूपों का प्रयोग करता है, शब्दों का नहीं।"]),
  q(0, "pedagogy", "child-development", "H", 1,
    ["The Wechsler scales (WISC, WAIS) measure intelligence through:", ["Only one score on a single task", "Verbal and performance subtests", "Handwriting samples", "Interviews alone"], "They combine verbal and performance scales."],
    ["वेक्स्लर मापनियाँ (डब्ल्यूआईएससी, डब्ल्यूएआईएस) बुद्धि को किस प्रकार मापती हैं?", ["एक ही कार्य पर एक अंक से", "शाब्दिक और निष्पादन उप-परीक्षणों से", "लिखावट के नमूनों से", "केवल साक्षात्कार से"], "ये शाब्दिक और निष्पादन मापनियों को जोड़ती हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["A test that predicts how well a person is likely to perform in future training is an:", ["Achievement test", "Diagnostic test", "Attitude scale", "Aptitude test"], "Aptitude tests measure potential."],
    ["जो परीक्षण यह भविष्यवाणी करता है कि व्यक्ति भावी प्रशिक्षण में कितना अच्छा करेगा, वह है:", ["उपलब्धि परीक्षण", "निदानात्मक परीक्षण", "अभिवृत्ति मापनी", "अभिक्षमता परीक्षण"], "अभिक्षमता परीक्षण क्षमता-संभावना मापते हैं।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["The Kuder Preference Record and Strong Interest Inventory are used to assess a student's:", ["Vocational interests", "Intelligence", "Memory span", "Reaction time"], "They are interest inventories for guidance."],
    ["कुडर प्रेफ़रेंस रिकॉर्ड और स्ट्रॉन्ग इंटरेस्ट इन्वेंटरी का प्रयोग विद्यार्थी की किस बात के आकलन के लिए होता है?", ["व्यावसायिक रुचियों के", "बुद्धि के", "स्मृति-विस्तार के", "प्रतिक्रिया-समय के"], "ये निर्देशन के लिए रुचि-सूचियाँ हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["The MMPI is a widely used:", ["Intelligence test", "Personality inventory", "Memory test", "Reading test"], "The Minnesota Multiphasic Personality Inventory assesses personality and psychopathology."],
    ["एमएमपीआई एक व्यापक रूप से प्रयुक्त क्या है?", ["बुद्धि परीक्षण", "व्यक्तित्व सूची", "स्मृति परीक्षण", "पठन परीक्षण"], "मिनेसोटा मल्टीफ़ेज़िक पर्सनैलिटी इन्वेंटरी व्यक्तित्व और मनोविकृति का आकलन करती है।"]),
  q(0, "pedagogy", "inclusive-education", "H", 2,
    ["Under the RTE Act, a person to be appointed as a teacher in an elementary school must pass the:", ["NET", "GATE", "Teacher Eligibility Test (TET)", "NDA"], "Section 23 requires the TET along with prescribed qualifications."],
    ["आरटीई अधिनियम के अंतर्गत प्रारंभिक विद्यालय में शिक्षक नियुक्त होने के लिए किस परीक्षा में उत्तीर्ण होना आवश्यक है?", ["नेट", "गेट", "शिक्षक पात्रता परीक्षा (टेट)", "एनडीए"], "धारा 23 निर्धारित योग्यता के साथ टेट की अपेक्षा करती है।"]),
  q(0, "pedagogy", "inclusive-education", "H", 3,
    ["The UN Convention on the Rights of the Child was adopted in:", ["1948", "1966", "1979", "1989"], "The UNCRC was adopted in 1989; India ratified it in 1992."],
    ["बाल अधिकारों पर संयुक्त राष्ट्र अभिसमय किस वर्ष अपनाया गया?", ["1948", "1966", "1979", "1989"], "यूएनसीआरसी 1989 में अपनाया गया; भारत ने 1992 में इसकी पुष्टि की।"]),
  q(0, "pedagogy", "inclusive-education", "M", 0,
    ["The POCSO Act, 2012 protects children from:", ["Sexual offences", "Road accidents", "Exam stress", "Child labour in mines only"], "POCSO deals with child sexual abuse and exploitation."],
    ["पॉक्सो अधिनियम 2012 बच्चों को किससे सुरक्षा देता है?", ["यौन अपराधों से", "सड़क दुर्घटनाओं से", "परीक्षा-तनाव से", "केवल खदानों में बाल श्रम से"], "पॉक्सो बाल यौन शोषण और उत्पीड़न से संबंधित है।"]),
  q(0, "pedagogy", "child-development", "M", 2,
    ["Excessive fear or worry that interferes with a student's daily activities is commonly called:", ["Happiness", "Curiosity", "Anxiety", "Motivation"], "Anxiety disorders involve persistent worry."],
    ["अत्यधिक भय या चिंता जो विद्यार्थी की दैनिक गतिविधियों में बाधा डाले, सामान्यतः क्या कहलाती है?", ["प्रसन्नता", "जिज्ञासा", "दुश्चिंता (एंग्ज़ाइटी)", "अभिप्रेरणा"], "दुश्चिंता विकारों में लगातार चिंता रहती है।"]),
  q(0, "pedagogy", "child-development", "H", 1,
    ["Which of these is the best first step when a teacher suspects a pupil is depressed?", ["Publicly question her", "Talk with her privately and involve the counsellor and parents", "Ignore the signs", "Give extra homework"], "Supportive private contact and referral are appropriate."],
    ["जब शिक्षक को संदेह हो कि विद्यार्थी अवसादग्रस्त है, तो सबसे अच्छा पहला कदम कौन-सा है?", ["उससे सबके सामने पूछताछ करना", "उससे एकांत में बात करना तथा परामर्शदाता और अभिभावकों को शामिल करना", "संकेतों की अनदेखी करना", "अतिरिक्त गृहकार्य देना"], "सहयोगी निजी संवाद और संदर्भन उपयुक्त हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["In peer tutoring, a more able pupil:", ["Marks the exam papers", "Takes the teacher's place permanently", "Replaces the textbook", "Helps a classmate to learn"], "Peer tutoring uses learners as helpers of one another."],
    ["सहपाठी शिक्षण (पीयर ट्यूटरिंग) में अधिक सक्षम विद्यार्थी:", ["परीक्षा-पत्र जाँचता है", "शिक्षक का स्थान स्थायी रूप से ले लेता है", "पाठ्यपुस्तक की जगह लेता है", "सहपाठी को सीखने में मदद करता है"], "सहपाठी शिक्षण में शिक्षार्थी एक-दूसरे के सहायक होते हैं।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["In a 'flipped classroom', pupils typically:", ["Study new content at home and practise in class", "Sit facing the back", "Learn only through tests", "Skip homework"], "Content delivery moves outside class; class time is for application."],
    ["'फ़्लिप्ड क्लासरूम' में विद्यार्थी सामान्यतः:", ["नई सामग्री घर पर पढ़ते हैं और अभ्यास कक्षा में करते हैं", "पीछे की ओर मुँह करके बैठते हैं", "केवल परीक्षाओं से सीखते हैं", "गृहकार्य छोड़ देते हैं"], "सामग्री कक्षा के बाहर पढ़ी जाती है; कक्षा-समय अनुप्रयोग के लिए होता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["Using game elements such as points and badges to motivate learning is called:", ["Gamification", "Dictation", "Rote learning", "Detention"], "Gamification adds game mechanics to learning tasks."],
    ["सीखने को प्रेरित करने के लिए अंक और बैज जैसे खेल-तत्वों का उपयोग क्या कहलाता है?", ["गेमिफ़िकेशन", "श्रुतलेख", "रटंत अधिगम", "रोक-थाम"], "गेमिफ़िकेशन सीखने के कार्यों में खेल-तंत्र जोड़ता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["Which is a real advantage of group work in a science class?", ["It eliminates the need for planning", "Pupils learn from each other and develop communication", "It always saves time", "It stops all noise"], "Group work builds collaboration."],
    ["विज्ञान की कक्षा में समूह-कार्य का वास्तविक लाभ कौन-सा है?", ["योजना की आवश्यकता समाप्त हो जाती है", "विद्यार्थी एक-दूसरे से सीखते हैं और संप्रेषण विकसित करते हैं", "यह सदा समय बचाता है", "यह सारा शोर रोक देता है"], "समूह-कार्य सहयोग को बढ़ाता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["Which of these best describes 'authentic assessment'?", ["A multiple-choice test on facts", "A closed-book recall quiz", "A ranking of pupils", "Tasks that resemble real-life situations"], "Authentic tasks ask learners to apply knowledge in realistic contexts."],
    ["'प्रामाणिक आकलन' का सबसे अच्छा वर्णन इनमें से कौन-सा है?", ["तथ्यों पर बहुविकल्पी परीक्षा", "पुस्तक बंद करके याद करने की प्रश्नोत्तरी", "विद्यार्थियों को क्रम देना", "वास्तविक जीवन जैसी परिस्थितियों वाले कार्य"], "प्रामाणिक कार्य शिक्षार्थियों से यथार्थ संदर्भों में ज्ञान का प्रयोग माँगते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["Which statement about teacher-made tests is correct?", ["They are always standardised", "They cannot be valid", "They can be tailored to what was actually taught", "They never need a blueprint"], "Teacher-made tests match classroom objectives."],
    ["शिक्षक-निर्मित परीक्षणों के बारे में कौन-सा कथन सही है?", ["वे सदा मानकीकृत होते हैं", "वे वैध नहीं हो सकते", "उन्हें वास्तव में पढ़ाई गई बातों के अनुरूप बनाया जा सकता है", "उन्हें कभी ब्लू-प्रिंट नहीं चाहिए"], "शिक्षक-निर्मित परीक्षण कक्षा के उद्देश्यों से मेल खाते हैं।"]),
  q(0, "pedagogy", "child-development", "H", 0,
    ["Which type of play, according to Parten, shows children playing together with a shared goal?", ["Cooperative play", "Solitary play", "Onlooker play", "Unoccupied play"], "In cooperative play children organise around a common goal."],
    ["पार्टेन के अनुसार किस प्रकार के खेल में बच्चे साझा लक्ष्य के साथ मिलकर खेलते हैं?", ["सहकारी खेल", "एकाकी खेल", "दर्शक खेल", "अनधिकृत खेल"], "सहकारी खेल में बच्चे साझा लक्ष्य के चारों ओर संगठित होते हैं।"]),
  q(0, "pedagogy", "child-development", "M", 3,
    ["Which of these is a main task of a school counsellor?", ["Setting question papers", "Collecting fees", "Supervising construction", "Helping students with personal, social and career concerns"], "A counsellor supports students' emotional and vocational needs."],
    ["विद्यालय के परामर्शदाता का एक प्रमुख कार्य इनमें से कौन-सा है?", ["प्रश्नपत्र बनाना", "शुल्क एकत्र करना", "निर्माण की निगरानी करना", "विद्यार्थियों की व्यक्तिगत, सामाजिक और कैरियर संबंधी चिंताओं में सहायता करना"], "परामर्शदाता विद्यार्थियों की भावनात्मक और व्यावसायिक आवश्यकताओं में सहायता करता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["Reinforcement is most effective when it follows the desired behaviour:", ["After a long delay", "Immediately", "Only at the year's end", "Randomly, unrelated to behaviour"], "Prompt reinforcement strengthens the connection."],
    ["पुनर्बलन तब सबसे प्रभावी होता है जब वह वांछित व्यवहार के बाद दिया जाए:", ["लंबे विलंब के बाद", "तुरंत", "केवल वर्ष के अंत में", "यादृच्छिक रूप से, व्यवहार से असंबद्ध"], "तत्काल पुनर्बलन संबंध को मज़बूत करता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["The idea that learners construct knowledge and meaning from experience, rather than receive it passively, is the core of:", ["Behaviourism", "Nativism", "Constructivism", "Psychoanalysis"], "Constructivism stresses active meaning-making."],
    ["यह विचार कि शिक्षार्थी अनुभव से ज्ञान और अर्थ का निर्माण करते हैं, निष्क्रिय रूप से ग्रहण नहीं करते, किसका मूल है?", ["व्यवहारवाद", "जन्मजातवाद", "रचनावाद", "मनोविश्लेषण"], "रचनावाद सक्रिय अर्थ-निर्माण पर बल देता है।"]),
  q(0, "pedagogy", "inclusive-education", "M", 0,
    ["Which step helps a child with a hearing impairment to follow a lesson better?", ["Using visual aids and facing the child while speaking", "Speaking with one's back turned", "Speaking very softly", "Avoiding group work"], "Clear lip-reading access and visuals help."],
    ["श्रवण-बाधित बच्चे को पाठ बेहतर समझने में कौन-सा कदम मदद करता है?", ["दृश्य सामग्री का प्रयोग और बोलते समय बच्चे की ओर मुँह रखना", "पीठ फेरकर बोलना", "बहुत धीमे बोलना", "समूह-कार्य से बचना"], "होंठ पढ़ने की स्पष्ट सुविधा और दृश्य सामग्री सहायक हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["A 'learning outcome' is best written as:", ["A topic title", "A teacher's activity", "A time schedule", "A statement of what the learner will be able to do"], "Outcomes describe learner performance."],
    ["'अधिगम निष्पत्ति' को सबसे अच्छा किस रूप में लिखा जाता है?", ["विषय का शीर्षक", "शिक्षक की गतिविधि", "समय-सारणी", "इस कथन के रूप में कि शिक्षार्थी क्या कर सकेगा"], "निष्पत्तियाँ शिक्षार्थी के निष्पादन का वर्णन करती हैं।"]),
  q(0, "pedagogy", "child-development", "H", 1,
    ["The 'Zeigarnik effect' says that people remember:", ["Completed tasks better", "Interrupted or unfinished tasks better", "Only pleasant events", "Only recent events"], "Unfinished tasks stay active in memory."],
    ["'ज़ीगार्निक प्रभाव' के अनुसार लोग किसे बेहतर याद रखते हैं?", ["पूर्ण किए गए कार्यों को", "बाधित या अधूरे कार्यों को", "केवल सुखद घटनाओं को", "केवल हाल की घटनाओं को"], "अधूरे कार्य स्मृति में सक्रिय रहते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["Teaching through stories is especially suitable for young children because stories:", ["Replace all textbooks", "Are always true", "Hold attention and make ideas memorable", "End the need for questions"], "Narrative engages imagination and memory."],
    ["छोटे बच्चों के लिए कहानियों द्वारा शिक्षण विशेष रूप से उपयुक्त है क्योंकि कहानियाँ:", ["सभी पाठ्यपुस्तकों की जगह ले लेती हैं", "सदा सत्य होती हैं", "ध्यान बाँधती हैं और विचारों को यादगार बनाती हैं", "प्रश्नों की आवश्यकता समाप्त कर देती हैं"], "कथा-वाचन कल्पना और स्मृति को जोड़ता है।"]),

  q(0, "pedagogy", "learning-theories", "M", 1,
    ["Which of these is an example of formative assessment?", ["Annual examination", "A class quiz followed by feedback", "Board examination result", "Admission test"], "Formative assessment guides learning during teaching."],
    ["इनमें से रचनात्मक मूल्यांकन का उदाहरण कौन-सा है?", ["वार्षिक परीक्षा", "प्रतिपुष्टि सहित कक्षा-प्रश्नोत्तरी", "बोर्ड परीक्षा परिणाम", "प्रवेश परीक्षा"], "रचनात्मक मूल्यांकन पढ़ाने के दौरान अधिगम को दिशा देता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["The word 'pedagogy' refers to:", ["The art and science of teaching", "The study of plants", "The study of rocks", "A kind of test"], "Pedagogy is about how teaching and learning take place."],
    ["'पेडागॉजी' (शिक्षाशास्त्र) शब्द का अर्थ है:", ["शिक्षण की कला और विज्ञान", "पौधों का अध्ययन", "चट्टानों का अध्ययन", "एक प्रकार की परीक्षा"], "शिक्षाशास्त्र शिक्षण और अधिगम कैसे होता है, इससे संबंधित है।"]),

  // ───────── Section 1: Hindi (30) ─────────
  q(1, "hindi", "sahitya", "M", 3,
    ["'चित्रलेखा', a famous novel on sin and virtue, was written by:", ["यशपाल", "अज्ञेय", "जैनेंद्र", "भगवतीचरण वर्मा"], "Bhagwati Charan Verma wrote Chitralekha (1934)."],
    ["पाप और पुण्य पर आधारित प्रसिद्ध उपन्यास 'चित्रलेखा' किसने लिखा?", ["यशपाल", "अज्ञेय", "जैनेंद्र", "भगवतीचरण वर्मा"], "भगवतीचरण वर्मा ने चित्रलेखा (1934) लिखा।"]),
  q(1, "hindi", "sahitya", "H", 0,
    ["'उसने कहा था', a pioneering short story, is by:", ["चंद्रधर शर्मा गुलेरी", "प्रेमचंद", "जयशंकर प्रसाद", "सुदर्शन"], "Guleri's story (1915) is among the first modern Hindi stories."],
    ["अग्रणी कहानी 'उसने कहा था' किसकी है?", ["चंद्रधर शर्मा गुलेरी", "प्रेमचंद", "जयशंकर प्रसाद", "सुदर्शन"], "गुलेरी की यह कहानी (1915) आधुनिक हिंदी की आरंभिक कहानियों में है।"]),
  q(1, "hindi", "sahitya", "M", 2,
    ["'ठाकुर का कुआँ' and 'कफ़न' are stories by:", ["यशपाल", "जैनेंद्र", "प्रेमचंद", "अमरकांत"], "Both are well-known Premchand stories."],
    ["'ठाकुर का कुआँ' और 'कफ़न' किसकी कहानियाँ हैं?", ["यशपाल", "जैनेंद्र", "प्रेमचंद", "अमरकांत"], "ये दोनों प्रेमचंद की प्रसिद्ध कहानियाँ हैं।"]),
  q(1, "hindi", "sahitya", "H", 1,
    ["Which poet's work 'अंधेरे में' is a landmark of modern Hindi poetry?", ["अज्ञेय", "गजानन माधव मुक्तिबोध", "नागार्जुन", "धूमिल"], "Muktibodh's long poem 'Andhere Mein' is a landmark."],
    ["आधुनिक हिंदी कविता की मील का पत्थर रचना 'अंधेरे में' किस कवि की है?", ["अज्ञेय", "गजानन माधव मुक्तिबोध", "नागार्जुन", "धूमिल"], "मुक्तिबोध की लंबी कविता 'अंधेरे में' मील का पत्थर है।"]),
  q(1, "hindi", "sahitya", "M", 0,
    ["'पृथ्वीराज रासो' is attributed to:", ["चंदबरदाई", "जगनिक", "नरपति नाल्ह", "विद्यापति"], "Chand Bardai is credited with Prithviraj Raso."],
    ["'पृथ्वीराज रासो' का श्रेय किसे दिया जाता है?", ["चंदबरदाई", "जगनिक", "नरपति नाल्ह", "विद्यापति"], "चंदबरदाई को पृथ्वीराज रासो का रचयिता माना जाता है।"]),
  q(1, "hindi", "sahitya", "H", 3,
    ["The 'Padmavat' poet's work is in which language of Hindi literature?", ["Braj", "Khari Boli", "Maithili", "Awadhi"], "Jayasi wrote in Awadhi."],
    ["पद्मावत के कवि की रचना हिंदी साहित्य की किस भाषा में है?", ["ब्रज", "खड़ी बोली", "मैथिली", "अवधी"], "जायसी ने अवधी में लिखा।"]),
  q(1, "hindi", "sahitya", "M", 1,
    ["'जनता पागल हो गई है' and 'अकाल और उसके बाद' are poems by:", ["त्रिलोचन", "नागार्जुन", "शमशेर", "केदारनाथ अग्रवाल"], "Nagarjun wrote 'Akal aur Uske Baad'."],
    ["'अकाल और उसके बाद' कविता किसकी है?", ["त्रिलोचन", "नागार्जुन", "शमशेर", "केदारनाथ अग्रवाल"], "नागार्जुन ने 'अकाल और उसके बाद' लिखी।"]),
  q(1, "hindi", "sandhi-samas", "M", 2,
    ["Split the word 'परमार्थ' into sandhi parts:", ["परम + आर्थ", "परमा + अर्थ", "परम + अर्थ", "पर + मार्थ"], "अ + अ = आ (dirgha sandhi): परम + अर्थ."],
    ["'परमार्थ' का संधि-विच्छेद कीजिए:", ["परम + आर्थ", "परमा + अर्थ", "परम + अर्थ", "पर + मार्थ"], "अ + अ = आ (दीर्घ संधि): परम + अर्थ।"]),
  q(1, "hindi", "sandhi-samas", "H", 1,
    ["Split the word 'दुरात्मा' into sandhi parts:", ["दू + रात्मा", "दुः + आत्मा", "दुर + आत्मा", "दुस् + आत्मा"], "Visarg before a vowel changes to र्: दुः + आत्मा."],
    ["'दुरात्मा' का संधि-विच्छेद कीजिए:", ["दू + रात्मा", "दुः + आत्मा", "दुर + आत्मा", "दुस् + आत्मा"], "स्वर से पहले विसर्ग का र् हो जाता है: दुः + आत्मा।"]),
  q(1, "hindi", "sandhi-samas", "M", 0,
    ["Split the word 'नयन' into sandhi parts:", ["ने + अन", "न + यन", "नय + अन", "नी + यन"], "ए + अ = अय् + अ (ayadi): ने + अन."],
    ["'नयन' का संधि-विच्छेद कीजिए:", ["ने + अन", "न + यन", "नय + अन", "नी + यन"], "ए + अ = अय् + अ (अयादि): ने + अन।"]),
  q(1, "hindi", "sandhi-samas", "H", 3,
    ["'दिन-रात' (दिन और रात) is an example of:", ["तत्पुरुष समास", "बहुव्रीहि समास", "कर्मधारय समास", "द्वंद्व समास"], "Both parts are equal in importance and joined by 'और': dvandva."],
    ["'दिन-रात' (दिन और रात) किसका उदाहरण है?", ["तत्पुरुष समास", "बहुव्रीहि समास", "कर्मधारय समास", "द्वंद्व समास"], "दोनों पद समान महत्त्व के हैं और 'और' से जुड़े हैं: द्वंद्व।"]),
  q(1, "hindi", "sandhi-samas", "M", 2,
    ["'नीलगगन' (नीला है जो गगन) is an example of:", ["द्वंद्व समास", "द्विगु समास", "कर्मधारय समास", "अव्ययीभाव समास"], "An adjective and noun for the same thing: karmadharay."],
    ["'नीलगगन' (नीला है जो गगन) किसका उदाहरण है?", ["द्वंद्व समास", "द्विगु समास", "कर्मधारय समास", "अव्ययीभाव समास"], "एक ही वस्तु के विशेषण और विशेष्य: कर्मधारय।"]),
  q(1, "hindi", "paryay-vilom", "M", 1,
    ["Choose the synonym of 'चाँद':", ["दिनकर", "शशि", "तारा", "पवन"], "चाँद, शशि and सोम are synonyms."],
    ["'चाँद' का पर्यायवाची चुनिए:", ["दिनकर", "शशि", "तारा", "पवन"], "चाँद, शशि और सोम पर्यायवाची हैं।"]),
  q(1, "hindi", "paryay-vilom", "H", 3,
    ["Choose the synonym of 'वारिद':", ["पृथ्वी", "नदी", "अग्नि", "बादल"], "वारिद, जलद and घन mean cloud."],
    ["'वारिद' का पर्यायवाची चुनिए:", ["पृथ्वी", "नदी", "अग्नि", "बादल"], "वारिद, जलद और घन का अर्थ बादल है।"]),
  q(1, "hindi", "paryay-vilom", "M", 0,
    ["Choose the antonym of 'अमृत':", ["विष", "सुधा", "पेय", "रस"], "अमृत is nectar; विष is poison."],
    ["'अमृत' का विलोम चुनिए:", ["विष", "सुधा", "पेय", "रस"], "अमृत का अर्थ पीयूष है; विष का अर्थ ज़हर है।"]),
  q(1, "hindi", "paryay-vilom", "H", 2,
    ["Choose the antonym of 'अनुराग':", ["प्रेम", "लगाव", "विराग", "आसक्ति"], "अनुराग is attachment; विराग is detachment."],
    ["'अनुराग' का विलोम चुनिए:", ["प्रेम", "लगाव", "विराग", "आसक्ति"], "अनुराग का अर्थ लगाव है; विराग का अर्थ अनासक्ति है।"]),
  q(1, "hindi", "ek-shabd", "M", 3,
    ["Which single word means 'जो सदा से चला आ रहा हो'?", ["नवीन", "आधुनिक", "तात्कालिक", "सनातन"], "सनातन means eternal."],
    ["'जो सदा से चला आ रहा हो' के लिए एक शब्द कौन-सा है?", ["नवीन", "आधुनिक", "तात्कालिक", "सनातन"], "सनातन का अर्थ शाश्वत है।"]),
  q(1, "hindi", "ek-shabd", "H", 0,
    ["Which single word means 'जो कानून के विरुद्ध हो'?", ["अवैध", "वैध", "न्यायसंगत", "उचित"], "अवैध means illegal."],
    ["'जो कानून के विरुद्ध हो' के लिए एक शब्द कौन-सा है?", ["अवैध", "वैध", "न्यायसंगत", "उचित"], "अवैध का अर्थ कानून-विरुद्ध है।"]),
  q(1, "hindi", "ek-shabd", "M", 2,
    ["Which single word means 'जो अपनी इंद्रियों को वश में रखे'?", ["भोगी", "विलासी", "जितेंद्रिय", "आसक्त"], "जितेंद्रिय has mastery over the senses."],
    ["'जो अपनी इंद्रियों को वश में रखे' के लिए एक शब्द कौन-सा है?", ["भोगी", "विलासी", "जितेंद्रिय", "आसक्त"], "जितेंद्रिय इंद्रियों पर नियंत्रण रखता है।"]),
  q(1, "hindi", "muhavare", "H", 1,
    ["Meaning of the idiom 'अपना उल्लू सीधा करना':", ["उल्लू पालना", "स्वार्थ सिद्ध करना", "रात जागना", "निशाना लगाना"], "The idiom means to serve one's own interest."],
    ["मुहावरे 'अपना उल्लू सीधा करना' का अर्थ है:", ["उल्लू पालना", "स्वार्थ सिद्ध करना", "रात जागना", "निशाना लगाना"], "इस मुहावरे का अर्थ अपना मतलब निकालना है।"]),
  q(1, "hindi", "muhavare", "M", 3,
    ["Meaning of the idiom 'कमर कसना':", ["कमर में दर्द होना", "पट्टा बाँधना", "आराम करना", "किसी कार्य के लिए तैयार होना"], "The idiom means to get ready for a task."],
    ["मुहावरे 'कमर कसना' का अर्थ है:", ["कमर में दर्द होना", "पट्टा बाँधना", "आराम करना", "किसी कार्य के लिए तैयार होना"], "इस मुहावरे का अर्थ किसी कार्य के लिए कटिबद्ध होना है।"]),
  q(1, "hindi", "muhavare", "H", 2,
    ["Meaning of the proverb 'दूध का दूध पानी का पानी':", ["मिलावट करना", "दूध बेचना", "सही न्याय करना", "दूध उबालना"], "The proverb means impartial, fair judgement."],
    ["लोकोक्ति 'दूध का दूध पानी का पानी' का अर्थ है:", ["मिलावट करना", "दूध बेचना", "सही न्याय करना", "दूध उबालना"], "इसका अर्थ निष्पक्ष, सही न्याय करना है।"]),
  q(1, "hindi", "shuddh-vartani", "M", 0,
    ["Pick the correct spelling of the word meaning 'respect':", ["सम्मान", "सन्मान", "समान्न", "सम्मांन"], "The standard spelling is सम्मान."],
    ["'आदर' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["सम्मान", "सन्मान", "समान्न", "सम्मांन"], "मानक वर्तनी सम्मान है।"]),
  q(1, "hindi", "shuddh-vartani", "H", 3,
    ["Pick the correct spelling of the word meaning 'author':", ["लेखिक", "लेखक्", "लेखख", "लेखक"], "The correct form is लेखक."],
    ["'लिखने वाला' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["लेखिक", "लेखक्", "लेखख", "लेखक"], "शुद्ध रूप लेखक है।"]),
  q(1, "hindi", "vyakaran", "M", 2,
    ["The word 'पढ़ाई' is formed from 'पढ़' by adding which suffix?", ["-ता", "-पन", "-आई", "-ई"], "The suffix -आई forms abstract nouns."],
    ["'पढ़' में कौन-सा प्रत्यय जोड़ने से 'पढ़ाई' बनता है?", ["-ता", "-पन", "-आई", "-ई"], "-आई प्रत्यय भाववाचक संज्ञा बनाता है।"]),
  q(1, "hindi", "vyakaran", "H", 1,
    ["In 'रमेश दौड़कर आया', the word 'दौड़कर' is a:", ["संज्ञा", "पूर्वकालिक कृदंत", "विशेषण", "सर्वनाम"], "The -कर form shows an action completed before another: purvakalik kridant."],
    ["'रमेश दौड़कर आया' में 'दौड़कर' क्या है?", ["संज्ञा", "पूर्वकालिक कृदंत", "विशेषण", "सर्वनाम"], "-कर रूप किसी अन्य क्रिया से पहले पूरी हुई क्रिया बताता है: पूर्वकालिक कृदंत।"]),
  q(1, "hindi", "vyakaran", "M", 3,
    ["Which of these words is a 'तद्भव' word?", ["अग्नि", "कर्म", "सूर्य", "आग"], "आग is the tadbhav form of अग्नि."],
    ["इनमें से कौन-सा शब्द 'तद्भव' है?", ["अग्नि", "कर्म", "सूर्य", "आग"], "आग, अग्नि का तद्भव रूप है।"]),
  q(1, "hindi", "alankar-ras", "H", 0,
    ["'सुनत जोग संदेसु आली' – the sthayi bhav of the ras in a viraha poem is typically:", ["रति", "क्रोध", "भय", "उत्साह"], "Viyog Shringar has rati as its sthayi bhav."],
    ["वियोग-शृंगार की किसी कविता के रस का स्थायी भाव प्रायः क्या होता है?", ["रति", "क्रोध", "भय", "उत्साह"], "वियोग शृंगार का स्थायी भाव रति है।"]),
  q(1, "hindi", "alankar-ras", "M", 2,
    ["'हाय-हाय! यह कैसी विपदा आ गई' – this line expresses which ras?", ["हास्य", "वीर", "करुण", "अद्भुत"], "Grief and pity make it karun ras."],
    ["'हाय-हाय! यह कैसी विपदा आ गई' – यह पंक्ति किस रस को व्यक्त करती है?", ["हास्य", "वीर", "करुण", "अद्भुत"], "शोक और करुणा इसे करुण रस बनाते हैं।"]),

  q(1, "hindi", "paryay-vilom", "M", 2,
    ["Choose the synonym of 'दीपक':", ["जल", "नभ", "दीया", "पवन"], "दीपक, दीया and दीप all mean a lamp."],
    ["'दीपक' का पर्यायवाची चुनिए:", ["जल", "नभ", "दीया", "पवन"], "दीपक, दीया और दीप का अर्थ दीप है।"]),

  // ───────── Section 2: English (30) ─────────
  q(2, "english", "literature", "M", 1,
    ["'A Midsummer Night's Dream' is a comedy by:", ["Ben Jonson", "William Shakespeare", "Marlowe", "Thomas Kyd"], "Shakespeare wrote it around 1595."],
    ["'A Midsummer Night's Dream' किसकी हास्य-रचना है?", ["बेन जॉनसन", "विलियम शेक्सपियर", "मार्लो", "थॉमस किड"], "शेक्सपियर ने इसे लगभग 1595 में लिखा।"]),
  q(2, "english", "literature", "H", 3,
    ["'Songs of Innocence' and 'Songs of Experience' were written by:", ["John Donne", "Robert Burns", "William Wordsworth", "William Blake"], "Blake published them in 1789 and 1794."],
    ["'Songs of Innocence' और 'Songs of Experience' किसने लिखे?", ["जॉन डन", "रॉबर्ट बर्न्स", "विलियम वर्ड्सवर्थ", "विलियम ब्लेक"], "ब्लेक ने इन्हें 1789 और 1794 में प्रकाशित किया।"]),
  q(2, "english", "literature", "M", 0,
    ["'Midnight's Children' is a Booker-winning novel by:", ["Salman Rushdie", "Vikram Seth", "Amitav Ghosh", "Anita Desai"], "Rushdie's novel won the Booker in 1981."],
    ["बुकर पुरस्कार विजेता उपन्यास 'Midnight's Children' किसका है?", ["सलमान रुश्दी", "विक्रम सेठ", "अमिताव घोष", "अनीता देसाई"], "रुश्दी के उपन्यास ने 1981 में बुकर जीता।"]),
  q(2, "english", "literature", "H", 2,
    ["The poem 'Stopping by Woods on a Snowy Evening' ends with the line:", ["Do not go gentle into that good night", "I wandered lonely as a cloud", "And miles to go before I sleep", "Water, water, everywhere"], "Frost's poem repeats 'And miles to go before I sleep'."],
    ["कविता 'Stopping by Woods on a Snowy Evening' किस पंक्ति पर समाप्त होती है?", ["Do not go gentle into that good night", "I wandered lonely as a cloud", "And miles to go before I sleep", "Water, water, everywhere"], "फ़्रॉस्ट की कविता 'And miles to go before I sleep' दोहराती है।"]),
  q(2, "english", "grammar", "M", 3,
    ["Fill in the blank: 'The students were excited ___ the trip.'", ["with", "for", "on", "about"], "'Excited about' is the common collocation."],
    ["रिक्त स्थान भरिए: 'The students were excited ___ the trip.'", ["with", "for", "on", "about"], "'Excited about' सामान्य प्रयोग है।"]),
  q(2, "english", "grammar", "H", 0,
    ["Choose the correct form: 'It is high time you ___ your homework.'", ["did", "do", "will do", "have been doing"], "'It is high time' takes the past subjunctive."],
    ["सही रूप चुनिए: 'It is high time you ___ your homework.'", ["did", "do", "will do", "have been doing"], "'It is high time' के साथ past subjunctive आता है।"]),
  q(2, "english", "grammar", "M", 2,
    ["Fill in the blank: 'She sings ___ than her sister.'", ["good", "best", "better", "more good"], "'Better' is the comparative of 'well'."],
    ["रिक्त स्थान भरिए: 'She sings ___ than her sister.'", ["good", "best", "better", "more good"], "'Better', 'well' का तुलनात्मक रूप है।"]),
  q(2, "english", "grammar", "H", 1,
    ["Choose the correct pair: 'Not only the teacher ___ also the students ___ present.'", ["but / was", "but / were", "and / was", "or / is"], "'Not only … but also' pairs with the nearer subject's verb."],
    ["सही जोड़ी चुनिए: 'Not only the teacher ___ also the students ___ present.'", ["but / was", "but / were", "and / was", "or / is"], "'Not only … but also' के साथ निकटतम कर्ता की क्रिया आती है।"]),
  q(2, "english", "grammar", "M", 0,
    ["Fill in the blank: 'He speaks as if he ___ the owner.'", ["were", "is", "was being", "will be"], "'As if' with an unreal comparison takes 'were'."],
    ["रिक्त स्थान भरिए: 'He speaks as if he ___ the owner.'", ["were", "is", "was being", "will be"], "अवास्तविक तुलना में 'as if' के साथ 'were' आता है।"]),
  q(2, "english", "error-spotting", "H", 3,
    ["Find the part with an error: 'He is (A) the tallest (B) of (C) the two brothers. (D)'", ["A", "B", "C", "D"], "For two persons use the comparative: 'the taller of the two'."],
    ["त्रुटि वाला भाग चुनिए: 'He is (A) the tallest (B) of (C) the two brothers. (D)'", ["A", "B", "C", "D"], "दो व्यक्तियों के लिए तुलनात्मक रूप आता है: 'the taller of the two'।"]),
  q(2, "english", "error-spotting", "M", 1,
    ["Find the part with an error: 'The sceneries (A) of Kangra (B) are (C) beautiful. (D)'", ["A", "B", "C", "D"], "'Scenery' is uncountable and has no plural."],
    ["त्रुटि वाला भाग चुनिए: 'The sceneries (A) of Kangra (B) are (C) beautiful. (D)'", ["A", "B", "C", "D"], "'Scenery' अगणनीय है और इसका बहुवचन नहीं होता।"]),
  q(2, "english", "error-spotting", "H", 2,
    ["Find the part with an error: 'She said (A) that she had (B) seen him (C) yesterday. (D)'", ["A", "B", "D", "C"], "In reported speech 'yesterday' becomes 'the day before'."],
    ["त्रुटि वाला भाग चुनिए: 'She said (A) that she had (B) seen him (C) yesterday. (D)'", ["A", "B", "D", "C"], "Reported speech में 'yesterday', 'the day before' हो जाता है।"]),
  q(2, "english", "voice-speech", "M", 2,
    ["Change to the passive: 'People respect honest persons.'", ["Honest persons respect people.", "Honest persons are respecting by people.", "Honest persons are respected by people.", "Honest persons were respected."], "Simple present passive: are + past participle."],
    ["Passive में बदलिए: 'People respect honest persons.'", ["Honest persons respect people.", "Honest persons are respecting by people.", "Honest persons are respected by people.", "Honest persons were respected."], "Simple present का passive: are + past participle।"]),
  q(2, "english", "voice-speech", "H", 1,
    ["Change to indirect speech: 'He said, \"I have finished my work.\"'", ["He said that he has finished his work.", "He said that he had finished his work.", "He said that I had finished my work.", "He said he finished his work then."], "Present perfect becomes past perfect."],
    ["Indirect speech में बदलिए: 'He said, \"I have finished my work.\"'", ["He said that he has finished his work.", "He said that he had finished his work.", "He said that I had finished my work.", "He said he finished his work then."], "Present perfect, past perfect में बदलता है।"]),
  q(2, "english", "vocabulary", "H", 0,
    ["Which word is nearest in meaning to 'BENIGN'?", ["Harmless", "Cruel", "Poisonous", "Harsh"], "A benign tumour is not harmful."],
    ["'BENIGN' के निकटतम अर्थ वाला शब्द कौन-सा है?", ["Harmless", "Cruel", "Poisonous", "Harsh"], "Benign ट्यूमर हानिकारक नहीं होता।"]),
  q(2, "english", "synonyms-antonyms", "M", 2,
    ["The antonym of 'ASCEND' is:", ["Climb", "Rise", "Descend", "Mount"], "Ascend means go up; descend means go down."],
    ["'ASCEND' का विलोम है:", ["Climb", "Rise", "Descend", "Mount"], "Ascend का अर्थ ऊपर जाना है; descend का अर्थ नीचे आना है।"]),
  q(2, "english", "synonyms-antonyms", "H", 3,
    ["The antonym of 'DILIGENCE' is:", ["Hard work", "Care", "Effort", "Laziness"], "Diligence is steady effort; laziness is its opposite."],
    ["'DILIGENCE' का विलोम है:", ["Hard work", "Care", "Effort", "Laziness"], "Diligence सतत परिश्रम है; laziness उसका उलटा है।"]),
  q(2, "english", "idioms", "M", 1,
    ["'To spill the beans' means to:", ["Cook a meal", "Reveal a secret", "Waste food", "Make a mess"], "The idiom means to disclose confidential information."],
    ["'to spill the beans' का अर्थ है:", ["भोजन पकाना", "रहस्य प्रकट कर देना", "खाना बर्बाद करना", "गंदगी फैलाना"], "इस मुहावरे का अर्थ गोपनीय बात उजागर करना है।"]),
  q(2, "english", "idioms", "H", 2,
    ["'To add fuel to the fire' means to:", ["Light a lamp", "Make a situation worse", "Cook food", "Save energy"], "It means to make an angry situation more intense."],
    ["'to add fuel to the fire' का अर्थ है:", ["दीपक जलाना", "स्थिति को और बिगाड़ना", "भोजन पकाना", "ऊर्जा बचाना"], "इसका अर्थ क्रोधपूर्ण स्थिति को और भड़काना है।"]),
  q(2, "english", "idioms", "M", 3,
    ["'To keep an eye on' someone means to:", ["Blink often", "Close one's eyes", "Hurt his eye", "Watch him carefully"], "It means to observe closely."],
    ["किसी पर 'keep an eye on' का अर्थ है:", ["बार-बार पलक झपकाना", "आँखें बंद करना", "उसकी आँख को चोट पहुँचाना", "उस पर बारीकी से नज़र रखना"], "इसका अर्थ ध्यान से देखते रहना है।"]),
  q(2, "english", "one-word", "M", 0,
    ["Which single word means 'a person who writes the biography of another'?", ["Biographer", "Autobiographer", "Novelist", "Historian"], "A biographer writes about someone else's life."],
    ["'किसी अन्य की जीवनी लिखने वाला' के लिए एक शब्द कौन-सा है?", ["Biographer", "Autobiographer", "Novelist", "Historian"], "Biographer किसी और के जीवन के बारे में लिखता है।"]),
  q(2, "english", "one-word", "H", 3,
    ["Which single word means 'to cure all diseases'?", ["Curative", "Remedial", "Preventive", "Panacea"], "A panacea is a universal remedy."],
    ["'सब रोगों का इलाज' के लिए एक शब्द कौन-सा है?", ["Curative", "Remedial", "Preventive", "Panacea"], "Panacea सर्वरोगहारी उपाय है।"]),
  q(2, "english", "one-word", "M", 1,
    ["Which single word means 'a place where plants are grown under glass'?", ["Orchard", "Greenhouse", "Aquarium", "Nursery"], "Plants in a greenhouse grow under glass."],
    ["'जहाँ काँच के नीचे पौधे उगाए जाते हैं' उस स्थान के लिए एक शब्द कौन-सा है?", ["Orchard", "Greenhouse", "Aquarium", "Nursery"], "ग्रीनहाउस में पौधे काँच के नीचे उगते हैं।"]),
  q(2, "english", "spelling", "H", 2,
    ["Select the correct spelling of the verb meaning 'to get better after illness':", ["Recuperate", "Recooperate", "Recuparate", "Recuperete"], "The word is recuperate."],
    ["'बीमारी के बाद स्वस्थ होना' अर्थ वाली क्रिया की सही वर्तनी चुनिए:", ["Recooperate", "Recuparate", "Recuperate", "Recuperete"], "सही शब्द recuperate है।"]),
  q(2, "english", "spelling", "M", 0,
    ["Select the correct spelling of the noun meaning 'knowledge gained by study':", ["Science", "Sciense", "Scince", "Sience"], "The word is science."],
    ["'अध्ययन से प्राप्त ज्ञान' अर्थ वाले संज्ञा की सही वर्तनी चुनिए:", ["Science", "Sciense", "Scince", "Sience"], "सही शब्द science है।"]),
  q(2, "english", "comprehension", "M", 3,
    ["Which type of question encourages pupils to give personal opinions on a story?", ["What is the title?", "Who wrote it?", "How many paragraphs are there?", "Do you agree with what the girl did, and why?"], "Evaluative questions invite opinions with reasons."],
    ["कहानी पर विद्यार्थियों को व्यक्तिगत राय देने के लिए कौन-सा प्रश्न-प्रकार प्रेरित करता है?", ["शीर्षक क्या है?", "किसने लिखा?", "कितने अनुच्छेद हैं?", "क्या तुम लड़की के कार्य से सहमत हो, और क्यों?"], "मूल्यांकनात्मक प्रश्न कारण सहित राय आमंत्रित करते हैं।"]),
  q(2, "english", "comprehension", "H", 1,
    ["Teaching grammar by letting pupils discover the rule from many examples is called the:", ["Deductive approach", "Inductive approach", "Translation approach", "Dictation approach"], "Induction moves from examples to the rule."],
    ["अनेक उदाहरणों से नियम की खोज कराकर व्याकरण पढ़ाना क्या कहलाता है?", ["निगमनात्मक उपागम", "आगमनात्मक उपागम", "अनुवाद उपागम", "श्रुतलेख उपागम"], "आगमन उदाहरणों से नियम की ओर बढ़ता है।"]),
  q(2, "english", "comprehension", "M", 2,
    ["Which of these is a good way to check a pupil's reading comprehension?", ["Counting the pages she read", "Timing her handwriting", "Asking her to retell the passage in her own words", "Checking her uniform"], "Retelling shows understanding."],
    ["विद्यार्थी का पठन-बोध जाँचने का अच्छा तरीका इनमें से कौन-सा है?", ["उसके पढ़े पन्ने गिनना", "उसकी लिखावट का समय नापना", "उससे अनुच्छेद अपने शब्दों में दोहराने को कहना", "उसकी वर्दी जाँचना"], "पुनः-कथन समझ को दर्शाता है।"]),
  q(2, "english", "grammar", "H", 3,
    ["Which sentence correctly describes work that began in 2018 and still continues?", ["I am working here since 2018.", "I worked here since 2018.", "I will be working here since 2018.", "I have been working here since 2018."], "A continuing action from a past point takes the present perfect continuous."],
    ["अतीत के किसी बिंदु से जारी क्रिया के लिए सही वाक्य चुनिए।", ["I am working here since 2018.", "I worked here since 2018.", "I will be working here since 2018.", "I have been working here since 2018."], "अतीत से चली आ रही क्रिया के लिए present perfect continuous आता है।"]),
  q(2, "english", "grammar", "M", 2,
    ["Fill in the blank: 'I enjoy ___ in the garden in the morning.'", ["to walk", "walk", "walking", "walked"], "'Enjoy' is followed by a gerund."],
    ["रिक्त स्थान भरिए: 'I enjoy ___ in the garden in the morning.'", ["to walk", "walk", "walking", "walked"], "'Enjoy' के बाद gerund आता है।"]),

  // ───────── Section 3: Biology (30) ─────────
  q(3, "biology", "cell-biology", "M", 0,
    ["The number of chromosomes in a normal human body (somatic) cell is:", ["46", "23", "44", "48"], "Humans have 23 pairs, i.e. 46 chromosomes."],
    ["सामान्य मानव शरीर (कायिक) कोशिका में गुणसूत्रों की संख्या है:", ["46", "23", "44", "48"], "मनुष्य में 23 जोड़े, यानी 46 गुणसूत्र होते हैं।"], "46"),
  q(3, "biology", "cell-biology", "H", 2,
    ["Meiosis results in the formation of:", ["Two diploid cells", "Four diploid cells", "Four haploid cells", "One haploid cell"], "Meiosis halves the chromosome number to give four haploid gametes."],
    ["अर्धसूत्री विभाजन (मियोसिस) से क्या बनता है?", ["दो द्विगुणित कोशिकाएँ", "चार द्विगुणित कोशिकाएँ", "चार अगुणित कोशिकाएँ", "एक अगुणित कोशिका"], "मियोसिस गुणसूत्र संख्या आधी करके चार अगुणित युग्मक देता है।"]),
  q(3, "biology", "cell-biology", "M", 1,
    ["Mitosis is the type of cell division that is needed for:", ["Gamete formation", "Growth and repair", "Crossing over", "Formation of sperm only"], "Mitosis produces identical cells for growth and repair."],
    ["समसूत्री विभाजन (माइटोसिस) किसके लिए आवश्यक है?", ["युग्मक निर्माण", "वृद्धि और मरम्मत", "जीन विनिमय", "केवल शुक्राणु निर्माण"], "माइटोसिस वृद्धि और मरम्मत के लिए समान कोशिकाएँ बनाता है।"]),
  q(3, "biology", "cell-biology", "H", 3,
    ["The net gain of ATP from one molecule of glucose in glycolysis is:", ["38", "36", "4", "2"], "Glycolysis makes 4 ATP but uses 2, net 2."],
    ["ग्लाइकोलिसिस में ग्लूकोज़ के एक अणु से ATP का शुद्ध लाभ कितना है?", ["38", "36", "4", "2"], "ग्लाइकोलिसिस 4 ATP बनाता है पर 2 खर्च करता है, शुद्ध 2।"], "4-2"),
  q(3, "biology", "cell-biology", "M", 2,
    ["The 'currency' of energy in cells is:", ["DNA", "RNA", "ATP", "Glucose only"], "ATP stores and supplies energy for cellular work."],
    ["कोशिकाओं में ऊर्जा की 'मुद्रा' क्या है?", ["डीएनए", "आरएनए", "एटीपी", "केवल ग्लूकोज़"], "एटीपी कोशिकीय कार्य के लिए ऊर्जा संचित करता और देता है।"]),
  q(3, "biology", "genetics-evolution", "H", 1,
    ["The enzyme that joins DNA fragments in genetic engineering is:", ["Restriction endonuclease", "DNA ligase", "DNA polymerase", "Helicase"], "DNA ligase seals fragments together."],
    ["आनुवंशिक अभियांत्रिकी में डीएनए खंडों को जोड़ने वाला एंज़ाइम है:", ["रेस्ट्रिक्शन एंडोन्यूक्लिएज़", "डीएनए लाइगेज़", "डीएनए पॉलीमरेज़", "हेलिकेज़"], "डीएनए लाइगेज़ खंडों को जोड़ता है।"]),
  q(3, "biology", "genetics-evolution", "M", 0,
    ["Bt cotton is a genetically modified crop resistant to:", ["Bollworm", "Drought only", "Frost", "Salinity only"], "Bt toxin protects the plant against bollworm."],
    ["बीटी कपास एक आनुवंशिक रूप से रूपांतरित फ़सल है जो किसके प्रति प्रतिरोधी है?", ["बॉलवर्म", "केवल सूखे", "पाले", "केवल लवणता"], "बीटी विष पौधे को बॉलवर्म से बचाता है।"]),
  q(3, "biology", "genetics-evolution", "H", 3,
    ["PCR (polymerase chain reaction) is used to:", ["Digest food", "Count blood cells", "Measure pH", "Make many copies of a DNA segment"], "PCR amplifies DNA."],
    ["पीसीआर (पॉलीमरेज़ शृंखला अभिक्रिया) का प्रयोग किसलिए होता है?", ["भोजन पचाने के लिए", "रक्त कोशिकाएँ गिनने के लिए", "pH मापने के लिए", "डीएनए खंड की अनेक प्रतियाँ बनाने के लिए"], "पीसीआर डीएनए का प्रवर्धन करता है।"]),
  q(3, "biology", "genetics-evolution", "M", 2,
    ["Organs like the human arm and a whale's flipper, with a similar basic structure, are called:", ["Analogous organs", "Vestigial organs", "Homologous organs", "Accessory organs"], "Homologous organs share an origin but may differ in function."],
    ["मानव भुजा और व्हेल के पख जैसे समान मूल संरचना वाले अंग कहलाते हैं:", ["समवृत्ति अंग", "अवशेषी अंग", "समजात अंग", "सहायक अंग"], "समजात अंगों की उत्पत्ति समान होती है पर कार्य भिन्न हो सकते हैं।"]),
  q(3, "biology", "genetics-evolution", "H", 0,
    ["Darwin's theory of evolution is based on:", ["Natural selection", "Inheritance of acquired characters", "Mutation only", "Spontaneous generation"], "Darwin proposed natural selection."],
    ["डार्विन का विकास-सिद्धांत किस पर आधारित है?", ["प्राकृतिक चयन", "अर्जित लक्षणों की वंशागति", "केवल उत्परिवर्तन", "स्वतः उत्पत्ति"], "डार्विन ने प्राकृतिक चयन का प्रस्ताव दिया।"]),
  q(3, "biology", "human-physiology", "M", 3,
    ["Antibodies are produced by:", ["Red blood cells", "Platelets", "Neurons", "B lymphocytes"], "B cells secrete antibodies."],
    ["प्रतिरक्षी (ऐंटीबॉडी) का निर्माण कौन करता है?", ["लाल रुधिर कोशिकाएँ", "प्लेटलेट्स", "न्यूरॉन", "बी लसीकाणु"], "बी कोशिकाएँ प्रतिरक्षी स्रावित करती हैं।"]),
  q(3, "biology", "human-physiology", "M", 1,
    ["The hormone that controls blood calcium by acting on bones is secreted by the:", ["Pancreas", "Parathyroid glands", "Adrenal glands", "Pituitary only"], "Parathyroid hormone raises blood calcium."],
    ["अस्थियों पर क्रिया करके रक्त कैल्सियम नियंत्रित करने वाला हार्मोन किसके द्वारा स्रावित होता है?", ["अग्न्याशय", "पैराथायरॉइड ग्रंथियाँ", "अधिवृक्क ग्रंथियाँ", "केवल पीयूष"], "पैराथायरॉइड हार्मोन रक्त कैल्सियम बढ़ाता है।"]),
  q(3, "biology", "human-physiology", "H", 2,
    ["The hormone that prepares the body for 'fight or flight' is:", ["Insulin", "Thyroxine", "Adrenaline", "Oestrogen"], "Adrenaline raises heart rate and alertness."],
    ["शरीर को 'लड़ो या भागो' के लिए तैयार करने वाला हार्मोन है:", ["इंसुलिन", "थायरॉक्सिन", "एड्रेनालिन", "ईस्ट्रोजन"], "एड्रेनालिन हृदय-गति और सतर्कता बढ़ाता है।"]),
  q(3, "biology", "human-physiology", "M", 0,
    ["Fertilisation in humans normally takes place in the:", ["Fallopian tube (oviduct)", "Uterus", "Vagina", "Ovary"], "The sperm meets the egg in the oviduct."],
    ["मनुष्य में निषेचन सामान्यतः कहाँ होता है?", ["अंडवाहिनी (फैलोपियन नलिका)", "गर्भाशय", "योनि", "अंडाशय"], "शुक्राणु अंडाणु से अंडवाहिनी में मिलता है।"]),
  q(3, "biology", "human-physiology", "H", 3,
    ["In the menstrual cycle, ovulation typically occurs around the:", ["1st day", "7th day", "21st day", "14th day"], "Ovulation is about mid-cycle, around day 14."],
    ["मासिक चक्र में अंडोत्सर्ग सामान्यतः लगभग किस दिन होता है?", ["पहले दिन", "7वें दिन", "21वें दिन", "14वें दिन"], "अंडोत्सर्ग चक्र के मध्य, लगभग 14वें दिन, होता है।"], "14"),
  q(3, "biology", "human-physiology", "M", 2,
    ["The pacemaker of the human heart is the:", ["Aortic valve", "Left ventricle", "Sinoatrial (SA) node", "Pulmonary vein"], "The SA node initiates each heartbeat."],
    ["मानव हृदय का गति-निर्धारक (पेसमेकर) है:", ["महाधमनी कपाट", "बायाँ निलय", "सिनोएट्रियल (एसए) नोड", "फुफ्फुस शिरा"], "एसए नोड प्रत्येक धड़कन आरंभ करता है।"]),
  q(3, "biology", "human-physiology", "H", 1,
    ["The part of the human brain that controls balance and coordination of movement is the:", ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"], "The cerebellum coordinates posture and movement."],
    ["मानव मस्तिष्क का वह भाग जो संतुलन और गति के समन्वय को नियंत्रित करता है:", ["प्रमस्तिष्क", "अनुमस्तिष्क", "मेडुला", "हाइपोथैलेमस"], "अनुमस्तिष्क मुद्रा और गति का समन्वय करता है।"]),
  q(3, "biology", "human-physiology", "M", 3,
    ["Kwashiorkor in children is caused mainly by a deficiency of:", ["Vitamin C", "Iron", "Iodine", "Protein"], "Severe protein deficiency causes kwashiorkor."],
    ["बच्चों में क्वाशियोरकर रोग मुख्यतः किसकी कमी से होता है?", ["विटामिन C", "लोहा", "आयोडीन", "प्रोटीन"], "प्रोटीन की गंभीर कमी क्वाशियोरकर करती है।"]),
  q(3, "biology", "plant-biology", "M", 1,
    ["Water and minerals are conducted upwards in a plant by the:", ["Phloem", "Xylem", "Cambium", "Cortex"], "Xylem carries water and minerals."],
    ["पौधे में जल और खनिज ऊपर की ओर किसके द्वारा पहुँचाए जाते हैं?", ["फ़्लोएम", "जाइलम", "कैम्बियम", "वल्कुट"], "जाइलम जल और खनिज वहन करता है।"]),
  q(3, "biology", "plant-biology", "M", 0,
    ["Food made in the leaves is carried to other parts of the plant by the:", ["Phloem", "Xylem", "Root hairs", "Stomata"], "Phloem translocates sugars."],
    ["पत्तियों में बना भोजन पौधे के अन्य भागों तक किसके द्वारा पहुँचता है?", ["फ़्लोएम", "जाइलम", "मूल रोम", "रंध्र"], "फ़्लोएम शर्कराओं का स्थानांतरण करता है।"]),
  q(3, "biology", "plant-biology", "H", 2,
    ["The first step in the germination of a seed is the absorption of:", ["Light", "Carbon dioxide", "Water", "Nitrogen"], "Imbibition of water activates the seed."],
    ["बीज के अंकुरण का पहला चरण किसका अवशोषण है?", ["प्रकाश", "कार्बन डाइऑक्साइड", "जल", "नाइट्रोजन"], "जल का अंतःशोषण बीज को सक्रिय करता है।"]),
  q(3, "biology", "diversity-health", "M", 3,
    ["The five-kingdom classification of living things was proposed by:", ["Linnaeus", "Haeckel", "Aristotle", "R. H. Whittaker"], "Whittaker proposed it in 1969."],
    ["जीवों का पाँच-जगत वर्गीकरण किसने प्रस्तावित किया?", ["लिनियस", "हैकल", "अरस्तू", "आर. एच. व्हिटेकर"], "व्हिटेकर ने इसे 1969 में प्रस्तावित किया।"]),
  q(3, "biology", "diversity-health", "H", 0,
    ["Binomial nomenclature, giving each species a two-part name, was introduced by:", ["Carolus Linnaeus", "Charles Darwin", "Gregor Mendel", "Robert Hooke"], "Linnaeus established the system in the 18th century."],
    ["प्रत्येक जाति को दो-पदीय नाम देने वाला द्विनाम पद्धति किसने आरंभ की?", ["कैरोलस लिनियस", "चार्ल्स डार्विन", "ग्रेगर मेंडल", "रॉबर्ट हुक"], "लिनियस ने 18वीं सदी में यह पद्धति स्थापित की।"]),
  q(3, "biology", "diversity-health", "M", 2,
    ["Which of these is an invertebrate?", ["Frog", "Snake", "Earthworm", "Fish"], "Earthworms lack a backbone."],
    ["इनमें से कौन-सा अकशेरुकी है?", ["मेंढक", "साँप", "केंचुआ", "मछली"], "केंचुए में रीढ़ की हड्डी नहीं होती।"]),
  q(3, "biology", "diversity-health", "H", 1,
    ["Rickets in children is caused by a deficiency of:", ["Vitamin A", "Vitamin D", "Vitamin K", "Vitamin B₁"], "Lack of Vitamin D softens bones."],
    ["बच्चों में रिकेट्स किसकी कमी से होता है?", ["विटामिन A", "विटामिन D", "विटामिन K", "विटामिन B₁"], "विटामिन D की कमी हड्डियाँ कमज़ोर करती है।"]),
  q(3, "biology", "ecology-environment", "M", 3,
    ["A network of interconnected food chains in an ecosystem is called a:", ["Food chain", "Pyramid", "Biome", "Food web"], "Many chains linked together form a food web."],
    ["पारितंत्र में परस्पर जुड़ी खाद्य शृंखलाओं का जाल क्या कहलाता है?", ["खाद्य शृंखला", "पिरामिड", "बायोम", "खाद्य जाल"], "कई जुड़ी शृंखलाएँ मिलकर खाद्य जाल बनाती हैं।"]),
  q(3, "biology", "ecology-environment", "H", 2,
    ["The gradual, orderly replacement of one community by another over time is called:", ["Migration", "Adaptation", "Ecological succession", "Mutation"], "Succession ends at a stable climax community."],
    ["समय के साथ एक समुदाय का दूसरे द्वारा क्रमिक, व्यवस्थित प्रतिस्थापन क्या कहलाता है?", ["प्रवास", "अनुकूलन", "पारिस्थितिक अनुक्रमण", "उत्परिवर्तन"], "अनुक्रमण एक स्थिर चरम समुदाय पर समाप्त होता है।"]),
  q(3, "biology", "ecology-environment", "M", 1,
    ["Which gas is chiefly responsible for the greenhouse effect due to burning fossil fuels?", ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], "CO₂ traps heat in the atmosphere."],
    ["जीवाश्म ईंधन जलाने से ग्रीनहाउस प्रभाव के लिए मुख्यतः कौन-सी गैस उत्तरदायी है?", ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "आर्गन"], "CO₂ वायुमंडल में ऊष्मा रोकती है।"]),
  q(3, "biology", "diversity-health", "H", 3,
    ["Out of these illnesses, which one is spread by a virus?", ["Typhoid", "Cholera", "Tuberculosis", "Dengue"], "Dengue is caused by the dengue virus."],
    ["इनमें से कौन-सा रोग विषाणु (वायरस) से होता है?", ["टाइफ़ाइड", "हैज़ा", "क्षय रोग", "डेंगू"], "डेंगू डेंगू वायरस से होता है।"]),

  q(3, "biology", "human-physiology", "M", 1,
    ["The blood vessels that carry blood away from the heart are called:", ["Veins", "Arteries", "Capillaries", "Lymph vessels"], "Arteries take blood away from the heart."],
    ["हृदय से रक्त को दूर ले जाने वाली वाहिकाएँ कहलाती हैं:", ["शिराएँ", "धमनियाँ", "केशिकाएँ", "लसीका वाहिकाएँ"], "धमनियाँ हृदय से रक्त को बाहर ले जाती हैं।"]),

  // ───────── Section 4: Physics & Chemistry (30) ─────────
  q(4, "physics", "mechanics", "M", 2,
    ["According to Kepler's third law, the square of a planet's period of revolution is proportional to the cube of its:", ["Mass", "Speed", "Mean distance from the Sun", "Diameter"], "T² ∝ r³."],
    ["केपलर के तृतीय नियम के अनुसार ग्रह के परिक्रमण-काल का वर्ग किसके घन के समानुपाती होता है?", ["द्रव्यमान", "चाल", "सूर्य से औसत दूरी", "व्यास"], "T² ∝ r³।"]),
  q(4, "physics", "mechanics", "H", 0,
    ["In simple harmonic motion, the acceleration is always directed:", ["Towards the mean position", "Away from the mean position", "Along the velocity only", "Perpendicular to the path"], "SHM acceleration is a restoring one."],
    ["सरल आवर्त गति में त्वरण सदा किस ओर निर्देशित होता है?", ["माध्य स्थिति की ओर", "माध्य स्थिति से दूर", "केवल वेग की दिशा में", "पथ के लंबवत"], "सरल आवर्त गति का त्वरण प्रत्यानयन होता है।"]),
  q(4, "physics", "optics-waves", "M", 1,
    ["White light splits into seven colours on passing through a prism. This is called:", ["Reflection", "Dispersion", "Diffraction", "Polarisation"], "Different colours bend by different amounts."],
    ["श्वेत प्रकाश प्रिज़्म से गुज़रकर सात रंगों में बँट जाता है। इसे कहते हैं:", ["परावर्तन", "विक्षेपण (वर्ण-विक्षेपण)", "विवर्तन", "ध्रुवण"], "भिन्न रंग भिन्न मात्रा में मुड़ते हैं।"]),
  q(4, "physics", "electricity-magnetism", "M", 3,
    ["Two resistors of 4 Ω and 6 Ω are connected in series. Their combined resistance is:", ["2.4 Ω", "5 Ω", "24 Ω", "10 Ω"], "Series resistances add: 4 + 6 = 10 Ω."],
    ["4 Ω और 6 Ω के दो प्रतिरोधक श्रेणी क्रम में जुड़े हैं। उनका संयुक्त प्रतिरोध है:", ["2.4 Ω", "5 Ω", "24 Ω", "10 Ω"], "श्रेणी में प्रतिरोध जुड़ते हैं: 4 + 6 = 10 Ω।"], "4+6"),
  q(4, "physics", "electricity-magnetism", "H", 1,
    ["Lenz's law is a consequence of the conservation of:", ["Mass", "Energy", "Charge", "Momentum"], "The induced current opposes the change that causes it, conserving energy."],
    ["लेंज़ का नियम किसके संरक्षण का परिणाम है?", ["द्रव्यमान", "ऊर्जा", "आवेश", "संवेग"], "प्रेरित धारा अपने कारण का विरोध करती है, जिससे ऊर्जा संरक्षित रहती है।"]),
  q(4, "physics", "heat-thermodynamics", "M", 2,
    ["Water boils at what temperature on the Kelvin scale at normal pressure?", ["273 K", "323 K", "373 K", "100 K"], "100 °C + 273 = 373 K."],
    ["सामान्य दाब पर जल केल्विन पैमाने पर किस ताप पर उबलता है?", ["273 K", "323 K", "373 K", "100 K"], "100 °C + 273 = 373 K।"], "100+273"),
  q(4, "physics", "mechanics", "M", 0,
    ["The unit of work in the SI system is the:", ["Joule", "Watt", "Newton", "Pascal"], "Work is measured in joules."],
    ["SI पद्धति में कार्य की इकाई है:", ["जूल", "वाट", "न्यूटन", "पास्कल"], "कार्य जूल में मापा जाता है।"]),
  q(4, "physics", "optics-waves", "H", 3,
    ["The twinkling of stars is caused by:", ["Their own flickering light", "Reflection from the Moon", "Dust on the lens", "Atmospheric refraction"], "Refraction by varying air layers makes starlight appear to flicker."],
    ["तारों के टिमटिमाने का कारण है:", ["उनके स्वयं का कंपन करता प्रकाश", "चंद्रमा से परावर्तन", "लेंस पर धूल", "वायुमंडलीय अपवर्तन"], "वायु की बदलती परतों से अपवर्तन तारे के प्रकाश को टिमटिमाता दिखाता है।"]),
  q(4, "physics", "modern-physics", "M", 1,
    ["The unit of radioactivity named after a French scientist is the:", ["Hertz", "Becquerel", "Tesla", "Henry"], "One becquerel is one disintegration per second."],
    ["एक फ़्रांसीसी वैज्ञानिक के नाम पर रेडियोधर्मिता की इकाई है:", ["हर्ट्ज़", "बेकरेल", "टेस्ला", "हेनरी"], "एक बेकरेल प्रति सेकंड एक विघटन है।"]),
  q(4, "physics", "electricity-magnetism", "M", 2,
    ["A device that converts mechanical energy into electrical energy is a:", ["Motor", "Heater", "Generator", "Fuse"], "A generator produces electricity from motion."],
    ["यांत्रिक ऊर्जा को विद्युत ऊर्जा में बदलने वाला उपकरण है:", ["मोटर", "हीटर", "जनित्र (जनरेटर)", "फ़्यूज़"], "जनरेटर गति से बिजली बनाता है।"]),
  q(4, "physics", "mechanics", "H", 2,
    ["Which law explains why passengers fall forward when a moving bus brakes suddenly?", ["Newton's third law", "Law of gravitation", "Newton's first law (inertia)", "Ohm's law"], "The body tends to continue its state of motion."],
    ["चलती बस के अचानक रुकने पर यात्री आगे की ओर क्यों गिरते हैं? यह कौन-सा नियम समझाता है?", ["न्यूटन का तृतीय नियम", "गुरुत्वाकर्षण का नियम", "न्यूटन का प्रथम नियम (जड़त्व)", "ओम का नियम"], "पिंड अपनी गति की अवस्था बनाए रखने की प्रवृत्ति रखता है।"]),
  q(4, "physics", "heat-thermodynamics", "H", 3,
    ["Heat is transferred in a vacuum by:", ["Conduction", "Convection", "Evaporation", "Radiation"], "Radiation needs no medium."],
    ["निर्वात में ऊष्मा का स्थानांतरण किसके द्वारा होता है?", ["चालन", "संवहन", "वाष्पीकरण", "विकिरण"], "विकिरण को किसी माध्यम की आवश्यकता नहीं होती।"]),
  q(4, "chemistry", "atomic-structure", "M", 1,
    ["Which block of the periodic table contains the transition elements?", ["s-block", "d-block", "p-block", "f-block only"], "Transition elements fill the d orbitals."],
    ["आवर्त सारणी का कौन-सा ब्लॉक संक्रमण तत्वों को समाहित करता है?", ["s-ब्लॉक", "d-ब्लॉक", "p-ब्लॉक", "केवल f-ब्लॉक"], "संक्रमण तत्व d कक्षकों को भरते हैं।"]),
  q(4, "chemistry", "atomic-structure", "H", 3,
    ["Ionisation energy generally ___ down a group of the periodic table.", ["Increases", "Stays constant", "Doubles", "Decreases"], "Larger atoms hold their outer electron less tightly."],
    ["आवर्त सारणी के किसी समूह में ऊपर से नीचे जाने पर आयनन ऊर्जा सामान्यतः ___ है।", ["बढ़ती", "स्थिर रहती", "दुगुनी होती", "घटती"], "बड़े परमाणु बाहरी इलेक्ट्रॉन को कम कसकर पकड़ते हैं।"]),
  q(4, "chemistry", "physical-chemistry", "M", 2,
    ["The number of moles of oxygen atoms in 1 mole of water is:", ["0.5", "2", "1", "3"], "One mole of H₂O contains one mole of O atoms."],
    ["जल के 1 मोल में ऑक्सीजन परमाणुओं के कितने मोल होते हैं?", ["0.5", "2", "1", "3"], "H₂O के एक मोल में O परमाणुओं का एक मोल होता है।"], "1"),
  q(4, "chemistry", "physical-chemistry", "H", 0,
    ["In a redox reaction, the substance that loses electrons is said to be:", ["Oxidised", "Reduced", "Neutralised", "Hydrolysed"], "Loss of electrons is oxidation."],
    ["रेडॉक्स अभिक्रिया में जो पदार्थ इलेक्ट्रॉन खोता है उसे कहते हैं:", ["ऑक्सीकृत", "अपचयित", "उदासीन", "जल-अपघटित"], "इलेक्ट्रॉन का ह्रास ऑक्सीकरण है।"]),
  q(4, "chemistry", "physical-chemistry", "M", 3,
    ["A reaction that releases heat to the surroundings is called:", ["Endothermic", "Isothermal", "Adiabatic", "Exothermic"], "Exothermic reactions give out heat."],
    ["जो अभिक्रिया परिवेश में ऊष्मा मुक्त करती है उसे कहते हैं:", ["ऊष्माशोषी", "समतापी", "रुद्धोष्म", "ऊष्माक्षेपी"], "ऊष्माक्षेपी अभिक्रियाएँ ऊष्मा बाहर निकालती हैं।"]),
  q(4, "chemistry", "physical-chemistry", "H", 1,
    ["A catalyst increases the rate of a reaction by:", ["Raising the temperature", "Lowering the activation energy", "Increasing the yield only", "Being used up"], "Catalysts provide an alternative path with lower activation energy."],
    ["उत्प्रेरक अभिक्रिया की दर किस प्रकार बढ़ाता है?", ["ताप बढ़ाकर", "सक्रियण ऊर्जा घटाकर", "केवल उपज बढ़ाकर", "स्वयं खर्च होकर"], "उत्प्रेरक कम सक्रियण ऊर्जा वाला वैकल्पिक मार्ग देता है।"]),
  q(4, "chemistry", "chemical-bonding", "M", 2,
    ["Which gas is used in the manufacture of ammonia by the Haber process, together with nitrogen?", ["Oxygen", "Carbon dioxide", "Hydrogen", "Chlorine"], "N₂ + 3H₂ → 2NH₃."],
    ["हैबर प्रक्रम द्वारा अमोनिया बनाने में नाइट्रोजन के साथ कौन-सी गैस प्रयुक्त होती है?", ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "हाइड्रोजन", "क्लोरीन"], "N₂ + 3H₂ → 2NH₃।"]),
  q(4, "chemistry", "chemical-bonding", "H", 3,
    ["Which element is present in all organic compounds?", ["Hydrogen only", "Oxygen", "Nitrogen", "Carbon"], "Organic chemistry is the chemistry of carbon compounds."],
    ["सभी कार्बनिक यौगिकों में कौन-सा तत्व पाया जाता है?", ["केवल हाइड्रोजन", "ऑक्सीजन", "नाइट्रोजन", "कार्बन"], "कार्बनिक रसायन कार्बन यौगिकों का रसायन है।"]),
  q(4, "chemistry", "organic-chemistry", "M", 0,
    ["Starch is a polymer of:", ["Glucose", "Amino acids", "Fatty acids", "Nucleotides"], "Starch consists of many glucose units."],
    ["स्टार्च किसका बहुलक है?", ["ग्लूकोज़", "ऐमीनो अम्ल", "वसीय अम्ल", "न्यूक्लियोटाइड"], "स्टार्च अनेक ग्लूकोज़ इकाइयों से बना है।"]),
  q(4, "chemistry", "organic-chemistry", "H", 2,
    ["Sucrose on hydrolysis gives:", ["Glucose only", "Fructose only", "Glucose and fructose", "Lactose"], "Table sugar breaks into glucose and fructose."],
    ["सुक्रोज़ का जल-अपघटन करने पर क्या मिलता है?", ["केवल ग्लूकोज़", "केवल फ़्रक्टोज़", "ग्लूकोज़ और फ़्रक्टोज़", "लैक्टोज़"], "चीनी टूटकर ग्लूकोज़ और फ़्रक्टोज़ देती है।"]),
  q(4, "chemistry", "acids-bases-salts", "M", 1,
    ["Which compound is used in fire extinguishers along with sulphuric acid?", ["Sodium chloride", "Sodium hydrogencarbonate", "Potassium nitrate", "Calcium sulphate"], "Baking soda and acid produce CO₂ to put out fires."],
    ["अग्निशामक यंत्रों में सल्फ़्यूरिक अम्ल के साथ कौन-सा यौगिक प्रयुक्त होता है?", ["सोडियम क्लोराइड", "सोडियम हाइड्रोजनकार्बोनेट", "पोटैशियम नाइट्रेट", "कैल्सियम सल्फ़ेट"], "खाने का सोडा और अम्ल CO₂ बनाकर आग बुझाते हैं।"]),
  q(4, "chemistry", "acids-bases-salts", "H", 0,
    ["Plaster of Paris is chemically:", ["Calcium sulphate hemihydrate", "Calcium carbonate", "Calcium oxide", "Sodium sulphate"], "It is CaSO₄·½H₂O."],
    ["प्लास्टर ऑफ़ पेरिस रासायनिक रूप से है:", ["कैल्सियम सल्फ़ेट अर्धहाइड्रेट", "कैल्सियम कार्बोनेट", "कैल्सियम ऑक्साइड", "सोडियम सल्फ़ेट"], "यह CaSO₄·½H₂O है।"]),
  q(4, "chemistry", "chemical-bonding", "M", 3,
    ["Which of these is a noble gas?", ["Oxygen", "Chlorine", "Hydrogen", "Neon"], "Neon belongs to Group 18."],
    ["इनमें से कौन-सी उत्कृष्ट गैस है?", ["ऑक्सीजन", "क्लोरीन", "हाइड्रोजन", "नियॉन"], "नियॉन समूह 18 की है।"]),
  q(4, "chemistry", "acids-bases-salts", "M", 2,
    ["Which acid is present in vinegar?", ["Citric acid", "Lactic acid", "Acetic acid", "Formic acid"], "Vinegar contains acetic acid."],
    ["सिरके में कौन-सा अम्ल होता है?", ["सिट्रिक अम्ल", "लैक्टिक अम्ल", "ऐसीटिक अम्ल", "फ़ॉर्मिक अम्ल"], "सिरके में ऐसीटिक अम्ल होता है।"]),
  q(4, "chemistry", "chemical-bonding", "H", 1,
    ["Which metal is extracted from bauxite?", ["Iron", "Aluminium", "Copper", "Zinc"], "Bauxite is the chief ore of aluminium."],
    ["बॉक्साइट से कौन-सी धातु निकाली जाती है?", ["लोहा", "ऐलुमिनियम", "ताँबा", "जस्ता"], "बॉक्साइट ऐलुमिनियम का मुख्य अयस्क है।"]),
  q(4, "chemistry", "physical-chemistry", "M", 0,
    ["The SI unit of the amount of a substance is the:", ["Mole", "Gram", "Litre", "Kelvin"], "The mole measures the amount of substance."],
    ["पदार्थ की मात्रा की SI इकाई है:", ["मोल", "ग्राम", "लीटर", "केल्विन"], "मोल पदार्थ की मात्रा मापता है।"]),
  q(4, "physics", "optics-waves", "M", 3,
    ["The SI unit of frequency is the:", ["Newton", "Joule", "Watt", "Hertz"], "One hertz is one cycle per second."],
    ["आवृत्ति की SI इकाई है:", ["न्यूटन", "जूल", "वाट", "हर्ट्ज़"], "एक हर्ट्ज़ प्रति सेकंड एक चक्र है।"]),
  q(4, "chemistry", "organic-chemistry", "M", 2,
    ["The chemical formula of table sugar (sucrose) is:", ["C₆H₁₂O₆", "C₂H₅OH", "C₁₂H₂₂O₁₁", "CH₃COOH"], "Sucrose is C₁₂H₂₂O₁₁."],
    ["खाने की चीनी (सुक्रोज़) का रासायनिक सूत्र है:", ["C₆H₁₂O₆", "C₂H₅OH", "C₁₂H₂₂O₁₁", "CH₃COOH"], "सुक्रोज़ C₁₂H₂₂O₁₁ है।"]),
];
