// HP TET (TGT Medical) — Full Mock 1, written fresh: Child Development & Pedagogy 30, Hindi 30, English 30,
// Biology 30, Physics & Chemistry 30 (sections as in ./index.ts).

import { q, type PatwariQuestion } from "../patwari/types";

export const medicalMock1: PatwariQuestion[] = [
  // ───────── Section 0: Child Development & Pedagogy (30) ─────────
  q(0, "pedagogy", "child-development", "M", 1,
    ["A pupil's tendency to do well in school mainly because her parents expect it of her, shows the influence of:", ["Heredity alone", "Social expectations of the environment", "Instinct", "Chance"], "Environmental expectations shape effort and achievement."],
    ["किसी विद्यार्थी का विद्यालय में अच्छा करना मुख्यतः इसलिए कि माता-पिता उससे यही अपेक्षा रखते हैं, किसका प्रभाव दर्शाता है?", ["केवल आनुवंशिकता का", "परिवेश की सामाजिक अपेक्षाओं का", "सहज प्रवृत्ति का", "संयोग का"], "परिवेश की अपेक्षाएँ प्रयास और उपलब्धि को आकार देती हैं।"]),
  q(0, "pedagogy", "child-development", "H", 2,
    ["Twin studies are used by psychologists mainly to estimate the relative role of:", ["Diet and exercise", "Teachers and textbooks", "Heredity and environment", "Birth order only"], "Comparing identical and fraternal twins separates genetic and environmental effects."],
    ["जुड़वाँ बच्चों के अध्ययन का प्रयोग मनोवैज्ञानिक मुख्यतः किसकी सापेक्ष भूमिका आँकने के लिए करते हैं?", ["आहार और व्यायाम", "शिक्षकों और पाठ्यपुस्तकों", "आनुवंशिकता और वातावरण", "केवल जन्म-क्रम"], "एकसमान और भ्रातृ जुड़वाँ की तुलना आनुवंशिक और पर्यावरणीय प्रभावों को अलग करती है।"]),
  q(0, "pedagogy", "child-development", "M", 3,
    ["The study of changes in a person across the whole life span is called:", ["Educational statistics", "Comparative anatomy", "Social geography", "Developmental psychology"], "Developmental psychology studies change from conception to old age."],
    ["व्यक्ति में संपूर्ण जीवन-काल में होने वाले परिवर्तनों का अध्ययन क्या कहलाता है?", ["शैक्षिक सांख्यिकी", "तुलनात्मक शरीर-रचना", "सामाजिक भूगोल", "विकासात्मक मनोविज्ञान"], "विकासात्मक मनोविज्ञान गर्भाधान से वृद्धावस्था तक के परिवर्तनों का अध्ययन करता है।"]),
  q(0, "pedagogy", "child-development", "H", 0,
    ["A study that follows the same group of children for many years is called a:", ["Longitudinal study", "Cross-sectional study", "Survey", "Case-control study"], "A longitudinal study tracks the same individuals over time."],
    ["जिस अध्ययन में बच्चों के एक ही समूह का कई वर्षों तक अनुसरण किया जाता है, वह कहलाता है:", ["दीर्घकालिक (अनुदैर्ध्य) अध्ययन", "अनुप्रस्थ अध्ययन", "सर्वेक्षण", "प्रकरण-नियंत्रण अध्ययन"], "अनुदैर्ध्य अध्ययन समय के साथ उन्हीं व्यक्तियों को देखता है।"]),
  q(0, "pedagogy", "child-development", "M", 2,
    ["Which method of studying children involves watching them in natural surroundings without interfering?", ["Experimental method", "Interview", "Naturalistic observation", "Questionnaire"], "Naturalistic observation records behaviour as it occurs."],
    ["बच्चों के अध्ययन की कौन-सी विधि उन्हें बिना हस्तक्षेप किए प्राकृतिक परिवेश में देखने से जुड़ी है?", ["प्रयोगात्मक विधि", "साक्षात्कार", "प्राकृतिक अवलोकन", "प्रश्नावली"], "प्राकृतिक अवलोकन व्यवहार को जैसा घटित होता है वैसा दर्ज करता है।"]),
  q(0, "pedagogy", "child-development", "H", 1,
    ["The case-study method of studying a child is best suited for:", ["Studying thousands of children quickly", "Studying one child in depth", "Testing a drug", "Ranking schools"], "A case study gives detailed knowledge of an individual."],
    ["बच्चे के अध्ययन की व्यक्ति-इतिहास (केस स्टडी) विधि किसके लिए सबसे उपयुक्त है?", ["हज़ारों बच्चों का शीघ्र अध्ययन", "एक बच्चे का गहन अध्ययन", "औषधि का परीक्षण", "विद्यालयों को क्रम देना"], "केस स्टडी किसी एक व्यक्ति का विस्तृत ज्ञान देती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["Which learning theory explains why a child fears a dentist's chair after one painful visit?", ["Insight learning", "Observational learning", "Latent learning", "Classical conditioning"], "A neutral object paired with pain becomes a conditioned fear stimulus."],
    ["एक पीड़ादायक यात्रा के बाद बच्चा दंत-चिकित्सक की कुर्सी से डरने लगता है। कौन-सा अधिगम सिद्धांत यह समझाता है?", ["अंतर्दृष्टि अधिगम", "अवलोकनात्मक अधिगम", "अव्यक्त अधिगम", "शास्त्रीय अनुबंधन"], "पीड़ा से जुड़ी तटस्थ वस्तु अनुबंधित भय-उद्दीपक बन जाती है।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["Fear spreading from a dog that bit the child to all dogs is called:", ["Discrimination", "Extinction", "Stimulus generalisation", "Habituation"], "Generalisation is responding to stimuli similar to the conditioned one."],
    ["जिस कुत्ते ने काटा उससे भय सभी कुत्तों तक फैल जाना क्या कहलाता है?", ["विभेदीकरण", "विलोपन", "उद्दीपक सामान्यीकरण", "आदतीकरण"], "अनुबंधित उद्दीपक जैसे उद्दीपकों पर प्रतिक्रिया करना सामान्यीकरण है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["Sleep, hunger and thirst are examples of:", ["Biological (primary) motives", "Social motives", "Learned habits", "Attitudes"], "They are unlearned physiological drives."],
    ["नींद, भूख और प्यास किसके उदाहरण हैं?", ["जैविक (प्राथमिक) अभिप्रेरक", "सामाजिक अभिप्रेरक", "अर्जित आदतें", "अभिवृत्तियाँ"], "ये अनर्जित शारीरिक चालक हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["The need for approval and friendship from others is a:", ["Biological need", "Social (secondary) motive", "Reflex", "Instinct only"], "Affiliation is a learned, social motive."],
    ["दूसरों से स्वीकृति और मित्रता की आवश्यकता क्या है?", ["जैविक आवश्यकता", "सामाजिक (गौण) अभिप्रेरक", "प्रतिवर्त", "केवल सहज प्रवृत्ति"], "संबद्धता अर्जित, सामाजिक अभिप्रेरक है।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["A pupil with a high 'level of aspiration' typically:", ["Avoids all tasks", "Sets very low goals", "Has no goals", "Sets challenging but realistic goals for herself"], "Level of aspiration is the standard a person sets for her next performance."],
    ["उच्च 'आकांक्षा-स्तर' वाला विद्यार्थी सामान्यतः:", ["सभी कार्यों से बचता है", "बहुत निम्न लक्ष्य रखता है", "कोई लक्ष्य नहीं रखता", "अपने लिए चुनौतीपूर्ण पर यथार्थवादी लक्ष्य तय करता है"], "आकांक्षा-स्तर वह मानक है जो व्यक्ति अपने अगले निष्पादन के लिए रखता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["Attention can be held in the classroom for longer if the lesson includes:", ["Monotony", "Long lectures", "Variety and activity", "Complete silence"], "Variety in method sustains attention."],
    ["कक्षा में ध्यान लंबे समय तक बाँधे रखने के लिए पाठ में क्या होना चाहिए?", ["एकरसता", "लंबे व्याख्यान", "विविधता और क्रियाशीलता", "पूर्ण निःशब्दता"], "विधि में विविधता ध्यान बनाए रखती है।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["Perception in the classroom is influenced by a pupil's:", ["Past experience and expectations", "Shoe size", "Seat number only", "Birth month only"], "What we perceive is shaped by past experience and set."],
    ["कक्षा में प्रत्यक्षण किससे प्रभावित होता है?", ["विद्यार्थी के पूर्व अनुभव और अपेक्षाओं से", "जूतों के नाप से", "केवल सीट संख्या से", "केवल जन्म-मास से"], "हम जो देखते हैं वह पूर्व अनुभव और मानसिक तैयारी से आकार पाता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["Sensation differs from perception in that sensation is:", ["Interpretation of the stimulus", "Always learnt", "Based on memory", "The basic, raw experience produced by a stimulus"], "Perception adds meaning to sensory input."],
    ["संवेदना प्रत्यक्षण से इस अर्थ में भिन्न है कि संवेदना है:", ["उद्दीपक की व्याख्या", "सदा अर्जित", "स्मृति पर आधारित", "उद्दीपक से उत्पन्न मूल, कच्चा अनुभव"], "प्रत्यक्षण संवेदी निवेश में अर्थ जोड़ता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["Bloom's 'mastery learning' holds that most pupils can master a unit if they get:", ["Less time", "Enough time and appropriate instruction", "Only lectures", "No feedback"], "Mastery learning varies time and support rather than expecting uniform pace."],
    ["ब्लूम के 'निपुणता अधिगम' के अनुसार अधिकांश विद्यार्थी इकाई में निपुण हो सकते हैं यदि उन्हें मिले:", ["कम समय", "पर्याप्त समय और उपयुक्त निर्देशन", "केवल व्याख्यान", "कोई प्रतिपुष्टि नहीं"], "निपुणता अधिगम एकसमान गति की अपेक्षा के बजाय समय और सहायता में भिन्नता रखता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["A teacher who plans lessons keeping in mind different ways pupils learn is practising:", ["Rote teaching", "Uniform teaching", "Differentiated instruction", "Tuition"], "Differentiated instruction adapts content and process to learners."],
    ["जो शिक्षक विद्यार्थियों के सीखने के विभिन्न तरीकों को ध्यान में रखकर पाठ की योजना बनाता है, वह क्या कर रहा है?", ["रटंत शिक्षण", "एकसमान शिक्षण", "विभेदित अनुदेशन", "ट्यूशन"], "विभेदित अनुदेशन विषयवस्तु और प्रक्रिया को शिक्षार्थियों के अनुसार ढालता है।"]),
  q(0, "pedagogy", "inclusive-education", "M", 0,
    ["A resource room in an inclusive school provides:", ["Special help from a trained teacher for children with special needs", "A canteen", "A sports field", "A staff lounge"], "Resource rooms offer supplementary specialised support."],
    ["समावेशी विद्यालय में संसाधन कक्ष क्या प्रदान करता है?", ["विशेष आवश्यकता वाले बच्चों के लिए प्रशिक्षित शिक्षक की विशेष सहायता", "कैंटीन", "खेल का मैदान", "कर्मचारी विश्राम-कक्ष"], "संसाधन कक्ष पूरक विशेषीकृत सहायता देते हैं।"]),
  q(0, "pedagogy", "inclusive-education", "H", 3,
    ["An Individualised Education Plan (IEP) is prepared for:", ["The whole school", "Every teacher", "The principal", "A child with special needs"], "An IEP sets goals and supports tailored to one learner."],
    ["वैयक्तिक शिक्षा योजना (आईईपी) किसके लिए बनाई जाती है?", ["पूरे विद्यालय के लिए", "प्रत्येक शिक्षक के लिए", "प्राचार्य के लिए", "विशेष आवश्यकता वाले बच्चे के लिए"], "आईईपी एक शिक्षार्थी के अनुरूप लक्ष्य और सहायता तय करती है।"]),
  q(0, "pedagogy", "inclusive-education", "M", 1,
    ["The sign language and Braille are examples of:", ["Entertainment media", "Assistive means of communication", "Punishments", "Subjects of study only"], "They help persons with sensory impairments to communicate."],
    ["सांकेतिक भाषा और ब्रेल किसके उदाहरण हैं?", ["मनोरंजन के माध्यम", "सहायक संप्रेषण साधन", "दंड", "केवल अध्ययन के विषय"], "ये संवेदी अक्षमता वाले व्यक्तियों को संप्रेषण में मदद करते हैं।"]),
  q(0, "pedagogy", "inclusive-education", "H", 2,
    ["A child with a visual impairment in a regular class should be seated:", ["At the back", "Away from the teacher", "Near the front, with good light and access to the teacher", "Outside the room"], "Seating near the front with suitable light supports learning."],
    ["सामान्य कक्षा में दृष्टिबाधित बच्चे को कहाँ बिठाना चाहिए?", ["पीछे", "शिक्षक से दूर", "आगे, अच्छी रोशनी और शिक्षक तक सुगम पहुँच के साथ", "कक्षा के बाहर"], "अच्छी रोशनी सहित आगे बैठना सीखने में सहायक है।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["The teaching of a lesson in which pupils actively do experiments themselves is called:", ["Lecture method", "Dictation method", "Recitation method", "Laboratory method"], "In the laboratory method pupils learn by experimenting."],
    ["जिस शिक्षण में विद्यार्थी स्वयं सक्रिय रूप से प्रयोग करते हैं, उसे कहते हैं:", ["व्याख्यान विधि", "श्रुतलेख विधि", "सस्वर पाठ विधि", "प्रयोगशाला विधि"], "प्रयोगशाला विधि में विद्यार्थी प्रयोग करके सीखते हैं।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["In the 'problem-solving method' of teaching science, the first step is usually to:", ["Identify and define the problem", "Write the conclusion", "Give homework", "Take the test"], "Problem solving begins with sensing and defining a problem."],
    ["विज्ञान शिक्षण की 'समस्या-समाधान विधि' में पहला चरण सामान्यतः क्या होता है?", ["समस्या को पहचानना और परिभाषित करना", "निष्कर्ष लिखना", "गृहकार्य देना", "परीक्षा लेना"], "समस्या-समाधान समस्या को अनुभव करने और परिभाषित करने से शुरू होता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["Which is a good practice while teaching a health topic such as hygiene to adolescents?", ["Avoid discussing it", "Only show a poster once", "Use discussion, demonstration and real-life examples", "Give only a written test"], "Participatory methods lead to better health habits."],
    ["किशोरों को स्वच्छता जैसा स्वास्थ्य-विषय पढ़ाते समय कौन-सा अच्छा अभ्यास है?", ["उस पर चर्चा से बचना", "केवल एक बार पोस्टर दिखाना", "चर्चा, प्रदर्शन और वास्तविक उदाहरणों का प्रयोग", "केवल लिखित परीक्षा लेना"], "सहभागी विधियाँ बेहतर स्वास्थ्य-आदतें बनाती हैं।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["The Right to Education Act requires teachers to complete the curriculum within the specified time and:", ["Stop remedial work", "Assess learning ability of each child and hold additional instruction if needed", "Give tuition privately", "Detain slow learners"], "Section 24 of RTE sets teacher duties, including supplementary instruction."],
    ["आरटीई अधिनियम शिक्षकों से निर्धारित समय में पाठ्यक्रम पूरा करने और क्या करने की अपेक्षा करता है?", ["उपचारात्मक कार्य बंद करना", "प्रत्येक बच्चे की सीखने की क्षमता का आकलन करना और आवश्यक होने पर अतिरिक्त अनुदेशन देना", "निजी ट्यूशन देना", "मंद विद्यार्थियों को रोकना"], "आरटीई की धारा 24 में शिक्षकों के कर्तव्य हैं, जिनमें अतिरिक्त अनुदेशन शामिल है।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["Teaching pupils how to learn, such as how to take notes and revise, is an example of developing:", ["Rote memory", "Physical skills", "Language skills", "Study skills"], "Study skills help pupils become independent learners."],
    ["विद्यार्थियों को सीखना सिखाना, जैसे नोट्स बनाना और दोहराना, किसके विकास का उदाहरण है?", ["रटने की स्मृति", "शारीरिक कौशल", "भाषा कौशल", "अध्ययन कौशल"], "अध्ययन कौशल विद्यार्थियों को स्वतंत्र शिक्षार्थी बनाते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["Which statement about the role of play in learning is accurate?", ["Play wastes time", "Play helps children learn social and cognitive skills", "Play is only for toddlers", "Play harms discipline"], "Play supports language, thinking and social development."],
    ["सीखने में खेल की भूमिका के बारे में कौन-सा कथन सही है?", ["खेल समय बर्बाद करता है", "खेल बच्चों को सामाजिक और संज्ञानात्मक कौशल सीखने में मदद करता है", "खेल केवल नन्हे बच्चों के लिए है", "खेल अनुशासन को हानि पहुँचाता है"], "खेल भाषा, चिंतन और सामाजिक विकास में सहायक है।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["The 'Right to Education' also requires schools to ensure that no child is denied admission for want of:", ["Uniform", "Documents like age proof or transfer certificate", "Fees only", "Private tuition"], "Section 14 allows admission without age proof, and Section 5 without a transfer certificate."],
    ["आरटीई के अनुसार किस कमी के कारण किसी बच्चे को प्रवेश से वंचित नहीं किया जा सकता?", ["वर्दी की", "आयु-प्रमाण या स्थानांतरण प्रमाणपत्र जैसे दस्तावेज़ों की", "केवल शुल्क की", "निजी ट्यूशन की"], "धारा 14 आयु-प्रमाण के बिना और धारा 5 स्थानांतरण प्रमाणपत्र के बिना प्रवेश की अनुमति देती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["The main aim of 'continuous' evaluation is to:", ["Monitor and improve learning throughout the year", "Conduct one big exam", "Rank schools", "Reduce teachers"], "Continuous evaluation provides frequent feedback."],
    ["'सतत' मूल्यांकन का मुख्य उद्देश्य है:", ["पूरे वर्ष अधिगम की निगरानी और सुधार", "एक बड़ी परीक्षा लेना", "विद्यालयों को क्रम देना", "शिक्षकों को घटाना"], "सतत मूल्यांकन बार-बार प्रतिपुष्टि देता है।"]),
  q(0, "pedagogy", "child-development", "H", 3,
    ["The 'imaginary friend' commonly seen in children aged 3 to 6 years is regarded by psychologists as:", ["A sign of serious illness", "A lie", "An error of perception", "A normal part of imaginative play"], "Imaginary companions are a common, healthy feature of this age."],
    ["3 से 6 वर्ष के बच्चों में सामान्यतः दिखने वाले 'काल्पनिक मित्र' को मनोवैज्ञानिक क्या मानते हैं?", ["गंभीर रोग का संकेत", "झूठ", "प्रत्यक्षण की त्रुटि", "कल्पनाशील खेल का सामान्य भाग"], "काल्पनिक साथी इस आयु की सामान्य, स्वस्थ विशेषता हैं।"]),

  q(0, "pedagogy", "child-development", "M", 2,
    ["The biological transmission of traits from parents to offspring takes place through:", ["Hormones", "Blood", "Genes", "Enzymes"], "Genes carry hereditary information."],
    ["माता-पिता से संतान में लक्षणों का जैविक संचरण किसके माध्यम से होता है?", ["हार्मोन", "रक्त", "जीन", "एंज़ाइम"], "जीन आनुवंशिक सूचना वहन करते हैं।"]),

  // ───────── Section 1: Hindi (30) ─────────
  q(1, "hindi", "sahitya", "M", 1,
    ["'रंगभूमि' and 'कर्मभूमि' are novels by:", ["जैनेंद्र", "प्रेमचंद", "यशपाल", "अज्ञेय"], "Both are Premchand's novels."],
    ["'रंगभूमि' और 'कर्मभूमि' किसके उपन्यास हैं?", ["जैनेंद्र", "प्रेमचंद", "यशपाल", "अज्ञेय"], "दोनों प्रेमचंद के उपन्यास हैं।"]),
  q(1, "hindi", "sahitya", "H", 3,
    ["The play 'ध्रुवस्वामिनी' was written by:", ["भारतेंदु", "मोहन राकेश", "उपेंद्रनाथ अश्क", "जयशंकर प्रसाद"], "Jaishankar Prasad wrote Dhruvaswamini."],
    ["नाटक 'ध्रुवस्वामिनी' किसने लिखा?", ["भारतेंदु", "मोहन राकेश", "उपेंद्रनाथ अश्क", "जयशंकर प्रसाद"], "जयशंकर प्रसाद ने ध्रुवस्वामिनी लिखा।"]),
  q(1, "hindi", "sahitya", "M", 0,
    ["The author of the satire 'राग दरबारी' is:", ["श्रीलाल शुक्ल", "हरिशंकर परसाई", "शरद जोशी", "रेणु"], "Shrilal Shukla won the Sahitya Akademi Award for it in 1970."],
    ["व्यंग्य उपन्यास 'राग दरबारी' के लेखक कौन हैं?", ["श्रीलाल शुक्ल", "हरिशंकर परसाई", "शरद जोशी", "रेणु"], "श्रीलाल शुक्ल को इस पर 1970 में साहित्य अकादमी पुरस्कार मिला।"]),
  q(1, "hindi", "sahitya", "H", 2,
    ["Which poet is known for the line 'अबला जीवन हाय तुम्हारी यही कहानी'?", ["निराला", "पंत", "मैथिलीशरण गुप्त", "दिनकर"], "It is from Maithili Sharan Gupt's 'Yashodhara'."],
    ["'अबला जीवन हाय तुम्हारी यही कहानी' पंक्ति किस कवि की है?", ["निराला", "पंत", "मैथिलीशरण गुप्त", "दिनकर"], "यह मैथिलीशरण गुप्त की 'यशोधरा' से है।"]),
  q(1, "hindi", "sahitya", "M", 3,
    ["'नीर भरी दुख की बदली' is a poetic line of:", ["सुभद्राकुमारी", "पंत", "प्रसाद", "महादेवी वर्मा"], "Mahadevi Varma's 'Neer bhari dukh ki badli'."],
    ["'नीर भरी दुख की बदली' किसकी काव्य-पंक्ति है?", ["सुभद्राकुमारी", "पंत", "प्रसाद", "महादेवी वर्मा"], "यह महादेवी वर्मा की पंक्ति है।"]),
  q(1, "hindi", "sahitya", "H", 1,
    ["The 'Padmavat' epic was composed by the Sufi poet:", ["कबीर", "मलिक मुहम्मद जायसी", "रहीम", "रसखान"], "Jayasi wrote Padmavat in Awadhi in 1540."],
    ["'पद्मावत' महाकाव्य की रचना किस सूफ़ी कवि ने की?", ["कबीर", "मलिक मुहम्मद जायसी", "रहीम", "रसखान"], "जायसी ने 1540 में अवधी में पद्मावत रचा।"]),
  q(1, "hindi", "sahitya", "M", 2,
    ["'कविवचन सुधा' was a magazine edited by:", ["महावीर प्रसाद द्विवेदी", "बालमुकुंद गुप्त", "भारतेंदु हरिश्चंद्र", "प्रेमचंद"], "Bharatendu started Kavivachan Sudha in 1867."],
    ["'कविवचन सुधा' पत्रिका का संपादन किसने किया?", ["महावीर प्रसाद द्विवेदी", "बालमुकुंद गुप्त", "भारतेंदु हरिश्चंद्र", "प्रेमचंद"], "भारतेंदु ने 1867 में कविवचन सुधा शुरू की।"]),
  q(1, "hindi", "sandhi-samas", "M", 0,
    ["Split the word 'हिमालय' into sandhi parts:", ["हिम + आलय", "हिमा + लय", "हिम + अलय", "हि + मालय"], "अ + आ = आ: हिम + आलय."],
    ["'हिमालय' का संधि-विच्छेद कीजिए:", ["हिम + आलय", "हिमा + लय", "हिम + अलय", "हि + मालय"], "अ + आ = आ: हिम + आलय।"]),
  q(1, "hindi", "sandhi-samas", "H", 2,
    ["Split the word 'निर्जन' into sandhi parts:", ["नि + रजन", "निर + जन", "निः + जन", "निज + न"], "Visarg before a voiced consonant becomes र्: निः + जन."],
    ["'निर्जन' का संधि-विच्छेद कीजिए:", ["नि + रजन", "निर + जन", "निः + जन", "निज + न"], "घोष व्यंजन से पहले विसर्ग का र् हो जाता है: निः + जन।"]),
  q(1, "hindi", "sandhi-samas", "H", 3,
    ["Split the word 'वागीश' into sandhi parts:", ["वाग + ईश", "वा + गीश", "वाक् + ईश", "वाग् + इश"], "क् becomes ग् before a vowel: वाक् + ईश."],
    ["'वागीश' का संधि-विच्छेद कीजिए:", ["वाग + ईश", "वा + गीश", "वाग् + इश", "वाक् + ईश"], "स्वर से पहले क् का ग् हो जाता है: वाक् + ईश।"]),
  q(1, "hindi", "sandhi-samas", "M", 1,
    ["'सप्ताह' (सात दिनों का समूह) is an example of:", ["तत्पुरुष समास", "द्विगु समास", "द्वंद्व समास", "अव्ययीभाव समास"], "A number first and a group meaning: dvigu."],
    ["'सप्ताह' (सात दिनों का समूह) किसका उदाहरण है?", ["तत्पुरुष समास", "द्विगु समास", "द्वंद्व समास", "अव्ययीभाव समास"], "पहला पद संख्यावाचक और अर्थ समूह का: द्विगु।"]),
  q(1, "hindi", "sandhi-samas", "H", 0,
    ["'चंद्रमुखी' (चंद्रमा के समान मुख वाली) – the compound here, when it describes a woman, is:", ["बहुव्रीहि समास", "द्वंद्व समास", "द्विगु समास", "अव्ययीभाव समास"], "It describes another person (the woman): bahuvrihi."],
    ["'चंद्रमुखी' (चंद्रमा के समान मुख वाली) – स्त्री का वर्णन करने पर यह कौन-सा समास है?", ["बहुव्रीहि समास", "द्वंद्व समास", "द्विगु समास", "अव्ययीभाव समास"], "यह अन्य व्यक्ति (स्त्री) का वर्णन करता है: बहुव्रीहि।"]),
  q(1, "hindi", "sandhi-samas", "M", 2,
    ["'राजमार्ग' (राजाओं के लिए मार्ग) is an example of:", ["द्वंद्व समास", "द्विगु समास", "तत्पुरुष समास", "अव्ययीभाव समास"], "A relation of purpose or possession joins the words: tatpurush."],
    ["'राजमार्ग' (राजाओं के लिए मार्ग) किसका उदाहरण है?", ["द्वंद्व समास", "द्विगु समास", "तत्पुरुष समास", "अव्ययीभाव समास"], "प्रयोजन या संबंध दोनों शब्दों को जोड़ता है: तत्पुरुष।"]),
  q(1, "hindi", "paryay-vilom", "M", 3,
    ["Choose the synonym of 'कमल':", ["कुमुद", "पुष्प", "सरिता", "पंकज"], "कमल, पंकज and नीरज are names of the lotus."],
    ["'कमल' का पर्यायवाची चुनिए:", ["कुमुद", "पुष्प", "सरिता", "पंकज"], "कमल, पंकज और नीरज कमल के नाम हैं।"]),
  q(1, "hindi", "paryay-vilom", "H", 2,
    ["Choose the antonym of 'आविष्कार':", ["खोज", "निर्माण", "लोप", "अनुसंधान"], "आविष्कार is invention; the opposite sense is disappearance (लोप)."],
    ["'आविष्कार' का विलोम चुनिए:", ["खोज", "निर्माण", "लोप", "अनुसंधान"], "आविष्कार का अर्थ सृजन/प्रकट होना है; विपरीत भाव लोप है।"]),
  q(1, "hindi", "paryay-vilom", "M", 0,
    ["Choose the antonym of 'कठोर':", ["कोमल", "सख़्त", "तीव्र", "भारी"], "कठोर is hard; कोमल is soft."],
    ["'कठोर' का विलोम चुनिए:", ["कोमल", "सख़्त", "तीव्र", "भारी"], "कठोर का अर्थ कड़ा है; कोमल का अर्थ नरम है।"]),
  q(1, "hindi", "ek-shabd", "M", 2,
    ["Which single word means 'जो अपने कर्तव्य का पालन करे'?", ["कर्तव्यहीन", "स्वार्थी", "कर्तव्यनिष्ठ", "आलसी"], "कर्तव्यनिष्ठ is devoted to duty."],
    ["'जो अपने कर्तव्य का पालन करे' के लिए एक शब्द कौन-सा है?", ["कर्तव्यहीन", "स्वार्थी", "कर्तव्यनिष्ठ", "आलसी"], "कर्तव्यनिष्ठ अपने कर्तव्य के प्रति समर्पित होता है।"]),
  q(1, "hindi", "ek-shabd", "H", 1,
    ["Which single word means 'जो विदेश से लाया गया हो'?", ["स्वदेशी", "आयातित", "निर्यातित", "प्रवासी"], "आयातित means imported."],
    ["'जो विदेश से लाया गया हो' के लिए एक शब्द कौन-सा है?", ["स्वदेशी", "आयातित", "निर्यातित", "प्रवासी"], "आयातित का अर्थ विदेश से मँगाया हुआ है।"]),
  q(1, "hindi", "ek-shabd", "M", 3,
    ["Which single word means 'पूर्व दिशा में उगने वाला'?", ["पश्चिमी", "दक्षिणी", "उत्तरी", "प्राच्य"], "प्राच्य relates to the east."],
    ["'पूर्व दिशा से संबंधित' के लिए एक शब्द कौन-सा है?", ["पश्चिमी", "दक्षिणी", "उत्तरी", "प्राच्य"], "प्राच्य पूर्व दिशा से संबंधित है।"]),
  q(1, "hindi", "muhavare", "M", 0,
    ["Meaning of the idiom 'आँख का काँटा होना':", ["किसी को बुरा लगना", "आँख में दर्द होना", "काँटा चुभना", "आँखें बंद करना"], "The idiom means to be disliked, an eyesore."],
    ["मुहावरे 'आँख का काँटा होना' का अर्थ है:", ["किसी को बुरा लगना", "आँख में दर्द होना", "काँटा चुभना", "आँखें बंद करना"], "इस मुहावरे का अर्थ है किसी की आँखों में खटकना।"]),
  q(1, "hindi", "muhavare", "H", 3,
    ["Meaning of the idiom 'हाथ मलना':", ["हाथ धोना", "ताली बजाना", "हाथ मिलाना", "पछताना"], "The idiom means to regret."],
    ["मुहावरे 'हाथ मलना' का अर्थ है:", ["हाथ धोना", "ताली बजाना", "हाथ मिलाना", "पछताना"], "इस मुहावरे का अर्थ है पछतावा करना।"]),
  q(1, "hindi", "muhavare", "M", 2,
    ["Meaning of the proverb 'नाम बड़े और दर्शन छोटे':", ["नाम छोटा होना", "दर्शन करना", "प्रसिद्धि अधिक पर गुण कम", "बड़ा मंदिर"], "Big in name, small in worth."],
    ["लोकोक्ति 'नाम बड़े और दर्शन छोटे' का अर्थ है:", ["नाम छोटा होना", "दर्शन करना", "प्रसिद्धि अधिक पर गुण कम", "बड़ा मंदिर"], "नाम बड़ा पर वास्तविकता छोटी।"]),
  q(1, "hindi", "shuddh-vartani", "H", 1,
    ["Pick the correct spelling of the word meaning 'peace':", ["शांती", "शांति", "शान्ती", "शाँति"], "The standard form is शांति."],
    ["'अमन-चैन' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["शांती", "शांति", "शान्ती", "शाँति"], "मानक रूप शांति है।"]),
  q(1, "hindi", "shuddh-vartani", "M", 3,
    ["Pick the correct spelling of the word meaning 'stomach illness':", ["बिमारी", "बीमारी", "वीमारी", "बीमारि"], "The correct form is बीमारी."],
    ["'रोग' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["बिमारी", "वीमारी", "बीमारि", "बीमारी"], "शुद्ध रूप बीमारी है।"]),
  q(1, "hindi", "vyakaran", "M", 1,
    ["Which of these is a 'सकर्मक क्रिया'?", ["सोना", "पढ़ना", "रोना", "हँसना"], "'पढ़ना' takes an object: 'वह पुस्तक पढ़ता है'."],
    ["इनमें से कौन-सी 'सकर्मक क्रिया' है?", ["सोना", "पढ़ना", "रोना", "हँसना"], "'पढ़ना' कर्म लेती है: 'वह पुस्तक पढ़ता है'।"]),
  q(1, "hindi", "vyakaran", "H", 2,
    ["The word 'सज्जनता' is formed by adding which suffix to 'सज्जन'?", ["-ई", "-पन", "-ता", "-आई"], "The suffix -ता forms abstract nouns."],
    ["'सज्जन' में कौन-सा प्रत्यय जोड़ने से 'सज्जनता' बनता है?", ["-ई", "-पन", "-ता", "-आई"], "-ता प्रत्यय भाववाचक संज्ञा बनाता है।"]),
  q(1, "hindi", "vyakaran", "M", 0,
    ["Which word is a 'क्रिया-विशेषण' in 'वह यहाँ रहता है'?", ["यहाँ", "वह", "रहता", "है"], "'यहाँ' tells the place of the action."],
    ["'वह यहाँ रहता है' में क्रिया-विशेषण कौन-सा है?", ["यहाँ", "वह", "रहता", "है"], "'यहाँ' क्रिया का स्थान बताता है।"]),
  q(1, "hindi", "vyakaran", "H", 3,
    ["'ईश्वर सर्वत्र है' – 'सर्वत्र' is which kind of adverb?", ["कालवाचक", "रीतिवाचक", "परिमाणवाचक", "स्थानवाचक"], "'सर्वत्र' denotes place."],
    ["'ईश्वर सर्वत्र है' में 'सर्वत्र' किस प्रकार का क्रिया-विशेषण है?", ["कालवाचक", "रीतिवाचक", "परिमाणवाचक", "स्थानवाचक"], "'सर्वत्र' स्थान बताता है।"]),
  q(1, "hindi", "alankar-ras", "M", 2,
    ["The sthayi bhav of 'वात्सल्य रस' is:", ["रति", "शोक", "वत्सलता", "हास"], "Vatsalata (parental affection) is the sthayi bhav of vatsalya ras."],
    ["'वात्सल्य रस' का स्थायी भाव है:", ["रति", "शोक", "वत्सलता", "हास"], "वात्सल्य रस का स्थायी भाव वत्सलता है।"]),
  q(1, "hindi", "alankar-ras", "H", 0,
    ["'पानी गए न ऊबरै, मोती, मानुष, चून' – 'पानी' is used in different senses. The figure of speech is:", ["श्लेष", "अनुप्रास", "उपमा", "रूपक"], "One word carries several meanings: shlesh."],
    ["'पानी गए न ऊबरै, मोती, मानुष, चून' में 'पानी' शब्द अनेक अर्थों में आया है। यहाँ अलंकार है:", ["श्लेष", "अनुप्रास", "उपमा", "रूपक"], "एक शब्द के अनेक अर्थ: श्लेष।"]),

  // ───────── Section 2: English (30) ─────────
  q(2, "english", "literature", "M", 0,
    ["'Romeo and Juliet' is a play by:", ["William Shakespeare", "Charles Dickens", "John Milton", "Oscar Wilde"], "Shakespeare wrote it around 1595."],
    ["'Romeo and Juliet' नाटक किसका है?", ["विलियम शेक्सपियर", "चार्ल्स डिकेंस", "जॉन मिल्टन", "ऑस्कर वाइल्ड"], "शेक्सपियर ने इसे लगभग 1595 में लिखा।"]),
  q(2, "english", "literature", "H", 2,
    ["The poem 'Ozymandias' is by:", ["Wordsworth", "Keats", "P. B. Shelley", "Coleridge"], "Shelley wrote it in 1818."],
    ["कविता 'Ozymandias' किसकी है?", ["वर्ड्सवर्थ", "कीट्स", "पी. बी. शेली", "कोलरिज"], "शेली ने इसे 1818 में लिखा।"]),
  q(2, "english", "literature", "M", 3,
    ["'Swami and Friends' is a novel by:", ["Mulk Raj Anand", "Raja Rao", "Khushwant Singh", "R. K. Narayan"], "R. K. Narayan's first novel appeared in 1935."],
    ["'Swami and Friends' उपन्यास किसका है?", ["मुल्क राज आनंद", "राजा राव", "खुशवंत सिंह", "आर. के. नारायण"], "आर. के. नारायण का पहला उपन्यास 1935 में आया।"]),
  q(2, "english", "literature", "H", 1,
    ["'The Old Man and the Sea' was written by:", ["F. Scott Fitzgerald", "Ernest Hemingway", "John Steinbeck", "Mark Twain"], "Hemingway published it in 1952."],
    ["'The Old Man and the Sea' किसने लिखा?", ["एफ़. स्कॉट फ़िट्ज़गेराल्ड", "अर्नेस्ट हेमिंग्वे", "जॉन स्टीनबेक", "मार्क ट्वेन"], "हेमिंग्वे ने इसे 1952 में प्रकाशित किया।"]),
  q(2, "english", "grammar", "M", 2,
    ["Fill in the blank: 'The patient ___ before the doctor reached the ward.'", ["dies", "is dying", "had died", "will die"], "The earlier of two past actions takes the past perfect."],
    ["रिक्त स्थान भरिए: 'The patient ___ before the doctor reached the ward.'", ["dies", "is dying", "had died", "will die"], "दो भूतकालीन क्रियाओं में पहले वाली past perfect में आती है।"]),
  q(2, "english", "grammar", "H", 0,
    ["Which sentence about a patient and a nurse is correctly inverted after 'Scarcely'?", ["Scarcely had the patient entered when the nurse called him.", "Scarcely the patient had entered when the nurse called him.", "Scarcely has the patient entered than the nurse called him.", "Scarcely had the patient entered than the nurse call him."], "'Scarcely had … when' takes inverted order."],
    ["'Scarcely' से शुरू होने वाला सही वाक्य चुनिए।", ["Scarcely had the patient entered when the nurse called him.", "Scarcely the patient had entered when the nurse called him.", "Scarcely has the patient entered than the nurse called him.", "Scarcely had the patient entered than the nurse call him."], "'Scarcely had … when' में व्युत्क्रमित क्रम आता है।"]),
  q(2, "english", "grammar", "M", 1,
    ["Fill in the blank: 'Please take care ___ your health.'", ["at", "of", "from", "with"], "'Take care of' is the usual phrase."],
    ["रिक्त स्थान भरिए: 'Please take care ___ your health.'", ["at", "of", "from", "with"], "सामान्य प्रयोग 'take care of' है।"]),
  q(2, "english", "grammar", "H", 3,
    ["Fill in the blank: 'The medicines ___ in the cupboard by the nurse.'", ["keeps", "is keeping", "are kept", "kept"], "The passive plural present: 'are kept'."],
    ["रिक्त स्थान भरिए: 'The medicines ___ in the cupboard by the nurse.'", ["keeps", "is keeping", "are kept", "kept"], "बहुवचन वर्तमान passive: 'are kept'।"]),
  q(2, "english", "grammar", "M", 0,
    ["Fill in the blank: 'There ___ some fresh fruit on the table.'", ["is", "are", "were", "have"], "'Fruit' here is an uncountable mass noun."],
    ["रिक्त स्थान भरिए: 'There ___ some fresh fruit on the table.'", ["is", "are", "were", "have"], "यहाँ 'fruit' अगणनीय समूहवाची संज्ञा है।"]),
  q(2, "english", "error-spotting", "H", 2,
    ["Find the part with an error: 'The doctor (A) advised me (B) to not smoke (C) any more. (D)'", ["A", "B", "D", "C"], "The split infinitive 'to not smoke' should be 'not to smoke'."],
    ["त्रुटि वाला भाग चुनिए: 'The doctor (A) advised me (B) to not smoke (C) any more. (D)'", ["A", "B", "D", "C"], "'to not smoke' के स्थान पर 'not to smoke' आना चाहिए।"]),
  q(2, "english", "error-spotting", "M", 3,
    ["Find the part with an error: 'Neither the nurse (A) nor the doctors (B) was (C) present. (D)'", ["A", "B", "D", "C"], "The verb agrees with the nearer subject 'doctors': 'were'."],
    ["त्रुटि वाला भाग चुनिए: 'Neither the nurse (A) nor the doctors (B) was (C) present. (D)'", ["A", "B", "D", "C"], "क्रिया निकटतम कर्ता 'doctors' के अनुसार 'were' होगी।"]),
  q(2, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'She is (A) more intelligent (B) than any girl (C) in her class. (D)'", ["A", "B", "C", "D"], "It should read 'any other girl' when comparing within the same group."],
    ["त्रुटि वाला भाग चुनिए: 'She is (A) more intelligent (B) than any girl (C) in her class. (D)'", ["A", "B", "C", "D"], "एक ही समूह में तुलना हो तो 'any other girl' आना चाहिए।"]),
  q(2, "english", "voice-speech", "M", 3,
    ["Change to the passive: 'The nurse gave the child an injection.'", ["The child gave an injection by the nurse.", "An injection gave the child by the nurse.", "The injection was giving by the nurse.", "The child was given an injection by the nurse."], "With two objects, either can become the subject."],
    ["Passive में बदलिए: 'The nurse gave the child an injection.'", ["The child gave an injection by the nurse.", "An injection gave the child by the nurse.", "The injection was giving by the nurse.", "The child was given an injection by the nurse."], "दो कर्मों वाले वाक्य में कोई भी कर्म कर्ता बन सकता है।"]),
  q(2, "english", "voice-speech", "H", 0,
    ["Change to indirect speech: 'He said to me, \"Where are you going?\"'", ["He asked me where I was going.", "He asked me where was I going.", "He said me where I am going.", "He told me where I going."], "A wh-question keeps statement order when reported."],
    ["Indirect speech में बदलिए: 'He said to me, \"Where are you going?\"'", ["He asked me where I was going.", "He asked me where was I going.", "He said me where I am going.", "He told me where I going."], "Reported wh-प्रश्न कथन-क्रम रखता है।"]),
  q(2, "english", "vocabulary", "M", 1,
    ["Which word is nearest in meaning to 'ROBUST'?", ["Weak", "Strong", "Thin", "Slow"], "Robust means strong and healthy."],
    ["'ROBUST' के निकटतम अर्थ वाला शब्द कौन-सा है?", ["Weak", "Strong", "Thin", "Slow"], "Robust का अर्थ मज़बूत और स्वस्थ है।"]),
  q(2, "english", "synonyms-antonyms", "H", 3,
    ["The antonym of 'ACUTE' (as in acute pain) is:", ["Severe", "Sharp", "Intense", "Mild"], "Acute pain is sharp and severe; mild is the opposite."],
    ["'ACUTE' (जैसे acute pain) का विलोम है:", ["Severe", "Sharp", "Intense", "Mild"], "Acute पीड़ा तीव्र होती है; mild उसका उलटा है।"]),
  q(2, "english", "synonyms-antonyms", "M", 0,
    ["The antonym of 'ENCOURAGE' is:", ["Discourage", "Support", "Inspire", "Urge"], "Discourage is the opposite of encourage."],
    ["'ENCOURAGE' का विलोम है:", ["Discourage", "Support", "Inspire", "Urge"], "Discourage, encourage का उलटा है।"]),
  q(2, "english", "idioms", "M", 2,
    ["To 'be under the weather' means to:", ["Stand in the rain", "Be a weather forecaster", "Feel slightly unwell", "Plan a trip"], "The idiom means to feel ill."],
    ["'to be under the weather' का अर्थ है:", ["बारिश में खड़े रहना", "मौसम-वैज्ञानिक होना", "थोड़ा अस्वस्थ महसूस करना", "यात्रा की योजना बनाना"], "इस मुहावरे का अर्थ बीमार-सा महसूस करना है।"]),
  q(2, "english", "idioms", "H", 1,
    ["'A bitter pill to swallow' refers to:", ["Strong medicine", "Something unpleasant that must be accepted", "A kind of sweet", "A cure"], "The idiom describes an unpleasant truth one has to accept."],
    ["'A bitter pill to swallow' किसकी ओर संकेत करता है?", ["कड़वी दवा", "ऐसी अप्रिय बात जिसे स्वीकार करना ही पड़े", "एक प्रकार की मिठाई", "इलाज"], "यह उस अप्रिय सच्चाई के लिए है जिसे मानना पड़ता है।"]),
  q(2, "english", "idioms", "M", 3,
    ["'To catch a cold' means to:", ["Throw a ball", "Feel the weather", "Win a prize", "Become ill with a cold"], "It means to get infected with a cold."],
    ["'to catch a cold' का अर्थ है:", ["गेंद फेंकना", "मौसम महसूस करना", "इनाम जीतना", "ज़ुकाम से पीड़ित हो जाना"], "इसका अर्थ है ज़ुकाम की चपेट में आना।"]),
  q(2, "english", "one-word", "M", 1,
    ["Which single word means 'a doctor who treats children'?", ["Surgeon", "Paediatrician", "Cardiologist", "Dentist"], "A paediatrician specialises in children's health."],
    ["'बच्चों का इलाज करने वाला डॉक्टर' के लिए एक शब्द कौन-सा है?", ["Surgeon", "Paediatrician", "Cardiologist", "Dentist"], "Paediatrician बच्चों के स्वास्थ्य का विशेषज्ञ होता है।"]),
  q(2, "english", "one-word", "H", 0,
    ["Which single word means 'a person who studies and treats diseases of the heart'?", ["Cardiologist", "Neurologist", "Orthopaedist", "Dermatologist"], "A cardiologist treats heart disease."],
    ["'हृदय रोगों का अध्ययन और उपचार करने वाले' के लिए एक शब्द कौन-सा है?", ["Cardiologist", "Neurologist", "Orthopaedist", "Dermatologist"], "Cardiologist हृदय रोगों का उपचार करता है।"]),
  q(2, "english", "one-word", "M", 2,
    ["Which single word means 'a place where sick people are treated'?", ["Library", "School", "Hospital", "Museum"], "A hospital treats the sick."],
    ["'जहाँ बीमार लोगों का इलाज होता है' उस स्थान के लिए एक शब्द कौन-सा है?", ["Library", "School", "Hospital", "Museum"], "Hospital में बीमारों का इलाज होता है।"]),
  q(2, "english", "spelling", "H", 3,
    ["Select the correct spelling of the adjective meaning 'relating to treatment':", ["Medicinal", "Medicenal", "Medicinel", "Madicinal"], "The word is medicinal."],
    ["'उपचार से संबंधित' अर्थ वाले विशेषण की सही वर्तनी चुनिए:", ["Medicenal", "Medicinel", "Madicinal", "Medicinal"], "सही शब्द medicinal है।"]),
  q(2, "english", "spelling", "M", 1,
    ["Select the correct spelling of the word for cleanliness practices that prevent disease:", ["Hygeine", "Hygiene", "Hygiene's", "Higiene"], "The word is hygiene."],
    ["स्वच्छता अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Hygeine", "Hygiene", "Hygiene's", "Higiene"], "सही शब्द hygiene है।"]),
  q(2, "english", "comprehension", "M", 2,
    ["Which technique best helps pupils learn the spelling of new words?", ["Copying a page once", "Skipping them", "Look, say, cover, write and check", "Hearing them once"], "Multisensory spelling practice improves retention."],
    ["नए शब्दों की वर्तनी सीखने में कौन-सी तकनीक विद्यार्थियों की सबसे अधिक सहायता करती है?", ["एक पन्ना एक बार उतारना", "उन्हें छोड़ देना", "देखो, बोलो, ढको, लिखो और जाँचो", "उन्हें एक बार सुनना"], "बहु-संवेदी वर्तनी अभ्यास धारण सुधारता है।"]),
  q(2, "english", "comprehension", "H", 3,
    ["An 'oral cloze' where the teacher pauses and pupils supply the missing word mainly develops:", ["Handwriting", "Arithmetic", "Map skills", "Listening and prediction"], "It builds attentive listening and use of context."],
    ["मौखिक क्लोज़ में शिक्षक रुकता है और विद्यार्थी छूटा शब्द बताते हैं। यह मुख्यतः क्या विकसित करता है?", ["लिखावट", "अंकगणित", "मानचित्र कौशल", "सुनना और पूर्वानुमान"], "यह ध्यानपूर्वक सुनने और संदर्भ-प्रयोग को बढ़ाता है।"]),
  q(2, "english", "comprehension", "M", 0,
    ["The best way to build a reading habit among primary pupils is to:", ["Provide a class library and read-aloud time", "Ban story books", "Make them copy long passages", "Test them daily"], "Access and enjoyment build habits."],
    ["प्राथमिक विद्यार्थियों में पढ़ने की आदत बनाने का सबसे अच्छा तरीका है:", ["कक्षा पुस्तकालय और सस्वर पठन का समय देना", "कहानी की किताबों पर रोक", "लंबे अनुच्छेद उतरवाना", "रोज़ परीक्षा लेना"], "पहुँच और आनंद आदत बनाते हैं।"]),
  q(2, "english", "grammar", "H", 1,
    ["Which sentence expresses uncertainty about a report correctly?", ["I have a doubt about the topic and I am not sure.", "I doubt whether the report is correct.", "I doubt that the report be correct.", "I am doubting the report is correct."], "'Doubt whether/if' expresses uncertainty."],
    ["सही वाक्य चुनिए (संदेह व्यक्त करने वाला)।", ["I have a doubt about the topic and I am not sure.", "I doubt whether the report is correct.", "I doubt that the report be correct.", "I am doubting the report is correct."], "'Doubt whether/if' अनिश्चय व्यक्त करता है।"]),
  q(2, "english", "grammar", "M", 3,
    ["Fill in the blank: 'The doctor, who was tired, ___ his rounds.'", ["finish", "finishing", "have finished", "finished"], "The past simple fits the narrative."],
    ["रिक्त स्थान भरिए: 'The doctor, who was tired, ___ his rounds.'", ["finish", "finishing", "have finished", "finished"], "कथात्मक वाक्य में past simple उपयुक्त है।"]),

  // ───────── Section 3: Biology (30) ─────────
  q(3, "biology", "cell-biology", "E", 2,
    ["Protein synthesis in the cell takes place at the:", ["Nucleolus", "Golgi body", "Ribosomes", "Lysosomes"], "Ribosomes translate mRNA into proteins."],
    ["कोशिका में प्रोटीन संश्लेषण कहाँ होता है?", ["केंद्रिका में", "गॉल्जी काय में", "राइबोसोम में", "लाइसोसोम में"], "राइबोसोम mRNA को प्रोटीन में अनूदित करते हैं।"]),
  q(3, "biology", "cell-biology", "M", 1,
    ["The cell theory was proposed by:", ["Robert Hooke", "Schleiden and Schwann", "Watson and Crick", "Louis Pasteur"], "Schleiden (plants) and Schwann (animals) formulated it."],
    ["कोशिका सिद्धांत किसने प्रतिपादित किया?", ["रॉबर्ट हुक", "श्लाइडेन और श्वान", "वाटसन और क्रिक", "लुई पाश्चर"], "श्लाइडेन (पादप) और श्वान (जंतु) ने इसे प्रतिपादित किया।"]),
  q(3, "biology", "cell-biology", "E", 0,
    ["A cell without a membrane-bound nucleus is called:", ["Prokaryotic", "Eukaryotic", "Multicellular", "Diploid"], "Bacteria are prokaryotes."],
    ["झिल्ली-युक्त केंद्रक रहित कोशिका कहलाती है:", ["प्रोकैरियोटिक", "यूकैरियोटिक", "बहुकोशिकीय", "द्विगुणित"], "जीवाणु प्रोकैरियोट हैं।"]),
  q(3, "biology", "genetics-evolution", "M", 3,
    ["The double-helix model of DNA was proposed by:", ["Mendel and Morgan", "Darwin and Wallace", "Hershey and Chase", "Watson and Crick"], "Watson and Crick proposed it in 1953."],
    ["डीएनए का द्वि-कुंडलित मॉडल किसने प्रस्तुत किया?", ["मेंडल और मॉर्गन", "डार्विन और वॉलेस", "हर्शी और चेज़", "वाटसन और क्रिक"], "वाटसन और क्रिक ने इसे 1953 में प्रस्तुत किया।"]),
  q(3, "biology", "genetics-evolution", "M", 0,
    ["Mendel's law of segregation states that:", ["Alleles of a gene separate during gamete formation", "Genes mix permanently", "All traits blend", "Traits skip generations always"], "Each gamete receives only one allele of a gene."],
    ["मेंडल के पृथक्करण के नियम के अनुसार:", ["युग्मक निर्माण के समय जीन के युग्मविकल्पी अलग हो जाते हैं", "जीन स्थायी रूप से मिल जाते हैं", "सभी लक्षण मिश्रित हो जाते हैं", "लक्षण सदा पीढ़ी छोड़कर आते हैं"], "प्रत्येक युग्मक को जीन का केवल एक युग्मविकल्पी मिलता है।"]),
  q(3, "biology", "genetics-evolution", "H", 1,
    ["A test cross is made between an individual of unknown genotype and one that is:", ["Homozygous dominant", "Homozygous recessive", "Heterozygous", "Haploid"], "Crossing with a homozygous recessive reveals the unknown genotype."],
    ["परीक्षण संकरण (टेस्ट क्रॉस) में अज्ञात जीनप्ररूप वाले जीव का संकरण किससे कराया जाता है?", ["समयुग्मजी प्रभावी", "समयुग्मजी अप्रभावी", "विषमयुग्मजी", "अगुणित"], "समयुग्मजी अप्रभावी से संकरण अज्ञात जीनप्ररूप को प्रकट करता है।"]),
  q(3, "biology", "genetics-evolution", "H", 2,
    ["A child with blood group O can NOT be born to parents of blood groups:", ["A and B", "A and O", "AB and AB", "B and B"], "AB × AB parents can produce only A, B or AB children."],
    ["रक्त समूह O वाला बच्चा किन माता-पिता से उत्पन्न नहीं हो सकता?", ["A और B", "A और O", "AB और AB", "B और B"], "AB × AB माता-पिता से केवल A, B या AB संतानें ही हो सकती हैं।"]),
  q(3, "biology", "genetics-evolution", "M", 3,
    ["Down syndrome is caused by:", ["Monosomy of the X chromosome", "Extra Y chromosome", "A gene mutation on chromosome 7", "Trisomy of chromosome 21"], "An extra copy of chromosome 21 causes it."],
    ["डाउन सिंड्रोम किसके कारण होता है?", ["X गुणसूत्र की एकल-सूत्रता", "अतिरिक्त Y गुणसूत्र", "गुणसूत्र 7 पर जीन उत्परिवर्तन", "गुणसूत्र 21 की त्रिसूत्रता"], "गुणसूत्र 21 की अतिरिक्त प्रति इसका कारण है।"]),
  q(3, "biology", "genetics-evolution", "M", 1,
    ["In humans, the sex of the child is determined by the:", ["Egg", "Sperm", "Mother's blood group", "Season of birth"], "The sperm carries either X or Y."],
    ["मनुष्य में शिशु का लिंग किसके द्वारा निर्धारित होता है?", ["अंडाणु", "शुक्राणु", "माता के रक्त समूह", "जन्म-ऋतु"], "शुक्राणु X या Y वहन करता है।"]),
  q(3, "biology", "human-physiology", "M", 2,
    ["Lack of haemoglobin or red blood cells in the blood causes:", ["Diabetes", "Goitre", "Anaemia", "Scurvy"], "Anaemia reduces oxygen-carrying capacity."],
    ["रक्त में हीमोग्लोबिन या लाल रुधिर कोशिकाओं की कमी से कौन-सा रोग होता है?", ["मधुमेह", "घेंघा", "रक्ताल्पता", "स्कर्वी"], "रक्ताल्पता ऑक्सीजन-वहन क्षमता घटाती है।"]),
  q(3, "biology", "human-physiology", "M", 0,
    ["Insulin is secreted by the beta cells of the:", ["Islets of Langerhans in the pancreas", "Liver", "Thyroid", "Adrenal"], "Insulin lowers blood glucose."],
    ["इंसुलिन का स्राव किसकी बीटा कोशिकाओं से होता है?", ["अग्न्याशय की लैंगरहैंस द्वीपिकाओं", "यकृत", "थायरॉइड", "अधिवृक्क"], "इंसुलिन रक्त शर्करा घटाता है।"]),
  q(3, "biology", "human-physiology", "M", 3,
    ["The normal resting heart rate of a healthy adult is about:", ["30 beats per minute", "120 beats per minute", "150 beats per minute", "72 beats per minute"], "Roughly 60–100, with about 72 as the typical figure."],
    ["स्वस्थ वयस्क की सामान्य विश्राम हृदय-गति लगभग कितनी होती है?", ["30 धड़कन प्रति मिनट", "120 धड़कन प्रति मिनट", "150 धड़कन प्रति मिनट", "72 धड़कन प्रति मिनट"], "लगभग 60–100, सामान्यतः 72 के आसपास।"]),
  q(3, "biology", "human-physiology", "M", 1,
    ["The structural and functional unit of the kidney is the:", ["Neuron", "Nephron", "Alveolus", "Villus"], "Each kidney has about a million nephrons."],
    ["वृक्क की संरचनात्मक एवं क्रियात्मक इकाई है:", ["न्यूरॉन", "नेफ़्रॉन", "वायुकोशिका", "रसांकुर"], "प्रत्येक वृक्क में लगभग दस लाख नेफ़्रॉन होते हैं।"]),
  q(3, "biology", "human-physiology", "M", 2,
    ["Bile, which helps in the digestion of fats, is produced by the:", ["Stomach", "Pancreas", "Liver", "Small intestine"], "Bile is made in the liver and stored in the gall bladder."],
    ["वसा के पाचन में सहायक पित्त का निर्माण कहाँ होता है?", ["आमाशय", "अग्न्याशय", "यकृत", "छोटी आँत"], "पित्त यकृत में बनता है और पित्ताशय में संचित होता है।"]),
  q(3, "biology", "human-physiology", "M", 0,
    ["The enzyme pepsin begins the digestion of proteins in the:", ["Stomach", "Mouth", "Small intestine", "Large intestine"], "Pepsin works in the acidic stomach."],
    ["एंज़ाइम पेप्सिन प्रोटीन के पाचन की शुरुआत कहाँ करता है?", ["आमाशय में", "मुख में", "छोटी आँत में", "बड़ी आँत में"], "पेप्सिन अम्लीय आमाशय में कार्य करता है।"]),
  q(3, "biology", "human-physiology", "M", 3,
    ["During inhalation, the diaphragm:", ["Relaxes and moves up", "Stops moving", "Bursts", "Contracts and moves down"], "Its contraction increases chest volume."],
    ["अंतःश्वसन के समय डायाफ़्राम:", ["शिथिल होकर ऊपर उठता है", "गति रोक देता है", "फट जाता है", "संकुचित होकर नीचे जाता है"], "इसका संकुचन वक्ष का आयतन बढ़ाता है।"]),
  q(3, "biology", "human-physiology", "M", 2,
    ["In a neuron, the part that carries impulses away from the cell body is the:", ["Dendrite", "Nucleus", "Axon", "Synapse"], "The axon conducts impulses outward."],
    ["न्यूरॉन में कोशिका-काय से आवेग को बाहर ले जाने वाला भाग है:", ["डेंड्राइट", "केंद्रक", "ऐक्सॉन", "सिनैप्स"], "ऐक्सॉन आवेग को बाहर की ओर ले जाता है।"]),
  q(3, "biology", "human-physiology", "H", 1,
    ["The path of a reflex action is called the reflex arc. Which structure makes the decision in a spinal reflex?", ["Cerebrum", "Spinal cord", "Cerebellum", "Heart"], "In a spinal reflex the spinal cord integrates the response."],
    ["प्रतिवर्ती क्रिया के मार्ग को प्रतिवर्त चाप कहते हैं। मेरुरज्जु प्रतिवर्त में निर्णय कौन-सी संरचना करती है?", ["प्रमस्तिष्क", "मेरुरज्जु", "अनुमस्तिष्क", "हृदय"], "मेरुरज्जु प्रतिवर्त में प्रतिक्रिया का समन्वय करती है।"]),
  q(3, "biology", "plant-biology", "H", 0,
    ["The light reactions of photosynthesis occur in the:", ["Grana of chloroplasts", "Stroma only", "Mitochondria", "Nucleus"], "Light reactions take place on the thylakoid membranes of grana."],
    ["प्रकाश-संश्लेषण की प्रकाश अभिक्रियाएँ कहाँ होती हैं?", ["हरित लवक के ग्रैना में", "केवल स्ट्रोमा में", "माइटोकॉन्ड्रिया में", "केंद्रक में"], "प्रकाश अभिक्रियाएँ ग्रैना की थाइलेकॉइड झिल्लियों पर होती हैं।"]),
  q(3, "biology", "plant-biology", "H", 3,
    ["The plant hormone that promotes cell elongation in stems is:", ["Abscisic acid", "Ethylene", "Cytokinin", "Auxin"], "Auxin promotes elongation of cells in shoots."],
    ["तने में कोशिका-दीर्घन को बढ़ावा देने वाला पादप हार्मोन है:", ["ऐब्सिसिक अम्ल", "एथिलीन", "साइटोकाइनिन", "ऑक्सिन"], "ऑक्सिन प्ररोहों में कोशिकाओं के दीर्घन को बढ़ावा देता है।"]),
  q(3, "biology", "plant-biology", "M", 1,
    ["The growth of a plant shoot towards light is called:", ["Geotropism", "Phototropism", "Hydrotropism", "Chemotropism"], "Phototropism is a response to light."],
    ["पौधे के प्ररोह का प्रकाश की ओर वृद्धि करना कहलाता है:", ["गुरुत्वानुवर्तन", "प्रकाशानुवर्तन", "जलानुवर्तन", "रसायनानुवर्तन"], "प्रकाशानुवर्तन प्रकाश के प्रति अनुक्रिया है।"]),
  q(3, "biology", "plant-biology", "M", 2,
    ["Transfer of pollen from an anther to a stigma is called:", ["Fertilisation", "Germination", "Pollination", "Dispersal"], "Pollination precedes fertilisation."],
    ["परागकोश से वर्तिकाग्र तक पराग का स्थानांतरण कहलाता है:", ["निषेचन", "अंकुरण", "परागण", "प्रकीर्णन"], "परागण निषेचन से पहले होता है।"]),
  q(3, "biology", "plant-biology", "H", 0,
    ["Double fertilisation is a feature of:", ["Angiosperms", "Gymnosperms", "Ferns", "Mosses"], "Flowering plants have two fusion events in the embryo sac."],
    ["द्वि-निषेचन किसकी विशेषता है?", ["आवृतबीजी पौधों की", "अनावृतबीजी पौधों की", "फ़र्न की", "मॉस की"], "पुष्पी पौधों में भ्रूणकोश में दो संलयन होते हैं।"]),
  q(3, "biology", "ecology-environment", "E", 1,
    ["In an ecosystem, green plants are called:", ["Consumers", "Producers", "Decomposers", "Parasites"], "Plants make food by photosynthesis."],
    ["पारितंत्र में हरे पौधों को क्या कहते हैं?", ["उपभोक्ता", "उत्पादक", "अपघटक", "परजीवी"], "पौधे प्रकाश-संश्लेषण से भोजन बनाते हैं।"]),
  q(3, "biology", "ecology-environment", "M", 3,
    ["According to the ten per cent law, from one trophic level to the next about what share of energy is passed on?", ["1%", "50%", "90%", "10%"], "Only about 10% of the energy moves up each level."],
    ["दस प्रतिशत नियम के अनुसार एक पोषी स्तर से अगले स्तर तक ऊर्जा का लगभग कितना भाग पहुँचता है?", ["1%", "50%", "90%", "10%"], "हर स्तर पर केवल लगभग 10% ऊर्जा आगे जाती है।"]),
  q(3, "biology", "ecology-environment", "M", 0,
    ["Which group of chemicals is mainly responsible for the depletion of the ozone layer?", ["Chlorofluorocarbons (CFCs)", "Carbon monoxide", "Methane only", "Sulphates"], "CFCs release chlorine that destroys ozone."],
    ["ओज़ोन परत के क्षरण के लिए मुख्यतः कौन-से रसायन उत्तरदायी हैं?", ["क्लोरोफ़्लोरोकार्बन (सीएफ़सी)", "कार्बन मोनोक्साइड", "केवल मेथेन", "सल्फ़ेट"], "सीएफ़सी क्लोरीन मुक्त करते हैं जो ओज़ोन को नष्ट करती है।"]),
  q(3, "biology", "diversity-health", "M", 2,
    ["Edward Jenner developed the first vaccine against:", ["Polio", "Tuberculosis", "Smallpox", "Cholera"], "Jenner used cowpox material in 1796."],
    ["एडवर्ड जेनर ने किस रोग का पहला टीका विकसित किया?", ["पोलियो", "क्षय रोग", "चेचक", "हैज़ा"], "जेनर ने 1796 में काउपॉक्स पदार्थ का प्रयोग किया।"]),
  q(3, "biology", "diversity-health", "M", 1,
    ["Malaria is transmitted by the bite of the female:", ["Aedes mosquito", "Anopheles mosquito", "Culex mosquito", "Housefly"], "The parasite Plasmodium is carried by female Anopheles."],
    ["मलेरिया किसके काटने से फैलता है?", ["मादा एडीज़ मच्छर", "मादा एनोफ़िलीज़ मच्छर", "मादा क्यूलेक्स मच्छर", "घरेलू मक्खी"], "परजीवी प्लाज़्मोडियम मादा एनोफ़िलीज़ ले जाती है।"]),
  q(3, "biology", "diversity-health", "H", 3,
    ["HIV mainly destroys which cells of the immune system?", ["Red blood cells", "Platelets", "B-cell antibodies only", "Helper T cells"], "HIV infects and depletes CD4 helper T cells."],
    ["एचआईवी प्रतिरक्षा तंत्र की मुख्यतः किन कोशिकाओं को नष्ट करता है?", ["लाल रुधिर कोशिकाओं को", "प्लेटलेट्स को", "केवल बी-कोशिका प्रतिरक्षियों को", "सहायक टी कोशिकाओं को"], "एचआईवी CD4 सहायक टी कोशिकाओं को संक्रमित कर घटाता है।"]),

  q(3, "biology", "human-physiology", "E", 1,
    ["The respiratory pigment found in human red blood cells is:", ["Chlorophyll", "Haemoglobin", "Melanin", "Carotene"], "Haemoglobin carries oxygen."],
    ["मानव लाल रुधिर कोशिकाओं में पाया जाने वाला श्वसन वर्णक है:", ["पर्णहरित", "हीमोग्लोबिन", "मेलानिन", "कैरोटीन"], "हीमोग्लोबिन ऑक्सीजन का वहन करता है।"]),

  // ───────── Section 4: Physics & Chemistry (30) ─────────
  q(4, "physics", "mechanics", "M", 1,
    ["Archimedes' principle states that a body immersed in a fluid experiences an upthrust equal to the:", ["Volume of the fluid", "Weight of the fluid displaced", "Density of the fluid", "Mass of the body"], "Buoyant force equals weight of displaced fluid."],
    ["आर्किमिडीज़ का सिद्धांत कहता है कि द्रव में डूबे पिंड पर ऊपर की ओर लगने वाला बल किसके बराबर होता है?", ["द्रव के आयतन", "विस्थापित द्रव के भार", "द्रव के घनत्व", "पिंड के द्रव्यमान"], "उत्प्लावन बल विस्थापित द्रव के भार के बराबर होता है।"]),
  q(4, "physics", "mechanics", "M", 3,
    ["The pressure due to a water column of height 10 m (ρ = 1,000 kg/m³, g = 9.8 m/s²) is:", ["9,800 Pa", "10,000 Pa", "49,000 Pa", "98,000 Pa"], "P = hρg = 10 × 1000 × 9.8 = 98,000 Pa."],
    ["10 मी ऊँचे जल-स्तंभ के कारण दाब है (ρ = 1,000 किग्रा/मी³, g = 9.8 मी/से²):", ["9,800 Pa", "10,000 Pa", "49,000 Pa", "98,000 Pa"], "P = hρg = 10 × 1000 × 9.8 = 98,000 Pa।"], "10*1000*9.8"),
  q(4, "physics", "optics-waves", "M", 0,
    ["A person who cannot see distant objects clearly (short-sightedness) is helped by wearing a:", ["Concave lens", "Convex lens", "Plane mirror", "Prism"], "A diverging lens moves the image back onto the retina."],
    ["निकट-दृष्टि दोष (मायोपिया) का संशोधन किसके प्रयोग से होता है?", ["अवतल लेंस", "उत्तल लेंस", "समतल दर्पण", "प्रिज़्म"], "अपसारी लेंस प्रतिबिंब को वापस दृष्टिपटल पर लाता है।"]),
  q(4, "physics", "optics-waves", "M", 1,
    ["Hypermetropia (long-sightedness) is corrected by using a:", ["Concave lens", "Convex lens", "Cylindrical lens only", "Plane glass"], "A converging lens brings the image forward onto the retina."],
    ["दूर-दृष्टि दोष (हाइपरमेट्रोपिया) का संशोधन किसके प्रयोग से होता है?", ["अवतल लेंस", "उत्तल लेंस", "केवल बेलनाकार लेंस", "समतल काँच"], "अभिसारी लेंस प्रतिबिंब को आगे दृष्टिपटल पर लाता है।"]),
  q(4, "physics", "optics-waves", "M", 2,
    ["The least distance of distinct vision for a normal human eye is about:", ["5 cm", "15 cm", "25 cm", "100 cm"], "The near point of a normal eye is about 25 cm."],
    ["सामान्य मानव नेत्र के लिए स्पष्ट दृष्टि की न्यूनतम दूरी लगभग कितनी होती है?", ["5 सेमी", "15 सेमी", "25 सेमी", "100 सेमी"], "सामान्य नेत्र का निकट बिंदु लगभग 25 सेमी होता है।"]),
  q(4, "physics", "modern-physics", "M", 0,
    ["X-rays were discovered by:", ["Wilhelm Röntgen", "Marie Curie", "J. J. Thomson", "Henri Becquerel"], "Röntgen discovered them in 1895."],
    ["एक्स-किरणों की खोज किसने की?", ["विल्हेम रॉन्टजन", "मैरी क्यूरी", "जे. जे. थॉमसन", "हेनरी बेकरेल"], "रॉन्टजन ने 1895 में इनकी खोज की।"]),
  q(4, "physics", "optics-waves", "M", 3,
    ["Ultrasound used in medical scans has a frequency:", ["Below 20 Hz", "Between 20 Hz and 20 kHz", "Of exactly 1 Hz", "Above 20 kHz"], "Ultrasound lies above the human hearing range."],
    ["चिकित्सीय स्कैन में प्रयुक्त पराश्रव्य ध्वनि (अल्ट्रासाउंड) की आवृत्ति होती है:", ["20 Hz से कम", "20 Hz और 20 kHz के बीच", "ठीक 1 Hz", "20 kHz से अधिक"], "पराश्रव्य ध्वनि मानव श्रवण-परास से ऊपर होती है।"]),
  q(4, "physics", "electricity-magnetism", "M", 2,
    ["A 1,000 W heater used for 2 hours consumes how much electrical energy?", ["0.5 kWh", "1 kWh", "2 kWh", "1,000 kWh"], "E = 1 kW × 2 h = 2 kWh."],
    ["2 घंटे चलने वाला 1,000 W का हीटर कितनी विद्युत ऊर्जा खर्च करता है?", ["0.5 kWh", "1 kWh", "2 kWh", "1,000 kWh"], "E = 1 kW × 2 घंटे = 2 kWh।"], "1*2"),
  q(4, "physics", "electricity-magnetism", "E", 0,
    ["Outside a bar magnet, magnetic field lines go from the:", ["North pole to the south pole", "South pole to the north pole", "Centre to the sides", "Sides to the centre"], "Field lines emerge from the north and enter the south pole."],
    ["छड़ चुंबक के बाहर चुंबकीय क्षेत्र रेखाएँ किस ओर जाती हैं?", ["उत्तरी ध्रुव से दक्षिणी ध्रुव की ओर", "दक्षिणी ध्रुव से उत्तरी ध्रुव की ओर", "केंद्र से किनारों की ओर", "किनारों से केंद्र की ओर"], "क्षेत्र रेखाएँ उत्तरी ध्रुव से निकलकर दक्षिणी ध्रुव में प्रवेश करती हैं।"]),
  q(4, "physics", "electricity-magnetism", "M", 1,
    ["An electrical transformer, used to step voltage up or down, depends on:", ["Self-heating", "Mutual induction", "Total reflection", "Diffraction"], "Changing current in one coil induces voltage in another."],
    ["ट्रांसफ़ॉर्मर किस सिद्धांत पर कार्य करता है?", ["स्व-तापन", "अन्योन्य प्रेरण", "पूर्ण परावर्तन", "विवर्तन"], "एक कुंडली में बदलती धारा दूसरी में वोल्टता प्रेरित करती है।"]),
  q(4, "physics", "modern-physics", "H", 3,
    ["Which radioactive isotope is commonly used in radiotherapy for cancer?", ["Carbon-14", "Uranium-238", "Hydrogen-3", "Cobalt-60"], "Cobalt-60 emits gamma rays used to treat tumours."],
    ["कैंसर के विकिरण-उपचार में सामान्यतः कौन-सा रेडियोधर्मी समस्थानिक प्रयुक्त होता है?", ["कार्बन-14", "यूरेनियम-238", "हाइड्रोजन-3", "कोबाल्ट-60"], "कोबाल्ट-60 गामा किरणें उत्सर्जित करता है जिनसे ट्यूमर का उपचार होता है।"]),
  q(4, "physics", "optics-waves", "M", 2,
    ["A sound wave has a speed of 340 m/s and a frequency of 170 Hz. Its wavelength is:", ["0.5 m", "1 m", "2 m", "4 m"], "λ = v ÷ f = 340 ÷ 170 = 2 m."],
    ["एक ध्वनि तरंग की चाल 340 मी/से और आवृत्ति 170 Hz है। उसकी तरंगदैर्ध्य है:", ["0.5 मी", "1 मी", "2 मी", "4 मी"], "λ = v ÷ f = 340 ÷ 170 = 2 मी।"], "340/170"),
  q(4, "chemistry", "organic-chemistry", "E", 1,
    ["The molecular formula of glucose is:", ["C₁₂H₂₂O₁₁", "C₆H₁₂O₆", "C₂H₅OH", "CH₄"], "Glucose is C₆H₁₂O₆."],
    ["ग्लूकोज़ का आणविक सूत्र है:", ["C₁₂H₂₂O₁₁", "C₆H₁₂O₆", "C₂H₅OH", "CH₄"], "ग्लूकोज़ C₆H₁₂O₆ है।"]),
  q(4, "chemistry", "organic-chemistry", "M", 3,
    ["Proteins are polymers made up of:", ["Fatty acids", "Glucose units", "Nucleotides", "Amino acids"], "Amino acids join by peptide bonds."],
    ["प्रोटीन किससे बने बहुलक हैं?", ["वसीय अम्ल", "ग्लूकोज़ इकाइयाँ", "न्यूक्लियोटाइड", "ऐमीनो अम्ल"], "ऐमीनो अम्ल पेप्टाइड बंध से जुड़ते हैं।"]),
  q(4, "chemistry", "organic-chemistry", "H", 0,
    ["The bond that links two amino acids in a protein is called a:", ["Peptide bond", "Glycosidic bond", "Ester bond", "Hydrogen bond only"], "–CO–NH– links amino acids."],
    ["प्रोटीन में दो ऐमीनो अम्लों को जोड़ने वाला बंध क्या कहलाता है?", ["पेप्टाइड बंध", "ग्लाइकोसिडिक बंध", "एस्टर बंध", "केवल हाइड्रोजन बंध"], "–CO–NH– ऐमीनो अम्लों को जोड़ता है।"]),
  q(4, "chemistry", "organic-chemistry", "M", 2,
    ["An enzyme acts only on a particular substrate. This property is called:", ["Denaturation", "Hydrolysis", "Specificity", "Oxidation"], "Enzymes are highly specific for their substrates."],
    ["एंज़ाइम केवल किसी विशेष क्रियाधार पर कार्य करता है। इस गुण को कहते हैं:", ["विकृतीकरण", "जल-अपघटन", "विशिष्टता", "ऑक्सीकरण"], "एंज़ाइम अपने क्रियाधार के लिए अत्यंत विशिष्ट होते हैं।"]),
  q(4, "chemistry", "organic-chemistry", "H", 1,
    ["Vitamin B₁₂ contains which metal in its structure?", ["Iron", "Cobalt", "Zinc", "Copper"], "Cyanocobalamin has a cobalt atom."],
    ["विटामिन B₁₂ की संरचना में कौन-सी धातु होती है?", ["लोहा", "कोबाल्ट", "जस्ता", "ताँबा"], "सायनोकोबालामिन में कोबाल्ट परमाणु होता है।"]),
  q(4, "chemistry", "organic-chemistry", "M", 0,
    ["In DNA, adenine always pairs with:", ["Thymine", "Cytosine", "Guanine", "Uracil"], "A pairs with T; G pairs with C."],
    ["डीएनए में ऐडेनीन सदा किससे जोड़ा बनाता है?", ["थाइमीन", "साइटोसीन", "ग्वानीन", "यूरेसिल"], "A, T से जुड़ता है; G, C से।"]),
  q(4, "chemistry", "organic-chemistry", "H", 2,
    ["Fats and oils are esters of fatty acids with:", ["Ethanol", "Methanol", "Glycerol", "Glucose"], "A triglyceride is glycerol esterified with three fatty acids."],
    ["वसा और तेल वसीय अम्लों के किसके साथ बने एस्टर हैं?", ["एथेनॉल", "मेथेनॉल", "ग्लिसरॉल", "ग्लूकोज़"], "ट्राइग्लिसराइड ग्लिसरॉल का तीन वसीय अम्लों से एस्टरीकरण है।"]),
  q(4, "chemistry", "organic-chemistry", "M", 3,
    ["Soap is prepared by the alkaline hydrolysis of fats, a reaction known as:", ["Esterification", "Hydrogenation", "Polymerisation", "Saponification"], "Saponification makes soap from fats and alkali."],
    ["वसा के क्षारीय जल-अपघटन से साबुन बनाने की अभिक्रिया कहलाती है:", ["एस्टरीकरण", "हाइड्रोजनीकरण", "बहुलकन", "साबुनीकरण"], "साबुनीकरण वसा और क्षार से साबुन बनाता है।"]),
  q(4, "chemistry", "acids-bases-salts", "M", 1,
    ["Hardness of water is caused mainly by dissolved salts of:", ["Sodium and potassium", "Calcium and magnesium", "Iron and zinc", "Lead and tin"], "Ca²⁺ and Mg²⁺ ions make water hard."],
    ["जल की कठोरता मुख्यतः किन लवणों के घुले होने से होती है?", ["सोडियम और पोटैशियम", "कैल्सियम और मैग्नीशियम", "लोहा और जस्ता", "सीसा और राँगा"], "Ca²⁺ और Mg²⁺ आयन जल को कठोर बनाते हैं।"]),
  q(4, "chemistry", "acids-bases-salts", "H", 3,
    ["Rain is called 'acid rain' when its pH falls below about:", ["8.5", "7.0", "6.5", "5.6"], "Normal rain is slightly acidic, at about 5.6."],
    ["वर्षा का जल लगभग किस pH से नीचे होने पर 'अम्ल वर्षा' कहलाता है?", ["8.5", "7.0", "6.5", "5.6"], "सामान्य वर्षा लगभग 5.6 pH की हल्की अम्लीय होती है।"], "5.6"),
  q(4, "chemistry", "physical-chemistry", "H", 0,
    ["Biochemical oxygen demand (BOD) is used to measure:", ["Organic pollution in water", "Hardness of water", "Salt content", "Temperature"], "High BOD signals heavy organic pollution."],
    ["जैव-रासायनिक ऑक्सीजन माँग (बीओडी) किसे मापने के लिए प्रयुक्त होती है?", ["जल में कार्बनिक प्रदूषण को", "जल की कठोरता को", "लवण की मात्रा को", "ताप को"], "उच्च बीओडी भारी कार्बनिक प्रदूषण का संकेत देती है।"]),
  q(4, "chemistry", "atomic-structure", "M", 2,
    ["Which element is the most electronegative?", ["Oxygen", "Chlorine", "Fluorine", "Nitrogen"], "Fluorine has the highest electronegativity."],
    ["सबसे अधिक विद्युत-ऋणात्मक तत्व कौन-सा है?", ["ऑक्सीजन", "क्लोरीन", "फ़्लोरीन", "नाइट्रोजन"], "फ़्लोरीन की विद्युत-ऋणात्मकता सर्वाधिक है।"]),
  q(4, "chemistry", "organic-chemistry", "E", 0,
    ["The molecular formula of benzene is:", ["C₆H₆", "C₆H₁₂", "C₂H₆", "C₆H₁₄"], "Benzene is C₆H₆."],
    ["बेंज़ीन का आणविक सूत्र है:", ["C₆H₆", "C₆H₁₂", "C₂H₆", "C₆H₁₄"], "बेंज़ीन C₆H₆ है।"]),
  q(4, "chemistry", "organic-chemistry", "H", 1,
    ["The reaction between a carboxylic acid and an alcohol in the presence of an acid catalyst gives an:", ["Ether", "Ester", "Aldehyde", "Alkene"], "That reaction is esterification."],
    ["कार्बोक्सिलिक अम्ल और ऐल्कोहॉल की अम्ल-उत्प्रेरक की उपस्थिति में अभिक्रिया से क्या बनता है?", ["ईथर", "एस्टर", "ऐल्डिहाइड", "ऐल्कीन"], "यह अभिक्रिया एस्टरीकरण है।"]),
  q(4, "chemistry", "organic-chemistry", "H", 3,
    ["Nylon-6,6 is an example of a:", ["Natural polymer", "Addition polymer", "Biopolymer", "Condensation polymer"], "It forms from hexamethylenediamine and adipic acid with loss of water."],
    ["नायलॉन-6,6 किसका उदाहरण है?", ["प्राकृतिक बहुलक", "योगात्मक बहुलक", "जैव-बहुलक", "संघनन बहुलक"], "यह हेक्सामेथिलीनडाइऐमीन और ऐडिपिक अम्ल से जल निकलने पर बनता है।"]),
  q(4, "chemistry", "physical-chemistry", "E", 1,
    ["The molar mass of carbon dioxide (C = 12, O = 16) is:", ["28 g/mol", "44 g/mol", "32 g/mol", "56 g/mol"], "12 + 2 × 16 = 44 g/mol."],
    ["कार्बन डाइऑक्साइड का मोलर द्रव्यमान है (C = 12, O = 16):", ["28 ग्राम/मोल", "44 ग्राम/मोल", "32 ग्राम/मोल", "56 ग्राम/मोल"], "12 + 2 × 16 = 44 ग्राम/मोल।"], "12+2*16"),
  q(4, "physics", "electricity-magnetism", "M", 2,
    ["The SI unit of electrical resistance is the:", ["Volt", "Ampere", "Ohm", "Coulomb"], "Resistance is measured in ohms."],
    ["विद्युत प्रतिरोध की SI इकाई है:", ["वोल्ट", "ऐम्पियर", "ओम", "कूलॉम"], "प्रतिरोध ओम में मापा जाता है।"]),
  q(4, "chemistry", "acids-bases-salts", "M", 0,
    ["The chemical formula of quicklime is:", ["CaO", "Ca(OH)₂", "CaCO₃", "CaCl₂"], "Quicklime is calcium oxide."],
    ["बिना बुझे चूने (क्विकलाइम) का रासायनिक सूत्र है:", ["CaO", "Ca(OH)₂", "CaCO₃", "CaCl₂"], "बिना बुझा चूना कैल्सियम ऑक्साइड है।"]),
];
