// HP TET (TGT Non-Medical) — Full Mock 1, written fresh: Child Development & Pedagogy 30, Hindi 30, English 30,
// Mathematics 30, Physics & Chemistry 30 (sections as in ./index.ts).

import { q, type PatwariQuestion } from "../patwari/types";

export const nonMedicalMock1: PatwariQuestion[] = [
  // ───────── Section 0: Child Development & Pedagogy (30) ─────────
  q(0, "pedagogy", "child-development", "H", 1,
    ["In Cattell's theory, 'crystallised intelligence' is the ability that depends mainly on:", ["Speed of reaction", "Accumulated knowledge and experience", "Inherited reflexes", "Physical strength"], "Crystallised intelligence grows with learning; fluid intelligence is reasoning on new problems."],
    ["कैटेल के सिद्धांत में 'क्रिस्टलीकृत बुद्धि' मुख्यतः किस पर निर्भर करती है?", ["प्रतिक्रिया की गति", "संचित ज्ञान और अनुभव", "जन्मजात प्रतिवर्त", "शारीरिक बल"], "क्रिस्टलीकृत बुद्धि सीखने से बढ़ती है; तरल बुद्धि नई समस्याओं पर तर्क है।"]),
  q(0, "pedagogy", "child-development", "H", 2,
    ["Guilford's 'Structure of Intellect' model classifies mental abilities along three dimensions:", ["Verbal, numerical, spatial", "Heredity, environment, age", "Operations, contents and products", "Memory, speed, attention"], "The model combines operations, contents and products."],
    ["गिलफ़ोर्ड का 'बुद्धि की संरचना' मॉडल मानसिक योग्यताओं को किन तीन आयामों में वर्गीकृत करता है?", ["शाब्दिक, संख्यात्मक, स्थानिक", "आनुवंशिकता, वातावरण, आयु", "संक्रियाएँ, विषयवस्तु और उत्पाद", "स्मृति, गति, ध्यान"], "यह मॉडल संक्रियाओं, विषयवस्तु और उत्पादों को मिलाता है।"]),
  q(0, "pedagogy", "child-development", "H", 0,
    ["Eysenck described personality mainly along the two dimensions of:", ["Extraversion–introversion and neuroticism", "Intelligence and creativity", "Height and weight", "Honesty and courage"], "Eysenck's model uses E, N (and later P)."],
    ["आइज़ेंक ने व्यक्तित्व का वर्णन मुख्यतः किन दो आयामों में किया?", ["बहिर्मुखता–अंतर्मुखता और न्यूरोटिसिज़्म", "बुद्धि और सृजनात्मकता", "ऊँचाई और भार", "ईमानदारी और साहस"], "आइज़ेंक का मॉडल ई, एन (और बाद में पी) आयाम प्रयोग करता है।"]),
  q(0, "pedagogy", "child-development", "M", 3,
    ["In Jung's typology, an introvert is a person who is mainly:", ["Outgoing and talkative", "Aggressive", "Careless", "Reserved and inward-looking"], "Introverts draw energy from their inner world."],
    ["युंग के प्रारूप-वर्गीकरण में अंतर्मुखी व्यक्ति मुख्यतः कैसा होता है?", ["मिलनसार और बातूनी", "आक्रामक", "लापरवाह", "संकोची और अंतर्मुखी"], "अंतर्मुखी अपनी आंतरिक दुनिया से ऊर्जा पाते हैं।"]),
  q(0, "pedagogy", "child-development", "H", 1,
    ["Allport classified personality traits as cardinal, central and:", ["Primary only", "Secondary", "Hidden", "Zero-order"], "Allport's three levels are cardinal, central and secondary traits."],
    ["आलपोर्ट ने व्यक्तित्व के गुणों को कार्डिनल, केंद्रीय और किसमें वर्गीकृत किया?", ["केवल प्राथमिक", "गौण", "गुप्त", "शून्य-क्रम"], "आलपोर्ट के तीन स्तर कार्डिनल, केंद्रीय और गौण गुण हैं।"]),
  q(0, "pedagogy", "child-development", "M", 2,
    ["Sheldon's classification of body types includes endomorph, mesomorph and:", ["Polymorph", "Isomorph", "Ectomorph", "Amorph"], "Sheldon's three somatotypes link body build with temperament."],
    ["शेल्डन के शरीर-प्रकार वर्गीकरण में एंडोमॉर्फ़, मेसोमॉर्फ़ और कौन-सा शामिल है?", ["पॉलीमॉर्फ़", "आइसोमॉर्फ़", "एक्टोमॉर्फ़", "एमॉर्फ़"], "शेल्डन के तीन सोमैटोटाइप शरीर-गठन को स्वभाव से जोड़ते हैं।"]),
  q(0, "pedagogy", "child-development", "H", 0,
    ["The Thematic Apperception Test (TAT), a projective test using pictures, was developed by:", ["Murray and Morgan", "Rorschach", "Binet", "Cattell"], "Henry Murray and Christiana Morgan developed the TAT."],
    ["चित्रों का प्रयोग करने वाला प्रक्षेपी परीक्षण 'थीमैटिक एपर्सेप्शन टेस्ट' (टीएटी) किसने विकसित किया?", ["मरे और मॉर्गन", "रोर्शा", "बिने", "कैटेल"], "हेनरी मरे और क्रिस्टियाना मॉर्गन ने टीएटी विकसित किया।"]),
  q(0, "pedagogy", "child-development", "M", 3,
    ["The Rorschach test uses:", ["Word lists", "Maze puzzles", "Number series", "Ten inkblots"], "It is a projective test based on ten inkblots."],
    ["रोर्शा परीक्षण में किसका प्रयोग होता है?", ["शब्द-सूचियाँ", "भूल-भुलैया पहेलियाँ", "संख्या-श्रेणियाँ", "दस स्याही के धब्बे"], "यह दस स्याही के धब्बों पर आधारित प्रक्षेपी परीक्षण है।"]),
  q(0, "pedagogy", "child-development", "M", 1,
    ["A student who failed an exam says 'the paper was unfair and the teacher was biased'. This defence mechanism is:", ["Sublimation", "Rationalisation", "Repression", "Regression"], "Rationalisation gives acceptable reasons for one's failure."],
    ["परीक्षा में असफल एक विद्यार्थी कहता है 'प्रश्नपत्र अन्यायपूर्ण था और शिक्षक पक्षपाती था'। यह कौन-सा रक्षा-तंत्र है?", ["उदात्तीकरण", "औचित्य-स्थापन", "दमन", "प्रत्यावर्तन"], "औचित्य-स्थापन अपनी असफलता के स्वीकार्य कारण गढ़ता है।"]),
  q(0, "pedagogy", "child-development", "M", 2,
    ["A dishonest person who thinks that 'everyone else is dishonest' shows the defence mechanism of:", ["Denial", "Displacement", "Projection", "Compensation"], "Projection attributes one's own undesirable traits to others."],
    ["जो बेईमान व्यक्ति सोचता है कि 'बाकी सब बेईमान हैं', वह किस रक्षा-तंत्र का प्रदर्शन कर रहा है?", ["अस्वीकार", "विस्थापन", "प्रक्षेपण", "क्षतिपूर्ति"], "प्रक्षेपण अपने अवांछनीय गुणों को दूसरों पर थोप देता है।"]),
  q(0, "pedagogy", "child-development", "H", 0,
    ["An aggressive boy takes up boxing and becomes a state champion. This is an example of:", ["Sublimation", "Projection", "Reaction formation", "Fixation"], "Sublimation channels unacceptable impulses into approved activities."],
    ["एक आक्रामक लड़का मुक्केबाज़ी अपनाकर राज्य चैंपियन बन जाता है। यह किसका उदाहरण है?", ["उदात्तीकरण", "प्रक्षेपण", "प्रतिक्रिया-निर्माण", "स्थिरीकरण"], "उदात्तीकरण अस्वीकार्य आवेगों को स्वीकृत गतिविधियों में लगा देता है।"]),
  q(0, "pedagogy", "child-development", "M", 3,
    ["A ten-year-old who starts bed-wetting and thumb-sucking after a new baby arrives shows:", ["Compensation", "Projection", "Rationalisation", "Regression"], "Regression is a return to behaviour of an earlier stage under stress."],
    ["नए शिशु के आने के बाद दस वर्ष का बच्चा बिस्तर गीला करने और अँगूठा चूसने लगता है। यह दिखाता है:", ["क्षतिपूर्ति", "प्रक्षेपण", "औचित्य-स्थापन", "प्रत्यावर्तन"], "तनाव में पहले की अवस्था के व्यवहार पर लौट जाना प्रत्यावर्तन है।"]),
  q(0, "pedagogy", "child-development", "M", 2,
    ["Choosing between two equally attractive options, such as two scholarships, is an example of an:", ["Avoidance–avoidance conflict", "Approach–avoidance conflict", "Approach–approach conflict", "Multiple conflict only"], "Both options are desirable, so the conflict is approach–approach."],
    ["दो समान आकर्षक विकल्पों, जैसे दो छात्रवृत्तियों, में से चुनना किस द्वंद्व का उदाहरण है?", ["परिहार–परिहार द्वंद्व", "उपागम–परिहार द्वंद्व", "उपागम–उपागम द्वंद्व", "केवल बहुल द्वंद्व"], "दोनों विकल्प वांछनीय हैं, इसलिए यह उपागम–उपागम द्वंद्व है।"]),
  q(0, "pedagogy", "child-development", "H", 3,
    ["The 'frustration–aggression hypothesis' was put forward by:", ["Freud", "Skinner", "Rogers", "Dollard and Miller"], "Dollard, Doob, Miller and others linked frustration to aggression."],
    ["'कुंठा–आक्रामकता परिकल्पना' किसने प्रस्तुत की?", ["फ्रायड", "स्किनर", "रोजर्स", "डॉलर्ड और मिलर"], "डॉलर्ड, डूब, मिलर और अन्य ने कुंठा को आक्रामकता से जोड़ा।"]),
  q(0, "pedagogy", "child-development", "H", 0,
    ["Hans Selye's General Adaptation Syndrome describes the stages of stress as:", ["Alarm, resistance, exhaustion", "Birth, growth, decay", "Hope, effort, success", "Fear, flight, calm"], "The three stages are alarm, resistance and exhaustion."],
    ["हैंस सेल्ये का सामान्य अनुकूलन सिंड्रोम तनाव की अवस्थाएँ किस प्रकार बताता है?", ["चेतावनी, प्रतिरोध, थकावट", "जन्म, वृद्धि, क्षय", "आशा, प्रयास, सफलता", "भय, पलायन, शांति"], "तीन अवस्थाएँ हैं चेतावनी, प्रतिरोध और थकावट।"]),
  q(0, "pedagogy", "child-development", "M", 1,
    ["A mentally healthy, well-adjusted person is generally one who:", ["Avoids all problems", "Faces problems realistically and copes with them", "Never feels anxious", "Depends on others for every decision"], "Good adjustment means coping with reality and stress."],
    ["मानसिक रूप से स्वस्थ, भली-भाँति समायोजित व्यक्ति सामान्यतः वह होता है जो:", ["सभी समस्याओं से बचता है", "समस्याओं का यथार्थवादी ढंग से सामना कर उनसे निपटता है", "कभी चिंतित नहीं होता", "हर निर्णय के लिए दूसरों पर निर्भर रहता है"], "अच्छे समायोजन का अर्थ यथार्थ और तनाव से निपटना है।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["Rosenthal and Jacobson's study of how teachers' high expectations raise pupils' performance is known as the:", ["Halo effect", "Hawthorne effect", "Pygmalion effect", "Flynn effect"], "Teacher expectations can become self-fulfilling prophecies."],
    ["शिक्षकों की उच्च अपेक्षाओं से विद्यार्थियों का प्रदर्शन बढ़ने पर रोज़ेन्थल और जैकबसन का अध्ययन किस नाम से जाना जाता है?", ["हेलो प्रभाव", "हॉथॉर्न प्रभाव", "पिग्मैलियन प्रभाव", "फ़्लिन प्रभाव"], "शिक्षक की अपेक्षाएँ स्वतः-पूर्ण भविष्यवाणी बन सकती हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["A teacher who rates a pupil's essay highly just because the pupil is generally well-behaved is showing the:", ["Halo effect", "Primacy effect", "Zeigarnik effect", "Placebo effect"], "The halo effect lets one good trait colour overall judgement."],
    ["जो शिक्षक किसी विद्यार्थी के निबंध को केवल इसलिए ऊँचा आँकता है कि वह सामान्यतः सुशील है, वह क्या दिखा रहा है?", ["हेलो प्रभाव", "प्रथमता प्रभाव", "ज़ीगार्निक प्रभाव", "प्लेसीबो प्रभाव"], "हेलो प्रभाव में एक अच्छा गुण समग्र निर्णय को रंग देता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["Among Lewin's leadership styles, which one best promotes pupil participation and responsibility in the classroom?", ["Autocratic", "Laissez-faire", "Dictatorial", "Democratic"], "A democratic teacher shares decisions with the group."],
    ["लेविन की नेतृत्व शैलियों में से कौन-सी कक्षा में विद्यार्थियों की सहभागिता और उत्तरदायित्व को सबसे अधिक बढ़ाती है?", ["निरंकुश", "अहस्तक्षेप", "तानाशाही", "लोकतांत्रिक"], "लोकतांत्रिक शिक्षक निर्णय समूह के साथ साझा करता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["Sociometry, the technique that maps social relationships in a group, was developed by:", ["Piaget", "J. L. Moreno", "Thorndike", "Watson"], "Moreno devised the sociogram."],
    ["समूह में सामाजिक संबंधों का मानचित्र बनाने वाली समाजमिति तकनीक किसने विकसित की?", ["पियाजे", "जे. एल. मोरेनो", "थॉर्नडाइक", "वॉटसन"], "मोरेनो ने समाजलेख (सोशियोग्राम) बनाया।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["A tool in which the observer marks the degree of a trait on a continuum, such as 'always–often–sometimes–never', is a:", ["Achievement test", "Checklist", "Rating scale", "Interview schedule"], "A rating scale records the extent of a quality."],
    ["जिस उपकरण में अवलोकनकर्ता किसी गुण की मात्रा को सतत पैमाने, जैसे 'सदा–प्रायः–कभी-कभी–कभी नहीं', पर अंकित करता है, वह है:", ["उपलब्धि परीक्षण", "जाँच-सूची", "मूल्यांकन मापनी (रेटिंग स्केल)", "साक्षात्कार अनुसूची"], "मापनी किसी गुण की सीमा को दर्ज करती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["In a set of scores, the value that occurs most often is called the:", ["Mode", "Median", "Mean", "Range"], "The mode is the most frequent score."],
    ["अंकों के किसी समूह में जो मान सबसे अधिक बार आता है, उसे कहते हैं:", ["बहुलक", "माध्यिका", "माध्य", "परास"], "बहुलक सबसे बारंबार अंक होता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["The median of the scores 3, 7, 9, 12, 15 is:", ["7", "9", "12", "9.2"], "The middle score of the ordered list is 9."],
    ["अंकों 3, 7, 9, 12, 15 की माध्यिका है:", ["7", "9", "12", "9.2"], "क्रमबद्ध सूची का मध्य अंक 9 है।"], "9"),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["In a normal distribution, about what per cent of scores lie within ±1 standard deviation of the mean?", ["50%", "34%", "68%", "95%"], "About 68% fall within one SD of the mean."],
    ["सामान्य बंटन में माध्य के ±1 मानक विचलन के भीतर लगभग कितने प्रतिशत अंक आते हैं?", ["50%", "34%", "68%", "95%"], "लगभग 68% अंक माध्य से एक मानक विचलन के भीतर होते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["A correlation coefficient can take values only between:", ["0 and 100", "0 and 10", "–10 and +10", "–1 and +1"], "The coefficient ranges from –1 to +1."],
    ["सहसंबंध गुणांक के मान किनके बीच ही हो सकते हैं?", ["0 और 100", "0 और 10", "–10 और +10", "–1 और +1"], "गुणांक –1 से +1 के बीच रहता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["A pupil scores 70 where the class mean is 60 and the standard deviation is 5. Her z-score is:", ["1", "2", "3", "0.5"], "z = (70 – 60) ÷ 5 = 2."],
    ["एक विद्यार्थी 70 अंक पाती है जबकि कक्षा का माध्य 60 और मानक विचलन 5 है। उसका z-अंक है:", ["1", "2", "3", "0.5"], "z = (70 – 60) ÷ 5 = 2।"], "(70-60)/5"),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["A percentile rank of 80 for a pupil means that she scored:", ["Higher than 80% of the group", "80 marks out of 100", "Lower than 80% of the group", "Exactly at the average"], "Percentile rank shows the share of the group scoring below her."],
    ["किसी विद्यार्थी की शतांशिक कोटि 80 होने का अर्थ है कि उसने:", ["समूह के 80% से अधिक अंक पाए", "100 में से 80 अंक पाए", "समूह के 80% से कम अंक पाए", "ठीक औसत अंक पाए"], "शतांशिक कोटि बताती है कि समूह का कितना भाग उससे कम अंक पाता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["In Gagné's nine events of instruction, the first event is:", ["Presenting the content", "Giving feedback", "Assessing performance", "Gaining the learners' attention"], "Instruction begins by gaining attention."],
    ["गैग्ने के शिक्षण के नौ घटनाक्रमों में पहला घटनाक्रम कौन-सा है?", ["विषय-वस्तु प्रस्तुत करना", "प्रतिपुष्टि देना", "निष्पादन का आकलन करना", "शिक्षार्थियों का ध्यान आकर्षित करना"], "शिक्षण शिक्षार्थियों का ध्यान आकर्षित करने से शुरू होता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["Bruner's 'spiral curriculum' means that a topic is:", ["Taught once only", "Dropped after Class 5", "Revisited at increasing levels of depth", "Taught in a circle of desks"], "Ideas are returned to repeatedly with growing complexity."],
    ["ब्रूनर की 'सर्पिल पाठ्यचर्या' का अर्थ है कि विषय को:", ["केवल एक बार पढ़ाया जाता है", "कक्षा 5 के बाद छोड़ दिया जाता है", "बढ़ती गहराई के स्तरों पर बार-बार लिया जाता है", "मेज़ों के घेरे में पढ़ाया जाता है"], "विचारों को बढ़ती जटिलता के साथ बार-बार दोहराया जाता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["The branching type of programmed instruction, in which the next frame depends on the learner's answer, was developed by:", ["B. F. Skinner", "Norman Crowder", "Pressey", "Bloom"], "Crowder's intrinsic programming is the branching model."],
    ["अभिक्रमित अनुदेशन का वह शाखीय प्रकार, जिसमें अगला फ़्रेम शिक्षार्थी के उत्तर पर निर्भर करता है, किसने विकसित किया?", ["बी. एफ़. स्किनर", "नॉर्मन क्राउडर", "प्रेसी", "ब्लूम"], "क्राउडर की आंतरिक अभिक्रमण शाखीय मॉडल है।"]),

  // ───────── Section 1: Hindi (30) ─────────
  q(1, "hindi", "sahitya", "H", 2,
    ["'बाणभट्ट की आत्मकथा' is a historical novel by:", ["यशपाल", "भगवतीचरण वर्मा", "हजारी प्रसाद द्विवेदी", "वृंदावनलाल वर्मा"], "Hazari Prasad Dwivedi wrote it in 1946."],
    ["'बाणभट्ट की आत्मकथा' ऐतिहासिक उपन्यास किसने लिखा?", ["यशपाल", "भगवतीचरण वर्मा", "हजारी प्रसाद द्विवेदी", "वृंदावनलाल वर्मा"], "हजारी प्रसाद द्विवेदी ने इसे 1946 में लिखा।"]),
  q(1, "hindi", "sahitya", "M", 0,
    ["'अंधा युग', a verse play on the Mahabharata war, is by:", ["धर्मवीर भारती", "जगदीशचंद्र माथुर", "मोहन राकेश", "भुवनेश्वर"], "Dharamvir Bharati wrote Andha Yug (1954)."],
    ["महाभारत युद्ध पर आधारित काव्य-नाटक 'अंधा युग' किसका है?", ["धर्मवीर भारती", "जगदीशचंद्र माथुर", "मोहन राकेश", "भुवनेश्वर"], "धर्मवीर भारती ने अंधा युग (1954) लिखा।"]),
  q(1, "hindi", "sahitya", "M", 3,
    ["'मैला आँचल', a regional (aanchalik) novel of Purnia, was written by:", ["प्रेमचंद", "राही मासूम रज़ा", "श्रीलाल शुक्ल", "फणीश्वरनाथ रेणु"], "Renu's Maila Aanchal (1954) is the classic aanchalik novel."],
    ["पूर्णिया अंचल के आंचलिक उपन्यास 'मैला आँचल' के लेखक कौन हैं?", ["प्रेमचंद", "राही मासूम रज़ा", "श्रीलाल शुक्ल", "फणीश्वरनाथ रेणु"], "रेणु का मैला आँचल (1954) आंचलिक उपन्यास की श्रेष्ठ कृति है।"]),
  q(1, "hindi", "sahitya", "H", 1,
    ["The novel 'चंद्रकांता', famed for its tilism and aiyyari, was written by:", ["भारतेंदु", "देवकीनंदन खत्री", "किशोरीलाल गोस्वामी", "प्रेमचंद"], "Devaki Nandan Khatri's Chandrakanta drew readers to Hindi."],
    ["तिलिस्म और ऐयारी के लिए प्रसिद्ध उपन्यास 'चंद्रकांता' किसने लिखा?", ["भारतेंदु", "देवकीनंदन खत्री", "किशोरीलाल गोस्वामी", "प्रेमचंद"], "देवकीनंदन खत्री की चंद्रकांता ने पाठकों को हिंदी की ओर खींचा।"]),
  q(1, "hindi", "sahitya", "H", 2,
    ["'गुनाहों का देवता' is a popular romantic novel by:", ["यशपाल", "अज्ञेय", "धर्मवीर भारती", "निर्मल वर्मा"], "Dharamvir Bharati's novel appeared in 1949."],
    ["'गुनाहों का देवता' लोकप्रिय प्रेम-उपन्यास किसका है?", ["यशपाल", "अज्ञेय", "धर्मवीर भारती", "निर्मल वर्मा"], "धर्मवीर भारती का यह उपन्यास 1949 में आया।"]),
  q(1, "hindi", "sahitya", "M", 1,
    ["'अंधेर नगरी', a famous satirical play, was written by:", ["जयशंकर प्रसाद", "भारतेंदु हरिश्चंद्र", "मोहन राकेश", "हरिशंकर परसाई"], "Bharatendu wrote Andher Nagari in 1881."],
    ["प्रसिद्ध व्यंग्य-नाटक 'अंधेर नगरी' किसने लिखा?", ["जयशंकर प्रसाद", "भारतेंदु हरिश्चंद्र", "मोहन राकेश", "हरिशंकर परसाई"], "भारतेंदु ने अंधेर नगरी 1881 में लिखा।"]),
  q(1, "hindi", "sahitya", "H", 0,
    ["The satirist famous for 'विकलांग श्रद्धा का दौर' is:", ["हरिशंकर परसाई", "श्रीलाल शुक्ल", "शरद जोशी", "काका हाथरसी"], "Parsai's collection won the Sahitya Akademi Award in 1982."],
    ["'विकलांग श्रद्धा का दौर' के लिए प्रसिद्ध व्यंग्यकार कौन हैं?", ["हरिशंकर परसाई", "श्रीलाल शुक्ल", "शरद जोशी", "काका हाथरसी"], "परसाई के इस संग्रह को 1982 में साहित्य अकादमी पुरस्कार मिला।"]),
  q(1, "hindi", "sahitya", "M", 3,
    ["'आधे-अधूरे', a modern Hindi play on middle-class family tensions, is by:", ["भारतेंदु", "प्रसाद", "उपेंद्रनाथ अश्क", "मोहन राकेश"], "Mohan Rakesh wrote Adhe Adhure (1969)."],
    ["मध्यवर्गीय परिवार के तनावों पर आधारित आधुनिक हिंदी नाटक 'आधे-अधूरे' किसका है?", ["भारतेंदु", "प्रसाद", "उपेंद्रनाथ अश्क", "मोहन राकेश"], "मोहन राकेश ने आधे-अधूरे (1969) लिखा।"]),
  q(1, "hindi", "sandhi-samas", "M", 2,
    ["Split the word 'महेश' into sandhi parts:", ["मह + ईश", "महा + ईष", "महा + ईश", "महि + ईश"], "आ + ई = ए (gun sandhi): महा + ईश."],
    ["'महेश' का संधि-विच्छेद कीजिए:", ["मह + ईश", "महा + ईष", "महा + ईश", "महि + ईश"], "आ + ई = ए (गुण संधि): महा + ईश।"]),
  q(1, "hindi", "sandhi-samas", "H", 0,
    ["Split the word 'सन्मार्ग' into sandhi parts:", ["सत् + मार्ग", "सन + मार्ग", "सम् + मार्ग", "सद् + मार्ग"], "त् before म becomes न्: सत् + मार्ग = सन्मार्ग."],
    ["'सन्मार्ग' का संधि-विच्छेद कीजिए:", ["सत् + मार्ग", "सन + मार्ग", "सम् + मार्ग", "सद् + मार्ग"], "म से पहले त् का न् हो जाता है: सत् + मार्ग = सन्मार्ग।"]),
  q(1, "hindi", "sandhi-samas", "H", 3,
    ["Split the word 'मनोहर' into sandhi parts:", ["मन + ओहर", "मनो + हर", "मना + हर", "मनः + हर"], "Visarg followed by a voiced consonant becomes ओ: मनः + हर."],
    ["'मनोहर' का संधि-विच्छेद कीजिए:", ["मन + ओहर", "मनो + हर", "मना + हर", "मनः + हर"], "घोष व्यंजन से पहले विसर्ग ओ हो जाता है: मनः + हर।"]),
  q(1, "hindi", "sandhi-samas", "M", 1,
    ["'पंचवटी' (पाँच वटों का समूह) is an example of:", ["तत्पुरुष समास", "द्विगु समास", "द्वंद्व समास", "कर्मधारय समास"], "A number first and a group meaning: dvigu."],
    ["'पंचवटी' (पाँच वटों का समूह) किसका उदाहरण है?", ["तत्पुरुष समास", "द्विगु समास", "द्वंद्व समास", "कर्मधारय समास"], "पहला पद संख्यावाचक और अर्थ समूह का: द्विगु।"]),
  q(1, "hindi", "sandhi-samas", "H", 2,
    ["'वीणापाणि' (वीणा है हाथ में जिसके, अर्थात् सरस्वती) is an example of:", ["तत्पुरुष समास", "द्वंद्व समास", "बहुव्रीहि समास", "कर्मधारय समास"], "It names a third person (Saraswati): bahuvrihi."],
    ["'वीणापाणि' (वीणा है हाथ में जिसके, अर्थात् सरस्वती) किसका उदाहरण है?", ["तत्पुरुष समास", "द्वंद्व समास", "बहुव्रीहि समास", "कर्मधारय समास"], "यह तीसरे व्यक्ति (सरस्वती) को बताता है: बहुव्रीहि।"]),
  q(1, "hindi", "paryay-vilom", "M", 0,
    ["Choose the synonym of 'नेत्र':", ["लोचन", "कर्ण", "नासिका", "ग्रीवा"], "नेत्र, लोचन and नयन all mean eye."],
    ["'नेत्र' का पर्यायवाची चुनिए:", ["लोचन", "कर्ण", "नासिका", "ग्रीवा"], "नेत्र, लोचन और नयन का अर्थ आँख है।"]),
  q(1, "hindi", "paryay-vilom", "M", 3,
    ["Choose the synonym of 'समुद्र':", ["सरिता", "सरोवर", "निर्झर", "सागर"], "समुद्र, सागर, जलधि and उदधि are synonyms."],
    ["'समुद्र' का पर्यायवाची चुनिए:", ["सरिता", "सरोवर", "निर्झर", "सागर"], "समुद्र, सागर, जलधि और उदधि पर्यायवाची हैं।"]),
  q(1, "hindi", "paryay-vilom", "H", 1,
    ["Choose the antonym of 'स्वाधीन':", ["स्वतंत्र", "पराधीन", "मुक्त", "आज़ाद"], "स्वाधीन is independent; पराधीन is dependent."],
    ["'स्वाधीन' का विलोम चुनिए:", ["स्वतंत्र", "पराधीन", "मुक्त", "आज़ाद"], "स्वाधीन का अर्थ स्वतंत्र है; पराधीन का अर्थ दूसरे के अधीन है।"]),
  q(1, "hindi", "paryay-vilom", "M", 2,
    ["Choose the antonym of 'उपकार':", ["सहायता", "भलाई", "अपकार", "दया"], "उपकार is a good turn; अपकार is harm."],
    ["'उपकार' का विलोम चुनिए:", ["सहायता", "भलाई", "अपकार", "दया"], "उपकार का अर्थ भलाई है; अपकार का अर्थ हानि पहुँचाना है।"]),
  q(1, "hindi", "ek-shabd", "M", 1,
    ["Which single word means 'वह स्त्री जिसका पति मर गया हो'?", ["सधवा", "विधवा", "कुमारी", "परित्यक्ता"], "विधवा is a widow."],
    ["'वह स्त्री जिसका पति मर गया हो' के लिए एक शब्द कौन-सा है?", ["सधवा", "विधवा", "कुमारी", "परित्यक्ता"], "विधवा पति के निधन के बाद की स्त्री को कहते हैं।"]),
  q(1, "hindi", "ek-shabd", "H", 3,
    ["Which single word means 'जिसका वर्णन न किया जा सके'?", ["वर्णनीय", "प्रशंसनीय", "विवरणीय", "अवर्णनीय"], "अवर्णनीय cannot be described."],
    ["'जिसका वर्णन न किया जा सके' के लिए एक शब्द कौन-सा है?", ["वर्णनीय", "प्रशंसनीय", "विवरणीय", "अवर्णनीय"], "अवर्णनीय का वर्णन नहीं किया जा सकता।"]),
  q(1, "hindi", "ek-shabd", "M", 2,
    ["Which single word means 'पढ़ने-लिखने वाला विद्यार्थी'?", ["शिक्षक", "अध्यापक", "छात्र", "गुरु"], "छात्र is a student."],
    ["'अध्ययन करने वाला' के लिए एक शब्द कौन-सा है?", ["शिक्षक", "अध्यापक", "छात्र", "गुरु"], "छात्र अध्ययन करने वाला होता है।"]),
  q(1, "hindi", "muhavare", "H", 0,
    ["Meaning of the idiom 'दाँतों तले उँगली दबाना':", ["आश्चर्यचकित होना", "डर जाना", "दाँत दिखाना", "भूखा होना"], "The idiom means to be amazed."],
    ["मुहावरे 'दाँतों तले उँगली दबाना' का अर्थ है:", ["आश्चर्यचकित होना", "डर जाना", "दाँत दिखाना", "भूखा होना"], "इस मुहावरे का अर्थ है बहुत चकित होना।"]),
  q(1, "hindi", "muhavare", "M", 3,
    ["Meaning of the idiom 'सिर पर सवार होना':", ["सवारी करना", "सिर दर्द होना", "ऊँचाई पर चढ़ना", "बार-बार तंग करना"], "The idiom means to pester someone continually."],
    ["मुहावरे 'सिर पर सवार होना' का अर्थ है:", ["सवारी करना", "सिर दर्द होना", "ऊँचाई पर चढ़ना", "बार-बार तंग करना"], "इस मुहावरे का अर्थ है लगातार पीछे पड़े रहना।"]),
  q(1, "hindi", "muhavare", "H", 1,
    ["Meaning of the proverb 'जिन खोजा तिन पाइयाँ':", ["खोज बेकार है", "परिश्रम करने वाले को सफलता मिलती है", "खोजना कठिन है", "पाना सरल है"], "Those who seek earnestly find."],
    ["लोकोक्ति 'जिन खोजा तिन पाइयाँ' का अर्थ है:", ["खोज बेकार है", "परिश्रम करने वाले को सफलता मिलती है", "खोजना कठिन है", "पाना सरल है"], "जो सच्चे मन से खोजता है, उसे मिलता है।"]),
  q(1, "hindi", "shuddh-vartani", "M", 2,
    ["Pick the correctly spelt word meaning 'prestige':", ["प्रतिस्ठा", "प्रतिष्टा", "प्रतिष्ठा", "प्रतीष्ठा"], "The correct form is प्रतिष्ठा."],
    ["'मान-सम्मान' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["प्रतिस्ठा", "प्रतिष्टा", "प्रतिष्ठा", "प्रतीष्ठा"], "शुद्ध रूप प्रतिष्ठा है।"]),
  q(1, "hindi", "shuddh-vartani", "H", 1,
    ["Pick the correctly spelt word meaning 'effort':", ["प्रयास", "प्रयत्न्", "प्रयाश", "परयास"], "Both प्रयास and प्रयत्न are correct words; प्रयास is the standard spelling here."],
    ["'कोशिश' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["प्रयाश", "प्रयास", "प्रयत्न्", "परयास"], "प्रयास शुद्ध वर्तनी है।"]),
  q(1, "hindi", "vyakaran", "M", 0,
    ["The word 'पुस्तकालय' is formed by which process?", ["संधि", "उपसर्ग लगाकर", "प्रत्यय लगाकर", "द्विरुक्ति"], "पुस्तक + आलय is a sandhi formation."],
    ["'पुस्तकालय' शब्द किस प्रक्रिया से बना है?", ["संधि", "उपसर्ग लगाकर", "प्रत्यय लगाकर", "द्विरुक्ति"], "पुस्तक + आलय संधि से बना शब्द है।"]),
  q(1, "hindi", "vyakaran", "H", 3,
    ["In the word 'अनपढ़', 'अन' is a:", ["प्रत्यय", "संज्ञा", "क्रिया", "उपसर्ग"], "'अन' is a prefix meaning 'not'."],
    ["'अनपढ़' शब्द में 'अन' क्या है?", ["प्रत्यय", "संज्ञा", "क्रिया", "उपसर्ग"], "'अन' निषेधवाचक उपसर्ग है।"]),
  q(1, "hindi", "vyakaran", "M", 2,
    ["The word 'मिठास' is formed by adding which suffix?", ["-पन", "-ता", "-आस", "-ई"], "The suffix -आस is added to मीठा."],
    ["'मिठास' शब्द में कौन-सा प्रत्यय लगा है?", ["-पन", "-ता", "-आस", "-ई"], "मीठा में -आस प्रत्यय जुड़ा है।"]),
  q(1, "hindi", "alankar-ras", "M", 0,
    ["The sthayi bhav of 'वीभत्स रस' is:", ["जुगुप्सा", "भय", "क्रोध", "उत्साह"], "Jugupsa (disgust) is the sthayi bhav of vibhatsa ras."],
    ["'वीभत्स रस' का स्थायी भाव है:", ["जुगुप्सा", "भय", "क्रोध", "उत्साह"], "वीभत्स रस का स्थायी भाव जुगुप्सा है।"]),
  q(1, "hindi", "alankar-ras", "H", 2,
    ["The sthayi bhav of 'रौद्र रस' is:", ["शोक", "हास", "क्रोध", "रति"], "Krodh (anger) is the sthayi bhav of raudra ras."],
    ["'रौद्र रस' का स्थायी भाव है:", ["शोक", "हास", "क्रोध", "रति"], "रौद्र रस का स्थायी भाव क्रोध है।"]),
  // ───────── Section 2: English (30) ─────────
  q(2, "english", "literature", "M", 1,
    ["'Macbeth' is a tragedy by:", ["Christopher Marlowe", "William Shakespeare", "Thomas Hardy", "Oscar Wilde"], "Macbeth is one of Shakespeare's great tragedies."],
    ["'Macbeth' किसकी त्रासदी है?", ["क्रिस्टोफ़र मार्लो", "विलियम शेक्सपियर", "थॉमस हार्डी", "ऑस्कर वाइल्ड"], "मैकबेथ शेक्सपियर की महान त्रासदियों में से एक है।"]),
  q(2, "english", "literature", "H", 3,
    ["Who wrote the play 'Pygmalion'?", ["T. S. Eliot", "Harold Pinter", "John Osborne", "George Bernard Shaw"], "Shaw's Pygmalion (1913) inspired 'My Fair Lady'."],
    ["नाटक 'Pygmalion' किसने लिखा?", ["टी. एस. एलियट", "हेरोल्ड पिंटर", "जॉन ऑस्बोर्न", "जॉर्ज बर्नार्ड शॉ"], "शॉ के पिग्मैलियन (1913) से 'माई फ़ेयर लेडी' प्रेरित है।"]),
  q(2, "english", "literature", "H", 0,
    ["'Ode to a Nightingale' is a poem by:", ["John Keats", "William Blake", "Alfred Tennyson", "Robert Browning"], "Keats wrote it in 1819."],
    ["'Ode to a Nightingale' किसकी कविता है?", ["जॉन कीट्स", "विलियम ब्लेक", "अल्फ़्रेड टेनिसन", "रॉबर्ट ब्राउनिंग"], "कीट्स ने इसे 1819 में लिखा।"]),
  q(2, "english", "literature", "M", 2,
    ["'The God of Small Things', which won the Booker Prize in 1997, was written by:", ["Kiran Desai", "Anita Desai", "Arundhati Roy", "Jhumpa Lahiri"], "Arundhati Roy's debut novel won the 1997 Booker."],
    ["1997 का बुकर पुरस्कार जीतने वाला 'The God of Small Things' किसने लिखा?", ["किरण देसाई", "अनीता देसाई", "अरुंधति रॉय", "झुम्पा लाहिड़ी"], "अरुंधति रॉय के पहले उपन्यास ने 1997 का बुकर जीता।"]),
  q(2, "english", "grammar", "M", 3,
    ["Choose the correct article: 'She is ___ honest girl who always speaks ___ truth.'", ["a / a", "an / a", "the / the", "an / the"], "'Honest' begins with a vowel sound; 'the truth' is a fixed phrase."],
    ["सही article चुनिए: 'She is ___ honest girl who always speaks ___ truth.'", ["a / a", "an / a", "the / the", "an / the"], "'Honest' स्वर-ध्वनि से शुरू होता है; 'the truth' स्थिर पदबंध है।"]),
  q(2, "english", "grammar", "H", 1,
    ["Pick the sentence that uses 'each' correctly.", ["Each of the boys have a book.", "Each of the boys has a book.", "Each of the boy have a book.", "Each of the boys are having a book."], "'Each' takes a singular verb and 'of' takes a plural noun."],
    ["'each' का सही प्रयोग करने वाला वाक्य चुनिए।", ["Each of the boys have a book.", "Each of the boys has a book.", "Each of the boy have a book.", "Each of the boys are having a book."], "'Each' के साथ एकवचन क्रिया आती है और 'of' के बाद बहुवचन संज्ञा।"]),
  q(2, "english", "grammar", "M", 0,
    ["Fill in the blank: 'The train had left ___ we reached the station.'", ["before", "since", "until", "unless"], "The earlier action in the past perfect is linked by 'before'."],
    ["रिक्त स्थान भरिए: 'The train had left ___ we reached the station.'", ["before", "since", "until", "unless"], "पहले हुई past perfect क्रिया को 'before' जोड़ता है।"]),
  q(2, "english", "grammar", "H", 2,
    ["Choose the correct form: 'I am looking forward to ___ from you soon.'", ["hear", "have heard", "hearing", "be hearing"], "'To' here is a preposition, followed by a gerund."],
    ["सही रूप चुनिए: 'I am looking forward to ___ from you soon.'", ["hear", "have heard", "hearing", "be hearing"], "यहाँ 'to' preposition है, इसके बाद gerund आता है।"]),
  q(2, "english", "grammar", "M", 1,
    ["Fill in the blank: 'The jewellery she wore ___ very expensive.'", ["were", "was", "are", "have been"], "'Jewellery' is uncountable and singular."],
    ["रिक्त स्थान भरिए: 'The jewellery she wore ___ very expensive.'", ["were", "was", "are", "have been"], "'Jewellery' अगणनीय व एकवचन है।"]),
  q(2, "english", "error-spotting", "H", 2,
    ["Find the part with an error: 'She told (A) me that (B) she will come (C) the next day. (D)'", ["A", "B", "C", "D"], "In reported speech 'will' becomes 'would'."],
    ["त्रुटि वाला भाग चुनिए: 'She told (A) me that (B) she will come (C) the next day. (D)'", ["A", "B", "C", "D"], "Reported speech में 'will', 'would' बन जाता है।"]),
  q(2, "english", "error-spotting", "M", 3,
    ["Find the part with an error: 'He is (A) one of (B) the best player (C) in our school. (D)'", ["A", "B", "D", "C"], "'One of the' is followed by a plural noun: 'best players'."],
    ["त्रुटि वाला भाग चुनिए: 'He is (A) one of (B) the best player (C) in our school. (D)'", ["A", "B", "D", "C"], "'One of the' के बाद बहुवचन संज्ञा आती है: 'best players'।"]),
  q(2, "english", "error-spotting", "H", 0,
    ["Find the part with an error: 'The teacher (A) congratulated to (B) the winners (C) of the quiz. (D)'", ["B", "A", "C", "D"], "'Congratulate' is transitive: no 'to'."],
    ["त्रुटि वाला भाग चुनिए: 'The teacher (A) congratulated to (B) the winners (C) of the quiz. (D)'", ["B", "A", "C", "D"], "'Congratulate' सकर्मक है: 'to' नहीं आता।"]),
  q(2, "english", "voice-speech", "H", 1,
    ["Change to the passive: 'Someone has stolen my bicycle.'", ["My bicycle is stolen by someone.", "My bicycle has been stolen.", "My bicycle was being stolen.", "My bicycle had stolen."], "Present perfect passive: has been + past participle."],
    ["Passive में बदलिए: 'Someone has stolen my bicycle.'", ["My bicycle is stolen by someone.", "My bicycle has been stolen.", "My bicycle was being stolen.", "My bicycle had stolen."], "Present perfect का passive: has been + past participle।"]),
  q(2, "english", "voice-speech", "M", 2,
    ["Change to indirect speech: 'She said to him, \"Please help me.\"'", ["She told him that please help me.", "She said him to help her.", "She requested him to help her.", "She asked him help her."], "A polite request is reported with 'requested'."],
    ["Indirect speech में बदलिए: 'She said to him, \"Please help me.\"'", ["She told him that please help me.", "She said him to help her.", "She requested him to help her.", "She asked him help her."], "विनम्र अनुरोध को 'requested' से बताया जाता है।"]),
  q(2, "english", "vocabulary", "M", 0,
    ["Which word is a synonym of 'BRIEF'?", ["Short", "Endless", "Wide", "Heavy"], "Brief means of short duration."],
    ["'BRIEF' का पर्यायवाची शब्द कौन-सा है?", ["Short", "Endless", "Wide", "Heavy"], "Brief का अर्थ थोड़ी अवधि का है।"]),
  q(2, "english", "synonyms-antonyms", "H", 3,
    ["The antonym of 'CONCEAL' is:", ["Hide", "Cover", "Bury", "Reveal"], "Conceal means to hide; reveal is the opposite."],
    ["'CONCEAL' का विलोम है:", ["Hide", "Cover", "Bury", "Reveal"], "Conceal का अर्थ छिपाना है; reveal उसका उलटा है।"]),
  q(2, "english", "synonyms-antonyms", "M", 1,
    ["The antonym of 'EXTERNAL' is:", ["Outer", "Internal", "Outside", "Foreign"], "External is outside; internal is inside."],
    ["'EXTERNAL' का विलोम है:", ["Outer", "Internal", "Outside", "Foreign"], "External बाहरी है; internal आंतरिक है।"]),
  q(2, "english", "idioms", "H", 2,
    ["The idiom 'to have a sweet tooth' means to:", ["Have dental trouble", "Dislike sweets", "Be fond of sweet things", "Be a cook"], "It means to love sweets."],
    ["'to have a sweet tooth' का अर्थ है:", ["दाँतों की समस्या होना", "मिठाई नापसंद करना", "मीठी चीज़ों का शौकीन होना", "रसोइया होना"], "इसका अर्थ है मिठाइयों का शौकीन होना।"]),
  q(2, "english", "idioms", "M", 3,
    ["'A bolt from the blue' means:", ["A lightning rod", "A planned event", "A blue colour", "A sudden, unexpected event"], "It refers to a complete surprise."],
    ["'A bolt from the blue' का अर्थ है:", ["तड़ित-चालक", "योजनाबद्ध घटना", "नीला रंग", "अचानक, अप्रत्याशित घटना"], "यह पूर्णतः अचानक आई बात के लिए है।"]),
  q(2, "english", "idioms", "H", 0,
    ["To 'turn over a new leaf' is to:", ["Begin to behave better and start afresh", "Change a book", "Fall from a tree", "Read quickly"], "The idiom means to start a better way of life."],
    ["'turn over a new leaf' का अर्थ है:", ["बेहतर आचरण करना और नए सिरे से शुरू करना", "पुस्तक बदलना", "पेड़ से गिरना", "तेज़ पढ़ना"], "इसका अर्थ है बेहतर जीवन की शुरुआत करना।"]),
  q(2, "english", "one-word", "M", 2,
    ["Which single word means 'a person who studies the stars'?", ["Astrologer", "Archaeologist", "Astronomer", "Geologist"], "An astronomer studies celestial bodies scientifically."],
    ["'तारों का अध्ययन करने वाला व्यक्ति' के लिए एक शब्द कौन-सा है?", ["Astrologer", "Archaeologist", "Astronomer", "Geologist"], "Astronomer आकाशीय पिंडों का वैज्ञानिक अध्ययन करता है।"]),
  q(2, "english", "one-word", "H", 1,
    ["Which single word means 'to kill a king'?", ["Homicide", "Regicide", "Suicide", "Fratricide"], "Regicide is the killing of a king."],
    ["'राजा की हत्या' के लिए एक शब्द कौन-सा है?", ["Homicide", "Regicide", "Suicide", "Fratricide"], "Regicide राजा की हत्या है।"]),
  q(2, "english", "spelling", "M", 3,
    ["Select the correct spelling of the verb meaning 'to take place':", ["Occure", "Ocur", "Occurr", "Occur"], "The word is spelt occur."],
    ["'घटित होना' अर्थ वाली क्रिया की सही वर्तनी चुनिए:", ["Occure", "Ocur", "Occurr", "Occur"], "सही वर्तनी occur है।"]),
  q(2, "english", "spelling", "H", 0,
    ["Select the correct spelling of the adjective meaning 'happening once a year':", ["Annual", "Anual", "Annuel", "Annul"], "The word is annual."],
    ["'वर्ष में एक बार होने वाला' अर्थ वाले विशेषण की सही वर्तनी चुनिए:", ["Annual", "Anual", "Annuel", "Annul"], "सही शब्द annual है।"]),
  q(2, "english", "comprehension", "M", 1,
    ["Which strategy best helps learners understand an unseen reading passage?", ["Reading it once, very fast", "Predicting from the title and guessing meaning from context", "Translating each word", "Copying it"], "Prediction and context clues build comprehension."],
    ["अपठित गद्यांश को समझने में शिक्षार्थियों की सबसे अधिक सहायता कौन-सी युक्ति करती है?", ["इसे एक बार बहुत तेज़ पढ़ना", "शीर्षक से अनुमान लगाना और संदर्भ से अर्थ निकालना", "हर शब्द का अनुवाद करना", "इसे उतारना"], "अनुमान और संदर्भ-संकेत बोध बढ़ाते हैं।"]),
  q(2, "english", "comprehension", "H", 3,
    ["In language teaching, 'scanning' means reading a text to:", ["Understand every word", "Memorise it", "Improve handwriting", "Find specific information quickly"], "Scanning looks for particular details such as names or dates."],
    ["भाषा-शिक्षण में 'स्कैनिंग' का अर्थ है किसी पाठ को पढ़ना ताकि:", ["हर शब्द समझा जाए", "उसे याद किया जाए", "लिखावट सुधरे", "विशिष्ट जानकारी शीघ्र ढूँढी जाए"], "स्कैनिंग नाम या तिथि जैसे विशेष ब्योरे ढूँढती है।"]),
  q(2, "english", "comprehension", "M", 0,
    ["Which type of question best tests a pupil's understanding of a story at the inferential level?", ["Why do you think the girl stayed silent?", "What was the girl's name?", "Where did the story take place?", "How many characters were there?"], "Inferential questions ask for reasoning beyond what is stated."],
    ["कहानी की अनुमानात्मक स्तर पर समझ परखने के लिए कौन-सा प्रश्न-प्रकार सबसे उपयुक्त है?", ["तुम्हारे विचार से लड़की चुप क्यों रही?", "लड़की का नाम क्या था?", "कहानी कहाँ घटित हुई?", "कितने पात्र थे?"], "अनुमानात्मक प्रश्न कही गई बात से आगे तर्क माँगते हैं।"]),
  q(2, "english", "grammar", "H", 2,
    ["Which sentence shows correct agreement after 'neither … nor' with a plural noun nearby?", ["Neither the teacher nor the pupils was late.", "Neither the teacher nor the pupils is late.", "Neither the teacher nor the pupils were late.", "Neither the teacher nor the pupils has been late."], "The verb agrees with the nearer subject 'pupils'."],
    ["सही वाक्य चुनिए (निकटतम कर्ता के अनुसार क्रिया)।", ["Neither the teacher nor the pupils was late.", "Neither the teacher nor the pupils is late.", "Neither the teacher nor the pupils were late.", "Neither the teacher nor the pupils has been late."], "क्रिया निकटतम कर्ता 'pupils' के अनुसार आती है।"]),
  q(2, "english", "grammar", "M", 3,
    ["Which comparison of height is expressed correctly?", ["He is taller than me by a head.", "He is more taller than I.", "He is tallest than me.", "He is taller than I am."], "The comparison 'than I am' is the formal complete form."],
    ["सही वाक्य चुनिए (तुलना के लिए)।", ["He is taller than me by a head.", "He is more taller than I.", "He is tallest than me.", "He is taller than I am."], "औपचारिक पूर्ण रूप 'than I am' है।"]),

  q(2, "english", "grammar", "M", 1,
    ["Fill in the blank: 'The old man is addicted ___ smoking.'", ["with", "to", "for", "on"], "The fixed phrase is 'addicted to'."],
    ["रिक्त स्थान भरिए: 'The old man is addicted ___ smoking.'", ["with", "to", "for", "on"], "स्थिर पदबंध 'addicted to' है।"]),

  // ───────── Section 3: Mathematics (30) ─────────
  q(3, "mathematics", "algebra", "E", 2,
    ["If n(A) = 20, n(B) = 15 and n(A ∩ B) = 5, then n(A ∪ B) is:", ["25", "35", "30", "40"], "n(A ∪ B) = 20 + 15 – 5 = 30."],
    ["यदि n(A) = 20, n(B) = 15 और n(A ∩ B) = 5 है तो n(A ∪ B) है:", ["25", "35", "30", "40"], "n(A ∪ B) = 20 + 15 – 5 = 30।"], "20+15-5"),
  q(3, "mathematics", "algebra", "M", 0,
    ["The sum of the roots of the equation x² – 7x + 10 = 0 is:", ["7", "10", "–7", "3"], "Sum of roots = –b/a = 7."],
    ["समीकरण x² – 7x + 10 = 0 के मूलों का योग है:", ["7", "10", "–7", "3"], "मूलों का योग = –b/a = 7।"], "7"),
  q(3, "mathematics", "algebra", "M", 3,
    ["The 5th term of an AP whose first term is 3 and common difference 4 is:", ["15", "17", "21", "19"], "a + 4d = 3 + 16 = 19."],
    ["एक समांतर श्रेढ़ी का प्रथम पद 3 और सार्व अंतर 4 है। उसका 5वाँ पद है:", ["15", "17", "21", "19"], "a + 4d = 3 + 16 = 19।"], "3+4*4"),
  q(3, "mathematics", "algebra", "M", 1,
    ["The sum of the first 10 terms of the AP 2, 5, 8, … is:", ["145", "155", "165", "175"], "S = 10/2 × (2·2 + 9·3) = 5 × 31 = 155."],
    ["समांतर श्रेढ़ी 2, 5, 8, … के पहले 10 पदों का योग है:", ["145", "155", "165", "175"], "S = 10/2 × (2·2 + 9·3) = 5 × 31 = 155।"], "5*31"),
  q(3, "mathematics", "algebra", "M", 2,
    ["The 5th term of the GP 2, 6, 18, … is:", ["54", "108", "162", "486"], "ar⁴ = 2 × 81 = 162."],
    ["गुणोत्तर श्रेढ़ी 2, 6, 18, … का 5वाँ पद है:", ["54", "108", "162", "486"], "ar⁴ = 2 × 81 = 162।"], "2*81"),
  q(3, "mathematics", "algebra", "M", 0,
    ["The value of log₂ 64 is:", ["6", "5", "7", "8"], "2⁶ = 64, so log₂ 64 = 6."],
    ["log₂ 64 का मान है:", ["6", "5", "7", "8"], "2⁶ = 64, इसलिए log₂ 64 = 6।"], "6"),
  q(3, "mathematics", "algebra", "M", 3,
    ["The modulus of the complex number 3 + 4i is:", ["7", "1", "25", "5"], "|z| = √(9 + 16) = 5."],
    ["सम्मिश्र संख्या 3 + 4i का मापांक है:", ["7", "1", "25", "5"], "|z| = √(9 + 16) = 5।"], "5"),
  q(3, "mathematics", "algebra", "M", 1,
    ["The determinant of the matrix [[2, 3], [1, 4]] is:", ["8", "5", "11", "–5"], "2×4 – 3×1 = 5."],
    ["आव्यूह [[2, 3], [1, 4]] का सारणिक है:", ["8", "5", "11", "–5"], "2×4 – 3×1 = 5।"], "2*4-3*1"),
  q(3, "mathematics", "statistics-probability", "M", 2,
    ["The value of ⁵P₂ is:", ["10", "15", "20", "25"], "5 × 4 = 20."],
    ["⁵P₂ का मान है:", ["10", "15", "20", "25"], "5 × 4 = 20।"], "5*4"),
  q(3, "mathematics", "statistics-probability", "M", 0,
    ["The value of ⁶C₂ is:", ["15", "12", "30", "20"], "6 × 5 ÷ 2 = 15."],
    ["⁶C₂ का मान है:", ["15", "12", "30", "20"], "6 × 5 ÷ 2 = 15।"], "6*5/2"),
  q(3, "mathematics", "statistics-probability", "H", 1,
    ["Two fair dice are thrown. The probability that the sum of the numbers is 7 is:", ["1/12", "1/6", "1/9", "5/36"], "Six of the 36 outcomes give a sum of 7."],
    ["दो निष्पक्ष पासे फेंके जाते हैं। संख्याओं का योग 7 होने की प्रायिकता है:", ["1/12", "1/6", "1/9", "5/36"], "36 में से 6 परिणामों का योग 7 होता है।"]),
  q(3, "mathematics", "trigonometry", "E", 1,
    ["The value of sin² 25° + cos² 25° is:", ["0", "1", "2", "1/2"], "sin²θ + cos²θ = 1 for every θ."],
    ["sin² 25° + cos² 25° का मान है:", ["0", "1", "2", "1/2"], "प्रत्येक θ के लिए sin²θ + cos²θ = 1।"], "1"),
  q(3, "mathematics", "trigonometry", "H", 3,
    ["The value of sin 60° cos 30° + cos 60° sin 30° is:", ["1/2", "√3/2", "3/4", "1"], "It equals sin(60° + 30°) = sin 90° = 1."],
    ["sin 60° cos 30° + cos 60° sin 30° का मान है:", ["1/2", "√3/2", "3/4", "1"], "यह sin(60° + 30°) = sin 90° = 1 के बराबर है।"]),
  q(3, "mathematics", "trigonometry", "M", 0,
    ["The shadow of a vertical pole is 10 m long when the angle of elevation of the sun is 45°. The height of the pole is:", ["10 m", "5 m", "10√3 m", "20 m"], "tan 45° = 1, so height = shadow = 10 m."],
    ["सूर्य का उन्नयन कोण 45° होने पर एक ऊर्ध्वाधर खंभे की छाया 10 मी लंबी है। खंभे की ऊँचाई है:", ["10 मी", "5 मी", "10√3 मी", "20 मी"], "tan 45° = 1, इसलिए ऊँचाई = छाया = 10 मी।"], "10"),
  q(3, "mathematics", "coordinate-geometry", "E", 2,
    ["The distance between the points (0, 0) and (6, 8) is:", ["7", "12", "10", "14"], "√(36 + 64) = 10."],
    ["बिंदुओं (0, 0) और (6, 8) के बीच की दूरी है:", ["7", "12", "10", "14"], "√(36 + 64) = 10।"], "10"),
  q(3, "mathematics", "coordinate-geometry", "M", 1,
    ["The slope of the line joining (1, 2) and (3, 8) is:", ["2", "3", "4", "6"], "(8 – 2) ÷ (3 – 1) = 3."],
    ["बिंदुओं (1, 2) और (3, 8) को मिलाने वाली रेखा की प्रवणता है:", ["2", "3", "4", "6"], "(8 – 2) ÷ (3 – 1) = 3।"], "(8-2)/(3-1)"),
  q(3, "mathematics", "coordinate-geometry", "M", 3,
    ["The equation of a circle with centre at the origin and radius 5 is:", ["x + y = 5", "x² + y² = 5", "x² – y² = 25", "x² + y² = 25"], "x² + y² = r²."],
    ["मूल बिंदु पर केंद्र और त्रिज्या 5 वाले वृत्त का समीकरण है:", ["x + y = 5", "x² + y² = 5", "x² – y² = 25", "x² + y² = 25"], "x² + y² = r²।"]),
  q(3, "mathematics", "calculus", "E", 0,
    ["The derivative of x³ with respect to x is:", ["3x²", "x²", "3x", "x⁴/4"], "d/dx(xⁿ) = n xⁿ⁻¹."],
    ["x³ का x के सापेक्ष अवकलज है:", ["3x²", "x²", "3x", "x⁴/4"], "d/dx(xⁿ) = n xⁿ⁻¹।"]),
  q(3, "mathematics", "calculus", "M", 2,
    ["The derivative of sin x is:", ["– cos x", "– sin x", "cos x", "tan x"], "d/dx(sin x) = cos x."],
    ["sin x का अवकलज है:", ["– cos x", "– sin x", "cos x", "tan x"], "d/dx(sin x) = cos x।"]),
  q(3, "mathematics", "calculus", "M", 1,
    ["∫ x dx equals:", ["x² + C", "x²/2 + C", "2x + C", "1 + C"], "The integral of x is x²/2 plus a constant."],
    ["∫ x dx बराबर है:", ["x² + C", "x²/2 + C", "2x + C", "1 + C"], "x का समाकल x²/2 जमा एक अचर है।"]),
  q(3, "mathematics", "calculus", "M", 3,
    ["The value of ∫ from 0 to 3 of 2x dx is:", ["3", "6", "12", "9"], "[x²] from 0 to 3 = 9."],
    ["∫ (0 से 3 तक) 2x dx का मान है:", ["3", "6", "12", "9"], "[x²] (0 से 3) = 9।"], "9"),
  q(3, "mathematics", "calculus", "M", 0,
    ["The limit of (sin x)/x as x tends to 0 is:", ["1", "0", "∞", "–1"], "This is a standard limit equal to 1."],
    ["x → 0 पर (sin x)/x की सीमा है:", ["1", "0", "∞", "–1"], "यह मानक सीमा है जिसका मान 1 है।"]),
  q(3, "mathematics", "calculus", "H", 2,
    ["The minimum value of f(x) = x² – 4x + 5 is:", ["0", "5", "1", "–1"], "f(x) = (x – 2)² + 1, so the minimum is 1."],
    ["f(x) = x² – 4x + 5 का न्यूनतम मान है:", ["0", "5", "1", "–1"], "f(x) = (x – 2)² + 1, इसलिए न्यूनतम मान 1 है।"], "1"),
  q(3, "mathematics", "statistics-probability", "E", 1,
    ["The mean of 2, 4, 6, 8, 10 is:", ["5", "6", "7", "8"], "30 ÷ 5 = 6."],
    ["2, 4, 6, 8, 10 का माध्य है:", ["5", "6", "7", "8"], "30 ÷ 5 = 6।"], "6"),
  q(3, "mathematics", "statistics-probability", "H", 3,
    ["The variance of the numbers 2, 4, 6, 8, 10 is:", ["4", "10", "6", "8"], "Deviations –4, –2, 0, 2, 4 give 40 ÷ 5 = 8."],
    ["संख्याओं 2, 4, 6, 8, 10 का प्रसरण है:", ["4", "10", "6", "8"], "विचलन –4, –2, 0, 2, 4 से 40 ÷ 5 = 8।"], "8"),
  q(3, "mathematics", "geometry-mensuration", "M", 2,
    ["The sum of the exterior angles of any convex polygon is:", ["180°", "270°", "360°", "540°"], "It is always 360°."],
    ["किसी भी उत्तल बहुभुज के बाह्य कोणों का योग होता है:", ["180°", "270°", "360°", "540°"], "यह सदैव 360° होता है।"], "360"),
  q(3, "mathematics", "geometry-mensuration", "M", 0,
    ["The curved surface area of a cylinder of radius 7 cm and height 10 cm is (π = 22/7):", ["440 cm²", "220 cm²", "880 cm²", "1,540 cm²"], "2πrh = 2 × (22/7) × 7 × 10 = 440 cm²."],
    ["7 सेमी त्रिज्या और 10 सेमी ऊँचाई वाले बेलन का वक्र पृष्ठीय क्षेत्रफल है (π = 22/7):", ["440 सेमी²", "220 सेमी²", "880 सेमी²", "1,540 सेमी²"], "2πrh = 2 × (22/7) × 7 × 10 = 440 सेमी²।"], "2*22/7*7*10"),
  q(3, "mathematics", "algebra", "H", 1,
    ["The dot product of the vectors (1, 2, 3) and (4, 5, 6) is:", ["28", "32", "36", "21"], "1×4 + 2×5 + 3×6 = 32."],
    ["सदिशों (1, 2, 3) और (4, 5, 6) का अदिश गुणनफल है:", ["28", "32", "36", "21"], "1×4 + 2×5 + 3×6 = 32।"], "1*4+2*5+3*6"),
  q(3, "mathematics", "geometry-mensuration", "M", 2,
    ["The number of diagonals in a hexagon is:", ["6", "8", "9", "12"], "n(n – 3)/2 = 6 × 3 ÷ 2 = 9."],
    ["षट्भुज के विकर्णों की संख्या है:", ["6", "8", "9", "12"], "n(n – 3)/2 = 6 × 3 ÷ 2 = 9।"], "6*3/2"),

  q(3, "mathematics", "statistics-probability", "H", 2,
    ["A fair coin is tossed three times. The probability of getting exactly two heads is:", ["1/8", "1/4", "3/8", "1/2"], "Three of the eight equally likely outcomes have exactly two heads."],
    ["एक निष्पक्ष सिक्का तीन बार उछाला जाता है। ठीक दो चित आने की प्रायिकता है:", ["1/8", "1/4", "3/8", "1/2"], "आठ समप्रायिक परिणामों में से तीन में ठीक दो चित आते हैं।"]),

  // ───────── Section 4: Physics & Chemistry (30) ─────────
  q(4, "physics", "mechanics", "E", 1,
    ["The force required to give a mass of 5 kg an acceleration of 3 m/s² is:", ["8 N", "15 N", "1.67 N", "2 N"], "F = ma = 5 × 3 = 15 N."],
    ["5 किग्रा द्रव्यमान को 3 मी/से² त्वरण देने के लिए आवश्यक बल है:", ["8 N", "15 N", "1.67 N", "2 N"], "F = ma = 5 × 3 = 15 N।"], "5*3"),
  q(4, "physics", "mechanics", "M", 2,
    ["The kinetic energy of a 2 kg body moving at 4 m/s is:", ["8 J", "4 J", "16 J", "32 J"], "KE = ½mv² = ½ × 2 × 16 = 16 J."],
    ["4 मी/से की चाल से गतिमान 2 किग्रा पिंड की गतिज ऊर्जा है:", ["8 J", "4 J", "16 J", "32 J"], "KE = ½mv² = ½ × 2 × 16 = 16 J।"], "0.5*2*16"),
  q(4, "physics", "mechanics", "M", 0,
    ["The escape velocity from the surface of the Earth is about:", ["11.2 km/s", "7.9 km/s", "3 km/s", "30 km/s"], "Escape velocity from Earth is roughly 11.2 km/s."],
    ["पृथ्वी की सतह से पलायन वेग लगभग कितना है?", ["11.2 किमी/से", "7.9 किमी/से", "3 किमी/से", "30 किमी/से"], "पृथ्वी से पलायन वेग लगभग 11.2 किमी/से है।"]),
  q(4, "physics", "mechanics", "E", 3,
    ["One watt is equal to one:", ["Newton per second", "Joule per metre", "Newton-metre", "Joule per second"], "Power is the rate of doing work: 1 W = 1 J/s."],
    ["एक वाट बराबर है:", ["एक न्यूटन प्रति सेकंड", "एक जूल प्रति मीटर", "एक न्यूटन-मीटर", "एक जूल प्रति सेकंड"], "शक्ति कार्य की दर है: 1 W = 1 J/s।"]),
  q(4, "physics", "electricity-magnetism", "M", 1,
    ["A potential difference of 10 V across a 5 Ω resistor drives a current of:", ["0.5 A", "2 A", "5 A", "50 A"], "I = V ÷ R = 10 ÷ 5 = 2 A."],
    ["5 Ω प्रतिरोध पर 10 V का विभवांतर कितनी धारा बहाता है?", ["0.5 A", "2 A", "5 A", "50 A"], "I = V ÷ R = 10 ÷ 5 = 2 A।"], "10/5"),
  q(4, "physics", "electricity-magnetism", "H", 2,
    ["The equivalent resistance of 3 Ω and 6 Ω connected in parallel is:", ["9 Ω", "4.5 Ω", "2 Ω", "1 Ω"], "(3 × 6) ÷ (3 + 6) = 2 Ω."],
    ["समानांतर क्रम में जुड़े 3 Ω और 6 Ω का तुल्य प्रतिरोध है:", ["9 Ω", "4.5 Ω", "2 Ω", "1 Ω"], "(3 × 6) ÷ (3 + 6) = 2 Ω।"], "3*6/9"),
  q(4, "physics", "optics-waves", "M", 3,
    ["The refractive index of a medium is the ratio of the speed of light in:", ["The medium to that in vacuum", "Water to that in air", "Glass to that in water", "Vacuum to that in the medium"], "n = c ÷ v."],
    ["किसी माध्यम का अपवर्तनांक किन गतियों का अनुपात है?", ["माध्यम में प्रकाश की चाल और निर्वात में चाल", "जल में प्रकाश की चाल और वायु में चाल", "काँच में प्रकाश की चाल और जल में चाल", "निर्वात में प्रकाश की चाल और माध्यम में चाल"], "n = c ÷ v।"]),
  q(4, "physics", "optics-waves", "M", 0,
    ["A lens of focal length 50 cm has a power of:", ["2 D", "0.5 D", "50 D", "5 D"], "P = 100 ÷ f(cm) = 2 D."],
    ["50 सेमी फ़ोकस दूरी वाले लेंस की क्षमता है:", ["2 D", "0.5 D", "50 D", "5 D"], "P = 100 ÷ f(सेमी) = 2 D।"], "100/50"),
  q(4, "physics", "optics-waves", "M", 2,
    ["Total internal reflection can occur when light travels from:", ["Rarer to denser medium", "Vacuum to glass", "Denser to rarer medium", "Air to water"], "It needs travel from a denser to a rarer medium at an angle beyond the critical angle."],
    ["पूर्ण आंतरिक परावर्तन तब हो सकता है जब प्रकाश चलता है:", ["विरल से सघन माध्यम में", "निर्वात से काँच में", "सघन से विरल माध्यम में", "वायु से जल में"], "इसके लिए सघन से विरल माध्यम में क्रांतिक कोण से अधिक कोण पर चलना आवश्यक है।"]),
  q(4, "physics", "optics-waves", "E", 1,
    ["The speed of sound in air at room temperature is about:", ["34 m/s", "340 m/s", "3,400 m/s", "3 × 10⁸ m/s"], "Sound travels at about 340 m/s in air."],
    ["कमरे के ताप पर वायु में ध्वनि की चाल लगभग कितनी है?", ["34 मी/से", "340 मी/से", "3,400 मी/से", "3 × 10⁸ मी/से"], "वायु में ध्वनि लगभग 340 मी/से की चाल से चलती है।"]),
  q(4, "physics", "modern-physics", "M", 3,
    ["The photoelectric effect was explained by:", ["Newton", "Faraday", "Maxwell", "Einstein"], "Einstein explained it using quanta of light in 1905."],
    ["प्रकाश-विद्युत प्रभाव की व्याख्या किसने की?", ["न्यूटन", "फैराडे", "मैक्सवेल", "आइंस्टाइन"], "आइंस्टाइन ने 1905 में प्रकाश के क्वांटा से इसकी व्याख्या की।"]),
  q(4, "physics", "modern-physics", "H", 1,
    ["A sample of 80 g of a radioactive element has a half-life of 2 days. The mass left after 6 days is:", ["20 g", "10 g", "5 g", "40 g"], "Three half-lives: 80 → 40 → 20 → 10 g."],
    ["80 ग्राम के एक रेडियोधर्मी तत्व की अर्धायु 2 दिन है। 6 दिन बाद शेष द्रव्यमान है:", ["20 ग्राम", "10 ग्राम", "5 ग्राम", "40 ग्राम"], "तीन अर्धायु: 80 → 40 → 20 → 10 ग्राम।"], "80/8"),
  q(4, "physics", "heat-thermodynamics", "M", 2,
    ["Heat needed to raise the temperature of 2 kg of water by 10 °C (specific heat 4,200 J/kg·K) is:", ["42,000 J", "21,000 J", "84,000 J", "8,400 J"], "Q = mcΔT = 2 × 4200 × 10 = 84,000 J."],
    ["2 किग्रा जल का ताप 10 °C बढ़ाने के लिए आवश्यक ऊष्मा है (विशिष्ट ऊष्मा 4,200 J/किग्रा·K):", ["42,000 J", "21,000 J", "84,000 J", "8,400 J"], "Q = mcΔT = 2 × 4200 × 10 = 84,000 J।"], "2*4200*10"),
  q(4, "physics", "modern-physics", "M", 0,
    ["Which isotope is most commonly used as fuel in nuclear fission reactors?", ["Uranium-235", "Carbon-14", "Hydrogen-1", "Helium-4"], "U-235 undergoes fission with slow neutrons."],
    ["नाभिकीय विखंडन रिएक्टरों में ईंधन के रूप में सबसे अधिक कौन-सा समस्थानिक प्रयुक्त होता है?", ["यूरेनियम-235", "कार्बन-14", "हाइड्रोजन-1", "हीलियम-4"], "यूरेनियम-235 धीमे न्यूट्रॉनों से विखंडित होता है।"]),
  q(4, "physics", "optics-waves", "M", 3,
    ["The apparent change in the frequency of a wave due to relative motion of the source and observer is called the:", ["Interference", "Diffraction", "Polarisation", "Doppler effect"], "This is the Doppler effect."],
    ["स्रोत और प्रेक्षक की सापेक्ष गति के कारण तरंग की आवृत्ति में आभासी परिवर्तन को कहते हैं:", ["व्यतिकरण", "विवर्तन", "ध्रुवण", "डॉप्लर प्रभाव"], "यह डॉप्लर प्रभाव है।"]),
  q(4, "chemistry", "atomic-structure", "E", 2,
    ["How many protons does a carbon atom have, i.e. what is its atomic number?", ["4", "8", "6", "12"], "Carbon has 6 protons."],
    ["कार्बन की परमाणु संख्या है:", ["4", "8", "6", "12"], "कार्बन में 6 प्रोटॉन होते हैं।"], "6"),
  q(4, "chemistry", "atomic-structure", "M", 1,
    ["The number of neutrons in the atom ²³₁₁Na is:", ["11", "12", "23", "34"], "Neutrons = mass number – atomic number = 23 – 11 = 12."],
    ["परमाणु ²³₁₁Na में न्यूट्रॉनों की संख्या है:", ["11", "12", "23", "34"], "न्यूट्रॉन = द्रव्यमान संख्या – परमाणु संख्या = 23 – 11 = 12।"], "23-11"),
  q(4, "chemistry", "atomic-structure", "M", 0,
    ["The noble gases are placed in which group of the modern periodic table?", ["Group 18", "Group 1", "Group 17", "Group 2"], "Helium, neon, argon and others form Group 18."],
    ["आधुनिक आवर्त सारणी में उत्कृष्ट गैसें किस समूह में रखी गई हैं?", ["समूह 18", "समूह 1", "समूह 17", "समूह 2"], "हीलियम, नियॉन, आर्गन आदि समूह 18 बनाती हैं।"]),
  q(4, "chemistry", "chemical-bonding", "E", 3,
    ["The bond between sodium and chlorine in common salt is:", ["Covalent", "Metallic", "Hydrogen", "Ionic"], "Sodium gives an electron to chlorine, forming an ionic bond."],
    ["साधारण नमक में सोडियम और क्लोरीन के बीच का बंध है:", ["सहसंयोजक", "धात्विक", "हाइड्रोजन", "आयनिक"], "सोडियम क्लोरीन को इलेक्ट्रॉन देता है, जिससे आयनिक बंध बनता है।"]),
  q(4, "chemistry", "chemical-bonding", "M", 2,
    ["The hybridisation of carbon in methane (CH₄) is:", ["sp", "sp²", "sp³", "dsp²"], "Four sigma bonds mean sp³ hybridisation."],
    ["मेथेन (CH₄) में कार्बन का संकरण है:", ["sp", "sp²", "sp³", "dsp²"], "चार सिग्मा बंध sp³ संकरण दर्शाते हैं।"]),
  q(4, "chemistry", "acids-bases-salts", "H", 0,
    ["The pH of a 0.01 M solution of the strong acid HCl is:", ["2", "1", "0.01", "12"], "pH = –log(0.01) = 2."],
    ["प्रबल अम्ल HCl के 0.01 M विलयन का pH है:", ["2", "1", "0.01", "12"], "pH = –log(0.01) = 2।"], "2"),
  q(4, "chemistry", "physical-chemistry", "M", 1,
    ["Avogadro's number is approximately:", ["6.022 × 10²²", "6.022 × 10²³", "6.022 × 10²⁴", "3.011 × 10²³"], "One mole contains 6.022 × 10²³ particles."],
    ["एवोगैड्रो संख्या लगभग कितनी है?", ["6.022 × 10²²", "6.022 × 10²³", "6.022 × 10²⁴", "3.011 × 10²³"], "एक मोल में 6.022 × 10²³ कण होते हैं।"]),
  q(4, "chemistry", "physical-chemistry", "M", 3,
    ["The number of moles in 36 g of water (molar mass 18 g/mol) is:", ["1", "3", "4", "2"], "36 ÷ 18 = 2 moles."],
    ["36 ग्राम जल (मोलर द्रव्यमान 18 ग्राम/मोल) में मोलों की संख्या है:", ["1", "3", "4", "2"], "36 ÷ 18 = 2 मोल।"], "36/18"),
  q(4, "chemistry", "chemical-bonding", "H", 2,
    ["The oxidation state of manganese in KMnO₄ is:", ["+2", "+4", "+7", "+6"], "K = +1, 4 O = –8, so Mn = +7."],
    ["KMnO₄ में मैंगनीज़ की ऑक्सीकरण अवस्था है:", ["+2", "+4", "+7", "+6"], "K = +1, 4 O = –8, इसलिए Mn = +7।"], "7"),
  q(4, "chemistry", "physical-chemistry", "M", 1,
    ["In the electrolysis of brine (aqueous NaCl), chlorine gas is liberated at the:", ["Cathode", "Anode", "Salt bridge", "Both electrodes"], "Oxidation of chloride ions occurs at the anode."],
    ["खारे जल (NaCl विलयन) के विद्युत-अपघटन में क्लोरीन गैस कहाँ मुक्त होती है?", ["कैथोड पर", "ऐनोड पर", "लवण सेतु पर", "दोनों इलेक्ट्रोडों पर"], "क्लोराइड आयनों का ऑक्सीकरण ऐनोड पर होता है।"]),
  q(4, "chemistry", "organic-chemistry", "M", 2,
    ["The IUPAC name of CH₃CH₂OH is:", ["Methanol", "Ethanal", "Ethanol", "Propanol"], "Two carbons with an –OH group: ethanol."],
    ["CH₃CH₂OH का IUPAC नाम है:", ["मेथेनॉल", "एथेनल", "एथेनॉल", "प्रोपेनॉल"], "दो कार्बन और –OH समूह: एथेनॉल।"]),
  q(4, "chemistry", "organic-chemistry", "E", 0,
    ["The functional group present in carboxylic acids is:", ["–COOH", "–OH", "–CHO", "–NH₂"], "Carboxylic acids contain –COOH."],
    ["कार्बोक्सिलिक अम्लों में उपस्थित क्रियात्मक समूह है:", ["–COOH", "–OH", "–CHO", "–NH₂"], "कार्बोक्सिलिक अम्लों में –COOH होता है।"]),
  q(4, "chemistry", "physical-chemistry", "M", 3,
    ["The catalyst used in the Haber process for ammonia is:", ["Platinum", "Vanadium pentoxide", "Nickel", "Finely divided iron"], "Iron with promoters catalyses N₂ + 3H₂ → 2NH₃."],
    ["अमोनिया के हैबर प्रक्रम में प्रयुक्त उत्प्रेरक है:", ["प्लैटिनम", "वैनेडियम पेंटाऑक्साइड", "निकल", "बारीक लोहा चूर्ण"], "प्रवर्तकों सहित लोहा N₂ + 3H₂ → 2NH₃ को उत्प्रेरित करता है।"]),
  q(4, "chemistry", "physical-chemistry", "H", 0,
    ["According to Le Chatelier's principle, increasing the pressure on N₂ + 3H₂ ⇌ 2NH₃ shifts the equilibrium:", ["To the right, towards fewer gas moles", "To the left", "Nowhere", "Towards reactants and heat"], "The forward reaction reduces the number of gas moles from 4 to 2."],
    ["ले शातेलिए के सिद्धांत के अनुसार N₂ + 3H₂ ⇌ 2NH₃ पर दाब बढ़ाने से साम्य किस ओर खिसकता है?", ["दाईं ओर, गैस के कम मोलों की ओर", "बाईं ओर", "कहीं नहीं", "अभिकारकों और ऊष्मा की ओर"], "अग्र अभिक्रिया गैस के मोल 4 से घटाकर 2 कर देती है।"]),
  q(4, "chemistry", "acids-bases-salts", "E", 1,
    ["Rusting of iron needs the presence of:", ["Oxygen only", "Oxygen and moisture", "Nitrogen and dust", "Carbon dioxide only"], "Iron rusts in the presence of both oxygen and water."],
    ["लोहे में जंग लगने के लिए किसकी उपस्थिति आवश्यक है?", ["केवल ऑक्सीजन", "ऑक्सीजन और नमी", "नाइट्रोजन और धूल", "केवल कार्बन डाइऑक्साइड"], "लोहे में जंग ऑक्सीजन और जल दोनों की उपस्थिति में लगता है।"]),
];
