// HP TET (TGT Non-Medical) — Full Mock 2, written fresh: Child Development & Pedagogy 30, Hindi 30, English 30,
// Mathematics 30, Physics & Chemistry 30 (sections as in ./index.ts).

import { q, type PatwariQuestion } from "../patwari/types";

export const nonMedicalMock2: PatwariQuestion[] = [
  // ───────── Section 0: Child Development & Pedagogy (30) ─────────
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["Clark Hull's theory of learning explains behaviour mainly through:", ["Insight", "Observation", "Drive reduction", "Imprinting"], "Hull held that reinforcement is the reduction of a drive."],
    ["क्लार्क हल का अधिगम सिद्धांत व्यवहार की व्याख्या मुख्यतः किससे करता है?", ["अंतर्दृष्टि", "अवलोकन", "चालक-न्यूनता (ड्राइव रिडक्शन)", "छापन"], "हल के अनुसार पुनर्बलन किसी चालक (ड्राइव) में कमी है।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["Kurt Lewin's 'life space' refers to:", ["The person and the psychological environment as perceived by him", "A physical classroom area", "A teaching schedule", "A library corner"], "Life space = person + perceived environment."],
    ["कर्ट लेविन के 'जीवन-स्थल' (लाइफ़ स्पेस) का अर्थ है:", ["व्यक्ति और उसके द्वारा प्रत्यक्षित मनोवैज्ञानिक पर्यावरण", "कक्षा का भौतिक क्षेत्र", "शिक्षण की समय-सारणी", "पुस्तकालय का कोना"], "जीवन-स्थल = व्यक्ति + उसका प्रत्यक्षित पर्यावरण।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["Kolb's experiential learning cycle includes concrete experience, reflective observation, abstract conceptualisation and:", ["Passive listening", "Active experimentation", "Rote revision", "Formal testing"], "Kolb's four stages end with active experimentation."],
    ["कोल्ब के अनुभवजन्य अधिगम चक्र में मूर्त अनुभव, चिंतनशील अवलोकन, अमूर्त संप्रत्ययीकरण और क्या शामिल है?", ["निष्क्रिय श्रवण", "सक्रिय प्रयोग", "रटकर दोहराव", "औपचारिक परीक्षण"], "कोल्ब के चार चरण सक्रिय प्रयोग पर पूरे होते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["Humanistic psychologist Carl Rogers saw the teacher mainly as a:", ["Judge", "Drill master", "Examiner", "Facilitator of learning"], "Rogers advocated student-centred, facilitative teaching."],
    ["मानवतावादी मनोवैज्ञानिक कार्ल रोजर्स शिक्षक को मुख्यतः क्या मानते थे?", ["न्यायाधीश", "अभ्यास-निर्देशक", "परीक्षक", "अधिगम का सुगमकर्ता"], "रोजर्स ने विद्यार्थी-केंद्रित, सुगमकारी शिक्षण का समर्थन किया।"]),
  q(0, "pedagogy", "child-development", "H", 2,
    ["In Piaget's theory, the process of restoring balance between existing schemes and new experiences is called:", ["Conservation", "Centration", "Equilibration", "Seriation"], "Equilibration drives movement between stages."],
    ["पियाजे के सिद्धांत में मौजूदा स्कीमा और नए अनुभवों के बीच संतुलन पुनः स्थापित करने की प्रक्रिया क्या कहलाती है?", ["संरक्षण", "केंद्रीकरण", "साम्यधारण", "क्रमबद्धता"], "साम्यधारण अवस्थाओं के बीच संक्रमण को चलाता है।"]),
  q(0, "pedagogy", "child-development", "M", 0,
    ["A 'schema' in Piaget's theory is a:", ["Mental framework for organising knowledge", "School timetable", "Type of test", "Reflex"], "Schemas are organised patterns of thought or action."],
    ["पियाजे के सिद्धांत में 'स्कीमा' क्या है?", ["ज्ञान को व्यवस्थित करने की मानसिक रूपरेखा", "विद्यालय की समय-सारणी", "परीक्षण का प्रकार", "प्रतिवर्त"], "स्कीमा चिंतन या क्रिया के व्यवस्थित प्रतिरूप हैं।"]),
  q(0, "pedagogy", "child-development", "M", 3,
    ["According to Freud, the stage of psychosexual development from about 6 years to puberty is the:", ["Oral stage", "Anal stage", "Phallic stage", "Latency stage"], "The latency stage follows the phallic stage."],
    ["फ्रायड के अनुसार लगभग 6 वर्ष से यौवनारंभ तक की मनोलैंगिक विकास की अवस्था कौन-सी है?", ["मौखिक अवस्था", "गुदा अवस्था", "लिंग-प्रधान अवस्था", "सुषुप्तावस्था"], "सुषुप्तावस्था लिंग-प्रधान अवस्था के बाद आती है।"]),
  q(0, "pedagogy", "child-development", "M", 1,
    ["Development proceeding from head to foot is known as the:", ["Proximodistal principle", "Cephalocaudal principle", "Principle of continuity", "Principle of integration"], "Cephalocaudal means head to tail."],
    ["सिर से पैर की ओर होने वाले विकास को क्या कहते हैं?", ["निकट-दूर सिद्धांत", "शिरोपादाभिमुख (सेफ़ैलोकॉडल) सिद्धांत", "निरंतरता का सिद्धांत", "समेकन का सिद्धांत"], "सेफ़ैलोकॉडल का अर्थ सिर से पूँछ की ओर है।"]),
  q(0, "pedagogy", "child-development", "M", 2,
    ["Development proceeding from the centre of the body to the extremities, as in control of the arm before the fingers, is called the:", ["Cephalocaudal law", "Law of maturation", "Proximodistal law", "Law of use"], "Proximodistal means near to far."],
    ["शरीर के केंद्र से छोरों की ओर होने वाला विकास, जैसे उँगलियों से पहले भुजा पर नियंत्रण, क्या कहलाता है?", ["शिरोपादाभिमुख नियम", "परिपक्वता का नियम", "निकट-दूर (प्रॉक्सिमोडिस्टल) नियम", "उपयोग का नियम"], "प्रॉक्सिमोडिस्टल का अर्थ निकट से दूर की ओर है।"]),
  q(0, "pedagogy", "child-development", "H", 3,
    ["Havighurst's 'developmental tasks' are:", ["Games played by children", "Test items", "Teaching methods", "Tasks that arise at a certain life stage whose mastery leads to later success"], "Developmental tasks are age-related challenges to be mastered."],
    ["हैविगहर्स्ट के 'विकासात्मक कार्य' क्या हैं?", ["बच्चों द्वारा खेले जाने वाले खेल", "परीक्षण-प्रश्न", "शिक्षण-विधियाँ", "जीवन की किसी अवस्था में उठने वाले कार्य जिनमें दक्षता भावी सफलता देती है"], "विकासात्मक कार्य आयु से जुड़ी चुनौतियाँ हैं जिनमें निपुण होना होता है।"]),
  q(0, "pedagogy", "child-development", "H", 1,
    ["The 'looking-glass self' is the idea that self-concept develops from:", ["Reading about oneself", "How we think others see us", "Physical appearance only", "Exam marks only"], "Cooley held that we see ourselves reflected in others' reactions."],
    ["'लुकिंग-ग्लास सेल्फ़' का विचार है कि आत्म-संप्रत्यय विकसित होता है:", ["अपने बारे में पढ़ने से", "इस बात से कि हम सोचते हैं दूसरे हमें कैसे देखते हैं", "केवल शारीरिक रूप-रंग से", "केवल परीक्षा-अंकों से"], "कूले के अनुसार हम स्वयं को दूसरों की प्रतिक्रियाओं में प्रतिबिंबित देखते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["A curriculum that combines subjects such as physics, chemistry and biology into 'general science' is called:", ["Integrated curriculum", "Subject-centred only", "Hidden curriculum", "Extra-curriculum"], "Integration merges related subjects."],
    ["जो पाठ्यचर्या भौतिकी, रसायन और जीव विज्ञान जैसे विषयों को 'सामान्य विज्ञान' में मिलाती है, वह कहलाती है:", ["समेकित पाठ्यचर्या", "केवल विषय-केंद्रित", "छिपी पाठ्यचर्या", "पाठ्येतर"], "समेकन संबंधित विषयों को मिलाता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["A blueprint used in test construction shows:", ["The names of pupils", "The seating plan", "The invigilator's duty", "The weightage of content areas and objectives"], "A blueprint distributes marks across content and objectives."],
    ["परीक्षण-निर्माण में प्रयुक्त ब्लू-प्रिंट क्या दिखाता है?", ["विद्यार्थियों के नाम", "बैठक-व्यवस्था", "निरीक्षक का कर्तव्य", "विषय-क्षेत्रों और उद्देश्यों का भारांक"], "ब्लू-प्रिंट अंकों को विषय-वस्तु और उद्देश्यों में बाँटता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 2,
    ["A main advantage of objective-type questions over essay questions is that they:", ["Test creativity better", "Need no preparation", "Can be scored objectively and cover more content", "Cannot be guessed"], "Objective items give reliable, quick scoring and wide coverage."],
    ["निबंधात्मक प्रश्नों की तुलना में वस्तुनिष्ठ प्रश्नों का मुख्य लाभ यह है कि वे:", ["सृजनात्मकता को बेहतर जाँचते हैं", "तैयारी की माँग नहीं करते", "वस्तुनिष्ठ अंकन संभव करते हैं और अधिक विषय-वस्तु को समेटते हैं", "अनुमान से हल नहीं हो सकते"], "वस्तुनिष्ठ प्रश्न विश्वसनीय, त्वरित अंकन और व्यापक कवरेज देते हैं।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["Evaluation done at the start of a course to know the learners' entry level is called:", ["Summative evaluation", "Placement evaluation", "Terminal evaluation", "External evaluation"], "Placement evaluation finds where to start."],
    ["पाठ्यक्रम के आरंभ में शिक्षार्थियों का प्रवेश-स्तर जानने के लिए किया गया मूल्यांकन कहलाता है:", ["योगात्मक मूल्यांकन", "स्थान-निर्धारण मूल्यांकन", "सत्रांत मूल्यांकन", "बाह्य मूल्यांकन"], "स्थान-निर्धारण मूल्यांकन बताता है कि कहाँ से शुरू करना है।"]),
  q(0, "pedagogy", "inclusive-education", "M", 2,
    ["For the education of a gifted pupil, 'enrichment' means:", ["Skipping school", "Extra homework of the same type", "Providing wider and deeper learning experiences", "Removing the pupil from class"], "Enrichment adds depth and variety."],
    ["प्रतिभाशाली विद्यार्थी की शिक्षा के संदर्भ में 'संवर्धन' का अर्थ है:", ["विद्यालय छोड़ना", "उसी प्रकार का अतिरिक्त गृहकार्य", "अधिक व्यापक और गहरे अधिगम-अनुभव देना", "विद्यार्थी को कक्षा से हटाना"], "संवर्धन गहराई और विविधता जोड़ता है।"]),
  q(0, "pedagogy", "learning-theories", "H", 0,
    ["SWAYAM, the Indian platform that offers online courses, is run under the:", ["Ministry of Education", "Ministry of Railways", "Ministry of Defence", "Ministry of Mines"], "SWAYAM was launched by the Ministry of Education (then MHRD)."],
    ["ऑनलाइन पाठ्यक्रम उपलब्ध कराने वाला भारतीय मंच स्वयं (SWAYAM) किसके अंतर्गत संचालित है?", ["शिक्षा मंत्रालय", "रेल मंत्रालय", "रक्षा मंत्रालय", "खान मंत्रालय"], "स्वयं को शिक्षा मंत्रालय (तत्कालीन मानव संसाधन विकास मंत्रालय) ने शुरू किया।"]),
  q(0, "pedagogy", "learning-theories", "H", 3,
    ["The National Curriculum Framework for School Education (NCF-SE) was released in:", ["2005", "2009", "2020", "2023"], "NCF-SE 2023 followed NEP 2020."],
    ["स्कूली शिक्षा के लिए राष्ट्रीय पाठ्यचर्या की रूपरेखा (एनसीएफ-एसई) कब जारी हुई?", ["2005", "2009", "2020", "2023"], "एनसीएफ-एसई 2023 एनईपी 2020 के बाद आई।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["In a science class, the best way to arouse curiosity at the start of a lesson is to:", ["Dictate definitions", "Show a surprising demonstration and ask 'why?'", "Announce a test", "Read the summary"], "A discrepant event stimulates inquiry."],
    ["विज्ञान की कक्षा में पाठ के आरंभ में जिज्ञासा जगाने का सबसे अच्छा तरीका है:", ["परिभाषाएँ लिखवाना", "कोई आश्चर्यजनक प्रदर्शन दिखाकर 'क्यों?' पूछना", "परीक्षा की घोषणा करना", "सारांश पढ़ना"], "असंगत घटना जाँच-पड़ताल को प्रेरित करती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["Which of these is the most valid sign that a lesson in mathematics has succeeded?", ["Pupils were quiet", "The bell rang on time", "Pupils can apply the idea to new problems", "Notebooks were neat"], "Transfer to new problems shows real understanding."],
    ["गणित के पाठ की सफलता का सबसे वैध संकेत इनमें से कौन-सा है?", ["विद्यार्थी शांत थे", "घंटी समय पर बजी", "विद्यार्थी विचार को नई समस्याओं पर लागू कर पाते हैं", "कॉपियाँ साफ़ थीं"], "नई समस्याओं पर प्रयोग वास्तविक समझ को दर्शाता है।"]),
  q(0, "pedagogy", "inclusive-education", "H", 3,
    ["A teacher notices that a very bright pupil is bored and disruptive. The best response is to:", ["Punish him", "Ignore him", "Make him repeat the class", "Give him challenging, open-ended extension tasks"], "Challenge, not punishment, answers boredom in gifted learners."],
    ["शिक्षक देखता है कि एक अत्यंत कुशाग्र विद्यार्थी ऊब कर व्यवधान डाल रहा है। सर्वोत्तम प्रतिक्रिया है:", ["उसे दंडित करना", "उसे अनदेखा करना", "उसे वही कक्षा दोहरवाना", "उसे चुनौतीपूर्ण, खुले विस्तार-कार्य देना"], "प्रतिभाशाली शिक्षार्थियों की ऊब का उत्तर दंड नहीं, चुनौती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 0,
    ["The 'zone of proximal development' suggests that the teacher should set tasks that are:", ["Slightly beyond what the pupil can do alone", "Far above the pupil's level", "Far below the pupil's level", "Identical to last year's"], "Tasks should stretch the learner with support."],
    ["'समीपस्थ विकास क्षेत्र' के अनुसार शिक्षक को कैसे कार्य देने चाहिए?", ["जो विद्यार्थी अकेले जो कर सकता है उससे थोड़ा आगे के हों", "विद्यार्थी के स्तर से बहुत ऊपर के हों", "विद्यार्थी के स्तर से बहुत नीचे के हों", "पिछले वर्ष जैसे ही हों"], "कार्य सहायता के साथ शिक्षार्थी को आगे खींचने वाले होने चाहिए।"]),
  q(0, "pedagogy", "learning-theories", "H", 1,
    ["Which of these assessments is MOST suited to judge a pupil's practical skills in a science laboratory?", ["A multiple-choice test", "A practical performance assessment with a checklist", "A dictation", "A recitation"], "Performance tasks assess skills directly."],
    ["विज्ञान प्रयोगशाला में विद्यार्थी के व्यावहारिक कौशल परखने के लिए इनमें से कौन-सा आकलन सबसे उपयुक्त है?", ["बहुविकल्पी परीक्षा", "जाँच-सूची सहित प्रायोगिक निष्पादन आकलन", "श्रुतलेख", "सस्वर पाठ"], "निष्पादन कार्य कौशलों का सीधा आकलन करते हैं।"]),
  q(0, "pedagogy", "child-development", "M", 3,
    ["Puberty in girls is generally marked by:", ["Cessation of growth", "Loss of memory", "Fall in height", "Onset of menstruation and growth of secondary sex characters"], "Menarche and secondary characteristics mark puberty."],
    ["बालिकाओं में यौवनारंभ सामान्यतः किससे चिह्नित होता है?", ["वृद्धि का रुकना", "स्मृति-लोप", "कद का घटना", "रजोधर्म का आरंभ और गौण लैंगिक लक्षणों का विकास"], "रजोदर्शन और गौण लक्षण यौवनारंभ के सूचक हैं।"]),
  q(0, "pedagogy", "child-development", "H", 2,
    ["Which hormone, secreted by the thyroid gland, strongly affects the child's growth and mental development?", ["Insulin", "Adrenaline", "Thyroxine", "Oestrogen"], "Deficiency of thyroxine in infancy can retard growth (cretinism)."],
    ["थायरॉइड ग्रंथि द्वारा स्रावित कौन-सा हार्मोन बच्चे की वृद्धि और मानसिक विकास को बहुत प्रभावित करता है?", ["इंसुलिन", "एड्रेनालिन", "थायरॉक्सिन", "ईस्ट्रोजन"], "शैशव में थायरॉक्सिन की कमी वृद्धि को रोक सकती है (क्रेटिनिज़्म)।"]),
  q(0, "pedagogy", "learning-theories", "M", 1,
    ["In a lesson plan, 'recapitulation' at the end of the lesson serves to:", ["Waste time", "Consolidate what was learnt", "Introduce a new topic", "Punish pupils"], "Recapitulation reinforces key points."],
    ["पाठ-योजना में पाठ के अंत में 'पुनरावृत्ति' का उद्देश्य है:", ["समय बर्बाद करना", "जो सीखा गया उसे सुदृढ़ करना", "नया विषय आरंभ करना", "विद्यार्थियों को दंडित करना"], "पुनरावृत्ति मुख्य बिंदुओं को पक्का करती है।"]),
  q(0, "pedagogy", "learning-theories", "M", 2,
    ["A teacher uses concept maps in science. They mainly help pupils to:", ["Draw maps of India", "Memorise formulas", "See relationships between ideas", "Write faster"], "A concept map shows links among concepts."],
    ["शिक्षक विज्ञान में संप्रत्यय-मानचित्र (कॉन्सेप्ट मैप) का प्रयोग करता है। ये मुख्यतः विद्यार्थियों को किसमें सहायता करते हैं?", ["भारत का नक़्शा बनाने में", "सूत्र रटने में", "विचारों के बीच संबंध देखने में", "तेज़ लिखने में"], "संप्रत्यय-मानचित्र विचारों के आपसी संबंध दिखाता है।"]),
  q(0, "pedagogy", "inclusive-education", "H", 0,
    ["Under the RPwD Act, 2016, reservation in government jobs for persons with benchmark disabilities is:", ["4 per cent", "1 per cent", "10 per cent", "25 per cent"], "The Act provides 4% reservation in government posts."],
    ["दिव्यांगजन अधिकार अधिनियम 2016 के अंतर्गत बेंचमार्क दिव्यांगता वाले व्यक्तियों के लिए सरकारी नौकरियों में आरक्षण है:", ["4 प्रतिशत", "1 प्रतिशत", "10 प्रतिशत", "25 प्रतिशत"], "अधिनियम सरकारी पदों में 4% आरक्षण देता है।"]),
  q(0, "pedagogy", "learning-theories", "M", 3,
    ["Which is an example of an extrinsic reward in a classroom?", ["Joy of solving a problem", "Curiosity", "A sense of achievement", "A prize for the best answer"], "Prizes come from outside the task."],
    ["कक्षा में बाह्य पुरस्कार का उदाहरण कौन-सा है?", ["समस्या हल करने का आनंद", "जिज्ञासा", "उपलब्धि की अनुभूति", "सर्वश्रेष्ठ उत्तर के लिए इनाम"], "इनाम कार्य के बाहर से आता है।"]),

  q(0, "pedagogy", "learning-theories", "M", 3,
    ["Which one of these is NOT a feature of effective feedback to students?", ["Timely", "Specific", "Constructive", "Humiliating"], "Good feedback is timely, specific and constructive, never humiliating."],
    ["विद्यार्थियों को दी जाने वाली प्रभावी प्रतिपुष्टि की विशेषता इनमें से कौन-सी नहीं है?", ["समयबद्ध", "विशिष्ट", "रचनात्मक", "अपमानजनक"], "अच्छी प्रतिपुष्टि समयबद्ध, विशिष्ट और रचनात्मक होती है, कभी अपमानजनक नहीं।"]),

  // ───────── Section 1: Hindi (30) ─────────
  q(1, "hindi", "sahitya", "M", 1,
    ["'हल्दीघाटी', a famous epic poem on Maharana Pratap, was written by:", ["दिनकर", "श्यामनारायण पांडेय", "बच्चन", "माखनलाल चतुर्वेदी"], "Shyamnarayan Pandey wrote Haldighati."],
    ["महाराणा प्रताप पर आधारित प्रसिद्ध महाकाव्य 'हल्दीघाटी' किसने लिखा?", ["दिनकर", "श्यामनारायण पांडेय", "बच्चन", "माखनलाल चतुर्वेदी"], "श्यामनारायण पांडेय ने हल्दीघाटी लिखा।"]),
  q(1, "hindi", "sahitya", "M", 3,
    ["'झाँसी की रानी' (ख़ूब लड़ी मर्दानी) is a famous poem by:", ["महादेवी वर्मा", "निराला", "माखनलाल चतुर्वेदी", "सुभद्राकुमारी चौहान"], "Subhadra Kumari Chauhan wrote it."],
    ["'झाँसी की रानी' (ख़ूब लड़ी मर्दानी) प्रसिद्ध कविता किसकी है?", ["महादेवी वर्मा", "निराला", "माखनलाल चतुर्वेदी", "सुभद्राकुमारी चौहान"], "यह सुभद्राकुमारी चौहान की रचना है।"]),
  q(1, "hindi", "sahitya", "H", 2,
    ["'पुष्प की अभिलाषा' was written by:", ["निराला", "सोहनलाल द्विवेदी", "माखनलाल चतुर्वेदी", "हरिवंश राय बच्चन"], "Makhanlal Chaturvedi ('Ek Bharatiya Atma') wrote it."],
    ["'पुष्प की अभिलाषा' कविता किसने लिखी?", ["निराला", "सोहनलाल द्विवेदी", "माखनलाल चतुर्वेदी", "हरिवंश राय बच्चन"], "इसे माखनलाल चतुर्वेदी ('एक भारतीय आत्मा') ने लिखा।"]),
  q(1, "hindi", "sahitya", "M", 0,
    ["The author of 'निर्मला' and 'गबन' is:", ["प्रेमचंद", "प्रसाद", "यशपाल", "रेणु"], "Both novels are by Premchand."],
    ["'निर्मला' और 'गबन' के लेखक कौन हैं?", ["प्रेमचंद", "प्रसाद", "यशपाल", "रेणु"], "दोनों उपन्यास प्रेमचंद के हैं।"]),
  q(1, "hindi", "sahitya", "H", 1,
    ["'रेखाचित्र' ('अतीत के चलचित्र') in Hindi prose is associated with:", ["हजारी प्रसाद द्विवेदी", "महादेवी वर्मा", "रामचंद्र शुक्ल", "प्रेमचंद"], "Mahadevi Varma is known for her sketches and memoirs."],
    ["हिंदी गद्य में 'अतीत के चलचित्र' जैसे रेखाचित्र किससे जुड़े हैं?", ["हजारी प्रसाद द्विवेदी", "महादेवी वर्मा", "रामचंद्र शुक्ल", "प्रेमचंद"], "महादेवी वर्मा अपने रेखाचित्र और संस्मरणों के लिए जानी जाती हैं।"]),
  q(1, "hindi", "sahitya", "H", 3,
    ["The 'हिंदी साहित्य का इतिहास' (1929), a standard literary history, was written by:", ["हजारी प्रसाद द्विवेदी", "रामकुमार वर्मा", "नगेंद्र", "रामचंद्र शुक्ल"], "Acharya Ramchandra Shukla wrote it."],
    ["मानक साहित्य-इतिहास 'हिंदी साहित्य का इतिहास' (1929) किसने लिखा?", ["हजारी प्रसाद द्विवेदी", "रामकुमार वर्मा", "नगेंद्र", "रामचंद्र शुक्ल"], "आचार्य रामचंद्र शुक्ल ने इसे लिखा।"]),
  q(1, "hindi", "sahitya", "M", 2,
    ["Which Hindi poet is known for the lines 'चाह नहीं, मैं सुरबाला के गहनों में गूँथा जाऊँ'?", ["पंत", "निराला", "माखनलाल चतुर्वेदी", "प्रसाद"], "These are lines of 'Pushp ki Abhilasha'."],
    ["'चाह नहीं, मैं सुरबाला के गहनों में गूँथा जाऊँ' पंक्तियाँ किस कवि की हैं?", ["पंत", "निराला", "माखनलाल चतुर्वेदी", "प्रसाद"], "ये 'पुष्प की अभिलाषा' की पंक्तियाँ हैं।"]),
  q(1, "hindi", "sandhi-samas", "M", 3,
    ["Split the word 'अत्याचार' into sandhi parts:", ["अत् + याचार", "अत्य + आचार", "अत्या + चार", "अति + आचार"], "इ + आ = य् + आ (yan sandhi): अति + आचार."],
    ["'अत्याचार' का संधि-विच्छेद कीजिए:", ["अत् + याचार", "अत्य + आचार", "अत्या + चार", "अति + आचार"], "इ + आ = य् + आ (यण संधि): अति + आचार।"]),
  q(1, "hindi", "sandhi-samas", "H", 3,
    ["Split the word 'पावक' into sandhi parts:", ["पो + अक", "पा + वक", "पाव + क", "पौ + अक"], "औ + अ = आव् + अ (ayadi sandhi): पौ + अक = पावक."],
    ["'पावक' का संधि-विच्छेद कीजिए:", ["पो + अक", "पा + वक", "पाव + क", "पौ + अक"], "औ + अ = आव् + अ (अयादि संधि): पौ + अक = पावक।"]),
  q(1, "hindi", "sandhi-samas", "M", 2,
    ["'यथासमय' (समय के अनुसार) is an example of:", ["द्वंद्व समास", "बहुव्रीहि समास", "अव्ययीभाव समास", "कर्मधारय समास"], "A word starting with the avyaya 'यथा' is avyayibhav."],
    ["'यथासमय' (समय के अनुसार) किसका उदाहरण है?", ["द्वंद्व समास", "बहुव्रीहि समास", "अव्ययीभाव समास", "कर्मधारय समास"], "अव्यय 'यथा' से शुरू होने वाला शब्द अव्ययीभाव होता है।"]),
  q(1, "hindi", "sandhi-samas", "H", 1,
    ["'त्रिनेत्र' (तीन हैं नेत्र जिसके, अर्थात् शिव) is an example of:", ["द्विगु समास", "बहुव्रीहि समास", "तत्पुरुष समास", "कर्मधारय समास"], "The meaning points to Shiva, a third entity: bahuvrihi."],
    ["'त्रिनेत्र' (तीन हैं नेत्र जिसके, अर्थात् शिव) किसका उदाहरण है?", ["द्विगु समास", "बहुव्रीहि समास", "तत्पुरुष समास", "कर्मधारय समास"], "अर्थ शिव, तीसरे व्यक्ति, की ओर संकेत करता है: बहुव्रीहि।"]),
  q(1, "hindi", "sandhi-samas", "M", 0,
    ["'हस्तलिखित' (हाथ से लिखित) is an example of:", ["तत्पुरुष समास", "द्वंद्व समास", "द्विगु समास", "अव्ययीभाव समास"], "Third-case (से) relation: tatpurush."],
    ["'हस्तलिखित' (हाथ से लिखित) किसका उदाहरण है?", ["तत्पुरुष समास", "द्वंद्व समास", "द्विगु समास", "अव्ययीभाव समास"], "तृतीया (से) संबंध: तत्पुरुष।"]),
  q(1, "hindi", "paryay-vilom", "M", 2,
    ["Choose the synonym of 'पर्वत':", ["सागर", "सरिता", "गिरि", "वन"], "पर्वत, गिरि and अचल all mean mountain."],
    ["'पर्वत' का पर्यायवाची चुनिए:", ["सागर", "सरिता", "गिरि", "वन"], "पर्वत, गिरि और अचल का अर्थ पहाड़ है।"]),
  q(1, "hindi", "paryay-vilom", "H", 3,
    ["Choose the synonym of 'भुजंग':", ["हाथी", "शेर", "बंदर", "साँप"], "भुजंग, सर्प and व्याल mean snake."],
    ["'भुजंग' का पर्यायवाची चुनिए:", ["हाथी", "शेर", "बंदर", "साँप"], "भुजंग, सर्प और व्याल का अर्थ साँप है।"]),
  q(1, "hindi", "paryay-vilom", "M", 0,
    ["Choose the antonym of 'दिन':", ["रात", "दोपहर", "शाम", "सुबह"], "दिन is day; रात is night."],
    ["'दिन' का विलोम चुनिए:", ["रात", "दोपहर", "शाम", "सुबह"], "दिन का विलोम रात है।"]),
  q(1, "hindi", "paryay-vilom", "H", 1,
    ["Choose the antonym of 'संक्षेप':", ["सार", "विस्तार", "सूक्ष्म", "लघु"], "संक्षेप is brevity; विस्तार is expansion."],
    ["'संक्षेप' का विलोम चुनिए:", ["सार", "विस्तार", "सूक्ष्म", "लघु"], "संक्षेप का अर्थ थोड़े में है; विस्तार का अर्थ फैलाव है।"]),
  q(1, "hindi", "ek-shabd", "M", 3,
    ["Which single word means 'जो हर जगह मौजूद हो'?", ["सर्वज्ञ", "सर्वशक्तिमान", "सर्वोच्च", "सर्वव्यापी"], "सर्वव्यापी is all-pervading."],
    ["'जो हर जगह मौजूद हो' के लिए एक शब्द कौन-सा है?", ["सर्वज्ञ", "सर्वशक्तिमान", "सर्वोच्च", "सर्वव्यापी"], "सर्वव्यापी का अर्थ है सर्वत्र विद्यमान।"]),
  q(1, "hindi", "ek-shabd", "H", 0,
    ["Which single word means 'जिस पर विश्वास किया जा सके'?", ["विश्वसनीय", "विश्वासघाती", "विश्वास", "अविश्वासी"], "विश्वसनीय is trustworthy."],
    ["'जिस पर विश्वास किया जा सके' के लिए एक शब्द कौन-सा है?", ["विश्वसनीय", "विश्वासघाती", "विश्वास", "अविश्वासी"], "विश्वसनीय का अर्थ भरोसे के योग्य है।"]),
  q(1, "hindi", "ek-shabd", "M", 2,
    ["Which single word means 'जिसके पास बहुत धन हो'?", ["निर्धन", "दरिद्र", "धनाढ्य", "कंगाल"], "धनाढ्य is wealthy."],
    ["'जिसके पास बहुत धन हो' के लिए एक शब्द कौन-सा है?", ["निर्धन", "दरिद्र", "धनाढ्य", "कंगाल"], "धनाढ्य का अर्थ अत्यंत धनवान है।"]),
  q(1, "hindi", "muhavare", "M", 1,
    ["Meaning of the idiom 'हवा से बातें करना':", ["बातूनी होना", "बहुत तेज़ चलना", "हवा में उड़ना", "मौन रहना"], "The idiom means moving extremely fast."],
    ["मुहावरे 'हवा से बातें करना' का अर्थ है:", ["बातूनी होना", "बहुत तेज़ चलना", "हवा में उड़ना", "मौन रहना"], "इस मुहावरे का अर्थ है बहुत तेज़ गति से चलना।"]),
  q(1, "hindi", "muhavare", "H", 3,
    ["Meaning of the idiom 'गागर में सागर भरना':", ["पानी भरना", "घड़ा खरीदना", "बहुत बड़ा काम करना", "थोड़े शब्दों में बहुत बात कहना"], "The idiom praises compactness of expression."],
    ["मुहावरे 'गागर में सागर भरना' का अर्थ है:", ["पानी भरना", "घड़ा खरीदना", "बहुत बड़ा काम करना", "थोड़े शब्दों में बहुत बात कहना"], "यह मुहावरा संक्षिप्त कथन की विशालता की प्रशंसा है।"]),
  q(1, "hindi", "muhavare", "M", 0,
    ["Meaning of the proverb 'सब धान बाईस पसेरी':", ["अच्छे-बुरे सबको एक समझना", "धान खरीदना", "अनाज तौलना", "खेती करना"], "It criticises treating all things as equal regardless of worth."],
    ["लोकोक्ति 'सब धान बाईस पसेरी' का अर्थ है:", ["अच्छे-बुरे सबको एक समझना", "धान खरीदना", "अनाज तौलना", "खेती करना"], "यह गुण-भेद किए बिना सबको बराबर मानने की आलोचना है।"]),
  q(1, "hindi", "shuddh-vartani", "H", 2,
    ["Pick the correct spelling of the word meaning 'revenge':", ["प्रतिशोद", "प्रतिसोध", "प्रतिशोध", "प्रतिसोद"], "The correct form is प्रतिशोध."],
    ["'बदला' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["प्रतिशोद", "प्रतिसोध", "प्रतिशोध", "प्रतिसोद"], "शुद्ध रूप प्रतिशोध है।"]),
  q(1, "hindi", "shuddh-vartani", "M", 3,
    ["Pick the correct spelling of the word meaning 'knowledgeable person':", ["विद्वान्न", "विध्वान", "विद्वाण", "विद्वान"], "The correct form is विद्वान."],
    ["'ज्ञानी व्यक्ति' अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["विद्वान्न", "विध्वान", "विद्वाण", "विद्वान"], "शुद्ध रूप विद्वान है।"]),
  q(1, "hindi", "vyakaran", "M", 1,
    ["The gender of the word 'पुस्तक' is:", ["पुल्लिंग", "स्त्रीलिंग", "उभयलिंग", "नपुंसकलिंग"], "पुस्तक is feminine: 'यह पुस्तक अच्छी है'."],
    ["'पुस्तक' शब्द का लिंग है:", ["पुल्लिंग", "स्त्रीलिंग", "उभयलिंग", "नपुंसकलिंग"], "पुस्तक स्त्रीलिंग है: 'यह पुस्तक अच्छी है'।"]),
  q(1, "hindi", "vyakaran", "H", 0,
    ["In 'वह सुंदर चित्र बनाता है', the word 'सुंदर' is a:", ["विशेषण", "क्रिया-विशेषण", "संज्ञा", "सर्वनाम"], "It describes the noun 'चित्र'."],
    ["'वह सुंदर चित्र बनाता है' में 'सुंदर' क्या है?", ["विशेषण", "क्रिया-विशेषण", "संज्ञा", "सर्वनाम"], "यह संज्ञा 'चित्र' की विशेषता बताता है।"]),
  q(1, "hindi", "vyakaran", "M", 2,
    ["The plural of 'लड़की' is:", ["लड़किये", "लड़कीयाँ", "लड़कियाँ", "लड़कियों"], "Nouns ending in ई form the plural with -याँ."],
    ["'लड़की' का बहुवचन है:", ["लड़किये", "लड़कीयाँ", "लड़कियाँ", "लड़कियों"], "ईकारांत संज्ञाओं का बहुवचन -याँ से बनता है।"]),
  q(1, "hindi", "alankar-ras", "H", 3,
    ["'सिंधु-सा गंभीर' – the figure of speech here is:", ["अनुप्रास", "यमक", "रूपक", "उपमा"], "'सा' marks the comparison: upama."],
    ["'सिंधु-सा गंभीर' में कौन-सा अलंकार है?", ["अनुप्रास", "यमक", "रूपक", "उपमा"], "'सा' तुलना बताता है: उपमा।"]),
  q(1, "hindi", "alankar-ras", "M", 0,
    ["The sthayi bhav of 'अद्भुत रस' is:", ["विस्मय", "भय", "शोक", "रति"], "Vismay (wonder) is the sthayi bhav of adbhut ras."],
    ["'अद्भुत रस' का स्थायी भाव है:", ["विस्मय", "भय", "शोक", "रति"], "अद्भुत रस का स्थायी भाव विस्मय है।"]),

  q(1, "hindi", "paryay-vilom", "M", 1,
    ["Choose the synonym of 'अनिल':", ["अग्नि", "पवन", "जल", "धरा"], "अनिल, पवन and समीर mean wind."],
    ["'अनिल' का पर्यायवाची चुनिए:", ["अग्नि", "पवन", "जल", "धरा"], "अनिल, पवन और समीर का अर्थ हवा है।"]),

  // ───────── Section 2: English (30) ─────────
  q(2, "english", "literature", "M", 2,
    ["'Wuthering Heights' is a novel by:", ["Charlotte Brontë", "Jane Austen", "Emily Brontë", "Mary Shelley"], "Emily Brontë published it in 1847."],
    ["'Wuthering Heights' उपन्यास किसका है?", ["शार्लट ब्रॉन्टी", "जेन ऑस्टिन", "एमिली ब्रॉन्टी", "मैरी शेली"], "एमिली ब्रॉन्टी ने इसे 1847 में प्रकाशित किया।"]),
  q(2, "english", "literature", "H", 0,
    ["'The Waste Land', a landmark modernist poem, was written by:", ["T. S. Eliot", "W. B. Yeats", "Ezra Pound", "W. H. Auden"], "T. S. Eliot published it in 1922."],
    ["आधुनिकतावादी युगांतरकारी कविता 'The Waste Land' किसने लिखी?", ["टी. एस. एलियट", "डब्ल्यू. बी. येट्स", "एज़रा पाउंड", "डब्ल्यू. एच. ऑडेन"], "टी. एस. एलियट ने इसे 1922 में प्रकाशित किया।"]),
  q(2, "english", "literature", "M", 3,
    ["'Train to Pakistan' is a novel by:", ["R. K. Narayan", "Mulk Raj Anand", "Raja Rao", "Khushwant Singh"], "Khushwant Singh wrote it in 1956."],
    ["'Train to Pakistan' उपन्यास किसका है?", ["आर. के. नारायण", "मुल्क राज आनंद", "राजा राव", "खुशवंत सिंह"], "खुशवंत सिंह ने इसे 1956 में लिखा।"]),
  q(2, "english", "literature", "H", 1,
    ["The poem 'Where the Mind is Without Fear' is from which collection by Tagore?", ["The Crescent Moon", "Gitanjali", "Stray Birds", "Fruit-Gathering"], "It is poem 35 of Gitanjali."],
    ["टैगोर की कविता 'Where the Mind is Without Fear' किस संग्रह की है?", ["द क्रेसेंट मून", "गीतांजलि", "स्ट्रे बर्ड्स", "फ्रूट-गैदरिंग"], "यह गीतांजलि की 35वीं कविता है।"]),
  q(2, "english", "grammar", "M", 0,
    ["Choose the right word: 'The committee ___ its decision yesterday.'", ["announced", "have announced", "announce", "announcing"], "A past time word takes the simple past."],
    ["सही शब्द चुनिए: 'The committee ___ its decision yesterday.'", ["announced", "have announced", "announce", "announcing"], "भूतकालिक समय-सूचक के साथ simple past आता है।"]),
  q(2, "english", "grammar", "H", 3,
    ["Choose the correct form: 'Had she studied harder, she ___ the examination.'", ["will pass", "would pass", "passed", "would have passed"], "A third conditional uses 'would have + past participle'."],
    ["सही रूप चुनिए: 'Had she studied harder, she ___ the examination.'", ["will pass", "would pass", "passed", "would have passed"], "तृतीय conditional में 'would have + past participle' आता है।"]),
  q(2, "english", "grammar", "M", 2,
    ["Fill in the blank: 'She is the girl ___ won the first prize.'", ["whom", "whose", "who", "which"], "'Who' is the subject of 'won'."],
    ["रिक्त स्थान भरिए: 'She is the girl ___ won the first prize.'", ["whom", "whose", "who", "which"], "'Who', 'won' का कर्ता है।"]),
  q(2, "english", "grammar", "H", 1,
    ["Choose the correct word: 'The fees ___ been paid.'", ["has", "have", "is", "was"], "'Fees' is plural here."],
    ["सही शब्द चुनिए: 'The fees ___ been paid.'", ["has", "have", "is", "was"], "यहाँ 'fees' बहुवचन है।"]),
  q(2, "english", "grammar", "M", 3,
    ["Fill in the blank: 'The shopkeeper gave me ___ change.'", ["a", "an", "many", "some"], "'Change' is uncountable; 'some' fits."],
    ["रिक्त स्थान भरिए: 'The shopkeeper gave me ___ change.'", ["a", "an", "many", "some"], "'Change' अगणनीय है; 'some' उपयुक्त है।"]),
  q(2, "english", "error-spotting", "H", 0,
    ["Find the part with an error: 'He asked me (A) what was my name (B) and where (C) I lived. (D)'", ["B", "A", "C", "D"], "In a reported question the order is 'what my name was'."],
    ["त्रुटि वाला भाग चुनिए: 'He asked me (A) what was my name (B) and where (C) I lived. (D)'", ["B", "A", "C", "D"], "Reported question में क्रम 'what my name was' होता है।"]),
  q(2, "english", "error-spotting", "M", 2,
    ["Find the part with an error: 'Everyone (A) of the students (B) have (C) passed. (D)'", ["A", "B", "C", "D"], "'Each/every one' takes 'has'."],
    ["त्रुटि वाला भाग चुनिए: 'Everyone (A) of the students (B) have (C) passed. (D)'", ["A", "B", "C", "D"], "'Each/every one' के साथ 'has' आता है।"]),
  q(2, "english", "error-spotting", "H", 3,
    ["Find the part with an error: 'I am (A) afraid that (B) he is not (C) agree. (D)'", ["A", "B", "C", "D"], "'Agree' is a verb; the sentence needs 'does not agree'."],
    ["त्रुटि वाला भाग चुनिए: 'I am (A) afraid that (B) he is not (C) agree. (D)'", ["A", "B", "C", "D"], "'Agree' क्रिया है; वाक्य में 'does not agree' चाहिए।"]),
  q(2, "english", "voice-speech", "M", 1,
    ["Change to the passive: 'The police are searching the house.'", ["The house is searched by the police.", "The house is being searched by the police.", "The house was searched by the police.", "The house has searched by the police."], "Present continuous passive: is being + past participle."],
    ["Passive में बदलिए: 'The police are searching the house.'", ["The house is searched by the police.", "The house is being searched by the police.", "The house was searched by the police.", "The house has searched by the police."], "Present continuous का passive: is being + past participle।"]),
  q(2, "english", "voice-speech", "H", 2,
    ["Change to indirect speech: 'He said, \"Alas! I am ruined.\"'", ["He said that alas I am ruined.", "He said alas that he was ruined.", "He exclaimed sadly that he was ruined.", "He told that he had ruined."], "An exclamation is reported with 'exclaimed/cried out' and a clause."],
    ["Indirect speech में बदलिए: 'He said, \"Alas! I am ruined.\"'", ["He said that alas I am ruined.", "He said alas that he was ruined.", "He exclaimed sadly that he was ruined.", "He told that he had ruined."], "विस्मयादिबोधक को 'exclaimed' और एक उपवाक्य से बताया जाता है।"]),
  q(2, "english", "vocabulary", "H", 3,
    ["Which word is nearest in meaning to 'PRUDENT'?", ["Foolish", "Careless", "Angry", "Wise and careful"], "Prudent means acting with care and thought."],
    ["'PRUDENT' के निकटतम अर्थ वाला शब्द कौन-सा है?", ["Foolish", "Careless", "Angry", "Wise and careful"], "Prudent का अर्थ सोच-समझकर सावधानी से काम करने वाला है।"]),
  q(2, "english", "synonyms-antonyms", "M", 0,
    ["The antonym of 'INNOCENT' is:", ["Guilty", "Pure", "Naive", "Harmless"], "Innocent means not guilty; guilty is the opposite."],
    ["'INNOCENT' का विलोम है:", ["Guilty", "Pure", "Naive", "Harmless"], "Innocent का अर्थ निर्दोष है; guilty उसका उलटा है।"]),
  q(2, "english", "synonyms-antonyms", "H", 2,
    ["The antonym of 'TEDIOUS' is:", ["Boring", "Dull", "Interesting", "Long"], "Tedious means boring; interesting is the opposite."],
    ["'TEDIOUS' का विलोम है:", ["Boring", "Dull", "Interesting", "Long"], "Tedious का अर्थ उबाऊ है; interesting उसका उलटा है।"]),
  q(2, "english", "idioms", "M", 1,
    ["'To be in hot water' means to be:", ["Having a bath", "In trouble", "Cooking", "Feeling warm"], "The idiom means to be in difficulty."],
    ["'to be in hot water' का अर्थ है:", ["नहा रहा होना", "संकट में होना", "खाना पकाना", "गरमी महसूस करना"], "इस मुहावरे का अर्थ मुसीबत में होना है।"]),
  q(2, "english", "idioms", "H", 3,
    ["The idiom 'to leave no stone unturned' means to:", ["Clean the garden", "Hurt someone", "Build a wall", "Try every possible means"], "It means to make every effort."],
    ["'to leave no stone unturned' का अर्थ है:", ["बाग़ साफ़ करना", "किसी को चोट पहुँचाना", "दीवार बनाना", "हर संभव उपाय आज़माना"], "इसका अर्थ है हर संभव प्रयास करना।"]),
  q(2, "english", "idioms", "M", 0,
    ["'A storm in a teacup' refers to:", ["A great fuss about something trivial", "A tea party", "A natural disaster", "A cold drink"], "It means much excitement over a small matter."],
    ["'A storm in a teacup' किसकी ओर संकेत करता है?", ["किसी तुच्छ बात पर बड़ा हंगामा", "चाय पार्टी", "प्राकृतिक आपदा", "ठंडा पेय"], "इसका अर्थ छोटी बात पर बहुत उत्तेजना है।"]),
  q(2, "english", "one-word", "M", 2,
    ["Which single word means 'a place where animals are kept for public viewing'?", ["Aquarium", "Aviary", "Zoo", "Stable"], "A zoo displays animals to the public."],
    ["'जहाँ जानवर जनता के देखने के लिए रखे जाते हैं' उस स्थान के लिए एक शब्द कौन-सा है?", ["Aquarium", "Aviary", "Zoo", "Stable"], "Zoo में जानवर जनता को दिखाने के लिए रखे जाते हैं।"]),
  q(2, "english", "one-word", "H", 1,
    ["Which single word means 'a person who is not sure whether God exists'?", ["Atheist", "Agnostic", "Theist", "Pagan"], "An agnostic holds that the existence of God cannot be known."],
    ["'जो यह निश्चित नहीं मानता कि ईश्वर है या नहीं' उस व्यक्ति के लिए एक शब्द कौन-सा है?", ["Atheist", "Agnostic", "Theist", "Pagan"], "Agnostic मानता है कि ईश्वर के अस्तित्व को जाना नहीं जा सकता।"]),
  q(2, "english", "one-word", "M", 3,
    ["Which single word means 'speaking aloud to oneself on the stage'?", ["Prologue", "Epilogue", "Dialogue", "Soliloquy"], "A soliloquy is a speech made to oneself."],
    ["'मंच पर स्वयं से ज़ोर से बोलना' के लिए एक शब्द कौन-सा है?", ["Prologue", "Epilogue", "Dialogue", "Soliloquy"], "Soliloquy स्वयं से किया गया संवाद है।"]),
  q(2, "english", "spelling", "H", 0,
    ["Select the correct spelling of the noun meaning 'the state of being sure':", ["Certainty", "Certainity", "Certanty", "Certeinty"], "The word is certainty."],
    ["'निश्चित होने की स्थिति' अर्थ वाले संज्ञा की सही वर्तनी चुनिए:", ["Certainty", "Certainity", "Certanty", "Certeinty"], "सही शब्द certainty है।"]),
  q(2, "english", "spelling", "M", 2,
    ["Select the correct spelling of the adjective meaning 'having no fixed shape or form':", ["Amorfous", "Amorphus", "Amorphous", "Amorphouse"], "The word is amorphous."],
    ["'जिसका कोई निश्चित आकार न हो' अर्थ वाले विशेषण की सही वर्तनी चुनिए:", ["Amorfous", "Amorphus", "Amorphous", "Amorphouse"], "सही शब्द amorphous है।"]),
  q(2, "english", "comprehension", "H", 1,
    ["In reading instruction, 'skimming' is used to:", ["Study every sentence closely", "Get the general idea quickly", "Find a single date", "Correct spelling"], "Skimming gives the gist of a text."],
    ["पठन-शिक्षण में 'स्किमिंग' का प्रयोग किसलिए होता है?", ["हर वाक्य को ध्यान से पढ़ने के लिए", "सामान्य विचार जल्दी जानने के लिए", "केवल एक तिथि खोजने के लिए", "वर्तनी सुधारने के लिए"], "स्किमिंग पाठ का सार देती है।"]),
  q(2, "english", "comprehension", "M", 3,
    ["Which activity best develops the speaking skill of secondary school pupils?", ["Silent copying", "Memorising poems without understanding", "Taking dictation", "Group discussion and debates"], "Speaking improves with real interaction."],
    ["माध्यमिक विद्यालय के विद्यार्थियों में बोलने का कौशल सबसे अच्छा किस गतिविधि से विकसित होता है?", ["मौन नक़ल", "बिना समझे कविता रटना", "श्रुतलेख लेना", "समूह चर्चा और वाद-विवाद"], "वास्तविक अंतःक्रिया से बोलने का कौशल निखरता है।"]),
  q(2, "english", "comprehension", "H", 2,
    ["A teacher gives pupils a dialogue with words missing and asks them to complete it from a word box. This mainly develops:", ["Handwriting", "Mental maths", "Vocabulary and sentence use in context", "Map reading"], "Guided completion practises words in context."],
    ["शिक्षक विद्यार्थियों को शब्दों वाले बक्से से रिक्त स्थान भरकर संवाद पूरा करने को कहता है। यह मुख्यतः क्या विकसित करता है?", ["लिखावट", "मानसिक गणित", "संदर्भ में शब्द-भंडार और वाक्य-प्रयोग", "मानचित्र पढ़ना"], "निर्देशित पूर्ति संदर्भ में शब्दों का अभ्यास कराती है।"]),
  q(2, "english", "grammar", "M", 0,
    ["Fill in the blank: 'This is the ___ of the two books.'", ["better", "best", "good", "more good"], "'The better of the two' compares two items."],
    ["रिक्त स्थान भरिए: 'This is the ___ of the two books.'", ["better", "best", "good", "more good"], "दो वस्तुओं की तुलना में 'the better of the two' आता है।"]),
  q(2, "english", "grammar", "H", 1,
    ["Choose the correctly punctuated sentence.", ["Its a lovely day, isn't it.", "It's a lovely day, isn't it?", "Its' a lovely day isn't it?", "It's a lovely day isnt it?"], "'It's' is the contraction of 'it is' and a tag question ends with '?'."],
    ["सही विराम-चिह्नों वाला वाक्य चुनिए।", ["Its a lovely day, isn't it.", "It's a lovely day, isn't it?", "Its' a lovely day isn't it?", "It's a lovely day isnt it?"], "'It's', 'it is' का संक्षिप्त रूप है और tag question '?' से समाप्त होता है।"]),

  // ───────── Section 3: Mathematics (30) ─────────
  q(3, "mathematics", "algebra", "M", 1,
    ["If A = {1, 2, 3, 4} and B = {3, 4, 5, 6}, then A ∩ B is:", ["{1, 2}", "{3, 4}", "{5, 6}", "{1, 2, 3, 4, 5, 6}"], "The common elements are 3 and 4."],
    ["यदि A = {1, 2, 3, 4} और B = {3, 4, 5, 6} है तो A ∩ B है:", ["{1, 2}", "{3, 4}", "{5, 6}", "{1, 2, 3, 4, 5, 6}"], "उभयनिष्ठ अवयव 3 और 4 हैं।"]),
  q(3, "mathematics", "algebra", "M", 2,
    ["The product of the roots of x² – 5x + 6 = 0 is:", ["5", "–6", "6", "11"], "Product of roots = c/a = 6."],
    ["x² – 5x + 6 = 0 के मूलों का गुणनफल है:", ["5", "–6", "6", "11"], "मूलों का गुणनफल = c/a = 6।"], "6"),
  q(3, "mathematics", "algebra", "H", 0,
    ["The number of terms in the AP 7, 11, 15, …, 79 is:", ["19", "18", "20", "21"], "n = (79 – 7)/4 + 1 = 19."],
    ["समांतर श्रेढ़ी 7, 11, 15, …, 79 में पदों की संख्या है:", ["19", "18", "20", "21"], "n = (79 – 7)/4 + 1 = 19।"], "(79-7)/4+1"),
  q(3, "mathematics", "algebra", "M", 3,
    ["The sum to infinity of the GP 1, 1/2, 1/4, … is:", ["1", "1.5", "4", "2"], "S = a/(1 – r) = 1/(1/2) = 2."],
    ["गुणोत्तर श्रेढ़ी 1, 1/2, 1/4, … का अनंत पदों तक योग है:", ["1", "1.5", "4", "2"], "S = a/(1 – r) = 1/(1/2) = 2।"], "2"),
  q(3, "mathematics", "algebra", "M", 0,
    ["The value of i² (where i = √–1) is:", ["–1", "1", "i", "0"], "By definition i² = –1."],
    ["i² का मान (जहाँ i = √–1) है:", ["–1", "1", "i", "0"], "परिभाषा से i² = –1।"]),
  q(3, "mathematics", "algebra", "H", 2,
    ["If the matrix A = [[1, 2], [3, 4]], then its determinant is:", ["10", "–10", "–2", "2"], "1×4 – 2×3 = –2."],
    ["यदि आव्यूह A = [[1, 2], [3, 4]] है तो उसका सारणिक है:", ["10", "–10", "–2", "2"], "1×4 – 2×3 = –2।"]),
  q(3, "mathematics", "algebra", "M", 1,
    ["The solution set of the inequality 2x – 3 > 7 is:", ["x < 5", "x > 5", "x > 2", "x < 2"], "2x > 10, so x > 5."],
    ["असमिका 2x – 3 > 7 का हल समुच्चय है:", ["x < 5", "x > 5", "x > 2", "x < 2"], "2x > 10, इसलिए x > 5।"]),
  q(3, "mathematics", "algebra", "H", 3,
    ["If log₁₀ 2 = 0.3010, then log₁₀ 8 equals:", ["0.6020", "0.7525", "0.4515", "0.9030"], "log 8 = 3 log 2 = 0.9030."],
    ["यदि log₁₀ 2 = 0.3010 है तो log₁₀ 8 बराबर है:", ["0.6020", "0.7525", "0.4515", "0.9030"], "log 8 = 3 log 2 = 0.9030।"], "3*0.3010"),
  q(3, "mathematics", "statistics-probability", "M", 2,
    ["A card is drawn from a well-shuffled pack of 52. The probability that it is an ace is:", ["1/52", "1/26", "1/13", "4/13"], "4 aces in 52 cards give 1/13."],
    ["52 पत्तों की भली-भाँति फेंटी गड्डी से एक पत्ता निकाला जाता है। उसके इक्का होने की प्रायिकता है:", ["1/52", "1/26", "1/13", "4/13"], "52 पत्तों में 4 इक्के: 1/13।"]),
  q(3, "mathematics", "statistics-probability", "M", 0,
    ["The median of the data 5, 8, 12, 15, 20, 25 is:", ["13.5", "12", "15", "14"], "Average of the two middle values 12 and 15 = 13.5."],
    ["आँकड़ों 5, 8, 12, 15, 20, 25 की माध्यिका है:", ["13.5", "12", "15", "14"], "दो मध्य मान 12 और 15 का औसत = 13.5।"], "(12+15)/2"),
  q(3, "mathematics", "statistics-probability", "H", 3,
    ["The number of ways to arrange the letters of the word 'LEVEL' is:", ["120", "60", "40", "30"], "5!/(2!·2!) = 30."],
    ["शब्द 'LEVEL' के अक्षरों को सजाने के तरीकों की संख्या है:", ["120", "60", "40", "30"], "5!/(2!·2!) = 30।"], "120/4"),
  q(3, "mathematics", "trigonometry", "M", 1,
    ["The value of tan 45° + sin 30° is:", ["1", "1.5", "2", "0.5"], "1 + 1/2 = 1.5."],
    ["tan 45° + sin 30° का मान है:", ["1", "1.5", "2", "0.5"], "1 + 1/2 = 1.5।"], "1+0.5"),
  q(3, "mathematics", "trigonometry", "H", 2,
    ["If sin θ = 3/5 and θ is acute, then cos θ equals:", ["3/4", "5/3", "4/5", "5/4"], "cos θ = √(1 – 9/25) = 4/5."],
    ["यदि sin θ = 3/5 और θ न्यून कोण है तो cos θ बराबर है:", ["3/4", "5/3", "4/5", "5/4"], "cos θ = √(1 – 9/25) = 4/5।"]),
  q(3, "mathematics", "trigonometry", "M", 0,
    ["From a point 30 m from the foot of a tower, the angle of elevation of its top is 45°. The height of the tower is:", ["30 m", "15 m", "30√3 m", "60 m"], "tan 45° = 1, so the height equals the distance: 30 m."],
    ["एक मीनार के आधार से 30 मी दूर बिंदु से उसके शिखर का उन्नयन कोण 45° है। मीनार की ऊँचाई है:", ["30 मी", "15 मी", "30√3 मी", "60 मी"], "tan 45° = 1, इसलिए ऊँचाई = दूरी = 30 मी।"], "30"),
  q(3, "mathematics", "trigonometry", "M", 3,
    ["The value of cos 60° is:", ["1", "√3/2", "0", "1/2"], "cos 60° = 1/2."],
    ["cos 60° का मान है:", ["1", "√3/2", "0", "1/2"], "cos 60° = 1/2।"]),
  q(3, "mathematics", "coordinate-geometry", "M", 2,
    ["The midpoint of the segment joining (2, 4) and (8, 10) is:", ["(3, 3)", "(6, 7)", "(5, 7)", "(10, 14)"], "((2 + 8)/2, (4 + 10)/2) = (5, 7)."],
    ["(2, 4) और (8, 10) को मिलाने वाले रेखाखंड का मध्य बिंदु है:", ["(3, 3)", "(6, 7)", "(5, 7)", "(10, 14)"], "((2 + 8)/2, (4 + 10)/2) = (5, 7)।"]),
  q(3, "mathematics", "coordinate-geometry", "H", 1,
    ["The equation of the straight line with slope 2 and y-intercept 3 is:", ["y = 3x + 2", "y = 2x + 3", "y = 2x – 3", "y = x + 5"], "y = mx + c."],
    ["प्रवणता 2 और y-अंतःखंड 3 वाली सरल रेखा का समीकरण है:", ["y = 3x + 2", "y = 2x + 3", "y = 2x – 3", "y = x + 5"], "y = mx + c।"]),
  q(3, "mathematics", "coordinate-geometry", "M", 0,
    ["The area of the triangle with vertices (0, 0), (4, 0) and (0, 3) is:", ["6", "12", "7", "3.5"], "½ × 4 × 3 = 6."],
    ["शीर्षों (0, 0), (4, 0) और (0, 3) वाले त्रिभुज का क्षेत्रफल है:", ["6", "12", "7", "3.5"], "½ × 4 × 3 = 6।"], "0.5*4*3"),
  q(3, "mathematics", "calculus", "M", 3,
    ["The derivative of 5x⁴ is:", ["5x³", "4x³", "20x⁵", "20x³"], "5 × 4x³ = 20x³."],
    ["5x⁴ का अवकलज है:", ["5x³", "4x³", "20x⁵", "20x³"], "5 × 4x³ = 20x³।"]),
  q(3, "mathematics", "calculus", "M", 1,
    ["The derivative of eˣ is:", ["x eˣ⁻¹", "eˣ", "eˣ⁺¹", "ln x"], "d/dx(eˣ) = eˣ."],
    ["eˣ का अवकलज है:", ["x eˣ⁻¹", "eˣ", "eˣ⁺¹", "ln x"], "d/dx(eˣ) = eˣ।"]),
  q(3, "mathematics", "calculus", "H", 2,
    ["The derivative of x² sin x is:", ["2x cos x", "x² cos x", "2x sin x + x² cos x", "2x sin x – x² cos x"], "By the product rule: 2x sin x + x² cos x."],
    ["x² sin x का अवकलज है:", ["2x cos x", "x² cos x", "2x sin x + x² cos x", "2x sin x – x² cos x"], "गुणनफल नियम से: 2x sin x + x² cos x।"]),
  q(3, "mathematics", "calculus", "M", 0,
    ["The value of ∫ from 0 to 1 of 3x² dx is:", ["1", "3", "0", "1/3"], "[x³] from 0 to 1 = 1."],
    ["∫ (0 से 1 तक) 3x² dx का मान है:", ["1", "3", "0", "1/3"], "[x³] (0 से 1) = 1।"], "1"),
  q(3, "mathematics", "calculus", "H", 3,
    ["The limit of (x² – 9)/(x – 3) as x tends to 3 is:", ["0", "3", "9", "6"], "(x – 3)(x + 3)/(x – 3) = x + 3 → 6."],
    ["x → 3 पर (x² – 9)/(x – 3) की सीमा है:", ["0", "3", "9", "6"], "(x – 3)(x + 3)/(x – 3) = x + 3 → 6।"], "6"),
  q(3, "mathematics", "geometry-mensuration", "M", 2,
    ["The volume of a sphere of radius 3 cm is (π = 3.14):", ["28.26 cm³", "56.52 cm³", "113.04 cm³", "226.08 cm³"], "(4/3)πr³ = 4/3 × 3.14 × 27 = 113.04 cm³."],
    ["3 सेमी त्रिज्या वाले गोले का आयतन है (π = 3.14):", ["28.26 सेमी³", "56.52 सेमी³", "113.04 सेमी³", "226.08 सेमी³"], "(4/3)πr³ = 4/3 × 3.14 × 27 = 113.04 सेमी³।"], "4/3*3.14*27"),
  q(3, "mathematics", "geometry-mensuration", "M", 1,
    ["The area of an equilateral triangle of side 4 cm is:", ["4√3 cm²", "8 cm²", "16 cm²", "2√3 cm²"], "(√3/4) × 16 = 4√3 cm²."],
    ["4 सेमी भुजा वाले समबाहु त्रिभुज का क्षेत्रफल है:", ["4√3 सेमी²", "8 सेमी²", "16 सेमी²", "2√3 सेमी²"], "(√3/4) × 16 = 4√3 सेमी²।"]),
  q(3, "mathematics", "geometry-mensuration", "H", 0,
    ["The angle subtended by a diameter of a circle at any point on the circle is:", ["90°", "180°", "60°", "45°"], "Angle in a semicircle is a right angle."],
    ["वृत्त के किसी व्यास द्वारा वृत्त पर किसी भी बिंदु पर बना कोण होता है:", ["90°", "180°", "60°", "45°"], "अर्धवृत्त में बना कोण समकोण होता है।"]),
  q(3, "mathematics", "algebra", "H", 1,
    ["The magnitude of the vector (3, 4) is:", ["7", "5", "25", "1"], "√(9 + 16) = 5."],
    ["सदिश (3, 4) का परिमाण है:", ["7", "5", "25", "1"], "√(9 + 16) = 5।"], "5"),
  q(3, "mathematics", "statistics-probability", "M", 3,
    ["The probability of getting an even number when a fair die is thrown once is:", ["1/6", "1/3", "2/3", "1/2"], "Three even faces out of six: 1/2."],
    ["एक निष्पक्ष पासा एक बार फेंकने पर सम संख्या आने की प्रायिकता है:", ["1/6", "1/3", "2/3", "1/2"], "छह में से तीन फलक सम हैं: 1/2।"]),

  q(3, "mathematics", "algebra", "M", 2,
    ["If x + y = 10 and x – y = 4, then x equals:", ["5", "6", "7", "8"], "Adding gives 2x = 14, so x = 7."],
    ["यदि x + y = 10 और x – y = 4 है तो x बराबर है:", ["5", "6", "7", "8"], "जोड़ने पर 2x = 14, इसलिए x = 7।"], "7"),
  q(3, "mathematics", "geometry-mensuration", "M", 1,
    ["The total surface area of a cube of edge 5 cm is:", ["125 cm²", "150 cm²", "100 cm²", "75 cm²"], "6a² = 6 × 25 = 150 cm²."],
    ["5 सेमी भुजा वाले घन का संपूर्ण पृष्ठीय क्षेत्रफल है:", ["125 सेमी²", "150 सेमी²", "100 सेमी²", "75 सेमी²"], "6a² = 6 × 25 = 150 सेमी²।"], "6*25"),

  // ───────── Section 4: Physics & Chemistry (30) ─────────
  q(4, "physics", "mechanics", "M", 0,
    ["Newton's first law of motion is also called the law of:", ["Inertia", "Gravitation", "Momentum", "Reaction"], "A body continues in its state unless acted on by a net force."],
    ["न्यूटन का गति का प्रथम नियम किस नियम के नाम से भी जाना जाता है?", ["जड़त्व", "गुरुत्वाकर्षण", "संवेग", "प्रतिक्रिया"], "जब तक कोई परिणामी बल न लगे, पिंड अपनी अवस्था में बना रहता है।"]),
  q(4, "physics", "mechanics", "M", 2,
    ["A body of mass 5 kg moving at 4 m/s has a momentum of:", ["9 kg m/s", "1.25 kg m/s", "20 kg m/s", "80 kg m/s"], "p = mv = 5 × 4 = 20 kg m/s."],
    ["4 मी/से की चाल से गतिमान 5 किग्रा द्रव्यमान के पिंड का संवेग है:", ["9 किग्रा मी/से", "1.25 किग्रा मी/से", "20 किग्रा मी/से", "80 किग्रा मी/से"], "p = mv = 5 × 4 = 20 किग्रा मी/से।"], "5*4"),
  q(4, "physics", "mechanics", "H", 3,
    ["The acceleration due to gravity at the surface of the Earth is about 9.8 m/s². A stone dropped from rest falls for 2 s. The distance covered is about:", ["9.8 m", "4.9 m", "39.2 m", "19.6 m"], "s = ½gt² = ½ × 9.8 × 4 = 19.6 m."],
    ["पृथ्वी की सतह पर गुरुत्वीय त्वरण लगभग 9.8 मी/से² है। विरामावस्था से छोड़ा गया पत्थर 2 सेकंड गिरता है। तय की गई दूरी लगभग है:", ["9.8 मी", "4.9 मी", "39.2 मी", "19.6 मी"], "s = ½gt² = ½ × 9.8 × 4 = 19.6 मी।"], "0.5*9.8*4"),
  q(4, "physics", "mechanics", "M", 1,
    ["The time period of a simple pendulum depends on its:", ["Mass of the bob", "Length", "Colour", "Material of the string only"], "T = 2π√(l/g)."],
    ["सरल लोलक का आवर्तकाल किस पर निर्भर करता है?", ["गोलक के द्रव्यमान पर", "लंबाई पर", "रंग पर", "केवल डोरी की सामग्री पर"], "T = 2π√(l/g)।"]),
  q(4, "physics", "heat-thermodynamics", "M", 2,
    ["The SI unit of temperature is the:", ["Celsius", "Fahrenheit", "Kelvin", "Joule"], "The kelvin is the SI base unit of temperature."],
    ["ताप की SI इकाई है:", ["सेल्सियस", "फ़ारेनहाइट", "केल्विन", "जूल"], "केल्विन ताप की SI मूल इकाई है।"]),
  q(4, "physics", "heat-thermodynamics", "H", 0,
    ["According to the first law of thermodynamics, the change in internal energy of a system equals:", ["Heat added minus work done by the system", "Heat added plus work done by the system", "Work done only", "Heat lost only"], "ΔU = Q – W."],
    ["ऊष्मागतिकी के प्रथम नियम के अनुसार निकाय की आंतरिक ऊर्जा में परिवर्तन बराबर है:", ["दी गई ऊष्मा घटा निकाय द्वारा किया गया कार्य", "दी गई ऊष्मा जमा निकाय द्वारा किया गया कार्य", "केवल किया गया कार्य", "केवल खोई ऊष्मा"], "ΔU = Q – W।"]),
  q(4, "physics", "electricity-magnetism", "M", 3,
    ["The SI unit of electric charge is the:", ["Ampere", "Volt", "Ohm", "Coulomb"], "Charge is measured in coulombs."],
    ["विद्युत आवेश की SI इकाई है:", ["ऐम्पियर", "वोल्ट", "ओम", "कूलॉम"], "आवेश कूलॉम में मापा जाता है।"]),
  q(4, "physics", "electricity-magnetism", "H", 1,
    ["The electrical energy used by a 100 W bulb in 10 hours is:", ["0.1 kWh", "1 kWh", "10 kWh", "100 kWh"], "100 W × 10 h = 1,000 Wh = 1 kWh."],
    ["100 W का बल्ब 10 घंटे में कितनी विद्युत ऊर्जा खर्च करता है?", ["0.1 kWh", "1 kWh", "10 kWh", "100 kWh"], "100 W × 10 घंटे = 1,000 Wh = 1 kWh।"], "100*10/1000"),
  q(4, "physics", "electricity-magnetism", "M", 0,
    ["Electromagnetic induction was discovered by:", ["Michael Faraday", "Isaac Newton", "Galileo", "Niels Bohr"], "Faraday discovered it in 1831."],
    ["विद्युत-चुंबकीय प्रेरण की खोज किसने की?", ["माइकल फैराडे", "आइज़क न्यूटन", "गैलीलियो", "नील्स बोर"], "फैराडे ने इसे 1831 में खोजा।"]),
  q(4, "physics", "optics-waves", "M", 2,
    ["A concave mirror used as a shaving mirror forms:", ["A real, inverted image", "A diminished image", "An enlarged, erect, virtual image", "No image"], "When the face is inside the focal length the image is enlarged and erect."],
    ["दाढ़ी बनाने के दर्पण के रूप में प्रयुक्त अवतल दर्पण कैसा प्रतिबिंब बनाता है?", ["वास्तविक, उलटा", "छोटा", "बड़ा, सीधा, आभासी", "कोई नहीं"], "चेहरा फ़ोकस के भीतर हो तो प्रतिबिंब बड़ा और सीधा बनता है।"]),
  q(4, "physics", "optics-waves", "H", 3,
    ["Young's double-slit experiment demonstrates the:", ["Particle nature of light", "Photoelectric effect", "Reflection", "Wave nature of light (interference)"], "Interference fringes show light behaves as a wave."],
    ["यंग का द्वि-स्लिट प्रयोग क्या प्रदर्शित करता है?", ["प्रकाश की कणीय प्रकृति", "प्रकाश-विद्युत प्रभाव", "परावर्तन", "प्रकाश की तरंग प्रकृति (व्यतिकरण)"], "व्यतिकरण फ्रिंज दिखाती हैं कि प्रकाश तरंग की तरह व्यवहार करता है।"]),
  q(4, "physics", "modern-physics", "M", 1,
    ["The nucleus of an atom contains:", ["Protons and electrons", "Protons and neutrons", "Neutrons and electrons", "Only electrons"], "The nucleus holds protons and neutrons."],
    ["परमाणु के नाभिक में होते हैं:", ["प्रोटॉन और इलेक्ट्रॉन", "प्रोटॉन और न्यूट्रॉन", "न्यूट्रॉन और इलेक्ट्रॉन", "केवल इलेक्ट्रॉन"], "नाभिक में प्रोटॉन और न्यूट्रॉन होते हैं।"]),
  q(4, "physics", "modern-physics", "H", 2,
    ["Einstein's mass–energy relation is:", ["E = mv", "E = ½mv²", "E = mc²", "E = mgh"], "E = mc²."],
    ["आइंस्टाइन का द्रव्यमान–ऊर्जा संबंध है:", ["E = mv", "E = ½mv²", "E = mc²", "E = mgh"], "E = mc²।"]),
  q(4, "physics", "optics-waves", "M", 0,
    ["Which colour of visible light has the longest wavelength?", ["Red", "Violet", "Green", "Blue"], "Red has the longest wavelength in the visible spectrum."],
    ["दृश्य प्रकाश के किस रंग की तरंगदैर्ध्य सबसे अधिक होती है?", ["लाल", "बैंगनी", "हरा", "नीला"], "दृश्य स्पेक्ट्रम में लाल की तरंगदैर्ध्य सबसे अधिक है।"]),
  q(4, "physics", "mechanics", "M", 3,
    ["The weight of a 10 kg object on Earth (g = 10 m/s²) is:", ["10 N", "1 N", "0.1 N", "100 N"], "W = mg = 100 N."],
    ["पृथ्वी पर 10 किग्रा की वस्तु का भार है (g = 10 मी/से²):", ["10 N", "1 N", "0.1 N", "100 N"], "W = mg = 100 N।"], "10*10"),
  q(4, "chemistry", "atomic-structure", "M", 1,
    ["Across a period from left to right in the periodic table, the atomic radius generally:", ["Increases", "Decreases", "Stays constant", "First doubles"], "Increasing nuclear charge pulls electrons closer."],
    ["आवर्त सारणी में किसी आवर्त में बाएँ से दाएँ जाने पर परमाणु त्रिज्या सामान्यतः:", ["बढ़ती है", "घटती है", "स्थिर रहती है", "पहले दुगुनी होती है"], "बढ़ता नाभिकीय आवेश इलेक्ट्रॉनों को निकट खींचता है।"]),
  q(4, "chemistry", "atomic-structure", "H", 3,
    ["The element with the electronic configuration 2, 8, 1 is:", ["Lithium", "Magnesium", "Potassium", "Sodium"], "Atomic number 11 is sodium."],
    ["इलेक्ट्रॉनिक विन्यास 2, 8, 1 वाला तत्व है:", ["लिथियम", "मैग्नीशियम", "पोटैशियम", "सोडियम"], "परमाणु क्रमांक 11 सोडियम है।"]),
  q(4, "chemistry", "physical-chemistry", "M", 2,
    ["The molarity of a solution containing 4 g of NaOH (molar mass 40 g/mol) in 1 litre is:", ["1 M", "0.01 M", "0.1 M", "10 M"], "Moles = 4/40 = 0.1, so 0.1 M."],
    ["1 लीटर में 4 ग्राम NaOH (मोलर द्रव्यमान 40 ग्राम/मोल) वाले विलयन की मोलरता है:", ["1 M", "0.01 M", "0.1 M", "10 M"], "मोल = 4/40 = 0.1, इसलिए 0.1 M।"], "4/40"),
  q(4, "chemistry", "acids-bases-salts", "M", 0,
    ["Which of these is a strong base?", ["Sodium hydroxide", "Acetic acid", "Ammonium chloride", "Carbonic acid"], "NaOH ionises completely in water."],
    ["इनमें से कौन-सा प्रबल क्षार है?", ["सोडियम हाइड्रॉक्साइड", "ऐसीटिक अम्ल", "अमोनियम क्लोराइड", "कार्बोनिक अम्ल"], "NaOH जल में पूर्णतः आयनित होता है।"]),
  q(4, "chemistry", "acids-bases-salts", "H", 1,
    ["Pure water at 25 °C has a pH that is neither acidic nor basic. This pH value is:", ["0", "7", "14", "1"], "Neutral solutions have pH 7."],
    ["25 °C पर उदासीन विलयन का pH है:", ["0", "7", "14", "1"], "उदासीन विलयनों का pH 7 होता है।"], "7"),
  q(4, "chemistry", "physical-chemistry", "H", 2,
    ["During electrolysis, reduction takes place at the:", ["Anode", "Salt bridge", "Cathode", "Electrolyte only"], "Cations gain electrons at the cathode."],
    ["विद्युत-अपघटन में अपचयन कहाँ होता है?", ["ऐनोड पर", "लवण सेतु पर", "कैथोड पर", "केवल विद्युत-अपघट्य में"], "धनायन कैथोड पर इलेक्ट्रॉन ग्रहण करते हैं।"]),
  q(4, "chemistry", "organic-chemistry", "M", 3,
    ["The simplest alkane is:", ["Ethane", "Propane", "Butane", "Methane"], "Methane (CH₄) is the first member of the alkane series."],
    ["सबसे सरल ऐल्केन है:", ["एथेन", "प्रोपेन", "ब्यूटेन", "मेथेन"], "मेथेन (CH₄) ऐल्केन श्रेणी का प्रथम सदस्य है।"]),
  q(4, "chemistry", "organic-chemistry", "H", 0,
    ["Compounds with the same molecular formula but different structures are called:", ["Isomers", "Isotopes", "Isobars", "Allotropes"], "Isomers share a formula but differ in arrangement."],
    ["समान आणविक सूत्र लेकिन भिन्न संरचना वाले यौगिक कहलाते हैं:", ["समावयवी", "समस्थानिक", "समभारिक", "अपरूप"], "समावयवियों का सूत्र समान पर विन्यास भिन्न होता है।"]),
  q(4, "chemistry", "organic-chemistry", "M", 2,
    ["Polythene is a polymer of:", ["Propene", "Styrene", "Ethene", "Vinyl chloride"], "Polythene is made by polymerising ethene."],
    ["पॉलिथीन किसका बहुलक है?", ["प्रोपीन", "स्टायरीन", "एथीन", "विनाइल क्लोराइड"], "पॉलिथीन एथीन के बहुलकन से बनती है।"]),
  q(4, "chemistry", "chemical-bonding", "M", 1,
    ["The shape of a water molecule is:", ["Linear", "Bent (V-shaped)", "Tetrahedral", "Trigonal planar"], "Two lone pairs on oxygen bend the molecule."],
    ["जल के अणु की आकृति है:", ["रैखिक", "कोणीय (V-आकार)", "चतुष्फलकीय", "त्रिकोणीय समतलीय"], "ऑक्सीजन पर दो एकाकी युग्म अणु को मोड़ देते हैं।"]),
  q(4, "chemistry", "chemical-bonding", "H", 3,
    ["Which gas is evolved when zinc reacts with dilute hydrochloric acid?", ["Oxygen", "Carbon dioxide", "Chlorine", "Hydrogen"], "Zn + 2HCl → ZnCl₂ + H₂."],
    ["जस्ते की तनु हाइड्रोक्लोरिक अम्ल से अभिक्रिया पर कौन-सी गैस निकलती है?", ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "क्लोरीन", "हाइड्रोजन"], "Zn + 2HCl → ZnCl₂ + H₂।"]),
  q(4, "chemistry", "acids-bases-salts", "M", 2,
    ["Baking soda has the chemical name:", ["Sodium carbonate", "Calcium carbonate", "Sodium hydrogencarbonate", "Sodium chloride"], "Baking soda is NaHCO₃."],
    ["खाने के सोडे (बेकिंग सोडा) का रासायनिक नाम है:", ["सोडियम कार्बोनेट", "कैल्सियम कार्बोनेट", "सोडियम हाइड्रोजनकार्बोनेट", "सोडियम क्लोराइड"], "बेकिंग सोडा NaHCO₃ है।"]),
  q(4, "physics", "mechanics", "M", 0,
    ["The SI unit of pressure is the:", ["Pascal", "Newton", "Joule", "Watt"], "One pascal is one newton per square metre."],
    ["दाब की SI इकाई है:", ["पास्कल", "न्यूटन", "जूल", "वाट"], "एक पास्कल एक न्यूटन प्रति वर्ग मीटर के बराबर है।"]),
  q(4, "physics", "optics-waves", "M", 2,
    ["A ray of light passing through the optical centre of a thin convex lens:", ["Is reflected back", "Bends towards the axis", "Passes undeviated", "Splits into colours"], "A ray through the optical centre goes straight."],
    ["पतले उत्तल लेंस के प्रकाशिक केंद्र से गुज़रने वाली प्रकाश-किरण:", ["परावर्तित होकर लौट जाती है", "अक्ष की ओर मुड़ जाती है", "बिना विचलित हुए निकल जाती है", "रंगों में बँट जाती है"], "प्रकाशिक केंद्र से गुज़रने वाली किरण सीधी निकल जाती है।"]),
  q(4, "chemistry", "acids-bases-salts", "M", 1,
    ["The chemical formula of washing soda is:", ["NaHCO₃", "Na₂CO₃·10H₂O", "CaCO₃", "NaOH"], "Washing soda is hydrated sodium carbonate."],
    ["धावन सोडा (वॉशिंग सोडा) का रासायनिक सूत्र है:", ["NaHCO₃", "Na₂CO₃·10H₂O", "CaCO₃", "NaOH"], "धावन सोडा जलयोजित सोडियम कार्बोनेट है।"]),
];
