// HP Police Constable Full Mock 5 — 100 questions (25 HP GK, 25 GK, 20 Reasoning, 15 Maths, 15 Hindi/English).

import { q, type PoliceQuestion } from "./types";

export const mock5: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK (25) ─────────
  q(0, "hp-gk", "geography", "M", 0,
    ["The highest peak of Himachal Pradesh, on the Tibet border in Kinnaur, is:", ["Reo Purgyil (Leo Pargial)", "Deo Tibba", "Kinner Kailash", "Shrikhand Mahadev"], "Reo Purgyil (about 6,816 m) in Kinnaur is the highest peak of Himachal Pradesh. Kinner Kailash is about 6,050 m."],
    ["तिब्बत सीमा पर किन्नौर में स्थित हिमाचल प्रदेश की सबसे ऊँची चोटी कौन-सी है?", ["रियो पुर्गिल (लियो पारगिल)", "देव टिब्बा", "किन्नर कैलाश", "श्रीखंड महादेव"], "किन्नौर की रियो पुर्गिल (लगभग 6,816 मी) हिमाचल प्रदेश की सबसे ऊँची चोटी है। किन्नर कैलाश लगभग 6,050 मी ऊँचा है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 1,
    ["The river Sutlej enters Himachal Pradesh from Tibet through which pass?", ["Rohtang Pass", "Shipki La", "Kunzum La", "Baralacha La"], "The Sutlej rises near Rakas Tal in Tibet and enters Kinnaur district through the Shipki La."],
    ["सतलुज नदी तिब्बत से हिमाचल प्रदेश में किस दर्रे से प्रवेश करती है?", ["रोहतांग दर्रा", "शिपकी ला", "कुंजम ला", "बारालाचा ला"], "सतलुज तिब्बत में राकस ताल के पास से निकलती है और शिपकी ला के रास्ते किन्नौर जिले में प्रवेश करती है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 2,
    ["The Spiti river meets the Sutlej at:", ["Kaza", "Tabo", "Khab", "Karcham"], "The Spiti river, rising near the Kunzum range, joins the Sutlej at Khab in Kinnaur district."],
    ["स्पीति नदी सतलुज में कहाँ मिलती है?", ["काज़ा", "ताबो", "खाब", "करछम"], "कुंजम श्रेणी के पास से निकलने वाली स्पीति नदी किन्नौर जिले में खाब के पास सतलुज में मिलती है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The ancient Baijnath temple in Kangra district, built in 1204 AD by the merchant brothers Ahuka and Manyuka, is dedicated to:", ["Lord Vishnu", "Goddess Durga", "Lord Hanuman", "Lord Shiva (Vaidyanath)"], "The Baijnath temple, an early Nagara-style stone temple, is dedicated to Shiva as Vaidyanath, 'Lord of Physicians'."],
    ["कांगड़ा जिले का प्राचीन बैजनाथ मंदिर, जो 1204 ई. में व्यापारी बंधुओं अहुका और मन्युका ने बनवाया, किसे समर्पित है?", ["भगवान विष्णु", "देवी दुर्गा", "भगवान हनुमान", "भगवान शिव (वैद्यनाथ)"], "बैजनाथ मंदिर आरंभिक नागर शैली का पत्थर का मंदिर है, जो शिव को वैद्यनाथ ('वैद्यों के स्वामी') के रूप में समर्पित है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 0,
    ["Which of the following rivers of Himachal Pradesh has its origin outside India?", ["Sutlej","Beas","Ravi","Chandra"], "The Sutlej rises near Rakshastal in Tibet and enters Himachal at Shipki La. The Beas, Ravi and Chandra all originate in Himachal Pradesh."],
    ["हिमाचल प्रदेश की निम्नलिखित नदियों में से किसका उद्गम भारत से बाहर है?", ["सतलुज","ब्यास","रावी","चंद्रा"], "सतलुज का उद्गम तिब्बत में राक्षसताल के पास है और यह शिपकी ला से हिमाचल में प्रवेश करती है। ब्यास, रावी और चंद्रा तीनों का उद्गम हिमाचल प्रदेश में है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["The Hadimba Devi Temple, built in a wooden pagoda style amid cedar forest, is at:", ["Kasol", "Manali", "Kufri", "Dalhousie"], "The Hadimba temple at Manali is dedicated to Hidimba, the wife of the Pandava Bhima, and was built in 1553."],
    ["देवदार के जंगल के बीच पैगोडा शैली में बना हडिंबा देवी मंदिर कहाँ है?", ["कसोल", "मनाली", "कुफ़री", "डलहौज़ी"], "मनाली का हडिंबा मंदिर पांडव भीम की पत्नी हिडिंबा को समर्पित है और 1553 में बना था।"]),
  q(0, "hp-gk", "geography", "H", 2,
    ["Manimahesh Lake, the venue of a yearly pilgrimage after Janmashtami, lies in which district?", ["Kangra", "Kullu", "Chamba", "Kinnaur"], "Manimahesh Lake (about 4,080 m) is at the foot of Manimahesh Kailash in the Bharmour region of Chamba district."],
    ["जन्माष्टमी के बाद होने वाली वार्षिक तीर्थयात्रा का स्थल मणिमहेश झील किस जिले में है?", ["कांगड़ा", "कुल्लू", "चंबा", "किन्नौर"], "मणिमहेश झील (लगभग 4,080 मी) चंबा जिले के भरमौर क्षेत्र में मणिमहेश कैलाश के तल पर है।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["The Kunzum Pass connects which two regions of Himachal Pradesh?", ["Kullu and Lahaul", "Kinnaur and Spiti", "Chamba and Pangi", "Lahaul and Spiti"], "Kunzum La (about 4,590 m) links the Lahaul and Spiti valleys and is close to Chandertal."],
    ["कुंजम दर्रा हिमाचल प्रदेश के किन दो क्षेत्रों को जोड़ता है?", ["कुल्लू और लाहौल", "किन्नौर और स्पीति", "चंबा और पांगी", "लाहौल और स्पीति"], "कुंजम ला (लगभग 4,590 मी) लाहौल और स्पीति घाटियों को जोड़ता है और चंद्रताल के निकट है।"]),
  q(0, "hp-gk", "economy", "M", 0,
    ["Bir-Billing in Kangra district is world famous for:", ["Paragliding", "Skiing", "River rafting", "Rock climbing"], "Bir is the landing site and Billing the take-off site; the pair is among the best paragliding destinations in the world."],
    ["कांगड़ा जिले का बीर-बिलिंग किसके लिए विश्व-प्रसिद्ध है?", ["पैराग्लाइडिंग", "स्कीइंग", "रिवर राफ्टिंग", "चट्टान पर चढ़ाई"], "बीर लैंडिंग स्थल और बिलिंग टेक-ऑफ स्थल है; यह जोड़ी विश्व के श्रेष्ठ पैराग्लाइडिंग स्थलों में गिनी जाती है।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["The golf course at Naldehra near Shimla was laid out by which Viceroy?", ["Lord Ripon", "Lord Curzon", "Lord Dalhousie", "Lord Mayo"], "Lord Curzon, who loved the place, laid out the Naldehra golf course in the early 1900s."],
    ["शिमला के पास नालदेहरा गोल्फ़ कोर्स किस वायसराय ने बनवाया?", ["लॉर्ड रिपन", "लॉर्ड कर्ज़न", "लॉर्ड डलहौज़ी", "लॉर्ड मेयो"], "नालदेहरा को पसंद करने वाले लॉर्ड कर्ज़न ने 1900 के दशक की शुरुआत में यह गोल्फ़ कोर्स बनवाया।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Lavi Fair, held every November on the bank of the Sutlej, is celebrated at:", ["Nahan", "Bilaspur", "Rampur Bushahr", "Kalpa"], "The Lavi Fair at Rampur is a traditional trade fair for woollen goods, dry fruits and horses from Kinnaur and Tibet."],
    ["हर नवंबर में सतलुज के तट पर लगने वाला लवी मेला कहाँ आयोजित होता है?", ["नाहन", "बिलासपुर", "रामपुर बुशहर", "कल्पा"], "रामपुर का लवी मेला ऊनी वस्त्रों, सूखे मेवों और किन्नौर व तिब्बत से आने वाले घोड़ों का परंपरागत व्यापारिक मेला है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The Shoolini Fair, celebrated every June, is associated with which town?", ["Shimla", "Nahan", "Paonta Sahib", "Solan"], "The fair honours Goddess Shoolini Devi, from whose name the town of Solan is said to have taken its name."],
    ["हर जून में मनाया जाने वाला शूलिनी मेला किस नगर से संबंधित है?", ["शिमला", "नाहन", "पांवटा साहिब", "सोलन"], "यह मेला देवी शूलिनी को समर्पित है, जिनके नाम पर सोलन नगर का नाम पड़ा माना जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Phulaich (Ukhyang) festival, in which flowers are gathered from the high meadows, is celebrated in:", ["Kinnaur", "Chamba", "Sirmaur", "Lahaul"], "Phulaich, the 'festival of flowers', is celebrated in Kinnaur in September, when villagers bring flowers from the high pastures to offer to the deities."],
    ["फुलैच (उख्यांग) उत्सव, जिसमें ऊँचे चरागाहों से फूल लाए जाते हैं, कहाँ मनाया जाता है?", ["किन्नौर", "चंबा", "सिरमौर", "लाहौल"], "फुलैच 'फूलों का त्योहार' है, जो सितंबर में किन्नौर में मनाया जाता है; ग्रामीण ऊँचे चरागाहों से फूल लाकर देवताओं को चढ़ाते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["Halda, a winter festival in which burning cedar torches are carried and burnt at night, is celebrated in:", ["Kinnaur", "Lahaul", "Kullu", "Pangi"], "Halda is the winter festival of the Lahaul valley, marked by torches of cedar wood and a bonfire, to drive away evil spirits."],
    ["हलदा, जिसमें रात को जलती हुई देवदार की मशालें ले जाकर जलाई जाती हैं, किस क्षेत्र का शीतकालीन उत्सव है?", ["किन्नौर", "लाहौल", "कुल्लू", "पांगी"], "हलदा लाहौल घाटी का शीतकालीन उत्सव है, जिसमें बुरी शक्तियों को भगाने के लिए देवदार की मशालें और अलाव जलाए जाते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Masroor rock-cut temples, often called the 'Ellora of Himachal', are in which district?", ["Mandi", "Chamba", "Kangra", "Kullu"], "The Masroor temples (8th century, about 15 monolithic temples in the Nagara style) are in Kangra district."],
    ["मसरूर के चट्टान काटकर बने मंदिर, जिन्हें प्रायः 'हिमाचल का एलोरा' कहा जाता है, किस जिले में हैं?", ["मंडी", "चंबा", "कांगड़ा", "कुल्लू"], "मसरूर मंदिर (आठवीं शताब्दी, नागर शैली के लगभग 15 एकाश्म मंदिर) कांगड़ा जिले में हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["Tabo Monastery in Spiti, called the 'Ajanta of the Himalayas', was founded in about:", ["1042 AD", "1320 AD", "1575 AD", "996 AD"], "Tabo Monastery was founded in 996 AD by the translator Rinchen Zangpo and is known for its ancient wall paintings."],
    ["स्पीति का ताबो मठ, जिसे 'हिमालय का अजंता' कहा जाता है, लगभग किस वर्ष स्थापित हुआ?", ["1042 ई.", "1320 ई.", "1575 ई.", "996 ई."], "ताबो मठ की स्थापना 996 ई. में अनुवादक रिन्चेन ज़ंगपो ने की थी और यह अपने प्राचीन भित्ति-चित्रों के लिए प्रसिद्ध है।"], "996"),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["The Baspa river, which flows through the Sangla valley past Chitkul village, is a tributary of:", ["Sutlej", "Beas", "Ravi", "Yamuna"], "The Baspa rises near the Indo-Tibetan border, flows through the Sangla valley of Kinnaur and joins the Sutlej near Karcham."],
    ["सांगला घाटी में चितकुल गाँव के पास से बहने वाली बास्पा नदी किसकी सहायक नदी है?", ["सतलुज", "ब्यास", "रावी", "यमुना"], "बास्पा इंडो-तिब्बती सीमा के पास से निकलकर किन्नौर की सांगला घाटी में बहती है और करछम के पास सतलुज में मिलती है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 1,
    ["The Giri river, on which the Giri Bata hydel project stands, joins which river near Paonta Sahib?", ["Sutlej", "Yamuna", "Tons", "Beas"], "The Giri rises near Kupar in the Shimla hills, flows through Sirmaur and meets the Yamuna near Paonta Sahib."],
    ["गिरि नदी, जिस पर गिरि बाटा जलविद्युत परियोजना है, पांवटा साहिब के पास किस नदी में मिलती है?", ["सतलुज", "यमुना", "टौंस", "ब्यास"], "गिरि शिमला की पहाड़ियों में कुपर के पास से निकलती है, सिरमौर से बहती है और पांवटा साहिब के पास यमुना में मिलती है।"]),
  q(0, "hp-gk", "economy", "H", 2,
    ["Apple cultivation was introduced in Himachal Pradesh at Kotgarh in 1916 by:", ["Captain R.C. Lee", "Sir Edwin Lutyens", "Samuel Evans Stokes (Satyanand Stokes)", "Dr Y.S. Parmar"], "The American Samuel Stokes, who later took the name Satyanand, planted the Delicious variety at Kotgarh (Thanedar) in Shimla district."],
    ["1916 में हिमाचल प्रदेश में कोटगढ़ में सेब की खेती की शुरुआत किसने की?", ["कैप्टन आर.सी. ली", "सर एडविन लुटियंस", "सैमुअल इवांस स्टोक्स (सत्यानंद स्टोक्स)", "डॉ. वाई.एस. परमार"], "अमेरिकी सैमुअल स्टोक्स, जिन्होंने बाद में सत्यानंद नाम अपनाया, ने शिमला जिले के कोटगढ़ (थानेदार) में डिलीशियस किस्म लगाई।"]),
  q(0, "hp-gk", "history", "M", 3,
    ["Shimla was officially declared the summer capital of British India in:", ["1857", "1877", "1902", "1864"], "Shimla was made the summer capital of British India in 1864 in the time of Viceroy Sir John Lawrence."],
    ["शिमला को ब्रिटिश भारत की ग्रीष्मकालीन राजधानी आधिकारिक रूप से कब घोषित किया गया?", ["1857", "1877", "1902", "1864"], "1864 में वायसराय सर जॉन लॉरेंस के समय शिमला को ब्रिटिश भारत की ग्रीष्मकालीन राजधानी बनाया गया।"], "1864"),
  q(0, "hp-gk", "economy", "M", 0,
    ["The Kalka-Shimla narrow gauge railway, later named a World Heritage Site, was opened in:", ["1903", "1885", "1912", "1927"], "The 96 km Kalka-Shimla railway opened in 1903 and was inscribed on the UNESCO World Heritage list in 2008 as part of the Mountain Railways of India."],
    ["कालका-शिमला नैरो गेज रेलवे, जिसे बाद में विश्व धरोहर घोषित किया गया, कब खोली गई?", ["1903", "1885", "1912", "1927"], "96 किमी लंबी कालका-शिमला रेलवे 1903 में खुली और 2008 में 'भारत की पर्वतीय रेलवे' के भाग के रूप में यूनेस्को विश्व धरोहर सूची में शामिल हुई।"], "1903"),
  q(0, "hp-gk", "economy", "H", 1,
    ["The Nathpa Jhakri hydroelectric project on the Sutlej has an installed capacity of:", ["1,045 MW", "1,500 MW", "800 MW", "2,000 MW"], "Nathpa Jhakri (6 x 250 MW = 1,500 MW), run by SJVN, is the largest hydropower project in Himachal Pradesh. Karcham Wangtoo is 1,045 MW."],
    ["सतलुज पर बनी नाथपा झाकड़ी जलविद्युत परियोजना की स्थापित क्षमता कितनी है?", ["1,045 मेगावाट", "1,500 मेगावाट", "800 मेगावाट", "2,000 मेगावाट"], "SJVN द्वारा संचालित नाथपा झाकड़ी (6 x 250 = 1,500 मेगावाट) हिमाचल प्रदेश की सबसे बड़ी जलविद्युत परियोजना है। करछम वांगतू 1,045 मेगावाट की है।"], "1500"),
  q(0, "hp-gk", "districts", "M", 2,
    ["Which town is the district headquarters of Lahaul & Spiti?", ["Kaza","Tabo","Keylong","Udaipur"], "Keylong, on the bank of the Bhaga river, is the district headquarters of Lahaul & Spiti. Kaza is the sub-divisional headquarters of Spiti."],
    ["लाहौल-स्पीति जिले का मुख्यालय कौन-सा नगर है?", ["काज़ा","ताबो","केलांग","उदयपुर"], "भागा नदी के तट पर बसा केलांग लाहौल-स्पीति का जिला मुख्यालय है। काज़ा स्पीति का उपमंडल मुख्यालय है।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["The Pin Valley National Park, home of the snow leopard and ibex, lies in the cold desert of:", ["Kullu", "Kangra", "Sirmaur", "Spiti"], "Pin Valley National Park is in the cold desert region of Spiti (Lahaul & Spiti district). The snow leopard is the state animal of Himachal Pradesh."],
    ["हिम तेंदुए और आइबेक्स का घर पिन वैली राष्ट्रीय उद्यान किस शीत मरुस्थल में है?", ["कुल्लू", "कांगड़ा", "सिरमौर", "स्पीति"], "पिन वैली राष्ट्रीय उद्यान स्पीति (लाहौल-स्पीति जिला) के शीत मरुस्थल में है। हिम तेंदुआ हिमाचल प्रदेश का राज्य पशु है।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["How many princely states were merged to form Himachal Pradesh on 15 April 1948?", ["30", "21", "27", "36"], "Himachal Pradesh was formed as a Chief Commissioner's province by the merger of 30 princely states of the Punjab hill and Shimla hill regions."],
    ["15 अप्रैल 1948 को हिमाचल प्रदेश के गठन में कितनी रियासतों का विलय हुआ?", ["30", "21", "27", "36"], "पंजाब और शिमला पहाड़ी क्षेत्रों की 30 रियासतों के विलय से हिमाचल प्रदेश मुख्य आयुक्त प्रांत के रूप में बना।"], "30"),

  // ───────── Section 1: General Knowledge (25) ─────────
  q(1, "general-studies", "indian-history", "H", 1,
    ["Which was the first Indian state annexed by Lord Dalhousie under the Doctrine of Lapse (1848)?", ["Jhansi", "Satara", "Nagpur", "Sambalpur"], "Satara was the first state annexed under the Doctrine of Lapse, in 1848. Sambalpur, Jaitpur, Jhansi and Nagpur followed."],
    ["लॉर्ड डलहौज़ी ने व्यपगत के सिद्धांत (1848) के अंतर्गत सबसे पहले किस भारतीय राज्य को मिलाया?", ["झाँसी", "सतारा", "नागपुर", "संबलपुर"], "व्यपगत के सिद्धांत से सबसे पहले 1848 में सतारा मिलाया गया। इसके बाद संबलपुर, जैतपुर, झाँसी और नागपुर मिलाए गए।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["The Ryotwari land revenue system, in which the cultivator paid tax directly to the government, was introduced mainly by:", ["Lord Cornwallis", "Lord Wellesley", "Thomas Munro", "John Shore"], "The Ryotwari system was introduced by Thomas Munro and Alexander Read in Madras and Bombay. Cornwallis brought the Permanent Settlement in Bengal."],
    ["रैयतवाड़ी भू-राजस्व व्यवस्था, जिसमें किसान सीधे सरकार को कर देता था, मुख्यतः किसने लागू की?", ["लॉर्ड कॉर्नवालिस", "लॉर्ड वेलेज़ली", "थॉमस मुनरो", "जॉन शोर"], "रैयतवाड़ी व्यवस्था थॉमस मुनरो और अलेक्ज़ेंडर रीड ने मद्रास और बंबई में लागू की। कॉर्नवालिस ने बंगाल में स्थायी बंदोबस्त लागू किया।"]),
  q(1, "general-studies", "indian-history", "M", 3,
    ["The Bardoli Satyagraha of 1928, against an increase in land revenue, was led by:", ["Mahatma Gandhi", "Jawaharlal Nehru", "Rajendra Prasad", "Vallabhbhai Patel"], "Vallabhbhai Patel led the Bardoli Satyagraha in Gujarat, after which the women of Bardoli gave him the title 'Sardar'."],
    ["भू-राजस्व वृद्धि के विरुद्ध 1928 के बारदोली सत्याग्रह का नेतृत्व किसने किया?", ["महात्मा गांधी", "जवाहरलाल नेहरू", "राजेंद्र प्रसाद", "वल्लभभाई पटेल"], "वल्लभभाई पटेल ने गुजरात में बारदोली सत्याग्रह का नेतृत्व किया, जिसके बाद बारदोली की महिलाओं ने उन्हें 'सरदार' की उपाधि दी।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Who wrote the 'Harshacharita', the biography of the emperor Harshavardhana?", ["Banabhatta", "Kalidasa", "Vishakhadatta", "Kalhana"], "Banabhatta, the court poet of Harsha, wrote the Harshacharita and the novel Kadambari."],
    ["सम्राट हर्षवर्धन की जीवनी 'हर्षचरित' किसने लिखी?", ["बाणभट्ट", "कालिदास", "विशाखदत्त", "कल्हण"], "हर्ष के दरबारी कवि बाणभट्ट ने हर्षचरित और उपन्यास कादंबरी लिखे।"]),
  q(1, "general-studies", "indian-history", "H", 1,
    ["Lala Lajpat Rai died in 1928 from injuries received in a lathi charge during a protest against the:", ["Rowlatt Act", "Simon Commission", "Cripps Mission", "Cabinet Mission"], "Lala Lajpat Rai was hurt in a police lathi charge at Lahore on 30 October 1928 during a demonstration against the all-white Simon Commission and died on 17 November."],
    ["लाला लाजपत राय की 1928 में लाठी-चार्ज में लगी चोटों से मृत्यु हुई; वह प्रदर्शन किसके विरुद्ध था?", ["रौलट एक्ट", "साइमन कमीशन", "क्रिप्स मिशन", "कैबिनेट मिशन"], "30 अक्टूबर 1928 को लाहौर में केवल श्वेत सदस्यों वाले साइमन कमीशन के विरुद्ध प्रदर्शन में लाला लाजपत राय पुलिस लाठी-चार्ज में घायल हुए और 17 नवंबर को उनका निधन हो गया।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["A writ commanding a public official to perform a duty that he has failed to perform is called:", ["Certiorari", "Quo Warranto", "Mandamus", "Prohibition"], "Mandamus ('we command') directs a public authority to perform its legal duty. Quo warranto questions a person's right to hold a public office."],
    ["किसी लोक अधिकारी को अपना न किया हुआ कर्तव्य निभाने का आदेश देने वाली रिट क्या कहलाती है?", ["उत्प्रेषण", "अधिकार पृच्छा", "परमादेश (मैंडमस)", "प्रतिषेध"], "परमादेश ('हम आदेश देते हैं') किसी लोक प्राधिकारी को उसका विधिक कर्तव्य निभाने का निर्देश देता है। अधिकार पृच्छा किसी व्यक्ति के सार्वजनिक पद पर बने रहने के अधिकार पर प्रश्न उठाती है।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["How many members of the Rajya Sabha are nominated by the President of India?", ["2", "10", "15", "12"], "The President nominates 12 members with special knowledge of literature, science, art or social service. The maximum strength of the Rajya Sabha is 250."],
    ["राज्यसभा के कितने सदस्य भारत के राष्ट्रपति द्वारा मनोनीत किए जाते हैं?", ["2", "10", "15", "12"], "राष्ट्रपति साहित्य, विज्ञान, कला या समाज सेवा के विशेष ज्ञान वाले 12 सदस्य मनोनीत करता है। राज्यसभा की अधिकतम संख्या 250 है।"], "12"),
  q(1, "general-studies", "indian-polity", "H", 0,
    ["Under which Article of the Constitution can the President summon a joint sitting of both Houses of Parliament?", ["Article 108","Article 110","Article 112","Article 123"], "Article 108 provides for a joint sitting when the two Houses disagree on a Bill. Article 110 defines a Money Bill, Article 112 the annual financial statement and Article 123 ordinances."],
    ["संविधान के किस अनुच्छेद के अंतर्गत राष्ट्रपति संसद के दोनों सदनों की संयुक्त बैठक बुला सकते हैं?", ["अनुच्छेद 108","अनुच्छेद 110","अनुच्छेद 112","अनुच्छेद 123"], "अनुच्छेद 108 दोनों सदनों में किसी विधेयक पर असहमति होने पर संयुक्त बैठक का प्रावधान करता है। अनुच्छेद 110 धन विधेयक, 112 वार्षिक वित्तीय विवरण और 123 अध्यादेश से संबंधित है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Free and compulsory education for children aged 6 to 14 years is guaranteed as a Fundamental Right by which Article?", ["Article 19", "Article 21A", "Article 29", "Article 45"], "Article 21A, inserted by the 86th Amendment (2002), makes elementary education a Fundamental Right. The Right to Education Act came into force in 2010."],
    ["6 से 14 वर्ष के बच्चों की निःशुल्क और अनिवार्य शिक्षा किस अनुच्छेद द्वारा मौलिक अधिकार के रूप में प्रत्याभूत है?", ["अनुच्छेद 19", "अनुच्छेद 21A", "अनुच्छेद 29", "अनुच्छेद 45"], "86वें संशोधन (2002) द्वारा जोड़ा गया अनुच्छेद 21A प्रारंभिक शिक्षा को मौलिक अधिकार बनाता है। शिक्षा का अधिकार अधिनियम 2010 में लागू हुआ।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["Superintendence, direction and control of elections in India is vested in the Election Commission under which Article?", ["Article 280", "Article 315", "Article 324", "Article 356"], "Article 324 vests the superintendence, direction and control of elections to Parliament, State Legislatures and the offices of President and Vice-President in the Election Commission."],
    ["भारत में चुनावों के अधीक्षण, निदेशन और नियंत्रण की शक्ति निर्वाचन आयोग में किस अनुच्छेद द्वारा निहित है?", ["अनुच्छेद 280", "अनुच्छेद 315", "अनुच्छेद 324", "अनुच्छेद 356"], "अनुच्छेद 324 संसद, राज्य विधानमंडलों तथा राष्ट्रपति और उपराष्ट्रपति के पदों के चुनावों का अधीक्षण, निदेशन और नियंत्रण निर्वाचन आयोग में निहित करता है।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["Which of the following states is NOT crossed by the Tropic of Cancer?", ["Chhattisgarh", "Jharkhand", "Tripura", "Odisha"], "The Tropic of Cancer passes through eight states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram."],
    ["निम्नलिखित में से किस राज्य से कर्क रेखा नहीं गुज़रती?", ["छत्तीसगढ़", "झारखंड", "त्रिपुरा", "ओडिशा"], "कर्क रेखा आठ राज्यों से गुज़रती है: गुजरात, राजस्थान, मध्य प्रदेश, छत्तीसगढ़, झारखंड, पश्चिम बंगाल, त्रिपुरा और मिज़ोरम।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Sambhar Lake, the largest inland salt-water lake in India, is in:", ["Rajasthan", "Gujarat", "Haryana", "Odisha"], "Sambhar Salt Lake, near Jaipur in Rajasthan, is India's largest inland saline lake and a major source of salt."],
    ["भारत की सबसे बड़ी अंतर्देशीय खारे पानी की झील सांभर झील कहाँ है?", ["राजस्थान", "गुजरात", "हरियाणा", "ओडिशा"], "राजस्थान में जयपुर के पास स्थित सांभर साल्ट लेक भारत की सबसे बड़ी अंतर्देशीय खारी झील और नमक का प्रमुख स्रोत है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Wular Lake, considered the largest freshwater lake in India, is located in:", ["Rajasthan", "Jammu and Kashmir", "Manipur", "Odisha"], "Wular Lake lies near Bandipora in Kashmir and is fed by the Jhelum. Loktak in Manipur is the largest freshwater lake of North-East India."],
    ["भारत की सबसे बड़ी मीठे पानी की झील मानी जाने वाली वुलर झील कहाँ है?", ["राजस्थान", "जम्मू और कश्मीर", "मणिपुर", "ओडिशा"], "वुलर झील कश्मीर में बांदीपोरा के पास है और झेलम से पोषित होती है। मणिपुर की लोकटक पूर्वोत्तर की सबसे बड़ी मीठे पानी की झील है।"]),
  q(1, "general-studies", "indian-geography", "E", 2,
    ["The one-horned rhinoceros is the famous attraction of which national park?", ["Gir National Park", "Jim Corbett National Park", "Kaziranga National Park", "Ranthambore National Park"], "Kaziranga in Assam holds most of the world's one-horned rhinos. Gir is known for the Asiatic lion and Corbett and Ranthambore for tigers."],
    ["एक सींग वाले गैंडे के लिए कौन-सा राष्ट्रीय उद्यान प्रसिद्ध है?", ["गिर राष्ट्रीय उद्यान", "जिम कॉर्बेट राष्ट्रीय उद्यान", "काज़ीरंगा राष्ट्रीय उद्यान", "रणथंभौर राष्ट्रीय उद्यान"], "असम का काज़ीरंगा दुनिया के अधिकांश एक सींग वाले गैंडों का घर है। गिर एशियाई शेर के लिए और कॉर्बेट व रणथंभौर बाघों के लिए जाने जाते हैं।"]),
  q(1, "general-studies", "indian-geography", "M", 3,
    ["The longest river of Peninsular India is the:", ["Krishna", "Kaveri", "Narmada", "Godavari"], "The Godavari (about 1,465 km), called 'Dakshin Ganga', is the longest river of Peninsular India."],
    ["प्रायद्वीपीय भारत की सबसे लंबी नदी कौन-सी है?", ["कृष्णा", "कावेरी", "नर्मदा", "गोदावरी"], "गोदावरी (लगभग 1,465 किमी), जिसे 'दक्षिण गंगा' कहते हैं, प्रायद्वीपीय भारत की सबसे लंबी नदी है।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["The GST Council, which decides GST rates in India, is chaired by:", ["The Union Finance Minister","The Prime Minister","The Governor of the RBI","The President"], "Under Article 279A the GST Council is chaired by the Union Finance Minister, and its members are the Union and State finance ministers."],
    ["भारत में GST की दरें तय करने वाली GST परिषद की अध्यक्षता कौन करता है?", ["केंद्रीय वित्त मंत्री","प्रधानमंत्री","भारतीय रिज़र्व बैंक के गवर्नर","राष्ट्रपति"], "अनुच्छेद 279A के अंतर्गत GST परिषद की अध्यक्षता केंद्रीय वित्त मंत्री करते हैं, और इसके सदस्य केंद्र व राज्यों के वित्त मंत्री होते हैं।"]),
  q(1, "general-studies", "indian-economy", "M", 1,
    ["The Sensex is the benchmark share-price index of which stock exchange?", ["National Stock Exchange (NSE)", "Bombay Stock Exchange (BSE)", "Calcutta Stock Exchange", "Multi Commodity Exchange"], "Sensex tracks 30 large companies listed on the BSE. The benchmark index of the NSE is the Nifty 50."],
    ["सेंसेक्स किस शेयर बाज़ार का प्रमुख शेयर-मूल्य सूचकांक है?", ["नेशनल स्टॉक एक्सचेंज (NSE)", "बॉम्बे स्टॉक एक्सचेंज (BSE)", "कलकत्ता स्टॉक एक्सचेंज", "मल्टी कमोडिटी एक्सचेंज"], "सेंसेक्स BSE में सूचीबद्ध 30 बड़ी कंपनियों को दर्शाता है। NSE का प्रमुख सूचकांक निफ्टी 50 है।"]),
  q(1, "general-studies", "indian-economy", "M", 2,
    ["Operation Flood, the dairy programme behind India's White Revolution, is associated with:", ["M.S. Swaminathan", "Norman Borlaug", "Verghese Kurien", "Homi Bhabha"], "Dr Verghese Kurien, the 'Milkman of India' and founder of Amul, led Operation Flood. Swaminathan is linked to the Green Revolution."],
    ["भारत की श्वेत क्रांति के पीछे के डेयरी कार्यक्रम 'ऑपरेशन फ्लड' का संबंध किससे है?", ["एम.एस. स्वामीनाथन", "नॉर्मन बोरलॉग", "वर्गीज़ कुरियन", "होमी भाभा"], "'भारत के मिल्कमैन' और अमूल के संस्थापक डॉ. वर्गीज़ कुरियन ने ऑपरेशन फ्लड का नेतृत्व किया। स्वामीनाथन हरित क्रांति से जुड़े हैं।"]),
  q(1, "general-studies", "indian-economy", "H", 3,
    ["The Minimum Support Price (MSP) of crops is announced by the Government of India on the recommendation of:", ["NITI Aayog", "NABARD", "The Finance Commission", "The Commission for Agricultural Costs and Prices (CACP)"], "The CACP recommends MSPs for notified crops and the Cabinet Committee on Economic Affairs approves them."],
    ["फ़सलों का न्यूनतम समर्थन मूल्य (MSP) भारत सरकार किसकी सिफ़ारिश पर घोषित करती है?", ["नीति आयोग", "नाबार्ड", "वित्त आयोग", "कृषि लागत एवं मूल्य आयोग (CACP)"], "CACP अधिसूचित फ़सलों के MSP की सिफ़ारिश करता है और आर्थिक मामलों की मंत्रिमंडलीय समिति उन्हें मंज़ूरी देती है।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Which non-metal is a liquid at room temperature?", ["Bromine", "Iodine", "Chlorine", "Sulphur"], "Bromine is the only liquid non-metal at room temperature; mercury is the only liquid metal."],
    ["कमरे के तापमान पर कौन-सा अधातु द्रव अवस्था में होता है?", ["ब्रोमीन", "आयोडीन", "क्लोरीन", "सल्फ़र"], "ब्रोमीन कमरे के तापमान पर एकमात्र द्रव अधातु है; पारा एकमात्र द्रव धातु है।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["Night blindness is caused by the deficiency of which vitamin?", ["Vitamin K","Vitamin A","Vitamin B1","Vitamin E"], "Lack of vitamin A affects the retina and causes night blindness. Carrots, papaya and green leafy vegetables are rich in it."],
    ["रतौंधी (रात्रि अंधता) किस विटामिन की कमी से होती है?", ["विटामिन K","विटामिन A","विटामिन B1","विटामिन E"], "विटामिन A की कमी से रेटिना प्रभावित होता है और रतौंधी होती है। गाजर, पपीता और हरी पत्तेदार सब्ज़ियाँ इसका अच्छा स्रोत हैं।"]),
  q(1, "general-studies", "general-science", "H", 2,
    ["Which blood group is called the universal recipient?", ["O negative","A positive","AB positive","B negative"], "AB positive blood has both A and B antigens and the Rh antigen, and no anti-A or anti-B antibodies, so the person can receive blood of any group."],
    ["कौन-सा रक्त समूह सर्वग्राही (यूनिवर्सल रिसीपिएंट) कहलाता है?", ["O ऋणात्मक","A धनात्मक","AB धनात्मक","B ऋणात्मक"], "AB धनात्मक रक्त में A और B दोनों एंटीजन तथा Rh एंटीजन होते हैं और एंटी-A या एंटी-B प्रतिरक्षी नहीं होते, इसलिए यह व्यक्ति किसी भी समूह का रक्त ले सकता है।"]),
  q(1, "general-studies", "general-science", "E", 3,
    ["The SI unit of pressure is:", ["Newton","Joule","Watt","Pascal"], "Pressure is force per unit area and is measured in pascal (Pa), which equals one newton per square metre."],
    ["दाब का SI मात्रक है:", ["न्यूटन","जूल","वाट","पास्कल"], "दाब प्रति इकाई क्षेत्रफल पर लगने वाला बल है और पास्कल (Pa) में मापा जाता है, जो एक न्यूटन प्रति वर्ग मीटर के बराबर है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["The headquarters of INTERPOL, the international police organisation, is at:", ["Lyon (France)", "Paris (France)", "The Hague (Netherlands)", "Geneva (Switzerland)"], "INTERPOL has its General Secretariat at Lyon, France. The International Court of Justice sits at The Hague."],
    ["अंतरराष्ट्रीय पुलिस संगठन इंटरपोल का मुख्यालय कहाँ है?", ["ल्यों (फ्रांस)", "पेरिस (फ्रांस)", "द हेग (नीदरलैंड)", "जिनेवा (स्विट्ज़रलैंड)"], "इंटरपोल का महासचिवालय फ्रांस के ल्यों में है। अंतरराष्ट्रीय न्यायालय द हेग में स्थित है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["The Sardar Vallabhbhai Patel National Police Academy, which trains IPS officers, is located at:", ["Dehradun", "Hyderabad", "Mount Abu", "Lucknow"], "The SVP National Police Academy is at Shivarampally, Hyderabad, and trains IPS officers."],
    ["IPS अधिकारियों को प्रशिक्षण देने वाली सरदार वल्लभभाई पटेल राष्ट्रीय पुलिस अकादमी कहाँ है?", ["देहरादून", "हैदराबाद", "माउंट आबू", "लखनऊ"], "सरदार वल्लभभाई पटेल राष्ट्रीय पुलिस अकादमी हैदराबाद के शिवरामपल्ली में है और IPS अधिकारियों को प्रशिक्षण देती है।"]),

  // ───────── Section 2: Reasoning (20) ─────────
  q(2, "reasoning", "series", "M", 2,
    ["Find the next number: 3, 8, 15, 24, 35, ?", ["45", "49", "48", "50"], "The terms are n² − 1 for n = 2, 3, 4, 5, 6. The next is 7² − 1 = 48."],
    ["अगली संख्या ज्ञात कीजिए: 3, 8, 15, 24, 35, ?", ["45", "49", "48", "50"], "पद n² − 1 हैं, n = 2, 3, 4, 5, 6 के लिए। अगला 7² − 1 = 48 है।"], "7*7-1"),
  q(2, "reasoning", "series", "H", 3,
    ["Find the next number: 11, 13, 17, 23, 31, ?", ["39","43","45","41"], "The differences are 2, 4, 6, 8, which increase by 2 each time. The next difference is 10, so 31 + 10 = 41."],
    ["अगली संख्या ज्ञात कीजिए: 11, 13, 17, 23, 31, ?", ["39","43","45","41"], "अंतर 2, 4, 6, 8 हैं, जो हर बार 2 बढ़ते हैं। अगला अंतर 10 है, अतः 31 + 10 = 41।"], "31+10"),
  q(2, "reasoning", "series", "H", 0,
    ["Find the next letter: B, D, G, K, P, ?", ["V", "U", "W", "T"], "Positions are 2, 4, 7, 11, 16. The gaps grow by 1 each time: +2, +3, +4, +5, so the next is +6: 16 + 6 = 22, which is V."],
    ["अगला अक्षर ज्ञात कीजिए: B, D, G, K, P, ?", ["V", "U", "W", "T"], "क्रमांक 2, 4, 7, 11, 16 हैं। अंतर हर बार 1 बढ़ता है: +2, +3, +4, +5, अतः अगला +6 है: 16 + 6 = 22, यानी V।"]),
  q(2, "reasoning", "series", "H", 1,
    ["Find the wrong term in the series: 1, 8, 27, 65, 125, 216", ["27", "65", "125", "216"], "The terms are the cubes 1³, 2³, 3³, 4³, 5³, 6³. So 4³ = 64, not 65."],
    ["श्रेणी में गलत पद ज्ञात कीजिए: 1, 8, 27, 65, 125, 216", ["27", "65", "125", "216"], "पद घन हैं: 1³, 2³, 3³, 4³, 5³, 6³। अतः 4³ = 64 होना चाहिए, 65 नहीं।"], "65"),
  q(2, "reasoning", "coding-decoding", "M", 2,
    ["If MOTHER is coded as OQVJGT, how will POLICE be coded?", ["RQMKEG", "QPNKEG", "RQNKEG", "RQNJEG"], "Each letter moves 2 steps forward: P→R, O→Q, L→N, I→K, C→E, E→G."],
    ["यदि MOTHER को OQVJGT लिखा जाता है, तो POLICE को कैसे लिखा जाएगा?", ["RQMKEG", "QPNKEG", "RQNKEG", "RQNJEG"], "प्रत्येक अक्षर 2 स्थान आगे बढ़ता है: P→R, O→Q, L→N, I→K, C→E, E→G।"]),
  q(2, "reasoning", "coding-decoding", "M", 3,
    ["If A = 1, B = 2, C = 3 and so on, then CAT = 24 and DOG = 26. What is the value of RAT?", ["37", "41", "45", "39"], "R = 18, A = 1, T = 20, so RAT = 18 + 1 + 20 = 39."],
    ["यदि A = 1, B = 2, C = 3 इत्यादि हो, तो CAT = 24 और DOG = 26 है। RAT का मान क्या होगा?", ["37", "41", "45", "39"], "R = 18, A = 1, T = 20, अतः RAT = 18 + 1 + 20 = 39।"], "18+1+20"),
  q(2, "reasoning", "blood-relations", "M", 0,
    ["Pointing to a girl, Ramesh says, 'Her mother is the only daughter of my mother.' How is the girl related to Ramesh?", ["Niece", "Sister", "Cousin", "Aunt"], "The only daughter of Ramesh's mother is Ramesh's sister. She is the girl's mother, so the girl is Ramesh's niece."],
    ["एक लड़की की ओर इशारा करके रमेश कहता है, 'इसकी माँ मेरी माँ की इकलौती बेटी है।' लड़की रमेश की क्या लगती है?", ["भांजी", "बहन", "चचेरी बहन", "बुआ"], "रमेश की माँ की इकलौती बेटी रमेश की बहन है। वह लड़की की माँ है, अतः लड़की रमेश की भांजी (बहन की बेटी) है।"]),
  q(2, "reasoning", "blood-relations", "H", 1,
    ["P is the son of Q. Q is the sister of R. S is the father of R. How is S related to P?", ["Father", "Maternal grandfather", "Paternal grandfather", "Maternal uncle"], "S is the father of R and so also of Q, who is R's sister. Q is P's mother, so S is P's maternal grandfather."],
    ["P, Q का पुत्र है। Q, R की बहन है। S, R का पिता है। S का P से क्या संबंध है?", ["पिता", "नाना", "दादा", "मामा"], "S, R का पिता है और इसलिए R की बहन Q का भी पिता है। Q, P की माँ है, अतः S, P का नाना है।"]),
  q(2, "reasoning", "direction-sense", "M", 2,
    ["Rohit walks 5 km north, turns right and walks 3 km, then turns right again and walks 5 km. How far and in which direction is he from the starting point?", ["3 km west", "5 km east", "3 km east", "8 km north"], "North 5, east 3, then south 5 brings him level with the start, but 3 km to the east."],
    ["रोहित 5 किमी उत्तर चलता है, दाएँ मुड़कर 3 किमी चलता है, फिर दाएँ मुड़कर 5 किमी चलता है। वह प्रारंभिक बिंदु से कितनी दूर और किस दिशा में है?", ["3 किमी पश्चिम", "5 किमी पूर्व", "3 किमी पूर्व", "8 किमी उत्तर"], "उत्तर 5, पूर्व 3, फिर दक्षिण 5 चलने पर वह प्रारंभिक बिंदु की सीध में आ जाता है, पर 3 किमी पूर्व में।"]),
  q(2, "reasoning", "direction-sense", "H", 3,
    ["Sunil walks 10 m south, turns left and walks 6 m, turns left again and walks 10 m, then turns right and walks 4 m. How far and in which direction is he from the starting point?", ["6 m east", "4 m north", "10 m west", "10 m east"], "South 10, east 6 (left of south is east), north 10 (left of east is north) puts him 6 m east of the start. Turning right (east) and walking 4 m makes it 10 m east."],
    ["सुनील 10 मी दक्षिण चलता है, बाएँ मुड़कर 6 मी चलता है, फिर बाएँ मुड़कर 10 मी चलता है, फिर दाएँ मुड़कर 4 मी चलता है। वह प्रारंभिक बिंदु से कितनी दूर और किस दिशा में है?", ["6 मी पूर्व", "4 मी उत्तर", "10 मी पश्चिम", "10 मी पूर्व"], "दक्षिण 10, पूर्व 6 (दक्षिण की ओर मुँह हो तो बायाँ पूर्व है), उत्तर 10 (पूर्व की ओर मुँह हो तो बायाँ उत्तर है) से वह प्रारंभिक बिंदु से 6 मी पूर्व में आ जाता है। दाएँ (पूर्व) मुड़कर 4 मी चलने पर वह 10 मी पूर्व में है।"]),
  q(2, "reasoning", "ranking", "M", 0,
    ["Meena is 12th from the top and 29th from the bottom in a class. How many students are there in the class?", ["40", "41", "42", "43"], "Total = 12 + 29 − 1 = 40."],
    ["एक कक्षा में मीना ऊपर से 12वें और नीचे से 29वें स्थान पर है। कक्षा में कुल कितने छात्र हैं?", ["40", "41", "42", "43"], "कुल = 12 + 29 − 1 = 40।"], "12+29-1"),
  q(2, "reasoning", "puzzles", "M", 1,
    ["D is older than A. A is older than B. C is younger than B. Who is the youngest of the four?", ["A", "C", "B", "D"], "The order from oldest is D > A > B > C, so C is the youngest."],
    ["D, A से बड़ा है। A, B से बड़ा है। C, B से छोटा है। चारों में सबसे छोटा कौन है?", ["A", "C", "B", "D"], "बड़े से छोटे का क्रम D > A > B > C है, अतः C सबसे छोटा है।"]),
  q(2, "reasoning", "analogy", "M", 2,
    ["Doctor : Hospital :: Constable : ?", ["Court", "Jail", "Police station", "School"], "A doctor works in a hospital; a constable works in a police station."],
    ["डॉक्टर : अस्पताल :: कांस्टेबल : ?", ["न्यायालय", "जेल", "थाना", "विद्यालय"], "डॉक्टर अस्पताल में काम करता है; कांस्टेबल थाने में काम करता है।"]),
  q(2, "reasoning", "analogy", "H", 3,
    ["8 : 65 :: 6 : ?", ["36", "35", "49", "37"], "The rule is n² + 1: 8² + 1 = 65, so 6² + 1 = 37."],
    ["8 : 65 :: 6 : ?", ["36", "35", "49", "37"], "नियम n² + 1 है: 8² + 1 = 65, अतः 6² + 1 = 37।"], "6*6+1"),
  q(2, "reasoning", "odd-one-out", "M", 0,
    ["Find the odd one out: 121, 144, 169, 200, 225", ["200", "121", "169", "225"], "All the others are perfect squares (11², 12², 13², 15²). 200 is not."],
    ["विषम चुनिए: 121, 144, 169, 200, 225", ["200", "121", "169", "225"], "अन्य सभी पूर्ण वर्ग हैं (11², 12², 13², 15²)। 200 पूर्ण वर्ग नहीं है।"], "200"),
  q(2, "reasoning", "syllogism", "H", 0,
    ["Statements: Some pens are books. No book is a table. Conclusions: I. Some pens are not tables. II. No pen is a table.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "The pens that are books cannot be tables, so some pens are not tables (I follows). Other pens are not covered by the statements, so we cannot say that no pen is a table (II does not follow)."],
    ["कथन: कुछ पेन किताबें हैं। कोई किताब मेज़ नहीं है। निष्कर्ष: I. कुछ पेन मेज़ नहीं हैं। II. कोई पेन मेज़ नहीं है।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "जो पेन किताबें हैं वे मेज़ नहीं हो सकते, अतः कुछ पेन मेज़ नहीं हैं (I सही)। बाकी पेनों के बारे में कथन कुछ नहीं कहते, अतः यह नहीं कह सकते कि कोई पेन मेज़ नहीं है (II सही नहीं)।"]),
  q(2, "reasoning", "syllogism", "H", 2,
    ["Statements: P > Q ≥ R, R > S. Conclusions: I. P > S. II. Q > S.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "Combining the statements gives P > Q ≥ R > S. Hence P > S (I) and Q > S (II) both follow."],
    ["कथन: P > Q ≥ R, R > S. निष्कर्ष: I. P > S. II. Q > S.", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "कथनों को मिलाने पर P > Q ≥ R > S मिलता है। अतः P > S (I) और Q > S (II) दोनों सही हैं।"]),
  q(2, "reasoning", "clock-calendar", "H", 3,
    ["What is the mirror image of the time 3:40 on a clock?", ["9:20", "8:40", "7:20", "8:20"], "Mirror time = 11:60 − 3:40 = 8:20."],
    ["घड़ी में समय 3:40 का दर्पण प्रतिबिंब क्या होगा?", ["9:20", "8:40", "7:20", "8:20"], "दर्पण समय = 11:60 − 3:40 = 8:20।"]),
  q(2, "reasoning", "clock-calendar", "H", 0,
    ["If 15 August 2026 is a Saturday, what day of the week will 15 August 2027 be?", ["Sunday", "Monday", "Friday", "Saturday"], "The period from August 2026 to August 2027 contains no 29 February, so it has 365 days = 52 weeks + 1 day. Saturday + 1 = Sunday."],
    ["यदि 15 अगस्त 2026 को शनिवार है, तो 15 अगस्त 2027 को सप्ताह का कौन-सा दिन होगा?", ["रविवार", "सोमवार", "शुक्रवार", "शनिवार"], "अगस्त 2026 से अगस्त 2027 के बीच 29 फ़रवरी नहीं आती, इसलिए 365 दिन = 52 सप्ताह + 1 दिन। शनिवार + 1 = रविवार।"]),
  q(2, "reasoning", "dice-cube", "H", 1,
    ["A cube painted on all faces is cut into 125 equal small cubes. How many small cubes have exactly one painted face?", ["36", "54", "48", "27"], "The cube is 5 x 5 x 5. Cubes with exactly one painted face = 6 x (5 − 2)² = 6 x 9 = 54."],
    ["सभी फलकों पर रंगे एक घन को 125 बराबर छोटे घनों में काटा जाता है। कितने छोटे घनों के ठीक एक फलक पर रंग होगा?", ["36", "54", "48", "27"], "घन 5 x 5 x 5 का है। ठीक एक फलक रंगे घन = 6 x (5 − 2)² = 6 x 9 = 54।"], "6*9"),

  // ───────── Section 3: Numerical Ability (15) ─────────
  q(3, "quant", "percentage", "M", 3,
    ["If the price of sugar rises by 25%, by what percent must a family cut its consumption so that its expenditure stays the same?", ["25%", "15%", "30%", "20%"], "Reduction = 25/(100 + 25) x 100 = 20%."],
    ["यदि चीनी का मूल्य 25% बढ़ जाए, तो एक परिवार को अपनी खपत कितने प्रतिशत घटानी होगी ताकि व्यय समान रहे?", ["25%", "15%", "30%", "20%"], "कमी = 25/(100 + 25) x 100 = 20%।"], "25/125*100"),
  q(3, "quant", "ratio-proportion", "M", 0,
    ["₹1,540 is divided among A, B and C in the ratio 2 : 3 : 6. What is C's share?", ["₹840", "₹560", "₹720", "₹900"], "Total parts = 11, so one part = 1,540 ÷ 11 = ₹140. C gets 6 x 140 = ₹840."],
    ["₹1,540 को A, B और C में 2 : 3 : 6 के अनुपात में बाँटा जाता है। C का हिस्सा क्या है?", ["₹840", "₹560", "₹720", "₹900"], "कुल भाग = 11, अतः एक भाग = 1,540 ÷ 11 = ₹140। C को 6 x 140 = ₹840 मिलेंगे।"], "840"),
  q(3, "quant", "profit-loss", "H", 1,
    ["A trader sells two articles at ₹1,200 each, one at a 20% gain and the other at a 20% loss. What is his overall gain or loss?", ["No gain, no loss", "Loss of ₹100", "Gain of ₹100", "Loss of ₹120"], "Cost of the first = 1,200 ÷ 1.2 = ₹1,000; of the second = 1,200 ÷ 0.8 = ₹1,500. Total cost = ₹2,500 and total selling price = ₹2,400, so the loss is ₹100."],
    ["एक व्यापारी दो वस्तुएँ ₹1,200 प्रति वस्तु बेचता है, एक पर 20% लाभ और दूसरी पर 20% हानि होती है। कुल लाभ या हानि क्या है?", ["न लाभ न हानि", "₹100 की हानि", "₹100 का लाभ", "₹120 की हानि"], "पहली का क्रय मूल्य = 1,200 ÷ 1.2 = ₹1,000; दूसरी का = 1,200 ÷ 0.8 = ₹1,500। कुल क्रय मूल्य ₹2,500 और कुल विक्रय मूल्य ₹2,400 है, अतः हानि ₹100।"]),
  q(3, "quant", "interest", "M", 2,
    ["In how many years will ₹8,000 amount to ₹9,200 at 5% per annum simple interest?", ["2 years", "4 years", "3 years", "2.5 years"], "Interest = 9,200 − 8,000 = 1,200. Interest per year = 8,000 x 5% = 400, so time = 1,200 ÷ 400 = 3 years."],
    ["साधारण ब्याज की 5% वार्षिक दर पर ₹8,000 कितने वर्षों में ₹9,200 हो जाएँगे?", ["2 वर्ष", "4 वर्ष", "3 वर्ष", "2.5 वर्ष"], "ब्याज = 9,200 − 8,000 = 1,200। प्रति वर्ष ब्याज = 8,000 x 5% = 400, अतः समय = 1,200 ÷ 400 = 3 वर्ष।"], "1200/400"),
  q(3, "quant", "interest", "H", 3,
    ["What is the difference between the compound interest and the simple interest on ₹5,000 for 2 years at 10% per annum?", ["₹25", "₹75", "₹100", "₹50"], "For 2 years the difference = P x (r/100)² = 5,000 x 0.01 = ₹50."],
    ["₹5,000 पर 10% वार्षिक दर से 2 वर्ष के चक्रवृद्धि ब्याज और साधारण ब्याज का अंतर क्या है?", ["₹25", "₹75", "₹100", "₹50"], "2 वर्ष के लिए अंतर = P x (r/100)² = 5,000 x 0.01 = ₹50।"], "5000*0.01"),
  q(3, "quant", "time-work", "H", 0,
    ["Pipe A can fill a tank in 12 hours and pipe B in 20 hours, while pipe C can empty the full tank in 30 hours. If all three are opened together, in how many hours will the tank be full?", ["10", "8", "12", "15"], "Net rate per hour = 1/12 + 1/20 − 1/30 = (5 + 3 − 2)/60 = 6/60 = 1/10. So the tank fills in 10 hours."],
    ["पाइप A एक टंकी को 12 घंटे में और पाइप B 20 घंटे में भर सकता है, जबकि पाइप C भरी टंकी को 30 घंटे में खाली कर सकता है। तीनों साथ खोलने पर टंकी कितने घंटे में भरेगी?", ["10", "8", "12", "15"], "प्रति घंटा शुद्ध दर = 1/12 + 1/20 − 1/30 = (5 + 3 − 2)/60 = 6/60 = 1/10। अतः टंकी 10 घंटे में भरेगी।"], "1/(1/12+1/20-1/30)"),
  q(3, "quant", "speed-distance", "M", 1,
    ["A train 180 m long is running at 72 km/h. How long will it take to cross a platform 220 m long?", ["18 seconds", "20 seconds", "22 seconds", "25 seconds"], "Speed = 72 x 5/18 = 20 m/s. Distance = 180 + 220 = 400 m, so time = 400 ÷ 20 = 20 seconds."],
    ["180 मी लंबी एक रेलगाड़ी 72 किमी/घंटा की चाल से चल रही है। 220 मी लंबे प्लेटफ़ॉर्म को पार करने में उसे कितना समय लगेगा?", ["18 सेकंड", "20 सेकंड", "22 सेकंड", "25 सेकंड"], "चाल = 72 x 5/18 = 20 मी/से। दूरी = 180 + 220 = 400 मी, अतः समय = 400 ÷ 20 = 20 सेकंड।"], "400/20"),
  q(3, "quant", "average", "M", 2,
    ["The average of five numbers is 27. If one number is removed, the average of the remaining four becomes 25. What is the number removed?", ["30", "32", "35", "37"], "Total of five = 135. Total of four = 100. Removed number = 135 − 100 = 35."],
    ["पाँच संख्याओं का औसत 27 है। एक संख्या हटाने पर शेष चार का औसत 25 हो जाता है। हटाई गई संख्या क्या है?", ["30", "32", "35", "37"], "पाँच का योग = 135। चार का योग = 100। हटाई गई संख्या = 135 − 100 = 35।"], "135-100"),
  q(3, "quant", "mixture-alligation", "H", 3,
    ["A mixture of 50 litres contains milk and water in the ratio 4 : 1. If 10 litres of water is added, what will be the new ratio of milk to water?", ["3 : 1", "4 : 3", "5 : 2", "2 : 1"], "Milk = 40 L and water = 10 L. After adding 10 L of water, water = 20 L. Ratio = 40 : 20 = 2 : 1."],
    ["50 लीटर के मिश्रण में दूध और पानी 4 : 1 के अनुपात में हैं। यदि 10 लीटर पानी मिलाया जाए, तो दूध और पानी का नया अनुपात क्या होगा?", ["3 : 1", "4 : 3", "5 : 2", "2 : 1"], "दूध = 40 ली और पानी = 10 ली। 10 ली पानी मिलाने पर पानी = 20 ली। अनुपात = 40 : 20 = 2 : 1।"]),
  q(3, "quant", "mensuration", "M", 0,
    ["The area of a circle is 154 cm². What is its circumference? (Take pi = 22/7)", ["44 cm", "22 cm", "88 cm", "66 cm"], "pi x r² = 154 gives r² = 49, so r = 7 cm. Circumference = 2 x 22/7 x 7 = 44 cm."],
    ["एक वृत्त का क्षेत्रफल 154 सेमी² है। उसकी परिधि क्या है? (pi = 22/7 लें)", ["44 सेमी", "22 सेमी", "88 सेमी", "66 सेमी"], "pi x r² = 154 से r² = 49, अतः r = 7 सेमी। परिधि = 2 x 22/7 x 7 = 44 सेमी।"], "44"),
  q(3, "quant", "number-system", "M", 1,
    ["What is the sum of the first 25 odd natural numbers?", ["525", "625", "650", "600"], "The sum of the first n odd numbers is n², so the sum is 25² = 625."],
    ["पहली 25 विषम प्राकृतिक संख्याओं का योग क्या है?", ["525", "625", "650", "600"], "पहली n विषम संख्याओं का योग n² होता है, अतः योग 25² = 625।"], "25*25"),
  q(3, "quant", "percentage", "M", 2,
    ["Find the value of 12.5% of 640 + 15% of 200.", ["100", "120", "110", "95"], "12.5% of 640 = 80 and 15% of 200 = 30. The sum = 110."],
    ["12.5% of 640 + 15% of 200 का मान ज्ञात कीजिए।", ["100", "120", "110", "95"], "640 का 12.5% = 80 और 200 का 15% = 30। योग = 110।"], "0.125*640+0.15*200"),
  q(3, "quant", "ages", "H", 3,
    ["A father is three times as old as his son. After 10 years he will be twice as old as his son. What is the present age of the son?", ["12 years", "15 years", "8 years", "10 years"], "Let the son be S. Then 3S + 10 = 2(S + 10), so S = 10 years."],
    ["एक पिता की आयु उसके पुत्र की आयु की तीन गुनी है। 10 वर्ष बाद वह पुत्र की आयु का दोगुना होगा। पुत्र की वर्तमान आयु क्या है?", ["12 वर्ष", "15 वर्ष", "8 वर्ष", "10 वर्ष"], "मान लें पुत्र की आयु S है। तब 3S + 10 = 2(S + 10), अतः S = 10 वर्ष।"], "10"),
  q(3, "quant", "hcf-lcm", "M", 0,
    ["Three bells ring at intervals of 12, 15 and 20 minutes. If they ring together at 9:00 am, when will they next ring together?", ["10:00 am", "9:30 am", "10:30 am", "11:00 am"], "LCM of 12, 15 and 20 = 60 minutes, so they ring together again after 1 hour, at 10:00 am."],
    ["तीन घंटियाँ 12, 15 और 20 मिनट के अंतराल पर बजती हैं। यदि वे सुबह 9:00 बजे एक साथ बजें, तो अगली बार एक साथ कब बजेंगी?", ["सुबह 10:00 बजे", "सुबह 9:30 बजे", "सुबह 10:30 बजे", "सुबह 11:00 बजे"], "12, 15 और 20 का LCM = 60 मिनट, अतः वे 1 घंटे बाद, सुबह 10:00 बजे फिर एक साथ बजेंगी।"]),
  q(3, "quant", "percentage", "H", 1,
    ["If 15% of a number is equal to 45% of 60, what is the number?", ["120", "180", "160", "200"], "45% of 60 = 27. So 15% of x = 27 and x = 27 ÷ 0.15 = 180."],
    ["यदि किसी संख्या का 15%, 60 के 45% के बराबर है, तो वह संख्या क्या है?", ["120", "180", "160", "200"], "60 का 45% = 27। अतः x का 15% = 27 और x = 27 ÷ 0.15 = 180।"], "27/0.15"),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "english", "grammar", "M", 2,
    ["Fill in the blank: 'Each of the players ___ given a medal.'", ["were", "are", "was", "have been"], "'Each' is singular and takes a singular verb: 'Each of the players was given a medal'."],
    ["रिक्त स्थान भरिए: 'Each of the players ___ given a medal.'", ["were", "are", "was", "have been"], "'Each' एकवचन है और एकवचन क्रिया लेता है: 'Each of the players was given a medal'।"]),
  q(4, "english", "grammar", "M", 3,
    ["Fill in the blank: 'He is senior ___ me in service.'", ["than", "from", "over", "to"], "Adjectives such as senior, junior, superior and inferior take 'to', not 'than'."],
    ["रिक्त स्थान भरिए: 'He is senior ___ me in service.'", ["than", "from", "over", "to"], "Senior, junior, superior और inferior जैसे विशेषणों के साथ 'than' नहीं, 'to' आता है।"]),
  q(4, "english", "synonyms-antonyms", "M", 0,
    ["Choose the synonym of 'ABUNDANT':", ["Plentiful","Scarce","Meagre","Rare"], "'Abundant' means existing in large quantities, which is plentiful. Scarce, meagre and rare are its opposites."],
    ["'ABUNDANT' का समानार्थी शब्द चुनिए:", ["Plentiful","Scarce","Meagre","Rare"], "'Abundant' का अर्थ है बहुतायत में उपलब्ध, यानी plentiful। Scarce, meagre और rare इसके विपरीत हैं।"]),
  q(4, "english", "synonyms-antonyms", "M", 1,
    ["Choose the antonym of 'SCARCE':", ["Rare", "Abundant", "Limited", "Meagre"], "'Scarce' means in short supply. Its opposite is 'abundant'."],
    ["'SCARCE' का विलोम शब्द चुनिए:", ["Rare", "Abundant", "Limited", "Meagre"], "'Scarce' का अर्थ है कम मात्रा में उपलब्ध। इसका विलोम 'abundant' (प्रचुर) है।"]),
  q(4, "english", "one-word", "H", 2,
    ["One word for 'a person who hates mankind':", ["Philanthropist","Misogynist","Misanthrope","Pessimist"], "A misanthrope dislikes or distrusts people in general. A philanthropist loves mankind and a misogynist hates women."],
    ["'मानवजाति से घृणा करने वाला व्यक्ति' के लिए एक शब्द:", ["Philanthropist","Misogynist","Misanthrope","Pessimist"], "Misanthrope सामान्यतः मनुष्यों से घृणा या अविश्वास रखता है। Philanthropist मानवता से प्रेम करता है और misogynist स्त्रियों से घृणा करता है।"]),
  q(4, "english", "idioms", "H", 3,
    ["Choose the meaning of the idiom 'to bite the bullet':", ["To shoot at someone", "To eat very fast", "To give up quickly", "To face a painful situation bravely"], "'To bite the bullet' means to endure a painful or unpleasant situation with courage."],
    ["मुहावरे 'to bite the bullet' का अर्थ चुनिए:", ["किसी पर गोली चलाना", "बहुत तेज़ खाना", "जल्दी हार मान लेना", "कष्टदायक स्थिति का साहस से सामना करना"], "'To bite the bullet' का अर्थ है किसी कष्टदायक या अप्रिय स्थिति को साहस से सहना।"]),
  q(4, "english", "spelling", "M", 0,
    ["Which spelling of the word meaning 'needed or required' is correct?", ["Necessary","Neccessary","Necesary","Necessery"], "'Necessary' has one c and two s: n-e-c-e-s-s-a-r-y."],
    ["'आवश्यक' अर्थ वाले शब्द की सही वर्तनी कौन-सी है?", ["Necessary","Neccessary","Necesary","Necessery"], "'Necessary' में एक c और दो s आते हैं: n-e-c-e-s-s-a-r-y।"]),
  q(4, "english", "voice-speech", "M", 1,
    ["Change into indirect speech: She said, \"I have finished my work.\"", ["She said that I had finished my work.","She said that she had finished her work.","She said that she has finished her work.","She said that she would finish her work."], "In indirect speech the present perfect 'have finished' changes to the past perfect 'had finished', and 'I' and 'my' become 'she' and 'her'."],
    ["अप्रत्यक्ष कथन में बदलिए: She said, \"I have finished my work.\"", ["She said that I had finished my work.","She said that she had finished her work.","She said that she has finished her work.","She said that she would finish her work."], "अप्रत्यक्ष कथन में present perfect 'have finished' बदलकर past perfect 'had finished' हो जाता है, और 'I' तथा 'my' क्रमशः 'she' और 'her' हो जाते हैं।"]),
  q(4, "hindi", "paryay-vilom", "M", 2,
    ["Which of these is NOT a synonym of 'सूर्य' (sun)?", ["दिनकर", "भास्कर", "शशि", "रवि"], "दिनकर, भास्कर and रवि all mean the sun. 'शशि' means the moon."],
    ["निम्नलिखित में से कौन-सा 'सूर्य' का पर्यायवाची नहीं है?", ["दिनकर", "भास्कर", "शशि", "रवि"], "दिनकर, भास्कर और रवि सूर्य के पर्यायवाची हैं। 'शशि' का अर्थ चंद्रमा है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Choose the antonym of the Hindi word 'उत्कर्ष' (rise, progress):", ["उन्नति", "प्रगति", "विकास", "अपकर्ष"], "The opposite of 'उत्कर्ष' (rise) is 'अपकर्ष' (decline). The other three mean progress."],
    ["'उत्कर्ष' शब्द का विलोम चुनिए:", ["उन्नति", "प्रगति", "विकास", "अपकर्ष"], "'उत्कर्ष' का विलोम 'अपकर्ष' है। अन्य तीनों उन्नति के अर्थ में हैं।"]),
  q(4, "hindi", "sandhi-samas", "H", 0,
    ["Choose the correct split of the sandhi word 'सदाचार':", ["सत् + आचार", "सदा + चार", "सद + आचार", "सत + चार"], "'सदाचार' = सत् + आचार. When 'त्' meets a vowel it changes to 'द्', which is a consonant (vyanjan) sandhi."],
    ["'सदाचार' का सही संधि-विच्छेद चुनिए:", ["सत् + आचार", "सदा + चार", "सद + आचार", "सत + चार"], "'सदाचार' = सत् + आचार। स्वर से मिलने पर 'त्' का 'द्' हो जाता है, यह व्यंजन संधि है।"]),
  q(4, "hindi", "shabdavali", "M", 1,
    ["Choose one word for 'जो आँखों के सामने हो' (that which is before the eyes):", ["परोक्ष", "प्रत्यक्ष", "अदृश्य", "सापेक्ष"], "'प्रत्यक्ष' means directly in front of the eyes. Its opposite is 'परोक्ष'."],
    ["'जो आँखों के सामने हो' के लिए एक शब्द चुनिए:", ["परोक्ष", "प्रत्यक्ष", "अदृश्य", "सापेक्ष"], "'प्रत्यक्ष' का अर्थ है आँखों के सामने। इसका विलोम 'परोक्ष' है।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["What is the meaning of the Hindi idiom 'आँखों का तारा'?", ["A star in the eyes", "An eye disease", "Very dear person", "A blind person"], "'आँखों का तारा' means someone very dear and beloved, usually a child."],
    ["मुहावरे 'आँखों का तारा' का अर्थ है:", ["आँखों में तारा", "आँखों की बीमारी", "अत्यंत प्रिय व्यक्ति", "अंधा व्यक्ति"], "'आँखों का तारा' का अर्थ है अत्यंत प्रिय व्यक्ति, प्रायः कोई बच्चा।"]),
  q(4, "hindi", "shabdavali", "H", 3,
    ["What is the tatsam form of the tadbhav word 'हाथ'?", ["हस्ती", "हथेली", "भुजा", "हस्त"], "'हाथ' is the tadbhav form of the Sanskrit tatsam word 'हस्त'."],
    ["तद्भव शब्द 'हाथ' का तत्सम रूप क्या है?", ["हस्ती", "हथेली", "भुजा", "हस्त"], "'हाथ' संस्कृत के तत्सम शब्द 'हस्त' का तद्भव रूप है।"]),
  q(4, "hindi", "vyakaran", "H", 0,
    ["Which of these words is masculine in gender?", ["दही", "रोटी", "चटनी", "कुर्सी"], "'दही' is masculine (यह दही खट्टा है). रोटी, चटनी and कुर्सी are feminine."],
    ["निम्नलिखित में से कौन-सा शब्द पुल्लिंग है?", ["दही", "रोटी", "चटनी", "कुर्सी"], "'दही' पुल्लिंग है (दही खट्टा है)। रोटी, चटनी और कुर्सी स्त्रीलिंग हैं।"]),
];
