// HP Police Constable Full Mock 6 — 100 questions (25 HP GK, 25 GK, 20 Reasoning, 15 Maths, 15 Hindi/English).
// Emphasis: HP history, temples and culture, polity, police-related law, Indian polity.

import { q, type PoliceQuestion } from "./types";

export const mock6: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK (25) ─────────
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Bhimakali temple at Sarahan in Shimla district was the family deity of the rulers of which former princely state?", ["Keonthal","Sirmaur","Bushahr","Jubbal"], "Sarahan was an early seat of the Bushahr rulers, and the Bhimakali temple was their family deity. The temple is a fine example of Himachali wood-and-stone architecture."],
    ["शिमला जिले के सराहन में स्थित भीमाकाली मंदिर किस पूर्व रियासत के शासकों की कुलदेवी का मंदिर था?", ["क्योंथल","सिरमौर","बुशहर","जुब्बल"], "सराहन बुशहर के शासकों का एक प्रारंभिक केंद्र था और भीमाकाली मंदिर उनकी कुलदेवी का मंदिर था। यह मंदिर हिमाचली काष्ठ-पत्थर स्थापत्य का सुंदर उदाहरण है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The wooden Hidimba Devi temple at Manali, built in 1553 amid a cedar forest at Dhungri, was constructed by Raja:", ["Jagat Singh","Bidhi Singh","Man Singh","Bahadur Singh"], "The temple, dedicated to Hidimba (wife of Bhima), was built in 1553 by Raja Bahadur Singh of Kullu."],
    ["मनाली में ढुंगरी के देवदार वन के बीच 1553 में बना काष्ठ का हिडिंबा देवी मंदिर किस राजा ने बनवाया?", ["जगत सिंह","बिधि सिंह","मान सिंह","बहादुर सिंह"], "भीम की पत्नी हिडिंबा को समर्पित इस मंदिर का निर्माण कुल्लू के राजा बहादुर सिंह ने 1553 में करवाया।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The ancient Baijnath (Vaidyanath) Shiva temple in Kangra district was built in 1204 CE by which two brothers?", ["Ahuka and Manyuka","Sahil Varman and Yugakar Varman","Sansar Chand and Anirudh Chand","Ajbar Sen and Sidh Sen"], "Two local merchant brothers, Ahuka and Manyuka, built the Nagara-style temple in 1204. Sanskrit inscriptions on its walls record this. The old name of the place was Kiragrama."],
    ["कांगड़ा जिले का प्राचीन बैजनाथ (वैद्यनाथ) शिव मंदिर 1204 ई. में किन दो भाइयों ने बनवाया?", ["अहुका और मन्युका","साहिल वर्मन और युगाकर वर्मन","संसार चंद और अनिरुद्ध चंद","अजबर सेन और सिद्ध सेन"], "स्थानीय व्यापारी भाइयों अहुका और मन्युका ने 1204 में नागर शैली का यह मंदिर बनवाया। दीवारों पर संस्कृत शिलालेख इसका उल्लेख करते हैं। इस स्थान का पुराना नाम कीरग्राम था।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["The monolithic rock-cut Masroor temples, sometimes called the 'Ellora of Himachal', are in which district?", ["Chamba","Kangra","Mandi","Sirmaur"], "Masroor, near Lunj in Kangra district, has a group of about 15 Nagara-style temples carved out of a single sandstone ridge, dated to around the 8th century."],
    ["एकाश्म चट्टान को काटकर बने मसरूर मंदिर, जिन्हें कभी-कभी 'हिमाचल का एलोरा' कहा जाता है, किस जिले में हैं?", ["चंबा","कांगड़ा","मंडी","सिरमौर"], "कांगड़ा जिले में लुंज के पास मसरूर में लगभग 15 नागर शैली के मंदिरों का समूह है, जो एक ही बलुआ पत्थर की चट्टान को काटकर बने हैं और लगभग 8वीं शताब्दी के माने जाते हैं।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["The Lakshmi Narayan group of temples at Chamba town was built during the reign of Raja:", ["Umed Singh","Bhuri Singh","Sahil Varman","Jagat Singh"], "Raja Sahil (Sahila) Varman, who founded Chamba town in about 920 CE, built the Lakshmi Narayan temples there. The earlier capital of the state was Brahmapura (Bharmour)."],
    ["चंबा नगर में लक्ष्मी नारायण मंदिर समूह किस राजा के शासनकाल में बना?", ["उमेद सिंह","भूरी सिंह","साहिल वर्मन","जगत सिंह"], "लगभग 920 ई. में चंबा नगर की स्थापना करने वाले राजा साहिल (साहिला) वर्मन ने यहाँ लक्ष्मी नारायण मंदिर बनवाए। राज्य की पहले की राजधानी ब्रह्मपुरा (भरमौर) थी।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["Manimahesh Lake, sacred to Lord Shiva and the site of an annual pilgrimage after Janmashtami, is near which town of Chamba district?", ["Dalhousie","Tissa","Killar","Bharmour"], "Manimahesh Lake lies at about 4,000 m, beneath the Manimahesh Kailash peak, near Bharmour. The yatra runs from Janmashtami to Radhashtami."],
    ["भगवान शिव को समर्पित मणिमहेश झील, जहाँ जन्माष्टमी के बाद वार्षिक यात्रा होती है, चंबा जिले के किस नगर के पास है?", ["डलहौज़ी","तिस्सा","किलाड़","भरमौर"], "मणिमहेश झील लगभग 4,000 मी की ऊँचाई पर मणिमहेश कैलाश शिखर के नीचे भरमौर के पास है। यात्रा जन्माष्टमी से राधाष्टमी तक चलती है।"]),
  q(0, "hp-gk", "polity-administration", "M", 0,
    ["The Himachal Pradesh Panchayati Raj Act, which set up the three-tier panchayat system in line with the 73rd Constitutional Amendment, was enacted in:", ["1994","1992","1996","2000"], "The HP Panchayati Raj Act, 1994 provides for the Gram Panchayat, Panchayat Samiti and Zila Parishad."],
    ["73वें संविधान संशोधन के अनुरूप त्रि-स्तरीय पंचायती व्यवस्था बनाने वाला हिमाचल प्रदेश पंचायती राज अधिनियम कब बना?", ["1994","1992","1996","2000"], "हिमाचल प्रदेश पंचायती राज अधिनियम, 1994 में ग्राम पंचायत, पंचायत समिति और ज़िला परिषद की व्यवस्था है।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["Full statehood was announced for Himachal Pradesh at a ceremony at the Ridge, Shimla, on 25 January 1971 by Prime Minister:", ["Lal Bahadur Shastri","Indira Gandhi","Morarji Desai","Jawaharlal Nehru"], "Under the State of Himachal Pradesh Act, 1970, Himachal became the 18th state of India. Prime Minister Indira Gandhi announced the statehood at the Ridge on 25 January 1971."],
    ["25 जनवरी 1971 को शिमला के रिज पर आयोजित समारोह में हिमाचल प्रदेश को पूर्ण राज्य का दर्जा देने की घोषणा किस प्रधानमंत्री ने की?", ["लाल बहादुर शास्त्री","इंदिरा गांधी","मोरारजी देसाई","जवाहरलाल नेहरू"], "हिमाचल प्रदेश राज्य अधिनियम, 1970 के तहत हिमाचल भारत का 18वाँ राज्य बना। प्रधानमंत्री इंदिरा गांधी ने 25 जनवरी 1971 को रिज पर इसकी घोषणा की।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["The devastating Kangra earthquake, which badly damaged Kangra, Dharamshala and the Bajreshwari temple, occurred in:", ["1897","1934","1905","1950"], "The earthquake struck on 4 April 1905 and killed about 20,000 people. The Bajreshwari Devi temple at Kangra was destroyed and later rebuilt."],
    ["विनाशकारी कांगड़ा भूकंप, जिसने कांगड़ा, धर्मशाला और बज्रेश्वरी मंदिर को भारी क्षति पहुँचाई, कब आया?", ["1897","1934","1905","1950"], "यह भूकंप 4 अप्रैल 1905 को आया और लगभग 20,000 लोगों की मृत्यु हुई। कांगड़ा का बज्रेश्वरी देवी मंदिर नष्ट हो गया था और बाद में पुनर्निर्मित हुआ।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["Sansar Chand of Kangra sought help against the Gurkha siege, and the Kangra Fort passed to the Sikhs in 1809 under:", ["Banda Singh Bahadur","Maharaja Duleep Singh","Raja Gulab Singh","Maharaja Ranjit Singh"], "The Gurkhas under Amar Singh Thapa besieged Kangra from 1806. Sansar Chand asked Ranjit Singh for help; the Sikhs defeated the Gurkhas but took the fort in 1809."],
    ["गोरखा घेराबंदी के विरुद्ध कांगड़ा के संसार चंद ने सहायता माँगी और 1809 में कांगड़ा क़िला किसके अधीन सिखों के हाथ में आ गया?", ["बंदा सिंह बहादुर","महाराजा दलीप सिंह","राजा गुलाब सिंह","महाराजा रणजीत सिंह"], "अमर सिंह थापा के नेतृत्व में गोरखों ने 1806 से कांगड़ा को घेर रखा था। संसार चंद ने रणजीत सिंह से सहायता माँगी; सिखों ने गोरखों को हराया पर 1809 में क़िला अपने अधीन कर लिया।"]),
  q(0, "hp-gk", "history", "H", 0,
    ["In May 1815, the Gurkha commander Amar Singh Thapa surrendered to General Ochterlony at which fort, ending Gurkha rule in the hills?", ["Malaun","Kangra","Arki","Sabathu"], "Amar Singh Thapa surrendered at Malaun fort. The Anglo-Gorkha war ended with the Treaty of Sugauli, and the British took control of the Shimla hill states."],
    ["मई 1815 में गोरखा सेनापति अमर सिंह थापा ने जनरल ऑक्टरलोनी के सामने किस क़िले में आत्मसमर्पण किया, जिससे पहाड़ों में गोरखा शासन समाप्त हुआ?", ["मलौन","कांगड़ा","अर्की","सबाथू"], "अमर सिंह थापा ने मलौन क़िले में आत्मसमर्पण किया। आंग्ल-गोरखा युद्ध सुगौली की संधि से समाप्त हुआ और शिमला की पहाड़ी रियासतों पर अंग्रेज़ों का नियंत्रण हो गया।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["Shimla was formally made the summer capital of British India in the year:", ["1830","1864","1876","1911"], "Viceroy Sir John Lawrence moved the government to Shimla in the summer of 1864, and it was declared the summer capital of the British Indian government."],
    ["शिमला को औपचारिक रूप से ब्रिटिश भारत की ग्रीष्मकालीन राजधानी किस वर्ष बनाया गया?", ["1830","1864","1876","1911"], "वायसराय सर जॉन लॉरेंस ने 1864 की गर्मियों में सरकार शिमला स्थानांतरित की और इसे ब्रिटिश भारतीय सरकार की ग्रीष्मकालीन राजधानी घोषित किया गया।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["The Kalka-Shimla narrow-gauge railway, a UNESCO World Heritage Site since 2008, was opened to traffic in:", ["1864","1911","1903","1925"], "The line, about 96 km long, was opened on 9 November 1903. It was inscribed with the Mountain Railways of India in 2008."],
    ["कालका-शिमला नैरो-गेज रेलवे, जो 2008 से यूनेस्को विश्व धरोहर है, किस वर्ष यातायात के लिए खोली गई?", ["1864","1911","1903","1925"], "लगभग 96 किमी लंबी यह लाइन 9 नवंबर 1903 को खोली गई। 2008 में इसे भारत की पर्वतीय रेलों के साथ विश्व धरोहर में शामिल किया गया।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["The town of Mandi on the Beas was founded in 1527 by Raja:", ["Sidh Sen","Ishwari Sen","Balbir Sen","Ajbar Sen"], "Ajbar Sen founded Mandi town on the Beas in 1527. Later rulers such as Sidh Sen expanded the state."],
    ["ब्यास के तट पर बसे मंडी नगर की स्थापना 1527 में किस राजा ने की?", ["सिद्ध सेन","ईश्वरी सेन","बलबीर सेन","अजबर सेन"], "अजबर सेन ने 1527 में ब्यास के तट पर मंडी नगर बसाया। बाद में सिद्ध सेन जैसे शासकों ने राज्य का विस्तार किया।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The Phulaich (Ukhyang) festival, in which people gather wild flowers from the high pastures, is celebrated in:", ["Kinnaur","Chamba","Kullu","Sirmaur"], "Phulaich, also called Ukhyang, is the 'festival of flowers' of Kinnaur, held around September when villagers bring flowers from the high pastures to offer to the deities."],
    ["फुलैच (उखयांग) उत्सव, जिसमें लोग ऊँचे चरागाहों से जंगली फूल लाते हैं, कहाँ मनाया जाता है?", ["किन्नौर","चंबा","कुल्लू","सिरमौर"], "फुलैच, जिसे उखयांग भी कहते हैं, किन्नौर का 'फूलों का त्योहार' है। यह लगभग सितंबर में मनाया जाता है, जब ग्रामीण ऊँचे चरागाहों से फूल लाकर देवताओं को चढ़ाते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["In the grand 'Jaleb' procession of the Mandi Shivratri fair, which deity of the former Mandi state is carried at the head?", ["Raghunath","Madho Rai","Hidimba","Jamlu"], "Madho Rai, a form of Vishnu regarded as the presiding deity of the former Mandi state, leads the Jaleb procession, followed by hundreds of local deities."],
    ["मंडी शिवरात्रि मेले की भव्य 'जलेब' शोभायात्रा में मंडी रियासत के किस देवता को सबसे आगे रखा जाता है?", ["रघुनाथ","माधो राय","हिडिंबा","जमलू"], "विष्णु का रूप माने जाने वाले और पूर्व मंडी रियासत के अधिष्ठाता देवता माधो राय जलेब का नेतृत्व करते हैं, उनके पीछे सैकड़ों स्थानीय देवता चलते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Renuka fair, held every November on the shore of Renuka lake in honour of Parshuram and his mother, is in which district?", ["Solan","Bilaspur","Sirmaur","Una"], "The Renuka fair is held around Kartik Ekadashi at Renuka ji in Sirmaur district, commemorating the yearly visit of Parshuram to his mother Renuka."],
    ["परशुराम और उनकी माता के सम्मान में हर नवंबर रेणुका झील के किनारे लगने वाला रेणुका मेला किस जिले में है?", ["सोलन","बिलासपुर","सिरमौर","ऊना"], "रेणुका मेला सिरमौर जिले के रेणुका जी में कार्तिक एकादशी के आसपास लगता है, जो परशुराम के अपनी माता रेणुका से वार्षिक मिलन की स्मृति में है।"]),
  q(0, "hp-gk", "history", "M", 3,
    ["Sansar Chand, the last great Katoch ruler of Kangra, held court at which town on the Beas and patronised the Kangra school of painting?", ["Dharamshala","Palampur","Jawalamukhi","Sujanpur Tira"], "Sansar Chand (ruled from 1775) made Sujanpur Tira his capital and patron of Pahari (Kangra) painting. The Holi fair of Sujanpur is a well-known fair today."],
    ["कांगड़ा के अंतिम महान कटोच शासक संसार चंद ने ब्यास के किस नगर में दरबार लगाया और कांगड़ा चित्रकला को संरक्षण दिया?", ["धर्मशाला","पालमपुर","ज्वालामुखी","सुजानपुर टीहरा"], "संसार चंद (1775 से शासक) ने सुजानपुर टीहरा को अपना केंद्र बनाया और पहाड़ी (कांगड़ा) चित्रकला को संरक्षण दिया। सुजानपुर का होली मेला आज भी प्रसिद्ध है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Brij Raj Swami temple, where Krishna and Meera Bai are worshipped together, stands inside the fort of:", ["Nurpur","Kangra","Guler","Chamba"], "The temple within the Nurpur fort in Kangra district is known for the joint worship of Krishna and Meera Bai. Nurpur was the capital of the Pathania rulers."],
    ["ब्रिज राज स्वामी मंदिर, जहाँ कृष्ण और मीरा बाई की एक साथ पूजा होती है, किस क़िले के भीतर है?", ["नूरपुर","कांगड़ा","गुलेर","चंबा"], "कांगड़ा जिले के नूरपुर क़िले में स्थित यह मंदिर कृष्ण और मीरा बाई की संयुक्त पूजा के लिए प्रसिद्ध है। नूरपुर पठानिया शासकों की राजधानी थी।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["Gurudwara Paonta Sahib, where Guru Gobind Singh stayed for about four years, stands on the bank of which river?", ["Sutlej","Yamuna","Beas","Giri"], "Paonta Sahib in Sirmaur district lies on the Yamuna. Guru Gobind Singh stayed there for about four years and composed part of his literary work."],
    ["गुरुद्वारा पांवटा साहिब, जहाँ गुरु गोबिंद सिंह लगभग चार वर्ष रहे, किस नदी के तट पर है?", ["सतलुज","यमुना","ब्यास","गिरि"], "सिरमौर जिले का पांवटा साहिब यमुना के तट पर है। गुरु गोबिंद सिंह यहाँ लगभग चार वर्ष रहे और अपनी रचनाओं का कुछ भाग यहीं लिखा।"]),
  q(0, "hp-gk", "polity-administration", "E", 2,
    ["Which single emergency number connects a caller to the police, fire and ambulance services under the ERSS, including in Himachal Pradesh?", ["100","108","112","1090"], "ERSS (Emergency Response Support System) uses the single number 112. Earlier separate numbers were 100 (police), 101 (fire) and 108 (ambulance)."],
    ["ERSS के अंतर्गत, हिमाचल प्रदेश सहित, कौन-सा एकल आपातकालीन नंबर पुलिस, अग्निशमन और एम्बुलेंस सेवाओं से जोड़ता है?", ["100","108","112","1090"], "ERSS (आपातकालीन प्रतिक्रिया सहायता प्रणाली) एकल नंबर 112 का प्रयोग करती है। पहले अलग-अलग नंबर थे: 100 (पुलिस), 101 (अग्निशमन) और 108 (एम्बुलेंस)।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The 'Dohru', a long woollen wrap pinned at the shoulders, is the traditional dress of women of which district?", ["Kullu","Chamba","Sirmaur","Kinnaur"], "The dohru is a rectangular woollen wrap worn by Kinnauri women, usually with a Kinnauri cap. Kullu women wear the 'pattu'."],
    ["कंधों पर पिन से टिकाया जाने वाला लंबा ऊनी 'दोहरू' किस जिले की महिलाओं का परंपरागत परिधान है?", ["कुल्लू","चंबा","सिरमौर","किन्नौर"], "दोहरू आयताकार ऊनी वस्त्र है जिसे किन्नौरी महिलाएँ पहनती हैं, प्रायः किन्नौरी टोपी के साथ। कुल्लू की महिलाएँ 'पट्टू' पहनती हैं।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The 'Ransingha', played in temple and deity processions of Himachal, is a:", ["Curved brass horn (wind instrument)","Drum played with sticks","String instrument","Pair of small hand cymbals"], "The ransingha is a crescent-shaped brass horn blown during fairs and deity processions, along with the karnal, nagara and shehnai."],
    ["हिमाचल में मंदिर और देव-यात्राओं में बजाया जाने वाला 'रणसिंघा' क्या है?", ["मुड़ा हुआ पीतल का सींगनुमा वाद्य (फूँककर बजाने वाला)","डंडों से बजने वाला ढोल","तार वाद्य","छोटे झाँझ की जोड़ी"], "रणसिंघा अर्धचंद्राकार पीतल का सींगनुमा वाद्य है जो मेलों और देव-यात्राओं में करनाल, नगाड़ा और शहनाई के साथ बजाया जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The Tabo Monastery in Spiti, famous for its ancient wall paintings, was founded in 996 CE by:", ["Padmasambhava","Rinchen Zangpo","Atisha","Tsongkhapa"], "The Tibetan 'great translator' Rinchen Zangpo founded Tabo in 996 CE. It is one of the oldest continuously functioning Buddhist monasteries in India."],
    ["स्पीति का ताबो मठ, जो अपने प्राचीन भित्ति-चित्रों के लिए प्रसिद्ध है, 996 ई. में किसने स्थापित किया?", ["पद्मसंभव","रिनचेन ज़ंगपो","अतिश","त्सोंगखापा"], "तिब्बती 'महान अनुवादक' रिनचेन ज़ंगपो ने 996 ई. में ताबो की स्थापना की। यह भारत के सबसे पुराने निरंतर चल रहे बौद्ध मठों में से एक है।"]),
  q(0, "hp-gk", "polity-administration", "H", 2,
    ["Under the Constitution, who appoints the Advocate General of Himachal Pradesh?", ["The Chief Justice of the High Court","The Chief Minister","The Governor","The President"], "Under Article 165 the Governor appoints the Advocate General of a State, a person qualified to be a High Court judge. He holds office during the Governor's pleasure."],
    ["संविधान के अनुसार हिमाचल प्रदेश के महाधिवक्ता (Advocate General) की नियुक्ति कौन करता है?", ["उच्च न्यायालय के मुख्य न्यायाधीश","मुख्यमंत्री","राज्यपाल","राष्ट्रपति"], "अनुच्छेद 165 के अंतर्गत राज्यपाल राज्य के महाधिवक्ता को नियुक्त करते हैं, जो उच्च न्यायालय का न्यायाधीश बनने की योग्यता रखता हो। वह राज्यपाल के प्रसादपर्यंत पद धारण करता है।"]),

  // ───────── Section 1: General Knowledge (25) ─────────
  q(1, "general-studies", "indian-polity", "M", 3,
    ["Anticipatory bail is sought by a person who:", ["Has already been convicted and wants a lesser sentence","Wants earlier bail to be cancelled","Wants his case moved to another court","Apprehends arrest for a non-bailable offence and wants protection in advance"], "Anticipatory bail is granted by the Sessions Court or High Court so that a person who fears arrest for a non-bailable offence is released on bail if arrested (Section 438 of the old CrPC)."],
    ["अग्रिम जमानत (anticipatory bail) वह व्यक्ति माँगता है जो:", ["दोषसिद्ध हो चुका है और कम सज़ा चाहता है","पहले मिली ज़मानत रद्द कराना चाहता है","अपना मुक़दमा दूसरे न्यायालय में स्थानांतरित कराना चाहता है","गैर-ज़मानती अपराध में गिरफ़्तारी की आशंका होने पर पहले से संरक्षण चाहता है"], "गैर-ज़मानती अपराध में गिरफ़्तारी की आशंका वाले व्यक्ति को सत्र न्यायालय या उच्च न्यायालय अग्रिम जमानत देता है, ताकि गिरफ़्तारी होने पर उसे ज़मानत पर छोड़ दिया जाए (पुरानी CrPC की धारा 438)।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["Article 20(1) of the Constitution protects a person from:", ["Being arrested without a warrant","Being tried twice for the same offence","Being convicted under a law that was not in force when the act was done","Being detained for more than 24 hours"], "Article 20(1) bars ex post facto criminal laws: no one can be convicted for an act that was not an offence when it was done, or given a heavier penalty than the law then allowed. Protection against double jeopardy is Article 20(2)."],
    ["संविधान का अनुच्छेद 20(1) किस बात से संरक्षण देता है?", ["बिना वारंट गिरफ़्तारी से","एक ही अपराध के लिए दो बार मुक़दमे से","ऐसे कानून के अंतर्गत दोषसिद्धि से जो कार्य करते समय लागू नहीं था","24 घंटे से अधिक समय तक निरोध से"], "अनुच्छेद 20(1) भूतलक्षी दांडिक कानूनों को रोकता है: किसी कार्य के लिए, जो करते समय अपराध नहीं था, दोषसिद्धि नहीं हो सकती और न ही तब के कानून से अधिक दंड दिया जा सकता है। दोहरे दंड से संरक्षण अनुच्छेद 20(2) है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["The Right to Education for children aged 6 to 14 years was made a Fundamental Right under Article 21A by the:", ["86th Amendment, 2002","42nd Amendment, 1976","44th Amendment, 1978","73rd Amendment, 1992"], "The 86th Constitutional Amendment Act, 2002 inserted Article 21A. The Right of Children to Free and Compulsory Education Act, 2009 (RTE) came into force in 2010."],
    ["6 से 14 वर्ष के बच्चों की शिक्षा का अधिकार अनुच्छेद 21A के अंतर्गत मौलिक अधिकार किस संशोधन से बना?", ["86वाँ संशोधन, 2002","42वाँ संशोधन, 1976","44वाँ संशोधन, 1978","73वाँ संशोधन, 1992"], "86वें संविधान संशोधन अधिनियम, 2002 ने अनुच्छेद 21A जोड़ा। निःशुल्क और अनिवार्य बाल शिक्षा का अधिकार अधिनियम, 2009 (RTE) 2010 में लागू हुआ।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Dr B.R. Ambedkar described which Article as 'the very soul of the Constitution and the very heart of it'?", ["Article 14","Article 32","Article 21","Article 368"], "Article 32 gives the right to move the Supreme Court for enforcement of Fundamental Rights, which is why Ambedkar called it the heart and soul of the Constitution."],
    ["डॉ. बी.आर. अम्बेडकर ने किस अनुच्छेद को 'संविधान की आत्मा और हृदय' कहा?", ["अनुच्छेद 14","अनुच्छेद 32","अनुच्छेद 21","अनुच्छेद 368"], "अनुच्छेद 32 मौलिक अधिकारों के प्रवर्तन के लिए सर्वोच्च न्यायालय जाने का अधिकार देता है, इसीलिए अम्बेडकर ने इसे संविधान का हृदय और आत्मा कहा।"]),
  q(1, "general-studies", "indian-polity", "E", 3,
    ["Untouchability is abolished and its practice in any form is forbidden by which Article?", ["Article 15","Article 16","Article 18","Article 17"], "Article 17 abolishes untouchability. The Protection of Civil Rights Act, 1955 punishes its practice."],
    ["अस्पृश्यता का अंत और उसका किसी भी रूप में आचरण किस अनुच्छेद द्वारा निषिद्ध है?", ["अनुच्छेद 15","अनुच्छेद 16","अनुच्छेद 18","अनुच्छेद 17"], "अनुच्छेद 17 अस्पृश्यता का अंत करता है। नागरिक अधिकार संरक्षण अधिनियम, 1955 इसके आचरण को दंडनीय बनाता है।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["Once approved by Parliament, a Proclamation of President's Rule under Article 356 initially continues for a period of:", ["Three months","One year","Six months","Two years"], "After approval by both Houses within two months, President's Rule lasts six months and can be extended in six-month steps up to a maximum of three years under the stated conditions."],
    ["संसद की स्वीकृति के बाद अनुच्छेद 356 के अधीन राष्ट्रपति शासन की उद्घोषणा प्रारंभ में कितनी अवधि तक चलती है?", ["तीन माह","एक वर्ष","छह माह","दो वर्ष"], "दोनों सदनों द्वारा दो माह के भीतर स्वीकृति के बाद राष्ट्रपति शासन छह माह चलता है और निर्धारित शर्तों के अधीन छह-छह माह बढ़ाकर अधिकतम तीन वर्ष तक जा सकता है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["In case of a deadlock between the two Houses over an ordinary Bill, the joint sitting of Parliament is presided over by:", ["The Speaker of the Lok Sabha","The Vice-President","The President","The Chairman of the Rajya Sabha"], "Under Article 108 the Speaker presides over a joint sitting; in his absence, the Deputy Speaker does. The Chairman of the Rajya Sabha never presides."],
    ["साधारण विधेयक पर दोनों सदनों के गतिरोध की स्थिति में संसद की संयुक्त बैठक की अध्यक्षता कौन करता है?", ["लोकसभा अध्यक्ष","उपराष्ट्रपति","राष्ट्रपति","राज्यसभा के सभापति"], "अनुच्छेद 108 के अनुसार संयुक्त बैठक की अध्यक्षता लोकसभा अध्यक्ष करता है; उसकी अनुपस्थिति में उपाध्यक्ष। राज्यसभा का सभापति कभी अध्यक्षता नहीं करता।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["The superintendence, direction and control of elections to Parliament and State Legislatures is vested in the Election Commission under Article:", ["315","324","280","148"], "Article 324 vests this power in the Election Commission of India. Article 315 relates to Public Service Commissions and Article 148 to the CAG."],
    ["संसद और राज्य विधानमंडलों के चुनावों का अधीक्षण, निर्देशन और नियंत्रण किस अनुच्छेद के अंतर्गत निर्वाचन आयोग में निहित है?", ["315","324","280","148"], "अनुच्छेद 324 यह शक्ति भारत निर्वाचन आयोग में निहित करता है। अनुच्छेद 315 लोक सेवा आयोगों और अनुच्छेद 148 नियंत्रक-महालेखा परीक्षक से संबंधित है।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["The Lokpal and Lokayuktas Act, which provides for an anti-corruption ombudsman at the Centre, was passed in:", ["2005","2009","2016","2013"], "The Act was passed in 2013 and received the President's assent in January 2014. Justice Pinaki Chandra Ghose was appointed the first Lokpal chairperson in 2019."],
    ["केंद्र में भ्रष्टाचार-निरोधी लोकपाल की व्यवस्था करने वाला लोकपाल और लोकायुक्त अधिनियम कब पारित हुआ?", ["2005","2009","2016","2013"], "यह अधिनियम 2013 में पारित हुआ और जनवरी 2014 में राष्ट्रपति की स्वीकृति मिली। न्यायमूर्ति पिनाकी चंद्र घोष 2019 में पहले लोकपाल अध्यक्ष नियुक्त हुए।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["In its 2006 judgment in the Prakash Singh case, the Supreme Court gave directions mainly on:", ["Electoral reforms","Judicial appointments","Police reforms","Prison reforms"], "The Supreme Court directed states to set up a State Security Commission, fix minimum tenure for the DGP and separate investigation from law and order, among other reforms."],
    ["प्रकाश सिंह मामले (2006) में सर्वोच्च न्यायालय ने मुख्यतः किस विषय पर निर्देश दिए?", ["चुनाव सुधार","न्यायाधीशों की नियुक्ति","पुलिस सुधार","कारागार सुधार"], "सर्वोच्च न्यायालय ने राज्यों को राज्य सुरक्षा आयोग बनाने, पुलिस महानिदेशक का न्यूनतम कार्यकाल तय करने और जाँच को कानून-व्यवस्था से अलग करने जैसे निर्देश दिए।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["The Protection of Children from Sexual Offences (POCSO) Act was enacted in the year:", ["2012","2005","2009","2015"], "The POCSO Act, 2012 protects children below 18 years from sexual assault, harassment and pornography and provides for special courts."],
    ["यौन अपराधों से बालकों का संरक्षण अधिनियम (POCSO) किस वर्ष अधिनियमित हुआ?", ["2012","2005","2009","2015"], "POCSO अधिनियम, 2012 18 वर्ष से कम आयु के बच्चों को यौन उत्पीड़न, छेड़छाड़ और अश्लील सामग्री से बचाता है और विशेष न्यायालयों की व्यवस्था करता है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["The Narcotic Drugs and Psychotropic Substances (NDPS) Act, which police enforce against drug trafficking, was enacted in:", ["1961","1985","1978","1999"], "The NDPS Act was passed in 1985 and has been amended several times, most notably in 1989 and 2001."],
    ["मादक पदार्थ एवं मनःप्रभावी पदार्थ (NDPS) अधिनियम, जिसे पुलिस मादक पदार्थों की तस्करी के विरुद्ध लागू करती है, कब बना?", ["1961","1985","1978","1999"], "NDPS अधिनियम 1985 में बना और इसमें कई संशोधन हुए, जिनमें 1989 और 2001 प्रमुख हैं।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["The Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act was enacted in the year:", ["1955","1976","2005","1989"], "The SC/ST (Prevention of Atrocities) Act, 1989 defines atrocities against SC/ST members and provides for special courts and relief."],
    ["अनुसूचित जाति और अनुसूचित जनजाति (अत्याचार निवारण) अधिनियम किस वर्ष बना?", ["1955","1976","2005","1989"], "SC/ST (अत्याचार निवारण) अधिनियम, 1989 अनुसूचित जाति और जनजाति के सदस्यों के विरुद्ध अत्याचारों को परिभाषित करता है तथा विशेष न्यायालय और राहत की व्यवस्था करता है।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["The Battle of Buxar (1764), which made the East India Company the real power in north India, was fought against the combined forces of:", ["Siraj-ud-Daulah and the French","Tipu Sultan and the Nizam","Mir Qasim, Shuja-ud-Daula and Shah Alam II","Hyder Ali and the Marathas"], "The British under Hector Munro defeated Mir Qasim, Shuja-ud-Daula of Awadh and the Mughal emperor Shah Alam II. The Treaty of Allahabad (1765) then gave the Company the diwani of Bengal."],
    ["बक्सर का युद्ध (1764), जिसने ईस्ट इंडिया कंपनी को उत्तर भारत की वास्तविक शक्ति बना दिया, किनकी संयुक्त सेना के विरुद्ध लड़ा गया?", ["सिराजुद्दौला और फ़्रांसीसी","टीपू सुल्तान और निज़ाम","मीर क़ासिम, शुजाउद्दौला और शाह आलम द्वितीय","हैदर अली और मराठे"], "हेक्टर मुनरो के नेतृत्व में अंग्रेज़ों ने मीर क़ासिम, अवध के शुजाउद्दौला और मुग़ल सम्राट शाह आलम द्वितीय को हराया। इलाहाबाद की संधि (1765) से कंपनी को बंगाल की दीवानी मिली।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["The famous 'Great Bath', a water tank of the Indus Valley Civilization, was found at:", ["Mohenjodaro","Harappa","Lothal","Kalibangan"], "The Great Bath was excavated at Mohenjodaro (Sindh, now in Pakistan), probably used for ritual bathing. Lothal is known for its dockyard."],
    ["सिंधु घाटी सभ्यता का प्रसिद्ध 'विशाल स्नानागार' कहाँ मिला?", ["मोहनजोदड़ो","हड़प्पा","लोथल","कालीबंगा"], "विशाल स्नानागार की खुदाई मोहनजोदड़ो (सिंध, अब पाकिस्तान में) में हुई, जिसका प्रयोग संभवतः धार्मिक स्नान के लिए होता था। लोथल अपने गोदी-बाड़े के लिए प्रसिद्ध है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Which Indian river is known as the 'Sorrow of Bihar' because of its frequent floods?", ["Gandak","Kosi","Son","Bagmati"], "The Kosi, which changes course frequently and carries heavy silt from Nepal, is called the 'Sorrow of Bihar'."],
    ["किस भारतीय नदी को बार-बार आने वाली बाढ़ के कारण 'बिहार का शोक' कहा जाता है?", ["गंडक","कोसी","सोन","बागमती"], "कोसी नदी बार-बार अपना मार्ग बदलती है और नेपाल से भारी गाद लाती है, इसलिए इसे 'बिहार का शोक' कहा जाता है।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["The Tropic of Cancer passes through how many Indian states?", ["6","7","9","8"], "It passes through Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram: eight states."],
    ["कर्क रेखा भारत के कितने राज्यों से होकर गुज़रती है?", ["6","7","9","8"], "यह गुजरात, राजस्थान, मध्य प्रदेश, छत्तीसगढ़, झारखंड, पश्चिम बंगाल, त्रिपुरा और मिज़ोरम से गुज़रती है: कुल आठ राज्य।"]),
  q(1, "general-studies", "indian-economy", "M", 2,
    ["The 'Blue Revolution' in India is associated with which sector?", ["Milk production","Oilseed production","Fish production","Egg production"], "The Blue Revolution refers to the rapid growth of fisheries and aquaculture. Milk is the White Revolution, oilseeds the Yellow Revolution and eggs the Silver Revolution."],
    ["भारत में 'नीली क्रांति' किस क्षेत्र से संबंधित है?", ["दूध उत्पादन","तिलहन उत्पादन","मछली उत्पादन","अंडा उत्पादन"], "नीली क्रांति मत्स्य पालन और जलीय कृषि की तीव्र वृद्धि को कहते हैं। दूध श्वेत क्रांति, तिलहन पीली क्रांति और अंडा रजत क्रांति से जुड़े हैं।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Which is the only metal that is liquid at room temperature?", ["Mercury","Sodium","Zinc","Lead"], "Mercury is the only common metal that is liquid at room temperature; it melts at about -39 degrees Celsius."],
    ["कमरे के तापमान पर द्रव अवस्था में रहने वाला एकमात्र धातु कौन-सा है?", ["पारा","सोडियम","जस्ता","सीसा"], "पारा कमरे के तापमान पर द्रव रहने वाली एकमात्र सामान्य धातु है; यह लगभग -39 डिग्री सेल्सियस पर पिघलता है।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["Diamond and graphite are different forms of the same element. Such forms are called:", ["Isotopes","Allotropes","Isobars","Isomers"], "Diamond and graphite are allotropes of carbon: same atoms, different arrangement. Isotopes are atoms of one element with different mass numbers."],
    ["हीरा और ग्रेफ़ाइट एक ही तत्व के भिन्न रूप हैं। ऐसे रूप क्या कहलाते हैं?", ["समस्थानिक","अपरूप (एलोट्रोप)","समभारिक","समावयवी"], "हीरा और ग्रेफ़ाइट कार्बन के अपरूप हैं: परमाणु वही, व्यवस्था भिन्न। समस्थानिक एक ही तत्व के भिन्न द्रव्यमान संख्या वाले परमाणु होते हैं।"]),
  q(1, "general-studies", "general-science", "H", 3,
    ["Which blood group is known as the universal donor for red blood cells?", ["AB positive","A negative","B positive","O negative"], "O negative red cells carry no A, B or Rh antigens, so they can be given to almost any recipient in an emergency. AB positive is the universal recipient."],
    ["लाल रक्त कोशिकाओं के लिए किस रक्त समूह को सर्वदाता (universal donor) कहा जाता है?", ["AB धनात्मक","A ऋणात्मक","B धनात्मक","O ऋणात्मक"], "O ऋणात्मक कोशिकाओं में A, B या Rh प्रतिजन नहीं होते, इसलिए आपात स्थिति में इन्हें लगभग किसी भी रोगी को दिया जा सकता है। AB धनात्मक सर्वग्राही है।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Police Commemoration Day, observed every year to honour police personnel killed on duty, falls on:", ["26 January","15 August","21 October","2 October"], "It marks the ambush at Hot Springs in Ladakh on 21 October 1959, in which ten CRPF personnel were killed defending the border."],
    ["ड्यूटी के दौरान शहीद पुलिसकर्मियों को श्रद्धांजलि देने के लिए हर वर्ष मनाया जाने वाला पुलिस स्मृति दिवस किस तिथि को होता है?", ["26 जनवरी","15 अगस्त","21 अक्टूबर","2 अक्टूबर"], "यह 21 अक्टूबर 1959 को लद्दाख के हॉट स्प्रिंग्स में हुए हमले की याद में मनाया जाता है, जिसमें सीमा की रक्षा करते हुए CRPF के दस जवान शहीद हुए थे।"]),
  q(1, "general-studies", "indian-history", "E", 0,
    ["The Bharat Ratna, the highest civilian honour of India, was instituted in the year:", ["1954","1947","1950","1961"], "The Bharat Ratna was instituted in 1954. C. Rajagopalachari, C.V. Raman and S. Radhakrishnan were the first recipients."],
    ["भारत का सर्वोच्च नागरिक सम्मान भारत रत्न किस वर्ष स्थापित किया गया?", ["1954","1947","1950","1961"], "भारत रत्न 1954 में स्थापित हुआ। सी. राजगोपालाचारी, सी.वी. रमन और एस. राधाकृष्णन पहले प्राप्तकर्ता थे।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["Neeraj Chopra won India's first Olympic athletics gold medal in the javelin throw at the Olympic Games held in:", ["London (2012)","Tokyo (2020, held in 2021)","Rio de Janeiro (2016)","Paris (2024)"], "Neeraj Chopra won gold at the Tokyo Olympics in August 2021 with a throw of 87.58 m. He won silver at Paris 2024."],
    ["नीरज चोपड़ा ने भाला फेंक में भारत का पहला ओलंपिक एथलेटिक्स स्वर्ण पदक किस ओलंपिक में जीता?", ["लंदन (2012)","टोक्यो (2020, आयोजन 2021 में)","रियो डी जनेरियो (2016)","पेरिस (2024)"], "नीरज चोपड़ा ने अगस्त 2021 में टोक्यो ओलंपिक में 87.58 मी के थ्रो से स्वर्ण जीता। पेरिस 2024 में उन्होंने रजत जीता।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["Article 40 of the Directive Principles directs the State to take steps to organise:", ["Cooperative societies","Free legal aid","Cottage industries","Village panchayats"], "Article 40, a Gandhian principle, directs the State to organise village panchayats and give them the powers to work as units of self-government."],
    ["नीति-निदेशक तत्वों का अनुच्छेद 40 राज्य को किसके गठन के लिए कदम उठाने का निर्देश देता है?", ["सहकारी समितियाँ","निःशुल्क विधिक सहायता","कुटीर उद्योग","ग्राम पंचायतें"], "गांधीवादी सिद्धांत वाला अनुच्छेद 40 राज्य को ग्राम पंचायतों के गठन और उन्हें स्वशासन की इकाइयों के रूप में कार्य करने की शक्तियाँ देने का निर्देश देता है।"]),

  // ───────── Section 2: Reasoning (20) ─────────
  q(2, "reasoning", "series", "M", 2,
    ["Find the next number: 6, 13, 27, 55, 111, ?", ["221","225","223","227"], "Each term is double the previous plus 1: 6×2+1 = 13, 13×2+1 = 27, 27×2+1 = 55, 55×2+1 = 111. So the next is 111×2+1 = 223."],
    ["अगली संख्या ज्ञात कीजिए: 6, 13, 27, 55, 111, ?", ["221","225","223","227"], "प्रत्येक पद पिछले पद का दुगुना और 1 अधिक है: 6×2+1 = 13, 13×2+1 = 27, 27×2+1 = 55, 55×2+1 = 111। अतः अगला 111×2+1 = 223।"], "111*2+1"),
  q(2, "reasoning", "series", "M", 3,
    ["Find the next number: 2, 6, 24, 120, 720, ?", ["3600","4320","5760","5040"], "The terms are factorials: 2!, 3!, 4!, 5!, 6!. The next is 7! = 5040."],
    ["अगली संख्या ज्ञात कीजिए: 2, 6, 24, 120, 720, ?", ["3600","4320","5760","5040"], "पद क्रमगुणित हैं: 2!, 3!, 4!, 5!, 6!। अगला 7! = 5040 है।"], "5040"),
  q(2, "reasoning", "series", "H", 0,
    ["Find the next number: 1, 4, 27, 256, ?", ["3125","1024","2500","3025"], "The terms are 1¹, 2², 3³, 4⁴. The next is 5⁵ = 3125."],
    ["अगली संख्या ज्ञात कीजिए: 1, 4, 27, 256, ?", ["3125","1024","2500","3025"], "पद 1¹, 2², 3³, 4⁴ हैं। अगला 5⁵ = 3125 है।"], "Math.pow(5,5)"),
  q(2, "reasoning", "series", "H", 1,
    ["Find the next letter: B, E, I, N, T, ?", ["Z","A","B","Y"], "Positions are 2, 5, 9, 14, 20 with differences 3, 4, 5, 6. The next difference is 7: 20 + 7 = 27, which wraps around to 1, i.e. A."],
    ["अगला अक्षर ज्ञात कीजिए: B, E, I, N, T, ?", ["Z","A","B","Y"], "क्रमांक 2, 5, 9, 14, 20 हैं और अंतर 3, 4, 5, 6। अगला अंतर 7 है: 20 + 7 = 27, जो घूमकर 1 यानी A होता है।"]),
  q(2, "reasoning", "coding-decoding", "M", 2,
    ["If POLICE is coded as QPMJDF, how will CADET be coded in the same way?", ["DBFFU","CBEFU","DBEFU","DBEEU"], "Each letter moves one step forward: C→D, A→B, D→E, E→F, T→U. So CADET becomes DBEFU."],
    ["यदि POLICE को QPMJDF लिखा जाता है, तो उसी प्रकार CADET को कैसे लिखा जाएगा?", ["DBFFU","CBEFU","DBEFU","DBEEU"], "प्रत्येक अक्षर एक स्थान आगे बढ़ता है: C→D, A→B, D→E, E→F, T→U। अतः CADET का कूट DBEFU होगा।"]),
  q(2, "reasoning", "coding-decoding", "M", 3,
    ["If A = 1, B = 2, C = 3 and so on, what is the sum of the letter values of the word LAW?", ["34","38","35","36"], "L = 12, A = 1, W = 23, so the sum is 12 + 1 + 23 = 36."],
    ["यदि A = 1, B = 2, C = 3 इत्यादि हों, तो शब्द LAW के अक्षरों के मानों का योग क्या है?", ["34","38","35","36"], "L = 12, A = 1, W = 23, अतः योग 12 + 1 + 23 = 36।"], "12+1+23"),
  q(2, "reasoning", "coding-decoding", "H", 0,
    ["If DELHI is written as 73541 and CALCUTTA as 82589662, how will CALICUT be written in that code?", ["8251896","5279431","8251968","8215896"], "From the given words: D=7, E=3, L=5, H=4, I=1, C=8, A=2, U=9, T=6. So C-A-L-I-C-U-T becomes 8-2-5-1-8-9-6 = 8251896."],
    ["यदि DELHI को 73541 और CALCUTTA को 82589662 लिखा जाता है, तो उसी कूट में CALICUT कैसे लिखा जाएगा?", ["8251896","5279431","8251968","8215896"], "दिए शब्दों से: D=7, E=3, L=5, H=4, I=1, C=8, A=2, U=9, T=6। अतः C-A-L-I-C-U-T = 8-2-5-1-8-9-6 = 8251896।"]),
  q(2, "reasoning", "blood-relations", "M", 1,
    ["Pointing to a photograph, Ravi says, 'He is the son of the only son of my grandfather.' How is the man in the photograph related to Ravi?", ["Cousin","Brother","Uncle","Nephew"], "The only son of Ravi's grandfather is Ravi's father. The son of Ravi's father is Ravi's brother."],
    ["एक फ़ोटो की ओर संकेत करके रवि कहता है, 'यह मेरे दादा के इकलौते पुत्र का पुत्र है।' फ़ोटो वाला व्यक्ति रवि का क्या लगता है?", ["चचेरा भाई","भाई","चाचा","भतीजा"], "रवि के दादा का इकलौता पुत्र रवि का पिता है। रवि के पिता का पुत्र रवि का भाई है।"]),
  q(2, "reasoning", "blood-relations", "H", 2,
    ["P is Q's brother. R is Q's mother. S is R's father. How is P related to S?", ["Son","Nephew","Grandson","Great-grandson"], "R is the mother of P and Q. S is R's father, so S is P's maternal grandfather and P is S's grandson."],
    ["P, Q का भाई है। R, Q की माता है। S, R का पिता है। P, S से किस प्रकार संबंधित है?", ["पुत्र","भतीजा","नाती (दौहित्र)","परनाती"], "R, P और Q की माता है। S, R का पिता है, अतः S, P का नाना है और P, S का नाती है।"]),
  q(2, "reasoning", "direction-sense", "H", 3,
    ["A man walks 5 km east, turns right and walks 3 km, turns right again and walks 5 km, then turns left and walks 2 km. How far and in which direction is he from the starting point?", ["5 km north","3 km south","7 km south","5 km south"], "East 5 km puts him at (5, 0). Right (south) 3 km: (5, −3). Right (west) 5 km: (0, −3). Left from west is south: 2 km gives (0, −5). He is 5 km south of the start."],
    ["एक व्यक्ति 5 किमी पूर्व की ओर चलता है, दाएँ मुड़कर 3 किमी चलता है, फिर दाएँ मुड़कर 5 किमी चलता है, फिर बाएँ मुड़कर 2 किमी चलता है। वह आरंभ बिंदु से कितनी दूर और किस दिशा में है?", ["5 किमी उत्तर","3 किमी दक्षिण","7 किमी दक्षिण","5 किमी दक्षिण"], "पूर्व 5 किमी पर वह (5, 0) पर है। दाएँ (दक्षिण) 3 किमी: (5, −3)। दाएँ (पश्चिम) 5 किमी: (0, −3)। पश्चिम मुख से बाएँ मुड़ना दक्षिण है: 2 किमी से (0, −5)। वह आरंभ से 5 किमी दक्षिण में है।"]),
  q(2, "reasoning", "direction-sense", "M", 0,
    ["Ravi walks 10 m north, then turns left and walks 24 m. What is his shortest distance from the starting point?", ["26 m","34 m","30 m","28 m"], "The path forms a right angle, so distance = `√(10² + 24²)` = `√676` = 26 m."],
    ["रवि 10 मी उत्तर की ओर चलता है, फिर बाएँ मुड़कर 24 मी चलता है। आरंभ बिंदु से उसकी न्यूनतम दूरी कितनी है?", ["26 मी","34 मी","30 मी","28 मी"], "पथ समकोण बनाता है, अतः दूरी = `√(10² + 24²)` = `√676` = 26 मी।"], "Math.sqrt(10*10+24*24)"),
  q(2, "reasoning", "ranking", "M", 1,
    ["In a row of 40 students, Meena is 12th from the left. What is her position from the right end?", ["28th","29th","30th","27th"], "Position from right = total − position from left + 1 = 40 − 12 + 1 = 29."],
    ["40 विद्यार्थियों की एक पंक्ति में मीना बाईं ओर से 12वीं है। दाएँ छोर से उसका स्थान कौन-सा है?", ["28वाँ","29वाँ","30वाँ","27वाँ"], "दाएँ से स्थान = कुल − बाएँ से स्थान + 1 = 40 − 12 + 1 = 29।"]),
  q(2, "reasoning", "ranking", "M", 2,
    ["Ajay ranks 9th from the top and 32nd from the bottom in a class. How many students are there in the class?", ["41","39","40","42"], "Total = rank from top + rank from bottom − 1 = 9 + 32 − 1 = 40."],
    ["एक कक्षा में अजय ऊपर से 9वें और नीचे से 32वें स्थान पर है। कक्षा में कुल कितने विद्यार्थी हैं?", ["41","39","40","42"], "कुल = ऊपर से स्थान + नीचे से स्थान − 1 = 9 + 32 − 1 = 40।"], "9+32-1"),
  q(2, "reasoning", "syllogism", "M", 0,
    ["Statements: Some doctors are teachers. All teachers are honest. Conclusions: I. Some doctors are honest. II. All honest persons are teachers.", ["Only conclusion I follows","Only conclusion II follows","Both I and II follow","Neither I nor II follows"], "Some doctors are teachers and all teachers are honest, so some doctors are honest (I follows). 'All honest are teachers' reverses the statement and does not follow."],
    ["कथन: कुछ डॉक्टर अध्यापक हैं। सभी अध्यापक ईमानदार हैं। निष्कर्ष: I. कुछ डॉक्टर ईमानदार हैं। II. सभी ईमानदार व्यक्ति अध्यापक हैं।", ["केवल निष्कर्ष I अनुसरण करता है","केवल निष्कर्ष II अनुसरण करता है","I और II दोनों अनुसरण करते हैं","न तो I और न ही II अनुसरण करता है"], "कुछ डॉक्टर अध्यापक हैं और सभी अध्यापक ईमानदार हैं, अतः कुछ डॉक्टर ईमानदार हैं (I अनुसरण करता है)। 'सभी ईमानदार अध्यापक हैं' कथन को उलटता है और अनुसरण नहीं करता।"]),
  q(2, "reasoning", "syllogism", "M", 1,
    ["Statements: All roses are flowers. All flowers are plants. Conclusions: I. All roses are plants. II. Some plants are flowers.", ["Only conclusion I follows","Both I and II follow","Only conclusion II follows","Neither I nor II follows"], "All roses are flowers and all flowers are plants, so all roses are plants (I). Since all flowers are plants, some plants are flowers (II)."],
    ["कथन: सभी गुलाब फूल हैं। सभी फूल पौधे हैं। निष्कर्ष: I. सभी गुलाब पौधे हैं। II. कुछ पौधे फूल हैं।", ["केवल निष्कर्ष I अनुसरण करता है","I और II दोनों अनुसरण करते हैं","केवल निष्कर्ष II अनुसरण करता है","न तो I और न ही II अनुसरण करता है"], "सभी गुलाब फूल हैं और सभी फूल पौधे हैं, अतः सभी गुलाब पौधे हैं (I)। चूँकि सभी फूल पौधे हैं, कुछ पौधे फूल हैं (II)।"]),
  q(2, "reasoning", "analogy", "H", 3,
    ["Find the missing term: 27 : 3 :: 64 : ?", ["8","6","16","4"], "27 is the cube of 3, so 3 is the cube root of 27. Likewise, the cube root of 64 is 4."],
    ["लुप्त पद ज्ञात कीजिए: 27 : 3 :: 64 : ?", ["8","6","16","4"], "27 का घनमूल 3 है। इसी प्रकार 64 का घनमूल 4 है।"]),
  q(2, "reasoning", "odd-one-out", "M", 0,
    ["Find the odd one out: 121, 169, 225, 250, 289", ["250","121","225","289"], "121 = 11², 169 = 13², 225 = 15², 289 = 17² are perfect squares. 250 is not."],
    ["विषम संख्या ज्ञात कीजिए: 121, 169, 225, 250, 289", ["250","121","225","289"], "121 = 11², 169 = 13², 225 = 15², 289 = 17² पूर्ण वर्ग हैं। 250 पूर्ण वर्ग नहीं है।"]),
  q(2, "reasoning", "clock-calendar", "H", 1,
    ["What is the angle between the hour and minute hands of a clock at 3:40?", ["120°","130°","140°","150°"], "Angle = |30H − 5.5M| = |30×3 − 5.5×40| = |90 − 220| = 130°."],
    ["घड़ी में 3:40 बजे घंटे और मिनट की सुइयों के बीच कितना कोण होता है?", ["120°","130°","140°","150°"], "कोण = |30H − 5.5M| = |30×3 − 5.5×40| = |90 − 220| = 130°।"]),
  q(2, "reasoning", "clock-calendar", "H", 2,
    ["If 5 January 2026 is a Monday, what day of the week is 5 March 2026?", ["Wednesday","Friday","Thursday","Tuesday"], "From 5 January to 5 March 2026 there are 26 + 28 + 5 = 59 days. 59 = 8 weeks + 3 days, so the day is Monday + 3 = Thursday."],
    ["यदि 5 जनवरी 2026 को सोमवार है, तो 5 मार्च 2026 को कौन-सा दिन होगा?", ["बुधवार","शुक्रवार","गुरुवार","मंगलवार"], "5 जनवरी से 5 मार्च 2026 तक 26 + 28 + 5 = 59 दिन होते हैं। 59 = 8 सप्ताह + 3 दिन, अतः दिन सोमवार + 3 = गुरुवार।"]),
  q(2, "reasoning", "puzzles", "H", 3,
    ["Five friends P, Q, R, S and T sit in a row facing north. P is at the extreme left and R is at the extreme right. Q sits immediately to the left of R. S does not sit next to Q. Who sits in the middle?", ["S","Q","P","T"], "The order starts P _ _ Q R. S and T fill the two blank places, and S cannot be next to Q, so S is second and T is third: P, S, T, Q, R. T is in the middle."],
    ["पाँच मित्र P, Q, R, S और T उत्तर की ओर मुख करके एक पंक्ति में बैठे हैं। P सबसे बाएँ और R सबसे दाएँ है। Q, R के ठीक बाईं ओर बैठा है। S, Q के बगल में नहीं बैठा है। बीच में कौन बैठा है?", ["S","Q","P","T"], "क्रम P _ _ Q R से शुरू होता है। S और T दो खाली स्थान भरते हैं और S, Q के बगल में नहीं हो सकता, अतः S दूसरे और T तीसरे स्थान पर है: P, S, T, Q, R। बीच में T है।"]),

  // ───────── Section 3: Numerical Ability (15) ─────────
  q(3, "quant", "percentage", "M", 0,
    ["A number is increased by 20% and the result is then decreased by 20%. The net change is:", ["4% decrease","No change","4% increase","2% decrease"], "The final value is `1.2 × 0.8` = 0.96 of the original, which is a 4% decrease."],
    ["एक संख्या में 20% की वृद्धि की जाती है और फिर परिणाम में 20% की कमी की जाती है। कुल परिवर्तन क्या है?", ["4% कमी","कोई परिवर्तन नहीं","4% वृद्धि","2% कमी"], "अंतिम मान मूल का `1.2 × 0.8` = 0.96 है, अर्थात 4% की कमी।"]),
  q(3, "quant", "percentage", "H", 1,
    ["In an election between two candidates, the winner gets 55% of the valid votes and wins by 1,200 votes. What is the total number of valid votes?", ["10,000","12,000","15,000","14,400"], "The winner gets 55% and the loser 45%, so the margin is 10% of the total. 10% of the total = 1,200, so total = 12,000."],
    ["दो उम्मीदवारों के बीच चुनाव में विजेता को वैध मतों का 55% मिलता है और वह 1,200 मतों से जीतता है। कुल वैध मत कितने हैं?", ["10,000","12,000","15,000","14,400"], "विजेता को 55% और हारने वाले को 45% मिले, अतः अंतर कुल का 10% है। कुल का 10% = 1,200, अतः कुल = 12,000।"], "1200*10"),
  q(3, "quant", "profit-loss", "M", 2,
    ["A shopkeeper marks an article 40% above its cost price and allows a discount of 10%. His profit percentage is:", ["30%","25%","26%","24%"], "Let the cost be 100. Marked price = 140. Selling price = `140 × 0.9` = 126. Profit = 26%."],
    ["एक दुकानदार वस्तु का मूल्य क्रय मूल्य से 40% अधिक अंकित करता है और 10% की छूट देता है। उसका लाभ प्रतिशत क्या है?", ["30%","25%","26%","24%"], "मान लें क्रय मूल्य 100 है। अंकित मूल्य = 140। विक्रय मूल्य = `140 × 0.9` = 126। लाभ = 26%।"], "140*0.9-100"),
  q(3, "quant", "interest", "H", 3,
    ["A sum of money becomes Rs 6,000 in 2 years and Rs 7,500 in 5 years at simple interest. What is the sum?", ["Rs 4,500","Rs 5,500","Rs 4,000","Rs 5,000"], "Interest for 3 years = 7,500 − 6,000 = 1,500, so 500 per year. The sum = 6,000 − 2×500 = 5,000."],
    ["साधारण ब्याज पर कोई धनराशि 2 वर्ष में 6,000 रुपये और 5 वर्ष में 7,500 रुपये हो जाती है। मूलधन कितना है?", ["4,500 रुपये","5,500 रुपये","4,000 रुपये","5,000 रुपये"], "3 वर्ष का ब्याज = 7,500 − 6,000 = 1,500, अर्थात 500 रुपये प्रति वर्ष। मूलधन = 6,000 − 2×500 = 5,000।"], "6000-2*500"),
  q(3, "quant", "interest", "M", 0,
    ["What is the compound interest on Rs 8,000 at 10% per annum for 2 years, compounded annually?", ["Rs 1,680","Rs 1,600","Rs 1,620","Rs 1,700"], "Amount = `8000 × 1.1 × 1.1` = 9,680. Compound interest = 9,680 − 8,000 = 1,680."],
    ["8,000 रुपये पर 10% वार्षिक दर से 2 वर्ष का चक्रवृद्धि ब्याज (वार्षिक संयोजन) कितना होगा?", ["1,680 रुपये","1,600 रुपये","1,620 रुपये","1,700 रुपये"], "मिश्रधन = `8000 × 1.1 × 1.1` = 9,680। चक्रवृद्धि ब्याज = 9,680 − 8,000 = 1,680।"], "8000*1.21-8000"),
  q(3, "quant", "time-work", "H", 1,
    ["A and B together can do a job in 12 days, B and C in 15 days, and A and C in 20 days. In how many days can all three together do it?", ["8 days","10 days","12 days","9 days"], "Adding the three rates: 2(A+B+C) = 1/12 + 1/15 + 1/20 = 12/60 = 1/5. So A+B+C = 1/10 per day, i.e. 10 days."],
    ["A और B मिलकर एक कार्य 12 दिन में, B और C 15 दिन में तथा A और C 20 दिन में कर सकते हैं। तीनों मिलकर वह कार्य कितने दिन में करेंगे?", ["8 दिन","10 दिन","12 दिन","9 दिन"], "तीनों दरें जोड़ने पर: 2(A+B+C) = 1/12 + 1/15 + 1/20 = 12/60 = 1/5। अतः A+B+C = 1/10 प्रतिदिन, यानी 10 दिन।"], "10"),
  q(3, "quant", "time-work", "H", 2,
    ["Pipe A can fill a tank in 20 minutes and pipe B in 30 minutes, while pipe C can empty the full tank in 60 minutes. If all three are opened together, how long will it take to fill the tank?", ["12 minutes","18 minutes","15 minutes","20 minutes"], "Net rate = 1/20 + 1/30 − 1/60 = (3 + 2 − 1)/60 = 4/60 = 1/15. So the tank fills in 15 minutes."],
    ["नल A एक टंकी को 20 मिनट में और नल B 30 मिनट में भर सकता है, जबकि नल C भरी टंकी को 60 मिनट में खाली कर सकता है। तीनों एक साथ खोलने पर टंकी कितने समय में भरेगी?", ["12 मिनट","18 मिनट","15 मिनट","20 मिनट"], "शुद्ध दर = 1/20 + 1/30 − 1/60 = (3 + 2 − 1)/60 = 4/60 = 1/15। अतः टंकी 15 मिनट में भरेगी।"], "15"),
  q(3, "quant", "speed-distance", "M", 3,
    ["A 180 m long train crosses a pole in 12 seconds. How long will it take to cross a platform 270 m long at the same speed?", ["36 seconds","24 seconds","27 seconds","30 seconds"], "Speed = 180/12 = 15 m/s. Distance to cross the platform = 180 + 270 = 450 m. Time = 450/15 = 30 s."],
    ["180 मी लंबी रेलगाड़ी एक खंभे को 12 सेकंड में पार करती है। समान चाल से वह 270 मी लंबे प्लेटफ़ॉर्म को कितने समय में पार करेगी?", ["36 सेकंड","24 सेकंड","27 सेकंड","30 सेकंड"], "चाल = 180/12 = 15 मी/से। प्लेटफ़ॉर्म पार करने की दूरी = 180 + 270 = 450 मी। समय = 450/15 = 30 से।"], "450/15"),
  q(3, "quant", "speed-distance", "H", 0,
    ["Two trains 100 m and 140 m long run in opposite directions at 60 km/h and 48 km/h. How long do they take to cross each other completely?", ["8 seconds","10 seconds","6 seconds","12 seconds"], "Relative speed = 108 km/h = 30 m/s. Total length = 240 m. Time = 240/30 = 8 s."],
    ["100 मी और 140 मी लंबी दो रेलगाड़ियाँ विपरीत दिशाओं में 60 किमी/घं और 48 किमी/घं की चाल से चल रही हैं। वे एक-दूसरे को पूरी तरह पार करने में कितना समय लेंगी?", ["8 सेकंड","10 सेकंड","6 सेकंड","12 सेकंड"], "सापेक्ष चाल = 108 किमी/घं = 30 मी/से। कुल लंबाई = 240 मी। समय = 240/30 = 8 से।"], "240/30"),
  q(3, "quant", "hcf-lcm", "M", 1,
    ["The ratio of two numbers is 3 : 4 and their LCM is 240. What is their sum?", ["120","140","160","100"], "Let the numbers be 3k and 4k. Their LCM is 12k = 240, so k = 20. The numbers are 60 and 80, and the sum is 140."],
    ["दो संख्याओं का अनुपात 3 : 4 है और उनका लघुत्तम समापवर्त्य 240 है। उनका योग कितना है?", ["120","140","160","100"], "संख्याएँ 3k और 4k मानें। उनका ल.स. 12k = 240, अतः k = 20। संख्याएँ 60 और 80 हैं और योग 140।"], "60+80"),
  q(3, "quant", "average", "M", 2,
    ["The average of 5 numbers is 27. If one number is removed, the average of the remaining four becomes 25. What is the number removed?", ["30","37","35","32"], "Sum of five = 135. Sum of four = 100. Removed number = 135 − 100 = 35."],
    ["5 संख्याओं का औसत 27 है। एक संख्या हटा देने पर शेष चार का औसत 25 हो जाता है। हटाई गई संख्या कौन-सी है?", ["30","37","35","32"], "पाँचों का योग = 135। चारों का योग = 100। हटाई गई संख्या = 135 − 100 = 35।"], "5*27-4*25"),
  q(3, "quant", "mensuration", "M", 3,
    ["The area of a circle is 154 cm². What is its circumference? (Take π = 22/7)", ["22 cm","88 cm","66 cm","44 cm"], "`πr² = 154` gives r² = 49, so r = 7 cm. Circumference = `2πr = 2 × 22/7 × 7` = 44 cm."],
    ["एक वृत्त का क्षेत्रफल 154 सेमी² है। उसकी परिधि कितनी है? (π = 22/7 लें)", ["22 सेमी","88 सेमी","66 सेमी","44 सेमी"], "`πr² = 154` से r² = 49, अतः r = 7 सेमी। परिधि = `2πr = 2 × 22/7 × 7` = 44 सेमी।"], "2*22/7*7"),
  q(3, "quant", "mensuration", "H", 0,
    ["The total surface area of a cube is 294 cm². What is the length of its diagonal?", ["7√3 cm","7√2 cm","14 cm","21 cm"], "`6a² = 294` gives a² = 49, so a = 7 cm. The space diagonal of a cube is `a√3` = 7√3 cm."],
    ["एक घन का कुल पृष्ठीय क्षेत्रफल 294 सेमी² है। उसके विकर्ण की लंबाई कितनी है?", ["7√3 सेमी","7√2 सेमी","14 सेमी","21 सेमी"], "`6a² = 294` से a² = 49, अतः a = 7 सेमी। घन का अंतःकर्ण `a√3` = 7√3 सेमी होता है।"]),
  q(3, "quant", "simplification", "M", 1,
    ["Find the value of `√1764 ÷ 6 + 3²`.", ["14","16","12","18"], "`√1764` = 42. Then 42 ÷ 6 = 7, and 7 + 9 = 16."],
    ["`√1764 ÷ 6 + 3²` का मान ज्ञात कीजिए।", ["14","16","12","18"], "`√1764` = 42। फिर 42 ÷ 6 = 7 और 7 + 9 = 16।"], "Math.sqrt(1764)/6+9"),
  q(3, "quant", "mixture-alligation", "H", 2,
    ["In what ratio should sugar costing Rs 40 per kg be mixed with sugar costing Rs 50 per kg to get a mixture worth Rs 43 per kg?", ["3 : 7","2 : 1","7 : 3","4 : 3"], "By alligation, cheaper : dearer = (50 − 43) : (43 − 40) = 7 : 3."],
    ["40 रुपये प्रति किग्रा और 50 रुपये प्रति किग्रा वाली चीनी को किस अनुपात में मिलाने पर 43 रुपये प्रति किग्रा का मिश्रण बनेगा?", ["3 : 7","2 : 1","7 : 3","4 : 3"], "मिश्रण नियम से सस्ती : महँगी = (50 − 43) : (43 − 40) = 7 : 3।"]),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "english", "synonyms-antonyms", "M", 0,
    ["Choose the synonym of 'AUSTERE':", ["Stern","Luxurious","Cheerful","Generous"], "'Austere' means severe, plain and strict, without comfort or luxury. 'Stern' is the closest meaning."],
    ["'AUSTERE' का पर्यायवाची चुनिए:", ["Stern","Luxurious","Cheerful","Generous"], "'Austere' का अर्थ है कठोर, सादा और सख़्त, बिना सुख-सुविधा के। 'Stern' सबसे निकट अर्थ है।"]),
  q(4, "english", "synonyms-antonyms", "M", 3,
    ["Choose the antonym of 'FRAGILE':", ["Delicate","Brittle","Flimsy","Sturdy"], "'Fragile' means easily broken. Its opposite is 'sturdy', meaning strong and solid. Delicate, brittle and flimsy are close synonyms."],
    ["'FRAGILE' का विलोम चुनिए:", ["Delicate","Brittle","Flimsy","Sturdy"], "'Fragile' का अर्थ है आसानी से टूटने वाला। इसका विलोम 'sturdy' (मज़बूत) है। Delicate, brittle और flimsy इसके निकट समानार्थी हैं।"]),
  q(4, "english", "one-word", "M", 2,
    ["One word for 'a place where birds are kept':", ["Apiary","Aquarium","Aviary","Armoury"], "An aviary is a large cage or building for birds. An apiary is for bees, an aquarium for fish and an armoury for weapons."],
    ["'वह स्थान जहाँ पक्षी पाले जाते हैं' के लिए एक शब्द:", ["Apiary","Aquarium","Aviary","Armoury"], "Aviary पक्षियों के लिए बड़ा पिंजरा या भवन है। Apiary मधुमक्खियों, aquarium मछलियों और armoury हथियारों के लिए होता है।"]),
  q(4, "english", "idioms", "M", 0,
    ["Choose the meaning of the idiom 'to hit the nail on the head':", ["To say or do exactly the right thing","To repair a house","To hurt oneself","To make a loud noise"], "The idiom means to describe or do something with complete accuracy."],
    ["मुहावरे 'to hit the nail on the head' का अर्थ चुनिए:", ["ठीक वही बात कहना या करना जो सही हो","घर की मरम्मत करना","स्वयं को चोट पहुँचाना","ज़ोर से शोर करना"], "इस मुहावरे का अर्थ है किसी बात को बिल्कुल सटीक ढंग से कहना या करना।"]),
  q(4, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'Neither of the two suspects / were able to / give a satisfactory alibi. / No error'", ["Neither of the two suspects","were able to","give a satisfactory alibi.","No error"], "'Neither' takes a singular verb, so it should be 'was able to'."],
    ["त्रुटि वाला भाग चुनिए: 'Neither of the two suspects / were able to / give a satisfactory alibi. / No error'", ["Neither of the two suspects","were able to","give a satisfactory alibi.","No error"], "'Neither' के साथ एकवचन क्रिया आती है, अतः सही रूप 'was able to' है।"]),
  q(4, "english", "grammar", "M", 1,
    ["Fill in the blank: 'The inspector insisted ___ examining the evidence again.'", ["at","on","for","to"], "The verb 'insist' takes the preposition 'on': insist on doing something."],
    ["रिक्त स्थान भरिए: 'The inspector insisted ___ examining the evidence again.'", ["at","on","for","to"], "क्रिया 'insist' के साथ पूर्वसर्ग 'on' आता है: insist on doing something।"]),
  q(4, "english", "spelling", "M", 3,
    ["Choose the correct spelling of the word that means 'an event or incident':", ["Occurence","Ocurrence","Occurrance","Occurrence"], "'Occurrence' has a double 'c', a double 'r' and ends in -ence."],
    ["'घटना' अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Occurence","Ocurrence","Occurrance","Occurrence"], "'Occurrence' में दो 'c', दो 'r' आते हैं और अंत -ence से होता है।"]),
  q(4, "hindi", "paryay-vilom", "M", 2,
    ["Which of these is NOT a synonym of 'चंद्रमा' (moon)?", ["शशि","इंदु","दिनकर","सुधांशु"], "शशि, इंदु and सुधांशु all mean the moon. 'दिनकर' means the sun."],
    ["निम्नलिखित में से कौन-सा 'चंद्रमा' का पर्यायवाची नहीं है?", ["शशि","इंदु","दिनकर","सुधांशु"], "शशि, इंदु और सुधांशु सभी चंद्रमा के पर्यायवाची हैं। 'दिनकर' का अर्थ सूर्य है।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["Choose the antonym of the Hindi word 'उत्कर्ष':", ["अपकर्ष","अपकार","निकृष्ट","उपकार"], "'उत्कर्ष' means rise or progress. Its opposite is 'अपकर्ष' (decline). 'उपकार' and 'अपकार' are another pair."],
    ["'उत्कर्ष' शब्द का विलोम चुनिए:", ["अपकर्ष","अपकार","निकृष्ट","उपकार"], "'उत्कर्ष' का अर्थ उन्नति है। इसका विलोम 'अपकर्ष' (पतन) है। 'उपकार' और 'अपकार' दूसरा युग्म है।"]),
  q(4, "hindi", "ek-shabd", "M", 1,
    ["Choose the one word for 'जो कम बोलता हो':", ["वाचाल","मितभाषी","मौन","मृदुभाषी"], "'मितभाषी' means one who speaks little. 'वाचाल' is one who talks too much and 'मृदुभाषी' one who speaks softly."],
    ["'जो कम बोलता हो' के लिए एक शब्द चुनिए:", ["वाचाल","मितभाषी","मौन","मृदुभाषी"], "'मितभाषी' का अर्थ है कम बोलने वाला। 'वाचाल' बहुत बोलने वाला और 'मृदुभाषी' मधुर बोलने वाला होता है।"]),
  q(4, "hindi", "sandhi-samas", "H", 3,
    ["Choose the correct split of the sandhi word 'महर्षि':", ["मह + ऋषि","महर् + षि","महि + ऋषि","महा + ऋषि"], "'महर्षि' = महा + ऋषि. Here आ + ऋ = अर्, which is a guna sandhi."],
    ["'महर्षि' का सही संधि-विच्छेद चुनिए:", ["मह + ऋषि","महर् + षि","महि + ऋषि","महा + ऋषि"], "'महर्षि' = महा + ऋषि। यहाँ आ + ऋ = अर् हुआ है, यह गुण संधि है।"]),
  q(4, "hindi", "sandhi-samas", "H", 2,
    ["Identify the type of compound (samas) in 'त्रिलोक':", ["Tatpurush","Karmadharaya","Dvigu","Bahuvrihi"], "'त्रिलोक' = तीनों लोकों का समूह. The first word is a numeral and the compound denotes a collection, so it is a Dvigu samas."],
    ["'त्रिलोक' शब्द में कौन-सा समास है?", ["तत्पुरुष","कर्मधारय","द्विगु","बहुव्रीहि"], "'त्रिलोक' = तीनों लोकों का समूह। पहला पद संख्यावाचक है और समूह का बोध कराता है, अतः द्विगु समास है।"]),
  q(4, "hindi", "muhavare", "M", 0,
    ["What is the meaning of the Hindi idiom 'नौ दो ग्यारह होना'?", ["To run away","To become rich","To add numbers","To be very happy"], "The idiom means to flee or run away quickly."],
    ["'नौ दो ग्यारह होना' मुहावरे का अर्थ है:", ["भाग जाना","अमीर हो जाना","संख्याएँ जोड़ना","बहुत खुश होना"], "इस मुहावरे का अर्थ है तुरंत भाग जाना।"]),
  q(4, "hindi", "muhavare", "H", 1,
    ["What does the Hindi proverb 'ऊँट के मुँह में जीरा' mean?", ["A very costly gift","Something far too little for the need","Feeding a camel with care","A spicy meal"], "The proverb means an amount that is very small compared with the requirement."],
    ["लोकोक्ति 'ऊँट के मुँह में जीरा' का अर्थ है:", ["बहुत महँगा उपहार","आवश्यकता से बहुत कम वस्तु","ऊँट को सावधानी से खिलाना","तीखा भोजन"], "इस लोकोक्ति का अर्थ है आवश्यकता की तुलना में बहुत थोड़ी मात्रा।"]),
  q(4, "hindi", "vyakaran", "M", 3,
    ["Which of these Hindi words is correctly spelt?", ["प्रतिष्टा","प्रतीष्ठा","प्रतिस्ठा","प्रतिष्ठा"], "The correct spelling is 'प्रतिष्ठा' (respect, reputation), with the retroflex 'ष्ठ'."],
    ["इनमें से कौन-सा शब्द शुद्ध वर्तनी वाला है?", ["प्रतिष्टा","प्रतीष्ठा","प्रतिस्ठा","प्रतिष्ठा"], "शुद्ध वर्तनी 'प्रतिष्ठा' है, जिसमें मूर्धन्य 'ष्ठ' आता है।"]),
];
