// HP Police Constable Full Mock 7 — 100 questions (25 HP GK, 25 GK, 20 Reasoning, 15 Maths, 15 Hindi/English).

import { q, type PoliceQuestion } from "./types";

export const mock7: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK (25) ─────────
  q(0, "hp-gk", "economy", "H", 0,
    ["Dr Y.S. Parmar University of Horticulture and Forestry, a leading horticulture university of India, is located at:", ["Nauni (Solan)", "Palampur (Kangra)", "Sundernagar (Mandi)", "Kufri (Shimla)"], "The university was set up in 1985 and is named after Himachal's first Chief Minister. Its campus is at Nauni in Solan district. The agricultural university (CSK HPKV) is at Palampur."],
    ["डॉ. वाई.एस. परमार बागवानी एवं वानिकी विश्वविद्यालय, जो भारत का अग्रणी बागवानी विश्वविद्यालय है, कहाँ स्थित है?", ["नौणी (सोलन)", "पालमपुर (कांगड़ा)", "सुंदरनगर (मंडी)", "कुफ़री (शिमला)"], "इस विश्वविद्यालय की स्थापना 1985 में हुई और यह हिमाचल के पहले मुख्यमंत्री के नाम पर है। इसका परिसर सोलन जिले के नौणी में है। कृषि विश्वविद्यालय (CSK HPKV) पालमपुर में है।"]),
  q(0, "hp-gk", "economy", "H", 1,
    ["The CSIR Institute of Himalayan Bioresource Technology (IHBT), which works on medicinal and aromatic plants and tea, is located at:", ["Solan", "Palampur", "Shimla", "Nahan"], "CSIR-IHBT is at Palampur in Kangra district, a town also known for its tea gardens and the agricultural university."],
    ["औषधीय व सुगंधित पौधों और चाय पर काम करने वाला CSIR हिमालयी जैव-संपदा प्रौद्योगिकी संस्थान (IHBT) कहाँ है?", ["सोलन", "पालमपुर", "शिमला", "नाहन"], "CSIR-IHBT कांगड़ा जिले के पालमपुर में है, जो अपने चाय बागानों और कृषि विश्वविद्यालय के लिए भी जाना जाता है।"]),
  q(0, "hp-gk", "economy", "H", 2,
    ["Chilgoza (pine nut), a costly dry fruit, is obtained in Himachal Pradesh mainly from the dry inner valleys of:", ["Sirmaur", "Bilaspur", "Kinnaur", "Una"], "Chilgoza comes from the Pinus gerardiana tree, which grows in the dry, rain-shadow valleys of Kinnaur. It is also found in parts of Pangi in Chamba."],
    ["महँगा सूखा मेवा चिलगोज़ा (नियोज़ा) हिमाचल प्रदेश में मुख्यतः किसकी शुष्क भीतरी घाटियों से मिलता है?", ["सिरमौर", "बिलासपुर", "किन्नौर", "ऊना"], "चिलगोज़ा पाइनस गेरार्डियाना वृक्ष से मिलता है, जो किन्नौर की शुष्क, वर्षा-छाया घाटियों में उगता है। यह चंबा के पांगी के कुछ भागों में भी मिलता है।"]),
  q(0, "hp-gk", "economy", "M", 3,
    ["Which district is the largest producer of apples in Himachal Pradesh?", ["Kinnaur", "Kullu", "Mandi", "Shimla"], "Shimla district, with belts such as Kotgarh, Kotkhai, Jubbal and Rohru, produces the largest share of the state's apples."],
    ["हिमाचल प्रदेश में सेब का सबसे अधिक उत्पादन किस जिले में होता है?", ["किन्नौर", "कुल्लू", "मंडी", "शिमला"], "कोटगढ़, कोटखाई, जुब्बल और रोहड़ू जैसे क्षेत्रों वाला शिमला जिला राज्य के सेब उत्पादन का सबसे बड़ा हिस्सा देता है।"]),
  q(0, "hp-gk", "economy", "M", 0,
    ["Which is the principal Kharif cereal crop of Himachal Pradesh, grown mostly in the mid-hills on rain-fed land?", ["Maize", "Rice", "Bajra", "Sorghum"], "Maize is the main Kharif crop of the state by area, while wheat is the main Rabi crop. Rice is grown in valleys such as Kangra."],
    ["हिमाचल प्रदेश की मुख्य खरीफ़ अनाज फ़सल कौन-सी है, जो मुख्यतः मध्य पहाड़ी वर्षा-आधारित भूमि में उगाई जाती है?", ["मक्का", "धान", "बाजरा", "ज्वार"], "क्षेत्रफल की दृष्टि से मक्का राज्य की मुख्य खरीफ़ फ़सल है, जबकि गेहूँ मुख्य रबी फ़सल है। धान कांगड़ा जैसी घाटियों में उगता है।"]),
  q(0, "hp-gk", "economy", "M", 1,
    ["Sirmaur district is a leading producer of which cash crop and spice?", ["Saffron", "Ginger", "Cardamom", "Black pepper"], "Sirmaur is the leading ginger-growing district of Himachal Pradesh. Saffron is grown in Kashmir and cardamom and pepper in Kerala."],
    ["सिरमौर जिला किस नकदी फ़सल और मसाले का प्रमुख उत्पादक है?", ["केसर", "अदरक", "इलायची", "काली मिर्च"], "सिरमौर हिमाचल प्रदेश का प्रमुख अदरक उत्पादक जिला है। केसर कश्मीर में और इलायची व काली मिर्च केरल में उगती है।"]),
  q(0, "hp-gk", "economy", "H", 2,
    ["The ICAR Directorate of Mushroom Research, because of which a town is called the 'Mushroom City of India', is located in which district?", ["Kangra", "Mandi", "Solan", "Kullu"], "The Directorate of Mushroom Research is at Chambaghat in Solan district, which is also known for its tomato crop."],
    ["ICAR का मशरूम अनुसंधान निदेशालय, जिसके कारण एक नगर को 'भारत का मशरूम नगर' कहा जाता है, किस जिले में है?", ["कांगड़ा", "मंडी", "सोलन", "कुल्लू"], "मशरूम अनुसंधान निदेशालय सोलन जिले के चंबाघाट में है। सोलन टमाटर की फ़सल के लिए भी प्रसिद्ध है।"]),
  q(0, "hp-gk", "economy", "H", 0,
    ["The rock salt (sendha namak) mines of Guma and Drang are located in which district?", ["Mandi", "Sirmaur", "Bilaspur", "Kangra"], "The rock salt deposits of Guma and Drang are in Mandi district, which is the main source of rock salt in Himachal Pradesh."],
    ["सेंधा नमक (सिंधव लवण) की खानें गुम्मा और द्रंग किस जिले में हैं?", ["मंडी", "सिरमौर", "बिलासपुर", "कांगड़ा"], "गुम्मा और द्रंग के सेंधा नमक के भंडार मंडी जिले में हैं, जो हिमाचल प्रदेश में सेंधा नमक का मुख्य स्रोत है।"]),
  q(0, "hp-gk", "economy", "H", 1,
    ["The Baspa-II hydroelectric project on the Baspa river in Kinnaur has an installed capacity of:", ["100 MW", "300 MW", "450 MW", "600 MW"], "Baspa-II has three units of 100 MW each, giving 300 MW. It was built as a private sector project on the Baspa, a tributary of the Sutlej."],
    ["किन्नौर में बास्पा नदी पर बनी बास्पा-II जलविद्युत परियोजना की स्थापित क्षमता कितनी है?", ["100 मेगावाट", "300 मेगावाट", "450 मेगावाट", "600 मेगावाट"], "बास्पा-II में 100-100 मेगावाट की तीन इकाइयाँ हैं, यानी कुल 300 मेगावाट। यह सतलुज की सहायक बास्पा नदी पर निजी क्षेत्र की परियोजना के रूप में बनी।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 3,
    ["The Pandoh Dam, which diverts water of the Beas to the Sutlej through a tunnel under the Beas-Sutlej Link project, lies in which district?", ["Kullu", "Kangra", "Bilaspur", "Mandi"], "Pandoh Dam is on the Beas in Mandi district. Its water flows through the Pandoh-Baggi tunnel to Sundernagar and then to the Sutlej, feeding the Dehar power house."],
    ["ब्यास-सतलुज लिंक परियोजना के अंतर्गत ब्यास का पानी सुरंग द्वारा सतलुज में पहुँचाने वाला पंडोह बाँध किस जिले में है?", ["कुल्लू", "कांगड़ा", "बिलासपुर", "मंडी"], "पंडोह बाँध मंडी जिले में ब्यास पर है। इसका पानी पंडोह-बग्गी सुरंग से सुंदरनगर होकर सतलुज में जाता है और देहर बिजलीघर को चलाता है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 2,
    ["'Gobind Sagar', the reservoir of the Bhakra Dam, is named after:", ["Guru Nanak Dev", "Guru Tegh Bahadur", "Guru Gobind Singh", "Guru Arjan Dev"], "The reservoir formed behind the Bhakra Dam on the Sutlej is named Gobind Sagar after the tenth Sikh Guru, Guru Gobind Singh. It extends into Bilaspur district of Himachal Pradesh."],
    ["भाखड़ा बाँध का जलाशय 'गोबिंद सागर' किसके नाम पर है?", ["गुरु नानक देव", "गुरु तेग़ बहादुर", "गुरु गोबिंद सिंह", "गुरु अर्जन देव"], "सतलुज पर भाखड़ा बाँध के पीछे बने जलाशय का नाम दसवें सिख गुरु, गुरु गोबिंद सिंह, के नाम पर गोबिंद सागर है। यह हिमाचल के बिलासपुर जिले तक फैला है।"]),
  q(0, "hp-gk", "economy", "H", 0,
    ["The historic Shanan Power House at Jogindernagar, one of the oldest hydel projects of north India, was built in the 1930s under the leadership of:", ["Col. B.C. Batty", "Sir Ganga Ram", "Sir M. Visvesvaraya", "Sir William Willcocks"], "The Shanan project (about 1932) was built by Colonel B.C. Batty, the chief engineer of the Mandi state, using the water of the Uhl river."],
    ["उत्तर भारत की सबसे पुरानी जलविद्युत परियोजनाओं में से एक, जोगिंदरनगर का ऐतिहासिक शानन बिजलीघर 1930 के दशक में किसके नेतृत्व में बना?", ["कर्नल बी.सी. बैटी", "सर गंगा राम", "सर एम. विश्वेश्वरैया", "सर विलियम विलकॉक्स"], "शानन परियोजना (लगभग 1932) मंडी रियासत के मुख्य अभियंता कर्नल बी.सी. बैटी ने उहल नदी के पानी से बनाई।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["Which of the following is NOT one of the five major river systems of Himachal Pradesh?", ["Sutlej", "Jhelum", "Ravi", "Yamuna"], "The five river systems of Himachal Pradesh are the Chenab, Ravi, Beas, Sutlej and Yamuna. The Jhelum does not flow through the state."],
    ["निम्नलिखित में से कौन-सी हिमाचल प्रदेश की पाँच प्रमुख नदी प्रणालियों में शामिल नहीं है?", ["सतलुज", "झेलम", "रावी", "यमुना"], "हिमाचल प्रदेश की पाँच नदी प्रणालियाँ चिनाब, रावी, ब्यास, सतलुज और यमुना हैं। झेलम राज्य से होकर नहीं बहती।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["How many National Parks does Himachal Pradesh have?", ["3", "4", "6", "5"], "The five are the Great Himalayan, Pin Valley, Inderkilla, Khirganga and Simbalbara (Sher Jang) National Parks."],
    ["हिमाचल प्रदेश में कितने राष्ट्रीय उद्यान हैं?", ["3", "4", "6", "5"], "पाँच उद्यान हैं: ग्रेट हिमालयन, पिन वैली, इंद्रकिला, खीरगंगा और सिंबलबाड़ा (शेर जंग) राष्ट्रीय उद्यान।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["Which is the state animal of Himachal Pradesh?", ["Musk deer", "Himalayan tahr", "Snow leopard", "Himalayan black bear"], "The snow leopard is the state animal of Himachal Pradesh. It lives in the high cold desert of Lahaul & Spiti and Kinnaur. The state bird is the western tragopan."],
    ["हिमाचल प्रदेश का राज्य पशु कौन-सा है?", ["कस्तूरी मृग", "हिमालयी तहर", "हिम तेंदुआ", "हिमालयी काला भालू"], "हिम तेंदुआ हिमाचल प्रदेश का राज्य पशु है। यह लाहौल-स्पीति और किन्नौर के ऊँचे ठंडे मरुस्थल में रहता है। राज्य पक्षी पश्चिमी ट्रैगोपैन है।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["Which is the state tree of Himachal Pradesh?", ["Deodar", "Chir pine", "Blue pine", "Oak"], "The deodar (Cedrus deodara), meaning 'tree of the gods', is the state tree of Himachal Pradesh."],
    ["हिमाचल प्रदेश का राज्य वृक्ष कौन-सा है?", ["देवदार", "चीड़", "कैल (नीला चीड़)", "बाँज"], "देवदार (सीडरस देवदारा), जिसका अर्थ 'देवताओं का वृक्ष' है, हिमाचल प्रदेश का राज्य वृक्ष है।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["The Kalatop-Khajjiar Wildlife Sanctuary, known for its deodar forests, is in which district?", ["Kangra", "Chamba", "Kullu", "Mandi"], "Kalatop-Khajjiar Wildlife Sanctuary lies near Dalhousie in Chamba district."],
    ["देवदार के वनों के लिए प्रसिद्ध कालाटोप-खज्जियार वन्यजीव अभयारण्य किस जिले में है?", ["कांगड़ा", "चंबा", "कुल्लू", "मंडी"], "कालाटोप-खज्जियार वन्यजीव अभयारण्य चंबा जिले में डलहौज़ी के पास है।"]),
  q(0, "hp-gk", "geography", "H", 3,
    ["The Sarahan Pheasantry, which breeds pheasants including the state bird, the western tragopan, is in which district?", ["Kullu", "Chamba", "Kinnaur", "Shimla"], "The Sarahan Pheasantry is at Sarahan near Rampur Bushahr in Shimla district, close to the Bhimakali temple."],
    ["राज्य पक्षी पश्चिमी ट्रैगोपैन सहित अन्य तीतर-प्रजातियों का प्रजनन करने वाली सराहन फ़ीज़ेंटरी किस जिले में है?", ["कुल्लू", "चंबा", "किन्नौर", "शिमला"], "सराहन फ़ीज़ेंटरी शिमला जिले में रामपुर बुशहर के पास सराहन में, भीमाकाली मंदिर के निकट है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 0,
    ["Which of these rivers rises in the Great Himalayan National Park area and is a tributary of the Beas?", ["Tirthan", "Giri", "Pabbar", "Baspa"], "The Tirthan rises from the glaciers in the Great Himalayan National Park and joins the Beas near Larji. The Giri, Pabbar and Baspa belong to the Yamuna and Sutlej systems."],
    ["इनमें से कौन-सी नदी ग्रेट हिमालयन राष्ट्रीय उद्यान क्षेत्र से निकलती है और ब्यास की सहायक नदी है?", ["तीर्थन", "गिरि", "पब्बर", "बास्पा"], "तीर्थन ग्रेट हिमालयन राष्ट्रीय उद्यान के हिमनदों से निकलकर लारजी के पास ब्यास में मिलती है। गिरि, पब्बर और बास्पा यमुना व सतलुज प्रणाली की नदियाँ हैं।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["The Pong Dam Lake Wildlife Sanctuary, a Ramsar wetland visited by migratory birds such as the bar-headed goose, lies in which district?", ["Una", "Hamirpur", "Kangra", "Bilaspur"], "The Pong Dam lake (Maharana Pratap Sagar) and its wildlife sanctuary are in Kangra district, and it is a major winter home of migratory waterfowl."],
    ["पोंग बाँध झील वन्यजीव अभयारण्य, जो रामसर स्थल है और जहाँ बार-हेडेड गूज़ जैसे प्रवासी पक्षी आते हैं, किस जिले में है?", ["ऊना", "हमीरपुर", "कांगड़ा", "बिलासपुर"], "पोंग बाँध झील (महाराणा प्रताप सागर) और उसका अभयारण्य कांगड़ा जिले में हैं और यह प्रवासी जलपक्षियों का प्रमुख शीतकालीन आवास है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["Which tribe of Himachal Pradesh, found mainly in the Bharmour area of Chamba, is known for seasonal migration with sheep and goat flocks?", ["Gujjar", "Gaddi", "Kinnaura", "Lahaula"], "The Gaddis of Bharmour and the Dhauladhar slopes are transhumant shepherds who move their flocks between the high pastures and the lower hills. The Gujjars are nomadic buffalo herders."],
    ["हिमाचल प्रदेश की कौन-सी जनजाति, जो मुख्यतः चंबा के भरमौर क्षेत्र में रहती है, भेड़-बकरियों के साथ मौसमी प्रवास के लिए जानी जाती है?", ["गुज्जर", "गद्दी", "किन्नौरा", "लाहौला"], "भरमौर और धौलाधार ढलानों के गद्दी घुमंतू चरवाहे हैं जो अपने झुंड ऊँचे चरागाहों और निचली पहाड़ियों के बीच ले जाते हैं। गुज्जर घुमंतू भैंस-पालक हैं।"]),
  q(0, "hp-gk", "districts", "H", 3,
    ["Along with Kinnaur and Lahaul & Spiti, the tribal (Scheduled) areas of Himachal Pradesh include Pangi and which other area of Chamba district?", ["Churah", "Dalhousie", "Chowari", "Bharmour"], "The tribal areas of Himachal Pradesh are Kinnaur, Lahaul & Spiti and the Pangi and Bharmour areas (sub-divisions) of Chamba."],
    ["किन्नौर और लाहौल-स्पीति के साथ हिमाचल प्रदेश के जनजातीय (अनुसूचित) क्षेत्रों में पांगी और चंबा जिले का कौन-सा अन्य क्षेत्र शामिल है?", ["चुराह", "डलहौज़ी", "चौवारी", "भरमौर"], "हिमाचल प्रदेश के जनजातीय क्षेत्र किन्नौर, लाहौल-स्पीति तथा चंबा के पांगी और भरमौर क्षेत्र (उप-मंडल) हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Hattee community of the Trans-Giri area, which has been granted Scheduled Tribe status, lives in which district?", ["Sirmaur", "Shimla", "Solan", "Kullu"], "The Hattee community lives in the Trans-Giri area of Sirmaur district, on the Himachal side of the Giri and Tons valleys, and is known for its 'Khumbli' council system."],
    ["ट्रांस-गिरि क्षेत्र का हाटी समुदाय, जिसे अनुसूचित जनजाति का दर्जा मिला है, किस जिले में रहता है?", ["सिरमौर", "शिमला", "सोलन", "कुल्लू"], "हाटी समुदाय सिरमौर जिले के ट्रांस-गिरि क्षेत्र में रहता है और अपनी 'खुम्बली' पंचायत व्यवस्था के लिए जाना जाता है।"]),
  q(0, "hp-gk", "economy", "H", 1,
    ["As per Census 2011, the population of Himachal Pradesh was about:", ["60.8 lakh", "68.6 lakh", "72.5 lakh", "75.9 lakh"], "The 2011 Census counted 68,64,602 persons in Himachal Pradesh, with a literacy rate of about 82.8%."],
    ["जनगणना 2011 के अनुसार हिमाचल प्रदेश की जनसंख्या लगभग कितनी थी?", ["60.8 लाख", "68.6 लाख", "72.5 लाख", "75.9 लाख"], "जनगणना 2011 में हिमाचल प्रदेश में 68,64,602 व्यक्ति गिने गए और साक्षरता दर लगभग 82.8% थी।"]),
  q(0, "hp-gk", "polity-administration", "M", 2,
    ["Who took oath as the Chief Minister of Himachal Pradesh in December 2022?", ["Jai Ram Thakur", "Mukesh Agnihotri", "Sukhvinder Singh Sukhu", "Prem Kumar Dhumal"], "Sukhvinder Singh Sukhu of the Congress, from Hamirpur district, was sworn in as Chief Minister in December 2022 after the Assembly election. Mukesh Agnihotri became Deputy Chief Minister."],
    ["दिसंबर 2022 में हिमाचल प्रदेश के मुख्यमंत्री पद की शपथ किसने ली?", ["जय राम ठाकुर", "मुकेश अग्निहोत्री", "सुखविंदर सिंह सुक्खू", "प्रेम कुमार धूमल"], "हमीरपुर जिले के कांग्रेस नेता सुखविंदर सिंह सुक्खू ने विधानसभा चुनाव के बाद दिसंबर 2022 में मुख्यमंत्री पद की शपथ ली। मुकेश अग्निहोत्री उपमुख्यमंत्री बने।"]),

  // ───────── Section 1: General Knowledge (25) ─────────
  q(1, "general-studies", "indian-history", "H", 1,
    ["The Subsidiary Alliance system, under which Indian rulers accepted a British force and a Resident at their courts, was introduced by:", ["Lord Cornwallis", "Lord Wellesley", "Lord Dalhousie", "Lord Hastings"], "Lord Wellesley (1798-1805) used the Subsidiary Alliance to control Indian states. The Nizam of Hyderabad was the first to accept it, in 1798."],
    ["सहायक संधि प्रणाली, जिसमें भारतीय शासक अंग्रेज़ी सेना और रेज़ीडेंट को अपने दरबार में स्वीकार करते थे, किसने शुरू की?", ["लॉर्ड कॉर्नवालिस", "लॉर्ड वेलेज़ली", "लॉर्ड डलहौज़ी", "लॉर्ड हेस्टिंग्स"], "लॉर्ड वेलेज़ली (1798-1805) ने भारतीय रियासतों पर नियंत्रण के लिए सहायक संधि का प्रयोग किया। हैदराबाद का निज़ाम 1798 में इसे स्वीकार करने वाला पहला शासक था।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Gandhi suddenly withdrew the Non-Cooperation Movement in February 1922 after violence at:", ["Chauri Chaura", "Champaran", "Kheda", "Bardoli"], "A mob burnt a police station at Chauri Chaura (Gorakhpur, Uttar Pradesh) on 5 February 1922, killing 22 policemen. Gandhi then called off the movement."],
    ["फ़रवरी 1922 में गांधीजी ने किस स्थान पर हुई हिंसा के बाद असहयोग आंदोलन अचानक वापस ले लिया?", ["चौरी-चौरा", "चंपारण", "खेड़ा", "बारदोली"], "5 फ़रवरी 1922 को चौरी-चौरा (गोरखपुर, उत्तर प्रदेश) में भीड़ ने थाना जला दिया, जिसमें 22 पुलिसकर्मी मारे गए। इसके बाद गांधीजी ने आंदोलन वापस ले लिया।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["In the Second Battle of Panipat (1556), the forces of Akbar under Bairam Khan defeated:", ["Rana Sanga", "Ibrahim Lodi", "Hemu", "Daud Khan Karrani"], "Hemu, the Hindu general and minister of the Sur ruler Adil Shah, was defeated at Panipat in 1556, which restored Mughal rule in north India."],
    ["पानीपत के द्वितीय युद्ध (1556) में बैरम खाँ के नेतृत्व में अकबर की सेना ने किसे हराया?", ["राणा साँगा", "इब्राहिम लोदी", "हेमू", "दाऊद खाँ कर्रानी"], "सूर शासक आदिल शाह के हिंदू सेनापति और मंत्री हेमू को 1556 में पानीपत में हराया गया, जिससे उत्तर भारत में मुग़ल शासन पुनः स्थापित हुआ।"]),
  q(1, "general-studies", "indian-polity", "H", 1,
    ["The Fundamental Duties were added to the Constitution by the 42nd Amendment on the recommendation of the:", ["Sarkaria Commission", "Swaran Singh Committee", "Balwant Rai Mehta Committee", "Ashok Mehta Committee"], "The Swaran Singh Committee (1976) recommended Fundamental Duties, which were inserted as Part IVA (Article 51A) by the 42nd Amendment."],
    ["मौलिक कर्तव्य 42वें संशोधन द्वारा संविधान में किसकी सिफ़ारिश पर जोड़े गए?", ["सरकारिया आयोग", "स्वर्ण सिंह समिति", "बलवंत राय मेहता समिति", "अशोक मेहता समिति"], "स्वर्ण सिंह समिति (1976) ने मौलिक कर्तव्यों की सिफ़ारिश की, जिन्हें 42वें संशोधन द्वारा भाग IVक (अनुच्छेद 51क) के रूप में जोड़ा गया।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["The Finance Commission, which recommends the sharing of tax revenue between the Union and the States, is constituted under which Article?", ["Article 266", "Article 275", "Article 112", "Article 280"], "Article 280 provides for a Finance Commission every five years. Article 275 deals with grants-in-aid and Article 112 with the annual financial statement."],
    ["संघ और राज्यों के बीच कर राजस्व के बँटवारे की सिफ़ारिश करने वाला वित्त आयोग किस अनुच्छेद के अंतर्गत गठित होता है?", ["अनुच्छेद 266", "अनुच्छेद 275", "अनुच्छेद 112", "अनुच्छेद 280"], "अनुच्छेद 280 प्रत्येक पाँच वर्ष में वित्त आयोग का प्रावधान करता है। अनुच्छेद 275 सहायता अनुदान से और अनुच्छेद 112 वार्षिक वित्तीय विवरण से संबंधित है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["The Eleventh Schedule of the Constitution, added by the 73rd Amendment, lists the functions of:", ["Municipalities", "Panchayats", "State Legislatures", "Union Territories"], "The Eleventh Schedule lists 29 subjects for Panchayats. The Twelfth Schedule (74th Amendment) lists 18 functions of Municipalities."],
    ["73वें संशोधन द्वारा जोड़ी गई संविधान की ग्यारहवीं अनुसूची किसके कार्यों की सूची है?", ["नगरपालिकाओं", "पंचायतों", "राज्य विधानमंडलों", "संघ राज्य क्षेत्रों"], "ग्यारहवीं अनुसूची में पंचायतों के 29 विषय हैं। बारहवीं अनुसूची (74वाँ संशोधन) में नगरपालिकाओं के 18 कार्य हैं।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["The Jog Falls (Gersoppa Falls) are formed on which river?", ["Kaveri", "Tungabhadra", "Sharavati", "Krishna"], "The Jog Falls, one of the highest waterfalls of India, are on the Sharavati river in Karnataka."],
    ["जोग प्रपात (गेरसोप्पा प्रपात) किस नदी पर बना है?", ["कावेरी", "तुंगभद्रा", "शरावती", "कृष्णा"], "भारत के सबसे ऊँचे जलप्रपातों में से एक जोग प्रपात कर्नाटक में शरावती नदी पर है।"]),
  q(1, "general-studies", "indian-geography", "H", 0,
    ["India's longest National Highway, NH 44 (about 3,745 km), connects:", ["Srinagar and Kanniyakumari", "Delhi and Kolkata", "Mumbai and Chennai", "Amritsar and Guwahati"], "NH 44 (formerly NH 7) runs from Srinagar in Jammu & Kashmir to Kanniyakumari in Tamil Nadu through Delhi, Nagpur, Hyderabad and Bengaluru."],
    ["भारत का सबसे लंबा राष्ट्रीय राजमार्ग NH 44 (लगभग 3,745 किमी) किन्हें जोड़ता है?", ["श्रीनगर और कन्याकुमारी", "दिल्ली और कोलकाता", "मुंबई और चेन्नई", "अमृतसर और गुवाहाटी"], "NH 44 (पूर्व में NH 7) जम्मू-कश्मीर के श्रीनगर से तमिलनाडु के कन्याकुमारी तक दिल्ली, नागपुर, हैदराबाद और बेंगलुरु होकर जाता है।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["According to the India State of Forest Report, which state has the largest forest cover in terms of area?", ["Arunachal Pradesh", "Chhattisgarh", "Odisha", "Madhya Pradesh"], "Madhya Pradesh has the largest forest cover by area. Arunachal Pradesh is next, and Mizoram has the highest forest cover as a percentage of its area among the big states."],
    ["भारत वन स्थिति रिपोर्ट के अनुसार क्षेत्रफल की दृष्टि से सबसे अधिक वन आवरण किस राज्य में है?", ["अरुणाचल प्रदेश", "छत्तीसगढ़", "ओडिशा", "मध्य प्रदेश"], "क्षेत्रफल के अनुसार सबसे अधिक वन आवरण मध्य प्रदेश में है। उसके बाद अरुणाचल प्रदेश आता है।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["NITI Aayog, which replaced the Planning Commission, came into existence on:", ["1 January 2015", "15 August 2014", "26 January 2015", "1 April 2015"], "NITI Aayog (National Institution for Transforming India) was formed on 1 January 2015 by a Cabinet resolution, replacing the Planning Commission."],
    ["योजना आयोग की जगह लेने वाला नीति आयोग किस तिथि को अस्तित्व में आया?", ["1 जनवरी 2015", "15 अगस्त 2014", "26 जनवरी 2015", "1 अप्रैल 2015"], "नीति आयोग (नेशनल इंस्टीट्यूशन फ़ॉर ट्रांसफ़ॉर्मिंग इंडिया) का गठन मंत्रिमंडल के प्रस्ताव द्वारा 1 जनवरी 2015 को हुआ और इसने योजना आयोग का स्थान लिया।"]),
  q(1, "general-studies", "indian-economy", "H", 2,
    ["The Securities and Exchange Board of India (SEBI) was given statutory powers by an Act of Parliament in the year:", ["1988", "1999", "1992", "2003"], "SEBI was set up in 1988 as an administrative body and given statutory status by the SEBI Act of 1992."],
    ["भारतीय प्रतिभूति और विनिमय बोर्ड (सेबी) को संसद के अधिनियम द्वारा वैधानिक शक्तियाँ किस वर्ष दी गईं?", ["1988", "1999", "1992", "2003"], "सेबी की स्थापना 1988 में प्रशासनिक निकाय के रूप में हुई और 1992 के सेबी अधिनियम द्वारा इसे वैधानिक दर्जा मिला।"]),
  q(1, "general-studies", "indian-economy", "M", 3,
    ["Under the PM-KISAN scheme, eligible farmer families get direct income support of ₹6,000 a year, paid in:", ["Two equal instalments", "Four equal instalments", "Twelve monthly instalments", "Three equal instalments"], "PM-KISAN gives ₹6,000 per year to eligible farmer families in three equal instalments of ₹2,000 each, transferred directly to bank accounts."],
    ["पीएम-किसान योजना में पात्र किसान परिवारों को ₹6,000 प्रति वर्ष की प्रत्यक्ष आय सहायता किस प्रकार मिलती है?", ["दो समान किस्तों में", "चार समान किस्तों में", "बारह मासिक किस्तों में", "तीन समान किस्तों में"], "पीएम-किसान में पात्र किसान परिवारों को ₹6,000 प्रति वर्ष ₹2,000 की तीन समान किस्तों में सीधे बैंक खाते में मिलता है।"]),
  q(1, "general-studies", "indian-economy", "H", 1,
    ["The Unified Payments Interface (UPI), launched in 2016, was developed by:", ["RBI", "NPCI", "NABARD", "SEBI"], "UPI was developed by the National Payments Corporation of India (NPCI), an umbrella organisation for retail payments set up in 2008 with the guidance of the RBI and the Indian Banks' Association."],
    ["2016 में शुरू किया गया एकीकृत भुगतान इंटरफ़ेस (UPI) किसने विकसित किया?", ["RBI", "NPCI", "नाबार्ड", "सेबी"], "UPI को नेशनल पेमेंट्स कॉरपोरेशन ऑफ़ इंडिया (NPCI) ने विकसित किया, जिसे 2008 में RBI और भारतीय बैंक संघ के मार्गदर्शन में खुदरा भुगतान की संस्था के रूप में बनाया गया।"]),
  q(1, "general-studies", "indian-economy", "H", 2,
    ["The Fiscal Responsibility and Budget Management (FRBM) Act, which sets targets for reducing the fiscal deficit, was enacted in the year:", ["1991", "2008", "2003", "2011"], "The FRBM Act was passed in 2003 (in force from 2004) to bring fiscal discipline and cut the fiscal deficit."],
    ["राजकोषीय घाटा घटाने के लक्ष्य तय करने वाला राजकोषीय उत्तरदायित्व और बजट प्रबंधन (FRBM) अधिनियम किस वर्ष बना?", ["1991", "2008", "2003", "2011"], "FRBM अधिनियम 2003 में पारित हुआ (2004 से लागू) ताकि राजकोषीय अनुशासन आए और राजकोषीय घाटा घटे।"]),
  q(1, "general-studies", "indian-economy", "H", 0,
    ["Which sector of the Indian economy employs the largest share of the workforce, though its share in GDP is the smallest among the three broad sectors?", ["Agriculture and allied", "Industry", "Services", "Construction"], "Agriculture and allied activities employ nearly half of the workforce but contribute only about a sixth or so of gross value added. Services contribute the largest share of GDP."],
    ["भारतीय अर्थव्यवस्था का कौन-सा क्षेत्र कार्यबल का सबसे बड़ा हिस्सा रोज़गार देता है, जबकि तीनों प्रमुख क्षेत्रों में GDP में उसका हिस्सा सबसे कम है?", ["कृषि एवं संबद्ध", "उद्योग", "सेवाएँ", "निर्माण"], "कृषि एवं संबद्ध गतिविधियाँ लगभग आधे कार्यबल को रोज़गार देती हैं, पर सकल मूल्य वर्धन में उनका हिस्सा केवल छठे भाग के आसपास है। GDP में सबसे बड़ा हिस्सा सेवा क्षेत्र का है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["In August 2023, India's Chandrayaan-3 lander made a soft landing on the Moon near its:", ["Equator", "North polar region", "Far side", "South polar region"], "Vikram lander touched down on 23 August 2023 in the Moon's south polar region, making India the first country to land there and the fourth to soft-land on the Moon."],
    ["अगस्त 2023 में भारत के चंद्रयान-3 के लैंडर ने चंद्रमा के किस क्षेत्र के पास सॉफ़्ट लैंडिंग की?", ["विषुवत रेखा", "उत्तरी ध्रुवीय क्षेत्र", "सुदूर भाग", "दक्षिणी ध्रुवीय क्षेत्र"], "विक्रम लैंडर 23 अगस्त 2023 को चंद्रमा के दक्षिणी ध्रुवीय क्षेत्र में उतरा; भारत वहाँ उतरने वाला पहला और चंद्रमा पर सॉफ़्ट लैंडिंग करने वाला चौथा देश बना।"]),
  q(1, "general-studies", "general-science", "H", 0,
    ["India's solar mission Aditya-L1 is placed near the Lagrange point L1, which is about how far from the Earth?", ["About 1.5 million km", "About 3.8 lakh km", "About 15 million km", "About 150 million km"], "The L1 point lies about 1.5 million km from the Earth towards the Sun, so the spacecraft can watch the Sun continuously. About 3.8 lakh km is the Earth-Moon distance."],
    ["भारत का सौर मिशन आदित्य-L1 लैग्रेंज बिंदु L1 के पास स्थित है, जो पृथ्वी से लगभग कितनी दूरी पर है?", ["लगभग 15 लाख किमी", "लगभग 3.8 लाख किमी", "लगभग 1.5 करोड़ किमी", "लगभग 15 करोड़ किमी"], "L1 बिंदु पृथ्वी से सूर्य की ओर लगभग 15 लाख किमी दूर है, जिससे यान सूर्य को लगातार देख सकता है। लगभग 3.8 लाख किमी पृथ्वी-चंद्रमा की दूरी है।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["NavIC (Navigation with Indian Constellation), India's regional satellite navigation system, was developed by:", ["DRDO", "ISRO", "BEL", "NRSC"], "NavIC, formerly the Indian Regional Navigation Satellite System (IRNSS), was developed by ISRO and covers India and a region up to about 1,500 km around it."],
    ["भारत की क्षेत्रीय उपग्रह नौवहन प्रणाली NavIC (नाविक) किसने विकसित की?", ["DRDO", "ISRO", "BEL", "NRSC"], "NavIC, जिसे पहले IRNSS कहा जाता था, ISRO ने विकसित की और यह भारत तथा उसके लगभग 1,500 किमी तक के क्षेत्र को कवर करती है।"]),
  q(1, "general-studies", "general-science", "H", 2,
    ["Optical fibres carry light signals over long distances by the principle of:", ["Diffraction", "Polarisation", "Total internal reflection", "Interference"], "Light entering the core of an optical fibre strikes the core-cladding boundary beyond the critical angle and is totally reflected again and again along the fibre."],
    ["ऑप्टिकल फ़ाइबर प्रकाश संकेतों को लंबी दूरी तक किस सिद्धांत से ले जाते हैं?", ["विवर्तन", "ध्रुवण", "पूर्ण आंतरिक परावर्तन", "व्यतिकरण"], "फ़ाइबर के कोर में प्रवेश करने वाला प्रकाश कोर-क्लैडिंग सीमा पर क्रांतिक कोण से अधिक कोण पर टकराता है और बार-बार पूर्ण परावर्तित होकर आगे बढ़ता है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["Which gas or plant hormone is used to ripen fruits such as bananas artificially?", ["Auxin", "Gibberellin", "Cytokinin", "Ethylene"], "Ethylene is the natural fruit-ripening hormone, and it is used in controlled amounts in ripening chambers. Calcium carbide is banned for ripening because it is harmful."],
    ["केले जैसे फलों को कृत्रिम रूप से पकाने के लिए किस गैस या पादप हार्मोन का प्रयोग होता है?", ["ऑक्सिन", "जिबरेलिन", "साइटोकाइनिन", "एथिलीन"], "एथिलीन फल पकाने वाला प्राकृतिक हार्मोन है और इसे नियंत्रित मात्रा में पकाने वाले कक्षों में प्रयोग किया जाता है। हानिकारक होने के कारण कैल्शियम कार्बाइड से पकाना प्रतिबंधित है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["Dengue fever is spread by the bite of which mosquito?", ["Anopheles", "Culex", "Aedes", "Mansonia"], "Dengue is spread by the Aedes (Aedes aegypti) mosquito, which breeds in clean stagnant water. Anopheles spreads malaria and Culex spreads filariasis."],
    ["डेंगू बुखार किस मच्छर के काटने से फैलता है?", ["एनोफ़िलीज़", "क्यूलेक्स", "एडीज़", "मैनसोनिया"], "डेंगू एडीज़ (एडीज़ एजिप्टी) मच्छर से फैलता है, जो साफ़ ठहरे पानी में पनपता है। एनोफ़िलीज़ मलेरिया और क्यूलेक्स फाइलेरिया फैलाता है।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["The Montreal Protocol (1987) is an international agreement to protect the:", ["Ozone layer", "Wetlands", "Whales", "Biodiversity"], "The Montreal Protocol phases out substances such as CFCs that damage the ozone layer."],
    ["मॉन्ट्रियल प्रोटोकॉल (1987) किसकी रक्षा के लिए अंतरराष्ट्रीय समझौता है?", ["ओज़ोन परत", "आर्द्रभूमियाँ", "व्हेल", "जैव विविधता"], "मॉन्ट्रियल प्रोटोकॉल क्लोरोफ़्लोरोकार्बन (CFC) जैसे उन पदार्थों को चरणबद्ध रूप से बंद करता है जो ओज़ोन परत को नुकसान पहुँचाते हैं।"]),
  q(1, "general-studies", "general-science", "H", 1,
    ["A rocket moves forward in space on the principle of:", ["Bernoulli's principle", "Conservation of linear momentum", "Archimedes' principle", "Conservation of mass only"], "Hot gases are thrown backward at high speed, so by conservation of linear momentum (Newton's third law) the rocket gains momentum in the forward direction."],
    ["अंतरिक्ष में रॉकेट किस सिद्धांत पर आगे बढ़ता है?", ["बरनौली का सिद्धांत", "रेखीय संवेग संरक्षण", "आर्किमिडीज़ का सिद्धांत", "केवल द्रव्यमान संरक्षण"], "गर्म गैसें तेज़ गति से पीछे की ओर फेंकी जाती हैं, अतः रेखीय संवेग संरक्षण (न्यूटन के तीसरे नियम) से रॉकेट को आगे की दिशा में संवेग मिलता है।"]),
  q(1, "computer", "security", "H", 1,
    ["In a computer network, a firewall is used to:", ["Speed up downloads", "Monitor and filter incoming and outgoing network traffic", "Remove viruses only", "Increase the storage space"], "A firewall applies security rules to block unauthorised traffic and allow safe traffic. It is not an antivirus and does not speed up or store anything."],
    ["कंप्यूटर नेटवर्क में फ़ायरवॉल का प्रयोग किसलिए होता है?", ["डाउनलोड तेज़ करने के लिए", "आने-जाने वाले नेटवर्क ट्रैफ़िक की निगरानी और छँटाई के लिए", "केवल वायरस हटाने के लिए", "स्टोरेज बढ़ाने के लिए"], "फ़ायरवॉल सुरक्षा नियम लगाकर अनधिकृत ट्रैफ़िक को रोकता और सुरक्षित ट्रैफ़िक को जाने देता है। यह एंटीवायरस नहीं है और न गति बढ़ाता है, न स्टोरेज।"]),
  q(1, "computer", "internet-networking", "H", 2,
    ["HTTPS protects the data exchanged between a browser and a website by using which technology?", ["FTP", "SMTP", "SSL/TLS", "DNS"], "HTTPS is HTTP over SSL/TLS, which encrypts the data so that it cannot be read or altered on the way. FTP moves files, SMTP sends e-mail and DNS resolves domain names."],
    ["HTTPS ब्राउज़र और वेबसाइट के बीच के डेटा की सुरक्षा किस तकनीक से करता है?", ["FTP", "SMTP", "SSL/TLS", "DNS"], "HTTPS, SSL/TLS पर चलने वाला HTTP है, जो डेटा को एन्क्रिप्ट करता है ताकि रास्ते में उसे पढ़ा या बदला न जा सके। FTP फ़ाइलें भेजता है, SMTP ई-मेल और DNS डोमेन नाम का पता बताता है।"]),

  // ───────── Section 2: Reasoning (20) ─────────
  q(2, "reasoning", "series", "H", 0,
    ["Find the next number: 6, 13, 28, 59, 122, ?", ["249", "243", "245", "255"], "Each term is twice the previous one plus 1, 2, 3, 4, ...: 6×2+1 = 13, 13×2+2 = 28, 28×2+3 = 59, 59×2+4 = 122. So the next is 122×2+5 = 249."],
    ["अगली संख्या ज्ञात कीजिए: 6, 13, 28, 59, 122, ?", ["249", "243", "245", "255"], "प्रत्येक पद पिछले पद का दुगुना + 1, 2, 3, 4, ... है: 6×2+1 = 13, 13×2+2 = 28, 28×2+3 = 59, 59×2+4 = 122। अतः अगला 122×2+5 = 249।"], "122*2+5"),
  q(2, "reasoning", "series", "M", 3,
    ["Find the next number: 2, 9, 28, 65, 126, ?", ["189", "216", "343", "217"], "The terms are n³ + 1: 1³+1, 2³+1, 3³+1, 4³+1, 5³+1. The next is 6³ + 1 = 217."],
    ["अगली संख्या ज्ञात कीजिए: 2, 9, 28, 65, 126, ?", ["189", "216", "343", "217"], "पद n³ + 1 हैं: 1³+1, 2³+1, 3³+1, 4³+1, 5³+1। अगला 6³ + 1 = 217 है।"], "6**3+1"),
  q(2, "reasoning", "series", "H", 1,
    ["Find the next term: AB, DE, HI, MN, ?", ["RS", "ST", "TU", "SU"], "The first letters are at positions 1, 4, 8, 13, with gaps 3, 4, 5, so the next gap is 6 and the next position is 19 (S). The second letter is the one after it, T. So the term is ST."],
    ["अगला पद ज्ञात कीजिए: AB, DE, HI, MN, ?", ["RS", "ST", "TU", "SU"], "पहले अक्षरों के क्रमांक 1, 4, 8, 13 हैं, अंतर 3, 4, 5। अगला अंतर 6 है, अतः क्रमांक 19 (S)। दूसरा अक्षर उसके बाद का T है। अतः पद ST है।"]),
  q(2, "reasoning", "series", "H", 2,
    ["Find the wrong term in the series: 3, 7, 15, 31, 61, 127", ["7", "31", "61", "127"], "Each term is twice the previous term plus 1: 3, 7, 15, 31, 63, 127. So 61 is wrong; it should be 63."],
    ["श्रेणी में गलत पद ज्ञात कीजिए: 3, 7, 15, 31, 61, 127", ["7", "31", "61", "127"], "प्रत्येक पद पिछले पद का दुगुना + 1 है: 3, 7, 15, 31, 63, 127। अतः 61 गलत है; यह 63 होना चाहिए।"], "61"),
  q(2, "reasoning", "coding-decoding", "M", 0,
    ["In a certain code, BORDER is written as ANQCDQ. How will STATION be written in that code?", ["RSZSHNM", "TUBUJPO", "RSZTHNM", "RSZSGNM"], "Each letter moves one step back: B→A, O→N, R→Q, D→C, E→D, R→Q. So S→R, T→S, A→Z, T→S, I→H, O→N, N→M gives RSZSHNM."],
    ["एक कोड में BORDER को ANQCDQ लिखा जाता है। उसी कोड में STATION को कैसे लिखा जाएगा?", ["RSZSHNM", "TUBUJPO", "RSZTHNM", "RSZSGNM"], "प्रत्येक अक्षर एक स्थान पीछे जाता है: B→A, O→N, R→Q, D→C, E→D, R→Q। अतः S→R, T→S, A→Z, T→S, I→H, O→N, N→M से RSZSHNM।"]),
  q(2, "reasoning", "coding-decoding", "H", 2,
    ["In a code language, 'red blue green' is written as 'pa ma ta', 'blue yellow' as 'ma ka' and 'green yellow white' as 'ta ka sa'. What is the code for 'red'?", ["ma", "ka", "pa", "sa"], "'blue' is common to the first two, so blue = ma. 'green' is common to the first and third, so green = ta. Then, in the first sentence, red = pa."],
    ["एक कोड भाषा में 'red blue green' को 'pa ma ta', 'blue yellow' को 'ma ka' और 'green yellow white' को 'ta ka sa' लिखा जाता है। 'red' का कोड क्या है?", ["ma", "ka", "pa", "sa"], "'blue' पहले दो वाक्यों में समान है, अतः blue = ma। 'green' पहले और तीसरे में समान है, अतः green = ta। तब पहले वाक्य में red = pa।"]),
  q(2, "reasoning", "math-operations", "H", 3,
    ["If 4 # 3 = 19, 5 # 2 = 27 and 6 # 4 = 40, then 7 # 3 = ?", ["46", "49", "55", "52"], "The rule is a # b = a² + b: 4² + 3 = 19, 5² + 2 = 27, 6² + 4 = 40. So 7 # 3 = 49 + 3 = 52."],
    ["यदि 4 # 3 = 19, 5 # 2 = 27 और 6 # 4 = 40 हो, तो 7 # 3 = ?", ["46", "49", "55", "52"], "नियम a # b = a² + b है: 4² + 3 = 19, 5² + 2 = 27, 6² + 4 = 40। अतः 7 # 3 = 49 + 3 = 52।"], "49+3"),
  q(2, "reasoning", "blood-relations", "H", 0,
    ["P is the mother of R. R is the father of S. T is the brother of P. How is T related to S?", ["Grand-uncle", "Uncle", "Grandfather", "Brother-in-law"], "P is S's paternal grandmother (mother of S's father R). P's brother T is therefore S's paternal grand-uncle."],
    ["P, R की माता है। R, S का पिता है। T, P का भाई है। T का S से क्या संबंध है?", ["दादी का भाई (ग्रैंड-अंकल)", "चाचा", "दादा", "बहनोई"], "P, S की दादी है (S के पिता R की माता)। अतः P का भाई T, S का पिता-पक्ष का 'ग्रैंड-अंकल' (दादी का भाई) है।"]),
  q(2, "reasoning", "blood-relations", "M", 1,
    ["Amit says to Sunita, 'Your mother's only brother is the father of my wife.' How is Sunita related to Amit's wife?", ["Sister", "Cousin", "Aunt", "Niece"], "Sunita's mother's brother is Sunita's maternal uncle. His daughter is Amit's wife, so the two women are cousins."],
    ["अमित सुनीता से कहता है, 'आपकी माँ का इकलौता भाई मेरी पत्नी का पिता है।' सुनीता का अमित की पत्नी से क्या संबंध है?", ["बहन", "चचेरी/ममेरी बहन", "बुआ/मौसी", "भतीजी/भांजी"], "सुनीता की माँ का भाई सुनीता का मामा है। उसकी पुत्री अमित की पत्नी है, अतः दोनों ममेरी बहनें हैं।"]),
  q(2, "reasoning", "direction-sense", "M", 2,
    ["A person walks 14 m north, turns right and walks 6 m, then turns right again and walks 6 m. How far is he from the starting point?", ["8 m", "12 m", "10 m", "14 m"], "He goes 14 m north, 6 m east and then 6 m south. He is 6 m east and 8 m north of the start, so the distance is √(6² + 8²) = √100 = 10 m."],
    ["एक व्यक्ति 14 मी उत्तर की ओर चलता है, दाएँ मुड़कर 6 मी चलता है, फिर दाएँ मुड़कर 6 मी चलता है। वह प्रारंभिक बिंदु से कितनी दूर है?", ["8 मी", "12 मी", "10 मी", "14 मी"], "वह 14 मी उत्तर, 6 मी पूर्व और फिर 6 मी दक्षिण जाता है। वह प्रारंभ से 6 मी पूर्व और 8 मी उत्तर में है, अतः दूरी √(6² + 8²) = √100 = 10 मी।"], "Math.sqrt(6*6+8*8)"),
  q(2, "reasoning", "direction-sense", "H", 3,
    ["Rahul faces north-west. He turns 90° clockwise, then 45° anticlockwise and then 180°. Which direction is he facing now?", ["North", "East", "North-East", "South"], "North-west → 90° clockwise → north-east → 45° anticlockwise → north → 180° → south."],
    ["राहुल का मुँह उत्तर-पश्चिम की ओर है। वह 90° दक्षिणावर्त, फिर 45° वामावर्त और फिर 180° मुड़ता है। अब उसका मुँह किस दिशा में है?", ["उत्तर", "पूर्व", "उत्तर-पूर्व", "दक्षिण"], "उत्तर-पश्चिम → 90° दक्षिणावर्त → उत्तर-पूर्व → 45° वामावर्त → उत्तर → 180° → दक्षिण।"]),
  q(2, "reasoning", "ranking", "H", 1,
    ["In a class, Kiran ranks 15th from the top. Lata is 8 places below Kiran, and Lata is 20th from the bottom. How many students are there in the class?", ["40", "42", "41", "43"], "Lata is 15 + 8 = 23rd from the top. Total = 23 + 20 − 1 = 42."],
    ["एक कक्षा में किरण ऊपर से 15वें स्थान पर है। लता, किरण से 8 स्थान नीचे है और नीचे से 20वें स्थान पर है। कक्षा में कितने छात्र हैं?", ["40", "42", "41", "43"], "लता ऊपर से 15 + 8 = 23वें स्थान पर है। कुल = 23 + 20 − 1 = 42।"], "23+20-1"),
  q(2, "reasoning", "puzzles", "H", 3,
    ["Six friends A, B, C, D, E and F live on different floors of a six-storey building (floor 1 is the lowest). E lives on floor 1 and F on floor 3. B lives immediately above F. A lives immediately above D, and D lives above B. Who lives on the 2nd floor?", ["D", "A", "B", "C"], "F is on 3 and B is immediately above, so B is on 4. D is above B, so D is on 5 or 6. A is immediately above D, so D is on 5 and A on 6. The only person left for floor 2 is C."],
    ["छह मित्र A, B, C, D, E और F छह मंज़िला इमारत की अलग-अलग मंज़िलों पर रहते हैं (मंज़िल 1 सबसे नीचे है)। E मंज़िल 1 पर और F मंज़िल 3 पर रहता है। B, F के ठीक ऊपर रहता है। A, D के ठीक ऊपर रहता है और D, B से ऊपर रहता है। दूसरी मंज़िल पर कौन रहता है?", ["D", "A", "B", "C"], "F मंज़िल 3 पर है और B ठीक ऊपर, यानी 4 पर। D, B से ऊपर है, अतः 5 या 6 पर। A, D के ठीक ऊपर है, इसलिए D 5 पर और A 6 पर है। दूसरी मंज़िल के लिए केवल C बचता है।"]),
  q(2, "reasoning", "analogy", "M", 0,
    ["Thermometer : Temperature :: Barometer : ?", ["Atmospheric pressure", "Humidity", "Wind speed", "Rainfall"], "A thermometer measures temperature; in the same way, a barometer measures atmospheric pressure."],
    ["थर्मामीटर : तापमान :: बैरोमीटर : ?", ["वायुमंडलीय दाब", "आर्द्रता", "पवन वेग", "वर्षा"], "थर्मामीटर तापमान मापता है; उसी प्रकार बैरोमीटर वायुमंडलीय दाब मापता है।"]),
  q(2, "reasoning", "inequality", "H", 1,
    ["Statements: A ≥ B > C, D < C ≤ E. Conclusions: I. A > D. II. E ≥ B.", ["Only conclusion II follows", "Only conclusion I follows", "Both I and II follow", "Neither I nor II follows"], "From A ≥ B > C > D, we get A > D, so I follows. For II, E ≥ C and B > C give no link between E and B, so II does not follow."],
    ["कथन: A ≥ B > C, D < C ≤ E. निष्कर्ष: I. A > D. II. E ≥ B.", ["केवल निष्कर्ष II अनुसरण करता है", "केवल निष्कर्ष I अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "A ≥ B > C > D से A > D मिलता है, अतः I सही है। II के लिए E ≥ C और B > C से E और B का कोई संबंध नहीं बनता, अतः II अनुसरण नहीं करता।"]),
  q(2, "reasoning", "odd-one-out", "H", 3,
    ["Find the odd one out: NQT, UXA, BEH, DGK", ["NQT", "UXA", "BEH", "DGK"], "In NQT, UXA and BEH each letter is 3 places after the previous one. In DGK the steps are 3 and then 4 (D→G→K), so DGK is the odd one."],
    ["विषम चुनिए: NQT, UXA, BEH, DGK", ["NQT", "UXA", "BEH", "DGK"], "NQT, UXA और BEH में प्रत्येक अक्षर पिछले से 3 स्थान आगे है। DGK में अंतर पहले 3 और फिर 4 है (D→G→K), अतः DGK विषम है।"]),
  q(2, "reasoning", "syllogism", "H", 2,
    ["Statements: Some fans are coolers. All coolers are heaters. No heater is a geyser. Conclusions: I. Some fans are heaters. II. No cooler is a geyser. III. Some fans are not geysers.", ["Only I and II follow", "Only II and III follow", "All I, II and III follow", "Only I follows"], "Some fans are coolers and all coolers are heaters, so some fans are heaters (I). All coolers are heaters and no heater is a geyser, so no cooler is a geyser (II). Those fans that are coolers are not geysers, so some fans are not geysers (III)."],
    ["कथन: कुछ पंखे कूलर हैं। सभी कूलर हीटर हैं। कोई हीटर गीज़र नहीं है। निष्कर्ष: I. कुछ पंखे हीटर हैं। II. कोई कूलर गीज़र नहीं है। III. कुछ पंखे गीज़र नहीं हैं।", ["केवल I और II अनुसरण करते हैं", "केवल II और III अनुसरण करते हैं", "I, II और III तीनों अनुसरण करते हैं", "केवल I अनुसरण करता है"], "कुछ पंखे कूलर हैं और सभी कूलर हीटर हैं, अतः कुछ पंखे हीटर हैं (I)। सभी कूलर हीटर हैं और कोई हीटर गीज़र नहीं, अतः कोई कूलर गीज़र नहीं (II)। जो पंखे कूलर हैं वे गीज़र नहीं हैं, अतः कुछ पंखे गीज़र नहीं हैं (III)।"]),
  q(2, "reasoning", "syllogism", "M", 1,
    ["Statements: Some teachers are doctors. Some doctors are engineers. Conclusions: I. Some teachers are engineers. II. Some engineers are doctors.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "Two 'some' statements give no definite link between teachers and engineers, so I does not follow. 'Some doctors are engineers' can be reversed to 'some engineers are doctors', so II follows."],
    ["कथन: कुछ शिक्षक डॉक्टर हैं। कुछ डॉक्टर इंजीनियर हैं। निष्कर्ष: I. कुछ शिक्षक इंजीनियर हैं। II. कुछ इंजीनियर डॉक्टर हैं।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "दो 'कुछ' वाले कथनों से शिक्षकों और इंजीनियरों का कोई निश्चित संबंध नहीं बनता, अतः I अनुसरण नहीं करता। 'कुछ डॉक्टर इंजीनियर हैं' का उलटा 'कुछ इंजीनियर डॉक्टर हैं' है, अतः II अनुसरण करता है।"]),
  q(2, "reasoning", "clock-calendar", "H", 2,
    ["What is the angle between the hour hand and the minute hand of a clock at 5:40?", ["60°", "80°", "70°", "90°"], "At 5:40 the hour hand is at 5 × 30 + 40 × 0.5 = 170° and the minute hand is at 40 × 6 = 240°. The angle is 240 − 170 = 70°."],
    ["घड़ी में 5:40 बजे घंटे की सुई और मिनट की सुई के बीच कितना कोण होता है?", ["60°", "80°", "70°", "90°"], "5:40 पर घंटे की सुई 5 × 30 + 40 × 0.5 = 170° पर और मिनट की सुई 40 × 6 = 240° पर होती है। कोण = 240 − 170 = 70°।"], "240-170"),
  q(2, "reasoning", "clock-calendar", "H", 3,
    ["If 12 November 2026 is a Thursday, on which day of the week did 12 November 2025 fall?", ["Monday", "Tuesday", "Friday", "Wednesday"], "The period from 12 November 2025 to 12 November 2026 is 365 days (no 29 February falls in it), i.e. 52 weeks and 1 odd day. So the earlier date is one day before Thursday, which is Wednesday."],
    ["यदि 12 नवंबर 2026 को गुरुवार है, तो 12 नवंबर 2025 को सप्ताह का कौन-सा दिन था?", ["सोमवार", "मंगलवार", "शुक्रवार", "बुधवार"], "12 नवंबर 2025 से 12 नवंबर 2026 तक 365 दिन (बीच में 29 फ़रवरी नहीं) यानी 52 सप्ताह और 1 विषम दिन है। अतः पहले की तिथि गुरुवार से एक दिन पहले, यानी बुधवार थी।"]),

  // ───────── Section 3: Numerical Ability (15) ─────────
  q(3, "quant", "percentage", "H", 2,
    ["The value of a machine falls by 10% every year. If its present value is ₹72,900, what was its value 2 years ago?", ["₹85,000", "₹88,000", "₹90,000", "₹92,500"], "If the value 2 years ago was V, then V × 0.9 × 0.9 = 72,900. So V = 72,900 ÷ 0.81 = ₹90,000."],
    ["एक मशीन का मूल्य प्रतिवर्ष 10% घटता है। यदि उसका वर्तमान मूल्य ₹72,900 है, तो 2 वर्ष पहले उसका मूल्य क्या था?", ["₹85,000", "₹88,000", "₹90,000", "₹92,500"], "यदि 2 वर्ष पहले मूल्य V था, तो V × 0.9 × 0.9 = 72,900। अतः V = 72,900 ÷ 0.81 = ₹90,000।"], "72900/0.81"),
  q(3, "quant", "profit-loss", "H", 3,
    ["A trader allows a 25% discount on the marked price and still makes a profit of 20%. By what percent is the marked price above the cost price?", ["50%", "62.5%", "80%", "60%"], "0.75 × MP = 1.2 × CP, so MP = 1.6 × CP. The marked price is 60% above the cost price."],
    ["एक व्यापारी अंकित मूल्य पर 25% छूट देता है और फिर भी 20% लाभ कमाता है। अंकित मूल्य क्रय मूल्य से कितने प्रतिशत अधिक है?", ["50%", "62.5%", "80%", "60%"], "0.75 × अंकित मूल्य = 1.2 × क्रय मूल्य, अतः अंकित मूल्य = 1.6 × क्रय मूल्य। अंकित मूल्य क्रय मूल्य से 60% अधिक है।"], "(1.2/0.75-1)*100"),
  q(3, "quant", "interest", "H", 0,
    ["A sum invested at 20% per annum compound interest (compounded annually) amounts to ₹17,280 in 3 years. What is the sum?", ["₹10,000", "₹9,000", "₹10,800", "₹12,000"], "17,280 = P × (1.2)³ = P × 1.728. So P = 17,280 ÷ 1.728 = ₹10,000."],
    ["20% वार्षिक चक्रवृद्धि ब्याज (वार्षिक संयोजन) पर निवेश की गई राशि 3 वर्ष में ₹17,280 हो जाती है। राशि कितनी है?", ["₹10,000", "₹9,000", "₹10,800", "₹12,000"], "17,280 = P × (1.2)³ = P × 1.728। अतः P = 17,280 ÷ 1.728 = ₹10,000।"], "17280/1.2**3"),
  q(3, "quant", "time-work", "H", 1,
    ["A can do 1/4 of a work in 5 days and B can do 1/3 of the same work in 10 days. In how many days can they finish the work together?", ["10", "12", "15", "18"], "A alone takes 5 × 4 = 20 days and B alone takes 10 × 3 = 30 days. Together: 20 × 30 ÷ (20 + 30) = 12 days."],
    ["A किसी काम का 1/4 भाग 5 दिन में और B उसी काम का 1/3 भाग 10 दिन में कर सकता है। दोनों मिलकर काम कितने दिन में पूरा करेंगे?", ["10", "12", "15", "18"], "A अकेला 5 × 4 = 20 दिन और B अकेला 10 × 3 = 30 दिन लेता है। साथ में: 20 × 30 ÷ (20 + 30) = 12 दिन।"], "20*30/(20+30)"),
  q(3, "quant", "speed-distance", "M", 2,
    ["A boat covers 6 km downstream in 30 minutes and takes 45 minutes to return upstream. What is the speed of the stream?", ["1 km/h", "1.5 km/h", "2 km/h", "3 km/h"], "Downstream speed = 6 ÷ 0.5 = 12 km/h. Upstream speed = 6 ÷ 0.75 = 8 km/h. Stream speed = (12 − 8) ÷ 2 = 2 km/h."],
    ["एक नाव 6 किमी धारा के अनुकूल 30 मिनट में तय करती है और धारा के प्रतिकूल लौटने में 45 मिनट लेती है। धारा की चाल क्या है?", ["1 किमी/घंटा", "1.5 किमी/घंटा", "2 किमी/घंटा", "3 किमी/घंटा"], "अनुकूल चाल = 6 ÷ 0.5 = 12 किमी/घंटा। प्रतिकूल चाल = 6 ÷ 0.75 = 8 किमी/घंटा। धारा की चाल = (12 − 8) ÷ 2 = 2 किमी/घंटा।"], "(6/0.5-6/0.75)/2"),
  q(3, "quant", "speed-distance", "H", 3,
    ["A train crosses a pole in 15 seconds and a 100 m long platform in 25 seconds. What is the length of the train?", ["100 m", "120 m", "180 m", "150 m"], "The extra 100 m takes 25 − 15 = 10 seconds, so the speed is 10 m/s. Length of train = 10 × 15 = 150 m."],
    ["एक रेलगाड़ी एक खंभे को 15 सेकंड में और 100 मी लंबे प्लेटफ़ॉर्म को 25 सेकंड में पार करती है। रेलगाड़ी की लंबाई क्या है?", ["100 मी", "120 मी", "180 मी", "150 मी"], "अतिरिक्त 100 मी में 25 − 15 = 10 सेकंड लगते हैं, अतः चाल 10 मी/से है। रेलगाड़ी की लंबाई = 10 × 15 = 150 मी।"], "100*15/(25-15)"),
  q(3, "quant", "average", "M", 0,
    ["The average weight of 8 persons increases by 2.5 kg when a person weighing 65 kg is replaced by a new person. What is the weight of the new person?", ["85 kg", "80 kg", "82 kg", "90 kg"], "Total weight increases by 8 × 2.5 = 20 kg. New person's weight = 65 + 20 = 85 kg."],
    ["8 व्यक्तियों का औसत भार 2.5 किग्रा बढ़ जाता है जब 65 किग्रा भार वाले एक व्यक्ति की जगह नया व्यक्ति आता है। नए व्यक्ति का भार कितना है?", ["85 किग्रा", "80 किग्रा", "82 किग्रा", "90 किग्रा"], "कुल भार 8 × 2.5 = 20 किग्रा बढ़ता है। नए व्यक्ति का भार = 65 + 20 = 85 किग्रा।"], "65+8*2.5"),
  q(3, "quant", "ages", "H", 1,
    ["The present ages of P and Q are in the ratio 5 : 3. After 4 years the ratio will be 3 : 2. What is P's present age?", ["15 years", "20 years", "25 years", "30 years"], "Let the ages be 5x and 3x. (5x + 4) ÷ (3x + 4) = 3/2 gives 10x + 8 = 9x + 12, so x = 4. P's age = 5 × 4 = 20 years."],
    ["P और Q की वर्तमान आयु का अनुपात 5 : 3 है। 4 वर्ष बाद अनुपात 3 : 2 हो जाएगा। P की वर्तमान आयु क्या है?", ["15 वर्ष", "20 वर्ष", "25 वर्ष", "30 वर्ष"], "मान लें आयु 5x और 3x है। (5x + 4) ÷ (3x + 4) = 3/2 से 10x + 8 = 9x + 12, अतः x = 4। P की आयु = 5 × 4 = 20 वर्ष।"], "5*4"),
  q(3, "quant", "mixture-alligation", "H", 2,
    ["In what ratio should water be mixed with milk costing ₹60 per litre so that the mixture is worth ₹48 per litre?", ["1 : 5", "2 : 5", "1 : 4", "1 : 3"], "Water costs 0 and milk ₹60, mean price ₹48. Water : milk = (60 − 48) : (48 − 0) = 12 : 48 = 1 : 4."],
    ["₹60 प्रति लीटर वाले दूध में पानी किस अनुपात में मिलाया जाए कि मिश्रण का मूल्य ₹48 प्रति लीटर हो?", ["1 : 5", "2 : 5", "1 : 4", "1 : 3"], "पानी का मूल्य 0 और दूध का ₹60 है, माध्य मूल्य ₹48। पानी : दूध = (60 − 48) : (48 − 0) = 12 : 48 = 1 : 4।"]),
  q(3, "quant", "mensuration", "H", 2,
    ["If the radius of a cylinder is doubled and its height is halved, its volume:", ["Remains the same", "Becomes half", "Increases by 100%", "Increases by 50%"], "Volume is proportional to r² × h. New volume = 2² × 1/2 = 2 times the old volume, i.e. an increase of 100%."],
    ["यदि किसी बेलन की त्रिज्या दुगुनी और ऊँचाई आधी कर दी जाए, तो उसका आयतन:", ["वही रहेगा", "आधा हो जाएगा", "100% बढ़ जाएगा", "50% बढ़ जाएगा"], "आयतन r² × h के समानुपाती है। नया आयतन = 2² × 1/2 = पुराने का 2 गुना, यानी 100% की वृद्धि।"], "(2*2*0.5-1)*100"),
  q(3, "quant", "geometry", "M", 3,
    ["The diagonal of a rectangle is 25 cm and one of its sides is 7 cm. What is its perimeter?", ["56 cm", "64 cm", "50 cm", "62 cm"], "The other side = √(25² − 7²) = √576 = 24 cm. Perimeter = 2 × (7 + 24) = 62 cm."],
    ["एक आयत का विकर्ण 25 सेमी और एक भुजा 7 सेमी है। उसका परिमाप क्या है?", ["56 सेमी", "64 सेमी", "50 सेमी", "62 सेमी"], "दूसरी भुजा = √(25² − 7²) = √576 = 24 सेमी। परिमाप = 2 × (7 + 24) = 62 सेमी।"], "2*(7+24)"),
  q(3, "quant", "hcf-lcm", "H", 2,
    ["The LCM of two numbers is 180 and their HCF is 6. If one of the numbers is 30, what is the other number?", ["24", "30", "36", "45"], "Product of the numbers = HCF × LCM = 6 × 180 = 1,080. The other number = 1,080 ÷ 30 = 36."],
    ["दो संख्याओं का LCM 180 और HCF 6 है। यदि एक संख्या 30 है, तो दूसरी संख्या क्या है?", ["24", "30", "36", "45"], "संख्याओं का गुणनफल = HCF × LCM = 6 × 180 = 1,080। दूसरी संख्या = 1,080 ÷ 30 = 36।"], "6*180/30"),
  q(3, "quant", "number-system", "H", 0,
    ["What is the sum of all two-digit numbers that are divisible by 7?", ["728", "735", "686", "770"], "The numbers are 14, 21, ..., 98, which are 13 terms. Sum = 13 × (14 + 98) ÷ 2 = 13 × 56 = 728."],
    ["7 से विभाज्य सभी दो अंकों की संख्याओं का योग कितना है?", ["728", "735", "686", "770"], "संख्याएँ 14, 21, ..., 98 हैं, जो 13 पद हैं। योग = 13 × (14 + 98) ÷ 2 = 13 × 56 = 728।"], "13*(14+98)/2"),
  q(3, "quant", "algebra", "H", 3,
    ["The sum of two numbers is 45 and their difference is 9. What is their product?", ["504", "440", "520", "486"], "The numbers are (45 + 9) ÷ 2 = 27 and (45 − 9) ÷ 2 = 18. Product = 27 × 18 = 486."],
    ["दो संख्याओं का योग 45 और अंतर 9 है। उनका गुणनफल क्या है?", ["504", "440", "520", "486"], "संख्याएँ (45 + 9) ÷ 2 = 27 और (45 − 9) ÷ 2 = 18 हैं। गुणनफल = 27 × 18 = 486।"], "27*18"),
  q(3, "quant", "speed-distance", "M", 2,
    ["A vehicle travels 60 km at 30 km/h and returns the same distance at 20 km/h. What is its average speed for the whole journey?", ["25 km/h", "28 km/h", "24 km/h", "26 km/h"], "Total distance = 120 km. Time = 60 ÷ 30 + 60 ÷ 20 = 2 + 3 = 5 hours. Average speed = 120 ÷ 5 = 24 km/h."],
    ["एक वाहन 60 किमी की दूरी 30 किमी/घंटा से तय करता है और उसी दूरी को 20 किमी/घंटा से लौटता है। पूरी यात्रा की औसत चाल क्या है?", ["25 किमी/घंटा", "28 किमी/घंटा", "24 किमी/घंटा", "26 किमी/घंटा"], "कुल दूरी = 120 किमी। समय = 60 ÷ 30 + 60 ÷ 20 = 2 + 3 = 5 घंटे। औसत चाल = 120 ÷ 5 = 24 किमी/घंटा।"], "2*30*20/(30+20)"),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "english", "grammar", "H", 3,
    ["Fill in the blank: 'The teacher, along with her students, ___ visiting the museum.'", ["are", "were", "have been", "is"], "The verb agrees with the main subject 'The teacher', not with the phrase 'along with her students'. So the singular verb 'is' is used."],
    ["रिक्त स्थान भरिए: 'The teacher, along with her students, ___ visiting the museum.'", ["are", "were", "have been", "is"], "क्रिया मुख्य कर्ता 'The teacher' के अनुसार आती है, 'along with her students' के अनुसार नहीं। अतः एकवचन क्रिया 'is' आएगी।"]),
  q(4, "english", "grammar", "H", 1,
    ["Fill in the blank: 'It is high time we ___ this problem.'", ["solve", "solved", "shall solve", "are solving"], "After 'It is high time', the verb takes the simple past form even though the sense is present: 'It is high time we solved this problem.'"],
    ["रिक्त स्थान भरिए: 'It is high time we ___ this problem.'", ["solve", "solved", "shall solve", "are solving"], "'It is high time' के बाद अर्थ वर्तमान का होने पर भी क्रिया का सरल भूतकाल रूप आता है: 'It is high time we solved this problem.'"]),
  q(4, "english", "synonyms-antonyms", "H", 2,
    ["Choose the synonym of 'EPHEMERAL':", ["Eternal", "Fragile", "Short-lived", "Sudden"], "'Ephemeral' means lasting for a very short time. 'Eternal' is its opposite."],
    ["'EPHEMERAL' का समानार्थी शब्द चुनिए:", ["Eternal", "Fragile", "Short-lived", "Sudden"], "'Ephemeral' का अर्थ है बहुत थोड़े समय तक टिकने वाला। 'Eternal' इसका विलोम है।"]),
  q(4, "english", "synonyms-antonyms", "M", 1,
    ["Choose the antonym of 'FRUGAL':", ["Thrifty", "Extravagant", "Careful", "Stingy"], "'Frugal' means careful about spending money. Its opposite is 'extravagant', meaning wasteful with money."],
    ["'FRUGAL' का विलोम शब्द चुनिए:", ["Thrifty", "Extravagant", "Careful", "Stingy"], "'Frugal' का अर्थ है खर्च में सावधानी बरतने वाला, मितव्ययी। इसका विलोम 'extravagant' (फ़िज़ूलख़र्च) है।"]),
  q(4, "english", "one-word", "H", 3,
    ["One word for 'a system of government run by a small group of powerful people':", ["Autocracy", "Theocracy", "Democracy", "Oligarchy"], "Oligarchy is rule by a few. Autocracy is rule by one person, theocracy by religious leaders and democracy by the people."],
    ["'शक्तिशाली लोगों के एक छोटे समूह द्वारा चलाई जाने वाली शासन व्यवस्था' के लिए एक शब्द:", ["Autocracy", "Theocracy", "Democracy", "Oligarchy"], "Oligarchy (अल्पतंत्र) कुछ लोगों का शासन है। Autocracy एक व्यक्ति का, theocracy धार्मिक नेताओं का और democracy जनता का शासन है।"]),
  q(4, "english", "idioms", "M", 0,
    ["Choose the meaning of the idiom 'to let the cat out of the bag':", ["To reveal a secret by mistake", "To cause a fight", "To lose something valuable", "To escape from danger"], "To let the cat out of the bag means to disclose a secret, usually by accident."],
    ["मुहावरे 'to let the cat out of the bag' का अर्थ चुनिए:", ["गलती से कोई रहस्य खोल देना", "झगड़ा करवा देना", "कोई कीमती चीज़ खो देना", "खतरे से बच निकलना"], "इसका अर्थ है किसी रहस्य को, प्रायः अनजाने में, प्रकट कर देना।"]),
  q(4, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'The furniture in the room / were made / of teak. / No error'", ["The furniture in the room", "were made", "of teak.", "No error"], "'Furniture' is an uncountable noun and takes a singular verb. It should be 'was made'."],
    ["त्रुटि वाला भाग चुनिए: 'The furniture in the room / were made / of teak. / No error'", ["The furniture in the room", "were made", "of teak.", "No error"], "'Furniture' अगणनीय संज्ञा है और एकवचन क्रिया लेती है। सही रूप 'was made' है।"]),
  q(4, "english", "voice-speech", "H", 2,
    ["Change into indirect speech: He said, 'Alas! I am ruined.'", ["He said that alas he was ruined.", "He exclaimed that he had been ruined.", "He exclaimed sadly that he was ruined.", "He said sorrowfully that I was ruined."], "The exclamation 'Alas!' is shown by 'exclaimed sadly', the pronoun 'I' becomes 'he' and the present tense 'am' becomes past 'was'."],
    ["अप्रत्यक्ष कथन में बदलिए: He said, 'Alas! I am ruined.'", ["He said that alas he was ruined.", "He exclaimed that he had been ruined.", "He exclaimed sadly that he was ruined.", "He said sorrowfully that I was ruined."], "विस्मयादिबोधक 'Alas!' को 'exclaimed sadly' से दर्शाया जाता है, 'I' का 'he' और वर्तमान 'am' का भूतकाल 'was' हो जाता है।"]),
  q(4, "hindi", "sandhi-samas", "H", 2,
    ["Choose the correct split of the sandhi word 'परोपकार':", ["परः + उपकार", "परो + पकार", "पर + उपकार", "पर + ओपकार"], "'परोपकार' = पर + उपकार. The 'अ' and 'उ' combine to form 'ओ', which is a guna sandhi."],
    ["'परोपकार' का सही संधि-विच्छेद चुनिए:", ["परः + उपकार", "परो + पकार", "पर + उपकार", "पर + ओपकार"], "'परोपकार' = पर + उपकार। 'अ' और 'उ' मिलकर 'ओ' बन जाते हैं, यह गुण संधि है।"]),
  q(4, "hindi", "sandhi-samas", "M", 1,
    ["Identify the type of compound (samas) in 'यथाशक्ति' (as per one's strength):", ["Tatpurush", "Avyayibhava", "Bahuvrihi", "Dvandva"], "'यथाशक्ति' = शक्ति के अनुसार. The first part 'यथा' is an indeclinable and is the main word, so it is an Avyayibhava samas."],
    ["'यथाशक्ति' शब्द में कौन-सा समास है?", ["तत्पुरुष", "अव्ययीभाव", "बहुव्रीहि", "द्वंद्व"], "'यथाशक्ति' = शक्ति के अनुसार। पहला पद 'यथा' अव्यय है और वही प्रधान है, अतः अव्ययीभाव समास है।"]),
  q(4, "hindi", "muhavare", "M", 3,
    ["What is the meaning of the Hindi idiom 'अँधेरे में तीर चलाना'?", ["To hunt at night", "To attack the enemy secretly", "To practise archery", "To act blindly without proper knowledge"], "The idiom means to act or guess without knowing the facts, hoping to hit the mark by chance."],
    ["'अँधेरे में तीर चलाना' मुहावरे का अर्थ है:", ["रात में शिकार करना", "शत्रु पर चुपके से हमला करना", "तीरंदाज़ी का अभ्यास करना", "बिना जानकारी के अंदाज़े से काम करना"], "इस मुहावरे का अर्थ है तथ्यों को जाने बिना अंदाज़े से काम करना और संयोग से निशाना लग जाने की आशा रखना।"]),
  q(4, "hindi", "muhavare", "H", 0,
    ["What does the Hindi proverb 'नाच न जाने आँगन टेढ़ा' mean?", ["To blame others or the circumstances for one's own lack of skill", "To be too proud to dance", "To dance only at home", "To dance to another's tune"], "The proverb (lokokti) is used for a person who cannot do a thing well but blames the tools or circumstances."],
    ["लोकोक्ति 'नाच न जाने आँगन टेढ़ा' का अर्थ है:", ["अपनी अयोग्यता का दोष दूसरों या परिस्थितियों पर डालना", "नाचने में बहुत घमंडी होना", "केवल घर में नाचना", "दूसरे के इशारे पर नाचना"], "यह लोकोक्ति उस व्यक्ति के लिए है जो कोई काम ठीक से नहीं कर पाता और दोष साधनों या परिस्थितियों को देता है।"]),
  q(4, "hindi", "paryay-vilom", "H", 3,
    ["Which of these is NOT a synonym of 'सागर' (sea)?", ["जलधि", "उदधि", "रत्नाकर", "सरिता"], "जलधि, उदधि and रत्नाकर all mean sea or ocean. 'सरिता' means river."],
    ["निम्नलिखित में से कौन-सा 'सागर' का पर्यायवाची नहीं है?", ["जलधि", "उदधि", "रत्नाकर", "सरिता"], "जलधि, उदधि और रत्नाकर सागर के पर्यायवाची हैं। 'सरिता' का अर्थ नदी है।"]),
  q(4, "hindi", "paryay-vilom", "M", 1,
    ["Choose the antonym of the Hindi word 'स्थावर' (immovable):", ["अचल", "जंगम", "स्थिर", "अटल"], "'स्थावर' means immovable, and its opposite is 'जंगम' (movable). अचल, स्थिर and अटल are its synonyms."],
    ["'स्थावर' शब्द का विलोम चुनिए:", ["अचल", "जंगम", "स्थिर", "अटल"], "'स्थावर' का अर्थ अचल है और इसका विलोम 'जंगम' (चलने वाला) है। अचल, स्थिर और अटल इसके पर्याय हैं।"]),
  q(4, "hindi", "shuddh-vartani", "H", 2,
    ["Choose the correctly spelt Hindi word for 'adornment, make-up':", ["श्रृंगार", "श्रंगार", "शृंगार", "शृगांर"], "The correct spelling is 'शृंगार' (श + ऋ-matra + ंगार). The form 'श्रृंगार' with 'श्र' is a common mistake."],
    ["'सजावट, साज-सिंगार' के लिए शुद्ध वर्तनी वाला शब्द चुनिए:", ["श्रृंगार", "श्रंगार", "शृंगार", "शृगांर"], "शुद्ध वर्तनी 'शृंगार' (श + ऋ की मात्रा + ंगार) है। 'श्र' वाला रूप 'श्रृंगार' एक आम अशुद्धि है।"]),
];
