// HP Police Constable Full Mock 8 — 100 questions (25 HP GK, 25 GK, 20 Reasoning, 15 Maths, 15 Hindi/English).

import { q, type PoliceQuestion } from "./types";

export const mock8: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK (25) ─────────
  q(0, "hp-gk", "districts", "H", 2,
    ["Which of the following district–headquarters pairs is INCORRECT?", ["Sirmaur – Nahan", "Lahaul & Spiti – Keylong", "Kangra – Palampur", "Bilaspur – Bilaspur"], "The district headquarters of Kangra is Dharamshala; Palampur is only a town of the district. Nahan (Sirmaur) and Keylong (Lahaul & Spiti) are correct."],
    ["निम्नलिखित में से जिला–मुख्यालय का कौन-सा युग्म गलत है?", ["सिरमौर – नाहन", "लाहौल-स्पीति – केलांग", "कांगड़ा – पालमपुर", "बिलासपुर – बिलासपुर"], "कांगड़ा जिले का मुख्यालय धर्मशाला है; पालमपुर जिले का केवल एक नगर है। नाहन (सिरमौर) और केलांग (लाहौल-स्पीति) सही हैं।"]),
  q(0, "hp-gk", "polity-administration", "H", 2,
    ["Out of the 68 seats of the Himachal Pradesh Vidhan Sabha, how many are reserved for Scheduled Castes?", ["12", "15", "17", "20"], "Seventeen seats are reserved for Scheduled Castes and three for Scheduled Tribes (Kinnaur, Lahaul & Spiti and Bharmour)."],
    ["हिमाचल प्रदेश विधानसभा की 68 सीटों में से कितनी अनुसूचित जातियों के लिए आरक्षित हैं?", ["12", "15", "17", "20"], "सत्रह सीटें अनुसूचित जातियों के लिए और तीन अनुसूचित जनजातियों (किन्नौर, लाहौल-स्पीति और भरमौर) के लिए आरक्षित हैं।"],
    "17"),
  q(0, "hp-gk", "economy", "M", 1,
    ["The Jaypee University of Information Technology is located at Waknaghat, near:", ["Shimla", "Solan", "Mandi", "Una"], "Waknaghat lies in Solan district, on the Shimla–Solan road, and hosts the Jaypee University of Information Technology."],
    ["जेपी सूचना प्रौद्योगिकी विश्वविद्यालय वाकनाघाट में किस नगर के पास स्थित है?", ["शिमला", "सोलन", "मंडी", "ऊना"], "वाकनाघाट सोलन जिले में शिमला–सोलन मार्ग पर है और यहाँ जेपी सूचना प्रौद्योगिकी विश्वविद्यालय स्थित है।"]),
  q(0, "hp-gk", "economy", "H", 2,
    ["The campus of the Indian Institute of Management (IIM) Sirmaur is at Rampur Ghat near:", ["Nahan", "Solan", "Paonta Sahib", "Rajgarh"], "IIM Sirmaur, started in 2015, has its campus at Rampur Ghat near Paonta Sahib in Sirmaur district."],
    ["भारतीय प्रबंधन संस्थान (IIM) सिरमौर का परिसर रामपुर घाट में किस नगर के पास है?", ["नाहन", "सोलन", "पांवटा साहिब", "राजगढ़"], "2015 में शुरू हुए IIM सिरमौर का परिसर सिरमौर जिले में पांवटा साहिब के पास रामपुर घाट में है।"]),
  q(0, "hp-gk", "economy", "H", 2,
    ["Dr Rajendra Prasad Government Medical College is located at:", ["Shimla", "Nerchowk", "Tanda", "Chamba"], "Dr Rajendra Prasad Government Medical College is at Tanda in Kangra district. Indira Gandhi Medical College is at Shimla."],
    ["डॉ. राजेंद्र प्रसाद राजकीय चिकित्सा महाविद्यालय कहाँ स्थित है?", ["शिमला", "नेरचौक", "टांडा", "चंबा"], "डॉ. राजेंद्र प्रसाद राजकीय चिकित्सा महाविद्यालय कांगड़ा जिले के टांडा में है। इंदिरा गांधी चिकित्सा महाविद्यालय शिमला में है।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["The Viceregal Lodge (Rashtrapati Niwas) at Shimla, now home to the Indian Institute of Advanced Study, was built in 1884–88 for the Viceroy:", ["Lord Curzon", "Lord Dufferin", "Lord Lytton", "Lord Ripon"], "It was built for Lord Dufferin to the design of Henry Irwin. It became the Rashtrapati Niwas after Independence and has housed the IIAS since 1965."],
    ["शिमला का वाइसरीगल लॉज (राष्ट्रपति निवास), जिसमें अब भारतीय उच्च अध्ययन संस्थान है, 1884–88 में किस वायसराय के लिए बना था?", ["लॉर्ड कर्ज़न", "लॉर्ड डफ़रिन", "लॉर्ड लिटन", "लॉर्ड रिपन"], "यह हेनरी इरविन के डिज़ाइन पर लॉर्ड डफ़रिन के लिए बना था। स्वतंत्रता के बाद यह राष्ट्रपति निवास बना और 1965 से यहाँ IIAS है।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["Chail, near Solan, with one of the highest cricket grounds in the world, was once the summer capital of the Maharaja of:", ["Patiala", "Nabha", "Kapurthala", "Faridkot"], "Chail was developed as the summer capital of the Maharaja of Patiala. Its cricket ground lies at about 2,400 m."],
    ["सोलन के पास चायल, जहाँ विश्व के सबसे ऊँचे क्रिकेट मैदानों में से एक है, कभी किस महाराजा की ग्रीष्मकालीन राजधानी था?", ["पटियाला", "नाभा", "कपूरथला", "फ़रीदकोट"], "चायल को पटियाला के महाराजा की ग्रीष्मकालीन राजधानी के रूप में विकसित किया गया था। इसका क्रिकेट मैदान लगभग 2,400 मी की ऊँचाई पर है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["Key (Ki) Monastery, the largest monastery of Spiti and a training centre for lamas, is near:", ["Tabo", "Keylong", "Reckong Peo", "Kaza"], "Key Monastery stands on a hill above the Spiti river a few kilometres from Kaza, the sub-divisional headquarters of Spiti."],
    ["स्पीति का सबसे बड़ा मठ और लामाओं का प्रशिक्षण केंद्र की (Key) मठ किसके निकट है?", ["ताबो", "केलांग", "रिकांग पियो", "काज़ा"], "की मठ स्पीति नदी के ऊपर एक पहाड़ी पर काज़ा से कुछ किलोमीटर दूर है, जो स्पीति का उपमंडल मुख्यालय है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The Gaddi tribe, traditionally shepherds who migrate seasonally with their flocks, has its homeland in:", ["Kinnaur", "Pangi valley", "Lahaul", "Bharmour (Gadderan) in Chamba"], "Bharmour in Chamba district, once called Gadderan, is the traditional homeland of the Gaddis. The Pangi valley is home to the Pangwal tribe."],
    ["परंपरागत रूप से चरवाहे और भेड़ों के साथ मौसमी प्रवास करने वाली गद्दी जनजाति का मूल क्षेत्र कौन-सा है?", ["किन्नौर", "पांगी घाटी", "लाहौल", "भरमौर (गद्देरन), चंबा"], "चंबा जिले का भरमौर, जिसे पहले गद्देरन कहा जाता था, गद्दियों की पारंपरिक मातृभूमि है। पांगी घाटी पंगवाल जनजाति का क्षेत्र है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["'Thangka', seen in the monasteries of Lahaul-Spiti, is a:", ["Woollen shawl weaving", "Tibetan Buddhist painting on cloth", "Style of wood carving", "Metal casting technique"], "A thangka is a Tibetan Buddhist scroll painting on cloth showing deities, mandalas or events from the life of the Buddha."],
    ["लाहौल-स्पीति के मठों में दिखने वाला 'थांगका' क्या है?", ["ऊनी शॉल की बुनाई", "कपड़े पर बनी तिब्बती बौद्ध चित्रकला", "काष्ठ नक्काशी की शैली", "धातु ढलाई की तकनीक"], "थांगका कपड़े पर बनी तिब्बती बौद्ध चित्रकला है, जिसमें देवताओं, मंडलों या बुद्ध के जीवन की घटनाओं का चित्रण होता है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["'Cham' (Chham), performed at the festivals of Buddhist monasteries in Lahaul-Spiti, is a:", ["Harvest dance of Kullu", "Wedding dance of Kangra", "Masked dance performed by lamas", "Warrior dance of Chamba"], "Cham is a ritual masked dance performed by lamas in colourful costumes, symbolising the victory of good over evil."],
    ["लाहौल-स्पीति के बौद्ध मठों के उत्सवों में होने वाला 'छम' (Cham) क्या है?", ["कुल्लू का फ़सल नृत्य", "कांगड़ा का विवाह नृत्य", "लामाओं द्वारा किया जाने वाला मुखौटा नृत्य", "चंबा का योद्धा नृत्य"], "छम लामाओं द्वारा रंग-बिरंगी पोशाकों में किया जाने वाला अनुष्ठानिक मुखौटा नृत्य है, जो बुराई पर अच्छाई की जीत का प्रतीक है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The state-level Holi fair of Himachal Pradesh is held every year at Sujanpur Tihra in which district?", ["Hamirpur", "Una", "Bilaspur", "Kangra"], "Sujanpur Tihra, on the bank of the Beas, lies in Hamirpur district. Its Holi fair, held on the ground called the Chaugan, has been a state-level fair since 2007."],
    ["हिमाचल प्रदेश का राज्य-स्तरीय होली मेला प्रतिवर्ष सुजानपुर टीहरा में लगता है, जो किस जिले में है?", ["हमीरपुर", "ऊना", "बिलासपुर", "कांगड़ा"], "ब्यास के किनारे बसा सुजानपुर टीहरा हमीरपुर जिले में है। चौगान मैदान में लगने वाला इसका होली मेला 2007 से राज्य-स्तरीय मेला है।"]),
  q(0, "hp-gk", "polity-administration", "M", 2,
    ["In 2019, Himachal Pradesh declared which language as its second official language?", ["Punjabi", "Urdu", "Sanskrit", "Pahari"], "The Himachal Pradesh Assembly declared Sanskrit the second official language in 2019, after Uttarakhand did so. Hindi is the first official language."],
    ["2019 में हिमाचल प्रदेश ने किस भाषा को अपनी दूसरी राजभाषा घोषित किया?", ["पंजाबी", "उर्दू", "संस्कृत", "पहाड़ी"], "हिमाचल प्रदेश विधानसभा ने 2019 में उत्तराखंड के बाद संस्कृत को दूसरी राजभाषा घोषित किया। हिंदी पहली राजभाषा है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["Which of the following languages of Himachal Pradesh belongs to the Tibeto-Burman family, unlike the Indo-Aryan Pahari dialects?", ["Kullvi", "Mandeali", "Chambeali", "Kinnauri"], "Kinnauri, spoken in Kinnaur, is a Tibeto-Burman language. Kullvi, Mandeali and Chambeali are Indo-Aryan Pahari languages."],
    ["हिमाचल प्रदेश की निम्नलिखित भाषाओं में से कौन-सी इंडो-आर्यन पहाड़ी बोलियों के विपरीत तिब्बती-बर्मी परिवार की है?", ["कुल्वी", "मंडयाली", "चंबयाली", "किन्नौरी"], "किन्नौर में बोली जाने वाली किन्नौरी तिब्बती-बर्मी भाषा है। कुल्वी, मंडयाली और चंबयाली इंडो-आर्यन पहाड़ी भाषाएँ हैं।"]),
  q(0, "hp-gk", "polity-administration", "M", 1,
    ["For revenue administration, Himachal Pradesh is divided into how many divisions?", ["2", "3", "4", "5"], "The state has three revenue divisions: Shimla, Mandi and Kangra."],
    ["राजस्व प्रशासन के लिए हिमाचल प्रदेश कितने संभागों में बँटा है?", ["2", "3", "4", "5"], "राज्य में तीन राजस्व संभाग हैं: शिमला, मंडी और कांगड़ा।"],
    "3"),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The Pangwal tribe of Himachal Pradesh inhabits which area?", ["Kinnaur", "Pangi valley of Chamba", "Lahaul valley", "Spiti valley"], "The Pangwals live in the remote Pangi valley of Chamba district, which lies in the Pir Panjal range."],
    ["हिमाचल प्रदेश की पंगवाल जनजाति किस क्षेत्र में रहती है?", ["किन्नौर", "चंबा की पांगी घाटी", "लाहौल घाटी", "स्पीति घाटी"], "पंगवाल चंबा जिले की दुर्गम पांगी घाटी में रहते हैं, जो पीर पंजाल श्रेणी में है।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["The name of Shimla is believed to be derived from the name of the goddess:", ["Tara Devi", "Chamunda Devi", "Shyamala Devi", "Naina Devi"], "Shimla is believed to derive its name from Shyamala Devi, a form of Kali, whose temple stood in the area."],
    ["माना जाता है कि शिमला का नाम किस देवी के नाम से लिया गया है?", ["तारा देवी", "चामुंडा देवी", "श्यामला देवी", "नैना देवी"], "माना जाता है कि शिमला का नाम श्यामला देवी, जो काली का रूप हैं, से पड़ा है, जिनका मंदिर इस क्षेत्र में था।"]),
  q(0, "hp-gk", "history", "H", 2,
    ["The first permanent British house at Shimla, built in 1822, was constructed by:", ["William Moorcroft", "Lord Amherst", "Charles Pratt Kennedy", "Lord Dalhousie"], "Charles Pratt Kennedy, the Political Agent for the Hill States, built the first permanent British house (Kennedy House) at Shimla in 1822."],
    ["शिमला में 1822 में बना पहला स्थायी अंग्रेज़ी मकान किसने बनवाया था?", ["विलियम मूरक्रॉफ़्ट", "लॉर्ड एमहर्स्ट", "चार्ल्स प्रैट कैनेडी", "लॉर्ड डलहौज़ी"], "पहाड़ी रियासतों के पॉलिटिकल एजेंट चार्ल्स प्रैट कैनेडी ने 1822 में शिमला में पहला स्थायी अंग्रेज़ी मकान (कैनेडी हाउस) बनवाया।"]),
  q(0, "hp-gk", "history", "H", 2,
    ["The former princely state of Bilaspur (Kahlur) was merged into Himachal Pradesh on 1 July of the year:", ["1948", "1950", "1954", "1956"], "Bilaspur was a separate Part-C state until it was merged with Himachal Pradesh on 1 July 1954."],
    ["पूर्व रियासत बिलासपुर (कहलूर) का हिमाचल प्रदेश में विलय किस वर्ष की 1 जुलाई को हुआ?", ["1948", "1950", "1954", "1956"], "बिलासपुर 1 जुलाई 1954 को हिमाचल प्रदेश में मिलाए जाने तक अलग भाग-ग राज्य था।"],
    "1954"),
  q(0, "hp-gk", "history", "H", 1,
    ["After the First Anglo-Sikh War, the Jalandhar Doab and the hill tracts of Kangra, Kullu and Lahaul-Spiti passed to the British by the Treaty of:", ["Sugauli", "Lahore", "Amritsar", "Yandabo"], "By the Treaty of Lahore (March 1846) the Sikh Darbar ceded the Jalandhar Doab and the hill territories between the Beas and the Sutlej to the British. The Treaty of Sugauli was signed with Nepal."],
    ["प्रथम आंग्ल-सिख युद्ध के बाद जालंधर दोआब तथा कांगड़ा, कुल्लू और लाहौल-स्पीति के पहाड़ी क्षेत्र किस संधि से अंग्रेज़ों को मिले?", ["सुगौली", "लाहौर", "अमृतसर", "यंदाबू"], "लाहौर की संधि (मार्च 1846) द्वारा सिख दरबार ने जालंधर दोआब और ब्यास तथा सतलुज के बीच के पहाड़ी क्षेत्र अंग्रेज़ों को सौंप दिए। सुगौली की संधि नेपाल के साथ हुई थी।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["The 'Dum' agitation, a people's protest against oppressive administration, took place in which princely state of the Himachal hills?", ["Sirmaur", "Bushahr", "Mandi", "Chamba"], "The Dum agitation was a peasant protest against the administration of Bushahr (capital Rampur), one of the important people's movements in the hill states."],
    ["दमनकारी प्रशासन के विरुद्ध जन-विरोध 'दुम' आंदोलन हिमाचल की किस पहाड़ी रियासत में हुआ?", ["सिरमौर", "बुशहर", "मंडी", "चंबा"], "दुम आंदोलन बुशहर (राजधानी रामपुर) के प्रशासन के विरुद्ध किसानों का विरोध था, जो पहाड़ी रियासतों के प्रमुख जन-आंदोलनों में से एक है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Naina Devi temple, a Shakti Peeth famous for its fair during the Shravan Navratras, is located in which district?", ["Una", "Kangra", "Bilaspur", "Mandi"], "The Naina Devi temple stands on a hilltop in Bilaspur district. It is believed to be the place where the eyes of Sati fell."],
    ["श्रावण नवरात्रों के मेले के लिए प्रसिद्ध शक्तिपीठ नैना देवी मंदिर किस जिले में है?", ["ऊना", "कांगड़ा", "बिलासपुर", "मंडी"], "नैना देवी मंदिर बिलासपुर जिले में एक पहाड़ी की चोटी पर है। माना जाता है कि यहाँ सती के नेत्र गिरे थे।"]),
  q(0, "hp-gk", "economy", "M", 3,
    ["Which town of Himachal Pradesh, home to the ICAR Directorate of Mushroom Research, is called the 'Mushroom City of India'?", ["Kullu", "Nahan", "Una", "Solan"], "Solan, where the Directorate of Mushroom Research is located at Chambaghat, is called the Mushroom City of India. It is also known for tomatoes."],
    ["हिमाचल प्रदेश का कौन-सा नगर, जहाँ ICAR का मशरूम अनुसंधान निदेशालय है, 'भारत का मशरूम नगर' कहलाता है?", ["कुल्लू", "नाहन", "ऊना", "सोलन"], "सोलन, जहाँ चंबाघाट में मशरूम अनुसंधान निदेशालय है, 'भारत का मशरूम नगर' कहलाता है। यह टमाटर के लिए भी प्रसिद्ध है।"]),
  q(0, "hp-gk", "economy", "M", 1,
    ["Palampur, in the Kangra valley, is known as the:", ["Apple capital of India", "Tea capital of north-west India", "Mushroom city of India", "Cement capital of Himachal"], "Palampur is surrounded by tea gardens and is called the tea capital of north-west India, because Kangra tea is grown in the valley."],
    ["कांगड़ा घाटी में स्थित पालमपुर को क्या कहा जाता है?", ["भारत की सेब राजधानी", "उत्तर-पश्चिम भारत की चाय राजधानी", "भारत का मशरूम नगर", "हिमाचल की सीमेंट राजधानी"], "पालमपुर चाय बागानों से घिरा है और कांगड़ा चाय घाटी में उगाई जाती है, इसलिए इसे उत्तर-पश्चिम भारत की चाय राजधानी कहा जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Pahari dialect spoken in Bilaspur district is also known as:", ["Kahluri", "Kangri", "Hindauri", "Kullvi"], "Bilaspuri is also called Kahluri, after the old Kahlur state whose capital was Bilaspur."],
    ["बिलासपुर जिले में बोली जाने वाली पहाड़ी बोली को और किस नाम से जाना जाता है?", ["कहलूरी", "कांगड़ी", "हिंदूरी", "कुल्वी"], "बिलासपुरी को कहलूरी भी कहते हैं, जो पुरानी कहलूर रियासत के नाम पर है, जिसकी राजधानी बिलासपुर थी।"]),

  // ───────── Section 1: General Knowledge (25) ─────────
  q(1, "general-studies", "indian-history", "H", 1,
    ["Sir Michael O'Dwyer, Lieutenant Governor of Punjab at the time of the Jallianwala Bagh massacre, was shot dead in London in 1940 by:", ["Bhagat Singh", "Udham Singh", "Sukhdev", "Chandrashekhar Azad"], "Udham Singh shot O'Dwyer at Caxton Hall, London, in March 1940 to avenge the 1919 massacre and was hanged in July 1940."],
    ["जलियाँवाला बाग हत्याकांड के समय पंजाब के लेफ़्टिनेंट गवर्नर सर माइकल ओ'ड्वायर की 1940 में लंदन में गोली मारकर हत्या किसने की?", ["भगत सिंह", "उधम सिंह", "सुखदेव", "चंद्रशेखर आज़ाद"], "उधम सिंह ने 1919 के हत्याकांड का बदला लेने के लिए मार्च 1940 में लंदन के कैक्सटन हॉल में ओ'ड्वायर को गोली मारी और जुलाई 1940 में उन्हें फाँसी दी गई।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Gandhi suspended the Non-Cooperation Movement in February 1922 after a violent incident at:", ["Chauri Chaura", "Bardoli", "Kheda", "Dandi"], "At Chauri Chaura (Gorakhpur, Uttar Pradesh) a mob burnt a police station and killed 22 policemen, after which Gandhi withdrew the movement."],
    ["फ़रवरी 1922 में एक हिंसक घटना के बाद गांधीजी ने असहयोग आंदोलन कहाँ की घटना पर स्थगित किया?", ["चौरी चौरा", "बारदोली", "खेड़ा", "डांडी"], "चौरी चौरा (गोरखपुर, उत्तर प्रदेश) में भीड़ ने थाने को जला दिया और 22 पुलिसकर्मी मारे गए, जिसके बाद गांधीजी ने आंदोलन वापस ले लिया।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["Gandhi attended a Round Table Conference in London as the sole Congress representative after the Gandhi–Irwin Pact. It was the:", ["First (1930)", "Third (1932)", "Second (1931)", "All three"], "Gandhi attended only the Second Round Table Conference (1931) after the Gandhi–Irwin Pact. Congress boycotted the First and did not attend the Third."],
    ["गांधी–इरविन समझौते के बाद गांधीजी कांग्रेस के एकमात्र प्रतिनिधि के रूप में लंदन के किस गोलमेज़ सम्मेलन में गए थे?", ["प्रथम (1930)", "तृतीय (1932)", "द्वितीय (1931)", "तीनों"], "गांधी–इरविन समझौते के बाद गांधीजी केवल द्वितीय गोलमेज़ सम्मेलन (1931) में गए। कांग्रेस ने प्रथम का बहिष्कार किया और तृतीय में भाग नहीं लिया।"]),
  q(1, "general-studies", "indian-history", "M", 3,
    ["Who hoisted the Congress flag at Gowalia Tank Maidan, Bombay, on 9 August 1942 at the start of the Quit India Movement?", ["Sucheta Kripalani", "Usha Mehta", "Sarojini Naidu", "Aruna Asaf Ali"], "Aruna Asaf Ali hoisted the flag at Gowalia Tank after the top leaders had been arrested. Usha Mehta ran the Congress secret radio."],
    ["भारत छोड़ो आंदोलन की शुरुआत पर 9 अगस्त 1942 को बंबई के गोवालिया टैंक मैदान में कांग्रेस का झंडा किसने फहराया?", ["सुचेता कृपलानी", "उषा मेहता", "सरोजिनी नायडू", "अरुणा आसफ़ अली"], "शीर्ष नेताओं की गिरफ़्तारी के बाद अरुणा आसफ़ अली ने गोवालिया टैंक पर झंडा फहराया। उषा मेहता ने कांग्रेस का गुप्त रेडियो चलाया।"]),
  q(1, "general-studies", "indian-history", "H", 1,
    ["The Kakori train robbery of 1925 was carried out by the revolutionaries of the:", ["Anushilan Samiti", "Hindustan Republican Association", "Ghadar Party", "Abhinav Bharat"], "The Hindustan Republican Association, led by Ram Prasad Bismil and Ashfaqulla Khan, looted the government treasury on the 8 Down train near Kakori in August 1925."],
    ["1925 का काकोरी ट्रेन कांड किस क्रांतिकारी संगठन ने किया था?", ["अनुशीलन समिति", "हिंदुस्तान रिपब्लिकन एसोसिएशन", "ग़दर पार्टी", "अभिनव भारत"], "राम प्रसाद बिस्मिल और अशफ़ाकउल्ला ख़ान के नेतृत्व में हिंदुस्तान रिपब्लिकन एसोसिएशन ने अगस्त 1925 में काकोरी के पास 8 डाउन ट्रेन से सरकारी ख़ज़ाना लूटा।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["Who led the defence of the INA officers (Shah Nawaz Khan, Prem Sahgal and G.S. Dhillon) in the Red Fort trials of 1945–46?", ["Tej Bahadur Sapru", "M.C. Chagla", "Bhulabhai Desai", "C. Rajagopalachari"], "Bhulabhai Desai led the INA Defence Committee at the Red Fort trials. The trials caused a nationwide upsurge in favour of the INA prisoners."],
    ["1945–46 के लाल क़िला मुक़दमों में INA अधिकारियों (शाहनवाज़ ख़ान, प्रेम सहगल और जी.एस. ढिल्लों) के बचाव का नेतृत्व किसने किया?", ["तेज बहादुर सप्रू", "एम.सी. छागला", "भूलाभाई देसाई", "सी. राजगोपालाचारी"], "भूलाभाई देसाई ने लाल क़िला मुक़दमों में INA रक्षा समिति का नेतृत्व किया। इन मुक़दमों से INA क़ैदियों के पक्ष में देशव्यापी उभार आया।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["The Boundary Commission that drew the India–Pakistan boundary in 1947 was headed by:", ["Cyril Radcliffe", "Lord Mountbatten", "Lord Wavell", "Stafford Cripps"], "Sir Cyril Radcliffe chaired the Boundary Commissions for Punjab and Bengal. The resulting border is called the Radcliffe Line."],
    ["1947 में भारत–पाकिस्तान की सीमा तय करने वाले सीमा आयोग की अध्यक्षता किसने की?", ["सिरिल रैडक्लिफ़", "लॉर्ड माउंटबेटन", "लॉर्ड वेवेल", "स्टैफ़र्ड क्रिप्स"], "सर सिरिल रैडक्लिफ़ ने पंजाब और बंगाल के सीमा आयोगों की अध्यक्षता की। इस सीमा को रैडक्लिफ़ रेखा कहा जाता है।"]),
  q(1, "general-studies", "indian-history", "H", 1,
    ["Dyarchy (dual government) in the provinces was introduced by the:", ["Government of India Act, 1909", "Government of India Act, 1919", "Government of India Act, 1935", "Indian Councils Act, 1892"], "The Government of India Act, 1919 (Montagu–Chelmsford reforms) introduced dyarchy in the provinces, dividing subjects into 'reserved' and 'transferred'. The 1935 Act ended it in the provinces and introduced it at the Centre."],
    ["प्रांतों में द्वैध शासन (Dyarchy) किस अधिनियम द्वारा लागू हुआ?", ["भारत शासन अधिनियम, 1909", "भारत शासन अधिनियम, 1919", "भारत शासन अधिनियम, 1935", "भारतीय परिषद अधिनियम, 1892"], "भारत शासन अधिनियम, 1919 (मॉन्टेग्यू–चेम्सफ़ोर्ड सुधार) ने प्रांतों में द्वैध शासन लागू किया, जिसमें विषय 'आरक्षित' और 'हस्तांतरित' में बाँटे गए। 1935 के अधिनियम ने प्रांतों में इसे समाप्त कर केंद्र में लागू किया।"]),
  q(1, "general-studies", "indian-geography", "H", 2,
    ["Which is the deepest freshwater lake in the world?", ["Lake Superior", "Lake Tanganyika", "Lake Baikal", "Lake Victoria"], "Lake Baikal in Russia is about 1,640 m deep and is the deepest lake in the world. Tanganyika is the second deepest."],
    ["विश्व की सबसे गहरी मीठे पानी की झील कौन-सी है?", ["सुपीरियर झील", "टैंगान्यीका झील", "बैकाल झील", "विक्टोरिया झील"], "रूस की बैकाल झील लगभग 1,640 मी गहरी है और विश्व की सबसे गहरी झील है। टैंगान्यीका दूसरे स्थान पर है।"]),
  q(1, "general-studies", "indian-geography", "M", 3,
    ["The Atacama Desert, one of the driest places on Earth, lies mainly in:", ["Argentina", "Peru", "Bolivia", "Chile"], "The Atacama Desert lies along the Pacific coast of northern Chile, and some parts of it have hardly any recorded rain."],
    ["पृथ्वी के सबसे शुष्क स्थानों में से एक अटाकामा मरुस्थल मुख्यतः कहाँ है?", ["अर्जेंटीना", "पेरू", "बोलीविया", "चिली"], "अटाकामा मरुस्थल उत्तरी चिली के प्रशांत तट के साथ फैला है और इसके कुछ भागों में लगभग कोई वर्षा दर्ज नहीं होती।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["The Bering Strait separates:", ["Asia and North America", "Europe and Asia", "Asia and Australia", "Africa and Europe"], "The Bering Strait lies between the Chukchi Peninsula of Russia (Asia) and Alaska (North America)."],
    ["बेरिंग जलडमरूमध्य किन्हें अलग करता है?", ["एशिया और उत्तरी अमेरिका", "यूरोप और एशिया", "एशिया और ऑस्ट्रेलिया", "अफ़्रीका और यूरोप"], "बेरिंग जलडमरूमध्य रूस (एशिया) के चुकची प्रायद्वीप और अलास्का (उत्तरी अमेरिका) के बीच है।"]),
  q(1, "general-studies", "indian-geography", "H", 1,
    ["Which of the following is a 'doubly landlocked' country, that is, a landlocked country surrounded only by other landlocked countries?", ["Bolivia", "Uzbekistan", "Paraguay", "Nepal"], "Uzbekistan (like Liechtenstein) is doubly landlocked. Bolivia, Paraguay and Nepal each border at least one country with a coastline."],
    ["निम्नलिखित में से कौन-सा 'दोहरा स्थलरुद्ध' देश है, अर्थात् ऐसा स्थलरुद्ध देश जो केवल अन्य स्थलरुद्ध देशों से घिरा है?", ["बोलीविया", "उज़्बेकिस्तान", "पराग्वे", "नेपाल"], "उज़्बेकिस्तान (लिकटेंस्टाइन की तरह) दोहरा स्थलरुद्ध है। बोलीविया, पराग्वे और नेपाल की सीमा कम से कम एक तटीय देश से लगती है।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["The first Jnanpith Award (1965) was given to a poet writing in which language?", ["Hindi", "Bengali", "Odia", "Malayalam"], "The first Jnanpith Award was given in 1965 to the Malayalam poet G. Sankara Kurup for his collection 'Odakkuzhal'."],
    ["प्रथम ज्ञानपीठ पुरस्कार (1965) किस भाषा के कवि को दिया गया?", ["हिंदी", "बांग्ला", "ओड़िया", "मलयालम"], "प्रथम ज्ञानपीठ पुरस्कार 1965 में मलयालम कवि जी. शंकर कुरुप को उनके काव्य-संग्रह 'ओडक्कुज़ल' के लिए दिया गया।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["The first recipient of the Dadasaheb Phalke Award (1969) was:", ["Prithviraj Kapoor", "Nargis", "Devika Rani", "Raj Kapoor"], "Devika Rani, a pioneer actress of Indian cinema, received the first Dadasaheb Phalke Award in 1969."],
    ["दादासाहब फाल्के पुरस्कार (1969) की पहली प्राप्तकर्ता कौन थीं?", ["पृथ्वीराज कपूर", "नरगिस", "देविका रानी", "राज कपूर"], "भारतीय सिनेमा की अग्रणी अभिनेत्री देविका रानी को 1969 में पहला दादासाहब फाल्के पुरस्कार मिला।"]),
  q(1, "general-studies", "indian-history", "H", 1,
    ["The first recipient of the Rajiv Gandhi Khel Ratna (now Major Dhyan Chand Khel Ratna) in 1991–92 was:", ["Sachin Tendulkar", "Viswanathan Anand", "Leander Paes", "Karnam Malleswari"], "Chess Grandmaster Viswanathan Anand was the first winner of India's highest sporting honour in 1991–92."],
    ["1991–92 में राजीव गांधी खेल रत्न (अब मेजर ध्यानचंद खेल रत्न) के प्रथम प्राप्तकर्ता कौन थे?", ["सचिन तेंदुलकर", "विश्वनाथन आनंद", "लिएंडर पेस", "कर्णम मल्लेश्वरी"], "शतरंज ग्रैंडमास्टर विश्वनाथन आनंद 1991–92 में भारत के सर्वोच्च खेल सम्मान के पहले विजेता थे।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Geetanjali Shree won the 2022 International Booker Prize, the first for a Hindi novel, for:", ["Tomb of Sand", "The White Tiger", "The God of Small Things", "The Inheritance of Loss"], "'Tomb of Sand' (Ret Samadhi), translated into English by Daisy Rockwell, won the 2022 International Booker Prize."],
    ["गीतांजलि श्री ने 2022 का अंतर्राष्ट्रीय बुकर पुरस्कार, जो किसी हिंदी उपन्यास को पहली बार मिला, किस कृति के लिए जीता?", ["टूम्ब ऑफ़ सैंड (रेत समाधि)", "द व्हाइट टाइगर", "द गॉड ऑफ़ स्मॉल थिंग्स", "द इनहेरिटेंस ऑफ़ लॉस"], "डेज़ी रॉकवेल द्वारा अंग्रेज़ी में अनूदित 'टूम्ब ऑफ़ सैंड' (रेत समाधि) ने 2022 का अंतर्राष्ट्रीय बुकर पुरस्कार जीता।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["India's total medal count at the Paris 2024 Olympics was:", ["8", "5", "7", "6"], "India won six medals at Paris 2024: one silver (Neeraj Chopra) and five bronze. Its best-ever tally of seven came at Tokyo 2020."],
    ["पेरिस 2024 ओलंपिक में भारत के कुल पदकों की संख्या कितनी थी?", ["8", "5", "7", "6"], "भारत ने पेरिस 2024 में छह पदक जीते: एक रजत (नीरज चोपड़ा) और पाँच कांस्य। सात पदकों का सर्वश्रेष्ठ प्रदर्शन टोक्यो 2020 में था।"],
    "6"),
  q(1, "general-studies", "indian-history", "H", 1,
    ["In December 2024, D. Gukesh became the youngest undisputed World Chess Champion by defeating:", ["Magnus Carlsen", "Ding Liren", "Fabiano Caruana", "Ian Nepomniachtchi"], "At the age of 18, Gukesh beat China's Ding Liren in the World Championship match held in Singapore."],
    ["दिसंबर 2024 में डी. गुकेश ने किसे हराकर सबसे युवा निर्विवाद विश्व शतरंज चैंपियन बनने का गौरव पाया?", ["मैग्नस कार्लसन", "डिंग लिरेन", "फ़ैबियानो कारुआना", "इयान नेपोमनियाची"], "18 वर्ष की आयु में गुकेश ने सिंगापुर में हुए विश्व चैंपियनशिप मैच में चीन के डिंग लिरेन को हराया।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["India won the 2024 ICC Men's T20 World Cup final, beating South Africa, at:", ["Dubai", "Providence Stadium, Guyana", "Kensington Oval, Barbados", "Lord's, London"], "India beat South Africa by seven runs in the final on 29 June 2024 at Kensington Oval, Bridgetown, Barbados."],
    ["भारत ने 2024 का ICC पुरुष T20 विश्व कप फ़ाइनल दक्षिण अफ़्रीका को हराकर कहाँ जीता?", ["दुबई", "प्रोविडेंस स्टेडियम, गुयाना", "केंसिंग्टन ओवल, बारबाडोस", "लॉर्ड्स, लंदन"], "भारत ने 29 जून 2024 को बारबाडोस के ब्रिजटाउन स्थित केंसिंग्टन ओवल में फ़ाइनल में दक्षिण अफ़्रीका को सात रन से हराया।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["The Dronacharya Award is given in India to:", ["Outstanding sportspersons", "Coaches for outstanding work", "Sportspersons for lifetime achievement", "Sports institutions"], "The Dronacharya Award honours coaches who have produced medal winners at international events. The Dhyan Chand Award is for lifetime achievement."],
    ["भारत में द्रोणाचार्य पुरस्कार किसे दिया जाता है?", ["उत्कृष्ट खिलाड़ियों को", "उत्कृष्ट कार्य के लिए प्रशिक्षकों को", "खिलाड़ियों को जीवन भर की उपलब्धि के लिए", "खेल संस्थानों को"], "द्रोणाचार्य पुरस्कार उन प्रशिक्षकों को दिया जाता है जिनके शिष्यों ने अंतरराष्ट्रीय प्रतियोगिताओं में पदक जीते। ध्यानचंद पुरस्कार जीवन भर की उपलब्धि के लिए है।"]),
  q(1, "general-studies", "indian-polity", "H", 0,
    ["The Supreme Court laid down guidelines to be followed by the police during arrest and detention, to prevent custodial torture, in:", ["D.K. Basu v. State of West Bengal", "Maneka Gandhi v. Union of India", "Kesavananda Bharati v. State of Kerala", "Vishaka v. State of Rajasthan"], "In D.K. Basu v. State of West Bengal (1997) the Court set out guidelines such as an arrest memo, informing a relative and a medical check-up of the arrested person."],
    ["गिरफ़्तारी और हिरासत के दौरान हिरासती यातना रोकने के लिए पुलिस हेतु दिशा-निर्देश सर्वोच्च न्यायालय ने किस मामले में दिए?", ["डी.के. बसु बनाम पश्चिम बंगाल राज्य", "मेनका गांधी बनाम भारत संघ", "केशवानंद भारती बनाम केरल राज्य", "विशाखा बनाम राजस्थान राज्य"], "डी.के. बसु बनाम पश्चिम बंगाल राज्य (1997) में न्यायालय ने गिरफ़्तारी मेमो, रिश्तेदार को सूचना और गिरफ़्तार व्यक्ति की चिकित्सीय जाँच जैसे दिशा-निर्देश दिए।"]),
  q(1, "general-studies", "indian-economy", "H", 2,
    ["India's Planning Commission was set up in the year:", ["1947","1948","1950","1952"], "The Planning Commission was set up in March 1950 by a resolution of the Government of India, with the Prime Minister as its chairman."],
    ["भारत का योजना आयोग किस वर्ष स्थापित किया गया?", ["1947","1948","1950","1952"], "योजना आयोग की स्थापना मार्च 1950 में भारत सरकार के एक प्रस्ताव द्वारा हुई थी और प्रधानमंत्री इसके अध्यक्ष होते थे।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["The ozone layer, which absorbs most of the harmful ultraviolet radiation of the Sun, lies in which layer of the atmosphere?", ["Troposphere", "Stratosphere", "Mesosphere", "Exosphere"], "The ozone layer lies in the stratosphere, about 15–35 km above the Earth's surface."],
    ["सूर्य की अधिकांश हानिकारक पराबैंगनी विकिरण को सोखने वाली ओज़ोन परत वायुमंडल की किस परत में है?", ["क्षोभमंडल", "समतापमंडल", "मध्यमंडल", "बहिर्मंडल"], "ओज़ोन परत समतापमंडल में पृथ्वी की सतह से लगभग 15–35 किमी ऊपर है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["The scientific study of fingerprints for the purpose of identification is called:", ["Graphology", "Ballistics", "Toxicology", "Dactyloscopy"], "Dactyloscopy (fingerprint analysis) identifies people by their ridge patterns. Ballistics deals with firearms and graphology with handwriting."],
    ["पहचान के उद्देश्य से अंगुलि-छापों का वैज्ञानिक अध्ययन क्या कहलाता है?", ["हस्तलेख विज्ञान", "बैलिस्टिक्स", "विष विज्ञान", "अंगुलि-छाप विज्ञान (डैक्टिलोस्कोपी)"], "डैक्टिलोस्कोपी (अंगुलि-छाप विश्लेषण) रेखा-पैटर्न से व्यक्तियों की पहचान करती है। बैलिस्टिक्स आग्नेयास्त्रों और हस्तलेख विज्ञान लिखावट से संबंधित है।"]),
  q(1, "computer", "security", "M", 1,
    ["Which type of malware locks or encrypts a user's files and demands payment to restore access?", ["Spyware", "Ransomware", "Adware", "Worm"], "Ransomware encrypts or locks data and demands a ransom, usually in cryptocurrency. Such attacks should be reported on the cyber crime portal."],
    ["किस प्रकार का मैलवेयर उपयोगकर्ता की फ़ाइलों को लॉक या एन्क्रिप्ट कर उन्हें वापस देने के लिए भुगतान माँगता है?", ["स्पाईवेयर", "रैनसमवेयर", "एडवेयर", "वर्म"], "रैनसमवेयर डेटा को एन्क्रिप्ट या लॉक कर फिरौती, प्रायः क्रिप्टोकरेंसी में, माँगता है। ऐसे हमलों की सूचना साइबर अपराध पोर्टल पर दी जानी चाहिए।"]),

  // ───────── Section 2: Reasoning (20) ─────────
  q(2, "reasoning", "series", "M", 3,
    ["Find the next number: 5, 11, 23, 47, 95, ?", ["189", "193", "187", "191"], "Each term is double the previous term plus 1: 95 × 2 + 1 = 191."],
    ["अगली संख्या ज्ञात कीजिए: 5, 11, 23, 47, 95, ?", ["189", "193", "187", "191"], "प्रत्येक पद पिछले पद का दुगुना जोड़ 1 है: 95 × 2 + 1 = 191।"], "95*2+1"),
  q(2, "reasoning", "series", "H", 0,
    ["Find the next number: 4, 6, 12, 30, 90, ?", ["315", "270", "300", "360"], "The multipliers are 1.5, 2, 2.5, 3, so the next multiplier is 3.5: 90 × 3.5 = 315."],
    ["अगली संख्या ज्ञात कीजिए: 4, 6, 12, 30, 90, ?", ["315", "270", "300", "360"], "गुणक 1.5, 2, 2.5, 3 हैं, अतः अगला गुणक 3.5 है: 90 × 3.5 = 315।"], "90*3.5"),
  q(2, "reasoning", "series", "H", 2,
    ["Find the next group of letters: AZ, BY, CX, DW, ?", ["EU", "FV", "EV", "FW"], "The first letter moves forward one step (A, B, C, D, E) while the second moves backward one step (Z, Y, X, W, V). So the next group is EV."],
    ["अगला अक्षर-समूह ज्ञात कीजिए: AZ, BY, CX, DW, ?", ["EU", "FV", "EV", "FW"], "पहला अक्षर एक स्थान आगे बढ़ता है (A, B, C, D, E) और दूसरा एक स्थान पीछे (Z, Y, X, W, V)। अतः अगला समूह EV है।"]),
  q(2, "reasoning", "series", "H", 3,
    ["Find the wrong term in the series: 3, 10, 29, 66, 127, 218, 349", ["10", "127", "66", "349"], "The terms follow n³ + 2: 3, 10, 29, 66, 127, 218, 345. So 349 is wrong; it should be 345."],
    ["श्रेणी में गलत पद ज्ञात कीजिए: 3, 10, 29, 66, 127, 218, 349", ["10", "127", "66", "349"], "पद n³ + 2 के क्रम में हैं: 3, 10, 29, 66, 127, 218, 345। अतः 349 गलत है; यह 345 होना चाहिए।"], "349"),
  q(2, "reasoning", "coding-decoding", "H", 0,
    ["If DOG is coded as WLT, how will CAT be coded in the same way?", ["XZG", "XYG", "WZG", "XZH"], "Each letter is replaced by its opposite in the alphabet (A↔Z, B↔Y, …): D→W, O→L, G→T. So C→X, A→Z, T→G gives XZG."],
    ["यदि DOG को WLT लिखा जाता है, तो उसी प्रकार CAT को कैसे लिखा जाएगा?", ["XZG", "XYG", "WZG", "XZH"], "प्रत्येक अक्षर वर्णमाला में अपने विपरीत अक्षर से बदला जाता है (A↔Z, B↔Y, …): D→W, O→L, G→T। अतः C→X, A→Z, T→G से XZG।"]),
  q(2, "reasoning", "coding-decoding", "H", 2,
    ["In a code language, 'sun moon star' is written as 'ka ta mi', 'star sky' is written as 'mi ho' and 'moon night day' is written as 'ta re pu'. What is the code for 'sun'?", ["ta", "mi", "ka", "ho"], "'Star' is common to the first two sentences and its code is 'mi'. 'Moon' is common to the first and third and its code is 'ta'. So in the first sentence the remaining code 'ka' stands for 'sun'."],
    ["एक कोड भाषा में 'sun moon star' को 'ka ta mi', 'star sky' को 'mi ho' और 'moon night day' को 'ta re pu' लिखा जाता है। 'sun' का कोड क्या है?", ["ta", "mi", "ka", "ho"], "'Star' पहले दो वाक्यों में समान है और उसका कोड 'mi' है। 'Moon' पहले और तीसरे में समान है और उसका कोड 'ta' है। अतः पहले वाक्य में बचा कोड 'ka' 'sun' का है।"]),
  q(2, "reasoning", "blood-relations", "H", 3,
    ["Pointing to a girl, Rohit says, 'She is the daughter of the only son of my mother's father.' How is the girl related to Rohit?", ["Sister", "Niece", "Aunt", "Cousin"], "The only son of Rohit's mother's father is Rohit's maternal uncle. His daughter is Rohit's cousin."],
    ["एक लड़की की ओर इशारा करते हुए रोहित कहता है, 'यह मेरी माता के पिता के इकलौते पुत्र की पुत्री है।' वह लड़की रोहित की क्या लगती है?", ["बहन", "भतीजी", "चाची", "चचेरी/ममेरी बहन"], "रोहित की माता के पिता का इकलौता पुत्र रोहित का मामा है। उसकी पुत्री रोहित की ममेरी बहन है।"]),
  q(2, "reasoning", "direction-sense", "H", 0,
    ["Ramesh walks 6 km north, turns right and walks 3 km, turns right again and walks 12 km, and then turns left and walks 5 km. How far is he from his starting point?", ["10 km", "8 km", "12 km", "14 km"], "Taking the start as (0, 0): north 6 gives (0, 6); east 3 gives (3, 6); south 12 gives (3, −6); east 5 gives (8, −6). Distance = √(8² + 6²) = 10 km."],
    ["रमेश 6 किमी उत्तर चलता है, दाएँ मुड़कर 3 किमी चलता है, फिर दाएँ मुड़कर 12 किमी चलता है और फिर बाएँ मुड़कर 5 किमी चलता है। वह अपने आरंभिक बिंदु से कितनी दूर है?", ["10 किमी", "8 किमी", "12 किमी", "14 किमी"], "आरंभ को (0, 0) मानें: उत्तर 6 से (0, 6); पूर्व 3 से (3, 6); दक्षिण 12 से (3, −6); पूर्व 5 से (8, −6)। दूरी = √(8² + 6²) = 10 किमी।"], "Math.sqrt(8*8+6*6)"),
  q(2, "reasoning", "ranking", "H", 2,
    ["In a row of 45 students, Meena is 12th from the left and Seema is 20th from the right. How many students are between them?", ["11", "12", "13", "14"], "Seema from the left = 45 − 20 + 1 = 26th. Students between them = 26 − 12 − 1 = 13."],
    ["45 विद्यार्थियों की एक पंक्ति में मीना बाएँ से 12वें और सीमा दाएँ से 20वें स्थान पर है। उनके बीच कितने विद्यार्थी हैं?", ["11", "12", "13", "14"], "सीमा बाएँ से = 45 − 20 + 1 = 26वीं। उनके बीच विद्यार्थी = 26 − 12 − 1 = 13।"], "45-20+1-12-1"),
  q(2, "reasoning", "puzzles", "H", 3,
    ["Five friends A, B, C, D and E visit a police station on five different days, Monday to Friday, one each day. B visits the day after A. C visits before A, but not on Monday. D visits on Friday. Who visits on Monday?", ["A", "B", "C", "E"], "D is on Friday. B is the day after A, and C is before A but not on Monday, so A cannot be on Monday or Tuesday. A cannot be on Thursday because B would then fall on Friday. So A is on Wednesday, B on Thursday, C on Tuesday, and E is left with Monday."],
    ["पाँच मित्र A, B, C, D और E सोमवार से शुक्रवार तक पाँच अलग-अलग दिन एक-एक करके थाने जाते हैं। B, A के अगले दिन जाता है। C, A से पहले जाता है, पर सोमवार को नहीं। D शुक्रवार को जाता है। सोमवार को कौन जाता है?", ["A", "B", "C", "E"], "D शुक्रवार को है। B, A के अगले दिन है और C, A से पहले है पर सोमवार को नहीं, अतः A सोमवार या मंगलवार को नहीं हो सकता। A गुरुवार को नहीं हो सकता, क्योंकि तब B शुक्रवार को पड़ेगा। अतः A बुधवार, B गुरुवार, C मंगलवार को है और E के लिए सोमवार बचता है।"]),
  q(2, "reasoning", "analogy", "H", 0,
    ["7 : 50 :: 9 : ?", ["82", "80", "84", "90"], "The rule is n² + 1: 7² + 1 = 50, so 9² + 1 = 82."],
    ["7 : 50 :: 9 : ?", ["82", "80", "84", "90"], "नियम n² + 1 है: 7² + 1 = 50, अतः 9² + 1 = 82।"], "9*9+1"),
  q(2, "reasoning", "odd-one-out", "M", 2,
    ["Find the odd one out: Sparrow, Eagle, Bat, Pigeon", ["Sparrow", "Eagle", "Bat", "Pigeon"], "Sparrow, eagle and pigeon are birds. A bat is a flying mammal."],
    ["विषम चुनिए: गौरैया, बाज़, चमगादड़, कबूतर", ["गौरैया", "बाज़", "चमगादड़", "कबूतर"], "गौरैया, बाज़ और कबूतर पक्षी हैं। चमगादड़ उड़ने वाला स्तनधारी है।"]),
  q(2, "reasoning", "syllogism", "H", 0,
    ["Statements: Some pens are books. No book is a chair. Conclusions: I. Some pens are not chairs. II. No pen is a chair.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "The pens that are books cannot be chairs, so some pens are not chairs (I follows). Other pens may or may not be chairs, so 'No pen is a chair' is not certain (II does not follow)."],
    ["कथन: कुछ पेन किताबें हैं। कोई किताब कुर्सी नहीं है। निष्कर्ष: I. कुछ पेन कुर्सी नहीं हैं। II. कोई पेन कुर्सी नहीं है।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "जो पेन किताबें हैं वे कुर्सी नहीं हो सकते, अतः कुछ पेन कुर्सी नहीं हैं (I सही)। शेष पेन कुर्सी हो भी सकते हैं और नहीं भी, अतः 'कोई पेन कुर्सी नहीं है' निश्चित नहीं (II सही नहीं)।"]),
  q(2, "reasoning", "syllogism", "H", 1,
    ["Statements: All lions are cats. Some cats are wild. Conclusions: I. Some lions are wild. II. Some wild animals are cats.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "'Some cats are wild' converts to 'Some wild animals are cats', so II follows. The wild cats may not be lions, so I does not follow."],
    ["कथन: सभी शेर बिल्लियाँ हैं। कुछ बिल्लियाँ जंगली हैं। निष्कर्ष: I. कुछ शेर जंगली हैं। II. कुछ जंगली जानवर बिल्लियाँ हैं।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "'कुछ बिल्लियाँ जंगली हैं' का परिवर्तन 'कुछ जंगली जानवर बिल्लियाँ हैं' है, अतः II सही है। जंगली बिल्लियाँ शेर न भी हों, इसलिए I अनुसरण नहीं करता।"]),
  q(2, "reasoning", "clock-calendar", "H", 2,
    ["If 1 January 2026 is a Thursday, which day of the week will 15 August 2026 be?", ["Thursday", "Friday", "Saturday", "Sunday"], "From 1 January to 15 August there are 226 days (31 + 28 + 31 + 30 + 31 + 30 + 31 = 212 days up to 1 August, plus 14). 226 = 32 weeks + 2 odd days, so Thursday + 2 = Saturday."],
    ["यदि 1 जनवरी 2026 को गुरुवार है, तो 15 अगस्त 2026 को सप्ताह का कौन-सा दिन होगा?", ["गुरुवार", "शुक्रवार", "शनिवार", "रविवार"], "1 जनवरी से 15 अगस्त तक 226 दिन हैं (1 अगस्त तक 31 + 28 + 31 + 30 + 31 + 30 + 31 = 212 दिन, साथ में 14)। 226 = 32 सप्ताह + 2 विषम दिन, अतः गुरुवार + 2 = शनिवार।"]),
  q(2, "reasoning", "clock-calendar", "H", 3,
    ["What is the angle between the hands of a clock at 3:40?", ["120°", "125°", "135°", "130°"], "At 3:40 the hour hand is at 3 × 30 + 40 × 0.5 = 110° and the minute hand is at 40 × 6 = 240°. The angle between them is 130°."],
    ["घड़ी में 3:40 बजे दोनों सुइयों के बीच कितना कोण होता है?", ["120°", "125°", "135°", "130°"], "3:40 बजे घंटे की सुई 3 × 30 + 40 × 0.5 = 110° पर और मिनट की सुई 40 × 6 = 240° पर होती है। दोनों के बीच का कोण 130° है।"], "240-(3*30+40*0.5)"),
  q(2, "reasoning", "dice-cube", "H", 0,
    ["A cube of side 5 cm is painted on all faces and then cut into 1 cm cubes. How many small cubes have exactly two faces painted?", ["36", "24", "30", "48"], "Cubes with exactly two painted faces lie along the edges, not at the corners. Each of the 12 edges has 5 − 2 = 3 such cubes, so 12 × 3 = 36."],
    ["5 सेमी भुजा वाले एक घन के सभी फलकों पर रंग किया जाता है और फिर उसे 1 सेमी के घनों में काटा जाता है। कितने छोटे घनों के ठीक दो फलक रंगीन होंगे?", ["36", "24", "30", "48"], "ठीक दो रंगीन फलक वाले घन किनारों पर होते हैं, कोनों पर नहीं। 12 किनारों में से प्रत्येक पर 5 − 2 = 3 ऐसे घन हैं, अतः 12 × 3 = 36।"], "12*3"),
  q(2, "reasoning", "venn-diagram", "H", 3,
    ["Among 100 people, 60 like tea, 45 like coffee and 15 like neither. How many like both tea and coffee?", ["5", "10", "15", "20"], "People who like at least one drink = 100 − 15 = 85. Both = 60 + 45 − 85 = 20."],
    ["100 लोगों में से 60 को चाय, 45 को कॉफ़ी पसंद है और 15 को कोई नहीं। कितने लोगों को चाय और कॉफ़ी दोनों पसंद हैं?", ["5", "10", "15", "20"], "कम से कम एक पेय पसंद करने वाले = 100 − 15 = 85। दोनों = 60 + 45 − 85 = 20।"], "60+45-85"),
  q(2, "reasoning", "inequality", "H", 2,
    ["Statements: `A > B`, `B ≥ C`, `D < C`. Conclusions: I. `A > D`. II. `B > D`.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "Combining the statements gives `A > B ≥ C > D`. So A is greater than D (I) and B is greater than D (II). Both follow."],
    ["कथन: `A > B`, `B ≥ C`, `D < C`। निष्कर्ष: I. `A > D`। II. `B > D`।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "कथनों को मिलाने पर `A > B ≥ C > D` मिलता है। अतः A, D से बड़ा है (I) और B, D से बड़ा है (II)। दोनों अनुसरण करते हैं।"]),
  q(2, "reasoning", "math-operations", "H", 1,
    ["If `+` means `−`, `−` means `×`, `×` means `÷` and `÷` means `+`, what is the value of `18 ÷ 6 × 3 − 4 + 2`?", ["20", "24", "22", "28"], "Replacing the signs gives `18 + 6 ÷ 3 × 4 − 2`. By BODMAS, `6 ÷ 3 × 4 = 8`, so the value is 18 + 8 − 2 = 24."],
    ["यदि `+` का अर्थ `−`, `−` का अर्थ `×`, `×` का अर्थ `÷` और `÷` का अर्थ `+` है, तो `18 ÷ 6 × 3 − 4 + 2` का मान क्या होगा?", ["20", "24", "22", "28"], "चिह्न बदलने पर `18 + 6 ÷ 3 × 4 − 2` मिलता है। BODMAS से `6 ÷ 3 × 4 = 8`, अतः मान 18 + 8 − 2 = 24 है।"], "18+6/3*4-2"),

  // ───────── Section 3: Numerical Ability (15) ─────────
  q(3, "quant", "percentage", "H", 0,
    ["In a two-candidate election, 20% of the votes polled were invalid. The winner got 55% of the valid votes and won by 2,400 votes. How many votes were polled in all?", ["30,000", "28,000", "32,000", "36,000"], "The winning margin is 55% − 45% = 10% of the valid votes = 2,400, so valid votes = 24,000. These are 80% of the votes polled, so total = 24,000 ÷ 0.8 = 30,000."],
    ["दो उम्मीदवारों के चुनाव में डाले गए 20% मत अवैध थे। विजेता को वैध मतों का 55% मिला और वह 2,400 मतों से जीता। कुल कितने मत डाले गए?", ["30,000", "28,000", "32,000", "36,000"], "जीत का अंतर वैध मतों का 55% − 45% = 10% = 2,400, अतः वैध मत = 24,000। ये डाले गए मतों का 80% हैं, अतः कुल = 24,000 ÷ 0.8 = 30,000।"], "2400/0.1/0.8"),
  q(3, "quant", "profit-loss", "H", 1,
    ["A trader sells two articles at ₹1,200 each, making a 20% profit on one and a 20% loss on the other. What is his overall result?", ["No profit, no loss", "4% loss", "4% gain", "2% loss"], "Cost of the first = 1,200 ÷ 1.2 = ₹1,000 and of the second = 1,200 ÷ 0.8 = ₹1,500. Total cost = 2,500 and total sale = 2,400, so the loss is 100/2,500 × 100 = 4%."],
    ["एक व्यापारी दो वस्तुएँ ₹1,200 प्रति वस्तु बेचता है, एक पर 20% लाभ और दूसरी पर 20% हानि होती है। उसका कुल परिणाम क्या है?", ["न लाभ न हानि", "4% हानि", "4% लाभ", "2% हानि"], "पहली का क्रय मूल्य = 1,200 ÷ 1.2 = ₹1,000 और दूसरी का = 1,200 ÷ 0.8 = ₹1,500। कुल क्रय = 2,500 और कुल विक्रय = 2,400, अतः हानि = 100/2,500 × 100 = 4%।"], "100/2500*100"),
  q(3, "quant", "ratio-proportion", "H", 3,
    ["A 20-litre mixture contains milk and water in the ratio 7 : 3. How much water must be added to make the ratio 7 : 5?", ["3 litres", "5 litres", "6 litres", "4 litres"], "Milk = 14 L and water = 6 L. For 14 : (6 + x) = 7 : 5 we need 6 + x = 10, so x = 4 litres."],
    ["20 लीटर के एक मिश्रण में दूध और पानी का अनुपात 7 : 3 है। अनुपात 7 : 5 करने के लिए कितना पानी मिलाना होगा?", ["3 लीटर", "5 लीटर", "6 लीटर", "4 लीटर"], "दूध = 14 ली और पानी = 6 ली। 14 : (6 + x) = 7 : 5 के लिए 6 + x = 10, अतः x = 4 लीटर।"], "14*5/7-6"),
  q(3, "quant", "ages", "H", 3,
    ["The sum of the present ages of a father and his son is 56 years. Four years ago the father was three times as old as the son. What is the father's present age?", ["34 years", "36 years", "38 years", "40 years"], "Let the son be S now, so the father is 56 − S. Then 56 − S − 4 = 3(S − 4), which gives 64 = 4S, so S = 16 and the father is 40 years old."],
    ["एक पिता और उसके पुत्र की वर्तमान आयु का योग 56 वर्ष है। चार वर्ष पहले पिता की आयु पुत्र की आयु की तीन गुनी थी। पिता की वर्तमान आयु क्या है?", ["34 वर्ष", "36 वर्ष", "38 वर्ष", "40 वर्ष"], "मान लें पुत्र की वर्तमान आयु S है, तो पिता की 56 − S। तब 56 − S − 4 = 3(S − 4), जिससे 64 = 4S, अतः S = 16 और पिता 40 वर्ष का है।"], "56-16"),
  q(3, "quant", "time-work", "H", 0,
    ["Pipe A can fill a tank in 20 minutes and pipe B in 30 minutes, while pipe C can empty the full tank in 15 minutes. If all three are opened together, how long will the empty tank take to fill?", ["60 minutes", "45 minutes", "50 minutes", "30 minutes"], "Net filling per minute = 1/20 + 1/30 − 1/15 = (3 + 2 − 4)/60 = 1/60. So the tank fills in 60 minutes."],
    ["पाइप A एक टंकी को 20 मिनट में और पाइप B 30 मिनट में भर सकता है, जबकि पाइप C भरी टंकी को 15 मिनट में खाली कर सकता है। तीनों को एक साथ खोलने पर खाली टंकी कितनी देर में भरेगी?", ["60 मिनट", "45 मिनट", "50 मिनट", "30 मिनट"], "प्रति मिनट शुद्ध भराव = 1/20 + 1/30 − 1/15 = (3 + 2 − 4)/60 = 1/60। अतः टंकी 60 मिनट में भरेगी।"], "1/(1/20+1/30-1/15)"),
  q(3, "quant", "speed-distance", "H", 1,
    ["Two trains of lengths 150 m and 100 m run on parallel tracks in opposite directions at 60 km/h and 40 km/h. How long do they take to cross each other completely?", ["8 seconds", "9 seconds", "10 seconds", "12 seconds"], "Relative speed = 100 km/h = 100 × 5/18 m/s. Distance to cover = 150 + 100 = 250 m. Time = 250 ÷ (100 × 5/18) = 9 seconds."],
    ["150 मी और 100 मी लंबी दो रेलगाड़ियाँ समानांतर पटरियों पर विपरीत दिशाओं में 60 किमी/घंटा और 40 किमी/घंटा की चाल से चलती हैं। वे एक-दूसरे को पूरी तरह पार करने में कितना समय लेंगी?", ["8 सेकंड", "9 सेकंड", "10 सेकंड", "12 सेकंड"], "सापेक्ष चाल = 100 किमी/घंटा = 100 × 5/18 मी/से। तय करने वाली दूरी = 150 + 100 = 250 मी। समय = 250 ÷ (100 × 5/18) = 9 सेकंड।"], "250/(100*5/18)"),
  q(3, "quant", "interest", "H", 3,
    ["What is the difference between the compound interest and the simple interest on ₹5,000 for 2 years at 8% per annum?", ["₹24", "₹28", "₹30", "₹32"], "For 2 years the difference = P × (r/100)² = 5,000 × (0.08)² = 5,000 × 0.0064 = ₹32."],
    ["₹5,000 पर 8% वार्षिक दर से 2 वर्ष के चक्रवृद्धि ब्याज और साधारण ब्याज का अंतर क्या है?", ["₹24", "₹28", "₹30", "₹32"], "2 वर्ष के लिए अंतर = P × (r/100)² = 5,000 × (0.08)² = 5,000 × 0.0064 = ₹32।"], "5000*0.08*0.08"),
  q(3, "quant", "average", "M", 0,
    ["The average of five consecutive odd numbers is 27. What is the largest of these numbers?", ["31", "29", "33", "35"], "The middle number is the average, 27, so the numbers are 23, 25, 27, 29 and 31. The largest is 31."],
    ["पाँच क्रमागत विषम संख्याओं का औसत 27 है। इनमें सबसे बड़ी संख्या कौन-सी है?", ["31", "29", "33", "35"], "बीच की संख्या ही औसत 27 है, अतः संख्याएँ 23, 25, 27, 29 और 31 हैं। सबसे बड़ी 31 है।"], "27+4"),
  q(3, "quant", "mixture-alligation", "H", 1,
    ["In what ratio should rice costing ₹40 per kg be mixed with rice costing ₹55 per kg so that the mixture is worth ₹48 per kg?", ["8 : 7", "7 : 8", "3 : 4", "5 : 7"], "By alligation, the ratio of the cheaper to the dearer rice = (55 − 48) : (48 − 40) = 7 : 8."],
    ["₹40 प्रति किग्रा वाले चावल को ₹55 प्रति किग्रा वाले चावल के साथ किस अनुपात में मिलाएँ कि मिश्रण का मूल्य ₹48 प्रति किग्रा हो?", ["8 : 7", "7 : 8", "3 : 4", "5 : 7"], "एलिगेशन से सस्ते और महँगे चावल का अनुपात = (55 − 48) : (48 − 40) = 7 : 8।"]),
  q(3, "quant", "mensuration", "M", 3,
    ["A cylindrical tank has a radius of 7 m and a height of 10 m. What is its capacity? (Take π = 22/7 and 1 m³ = 1 kilolitre)", ["1,320 kilolitres", "1,430 kilolitres", "1,760 kilolitres", "1,540 kilolitres"], "Volume = πr²h = 22/7 × 7 × 7 × 10 = 1,540 m³, which is 1,540 kilolitres."],
    ["एक बेलनाकार टंकी की त्रिज्या 7 मी और ऊँचाई 10 मी है। उसकी क्षमता क्या है? (π = 22/7 और 1 मी³ = 1 किलोलीटर लें)", ["1,320 किलोलीटर", "1,430 किलोलीटर", "1,760 किलोलीटर", "1,540 किलोलीटर"], "आयतन = πr²h = 22/7 × 7 × 7 × 10 = 1,540 मी³, यानी 1,540 किलोलीटर।"], "22/7*7*7*10"),
  q(3, "quant", "number-system", "H", 3,
    ["What is the remainder when `2^10` is divided by 11?", ["0", "2", "10", "1"], "`2^10` = 1,024 = 11 × 93 + 1, so the remainder is 1. This also follows from Fermat's little theorem."],
    ["`2^10` को 11 से भाग देने पर शेषफल क्या होगा?", ["0", "2", "10", "1"], "`2^10` = 1,024 = 11 × 93 + 1, अतः शेषफल 1 है। यह फ़र्मा के लघु प्रमेय से भी मिलता है।"], "1024%11"),
  q(3, "quant", "hcf-lcm", "M", 0,
    ["The HCF and LCM of two numbers are 12 and 360. If one number is 72, what is the other?", ["60", "48", "54", "90"], "Product of the numbers = HCF × LCM = 12 × 360 = 4,320. The other number = 4,320 ÷ 72 = 60."],
    ["दो संख्याओं का HCF और LCM क्रमशः 12 और 360 है। यदि एक संख्या 72 है, तो दूसरी संख्या क्या है?", ["60", "48", "54", "90"], "संख्याओं का गुणनफल = HCF × LCM = 12 × 360 = 4,320। दूसरी संख्या = 4,320 ÷ 72 = 60।"], "12*360/72"),
  q(3, "quant", "percentage", "M", 1,
    ["A shopkeeper marks an article at ₹500 and allows a 12% discount. The selling price is:", ["₹430", "₹440", "₹445", "₹450"], "Selling price = 500 × (100 − 12)/100 = 500 × 0.88 = ₹440."],
    ["एक दुकानदार किसी वस्तु का अंकित मूल्य ₹500 रखकर 12% की छूट देता है। विक्रय मूल्य है:", ["₹430", "₹440", "₹445", "₹450"], "विक्रय मूल्य = 500 × (100 − 12)/100 = 500 × 0.88 = ₹440।"], "500*0.88"),
  q(3, "quant", "number-system", "H", 2,
    ["In how many ways can the letters of the word 'POLICE' be arranged so that the vowels always come together?", ["120", "240", "144", "720"], "The vowels O, I and E are treated as one block, giving 4 units to arrange in 4! = 24 ways. The vowels can be arranged within the block in 3! = 6 ways. Total = 24 × 6 = 144."],
    ["'POLICE' शब्द के अक्षरों को कितने प्रकार से व्यवस्थित किया जा सकता है ताकि स्वर सदैव साथ रहें?", ["120", "240", "144", "720"], "स्वर O, I और E को एक खंड मानने पर 4 इकाइयाँ 4! = 24 प्रकार से लगती हैं। खंड के भीतर स्वर 3! = 6 प्रकार से लग सकते हैं। कुल = 24 × 6 = 144।"], "24*6"),
  q(3, "quant", "number-system", "H", 3,
    ["A number is chosen at random from 1 to 30. What is the probability that it is a multiple of 4 or a multiple of 6?", ["1/5", "3/10", "2/5", "1/3"], "Multiples of 4: 7 numbers; multiples of 6: 5 numbers; multiples of both, i.e. of 12: 2 numbers (12, 24). Favourable = 7 + 5 − 2 = 10, so the probability = 10/30 = 1/3."],
    ["1 से 30 तक की संख्याओं में से एक संख्या यादृच्छिक चुनी जाती है। उसके 4 का गुणज या 6 का गुणज होने की प्रायिकता क्या है?", ["1/5", "3/10", "2/5", "1/3"], "4 के गुणज: 7 संख्याएँ; 6 के गुणज: 5 संख्याएँ; दोनों के, यानी 12 के, गुणज: 2 संख्याएँ (12, 24)। अनुकूल = 7 + 5 − 2 = 10, अतः प्रायिकता = 10/30 = 1/3।"]),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "english", "grammar", "M", 0,
    ["Fill in the blank: 'She is senior ___ me by three years.'", ["to", "than", "from", "over"], "Adjectives such as senior, junior, superior and inferior take 'to', not 'than'. So 'senior to me'."],
    ["रिक्त स्थान भरिए: 'She is senior ___ me by three years.'", ["to", "than", "from", "over"], "Senior, junior, superior और inferior जैसे विशेषण 'than' नहीं, 'to' के साथ आते हैं। अतः 'senior to me'।"]),
  q(4, "english", "grammar", "H", 3,
    ["Fill in the blank: 'Neither the sergeant nor his men ___ present at the scene.'", ["was", "is", "has been", "were"], "With 'neither … nor' the verb agrees with the subject nearer to it. Here 'men' is plural, so 'were' is correct."],
    ["रिक्त स्थान भरिए: 'Neither the sergeant nor his men ___ present at the scene.'", ["was", "is", "has been", "were"], "'Neither … nor' के साथ क्रिया निकटतम कर्ता के अनुसार होती है। यहाँ 'men' बहुवचन है, अतः 'were' सही है।"]),
  q(4, "english", "synonyms-antonyms", "M", 0,
    ["Choose the synonym of 'ABDUCT':", ["Kidnap", "Rescue", "Release", "Protect"], "To abduct is to take someone away by force or deception, that is, to kidnap."],
    ["'ABDUCT' का समानार्थी शब्द चुनिए:", ["Kidnap", "Rescue", "Release", "Protect"], "Abduct का अर्थ है किसी को बलपूर्वक या छल से ले जाना, यानी अपहरण करना (kidnap)।"]),
  q(4, "english", "synonyms-antonyms", "M", 3,
    ["Choose the antonym of 'VOLUNTARY':", ["Optional", "Willing", "Generous", "Compulsory"], "'Voluntary' means done by choice. Its opposite is 'compulsory'. 'Optional' and 'willing' are close in meaning."],
    ["'VOLUNTARY' का विलोम शब्द चुनिए:", ["Optional", "Willing", "Generous", "Compulsory"], "'Voluntary' का अर्थ है अपनी इच्छा से किया गया। इसका विलोम 'compulsory' (अनिवार्य) है। 'Optional' और 'willing' अर्थ में समान हैं।"]),
  q(4, "english", "one-word", "H", 0,
    ["One word for 'the killing of one's own brother or sister':", ["Fratricide", "Patricide", "Homicide", "Matricide"], "Fratricide is the killing of a brother or sister. Patricide is the killing of a father, matricide of a mother and homicide of any human being."],
    ["'अपने भाई या बहन की हत्या' के लिए एक शब्द:", ["Fratricide", "Patricide", "Homicide", "Matricide"], "Fratricide भाई या बहन की हत्या है। Patricide पिता की, matricide माता की और homicide किसी भी मनुष्य की हत्या है।"]),
  q(4, "english", "idioms", "M", 2,
    ["Choose the meaning of the idiom 'to leave no stone unturned':", ["To throw stones at someone", "To clear a field of rocks", "To try every possible means", "To give up easily"], "The idiom means to try every possible means to achieve something."],
    ["मुहावरे 'to leave no stone unturned' का अर्थ चुनिए:", ["किसी पर पत्थर फेंकना", "खेत से चट्टानें हटाना", "हर संभव उपाय आज़माना", "आसानी से हार मान लेना"], "इस मुहावरे का अर्थ है किसी काम को पूरा करने के लिए हर संभव उपाय आज़माना।"]),
  q(4, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'Each of the boys / have completed / their assignments. / No error'", ["Each of the boys", "have completed", "their assignments.", "No error"], "'Each' is singular, so the verb must be singular: 'Each of the boys has completed'."],
    ["त्रुटि वाला भाग चुनिए: 'Each of the boys / have completed / their assignments. / No error'", ["Each of the boys", "have completed", "their assignments.", "No error"], "'Each' एकवचन है, अतः क्रिया भी एकवचन होगी: 'Each of the boys has completed'।"]),
  q(4, "english", "voice-speech", "H", 0,
    ["Change into indirect speech: He said, \"I am writing a letter.\"", ["He said that he was writing a letter.", "He said that he is writing a letter.", "He said that I was writing a letter.", "He said that he had written a letter."], "In indirect speech after a past reporting verb, 'I' becomes 'he' and the present continuous 'am writing' becomes the past continuous 'was writing'."],
    ["अप्रत्यक्ष कथन में बदलिए: He said, \"I am writing a letter.\"", ["He said that he was writing a letter.", "He said that he is writing a letter.", "He said that I was writing a letter.", "He said that he had written a letter."], "भूतकालीन reporting verb के बाद अप्रत्यक्ष कथन में 'I' का 'he' और वर्तमान continuous 'am writing' का past continuous 'was writing' हो जाता है।"]),
  q(4, "hindi", "paryay-vilom", "H", 3,
    ["Which of these is NOT a synonym of 'वृक्ष' (tree)?", ["तरु", "विटप", "पादप", "सरोवर"], "तरु, विटप and पादप all mean a tree. 'सरोवर' means a lake."],
    ["निम्नलिखित में से कौन-सा 'वृक्ष' का पर्यायवाची नहीं है?", ["तरु", "विटप", "पादप", "सरोवर"], "तरु, विटप और पादप वृक्ष के पर्यायवाची हैं। 'सरोवर' का अर्थ झील है।"]),
  q(4, "hindi", "sandhi-samas", "H", 0,
    ["Choose the correct split of the sandhi word 'दिग्गज':", ["दिक् + गज", "दिग् + गज", "दिक + गज", "दिश् + गज"], "'दिग्गज' = दिक् + गज. The 'क्' before the voiced consonant 'ग' changes to 'ग्', which is a consonant (vyanjan) sandhi."],
    ["'दिग्गज' का सही संधि-विच्छेद चुनिए:", ["दिक् + गज", "दिग् + गज", "दिक + गज", "दिश् + गज"], "'दिग्गज' = दिक् + गज। घोष व्यंजन 'ग' से पहले 'क्' का 'ग्' हो जाता है, यह व्यंजन संधि है।"]),
  q(4, "hindi", "sandhi-samas", "H", 2,
    ["Identify the type of compound (samas) in 'नीलकमल':", ["Tatpurush", "Dvandva", "Karmadharaya", "Bahuvrihi"], "'नीलकमल' = नीला है जो कमल. Here the first word describes the second, so it is a Karmadharaya samas."],
    ["'नीलकमल' शब्द में कौन-सा समास है?", ["तत्पुरुष", "द्वंद्व", "कर्मधारय", "बहुव्रीहि"], "'नीलकमल' = नीला है जो कमल। यहाँ पहला पद दूसरे की विशेषता बताता है, अतः कर्मधारय समास है।"]),
  q(4, "hindi", "muhavare", "M", 0,
    ["What is the meaning of the Hindi idiom 'नाक कटना'?", ["To lose one's honour", "To have an injured nose", "To become very angry", "To catch a cold"], "The idiom means to lose one's honour or reputation, to be disgraced."],
    ["'नाक कटना' मुहावरे का अर्थ है:", ["इज़्ज़त चली जाना", "नाक में चोट लगना", "बहुत क्रोधित होना", "सर्दी होना"], "इस मुहावरे का अर्थ है इज़्ज़त या प्रतिष्ठा खो देना, अपमानित होना।"]),
  q(4, "hindi", "muhavare", "H", 3,
    ["What does the Hindi proverb 'अधजल गगरी छलकत जाय' mean?", ["A half-filled pot is easy to carry","Water should be stored carefully","Half-done work spoils everything","A person with little knowledge shows off the most"], "The proverb means that a person with half-knowledge makes the greatest display, just as a half-filled pot spills the most."],
    ["लोकोक्ति 'अधजल गगरी छलकत जाय' का अर्थ है:", ["आधा भरा घड़ा उठाना आसान है","पानी सावधानी से रखना चाहिए","अधूरा काम सब बिगाड़ देता है","कम ज्ञान वाला व्यक्ति सबसे अधिक दिखावा करता है"], "इस लोकोक्ति का अर्थ है कि अधूरे ज्ञान वाला व्यक्ति सबसे अधिक दिखावा करता है, जैसे आधा भरा घड़ा सबसे अधिक छलकता है।"]),
  q(4, "hindi", "shuddh-vartani", "M", 0,
    ["Which one of the following Hindi words is correctly spelt?", ["शृंगार", "श्रृंगार", "शृगांर", "श्रंगार"], "The correct spelling is 'शृंगार', written with 'शृ' (श + ऋ matra) and not with 'श्र'."],
    ["शुद्ध वर्तनी वाला शब्द चुनिए:", ["शृंगार", "श्रृंगार", "शृगांर", "श्रंगार"], "शुद्ध वर्तनी 'शृंगार' है, जो 'शृ' (श + ऋ की मात्रा) से बनती है, 'श्र' से नहीं।"]),
  q(4, "hindi", "ek-shabd", "M", 1,
    ["Choose one word for 'one who talks too much':", ["मौन", "वाचाल", "संकोची", "शांत"], "A person who talks too much is called 'वाचाल'. The other words describe quiet or reserved people."],
    ["'बहुत बोलने वाला' के लिए एक शब्द चुनिए:", ["मौन", "वाचाल", "संकोची", "शांत"], "बहुत बोलने वाले व्यक्ति को 'वाचाल' कहते हैं। शेष शब्द शांत या संकोची स्वभाव वाले के लिए हैं।"]),
];
