// HP Police Constable Full Mock 4 — 100 questions (25 HP GK, 25 GK, 20 Reasoning, 15 Maths, 15 Hindi/English).

import { q, type PoliceQuestion } from "./types";

export const mock4: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK (25) ─────────
  q(0, "hp-gk", "history", "M", 1,
    ["The devastating Kangra earthquake, which destroyed the Jwalamukhi region and Dharamshala, occurred in the year:", ["1897", "1905", "1934", "1950"], "The great Kangra earthquake struck on 4 April 1905 and killed about 20,000 people, and it badly damaged Kangra, Dharamshala and McLeodganj."],
    ["विनाशकारी कांगड़ा भूकंप, जिसने ज्वालामुखी क्षेत्र और धर्मशाला को तबाह किया, किस वर्ष आया था?", ["1897", "1905", "1934", "1950"], "महान कांगड़ा भूकंप 4 अप्रैल 1905 को आया, जिसमें लगभग 20,000 लोग मारे गए और कांगड़ा, धर्मशाला व मैक्लोडगंज को भारी क्षति पहुँची।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["The town of Chamba was founded by Raja Sahil Varman (Sahil Verma) around 920 AD and named after his daughter:", ["Padmavati", "Sunayna", "Champavati", "Rajkumari Amba"], "According to tradition, Raja Sahil Varman named the town Chamba after his daughter Champavati."],
    ["चंबा नगर की स्थापना लगभग 920 ई. में राजा साहिल वर्मन ने की और इसका नाम उनकी किस पुत्री के नाम पर रखा गया?", ["पद्मावती", "सुनयना", "चंपावती", "राजकुमारी अंबा"], "परंपरा के अनुसार राजा साहिल वर्मन ने अपनी पुत्री चंपावती के नाम पर नगर का नाम चंबा रखा।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["The town of Mandi was founded in 1527 by Raja:", ["Bahu Sen", "Sidh Sen", "Suraj Sen", "Ajbar Sen"], "Raja Ajbar Sen founded the town of Mandi in 1527 on the bank of the Beas. Bahu Sen is regarded as the founder of the Mandi state. Sidh Sen and Suraj Sen ruled much later."],
    ["मंडी नगर की स्थापना 1527 में किस राजा ने की?", ["बाहु सेन", "सिद्ध सेन", "सूरज सेन", "अजबर सेन"], "राजा अजबर सेन ने 1527 में ब्यास के तट पर मंडी नगर बसाया। बाहु सेन को मंडी रियासत का संस्थापक माना जाता है। सिद्ध सेन और सूरज सेन बहुत बाद के शासक थे।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The Chintpurni Shakti Peeth, where devotees offer prayers to Mata Chhinnamastika, is located in which district?", ["Una", "Hamirpur", "Bilaspur", "Solan"], "Mata Chintpurni temple is at Bharwain in Una district and is one of the Shakti Peeths of Himachal Pradesh."],
    ["माता छिन्नमस्तिका को समर्पित चिंतपूर्णी शक्तिपीठ किस जिले में है?", ["ऊना", "हमीरपुर", "बिलासपुर", "सोलन"], "माता चिंतपूर्णी का मंदिर ऊना जिले के भरवाईं में है और यह हिमाचल प्रदेश के शक्तिपीठों में से एक है।"]),
  q(0, "hp-gk", "polity-administration", "M", 1,
    ["Who became the first non-Congress Chief Minister of Himachal Pradesh in June 1977?", ["Thakur Ram Lal", "Shanta Kumar", "Virbhadra Singh", "Prem Kumar Dhumal"], "After the Emergency, the Janata Party won the 1977 election and Shanta Kumar became the first non-Congress Chief Minister of Himachal Pradesh."],
    ["जून 1977 में हिमाचल प्रदेश के पहले गैर-कांग्रेसी मुख्यमंत्री कौन बने?", ["ठाकुर राम लाल", "शांता कुमार", "वीरभद्र सिंह", "प्रेम कुमार धूमल"], "आपातकाल के बाद 1977 के चुनाव में जनता पार्टी जीती और शांता कुमार हिमाचल प्रदेश के पहले गैर-कांग्रेसी मुख्यमंत्री बने।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["Shimla was declared the summer capital of British India in the year:", ["1815", "1857", "1864", "1903"], "Viceroy John Lawrence made Shimla the summer capital of British India in 1864. The British had first developed it after the Gurkha War of 1815-16."],
    ["शिमला को ब्रिटिश भारत की ग्रीष्मकालीन राजधानी किस वर्ष घोषित किया गया?", ["1815", "1857", "1864", "1903"], "वायसराय जॉन लॉरेंस ने 1864 में शिमला को ब्रिटिश भारत की ग्रीष्मकालीन राजधानी बनाया। अंग्रेज़ों ने 1815-16 के गोरखा युद्ध के बाद इसे विकसित करना शुरू किया था।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The Kalka-Shimla railway was inscribed as a UNESCO World Heritage Site (as part of the Mountain Railways of India) in the year:", ["1999", "2003", "2005", "2008"], "The Kalka-Shimla railway (about 96 km, opened in 1903) was added to the World Heritage list in July 2008 as an extension of the Mountain Railways of India."],
    ["कालका-शिमला रेलवे को यूनेस्को विश्व धरोहर स्थल (भारत की पर्वतीय रेलों के भाग के रूप में) किस वर्ष घोषित किया गया?", ["1999", "2003", "2005", "2008"], "कालका-शिमला रेलवे (लगभग 96 किमी, 1903 में शुरू) को जुलाई 2008 में भारत की पर्वतीय रेलों के विस्तार के रूप में विश्व धरोहर सूची में शामिल किया गया।"]),
  q(0, "hp-gk", "history", "H", 0,
    ["Himachal Pradesh came into existence on 15 April 1948 through the merger of about how many princely states of the Punjab Hill region?", ["30", "26", "22", "35"], "Himachal Pradesh was formed on 15 April 1948 by integrating 30 princely states of the Shimla Hills and Punjab Hill States as a Chief Commissioner's province."],
    ["15 अप्रैल 1948 को हिमाचल प्रदेश का गठन पंजाब पहाड़ी क्षेत्र की लगभग कितनी रियासतों के विलय से हुआ?", ["30", "26", "22", "35"], "15 अप्रैल 1948 को शिमला पहाड़ी और पंजाब पहाड़ी रियासतों की 30 रियासतों को मिलाकर हिमाचल प्रदेश मुख्य आयुक्त प्रांत के रूप में बना।"]),
  q(0, "hp-gk", "polity-administration", "M", 1,
    ["The High Court of Himachal Pradesh is located at:", ["Dharamshala", "Shimla", "Mandi", "Solan"], "The High Court of Himachal Pradesh has its seat at Shimla, the state capital."],
    ["हिमाचल प्रदेश का उच्च न्यायालय कहाँ स्थित है?", ["धर्मशाला", "शिमला", "मंडी", "सोलन"], "हिमाचल प्रदेश उच्च न्यायालय का मुख्यालय राजधानी शिमला में है।"]),
  q(0, "hp-gk", "districts", "M", 2,
    ["Reckong Peo is the district headquarters of:", ["Lahaul & Spiti", "Chamba", "Kinnaur", "Kullu"], "Reckong Peo, at the foot of the Kinner Kailash range, is the headquarters of Kinnaur. Keylong is the headquarters of Lahaul & Spiti."],
    ["रिकांग पिओ किस जिले का मुख्यालय है?", ["लाहौल-स्पीति", "चंबा", "किन्नौर", "कुल्लू"], "किन्नर कैलाश श्रेणी की तलहटी में बसा रिकांग पिओ किन्नौर का मुख्यालय है। केलांग लाहौल-स्पीति का मुख्यालय है।"]),
  q(0, "hp-gk", "districts", "H", 3,
    ["Which district of Himachal Pradesh has the lowest literacy rate as per Census 2011?", ["Sirmaur", "Kullu", "Lahaul & Spiti", "Chamba"], "Chamba has the lowest literacy rate in the state (about 73%). The state average is about 82.8%, and Hamirpur is at the top."],
    ["जनगणना 2011 के अनुसार हिमाचल प्रदेश के किस जिले की साक्षरता दर सबसे कम है?", ["सिरमौर", "कुल्लू", "लाहौल-स्पीति", "चंबा"], "चंबा की साक्षरता दर राज्य में सबसे कम (लगभग 73%) है। राज्य का औसत लगभग 82.8% है और हमीरपुर सबसे ऊपर है।"]),
  q(0, "hp-gk", "geography", "H", 0,
    ["The river Sutlej enters India from Tibet through which pass in Kinnaur?", ["Shipki La", "Shinku La", "Baralacha La", "Kunzum La"], "The Sutlej (Langqen Zangbo) enters India through the Shipki La pass in Kinnaur. Shinku La connects Lahaul with Zanskar."],
    ["सतलुज नदी तिब्बत से किन्नौर के किस दर्रे से होकर भारत में प्रवेश करती है?", ["शिपकी ला", "शिंकू ला", "बारालाचा ला", "कुंज़ुम ला"], "सतलुज (लांगचेन जांगबो) किन्नौर के शिपकी ला दर्रे से भारत में प्रवेश करती है। शिंकू ला लाहौल को ज़ांस्कर से जोड़ता है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["The Kinner Kailash peak, sacred to Hindus and Buddhists for its natural Shivling-like rock formation, is in:", ["Kullu", "Kinnaur", "Chamba", "Lahaul & Spiti"], "Kinner Kailash (about 6,050 m) lies in Kinnaur, and the annual Kinner Kailash Yatra circles it."],
    ["हिंदुओं और बौद्धों के लिए पवित्र, प्राकृतिक शिवलिंग जैसी चट्टान वाला किन्नर कैलाश शिखर कहाँ है?", ["कुल्लू", "किन्नौर", "चंबा", "लाहौल-स्पीति"], "किन्नर कैलाश (लगभग 6,050 मी) किन्नौर में है और वार्षिक किन्नर कैलाश यात्रा इसकी परिक्रमा करती है।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["The Rohtang Pass, connecting Kullu valley with Lahaul, lies in which mountain range?", ["Dhauladhar", "Zanskar", "Pir Panjal", "Shivalik"], "Rohtang Pass (about 3,978 m) is on the Pir Panjal range between the Kullu valley and Lahaul valley."],
    ["कुल्लू घाटी को लाहौल से जोड़ने वाला रोहतांग दर्रा किस पर्वत श्रेणी में है?", ["धौलाधार", "ज़ांस्कर", "पीर पंजाल", "शिवालिक"], "रोहतांग दर्रा (लगभग 3,978 मी) कुल्लू घाटी और लाहौल घाटी के बीच पीर पंजाल श्रेणी में है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 3,
    ["The Spiti river joins the Sutlej at:", ["Kaza", "Tabo", "Rampur", "Khab"], "The Spiti river meets the Sutlej near Khab on the Kinnaur-Spiti boundary. Kaza and Tabo lie on the Spiti itself."],
    ["स्पीति नदी सतलुज में कहाँ मिलती है?", ["काज़ा", "ताबो", "रामपुर", "खाब"], "स्पीति नदी किन्नौर-स्पीति सीमा पर खाब के पास सतलुज में मिलती है। काज़ा और ताबो स्पीति नदी के किनारे ही हैं।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["The Giri river, which flows through Sirmaur district, is a tributary of the:", ["Yamuna", "Sutlej", "Beas", "Ravi"], "The Giri rises in the Shimla hills, flows through Sirmaur and joins the Yamuna near Paonta Sahib."],
    ["सिरमौर जिले से बहने वाली गिरि नदी किसकी सहायक नदी है?", ["यमुना", "सतलुज", "ब्यास", "रावी"], "गिरि शिमला की पहाड़ियों से निकलकर सिरमौर से बहती है और पांवटा साहिब के पास यमुना में मिलती है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["Prashar Lake, known for its floating island and a pagoda-style temple, is in which district?", ["Kullu", "Mandi", "Shimla", "Chamba"], "Prashar Lake (about 2,730 m) is in Mandi district, north of Mandi town, and has a pagoda-style temple of sage Prashar beside it."],
    ["तैरते द्वीप और पैगोडा शैली के मंदिर के लिए प्रसिद्ध पराशर झील किस जिले में है?", ["कुल्लू", "मंडी", "शिमला", "चंबा"], "पराशर झील (लगभग 2,730 मी) मंडी जिले में मंडी नगर के उत्तर में है और इसके किनारे ऋषि पराशर का पैगोडा शैली का मंदिर है।"]),
  q(0, "hp-gk", "geography", "H", 2,
    ["The Pin Valley National Park, a habitat of the snow leopard and ibex, lies in the cold desert of:", ["Kinnaur", "Chamba", "Spiti (Lahaul & Spiti)", "Kullu"], "Pin Valley National Park is in the Spiti part of Lahaul & Spiti district, in the cold desert biosphere reserve."],
    ["हिम तेंदुए और आइबेक्स के आवास पिन घाटी राष्ट्रीय उद्यान, किसके शीत मरुस्थल में स्थित है?", ["किन्नौर", "चंबा", "स्पीति (लाहौल-स्पीति)", "कुल्लू"], "पिन घाटी राष्ट्रीय उद्यान लाहौल-स्पीति जिले के स्पीति भाग में, शीत मरुस्थल जैवमंडल आरक्षित क्षेत्र में है।"]),
  q(0, "hp-gk", "economy", "H", 3,
    ["Samuel Evans Stokes, who introduced the commercial cultivation of Delicious apples in Himachal Pradesh in 1916, settled at:", ["Naggar", "Rohru", "Narkanda", "Kotgarh"], "Samuel Stokes (later Satyanand Stokes) planted American apple varieties at Kotgarh in Shimla district, starting the state's apple economy."],
    ["1916 में हिमाचल प्रदेश में डेलीशियस सेब की व्यावसायिक खेती शुरू करने वाले सैमुअल इवांस स्टोक्स कहाँ बसे थे?", ["नग्गर", "रोहड़ू", "नारकंडा", "कोटगढ़"], "सैमुअल स्टोक्स (बाद में सत्यानंद स्टोक्स) ने शिमला जिले के कोटगढ़ में अमेरिकी सेब की किस्में लगाईं, जिससे राज्य की सेब अर्थव्यवस्था शुरू हुई।"]),
  q(0, "hp-gk", "economy", "M", 0,
    ["Baddi, one of the largest pharmaceutical manufacturing hubs of Asia, is in which district of Himachal Pradesh?", ["Solan", "Una", "Sirmaur", "Kangra"], "Baddi-Barotiwala-Nalagarh is the main industrial belt of Himachal Pradesh and lies in Solan district."],
    ["एशिया के सबसे बड़े औषधि निर्माण केंद्रों में से एक बद्दी हिमाचल प्रदेश के किस जिले में है?", ["सोलन", "ऊना", "सिरमौर", "कांगड़ा"], "बद्दी-बरोटीवाला-नालागढ़ हिमाचल प्रदेश की मुख्य औद्योगिक पट्टी है और सोलन जिले में है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["The Renuka Fair, held every year in November near a lake, is celebrated in which district?", ["Solan", "Sirmaur", "Bilaspur", "Una"], "The Renuka fair is held at Renuka Ji in Sirmaur, in honour of Mata Renuka and her son Parshuram, around Kartik Ekadashi."],
    ["हर वर्ष नवंबर में एक झील के पास लगने वाला रेणुका मेला किस जिले में मनाया जाता है?", ["सोलन", "सिरमौर", "बिलासपुर", "ऊना"], "रेणुका मेला सिरमौर के रेणुका जी में कार्तिक एकादशी के आसपास माता रेणुका और उनके पुत्र परशुराम के सम्मान में लगता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The Phulaich (Ukhyang) festival, the 'festival of flowers', is celebrated in:", ["Chamba", "Kullu", "Kinnaur", "Mandi"], "Phulaich is a festival of the tribal people of Kinnaur, celebrated around September when villagers collect wild flowers from the high pastures."],
    ["'फूलों का त्योहार' कहलाने वाला फुलैच (उख्यांग) उत्सव कहाँ मनाया जाता है?", ["चंबा", "कुल्लू", "किन्नौर", "मंडी"], "फुलैच किन्नौर के जनजातीय लोगों का उत्सव है, जो लगभग सितंबर में मनाया जाता है और जिसमें ग्रामीण ऊँचे चरागाहों से जंगली फूल लाते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The wooden Hadimba Devi temple at Manali is dedicated to the wife of which Pandava?", ["Arjuna", "Yudhishthira", "Nakula", "Bhima"], "Hadimba (Hidimba) was the Rakshasi wife of Bhima and mother of Ghatotkacha. Her temple at Manali, built in 1553, has a pagoda-style roof."],
    ["मनाली का लकड़ी से बना हिडिंबा देवी मंदिर किस पांडव की पत्नी को समर्पित है?", ["अर्जुन", "युधिष्ठिर", "नकुल", "भीम"], "हिडिंबा भीम की राक्षसी पत्नी और घटोत्कच की माता थीं। मनाली में 1553 में बना उनका मंदिर पैगोडा शैली की छत वाला है।"]),
  q(0, "hp-gk", "personalities", "H", 0,
    ["Andretta near Palampur, known as an artists' village, was the home of the famous painter:", ["Sobha Singh", "Amrita Sher-Gil", "M.F. Husain", "Raja Ravi Varma"], "Sobha Singh, known for his paintings of the Sikh Gurus and 'Sohni Mahiwal', settled at Andretta in Kangra district and lived there until his death in 1986."],
    ["कलाकारों के गाँव के रूप में प्रसिद्ध पालमपुर के पास अंद्रेटा किस प्रसिद्ध चित्रकार का निवास था?", ["सोभा सिंह", "अमृता शेरगिल", "एम.एफ. हुसैन", "राजा रवि वर्मा"], "सिख गुरुओं और 'सोहनी महिवाल' के चित्रों के लिए प्रसिद्ध सोभा सिंह कांगड़ा जिले के अंद्रेटा में बसे और 1986 में अपने निधन तक वहीं रहे।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["Which of these districts of Himachal Pradesh was transferred from Punjab to Himachal Pradesh at the time of the reorganisation of Punjab in 1966?", ["Chamba", "Kangra", "Mandi", "Bilaspur"], "Kangra, Kullu, Shimla, Lahaul & Spiti and parts of Hoshiarpur and Ambala (Nalagarh, Una) were merged into Himachal Pradesh in 1966. Chamba, Mandi and Bilaspur were already part of Himachal from 1948-54."],
    ["1966 में पंजाब के पुनर्गठन के समय हिमाचल प्रदेश के इन जिलों में से कौन-सा पंजाब से हिमाचल में मिलाया गया?", ["चंबा", "कांगड़ा", "मंडी", "बिलासपुर"], "1966 में कांगड़ा, कुल्लू, शिमला, लाहौल-स्पीति और होशियारपुर व अंबाला के कुछ भाग (नालागढ़, ऊना) हिमाचल में मिलाए गए। चंबा, मंडी और बिलासपुर 1948-54 से ही हिमाचल में थे।"]),

  // ───────── Section 1: General Knowledge (25) ─────────
  q(1, "general-studies", "indian-history", "H", 2,
    ["By the Treaty of Allahabad (1765), the Diwani rights of Bengal, Bihar and Odisha were granted to the East India Company by:", ["Mir Qasim", "Siraj-ud-Daulah", "Shah Alam II", "Shuja-ud-Daulah"], "After the Battle of Buxar (1764), Mughal emperor Shah Alam II granted the Diwani (right to collect revenue) of Bengal, Bihar and Odisha to the Company by the Treaty of Allahabad."],
    ["इलाहाबाद की संधि (1765) द्वारा बंगाल, बिहार और उड़ीसा की दीवानी ईस्ट इंडिया कंपनी को किसने दी?", ["मीर क़ासिम", "सिराजुद्दौला", "शाह आलम द्वितीय", "शुजाउद्दौला"], "बक्सर के युद्ध (1764) के बाद मुगल बादशाह शाह आलम द्वितीय ने इलाहाबाद की संधि द्वारा बंगाल, बिहार और उड़ीसा की दीवानी (राजस्व वसूली का अधिकार) कंपनी को दी।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["Which was the first state annexed by Lord Dalhousie under the Doctrine of Lapse?", ["Jhansi", "Nagpur", "Sambalpur", "Satara"], "Satara was annexed in 1848, the first under the Doctrine of Lapse. Sambalpur (1849), Jhansi (1853) and Nagpur (1854) followed."],
    ["लॉर्ड डलहौज़ी ने व्यपगत के सिद्धांत के अंतर्गत सबसे पहले किस राज्य का विलय किया?", ["झाँसी", "नागपुर", "संबलपुर", "सतारा"], "सतारा का विलय 1848 में हुआ, जो व्यपगत सिद्धांत के अंतर्गत पहला था। इसके बाद संबलपुर (1849), झाँसी (1853) और नागपुर (1854) आए।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["The Poona Pact (1932), which gave reserved seats to the Depressed Classes in the legislatures, was signed between Gandhi and:", ["B.R. Ambedkar", "Jawaharlal Nehru", "Muhammad Ali Jinnah", "Madan Mohan Malaviya"], "After Gandhi's fast in Yerwada jail against the Communal Award, he and B.R. Ambedkar signed the Poona Pact on 24 September 1932."],
    ["पूना समझौता (1932), जिसने विधानमंडलों में दलित वर्गों को आरक्षित सीटें दीं, गांधीजी और किसके बीच हुआ?", ["बी.आर. अंबेडकर", "जवाहरलाल नेहरू", "मुहम्मद अली जिन्ना", "मदन मोहन मालवीय"], "सांप्रदायिक पंचाट के विरुद्ध गांधीजी के यरवदा जेल में उपवास के बाद उन्होंने और बी.आर. अंबेडकर ने 24 सितंबर 1932 को पूना समझौते पर हस्ताक्षर किए।"]),
  q(1, "general-studies", "indian-history", "H", 1,
    ["Who among the following was NOT a member of the Cabinet Mission of 1946?", ["Pethick-Lawrence", "Lord Wavell", "Stafford Cripps", "A.V. Alexander"], "The Cabinet Mission had three members: Pethick-Lawrence, Stafford Cripps and A.V. Alexander. Lord Wavell was the Viceroy, not a member of the Mission."],
    ["निम्नलिखित में से कौन 1946 के कैबिनेट मिशन का सदस्य नहीं था?", ["पैथिक-लॉरेंस", "लॉर्ड वेवल", "स्टैफ़र्ड क्रिप्स", "ए.वी. अलेक्ज़ेंडर"], "कैबिनेट मिशन के तीन सदस्य थे: पैथिक-लॉरेंस, स्टैफ़र्ड क्रिप्स और ए.वी. अलेक्ज़ेंडर। लॉर्ड वेवल वायसराय थे, मिशन के सदस्य नहीं।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["The Greek ambassador at the court of Chandragupta Maurya who wrote the book 'Indica' was:", ["Seleucus", "Antiochus", "Megasthenes", "Ptolemy"], "Megasthenes was sent by Seleucus Nicator to the Mauryan court and described Pataliputra and Mauryan administration in 'Indica'."],
    ["चंद्रगुप्त मौर्य के दरबार में यूनानी राजदूत, जिसने 'इंडिका' पुस्तक लिखी, कौन था?", ["सेल्यूकस", "एंटियोकस", "मेगस्थनीज़", "टॉलेमी"], "मेगस्थनीज़ को सेल्यूकस निकेटर ने मौर्य दरबार में भेजा था और उसने 'इंडिका' में पाटलिपुत्र और मौर्य प्रशासन का वर्णन किया।"]),
  q(1, "general-studies", "indian-history", "M", 3,
    ["The Moroccan traveller Ibn Battuta visited India during the reign of:", ["Alauddin Khilji", "Firoz Shah Tughlaq", "Balban", "Muhammad bin Tughlaq"], "Ibn Battuta came to India in about 1333 and served as a qazi at Muhammad bin Tughlaq's court in Delhi. His book is the 'Rihla'."],
    ["मोरक्को का यात्री इब्न बतूता भारत में किसके शासनकाल में आया?", ["अलाउद्दीन खिलजी", "फ़िरोज़ शाह तुगलक", "बलबन", "मुहम्मद बिन तुगलक"], "इब्न बतूता लगभग 1333 में भारत आया और दिल्ली में मुहम्मद बिन तुगलक के दरबार में क़ाज़ी रहा। उसकी पुस्तक 'रिहला' है।"]),
  q(1, "general-studies", "indian-polity", "H", 0,
    ["A National Emergency under Article 352 was declared for the first time in India in the year:", ["1962", "1971", "1975", "1965"], "The first National Emergency was declared in October 1962 during the war with China. The second was in 1971 (Indo-Pak war) and the third in 1975 (internal disturbance)."],
    ["भारत में अनुच्छेद 352 के अंतर्गत राष्ट्रीय आपातकाल पहली बार किस वर्ष घोषित हुआ?", ["1962", "1971", "1975", "1965"], "पहला राष्ट्रीय आपातकाल अक्टूबर 1962 में चीन युद्ध के समय घोषित हुआ। दूसरा 1971 (भारत-पाक युद्ध) में और तीसरा 1975 (आंतरिक अशांति) में हुआ।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["A joint sitting of the two Houses of Parliament is presided over by:", ["The Vice-President", "The Speaker of the Lok Sabha", "The President", "The Prime Minister"], "Under Article 108, the Speaker of the Lok Sabha presides over a joint sitting. In his absence the Deputy Speaker presides."],
    ["संसद के दोनों सदनों की संयुक्त बैठक की अध्यक्षता कौन करता है?", ["उपराष्ट्रपति", "लोकसभा अध्यक्ष", "राष्ट्रपति", "प्रधानमंत्री"], "अनुच्छेद 108 के अनुसार संयुक्त बैठक की अध्यक्षता लोकसभा अध्यक्ष करता है। उसकी अनुपस्थिति में उपाध्यक्ष अध्यक्षता करता है।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["The words 'Socialist', 'Secular' and 'Integrity' were added to the Preamble by which Constitutional Amendment?", ["24th Amendment", "44th Amendment", "42nd Amendment", "52nd Amendment"], "The 42nd Amendment (1976) added the words Socialist, Secular and Integrity to the Preamble."],
    ["प्रस्तावना में 'समाजवादी', 'पंथनिरपेक्ष' और 'अखंडता' शब्द किस संविधान संशोधन द्वारा जोड़े गए?", ["24वाँ संशोधन", "44वाँ संशोधन", "42वाँ संशोधन", "52वाँ संशोधन"], "42वें संशोधन (1976) ने प्रस्तावना में समाजवादी, पंथनिरपेक्ष और अखंडता शब्द जोड़े।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["The office of the Attorney General of India is provided for under which Article of the Constitution?", ["Article 148", "Article 124", "Article 165", "Article 76"], "Article 76 provides for the Attorney General of India, who is appointed by the President. Article 148 is for the CAG, 124 for the Supreme Court and 165 for the Advocate General of a State."],
    ["भारत के महान्यायवादी का पद संविधान के किस अनुच्छेद के अंतर्गत है?", ["अनुच्छेद 148", "अनुच्छेद 124", "अनुच्छेद 165", "अनुच्छेद 76"], "अनुच्छेद 76 भारत के महान्यायवादी का प्रावधान करता है, जिसे राष्ट्रपति नियुक्त करता है। अनुच्छेद 148 CAG का, 124 सर्वोच्च न्यायालय का और 165 राज्य के महाधिवक्ता का है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["Prohibitory orders against the assembly of four or more persons were issued under which Section of the Code of Criminal Procedure (CrPC)?", ["Section 144", "Section 154", "Section 164", "Section 302"], "Section 144 of the CrPC let a magistrate ban unlawful assembly. Under the new law (BNSS, 2023) the equivalent is Section 163. Section 154 dealt with the FIR."],
    ["चार या अधिक व्यक्तियों के एकत्र होने के विरुद्ध निषेधाज्ञा दंड प्रक्रिया संहिता (CrPC) की किस धारा के अंतर्गत जारी होती थी?", ["धारा 144", "धारा 154", "धारा 164", "धारा 302"], "CrPC की धारा 144 मजिस्ट्रेट को गैरकानूनी जमावड़े पर रोक लगाने देती थी। नए कानून (BNSS, 2023) में इसकी समकक्ष धारा 163 है। धारा 154 FIR से संबंधित थी।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Chilika, the largest brackish-water lagoon in India, lies on the coast of which state?", ["Andhra Pradesh", "Odisha", "West Bengal", "Tamil Nadu"], "Chilika Lake is a brackish-water lagoon on the coast of Odisha and is a Ramsar site."],
    ["भारत की सबसे बड़ी खारे पानी की लैगून चिल्का झील किस राज्य के तट पर स्थित है?", ["आंध्र प्रदेश", "ओडिशा", "पश्चिम बंगाल", "तमिलनाडु"], "चिल्का झील ओडिशा के तट पर स्थित खारे पानी की लैगून है और रामसर स्थल है।"]),
  q(1, "general-studies", "indian-geography", "H", 2,
    ["Which of the following is the largest freshwater lake in India by area, located in Jammu and Kashmir?", ["Dal Lake", "Nagin Lake", "Wular Lake", "Manasbal Lake"], "Wular Lake in Bandipora district is generally regarded as the largest freshwater lake in India."],
    ["जम्मू और कश्मीर में स्थित भारत की सबसे बड़ी मीठे पानी की झील कौन-सी मानी जाती है?", ["डल झील", "नागिन झील", "वुलर झील", "मानसबल झील"], "बांदीपोरा ज़िले की वुलर झील को सामान्यतः भारत की सबसे बड़ी मीठे पानी की झील माना जाता है।"]),
  q(1, "general-studies", "indian-geography", "M", 3,
    ["Kanchenjunga, the third highest mountain in the world, lies on the border of Sikkim and:", ["Bhutan", "Tibet", "Arunachal Pradesh", "Nepal"], "Kanchenjunga (8,586 m) lies on the border between Sikkim (India) and eastern Nepal."],
    ["विश्व की तीसरी सबसे ऊँची चोटी कंचनजंगा सिक्किम और किसकी सीमा पर स्थित है?", ["भूटान", "तिब्बत", "अरुणाचल प्रदेश", "नेपाल"], "कंचनजंगा (8,586 मी) सिक्किम (भारत) और पूर्वी नेपाल की सीमा पर है।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Black soil (regur) is best suited for the cultivation of:", ["Cotton", "Tea", "Jute", "Coffee"], "Black soil is rich in clay, lime and iron and holds moisture, so it suits cotton and is also called 'black cotton soil'."],
    ["काली मिट्टी (रेगुर) किस फ़सल की खेती के लिए सबसे उपयुक्त है?", ["कपास", "चाय", "जूट", "कॉफ़ी"], "काली मिट्टी में चिकनी मिट्टी, चूना और लोहा अधिक होता है और यह नमी रोकती है, इसलिए कपास के लिए उपयुक्त है और 'काली कपास मिट्टी' कहलाती है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Chilika Lake, the largest coastal lagoon in India, is located in which state?", ["Andhra Pradesh","Odisha","West Bengal","Tamil Nadu"], "Chilika Lake is a brackish-water lagoon on the coast of the Bay of Bengal in Odisha. It is the largest coastal lagoon in India."],
    ["भारत की सबसे बड़ी तटीय लैगून, चिल्का झील, किस राज्य में स्थित है?", ["आंध्र प्रदेश","ओडिशा","पश्चिम बंगाल","तमिलनाडु"], "चिल्का झील ओडिशा में बंगाल की खाड़ी के तट पर खारे पानी की लैगून है। यह भारत की सबसे बड़ी तटीय लैगून है।"]),
  q(1, "general-studies", "indian-economy", "M", 2,
    ["Who is regarded as the 'Father of the Green Revolution in India'?", ["Verghese Kurien", "B.P. Pal", "M.S. Swaminathan", "Homi Bhabha"], "M.S. Swaminathan led the Green Revolution in India using high-yielding wheat and rice varieties. Verghese Kurien is the 'Father of the White Revolution'."],
    ["भारत में 'हरित क्रांति का जनक' किसे माना जाता है?", ["वर्गीज़ कुरियन", "बी.पी. पाल", "एम.एस. स्वामीनाथन", "होमी भाभा"], "एम.एस. स्वामीनाथन ने उच्च उपज वाली गेहूँ और चावल की किस्मों से भारत में हरित क्रांति का नेतृत्व किया। वर्गीज़ कुरियन 'श्वेत क्रांति के जनक' हैं।"]),
  q(1, "general-studies", "indian-economy", "M", 3,
    ["The rate at which the RBI lends short-term money to commercial banks against securities is called the:", ["CRR", "SLR", "Reverse repo rate", "Repo rate"], "The repo rate is the rate at which the RBI lends to banks. The reverse repo rate is the rate at which the RBI borrows from banks."],
    ["जिस दर पर RBI वाणिज्यिक बैंकों को प्रतिभूतियों के बदले अल्पकालिक ऋण देता है, वह कहलाती है:", ["CRR", "SLR", "रिवर्स रेपो दर", "रेपो दर"], "रेपो दर वह दर है जिस पर RBI बैंकों को उधार देता है। रिवर्स रेपो दर वह दर है जिस पर RBI बैंकों से उधार लेता है।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["The Pradhan Mantri Jan Dhan Yojana (PMJDY) for financial inclusion was launched in the year:", ["2014", "2015", "2016", "2013"], "PMJDY was launched on 28 August 2014 to give every household a bank account."],
    ["वित्तीय समावेशन के लिए प्रधानमंत्री जन धन योजना (PMJDY) किस वर्ष शुरू हुई?", ["2014", "2015", "2016", "2013"], "PMJDY 28 अगस्त 2014 को हर परिवार को बैंक खाता उपलब्ध कराने के लिए शुरू की गई।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["Which gas makes up the largest part of the Earth's atmosphere?", ["Oxygen", "Nitrogen", "Argon", "Carbon dioxide"], "Nitrogen forms about 78% of dry air, oxygen about 21% and argon about 0.9%."],
    ["पृथ्वी के वायुमंडल का सबसे बड़ा भाग कौन-सी गैस है?", ["ऑक्सीजन", "नाइट्रोजन", "आर्गन", "कार्बन डाइऑक्साइड"], "शुष्क वायु में नाइट्रोजन लगभग 78%, ऑक्सीजन लगभग 21% और आर्गन लगभग 0.9% होती है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["What is the pH value of pure water at 25 °C?", ["0", "14", "7", "1"], "Pure water is neutral, so its pH is 7. Values below 7 are acidic and above 7 are basic."],
    ["25 °C पर शुद्ध जल का pH मान कितना होता है?", ["0", "14", "7", "1"], "शुद्ध जल उदासीन होता है, अतः उसका pH 7 होता है। 7 से कम अम्लीय और 7 से अधिक क्षारीय होता है।"]),
  q(1, "general-studies", "general-science", "H", 3,
    ["Which blood group is known as the universal donor?", ["AB positive", "A negative", "B positive", "O negative"], "O negative red cells have no A, B or Rh antigens, so they can be given to any patient in an emergency. AB positive is the universal recipient."],
    ["कौन-सा रक्त समूह सर्वदाता (यूनिवर्सल डोनर) कहलाता है?", ["AB धनात्मक", "A ऋणात्मक", "B धनात्मक", "O ऋणात्मक"], "O ऋणात्मक की लाल कोशिकाओं में A, B या Rh प्रतिजन नहीं होते, इसलिए आपातकाल में किसी भी रोगी को चढ़ाई जा सकती हैं। AB धनात्मक सर्वग्राही है।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Scurvy, which causes bleeding gums, is caused by a deficiency of which vitamin?", ["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin B12"], "Scurvy is caused by lack of Vitamin C (ascorbic acid), found in citrus fruits, amla and guava."],
    ["मसूड़ों से खून बहाने वाला रोग स्कर्वी किस विटामिन की कमी से होता है?", ["विटामिन C", "विटामिन A", "विटामिन D", "विटामिन B12"], "स्कर्वी विटामिन C (एस्कॉर्बिक अम्ल) की कमी से होता है, जो नींबू वर्गीय फलों, आँवले और अमरूद में मिलता है।"]),
  q(1, "computer", "hardware", "M", 1,
    ["RAM (Random Access Memory) is which type of memory?", ["Non-volatile and read-only", "Volatile and temporary", "Permanent storage", "Optical storage"], "RAM is volatile: it holds data only while the computer is on and loses it when power is switched off."],
    ["RAM (रैंडम एक्सेस मेमोरी) किस प्रकार की मेमोरी है?", ["अस्थिर नहीं और केवल पठन योग्य", "अस्थिर और अस्थायी", "स्थायी भंडारण", "ऑप्टिकल भंडारण"], "RAM अस्थिर (वोलेटाइल) है: कंप्यूटर चालू रहने तक ही डेटा रखती है और बिजली बंद होने पर डेटा खो देती है।"]),
  q(1, "general-studies", "general-science", "H", 2,
    ["Plaster of Paris is chemically known as:", ["Calcium sulphate dihydrate","Calcium carbonate","Calcium sulphate hemihydrate","Calcium oxide"], "Plaster of Paris is calcium sulphate hemihydrate, CaSO4.1/2H2O. Gypsum is the dihydrate, CaSO4.2H2O."],
    ["प्लास्टर ऑफ पेरिस का रासायनिक नाम है:", ["कैल्शियम सल्फेट डाइहाइड्रेट","कैल्शियम कार्बोनेट","कैल्शियम सल्फेट हेमिहाइड्रेट","कैल्शियम ऑक्साइड"], "प्लास्टर ऑफ पेरिस कैल्शियम सल्फेट हेमिहाइड्रेट, CaSO4.1/2H2O है। जिप्सम डाइहाइड्रेट, CaSO4.2H2O है।"]),

  // ───────── Section 2: Reasoning (20) ─────────
  q(2, "reasoning", "series", "M", 0,
    ["Find the next number: 7, 9, 13, 21, 37, ?", ["69", "65", "73", "61"], "The differences are 2, 4, 8, 16 (doubling). The next difference is 32, so 37 + 32 = 69."],
    ["अगली संख्या ज्ञात कीजिए: 7, 9, 13, 21, 37, ?", ["69", "65", "73", "61"], "अंतर 2, 4, 8, 16 (दुगुने) हैं। अगला अंतर 32 है, अतः 37 + 32 = 69।"], "37+32"),
  q(2, "reasoning", "series", "H", 1,
    ["Find the next number: 3, 8, 18, 38, 78, ?", ["148", "158", "156", "162"], "Each term is double the previous term plus 2: 3 → 8 → 18 → 38 → 78 → 78 × 2 + 2 = 158."],
    ["अगली संख्या ज्ञात कीजिए: 3, 8, 18, 38, 78, ?", ["148", "158", "156", "162"], "प्रत्येक पद पिछले पद का दुगुना जमा 2 है: 3 → 8 → 18 → 38 → 78 → 78 × 2 + 2 = 158।"], "78*2+2"),
  q(2, "reasoning", "series", "M", 2,
    ["Find the next number: 6, 11, 21, 36, 56, ?", ["76", "78", "81", "86"], "The differences are 5, 10, 15, 20 (multiples of 5). The next difference is 25, so 56 + 25 = 81."],
    ["अगली संख्या ज्ञात कीजिए: 6, 11, 21, 36, 56, ?", ["76", "78", "81", "86"], "अंतर 5, 10, 15, 20 (5 के गुणज) हैं। अगला अंतर 25 है, अतः 56 + 25 = 81।"], "56+25"),
  q(2, "reasoning", "series", "H", 3,
    ["Find the next term: CEG, FHJ, ILN, ?", ["KMO", "LMO", "MOQ", "LNP"], "Every letter of a group moves 3 places forward to give the next group: CEG → FHJ → ILN → LNP."],
    ["अगला पद ज्ञात कीजिए: CEG, FHJ, ILN, ?", ["KMO", "LMO", "MOQ", "LNP"], "प्रत्येक समूह का हर अक्षर 3 स्थान आगे बढ़कर अगला समूह बनाता है: CEG → FHJ → ILN → LNP।"]),
  q(2, "reasoning", "coding-decoding", "H", 0,
    ["If COURT is coded as DQXVY, how will JUDGE be coded in the same way?", ["KWGKJ", "KWGJK", "LWGKJ", "KVGKJ"], "The letters move forward by 1, 2, 3, 4 and 5 places in turn (C+1 = D, O+2 = Q, U+3 = X, R+4 = V, T+5 = Y). So J+1 = K, U+2 = W, D+3 = G, G+4 = K, E+5 = J, giving KWGKJ."],
    ["यदि COURT को DQXVY लिखा जाए, तो उसी प्रकार JUDGE को कैसे लिखा जाएगा?", ["KWGKJ", "KWGJK", "LWGKJ", "KVGKJ"], "अक्षर क्रमशः 1, 2, 3, 4 और 5 स्थान आगे बढ़ते हैं (C+1 = D, O+2 = Q, U+3 = X, R+4 = V, T+5 = Y)। अतः J+1 = K, U+2 = W, D+3 = G, G+4 = K, E+5 = J, यानी KWGKJ।"]),
  q(2, "reasoning", "math-operations", "H", 1,
    ["If 3 * 4 = 25, 5 * 12 = 169, then 8 * 15 = ?", ["225", "289", "273", "256"], "The rule is a * b = a² + b²: 3² + 4² = 25 and 5² + 12² = 169. So 8² + 15² = 64 + 225 = 289."],
    ["यदि 3 * 4 = 25, 5 * 12 = 169, तो 8 * 15 = ?", ["225", "289", "273", "256"], "नियम a * b = a² + b² है: 3² + 4² = 25 और 5² + 12² = 169। अतः 8² + 15² = 64 + 225 = 289।"], "8*8+15*15"),
  q(2, "reasoning", "blood-relations", "H", 2,
    ["A is the sister of B. C is the mother of B. D is the father of C. E is the mother of D. How is A related to E?", ["Daughter", "Granddaughter", "Great-granddaughter", "Niece"], "E is D's mother and D is C's father, so E is C's grandmother. C is the mother of A and B, so E is their great-grandmother. A is E's great-granddaughter."],
    ["A, B की बहन है। C, B की माता है। D, C का पिता है। E, D की माता है। A का E से क्या संबंध है?", ["पुत्री", "पौत्री", "परपौत्री", "भतीजी"], "E, D की माता है और D, C का पिता है, अतः E, C की दादी है। C, A और B की माता है, अतः E उनकी परदादी है। A, E की परपौत्री है।"]),
  q(2, "reasoning", "blood-relations", "M", 3,
    ["The only son of the sister of Vikram's father is related to Vikram as:", ["Brother", "Uncle", "Nephew", "Cousin"], "The sister of Vikram's father is his paternal aunt. Her son is Vikram's cousin."],
    ["विक्रम के पिता की बहन का इकलौता पुत्र विक्रम का क्या लगता है?", ["भाई", "चाचा", "भतीजा", "चचेरा भाई"], "विक्रम के पिता की बहन उसकी बुआ है। उसका पुत्र विक्रम का ममेरा/फुफेरा (चचेरा) भाई है।"]),
  q(2, "reasoning", "direction-sense", "H", 0,
    ["Meena walks 20 m east, then turns north and walks 15 m, then turns west and walks 35 m, and finally turns south and walks 15 m. Where is she now with respect to her starting point?", ["15 m west", "15 m east", "35 m west", "20 m west"], "Taking east as positive: x = 20 − 35 = −15 and the north and south walks cancel out. She is 15 m west of the starting point."],
    ["मीना 20 मी पूर्व चलती है, फिर उत्तर मुड़कर 15 मी चलती है, फिर पश्चिम मुड़कर 35 मी चलती है और अंत में दक्षिण मुड़कर 15 मी चलती है। अब वह अपने आरंभिक बिंदु से किस स्थिति में है?", ["15 मी पश्चिम", "15 मी पूर्व", "35 मी पश्चिम", "20 मी पश्चिम"], "पूर्व को धनात्मक मानें: x = 20 − 35 = −15 और उत्तर-दक्षिण की चालें कट जाती हैं। वह आरंभिक बिंदु से 15 मी पश्चिम में है।"]),
  q(2, "reasoning", "ranking", "H", 1,
    ["In a queue, Amit is 14th from the front. Sumit stands behind Amit with 6 persons between them, and Sumit is 9th from the back. How many persons are there in the queue?", ["27", "29", "30", "31"], "Sumit's position from the front = 14 + 6 + 1 = 21. Total = 21 + 9 − 1 = 29."],
    ["एक पंक्ति में अमित आगे से 14वें स्थान पर है। सुमित, अमित के पीछे है और दोनों के बीच 6 व्यक्ति हैं। सुमित पीछे से 9वें स्थान पर है। पंक्ति में कुल कितने व्यक्ति हैं?", ["27", "29", "30", "31"], "सुमित की आगे से स्थिति = 14 + 6 + 1 = 21। कुल = 21 + 9 − 1 = 29।"], "14+6+1+9-1"),
  q(2, "reasoning", "puzzles", "H", 2,
    ["Six persons A, B, C, D, E and F sit in a row facing north. D sits at the extreme right end. B sits immediately to the right of A. E sits immediately to the left of A. C sits immediately to the left of E. Who sits third from the left?", ["A", "C", "E", "F"], "The chain C, E, A, B sits together in that order and D is at the right end. F is the remaining person, so the order is F, C, E, A, B, D. The third from the left is E."],
    ["छह व्यक्ति A, B, C, D, E और F उत्तर की ओर मुँह करके एक पंक्ति में बैठे हैं। D सबसे दाएँ छोर पर है। B, A के ठीक दाएँ बैठा है। E, A के ठीक बाएँ बैठा है। C, E के ठीक बाएँ बैठा है। बाएँ से तीसरे स्थान पर कौन है?", ["A", "C", "E", "F"], "C, E, A, B इसी क्रम में साथ बैठे हैं और D दाएँ छोर पर है। बचा हुआ व्यक्ति F है, अतः क्रम F, C, E, A, B, D है। बाएँ से तीसरा E है।"]),
  q(2, "reasoning", "analogy", "H", 3,
    ["12 : 156 :: 15 : ?", ["225", "210", "256", "240"], "The rule is n × (n + 1): 12 × 13 = 156, so 15 × 16 = 240."],
    ["12 : 156 :: 15 : ?", ["225", "210", "256", "240"], "नियम n × (n + 1) है: 12 × 13 = 156, अतः 15 × 16 = 240।"], "15*16"),
  q(2, "reasoning", "odd-one-out", "H", 0,
    ["Find the odd one out: KMO, PRT, BDF, GJL", ["GJL", "KMO", "PRT", "BDF"], "In KMO, PRT and BDF the letters increase by 2 each time. In GJL the gaps are 3 and 2, so GJL is the odd one out."],
    ["विषम चुनिए: KMO, PRT, BDF, GJL", ["GJL", "KMO", "PRT", "BDF"], "KMO, PRT और BDF में अक्षर हर बार 2 बढ़ते हैं। GJL में अंतर 3 और 2 है, अतः GJL विषम है।"]),
  q(2, "reasoning", "odd-one-out", "M", 1,
    ["Find the odd one out: 8, 27, 64, 100, 125", ["64", "100", "125", "27"], "8, 27, 64 and 125 are cubes (2³, 3³, 4³, 5³). 100 is not a perfect cube."],
    ["विषम चुनिए: 8, 27, 64, 100, 125", ["64", "100", "125", "27"], "8, 27, 64 और 125 पूर्ण घन हैं (2³, 3³, 4³, 5³)। 100 पूर्ण घन नहीं है।"]),
  q(2, "reasoning", "syllogism", "H", 2,
    ["Statements: Some pens are books. All books are tables. No table is a chair. Conclusions: I. Some pens are tables. II. No book is a chair.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "The pens that are books are tables, so some pens are tables (I). All books are tables and no table is a chair, so no book is a chair (II). Both follow."],
    ["कथन: कुछ पेन किताबें हैं। सभी किताबें मेज़ें हैं। कोई मेज़ कुर्सी नहीं है। निष्कर्ष: I. कुछ पेन मेज़ें हैं। II. कोई किताब कुर्सी नहीं है।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "जो पेन किताबें हैं वे मेज़ें हैं, अतः कुछ पेन मेज़ें हैं (I)। सभी किताबें मेज़ें हैं और कोई मेज़ कुर्सी नहीं, अतः कोई किताब कुर्सी नहीं है (II)। दोनों अनुसरण करते हैं।"]),
  q(2, "reasoning", "clock-calendar", "H", 3,
    ["If 7 March is a Monday, what day of the week will 7 June of the same year be?", ["Sunday", "Monday", "Wednesday", "Tuesday"], "From 7 March to 7 June there are 31 + 30 + 31 = 92 days. 92 = 13 weeks + 1 day, so the day is one after Monday, which is Tuesday."],
    ["यदि 7 मार्च को सोमवार है, तो उसी वर्ष 7 जून को कौन-सा दिन होगा?", ["रविवार", "सोमवार", "बुधवार", "मंगलवार"], "7 मार्च से 7 जून तक 31 + 30 + 31 = 92 दिन हैं। 92 = 13 सप्ताह + 1 दिन, अतः सोमवार के एक दिन बाद, यानी मंगलवार।"]),
  q(2, "reasoning", "clock-calendar", "H", 0,
    ["How many times do the hands of a clock coincide (overlap) between 3:00 and 9:00?", ["6", "5", "7", "4"], "The hands overlap once every 12/11 hours: at about 3:16, 4:22, 5:27, 6:33, 7:38 and 8:44. There are 6 overlaps between 3:00 and 9:00."],
    ["3:00 और 9:00 के बीच घड़ी की सुइयाँ कितनी बार एक-दूसरे पर आती (एक साथ होती) हैं?", ["6", "5", "7", "4"], "सुइयाँ हर 12/11 घंटे में एक बार एक-दूसरे पर आती हैं: लगभग 3:16, 4:22, 5:27, 6:33, 7:38 और 8:44 पर। 3:00 और 9:00 के बीच 6 बार।"]),
  q(2, "reasoning", "puzzles", "H", 1,
    ["Statement: 'The police department has advised citizens never to share their OTP with anyone.' Assumptions: I. Sharing an OTP can lead to fraud. II. All citizens share their OTP regularly.", ["Both I and II are implicit", "Only assumption I is implicit", "Only assumption II is implicit", "Neither I nor II is implicit"], "The advice makes sense only if sharing an OTP is risky, so I is implicit. The advice does not assume that everyone already shares OTPs, so II is not implicit."],
    ["कथन: 'पुलिस विभाग ने नागरिकों को सलाह दी है कि वे अपना OTP कभी किसी से साझा न करें।' अभिधारणाएँ: I. OTP साझा करने से धोखाधड़ी हो सकती है। II. सभी नागरिक नियमित रूप से अपना OTP साझा करते हैं।", ["I और II दोनों निहित हैं", "केवल अभिधारणा I निहित है", "केवल अभिधारणा II निहित है", "न I न II निहित है"], "यह सलाह तभी सार्थक है जब OTP साझा करना जोखिम भरा हो, अतः I निहित है। सलाह यह नहीं मानती कि सभी पहले से OTP साझा करते हैं, अतः II निहित नहीं है।"]),
  q(2, "reasoning", "dice-cube", "H", 2,
    ["A cube of side 5 cm is painted red on all faces and then cut into 125 cubes of side 1 cm. How many small cubes have exactly two faces painted?", ["24", "30", "36", "48"], "Cubes with exactly two painted faces lie along the edges, excluding the corners: 12 edges × (5 − 2) = 36."],
    ["5 सेमी भुजा वाले एक घन के सभी फलक लाल रंगे गए और फिर उसे 1 सेमी भुजा वाले 125 घनों में काटा गया। कितने छोटे घनों के ठीक दो फलक रंगे होंगे?", ["24", "30", "36", "48"], "ठीक दो रंगे फलक वाले घन किनारों पर होते हैं, कोनों को छोड़कर: 12 किनारे × (5 − 2) = 36।"], "12*3"),
  q(2, "reasoning", "clock-calendar", "H", 3,
    ["The time in a clock's mirror image appears as 4:25. What is the actual time?", ["7:25", "8:35", "6:35", "7:35"], "Actual time = 12:00 − mirror time = 11:60 − 4:25 = 7:35."],
    ["घड़ी के दर्पण प्रतिबिंब में समय 4:25 दिखता है। वास्तविक समय क्या है?", ["7:25", "8:35", "6:35", "7:35"], "वास्तविक समय = 12:00 − दर्पण समय = 11:60 − 4:25 = 7:35।"]),

  // ───────── Section 3: Numerical Ability (15) ─────────
  q(3, "quant", "percentage", "H", 0,
    ["In an office of 200 employees, 60% are men. If 25% of the men and 40% of the women are graduates, how many employees are graduates?", ["62", "60", "64", "58"], "Men = 120 and women = 80. Graduates = 25% of 120 + 40% of 80 = 30 + 32 = 62."],
    ["200 कर्मचारियों वाले एक कार्यालय में 60% पुरुष हैं। यदि 25% पुरुष और 40% महिलाएँ स्नातक हैं, तो कितने कर्मचारी स्नातक हैं?", ["62", "60", "64", "58"], "पुरुष = 120 और महिलाएँ = 80। स्नातक = 120 का 25% + 80 का 40% = 30 + 32 = 62।"], "0.25*120+0.4*80"),
  q(3, "quant", "percentage", "M", 1,
    ["If the side of a square is increased by 20%, its area increases by:", ["40%", "44%", "42%", "20%"], "New area = (1.2)² = 1.44 times the old area, an increase of 44%."],
    ["यदि किसी वर्ग की भुजा 20% बढ़ा दी जाए, तो उसका क्षेत्रफल कितने प्रतिशत बढ़ेगा?", ["40%", "44%", "42%", "20%"], "नया क्षेत्रफल = (1.2)² = पुराने का 1.44 गुना, यानी 44% की वृद्धि।"], "(1.2*1.2-1)*100"),
  q(3, "quant", "profit-loss", "H", 2,
    ["A sells an article to B at a profit of 20%, and B sells it to C at a profit of 10%. If C pays ₹1,320, what did the article cost A?", ["₹900", "₹960", "₹1,000", "₹1,100"], "C's price = CP × 1.2 × 1.1 = 1.32 × CP. So CP = 1,320 ÷ 1.32 = ₹1,000."],
    ["A एक वस्तु B को 20% लाभ पर बेचता है और B उसे C को 10% लाभ पर बेचता है। यदि C ₹1,320 देता है, तो A का क्रय मूल्य क्या था?", ["₹900", "₹960", "₹1,000", "₹1,100"], "C का मूल्य = क्रय मूल्य × 1.2 × 1.1 = 1.32 × क्रय मूल्य। अतः क्रय मूल्य = 1,320 ÷ 1.32 = ₹1,000।"], "1320/1.32"),
  q(3, "quant", "profit-loss", "H", 3,
    ["A shopkeeper sells two articles at ₹1,200 each, one at a 20% profit and the other at a 20% loss. What is the overall result?", ["No gain, no loss", "Gain of 4%", "Loss of 2%", "Loss of 4%"], "CP of the first = 1,200 ÷ 1.2 = ₹1,000 and of the second = 1,200 ÷ 0.8 = ₹1,500. Total CP = ₹2,500 and total SP = ₹2,400, so the loss = 100/2,500 = 4%."],
    ["एक दुकानदार दो वस्तुएँ ₹1,200 प्रति वस्तु पर बेचता है, एक पर 20% लाभ और दूसरी पर 20% हानि। कुल परिणाम क्या रहा?", ["न लाभ न हानि", "4% लाभ", "2% हानि", "4% हानि"], "पहली का क्रय मूल्य = 1,200 ÷ 1.2 = ₹1,000 और दूसरी का = 1,200 ÷ 0.8 = ₹1,500। कुल क्रय मूल्य = ₹2,500 और कुल विक्रय मूल्य = ₹2,400, अतः हानि = 100/2,500 = 4%।"]),
  q(3, "quant", "interest", "M", 0,
    ["In how many years will ₹5,000 amount to ₹6,800 at 8% per annum simple interest?", ["4.5 years", "4 years", "5 years", "3.5 years"], "Interest = 6,800 − 5,000 = ₹1,800. Interest per year = 8% of 5,000 = ₹400. Time = 1,800 ÷ 400 = 4.5 years."],
    ["8% वार्षिक साधारण ब्याज की दर से ₹5,000 कितने वर्षों में ₹6,800 हो जाएगा?", ["4.5 वर्ष", "4 वर्ष", "5 वर्ष", "3.5 वर्ष"], "ब्याज = 6,800 − 5,000 = ₹1,800। प्रति वर्ष ब्याज = 5,000 का 8% = ₹400। समय = 1,800 ÷ 400 = 4.5 वर्ष।"], "1800/400"),
  q(3, "quant", "interest", "H", 1,
    ["The population of a town grows by 10% every year. If it is 60,500 now, what was it 2 years ago?", ["48,000", "50,000", "55,000", "52,500"], "Present = Past × (1.1)² = Past × 1.21. So Past = 60,500 ÷ 1.21 = 50,000."],
    ["किसी नगर की जनसंख्या हर वर्ष 10% बढ़ती है। यदि वह अब 60,500 है, तो 2 वर्ष पहले कितनी थी?", ["48,000", "50,000", "55,000", "52,500"], "वर्तमान = पहले की × (1.1)² = पहले की × 1.21। अतः पहले की = 60,500 ÷ 1.21 = 50,000।"], "60500/1.21"),
  q(3, "quant", "time-work", "H", 2,
    ["A is twice as efficient as B, and together they can finish a work in 18 days. In how many days can A alone finish the work?", ["36", "30", "27", "24"], "Let B's daily work be x, so A's is 2x. Together 3x = 1/18, so x = 1/54. A's daily work = 2/54 = 1/27, so A takes 27 days."],
    ["A, B से दुगुना कुशल है और दोनों मिलकर काम 18 दिन में पूरा करते हैं। A अकेला कितने दिन में काम पूरा करेगा?", ["36", "30", "27", "24"], "मान लें B का दैनिक कार्य x है, तो A का 2x। साथ में 3x = 1/18, अतः x = 1/54। A का दैनिक कार्य = 2/54 = 1/27, अतः A को 27 दिन लगेंगे।"], "18*3/2"),
  q(3, "quant", "speed-distance", "H", 3,
    ["Two runners start together from the same point of a circular track of 400 m and run in the same direction at 6 m/s and 4 m/s. After how many seconds will they meet for the first time?", ["100 s", "400 s", "150 s", "200 s"], "The faster runner must gain one full lap of 400 m. Relative speed = 6 − 4 = 2 m/s, so time = 400 ÷ 2 = 200 s."],
    ["दो धावक 400 मी के वृत्ताकार पथ के एक ही बिंदु से साथ-साथ एक ही दिशा में 6 मी/से और 4 मी/से की चाल से दौड़ना शुरू करते हैं। वे पहली बार कितने सेकंड बाद मिलेंगे?", ["100 से", "400 से", "150 से", "200 से"], "तेज़ धावक को 400 मी का एक पूरा चक्कर बढ़ाना है। सापेक्ष चाल = 6 − 4 = 2 मी/से, अतः समय = 400 ÷ 2 = 200 से।"], "400/2"),
  q(3, "quant", "average", "M", 0,
    ["The average of 5 numbers is 27. When one number is removed, the average of the remaining four becomes 25. What is the number removed?", ["35", "30", "40", "32"], "Sum of five = 5 × 27 = 135. Sum of four = 4 × 25 = 100. The removed number = 135 − 100 = 35."],
    ["5 संख्याओं का औसत 27 है। एक संख्या हटाने पर शेष चार का औसत 25 हो जाता है। हटाई गई संख्या क्या है?", ["35", "30", "40", "32"], "पाँचों का योग = 5 × 27 = 135। चारों का योग = 4 × 25 = 100। हटाई गई संख्या = 135 − 100 = 35।"], "135-100"),
  q(3, "quant", "ratio-proportion", "M", 1,
    ["What is the fourth proportional to 4, 6 and 10?", ["12", "15", "18", "20"], "If 4 : 6 = 10 : x, then x = (6 × 10) ÷ 4 = 15."],
    ["4, 6 और 10 का चतुर्थानुपाती क्या है?", ["12", "15", "18", "20"], "यदि 4 : 6 = 10 : x, तो x = (6 × 10) ÷ 4 = 15।"], "6*10/4"),
  q(3, "quant", "mensuration", "M", 2,
    ["The area of a square is 128 cm². What is the length of its diagonal?", ["12 cm", "14 cm", "16 cm", "18 cm"], "Area = diagonal² ÷ 2, so diagonal² = 256 and the diagonal = 16 cm."],
    ["एक वर्ग का क्षेत्रफल 128 सेमी² है। उसके विकर्ण की लंबाई क्या है?", ["12 सेमी", "14 सेमी", "16 सेमी", "18 सेमी"], "क्षेत्रफल = विकर्ण² ÷ 2, अतः विकर्ण² = 256 और विकर्ण = 16 सेमी।"], "Math.sqrt(2*128)"),
  q(3, "quant", "number-system", "H", 0,
    ["What is the remainder when `2^100` is divided by 7?", ["2", "1", "4", "3"], "Since 2³ = 8 leaves remainder 1 when divided by 7, 2^99 = (2³)^33 leaves remainder 1. So 2^100 = 2^99 × 2 leaves remainder 2."],
    ["`2^100` को 7 से भाग देने पर शेषफल क्या होगा?", ["2", "1", "4", "3"], "चूँकि 2³ = 8 को 7 से भाग देने पर शेष 1 बचता है, अतः 2^99 = (2³)^33 का शेष 1 है। इसलिए 2^100 = 2^99 × 2 का शेष 2 है।"], "2"),
  q(3, "quant", "algebra", "H", 1,
    ["If a + b = 7 and a² + b² = 25, what is the value of ab?", ["10", "12", "14", "24"], "(a + b)² = a² + b² + 2ab, so 49 = 25 + 2ab and ab = 12."],
    ["यदि a + b = 7 और a² + b² = 25, तो ab का मान क्या है?", ["10", "12", "14", "24"], "(a + b)² = a² + b² + 2ab, अतः 49 = 25 + 2ab और ab = 12।"], "(49-25)/2"),
  q(3, "quant", "percentage", "M", 2,
    ["A person spends 40% of his income on food, 20% on rent and 15% on transport. If he saves ₹9,000 a month, what is his monthly income?", ["₹32,000", "₹34,000", "₹36,000", "₹40,000"], "Spending = 40 + 20 + 15 = 75%, so savings = 25% of income = ₹9,000. Income = 9,000 ÷ 0.25 = ₹36,000."],
    ["एक व्यक्ति अपनी आय का 40% भोजन, 20% किराये और 15% यात्रा पर खर्च करता है। यदि वह प्रति माह ₹9,000 बचाता है, तो उसकी मासिक आय क्या है?", ["₹32,000", "₹34,000", "₹36,000", "₹40,000"], "खर्च = 40 + 20 + 15 = 75%, अतः बचत = आय का 25% = ₹9,000। आय = 9,000 ÷ 0.25 = ₹36,000।"], "9000/0.25"),
  q(3, "quant", "hcf-lcm", "H", 3,
    ["What is the greatest number that divides 245 and 1,029, leaving a remainder of 5 in each case?", ["8", "12", "24", "16"], "The required number is the HCF of (245 − 5) and (1,029 − 5), i.e. of 240 and 1,024. 240 = 2⁴ × 15 and 1,024 = 2¹⁰, so the HCF = 16."],
    ["वह महत्तम संख्या क्या है जिससे 245 और 1,029 को भाग देने पर प्रत्येक बार शेषफल 5 बचता है?", ["8", "12", "24", "16"], "अभीष्ट संख्या (245 − 5) और (1,029 − 5), यानी 240 और 1,024 का म.स. है। 240 = 2⁴ × 15 और 1,024 = 2¹⁰, अतः म.स. = 16।"], "16"),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "english", "grammar", "M", 0,
    ["Fill in the blank: 'She is senior ___ me by two years.'", ["to", "than", "from", "of"], "Adjectives such as senior, junior, superior and inferior take 'to', not 'than': 'senior to me'."],
    ["रिक्त स्थान भरिए: 'She is senior ___ me by two years.'", ["to", "than", "from", "of"], "Senior, junior, superior और inferior जैसे विशेषणों के साथ 'than' नहीं, 'to' आता है: 'senior to me'।"]),
  q(4, "english", "grammar", "H", 3,
    ["Fill in the blank: 'Neither of the two answers ___ correct.'", ["are", "were", "have been", "is"], "'Neither' refers to each one separately and takes a singular verb: 'Neither of the answers is correct'."],
    ["रिक्त स्थान भरिए: 'Neither of the two answers ___ correct.'", ["are", "were", "have been", "is"], "'Neither' प्रत्येक को अलग-अलग दर्शाता है और एकवचन क्रिया लेता है: 'Neither of the answers is correct'।"]),
  q(4, "english", "synonyms-antonyms", "M", 1,
    ["Choose the synonym of 'MITIGATE':", ["Aggravate", "Alleviate", "Provoke", "Postpone"], "To mitigate means to make less severe, which is the same as to alleviate. Aggravate means to make worse."],
    ["'MITIGATE' का समानार्थी शब्द चुनिए:", ["Aggravate", "Alleviate", "Provoke", "Postpone"], "Mitigate का अर्थ है कम गंभीर करना, जो alleviate के समान है। Aggravate का अर्थ है और बिगाड़ना।"]),
  q(4, "english", "synonyms-antonyms", "H", 3,
    ["Choose the antonym of 'BENEVOLENT':", ["Generous", "Kind", "Charitable", "Malevolent"], "Benevolent means well-meaning and kind. Its opposite is malevolent, meaning wishing harm to others."],
    ["'BENEVOLENT' का विलोम शब्द चुनिए:", ["Generous", "Kind", "Charitable", "Malevolent"], "Benevolent का अर्थ है परोपकारी और दयालु। इसका विलोम malevolent है, जिसका अर्थ है दूसरों का बुरा चाहने वाला।"]),
  q(4, "english", "one-word", "H", 2,
    ["One word for 'a lover of books':", ["Bibliographer","Librarian","Bibliophile","Bibliophobe"], "A bibliophile is a lover or collector of books. A bibliographer writes lists of books, and a bibliophobe fears books."],
    ["'पुस्तकों से प्रेम करने वाला' के लिए एक शब्द:", ["Bibliographer","Librarian","Bibliophile","Bibliophobe"], "Bibliophile पुस्तक-प्रेमी होता है। Bibliographer पुस्तक-सूची बनाने वाला होता है और bibliophobe को पुस्तकों से भय होता है।"]),
  q(4, "english", "idioms", "M", 3,
    ["Choose the meaning of the idiom 'to bury the hatchet':", ["To hide a weapon", "To start a fight", "To dig a grave", "To end a quarrel and make peace"], "To bury the hatchet means to stop quarrelling and become friends again."],
    ["मुहावरे 'to bury the hatchet' का अर्थ चुनिए:", ["हथियार छिपाना", "झगड़ा शुरू करना", "कब्र खोदना", "झगड़ा समाप्त कर मेल कर लेना"], "To bury the hatchet का अर्थ है झगड़ा छोड़कर फिर से मित्र बन जाना।"]),
  q(4, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'Each of the students / have submitted / his assignment. / No error'", ["Each of the students", "have submitted", "his assignment.", "No error"], "'Each' is singular, so the verb must be 'has submitted'."],
    ["त्रुटि वाला भाग चुनिए: 'Each of the students / have submitted / his assignment. / No error'", ["Each of the students", "have submitted", "his assignment.", "No error"], "'Each' एकवचन है, अतः क्रिया 'has submitted' होनी चाहिए।"]),
  q(4, "english", "voice-speech", "H", 0,
    ["Change into indirect speech: She said, 'I will call you tomorrow.'", ["She said that she would call me the next day.", "She said that she will call you tomorrow.", "She said that I would call her the next day.", "She told that she would call me the next day."], "In indirect speech 'will' becomes 'would', 'I' becomes 'she', 'you' becomes 'me' and 'tomorrow' becomes 'the next day'."],
    ["अप्रत्यक्ष कथन (Indirect speech) में बदलिए: She said, 'I will call you tomorrow.'", ["She said that she would call me the next day.", "She said that she will call you tomorrow.", "She said that I would call her the next day.", "She told that she would call me the next day."], "अप्रत्यक्ष कथन में 'will' का 'would', 'I' का 'she', 'you' का 'me' और 'tomorrow' का 'the next day' हो जाता है।"]),
  q(4, "hindi", "sandhi-samas", "M", 0,
    ["Choose the correct split of the sandhi word 'देवालय':", ["देव + आलय","देवा + लय","देव + लय","दे + वालय"], "'देवालय' = देव + आलय. Here अ + आ = आ, which is a dirgha sandhi."],
    ["'देवालय' का सही संधि-विच्छेद चुनिए:", ["देव + आलय","देवा + लय","देव + लय","दे + वालय"], "'देवालय' = देव + आलय। यहाँ अ + आ = आ हुआ है, यह दीर्घ संधि है।"]),
  q(4, "hindi", "sandhi-samas", "H", 2,
    ["Identify the type of compound (samas) in 'पंचवटी' (a place of five banyan trees):", ["Tatpurush", "Karmadharaya", "Dvigu", "Bahuvrihi"], "'पंचवटी' = पाँच वटों का समूह. The first part is a number and the compound means a group, so it is a Dvigu samas."],
    ["'पंचवटी' (पाँच वट वृक्षों का स्थान) शब्द में कौन-सा समास है?", ["तत्पुरुष", "कर्मधारय", "द्विगु", "बहुव्रीहि"], "'पंचवटी' = पाँच वटों का समूह। पहला पद संख्यावाचक है और समास समूह का बोध कराता है, अतः द्विगु समास है।"]),
  q(4, "hindi", "muhavare", "M", 3,
    ["What is the meaning of the Hindi idiom 'आँखों में धूल झोंकना'?", ["To have eye pain", "To become very angry", "To weep", "To deceive someone"], "The idiom means to deceive or cheat someone."],
    ["'आँखों में धूल झोंकना' मुहावरे का अर्थ है:", ["आँखों में दर्द होना", "बहुत क्रोधित होना", "रोना", "धोखा देना"], "इस मुहावरे का अर्थ है किसी को धोखा देना या चकमा देना।"]),
  q(4, "hindi", "paryay-vilom", "H", 3,
    ["Which of these is NOT a synonym of 'घोड़ा' (horse)?", ["अश्व","तुरंग","हय","गज"], "अश्व, तुरंग and हय all mean horse. 'गज' means the elephant."],
    ["निम्नलिखित में से कौन-सा 'घोड़ा' का पर्यायवाची नहीं है?", ["अश्व","तुरंग","हय","गज"], "अश्व, तुरंग और हय घोड़े के पर्यायवाची हैं। 'गज' का अर्थ हाथी है।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["Choose the antonym of the Hindi word 'स्वतंत्र' (independent):", ["परतंत्र", "स्वाधीन", "आज़ाद", "मुक्त"], "The opposite of 'स्वतंत्र' (independent) is 'परतंत्र' (dependent, under another's control). The other three mean free."],
    ["'स्वतंत्र' शब्द का विलोम चुनिए:", ["परतंत्र", "स्वाधीन", "आज़ाद", "मुक्त"], "'स्वतंत्र' का विलोम 'परतंत्र' (दूसरे के अधीन) है। शेष तीनों का अर्थ स्वतंत्र ही है।"]),
  q(4, "hindi", "ek-shabd", "M", 1,
    ["Choose the one word for 'one who speaks little' (जो कम बोलता हो):", ["वाचाल", "मितभाषी", "मृदुभाषी", "अल्पज्ञ"], "One who speaks little is 'मितभाषी'. 'वाचाल' talks too much, 'मृदुभाषी' speaks softly and 'अल्पज्ञ' knows little."],
    ["'जो कम बोलता हो' के लिए एक शब्द चुनिए:", ["वाचाल", "मितभाषी", "मृदुभाषी", "अल्पज्ञ"], "कम बोलने वाला 'मितभाषी' होता है। 'वाचाल' बहुत बोलता है, 'मृदुभाषी' मधुर बोलता है और 'अल्पज्ञ' कम जानता है।"]),
  q(4, "hindi", "shuddh-vartani", "H", 2,
    ["Choose the correctly spelt Hindi word for 'bright, radiant':", ["उज्जवल", "उज्वल", "उज्ज्वल", "उजज्वल"], "The correct spelling is 'उज्ज्वल', formed from उत् + ज्वल, with the conjunct ज्ज्व."],
    ["'चमकीला, प्रकाशमान' के लिए शुद्ध वर्तनी वाला शब्द चुनिए:", ["उज्जवल", "उज्वल", "उज्ज्वल", "उजज्वल"], "शुद्ध वर्तनी 'उज्ज्वल' है, जो उत् + ज्वल से बना है और जिसमें संयुक्ताक्षर ज्ज्व है।"]),
];
