// HP Police Constable Full Mock 1 — 100 questions (25 HP GK, 25 GK, 20 Reasoning, 15 Maths, 15 Hindi/English).

import { q, type PoliceQuestion } from "./types";

export const mock1: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK (25) ─────────
  q(0, "hp-gk", "history", "H", 0,
    ["The hill state of Suket was founded by Bir Sen in about 765 AD. What was its first capital?", ["Pangna", "Lohara", "Karangarh", "Sundernagar"], "Bir Sen founded Suket with Pangna as its capital. The capital later moved to Lohara, then Karangarh, and finally to Bhojpur–Sundernagar."],
    ["सुकेत पहाड़ी रियासत की स्थापना बीर सेन ने लगभग 765 ई. में की। इसकी पहली राजधानी कौन-सी थी?", ["पांगणा", "लोहारा", "करनगढ़", "सुंदरनगर"], "बीर सेन ने पांगणा को राजधानी बनाकर सुकेत की स्थापना की। बाद में राजधानी लोहारा, फिर करनगढ़ और अंत में भोजपुर–सुंदरनगर गई।"]),
  q(0, "hp-gk", "history", "H", 0,
    ["The idol of Lord Raghunath was brought from Ayodhya to Kullu in the 17th century during the reign of Raja:", ["Jagat Singh", "Bahadur Singh", "Man Singh", "Pritam Singh"], "Raja Jagat Singh of Kullu had the idol of Raghunath brought from Ayodhya (by Damodar Das) and declared Raghunath the ruling deity of Kullu. This is the origin of the Kullu Dussehra tradition."],
    ["17वीं शताब्दी में भगवान रघुनाथ की मूर्ति अयोध्या से कुल्लू किस राजा के शासनकाल में लाई गई?", ["जगत सिंह", "बहादुर सिंह", "मान सिंह", "प्रीतम सिंह"], "कुल्लू के राजा जगत सिंह ने (दामोदर दास के माध्यम से) रघुनाथ जी की मूर्ति अयोध्या से मँगवाई और रघुनाथ जी को कुल्लू का अधिष्ठाता देवता घोषित किया। कुल्लू दशहरे की परंपरा यहीं से शुरू हुई।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["Which Mughal emperor captured the Kangra Fort in 1620 after a long siege?", ["Akbar", "Jahangir", "Shah Jahan", "Aurangzeb"], "Kangra Fort fell to the Mughals in 1620 during Jahangir's reign. Jahangir visited it in 1622, and the 'Jahangiri Darwaza' of the fort is named after him."],
    ["किस मुगल बादशाह ने लंबी घेराबंदी के बाद 1620 में कांगड़ा किले पर अधिकार किया?", ["अकबर", "जहाँगीर", "शाहजहाँ", "औरंगज़ेब"], "जहाँगीर के शासनकाल में 1620 में कांगड़ा किला मुगलों के अधिकार में आया। जहाँगीर 1622 में यहाँ आया और किले का 'जहाँगीरी दरवाज़ा' उसी के नाम पर है।"]),
  q(0, "hp-gk", "history", "H", 2,
    ["The princely state of Guler, famous for its school of Pahari painting, was founded in 1405 by Raja:", ["Sansar Chand", "Karam Chand", "Hari Chand", "Dharam Chand"], "Raja Hari Chand of the Kangra (Katoch) family founded Guler, with its capital at Haripur. The Guler school later became a major centre of Pahari miniature painting."],
    ["पहाड़ी चित्रकला की शैली के लिए प्रसिद्ध गुलेर रियासत की स्थापना 1405 में किस राजा ने की?", ["संसार चंद", "करम चंद", "हरि चंद", "धर्म चंद"], "कांगड़ा (कटोच) वंश के राजा हरि चंद ने हरिपुर को राजधानी बनाकर गुलेर की स्थापना की। गुलेर शैली बाद में पहाड़ी लघुचित्रकला का प्रमुख केंद्र बनी।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["The Suket Satyagraha of February 1948, which forced the ruler of Suket to join the new Himachal Pradesh, was led by:", ["Dr Y.S. Parmar", "Baba Kanshi Ram", "Lala Lajpat Rai", "Satyanand Stokes"], "Dr Y.S. Parmar led the Suket Satyagraha in 1948. Baba Kanshi Ram ('Pahari Gandhi') had died in 1943, and Stokes died in 1946."],
    ["फरवरी 1948 का सुकेत सत्याग्रह, जिसने सुकेत के शासक को नए हिमाचल प्रदेश में शामिल होने के लिए विवश किया, किसके नेतृत्व में हुआ?", ["डॉ. वाई.एस. परमार", "बाबा कांशी राम", "लाला लाजपत राय", "सत्यानंद स्टोक्स"], "1948 के सुकेत सत्याग्रह का नेतृत्व डॉ. वाई.एस. परमार ने किया। बाबा कांशी राम ('पहाड़ी गांधी') का निधन 1943 में और स्टोक्स का 1946 में हो चुका था।"]),
  q(0, "hp-gk", "polity-administration", "H", 0,
    ["Who was the first Governor of Himachal Pradesh after it became a full state in 1971?", ["S. Chakravarti", "Ali Yavar Jung", "Dharma Vira", "B.K. Nehru"], "S. Chakravarti was the first Governor of the State of Himachal Pradesh (from 25 January 1971). The others served as Governors of other states."],
    ["1971 में पूर्ण राज्य बनने के बाद हिमाचल प्रदेश के पहले राज्यपाल कौन थे?", ["एस. चक्रवर्ती", "अली यावर जंग", "धर्म वीर", "बी.के. नेहरू"], "एस. चक्रवर्ती 25 जनवरी 1971 से हिमाचल प्रदेश राज्य के पहले राज्यपाल थे। अन्य व्यक्ति दूसरे राज्यों के राज्यपाल रहे।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["Kinnaur was made a separate district of Himachal Pradesh in the year:", ["1948", "1960", "1966", "1972"], "Kinnaur district was formed on 1 May 1960 from the Chini tehsil of the old Mahasu district."],
    ["किन्नौर को हिमाचल प्रदेश का अलग जिला किस वर्ष बनाया गया?", ["1948", "1960", "1966", "1972"], "किन्नौर जिला 1 मई 1960 को पुराने महासू जिले की चीनी तहसील से बनाया गया।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["In 1972, the districts of Hamirpur and Una were carved out of which district?", ["Kangra", "Mandi", "Bilaspur", "Shimla"], "On 1 September 1972 the old Kangra district was reorganised into three districts: Kangra, Hamirpur and Una."],
    ["1972 में हमीरपुर और ऊना जिले किस जिले से अलग करके बनाए गए?", ["कांगड़ा", "मंडी", "बिलासपुर", "शिमला"], "1 सितंबर 1972 को पुराने कांगड़ा जिले को तीन जिलों — कांगड़ा, हमीरपुर और ऊना — में बाँटा गया।"]),
  q(0, "hp-gk", "districts", "M", 2,
    ["Which is the largest district of Himachal Pradesh by area?", ["Chamba", "Kinnaur", "Lahaul & Spiti", "Kangra"], "Lahaul & Spiti is the largest district by area (about 13,800 km²) but has the smallest population. Hamirpur is the smallest district by area."],
    ["क्षेत्रफल की दृष्टि से हिमाचल प्रदेश का सबसे बड़ा जिला कौन-सा है?", ["चंबा", "किन्नौर", "लाहौल-स्पीति", "कांगड़ा"], "लाहौल-स्पीति क्षेत्रफल में सबसे बड़ा जिला (लगभग 13,800 वर्ग किमी) है, परंतु इसकी जनसंख्या सबसे कम है। क्षेत्रफल में सबसे छोटा जिला हमीरपुर है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 3,
    ["The rivers Chandra and Bhaga meet to form the Chandrabhaga (Chenab) at:", ["Keylong", "Udaipur", "Darcha", "Tandi"], "The Chandra and the Bhaga meet at Tandi in Lahaul, and the combined river is called the Chandrabhaga or Chenab."],
    ["चंद्रा और भागा नदियाँ मिलकर चंद्रभागा (चिनाब) कहाँ बनाती हैं?", ["केलांग", "उदयपुर", "दारचा", "तांदी"], "चंद्रा और भागा लाहौल में तांदी नामक स्थान पर मिलती हैं और संयुक्त नदी चंद्रभागा या चिनाब कहलाती है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 1,
    ["The river Ravi rises in which region of Himachal Pradesh?", ["Beas Kund in Kullu", "Bara Bhangal in Kangra", "Chandratal in Lahaul", "Manimahesh in Chamba"], "The Ravi rises in the Bara Bhangal area of Kangra district and flows through Chamba district before entering Punjab and Pakistan."],
    ["रावी नदी हिमाचल प्रदेश के किस क्षेत्र से निकलती है?", ["कुल्लू का ब्यास कुंड", "कांगड़ा का बड़ा भंगाल", "लाहौल का चंद्रताल", "चंबा का मणिमहेश"], "रावी कांगड़ा जिले के बड़ा भंगाल क्षेत्र से निकलती है और चंबा जिले से बहकर पंजाब और पाकिस्तान जाती है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 0,
    ["The Pabbar river of Shimla district is a tributary of which river?", ["Tons", "Sutlej", "Beas", "Giri"], "The Pabbar flows through Rohru and joins the Tons, which in turn is a tributary of the Yamuna."],
    ["शिमला जिले की पब्बर नदी किस नदी की सहायक नदी है?", ["टौंस", "सतलुज", "ब्यास", "गिरि"], "पब्बर नदी रोहड़ू से बहती हुई टौंस में मिलती है, और टौंस यमुना की सहायक नदी है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["The reservoir formed by the Pong Dam on the Beas is known as:", ["Gobind Sagar", "Maharana Pratap Sagar", "Chamera Lake", "Rana Sagar"], "The Pong Dam on the Beas in Kangra district formed the Maharana Pratap Sagar. Gobind Sagar is the reservoir of the Bhakra Dam on the Sutlej."],
    ["ब्यास नदी पर पौंग बाँध से बने जलाशय को क्या कहते हैं?", ["गोविंद सागर", "महाराणा प्रताप सागर", "चमेरा झील", "राणा सागर"], "कांगड़ा जिले में ब्यास पर बने पौंग बाँध से महाराणा प्रताप सागर बना। गोविंद सागर सतलुज पर भाखड़ा बाँध का जलाशय है।"]),
  q(0, "hp-gk", "geography", "H", 0,
    ["The Sach Pass in the Pir Panjal range connects Chamba with:", ["Pangi valley", "Lahaul valley", "Kullu valley", "Kangra valley"], "The Sach Pass (about 4,400 m) links Chamba town with the remote Pangi valley (Killar)."],
    ["पीर पंजाल श्रेणी का साच दर्रा चंबा को किससे जोड़ता है?", ["पांगी घाटी", "लाहौल घाटी", "कुल्लू घाटी", "कांगड़ा घाटी"], "साच दर्रा (लगभग 4,400 मी) चंबा नगर को दुर्गम पांगी घाटी (किलाड़) से जोड़ता है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["The Atal Tunnel under the Rohtang Pass, opened in October 2020, is about how long?", ["5.4 km", "9.02 km", "11.2 km", "13.5 km"], "The Atal Tunnel is about 9.02 km long and links Manali with Sissu in the Lahaul valley. It is the world's longest highway tunnel above 10,000 feet."],
    ["रोहतांग दर्रे के नीचे अक्टूबर 2020 में खुली अटल सुरंग की लंबाई लगभग कितनी है?", ["5.4 किमी", "9.02 किमी", "11.2 किमी", "13.5 किमी"], "अटल सुरंग लगभग 9.02 किमी लंबी है और मनाली को लाहौल घाटी के सिस्सू से जोड़ती है। यह 10,000 फीट से ऊपर विश्व की सबसे लंबी राजमार्ग सुरंग है।"]),
  q(0, "hp-gk", "geography", "H", 2,
    ["The Great Himalayan National Park in Kullu district was declared a UNESCO World Heritage Site in:", ["2008", "2012", "2014", "2019"], "The Great Himalayan National Park Conservation Area was inscribed as a UNESCO World Heritage Site in 2014."],
    ["कुल्लू जिले के ग्रेट हिमालयन राष्ट्रीय उद्यान को यूनेस्को विश्व धरोहर स्थल कब घोषित किया गया?", ["2008", "2012", "2014", "2019"], "ग्रेट हिमालयन राष्ट्रीय उद्यान संरक्षण क्षेत्र को 2014 में यूनेस्को विश्व धरोहर स्थल घोषित किया गया।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["What is the state bird of Himachal Pradesh?", ["Himalayan Monal", "Western Tragopan (Jujurana)", "Cheer Pheasant", "Peacock"], "The Western Tragopan, locally called Jujurana ('king of birds'), is the state bird. The Himalayan Monal is the state bird of Uttarakhand."],
    ["हिमाचल प्रदेश का राज्य पक्षी कौन-सा है?", ["हिमालयन मोनाल", "पश्चिमी ट्रैगोपैन (जुजुराना)", "चीड़ फेज़ेंट", "मोर"], "पश्चिमी ट्रैगोपैन, जिसे स्थानीय रूप से जुजुराना ('पक्षियों का राजा') कहते हैं, राज्य पक्षी है। हिमालयन मोनाल उत्तराखंड का राज्य पक्षी है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["Which was the first product from Himachal Pradesh to receive a Geographical Indication (GI) tag?", ["Kullu Shawl", "Kangra Tea", "Chamba Rumal", "Kinnauri Shawl"], "The Kullu Shawl got the GI tag in 2004, the first for Himachal. Kangra Tea (2005), Chamba Rumal (2008) and Kinnauri Shawl (2010) followed."],
    ["भौगोलिक संकेतक (GI) टैग पाने वाला हिमाचल प्रदेश का पहला उत्पाद कौन-सा था?", ["कुल्लू शॉल", "कांगड़ा चाय", "चंबा रूमाल", "किन्नौरी शॉल"], "कुल्लू शॉल को 2004 में GI टैग मिला, जो हिमाचल का पहला था। इसके बाद कांगड़ा चाय (2005), चंबा रूमाल (2008) और किन्नौरी शॉल (2010) को मिला।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Minjar Fair, in which silk tassels resembling maize flowers are offered, is celebrated in:", ["Kullu", "Mandi", "Chamba", "Sirmaur"], "The Minjar Fair is held in Chamba town in July–August. 'Minjar' tassels are offered to the deity and finally immersed in the Ravi."],
    ["मिंजर मेला, जिसमें मक्की के फूल जैसे रेशमी गुच्छे चढ़ाए जाते हैं, कहाँ मनाया जाता है?", ["कुल्लू", "मंडी", "चंबा", "सिरमौर"], "मिंजर मेला जुलाई–अगस्त में चंबा नगर में होता है। 'मिंजर' के गुच्छे देवता को चढ़ाकर अंत में रावी में प्रवाहित किए जाते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The Ladarcha Fair, historically a trade fair between Spiti, Ladakh and Kinnaur traders, is held at:", ["Keylong", "Kaza", "Reckong Peo", "Rampur"], "The Ladarcha Fair is held at Kaza in Spiti in July–August. It began as a barter fair of traders from Spiti, Ladakh, Kinnaur and Rampur."],
    ["लदारचा मेला, जो ऐतिहासिक रूप से स्पीति, लद्दाख और किन्नौर के व्यापारियों का व्यापार मेला था, कहाँ लगता है?", ["केलांग", "काज़ा", "रिकांगपिओ", "रामपुर"], "लदारचा मेला जुलाई–अगस्त में स्पीति के काज़ा में लगता है। यह स्पीति, लद्दाख, किन्नौर और रामपुर के व्यापारियों के वस्तु-विनिमय मेले के रूप में शुरू हुआ।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Kullu Nati entered the Guinness Book of World Records as the largest folk dance in the year:", ["2012", "2014", "2016", "2019"], "In October 2015 about 10,000 women performed the Nati during Kullu Dussehra; the record was recognised by Guinness in 2016."],
    ["कुल्लवी नाटी को सबसे बड़े लोकनृत्य के रूप में गिनीज़ बुक ऑफ वर्ल्ड रिकॉर्ड्स में किस वर्ष स्थान मिला?", ["2012", "2014", "2016", "2019"], "अक्टूबर 2015 में कुल्लू दशहरे के दौरान लगभग 10,000 महिलाओं ने नाटी की; गिनीज़ ने इस रिकॉर्ड को 2016 में मान्यता दी।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The cave temple of Baba Balak Nath at Deotsidh is located in which district?", ["Hamirpur", "Una", "Bilaspur", "Kangra"], "The Baba Balak Nath temple at Deotsidh (Shahtalai area) lies in Hamirpur district, close to the Bilaspur border."],
    ["देवतसिद्ध में बाबा बालक नाथ का गुफा मंदिर किस जिले में है?", ["हमीरपुर", "ऊना", "बिलासपुर", "कांगड़ा"], "देवतसिद्ध (शाहतलाई क्षेत्र) का बाबा बालक नाथ मंदिर बिलासपुर सीमा के पास हमीरपुर जिले में है।"]),
  q(0, "hp-gk", "personalities", "H", 1,
    ["Major Somnath Sharma, the first recipient of the Param Vir Chakra (1947), was born in which district of Himachal Pradesh?", ["Mandi", "Kangra", "Hamirpur", "Solan"], "Major Somnath Sharma was born at Dadh in Kangra district. He was awarded the first Param Vir Chakra posthumously for the battle of Badgam, Kashmir, in November 1947."],
    ["पहले परमवीर चक्र (1947) विजेता मेजर सोमनाथ शर्मा का जन्म हिमाचल प्रदेश के किस जिले में हुआ था?", ["मंडी", "कांगड़ा", "हमीरपुर", "सोलन"], "मेजर सोमनाथ शर्मा का जन्म कांगड़ा जिले के डाढ़ में हुआ। नवंबर 1947 में कश्मीर के बडगाम युद्ध के लिए उन्हें मरणोपरांत पहला परमवीर चक्र मिला।"]),
  q(0, "hp-gk", "polity-administration", "M", 1,
    ["How many members does Himachal Pradesh send to the Rajya Sabha?", ["2", "3", "4", "5"], "Himachal Pradesh has 3 seats in the Rajya Sabha, 4 in the Lok Sabha and 68 in the Vidhan Sabha."],
    ["हिमाचल प्रदेश राज्यसभा में कितने सदस्य भेजता है?", ["2", "3", "4", "5"], "हिमाचल प्रदेश की राज्यसभा में 3, लोकसभा में 4 और विधानसभा में 68 सीटें हैं।"]),
  q(0, "hp-gk", "polity-administration", "H", 0,
    ["The Police Training College of the Himachal Pradesh Police, where constables receive basic training, is located at:", ["Daroh (Kangra)", "Junga (Shimla)", "Bangarh (Una)", "Dharampur (Mandi)"], "The HP Police Training College is at Daroh in Kangra district. Recruit constables undergo their basic training there."],
    ["हिमाचल प्रदेश पुलिस का पुलिस प्रशिक्षण महाविद्यालय, जहाँ कांस्टेबलों का बुनियादी प्रशिक्षण होता है, कहाँ स्थित है?", ["डरोह (कांगड़ा)", "जुन्गा (शिमला)", "बनगढ़ (ऊना)", "धर्मपुर (मंडी)"], "हिमाचल पुलिस प्रशिक्षण महाविद्यालय कांगड़ा जिले के डरोह में है। भर्ती कांस्टेबलों का बुनियादी प्रशिक्षण यहीं होता है।"]),

  // ───────── Section 1: General Knowledge (25) ─────────
  q(1, "general-studies", "indian-history", "H", 0,
    ["The Fourth Buddhist Council, held under the patronage of Kanishka, took place at:", ["Kundalvana (Kashmir)", "Rajagriha", "Vaishali", "Pataliputra"], "The Fourth Buddhist Council was held at Kundalvana in Kashmir under Kanishka, presided over by Vasumitra. Rajagriha, Vaishali and Pataliputra hosted the first three councils."],
    ["कनिष्क के संरक्षण में चौथी बौद्ध संगीति कहाँ हुई?", ["कुंडलवन (कश्मीर)", "राजगृह", "वैशाली", "पाटलिपुत्र"], "चौथी बौद्ध संगीति कनिष्क के समय कश्मीर के कुंडलवन में वसुमित्र की अध्यक्षता में हुई। राजगृह, वैशाली और पाटलिपुत्र में पहली तीन संगीतियाँ हुई थीं।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["The Khalsa Panth was founded in 1699 at Anandpur Sahib by:", ["Guru Gobind Singh", "Guru Tegh Bahadur", "Guru Arjan Dev", "Guru Har Rai"], "Guru Gobind Singh, the tenth Sikh Guru, founded the Khalsa on Baisakhi day in 1699 at Anandpur Sahib."],
    ["1699 में आनंदपुर साहिब में खालसा पंथ की स्थापना किसने की?", ["गुरु गोबिंद सिंह", "गुरु तेग बहादुर", "गुरु अर्जन देव", "गुरु हर राय"], "दसवें सिख गुरु, गुरु गोबिंद सिंह ने 1699 में बैसाखी के दिन आनंदपुर साहिब में खालसा की स्थापना की।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["The Permanent Settlement of land revenue in Bengal (1793) was introduced by:", ["Warren Hastings", "Lord Cornwallis", "Lord Wellesley", "Lord Dalhousie"], "Lord Cornwallis introduced the Permanent Settlement in 1793, fixing the land revenue payable by zamindars permanently."],
    ["बंगाल में भू-राजस्व का स्थायी बंदोबस्त (1793) किसने लागू किया?", ["वॉरेन हेस्टिंग्स", "लॉर्ड कॉर्नवॉलिस", "लॉर्ड वेलेज़ली", "लॉर्ड डलहौज़ी"], "लॉर्ड कॉर्नवॉलिस ने 1793 में स्थायी बंदोबस्त लागू किया, जिसमें ज़मींदारों द्वारा देय भू-राजस्व स्थायी रूप से तय कर दिया गया।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["The Simon Commission (1928) was boycotted all over India mainly because:", ["It proposed the partition of Bengal", "It was headed by the Viceroy", "It had no Indian member", "It abolished the provinces"], "The seven-member Simon Commission, sent to review the working of the 1919 reforms, had no Indian member. It was greeted with the slogan 'Simon Go Back'."],
    ["साइमन कमीशन (1928) का पूरे भारत में बहिष्कार मुख्यतः क्यों किया गया?", ["उसने बंगाल विभाजन का प्रस्ताव दिया", "उसके अध्यक्ष वायसराय थे", "उसमें कोई भारतीय सदस्य नहीं था", "उसने प्रांतों को समाप्त कर दिया"], "1919 के सुधारों की समीक्षा के लिए भेजे गए सात सदस्यीय साइमन कमीशन में एक भी भारतीय सदस्य नहीं था। इसका स्वागत 'साइमन गो बैक' के नारे से हुआ।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["The first Indian National Army (Azad Hind Fauj) was formed in 1942 by:", ["Subhas Chandra Bose", "Rash Behari Bose", "Captain Mohan Singh", "Shah Nawaz Khan"], "Captain Mohan Singh formed the first INA in 1942 with Indian prisoners of war in Malaya. Subhas Chandra Bose revived and led it from 1943."],
    ["पहली आज़ाद हिंद फ़ौज (INA) का गठन 1942 में किसने किया?", ["सुभाष चंद्र बोस", "रासबिहारी बोस", "कैप्टन मोहन सिंह", "शाहनवाज़ खान"], "कैप्टन मोहन सिंह ने 1942 में मलाया में भारतीय युद्धबंदियों को लेकर पहली INA बनाई। 1943 से सुभाष चंद्र बोस ने इसे पुनर्गठित कर नेतृत्व किया।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["The provisions relating to disqualification on the ground of defection (anti-defection law) are in which Schedule of the Constitution?", ["Seventh Schedule", "Eighth Schedule", "Ninth Schedule", "Tenth Schedule"], "The anti-defection law was added as the Tenth Schedule by the 52nd Amendment Act, 1985."],
    ["दल-बदल के आधार पर अयोग्यता (दल-बदल विरोधी कानून) के प्रावधान संविधान की किस अनुसूची में हैं?", ["सातवीं अनुसूची", "आठवीं अनुसूची", "नौवीं अनुसूची", "दसवीं अनुसूची"], "दल-बदल विरोधी कानून 52वें संशोधन अधिनियम, 1985 द्वारा दसवीं अनुसूची के रूप में जोड़ा गया।"]),
  q(1, "general-studies", "indian-polity", "H", 1,
    ["After it ceased to be a Fundamental Right, the right to property is now a constitutional (legal) right under:", ["Article 19(1)(f)", "Article 300A", "Article 31C", "Article 265"], "The 44th Amendment (1978) removed the right to property from Part III and placed it in Article 300A: no person shall be deprived of property save by authority of law."],
    ["मौलिक अधिकार न रहने के बाद संपत्ति का अधिकार अब किस अनुच्छेद के तहत संवैधानिक (विधिक) अधिकार है?", ["अनुच्छेद 19(1)(च)", "अनुच्छेद 300क", "अनुच्छेद 31ग", "अनुच्छेद 265"], "44वें संशोधन (1978) ने संपत्ति के अधिकार को भाग III से हटाकर अनुच्छेद 300क में रखा: किसी व्यक्ति को विधि के प्राधिकार के बिना संपत्ति से वंचित नहीं किया जाएगा।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["Who administers the oath of office to the President of India?", ["The Vice-President", "The Speaker of the Lok Sabha", "The Chief Justice of India", "The Prime Minister"], "The oath of the President is administered by the Chief Justice of India, or in his absence by the senior-most judge of the Supreme Court (Article 60)."],
    ["भारत के राष्ट्रपति को पद की शपथ कौन दिलाता है?", ["उपराष्ट्रपति", "लोकसभा अध्यक्ष", "भारत के मुख्य न्यायाधीश", "प्रधानमंत्री"], "राष्ट्रपति को शपथ भारत के मुख्य न्यायाधीश, और उनकी अनुपस्थिति में सर्वोच्च न्यायालय के वरिष्ठतम न्यायाधीश दिलाते हैं (अनुच्छेद 60)।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["The idea of the Directive Principles of State Policy in the Indian Constitution was borrowed from the Constitution of:", ["Ireland", "USA", "Canada", "Australia"], "The Directive Principles (Part IV) were inspired by the Irish Constitution. Fundamental Rights were inspired by the US Constitution."],
    ["भारतीय संविधान में राज्य के नीति-निदेशक तत्वों का विचार किस देश के संविधान से लिया गया?", ["आयरलैंड", "अमेरिका", "कनाडा", "ऑस्ट्रेलिया"], "नीति-निदेशक तत्व (भाग IV) आयरलैंड के संविधान से प्रेरित हैं। मौलिक अधिकार अमेरिका के संविधान से प्रेरित हैं।"]),
  q(1, "general-studies", "indian-polity", "H", 0,
    ["The Bharatiya Nyaya Sanhita (BNS), 2023, which came into force on 1 July 2024, replaced the:", ["Indian Penal Code, 1860", "Code of Criminal Procedure, 1973", "Indian Evidence Act, 1872", "Police Act, 1861"], "From 1 July 2024 the BNS replaced the IPC, the Bharatiya Nagarik Suraksha Sanhita (BNSS) replaced the CrPC, and the Bharatiya Sakshya Adhiniyam (BSA) replaced the Indian Evidence Act."],
    ["1 जुलाई 2024 से लागू भारतीय न्याय संहिता (BNS), 2023 ने किसका स्थान लिया?", ["भारतीय दंड संहिता, 1860", "दंड प्रक्रिया संहिता, 1973", "भारतीय साक्ष्य अधिनियम, 1872", "पुलिस अधिनियम, 1861"], "1 जुलाई 2024 से BNS ने IPC का, भारतीय नागरिक सुरक्षा संहिता (BNSS) ने CrPC का और भारतीय साक्ष्य अधिनियम (BSA) ने इंडियन एविडेंस एक्ट का स्थान लिया।"]),
  q(1, "general-studies", "indian-polity", "H", 1,
    ["Under Article 22 of the Constitution, a person who is arrested must be produced before the nearest magistrate within:", ["12 hours", "24 hours", "48 hours", "72 hours"], "Article 22(2) requires an arrested person to be produced before the nearest magistrate within 24 hours of arrest, excluding the time of the journey."],
    ["संविधान के अनुच्छेद 22 के अनुसार गिरफ़्तार व्यक्ति को निकटतम मजिस्ट्रेट के सामने कितने समय के भीतर पेश करना आवश्यक है?", ["12 घंटे", "24 घंटे", "48 घंटे", "72 घंटे"], "अनुच्छेद 22(2) के अनुसार गिरफ़्तार व्यक्ति को यात्रा का समय छोड़कर गिरफ़्तारी के 24 घंटे के भीतर निकटतम मजिस्ट्रेट के सामने पेश करना होता है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Which mountain pass connects Sikkim with Tibet and was reopened for border trade in 2006?", ["Shipki La", "Nathu La", "Zoji La", "Bomdi La"], "Nathu La in Sikkim connects India with Tibet (China); border trade through it resumed in 2006. Zoji La is in Ladakh and Bomdi La in Arunachal Pradesh."],
    ["कौन-सा दर्रा सिक्किम को तिब्बत से जोड़ता है और 2006 में सीमा व्यापार के लिए फिर खोला गया?", ["शिपकी ला", "नाथू ला", "ज़ोजी ला", "बोमडी ला"], "सिक्किम का नाथू ला भारत को तिब्बत (चीन) से जोड़ता है; 2006 में इससे सीमा व्यापार फिर शुरू हुआ। ज़ोजी ला लद्दाख में और बोमडी ला अरुणाचल प्रदेश में है।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["Which state is the largest producer of coffee in India?", ["Kerala", "Tamil Nadu", "Karnataka", "Assam"], "Karnataka produces about 70% of India's coffee, mainly in Kodagu (Coorg), Chikkamagaluru and Hassan."],
    ["भारत में कॉफी का सबसे बड़ा उत्पादक राज्य कौन-सा है?", ["केरल", "तमिलनाडु", "कर्नाटक", "असम"], "कर्नाटक भारत की लगभग 70% कॉफी पैदा करता है, मुख्यतः कोडागु (कुर्ग), चिकमगलूर और हासन में।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["The Duncan Passage separates:", ["India and Sri Lanka", "North and Middle Andaman", "Andaman and Nicobar groups", "South Andaman and Little Andaman"], "The Duncan Passage lies between South Andaman and Little Andaman. The Ten Degree Channel separates the Andaman group from the Nicobar group."],
    ["डंकन पैसेज किन्हें अलग करता है?", ["भारत और श्रीलंका", "उत्तरी और मध्य अंडमान", "अंडमान और निकोबार समूह", "दक्षिणी अंडमान और लिटिल अंडमान"], "डंकन पैसेज दक्षिणी अंडमान और लिटिल अंडमान के बीच है। टेन डिग्री चैनल अंडमान समूह को निकोबार समूह से अलग करता है।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Anamudi, the highest peak of peninsular India, is located in:", ["Kerala", "Tamil Nadu", "Karnataka", "Maharashtra"], "Anamudi (about 2,695 m) in the Anaimalai hills of Kerala is the highest peak in India south of the Himalayas."],
    ["प्रायद्वीपीय भारत की सबसे ऊँची चोटी अनामुडी कहाँ स्थित है?", ["केरल", "तमिलनाडु", "कर्नाटक", "महाराष्ट्र"], "केरल की अन्नामलाई पहाड़ियों में स्थित अनामुडी (लगभग 2,695 मी) हिमालय के दक्षिण में भारत की सबसे ऊँची चोटी है।"]),
  q(1, "general-studies", "indian-economy", "M", 3,
    ["Which of the following is NOT a function of the Reserve Bank of India?", ["Issuing currency notes", "Acting as banker to the Government", "Controlling credit in the economy", "Accepting savings deposits from the general public"], "The RBI issues currency, is banker to the Government and to banks, and controls credit. It does not accept deposits from the general public; commercial banks do."],
    ["निम्नलिखित में से कौन-सा भारतीय रिज़र्व बैंक का कार्य नहीं है?", ["करेंसी नोट जारी करना", "सरकार का बैंकर होना", "अर्थव्यवस्था में साख नियंत्रित करना", "आम जनता से बचत जमा स्वीकार करना"], "RBI मुद्रा जारी करता है, सरकार और बैंकों का बैंकर है और साख नियंत्रित करता है। यह आम जनता से जमा स्वीकार नहीं करता; यह काम वाणिज्यिक बैंक करते हैं।"]),
  q(1, "general-studies", "indian-economy", "M", 1,
    ["The 'Make in India' initiative to promote manufacturing was launched in the year:", ["2012", "2014", "2016", "2018"], "Make in India was launched on 25 September 2014 to encourage companies to manufacture in India."],
    ["विनिर्माण को बढ़ावा देने वाली 'मेक इन इंडिया' पहल किस वर्ष शुरू हुई?", ["2012", "2014", "2016", "2018"], "मेक इन इंडिया 25 सितंबर 2014 को कंपनियों को भारत में विनिर्माण के लिए प्रोत्साहित करने हेतु शुरू की गई।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["Myopia (short-sightedness) is corrected by using a:", ["Convex lens", "Concave lens", "Cylindrical lens", "Bifocal lens"], "In myopia the image forms in front of the retina. A concave (diverging) lens moves the image back onto the retina."],
    ["निकट-दृष्टि दोष (मायोपिया) को किस लेंस से ठीक किया जाता है?", ["उत्तल लेंस", "अवतल लेंस", "बेलनाकार लेंस", "द्विफोकसी लेंस"], "निकट-दृष्टि दोष में प्रतिबिंब रेटिना के आगे बनता है। अवतल (अपसारी) लेंस प्रतिबिंब को पीछे खिसकाकर रेटिना पर लाता है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["The 'lead' of a pencil is actually made of:", ["Lead", "Charcoal", "Graphite", "Silicon"], "Pencil 'lead' is a mixture of graphite (a form of carbon) and clay. It contains no lead metal."],
    ["पेंसिल का 'लेड' वास्तव में किससे बना होता है?", ["सीसा (लेड)", "चारकोल", "ग्रेफाइट", "सिलिकॉन"], "पेंसिल का 'लेड' ग्रेफाइट (कार्बन का एक रूप) और मिट्टी का मिश्रण है। इसमें सीसा धातु नहीं होती।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Which of the following diseases is caused by a bacterium?", ["Typhoid", "Malaria", "Dengue", "Polio"], "Typhoid is caused by the bacterium Salmonella typhi. Malaria is caused by a protozoan, while dengue and polio are viral."],
    ["निम्नलिखित में से कौन-सा रोग जीवाणु से होता है?", ["टाइफाइड", "मलेरिया", "डेंगू", "पोलियो"], "टाइफाइड साल्मोनेला टाइफी जीवाणु से होता है। मलेरिया प्रोटोज़ोआ से, जबकि डेंगू और पोलियो वायरस से होते हैं।"]),
  q(1, "general-studies", "general-science", "H", 3,
    ["If an object is placed at the principal focus of a convex lens, the image is formed:", ["At the focus on the other side", "At 2F on the other side", "On the same side as the object", "At infinity"], "Rays from an object at the focus become parallel after refraction through a convex lens, so the image forms at infinity (highly enlarged)."],
    ["यदि किसी वस्तु को उत्तल लेंस के मुख्य फोकस पर रखा जाए, तो प्रतिबिंब कहाँ बनता है?", ["दूसरी ओर फोकस पर", "दूसरी ओर 2F पर", "वस्तु की ओर ही", "अनंत पर"], "फोकस पर रखी वस्तु से आने वाली किरणें उत्तल लेंस से अपवर्तन के बाद समांतर हो जाती हैं, इसलिए प्रतिबिंब अनंत पर (अत्यधिक बड़ा) बनता है।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["Which gland is known as the 'master gland' of the human body?", ["Thyroid", "Pituitary", "Adrenal", "Pancreas"], "The pituitary gland controls the working of several other endocrine glands, so it is called the master gland."],
    ["मानव शरीर की कौन-सी ग्रंथि 'मास्टर ग्रंथि' कहलाती है?", ["थायरॉइड", "पीयूष (पिट्यूटरी)", "अधिवृक्क (एड्रिनल)", "अग्न्याशय"], "पीयूष (पिट्यूटरी) ग्रंथि कई अन्य अंतःस्रावी ग्रंथियों के कार्य को नियंत्रित करती है, इसलिए इसे मास्टर ग्रंथि कहते हैं।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Which of the following substances has the highest specific heat capacity?", ["Water", "Iron", "Copper", "Mercury"], "Water has a very high specific heat (about 4,186 J/kg·K), which is why it heats up and cools down slowly. Metals have much lower values."],
    ["निम्नलिखित में से किस पदार्थ की विशिष्ट ऊष्मा धारिता सबसे अधिक है?", ["जल", "लोहा", "तांबा", "पारा"], "जल की विशिष्ट ऊष्मा बहुत अधिक (लगभग 4,186 J/kg·K) है, इसलिए यह धीरे गर्म और धीरे ठंडा होता है। धातुओं का मान बहुत कम होता है।"]),
  q(1, "computer", "security", "H", 2,
    ["Which section of the Information Technology Act, 2000 deals with punishment for identity theft (fraudulent use of another person's password or electronic signature)?", ["Section 43", "Section 65", "Section 66C", "Section 67"], "Section 66C punishes identity theft. Section 65 covers tampering with source code, Section 67 obscene material in electronic form, and Section 43 compensation for damage to computers."],
    ["सूचना प्रौद्योगिकी अधिनियम, 2000 की कौन-सी धारा पहचान की चोरी (किसी अन्य के पासवर्ड या इलेक्ट्रॉनिक हस्ताक्षर का कपटपूर्ण उपयोग) के दंड से संबंधित है?", ["धारा 43", "धारा 65", "धारा 66C", "धारा 67"], "धारा 66C पहचान की चोरी को दंडित करती है। धारा 65 सोर्स कोड से छेड़छाड़, धारा 67 इलेक्ट्रॉनिक रूप में अश्लील सामग्री और धारा 43 कंप्यूटर को क्षति के मुआवज़े से संबंधित है।"]),
  q(1, "computer", "fundamentals", "M", 0,
    ["What is the full form of PDF?", ["Portable Document Format", "Printed Document File", "Public Data Format", "Personal Document File"], "PDF stands for Portable Document Format, developed by Adobe to show documents the same way on any device."],
    ["PDF का पूर्ण रूप क्या है?", ["Portable Document Format", "Printed Document File", "Public Data Format", "Personal Document File"], "PDF का पूर्ण रूप Portable Document Format है, जिसे Adobe ने विकसित किया ताकि दस्तावेज़ हर डिवाइस पर एक जैसा दिखे।"]),

  // ───────── Section 2: Reasoning (20) ─────────
  q(2, "reasoning", "series", "M", 2,
    ["Find the next number: 2, 6, 12, 20, 30, ?", ["40", "41", "42", "44"], "The terms are 1×2, 2×3, 3×4, 4×5, 5×6. The next is 6×7 = 42."],
    ["अगली संख्या ज्ञात कीजिए: 2, 6, 12, 20, 30, ?", ["40", "41", "42", "44"], "पद 1×2, 2×3, 3×4, 4×5, 5×6 हैं। अगला 6×7 = 42 है।"], "6*7"),
  q(2, "reasoning", "series", "H", 3,
    ["Find the next number: 5, 11, 24, 51, 106, ?", ["211", "212", "213", "217"], "Each term = previous × 2 + 1, + 2, + 3, + 4, …: 5×2+1 = 11, 11×2+2 = 24, 24×2+3 = 51, 51×2+4 = 106, so 106×2+5 = 217."],
    ["अगली संख्या ज्ञात कीजिए: 5, 11, 24, 51, 106, ?", ["211", "212", "213", "217"], "प्रत्येक पद = पिछला × 2 + 1, + 2, + 3, + 4, …: 5×2+1 = 11, 11×2+2 = 24, 24×2+3 = 51, 51×2+4 = 106, अतः 106×2+5 = 217।"], "106*2+5"),
  q(2, "reasoning", "series", "H", 1,
    ["Find the next letter: B, E, J, Q, ?", ["Y", "Z", "X", "W"], "Letter positions are 2, 5, 10, 17, i.e. 1²+1, 2²+1, 3²+1, 4²+1. The next is 5²+1 = 26, which is Z."],
    ["अगला अक्षर ज्ञात कीजिए: B, E, J, Q, ?", ["Y", "Z", "X", "W"], "अक्षरों के क्रमांक 2, 5, 10, 17 हैं, यानी 1²+1, 2²+1, 3²+1, 4²+1। अगला 5²+1 = 26 यानी Z है।"]),
  q(2, "reasoning", "coding-decoding", "M", 0,
    ["If POLICE is written as QPMJDF in a code, how will THANA be written in that code?", ["UIBOB", "UIBNB", "SGZMZ", "UHBOB"], "Each letter moves one step forward: P→Q, O→P, L→M, I→J, C→D, E→F. So T→U, H→I, A→B, N→O, A→B gives UIBOB."],
    ["यदि किसी कोड में POLICE को QPMJDF लिखा जाता है, तो THANA को कैसे लिखा जाएगा?", ["UIBOB", "UIBNB", "SGZMZ", "UHBOB"], "प्रत्येक अक्षर एक स्थान आगे बढ़ता है: P→Q, O→P, L→M, I→J, C→D, E→F। अतः T→U, H→I, A→B, N→O, A→B से UIBOB बनता है।"]),
  q(2, "reasoning", "coding-decoding", "H", 2,
    ["In a code, GUARD is written as HTBQE (letters shift +1, −1, +1, −1, +1 in turn). How will CRIME be written?", ["DSJNF", "BQHLD", "DQJLF", "DQJNF"], "Apply +1, −1, +1, −1, +1: C→D, R→Q, I→J, M→L, E→F, giving DQJLF."],
    ["एक कोड में GUARD को HTBQE लिखा जाता है (अक्षर बारी-बारी से +1, −1, +1, −1, +1 बदलते हैं)। CRIME को कैसे लिखा जाएगा?", ["DSJNF", "BQHLD", "DQJLF", "DQJNF"], "+1, −1, +1, −1, +1 लगाने पर: C→D, R→Q, I→J, M→L, E→F, अतः DQJLF।"]),
  q(2, "reasoning", "blood-relations", "M", 1,
    ["Introducing a man, a woman says, 'His wife is the only daughter of my father.' How is the man related to the woman?", ["Brother", "Husband", "Father-in-law", "Brother-in-law"], "The only daughter of the woman's father is the woman herself. So the man's wife is the woman, and he is her husband."],
    ["एक पुरुष का परिचय देते हुए एक महिला कहती है, 'इसकी पत्नी मेरे पिता की इकलौती पुत्री है।' वह पुरुष महिला का क्या लगता है?", ["भाई", "पति", "ससुर", "जीजा/देवर"], "महिला के पिता की इकलौती पुत्री स्वयं वह महिला है। अतः पुरुष की पत्नी वही महिला है और पुरुष उसका पति है।"]),
  q(2, "reasoning", "blood-relations", "H", 2,
    ["P is the brother of Q. R is the mother of P. S is the father of R. T is the mother of S. How is Q related to T?", ["Grandson", "Granddaughter", "Great-grandchild", "Daughter"], "T → S (son) → R (daughter) → Q (child). Q is three generations below T, so Q is T's great-grandchild. Q's gender is not given, so 'grandson' or 'granddaughter' cannot be chosen."],
    ["P, Q का भाई है। R, P की माता है। S, R का पिता है। T, S की माता है। Q का T से क्या संबंध है?", ["पोता", "पोती", "परपोता/परपोती (प्रपौत्र संतान)", "पुत्री"], "T → S (पुत्र) → R (पुत्री) → Q (संतान)। Q, T से तीन पीढ़ी नीचे है, अतः Q, T की प्रपौत्र संतान है। Q का लिंग नहीं दिया गया, इसलिए 'पोता' या 'पोती' नहीं चुना जा सकता।"]),
  q(2, "reasoning", "direction-sense", "H", 1,
    ["A police patrol starts from the police station, goes 12 km north, then turns right and goes 5 km. How far and in which direction is it now from the police station?", ["17 km, North-East", "13 km, North-East", "13 km, North-West", "7 km, East"], "12 km north and then 5 km east form a right angle. Distance = √(12² + 5²) = √169 = 13 km, towards the north-east of the station."],
    ["एक पुलिस गश्ती दल थाने से चलकर 12 किमी उत्तर जाता है, फिर दाएँ मुड़कर 5 किमी जाता है। अब वह थाने से कितनी दूरी पर और किस दिशा में है?", ["17 किमी, उत्तर-पूर्व", "13 किमी, उत्तर-पूर्व", "13 किमी, उत्तर-पश्चिम", "7 किमी, पूर्व"], "12 किमी उत्तर और फिर 5 किमी पूर्व समकोण बनाते हैं। दूरी = √(12² + 5²) = √169 = 13 किमी, थाने के उत्तर-पूर्व में।"]),
  q(2, "reasoning", "direction-sense", "M", 2,
    ["A man is facing north. He turns right, then right again, and then left. Which direction is he facing now?", ["North", "South", "East", "West"], "North → right → East → right → South → left → East."],
    ["एक व्यक्ति उत्तर की ओर मुँह करके खड़ा है। वह दाएँ मुड़ता है, फिर दोबारा दाएँ, और फिर बाएँ। अब उसका मुँह किस दिशा में है?", ["उत्तर", "दक्षिण", "पूर्व", "पश्चिम"], "उत्तर → दाएँ → पूर्व → दाएँ → दक्षिण → बाएँ → पूर्व।"]),
  q(2, "reasoning", "ranking", "H", 1,
    ["In a row, A is 17th from the left and B is 23rd from the right. When they interchange their positions, A becomes 30th from the left. How many persons are there in the row?", ["51", "52", "53", "46"], "After the interchange A stands at B's old place, which is 30th from the left and 23rd from the right. Total = 30 + 23 − 1 = 52."],
    ["एक पंक्ति में A बाएँ से 17वें और B दाएँ से 23वें स्थान पर है। स्थान बदलने पर A बाएँ से 30वें स्थान पर आ जाता है। पंक्ति में कुल कितने व्यक्ति हैं?", ["51", "52", "53", "46"], "स्थान बदलने के बाद A, B के पुराने स्थान पर है, जो बाएँ से 30वाँ और दाएँ से 23वाँ है। कुल = 30 + 23 − 1 = 52।"], "30+23-1"),
  q(2, "reasoning", "ranking", "M", 0,
    ["Mohan is 7th from the top and 26th from the bottom in his class. How many students are there in the class?", ["32", "33", "31", "34"], "Total = position from top + position from bottom − 1 = 7 + 26 − 1 = 32."],
    ["मोहन अपनी कक्षा में ऊपर से 7वें और नीचे से 26वें स्थान पर है। कक्षा में कितने छात्र हैं?", ["32", "33", "31", "34"], "कुल = ऊपर से स्थान + नीचे से स्थान − 1 = 7 + 26 − 1 = 32।"], "7+26-1"),
  q(2, "reasoning", "analogy", "M", 2,
    ["4 : 17 :: 6 : ?", ["35", "36", "37", "38"], "The rule is n² + 1: 4² + 1 = 17, so 6² + 1 = 37."],
    ["4 : 17 :: 6 : ?", ["35", "36", "37", "38"], "नियम n² + 1 है: 4² + 1 = 17, अतः 6² + 1 = 37।"], "6*6+1"),
  q(2, "reasoning", "analogy", "H", 0,
    ["PRQ : TVU :: JLK : ?", ["NPO", "NOP", "MON", "OPN"], "Each letter moves 4 steps forward: P→T, R→V, Q→U. So J→N, L→P, K→O gives NPO."],
    ["PRQ : TVU :: JLK : ?", ["NPO", "NOP", "MON", "OPN"], "प्रत्येक अक्षर 4 स्थान आगे बढ़ता है: P→T, R→V, Q→U। अतः J→N, L→P, K→O से NPO।"]),
  q(2, "reasoning", "odd-one-out", "M", 2,
    ["Find the odd one out: 13, 17, 21, 29", ["13", "17", "21", "29"], "13, 17 and 29 are prime numbers. 21 = 3 × 7 is not prime."],
    ["विषम संख्या चुनिए: 13, 17, 21, 29", ["13", "17", "21", "29"], "13, 17 और 29 अभाज्य संख्याएँ हैं। 21 = 3 × 7 अभाज्य नहीं है।"], "21"),
  q(2, "reasoning", "syllogism", "M", 0,
    ["Statements: All constables are officers. No officer is a thief. Conclusions: I. No constable is a thief. II. Some thieves are constables.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "All constables lie inside 'officers', and officers and thieves do not overlap, so no constable is a thief (I follows). II contradicts I, so it does not follow."],
    ["कथन: सभी कांस्टेबल अधिकारी हैं। कोई अधिकारी चोर नहीं है। निष्कर्ष: I. कोई कांस्टेबल चोर नहीं है। II. कुछ चोर कांस्टेबल हैं।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "सभी कांस्टेबल 'अधिकारी' के भीतर हैं और अधिकारी तथा चोर का कोई मेल नहीं है, अतः कोई कांस्टेबल चोर नहीं है (I सही)। II, I का विरोधी है, इसलिए अनुसरण नहीं करता।"]),
  q(2, "reasoning", "syllogism", "H", 0,
    ["Statements: Some guns are rifles. No rifle is a pistol. Conclusions: I. Some guns are not pistols. II. Some pistols are guns.", ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"], "The guns that are rifles can never be pistols, so some guns are definitely not pistols (I follows). Whether any pistol is a gun is not known, so II does not follow."],
    ["कथन: कुछ बंदूकें राइफल हैं। कोई राइफल पिस्तौल नहीं है। निष्कर्ष: I. कुछ बंदूकें पिस्तौल नहीं हैं। II. कुछ पिस्तौल बंदूकें हैं।", ["केवल निष्कर्ष I अनुसरण करता है", "केवल निष्कर्ष II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "जो बंदूकें राइफल हैं वे कभी पिस्तौल नहीं हो सकतीं, अतः कुछ बंदूकें निश्चित रूप से पिस्तौल नहीं हैं (I सही)। कोई पिस्तौल बंदूक है या नहीं, यह ज्ञात नहीं, अतः II अनुसरण नहीं करता।"]),
  q(2, "reasoning", "clock-calendar", "H", 3,
    ["15 August 2023 was a Tuesday. What day of the week was 15 August 2024?", ["Wednesday", "Tuesday", "Friday", "Thursday"], "The period from 15 Aug 2023 to 15 Aug 2024 contains 29 February 2024, so it has 366 days = 52 weeks + 2 days. Tuesday + 2 = Thursday."],
    ["15 अगस्त 2023 को मंगलवार था। 15 अगस्त 2024 को सप्ताह का कौन-सा दिन था?", ["बुधवार", "मंगलवार", "शुक्रवार", "गुरुवार"], "15 अगस्त 2023 से 15 अगस्त 2024 के बीच 29 फरवरी 2024 आती है, अतः 366 दिन = 52 सप्ताह + 2 दिन। मंगलवार + 2 = गुरुवार।"]),
  q(2, "reasoning", "clock-calendar", "H", 1,
    ["What is the angle between the hour hand and the minute hand of a clock at 2:20?", ["40°", "50°", "60°", "70°"], "Angle = |30H − 5.5M| = |30×2 − 5.5×20| = |60 − 110| = 50°."],
    ["2:20 बजे घड़ी की घंटे और मिनट की सुई के बीच कितना कोण होगा?", ["40°", "50°", "60°", "70°"], "कोण = |30H − 5.5M| = |30×2 − 5.5×20| = |60 − 110| = 50°।"], "Math.abs(30*2-5.5*20)"),
  q(2, "reasoning", "inequality", "H", 0,
    ["If A > B = C ≥ D < E, which of the following is definitely true?", ["A > D", "E > B", "C > E", "D = A"], "A > B = C ≥ D gives A > D. E is compared only with D, so nothing definite can be said about E and B or C."],
    ["यदि A > B = C ≥ D < E, तो निम्न में से क्या निश्चित रूप से सत्य है?", ["A > D", "E > B", "C > E", "D = A"], "A > B = C ≥ D से A > D मिलता है। E की तुलना केवल D से है, इसलिए E और B या C के बारे में निश्चित रूप से कुछ नहीं कहा जा सकता।"]),
  q(2, "reasoning", "math-operations", "H", 1,
    ["If '×' means '+', '+' means '÷', '−' means '×' and '÷' means '−', then 8 × 12 + 4 − 3 ÷ 5 = ?", ["10", "12", "14", "9"], "Replacing the signs: 8 + 12 ÷ 4 × 3 − 5 = 8 + 3 × 3 − 5 = 8 + 9 − 5 = 12."],
    ["यदि '×' का अर्थ '+', '+' का अर्थ '÷', '−' का अर्थ '×' और '÷' का अर्थ '−' हो, तो 8 × 12 + 4 − 3 ÷ 5 = ?", ["10", "12", "14", "9"], "चिह्न बदलने पर: 8 + 12 ÷ 4 × 3 − 5 = 8 + 3 × 3 − 5 = 8 + 9 − 5 = 12।"], "8+12/4*3-5"),

  // ───────── Section 3: Numerical Ability (15) ─────────
  q(3, "quant", "percentage", "H", 0,
    ["In an examination, 35% of the candidates failed in Hindi, 25% failed in English and 10% failed in both. What percentage of candidates passed in both subjects?", ["50%", "40%", "60%", "45%"], "Failed in at least one = 35 + 25 − 10 = 50%. So passed in both = 100 − 50 = 50%."],
    ["एक परीक्षा में 35% परीक्षार्थी हिंदी में, 25% अंग्रेज़ी में और 10% दोनों में अनुत्तीर्ण हुए। कितने प्रतिशत परीक्षार्थी दोनों विषयों में उत्तीर्ण हुए?", ["50%", "40%", "60%", "45%"], "कम से कम एक में अनुत्तीर्ण = 35 + 25 − 10 = 50%। अतः दोनों में उत्तीर्ण = 100 − 50 = 50%।"], "100-(35+25-10)"),
  q(3, "quant", "percentage", "M", 1,
    ["The price of petrol rises from ₹80 to ₹100 per litre. By what percentage must a person reduce consumption so that the expenditure stays the same?", ["25%", "20%", "15%", "22%"], "Reduction % = (rise ÷ new price) × 100 = (20 ÷ 100) × 100 = 20%."],
    ["पेट्रोल का मूल्य ₹80 से बढ़कर ₹100 प्रति लीटर हो जाता है। खर्च समान रखने के लिए खपत कितने प्रतिशत घटानी होगी?", ["25%", "20%", "15%", "22%"], "कमी % = (वृद्धि ÷ नया मूल्य) × 100 = (20 ÷ 100) × 100 = 20%।"], "20/100*100"),
  q(3, "quant", "profit-loss", "H", 2,
    ["A dishonest shopkeeper sells goods at cost price but uses a weight of 800 g instead of 1 kg. His gain percent is:", ["20%", "22.5%", "25%", "30%"], "He gives 800 g but charges for 1,000 g, gaining 200 g on 800 g. Gain % = 200/800 × 100 = 25%."],
    ["एक बेईमान दुकानदार सामान क्रय मूल्य पर बेचता है, परंतु 1 किग्रा के स्थान पर 800 ग्राम का बाट प्रयोग करता है। उसका लाभ प्रतिशत है:", ["20%", "22.5%", "25%", "30%"], "वह 800 ग्राम देता है पर 1,000 ग्राम का मूल्य लेता है, यानी 800 ग्राम पर 200 ग्राम का लाभ। लाभ % = 200/800 × 100 = 25%।"], "200/800*100"),
  q(3, "quant", "profit-loss", "M", 3,
    ["By selling a watch for ₹1,140, a man loses 5%. What is the cost price of the watch?", ["₹1,197", "₹1,180", "₹1,250", "₹1,200"], "SP = 95% of CP, so CP = 1,140 ÷ 0.95 = ₹1,200."],
    ["एक घड़ी ₹1,140 में बेचने पर व्यक्ति को 5% हानि होती है। घड़ी का क्रय मूल्य क्या है?", ["₹1,197", "₹1,180", "₹1,250", "₹1,200"], "विक्रय मूल्य = क्रय मूल्य का 95%, अतः क्रय मूल्य = 1,140 ÷ 0.95 = ₹1,200।"], "1140/0.95"),
  q(3, "quant", "interest", "M", 0,
    ["A sum of money doubles itself in 8 years at simple interest. The rate of interest per annum is:", ["12.5%", "10%", "8%", "15%"], "Doubling means interest = principal. So R × 8 = 100, R = 12.5%."],
    ["कोई धनराशि साधारण ब्याज पर 8 वर्ष में दुगुनी हो जाती है। वार्षिक ब्याज दर है:", ["12.5%", "10%", "8%", "15%"], "दुगुनी होने का अर्थ है ब्याज = मूलधन। अतः R × 8 = 100, R = 12.5%।"], "100/8"),
  q(3, "quant", "interest", "H", 1,
    ["What amount will ₹8,000 become in 3 years at 5% per annum compound interest, compounded annually?", ["₹9,200", "₹9,261", "₹9,240", "₹9,282"], "A = 8,000 × (1.05)³ = 8,000 × 1.157625 = ₹9,261."],
    ["₹8,000 की राशि 5% वार्षिक चक्रवृद्धि ब्याज (वार्षिक संयोजन) पर 3 वर्ष में कितनी हो जाएगी?", ["₹9,200", "₹9,261", "₹9,240", "₹9,282"], "मिश्रधन = 8,000 × (1.05)³ = 8,000 × 1.157625 = ₹9,261।"], "8000*1.05**3"),
  q(3, "quant", "time-work", "M", 2,
    ["A can do a piece of work in 10 days, B in 15 days and C in 30 days. Working together, in how many days will they finish it?", ["6 days", "4 days", "5 days", "7 days"], "One day's work = 1/10 + 1/15 + 1/30 = (3 + 2 + 1)/30 = 1/5. So they finish in 5 days."],
    ["A किसी काम को 10 दिन में, B 15 दिन में और C 30 दिन में कर सकता है। तीनों मिलकर यह काम कितने दिन में पूरा करेंगे?", ["6 दिन", "4 दिन", "5 दिन", "7 दिन"], "एक दिन का काम = 1/10 + 1/15 + 1/30 = (3 + 2 + 1)/30 = 1/5। अतः वे 5 दिन में काम पूरा करेंगे।"], "1/(1/10+1/15+1/30)"),
  q(3, "quant", "time-work", "H", 3,
    ["15 men working 8 hours a day can finish a work in 20 days. In how many days will 20 men working 6 hours a day finish the same work?", ["15", "18", "24", "20"], "Men × hours × days is constant: 15 × 8 × 20 = 20 × 6 × D, so D = 2,400 ÷ 120 = 20 days."],
    ["15 आदमी प्रतिदिन 8 घंटे काम करके एक काम 20 दिन में पूरा करते हैं। 20 आदमी प्रतिदिन 6 घंटे काम करके वही काम कितने दिन में पूरा करेंगे?", ["15", "18", "24", "20"], "आदमी × घंटे × दिन स्थिर रहता है: 15 × 8 × 20 = 20 × 6 × D, अतः D = 2,400 ÷ 120 = 20 दिन।"], "15*8*20/(20*6)"),
  q(3, "quant", "speed-distance", "H", 0,
    ["A thief running at 10 km/h is 600 m ahead of a police jeep moving at 40 km/h in the same direction. In how many seconds will the jeep catch the thief?", ["72 seconds", "54 seconds", "90 seconds", "60 seconds"], "Relative speed = 40 − 10 = 30 km/h. Time = 0.6 km ÷ 30 km/h = 0.02 h = 0.02 × 3,600 = 72 seconds."],
    ["10 किमी/घंटा से भाग रहा एक चोर, उसी दिशा में 40 किमी/घंटा से चल रही पुलिस जीप से 600 मीटर आगे है। जीप चोर को कितने सेकंड में पकड़ लेगी?", ["72 सेकंड", "54 सेकंड", "90 सेकंड", "60 सेकंड"], "सापेक्ष चाल = 40 − 10 = 30 किमी/घंटा। समय = 0.6 किमी ÷ 30 किमी/घंटा = 0.02 घंटा = 0.02 × 3,600 = 72 सेकंड।"], "0.6/30*3600"),
  q(3, "quant", "speed-distance", "M", 1,
    ["A train 240 m long crosses a platform 360 m long in 30 seconds. What is the speed of the train?", ["60 km/h", "72 km/h", "66 km/h", "80 km/h"], "Distance = 240 + 360 = 600 m. Speed = 600 ÷ 30 = 20 m/s = 20 × 18/5 = 72 km/h."],
    ["240 मीटर लंबी एक रेलगाड़ी 360 मीटर लंबे प्लेटफ़ॉर्म को 30 सेकंड में पार करती है। रेलगाड़ी की चाल क्या है?", ["60 किमी/घंटा", "72 किमी/घंटा", "66 किमी/घंटा", "80 किमी/घंटा"], "दूरी = 240 + 360 = 600 मी। चाल = 600 ÷ 30 = 20 मी/से = 20 × 18/5 = 72 किमी/घंटा।"], "600/30*18/5"),
  q(3, "quant", "average", "H", 2,
    ["The average of six consecutive even numbers is 25. What is the largest of these numbers?", ["28", "32", "30", "26"], "Six consecutive even numbers averaging 25 are 20, 22, 24, 26, 28, 30 (the middle pair 24 and 26 averages 25). The largest is 30."],
    ["छह क्रमागत सम संख्याओं का औसत 25 है। इनमें सबसे बड़ी संख्या कौन-सी है?", ["28", "32", "30", "26"], "औसत 25 वाली छह क्रमागत सम संख्याएँ 20, 22, 24, 26, 28, 30 हैं (बीच की 24 और 26 का औसत 25)। सबसे बड़ी 30 है।"], "25+5"),
  q(3, "quant", "ratio-proportion", "H", 3,
    ["Two numbers are in the ratio 5 : 7. If 6 is added to each, the ratio becomes 7 : 9. What is the sum of the two numbers?", ["48", "42", "30", "36"], "(5x + 6)/(7x + 6) = 7/9 → 45x + 54 = 49x + 42 → x = 3. The numbers are 15 and 21, and their sum is 36."],
    ["दो संख्याओं का अनुपात 5 : 7 है। प्रत्येक में 6 जोड़ने पर अनुपात 7 : 9 हो जाता है। दोनों संख्याओं का योग क्या है?", ["48", "42", "30", "36"], "(5x + 6)/(7x + 6) = 7/9 → 45x + 54 = 49x + 42 → x = 3। संख्याएँ 15 और 21 हैं, योग 36 है।"], "15+21"),
  q(3, "quant", "ages", "H", 0,
    ["The sum of the present ages of a mother and her daughter is 50 years. Five years ago the mother was 7 times as old as the daughter. What is the mother's present age?", ["40 years", "38 years", "42 years", "45 years"], "Let the daughter be D. Mother = 50 − D. 50 − D − 5 = 7(D − 5) → 45 − D = 7D − 35 → D = 10. Mother = 40 years."],
    ["माँ और बेटी की वर्तमान आयु का योग 50 वर्ष है। पाँच वर्ष पहले माँ की आयु बेटी की आयु की 7 गुनी थी। माँ की वर्तमान आयु क्या है?", ["40 वर्ष", "38 वर्ष", "42 वर्ष", "45 वर्ष"], "मान लें बेटी की आयु D है। माँ = 50 − D। 50 − D − 5 = 7(D − 5) → 45 − D = 7D − 35 → D = 10। माँ = 40 वर्ष।"], "50-10"),
  q(3, "quant", "mensuration", "M", 1,
    ["The perimeter of a rectangle is 46 cm and its length is 15 cm. What is its area?", ["110 cm²", "120 cm²", "135 cm²", "150 cm²"], "2(l + b) = 46 → l + b = 23 → b = 8 cm. Area = 15 × 8 = 120 cm²."],
    ["एक आयत का परिमाप 46 सेमी और लंबाई 15 सेमी है। उसका क्षेत्रफल क्या है?", ["110 सेमी²", "120 सेमी²", "135 सेमी²", "150 सेमी²"], "2(l + b) = 46 → l + b = 23 → b = 8 सेमी। क्षेत्रफल = 15 × 8 = 120 सेमी²।"], "15*8"),
  q(3, "quant", "number-system", "H", 2,
    ["What is the largest four-digit number that is exactly divisible by 88?", ["9988", "9900", "9944", "9966"], "9999 ÷ 88 gives quotient 113 and remainder 55. So the largest multiple is 88 × 113 = 9944."],
    ["88 से पूर्णतः विभाज्य सबसे बड़ी चार अंकों की संख्या कौन-सी है?", ["9988", "9900", "9944", "9966"], "9999 ÷ 88 का भागफल 113 और शेषफल 55 है। अतः सबसे बड़ा गुणज 88 × 113 = 9944 है।"], "88*113"),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "english", "grammar", "H", 1,
    ["Fill in the blank: 'The police ___ arrested the three culprits.'", ["has", "have", "is", "was"], "'Police' is a plural collective noun and always takes a plural verb: 'The police have arrested…'."],
    ["रिक्त स्थान भरिए: 'The police ___ arrested the three culprits.'", ["has", "have", "is", "was"], "'Police' बहुवचन समूहवाचक संज्ञा है और सदैव बहुवचन क्रिया लेती है: 'The police have arrested…'।"]),
  q(4, "english", "synonyms-antonyms", "M", 0,
    ["Choose the synonym of 'VIGILANT':", ["Watchful", "Careless", "Lazy", "Timid"], "'Vigilant' means keeping careful watch for danger or difficulty, i.e. watchful."],
    ["'VIGILANT' का समानार्थी शब्द चुनिए:", ["Watchful", "Careless", "Lazy", "Timid"], "'Vigilant' का अर्थ है खतरे के प्रति सतर्क रहना, यानी watchful (चौकस)।"]),
  q(4, "english", "synonyms-antonyms", "M", 2,
    ["Choose the antonym of 'CULPABLE':", ["Guilty", "Blameworthy", "Innocent", "Liable"], "'Culpable' means deserving blame. Its opposite is 'innocent'; 'guilty', 'blameworthy' and 'liable' are close in meaning to it."],
    ["'CULPABLE' का विलोम शब्द चुनिए:", ["Guilty", "Blameworthy", "Innocent", "Liable"], "'Culpable' का अर्थ है दोषी/दोष के योग्य। इसका विलोम 'innocent' (निर्दोष) है; 'guilty', 'blameworthy' और 'liable' इसके निकट अर्थ वाले हैं।"]),
  q(4, "english", "one-word", "H", 0,
    ["One word for 'the killing of one's own father':", ["Patricide", "Fratricide", "Regicide", "Homicide"], "Patricide is killing one's father. Fratricide is killing one's brother, regicide a king, and homicide any human being."],
    ["'अपने ही पिता की हत्या' के लिए एक शब्द:", ["Patricide", "Fratricide", "Regicide", "Homicide"], "Patricide = पिता की हत्या। Fratricide = भाई की हत्या, Regicide = राजा की हत्या, Homicide = किसी भी मनुष्य की हत्या।"]),
  q(4, "english", "idioms", "M", 1,
    ["Choose the meaning of the idiom 'to take the law into one's own hands':", ["To become a lawyer", "To punish someone yourself instead of going to the police or courts", "To make new laws", "To obey the law strictly"], "The idiom means to act on your own, often illegally or violently, to punish someone instead of letting the legal system deal with it."],
    ["मुहावरे 'to take the law into one's own hands' का अर्थ चुनिए:", ["वकील बन जाना", "पुलिस या अदालत के पास जाने के बजाय स्वयं किसी को दंड देना", "नए क़ानून बनाना", "क़ानून का कड़ाई से पालन करना"], "इसका अर्थ है क़ानूनी व्यवस्था पर छोड़ने के बजाय स्वयं (अक्सर अवैध या हिंसक ढंग से) किसी को दंड देना।"]),
  q(4, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'The number of road accidents / are increasing / every year. / No error'", ["The number of road accidents", "are increasing", "every year.", "No error"], "'The number of' takes a singular verb, so it should be 'is increasing'. ('A number of' takes a plural verb.)"],
    ["त्रुटि वाला भाग चुनिए: 'The number of road accidents / are increasing / every year. / No error'", ["The number of road accidents", "are increasing", "every year.", "No error"], "'The number of' के साथ एकवचन क्रिया आती है, अतः 'is increasing' होना चाहिए। ('A number of' के साथ बहुवचन क्रिया आती है।)"]),
  q(4, "english", "voice-speech", "M", 2,
    ["Change into the passive voice: 'The police caught the thief.'", ["The thief is caught by the police.", "The thief has been caught by the police.", "The thief was caught by the police.", "The police were caught by the thief."], "The sentence is in the simple past, so the passive is 'was + past participle': 'The thief was caught by the police.'"],
    ["वाच्य बदलिए (Passive Voice): 'The police caught the thief.'", ["The thief is caught by the police.", "The thief has been caught by the police.", "The thief was caught by the police.", "The police were caught by the thief."], "वाक्य सामान्य भूतकाल में है, अतः कर्मवाच्य 'was + past participle' होगा: 'The thief was caught by the police.'"]),
  q(4, "english", "voice-speech", "M", 0,
    ["Change into indirect speech: He said, 'I am tired.'", ["He said that he was tired.", "He said that I am tired.", "He said that he is tired.", "He says that he was tired."], "With a past reporting verb, 'I' becomes 'he' and 'am' becomes 'was': He said that he was tired."],
    ["अप्रत्यक्ष कथन में बदलिए: He said, 'I am tired.'", ["He said that he was tired.", "He said that I am tired.", "He said that he is tired.", "He says that he was tired."], "रिपोर्टिंग क्रिया भूतकाल में होने पर 'I' का 'he' और 'am' का 'was' हो जाता है: He said that he was tired."]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Choose the antonym of the Hindi word 'दोषी':", ["अपराधी", "कसूरवार", "पापी", "निर्दोष"], "'दोषी' means guilty; its antonym is 'निर्दोष' (innocent). The other options are near-synonyms of 'दोषी'."],
    ["'दोषी' शब्द का विलोम चुनिए:", ["अपराधी", "कसूरवार", "पापी", "निर्दोष"], "'दोषी' का विलोम 'निर्दोष' है। अन्य विकल्प 'दोषी' के समानार्थी जैसे हैं।"]),
  q(4, "hindi", "sandhi-samas", "H", 0,
    ["Choose the correct split of the sandhi word 'जगन्नाथ':", ["जगत् + नाथ", "जग + नाथ", "जगन् + नाथ", "जगत + अनाथ"], "'जगन्नाथ' = जगत् + नाथ. Before 'न', the 'त्' changes to 'न्', which is a vyanjan (consonant) sandhi."],
    ["'जगन्नाथ' का सही संधि-विच्छेद चुनिए:", ["जगत् + नाथ", "जग + नाथ", "जगन् + नाथ", "जगत + अनाथ"], "'जगन्नाथ' = जगत् + नाथ। 'न' से पहले 'त्' का 'न्' हो जाता है, यह व्यंजन संधि है।"]),
  q(4, "hindi", "sandhi-samas", "H", 1,
    ["Identify the type of compound (samas) in 'चौराहा' (a place where four roads meet):", ["Tatpurush", "Dvigu", "Bahuvrihi", "Dvandva"], "'चौराहा' = चार राहों का समूह. The first part is a number and the word denotes a group, so it is a Dvigu samas."],
    ["'चौराहा' शब्द में कौन-सा समास है?", ["तत्पुरुष", "द्विगु", "बहुव्रीहि", "द्वंद्व"], "'चौराहा' = चार राहों का समूह। पहला पद संख्यावाचक है और समूह का बोध होता है, अतः द्विगु समास है।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["What is the meaning of the Hindi idiom 'लोहे के चने चबाना'?", ["To eat hard food", "To become very strong", "To do an extremely difficult task", "To waste time"], "The idiom means to face great hardship or to do something extremely difficult."],
    ["'लोहे के चने चबाना' मुहावरे का अर्थ है:", ["कठोर भोजन करना", "बहुत बलवान होना", "अत्यंत कठिन कार्य करना", "समय बर्बाद करना"], "इस मुहावरे का अर्थ है बहुत कठिनाई झेलना या अत्यंत कठिन कार्य करना।"]),
  q(4, "hindi", "ek-shabd", "M", 0,
    ["Choose the one word for 'that which is against the law' (जो क़ानून के विरुद्ध हो):", ["अवैध", "अनैतिक", "असंवैधानिक", "अनुचित"], "'अवैध' means illegal, against the law. 'अनैतिक' is immoral, 'असंवैधानिक' against the Constitution and 'अनुचित' improper."],
    ["'जो क़ानून के विरुद्ध हो' के लिए एक शब्द चुनिए:", ["अवैध", "अनैतिक", "असंवैधानिक", "अनुचित"], "'अवैध' = जो क़ानून के विरुद्ध हो। 'अनैतिक' = नैतिकता के विरुद्ध, 'असंवैधानिक' = संविधान के विरुद्ध, 'अनुचित' = जो उचित न हो।"]),
  q(4, "hindi", "alankar-ras", "H", 1,
    ["Identify the figure of speech in 'मुख मयंक सम मंजु मनोहर':", ["Rupak", "Upma", "Utpreksha", "Anupras only"], "The face (मुख) is compared with the moon (मयंक) using the comparison word 'सम', so it is Upma alankar."],
    ["'मुख मयंक सम मंजु मनोहर' में कौन-सा अलंकार है?", ["रूपक", "उपमा", "उत्प्रेक्षा", "केवल अनुप्रास"], "यहाँ मुख की तुलना मयंक (चंद्रमा) से वाचक शब्द 'सम' द्वारा की गई है, अतः उपमा अलंकार है।"]),
  q(4, "hindi", "shuddh-vartani", "H", 0,
    ["Choose the correctly spelt Hindi word for 'bright, shining':", ["उज्ज्वल", "उज्वल", "उजवल", "उज्जवल"], "The correct spelling is 'उज्ज्वल' (उत् + ज्वल), with a half 'ज्' followed by 'ज्व'."],
    ["'चमकदार, प्रकाशमान' के लिए शुद्ध वर्तनी वाला शब्द चुनिए:", ["उज्ज्वल", "उज्वल", "उजवल", "उज्जवल"], "शुद्ध वर्तनी 'उज्ज्वल' (उत् + ज्वल) है, जिसमें आधे 'ज्' के बाद 'ज्व' आता है।"]),
];
