// HPSCB Clerk — Banking Awareness, 15 fresh questions for each of the two full mocks.

import { q, type PatwariQuestion } from "../../patwari/types";

const B = "banking";

export const banking: PatwariQuestion[][] = [
  [
    q(0, B, "banking-awareness", "M", 1,
      ["The Reserve Bank of India started functioning on:", ["15 August 1947", "1 April 1935", "26 January 1950", "1 January 1949"], "RBI was set up under the RBI Act, 1934 and began operations on 1 April 1935; it was nationalised on 1 January 1949."],
      ["भारतीय रिज़र्व बैंक ने कार्य करना कब शुरू किया?", ["15 अगस्त 1947", "1 अप्रैल 1935", "26 जनवरी 1950", "1 जनवरी 1949"], "RBI अधिनियम, 1934 के तहत बना RBI 1 अप्रैल 1935 से कार्य करने लगा; 1 जनवरी 1949 को इसका राष्ट्रीयकरण हुआ।"]),
    q(0, B, "cooperative-banking", "H", 2,
      ["In the short-term cooperative credit structure, the tier that deals directly with farmers at the village level is the:", ["State Cooperative Bank", "District Central Cooperative Bank", "Primary Agricultural Credit Society", "NABARD"], "The three tiers are StCB (state), DCCB (district) and PACS (village); NABARD refinances but is not a tier."],
      ["अल्पकालिक सहकारी ऋण ढाँचे में गाँव स्तर पर सीधे किसानों से लेन-देन करने वाला स्तर है:", ["राज्य सहकारी बैंक", "ज़िला केंद्रीय सहकारी बैंक", "प्राथमिक कृषि ऋण समिति", "नाबार्ड"], "तीन स्तर हैं: StCB (राज्य), DCCB (ज़िला) और PACS (गाँव); नाबार्ड पुनर्वित्त देता है पर स्वयं कोई स्तर नहीं है।"]),
    q(0, B, "banking-awareness", "M", 0,
      ["NABARD was established in:", ["1982", "1969", "1975", "1991"], "NABARD was set up on 12 July 1982 on the recommendation of the Shivaraman Committee (CRAFICARD)."],
      ["नाबार्ड की स्थापना कब हुई?", ["1982", "1969", "1975", "1991"], "शिवरामन समिति (CRAFICARD) की सिफ़ारिश पर 12 जुलाई 1982 को नाबार्ड स्थापित हुआ।"]),
    q(0, B, "banking-awareness", "H", 3,
      ["Deposits in a bank are insured by DICGC up to a maximum of:", ["₹1 lakh per account", "₹2 lakh per depositor", "₹10 lakh per depositor", "₹5 lakh per depositor per bank"], "Since February 2020 DICGC covers up to ₹5 lakh per depositor in each insured bank, including cooperative banks."],
      ["बैंक में जमा राशि DICGC द्वारा अधिकतम कितनी राशि तक बीमित है?", ["प्रति खाता ₹1 लाख", "प्रति जमाकर्ता ₹2 लाख", "प्रति जमाकर्ता ₹10 लाख", "प्रति बैंक प्रति जमाकर्ता ₹5 लाख"], "फ़रवरी 2020 से DICGC हर बीमित बैंक, सहकारी बैंकों सहित, में प्रति जमाकर्ता ₹5 लाख तक का बीमा देता है।"]),
    q(0, B, "banking-awareness", "M", 1,
      ["The rate at which RBI lends short-term funds to commercial banks against government securities is the:", ["Reverse repo rate", "Repo rate", "Bank rate", "CRR"], "Repo rate is RBI's main policy rate for lending to banks; reverse repo is for absorbing funds from banks."],
      ["जिस दर पर RBI सरकारी प्रतिभूतियों के बदले वाणिज्यिक बैंकों को अल्पकालिक ऋण देता है, वह है:", ["रिवर्स रेपो दर", "रेपो दर", "बैंक दर", "CRR"], "रेपो दर बैंकों को ऋण देने की RBI की मुख्य नीतिगत दर है; रिवर्स रेपो बैंकों से धन सोखने के लिए है।"]),
    q(0, B, "banking-awareness", "H", 0,
      ["A loan account is classified as a Non-Performing Asset when interest or instalment remains overdue for more than:", ["90 days", "30 days", "60 days", "180 days"], "As per RBI norms an advance becomes an NPA when interest or principal is overdue for more than 90 days."],
      ["ऋण खाते को अनर्जक परिसंपत्ति (NPA) कब माना जाता है जब ब्याज या किस्त कितने दिनों से अधिक बकाया रहे?", ["90 दिन", "30 दिन", "60 दिन", "180 दिन"], "RBI मानकों के अनुसार ब्याज या मूलधन 90 दिन से अधिक बकाया होने पर ऋण NPA बन जाता है।"]),
    q(0, B, "banking-awareness", "M", 2,
      ["The IFSC code used for electronic fund transfer has how many characters?", ["9", "10", "11", "12"], "IFSC is 11 characters: 4 letters for the bank, a zero, and 6 characters for the branch. MICR has 9 digits."],
      ["इलेक्ट्रॉनिक धन अंतरण में उपयोग होने वाले IFSC कोड में कितने अक्षर होते हैं?", ["9", "10", "11", "12"], "IFSC 11 अक्षरों का होता है: बैंक के 4 अक्षर, एक शून्य और शाखा के 6 अक्षर। MICR में 9 अंक होते हैं।"]),
    q(0, B, "banking-awareness", "H", 3,
      ["Dishonour of a cheque for insufficient funds is an offence under Section 138 of the:", ["Banking Regulation Act, 1949", "RBI Act, 1934", "Indian Contract Act, 1872", "Negotiable Instruments Act, 1881"], "Section 138 of the NI Act makes bouncing of a cheque for insufficient funds a criminal offence."],
      ["अपर्याप्त राशि के कारण चेक अनादरित होना किस अधिनियम की धारा 138 के तहत अपराध है?", ["बैंककारी विनियमन अधिनियम, 1949", "RBI अधिनियम, 1934", "भारतीय संविदा अधिनियम, 1872", "परक्राम्य लिखत अधिनियम, 1881"], "परक्राम्य लिखत अधिनियम की धारा 138 अपर्याप्त राशि से चेक बाउंस को आपराधिक अपराध बनाती है।"]),
    q(0, B, "banking-awareness", "M", 0,
      ["A cheque is valid for how long from the date written on it?", ["3 months", "6 months", "1 month", "1 year"], "Since 1 April 2012 RBI has set cheque validity at three months from the date of issue."],
      ["चेक उस पर लिखी तारीख से कितने समय तक वैध रहता है?", ["3 माह", "6 माह", "1 माह", "1 वर्ष"], "1 अप्रैल 2012 से RBI ने चेक की वैधता जारी करने की तारीख से तीन माह तय की है।"]),
    q(0, B, "banking-awareness", "H", 1,
      ["Fourteen major commercial banks were nationalised in India in:", ["1955", "1969", "1980", "1991"], "Fourteen banks were nationalised on 19 July 1969 and six more in April 1980."],
      ["भारत में चौदह प्रमुख वाणिज्यिक बैंकों का राष्ट्रीयकरण कब हुआ?", ["1955", "1969", "1980", "1991"], "19 जुलाई 1969 को चौदह बैंकों का और अप्रैल 1980 में छह और बैंकों का राष्ट्रीयकरण हुआ।"]),
    q(0, B, "cooperative-banking", "H", 2,
      ["After the Banking Regulation (Amendment) Act, 2020, urban and state cooperative banks are:", ["Regulated only by the state Registrar of Cooperative Societies", "Outside any banking regulation", "Brought under closer RBI supervision for banking functions", "Merged with NABARD"], "The 2020 amendment extended RBI's powers over the banking functions of cooperative banks; registration and management issues stay with the Registrar."],
      ["बैंककारी विनियमन (संशोधन) अधिनियम, 2020 के बाद शहरी और राज्य सहकारी बैंक:", ["केवल राज्य सहकारी समिति रजिस्ट्रार द्वारा विनियमित हैं", "किसी भी बैंकिंग विनियमन से बाहर हैं", "बैंकिंग कार्यों के लिए RBI की अधिक निगरानी में लाए गए हैं", "नाबार्ड में विलय कर दिए गए हैं"], "2020 संशोधन ने सहकारी बैंकों के बैंकिंग कार्यों पर RBI के अधिकार बढ़ाए; पंजीकरण और प्रबंधन के विषय रजिस्ट्रार के पास रहे।"]),
    q(0, B, "banking-awareness", "M", 3,
      ["The Kisan Credit Card scheme was introduced in:", ["2005", "1991", "2014", "1998"], "KCC was introduced in August 1998 on the recommendation of the R.V. Gupta Committee."],
      ["किसान क्रेडिट कार्ड योजना कब शुरू हुई?", ["2005", "1991", "2014", "1998"], "आर.वी. गुप्ता समिति की सिफ़ारिश पर अगस्त 1998 में KCC शुरू हुआ।"]),
    q(0, B, "banking-awareness", "M", 1,
      ["UPI (Unified Payments Interface) was developed by:", ["RBI", "National Payments Corporation of India", "State Bank of India", "SEBI"], "NPCI launched UPI in 2016; NPCI also runs RuPay, IMPS and NACH."],
      ["UPI (यूनिफ़ाइड पेमेंट्स इंटरफ़ेस) किसने विकसित किया?", ["RBI", "नेशनल पेमेंट्स कॉर्पोरेशन ऑफ़ इंडिया", "भारतीय स्टेट बैंक", "SEBI"], "NPCI ने 2016 में UPI शुरू किया; NPCI रुपे, IMPS और NACH भी चलाता है।"]),
    q(0, B, "banking-awareness", "H", 0,
      ["Under the RBI's flexible inflation targeting framework, the CPI inflation target is:", ["4% with a band of ±2%", "2% with a band of ±1%", "6% fixed", "5% with a band of ±3%"], "The target set by the government is 4% CPI inflation within a tolerance band of 2–6%; the Monetary Policy Committee has six members."],
      ["RBI के लचीले मुद्रास्फीति लक्ष्य ढाँचे में CPI मुद्रास्फीति का लक्ष्य है:", ["±2% सीमा के साथ 4%", "±1% सीमा के साथ 2%", "स्थिर 6%", "±3% सीमा के साथ 5%"], "सरकार द्वारा तय लक्ष्य 2–6% सहनशीलता सीमा के भीतर 4% CPI मुद्रास्फीति है; मौद्रिक नीति समिति में छह सदस्य हैं।"]),
    q(0, B, "banking-awareness", "E", 2,
      ["Pradhan Mantri Jan Dhan Yojana, launched in 2014, mainly aims at:", ["Crop insurance", "Housing for all", "Financial inclusion through bank accounts for all households", "Pension for the elderly"], "PMJDY gives zero-balance accounts with RuPay debit card and accident insurance to bring the unbanked into banking."],
      ["2014 में शुरू प्रधानमंत्री जन धन योजना का मुख्य उद्देश्य है:", ["फ़सल बीमा", "सबके लिए आवास", "सभी परिवारों के बैंक खाते खोलकर वित्तीय समावेशन", "वृद्धों के लिए पेंशन"], "PMJDY बिना बैंक वाले लोगों को बैंकिंग से जोड़ने के लिए रुपे डेबिट कार्ड और दुर्घटना बीमा सहित शून्य-शेष खाते देती है।"]),
  ],
  [
    q(0, B, "banking-awareness", "M", 2,
      ["The portion of deposits that banks must keep with the RBI in cash is called:", ["SLR", "Repo rate", "Cash Reserve Ratio", "Bank rate"], "CRR is held as cash balance with the RBI; SLR is kept by the bank itself in cash, gold or approved securities."],
      ["जमाओं का वह भाग जिसे बैंकों को नकद रूप में RBI के पास रखना होता है, कहलाता है:", ["SLR", "रेपो दर", "नकद आरक्षित अनुपात (CRR)", "बैंक दर"], "CRR RBI के पास नकद शेष के रूप में रखा जाता है; SLR बैंक स्वयं नकद, सोना या अनुमोदित प्रतिभूतियों में रखता है।"]),
    q(0, B, "banking-awareness", "H", 0,
      ["The minimum amount that can be sent through RTGS is:", ["₹2 lakh", "₹1 lakh", "₹50,000", "No minimum"], "RTGS is meant for large-value transfers with a minimum of ₹2 lakh and no upper limit; NEFT has no minimum."],
      ["RTGS द्वारा भेजी जा सकने वाली न्यूनतम राशि है:", ["₹2 लाख", "₹1 लाख", "₹50,000", "कोई न्यूनतम नहीं"], "RTGS बड़ी राशि के अंतरण के लिए है, न्यूनतम ₹2 लाख और कोई ऊपरी सीमा नहीं; NEFT में कोई न्यूनतम सीमा नहीं।"]),
    q(0, B, "cooperative-banking", "M", 1,
      ["A cooperative society is based on the principle of:", ["One share, one vote", "One member, one vote", "Maximum profit for shareholders", "Government ownership"], "Democratic member control — one member, one vote — is a core cooperative principle."],
      ["सहकारी समिति किस सिद्धांत पर आधारित होती है?", ["एक शेयर, एक वोट", "एक सदस्य, एक वोट", "शेयरधारकों के लिए अधिकतम लाभ", "सरकारी स्वामित्व"], "लोकतांत्रिक सदस्य नियंत्रण — एक सदस्य, एक वोट — सहकारिता का मूल सिद्धांत है।"]),
    q(0, B, "banking-awareness", "H", 3,
      ["SARFAESI Act, 2002 allows banks to:", ["Print currency", "Fix interest rates for all banks", "Open branches abroad without approval", "Enforce security interest and recover dues without court intervention"], "The Act lets secured creditors take possession of and sell secured assets of defaulters without going to court."],
      ["SARFAESI अधिनियम, 2002 बैंकों को किसकी अनुमति देता है?", ["मुद्रा छापने की", "सभी बैंकों की ब्याज दरें तय करने की", "बिना अनुमति विदेश में शाखा खोलने की", "न्यायालय के हस्तक्षेप बिना प्रतिभूति हित लागू कर बकाया वसूलने की"], "यह अधिनियम सुरक्षित लेनदारों को बिना न्यायालय गए चूककर्ताओं की गिरवी परिसंपत्तियाँ कब्ज़े में लेकर बेचने देता है।"]),
    q(0, B, "banking-awareness", "M", 0,
      ["'Know Your Customer' (KYC) norms in banks are mainly meant to:", ["Prevent money laundering and verify customer identity", "Increase interest income", "Reduce staff", "Fix loan limits"], "KYC verifies identity and address, helping prevent money laundering and terror financing (PMLA, 2002)."],
      ["बैंकों में 'अपने ग्राहक को जानिए' (KYC) मानदंड मुख्यतः किसलिए हैं?", ["धन-शोधन रोकने और ग्राहक की पहचान सत्यापित करने के लिए", "ब्याज आय बढ़ाने के लिए", "कर्मचारी घटाने के लिए", "ऋण सीमा तय करने के लिए"], "KYC पहचान और पते की पुष्टि करता है, जिससे धन-शोधन और आतंक-वित्तपोषण रोकने में मदद मिलती है (PMLA, 2002)।"]),
    q(0, B, "banking-awareness", "H", 2,
      ["Under RBI norms, domestic commercial banks must lend what share of Adjusted Net Bank Credit to the priority sector?", ["18%", "25%", "40%", "60%"], "The overall priority-sector target is 40% of ANBC (or credit equivalent of off-balance-sheet exposure); agriculture's sub-target is 18%. Urban cooperative banks have a higher, phased target."],
      ["RBI मानकों के अनुसार घरेलू वाणिज्यिक बैंकों को समायोजित निवल बैंक ऋण का कितना भाग प्राथमिकता क्षेत्र को देना होता है?", ["18%", "25%", "40%", "60%"], "समग्र प्राथमिकता क्षेत्र लक्ष्य ANBC का 40% है; कृषि का उप-लक्ष्य 18% है। शहरी सहकारी बैंकों का लक्ष्य अधिक और चरणबद्ध है।"]),
    q(0, B, "banking-awareness", "M", 3,
      ["A cheque with two parallel lines drawn across its face is called a:", ["Bearer cheque", "Stale cheque", "Post-dated cheque", "Crossed cheque"], "A crossed cheque can only be paid into a bank account, not encashed over the counter."],
      ["जिस चेक पर दो समानांतर रेखाएँ खिंची हों, वह कहलाता है:", ["वाहक चेक", "बासी चेक", "उत्तर-दिनांकित चेक", "रेखांकित (क्रॉस्ड) चेक"], "रेखांकित चेक का भुगतान केवल बैंक खाते में होता है, काउंटर पर नकद नहीं।"]),
    q(0, B, "banking-awareness", "M", 1,
      ["The Lead Bank Scheme, under which one bank coordinates credit in a district, was introduced in:", ["1955", "1969", "1982", "2005"], "The Lead Bank Scheme was started in 1969 on the basis of the Gadgil Study Group and Nariman Committee reports."],
      ["अग्रणी बैंक योजना, जिसमें एक बैंक ज़िले में ऋण का समन्वय करता है, कब शुरू हुई?", ["1955", "1969", "1982", "2005"], "गाडगिल अध्ययन समूह और नरीमन समिति की रिपोर्टों के आधार पर 1969 में अग्रणी बैंक योजना शुरू हुई।"]),
    q(0, B, "banking-awareness", "H", 0,
      ["Loans under Pradhan Mantri MUDRA Yojana are classified as Shishu, Kishore, Tarun and Tarun Plus. Shishu loans are up to:", ["₹50,000", "₹1 lakh", "₹5 lakh", "₹10 lakh"], "Shishu up to ₹50,000; Kishore ₹50,000–₹5 lakh; Tarun ₹5–10 lakh; Tarun Plus (from 2024) ₹10–20 lakh."],
      ["प्रधानमंत्री मुद्रा योजना के ऋण शिशु, किशोर, तरुण और तरुण प्लस में बँटे हैं। शिशु ऋण कितनी राशि तक है?", ["₹50,000", "₹1 लाख", "₹5 लाख", "₹10 लाख"], "शिशु ₹50,000 तक; किशोर ₹50,000–₹5 लाख; तरुण ₹5–10 लाख; तरुण प्लस (2024 से) ₹10–20 लाख।"]),
    q(0, B, "cooperative-banking", "H", 3,
      ["Which body provides refinance to State Cooperative Banks for agricultural lending?", ["SIDBI", "EXIM Bank", "SEBI", "NABARD"], "NABARD refinances StCBs and RRBs for crop loans and investment credit."],
      ["कृषि ऋण के लिए राज्य सहकारी बैंकों को पुनर्वित्त कौन देता है?", ["सिडबी", "एक्ज़िम बैंक", "सेबी", "नाबार्ड"], "नाबार्ड फ़सल ऋण और निवेश ऋण के लिए StCB और RRB को पुनर्वित्त देता है।"]),
    q(0, B, "banking-awareness", "M", 2,
      ["The MICR code printed on a cheque has:", ["6 digits", "11 characters", "9 digits", "12 digits"], "MICR (Magnetic Ink Character Recognition) code has 9 digits: city (3), bank (3) and branch (3)."],
      ["चेक पर छपे MICR कोड में होते हैं:", ["6 अंक", "11 अक्षर", "9 अंक", "12 अंक"], "MICR (चुंबकीय स्याही अक्षर पहचान) कोड में 9 अंक होते हैं: शहर (3), बैंक (3) और शाखा (3)।"]),
    q(0, B, "banking-awareness", "H", 1,
      ["Payments banks in India are NOT allowed to:", ["Accept deposits", "Give loans and issue credit cards", "Issue debit cards", "Offer remittance services"], "Payments banks can take deposits (limit ₹2 lakh per customer), issue debit cards and handle remittances but cannot lend."],
      ["भारत में पेमेंट्स बैंकों को किसकी अनुमति नहीं है?", ["जमा स्वीकार करना", "ऋण देना और क्रेडिट कार्ड जारी करना", "डेबिट कार्ड जारी करना", "धन-प्रेषण सेवाएँ देना"], "पेमेंट्स बैंक जमा ले सकते हैं (प्रति ग्राहक ₹2 लाख सीमा), डेबिट कार्ड दे सकते हैं और धन-प्रेषण कर सकते हैं, पर ऋण नहीं दे सकते।"]),
    q(0, B, "banking-awareness", "M", 0,
      ["A facility allowing a current account holder to withdraw more than the balance up to a limit is:", ["Overdraft", "Fixed deposit", "Recurring deposit", "Demand draft"], "An overdraft lets the account go into debit up to a sanctioned limit, with interest on the amount used."],
      ["चालू खाताधारक को शेष से अधिक एक सीमा तक निकासी की अनुमति देने वाली सुविधा है:", ["ओवरड्राफ़्ट", "सावधि जमा", "आवर्ती जमा", "डिमांड ड्राफ़्ट"], "ओवरड्राफ़्ट में स्वीकृत सीमा तक खाता ऋणात्मक हो सकता है और उपयोग की गई राशि पर ब्याज लगता है।"]),
    q(0, B, "banking-awareness", "H", 3,
      ["Which of these is the 'banker to the Government of India'?", ["State Bank of India", "NABARD", "Ministry of Finance", "Reserve Bank of India"], "RBI acts as banker to the central and state governments; SBI acts as an agent of RBI in many places."],
      ["इनमें से कौन 'भारत सरकार का बैंकर' है?", ["भारतीय स्टेट बैंक", "नाबार्ड", "वित्त मंत्रालय", "भारतीय रिज़र्व बैंक"], "RBI केंद्र और राज्य सरकारों का बैंकर है; कई स्थानों पर SBI, RBI के एजेंट के रूप में काम करता है।"]),
    q(0, B, "banking-awareness", "E", 1,
      ["ATM stands for:", ["Any Time Money", "Automated Teller Machine", "Automatic Transfer Mode", "All Time Machine"], "An Automated Teller Machine lets customers withdraw cash and check balances without a teller."],
      ["ATM का पूर्ण रूप है:", ["एनी टाइम मनी", "ऑटोमेटेड टेलर मशीन", "ऑटोमैटिक ट्रांसफ़र मोड", "ऑल टाइम मशीन"], "ऑटोमेटेड टेलर मशीन से ग्राहक बिना कैशियर के नकद निकाल सकते हैं और शेष जाँच सकते हैं।"]),
  ],
];
