// HPRCA Forest Guard — Forestry & Environment, 20 fresh questions for each of the two full mocks.

import { q, type PatwariQuestion } from "../../patwari/types";

const F = "forestry";

export const forestry: PatwariQuestion[][] = [
  [
    q(0, F, "forests-wildlife", "M", 1,
      ["Which bird is the state bird of Himachal Pradesh?", ["Monal", "Western Tragopan (Jujurana)", "Koklass pheasant", "Chukar"], "The Western Tragopan, locally Jujurana ('king of birds'), replaced the Monal as the state bird in 2007."],
      ["हिमाचल प्रदेश का राज्य पक्षी है:", ["मोनाल", "पश्चिमी ट्रैगोपैन (जुजुराना)", "कोकलास तीतर", "चकोर"], "पश्चिमी ट्रैगोपैन, स्थानीय नाम जुजुराना ('पक्षियों का राजा'), 2007 में मोनाल के स्थान पर राज्य पक्षी बना।"]),
    q(0, F, "forests-wildlife", "M", 0,
      ["The Great Himalayan National Park, a UNESCO World Heritage Site, is in which district?", ["Kullu", "Chamba", "Kinnaur", "Shimla"], "GHNP in Kullu district was inscribed as a UNESCO World Heritage Site in 2014."],
      ["यूनेस्को विश्व धरोहर स्थल ग्रेट हिमालयन नेशनल पार्क किस ज़िले में है?", ["कुल्लू", "चंबा", "किन्नौर", "शिमला"], "कुल्लू ज़िले का GHNP 2014 में यूनेस्को विश्व धरोहर स्थल घोषित हुआ।"]),
    q(0, F, "forests-wildlife", "H", 2,
      ["The botanical name of Deodar, the state tree of Himachal Pradesh, is:", ["Pinus roxburghii", "Pinus wallichiana", "Cedrus deodara", "Abies pindrow"], "Deodar is Cedrus deodara; chir pine is Pinus roxburghii, kail (blue pine) Pinus wallichiana and silver fir Abies pindrow."],
      ["हिमाचल प्रदेश के राज्य वृक्ष देवदार का वानस्पतिक नाम है:", ["पाइनस रॉक्सबर्गी", "पाइनस वालिचियाना", "सेड्रस देवदारा", "एबीज़ पिंड्रो"], "देवदार सेड्रस देवदारा है; चीड़ पाइनस रॉक्सबर्गी, कैल पाइनस वालिचियाना और रई/तोस एबीज़ पिंड्रो है।"]),
    q(0, F, "forests-wildlife", "H", 3,
      ["Resin (biroza) in Himachal Pradesh is mainly tapped from:", ["Deodar", "Kail", "Spruce", "Chir pine"], "Oleoresin is tapped commercially from chir pine (Pinus roxburghii) in the lower hills."],
      ["हिमाचल प्रदेश में बिरोज़ा (रेज़िन) मुख्य रूप से किससे निकाला जाता है?", ["देवदार", "कैल", "स्प्रूस", "चीड़"], "निचली पहाड़ियों में चीड़ (पाइनस रॉक्सबर्गी) से व्यावसायिक रूप से बिरोज़ा निकाला जाता है।"]),
    q(0, F, "forests-wildlife", "M", 1,
      ["The Wildlife (Protection) Act was enacted in:", ["1927", "1972", "1980", "1986"], "Wildlife (Protection) Act 1972; Indian Forest Act 1927; Forest (Conservation) Act 1980; Environment (Protection) Act 1986."],
      ["वन्यजीव (संरक्षण) अधिनियम कब बना?", ["1927", "1972", "1980", "1986"], "वन्यजीव (संरक्षण) अधिनियम 1972; भारतीय वन अधिनियम 1927; वन (संरक्षण) अधिनियम 1980; पर्यावरण (संरक्षण) अधिनियम 1986।"]),
    q(0, F, "forests-wildlife", "H", 0,
      ["According to the National Forest Policy 1988, the share of geographical area under forest or tree cover in hilly regions should be:", ["Two-thirds", "One-third", "One-half", "One-fourth"], "The 1988 policy sets a national goal of one-third of land under forest/tree cover and two-thirds in the hills."],
      ["राष्ट्रीय वन नीति 1988 के अनुसार पहाड़ी क्षेत्रों में भौगोलिक क्षेत्र का कितना भाग वन या वृक्ष आवरण में होना चाहिए?", ["दो-तिहाई", "एक-तिहाई", "आधा", "एक-चौथाई"], "1988 की नीति में राष्ट्रीय लक्ष्य एक-तिहाई और पहाड़ों में दो-तिहाई भूमि को वन/वृक्ष आवरण में लाना है।"]),
    q(0, F, "environment-ecology", "M", 2,
      ["In a food chain, about how much energy passes from one trophic level to the next?", ["50%", "1%", "10%", "90%"], "Lindeman's ten per cent law: roughly 10% of energy is transferred to the next level; the rest is lost mainly as heat."],
      ["आहार शृंखला में एक पोषी स्तर से अगले स्तर तक लगभग कितनी ऊर्जा पहुँचती है?", ["50%", "1%", "10%", "90%"], "लिंडमैन का दस प्रतिशत नियम: लगभग 10% ऊर्जा अगले स्तर तक जाती है; शेष मुख्यतः ऊष्मा के रूप में नष्ट होती है।"]),
    q(0, F, "environment-ecology", "M", 3,
      ["The ozone layer that protects us from ultraviolet rays lies mainly in the:", ["Troposphere", "Mesosphere", "Thermosphere", "Stratosphere"], "Most atmospheric ozone is in the stratosphere, about 15–35 km above the Earth."],
      ["पराबैंगनी किरणों से बचाने वाली ओज़ोन परत मुख्यतः कहाँ स्थित है?", ["क्षोभमंडल", "मध्यमंडल", "तापमंडल", "समतापमंडल"], "अधिकांश वायुमंडलीय ओज़ोन समतापमंडल में, पृथ्वी से लगभग 15–35 किमी ऊपर है।"]),
    q(0, F, "forests-wildlife", "H", 1,
      ["In which district does Pin Valley National Park, a home of the snow leopard and Siberian ibex, lie?", ["Kinnaur", "Lahaul and Spiti", "Chamba", "Kullu"], "Pin Valley National Park lies in the cold desert of Spiti in Lahaul and Spiti district."],
      ["हिम तेंदुए और आइबेक्स के लिए प्रसिद्ध पिन वैली नेशनल पार्क कहाँ स्थित है?", ["किन्नौर", "लाहौल-स्पीति", "चंबा", "कुल्लू"], "पिन वैली नेशनल पार्क लाहौल-स्पीति ज़िले के स्पीति के ठंडे मरुस्थल में है।"]),
    q(0, F, "forests-wildlife", "M", 2,
      ["The Chipko movement for protecting trees began in 1973 in:", ["Himachal Pradesh", "Karnataka", "Uttarakhand (then Uttar Pradesh)", "Rajasthan"], "Chipko began in Chamoli (Mandal, Reni) in the Garhwal Himalaya, then part of Uttar Pradesh; leaders included Chandi Prasad Bhatt, Gaura Devi and Sunderlal Bahuguna."],
      ["पेड़ों की रक्षा का चिपको आंदोलन 1973 में कहाँ शुरू हुआ?", ["हिमाचल प्रदेश", "कर्नाटक", "उत्तराखंड (तब उत्तर प्रदेश)", "राजस्थान"], "चिपको आंदोलन गढ़वाल हिमालय के चमोली (मंडल, रेणी) में शुरू हुआ, जो तब उत्तर प्रदेश का भाग था; नेताओं में चंडी प्रसाद भट्ट, गौरा देवी और सुंदरलाल बहुगुणा थे।"]),
    q(0, F, "environment-ecology", "H", 0,
      ["Which gas contributes most to the enhanced greenhouse effect from human activity?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Argon"], "CO₂ from burning fossil fuels and deforestation is the largest contributor to human-caused warming."],
      ["मानव गतिविधियों से बढ़े हरितगृह प्रभाव में सबसे अधिक योगदान किस गैस का है?", ["कार्बन डाइऑक्साइड", "ऑक्सीजन", "नाइट्रोजन", "आर्गन"], "जीवाश्म ईंधन जलाने और वनों की कटाई से निकली CO₂ मानवजनित तापवृद्धि में सबसे बड़ा योगदान देती है।"]),
    q(0, F, "forests-wildlife", "M", 3,
      ["Van Mahotsav, the annual tree-planting festival, was started in 1950 by:", ["Sunderlal Bahuguna", "Jawaharlal Nehru", "Indira Gandhi", "K.M. Munshi"], "K.M. Munshi, then Union Minister for Agriculture, started Van Mahotsav in July 1950."],
      ["वार्षिक वृक्षारोपण पर्व वन महोत्सव 1950 में किसने शुरू किया?", ["सुंदरलाल बहुगुणा", "जवाहरलाल नेहरू", "इंदिरा गांधी", "के.एम. मुंशी"], "तत्कालीन केंद्रीय कृषि मंत्री के.एम. मुंशी ने जुलाई 1950 में वन महोत्सव शुरू किया।"]),
    q(0, F, "environment-ecology", "M", 1,
      ["Organisms that break down dead plants and animals are called:", ["Producers", "Decomposers", "Primary consumers", "Predators"], "Decomposers such as bacteria and fungi recycle nutrients from dead matter."],
      ["मृत पौधों और जंतुओं को तोड़ने वाले जीव कहलाते हैं:", ["उत्पादक", "अपघटक", "प्राथमिक उपभोक्ता", "शिकारी"], "जीवाणु और कवक जैसे अपघटक मृत पदार्थ से पोषक तत्वों का पुनर्चक्रण करते हैं।"]),
    q(0, F, "forests-wildlife", "H", 2,
      ["Which of these is a Ramsar wetland in Himachal Pradesh?", ["Prashar Lake", "Dal Lake (Dharamshala)", "Pong Dam Lake", "Khajjiar Lake"], "Himachal's Ramsar sites are Pong Dam Lake, Renuka Lake and Chandertal (Pong in 2002, the other two in 2005)."],
      ["इनमें से कौन हिमाचल प्रदेश का रामसर आर्द्रभूमि स्थल है?", ["पराशर झील", "डल झील (धर्मशाला)", "पौंग बाँध झील", "खज्जियार झील"], "हिमाचल के रामसर स्थल पौंग बाँध झील, रेणुका झील और चंद्रताल हैं (पौंग 2002 में, बाकी दो 2005 में घोषित)।"]),
    q(0, F, "forests-wildlife", "M", 0,
      ["Growing trees together with crops on the same land is called:", ["Agroforestry", "Monoculture", "Shifting cultivation", "Afforestation"], "Agroforestry integrates trees with crops and/or livestock on farmland."],
      ["एक ही भूमि पर फ़सलों के साथ पेड़ उगाना कहलाता है:", ["कृषि-वानिकी", "एकल-कृषि", "झूम खेती", "वनारोपण"], "कृषि-वानिकी में खेत पर पेड़ों को फ़सलों और/या पशुपालन के साथ जोड़ा जाता है।"]),
    q(0, F, "environment-ecology", "H", 3,
      ["The Montreal Protocol (1987) is an international agreement to:", ["Reduce carbon emissions", "Protect wetlands", "Control trade in endangered species", "Phase out ozone-depleting substances"], "Montreal Protocol targets CFCs and other ozone-depleting substances; Kyoto deals with greenhouse gases, Ramsar with wetlands, CITES with species trade."],
      ["मॉन्ट्रियल प्रोटोकॉल (1987) किस उद्देश्य का अंतरराष्ट्रीय समझौता है?", [ "कार्बन उत्सर्जन घटाना", "आर्द्रभूमियों की रक्षा", "संकटग्रस्त प्रजातियों के व्यापार पर नियंत्रण", "ओज़ोन क्षयकारी पदार्थों को चरणबद्ध रूप से समाप्त करना"], "मॉन्ट्रियल प्रोटोकॉल CFC आदि ओज़ोन क्षयकारी पदार्थों पर है; क्योटो हरितगृह गैसों, रामसर आर्द्रभूमियों और CITES प्रजाति-व्यापार पर है।"]),
    q(0, F, "forests-wildlife", "H", 1,
      ["Forest fires in the lower hills of Himachal Pradesh spread mainly in which season and through which fuel?", ["Monsoon, through oak leaves", "Pre-monsoon summer, through dry chir pine needles", "Winter, through deodar cones", "Autumn, through grass only"], "April–June is the fire season; the highly inflammable needle litter of chir pine carries surface fires."],
      ["हिमाचल प्रदेश की निचली पहाड़ियों में वनाग्नि मुख्यतः किस मौसम में और किस ईंधन से फैलती है?", ["मानसून में, बान के पत्तों से", "मानसून-पूर्व गर्मियों में, सूखी चीड़ की पत्तियों से", "सर्दियों में, देवदार के शंकुओं से", "शरद में, केवल घास से"], "अप्रैल–जून आग का मौसम है; चीड़ की अत्यंत ज्वलनशील पत्तियों (पिरूल) की परत से सतही आग फैलती है।"]),
    q(0, F, "environment-ecology", "M", 2,
      ["The variety of life forms in a region is called:", ["Ecosystem", "Habitat", "Biodiversity", "Niche"], "Biodiversity covers genetic, species and ecosystem diversity."],
      ["किसी क्षेत्र में जीवन-रूपों की विविधता कहलाती है:", ["पारितंत्र", "आवास", "जैव विविधता", "निकेत (निश)"], "जैव विविधता में आनुवंशिक, प्रजातीय और पारितंत्रीय विविधता शामिल है।"]),
    q(0, F, "forests-wildlife", "E", 0,
      ["The state animal of Himachal Pradesh is:", ["Snow leopard", "Musk deer", "Himalayan tahr", "Ibex"], "The snow leopard was made the state animal in 2007, replacing the musk deer."],
      ["हिमाचल प्रदेश का राज्य पशु है:", ["हिम तेंदुआ", "कस्तूरी मृग", "हिमालयी थार", "आइबेक्स"], "2007 में कस्तूरी मृग के स्थान पर हिम तेंदुए को राज्य पशु बनाया गया।"]),
    q(0, F, "forests-wildlife", "H", 3,
      ["Under the Wildlife (Protection) Act, the animals given the highest protection are listed in:", ["Schedule V", "Schedule IV", "Schedule III", "Schedule I"], "Schedule I lists species with absolute protection, e.g. tiger and snow leopard; the 2022 amendment rationalised the schedules to four, Schedule I still being the highest."],
      ["वन्यजीव (संरक्षण) अधिनियम के तहत सर्वोच्च संरक्षण वाले जीव किस अनुसूची में सूचीबद्ध हैं?", ["अनुसूची V", "अनुसूची IV", "अनुसूची III", "अनुसूची I"], "अनुसूची I में पूर्ण संरक्षण वाली प्रजातियाँ हैं, जैसे बाघ और हिम तेंदुआ; 2022 संशोधन ने अनुसूचियाँ घटाकर चार कीं, फिर भी अनुसूची I सर्वोच्च है।"]),
  ],
  [
    q(0, F, "forests-wildlife", "M", 2,
      ["The state flower of Himachal Pradesh is:", ["Lotus", "Rose", "Pink Rhododendron", "Marigold"], "Pink Rhododendron (Rhododendron campanulatum) is the state flower of Himachal Pradesh."],
      ["हिमाचल प्रदेश का राज्य पुष्प है:", ["कमल", "गुलाब", "गुलाबी बुरांस", "गेंदा"], "गुलाबी बुरांस (रोडोडेंड्रॉन कैंपैन्युलेटम) हिमाचल प्रदेश का राज्य पुष्प है।"]),
    q(0, F, "forests-wildlife", "H", 0,
      ["Kail, an important timber tree of Himachal, is also known as:", ["Blue pine", "Silver fir", "Spruce", "Chir pine"], "Kail is the Himalayan blue pine (Pinus wallichiana)."],
      ["हिमाचल का महत्वपूर्ण इमारती वृक्ष कैल किस नाम से भी जाना जाता है?", ["ब्लू पाइन", "सिल्वर फ़र", "स्प्रूस", "चीड़"], "कैल हिमालयी ब्लू पाइन (पाइनस वालिचियाना) है।"]),
    q(0, F, "forests-wildlife", "M", 1,
      ["The Forest (Conservation) Act, 1980 mainly requires:", [ "Planting of one tree per family", "Central government approval before forest land is diverted to non-forest use", "Ban on all grazing", "Free timber for villagers"], "Section 2 of the 1980 Act requires prior central approval for de-reservation or diversion of forest land."],
      ["वन (संरक्षण) अधिनियम, 1980 मुख्य रूप से क्या अनिवार्य करता है?", [ "हर परिवार द्वारा एक पेड़ लगाना", "वन भूमि को गैर-वन उपयोग में देने से पहले केंद्र सरकार की स्वीकृति", "हर प्रकार की चराई पर रोक", "ग्रामीणों को मुफ़्त लकड़ी"], "1980 अधिनियम की धारा 2 के अनुसार वन भूमि को अनारक्षित करने या मोड़ने के लिए केंद्र की पूर्व स्वीकृति आवश्यक है।"]),
    q(0, F, "environment-ecology", "H", 3,
      ["Which of these is a biotic component of an ecosystem?", ["Sunlight", "Temperature", "Soil minerals", "Fungi"], "Biotic components are living things (producers, consumers, decomposers such as fungi); sunlight, temperature and minerals are abiotic."],
      ["इनमें से कौन पारितंत्र का जैविक घटक है?", ["सूर्य का प्रकाश", "तापमान", "मिट्टी के खनिज", "कवक"], "जैविक घटक सजीव हैं (उत्पादक, उपभोक्ता, कवक जैसे अपघटक); सूर्य का प्रकाश, तापमान और खनिज अजैविक हैं।"]),
    q(0, F, "forests-wildlife", "H", 2,
      ["The Cold Desert Biosphere Reserve of Himachal Pradesh was declared in:", ["1999", "2005", "2009", "2014"], "The Cold Desert Biosphere Reserve covering Pin Valley NP, Kibber sanctuary and Chandratal area was declared in 2009; it joined UNESCO's network in 2018."],
      ["हिमाचल प्रदेश का शीत मरुस्थल जैवमंडल आरक्षित क्षेत्र कब घोषित हुआ?", ["1999", "2005", "2009", "2014"], "पिन वैली नेशनल पार्क, किब्बर अभयारण्य और चंद्रताल क्षेत्र को समेटता शीत मरुस्थल जैवमंडल आरक्षित क्षेत्र 2009 में घोषित हुआ; 2018 में यह यूनेस्को नेटवर्क में शामिल हुआ।"]),
    q(0, F, "forests-wildlife", "M", 0,
      ["Planting trees on land that was not forested before is called:", ["Afforestation", "Reforestation", "Deforestation", "Silviculture"], "Afforestation creates forest on previously non-forest land; reforestation replants where forest was lost."],
      ["उस भूमि पर पेड़ लगाना जहाँ पहले वन नहीं था, कहलाता है:", ["वनारोपण", "पुनर्वनीकरण", "वनोन्मूलन", "वनवर्धन"], "वनारोपण पहले से गैर-वन भूमि पर वन बनाता है; पुनर्वनीकरण वहाँ पेड़ लगाता है जहाँ वन नष्ट हुआ।"]),
    q(0, F, "forests-wildlife", "H", 1,
      ["Silviculture is the science of:", ["Rearing silkworms", "Establishing, growing and tending forest crops", "Growing fruit orchards", "Measuring the volume of trees"], "Silviculture deals with raising and managing forest stands; measuring trees is forest mensuration, silkworm rearing is sericulture."],
      ["वनवर्धन (सिल्वीकल्चर) किसका विज्ञान है?", ["रेशम कीट पालन", "वन फ़सलों को स्थापित करना, उगाना और उनकी देखभाल", "फलों के बाग़ लगाना", "पेड़ों का आयतन मापना"], "वनवर्धन वन-समूहों को उगाने और प्रबंधित करने से संबंधित है; पेड़ मापना वन-मापिकी और रेशम कीट पालन सेरीकल्चर है।"]),
    q(0, F, "environment-ecology", "M", 2,
      ["Acid rain is mainly caused by emissions of:", ["Carbon monoxide and methane", "Ozone and oxygen", "Sulphur dioxide and nitrogen oxides", "Chlorofluorocarbons"], "SO₂ and NOₓ form sulphuric and nitric acids in the atmosphere."],
      ["अम्लीय वर्षा मुख्यतः किनके उत्सर्जन से होती है?", ["कार्बन मोनोऑक्साइड और मीथेन", "ओज़ोन और ऑक्सीजन", "सल्फ़र डाइऑक्साइड और नाइट्रोजन ऑक्साइड", "क्लोरोफ़्लोरोकार्बन"], "SO₂ और NOₓ वायुमंडल में सल्फ़्यूरिक और नाइट्रिक अम्ल बनाते हैं।"]),
    q(0, F, "forests-wildlife", "M", 3,
      ["Musk deer is hunted illegally mainly for:", ["Its horns", "Its hide", "Its meat", "The musk pod of the male"], "The musk gland of the male is valued in perfumes and medicine, driving poaching."],
      ["कस्तूरी मृग का अवैध शिकार मुख्यतः किसके लिए होता है?", ["उसके सींग", "उसकी खाल", "उसका मांस", "नर की कस्तूरी ग्रंथि"], "नर की कस्तूरी ग्रंथि इत्र और औषधि में मूल्यवान है, जिससे अवैध शिकार होता है।"]),
    q(0, F, "environment-ecology", "H", 0,
      ["The Paris Agreement (2015) aims to keep the global temperature rise this century well below:", ["2 °C above pre-industrial levels", "1 °C above 1990 levels", "3 °C above present levels", "0.5 °C above pre-industrial levels"], "Paris goal: well below 2 °C above pre-industrial levels, pursuing efforts to limit it to 1.5 °C."],
      ["पेरिस समझौता (2015) इस सदी में वैश्विक तापवृद्धि को किससे काफ़ी नीचे रखने का लक्ष्य रखता है?", ["पूर्व-औद्योगिक स्तर से 2 °C", "1990 स्तर से 1 °C", "वर्तमान स्तर से 3 °C", "पूर्व-औद्योगिक स्तर से 0.5 °C"], "पेरिस लक्ष्य: पूर्व-औद्योगिक स्तर से 2 °C से काफ़ी नीचे, और 1.5 °C तक सीमित रखने का प्रयास।"]),
    q(0, F, "forests-wildlife", "M", 1,
      ["The Western Tragopan is bred in captivity at the pheasantry of:", ["Manali", "Sarahan", "Dalhousie", "Palampur"], "The Sarahan Pheasantry in Shimla district runs the conservation breeding programme for the Western Tragopan."],
      ["पश्चिमी ट्रैगोपैन का कैप्टिव प्रजनन किस तीतर-प्रजनन केंद्र में होता है?", ["मनाली", "सराहन", "डलहौज़ी", "पालमपुर"], "शिमला ज़िले का सराहन फ़ेज़ेंटरी पश्चिमी ट्रैगोपैन का संरक्षण-प्रजनन कार्यक्रम चलाता है।"]),
    q(0, F, "environment-ecology", "M", 3,
      ["A species found naturally in only one particular region is called:", ["Exotic", "Extinct", "Migratory", "Endemic"], "Endemic species are restricted to a specific area; exotic species are introduced from elsewhere."],
      ["जो प्रजाति प्राकृतिक रूप से केवल एक विशेष क्षेत्र में पाई जाती है, कहलाती है:", ["विदेशी", "विलुप्त", "प्रवासी", "स्थानिक"], "स्थानिक प्रजातियाँ एक विशेष क्षेत्र तक सीमित होती हैं; विदेशी प्रजातियाँ बाहर से लाई जाती हैं।"]),
    q(0, F, "forests-wildlife", "H", 2,
      ["Which of these is NOT a national park of Himachal Pradesh?", ["Inderkilla", "Simbalbara", "Kalatop-Khajjiar", "Khirganga"], "Kalatop-Khajjiar in Chamba is a wildlife sanctuary. The national parks are Great Himalayan, Pin Valley, Inderkilla, Khirganga and Simbalbara."],
      ["इनमें से कौन हिमाचल प्रदेश का राष्ट्रीय उद्यान नहीं है?", ["इंद्रकिला", "सिंबलबाड़ा", "कालाटोप-खज्जियार", "खीरगंगा"], "चंबा का कालाटोप-खज्जियार वन्यजीव अभयारण्य है। राष्ट्रीय उद्यान: ग्रेट हिमालयन, पिन वैली, इंद्रकिला, खीरगंगा और सिंबलबाड़ा।"]),
    q(0, F, "environment-ecology", "H", 1,
      ["Biological magnification means that:", [ "Organisms grow larger over generations", "Concentration of non-biodegradable toxins like DDT increases at higher trophic levels", "Population of top predators increases", "Biodiversity increases with altitude"], "Persistent chemicals accumulate in tissues and concentrate up the food chain, harming top predators."],
      ["जैव आवर्धन का अर्थ है कि:", [ "पीढ़ियों के साथ जीव बड़े होते जाते हैं", "DDT जैसे अजैव-निम्नीकरणीय विषों की सांद्रता ऊँचे पोषी स्तरों पर बढ़ती है", "शीर्ष शिकारियों की संख्या बढ़ती है", "ऊँचाई के साथ जैव विविधता बढ़ती है"], "स्थायी रसायन ऊतकों में जमा होकर आहार शृंखला में ऊपर की ओर सांद्र होते हैं और शीर्ष शिकारियों को हानि पहुँचाते हैं।"]),
    q(0, F, "forests-wildlife", "M", 0,
      ["Joint Forest Management (JFM) involves:", [ "Forest department and local communities managing forests together", "Only private companies managing forests", "Only the army guarding forests", "Converting forests into farms"], "JFM (from the 1990 guidelines) shares forest protection duties and benefits with village forest committees."],
      ["संयुक्त वन प्रबंधन (JFM) में क्या शामिल है?", [ "वन विभाग और स्थानीय समुदायों का मिलकर वन प्रबंधन", "केवल निजी कंपनियों द्वारा वन प्रबंधन", "केवल सेना द्वारा वनों की रक्षा", "वनों को खेतों में बदलना"], "JFM (1990 के दिशानिर्देशों से) ग्राम वन समितियों के साथ वन-संरक्षण के कर्तव्य और लाभ बाँटता है।"]),
    q(0, F, "environment-ecology", "M", 2,
      ["World Environment Day is observed every year on:", ["22 April", "21 March", "5 June", "16 September"], "5 June is World Environment Day; 22 April Earth Day; 21 March International Day of Forests; 16 September Ozone Day."],
      ["विश्व पर्यावरण दिवस हर वर्ष कब मनाया जाता है?", ["22 अप्रैल", "21 मार्च", "5 जून", "16 सितंबर"], "5 जून विश्व पर्यावरण दिवस; 22 अप्रैल पृथ्वी दिवस; 21 मार्च अंतरराष्ट्रीय वन दिवस; 16 सितंबर ओज़ोन दिवस।"]),
    q(0, F, "forests-wildlife", "H", 3,
      ["Under the Indian Forest Act, 1927, the category of forest with the most restrictions on public rights is:", ["Village forest", "Protected forest", "Unclassed forest", "Reserved forest"], "In reserved forests most activities are prohibited unless permitted; protected forests allow activities unless prohibited."],
      ["भारतीय वन अधिनियम, 1927 के तहत जन-अधिकारों पर सबसे अधिक प्रतिबंध वाली वन श्रेणी है:", ["ग्राम वन", "संरक्षित वन", "अवर्गीकृत वन", "आरक्षित वन"], "आरक्षित वनों में अधिकांश गतिविधियाँ अनुमति के बिना वर्जित हैं; संरक्षित वनों में गतिविधियाँ तब तक अनुमत हैं जब तक वर्जित न हों।"]),
    q(0, F, "environment-ecology", "E", 1,
      ["Which of these is a renewable resource?", ["Coal", "Forest", "Petroleum", "Natural gas"], "Forests can regenerate if managed sustainably; fossil fuels cannot be replaced on a human time scale."],
      ["इनमें से कौन नवीकरणीय संसाधन है?", ["कोयला", "वन", "पेट्रोलियम", "प्राकृतिक गैस"], "सतत प्रबंधन से वन पुनः उग सकते हैं; जीवाश्म ईंधन मानवीय समय-सीमा में फिर नहीं बनते।"]),
    q(0, F, "forests-wildlife", "M", 2,
      ["Ban oak, important for fodder and water conservation in Himachal, belongs to the genus:", ["Pinus", "Cedrus", "Quercus", "Abies"], "Ban oak is Quercus leucotrichophora; oak forests protect springs and supply fodder and fuel."],
      ["हिमाचल में चारे और जल संरक्षण के लिए महत्वपूर्ण बान ओक किस वंश का है?", ["पाइनस", "सेड्रस", "क्वेरकस", "एबीज़"], "बान ओक क्वेरकस ल्यूकोट्राइकोफ़ोरा है; बान के वन जल-स्रोतों की रक्षा करते हैं और चारा व ईंधन देते हैं।"]),
  ],
];
