// HP Police Sub-Inspector — Law & Police Procedure, 15 fresh questions for each of the two full mocks.
// Written for the 2023 criminal laws (BNS, BNSS, BSA) in force since 1 July 2024.

import { q, type PatwariQuestion } from "../../patwari/types";

const L = "law";

export const law: PatwariQuestion[][] = [
  [
    q(0, L, "criminal-law", "M", 2,
      ["The Bharatiya Nyaya Sanhita, 2023 replaced which law?", ["Code of Criminal Procedure, 1973", "Indian Evidence Act, 1872", "Indian Penal Code, 1860", "Police Act, 1861"], "BNS replaced the IPC; BNSS replaced the CrPC; the Bharatiya Sakshya Adhiniyam replaced the Evidence Act."],
      ["भारतीय न्याय संहिता, 2023 ने किस क़ानून का स्थान लिया?", ["दंड प्रक्रिया संहिता, 1973", "भारतीय साक्ष्य अधिनियम, 1872", "भारतीय दंड संहिता, 1860", "पुलिस अधिनियम, 1861"], "BNS ने IPC का, BNSS ने CrPC का और भारतीय साक्ष्य अधिनियम ने साक्ष्य अधिनियम का स्थान लिया।"]),
    q(0, L, "criminal-law", "M", 0,
      ["The three new criminal laws came into force on:", ["1 July 2024", "1 January 2024", "26 January 2024", "15 August 2023"], "BNS, BNSS and BSA were notified to come into force from 1 July 2024."],
      ["तीनों नए आपराधिक क़ानून कब लागू हुए?", ["1 जुलाई 2024", "1 जनवरी 2024", "26 जनवरी 2024", "15 अगस्त 2023"], "BNS, BNSS और BSA 1 जुलाई 2024 से लागू होने के लिए अधिसूचित हुए।"]),
    q(0, L, "constitution", "M", 1,
      ["Under Article 22(2) of the Constitution, an arrested person must be produced before the nearest magistrate within:", ["12 hours", "24 hours, excluding travel time", "48 hours", "72 hours"], "Article 22(2) (and BNSS section 58) require production within 24 hours, excluding the journey time."],
      ["संविधान के अनुच्छेद 22(2) के तहत गिरफ़्तार व्यक्ति को निकटतम मजिस्ट्रेट के सामने कितने समय में पेश करना होता है?", ["12 घंटे", "24 घंटे, यात्रा का समय छोड़कर", "48 घंटे", "72 घंटे"], "अनुच्छेद 22(2) (और BNSS धारा 58) के अनुसार यात्रा का समय छोड़कर 24 घंटे के भीतर पेश करना आवश्यक है।"]),
    q(0, L, "criminal-law", "H", 3,
      ["A 'Zero FIR' means an FIR that:", [ "Is closed with no action", "Records an offence with zero punishment", "Is filed only online", "Can be registered at any police station regardless of where the offence occurred"], "BNSS section 173 lets information be recorded irrespective of jurisdiction; the FIR is then transferred to the competent police station."],
      ["'ज़ीरो FIR' का अर्थ वह FIR है जो:", [ "बिना कार्रवाई के बंद कर दी जाए", "शून्य दंड वाले अपराध को दर्ज करे", "केवल ऑनलाइन दर्ज हो", "अपराध कहीं भी हुआ हो, किसी भी थाने में दर्ज की जा सकती है"], "BNSS धारा 173 के तहत क्षेत्राधिकार की परवाह किए बिना सूचना दर्ज की जा सकती है; फिर FIR सक्षम थाने को भेजी जाती है।"]),
    q(0, L, "criminal-law", "M", 2,
      ["A cognizable offence is one in which the police:", ["Need a court warrant to arrest", "Cannot investigate at all", "Can arrest without a warrant", "Can only issue a summons"], "In cognizable offences police may register an FIR, investigate and arrest without a warrant."],
      ["संज्ञेय अपराध वह है जिसमें पुलिस:", ["गिरफ़्तारी के लिए न्यायालय के वारंट की ज़रूरत रखती है", "जाँच बिल्कुल नहीं कर सकती", "बिना वारंट गिरफ़्तार कर सकती है", "केवल समन जारी कर सकती है"], "संज्ञेय अपराधों में पुलिस FIR दर्ज कर, जाँच कर और बिना वारंट गिरफ़्तार कर सकती है।"]),
    q(0, L, "criminal-law", "H", 0,
      ["Which new form of punishment was introduced for certain petty offences by the BNS, 2023?", ["Community service", "Exile", "Forfeiture of all property", "Public flogging"], "Section 4(f) of BNS adds community service as a punishment, e.g. for some petty offences."],
      ["भारतीय न्याय संहिता, 2023 ने कुछ छोटे अपराधों के लिए कौन-सा नया दंड जोड़ा?", ["सामुदायिक सेवा", "देश निकाला", "सारी संपत्ति की ज़ब्ती", "सार्वजनिक कोड़े"], "BNS की धारा 4(f) सामुदायिक सेवा को दंड के रूप में जोड़ती है, जैसे कुछ छोटे अपराधों के लिए।"]),
    q(0, L, "criminal-law", "H", 1,
      ["Under the BNSS, forensic experts must visit the crime scene for offences punishable with imprisonment of:", ["Any term", "Seven years or more", "Ten years or more", "Life imprisonment only"], "BNSS section 176(3) makes forensic collection at the scene mandatory for offences punishable with seven years or more."],
      ["BNSS के तहत किन अपराधों में फ़ॉरेंसिक विशेषज्ञों का घटनास्थल पर जाना अनिवार्य है?", ["किसी भी अवधि के दंड वाले", "सात वर्ष या अधिक के कारावास वाले", "दस वर्ष या अधिक के कारावास वाले", "केवल आजीवन कारावास वाले"], "BNSS धारा 176(3) सात वर्ष या अधिक दंड वाले अपराधों में घटनास्थल से फ़ॉरेंसिक साक्ष्य संग्रह अनिवार्य करती है।"]),
    q(0, L, "constitution", "M", 3,
      ["'No person accused of any offence shall be compelled to be a witness against himself' is provided in:", ["Article 21", "Article 14", "Article 19", "Article 20(3)"], "Article 20(3) protects against self-incrimination."],
      ["'किसी अपराध के अभियुक्त को स्वयं के विरुद्ध गवाह बनने के लिए बाध्य नहीं किया जाएगा' — यह किस अनुच्छेद में है?", ["अनुच्छेद 21", "अनुच्छेद 14", "अनुच्छेद 19", "अनुच्छेद 20(3)"], "अनुच्छेद 20(3) आत्म-अभिशंसन से संरक्षण देता है।"]),
    q(0, L, "civil-law", "H", 2,
      ["Under the Bharatiya Sakshya Adhiniyam, a confession made to a police officer is:", ["Fully admissible", "Admissible if written", "Not admissible against the accused", "Admissible only in murder cases"], "As under the old section 25 of the Evidence Act, a confession to a police officer cannot be proved against the accused (BSA section 23)."],
      ["भारतीय साक्ष्य अधिनियम के तहत पुलिस अधिकारी के सामने की गई संस्वीकृति (कन्फ़ेशन):", ["पूर्णतः ग्राह्य है", "लिखित होने पर ग्राह्य है", "अभियुक्त के विरुद्ध ग्राह्य नहीं है", "केवल हत्या के मामलों में ग्राह्य है"], "पुराने साक्ष्य अधिनियम की धारा 25 की तरह, पुलिस अधिकारी के सामने की गई संस्वीकृति अभियुक्त के विरुद्ध सिद्ध नहीं की जा सकती (BSA धारा 23)।"]),
    q(0, L, "constitution", "M", 0,
      ["The writ issued to produce a detained person before the court is:", ["Habeas corpus", "Mandamus", "Certiorari", "Quo warranto"], "Habeas corpus ('you may have the body') checks unlawful detention."],
      ["हिरासत में लिए गए व्यक्ति को न्यायालय के समक्ष प्रस्तुत करने के लिए जारी रिट है:", ["बंदी प्रत्यक्षीकरण", "परमादेश", "उत्प्रेषण", "अधिकार पृच्छा"], "बंदी प्रत्यक्षीकरण ('शरीर प्रस्तुत करो') अवैध हिरासत पर रोक लगाता है।"]),
    q(0, L, "criminal-law", "H", 1,
      ["Under the Juvenile Justice (Care and Protection of Children) Act, 2015, a juvenile aged 16–18 accused of a heinous offence:", [ "Is always tried as an adult", "May be tried as an adult after a preliminary assessment by the Juvenile Justice Board", "Cannot be tried at all", "Is sent directly to prison"], "Section 15 of the JJ Act allows the Board to assess and transfer such a child to the Children's Court for trial as an adult."],
      ["किशोर न्याय (बालकों की देखरेख और संरक्षण) अधिनियम, 2015 के तहत जघन्य अपराध का आरोपी 16–18 वर्ष का किशोर:", [ "हमेशा वयस्क की तरह विचारित होता है", "किशोर न्याय बोर्ड के प्रारंभिक आकलन के बाद वयस्क की तरह विचारित हो सकता है", "उस पर मुकदमा चल ही नहीं सकता", "सीधे जेल भेजा जाता है"], "JJ अधिनियम की धारा 15 बोर्ड को आकलन कर ऐसे बालक को वयस्क के रूप में विचारण हेतु बाल न्यायालय भेजने की अनुमति देती है।"]),
    q(0, L, "criminal-law", "M", 3,
      ["The POCSO Act, 2012 protects children below the age of:", ["14 years", "16 years", "21 years", "18 years"], "The Protection of Children from Sexual Offences Act defines a child as anyone below 18."],
      ["पॉक्सो अधिनियम, 2012 किस आयु से कम के बच्चों की रक्षा करता है?", ["14 वर्ष", "16 वर्ष", "21 वर्ष", "18 वर्ष"], "लैंगिक अपराधों से बालकों का संरक्षण अधिनियम 18 वर्ष से कम आयु के किसी भी व्यक्ति को बालक मानता है।"]),
    q(0, L, "constitution", "H", 2,
      ["'Police' and 'Public order' are subjects in the:", ["Union List", "Concurrent List", "State List", "Residuary powers"], "Entries 1 (public order) and 2 (police) are in List II, the State List, of the Seventh Schedule."],
      ["'पुलिस' और 'लोक व्यवस्था' किस सूची के विषय हैं?", ["संघ सूची", "समवर्ती सूची", "राज्य सूची", "अवशिष्ट शक्तियाँ"], "सातवीं अनुसूची की सूची II (राज्य सूची) की प्रविष्टि 1 (लोक व्यवस्था) और 2 (पुलिस) हैं।"]),
    q(0, L, "criminal-law", "M", 1,
      ["The Supreme Court laid down guidelines on the rights of arrested persons (memo of arrest, informing a relative) in:", ["Maneka Gandhi v Union of India", "D.K. Basu v State of West Bengal", "Kesavananda Bharati v State of Kerala", "Vishaka v State of Rajasthan"], "D.K. Basu (1997) set out arrest and detention safeguards, later reflected in the CrPC and BNSS."],
      ["सर्वोच्च न्यायालय ने गिरफ़्तार व्यक्तियों के अधिकारों (गिरफ़्तारी ज्ञापन, रिश्तेदार को सूचना) पर दिशानिर्देश किस मामले में दिए?", ["मेनका गांधी बनाम भारत संघ", "डी.के. बसु बनाम पश्चिम बंगाल राज्य", "केशवानंद भारती बनाम केरल राज्य", "विशाखा बनाम राजस्थान राज्य"], "डी.के. बसु (1997) में गिरफ़्तारी और हिरासत के सुरक्षा उपाय तय हुए, जो बाद में CrPC और BNSS में शामिल हुए।"]),
    q(0, L, "civil-law", "M", 0,
      ["A statement made by a person about the cause of his death, who has since died, is known as:", ["Dying declaration", "Confession", "Hearsay statement", "Admission by conduct"], "A dying declaration is relevant evidence as an exception to the hearsay rule (old IEA section 32(1), now BSA section 26)."],
      ["मृत्यु से पहले व्यक्ति द्वारा अपनी मृत्यु के कारण के बारे में दिया गया कथन कहलाता है:", ["मृत्युकालिक कथन", "संस्वीकृति", "अनुश्रुत कथन", "आचरण द्वारा स्वीकृति"], "मृत्युकालिक कथन अनुश्रुत नियम का अपवाद होकर सुसंगत साक्ष्य है (पुरानी IEA धारा 32(1), अब BSA धारा 26)।"]),
  ],
  [
    q(0, L, "criminal-law", "M", 1,
      ["The Bharatiya Nagarik Suraksha Sanhita, 2023 replaced:", ["Indian Penal Code", "Code of Criminal Procedure, 1973", "Indian Evidence Act", "Arms Act"], "BNSS is the new procedural code in place of the CrPC."],
      ["भारतीय नागरिक सुरक्षा संहिता, 2023 ने किसका स्थान लिया?", ["भारतीय दंड संहिता", "दंड प्रक्रिया संहिता, 1973", "भारतीय साक्ष्य अधिनियम", "आयुध अधिनियम"], "BNSS, CrPC के स्थान पर नई प्रक्रिया संहिता है।"]),
    q(0, L, "criminal-law", "H", 3,
      ["Which offence under the old IPC was dropped by name in the BNS and replaced by a provision on acts endangering the sovereignty, unity and integrity of India?", ["Defamation", "Criminal conspiracy", "Dacoity", "Sedition"], "IPC section 124A (sedition) has no counterpart by that name; BNS section 152 deals with acts endangering sovereignty, unity and integrity."],
      ["पुराने IPC का कौन-सा अपराध BNS में नाम से हटा दिया गया और उसकी जगह भारत की संप्रभुता, एकता और अखंडता को ख़तरे में डालने वाले कृत्यों का प्रावधान आया?", ["मानहानि", "आपराधिक षड्यंत्र", "डकैती", "राजद्रोह"], "IPC धारा 124A (राजद्रोह) का उस नाम से कोई समकक्ष नहीं है; BNS धारा 152 संप्रभुता, एकता और अखंडता को ख़तरे में डालने वाले कृत्यों से संबंधित है।"]),
    q(0, L, "criminal-law", "M", 0,
      ["In a bailable offence, bail is:", ["A right of the accused", "At the full discretion of police", "Never granted", "Granted only by the High Court"], "For bailable offences the accused is entitled to be released on bail (BNSS section 478)."],
      ["ज़मानती अपराध में ज़मानत:", ["अभियुक्त का अधिकार है", "पूरी तरह पुलिस के विवेक पर है", "कभी नहीं मिलती", "केवल उच्च न्यायालय देता है"], "ज़मानती अपराधों में अभियुक्त ज़मानत पर रिहा होने का हक़दार है (BNSS धारा 478)।"]),
    q(0, L, "criminal-law", "H", 2,
      ["Under the BNS, nothing is an offence which is done by a child under the age of:", ["5 years", "10 years", "7 years", "12 years"], "Like IPC section 82, BNS section 20 gives absolute immunity to children below 7; those 7–12 get qualified immunity if immature."],
      ["BNS के तहत किस आयु से कम के बच्चे द्वारा किया गया कोई कार्य अपराध नहीं है?", ["5 वर्ष", "10 वर्ष", "7 वर्ष", "12 वर्ष"], "IPC धारा 82 की तरह, BNS धारा 20 सात वर्ष से कम के बच्चों को पूर्ण उन्मुक्ति देती है; 7–12 वर्ष वालों को अपरिपक्वता पर सीमित उन्मुक्ति।"]),
    q(0, L, "constitution", "M", 3,
      ["Which Article guarantees protection of life and personal liberty?", ["Article 14", "Article 19", "Article 32", "Article 21"], "Article 21: no person shall be deprived of life or personal liberty except according to procedure established by law."],
      ["कौन-सा अनुच्छेद प्राण और दैहिक स्वतंत्रता के संरक्षण की गारंटी देता है?", ["अनुच्छेद 14", "अनुच्छेद 19", "अनुच्छेद 32", "अनुच्छेद 21"], "अनुच्छेद 21: किसी व्यक्ति को विधि द्वारा स्थापित प्रक्रिया के अनुसार ही प्राण या दैहिक स्वतंत्रता से वंचित किया जाएगा।"]),
    q(0, L, "criminal-law", "H", 0,
      ["Which act was specifically made an offence in the BNS, 2023 that had no separate section in the IPC?", ["Snatching", "Theft", "Robbery", "Extortion"], "BNS section 304 makes snatching a distinct offence; theft, robbery and extortion existed in the IPC."],
      ["BNS, 2023 में किस कृत्य को विशेष रूप से अपराध बनाया गया जिसकी IPC में अलग धारा नहीं थी?", ["झपटमारी (स्नैचिंग)", "चोरी", "लूट", "उद्दापन"], "BNS धारा 304 झपटमारी को अलग अपराध बनाती है; चोरी, लूट और उद्दापन IPC में पहले से थे।"]),
    q(0, L, "criminal-law", "M", 2,
      ["The inquiry by police into the apparent cause of an unnatural death, prepared in the presence of witnesses, is called:", ["Charge sheet", "Case diary", "Inquest report", "Remand"], "Police hold an inquest (old CrPC section 174, now BNSS section 194) and prepare an inquest report."],
      ["अप्राकृतिक मृत्यु के प्रत्यक्ष कारण की पुलिस द्वारा गवाहों की उपस्थिति में की गई जाँच कहलाती है:", ["आरोप-पत्र", "केस डायरी", "मृत्यु-समीक्षा (इनक्वेस्ट) रिपोर्ट", "रिमांड"], "पुलिस मृत्यु-समीक्षा करती है (पुरानी CrPC धारा 174, अब BNSS धारा 194) और इनक्वेस्ट रिपोर्ट बनाती है।"]),
    q(0, L, "civil-law", "H", 1,
      ["Under the Bharatiya Sakshya Adhiniyam, 2023, electronic and digital records:", [ "Are not admissible", "Have the same legal effect as paper documents and are covered within 'document'", "Need a High Court order", "Are admissible only in civil cases"], "BSA expands the definition of 'document' to include electronic and digital records, which can be primary evidence."],
      ["भारतीय साक्ष्य अधिनियम, 2023 के तहत इलेक्ट्रॉनिक और डिजिटल अभिलेख:", [ "ग्राह्य नहीं हैं", "काग़ज़ी दस्तावेज़ों जैसा विधिक प्रभाव रखते हैं और 'दस्तावेज़' में शामिल हैं", "उच्च न्यायालय के आदेश की ज़रूरत रखते हैं", "केवल दीवानी मामलों में ग्राह्य हैं"], "BSA 'दस्तावेज़' की परिभाषा में इलेक्ट्रॉनिक और डिजिटल अभिलेख जोड़ता है, जो प्राथमिक साक्ष्य हो सकते हैं।"]),
    q(0, L, "criminal-law", "M", 3,
      ["The NDPS Act, enacted in 1985, deals with:", ["Arms and ammunition", "Dowry", "Cyber crime", "Narcotic drugs and psychotropic substances"], "The Narcotic Drugs and Psychotropic Substances Act, 1985 controls drug trafficking and abuse."],
      ["1985 में बना NDPS अधिनियम किससे संबंधित है?", ["हथियार और गोला-बारूद", "दहेज", "साइबर अपराध", "स्वापक औषधि और मनःप्रभावी पदार्थ"], "स्वापक औषधि और मनःप्रभावी पदार्थ अधिनियम, 1985 नशीली दवाओं की तस्करी और दुरुपयोग को नियंत्रित करता है।"]),
    q(0, L, "criminal-law", "H", 0,
      ["The right of private defence of the body extends to causing death in which situation?", [ "When there is reasonable apprehension of death or grievous hurt", "In any theft at night", "Whenever the attacker is unarmed", "Only when a police officer is present"], "Private defence may extend to causing death against assaults reasonably causing apprehension of death or grievous hurt (old IPC s.100, now BNS s.38)."],
      ["शरीर की निजी प्रतिरक्षा का अधिकार किस स्थिति में मृत्यु कारित करने तक विस्तृत होता है?", ["जब मृत्यु या घोर उपहति की युक्तियुक्त आशंका हो", "रात में किसी भी चोरी में", "जब भी हमलावर निहत्था हो", "केवल पुलिस अधिकारी की उपस्थिति में"], "मृत्यु या घोर उपहति की युक्तियुक्त आशंका उत्पन्न करने वाले हमले के विरुद्ध निजी प्रतिरक्षा मृत्यु कारित करने तक जा सकती है (पुरानी IPC धारा 100, अब BNS धारा 38)।"]),
    q(0, L, "criminal-law", "M", 1,
      ["The Information Technology Act, under which many cyber crimes are prosecuted, was enacted in:", ["1995", "2000", "2008", "2012"], "The IT Act was passed in 2000 and substantially amended in 2008."],
      ["सूचना प्रौद्योगिकी अधिनियम, जिसके तहत कई साइबर अपराधों पर मुकदमा चलता है, कब बना?", ["1995", "2000", "2008", "2012"], "आईटी अधिनियम 2000 में पारित हुआ और 2008 में व्यापक संशोधन हुआ।"]),
    q(0, L, "criminal-law", "H", 3,
      ["A non-cognizable offence is reported at a police station. The officer should:", [ "Arrest the accused at once", "Register an FIR and investigate without any order", "Refuse to record anything", "Enter it in the station register and refer the informant to the Magistrate"], "For non-cognizable cases the substance is entered in a register and the informant is referred to the Magistrate; investigation needs the Magistrate's order (BNSS section 174)."],
      ["थाने में असंज्ञेय अपराध की सूचना दी जाती है। अधिकारी को क्या करना चाहिए?", [ "तुरंत अभियुक्त को गिरफ़्तार करना", "बिना आदेश FIR दर्ज कर जाँच करना", "कुछ भी दर्ज करने से मना करना", "उसे थाने के रजिस्टर में दर्ज कर सूचनादाता को मजिस्ट्रेट के पास भेजना"], "असंज्ञेय मामलों में सार रजिस्टर में दर्ज कर सूचनादाता को मजिस्ट्रेट के पास भेजा जाता है; जाँच के लिए मजिस्ट्रेट का आदेश चाहिए (BNSS धारा 174)।"]),
    q(0, L, "constitution", "M", 2,
      ["Which Article of the Constitution is called the 'heart and soul' of the Constitution by Dr B.R. Ambedkar?", ["Article 14", "Article 19", "Article 32", "Article 368"], "Article 32, the right to constitutional remedies, was described by Ambedkar as the heart and soul of the Constitution."],
      ["डॉ. बी.आर. आंबेडकर ने संविधान के किस अनुच्छेद को संविधान का 'हृदय और आत्मा' कहा?", ["अनुच्छेद 14", "अनुच्छेद 19", "अनुच्छेद 32", "अनुच्छेद 368"], "आंबेडकर ने संवैधानिक उपचारों के अधिकार वाले अनुच्छेद 32 को संविधान का हृदय और आत्मा कहा।"]),
    q(0, L, "criminal-law", "M", 0,
      ["The Himachal Pradesh Police Act, which replaced the Police Act of 1861 in the state, was enacted in:", ["2007", "1971", "1995", "2015"], "Himachal Pradesh enacted its own Police Act in 2007 following the Prakash Singh judgment (2006) on police reforms."],
      ["राज्य में पुलिस अधिनियम 1861 का स्थान लेने वाला हिमाचल प्रदेश पुलिस अधिनियम कब बना?", ["2007", "1971", "1995", "2015"], "प्रकाश सिंह निर्णय (2006) के बाद पुलिस सुधारों के तहत हिमाचल प्रदेश ने 2007 में अपना पुलिस अधिनियम बनाया।"]),
    q(0, L, "civil-law", "H", 2,
      ["A witness who is hostile to the party calling him may be cross-examined by that party with the permission of:", ["The police", "The opposing lawyer", "The court", "The victim"], "The court may permit the party calling a witness to put questions as in cross-examination (old IEA s.154, now BSA s.157)."],
      ["बुलाने वाले पक्ष के प्रति पक्षद्रोही गवाह से वह पक्ष किसकी अनुमति से प्रतिपरीक्षा कर सकता है?", ["पुलिस", "विपक्षी वकील", "न्यायालय", "पीड़ित"], "न्यायालय गवाह बुलाने वाले पक्ष को प्रतिपरीक्षा की तरह प्रश्न पूछने की अनुमति दे सकता है (पुरानी IEA धारा 154, अब BSA धारा 157)।"]),
  ],
];
