// HPRCA JOA Library — Library & Information Science, 30 fresh questions for each of the two full mocks.

import { q, type PatwariQuestion } from "../../patwari/types";

const LS = "library-science";

export const libraryScience: PatwariQuestion[][] = [
  [
    q(0, LS, "foundations", "M", 1,
      ["S.R. Ranganathan formulated the Five Laws of Library Science in:", ["1924", "1931", "1948", "1957"], "Ranganathan published 'The Five Laws of Library Science' in 1931."],
      ["एस.आर. रंगनाथन ने पुस्तकालय विज्ञान के पाँच सूत्र कब प्रतिपादित किए?", ["1924", "1931", "1948", "1957"], "रंगनाथन ने 1931 में 'द फ़ाइव लॉज़ ऑफ़ लाइब्रेरी साइंस' प्रकाशित की।"]),
    q(0, LS, "foundations", "M", 3,
      ["Which is the fifth law of library science?", ["Books are for use", "Every reader his or her book", "Save the time of the reader", "The library is a growing organism"], "The laws in order: books are for use; every reader his/her book; every book its reader; save the time of the reader; the library is a growing organism."],
      ["पुस्तकालय विज्ञान का पाँचवाँ सूत्र कौन-सा है?", ["पुस्तकें उपयोग के लिए हैं", "प्रत्येक पाठक को उसकी पुस्तक", "पाठक का समय बचाओ", "पुस्तकालय एक वर्धनशील संस्था है"], "क्रम से सूत्र: पुस्तकें उपयोग के लिए हैं; प्रत्येक पाठक को उसकी पुस्तक; प्रत्येक पुस्तक को उसका पाठक; पाठक का समय बचाओ; पुस्तकालय एक वर्धनशील संस्था है।"]),
    q(0, LS, "classification", "H", 2,
      ["In the Dewey Decimal Classification, the main class 500 stands for:", ["Social sciences", "Technology", "Natural sciences and mathematics", "Arts and recreation"], "DDC main classes: 000 general works/computer science, 100 philosophy, 200 religion, 300 social sciences, 400 language, 500 science, 600 technology, 700 arts, 800 literature, 900 history & geography."],
      ["ड्यूई दशमलव वर्गीकरण में मुख्य वर्ग 500 किसका है?", ["सामाजिक विज्ञान", "प्रौद्योगिकी", "प्राकृतिक विज्ञान और गणित", "कला और मनोरंजन"], "DDC मुख्य वर्ग: 000 सामान्य कृतियाँ/कंप्यूटर विज्ञान, 100 दर्शन, 200 धर्म, 300 सामाजिक विज्ञान, 400 भाषा, 500 विज्ञान, 600 प्रौद्योगिकी, 700 कला, 800 साहित्य, 900 इतिहास व भूगोल।"]),
    q(0, LS, "classification", "M", 0,
      ["The Dewey Decimal Classification was first published in:", ["1876", "1895", "1905", "1933"], "Melvil Dewey published DDC anonymously in 1876."],
      ["ड्यूई दशमलव वर्गीकरण पहली बार कब प्रकाशित हुआ?", ["1876", "1895", "1905", "1933"], "मेल्विल ड्यूई ने 1876 में DDC गुमनाम रूप से प्रकाशित किया।"]),
    q(0, LS, "classification", "H", 3,
      ["Ranganathan's fundamental categories in Colon Classification are expressed by the formula:", ["AACR", "SLIS", "MARC", "PMEST"], "PMEST: Personality, Matter, Energy, Space, Time."],
      ["कोलन वर्गीकरण में रंगनाथन की मूलभूत श्रेणियाँ किस सूत्र से व्यक्त होती हैं?", ["AACR", "SLIS", "MARC", "PMEST"], "PMEST: व्यक्तित्व (Personality), पदार्थ (Matter), ऊर्जा (Energy), स्थान (Space), काल (Time)।"]),
    q(0, LS, "cataloguing", "M", 1,
      ["A call number of a book consists of:", ["Accession number and price", "Class number and book number", "ISBN and edition", "Author and publisher"], "Call number = class number + book number (+ collection number); it fixes the book's place on the shelf."],
      ["पुस्तक की क्रामक संख्या (कॉल नंबर) किससे बनती है?", ["परिग्रहण संख्या और मूल्य", "वर्ग संख्या और पुस्तक संख्या", "ISBN और संस्करण", "लेखक और प्रकाशक"], "क्रामक संख्या = वर्ग संख्या + पुस्तक संख्या (+ संग्रह संख्या); यह शेल्फ़ पर पुस्तक का स्थान तय करती है।"]),
    q(0, LS, "cataloguing", "H", 0,
      ["Since 2007, the ISBN consists of:", ["13 digits", "10 digits", "8 digits", "12 digits"], "ISBN moved from 10 to 13 digits on 1 January 2007; ISSN for serials has 8 digits."],
      ["2007 से ISBN में कितने अंक होते हैं?", ["13 अंक", "10 अंक", "8 अंक", "12 अंक"], "1 जनवरी 2007 से ISBN 10 से 13 अंकों का हो गया; पत्रिकाओं के ISSN में 8 अंक होते हैं।"]),
    q(0, LS, "library-management", "M", 2,
      ["The register in which every book added to the library is entered with a serial number is the:", ["Issue register", "Shelf list", "Accession register", "Withdrawal register"], "Each new item gets a unique accession number in the accession register, the library's stock record."],
      ["जिस रजिस्टर में पुस्तकालय में जुड़ने वाली हर पुस्तक क्रमांक सहित दर्ज होती है, वह है:", ["निर्गम रजिस्टर", "शेल्फ़ सूची", "परिग्रहण रजिस्टर", "विलोपन रजिस्टर"], "हर नई सामग्री को परिग्रहण रजिस्टर में एक अनूठी परिग्रहण संख्या मिलती है; यह पुस्तकालय का स्टॉक अभिलेख है।"]),
    q(0, LS, "foundations", "M", 0,
      ["National Library Day in India, observed on 12 August, marks the birth anniversary of:", ["S.R. Ranganathan", "Melvil Dewey", "Raja Rammohun Roy", "B.S. Kesavan"], "12 August, Ranganathan's birthday (1892), is observed as National Librarians' Day."],
      ["12 अगस्त को मनाया जाने वाला भारत का राष्ट्रीय पुस्तकालयाध्यक्ष दिवस किसकी जयंती है?", ["एस.आर. रंगनाथन", "मेल्विल ड्यूई", "राजा राममोहन राय", "बी.एस. केशवन"], "रंगनाथन के जन्मदिवस (1892) 12 अगस्त को राष्ट्रीय पुस्तकालयाध्यक्ष दिवस मनाया जाता है।"]),
    q(0, LS, "foundations", "H", 1,
      ["The National Library of India is located in:", ["New Delhi", "Kolkata", "Mumbai", "Chennai"], "The National Library at Belvedere, Kolkata grew out of the Imperial Library and was opened to the public as the National Library in 1953."],
      ["भारत का राष्ट्रीय पुस्तकालय कहाँ स्थित है?", ["नई दिल्ली", "कोलकाता", "मुंबई", "चेन्नई"], "कोलकाता के बेल्वेडियर स्थित राष्ट्रीय पुस्तकालय का विकास इंपीरियल लाइब्रेरी से हुआ और 1953 में यह राष्ट्रीय पुस्तकालय के रूप में जनता के लिए खुला।"]),
    q(0, LS, "information-sources", "M", 2,
      ["Which of these is a primary source of information?", ["Encyclopaedia", "Abstracting journal", "Research journal article", "Bibliography of bibliographies"], "Primary sources report original work (journal articles, patents, theses); secondary sources organise them (indexes, abstracts, encyclopaedias); tertiary guide to secondary ones."],
      ["इनमें से कौन सूचना का प्राथमिक स्रोत है?", ["विश्वकोश", "सारांश पत्रिका", "शोध पत्रिका का लेख", "ग्रंथसूचियों की ग्रंथसूची"], "प्राथमिक स्रोत मौलिक कार्य बताते हैं (शोध लेख, पेटेंट, शोध-प्रबंध); द्वितीयक स्रोत उन्हें व्यवस्थित करते हैं (अनुक्रमणिका, सारांश, विश्वकोश); तृतीयक द्वितीयक स्रोतों का मार्गदर्शन करते हैं।"]),
    q(0, LS, "library-automation", "M", 3,
      ["OPAC in a library stands for:", ["Official Public Access Card", "Open Publication Archive Catalogue", "Online Periodical Access Centre", "Online Public Access Catalogue"], "OPAC is the computerised catalogue that users search to locate library materials."],
      ["पुस्तकालय में OPAC का पूर्ण रूप है:", ["ऑफ़िशियल पब्लिक एक्सेस कार्ड", "ओपन पब्लिकेशन आर्काइव कैटलॉग", "ऑनलाइन पीरियॉडिकल एक्सेस सेंटर", "ऑनलाइन पब्लिक एक्सेस कैटलॉग"], "OPAC कंप्यूटरीकृत सूची है जिसमें उपयोगकर्ता पुस्तकालय सामग्री खोजते हैं।"]),
    q(0, LS, "library-automation", "H", 1,
      ["KOHA is an example of:", ["A classification scheme", "Open-source integrated library management software", "A citation index", "An institutional repository only"], "KOHA (from New Zealand, 2000) is a free open-source ILS; DSpace and EPrints are repository software."],
      ["KOHA किसका उदाहरण है?", ["वर्गीकरण पद्धति", "ओपन-सोर्स एकीकृत पुस्तकालय प्रबंधन सॉफ़्टवेयर", "उद्धरण अनुक्रमणिका", "केवल संस्थागत भंडार"], "KOHA (न्यूज़ीलैंड, 2000) निःशुल्क ओपन-सोर्स ILS है; DSpace और EPrints भंडार (रिपॉज़िटरी) सॉफ़्टवेयर हैं।"]),
    q(0, LS, "library-automation", "H", 0,
      ["MARC 21 is a standard used for:", ["Machine-readable bibliographic records", "Library building design", "Book binding", "Measuring reader satisfaction"], "MARC (Machine-Readable Cataloguing) lets catalogue records be exchanged between computer systems."],
      ["MARC 21 किसके लिए उपयोग होने वाला मानक है?", ["मशीन-पठनीय ग्रंथात्मक अभिलेख", "पुस्तकालय भवन डिज़ाइन", "जिल्दसाज़ी", "पाठक संतुष्टि मापना"], "MARC (मशीन-पठनीय सूचीकरण) से सूची अभिलेख कंप्यूटर प्रणालियों के बीच आदान-प्रदान हो पाते हैं।"]),
    q(0, LS, "library-services", "M", 2,
      ["Selective Dissemination of Information (SDI) was introduced by:", ["S.R. Ranganathan", "Melvil Dewey", "H.P. Luhn", "Paul Otlet"], "H.P. Luhn of IBM proposed SDI in 1958; he also developed KWIC indexing."],
      ["चयनात्मक सूचना प्रसार (SDI) किसने प्रस्तुत किया?", ["एस.आर. रंगनाथन", "मेल्विल ड्यूई", "एच.पी. लुन", "पॉल ओटलेट"], "IBM के एच.पी. लुन ने 1958 में SDI प्रस्तावित किया; उन्होंने KWIC अनुक्रमण भी विकसित किया।"]),
    q(0, LS, "library-services", "M", 1,
      ["Answering a user's query for a specific fact, such as a date or an address, is called:", ["Long-range reference service", "Ready reference service", "Technical service", "Circulation service"], "Ready reference (short-range) service answers quick factual queries from dictionaries, directories and yearbooks."],
      ["किसी उपयोगकर्ता के विशिष्ट तथ्य, जैसे तारीख या पता, संबंधी प्रश्न का उत्तर देना कहलाता है:", ["दीर्घकालिक संदर्भ सेवा", "तत्काल (रेडी) संदर्भ सेवा", "तकनीकी सेवा", "परिचालन सेवा"], "तत्काल (अल्पकालिक) संदर्भ सेवा शब्दकोशों, निर्देशिकाओं और वार्षिकियों से जल्दी तथ्यात्मक प्रश्नों का उत्तर देती है।"]),
    q(0, LS, "information-sources", "H", 3,
      ["Bradford's law relates to:", ["Author productivity", "Word frequency", "Library growth", "Scattering of articles on a subject over journals"], "Bradford's law: a few core journals carry most articles on a subject, the rest are scattered. Lotka's law is author productivity; Zipf's law word frequency."],
      ["ब्रैडफ़ोर्ड का नियम किससे संबंधित है?", ["लेखक उत्पादकता", "शब्द आवृत्ति", "पुस्तकालय वृद्धि", "किसी विषय के लेखों का पत्रिकाओं में बिखराव"], "ब्रैडफ़ोर्ड नियम: किसी विषय के अधिकांश लेख कुछ मुख्य पत्रिकाओं में होते हैं, बाकी बिखरे रहते हैं। लोटका नियम लेखक उत्पादकता और ज़िप्फ़ नियम शब्द आवृत्ति से संबंधित है।"]),
    q(0, LS, "library-management", "M", 0,
      ["The system in which readers can go to the shelves and choose books themselves is the:", ["Open access system", "Closed access system", "Indicator system", "Reserve system"], "Open access lets readers browse shelves directly, following Ranganathan's second and fourth laws."],
      ["जिस व्यवस्था में पाठक स्वयं शेल्फ़ तक जाकर पुस्तकें चुन सकते हैं, वह है:", ["मुक्त प्रवेश (ओपन एक्सेस) व्यवस्था", "बंद प्रवेश व्यवस्था", "सूचक व्यवस्था", "आरक्षित व्यवस्था"], "मुक्त प्रवेश में पाठक सीधे शेल्फ़ देख सकते हैं, जो रंगनाथन के दूसरे और चौथे सूत्र के अनुरूप है।"]),
    q(0, LS, "cataloguing", "H", 2,
      ["Which code replaced AACR2 as the international standard for describing resources?", ["CCC", "MARC 21", "RDA (Resource Description and Access)", "DDC 23"], "RDA, released in 2010, succeeded AACR2; CCC is Ranganathan's Classified Catalogue Code."],
      ["संसाधनों के विवरण के अंतरराष्ट्रीय मानक के रूप में AACR2 का स्थान किस संहिता ने लिया?", ["CCC", "MARC 21", "RDA (रिसोर्स डिस्क्रिप्शन एंड एक्सेस)", "DDC 23"], "2010 में जारी RDA ने AACR2 का स्थान लिया; CCC रंगनाथन की वर्गीकृत सूची संहिता है।"]),
    q(0, LS, "foundations", "H", 1,
      ["The Delivery of Books and Newspapers (Public Libraries) Act requires publishers to send a copy of each publication to designated libraries. It was passed in:", ["1947", "1954", "1972", "1986"], "The 1954 Act (amended 1956) requires copies to the National Library Kolkata and public libraries at Chennai, Mumbai and Delhi."],
      ["पुस्तक और समाचार-पत्र वितरण (सार्वजनिक पुस्तकालय) अधिनियम, जिसके तहत प्रकाशकों को हर प्रकाशन की प्रति निर्दिष्ट पुस्तकालयों को भेजनी होती है, कब पारित हुआ?", ["1947", "1954", "1972", "1986"], "1954 का अधिनियम (1956 में संशोधित) राष्ट्रीय पुस्तकालय कोलकाता और चेन्नई, मुंबई व दिल्ली के सार्वजनिक पुस्तकालयों को प्रतियाँ भेजना अनिवार्य करता है।"]),
    q(0, LS, "classification", "M", 2,
      ["Universal Decimal Classification (UDC) was developed by:", ["Melvil Dewey", "Charles Ammi Cutter", "Paul Otlet and Henri La Fontaine", "H.E. Bliss"], "Otlet and La Fontaine adapted DDC into UDC (first full edition 1905)."],
      ["सार्वभौमिक दशमलव वर्गीकरण (UDC) किसने विकसित किया?", ["मेल्विल ड्यूई", "चार्ल्स एमी कटर", "पॉल ओटलेट और हेनरी ला फ़ोंटेन", "एच.ई. ब्लिस"], "ओटलेट और ला फ़ोंटेन ने DDC को रूपांतरित कर UDC बनाया (पहला पूर्ण संस्करण 1905)।"]),
    q(0, LS, "library-automation", "M", 3,
      ["RFID technology in libraries is mainly used for:", ["Classification of books", "Writing abstracts", "Book selection", "Self check-in/check-out, security and stock verification"], "Radio-frequency tags allow fast self-service circulation, theft detection and inventory without line of sight."],
      ["पुस्तकालयों में RFID तकनीक मुख्यतः किसलिए उपयोग होती है?", ["पुस्तकों का वर्गीकरण", "सारांश लिखना", "पुस्तक चयन", "स्व-निर्गम/वापसी, सुरक्षा और स्टॉक सत्यापन"], "रेडियो-आवृत्ति टैग से तेज़ स्व-सेवा परिचालन, चोरी-पहचान और बिना सीधी दृष्टि के स्टॉक-गणना संभव होती है।"]),
    q(0, LS, "library-services", "H", 0,
      ["Chain indexing was developed by:", ["S.R. Ranganathan", "Derek Austin", "H.P. Luhn", "Mortimer Taube"], "Ranganathan devised chain indexing (1938); PRECIS is Derek Austin's, KWIC is Luhn's, Uniterm is Taube's."],
      ["शृंखला अनुक्रमण (चेन इंडेक्सिंग) किसने विकसित किया?", ["एस.आर. रंगनाथन", "डेरेक ऑस्टिन", "एच.पी. लुन", "मॉर्टिमर टॉबे"], "रंगनाथन ने शृंखला अनुक्रमण (1938) बनाया; PRECIS डेरेक ऑस्टिन का, KWIC लुन का और यूनिटर्म टॉबे का है।"]),
    q(0, LS, "library-management", "H", 3,
      ["The physical checking of library stock against records to find missing books is called:", ["Weeding", "Accessioning", "Binding", "Stock verification"], "Stock verification (inventory) compares shelves with the accession register or shelf list; weeding removes outdated items."],
      ["अभिलेखों से मिलान कर पुस्तकालय स्टॉक की भौतिक जाँच कर गुम पुस्तकें खोजना कहलाता है:", ["छँटाई (वीडिंग)", "परिग्रहण", "जिल्दबंदी", "स्टॉक सत्यापन"], "स्टॉक सत्यापन में शेल्फ़ों का परिग्रहण रजिस्टर या शेल्फ़ सूची से मिलान होता है; छँटाई पुरानी सामग्री हटाना है।"]),
    q(0, LS, "foundations", "M", 1,
      ["INFLIBNET, which supports university libraries in India, is located at:", ["Bengaluru", "Gandhinagar", "New Delhi", "Pune"], "INFLIBNET Centre, an inter-university centre of UGC set up in 1991, is at Gandhinagar, Gujarat; it runs Shodhganga and e-ShodhSindhu."],
      ["भारत में विश्वविद्यालय पुस्तकालयों को सहयोग देने वाला INFLIBNET कहाँ स्थित है?", ["बेंगलुरु", "गांधीनगर", "नई दिल्ली", "पुणे"], "UGC का अंतर-विश्वविद्यालय केंद्र INFLIBNET (1991) गांधीनगर, गुजरात में है; यह शोधगंगा और ई-शोधसिंधु चलाता है।"]),
    q(0, LS, "information-sources", "M", 0,
      ["A book that gives information about places, arranged alphabetically, is a:", ["Gazetteer", "Thesaurus", "Almanac", "Biographical dictionary"], "Gazetteers are geographical dictionaries of places; a thesaurus lists related words; an almanac gives yearly facts."],
      ["स्थानों के बारे में वर्णानुक्रम में जानकारी देने वाली पुस्तक है:", ["गज़ेटियर", "थिसॉरस", "पंचांग (अल्मनैक)", "जीवनी कोश"], "गज़ेटियर स्थानों के भौगोलिक कोश हैं; थिसॉरस संबंधित शब्द देता है; अल्मनैक वार्षिक तथ्य देता है।"]),
    q(0, LS, "library-services", "M", 2,
      ["Searching a database with 'library AND automation' will retrieve records containing:", ["Either term", "Neither term", "Both terms", "Only the first term"], "Boolean AND narrows the search to records with both terms; OR broadens; NOT excludes."],
      ["डेटाबेस में 'library AND automation' खोजने पर कौन-से अभिलेख मिलेंगे?", ["किसी एक शब्द वाले", "किसी भी शब्द से रहित", "दोनों शब्दों वाले", "केवल पहले शब्द वाले"], "बूलियन AND खोज को दोनों शब्दों वाले अभिलेखों तक सीमित करता है; OR विस्तार करता है; NOT बाहर करता है।"]),
    q(0, LS, "library-management", "M", 1,
      ["Removing outdated and damaged books from the collection is called:", ["Accessioning", "Weeding", "Shelving", "Classification"], "Weeding keeps the collection current and usable; withdrawn items are recorded in a withdrawal register."],
      ["संग्रह से पुरानी और क्षतिग्रस्त पुस्तकें हटाना कहलाता है:", ["परिग्रहण", "छँटाई (वीडिंग)", "शेल्फ़ में लगाना", "वर्गीकरण"], "छँटाई से संग्रह उपयोगी और अद्यतन रहता है; हटाई गई सामग्री विलोपन रजिस्टर में दर्ज होती है।"]),
    q(0, LS, "foundations", "E", 3,
      ["Who is known as the 'Father of Library Science in India'?", ["Melvil Dewey", "B.S. Kesavan", "P.N. Kaula", "S.R. Ranganathan"], "Dr S.R. Ranganathan, a mathematician turned librarian at Madras University, is the father of library science in India."],
      ["'भारत में पुस्तकालय विज्ञान के जनक' किसे कहा जाता है?", ["मेल्विल ड्यूई", "बी.एस. केशवन", "पी.एन. कौला", "एस.आर. रंगनाथन"], "मद्रास विश्वविद्यालय के गणितज्ञ से पुस्तकालयाध्यक्ष बने डॉ. एस.आर. रंगनाथन भारत में पुस्तकालय विज्ञान के जनक हैं।"]),
  ],
  [
    q(0, LS, "foundations", "M", 2,
      ["'Every book its reader' is Ranganathan's:", ["First law", "Second law", "Third law", "Fifth law"], "Third law: every book its reader — supported by open access, displays and good cataloguing."],
      ["'प्रत्येक पुस्तक को उसका पाठक' रंगनाथन का कौन-सा सूत्र है?", ["पहला सूत्र", "दूसरा सूत्र", "तीसरा सूत्र", "पाँचवाँ सूत्र"], "तीसरा सूत्र: प्रत्येक पुस्तक को उसका पाठक — मुक्त प्रवेश, प्रदर्शन और अच्छे सूचीकरण से सहायता मिलती है।"]),
    q(0, LS, "classification", "H", 0,
      ["Colon Classification was first published in:", ["1933", "1876", "1905", "1965"], "Ranganathan's Colon Classification first appeared in 1933; its name comes from the colon used as the connecting symbol."],
      ["कोलन वर्गीकरण पहली बार कब प्रकाशित हुआ?", ["1933", "1876", "1905", "1965"], "रंगनाथन का कोलन वर्गीकरण पहली बार 1933 में आया; इसका नाम संयोजक चिह्न कोलन से पड़ा।"]),
    q(0, LS, "classification", "M", 3,
      ["In DDC, 'history and geography' is in the main class:", ["300", "700", "800", "900"], "900 is history and geography; 800 literature; 700 arts; 300 social sciences."],
      ["DDC में 'इतिहास और भूगोल' किस मुख्य वर्ग में है?", ["300", "700", "800", "900"], "900 इतिहास और भूगोल; 800 साहित्य; 700 कला; 300 सामाजिक विज्ञान।"]),
    q(0, LS, "cataloguing", "H", 1,
      ["The ISSN, used to identify serial publications, has:", ["13 digits", "8 digits", "10 digits", "6 digits"], "ISSN is 8 digits in two groups of four (e.g. 1234-5679), the last being a check digit."],
      ["धारावाहिक प्रकाशनों की पहचान के लिए उपयोग होने वाले ISSN में होते हैं:", ["13 अंक", "8 अंक", "10 अंक", "6 अंक"], "ISSN 8 अंकों का होता है, चार-चार के दो समूहों में (जैसे 1234-5679), अंतिम अंक जाँच-अंक है।"]),
    q(0, LS, "cataloguing", "M", 2,
      ["Which subject heading list is commonly used in small and school libraries?", ["Library of Congress Subject Headings", "MeSH", "Sears List of Subject Headings", "UNESCO Thesaurus"], "Sears List is a simpler list designed for small and medium libraries; LCSH is used by large libraries; MeSH is for medicine."],
      ["छोटे और विद्यालय पुस्तकालयों में सामान्यतः कौन-सी विषय-शीर्षक सूची उपयोग होती है?", ["लाइब्रेरी ऑफ़ कांग्रेस सब्जेक्ट हेडिंग्स", "MeSH", "सियर्स लिस्ट ऑफ़ सब्जेक्ट हेडिंग्स", "यूनेस्को थिसॉरस"], "सियर्स लिस्ट छोटे और मध्यम पुस्तकालयों के लिए सरल सूची है; LCSH बड़े पुस्तकालयों में और MeSH चिकित्सा के लिए उपयोग होती है।"]),
    q(0, LS, "library-services", "H", 3,
      ["Current Awareness Service (CAS) mainly aims to:", ["Answer reference questions", "Lend books to other libraries", "Classify new arrivals", "Inform users about recent publications in their field"], "CAS alerts users to new literature, e.g. through lists of new arrivals, contents pages and alerts; SDI is its personalised form."],
      ["वर्तमान जागरूकता सेवा (CAS) का मुख्य उद्देश्य है:", ["संदर्भ प्रश्नों के उत्तर देना", "दूसरे पुस्तकालयों को पुस्तकें उधार देना", "नई सामग्री का वर्गीकरण", "उपयोगकर्ताओं को उनके क्षेत्र के नवीन प्रकाशनों की सूचना देना"], "CAS उपयोगकर्ताओं को नई सामग्री की जानकारी देती है, जैसे नवागत सूचियाँ, विषय-सूची पृष्ठ और अलर्ट; SDI इसका व्यक्तिगत रूप है।"]),
    q(0, LS, "library-management", "M", 0,
      ["The Browne charging system is used in libraries for:", ["Circulation (issue and return) of books", "Classification", "Cataloguing", "Book binding"], "In the Browne system each reader has ticket pockets that hold the book card while the book is on loan."],
      ["पुस्तकालयों में ब्राउन चार्जिंग प्रणाली किसके लिए उपयोग होती है?", ["पुस्तकों का परिचालन (निर्गम और वापसी)", "वर्गीकरण", "सूचीकरण", "जिल्दसाज़ी"], "ब्राउन प्रणाली में हर पाठक के टिकट-पॉकेट होते हैं जिनमें पुस्तक उधार रहने तक पुस्तक-कार्ड रखा जाता है।"]),
    q(0, LS, "information-sources", "H", 1,
      ["Lotka's law in bibliometrics deals with:", ["Scattering of journals", "Productivity of authors", "Frequency of words", "Obsolescence of literature"], "Lotka's inverse square law: the number of authors publishing n papers is about 1/n² of those publishing one."],
      ["ग्रंथमिति में लोटका का नियम किससे संबंधित है?", ["पत्रिकाओं का बिखराव", "लेखकों की उत्पादकता", "शब्दों की आवृत्ति", "साहित्य का अप्रचलन"], "लोटका का व्युत्क्रम वर्ग नियम: n लेख प्रकाशित करने वाले लेखकों की संख्या एक लेख वालों की लगभग 1/n² होती है।"]),
    q(0, LS, "library-automation", "M", 2,
      ["DSpace software is mainly used to build:", ["Library budgets", "Book selection lists", "Institutional digital repositories", "Classification schedules"], "DSpace (MIT and HP, 2002) is open-source software for digital repositories of theses, papers and data."],
      ["DSpace सॉफ़्टवेयर मुख्यतः किसे बनाने में उपयोग होता है?", ["पुस्तकालय बजट", "पुस्तक चयन सूचियाँ", "संस्थागत डिजिटल भंडार", "वर्गीकरण अनुसूचियाँ"], "DSpace (MIT और HP, 2002) शोध-प्रबंध, लेख और डेटा के डिजिटल भंडार हेतु ओपन-सोर्स सॉफ़्टवेयर है।"]),
    q(0, LS, "foundations", "M", 3,
      ["The library movement in Baroda state in the early 20th century was led by:", ["Raja Rammohun Roy", "Lord Curzon", "S.R. Ranganathan", "Maharaja Sayajirao Gaekwad III"], "Sayajirao Gaekwad III set up a state-wide free public library system in Baroda, with W.A. Borden as adviser (1910)."],
      ["20वीं सदी के आरंभ में बड़ौदा राज्य में पुस्तकालय आंदोलन का नेतृत्व किसने किया?", ["राजा राममोहन राय", "लॉर्ड कर्ज़न", "एस.आर. रंगनाथन", "महाराजा सयाजीराव गायकवाड़ तृतीय"], "सयाजीराव गायकवाड़ तृतीय ने डब्ल्यू.ए. बॉर्डन को सलाहकार बनाकर (1910) बड़ौदा में राज्यव्यापी निःशुल्क सार्वजनिक पुस्तकालय प्रणाली बनाई।"]),
    q(0, LS, "library-services", "H", 0,
      ["Inter-library loan means:", ["Borrowing material from another library for a user", "Lending books to staff only", "Exchange of librarians", "Merging two libraries"], "Inter-library loan obtains items the library lacks from another library, extending resource sharing."],
      ["अंतर-पुस्तकालय ऋण का अर्थ है:", ["किसी उपयोगकर्ता के लिए दूसरे पुस्तकालय से सामग्री उधार लेना", "केवल कर्मचारियों को पुस्तकें देना", "पुस्तकालयाध्यक्षों का आदान-प्रदान", "दो पुस्तकालयों का विलय"], "अंतर-पुस्तकालय ऋण में पुस्तकालय के पास न होने वाली सामग्री दूसरे पुस्तकालय से मँगाई जाती है, जिससे संसाधन-साझेदारी बढ़ती है।"]),
    q(0, LS, "cataloguing", "M", 1,
      ["Cutter's tables are used in libraries for:", ["Classifying subjects", "Assigning author marks (book numbers)", "Measuring shelf space", "Counting visitors"], "Cutter (or Cutter-Sanborn) tables give alphanumeric author marks to arrange books within a class."],
      ["पुस्तकालयों में कटर तालिकाएँ किसके लिए उपयोग होती हैं?", ["विषयों का वर्गीकरण", "लेखक चिह्न (पुस्तक संख्या) देना", "शेल्फ़ स्थान मापना", "आगंतुक गिनना"], "कटर (या कटर-सैनबॉर्न) तालिकाएँ किसी वर्ग के भीतर पुस्तकें व्यवस्थित करने के लिए अक्षरांकीय लेखक चिह्न देती हैं।"]),
    q(0, LS, "library-automation", "H", 3,
      ["Z39.50 is a protocol used for:", ["Book binding standards", "Measuring reading speed", "Library building lighting", "Searching and retrieving records from remote library databases"], "Z39.50 lets a client search catalogues on different systems, e.g. for copy cataloguing."],
      ["Z39.50 किसके लिए उपयोग होने वाला प्रोटोकॉल है?", ["जिल्दसाज़ी मानक", "पढ़ने की गति मापना", "पुस्तकालय भवन प्रकाश", "दूरस्थ पुस्तकालय डेटाबेस से अभिलेख खोजना और प्राप्त करना"], "Z39.50 से एक क्लाइंट विभिन्न प्रणालियों की सूचियाँ खोज सकता है, जैसे प्रति-सूचीकरण के लिए।"]),
    q(0, LS, "information-sources", "M", 0,
      ["An index that lists papers which cite a given earlier paper is a:", ["Citation index", "Subject catalogue", "Union catalogue", "Gazetteer"], "Eugene Garfield's Science Citation Index (1964) pioneered citation indexing."],
      ["जो अनुक्रमणिका किसी पूर्व लेख का उद्धरण देने वाले लेखों की सूची देती है, वह है:", ["उद्धरण अनुक्रमणिका", "विषय सूची", "संघ सूची", "गज़ेटियर"], "यूजीन गारफ़ील्ड के साइंस साइटेशन इंडेक्स (1964) ने उद्धरण अनुक्रमण की शुरुआत की।"]),
    q(0, LS, "library-management", "M", 2,
      ["Who said that the best book selection gives 'the best reading for the largest number at the least cost'?", ["S.R. Ranganathan", "F.K.W. Drury", "Melvil Dewey", "L.R. McColvin"], "This book-selection principle is attributed to Melvil Dewey."],
      ["'न्यूनतम लागत पर अधिकतम लोगों के लिए सर्वोत्तम पठन सामग्री' — पुस्तक चयन का यह सिद्धांत किसने दिया?", ["एस.आर. रंगनाथन", "एफ.के.डब्ल्यू. ड्रूरी", "मेल्विल ड्यूई", "एल.आर. मैककॉल्विन"], "यह पुस्तक चयन सिद्धांत मेल्विल ड्यूई का माना जाता है।"]),
    q(0, LS, "foundations", "H", 1,
      ["The ISBN agency for India, which allots ISBNs to Indian publishers, is the:", ["National Library, Kolkata", "Raja Rammohun Roy National Agency for ISBN", "INFLIBNET Centre", "National Book Trust"], "The Raja Rammohun Roy National Agency for ISBN under the Ministry of Education allots ISBNs in India."],
      ["भारतीय प्रकाशकों को ISBN आवंटित करने वाली भारत की ISBN एजेंसी है:", ["राष्ट्रीय पुस्तकालय, कोलकाता", "राजा राममोहन राय राष्ट्रीय ISBN एजेंसी", "INFLIBNET केंद्र", "नेशनल बुक ट्रस्ट"], "शिक्षा मंत्रालय के अधीन राजा राममोहन राय राष्ट्रीय ISBN एजेंसी भारत में ISBN आवंटित करती है।"]),
    q(0, LS, "classification", "H", 2,
      ["The Library of Congress Classification uses a notation of:", ["Pure numbers", "Pure Roman numerals", "Letters followed by numbers (mixed notation)", "Only symbols"], "LCC uses one to three capital letters for classes followed by numbers, e.g. QA76 for computing."],
      ["लाइब्रेरी ऑफ़ कांग्रेस वर्गीकरण में अंकन किस प्रकार का होता है?", ["केवल संख्याएँ", "केवल रोमन अंक", "अक्षरों के बाद संख्याएँ (मिश्रित अंकन)", "केवल चिह्न"], "LCC में वर्गों के लिए एक से तीन बड़े अक्षर और फिर संख्याएँ होती हैं, जैसे कंप्यूटिंग के लिए QA76।"]),
    q(0, LS, "information-sources", "M", 3,
      ["Which of these is a secondary source of information?", ["A doctoral thesis", "A patent", "A conference paper", "An abstracting journal"], "Abstracting and indexing journals digest primary literature, so they are secondary sources."],
      ["इनमें से कौन सूचना का द्वितीयक स्रोत है?", ["एक शोध-प्रबंध", "एक पेटेंट", "एक सम्मेलन शोधपत्र", "एक सारांश पत्रिका"], "सारांश और अनुक्रमणिका पत्रिकाएँ प्राथमिक साहित्य का सार देती हैं, इसलिए द्वितीयक स्रोत हैं।"]),
    q(0, LS, "library-automation", "M", 1,
      ["A barcode on a library book usually encodes its:", ["Price", "Accession number", "Author's address", "Number of pages"], "The barcode carries the item's accession or item ID, which the circulation module links to the catalogue record."],
      ["पुस्तकालय की पुस्तक पर लगा बारकोड सामान्यतः किसे दर्शाता है?", ["मूल्य", "परिग्रहण संख्या", "लेखक का पता", "पृष्ठों की संख्या"], "बारकोड में सामग्री की परिग्रहण या आइटम ID होती है, जिसे परिचालन मॉड्यूल सूची-अभिलेख से जोड़ता है।"]),
    q(0, LS, "library-services", "M", 0,
      ["Teaching users how to locate and use library resources is called:", ["User education (information literacy)", "Technical processing", "Accessioning", "Weeding"], "User education and information literacy programmes help readers use catalogues, databases and reference sources."],
      ["उपयोगकर्ताओं को पुस्तकालय संसाधन खोजना और उपयोग करना सिखाना कहलाता है:", ["उपयोगकर्ता शिक्षा (सूचना साक्षरता)", "तकनीकी प्रसंस्करण", "परिग्रहण", "छँटाई"], "उपयोगकर्ता शिक्षा और सूचना साक्षरता कार्यक्रम पाठकों को सूची, डेटाबेस और संदर्भ स्रोतों का उपयोग सिखाते हैं।"]),
    q(0, LS, "library-management", "H", 3,
      ["Which of these is part of 'technical services' in a library?", ["Reference service", "Reader's advisory", "User orientation", "Classification and cataloguing"], "Technical services are behind-the-scenes work: acquisition, classification, cataloguing and processing; the others are reader services."],
      ["इनमें से कौन पुस्तकालय की 'तकनीकी सेवाओं' का भाग है?", ["संदर्भ सेवा", "पाठक परामर्श", "उपयोगकर्ता अभिविन्यास", "वर्गीकरण और सूचीकरण"], "तकनीकी सेवाएँ पर्दे के पीछे का कार्य हैं: अधिग्रहण, वर्गीकरण, सूचीकरण और प्रसंस्करण; बाकी पाठक सेवाएँ हैं।"]),
    q(0, LS, "classification", "M", 2,
      ["In a classification scheme, 'notation' means:", ["The preface of the scheme", "Rules for book selection", "Symbols that represent classes", "List of library staff"], "Notation is the system of symbols (numbers, letters) that represents classes and fixes their order."],
      ["वर्गीकरण पद्धति में 'अंकन' (नोटेशन) का अर्थ है:", ["पद्धति की प्रस्तावना", "पुस्तक चयन के नियम", "वर्गों को दर्शाने वाले प्रतीक", "पुस्तकालय कर्मचारियों की सूची"], "अंकन प्रतीकों (संख्याएँ, अक्षर) की वह प्रणाली है जो वर्गों को दर्शाती और उनका क्रम तय करती है।"]),
    q(0, LS, "information-sources", "H", 0,
      ["Shodhganga, run by INFLIBNET, is a repository of:", ["Indian electronic theses and dissertations", "Government gazettes", "Newspapers", "Rare manuscripts only"], "Shodhganga hosts full-text PhD theses submitted by Indian universities under the UGC regulations of 2009."],
      ["INFLIBNET द्वारा संचालित शोधगंगा किसका भंडार है?", ["भारतीय इलेक्ट्रॉनिक शोध-प्रबंध और लघु शोध-प्रबंध", "सरकारी राजपत्र", "समाचार-पत्र", "केवल दुर्लभ पांडुलिपियाँ"], "शोधगंगा में UGC विनियम 2009 के तहत भारतीय विश्वविद्यालयों द्वारा जमा पूर्ण पाठ PhD शोध-प्रबंध हैं।"]),
    q(0, LS, "cataloguing", "M", 0,
      ["A catalogue that lists the holdings of several libraries together is a:", ["Union catalogue", "Shelf list", "Dictionary catalogue", "Accession list"], "A union catalogue (e.g. IndCat of INFLIBNET) shows which library holds which item, aiding inter-library loan."],
      ["अनेक पुस्तकालयों के संग्रह को एक साथ सूचीबद्ध करने वाली सूची है:", ["संघ सूची (यूनियन कैटलॉग)", "शेल्फ़ सूची", "शब्दकोश सूची", "परिग्रहण सूची"], "संघ सूची (जैसे INFLIBNET की IndCat) दिखाती है कि कौन-सी सामग्री किस पुस्तकालय में है, जिससे अंतर-पुस्तकालय ऋण में मदद मिलती है।"]),
    q(0, LS, "library-management", "M", 1,
      ["Periodicals in a library are usually recorded through the:", ["Accession register for books", "Kardex (periodical register) system", "Withdrawal register", "Gate register"], "A Kardex or periodical register tracks each issue received, missing issues and renewals."],
      ["पुस्तकालय में पत्रिकाएँ सामान्यतः किसके द्वारा दर्ज की जाती हैं?", ["पुस्तकों का परिग्रहण रजिस्टर", "कार्डेक्स (पत्रिका रजिस्टर) प्रणाली", "विलोपन रजिस्टर", "प्रवेश-द्वार रजिस्टर"], "कार्डेक्स या पत्रिका रजिस्टर में प्राप्त हर अंक, अप्राप्त अंक और नवीनीकरण का हिसाब रहता है।"]),
    q(0, LS, "library-services", "H", 2,
      ["KWIC indexing produces index entries by:", ["Assigning subject headings manually", "Using class numbers", "Rotating keywords from titles in context", "Listing authors alphabetically"], "Keyword-In-Context (Luhn, 1958) rotates each significant title word into the filing position with its surrounding words."],
      ["KWIC अनुक्रमण अनुक्रमणिका प्रविष्टियाँ कैसे बनाता है?", ["हाथ से विषय-शीर्षक देकर", "वर्ग संख्याओं का उपयोग करके", "शीर्षकों के मुख्य शब्दों को संदर्भ सहित घुमाकर", "लेखकों को वर्णानुक्रम में सूचीबद्ध करके"], "की-वर्ड-इन-कॉन्टेक्स्ट (लुन, 1958) शीर्षक के हर महत्वपूर्ण शब्द को आसपास के शब्दों सहित क्रम-स्थान पर घुमाता है।"]),
    q(0, LS, "foundations", "E", 3,
      ["The main purpose of a public library is to:", ["Earn profit", "Serve only students", "Store old files", "Provide free access to information and reading for all"], "The UNESCO Public Library Manifesto describes the public library as a free local gateway to knowledge for everyone."],
      ["सार्वजनिक पुस्तकालय का मुख्य उद्देश्य है:", ["लाभ कमाना", "केवल विद्यार्थियों की सेवा", "पुरानी फ़ाइलें रखना", "सभी को सूचना और पठन तक निःशुल्क पहुँच देना"], "यूनेस्को सार्वजनिक पुस्तकालय घोषणापत्र सार्वजनिक पुस्तकालय को सबके लिए ज्ञान का निःशुल्क स्थानीय द्वार बताता है।"]),
  ],
];
