// HPRCA Staff Nurse — three nursing sections, 20 fresh questions each for each of the two full mocks.

import { q, type PatwariQuestion } from "../../patwari/types";

const N = "nursing";

export const nursingFundamentals: PatwariQuestion[][] = [
  [
    q(0, N, "fundamentals", "M", 2,
      ["The normal adult resting pulse rate is:", ["40–60 beats/min", "100–140 beats/min", "60–100 beats/min", "120–160 beats/min"], "A resting adult pulse of 60–100/min is normal; below 60 is bradycardia and above 100 tachycardia."],
      ["वयस्क की सामान्य विश्राम नाड़ी दर है:", ["40–60 धड़कन/मिनट", "100–140 धड़कन/मिनट", "60–100 धड़कन/मिनट", "120–160 धड़कन/मिनट"], "वयस्क में विश्राम नाड़ी 60–100/मिनट सामान्य है; 60 से कम ब्रैडीकार्डिया और 100 से अधिक टैकीकार्डिया है।"]),
    q(0, N, "fundamentals", "H", 0,
      ["The most effective single measure to prevent hospital-acquired infection is:", ["Hand hygiene", "Wearing a mask at all times", "Giving antibiotics to all patients", "Fumigating wards daily"], "WHO identifies hand hygiene as the most important measure against healthcare-associated infections."],
      ["अस्पताल-जनित संक्रमण रोकने का सबसे प्रभावी एकल उपाय है:", ["हाथों की स्वच्छता", "हर समय मास्क पहनना", "सभी रोगियों को एंटीबायोटिक देना", "रोज़ वार्ड का धूमन"], "WHO के अनुसार स्वास्थ्य-सेवा संबंधी संक्रमणों के विरुद्ध हाथों की स्वच्छता सबसे महत्वपूर्ण उपाय है।"]),
    q(0, N, "fundamentals", "M", 3,
      ["The position in which the patient lies on the back with the head of the bed raised 45–60° is:", ["Prone position", "Trendelenburg position", "Lithotomy position", "Fowler's position"], "Fowler's position (semi-sitting) eases breathing; Trendelenburg is head-down, lithotomy for perineal procedures."],
      ["रोगी पीठ के बल लेटा हो और बिस्तर का सिरा 45–60° उठा हो — यह स्थिति है:", ["प्रोन स्थिति", "ट्रेंडेलेनबर्ग स्थिति", "लिथोटॉमी स्थिति", "फ़ाउलर स्थिति"], "फ़ाउलर स्थिति (अर्ध-बैठी) साँस लेना आसान करती है; ट्रेंडेलेनबर्ग में सिर नीचे और लिथोटॉमी पेरिनियल प्रक्रियाओं के लिए है।"]),
    q(0, N, "fundamentals", "H", 1,
      ["An intramuscular injection in adults is commonly given in the:", ["Deltoid only for large volumes", "Ventrogluteal or vastus lateralis site", "Abdomen around the umbilicus", "Inner forearm"], "Ventrogluteal and vastus lateralis are preferred for IM injections; the deltoid takes only small volumes; the abdomen is for subcutaneous injections."],
      ["वयस्कों में अंतःपेशीय (IM) इंजेक्शन सामान्यतः कहाँ दिया जाता है?", ["अधिक मात्रा के लिए केवल डेल्टॉइड", "वेंट्रोग्लूटियल या वैस्टस लेटरेलिस स्थल", "नाभि के आसपास पेट", "अग्रबाहु का भीतरी भाग"], "IM इंजेक्शन के लिए वेंट्रोग्लूटियल और वैस्टस लेटरेलिस बेहतर स्थल हैं; डेल्टॉइड में केवल कम मात्रा; पेट त्वचा-अधः इंजेक्शन के लिए है।"]),
    q(0, N, "fundamentals", "M", 0,
      ["An intradermal injection, as for the Mantoux test, is given at an angle of:", ["10–15°", "45°", "90°", "30–35°"], "Intradermal: 10–15°; subcutaneous: 45°; intramuscular: 90°."],
      ["इंट्राडर्मल इंजेक्शन, जैसे मैंटू परीक्षण में, किस कोण पर दिया जाता है?", ["10–15°", "45°", "90°", "30–35°"], "इंट्राडर्मल: 10–15°; त्वचा-अधः: 45°; अंतःपेशीय: 90°।"]),
    q(0, N, "fundamentals", "H", 2,
      ["Bed sores (pressure ulcers) are best prevented by:", [ "Applying powder to the back", "Keeping the patient in one position", "Changing the patient's position at least every 2 hours", "Massaging reddened bony areas hard"], "Regular repositioning relieves pressure; vigorous massage over reddened areas can damage tissue."],
      ["शय्या-व्रण (प्रेशर अल्सर) की सबसे अच्छी रोकथाम है:", ["पीठ पर पाउडर लगाना", "रोगी को एक ही स्थिति में रखना", "कम से कम हर 2 घंटे में रोगी की स्थिति बदलना", "लाल हुई हड्डीदार जगहों की ज़ोर से मालिश"], "नियमित स्थिति-परिवर्तन दबाव कम करता है; लाल हुई जगहों पर ज़ोरदार मालिश ऊतक को हानि पहुँचा सकती है।"]),
    q(0, N, "fundamentals", "M", 1,
      ["The 'five rights' of medication administration do NOT include the right:", ["Patient", "Price", "Dose", "Route"], "The rights are patient, drug, dose, route and time (often extended to documentation, reason, response); price is not one."],
      ["औषधि देने के 'पाँच अधिकारों' में कौन-सा शामिल नहीं है?", ["सही रोगी", "सही मूल्य", "सही मात्रा", "सही मार्ग"], "अधिकार हैं: रोगी, दवा, मात्रा, मार्ग और समय (प्रायः दस्तावेज़ीकरण, कारण, प्रतिक्रिया भी); मूल्य इनमें नहीं है।"]),
    q(0, N, "fundamentals", "H", 3,
      ["In the biomedical waste rules of India (2016), used sharps such as needles go into the:", ["Yellow bag", "Red bag", "Black bag", "White translucent puncture-proof container"], "BMW Rules 2016: white (translucent) puncture-proof container for sharps; yellow for anatomical/soiled waste; red for contaminated recyclable plastics."],
      ["भारत के जैव-चिकित्सा अपशिष्ट नियम (2016) में उपयोग की गई सुइयाँ जैसे नुकीले अपशिष्ट किसमें डाले जाते हैं?", ["पीले बैग में", "लाल बैग में", "काले बैग में", "सफ़ेद पारभासी छेद-रोधी डिब्बे में"], "BMW नियम 2016: नुकीले अपशिष्ट के लिए सफ़ेद (पारभासी) छेद-रोधी डिब्बा; शारीरिक/गंदे अपशिष्ट के लिए पीला; दूषित पुनर्चक्रण योग्य प्लास्टिक के लिए लाल।"]),
    q(0, N, "fundamentals", "M", 2,
      ["Normal adult respiratory rate at rest is:", ["6–10 breaths/min", "25–35 breaths/min", "12–20 breaths/min", "30–40 breaths/min"], "Adults normally breathe 12–20 times a minute at rest."],
      ["वयस्क की विश्राम पर सामान्य श्वसन दर है:", ["6–10 श्वास/मिनट", "25–35 श्वास/मिनट", "12–20 श्वास/मिनट", "30–40 श्वास/मिनट"], "वयस्क सामान्यतः विश्राम पर प्रति मिनट 12–20 बार साँस लेते हैं।"]),
    q(0, N, "fundamentals", "H", 0,
      ["The Glasgow Coma Scale assesses eye opening, verbal response and motor response. Its lowest possible score is:", ["3", "0", "1", "5"], "GCS ranges from 3 (deep coma) to 15 (fully alert)."],
      ["ग्लासगो कोमा स्केल आँख खुलना, मौखिक और गामक अनुक्रिया आँकता है। इसका न्यूनतम संभव अंक है:", ["3", "0", "1", "5"], "GCS 3 (गहरा कोमा) से 15 (पूर्ण सजग) तक होता है।"]),
    q(0, N, "fundamentals", "M", 3,
      ["Florence Nightingale is known for her work during the:", ["World War I", "American Civil War", "Boer War", "Crimean War"], "Nightingale led nurses at Scutari during the Crimean War (1853–56) and founded modern nursing; she was called 'the Lady with the Lamp'."],
      ["फ़्लोरेंस नाइटिंगेल किस युद्ध के दौरान अपने कार्य के लिए प्रसिद्ध हैं?", ["प्रथम विश्व युद्ध", "अमेरिकी गृहयुद्ध", "बोअर युद्ध", "क्रीमिया युद्ध"], "नाइटिंगेल ने क्रीमिया युद्ध (1853–56) में स्कुटारी में नर्सों का नेतृत्व किया और आधुनिक नर्सिंग की नींव रखी; उन्हें 'लेडी विद द लैंप' कहा गया।"]),
    q(0, N, "anatomy-physiology", "M", 1,
      ["The pacemaker of the heart is the:", ["AV node", "SA node", "Bundle of His", "Purkinje fibres"], "The sinoatrial (SA) node in the right atrium starts each heartbeat."],
      ["हृदय का पेसमेकर है:", ["AV नोड", "SA नोड", "हिस का बंडल", "पुर्किंजे तंतु"], "दाएँ अलिंद में स्थित साइनोएट्रियल (SA) नोड हर धड़कन शुरू करता है।"]),
    q(0, N, "anatomy-physiology", "H", 2,
      ["Which blood vessel carries oxygenated blood from the lungs to the heart?", ["Pulmonary artery", "Superior vena cava", "Pulmonary vein", "Aorta"], "Pulmonary veins are the only veins carrying oxygenated blood, into the left atrium; the pulmonary artery carries deoxygenated blood to the lungs."],
      ["कौन-सी रक्त वाहिका फेफड़ों से ऑक्सीजन-युक्त रक्त हृदय तक लाती है?", ["फुफ्फुसीय धमनी", "ऊर्ध्व महाशिरा", "फुफ्फुसीय शिरा", "महाधमनी"], "फुफ्फुसीय शिराएँ ही ऐसी शिराएँ हैं जो ऑक्सीजन-युक्त रक्त बाएँ अलिंद में लाती हैं; फुफ्फुसीय धमनी अशुद्ध रक्त फेफड़ों तक ले जाती है।"]),
    q(0, N, "anatomy-physiology", "M", 0,
      ["Which structure is the basic functional unit of the kidney?", ["Nephron", "Neuron", "Alveolus", "Hepatocyte"], "Each kidney has about a million nephrons, which filter blood and form urine."],
      ["गुर्दे की कार्यात्मक इकाई है:", ["नेफ़्रॉन", "न्यूरॉन", "कूपिका (एल्वियोलस)", "हेपेटोसाइट"], "हर गुर्दे में लगभग दस लाख नेफ़्रॉन होते हैं जो रक्त छानकर मूत्र बनाते हैं।"]),
    q(0, N, "anatomy-physiology", "H", 3,
      ["Which pancreatic cells secrete the hormone insulin?", ["Alpha cells", "Delta cells", "Acinar cells", "Beta cells of the islets of Langerhans"], "Beta cells secrete insulin, alpha cells glucagon and delta cells somatostatin; acinar cells make digestive enzymes."],
      ["इंसुलिन अग्न्याशय की किन कोशिकाओं से स्रावित होता है?", ["अल्फ़ा कोशिकाएँ", "डेल्टा कोशिकाएँ", "एसिनर कोशिकाएँ", "लैंगरहैंस द्वीपों की बीटा कोशिकाएँ"], "बीटा कोशिकाएँ इंसुलिन, अल्फ़ा ग्लूकागॉन और डेल्टा सोमैटोस्टैटिन स्रावित करती हैं; एसिनर कोशिकाएँ पाचक एंज़ाइम बनाती हैं।"]),
    q(0, N, "anatomy-physiology", "M", 2,
      ["The longest bone in the human body is the:", ["Tibia", "Humerus", "Femur", "Fibula"], "The femur (thigh bone) is the longest and strongest bone."],
      ["मानव शरीर की सबसे लंबी हड्डी है:", ["टिबिया", "ह्यूमरस", "फ़ीमर", "फ़िबुला"], "फ़ीमर (जाँघ की हड्डी) सबसे लंबी और मज़बूत हड्डी है।"]),
    q(0, N, "anatomy-physiology", "H", 1,
      ["The normal life span of a red blood cell is about:", ["30 days", "120 days", "7 days", "365 days"], "RBCs live about 120 days before removal by the spleen and liver."],
      ["लाल रक्त कोशिका का सामान्य जीवनकाल लगभग है:", ["30 दिन", "120 दिन", "7 दिन", "365 दिन"], "लाल रक्त कोशिकाएँ लगभग 120 दिन जीवित रहती हैं, फिर तिल्ली और यकृत द्वारा हटाई जाती हैं।"]),
    q(0, N, "anatomy-physiology", "M", 3,
      ["Bile is produced by the:", ["Gall bladder", "Pancreas", "Stomach", "Liver"], "The liver produces bile; the gall bladder only stores and concentrates it."],
      ["पित्त किसके द्वारा बनाया जाता है?", ["पित्ताशय", "अग्न्याशय", "आमाशय", "यकृत"], "यकृत पित्त बनाता है; पित्ताशय केवल उसे संग्रहित और सांद्रित करता है।"]),
    q(0, N, "anatomy-physiology", "H", 0,
      ["The cranial nerve that controls most facial expressions is the:", ["Facial nerve (VII)", "Trigeminal nerve (V)", "Vagus nerve (X)", "Oculomotor nerve (III)"], "Cranial nerve VII supplies the muscles of facial expression; V carries facial sensation and supplies chewing muscles."],
      ["चेहरे के अधिकांश भावों को नियंत्रित करने वाली कपाल तंत्रिका है:", ["फ़ेशियल तंत्रिका (VII)", "ट्राइजेमिनल तंत्रिका (V)", "वेगस तंत्रिका (X)", "ऑक्युलोमोटर तंत्रिका (III)"], "कपाल तंत्रिका VII चेहरे के भाव की पेशियों को आपूर्ति करती है; V चेहरे की संवेदना और चबाने की पेशियों से जुड़ी है।"]),
    q(0, N, "anatomy-physiology", "E", 1,
      ["Gas exchange in the lungs takes place in the:", ["Bronchi", "Alveoli", "Trachea", "Larynx"], "Oxygen and carbon dioxide are exchanged across the thin walls of the alveoli."],
      ["फेफड़ों में गैसों का आदान-प्रदान कहाँ होता है?", ["श्वसनी (ब्रॉन्काई)", "कूपिकाएँ (एल्वियोलाई)", "श्वासनली", "स्वरयंत्र"], "ऑक्सीजन और कार्बन डाइऑक्साइड का आदान-प्रदान कूपिकाओं की पतली दीवारों से होता है।"]),
  ],
  [
    q(0, N, "fundamentals", "M", 1,
      ["Normal oral body temperature of an adult is about:", ["35.0 °C", "37.0 °C", "38.5 °C", "39.5 °C"], "Average oral temperature is about 37 °C (98.6 °F); above about 38 °C is fever."],
      ["वयस्क का सामान्य मौखिक शरीर तापमान लगभग है:", ["35.0 °C", "37.0 °C", "38.5 °C", "39.5 °C"], "औसत मौखिक तापमान लगभग 37 °C (98.6 °F) है; लगभग 38 °C से अधिक बुख़ार है।"]),
    q(0, N, "fundamentals", "H", 3,
      ["Sterilisation by autoclave uses:", [ "Dry heat at 160 °C for 2 hours", "Ethylene oxide gas", "Boiling water for 5 minutes", "Saturated steam under pressure, about 121 °C for 15–20 minutes"], "Autoclaving uses moist heat under 15 psi pressure at 121 °C; dry heat ovens use 160 °C for about 2 hours."],
      ["ऑटोक्लेव द्वारा निर्जीवीकरण में किसका उपयोग होता है?", ["160 °C पर 2 घंटे शुष्क ऊष्मा", "एथिलीन ऑक्साइड गैस", "5 मिनट उबलता पानी", "दाब में संतृप्त भाप, लगभग 121 °C पर 15–20 मिनट"], "ऑटोक्लेव में 15 psi दाब पर 121 °C की नम ऊष्मा उपयोग होती है; शुष्क ऊष्मा ओवन में लगभग 2 घंटे 160 °C।"]),
    q(0, N, "fundamentals", "M", 0,
      ["Before giving a drug, the nurse checks the patient's identity primarily to prevent:", ["Medication errors", "Bed sores", "Dehydration", "Constipation"], "Correct patient identification is the first safeguard against giving a drug to the wrong person."],
      ["दवा देने से पहले नर्स रोगी की पहचान मुख्य रूप से किसे रोकने के लिए जाँचती है?", ["दवा संबंधी त्रुटियाँ", "शय्या-व्रण", "निर्जलीकरण", "कब्ज़"], "सही रोगी की पहचान गलत व्यक्ति को दवा देने के विरुद्ध पहली सुरक्षा है।"]),
    q(0, N, "fundamentals", "H", 2,
      ["A patient's blood pressure is 150/95 mmHg. The '95' indicates:", ["Pulse pressure", "Systolic pressure", "Diastolic pressure", "Mean arterial pressure"], "The lower figure is diastolic pressure (during ventricular relaxation); pulse pressure here is 150 – 95 = 55 mmHg."],
      ["एक रोगी का रक्तचाप 150/95 mmHg है। '95' क्या दर्शाता है?", ["नाड़ी दाब", "प्रकुंचन (सिस्टोलिक) दाब", "अनुशिथिलन (डायस्टोलिक) दाब", "माध्य धमनी दाब"], "नीचे वाला अंक डायस्टोलिक दाब है (निलय के शिथिल होने पर); यहाँ नाड़ी दाब 150 – 95 = 55 mmHg है।"]),
    q(0, N, "fundamentals", "M", 3,
      ["The first step of the nursing process is:", ["Planning", "Evaluation", "Implementation", "Assessment"], "Nursing process: assessment, nursing diagnosis, planning, implementation, evaluation (ADPIE)."],
      ["नर्सिंग प्रक्रिया का पहला चरण है:", ["योजना", "मूल्यांकन", "कार्यान्वयन", "आकलन"], "नर्सिंग प्रक्रिया: आकलन, नर्सिंग निदान, योजना, कार्यान्वयन, मूल्यांकन (ADPIE)।"]),
    q(0, N, "fundamentals", "H", 1,
      ["An IV infusion of 1000 mL is to run over 8 hours with a drop factor of 20 drops/mL. The flow rate is about:", ["21 drops/min", "42 drops/min", "63 drops/min", "125 drops/min"], "Drops/min = (volume × drop factor) ÷ time in minutes = (1000 × 20) ÷ 480 ≈ 41.7, i.e. about 42."],
      ["1000 mL IV द्रव 8 घंटे में चढ़ाना है और ड्रॉप फ़ैक्टर 20 बूँद/mL है। प्रवाह दर लगभग है:", ["21 बूँद/मिनट", "42 बूँद/मिनट", "63 बूँद/मिनट", "125 बूँद/मिनट"], "बूँद/मिनट = (मात्रा × ड्रॉप फ़ैक्टर) ÷ मिनट में समय = (1000 × 20) ÷ 480 ≈ 41.7, अर्थात् लगभग 42।"], "Math.round(1000*20/480)"),
    q(0, N, "fundamentals", "M", 2,
      ["Oral care for an unconscious patient should be done with the patient in:", ["Supine position with head straight", "Prone position", "Lateral (side-lying) position", "Sitting upright"], "Side-lying with the head turned lets fluid drain from the mouth and prevents aspiration."],
      ["अचेत रोगी की मुख-देखभाल किस स्थिति में करनी चाहिए?", ["सिर सीधा रखकर पीठ के बल", "पेट के बल", "करवट (पार्श्व) स्थिति", "सीधा बैठाकर"], "करवट की स्थिति में सिर मोड़ने से मुँह से द्रव बह जाता है और फेफड़ों में जाने (एस्पिरेशन) से बचाव होता है।"]),
    q(0, N, "fundamentals", "H", 0,
      ["Which is the correct sequence for removing personal protective equipment (PPE) as per CDC guidance?", ["Gloves, gown, goggles/face shield, mask", "Mask, gloves, gown, goggles", "Goggles, mask, gloves, gown", "Gown, mask, gloves, goggles"], "Doffing order: gloves first (most contaminated), then goggles/face shield and gown, and mask or respirator last; CDC also allows gown and gloves removed together."],
      ["CDC मार्गदर्शन के अनुसार व्यक्तिगत सुरक्षा उपकरण (PPE) उतारने का सही क्रम कौन-सा है?", ["दस्ताने, गाउन, चश्मा/फ़ेस शील्ड, मास्क", "मास्क, दस्ताने, गाउन, चश्मा", "चश्मा, मास्क, दस्ताने, गाउन", "गाउन, मास्क, दस्ताने, चश्मा"], "उतारने का क्रम: पहले दस्ताने (सबसे दूषित), फिर चश्मा/फ़ेस शील्ड और गाउन, अंत में मास्क; CDC गाउन और दस्ताने एक साथ उतारने की भी अनुमति देता है।"]),
    q(0, N, "fundamentals", "M", 1,
      ["The normal urine output of an adult is at least:", ["0.1 mL/kg/hour", "0.5 mL/kg/hour", "5 mL/kg/hour", "10 mL/kg/hour"], "Adult output below 0.5 mL/kg/hour (about 30 mL/hour) indicates oliguria and needs attention."],
      ["वयस्क का सामान्य मूत्र उत्पादन कम से कम होता है:", ["0.1 mL/kg/घंटा", "0.5 mL/kg/घंटा", "5 mL/kg/घंटा", "10 mL/kg/घंटा"], "वयस्क में 0.5 mL/kg/घंटा (लगभग 30 mL/घंटा) से कम मूत्र अल्पमूत्रता दर्शाता है और ध्यान माँगता है।"]),
    q(0, N, "fundamentals", "M", 3,
      ["Hypoglycaemia in a diabetic patient is most likely to show:", ["Dry hot skin and deep breathing", "Fruity breath and polyuria", "Slow pulse and warm skin", "Sweating, tremors and confusion"], "Low blood sugar causes sweating, shakiness, palpitations and confusion; fruity breath and deep breathing suggest ketoacidosis."],
      ["मधुमेह रोगी में हाइपोग्लाइसीमिया सबसे अधिक किस रूप में दिखेगा?", ["सूखी गर्म त्वचा और गहरी साँस", "फल जैसी गंध वाली साँस और बहुमूत्रता", "धीमी नाड़ी और गर्म त्वचा", "पसीना, कंपन और भ्रम"], "कम रक्त शर्करा से पसीना, कंपकंपी, धड़कन और भ्रम होता है; फल जैसी गंध और गहरी साँस कीटोएसिडोसिस के संकेत हैं।"]),
    q(0, N, "anatomy-physiology", "M", 2,
      ["The universal donor blood group is:", ["AB positive", "A negative", "O negative", "B positive"], "O negative red cells lack A, B and Rh D antigens, so they can be given in emergencies to any recipient."],
      ["सर्वदाता रक्त समूह है:", ["AB पॉज़िटिव", "A नेगेटिव", "O नेगेटिव", "B पॉज़िटिव"], "O नेगेटिव लाल कोशिकाओं में A, B और Rh D प्रतिजन नहीं होते, इसलिए आपात में किसी भी प्राप्तकर्ता को दी जा सकती हैं।"]),
    q(0, N, "anatomy-physiology", "H", 0,
      ["Which hormone is called the 'emergency hormone' (fight or flight)?", ["Adrenaline", "Thyroxine", "Insulin", "Oxytocin"], "Adrenaline (epinephrine) from the adrenal medulla prepares the body for fight or flight."],
      ["किस हार्मोन को 'आपातकालीन हार्मोन' (लड़ो या भागो) कहा जाता है?", ["एड्रेनालिन", "थायरॉक्सिन", "इंसुलिन", "ऑक्सीटोसिन"], "अधिवृक्क मज्जा से निकला एड्रेनालिन (एपिनेफ़्रिन) शरीर को लड़ने या भागने के लिए तैयार करता है।"]),
    q(0, N, "anatomy-physiology", "M", 3,
      ["The number of bones in the adult human skeleton is:", ["300", "212", "186", "206"], "An adult has 206 bones; a newborn has about 300, many of which fuse."],
      ["वयस्क मानव कंकाल में हड्डियों की संख्या है:", ["300", "212", "186", "206"], "वयस्क में 206 हड्डियाँ होती हैं; नवजात में लगभग 300, जिनमें से कई जुड़ जाती हैं।"]),
    q(0, N, "anatomy-physiology", "H", 1,
      ["The heart valve between the left atrium and left ventricle is the:", ["Tricuspid valve", "Mitral (bicuspid) valve", "Pulmonary valve", "Aortic valve"], "Mitral valve: left atrium to left ventricle; tricuspid: right atrium to right ventricle."],
      ["बाएँ अलिंद और बाएँ निलय के बीच हृदय कपाट है:", ["त्रिवलनी (ट्राइकस्पिड) कपाट", "मिट्रल (द्विवलनी) कपाट", "फुफ्फुसीय कपाट", "महाधमनी कपाट"], "मिट्रल कपाट: बायाँ अलिंद से बायाँ निलय; ट्राइकस्पिड: दायाँ अलिंद से दायाँ निलय।"]),
    q(0, N, "anatomy-physiology", "M", 0,
      ["The part of the brain that controls balance and coordination is the:", ["Cerebellum", "Cerebrum", "Medulla oblongata", "Hypothalamus"], "The cerebellum coordinates voluntary movement, posture and balance."],
      ["मस्तिष्क का कौन-सा भाग संतुलन और समन्वय नियंत्रित करता है?", ["अनुमस्तिष्क (सेरिबेलम)", "प्रमस्तिष्क (सेरिब्रम)", "मेडुला ऑब्लांगेटा", "हाइपोथैलेमस"], "अनुमस्तिष्क ऐच्छिक गति, मुद्रा और संतुलन का समन्वय करता है।"]),
    q(0, N, "anatomy-physiology", "H", 2,
      ["Most of the absorption of digested food takes place in the:", ["Stomach", "Large intestine", "Small intestine", "Oesophagus"], "The small intestine, with villi and microvilli, absorbs most nutrients; the large intestine mainly absorbs water."],
      ["पचे हुए भोजन का अधिकांश अवशोषण कहाँ होता है?", ["आमाशय", "बड़ी आँत", "छोटी आँत", "ग्रासनली"], "अंकुरों और सूक्ष्मांकुरों वाली छोटी आँत अधिकांश पोषक तत्व अवशोषित करती है; बड़ी आँत मुख्यतः पानी।"]),
    q(0, N, "anatomy-physiology", "M", 1,
      ["Normal haemoglobin in an adult woman is approximately:", ["6–8 g/dL", "12–15 g/dL", "18–20 g/dL", "3–5 g/dL"], "Adult women typically have 12–15 g/dL and men 13–17 g/dL; below 12 g/dL in non-pregnant women is anaemia (WHO)."],
      ["वयस्क महिला में सामान्य हीमोग्लोबिन लगभग होता है:", ["6–8 g/dL", "12–15 g/dL", "18–20 g/dL", "3–5 g/dL"], "वयस्क महिलाओं में सामान्यतः 12–15 g/dL और पुरुषों में 13–17 g/dL; गैर-गर्भवती महिलाओं में 12 g/dL से कम एनीमिया है (WHO)।"]),
    q(0, N, "anatomy-physiology", "H", 3,
      ["Antidiuretic hormone (ADH) is released from the:", ["Anterior pituitary", "Adrenal cortex", "Thyroid gland", "Posterior pituitary"], "ADH (vasopressin) is made in the hypothalamus and released from the posterior pituitary; it makes the kidneys conserve water."],
      ["प्रतिमूत्रल हार्मोन (ADH) कहाँ से मुक्त होता है?", ["अग्र पीयूष ग्रंथि", "अधिवृक्क वल्कुट", "थायरॉइड ग्रंथि", "पश्च पीयूष ग्रंथि"], "ADH (वैसोप्रेसिन) हाइपोथैलेमस में बनता है और पश्च पीयूष ग्रंथि से मुक्त होता है; यह गुर्दों को पानी बचाने को प्रेरित करता है।"]),
    q(0, N, "anatomy-physiology", "E", 0,
      ["Which is the largest organ of the human body?", ["Skin", "Liver", "Brain", "Lungs"], "The skin is the largest organ by surface area and weight; the liver is the largest internal organ."],
      ["मानव शरीर का सबसे बड़ा अंग है:", ["त्वचा", "यकृत", "मस्तिष्क", "फेफड़े"], "क्षेत्रफल और भार से त्वचा सबसे बड़ा अंग है; यकृत सबसे बड़ा आंतरिक अंग है।"]),
  ],
];

export const nursingMedSurg: PatwariQuestion[][] = [
  [
    q(0, N, "medical-surgical", "H", 1,
      ["In adult CPR, the recommended rate of chest compressions is:", ["60–80 per minute", "100–120 per minute", "140–160 per minute", "40–60 per minute"], "AHA guidelines: 100–120 compressions/min at a depth of 5–6 cm, ratio 30:2 with breaths."],
      ["वयस्क CPR में छाती संपीड़न की अनुशंसित दर है:", ["60–80 प्रति मिनट", "100–120 प्रति मिनट", "140–160 प्रति मिनट", "40–60 प्रति मिनट"], "AHA दिशानिर्देश: 5–6 सेमी गहराई पर 100–120 संपीड़न/मिनट, साँसों के साथ 30:2 अनुपात।"]),
    q(0, N, "medical-surgical", "M", 2,
      ["The classic triad of diabetes mellitus is:", ["Fever, rash, joint pain", "Headache, vomiting, neck stiffness", "Polyuria, polydipsia, polyphagia", "Cough, fever, weight gain"], "Excess urination, thirst and hunger are the classic symptoms of diabetes."],
      ["मधुमेह के तीन प्रमुख लक्षण हैं:", ["बुख़ार, चकत्ते, जोड़ों का दर्द", "सिरदर्द, उल्टी, गर्दन में अकड़न", "बहुमूत्रता, अतितृष्णा, अतिक्षुधा", "खाँसी, बुख़ार, वज़न बढ़ना"], "अधिक पेशाब, प्यास और भूख मधुमेह के प्रमुख लक्षण हैं।"]),
    q(0, N, "medical-surgical", "H", 0,
      ["A patient with a myocardial infarction typically complains of:", ["Crushing chest pain radiating to the left arm or jaw", "Pain in the right lower abdomen", "Itching all over the body", "Sudden loss of vision only"], "MI pain is central, crushing, lasting over 20 minutes and often radiates to the left arm, neck or jaw, with sweating."],
      ["मायोकार्डियल इन्फ़ार्क्शन (हृदयाघात) का रोगी सामान्यतः किसकी शिकायत करता है?", ["बाएँ हाथ या जबड़े तक फैलता छाती में भारी दबाव वाला दर्द", "पेट के दाएँ निचले भाग में दर्द", "पूरे शरीर में खुजली", "केवल अचानक दृष्टि-हानि"], "हृदयाघात का दर्द छाती के बीच, दबाने वाला, 20 मिनट से अधिक, अक्सर बाएँ हाथ, गर्दन या जबड़े तक फैलता है और पसीना आता है।"]),
    q(0, N, "medical-surgical", "M", 3,
      ["Pain at McBurney's point suggests:", ["Cholecystitis", "Pancreatitis", "Renal colic", "Appendicitis"], "McBurney's point lies one-third of the way from the right anterior superior iliac spine to the umbilicus; tenderness there suggests appendicitis."],
      ["मैकबर्नी बिंदु पर दर्द किसका संकेत है?", ["पित्ताशय शोथ", "अग्न्याशय शोथ", "वृक्क शूल", "एपेंडिसाइटिस"], "मैकबर्नी बिंदु दाईं अग्र ऊर्ध्व इलियक कंटिका से नाभि की ओर एक-तिहाई दूरी पर है; वहाँ दर्द एपेंडिसाइटिस दर्शाता है।"]),
    q(0, N, "medical-surgical", "H", 2,
      ["The 'Rule of Nines' is used to:", ["Calculate drug doses in children", "Count respiratory rate", "Estimate the body surface area burned", "Grade muscle power"], "In adults: head 9%, each arm 9%, each leg 18%, front and back of trunk 18% each, perineum 1%."],
      ["'नौ का नियम' (Rule of Nines) किसके लिए उपयोग होता है?", ["बच्चों में दवा की मात्रा निकालना", "श्वसन दर गिनना", "जले हुए शरीर-सतह क्षेत्र का अनुमान", "पेशी-शक्ति का श्रेणीकरण"], "वयस्कों में: सिर 9%, हर बाँह 9%, हर टाँग 18%, धड़ का आगे-पीछे 18-18%, पेरिनियम 1%।"]),
    q(0, N, "medical-surgical", "M", 1,
      ["The drug of choice for anaphylactic shock is:", ["Paracetamol", "Adrenaline (epinephrine) IM", "Atropine", "Furosemide"], "Intramuscular adrenaline 0.5 mg (1:1000) in adults is first-line treatment for anaphylaxis."],
      ["एनाफ़ाइलैक्टिक शॉक की प्रथम चयन औषधि है:", ["पैरासिटामॉल", "एड्रेनालिन (एपिनेफ़्रिन) IM", "एट्रोपिन", "फ़्यूरोसेमाइड"], "वयस्कों में 0.5 mg (1:1000) अंतःपेशीय एड्रेनालिन एनाफ़ाइलैक्सिस का पहला उपचार है।"]),
    q(0, N, "medical-surgical", "H", 3,
      ["A patient on digoxin has a pulse of 52/min. The nurse should:", ["Give the dose and record it", "Double the next dose", "Give it with milk", "Withhold the dose and inform the doctor"], "Digoxin slows the heart; an apical pulse below 60/min in adults is a reason to hold the dose and report possible toxicity."],
      ["डिगॉक्सिन ले रहे रोगी की नाड़ी 52/मिनट है। नर्स को क्या करना चाहिए?", ["खुराक देकर दर्ज करना", "अगली खुराक दोगुनी करना", "दूध के साथ देना", "खुराक रोककर डॉक्टर को सूचित करना"], "डिगॉक्सिन हृदय गति धीमी करता है; वयस्क में शीर्ष नाड़ी 60/मिनट से कम हो तो खुराक रोककर संभावित विषाक्तता की सूचना देनी चाहिए।"]),
    q(0, N, "medical-surgical", "M", 0,
      ["Hypertension in adults is generally diagnosed when blood pressure is persistently at or above:", ["140/90 mmHg", "120/80 mmHg", "110/70 mmHg", "160/110 mmHg only"], "Indian and WHO practice uses ≥140/90 mmHg on repeated readings; 160/110 indicates severe hypertension."],
      ["वयस्कों में उच्च रक्तचाप सामान्यतः तब माना जाता है जब रक्तचाप लगातार इससे अधिक या बराबर हो:", ["140/90 mmHg", "120/80 mmHg", "110/70 mmHg", "केवल 160/110 mmHg"], "भारतीय और WHO व्यवहार में बार-बार की रीडिंग पर ≥140/90 mmHg; 160/110 गंभीर उच्च रक्तचाप दर्शाता है।"]),
    q(0, N, "medical-surgical", "H", 1,
      ["Which position is best for a patient with severe breathlessness due to heart failure?", ["Trendelenburg", "High Fowler's, legs dependent", "Flat supine", "Prone"], "Sitting upright with legs down reduces venous return and eases lung congestion."],
      ["हृदय विफलता के कारण तीव्र साँस फूलने वाले रोगी के लिए सबसे अच्छी स्थिति कौन-सी है?", ["ट्रेंडेलेनबर्ग", "हाई फ़ाउलर, पैर नीचे लटके", "सीधा पीठ के बल", "पेट के बल"], "पैर नीचे करके सीधा बैठाने से शिरा-वापसी घटती है और फेफड़ों का जमाव कम होता है।"]),
    q(0, N, "medical-surgical", "M", 2,
      ["Jaundice becomes visible when serum bilirubin exceeds about:", ["0.5 mg/dL", "1 mg/dL", "2–3 mg/dL", "10 mg/dL"], "Normal bilirubin is up to about 1 mg/dL; yellow sclera appear when it exceeds about 2–3 mg/dL."],
      ["सीरम बिलीरुबिन लगभग कितने से अधिक होने पर पीलिया दिखने लगता है?", ["0.5 mg/dL", "1 mg/dL", "2–3 mg/dL", "10 mg/dL"], "सामान्य बिलीरुबिन लगभग 1 mg/dL तक होता है; 2–3 mg/dL से अधिक होने पर आँखों का सफ़ेद भाग पीला दिखता है।"]),
    q(0, N, "medical-surgical", "H", 0,
      ["After a thyroidectomy, the nurse watches for tingling around the mouth and muscle twitching because of possible:", ["Hypocalcaemia from parathyroid damage", "Hyperkalaemia", "Hypoglycaemia", "Hypernatraemia"], "Accidental injury or removal of parathyroid glands lowers calcium, causing tetany (Chvostek's and Trousseau's signs)."],
      ["थायरॉइडेक्टॉमी के बाद नर्स मुँह के आसपास झनझनाहट और पेशियों की फड़कन पर नज़र रखती है, क्योंकि संभावित है:", ["पैराथायरॉइड क्षति से हाइपोकैल्सीमिया", "हाइपरकेलीमिया", "हाइपोग्लाइसीमिया", "हाइपरनेट्रीमिया"], "पैराथायरॉइड ग्रंथियों को चोट या उनके निकल जाने से कैल्शियम घटता है, जिससे टेटनी (शवोस्टेक और ट्रूसो चिह्न) होती है।"]),
    q(0, N, "medical-surgical", "M", 3,
      ["Kussmaul breathing (deep, rapid breathing) is typical of:", ["Asthma attack", "Pneumothorax", "Opioid overdose", "Diabetic ketoacidosis"], "In DKA the body blows off CO₂ to compensate for metabolic acidosis; opioid overdose causes slow, shallow breathing."],
      ["कुसमाउल श्वसन (गहरी, तेज़ साँस) किसकी विशेषता है?", ["दमा का दौरा", "न्यूमोथोरैक्स", "ओपिऑइड ओवरडोज़", "डायबिटिक कीटोएसिडोसिस"], "DKA में शरीर चयापचयी अम्लता की भरपाई के लिए CO₂ बाहर निकालता है; ओपिऑइड ओवरडोज़ में साँस धीमी और उथली होती है।"]),
    q(0, N, "medical-surgical", "M", 2,
      ["The causative organism of tuberculosis is:", ["Vibrio cholerae", "Salmonella typhi", "Mycobacterium tuberculosis", "Plasmodium vivax"], "TB is caused by Mycobacterium tuberculosis, discovered by Robert Koch in 1882."],
      ["क्षय रोग (टीबी) का कारक जीव है:", ["विब्रियो कॉलेरी", "साल्मोनेला टाइफ़ी", "माइकोबैक्टीरियम ट्यूबरकुलोसिस", "प्लाज़्मोडियम वाइवैक्स"], "टीबी माइकोबैक्टीरियम ट्यूबरकुलोसिस से होता है, जिसे रॉबर्ट कोच ने 1882 में खोजा।"]),
    q(0, N, "medical-surgical", "H", 1,
      ["A post-operative patient has a fast thready pulse, falling BP and cold clammy skin. The most likely problem is:", ["Infection of the wound", "Hypovolaemic shock from haemorrhage", "Urinary retention", "Paralytic ileus"], "Tachycardia, hypotension and cold clammy skin after surgery point to blood loss and hypovolaemic shock."],
      ["शल्यक्रिया के बाद रोगी की नाड़ी तेज़ व क्षीण है, रक्तचाप गिर रहा है और त्वचा ठंडी व चिपचिपी है। सबसे संभावित समस्या है:", ["घाव में संक्रमण", "रक्तस्राव से हाइपोवोलेमिक शॉक", "मूत्र अवरोध", "पैरालिटिक इलियस"], "शल्यक्रिया के बाद तेज़ नाड़ी, निम्न रक्तचाप और ठंडी चिपचिपी त्वचा रक्त-हानि और हाइपोवोलेमिक शॉक दर्शाते हैं।"]),
    q(0, N, "medical-surgical", "M", 0,
      ["Peptic ulcer disease is most commonly associated with infection by:", ["Helicobacter pylori", "Escherichia coli", "Staphylococcus aureus", "Candida albicans"], "H. pylori infection and NSAID use are the two main causes of peptic ulcers."],
      ["पेप्टिक अल्सर रोग सबसे अधिक किसके संक्रमण से जुड़ा है?", ["हेलिकोबैक्टर पाइलोरी", "एशेरिकिया कोलाई", "स्टैफ़िलोकोकस ऑरियस", "कैंडिडा एल्बिकेन्स"], "एच. पाइलोरी संक्रमण और NSAID का उपयोग पेप्टिक अल्सर के दो मुख्य कारण हैं।"]),
    q(0, N, "medical-surgical", "H", 3,
      ["In a patient with chronic COPD, high-flow oxygen should be avoided because it may:", ["Cause hyperglycaemia", "Raise blood pressure sharply", "Cause bradycardia", "Reduce the hypoxic drive to breathe and cause CO₂ retention"], "Some COPD patients rely on low oxygen to drive breathing; target SpO₂ is usually 88–92% with controlled oxygen."],
      ["दीर्घकालिक COPD रोगी में अधिक प्रवाह ऑक्सीजन से क्यों बचना चाहिए?", [ "इससे हाइपरग्लाइसीमिया होता है", "इससे रक्तचाप तेज़ी से बढ़ता है", "इससे ब्रैडीकार्डिया होता है", "इससे साँस की हाइपॉक्सिक प्रेरणा घटकर CO₂ जमा हो सकती है"], "कुछ COPD रोगी साँस लेने के लिए कम ऑक्सीजन पर निर्भर होते हैं; नियंत्रित ऑक्सीजन से लक्ष्य SpO₂ प्रायः 88–92% रखा जाता है।"]),
    q(0, N, "medical-surgical", "M", 1,
      ["Which is a sign of raised intracranial pressure?", ["Tachycardia with low BP", "Bradycardia, widening pulse pressure and irregular breathing", "Fever with rash", "Excessive sweating only"], "Cushing's triad — bradycardia, hypertension with widened pulse pressure and irregular respiration — signals raised ICP."],
      ["बढ़े हुए अंतःकपालीय दाब का संकेत कौन-सा है?", ["निम्न रक्तचाप के साथ टैकीकार्डिया", "ब्रैडीकार्डिया, बढ़ता नाड़ी-दाब और अनियमित साँस", "चकत्तों के साथ बुख़ार", "केवल अत्यधिक पसीना"], "कुशिंग त्रयी — ब्रैडीकार्डिया, बढ़े नाड़ी-दाब सहित उच्च रक्तचाप और अनियमित श्वसन — बढ़े ICP का संकेत है।"]),
    q(0, N, "medical-surgical", "H", 2,
      ["Before blood transfusion, the most important check to prevent a fatal reaction is:", ["Patient's weight", "Room temperature", "ABO and Rh compatibility with patient identity at the bedside", "Speed of the infusion pump"], "Bedside verification of patient identity and blood unit compatibility prevents ABO-incompatible transfusion."],
      ["रक्ताधान से पहले घातक प्रतिक्रिया रोकने के लिए सबसे महत्वपूर्ण जाँच है:", ["रोगी का वज़न", "कमरे का तापमान", "बिस्तर के पास रोगी की पहचान सहित ABO और Rh अनुकूलता", "इन्फ़्यूज़न पंप की गति"], "बिस्तर के पास रोगी की पहचान और रक्त-इकाई की अनुकूलता का सत्यापन ABO-असंगत रक्ताधान को रोकता है।"]),
    q(0, N, "medical-surgical", "M", 3,
      ["The normal fasting blood glucose level in adults is:", ["40–60 mg/dL", "140–200 mg/dL", "200–250 mg/dL", "70–100 mg/dL"], "Fasting glucose 70–100 mg/dL is normal; 100–125 is prediabetes and ≥126 on two occasions is diabetes."],
      ["वयस्कों में सामान्य उपवास रक्त शर्करा स्तर है:", ["40–60 mg/dL", "140–200 mg/dL", "200–250 mg/dL", "70–100 mg/dL"], "उपवास शर्करा 70–100 mg/dL सामान्य है; 100–125 प्री-डायबिटीज़ और दो बार ≥126 मधुमेह है।"]),
    q(0, N, "medical-surgical", "E", 0,
      ["The first aid for a minor burn is to:", ["Cool it under clean running water", "Apply ghee or toothpaste", "Burst the blisters", "Cover it with cotton wool"], "Cool running water for about 20 minutes limits tissue damage; home remedies and cotton wool are harmful."],
      ["मामूली जलन का प्राथमिक उपचार है:", ["साफ़ बहते पानी से ठंडा करना", "घी या टूथपेस्ट लगाना", "छाले फोड़ना", "रूई से ढकना"], "लगभग 20 मिनट बहता ठंडा पानी ऊतक-क्षति सीमित करता है; घरेलू नुस्ख़े और रूई हानिकारक हैं।"]),
  ],
  [
    q(0, N, "medical-surgical", "H", 2,
      ["For adult CPR by a single rescuer, the compression-to-ventilation ratio is:", ["15:2", "5:1", "30:2", "30:1"], "AHA: 30 compressions to 2 breaths for adults, whether one or two rescuers."],
      ["एकल बचावकर्ता द्वारा वयस्क CPR में संपीड़न और श्वास का अनुपात है:", ["15:2", "5:1", "30:2", "30:1"], "AHA: वयस्कों में 30 संपीड़न पर 2 साँसें, चाहे एक या दो बचावकर्ता हों।"]),
    q(0, N, "medical-surgical", "M", 0,
      ["A patient with chronic kidney disease should usually restrict:", ["Potassium and phosphorus", "Vitamin C", "Fibre", "Iron"], "Failing kidneys cannot excrete potassium and phosphate well, so their intake is limited along with sodium and fluids as advised."],
      ["दीर्घकालिक गुर्दा रोग के रोगी को सामान्यतः किसे सीमित करना चाहिए?", ["पोटैशियम और फ़ॉस्फ़ोरस", "विटामिन C", "रेशा", "लौह"], "विफल गुर्दे पोटैशियम और फ़ॉस्फ़ेट ठीक से नहीं निकाल पाते, इसलिए सलाह के अनुसार सोडियम और द्रव के साथ इन्हें सीमित किया जाता है।"]),
    q(0, N, "medical-surgical", "H", 3,
      ["Trousseau's sign (carpal spasm on inflating a BP cuff) indicates:", ["Hypercalcaemia", "Hyponatraemia", "Hyperkalaemia", "Hypocalcaemia"], "Carpal spasm with cuff inflation is a sign of latent tetany due to low calcium."],
      ["ट्रूसो चिह्न (बीपी कफ़ फुलाने पर कलाई की ऐंठन) दर्शाता है:", ["हाइपरकैल्सीमिया", "हाइपोनेट्रीमिया", "हाइपरकेलीमिया", "हाइपोकैल्सीमिया"], "कफ़ फुलाने पर कलाई की ऐंठन कम कैल्शियम से होने वाली गुप्त टेटनी का संकेत है।"]),
    q(0, N, "medical-surgical", "M", 1,
      ["The antidote for heparin overdose is:", ["Vitamin K", "Protamine sulphate", "Naloxone", "Atropine"], "Protamine sulphate neutralises heparin; vitamin K reverses warfarin; naloxone reverses opioids."],
      ["हेपरिन अधिमात्रा का प्रतिविष है:", ["विटामिन K", "प्रोटामिन सल्फ़ेट", "नैलोक्सोन", "एट्रोपिन"], "प्रोटामिन सल्फ़ेट हेपरिन को निष्क्रिय करता है; विटामिन K वारफ़रिन और नैलोक्सोन ओपिऑइड का असर उलटता है।"]),
    q(0, N, "medical-surgical", "H", 0,
      ["The earliest sign of hypoxia in a patient is often:", ["Restlessness and increased pulse rate", "Cyanosis of lips", "Clubbing of fingers", "Bradycardia"], "Restlessness, anxiety and tachycardia appear early; cyanosis is a late sign."],
      ["रोगी में हाइपॉक्सिया का सबसे पहला संकेत प्रायः होता है:", ["बेचैनी और बढ़ी हुई नाड़ी", "होंठों का नीलापन", "उँगलियों का क्लबिंग", "ब्रैडीकार्डिया"], "बेचैनी, घबराहट और टैकीकार्डिया पहले दिखते हैं; नीलापन देर का संकेत है।"]),
    q(0, N, "medical-surgical", "M", 2,
      ["A stroke affecting the left cerebral hemisphere commonly causes weakness of the:", ["Left side of the body", "Both legs only", "Right side of the body", "Face only on the left"], "Motor pathways cross, so a left-hemisphere stroke causes right-sided hemiparesis and often aphasia."],
      ["बाएँ प्रमस्तिष्क गोलार्ध को प्रभावित करने वाले स्ट्रोक से सामान्यतः किस भाग में कमज़ोरी होती है?", ["शरीर का बायाँ भाग", "केवल दोनों पैर", "शरीर का दायाँ भाग", "केवल बाईं ओर चेहरा"], "गामक मार्ग क्रॉस होते हैं, इसलिए बाएँ गोलार्ध के स्ट्रोक से दाईं ओर अर्धांगघात और प्रायः वाचाघात होता है।"]),
    q(0, N, "medical-surgical", "H", 1,
      ["After cataract surgery, a patient should be told to avoid:", ["Walking", "Bending, lifting heavy objects and rubbing the eye", "Eating solid food", "Sleeping on the back"], "Bending, straining and rubbing raise intraocular pressure or injure the wound."],
      ["मोतियाबिंद शल्यक्रिया के बाद रोगी को किससे बचने को कहना चाहिए?", ["चलने से", "झुकने, भारी वस्तु उठाने और आँख मलने से", "ठोस भोजन से", "पीठ के बल सोने से"], "झुकने, ज़ोर लगाने और मलने से अंतःनेत्र दाब बढ़ता है या घाव को चोट लगती है।"]),
    q(0, N, "medical-surgical", "M", 3,
      ["Which electrolyte imbalance is most dangerous for the heart, causing arrhythmias?", ["Hypernatraemia", "Hypochloraemia", "Hypermagnesaemia only", "Hyperkalaemia"], "High potassium causes peaked T waves and can lead to fatal arrhythmias and cardiac arrest."],
      ["कौन-सा इलेक्ट्रोलाइट असंतुलन हृदय के लिए सबसे ख़तरनाक है और अतालता कराता है?", ["हाइपरनेट्रीमिया", "हाइपोक्लोरीमिया", "केवल हाइपरमैग्नीसीमिया", "हाइपरकेलीमिया"], "उच्च पोटैशियम से नुकीली T तरंगें बनती हैं और घातक अतालता व हृदयगति-रोध हो सकता है।"]),
    q(0, N, "medical-surgical", "M", 0,
      ["Colostomy care includes:", [ "Checking that the stoma is moist and pink-red", "Keeping the stoma dry and pale", "Inserting fingers into the stoma daily", "Applying alcohol around the stoma"], "A healthy stoma is moist and red-pink; pale, dusky or black colour signals poor blood supply."],
      ["कोलोस्टॉमी देखभाल में शामिल है:", ["जाँचना कि स्टोमा नम और गुलाबी-लाल है", "स्टोमा को सूखा और पीला रखना", "रोज़ स्टोमा में उँगलियाँ डालना", "स्टोमा के आसपास अल्कोहल लगाना"], "स्वस्थ स्टोमा नम और लाल-गुलाबी होता है; पीला, धूसर या काला रंग कम रक्त-आपूर्ति का संकेत है।"]),
    q(0, N, "medical-surgical", "H", 2,
      ["Tetanus is caused by:", ["A virus entering through wounds", "Plasmodium falciparum", "Clostridium tetani toxin acting on nerves", "Mycobacterium leprae"], "The tetanospasmin toxin of Clostridium tetani causes muscle spasms such as lockjaw."],
      ["टिटनेस किसके कारण होता है?", [ "घावों से प्रवेश करने वाला विषाणु", "प्लाज़्मोडियम फ़ाल्सीपेरम", "तंत्रिकाओं पर कार्य करने वाला क्लॉस्ट्रिडियम टिटैनी का विष", "माइकोबैक्टीरियम लेप्री"], "क्लॉस्ट्रिडियम टिटैनी का टिटैनोस्पास्मिन विष जबड़ा बंद होने जैसी पेशी-ऐंठन कराता है।"]),
    q(0, N, "medical-surgical", "M", 1,
      ["An insulin injection is given by which route?", ["Intramuscular", "Subcutaneous", "Intradermal", "Oral"], "Routine insulin is given subcutaneously; regular insulin may be given IV in emergencies."],
      ["इंसुलिन इंजेक्शन किस मार्ग से दिया जाता है?", ["अंतःपेशीय", "त्वचा-अधः (सबक्यूटेनियस)", "इंट्राडर्मल", "मौखिक"], "सामान्यतः इंसुलिन त्वचा-अधः दिया जाता है; आपात में रेगुलर इंसुलिन IV दिया जा सकता है।"]),
    q(0, N, "medical-surgical", "H", 3,
      ["A patient with a chest drain: the underwater seal bottle must be kept:", ["Above the level of the chest", "At the level of the heart", "Clamped at all times", "Below the level of the chest"], "Keeping the drainage bottle below chest level prevents back-flow of fluid and air into the pleural space."],
      ["छाती ड्रेन वाले रोगी में जल-सील बोतल कहाँ रखी जानी चाहिए?", ["छाती के स्तर से ऊपर", "हृदय के स्तर पर", "हर समय क्लैंप करके", "छाती के स्तर से नीचे"], "बोतल को छाती के स्तर से नीचे रखने से द्रव और हवा का फुफ्फुसावरण में वापस जाना रुकता है।"]),
    q(0, N, "medical-surgical", "M", 2,
      ["Dengue fever is transmitted by the bite of:", ["Anopheles mosquito", "Culex mosquito", "Aedes aegypti mosquito", "Sand fly"], "Aedes aegypti, a day-biting mosquito, transmits dengue, chikungunya and Zika."],
      ["डेंगू बुख़ार किसके काटने से फैलता है?", ["एनोफ़िलीज़ मच्छर", "क्यूलेक्स मच्छर", "एडीज़ इजिप्टी मच्छर", "बालू मक्खी"], "दिन में काटने वाला एडीज़ इजिप्टी मच्छर डेंगू, चिकनगुनिया और ज़ीका फैलाता है।"]),
    q(0, N, "medical-surgical", "H", 0,
      ["In a patient with a fractured femur, a sudden onset of breathlessness, confusion and petechial rash 24–72 hours later suggests:", ["Fat embolism syndrome", "Pneumonia", "Allergic reaction", "Hypoglycaemia"], "Fat globules from long-bone fractures can lodge in lungs and brain, giving the triad of respiratory distress, confusion and petechiae."],
      ["फ़ीमर फ़्रैक्चर वाले रोगी में 24–72 घंटे बाद अचानक साँस फूलना, भ्रम और पेटीकियल चकत्ते किसका संकेत हैं?", ["वसा अंतःशल्यता सिंड्रोम", "निमोनिया", "एलर्जी प्रतिक्रिया", "हाइपोग्लाइसीमिया"], "लंबी हड्डियों के फ़्रैक्चर से वसा के कण फेफड़ों और मस्तिष्क में फँसकर श्वसन कष्ट, भ्रम और पेटीकिया की त्रयी देते हैं।"]),
    q(0, N, "medical-surgical", "M", 3,
      ["Which test is used to screen for cervical cancer?", ["Widal test", "Mantoux test", "ELISA", "Pap smear"], "The Papanicolaou (Pap) smear and VIA screen for cervical cancer; Widal is for typhoid, Mantoux for TB."],
      ["गर्भाशय-ग्रीवा कैंसर की जाँच के लिए कौन-सा परीक्षण होता है?", ["वाइडल परीक्षण", "मैंटू परीक्षण", "एलिसा", "पैप स्मीयर"], "पैपनिकोलाउ (पैप) स्मीयर और VIA गर्भाशय-ग्रीवा कैंसर की जाँच करते हैं; वाइडल टाइफ़ाइड और मैंटू टीबी के लिए है।"]),
    q(0, N, "medical-surgical", "H", 1,
      ["A patient on warfarin should have which test monitored?", ["Serum amylase", "PT/INR", "ESR", "Serum uric acid"], "Warfarin therapy is monitored with prothrombin time expressed as INR, usually targeting 2–3."],
      ["वारफ़रिन ले रहे रोगी में किस परीक्षण की निगरानी होनी चाहिए?", ["सीरम एमाइलेज़", "PT/INR", "ESR", "सीरम यूरिक एसिड"], "वारफ़रिन उपचार की निगरानी प्रोथ्रॉम्बिन टाइम (INR) से होती है, सामान्यतः लक्ष्य 2–3।"]),
    q(0, N, "medical-surgical", "M", 0,
      ["The main symptom of glaucoma if untreated is:", ["Gradual loss of peripheral vision", "Itching of eyelids", "Excess tear production only", "Colour change of iris"], "Raised intraocular pressure damages the optic nerve, causing tunnel vision and eventual blindness."],
      ["अनुपचारित ग्लूकोमा का मुख्य लक्षण है:", ["परिधीय दृष्टि का धीरे-धीरे लोप", "पलकों में खुजली", "केवल अधिक आँसू बनना", "परितारिका का रंग बदलना"], "बढ़ा अंतःनेत्र दाब दृष्टि-तंत्रिका को हानि पहुँचाता है, जिससे सुरंग-दृष्टि और अंततः अंधापन होता है।"]),
    q(0, N, "medical-surgical", "M", 2,
      ["A patient is NPO before surgery mainly to prevent:", ["Constipation", "Hypertension", "Aspiration of stomach contents during anaesthesia", "Wound infection"], "An empty stomach reduces the risk of vomiting and aspiration under anaesthesia."],
      ["शल्यक्रिया से पहले रोगी को NPO (मुँह से कुछ नहीं) मुख्यतः किसे रोकने के लिए रखा जाता है?", ["कब्ज़", "उच्च रक्तचाप", "एनेस्थीसिया के दौरान पेट की सामग्री का फेफड़ों में जाना", "घाव संक्रमण"], "ख़ाली पेट एनेस्थीसिया में उल्टी और एस्पिरेशन का जोखिम घटाता है।"]),
    q(0, N, "medical-surgical", "H", 3,
      ["Which finding in a patient receiving IV potassium chloride requires the nurse to stop the infusion?", ["Mild thirst", "Pulse 78/min", "Urine output 60 mL/hour", "Burning at the IV site and irregular pulse"], "KCl irritates veins and can cause arrhythmias; it must never be given as an IV push and needs adequate urine output."],
      ["IV पोटैशियम क्लोराइड ले रहे रोगी में किस स्थिति में नर्स को इन्फ़्यूज़न रोकना चाहिए?", ["हल्की प्यास", "नाड़ी 78/मिनट", "मूत्र 60 mL/घंटा", "IV स्थल पर जलन और अनियमित नाड़ी"], "KCl शिराओं में जलन और अतालता कर सकता है; इसे कभी IV पुश के रूप में नहीं देते और पर्याप्त मूत्र-उत्पादन आवश्यक है।"]),
    q(0, N, "medical-surgical", "E", 1,
      ["Which vitamin deficiency causes scurvy?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B12"], "Vitamin C deficiency causes scurvy with bleeding gums and poor wound healing."],
      ["किस विटामिन की कमी से स्कर्वी होता है?", ["विटामिन A", "विटामिन C", "विटामिन D", "विटामिन B12"], "विटामिन C की कमी से स्कर्वी होता है जिसमें मसूड़ों से ख़ून और घाव देर से भरना होता है।"]),
  ],
];

export const nursingCommunity: PatwariQuestion[][] = [
  [
    q(0, N, "community-health", "M", 1,
      ["Under the national immunisation schedule, BCG vaccine is given:", ["At 9 months", "At birth or as early as possible till one year", "At 5 years", "At 16 weeks of pregnancy"], "BCG is given at birth (or as early as possible till one year) intradermally on the left upper arm."],
      ["राष्ट्रीय टीकाकरण अनुसूची के अनुसार बीसीजी टीका कब दिया जाता है?", ["9 माह पर", "जन्म पर या एक वर्ष तक जितनी जल्दी हो सके", "5 वर्ष पर", "गर्भावस्था के 16 सप्ताह पर"], "बीसीजी जन्म पर (या एक वर्ष तक जितनी जल्दी हो) बाएँ ऊपरी बाँह में इंट्राडर्मल दिया जाता है।"]),
    q(0, N, "community-health", "H", 3,
      ["A Primary Health Centre in hilly and tribal areas covers a population of about:", ["1,20,000", "5,000", "80,000", "20,000"], "PHC norms: 30,000 population in plains and 20,000 in hilly/tribal areas; sub-centre 5,000 / 3,000; CHC 1,20,000 / 80,000."],
      ["पहाड़ी और जनजातीय क्षेत्रों में एक प्राथमिक स्वास्थ्य केंद्र लगभग कितनी जनसंख्या को सेवा देता है?", ["1,20,000", "5,000", "80,000", "20,000"], "PHC मानक: मैदानों में 30,000 और पहाड़ी/जनजातीय क्षेत्रों में 20,000; उपकेंद्र 5,000/3,000; CHC 1,20,000/80,000।"]),
    q(0, N, "midwifery", "M", 2,
      ["The normal duration of pregnancy counted from the first day of the last menstrual period is about:", ["240 days", "260 days", "280 days", "300 days"], "Full-term pregnancy is about 280 days (40 weeks) from LMP; Naegele's rule adds 9 months and 7 days to the LMP."],
      ["अंतिम मासिक धर्म के पहले दिन से गर्भावस्था की सामान्य अवधि लगभग है:", ["240 दिन", "260 दिन", "280 दिन", "300 दिन"], "पूर्ण-अवधि गर्भावस्था LMP से लगभग 280 दिन (40 सप्ताह) होती है; नेगेले नियम में LMP में 9 माह 7 दिन जोड़े जाते हैं।"]),
    q(0, N, "child-health", "M", 0,
      ["For how long after birth is exclusive breastfeeding recommended?", ["6 months", "3 months", "9 months", "12 months"], "WHO and India recommend exclusive breastfeeding for 6 months, with continued breastfeeding up to 2 years or beyond."],
      ["केवल स्तनपान की सलाह पहले कितने समय के लिए दी जाती है?", ["6 माह", "3 माह", "9 माह", "12 माह"], "WHO और भारत 6 माह तक केवल स्तनपान और 2 वर्ष या उससे अधिक तक स्तनपान जारी रखने की सलाह देते हैं।"]),
    q(0, N, "midwifery", "H", 1,
      ["The drug commonly used to prevent postpartum haemorrhage in the third stage of labour is:", ["Magnesium sulphate", "Oxytocin", "Nifedipine", "Paracetamol"], "Active management of the third stage uses oxytocin 10 IU IM within a minute of birth; magnesium sulphate is for eclampsia."],
      ["प्रसव की तीसरी अवस्था में प्रसवोत्तर रक्तस्राव रोकने के लिए सामान्यतः कौन-सी दवा उपयोग होती है?", ["मैग्नीशियम सल्फ़ेट", "ऑक्सीटोसिन", "निफ़ेडिपिन", "पैरासिटामॉल"], "तीसरी अवस्था के सक्रिय प्रबंधन में जन्म के एक मिनट के भीतर ऑक्सीटोसिन 10 IU IM दिया जाता है; मैग्नीशियम सल्फ़ेट एक्लेम्पसिया के लिए है।"]),
    q(0, N, "child-health", "H", 2,
      ["The APGAR score is assessed at:", ["Birth and 24 hours", "1 hour and 6 hours", "1 minute and 5 minutes after birth", "Only at 10 minutes"], "APGAR (appearance, pulse, grimace, activity, respiration) is scored at 1 and 5 minutes; total out of 10."],
      ["अपगार (APGAR) अंक कब आँके जाते हैं?", ["जन्म पर और 24 घंटे पर", "1 घंटे और 6 घंटे पर", "जन्म के 1 मिनट और 5 मिनट बाद", "केवल 10 मिनट पर"], "APGAR (रंग, नाड़ी, प्रतिक्रिया, सक्रियता, श्वसन) 1 और 5 मिनट पर आँका जाता है; कुल 10 में से।"]),
    q(0, N, "community-health", "M", 3,
      ["ASHA workers are part of which programme?", ["ICDS", "Mid-Day Meal", "Swachh Bharat", "National Health Mission"], "Accredited Social Health Activists were introduced under the National Rural Health Mission (2005), now part of the NHM."],
      ["आशा (ASHA) कार्यकर्ता किस कार्यक्रम का भाग हैं?", ["आईसीडीएस", "मध्याह्न भोजन", "स्वच्छ भारत", "राष्ट्रीय स्वास्थ्य मिशन"], "मान्यता प्राप्त सामाजिक स्वास्थ्य कार्यकर्ता राष्ट्रीय ग्रामीण स्वास्थ्य मिशन (2005) के तहत शुरू हुईं, अब NHM का भाग हैं।"]),
    q(0, N, "child-health", "M", 1,
      ["ORS is used mainly to treat:", ["Fever", "Dehydration due to diarrhoea", "Malnutrition", "Anaemia"], "Oral rehydration solution replaces water and salts lost in diarrhoea; zinc is added for 14 days in children."],
      ["ORS मुख्यतः किसके उपचार में उपयोग होता है?", ["बुख़ार", "दस्त के कारण निर्जलीकरण", "कुपोषण", "एनीमिया"], "ओरल रिहाइड्रेशन घोल दस्त में खोए पानी और लवण की पूर्ति करता है; बच्चों में 14 दिन ज़िंक भी दिया जाता है।"]),
    q(0, N, "midwifery", "H", 0,
      ["The drug of choice to control convulsions in eclampsia is:", ["Magnesium sulphate", "Diazepam only", "Phenytoin", "Oxytocin"], "Magnesium sulphate (Pritchard or Zuspan regimen) is first-line; monitor knee jerk, respiration and urine output."],
      ["एक्लेम्पसिया में दौरे रोकने की प्रथम चयन दवा है:", ["मैग्नीशियम सल्फ़ेट", "केवल डायज़ेपाम", "फ़िनाइटॉइन", "ऑक्सीटोसिन"], "मैग्नीशियम सल्फ़ेट (प्रिचर्ड या ज़ुस्पान विधि) पहली पसंद है; घुटने की प्रतिवर्त क्रिया, श्वसन और मूत्र पर नज़र रखें।"]),
    q(0, N, "community-health", "H", 2,
      ["The infant mortality rate is expressed per:", ["100 live births", "100,000 population", "1,000 live births", "1,000 population"], "IMR = infant deaths under one year per 1,000 live births in a year; MMR is per 100,000 live births."],
      ["शिशु मृत्यु दर किसके प्रति व्यक्त की जाती है?", ["100 जीवित जन्म", "1,00,000 जनसंख्या", "1,000 जीवित जन्म", "1,000 जनसंख्या"], "IMR = एक वर्ष में एक वर्ष से कम आयु की मृत्यु प्रति 1,000 जीवित जन्म; MMR प्रति 1,00,000 जीवित जन्म है।"]),
    q(0, N, "child-health", "M", 3,
      ["The first vaccine dose of measles-rubella (MR) under the schedule is given at:", ["6 weeks", "Birth", "5 years", "9–12 months"], "MR-1 at 9–12 months and MR-2 at 16–24 months."],
      ["अनुसूची के अनुसार खसरा-रूबेला (MR) की पहली खुराक कब दी जाती है?", ["6 सप्ताह पर", "जन्म पर", "5 वर्ष पर", "9–12 माह पर"], "MR-1 9–12 माह पर और MR-2 16–24 माह पर।"]),
    q(0, N, "midwifery", "M", 1,
      ["The first stage of labour ends with:", ["Delivery of the placenta", "Full dilatation of the cervix (10 cm)", "Delivery of the baby", "Rupture of membranes"], "Stage 1: onset of labour to full cervical dilatation; stage 2: to birth of the baby; stage 3: to delivery of placenta."],
      ["प्रसव की पहली अवस्था किसके साथ समाप्त होती है?", ["अपरा (प्लेसेंटा) के निकलने", "गर्भाशय-ग्रीवा के पूर्ण फैलाव (10 सेमी)", "शिशु के जन्म", "झिल्लियों के फटने"], "अवस्था 1: प्रसव आरंभ से ग्रीवा के पूर्ण फैलाव तक; अवस्था 2: शिशु के जन्म तक; अवस्था 3: अपरा निकलने तक।"]),
    q(0, N, "child-health", "H", 0,
      ["A newborn is considered 'low birth weight' if the birth weight is less than:", ["2,500 g", "3,000 g", "2,000 g", "1,500 g"], "WHO: low birth weight < 2,500 g; very low < 1,500 g; extremely low < 1,000 g."],
      ["नवजात को 'कम जन्म-भार' कब माना जाता है जब जन्म-भार इससे कम हो:", ["2,500 ग्राम", "3,000 ग्राम", "2,000 ग्राम", "1,500 ग्राम"], "WHO: कम जन्म-भार < 2,500 ग्राम; बहुत कम < 1,500 ग्राम; अत्यंत कम < 1,000 ग्राम।"]),
    q(0, N, "community-health", "M", 2,
      ["Janani Suraksha Yojana mainly promotes:", ["Child vaccination", "Mid-day meals", "Institutional deliveries through cash assistance", "Family planning operations"], "JSY (2005) under NHM gives cash incentives to pregnant women for delivering in health facilities."],
      ["जननी सुरक्षा योजना मुख्यतः किसे बढ़ावा देती है?", ["बाल टीकाकरण", "मध्याह्न भोजन", "नकद सहायता द्वारा संस्थागत प्रसव", "परिवार नियोजन ऑपरेशन"], "NHM के तहत JSY (2005) स्वास्थ्य संस्थानों में प्रसव के लिए गर्भवती महिलाओं को नकद प्रोत्साहन देती है।"]),
    q(0, N, "midwifery", "H", 3,
      ["During pregnancy, iron and folic acid supplementation under the national programme is typically:", ["Only in the first month", "Only after delivery", "One tablet a week", "One tablet daily from the second trimester for at least 180 days"], "Pregnant women get one IFA tablet (60 mg iron, 500 mcg folic acid) daily for 180 days from 14–16 weeks, continued 180 days postpartum (Anaemia Mukt Bharat)."],
      ["राष्ट्रीय कार्यक्रम के अंतर्गत गर्भावस्था में आयरन-फ़ोलिक एसिड पूरक सामान्यतः:", ["केवल पहले माह में", "केवल प्रसव के बाद", "सप्ताह में एक गोली", "दूसरी तिमाही से कम से कम 180 दिन तक रोज़ एक गोली"], "गर्भवती महिलाओं को 14–16 सप्ताह से 180 दिन रोज़ एक IFA गोली (60 mg आयरन, 500 mcg फ़ोलिक एसिड) और प्रसव के बाद 180 दिन (एनीमिया मुक्त भारत)।"]),
    q(0, N, "child-health", "M", 1,
      ["Kangaroo mother care is mainly used for:", ["Children with fever", "Low birth weight and preterm babies", "Children with rickets", "Adolescents with anaemia"], "Skin-to-skin contact keeps preterm/LBW babies warm, supports breastfeeding and lowers mortality."],
      ["कंगारू मदर केयर मुख्यतः किसके लिए उपयोग होती है?", ["बुख़ार वाले बच्चे", "कम जन्म-भार और समय से पहले जन्मे शिशु", "रिकेट्स वाले बच्चे", "एनीमिया वाले किशोर"], "त्वचा से त्वचा का संपर्क समय से पहले/कम भार वाले शिशुओं को गर्म रखता है, स्तनपान में मदद करता है और मृत्यु दर घटाता है।"]),
    q(0, N, "community-health", "H", 0,
      ["The 'cold chain' in immunisation refers to:", [ "Keeping vaccines at the recommended temperature from manufacture to use", "A chain of cold storage for food", "Cooling the patient after vaccination", "Storing vaccines in a deep freezer only"], "Most vaccines are kept at +2 to +8 °C throughout transport and storage; some (like OPV) are stored frozen at higher levels."],
      ["टीकाकरण में 'कोल्ड चेन' का अर्थ है:", [ "निर्माण से उपयोग तक टीकों को अनुशंसित तापमान पर रखना", "भोजन के लिए शीत भंडारण की शृंखला", "टीकाकरण के बाद रोगी को ठंडा करना", "टीकों को केवल डीप फ़्रीज़र में रखना"], "अधिकांश टीके परिवहन और भंडारण में +2 से +8 °C पर रखे जाते हैं; कुछ (जैसे OPV) ऊपरी स्तरों पर जमे हुए रखे जाते हैं।"]),
    q(0, N, "midwifery", "M", 2,
      ["Lochia that is red in colour during the first 3–4 days after delivery is called:", ["Lochia alba", "Lochia serosa", "Lochia rubra", "Lochia purulenta"], "Lochia rubra (days 1–4), serosa (about days 5–9), alba (about day 10 onward)."],
      ["प्रसव के बाद पहले 3–4 दिनों में लाल रंग का स्राव (लोकिया) कहलाता है:", ["लोकिया अल्बा", "लोकिया सीरोसा", "लोकिया रूब्रा", "लोकिया प्यूरुलेंटा"], "लोकिया रूब्रा (दिन 1–4), सीरोसा (लगभग दिन 5–9), अल्बा (लगभग दिन 10 से)।"]),
    q(0, N, "child-health", "H", 3,
      ["Severe acute malnutrition in a child aged 6–59 months is indicated by a mid-upper arm circumference of less than:", ["13.5 cm", "15 cm", "12.5 cm", "11.5 cm"], "MUAC < 11.5 cm indicates SAM; 11.5–12.5 cm is moderate acute malnutrition."],
      ["6–59 माह के बच्चे में गंभीर तीव्र कुपोषण तब माना जाता है जब मध्य-ऊपरी बाँह की परिधि इससे कम हो:", ["13.5 सेमी", "15 सेमी", "12.5 सेमी", "11.5 सेमी"], "MUAC < 11.5 सेमी SAM दर्शाता है; 11.5–12.5 सेमी मध्यम तीव्र कुपोषण है।"]),
    q(0, N, "community-health", "E", 0,
      ["On which date is World Health Day observed each year?", ["7 April", "1 December", "31 May", "24 March"], "7 April (WHO founding day); 1 December World AIDS Day; 31 May No Tobacco Day; 24 March TB Day."],
      ["विश्व स्वास्थ्य दिवस हर वर्ष कब मनाया जाता है?", ["7 अप्रैल", "1 दिसंबर", "31 मई", "24 मार्च"], "7 अप्रैल (WHO स्थापना दिवस); 1 दिसंबर विश्व एड्स दिवस; 31 मई तंबाकू निषेध दिवस; 24 मार्च टीबी दिवस।"]),
  ],
  [
    q(0, N, "community-health", "M", 2,
      ["A Sub-Health Centre (now Ayushman Arogya Mandir) in hilly areas covers about:", ["30,000 people", "10,000 people", "3,000 people", "1,000 people"], "Sub-centre norm: 5,000 population in plains and 3,000 in hilly/tribal areas."],
      ["पहाड़ी क्षेत्रों में उप-स्वास्थ्य केंद्र (अब आयुष्मान आरोग्य मंदिर) लगभग कितने लोगों को सेवा देता है?", ["30,000 लोग", "10,000 लोग", "3,000 लोग", "1,000 लोग"], "उपकेंद्र मानक: मैदानों में 5,000 और पहाड़ी/जनजातीय क्षेत्रों में 3,000 जनसंख्या।"]),
    q(0, N, "child-health", "H", 0,
      ["The pentavalent vaccine protects against:", [ "Diphtheria, pertussis, tetanus, hepatitis B and Hib", "Measles, mumps, rubella, polio and TB", "Typhoid, cholera, rabies, polio and tetanus", "Hepatitis A, B, C, D and E"], "Pentavalent (DPT + HepB + Hib) is given at 6, 10 and 14 weeks."],
      ["पेंटावेलेंट टीका किनसे सुरक्षा देता है?", [ "डिप्थीरिया, काली खाँसी, टिटनेस, हेपेटाइटिस B और Hib", "खसरा, कण्ठमाला, रूबेला, पोलियो और टीबी", "टाइफ़ाइड, हैज़ा, रेबीज़, पोलियो और टिटनेस", "हेपेटाइटिस A, B, C, D और E"], "पेंटावेलेंट (DPT + HepB + Hib) 6, 10 और 14 सप्ताह पर दिया जाता है।"]),
    q(0, N, "midwifery", "M", 3,
      ["Naegele's rule for the expected date of delivery is: first day of LMP plus:", ["7 months and 9 days", "10 months", "280 weeks", "9 months and 7 days"], "EDD = LMP + 9 months + 7 days (or LMP – 3 months + 7 days + 1 year)."],
      ["प्रसव की अनुमानित तिथि का नेगेले नियम है: LMP का पहला दिन जमा:", ["7 माह और 9 दिन", "10 माह", "280 सप्ताह", "9 माह और 7 दिन"], "EDD = LMP + 9 माह + 7 दिन (या LMP – 3 माह + 7 दिन + 1 वर्ष)।"]),
    q(0, N, "child-health", "M", 1,
      ["A child usually starts walking without support at about:", ["6 months", "12–15 months", "24–30 months", "36 months"], "Most children walk independently between 12 and 15 months; delay beyond 18 months needs assessment."],
      ["बच्चा सामान्यतः बिना सहारे चलना कब शुरू करता है?", ["6 माह", "12–15 माह", "24–30 माह", "36 माह"], "अधिकांश बच्चे 12 से 15 माह के बीच स्वतंत्र रूप से चलने लगते हैं; 18 माह के बाद देरी पर आकलन चाहिए।"]),
    q(0, N, "midwifery", "H", 2,
      ["Placenta praevia typically presents as:", [ "Painful bleeding with a hard tender uterus", "High fever with foul discharge", "Painless, recurrent bright-red bleeding in late pregnancy", "Sudden severe headache"], "Placenta praevia causes painless bleeding; painful bleeding with a tense uterus suggests abruptio placentae."],
      ["प्लेसेंटा प्रीविया सामान्यतः किस रूप में प्रकट होता है?", [ "कठोर, दर्दनाक गर्भाशय के साथ दर्दभरा रक्तस्राव", "दुर्गंधयुक्त स्राव के साथ तेज़ बुख़ार", "गर्भावस्था के अंतिम चरण में दर्द-रहित, बार-बार चमकीला लाल रक्तस्राव", "अचानक तीव्र सिरदर्द"], "प्लेसेंटा प्रीविया में दर्द-रहित रक्तस्राव होता है; कठोर गर्भाशय के साथ दर्दभरा रक्तस्राव एब्रप्शियो प्लेसेंटी दर्शाता है।"]),
    q(0, N, "community-health", "H", 1,
      ["Mission Indradhanush was launched in 2014 to:", ["Eliminate malaria", "Achieve full immunisation coverage of children and pregnant women", "Provide free spectacles", "Promote sanitation in schools"], "Mission Indradhanush aims to reach unvaccinated and partially vaccinated children and pregnant women."],
      ["मिशन इंद्रधनुष 2014 में किस उद्देश्य से शुरू हुआ?", ["मलेरिया उन्मूलन", "बच्चों और गर्भवती महिलाओं का पूर्ण टीकाकरण", "मुफ़्त चश्मे देना", "विद्यालयों में स्वच्छता"], "मिशन इंद्रधनुष बिना टीके वाले और आंशिक टीके वाले बच्चों व गर्भवती महिलाओं तक पहुँचने का लक्ष्य रखता है।"]),
    q(0, N, "child-health", "M", 0,
      ["The anterior fontanelle of an infant usually closes by:", ["12–18 months", "2–3 months", "4 years", "At birth"], "The posterior fontanelle closes by about 2–3 months and the anterior by 12–18 months."],
      ["शिशु का अग्र कपाल-अंतराल (फ़ॉन्टानेल) सामान्यतः कब बंद होता है?", ["12–18 माह तक", "2–3 माह तक", "4 वर्ष तक", "जन्म पर"], "पश्च फ़ॉन्टानेल लगभग 2–3 माह और अग्र फ़ॉन्टानेल 12–18 माह तक बंद होता है।"]),
    q(0, N, "midwifery", "M", 2,
      ["The minimum number of antenatal visits recommended under national guidelines is:", ["One", "Two", "Four", "Twelve"], "India recommends at least four ANC visits including registration in the first trimester (WHO 2016 suggests eight contacts)."],
      ["राष्ट्रीय दिशानिर्देशों के अनुसार न्यूनतम प्रसव-पूर्व जाँचें कितनी होनी चाहिए?", ["एक", "दो", "चार", "बारह"], "भारत पहली तिमाही में पंजीकरण सहित कम से कम चार ANC जाँचों की सलाह देता है (WHO 2016 आठ संपर्क सुझाता है)।"]),
    q(0, N, "community-health", "H", 3,
      ["Which disease is targeted by the DOTS strategy?", ["Malaria", "Leprosy", "HIV/AIDS", "Tuberculosis"], "Directly Observed Treatment, Short-course was the core TB strategy; the programme is now the National TB Elimination Programme."],
      ["DOTS रणनीति किस रोग को लक्षित करती है?", ["मलेरिया", "कुष्ठ रोग", "एचआईवी/एड्स", "क्षय रोग"], "प्रत्यक्ष निगरानी उपचार, लघु अवधि टीबी की मुख्य रणनीति थी; कार्यक्रम अब राष्ट्रीय टीबी उन्मूलन कार्यक्रम है।"]),
    q(0, N, "child-health", "H", 2,
      ["Vitamin A prophylaxis under the national programme starts at 9 months with a dose of:", ["50,000 IU", "2,00,000 IU", "1,00,000 IU", "5,000 IU"], "First dose 1,00,000 IU at 9 months with MR-1, then 2,00,000 IU every 6 months up to 5 years (9 doses in all)."],
      ["राष्ट्रीय कार्यक्रम के तहत विटामिन A रोगनिरोधी खुराक 9 माह पर कितनी मात्रा से शुरू होती है?", ["50,000 IU", "2,00,000 IU", "1,00,000 IU", "5,000 IU"], "पहली खुराक 9 माह पर MR-1 के साथ 1,00,000 IU, फिर 5 वर्ष तक हर 6 माह 2,00,000 IU (कुल 9 खुराकें)।"]),
    q(0, N, "midwifery", "M", 0,
      ["The fetal heart rate is normally:", ["110–160 beats/min", "60–80 beats/min", "180–220 beats/min", "40–60 beats/min"], "A normal fetal heart rate is 110–160/min; persistent values outside this range suggest fetal distress."],
      ["भ्रूण की हृदय गति सामान्यतः होती है:", ["110–160 धड़कन/मिनट", "60–80 धड़कन/मिनट", "180–220 धड़कन/मिनट", "40–60 धड़कन/मिनट"], "सामान्य भ्रूण हृदय गति 110–160/मिनट है; इससे बाहर लगातार मान भ्रूण-संकट दर्शाते हैं।"]),
    q(0, N, "community-health", "M", 1,
      ["Chlorination of drinking water mainly protects against:", ["Fluorosis", "Water-borne bacterial diseases like cholera and typhoid", "Goitre", "Night blindness"], "Chlorine kills most bacteria in water; a residual of about 0.5 mg/L after 1 hour contact is the aim."],
      ["पीने के पानी का क्लोरीनीकरण मुख्यतः किससे सुरक्षा देता है?", ["फ़्लोरोसिस", "हैज़ा और टाइफ़ाइड जैसे जलजनित जीवाणु रोग", "घेंघा", "रतौंधी"], "क्लोरीन पानी के अधिकांश जीवाणु मारती है; 1 घंटे संपर्क के बाद लगभग 0.5 mg/L अवशिष्ट क्लोरीन का लक्ष्य होता है।"]),
    q(0, N, "child-health", "M", 3,
      ["Physiological jaundice in a full-term newborn usually appears:", ["Within the first 24 hours", "After 4 weeks", "Only at birth", "On the 2nd–3rd day and fades by about 2 weeks"], "Jaundice within 24 hours is pathological; physiological jaundice appears after 24 hours, peaks around day 3–5 and clears by about 2 weeks."],
      ["पूर्ण-अवधि नवजात में शारीरिक (फ़िज़ियोलॉजिकल) पीलिया सामान्यतः कब दिखता है?", ["पहले 24 घंटों में", "4 सप्ताह के बाद", "केवल जन्म पर", "दूसरे–तीसरे दिन और लगभग 2 सप्ताह में समाप्त"], "24 घंटे के भीतर पीलिया रोगजन्य है; शारीरिक पीलिया 24 घंटे बाद आता है, 3–5 दिन पर चरम पर और लगभग 2 सप्ताह में ठीक हो जाता है।"]),
    q(0, N, "midwifery", "H", 1,
      ["Postpartum haemorrhage after vaginal delivery is defined as blood loss of:", ["200 mL or more", "500 mL or more within 24 hours", "100 mL in the first hour", "1,500 mL only"], "PPH is blood loss ≥ 500 mL after vaginal birth (≥ 1,000 mL after caesarean) within 24 hours, or any loss causing instability."],
      ["योनि प्रसव के बाद प्रसवोत्तर रक्तस्राव की परिभाषा किस रक्त-हानि से है?", ["200 mL या अधिक", "24 घंटे में 500 mL या अधिक", "पहले घंटे में 100 mL", "केवल 1,500 mL"], "योनि प्रसव के बाद 24 घंटे में ≥ 500 mL (सिज़ेरियन के बाद ≥ 1,000 mL) या अस्थिरता पैदा करने वाली कोई भी हानि PPH है।"]),
    q(0, N, "community-health", "H", 0,
      ["The incubation period is best defined as the time between:", ["Entry of the infection and appearance of the first symptom", "First symptom and recovery", "Diagnosis and treatment", "Death and burial"], "Incubation period runs from invasion by the organism to onset of the first sign or symptom."],
      ["उद्भवन (इन्क्यूबेशन) अवधि की सबसे अच्छी परिभाषा किन दो के बीच का समय है?", ["संक्रमण का प्रवेश और पहला लक्षण प्रकट होना", "पहला लक्षण और स्वस्थ होना", "निदान और उपचार", "मृत्यु और अंत्येष्टि"], "उद्भवन अवधि जीव के प्रवेश से पहले चिह्न या लक्षण के प्रकट होने तक होती है।"]),
    q(0, N, "child-health", "H", 2,
      ["Which danger sign in a young infant under IMNCI needs urgent referral?", ["Sneezing", "Mild nasal block", "Not able to feed or convulsions", "Hiccups"], "Inability to feed, convulsions, fast breathing, chest indrawing, fever or low temperature are danger signs needing urgent referral."],
      ["IMNCI के अनुसार छोटे शिशु में कौन-सा ख़तरे का संकेत तुरंत रेफ़रल माँगता है?", ["छींक आना", "हल्की नाक बंद", "दूध न पी पाना या दौरे", "हिचकी"], "दूध न पी पाना, दौरे, तेज़ साँस, छाती धँसना, बुख़ार या कम तापमान ख़तरे के संकेत हैं जिनमें तुरंत रेफ़रल चाहिए।"]),
    q(0, N, "midwifery", "M", 3,
      ["The hormone responsible for milk ejection (let-down reflex) is:", ["Prolactin", "Oestrogen", "Progesterone", "Oxytocin"], "Prolactin produces milk; oxytocin, released when the baby suckles, ejects it."],
      ["दूध के निष्कासन (लेट-डाउन प्रतिवर्त) के लिए उत्तरदायी हार्मोन है:", ["प्रोलैक्टिन", "एस्ट्रोजन", "प्रोजेस्टेरोन", "ऑक्सीटोसिन"], "प्रोलैक्टिन दूध बनाता है; शिशु के चूसने पर निकलने वाला ऑक्सीटोसिन उसे बाहर निकालता है।"]),
    q(0, N, "community-health", "M", 2,
      ["Iodised salt is promoted to prevent:", ["Rickets", "Scurvy", "Iodine deficiency disorders such as goitre", "Anaemia"], "Lack of iodine causes goitre, hypothyroidism and cretinism; iodised salt is the main preventive measure."],
      ["आयोडीनयुक्त नमक को किसकी रोकथाम के लिए बढ़ावा दिया जाता है?", ["रिकेट्स", "स्कर्वी", "घेंघा जैसे आयोडीन अल्पता विकार", "एनीमिया"], "आयोडीन की कमी से घेंघा, हाइपोथायरॉइडिज़्म और क्रेटिनिज़्म होता है; आयोडीनयुक्त नमक मुख्य रोकथाम है।"]),
    q(0, N, "child-health", "M", 1,
      ["Oral polio vaccine (OPV) drops are given in a dose of:", ["1 drop", "2 drops", "5 drops", "10 drops"], "OPV is given as 2 drops orally per dose."],
      ["ओरल पोलियो वैक्सीन (OPV) की एक खुराक में कितनी बूँदें दी जाती हैं?", ["1 बूँद", "2 बूँद", "5 बूँद", "10 बूँद"], "OPV प्रति खुराक मुँह से 2 बूँद दी जाती है।"]),
    q(0, N, "community-health", "E", 0,
      ["Malaria is transmitted by the bite of an infected female:", ["Anopheles mosquito", "Aedes mosquito", "Culex mosquito", "Housefly"], "Female Anopheles mosquitoes transmit Plasmodium parasites."],
      ["मलेरिया किस संक्रमित मादा के काटने से फैलता है?", ["एनोफ़िलीज़ मच्छर", "एडीज़ मच्छर", "क्यूलेक्स मच्छर", "घरेलू मक्खी"], "मादा एनोफ़िलीज़ मच्छर प्लाज़्मोडियम परजीवी फैलाते हैं।"]),
  ],
];
