// HP TET (JBT) — Child Development & Pedagogy, 30 fresh questions for each of the two full mocks.

import { q, type PatwariQuestion } from "../../patwari/types";

const P = "pedagogy";

export const tetCdp: PatwariQuestion[][] = [
  [
    q(0, P, "child-development", "M", 0,
      ["The sensorimotor stage in Piaget's theory lasts approximately from:", ["Birth to 2 years", "2 to 7 years", "7 to 11 years", "11 years onwards"], "Sensorimotor: birth–2 years; preoperational: 2–7; concrete operational: 7–11; formal operational: 11+."],
      ["पियाजे के सिद्धांत में संवेदी-गामक अवस्था लगभग कब तक रहती है?", ["जन्म से 2 वर्ष", "2 से 7 वर्ष", "7 से 11 वर्ष", "11 वर्ष के बाद"], "संवेदी-गामक: जन्म–2 वर्ष; पूर्व-संक्रियात्मक: 2–7; मूर्त संक्रियात्मक: 7–11; औपचारिक संक्रियात्मक: 11+।"]),
    q(0, P, "child-development", "H", 2,
      ["A child understands that if 3 + 4 = 7, then 7 – 4 = 3. Piaget calls this ability:", ["Centration", "Animism", "Reversibility", "Object permanence"], "Reversibility — mentally undoing an operation — develops in the concrete operational stage."],
      ["बच्चा समझता है कि यदि 3 + 4 = 7 है तो 7 – 4 = 3 होगा। पियाजे इस क्षमता को कहते हैं:", ["केंद्रीकरण", "जीववाद", "उत्क्रमणीयता", "वस्तु स्थायित्व"], "उत्क्रमणीयता — किसी संक्रिया को मन में उलट पाना — मूर्त संक्रियात्मक अवस्था में विकसित होती है।"]),
    q(0, P, "child-development", "M", 1,
      ["A 9-month-old searches for a toy hidden under a cloth. The child has developed:", ["Conservation", "Object permanence", "Abstract thinking", "Seriation"], "Object permanence — knowing things exist when out of sight — emerges in the sensorimotor stage, around 8–12 months."],
      ["9 माह का बच्चा कपड़े के नीचे छिपाए गए खिलौने को ढूँढता है। बच्चे में विकसित हुआ है:", ["संरक्षण", "वस्तु स्थायित्व", "अमूर्त चिंतन", "क्रमबद्धता"], "वस्तु स्थायित्व — नज़र से ओझल चीज़ों का अस्तित्व समझना — संवेदी-गामक अवस्था में लगभग 8–12 माह में आता है।"]),
    q(0, P, "learning-theories", "H", 3,
      ["According to Vygotsky, learning is primarily:", ["An individual biological process", "Determined by maturation alone", "A result of reinforcement", "A social process shaped by culture and language"], "Vygotsky's socio-cultural theory holds that higher mental functions originate in social interaction mediated by language and cultural tools."],
      ["वाइगोत्स्की के अनुसार अधिगम मुख्यतः:", [ "एक व्यक्तिगत जैविक प्रक्रिया है", "केवल परिपक्वता से निर्धारित है", "पुनर्बलन का परिणाम है", "संस्कृति और भाषा से आकार पाने वाली सामाजिक प्रक्रिया है"], "वाइगोत्स्की के सामाजिक-सांस्कृतिक सिद्धांत के अनुसार उच्च मानसिक प्रक्रियाएँ भाषा और सांस्कृतिक साधनों द्वारा सामाजिक अंतःक्रिया से उत्पन्न होती हैं।"]),
    q(0, P, "learning-theories", "M", 0,
      ["Children's errors in learning should be seen by a teacher as:", ["A window into their thinking", "Signs of carelessness to be punished", "Proof of low intelligence", "Something to ignore"], "Errors reveal how a child is reasoning and guide the teacher's next step; NCF 2005 treats them as part of learning."],
      ["बच्चों की अधिगम-संबंधी त्रुटियों को शिक्षक को कैसे देखना चाहिए?", ["उनके चिंतन को समझने की खिड़की", "दंडनीय लापरवाही के संकेत", "कम बुद्धि का प्रमाण", "अनदेखा करने योग्य"], "त्रुटियाँ दिखाती हैं कि बच्चा कैसे सोच रहा है और शिक्षक का अगला कदम तय करती हैं; एनसीएफ 2005 इन्हें अधिगम का हिस्सा मानता है।"]),
    q(0, P, "child-development", "H", 1,
      ["Which of these is a primary (not secondary) agency of socialisation?", ["Mass media", "Family", "School", "Political party"], "The family socialises the child first and most intimately; school, media and peer groups are secondary agencies."],
      ["इनमें से कौन समाजीकरण की प्राथमिक (द्वितीयक नहीं) संस्था है?", ["जनसंचार माध्यम", "परिवार", "विद्यालय", "राजनीतिक दल"], "परिवार बच्चे का सबसे पहले और सबसे घनिष्ठ समाजीकरण करता है; विद्यालय, मीडिया और साथी समूह द्वितीयक संस्थाएँ हैं।"]),
    q(0, P, "inclusive-education", "H", 2,
      ["A teacher says 'Boys are naturally better at maths'. This reflects:", ["Gender equity", "Inclusive thinking", "Gender stereotyping", "Child-centred pedagogy"], "Attributing abilities to a gender is a stereotype; teachers should give equal opportunities and expectations."],
      ["एक शिक्षक कहता है 'लड़के स्वाभाविक रूप से गणित में बेहतर होते हैं'। यह दर्शाता है:", ["लैंगिक समता", "समावेशी सोच", "लैंगिक रूढ़िबद्धता", "बाल-केंद्रित शिक्षाशास्त्र"], "योग्यताओं को लिंग से जोड़ना रूढ़िबद्धता है; शिक्षकों को समान अवसर और समान अपेक्षाएँ देनी चाहिए।"]),
    q(0, P, "learning-theories", "M", 3,
      ["Multilingualism in the classroom should be treated as:", ["A barrier to learning", "A problem to be removed", "Something allowed only in language class", "A resource for learning"], "NCF 2005 treats children's home languages as a resource to build on, not an obstacle."],
      ["कक्षा में बहुभाषिकता को कैसे देखा जाना चाहिए?", ["अधिगम में बाधा", "हटाई जाने वाली समस्या", "केवल भाषा कक्षा में अनुमत", "अधिगम का संसाधन"], "एनसीएफ 2005 बच्चों की घरेलू भाषाओं को संसाधन मानता है जिस पर आगे बनाया जाए, बाधा नहीं।"]),
    q(0, P, "child-development", "M", 2,
      ["The first intelligence test was developed by:", ["Wechsler", "Terman", "Binet and Simon", "Spearman"], "Alfred Binet and Theodore Simon published the first practical intelligence scale in France in 1905."],
      ["पहला बुद्धि परीक्षण किसने विकसित किया?", ["वेक्सलर", "टर्मन", "बिने और साइमन", "स्पीयरमैन"], "अल्फ़्रेड बिने और थियोडोर साइमन ने 1905 में फ़्रांस में पहला व्यावहारिक बुद्धि-मापक प्रकाशित किया।"]),
    q(0, P, "learning-theories", "H", 0,
      ["Which is the best example of 'assessment for learning'?", [ "Teacher gives quick feedback on drafts so students improve before final submission", "Annual board examination", "Entrance test for admission", "Ranking students in a merit list"], "Assessment for learning is formative: feedback during learning to help improvement."],
      ["'अधिगम के लिए आकलन' का सबसे अच्छा उदाहरण कौन-सा है?", [ "शिक्षक प्रारूपों पर तुरंत प्रतिपुष्टि देता है ताकि विद्यार्थी अंतिम जमा से पहले सुधार करें", "वार्षिक बोर्ड परीक्षा", "प्रवेश परीक्षा", "मेरिट सूची में विद्यार्थियों को रैंक देना"], "अधिगम के लिए आकलन रचनात्मक है: सुधार में मदद के लिए अधिगम के दौरान प्रतिपुष्टि।"]),
    q(0, P, "child-development", "M", 1,
      ["Play is important for young children mainly because it:", [ "Keeps them away from studies", "Supports physical, social, emotional and cognitive development", "Is only for entertainment", "Replaces the need for teachers"], "Play builds motor skills, language, social rules, emotional regulation and problem-solving."],
      ["छोटे बच्चों के लिए खेल मुख्यतः क्यों महत्वपूर्ण है?", [ "यह उन्हें पढ़ाई से दूर रखता है", "यह शारीरिक, सामाजिक, संवेगात्मक और संज्ञानात्मक विकास में सहायक है", "यह केवल मनोरंजन है", "यह शिक्षकों की ज़रूरत खत्म करता है"], "खेल गामक कौशल, भाषा, सामाजिक नियम, संवेग-नियमन और समस्या-समाधान विकसित करता है।"]),
    q(0, P, "learning-theories", "H", 3,
      ["Which of these is NOT a characteristic of a child-centred classroom?", [ "Learners are active participants", "Learning is linked to children's experiences", "Group work and discussion are used", "The teacher is the only source of knowledge"], "Child-centred pedagogy treats the teacher as a facilitator; knowledge is built with learners, not just transmitted."],
      ["इनमें से कौन बाल-केंद्रित कक्षा की विशेषता नहीं है?", [ "विद्यार्थी सक्रिय भागीदार होते हैं", "अधिगम बच्चों के अनुभवों से जुड़ा होता है", "समूह कार्य और चर्चा का उपयोग होता है", "शिक्षक ही ज्ञान का एकमात्र स्रोत है"], "बाल-केंद्रित शिक्षाशास्त्र में शिक्षक सुगमकर्ता है; ज्ञान केवल हस्तांतरित नहीं, बच्चों के साथ बनाया जाता है।"]),
    q(0, P, "inclusive-education", "M", 1,
      ["ADHD in children is mainly marked by:", ["Difficulty in reading only", "Inattention, hyperactivity and impulsivity", "Loss of hearing", "Very high intelligence"], "Attention-Deficit/Hyperactivity Disorder shows persistent inattention and/or hyperactivity-impulsivity."],
      ["बच्चों में ADHD की मुख्य पहचान क्या है?", ["केवल पढ़ने में कठिनाई", "असावधानी, अतिसक्रियता और आवेगशीलता", "सुनने की क्षमता का ह्रास", "बहुत अधिक बुद्धि"], "ध्यान-अभाव/अतिसक्रियता विकार में लगातार असावधानी और/या अतिसक्रियता-आवेगशीलता होती है।"]),
    q(0, P, "learning-theories", "M", 2,
      ["Motivation that comes from a desire to get good marks or a reward is:", ["Intrinsic", "Achievement-free", "Extrinsic", "Instinctive"], "Rewards, marks and praise are external incentives — extrinsic motivation."],
      ["अच्छे अंक या पुरस्कार पाने की इच्छा से आने वाली प्रेरणा है:", ["आंतरिक", "उपलब्धि-रहित", "बाह्य", "मूल प्रवृत्तिक"], "पुरस्कार, अंक और प्रशंसा बाहरी प्रोत्साहन हैं — बाह्य प्रेरणा।"]),
    q(0, P, "child-development", "H", 0,
      ["Which statement about individual differences is correct?", [ "They arise from both heredity and environment", "They exist only in intelligence", "They disappear after primary school", "They should be ignored in teaching"], "Children differ in ability, interest, pace and style due to heredity and environment; teaching must respond to these differences."],
      ["वैयक्तिक भिन्नताओं के बारे में कौन-सा कथन सही है?", [ "ये वंशानुक्रम और वातावरण दोनों से उत्पन्न होती हैं", "ये केवल बुद्धि में होती हैं", "ये प्राथमिक विद्यालय के बाद समाप्त हो जाती हैं", "शिक्षण में इन्हें अनदेखा करना चाहिए"], "बच्चे वंशानुक्रम और वातावरण के कारण योग्यता, रुचि, गति और शैली में भिन्न होते हैं; शिक्षण को इनके अनुरूप होना चाहिए।"]),
    q(0, P, "learning-theories", "M", 1,
      ["'Readiness' in Thorndike's laws refers to:", ["Repeating a task many times", "The learner being prepared and willing to act", "Satisfaction after learning", "The teacher's preparation"], "Law of Readiness: when a learner is ready to act, acting is satisfying; being forced when not ready is annoying."],
      ["थॉर्नडाइक के नियमों में 'तत्परता' का अर्थ है:", ["किसी कार्य को अनेक बार दोहराना", "सीखने वाले का कार्य करने के लिए तैयार और इच्छुक होना", "सीखने के बाद संतोष", "शिक्षक की तैयारी"], "तत्परता का नियम: जब सीखने वाला कार्य के लिए तैयार हो तो कार्य संतोष देता है; तैयार न होने पर मजबूर करना खीज पैदा करता है।"]),
    q(0, P, "child-development", "M", 3,
      ["During the concrete operational stage children can classify objects but still find it hard to:", ["Count", "Sort by colour", "Arrange sticks by length", "Reason about purely abstract propositions"], "Concrete operational thinkers reason logically about real objects; purely abstract, hypothetical reasoning comes in the formal operational stage."],
      ["मूर्त संक्रियात्मक अवस्था में बच्चे वस्तुओं को वर्गीकृत कर सकते हैं पर किसमें अभी कठिनाई होती है?", ["गिनती", "रंग के अनुसार छाँटना", "डंडियों को लंबाई के अनुसार लगाना", "पूर्णतः अमूर्त कथनों पर तर्क"], "मूर्त संक्रियात्मक बच्चे वास्तविक वस्तुओं पर तार्किक सोचते हैं; पूर्णतः अमूर्त, काल्पनिक तर्क औपचारिक संक्रियात्मक अवस्था में आता है।"]),
    q(0, P, "inclusive-education", "H", 2,
      ["A child from a disadvantaged background is often absent and lags behind. The teacher's best response is to:", [ "Report the child for expulsion", "Seat the child separately", "Find out the reasons, involve the family and give remedial support", "Lower expectations permanently"], "Understanding causes, working with parents and providing remedial help keeps the child in school and learning."],
      ["वंचित पृष्ठभूमि का एक बच्चा अक्सर अनुपस्थित रहता है और पिछड़ जाता है। शिक्षक की सबसे अच्छी प्रतिक्रिया है:", ["उसे निष्कासन हेतु रिपोर्ट करना", "उसे अलग बैठाना", "कारण जानना, परिवार को जोड़ना और उपचारात्मक सहायता देना", "अपेक्षाएँ स्थायी रूप से घटा देना"], "कारण समझना, अभिभावकों के साथ काम करना और उपचारात्मक सहायता देना बच्चे को विद्यालय और अधिगम से जोड़े रखता है।"]),
    q(0, P, "learning-theories", "M", 0,
      ["Learning is most effective when it is:", ["Meaningful and related to the child's life", "Based only on memorisation", "Strictly teacher-controlled", "Done in silence without interaction"], "Meaningful learning connects new ideas to what children already know and experience."],
      ["अधिगम सबसे प्रभावी कब होता है?", ["जब वह सार्थक हो और बच्चे के जीवन से जुड़ा हो", "जब केवल रटने पर आधारित हो", "जब पूरी तरह शिक्षक-नियंत्रित हो", "जब बिना अंतःक्रिया के चुपचाप हो"], "सार्थक अधिगम नए विचारों को बच्चों के पूर्व-ज्ञान और अनुभव से जोड़ता है।"]),
    q(0, P, "child-development", "H", 1,
      ["Which statement about Piaget and Vygotsky is correct?", [ "Both ignored the role of language", "Piaget stressed the child as an individual explorer; Vygotsky stressed social interaction", "Vygotsky proposed four fixed stages", "Piaget invented the ZPD"], "Piaget saw the child as a 'little scientist' building schemas; Vygotsky stressed social and cultural mediation (ZPD, scaffolding)."],
      ["पियाजे और वाइगोत्स्की के बारे में कौन-सा कथन सही है?", [ "दोनों ने भाषा की भूमिका को अनदेखा किया", "पियाजे ने बच्चे को व्यक्तिगत खोजकर्ता माना; वाइगोत्स्की ने सामाजिक अंतःक्रिया पर बल दिया", "वाइगोत्स्की ने चार निश्चित अवस्थाएँ दीं", "पियाजे ने ZPD की अवधारणा दी"], "पियाजे ने बच्चे को स्कीमा बनाने वाला 'छोटा वैज्ञानिक' माना; वाइगोत्स्की ने सामाजिक-सांस्कृतिक मध्यस्थता (ZPD, स्कैफ़ोल्डिंग) पर बल दिया।"]),
    q(0, P, "learning-theories", "H", 3,
      ["Remedial teaching is given to students who:", ["Are gifted", "Want to skip a class", "Have completed the syllabus", "Show specific learning gaps found through diagnostic assessment"], "Diagnosis finds the gap; remedial teaching then addresses it."],
      ["उपचारात्मक शिक्षण किन विद्यार्थियों को दिया जाता है?", [ "प्रतिभाशाली विद्यार्थियों को", "जो कक्षा छोड़ना चाहते हैं", "जिन्होंने पाठ्यक्रम पूरा कर लिया है", "निदानात्मक आकलन में विशिष्ट अधिगम-कमियाँ दिखाने वालों को"], "निदान कमी को पहचानता है; फिर उपचारात्मक शिक्षण उसे दूर करता है।"]),
    q(0, P, "child-development", "M", 2,
      ["Emotions in early childhood are generally:", ["Stable and long-lasting", "Hidden and rarely shown", "Intense but short-lived", "Absent"], "Young children's emotions are intense, frequent, quickly changing and openly expressed."],
      ["प्रारंभिक बाल्यावस्था में संवेग सामान्यतः होते हैं:", ["स्थिर और लंबे समय तक रहने वाले", "छिपे हुए और कम प्रकट", "तीव्र पर अल्पकालिक", "अनुपस्थित"], "छोटे बच्चों के संवेग तीव्र, बार-बार होने वाले, जल्दी बदलने वाले और खुलकर व्यक्त होते हैं।"]),
    q(0, P, "inclusive-education", "M", 0,
      ["Which is the most appropriate way to assess a child with a writing disability?", [ "Allow oral answers or extra time", "Give the same written test with no change", "Exempt the child from all assessment", "Award zero for poor handwriting"], "Reasonable accommodations such as oral responses, scribes or extra time let the child show what they know."],
      ["लेखन-अक्षमता वाले बच्चे का आकलन करने का सबसे उपयुक्त तरीका कौन-सा है?", ["मौखिक उत्तर या अतिरिक्त समय देना", "बिना बदलाव वही लिखित परीक्षा देना", "बच्चे को हर आकलन से छूट देना", "खराब लिखावट पर शून्य देना"], "मौखिक उत्तर, लेखक (स्क्राइब) या अतिरिक्त समय जैसी उचित सुविधाएँ बच्चे को अपना ज्ञान दिखाने देती हैं।"]),
    q(0, P, "learning-theories", "H", 2,
      ["Gestalt psychologists emphasised that learning involves:", ["Stimulus–response bonds only", "Rewards and punishments", "Perceiving the whole pattern and its relationships", "Imitating models"], "Gestalt theory: 'the whole is more than the sum of its parts'; learners grasp the overall structure (insight)."],
      ["गेस्टाल्ट मनोवैज्ञानिकों ने ज़ोर दिया कि अधिगम में शामिल है:", ["केवल उद्दीपक-अनुक्रिया बंधन", "पुरस्कार और दंड", "पूरे स्वरूप और उसके संबंधों का प्रत्यक्षीकरण", "मॉडल का अनुकरण"], "गेस्टाल्ट सिद्धांत: 'पूर्ण, अंशों के योग से अधिक है'; सीखने वाला समग्र संरचना को समझता है (अंतर्दृष्टि)।"]),
    q(0, P, "child-development", "M", 1,
      ["A teacher notices a child is very shy and does not talk in class. The best first step is to:", [ "Force the child to speak in front of everyone", "Create small-group activities where the child feels safe to participate", "Ignore the child", "Complain to the parents"], "Low-pressure small-group work builds confidence gradually."],
      ["शिक्षक देखता है कि एक बच्चा बहुत संकोची है और कक्षा में नहीं बोलता। सबसे अच्छा पहला कदम है:", [ "उसे सबके सामने बोलने के लिए मजबूर करना", "छोटे समूह की गतिविधियाँ बनाना जहाँ वह सुरक्षित महसूस कर भाग ले सके", "बच्चे को अनदेखा करना", "अभिभावकों से शिकायत करना"], "कम दबाव वाला छोटे समूह का कार्य धीरे-धीरे आत्मविश्वास बढ़ाता है।"]),
    q(0, P, "learning-theories", "M", 3,
      ["Which is the main aim of portfolio assessment?", ["Rank students by a single score", "Test speed of writing", "Check attendance", "Show a learner's progress over time through collected work"], "A portfolio is a purposeful collection of a student's work showing growth across a period."],
      ["पोर्टफ़ोलियो आकलन का मुख्य उद्देश्य क्या है?", ["एक अंक से विद्यार्थियों को रैंक देना", "लिखने की गति परखना", "उपस्थिति जाँचना", "एकत्रित कार्य द्वारा समय के साथ विद्यार्थी की प्रगति दिखाना"], "पोर्टफ़ोलियो विद्यार्थी के कार्य का उद्देश्यपूर्ण संग्रह है जो एक अवधि में उसकी प्रगति दिखाता है।"]),
    q(0, P, "child-development", "H", 0,
      ["Kohlberg assessed moral development mainly by:", ["Presenting moral dilemmas such as the Heinz dilemma", "Observing children's play", "Measuring IQ", "Asking parents to rate children"], "Kohlberg analysed the reasoning children gave for resolving dilemmas like whether Heinz should steal a drug."],
      ["कोहलबर्ग ने नैतिक विकास का आकलन मुख्यतः कैसे किया?", ["हाइंज़ दुविधा जैसी नैतिक दुविधाएँ प्रस्तुत करके", "बच्चों के खेल का अवलोकन करके", "बुद्धिलब्धि मापकर", "अभिभावकों से बच्चों का मूल्यांकन करवाकर"], "कोहलबर्ग ने इस बात का विश्लेषण किया कि बच्चे हाइंज़ जैसी दुविधाओं (क्या उसे दवा चुरानी चाहिए) को हल करने के लिए क्या तर्क देते हैं।"]),
    q(0, P, "inclusive-education", "H", 1,
      ["The term 'Divyang' for persons with disabilities came into official use in India in:", ["2005", "2015-16", "1995", "2009"], "The term 'Divyang' was proposed by the Prime Minister in December 2015 and adopted in official usage thereafter."],
      ["दिव्यांगजनों के लिए 'दिव्यांग' शब्द भारत में आधिकारिक उपयोग में कब आया?", ["2005", "2015-16", "1995", "2009"], "'दिव्यांग' शब्द प्रधानमंत्री ने दिसंबर 2015 में प्रस्तावित किया और उसके बाद आधिकारिक उपयोग में अपनाया गया।"]),
    q(0, P, "learning-theories", "E", 0,
      ["A teacher should ask questions in class mainly to:", ["Stimulate thinking and check understanding", "Embarrass students", "Fill time", "Find out who is absent"], "Questioning engages learners and gives the teacher evidence of understanding."],
      ["शिक्षक को कक्षा में प्रश्न मुख्यतः किसलिए पूछने चाहिए?", [ "चिंतन को प्रेरित करने और समझ जाँचने के लिए", "विद्यार्थियों को शर्मिंदा करने के लिए", "समय भरने के लिए", "अनुपस्थित विद्यार्थियों का पता लगाने के लिए"], "प्रश्न पूछना विद्यार्थियों को जोड़ता है और शिक्षक को समझ का प्रमाण देता है।"]),
    q(0, P, "child-development", "M", 3,
      ["Which factor is environmental rather than hereditary?", ["Eye colour", "Blood group", "Height potential", "Quality of schooling"], "Schooling, nutrition and family climate are environmental; eye colour and blood group are inherited."],
      ["कौन-सा कारक वंशानुगत नहीं बल्कि वातावरणीय है?", ["आँखों का रंग", "रक्त समूह", "ऊँचाई की संभावना", "विद्यालयी शिक्षा की गुणवत्ता"], "विद्यालयी शिक्षा, पोषण और पारिवारिक माहौल वातावरणीय हैं; आँखों का रंग और रक्त समूह वंशानुगत हैं।"]),
  ],
  [
    q(0, P, "child-development", "M", 3,
      ["Pretend play, like using a stick as a horse, is typical of Piaget's:", ["Sensorimotor stage", "Concrete operational stage", "Formal operational stage", "Preoperational stage"], "Symbolic (pretend) play flourishes in the preoperational stage as children begin using symbols."],
      ["नाटकीय खेल, जैसे डंडे को घोड़ा बनाना, पियाजे की किस अवस्था की विशेषता है?", ["संवेदी-गामक अवस्था", "मूर्त संक्रियात्मक अवस्था", "औपचारिक संक्रियात्मक अवस्था", "पूर्व-संक्रियात्मक अवस्था"], "प्रतीकात्मक (नाटकीय) खेल पूर्व-संक्रियात्मक अवस्था में फलता-फूलता है जब बच्चे प्रतीकों का उपयोग शुरू करते हैं।"]),
    q(0, P, "child-development", "H", 0,
      ["Focusing on only one feature of a situation, such as the height of water and not the width of the glass, is called:", ["Centration", "Decentration", "Seriation", "Classification"], "Centration is a limitation of preoperational thought; decentration develops in the concrete operational stage."],
      ["किसी स्थिति की केवल एक विशेषता पर ध्यान देना, जैसे पानी की ऊँचाई पर पर गिलास की चौड़ाई पर नहीं, कहलाता है:", ["केंद्रीकरण", "विकेंद्रीकरण", "क्रमबद्धता", "वर्गीकरण"], "केंद्रीकरण पूर्व-संक्रियात्मक चिंतन की सीमा है; विकेंद्रीकरण मूर्त संक्रियात्मक अवस्था में विकसित होता है।"]),
    q(0, P, "learning-theories", "M", 2,
      ["Which teaching practice best applies Vygotsky's ideas?", ["Silent individual work only", "Rote repetition", "Collaborative learning with guidance from teacher and peers", "Waiting for the child to mature"], "Collaboration and guided support within the ZPD apply Vygotsky's socio-cultural view."],
      ["कौन-सी शिक्षण प्रक्रिया वाइगोत्स्की के विचारों को सबसे अच्छी तरह लागू करती है?", ["केवल मौन व्यक्तिगत कार्य", "रटंत दोहराव", "शिक्षक और साथियों के मार्गदर्शन के साथ सहयोगात्मक अधिगम", "बच्चे के परिपक्व होने की प्रतीक्षा"], "ZPD के भीतर सहयोग और निर्देशित सहायता वाइगोत्स्की के सामाजिक-सांस्कृतिक दृष्टिकोण को लागू करते हैं।"]),
    q(0, P, "child-development", "H", 1,
      ["Kohlberg's highest stage, 'universal ethical principles', belongs to the:", ["Conventional level", "Post-conventional level", "Pre-conventional level", "Concrete operational stage"], "Stages 5 (social contract) and 6 (universal ethical principles) make up the post-conventional level."],
      ["कोहलबर्ग की उच्चतम अवस्था 'सार्वभौमिक नैतिक सिद्धांत' किस स्तर की है?", ["परंपरागत स्तर", "उत्तर-परंपरागत स्तर", "पूर्व-परंपरागत स्तर", "मूर्त संक्रियात्मक अवस्था"], "अवस्था 5 (सामाजिक अनुबंध) और 6 (सार्वभौमिक नैतिक सिद्धांत) उत्तर-परंपरागत स्तर बनाती हैं।"]),
    q(0, P, "learning-theories", "M", 0,
      ["Giving a sticker each time a child completes reading a page is:", ["Positive reinforcement", "Negative reinforcement", "Punishment", "Extinction"], "Adding a pleasant stimulus after a behaviour to increase it is positive reinforcement."],
      ["हर बार पृष्ठ पढ़ लेने पर बच्चे को स्टिकर देना है:", ["धनात्मक पुनर्बलन", "ऋणात्मक पुनर्बलन", "दंड", "विलोपन"], "व्यवहार के बाद सुखद उद्दीपक जोड़कर उसे बढ़ाना धनात्मक पुनर्बलन है।"]),
    q(0, P, "child-development", "M", 2,
      ["Language development in children follows which correct sequence?", [ "Words, cooing, babbling, sentences", "Babbling, sentences, cooing, words", "Cooing, babbling, single words, sentences", "Sentences, words, babbling, cooing"], "Typical sequence: cooing (~2 months), babbling (~6 months), first words (~12 months), then two-word phrases and sentences."],
      ["बच्चों में भाषा विकास का सही क्रम कौन-सा है?", ["शब्द, कूजन, बड़बड़ाना, वाक्य", "बड़बड़ाना, वाक्य, कूजन, शब्द", "कूजन, बड़बड़ाना, एकल शब्द, वाक्य", "वाक्य, शब्द, बड़बड़ाना, कूजन"], "सामान्य क्रम: कूजन (~2 माह), बड़बड़ाना (~6 माह), पहले शब्द (~12 माह), फिर दो-शब्द वाक्यांश और वाक्य।"]),
    q(0, P, "inclusive-education", "H", 3,
      ["Which of these classroom practices promotes gender equality?", [ "Giving cleaning duties only to girls", "Letting only boys lead sports", "Using textbooks that show only men as scientists", "Rotating all roles among boys and girls"], "Sharing all roles equally challenges stereotypes; the other options reinforce them."],
      ["इनमें से कौन-सी कक्षा-प्रक्रिया लैंगिक समानता को बढ़ावा देती है?", [ "सफ़ाई का काम केवल लड़कियों को देना", "केवल लड़कों को खेल का नेतृत्व देना", "केवल पुरुषों को वैज्ञानिक दिखाने वाली पाठ्यपुस्तकें", "सभी भूमिकाएँ लड़कों और लड़कियों में बारी-बारी से बाँटना"], "सभी भूमिकाएँ बराबर बाँटना रूढ़ियों को चुनौती देता है; बाकी विकल्प उन्हें मज़बूत करते हैं।"]),
    q(0, P, "learning-theories", "H", 1,
      ["According to NCF 2005, the teacher's role is best described as a:", ["Strict disciplinarian", "Facilitator of learning", "Transmitter of facts", "Examiner only"], "NCF 2005 sees the teacher as a facilitator who creates opportunities for children to construct knowledge."],
      ["एनसीएफ 2005 के अनुसार शिक्षक की भूमिका का सबसे अच्छा वर्णन है:", ["कठोर अनुशासक", "अधिगम का सुगमकर्ता", "तथ्यों का संप्रेषक", "केवल परीक्षक"], "एनसीएफ 2005 शिक्षक को सुगमकर्ता मानता है जो बच्चों को ज्ञान-निर्माण के अवसर देता है।"]),
    q(0, P, "child-development", "M", 3,
      ["Which is a sign of normal cognitive development at age 4?", ["Solving algebra", "Reading newspapers fluently", "Abstract reasoning about justice", "Asking many 'why' questions"], "Around 3–5 years children ask frequent 'why' questions as curiosity and language grow."],
      ["4 वर्ष की आयु में सामान्य संज्ञानात्मक विकास का संकेत कौन-सा है?", ["बीजगणित हल करना", "समाचार-पत्र धाराप्रवाह पढ़ना", "न्याय पर अमूर्त तर्क", "बहुत-से 'क्यों' प्रश्न पूछना"], "लगभग 3–5 वर्ष में जिज्ञासा और भाषा बढ़ने के साथ बच्चे बार-बार 'क्यों' प्रश्न पूछते हैं।"]),
    q(0, P, "learning-theories", "M", 1,
      ["Which of these is a projective technique of personality assessment?", ["Questionnaire", "Rorschach inkblot test", "Rating scale", "Interview schedule"], "Projective tests (Rorschach, TAT) present ambiguous stimuli on which people project their feelings."],
      ["इनमें से कौन व्यक्तित्व आकलन की प्रक्षेपी तकनीक है?", ["प्रश्नावली", "रोर्शा स्याही-धब्बा परीक्षण", "मापनी (रेटिंग स्केल)", "साक्षात्कार अनुसूची"], "प्रक्षेपी परीक्षण (रोर्शा, TAT) अस्पष्ट उद्दीपक देते हैं जिन पर व्यक्ति अपनी भावनाएँ प्रक्षेपित करता है।"]),
    q(0, P, "inclusive-education", "M", 2,
      ["A child with low vision would be best helped by:", ["Seating at the back", "Using only oral instruction", "Large-print material and good lighting", "Excusing the child from reading"], "Large print, magnifiers, contrast and good lighting help children with low vision use remaining sight."],
      ["कम दृष्टि वाले बच्चे की सबसे अच्छी सहायता किससे होगी?", ["पीछे बैठाकर", "केवल मौखिक निर्देश देकर", "बड़े अक्षरों वाली सामग्री और अच्छी रोशनी से", "पढ़ने से छूट देकर"], "बड़े अक्षर, आवर्धक, कंट्रास्ट और अच्छी रोशनी कम दृष्टि वाले बच्चों को शेष दृष्टि का उपयोग करने में मदद करते हैं।"]),
    q(0, P, "child-development", "H", 0,
      ["'Development is a product of maturation and learning' means:", ["Biological growth and experience both contribute", "Only age matters", "Only teaching matters", "Development stops at puberty"], "Maturation provides readiness; learning through experience shapes what develops."],
      ["'विकास परिपक्वता और अधिगम का परिणाम है' का अर्थ है:", ["जैविक वृद्धि और अनुभव दोनों योगदान देते हैं", "केवल आयु मायने रखती है", "केवल शिक्षण मायने रखता है", "विकास यौवनारंभ पर रुक जाता है"], "परिपक्वता तत्परता देती है; अनुभव से अधिगम तय करता है कि क्या विकसित हो।"]),
    q(0, P, "learning-theories", "H", 2,
      ["A child learns to tie shoelaces by watching her elder sister. According to Bandura, the four processes involved in order are:", [ "Motivation, attention, retention, reproduction", "Retention, attention, motivation, reproduction", "Attention, retention, reproduction, motivation", "Reproduction, retention, attention, motivation"], "Bandura's observational learning: attention, retention, (motor) reproduction, motivation."],
      ["बच्ची बड़ी बहन को देखकर जूते के फीते बाँधना सीखती है। बंडूरा के अनुसार इसमें चार प्रक्रियाएँ क्रम से हैं:", ["प्रेरणा, अवधान, धारण, पुनरुत्पादन", "धारण, अवधान, प्रेरणा, पुनरुत्पादन", "अवधान, धारण, पुनरुत्पादन, प्रेरणा", "पुनरुत्पादन, धारण, अवधान, प्रेरणा"], "बंडूरा का अवलोकनात्मक अधिगम: अवधान, धारण, (गामक) पुनरुत्पादन, प्रेरणा।"]),
    q(0, P, "child-development", "M", 1,
      ["Which is the best indicator of a child's understanding of a concept?", ["Reproducing the textbook definition", "Applying it to explain a new situation", "Copying neatly", "Sitting quietly"], "Being able to use a concept in a new context shows real understanding, not just recall."],
      ["किसी अवधारणा की समझ का सबसे अच्छा संकेतक कौन-सा है?", ["पाठ्यपुस्तक की परिभाषा दोहराना", "नई स्थिति को समझाने में उसे लागू करना", "साफ़-सुथरा नकल करना", "चुपचाप बैठना"], "किसी अवधारणा को नए संदर्भ में प्रयोग कर पाना केवल स्मरण नहीं, वास्तविक समझ दर्शाता है।"]),
    q(0, P, "learning-theories", "M", 3,
      ["Which is a characteristic of a good learner-friendly school environment?", ["Physical punishment for discipline", "Fear of examinations", "Strict silence at all times", "Freedom to ask questions without fear"], "A safe climate where children can ask and make mistakes supports learning; RTE bans corporal punishment."],
      ["अच्छे अधिगम-अनुकूल विद्यालय वातावरण की विशेषता कौन-सी है?", ["अनुशासन हेतु शारीरिक दंड", "परीक्षाओं का भय", "हर समय कड़ा मौन", "बिना भय प्रश्न पूछने की स्वतंत्रता"], "सुरक्षित माहौल जहाँ बच्चे पूछ सकें और गलती कर सकें, अधिगम में सहायक है; आरटीई शारीरिक दंड पर रोक लगाता है।"]),
    q(0, P, "inclusive-education", "H", 0,
      ["Section 17 of the RTE Act, 2009 prohibits:", ["Physical punishment and mental harassment of children", "Admission tests only", "Private tuition by teachers only", "Detention of children"], "Section 17 prohibits physical punishment and mental harassment; screening procedures are covered by Section 13, private tuition by Section 28."],
      ["आरटीई अधिनियम, 2009 की धारा 17 किसे प्रतिबंधित करती है?", ["बच्चों को शारीरिक दंड और मानसिक उत्पीड़न", "केवल प्रवेश परीक्षाएँ", "केवल शिक्षकों द्वारा निजी ट्यूशन", "बच्चों को रोकना (डिटेंशन)"], "धारा 17 शारीरिक दंड और मानसिक उत्पीड़न पर रोक लगाती है; स्क्रीनिंग प्रक्रिया धारा 13 और निजी ट्यूशन धारा 28 में है।"]),
    q(0, P, "child-development", "M", 2,
      ["The 'whole child' approach in education focuses on:", ["Only academic marks", "Only physical fitness", "All aspects — cognitive, physical, social, emotional and moral", "Only discipline"], "Holistic development addresses every domain of the child, as NEP 2020 also stresses."],
      ["शिक्षा में 'संपूर्ण बालक' दृष्टिकोण किस पर केंद्रित है?", ["केवल शैक्षिक अंक", "केवल शारीरिक स्वास्थ्य", "सभी पक्ष — संज्ञानात्मक, शारीरिक, सामाजिक, संवेगात्मक और नैतिक", "केवल अनुशासन"], "समग्र विकास बच्चे के हर क्षेत्र को संबोधित करता है, जिस पर एनईपी 2020 भी बल देती है।"]),
    q(0, P, "learning-theories", "H", 0,
      ["'Spaced practice' leads to better retention than 'massed practice' because:", ["Learning spread over time allows consolidation in memory", "It takes less total time", "It avoids all forgetting", "It needs no revision"], "Distributed practice with gaps lets memories consolidate; cramming (massed practice) fades faster."],
      ["'अंतराल अभ्यास' 'सतत (संहत) अभ्यास' से बेहतर धारण क्यों देता है?", ["समय में फैला अधिगम स्मृति में दृढ़ीकरण का अवसर देता है", "इसमें कुल समय कम लगता है", "इससे बिल्कुल विस्मरण नहीं होता", "इसमें दोहराव की ज़रूरत नहीं"], "अंतराल वाला अभ्यास स्मृतियों को दृढ़ होने देता है; एक साथ रटना (संहत अभ्यास) जल्दी भूल जाता है।"]),
    q(0, P, "child-development", "H", 3,
      ["Which of these is a 'zone of actual development' task for a child?", [ "A task the child cannot do even with help", "A task needing an expert", "A task the child can do only with a hint", "A task the child can already do independently"], "In Vygotsky's terms the actual developmental level is what the child can do alone; the ZPD lies just beyond it."],
      ["बच्चे के लिए 'वास्तविक विकास क्षेत्र' का कार्य कौन-सा है?", [ "जो कार्य बच्चा सहायता से भी नहीं कर सकता", "जिस कार्य के लिए विशेषज्ञ चाहिए", "जो कार्य बच्चा केवल संकेत मिलने पर कर पाता है", "जो कार्य बच्चा पहले से स्वतंत्र रूप से कर सकता है"], "वाइगोत्स्की के अनुसार वास्तविक विकास स्तर वह है जो बच्चा अकेले कर सकता है; ZPD उससे ठीक आगे है।"]),
    q(0, P, "learning-theories", "M", 1,
      ["Which teaching aid is most suitable for teaching 'place value' to Class 2?", ["A long lecture", "Bundles of sticks or an abacus", "A dictionary", "A globe"], "Bundling sticks in tens or using an abacus makes place value concrete."],
      ["कक्षा 2 को 'स्थानीय मान' पढ़ाने के लिए सबसे उपयुक्त शिक्षण सामग्री कौन-सी है?", ["लंबा व्याख्यान", "तीलियों के बंडल या गिनतारा", "शब्दकोश", "ग्लोब"], "तीलियों को दहाई में बाँधना या गिनतारे का उपयोग स्थानीय मान को मूर्त बनाता है।"]),
    q(0, P, "inclusive-education", "M", 3,
      ["Which of these is an example of a 'socially disadvantaged' group addressed in inclusive education?", ["Children of wealthy families", "Students of elite schools", "Children of teachers", "Children from marginalised communities and migrant families"], "Inclusion covers children disadvantaged by caste, poverty, migration, gender, language and disability."],
      ["समावेशी शिक्षा में संबोधित 'सामाजिक रूप से वंचित' समूह का उदाहरण कौन-सा है?", ["धनी परिवारों के बच्चे", "विशिष्ट विद्यालयों के विद्यार्थी", "शिक्षकों के बच्चे", "हाशिए के समुदायों और प्रवासी परिवारों के बच्चे"], "समावेशन जाति, गरीबी, प्रवास, लिंग, भाषा और दिव्यांगता से वंचित बच्चों को समेटता है।"]),
    q(0, P, "child-development", "M", 0,
      ["Attachment theory, which stresses the bond between infant and caregiver, was developed by:", ["John Bowlby", "Jean Piaget", "B.F. Skinner", "Noam Chomsky"], "John Bowlby proposed attachment theory; Mary Ainsworth later studied attachment styles."],
      ["शिशु और देखभालकर्ता के बीच बंधन पर बल देने वाला लगाव सिद्धांत किसने विकसित किया?", ["जॉन बॉल्बी", "जीन पियाजे", "बी.एफ. स्किनर", "नोम चॉम्स्की"], "जॉन बॉल्बी ने लगाव सिद्धांत दिया; बाद में मैरी एन्सवर्थ ने लगाव-शैलियों का अध्ययन किया।"]),
    q(0, P, "learning-theories", "H", 2,
      ["A teacher gives a test at the start of a unit to find what students already know. This is:", ["Summative assessment", "Norm-referenced ranking", "Diagnostic or pre-assessment", "Achievement certification"], "A pre-test at the start diagnoses prior knowledge and gaps to plan teaching."],
      ["शिक्षक इकाई के आरंभ में यह जानने के लिए परीक्षण लेता है कि विद्यार्थी पहले से क्या जानते हैं। यह है:", ["योगात्मक आकलन", "मानक-संदर्भित रैंकिंग", "निदानात्मक या पूर्व-आकलन", "उपलब्धि प्रमाणन"], "आरंभ में पूर्व-परीक्षण पूर्व-ज्ञान और कमियों का निदान करता है ताकि शिक्षण की योजना बने।"]),
    q(0, P, "child-development", "M", 1,
      ["Peer group influence is strongest during:", ["Infancy", "Adolescence", "Early childhood", "Old age"], "Adolescents seek acceptance and identity among peers, so peer influence peaks then."],
      ["साथी समूह का प्रभाव सबसे अधिक कब होता है?", ["शैशवावस्था", "किशोरावस्था", "प्रारंभिक बाल्यावस्था", "वृद्धावस्था"], "किशोर साथियों के बीच स्वीकृति और पहचान खोजते हैं, इसलिए तब साथी-प्रभाव चरम पर होता है।"]),
    q(0, P, "learning-theories", "M", 0,
      ["Learning by discovery is associated with:", ["Jerome Bruner", "Ivan Pavlov", "Edward Thorndike", "Clark Hull"], "Bruner advocated discovery learning, where learners find principles themselves."],
      ["खोज द्वारा अधिगम किससे जुड़ा है?", ["जेरोम ब्रूनर", "इवान पावलॉव", "एडवर्ड थॉर्नडाइक", "क्लार्क हल"], "ब्रूनर ने खोज अधिगम का समर्थन किया, जिसमें सीखने वाले सिद्धांत स्वयं खोजते हैं।"]),
    q(0, P, "inclusive-education", "H", 2,
      ["Under the RTE Act, which body monitors the child's right to education at the national level?", ["UGC", "NCERT", "National Commission for Protection of Child Rights", "CBSE"], "Section 31 gives the NCPCR (and SCPCRs in states) the role of monitoring rights under the Act."],
      ["आरटीई अधिनियम के तहत राष्ट्रीय स्तर पर बच्चे के शिक्षा के अधिकार की निगरानी कौन करता है?", ["यूजीसी", "एनसीईआरटी", "राष्ट्रीय बाल अधिकार संरक्षण आयोग", "सीबीएसई"], "धारा 31 के अनुसार राष्ट्रीय बाल अधिकार संरक्षण आयोग (और राज्यों में राज्य आयोग) अधिनियम के अधिकारों की निगरानी करते हैं।"]),
    q(0, P, "child-development", "H", 3,
      ["A 6-year-old says a tree is 'sad' because its leaves fell. This shows:", ["Conservation", "Hypothetical reasoning", "Reversibility", "Animism"], "Attributing feelings and life to non-living or non-human things is animism, typical of the preoperational stage."],
      ["6 वर्ष का बच्चा कहता है कि पेड़ 'उदास' है क्योंकि उसके पत्ते गिर गए। यह दर्शाता है:", ["संरक्षण", "परिकल्पनात्मक तर्क", "उत्क्रमणीयता", "जीववाद"], "निर्जीव या मानवेतर चीज़ों में भावनाएँ और जीवन मानना जीववाद है, जो पूर्व-संक्रियात्मक अवस्था की विशेषता है।"]),
    q(0, P, "learning-theories", "E", 1,
      ["Which is the most suitable way to begin a new lesson?", ["Give a test straight away", "Connect it with what children already know", "Read the chapter aloud without stopping", "Write notes on the board"], "Linking new content to prior knowledge makes it meaningful and easier to learn."],
      ["नया पाठ शुरू करने का सबसे उपयुक्त तरीका कौन-सा है?", ["तुरंत परीक्षा लेना", "उसे बच्चों के पूर्व-ज्ञान से जोड़ना", "बिना रुके अध्याय ज़ोर से पढ़ना", "बोर्ड पर नोट्स लिखना"], "नई सामग्री को पूर्व-ज्ञान से जोड़ना उसे सार्थक और सीखने में आसान बनाता है।"]),
    q(0, P, "child-development", "M", 2,
      ["Which of these factors most directly affects a child's physical growth?", ["Number of siblings", "Type of school uniform", "Nutrition", "Choice of textbook"], "Adequate nutrition is the main environmental factor in physical growth."],
      ["इनमें से कौन-सा कारक बच्चे की शारीरिक वृद्धि को सबसे सीधे प्रभावित करता है?", ["भाई-बहनों की संख्या", "विद्यालय वर्दी का प्रकार", "पोषण", "पाठ्यपुस्तक का चुनाव"], "पर्याप्त पोषण शारीरिक वृद्धि का मुख्य वातावरणीय कारक है।"]),
  ],
];
