// HPSSC Junior Office Assistant (IT), Post Code 556 — written exam of 28-04-2017, Code C-413 Series A (200 questions, 200 marks,
// 2 hours, no negative marking). Questions follow the printed paper and answers follow the commission's provisional answer key
// (Series A). Option order is kept as printed. Nothing was dropped: all 200 questions are included. Hindi text and explanations were
// written by hand. Sections: 0 Science & Computer (Q1-50), 1 General Studies (Q51-129), 2 Reasoning & Maths (Q130-141),
// 3 Current Affairs (Q142-162), 4 Himachal GK (Q163-178), 5 English & Hindi (Q179-200).

import { q, type PatwariQuestion } from "../patwari/types";

export const JOA_IT_2017_SECTIONS = [
  { name: "Science & Computer", nameHi: "विज्ञान एवं कंप्यूटर" },
  { name: "General Studies", nameHi: "सामान्य अध्ययन" },
  { name: "Reasoning & Maths", nameHi: "तर्कशक्ति एवं गणित" },
  { name: "Current Affairs", nameHi: "समसामयिकी" },
  { name: "Himachal GK", nameHi: "हिमाचल सामान्य ज्ञान" },
  { name: "English & Hindi", nameHi: "अंग्रेज़ी एवं हिंदी" },
];

export const y2017p556: PatwariQuestion[] = [
  q(0, "general-studies", "general-science", "E", 0,
    ["Which one of the following is a conventional energy source ?", ["Biomass energy", "Tidal energy", "Geothermal energy", "Solar energy"], "Per the key, biomass is taken as the conventional (traditional) energy source of the options."],
    ["निम्न में से कौन सा एक परम्परागत ऊर्जा स्रोत है?", ["बायोमास ऊर्जा", "ज्वारीय ऊर्जा", "भूतापीय ऊर्जा", "सौर ऊर्जा"], "आयोग की कुंजी के अनुसार विकल्पों में बायोमास को परम्परागत ऊर्जा स्रोत माना गया है।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["During Solar eclipse", ["the sun comes in between the Earth and the Moon.", "the moon comes exactly halfway between the Earth and the Sun.", "the moon comes in between the Sun and the Earth.", "None of these"], "In a solar eclipse the moon comes between the Sun and the Earth and blocks the sunlight."],
    ["सूर्य ग्रहण के समय", ["सूर्य, पृथ्वी और चन्द्रमा के बीच में आता है।", "चन्द्रमा, पृथ्वी और सूर्य के ठीक अर्धपथ पर आता है।", "चन्द्रमा, पृथ्वी और सूर्य के बीच आता है।", "इनमें से कोई नहीं"], "सूर्य ग्रहण में चन्द्रमा सूर्य और पृथ्वी के बीच आकर सूर्य के प्रकाश को रोक देता है।"]),
  q(0, "general-studies", "general-science", "E", 3,
    ["The scientist who first discovered that the Earth revolves round the Sun was", ["Einstein", "Dalton", "Newton", "Copernicus"], "Copernicus proposed the heliocentric model in which the Earth revolves around the Sun."],
    ["वैज्ञानिक जिन्होंने प्रथम बार खोज की कि पृथ्वी, सूर्य के चतुर्दिक परिक्रमण करती है", ["आईन्स्टाइन", "डाल्टन", "न्यूटन", "कॉपरनिकस"], "कॉपरनिकस ने सूर्य-केन्द्रित मॉडल दिया जिसमें पृथ्वी सूर्य की परिक्रमा करती है।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["Density of water is", ["minimum at – 4 °C", "maximum at 4 °C", "maximum at 0 °C", "minimum at 0 °C"], "Water is densest at 4 °C."],
    ["जल का घनत्व होता है", ["– 4 °C पर कम से कम", "4 °C पर अधिकतम", "0 °C पर अधिकतम", "0 °C पर कम से कम"], "जल का घनत्व 4 °C पर सबसे अधिक होता है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["Ball Pen functions on which one of the following principle ?", ["Surface tension", "Viscosity", "Gravitational force", "Boyle’s law"], "The ink flows to the ball through surface tension and capillary action."],
    ["बॉल पेन निम्न किस सिद्धांत पर कार्य करता है?", ["पृष्ठ तनाव", "श्यानता", "गुरुत्व बल", "बॉयल का नियम"], "स्याही पृष्ठ तनाव और केशिकत्व से गेंद तक पहुँचती है।"]),
  q(0, "general-studies", "general-science", "E", 1,
    ["When ice melts, its", ["Volume increases", "Volume decreases", "Volume remains the same", "None of these"], "Ice occupies more volume than water, so its volume decreases on melting."],
    ["जब बर्फ पिघलती है, तो इसका", ["आयतन बढ़ता है", "आयतन घटता है", "आयतन समान रहता है", "इनमें से कोई नहीं"], "बर्फ का आयतन पानी से अधिक होता है, इसलिए पिघलने पर आयतन घटता है।"]),
  q(0, "general-studies", "general-science", "M", 3,
    ["Sound wave cannot pass through above", ["an ideal gas", "a solid-liquid mixture", "a liquid-gas mixture", "a perfect vacuum"], "Sound needs a material medium, so it cannot pass through a perfect vacuum."],
    ["ध्वनि तरंगें इसमें से नहीं गुज़र सकतीं", ["एक आदर्श गैस", "एक ठोस-द्रव मिश्रण", "एक द्रव-गैस मिश्रण", "एक पूर्ण निर्वात"], "ध्वनि को माध्यम चाहिए, इसलिए वह पूर्ण निर्वात से नहीं गुज़र सकती।"]),
  q(0, "general-studies", "general-science", "E", 0,
    ["Device used to measure very high temperature is", ["Pyrometer", "Thermometer", "Barometer", "Calorimeter"], "A pyrometer measures very high temperatures."],
    ["बहुत उच्च तापमान मापने के लिए प्रयुक्त उपकरण है", ["पाइरोमीटर", "थर्मामीटर", "बैरोमीटर", "कैलोरीमीटर"], "पाइरोमीटर बहुत उच्च तापमान मापता है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["The image formed on the retina of a human eye is", ["real and inverted", "real and erect", "virtual and erect", "virtual and inverted"], "The eye lens forms a real, inverted image on the retina."],
    ["मानव आँख के रेटिना पर बना प्रतिबिम्ब होता है", ["वास्तविक और उल्टा", "वास्तविक और सीधा", "आभासी और सीधा", "आभासी और उल्टा"], "आँख का लेंस रेटिना पर वास्तविक और उल्टा प्रतिबिम्ब बनाता है।"]),
  q(0, "general-studies", "general-science", "E", 1,
    ["A fuse wire is made of an alloy of", ["tin and aluminium", "tin and lead", "tin and copper", "None of these"], "A fuse wire is an alloy of tin and lead with a low melting point."],
    ["एक फ्यूज़ तार इसकी मिश्र धातु से बना होता है", ["टिन और एल्युमीनियम", "टिन और सीसा", "टिन और ताँबा", "इनमें से कोई नहीं"], "फ्यूज़ तार टिन और सीसे की मिश्र धातु है जिसका गलनांक कम होता है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["A radar beam consists of", ["microwaves", "X-rays", "ultraviolet rays", "infrared rays"], "Radar uses microwaves."],
    ["रडार किरण निर्मित होती है", ["माइक्रोवेव से", "X-किरणों से", "पराबैंगनी किरणों से", "अवरक्त किरणों से"], "रडार माइक्रोवेव का प्रयोग करता है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["The gas used in a refrigerator is", ["cooled down when expanded", "heated up on flowing", "cooled down when compressed", "None of these"], "The refrigerant gas cools when it expands, which produces the cooling effect."],
    ["रेफ्रिजरेटर में प्रयुक्त गैस", ["प्रसार होने पर ठंडी हो जाती है", "बहने पर गर्म हो जाती है", "संपीड़न पर ठंडी हो जाती है", "इनमें से कोई नहीं"], "रेफ्रिजरेंट गैस प्रसार होने पर ठंडी होती है, जिससे शीतलन होता है।"]),
  q(0, "general-studies", "general-science", "E", 2,
    ["Radioactive substance used in dating geological object is", ["C-11", "C-12", "C-14", "None of these"], "Carbon-14 dating is used to find the age of ancient objects."],
    ["भूवैज्ञानिक वस्तुओं की आयु निर्धारण में प्रयुक्त रेडियोधर्मी पदार्थ है", ["C-11", "C-12", "C-14", "इनमें से कोई नहीं"], "प्राचीन वस्तुओं की आयु निर्धारित करने में कार्बन-14 का उपयोग होता है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["Butter is a colloid formed when", ["water is dispersed in fat.", "fat is dispersed in water.", "fat globules are dispersed in water.", "None of these"], "Butter is a water-in-fat emulsion: water is dispersed in fat."],
    ["मक्खन एक कोलॉइड है जो तब बनता है जब", ["जल वसा में परिक्षिप्त होता है।", "वसा जल में परिक्षिप्त होती है।", "वसा के गोलक जल में परिक्षिप्त होते हैं।", "इनमें से कोई नहीं"], "मक्खन जल-में-वसा का इमल्शन है, यानी जल वसा में परिक्षिप्त है।"]),
  q(0, "general-studies", "general-science", "E", 1,
    ["Which one of the following is not a chemical change ?", ["Digestion of food", "Freezing of water", "Curding of milk", "Ripening of fruits"], "Freezing of water is a physical change, so no new substance forms."],
    ["निम्न में से कौन सा रासायनिक परिवर्तन नहीं है?", ["भोजन का पाचन", "जल का जमना", "दूध का दही बनना", "फलों का पकना"], "जल का जमना भौतिक परिवर्तन है, इसमें नया पदार्थ नहीं बनता।"]),
  q(0, "general-studies", "general-science", "E", 3,
    ["Which one of the following is the softest metal ?", ["Copper", "Iron", "Aluminium", "Sodium"], "Sodium is so soft that it can be cut with a knife."],
    ["निम्न में से सबसे मुलायम धातु कौन सी है?", ["ताँबा", "लोहा", "एल्युमीनियम", "सोडियम"], "सोडियम इतनी मुलायम है कि चाकू से कट जाती है।"]),
  q(0, "general-studies", "general-science", "E", 0,
    ["Dry ice is", ["CO2(s)", "H2O(s)", "NH3(g)", "None of these"], "Dry ice is solid carbon dioxide."],
    ["शुष्क बर्फ (ड्राई आइस) है", ["CO2(s)", "H2O(s)", "NH3(g)", "इनमें से कोई नहीं"], "शुष्क बर्फ ठोस कार्बन डाइऑक्साइड है।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["Glass is best described as a", ["Colloidal sol.", "Solid", "Supercooled liquid", "None of these"], "Glass is an amorphous solid regarded as a supercooled liquid."],
    ["काँच को सर्वोत्तम रूप में कहा जा सकता है", ["कोलॉइडी सोल", "ठोस", "अतिशीतित द्रव", "इनमें से कोई नहीं"], "काँच अक्रिस्टलीय ठोस है जिसे अतिशीतित द्रव माना जाता है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["In the heavy vehicles, diesel is used as fuel because", ["it has high power and economic savings.", "it is less costly and useful for the fuel savings point of view.", "it has more mileage and the safe for the engine.", "None of these"], "Diesel gives high power and is economical for heavy vehicles."],
    ["भारी वाहनों में डीज़ल ईंधन के रूप में प्रयोग किया जाता है क्योंकि", ["इसमें उच्च शक्ति तथा आर्थिक बचत होती है।", "यह कम लागत वाला है और ईंधन बचत की दृष्टि से उपयोगी है।", "इसमें अधिक माइलेज होता है और यह इंजन के लिए सुरक्षित है।", "इनमें से कोई नहीं"], "डीज़ल उच्च शक्ति देता है और भारी वाहनों के लिए किफ़ायती है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["The natural rubber is a polymer of", ["isoprene", "acetylene", "vinyl chloride", "None of these"], "Natural rubber is a polymer of isoprene."],
    ["प्राकृतिक रबर किसका बहुलक है?", ["आइसोप्रीन", "एसिटिलीन", "वाइनिल क्लोराइड", "इनमें से कोई नहीं"], "प्राकृतिक रबर आइसोप्रीन का बहुलक है।"]),
  q(0, "general-studies", "general-science", "E", 1,
    ["What is the pH of pure water ?", ["5", "7", "9", "None of these"], "Pure water is neutral with a pH of 7."],
    ["शुद्ध जल का pH क्या होता है?", ["5", "7", "9", "इनमें से कोई नहीं"], "शुद्ध जल उदासीन होता है और उसका pH 7 है।"]),
  q(0, "general-studies", "general-science", "E", 2,
    ["The main constituent of Vinegar is", ["ascorbic acid", "citric acid", "acetic acid", "None of these"], "Vinegar is mainly acetic acid."],
    ["सिरके का मुख्य घटक है", ["एस्कॉर्बिक अम्ल", "साइट्रिक अम्ल", "एसिटिक अम्ल", "इनमें से कोई नहीं"], "सिरका मुख्यतः एसिटिक अम्ल है।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["The metal present in Vitamin B12 is", ["Magnesium", "Manganese", "Cobalt", "Iron"], "Vitamin B12 (cobalamin) contains cobalt."],
    ["विटामिन B12 में उपस्थित धातु है", ["मैग्नीशियम", "मैंगनीज़", "कोबाल्ट", "लोहा"], "विटामिन B12 (कोबालामिन) में कोबाल्ट होता है।"]),
  q(0, "general-studies", "general-science", "E", 1,
    ["Vermicompost is a/an", ["synthetic fertilizer", "organic bio-fertilizer", "inorganic fertilizer", "None of these"], "Vermicompost is an organic bio-fertilizer made by earthworms."],
    ["वर्मीकम्पोस्ट एक है", ["संश्लेषित उर्वरक", "जैविक जैव-उर्वरक", "अकार्बनिक उर्वरक", "इनमें से कोई नहीं"], "वर्मीकम्पोस्ट केंचुओं से बना जैविक जैव-उर्वरक है।"]),
  q(0, "general-studies", "general-science", "E", 3,
    ["Suicidal bag of cell is", ["nucleosome", "ribosomes", "golgi bodies", "lysosome"], "Lysosomes digest the cell when it dies, hence 'suicidal bags'."],
    ["कोशिका की आत्मघाती थैली है", ["न्यूक्लिओसोम", "राइबोसोम", "गॉल्जी काय", "लाइसोसोम"], "कोशिका मरने पर लाइसोसोम उसे पचा देते हैं, इसलिए इन्हें आत्मघाती थैली कहते हैं।"]),
  q(0, "general-studies", "general-science", "M", 3,
    ["Pair of ribs found in man :", ["10", "14", "11", "12"], "Humans have 12 pairs (24) of ribs."],
    ["मनुष्य में पसलियों के जोड़े होते हैं", ["10", "14", "11", "12"], "मनुष्य में 12 जोड़ी (24) पसलियाँ होती हैं।"]),
  q(0, "general-studies", "general-science", "E", 1,
    ["Dinosaur was", ["mammal", "reptile", "large herbivorous animal", "None of these"], "Dinosaurs were reptiles."],
    ["डायनासोर था", ["स्तनधारी", "सरीसृप", "विशाल शाकाहारी जीव", "इनमें से कोई नहीं"], "डायनासोर सरीसृप थे।"]),
  q(0, "general-studies", "general-science", "E", 0,
    ["What is MRI ?", ["Magnetic Resonance Imaging", "Magnetic Record of Intestines", "Magnetic Recording of Investigations", "None of these"], "MRI stands for Magnetic Resonance Imaging."],
    ["MRI क्या है?", ["मैग्नेटिक रेज़ोनेन्स इमेजिंग", "मैग्नेटिक रिकॉर्ड ऑफ इन्टेस्टाइन्स", "मैग्नेटिक रिकॉर्डिंग ऑफ इन्वेस्टिगेशन्स", "इनमें से कोई नहीं"], "MRI का पूर्ण रूप मैग्नेटिक रेज़ोनेन्स इमेजिंग है।"]),
  q(0, "general-studies", "general-science", "E", 2,
    ["The cause of tuberculosis is", ["Fungi", "Virus", "Bacteria", "Protozoan"], "Tuberculosis is caused by the bacterium Mycobacterium tuberculosis."],
    ["क्षय रोग (तपेदिक) का कारण है", ["कवक", "विषाणु", "जीवाणु", "प्रोटोज़ोआ"], "तपेदिक माइकोबैक्टीरियम ट्यूबरकुलोसिस जीवाणु से होता है।"]),
  q(0, "general-studies", "general-science", "E", 2,
    ["Insulin is a kind of", ["enzyme", "salt", "hormone", "vitamin"], "Insulin is a hormone made by the pancreas."],
    ["इंसुलिन एक प्रकार का है", ["एन्ज़ाइम", "लवण", "हार्मोन", "विटामिन"], "इंसुलिन अग्न्याशय द्वारा बनाया गया हार्मोन है।"]),
  q(0, "general-studies", "general-science", "E", 0,
    ["Process by which plants prepare their food is called", ["Photosynthesis", "Photorespiration", "Carbohydrolysis", "None of these"], "Plants make food by photosynthesis."],
    ["जिस प्रक्रिया से पौधे अपना भोजन बनाते हैं, उसे कहते हैं", ["प्रकाश-संश्लेषण", "प्रकाश-श्वसन", "कार्बोहाइड्रोलिसिस", "इनमें से कोई नहीं"], "पौधे प्रकाश-संश्लेषण द्वारा भोजन बनाते हैं।"]),
  q(0, "general-studies", "general-science", "E", 2,
    ["Bile is stored in human beings in the", ["Stomach", "Liver", "Gall bladder", "None of these"], "Bile is made in the liver and stored in the gall bladder."],
    ["मनुष्यों में पित्त संगृहीत होता है", ["आमाशय में", "यकृत में", "पित्ताशय में", "इनमें से कोई नहीं"], "पित्त यकृत में बनता है और पित्ताशय में संगृहीत होता है।"]),
  q(0, "general-studies", "general-science", "E", 0,
    ["Human skin is", ["an organ", "a tissue", "a cell", "None of these"], "The skin is the largest organ of the body."],
    ["मानव त्वचा है", ["एक अंग", "एक ऊतक", "एक कोशिका", "इनमें से कोई नहीं"], "त्वचा शरीर का सबसे बड़ा अंग है।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["A seed is ripened", ["flower", "ovule", "ovary", "None of these"], "The ovule ripens into the seed (the ovary becomes the fruit)."],
    ["बीज परिपक्व होता है", ["पुष्प", "बीजाण्ड", "अण्डाशय", "इनमें से कोई नहीं"], "बीजाण्ड परिपक्व होकर बीज बनता है (अण्डाशय फल बनता है)।"]),
  q(0, "general-studies", "general-science", "E", 2,
    ["Tallest tree is", ["Eucalyptus", "Deodar", "Sequoia", "None of these"], "Per the key, the answer is (C) Sequoia, the world's tallest tree."],
    ["सबसे ऊँचा वृक्ष है", ["यूकेलिप्टस", "देवदार", "सिकोया", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार उत्तर (C) सिकोया है, जो विश्व का सबसे ऊँचा वृक्ष है।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["What is mixed farming ?", ["Growing of several crops in a planned way.", "Growing several crops and rearing animals.", "Growing Rabi as well as Kharif crops.", "None of these"], "Mixed farming means growing crops and rearing animals together."],
    ["मिश्रित खेती क्या है?", ["कई फसलों को योजनाबद्ध ढंग से उगाना।", "कई फसलें उगाना और पशुपालन करना।", "रबी तथा खरीफ दोनों फसलें उगाना।", "इनमें से कोई नहीं"], "मिश्रित खेती में फसलें उगाने के साथ पशुपालन भी किया जाता है।"]),
  q(0, "general-studies", "general-science", "E", 0,
    ["Earthworm is called farmer’s friend because", ["it make soil porous.", "it fix atmospheric nitrogen.", "it work as fungicide", "None of these"], "Earthworms loosen the soil and make it porous."],
    ["केंचुए को किसान का मित्र कहा जाता है क्योंकि", ["यह मिट्टी को छिद्रयुक्त बनाता है।", "यह वायुमंडलीय नाइट्रोजन का स्थिरीकरण करता है।", "यह कवकनाशी का कार्य करता है।", "इनमें से कोई नहीं"], "केंचुए मिट्टी को ढीला और छिद्रयुक्त बनाते हैं।"]),
  q(0, "general-studies", "general-science", "E", 2,
    ["Saffron is obtained from which part of plants ?", ["Stem", "Anther and whole flower", "Stigma", "None of these"], "Saffron consists of the dried stigmas of the crocus flower."],
    ["केसर पौधे के किस भाग से प्राप्त होता है?", ["तना", "परागकोश तथा सम्पूर्ण पुष्प", "वर्तिकाग्र", "इनमें से कोई नहीं"], "केसर क्रोकस पुष्प के सूखे वर्तिकाग्र होते हैं।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["Which one of the following is responsible for the stimulating effect of tea ?", ["Alkaloid", "Flavonoid", "Steroid", "None of these"], "Caffeine, an alkaloid, gives tea its stimulating effect."],
    ["चाय के उत्तेजक प्रभाव के लिए निम्न में से कौन उत्तरदायी है?", ["एल्कलॉइड", "फ्लैवोनॉइड", "स्टेरॉइड", "इनमें से कोई नहीं"], "कैफीन (एल्कलॉइड) चाय को उत्तेजक प्रभाव देती है।"]),
  q(0, "general-studies", "general-science", "E", 0,
    ["Pashmina wool famous for its warmth is obtained from", ["Goat", "Sheep", "Bear", "None of these"], "Pashmina wool comes from the Changthangi (Pashmina) goat."],
    ["अपनी गर्माहट के लिए प्रसिद्ध पश्मीना ऊन प्राप्त की जाती है", ["बकरी से", "भेड़ से", "भालू से", "इनमें से कोई नहीं"], "पश्मीना ऊन पश्मीना (चंगथांगी) बकरी से मिलती है।"]),
  q(0, "computer", "security", "M", 2,
    ["‘Encryption’ in cyber world means", ["Cyber theft", "decoding some one’s personal data", "algorithmic alteration of password into scrabbled data to prevent access", "None of these"], "Encryption scrambles data with an algorithm so that unauthorised users cannot read it."],
    ["साइबर जगत में ‘एन्क्रिप्शन’ का अर्थ है", ["साइबर चोरी", "किसी के व्यक्तिगत डाटा को डिकोड करना", "पासवर्ड को पहुँच रोकने के लिए एल्गोरिथम द्वारा अव्यवस्थित डाटा में बदलना", "इनमें से कोई नहीं"], "एन्क्रिप्शन डाटा को एल्गोरिथम से अव्यवस्थित कर देता है ताकि अनधिकृत व्यक्ति उसे न पढ़ सके।"]),
  q(0, "computer", "fundamentals", "E", 2,
    ["Who is the father of Super Computer ?", ["Martin Cooper", "Lord Kelvin", "Seymour Cray", "None of these"], "Seymour Cray is called the father of the supercomputer."],
    ["सुपर कंप्यूटर का जनक कौन है?", ["मार्टिन कूपर", "लॉर्ड केल्विन", "सेमूर क्रे", "इनमें से कोई नहीं"], "सेमूर क्रे को सुपर कंप्यूटर का जनक कहा जाता है।"]),
  q(0, "computer", "programming-basics", "M", 3,
    ["Which one of the following computer languages is not the procedure-oriented language ?", ["C-language", "FORTRAN", "COBOL", "Simula"], "Simula is object-oriented; C, FORTRAN and COBOL are procedure-oriented."],
    ["निम्न में से कौन सी कंप्यूटर भाषा प्रक्रिया-उन्मुख भाषा नहीं है?", ["C-भाषा", "फोर्ट्रान", "कोबोल", "सिमुला"], "सिमुला ऑब्जेक्ट-उन्मुख है; C, फोर्ट्रान और कोबोल प्रक्रिया-उन्मुख हैं।"]),
  q(0, "computer", "operating-systems", "M", 3,
    ["Which one of the following applications uses the UNIX as an operating system ?", ["Internet servers", "Mobile devices", "Work station", "All of these"], "UNIX runs internet servers, mobile devices and workstations."],
    ["निम्न में से कौन सा अनुप्रयोग UNIX को ऑपरेटिंग सिस्टम के रूप में प्रयोग करता है?", ["इंटरनेट सर्वर", "मोबाइल उपकरण", "वर्क स्टेशन", "यह सभी"], "UNIX इंटरनेट सर्वर, मोबाइल उपकरणों और वर्कस्टेशनों पर चलता है।"]),
  q(0, "computer", "internet-networking", "M", 1,
    ["Which one of the following internet protocol version is the most deployed internet layer protocol ?", ["IPv2", "IPv4", "IPv8", "None of these"], "IPv4 is still the most widely deployed internet-layer protocol."],
    ["निम्न में से कौन सा इंटरनेट प्रोटोकॉल संस्करण सबसे अधिक तैनात इंटरनेट लेयर प्रोटोकॉल है?", ["IPv2", "IPv4", "IPv8", "इनमें से कोई नहीं"], "IPv4 आज भी सबसे अधिक प्रयुक्त इंटरनेट लेयर प्रोटोकॉल है।"]),
  q(0, "computer", "security", "E", 1,
    ["What is computer firewall ?", ["It is software or hardware-based program to protect the personal computer from crash due to bugs.", "It is software or hardware-based program to protect against threats and make the internet network secure.", "It is software or hardware-based program to enhance the speed of the personal computer.", "All the statements given above are correct."], "A firewall guards a network against threats and makes it secure."],
    ["कंप्यूटर फ़ायरवॉल क्या है?", ["यह सॉफ्टवेयर या हार्डवेयर आधारित प्रोग्राम है जो पर्सनल कंप्यूटर को बग के कारण क्रैश होने से बचाता है।", "यह सॉफ्टवेयर या हार्डवेयर आधारित प्रोग्राम है जो खतरों से सुरक्षा करता है और इंटरनेट नेटवर्क को सुरक्षित बनाता है।", "यह सॉफ्टवेयर या हार्डवेयर आधारित प्रोग्राम है जो पर्सनल कंप्यूटर की गति बढ़ाता है।", "ऊपर दिए गए सभी कथन सही हैं"], "फ़ायरवॉल नेटवर्क को खतरों से बचाकर उसे सुरक्षित बनाता है।"]),
  q(0, "computer", "web-technologies", "H", 2,
    ["What is the Super Cookie ?", ["It is a cookie that replicates after it is erased from the browser’s site.", "It is a cookie with a long life span.", "It is a cookie with a public suffix domain.", "None of these"], "A supercookie is set for a public suffix domain such as .com, so it can track users across many sites."],
    ["सुपर कुकी क्या है?", ["यह एक कुकी है जो ब्राउज़र की साइट से मिटाए जाने के बाद भी दोबारा बन जाती है।", "यह लंबी आयु वाली कुकी है।", "यह सार्वजनिक प्रत्यय डोमेन वाली कुकी है।", "इनमें से कोई नहीं"], "सुपर कुकी .com जैसे सार्वजनिक प्रत्यय डोमेन के लिए सेट होती है, इसलिए वह कई साइटों पर उपयोगकर्ता को ट्रैक कर सकती है।"]),
  q(0, "computer", "hardware", "M", 3,
    ["Which one of the following microprocessors is the world’s first commercially available microprocessor ?", ["Niagara", "Niagara-2", "Intel 8008", "Intel 4004"], "Intel 4004 (1971) was the first commercially available microprocessor."],
    ["निम्न में से कौन सा माइक्रोप्रोसेसर विश्व का पहला व्यावसायिक रूप से उपलब्ध माइक्रोप्रोसेसर है?", ["नियागरा", "नियागरा-2", "इंटेल 8008", "इंटेल 4004"], "इंटेल 4004 (1971) पहला व्यावसायिक रूप से उपलब्ध माइक्रोप्रोसेसर था।"]),
  q(0, "computer", "operating-systems", "M", 2,
    ["Most commonly used operating system in the super computers is", ["Mac OS", "Unix OS", "Linux OS", "None of these"], "Per the key, Linux is the most common operating system on supercomputers."],
    ["सुपर कंप्यूटरों में सबसे अधिक प्रयुक्त ऑपरेटिंग सिस्टम है", ["मैक OS", "यूनिक्स OS", "लिनक्स OS", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार सुपर कंप्यूटरों में लिनक्स सबसे अधिक प्रयुक्त है।"]),
  q(0, "computer", "fundamentals", "M", 3,
    ["Who is the father of Computer Science ?", ["John Moore", "Adam Osborne", "Neal Stephenson", "Alan Turing"], "Alan Turing is regarded as the father of computer science."],
    ["कंप्यूटर विज्ञान का जनक कौन है?", ["जॉन मूर", "एडम ऑसबोर्न", "नील स्टीफेन्सन", "एलन ट्यूरिंग"], "एलन ट्यूरिंग को कंप्यूटर विज्ञान का जनक माना जाता है।"]),
  q(1, "general-studies", "indian-history", "H", 0,
    ["‘Yapaniya’ was a school of", ["Jainism", "Buddhism", "Hinduism", "None of these"], "Yapaniya was a school (sect) of Jainism."],
    ["‘यापनीय’ किसका एक सम्प्रदाय था?", ["जैन धर्म", "बौद्ध धर्म", "हिन्दू धर्म", "इनमें से कोई नहीं"], "यापनीय जैन धर्म का एक सम्प्रदाय था।"]),
  q(1, "general-studies", "indian-history", "E", 0,
    ["Sarnath is associated with which aspect of Buddha’s life ?", ["First sermon", "Residence", "Death", "None of these"], "Buddha gave his first sermon at Sarnath (Dhammachakra Pravartana)."],
    ["सारनाथ बुद्ध के जीवन के किस पहलू से संबंधित है?", ["प्रथम उपदेश", "निवास", "मृत्यु", "इनमें से कोई नहीं"], "बुद्ध ने सारनाथ में पहला उपदेश (धर्मचक्र प्रवर्तन) दिया।"]),
  q(1, "general-studies", "indian-history", "E", 2,
    ["The great scholar, Banabhatta, lived during the reign of", ["Kanishka", "Ashoka", "Harsha", "None of these"], "Banabhatta was the court poet of Harsha and wrote the Harshacharita."],
    ["महान विद्वान बाणभट्ट किसके शासनकाल में हुए?", ["कनिष्क", "अशोक", "हर्ष", "इनमें से कोई नहीं"], "बाणभट्ट हर्ष के दरबारी कवि थे और उन्होंने हर्षचरित लिखा।"]),
  q(1, "general-studies", "indian-history", "H", 0,
    ["‘Jaubani’ is a dance form traditionally performed in North Eastern India by the", ["Dimasas", "Mizos", "Khasis", "None of these"], "Per the key, the Jaubani dance belongs to the Dimasa people."],
    ["‘जौबानी’ पूर्वोत्तर भारत का एक नृत्य रूप है जिसे परंपरागत रूप से किसके द्वारा किया जाता है?", ["दिमासा", "मिज़ो", "खासी", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार जौबानी नृत्य दिमासा लोगों का है।"]),
  q(1, "general-studies", "indian-history", "E", 3,
    ["Which of the following is a dance drama ?", ["Odissi", "Manipuri", "Kathak", "Kathakali"], "Kathakali is a dance-drama of Kerala."],
    ["निम्न में से कौन सा एक नृत्य नाटक है?", ["ओडिसी", "मणिपुरी", "कत्थक", "कथकली"], "कथकली केरल का नृत्य नाटक है।"]),
  q(1, "general-studies", "indian-history", "E", 2,
    ["India’s first talkie film produced in 1931 was", ["Neel Kamal", "Shakuntala", "Alam Ara", "None of these"], "Alam Ara (1931) was India's first talkie."],
    ["1931 में निर्मित भारत की पहली बोलती फिल्म थी", ["नील कमल", "शकुन्तला", "आलम आरा", "इनमें से कोई नहीं"], "आलम आरा (1931) भारत की पहली सवाक् फिल्म थी।"]),
  q(1, "general-studies", "indian-history", "E", 2,
    ["Which one of the following sites is famous for prehistoric paintings ?", ["Ajanta", "Amarawati", "Bhimbetka", "None of these"], "Bhimbetka is famous for prehistoric rock paintings."],
    ["निम्न में से कौन सा स्थल प्रागैतिहासिक चित्रों के लिए प्रसिद्ध है?", ["अजन्ता", "अमरावती", "भीमबेटका", "इनमें से कोई नहीं"], "भीमबेटका प्रागैतिहासिक शैलचित्रों के लिए प्रसिद्ध है।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["At which place the famous enigmatic Trimurty Sadasiva located ?", ["Ellora", "Ajanta", "Elephanta", "None of these"], "The Trimurti Sadashiva sculpture is at Elephanta caves."],
    ["प्रसिद्ध रहस्यमयी त्रिमूर्ति सदाशिव किस स्थान पर स्थित है?", ["एलोरा", "अजन्ता", "एलिफेंटा", "इनमें से कोई नहीं"], "त्रिमूर्ति सदाशिव की प्रतिमा एलिफेंटा गुफाओं में है।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["Gandhar Art is a combination of", ["Greek and Kushan style", "Indian and Greek style", "Indian and Kushan style", "None of these"], "Gandhara art blends Indian and Greek (Hellenistic) styles."],
    ["गांधार कला किसका संयोजन है?", ["यूनानी और कुषाण शैली", "भारतीय और यूनानी शैली", "भारतीय और कुषाण शैली", "इनमें से कोई नहीं"], "गांधार कला में भारतीय और यूनानी शैलियों का मिश्रण है।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Who wrote the book ‘Neel Darpan’ ?", ["Dinabandhu Mitra", "Rabindranath Tagore", "Bankim Chandra Chatterjee", "None of these"], "Dinabandhu Mitra wrote 'Neel Darpan' about the indigo planters' oppression."],
    ["‘नील दर्पण’ पुस्तक किसने लिखी?", ["दीनबन्धु मित्र", "रवीन्द्रनाथ टैगोर", "बंकिम चन्द्र चटर्जी", "इनमें से कोई नहीं"], "दीनबन्धु मित्र ने नील किसानों के शोषण पर 'नील दर्पण' लिखा।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["The sangam text ‘Talkappiyam’ is a work on", ["Grammar", "Astronomy", "Medicine", "None of these"], "Tolkappiyam is a work on Tamil grammar."],
    ["संगम ग्रंथ ‘तोल्काप्पियम’ किस विषय की रचना है?", ["व्याकरण", "खगोल विज्ञान", "चिकित्सा", "इनमें से कोई नहीं"], "तोल्काप्पियम तमिल व्याकरण का ग्रंथ है।"]),
  q(1, "general-studies", "indian-history", "E", 2,
    ["‘Baisakhi’ is celebrated on", ["birth anniversary of Guru Gobind Singh", "birth anniversary of Guru Nanak", "establishment of Khalsa Panth", "establishment of Golden Temple"], "Baisakhi marks the founding of the Khalsa Panth in 1699."],
    ["‘बैसाखी’ किस अवसर पर मनाई जाती है?", ["गुरु गोबिन्द सिंह की जयन्ती", "गुरु नानक की जयन्ती", "खालसा पंथ की स्थापना", "स्वर्ण मन्दिर की स्थापना"], "बैसाखी 1699 में खालसा पंथ की स्थापना की स्मृति में मनाई जाती है।"]),
  q(1, "general-studies", "indian-history", "E", 0,
    ["Which of the following festival is closely related to the legendary King Bali ?", ["Onam", "Pongal", "Holi", "Bihu"], "Onam is linked to the legend of King Mahabali."],
    ["निम्न में से कौन सा त्यौहार पौराणिक राजा बली से निकटता से संबंधित है?", ["ओणम", "पोंगल", "होली", "बिहू"], "ओणम का संबंध राजा महाबली की कथा से है।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Which of the following leader never became the President of Indian National Congress ?", ["Bal Gangadhar Tilak", "J L Nehru", "Dadabhai Naoroji", "Motilal Nehru"], "Tilak never became President of the Congress."],
    ["निम्न में से कौन सा नेता कभी भारतीय राष्ट्रीय कांग्रेस का अध्यक्ष नहीं बना?", ["बाल गंगाधर तिलक", "जे.एल. नेहरू", "दादाभाई नौरोजी", "मोतीलाल नेहरू"], "तिलक कभी कांग्रेस के अध्यक्ष नहीं बने।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Who of the following was known as ‘Deshbandhu’ ?", ["Jyotiba Phule", "Dadabhai Naoroji", "Chittranjan Das", "None of these"], "C.R. Das was known as 'Deshbandhu'."],
    ["निम्न में से किसे ‘देशबन्धु’ के नाम से जाना जाता था?", ["ज्योतिबा फुले", "दादाभाई नौरोजी", "चित्तरंजन दास", "इनमें से कोई नहीं"], "चित्तरंजन दास को 'देशबन्धु' कहा जाता था।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["All India Trade Union Congress was formed in the year            ", ["1928", "1920", "1922", "1924"], "AITUC was formed in 1920."],
    ["अखिल भारतीय ट्रेड यूनियन कांग्रेस का गठन किस वर्ष हुआ?", ["1928", "1920", "1922", "1924"], "AITUC का गठन 1920 में हुआ था।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Mahatma Gandhi became the President of Indian National Congress in", ["Kanpur Session, 1925", "Bombay Session, 1915", "Belgaum Session, 1924", "None of these"], "Gandhi presided over the Belgaum session in 1924."],
    ["महात्मा गांधी भारतीय राष्ट्रीय कांग्रेस के अध्यक्ष कब बने?", ["कानपुर अधिवेशन, 1925", "बम्बई अधिवेशन, 1915", "बेलगाम अधिवेशन, 1924", "इनमें से कोई नहीं"], "गांधीजी 1924 के बेलगाम अधिवेशन के अध्यक्ष बने।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Who is remembered as the pioneer of economic nationalism ?", ["R.C. Dutt", "B.C. Pal", "B.G. Tilak", "None of these"], "R.C. Dutt, with Naoroji, pioneered economic nationalism."],
    ["आर्थिक राष्ट्रवाद के अग्रदूत के रूप में किसे याद किया जाता है?", ["आर.सी. दत्त", "बी.सी. पाल", "बी.जी. तिलक", "इनमें से कोई नहीं"], "आर.सी. दत्त को आर्थिक राष्ट्रवाद का अग्रदूत माना जाता है।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Who presided over the Cabinet Mission ?", ["A.V. Alexander", "S. Cripps", "P. Lawrence", "None of these"], "Lord Pethick-Lawrence presided over the Cabinet Mission (1946)."],
    ["कैबिनेट मिशन की अध्यक्षता किसने की?", ["ए.वी. अलेक्जेंडर", "एस. क्रिप्स", "पी. लॉरेन्स", "इनमें से कोई नहीं"], "लॉर्ड पेथिक-लॉरेन्स ने कैबिनेट मिशन (1946) की अध्यक्षता की।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Who of the following was associated with the August Offer ?", ["Lord Linlithgow", "Lord Wavell", "Lord Irwin", "None of these"], "The August Offer (1940) was made by Viceroy Lord Linlithgow."],
    ["निम्न में से कौन अगस्त प्रस्ताव से संबंधित था?", ["लॉर्ड लिनलिथगो", "लॉर्ड वेवेल", "लॉर्ड इरविन", "इनमें से कोई नहीं"], "अगस्त प्रस्ताव (1940) वायसराय लॉर्ड लिनलिथगो ने रखा।"]),
  q(1, "general-studies", "indian-history", "E", 0,
    ["Who was called the ‘Iron Man of India’ ?", ["Sardar Vallabhbhai Patel", "Lala Lajpat Rai", "S.N. Banerjee", "None of these"], "Sardar Vallabhbhai Patel was the 'Iron Man of India'."],
    ["‘भारत का लौह पुरुष’ किसे कहा जाता था?", ["सरदार वल्लभभाई पटेल", "लाला लाजपत राय", "एस.एन. बनर्जी", "इनमें से कोई नहीं"], "सरदार वल्लभभाई पटेल 'भारत के लौह पुरुष' थे।"]),
  q(1, "general-studies", "indian-history", "E", 2,
    ["Who is known as ‘Lok Nayak’ ?", ["Bal Gangadhar Tilak", "Subhash Chandra Bose", "Jai Prakash Narayan", "None of these"], "Jayaprakash Narayan is known as 'Lok Nayak'."],
    ["‘लोक नायक’ के नाम से किसे जाना जाता है?", ["बाल गंगाधर तिलक", "सुभाष चन्द्र बोस", "जय प्रकाश नारायण", "इनमें से कोई नहीं"], "जयप्रकाश नारायण 'लोक नायक' के नाम से जाने जाते हैं।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Quit India Movement was launched in response to", ["Cabinet Mission Plan", "Wavell Plan", "Cripps Proposals", "None of these"], "The Quit India Movement (1942) followed the failure of the Cripps Mission."],
    ["भारत छोड़ो आन्दोलन किसकी प्रतिक्रिया में शुरू किया गया?", ["कैबिनेट मिशन योजना", "वेवेल योजना", "क्रिप्स प्रस्ताव", "इनमें से कोई नहीं"], "क्रिप्स मिशन की विफलता के बाद 1942 में भारत छोड़ो आन्दोलन शुरू हुआ।"]),
  q(1, "general-studies", "indian-history", "E", 2,
    ["The first state in India which was created on linguistic basis is", ["Haryana", "Gujarat", "Andhra Pradesh", "Kerala"], "Andhra Pradesh (1953) was the first state created on a linguistic basis."],
    ["भाषायी आधार पर बनाया गया भारत का पहला राज्य है", ["हरियाणा", "गुजरात", "आंध्र प्रदेश", "केरल"], "आंध्र प्रदेश (1953) भाषायी आधार पर बना पहला राज्य था।"]),
  q(1, "general-studies", "indian-history", "E", 0,
    ["Jammu and Kashmir became an integral part of India on 26th October of", ["1947", "1948", "1949", "None of these"], "The Instrument of Accession was signed on 26 October 1947."],
    ["जम्मू और कश्मीर 26 अक्तूबर को किस वर्ष भारत का अभिन्न अंग बना?", ["1947", "1948", "1949", "इनमें से कोई नहीं"], "विलय-पत्र पर 26 अक्तूबर 1947 को हस्ताक्षर हुए।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["Who amongst the following drafted the ‘Sarvodaya Plan’ ?", ["Vinoba Bhave", "Mahatma Gandhi", "Jai Prakash Narain", "Morarji Desai"], "Jayaprakash Narayan drafted the Sarvodaya Plan in 1950."],
    ["निम्नलिखित में से किसने ‘सर्वोदय योजना’ का मसौदा तैयार किया?", ["विनोबा भावे", "महात्मा गांधी", "जय प्रकाश नारायण", "मोरारजी देसाई"], "जयप्रकाश नारायण ने 1950 में सर्वोदय योजना का मसौदा बनाया।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Which revolutionary died after 64 days fast in Jail ?", ["Jatin Das", "M.L. Dhingra", "Ramprasad Bismil", "None of these"], "Jatin Das died in Lahore jail in 1929 after a 63-64 day fast."],
    ["किस क्रान्तिकारी की जेल में 64 दिन के उपवास के बाद मृत्यु हो गई?", ["जतिन दास", "एम.एल. धींगरा", "रामप्रसाद बिस्मिल", "इनमें से कोई नहीं"], "जतिन दास की 1929 में लाहौर जेल में लगभग 64 दिन के उपवास के बाद मृत्यु हुई।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["Rani Gaidinliu was the fearless freedom fighter from which of the following part of the then British India ?", ["Assam", "Manipur", "Allahabad", "None of these"], "Rani Gaidinliu was a Naga freedom fighter from Manipur (Nungkao)."],
    ["रानी गाइदिन्ल्यू तत्कालीन ब्रिटिश भारत के किस भाग की निडर स्वतंत्रता सेनानी थीं?", ["असम", "मणिपुर", "इलाहाबाद", "इनमें से कोई नहीं"], "रानी गाइदिन्ल्यू मणिपुर क्षेत्र की नागा स्वतंत्रता सेनानी थीं।"]),
  q(1, "general-studies", "indian-polity", "E", 2,
    ["The members of the Rajya Sabha are", ["mostly nominated", "elected directly", "elected indirectly", "None of these"], "Rajya Sabha members are elected indirectly by the elected members of State Assemblies."],
    ["राज्य सभा के सदस्य होते हैं", ["अधिकतर मनोनीत", "प्रत्यक्ष रूप से निर्वाचित", "अप्रत्यक्ष रूप से निर्वाचित", "इनमें से कोई नहीं"], "राज्य सभा के सदस्य राज्य विधानसभाओं के निर्वाचित सदस्यों द्वारा अप्रत्यक्ष रूप से चुने जाते हैं।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["What is the fix number of members of Lok Sabha ?", ["540", "545", "444", "None of these"], "The Constitution fixes the maximum strength of the Lok Sabha at 552, of which 545 are counted here as per the key."],
    ["लोक सभा के सदस्यों की निश्चित संख्या कितनी है?", ["540", "545", "444", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार लोक सभा की निश्चित संख्या 545 मानी गई है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["The function of the Pro-tem Speaker is to", ["swearing members", "conduct the proceedings of the House in the absence of the speaker", "officiate as speaker when the speaker is unlikely to be elected", "None of these"], "The pro-tem Speaker swears in the new members and presides until a Speaker is elected."],
    ["प्रोटेम स्पीकर का कार्य है", ["सदस्यों को शपथ दिलाना", "अध्यक्ष की अनुपस्थिति में सदन की कार्यवाही का संचालन करना", "जब अध्यक्ष के निर्वाचित होने की संभावना न हो तब अध्यक्ष का कार्य करना", "इनमें से कोई नहीं"], "प्रोटेम स्पीकर नए सदस्यों को शपथ दिलाता है और अध्यक्ष के चुने जाने तक सदन चलाता है।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["What is ‘Zero Hour’ ?", ["when a Money Bill is introduced in the Lok Sabha", "interval between the morning and afternoon sessions", "when matters of utmost importance are raised", "None of these"], "Zero Hour is the time when members raise urgent matters without prior notice."],
    ["‘शून्य काल’ क्या है?", ["जब लोक सभा में धन विधेयक प्रस्तुत किया जाता है", "प्रातःकालीन और अपराह्न सत्रों के बीच का अन्तराल", "जब अत्यन्त महत्त्व के विषय उठाए जाते हैं", "इनमें से कोई नहीं"], "शून्य काल में सदस्य बिना पूर्व सूचना के अत्यावश्यक विषय उठाते हैं।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["To whom does the Public Accounts Committee submit its report ?", ["Union Finance Minister", "Chairman of Rajya Sabha", "Speaker of Lok Sabha", "President of India"], "The Public Accounts Committee submits its report to the Speaker of the Lok Sabha."],
    ["लोक लेखा समिति अपना प्रतिवेदन किसे प्रस्तुत करती है?", ["केन्द्रीय वित्त मंत्री", "राज्य सभा के सभापति", "लोक सभा अध्यक्ष", "भारत के राष्ट्रपति"], "लोक लेखा समिति अपना प्रतिवेदन लोक सभा अध्यक्ष को प्रस्तुत करती है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["How many types of writs can be issued by the Supreme Court ?", ["5", "6", "4", "None of these"], "The Supreme Court can issue five writs: habeas corpus, mandamus, prohibition, certiorari and quo warranto."],
    ["सर्वोच्च न्यायालय कितने प्रकार की रिट जारी कर सकता है?", ["5", "6", "4", "इनमें से कोई नहीं"], "सर्वोच्च न्यायालय पाँच रिट जारी कर सकता है: बन्दी प्रत्यक्षीकरण, परमादेश, प्रतिषेध, उत्प्रेषण और अधिकार-पृच्छा।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["Which of the following is not appointed by the Governor ?", ["Advocate General", "Chief Minster", "Member of State Public Service Commission", "Judges of the High Court"], "High Court judges are appointed by the President, not the Governor."],
    ["निम्न में से किसकी नियुक्ति राज्यपाल द्वारा नहीं की जाती?", ["महाधिवक्ता", "मुख्यमंत्री", "राज्य लोक सेवा आयोग का सदस्य", "उच्च न्यायालय के न्यायाधीश"], "उच्च न्यायालय के न्यायाधीशों की नियुक्ति राष्ट्रपति करते हैं, राज्यपाल नहीं।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["The salary of the Governor is charged on", ["the contingency fund of the state", "the consolidated fund of India", "the contingency fund of India", "the consolidated fund of the state"], "The Governor's salary is charged on the Consolidated Fund of the State."],
    ["राज्यपाल का वेतन किस पर भारित होता है?", ["राज्य की आकस्मिकता निधि", "भारत की संचित निधि", "भारत की आकस्मिकता निधि", "राज्य की संचित निधि"], "राज्यपाल का वेतन राज्य की संचित निधि पर भारित होता है।"]),
  q(1, "general-studies", "indian-polity", "E", 0,
    ["The three-tier system of Panchayati Raj was initially recommended by", ["Balwant Rai Mehta Committee", "Ashok Mehta Committee", "L.M. Singhivi Committee", "None of these"], "The Balwant Rai Mehta Committee (1957) first recommended the three-tier Panchayati Raj."],
    ["पंचायती राज की त्रि-स्तरीय प्रणाली की संस्तुति सबसे पहले किसने की थी?", ["बलवन्त राय मेहता समिति", "अशोक मेहता समिति", "एल.एम. सिंघवी समिति", "इनमें से कोई नहीं"], "बलवन्त राय मेहता समिति (1957) ने सबसे पहले त्रि-स्तरीय पंचायती राज की सिफारिश की।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["‘PRIYASOFT’ is related to", ["Panchayat", "Land Record", "Public Distribution System", "None of these"], "PRIASoft is the software used for Panchayat accounting."],
    ["‘प्रियासॉफ्ट’ किससे संबंधित है?", ["पंचायत", "भूमि अभिलेख", "सार्वजनिक वितरण प्रणाली", "इनमें से कोई नहीं"], "प्रियासॉफ्ट पंचायतों के लेखा-जोखा का सॉफ्टवेयर है।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["Who is the chairman of Second Administrative Reforms Commission ?", ["Ahmed Patel", "Bimal Jalan", "M. Veerapa Moily", "None of these"], "M. Veerappa Moily chaired the Second Administrative Reforms Commission."],
    ["द्वितीय प्रशासनिक सुधार आयोग का अध्यक्ष कौन है?", ["अहमद पटेल", "बिमल जालान", "एम. वीरप्पा मोइली", "इनमें से कोई नहीं"], "एम. वीरप्पा मोइली द्वितीय प्रशासनिक सुधार आयोग के अध्यक्ष थे।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["A financial emergency can be declared by applying which of the following article of the constitution of India ?", ["360", "356", "352", "370"], "Article 360 provides for a financial emergency."],
    ["भारतीय संविधान के निम्न में से किस अनुच्छेद के प्रयोग से वित्तीय आपातकाल घोषित किया जा सकता है?", ["360", "356", "352", "370"], "अनुच्छेद 360 वित्तीय आपातकाल से संबंधित है।"]),
  q(1, "general-studies", "indian-polity", "E", 2,
    ["How many languages have been recognized by the Constitution ?", ["18", "20", "22", "None of these"], "The Eighth Schedule recognises 22 languages."],
    ["संविधान द्वारा कितनी भाषाओं को मान्यता दी गई है?", ["18", "20", "22", "इनमें से कोई नहीं"], "आठवीं अनुसूची में 22 भाषाएँ मान्यता प्राप्त हैं।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Which of the following is contained in the eleventh schedule of Indian Constitution ?", ["Provisions of disqualification on grounds of defection", "Provisions of Panchayati Raj", "Provisions of Municipal Corporation", "None of these"], "The Eleventh Schedule lists the powers of Panchayats."],
    ["भारतीय संविधान की ग्यारहवीं अनुसूची में निम्न में से क्या सम्मिलित है?", ["दल-बदल के आधार पर अयोग्यता के उपबंध", "पंचायती राज के उपबंध", "नगर निगम के उपबंध", "इनमें से कोई नहीं"], "ग्यारहवीं अनुसूची में पंचायतों की शक्तियाँ दी गई हैं।"]),
  q(1, "general-studies", "indian-economy", "M", 1,
    ["Which one of the following schemes is the recast form of the National Literacy Mission of India ?", ["Bharat Kosh", "Sakshar Bharat", "National Livelihood Mission", "None of these"], "Sakshar Bharat (2009) is the recast form of the National Literacy Mission."],
    ["निम्न में से कौन सी योजना भारत के राष्ट्रीय साक्षरता मिशन का पुनर्गठित रूप है?", ["भारत कोष", "साक्षर भारत", "राष्ट्रीय आजीविका मिशन", "इनमें से कोई नहीं"], "साक्षर भारत (2009) राष्ट्रीय साक्षरता मिशन का पुनर्गठित रूप है।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["Who are provided social security under the ‘Aam Admi Bima Yojna’ ?", ["All landless labours living in rural areas", "All labours in urban areas", "Both (A) and (B)", "None of these"], "Aam Admi Bima Yojana covered landless labourers in rural areas."],
    ["‘आम आदमी बीमा योजना’ के अन्तर्गत किनको सामाजिक सुरक्षा प्रदान की गई है?", ["ग्रामीण क्षेत्रों में रहने वाले सभी भूमिहीन श्रमिक", "शहरी क्षेत्रों में सभी श्रमिक", "(A) तथा (B) दोनों", "इनमें से कोई नहीं"], "आम आदमी बीमा योजना ग्रामीण क्षेत्रों के भूमिहीन श्रमिकों के लिए थी।"]),
  q(1, "general-studies", "indian-economy", "M", 2,
    ["National Rural Employment Guarantee Scheme was launched initially in", ["50 districts", "100 districts", "200 districts", "None of these"], "NREGA began in 200 districts in 2006."],
    ["राष्ट्रीय ग्रामीण रोज़गार गारंटी स्कीम प्रारम्भिक तौर पर कितने जिलों में चलायी गयी थी?", ["50 जिलों में", "100 जिलों में", "200 जिलों में", "इनमें से कोई नहीं"], "NREGA 2006 में 200 जिलों में शुरू हुई।"]),
  q(1, "general-studies", "indian-economy", "E", 0,
    ["NITI Aayog stands for", ["National Institution for Transforming India", "New India Transforming Institute", "National India Transforming Institute", "None of these"], "NITI stands for National Institution for Transforming India."],
    ["नीति (NITI) आयोग का आशय है", ["नेशनल इंस्टीट्यूशन फॉर ट्रांसफॉर्मिंग इंडिया", "न्यू इंडिया ट्रांसफॉर्मिंग इंस्टीट्यूट", "नेशनल इंडिया ट्रांसफॉर्मिंग इंस्टीट्यूट", "इनमें से कोई नहीं"], "NITI का अर्थ नेशनल इंस्टीट्यूशन फॉर ट्रांसफॉर्मिंग इंडिया है।"]),
  q(1, "general-studies", "indian-economy", "E", 2,
    ["Where is the Central Rice Research Institute located ?", ["Shimla", "Bengaluru", "Cuttack", "None of these"], "The Central Rice Research Institute is at Cuttack, Odisha."],
    ["केन्द्रीय चावल अनुसंधान संस्थान कहाँ स्थित है?", ["शिमला", "बेंगलुरु", "कटक", "इनमें से कोई नहीं"], "केन्द्रीय चावल अनुसंधान संस्थान कटक (ओडिशा) में है।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["Gilt-edged means", ["market of Government securities", "bullion market", "market of guns", "None of these"], "Gilt-edged means the market for government securities."],
    ["गिल्ट-एड्ज का अर्थ है", ["सरकारी प्रतिभूतियों की मार्केट", "बुलीयन मार्केट", "गन की मार्केट", "इनमें से कोई नहीं"], "गिल्ट-एड्ज का अर्थ सरकारी प्रतिभूतियों का बाज़ार है।"]),
  q(1, "general-studies", "indian-economy", "E", 3,
    ["Priority sector lending by banks in India constitutes the lending to", ["Weaker sections", "Agriculture", "Micro and small enterprises", "All of these"], "Priority sector lending covers agriculture, weaker sections and micro and small enterprises."],
    ["भारत में बैंकों द्वारा दिए जाने वाले ऋण में किस क्षेत्र को प्राथमिकता दी गई है?", ["कमजोर वर्गों के लिए", "कृषि के लिए", "सूक्ष्म तथा लघु उद्यमों के लिए", "उपरोक्त सभी के लिए"], "प्राथमिकता क्षेत्र ऋण में कृषि, कमजोर वर्ग और सूक्ष्म-लघु उद्यम सभी आते हैं।"]),
  q(1, "general-studies", "indian-economy", "E", 1,
    ["The major aim of devaluation is to", ["encourage imports", "encourage exports", "both (A) and (B)", "None of these"], "Devaluation makes exports cheaper and imports costlier, so it aims to boost exports."],
    ["अवमूल्यन का प्रमुख उद्देश्य है", ["आयात को बढ़ावा", "निर्यात को बढ़ावा", "(A) तथा (B) दोनों", "इनमें से कोई नहीं"], "अवमूल्यन से निर्यात सस्ते और आयात महँगे होते हैं, इसलिए इसका उद्देश्य निर्यात बढ़ाना है।"]),
  q(1, "general-studies", "indian-economy", "E", 2,
    ["Insurance trade in India is regulated by", ["SEBI", "RBI", "IRDA", "None of these"], "IRDA regulates the insurance sector in India."],
    ["भारत में बीमा व्यवसाय का नियमन इसके द्वारा होता है", ["SEBI", "RBI", "IRDA", "इनमें से कोई नहीं"], "भारत में बीमा क्षेत्र का नियमन IRDA करता है।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["‘Octroi’ is levied and collected by", ["Local bodies", "State Government", "Central Government", "None of these"], "Octroi is a local tax on goods entering a town, collected by local bodies."],
    ["‘चुंगी’ की वसूली और संग्रहण किया जाता है", ["स्थानीय निकायों द्वारा", "राज्य सरकार द्वारा", "केन्द्र सरकार द्वारा", "इनमें से कोई नहीं"], "चुंगी नगर में आने वाले माल पर स्थानीय कर है, जिसे स्थानीय निकाय वसूलते हैं।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["Where was the electricity supply first introduced in India ?", ["Darjeeling", "Mumbai", "Chennai", "None of these"], "Electricity was first supplied in India at Darjeeling in 1897."],
    ["भारत में सर्वप्रथम विद्युत की आपूर्ति कहाँ से आरंभ की गई थी?", ["दार्जीलिंग", "मुम्बई", "चेन्नई", "इनमें से कोई नहीं"], "भारत में बिजली की आपूर्ति सबसे पहले 1897 में दार्जीलिंग में शुरू हुई।"]),
  q(1, "general-studies", "indian-economy", "M", 2,
    ["The term ‘Paper Gold’ means", ["Deficit financing", "Currencies still on Gold standard", "Special Drawing Rights (SDRs) of the IMF", "None of these"], "'Paper gold' is the IMF's Special Drawing Rights."],
    ["पद ‘पेपर गोल्ड’ से आशय है", ["घाटे का वित्त", "अब तक स्वर्ण मानों की मुद्रा", "IMF का विशिष्ट आहरणाधिकार (SDRs)", "इनमें से कोई नहीं"], "'पेपर गोल्ड' IMF के विशेष आहरण अधिकार (SDR) को कहते हैं।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["Which one of the following is not a member of MERCOSUR (Southern Common Market) ?", ["Chile", "Argentina", "Paraguay", "Uruguay"], "Chile is not a full member of MERCOSUR (Argentina, Brazil, Paraguay, Uruguay are)."],
    ["निम्न में से कौन मर्कोसुर (दक्षिणी साझा बाज़ार) का सदस्य नहीं है?", ["चिली", "अर्जेंटीना", "पैराग्वे", "उरुग्वे"], "चिली मर्कोसुर का पूर्ण सदस्य नहीं है (अर्जेंटीना, ब्राज़ील, पैराग्वे, उरुग्वे हैं)।"]),
  q(1, "general-studies", "indian-geography", "E", 0,
    ["Which one of the following state has the longest coastline ?", ["Gujarat", "Maharashtra", "Andhra Pradesh", "Tamil Nadu"], "Gujarat has the longest coastline in India."],
    ["निम्न में से किस राज्य की तटरेखा सबसे लंबी है?", ["गुजरात", "महाराष्ट्र", "आंध्र प्रदेश", "तमिलनाडु"], "गुजरात की तटरेखा भारत में सबसे लंबी है।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Western Ghats are", ["escarpment of the plateaus", "plateaus", "plains", "None of these"], "The Western Ghats are the steep escarpment of the Deccan plateau."],
    ["पश्चिमी घाट हैं", ["पठारों के कगार", "पठार", "मैदान", "इनमें से कोई नहीं"], "पश्चिमी घाट दक्कन पठार का तीव्र कगार हैं।"]),
  q(1, "general-studies", "indian-geography", "E", 3,
    ["With which country India has the longest International boundary ?", ["China", "Pakistan", "Nepal", "Bangladesh"], "India's longest international border is with Bangladesh."],
    ["भारत की सबसे लंबी अंतर्राष्ट्रीय सीमा किस देश के साथ है?", ["चीन", "पाकिस्तान", "नेपाल", "बांग्लादेश"], "भारत की सबसे लंबी अंतर्राष्ट्रीय सीमा बांग्लादेश से लगती है।"]),
  q(1, "general-studies", "indian-geography", "E", 2,
    ["Zanskar range is situated in", ["Uttaranchal", "Arunachal Pradesh", "Jammu and Kashmir", "None of these"], "The Zanskar range lies in Jammu and Kashmir (Ladakh)."],
    ["ज़ांस्कर श्रेणी स्थित है", ["उत्तरांचल में", "अरुणाचल प्रदेश में", "जम्मू और कश्मीर में", "इनमें से कोई नहीं"], "ज़ांस्कर श्रेणी जम्मू-कश्मीर (लद्दाख) में है।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Which one of the following states has the world’s largest fresh water island ?", ["Assam", "Meghalaya", "Mizoram", "None of these"], "Majuli in Assam is the world's largest river island."],
    ["निम्न में से किस राज्य में विश्व का सबसे बड़ा मीठे जल का द्वीप है?", ["असम", "मेघालय", "मिज़ोरम", "इनमें से कोई नहीं"], "असम का माजुली विश्व का सबसे बड़ा नदी द्वीप है।"]),
  q(1, "general-studies", "indian-geography", "M", 3,
    ["Which one of the following rivers forms an estuary ?", ["Mahanadi", "Cauvery", "Krishna", "Narmada"], "The Narmada forms an estuary, while the others form deltas."],
    ["निम्न में से कौन सी नदी ज्वारनदमुख (एश्चुअरी) बनाती है?", ["महानदी", "कावेरी", "कृष्णा", "नर्मदा"], "नर्मदा ज्वारनदमुख बनाती है, जबकि अन्य नदियाँ डेल्टा बनाती हैं।"]),
  q(1, "general-studies", "general-science", "E", 1,
    ["The technique of inducing rain from cloud is called", ["Cloud engineering", "Cloud seeding", "Cloud computing", "None of these"], "Inducing rain from clouds is called cloud seeding."],
    ["बादलों से वर्षा कराने की तकनीक को कहते हैं", ["क्लाउड इंजीनियरिंग", "क्लाउड सीडिंग", "क्लाउड कंप्यूटिंग", "इनमें से कोई नहीं"], "बादलों से कृत्रिम वर्षा कराना क्लाउड सीडिंग कहलाता है।"]),
  q(1, "general-studies", "indian-geography", "E", 0,
    ["Which one of the following is the first National Park established in India ?", ["Corbett", "Bandipur", "Great Himalayan", "Pin Valley"], "Corbett (1936) was India's first national park."],
    ["भारत में स्थापित प्रथम राष्ट्रीय उद्यान निम्न में से कौन सा है?", ["कॉर्बेट", "बांदीपुर", "ग्रेट हिमालयन", "पिन वैली"], "कॉर्बेट (1936) भारत का पहला राष्ट्रीय उद्यान था।"]),
  q(1, "general-studies", "indian-geography", "E", 0,
    ["Which type of soil retains maximum amount of water ?", ["Clay", "Sandy", "Loam", "Red"], "Clay soil has the highest water-holding capacity."],
    ["किस प्रकार की मिट्टी सर्वाधिक जल धारण करती है?", ["चिकनी", "बलुई", "दोमट", "लाल"], "चिकनी मिट्टी की जल धारण क्षमता सबसे अधिक होती है।"]),
  q(1, "general-studies", "indian-geography", "E", 1,
    ["Terrace farming is done", ["on roof tops", "on the slope of hills", "on mountain tops", "in dry regions"], "Terrace farming is done on hill slopes."],
    ["सीढ़ीदार खेती की जाती है", ["छतों पर", "पहाड़ी ढलानों पर", "पर्वत शिखरों पर", "शुष्क क्षेत्रों में"], "सीढ़ीदार खेती पहाड़ी ढलानों पर की जाती है।"]),
  q(1, "general-studies", "indian-geography", "E", 1,
    ["Which of the following is not a Kharif crop ?", ["Cotton", "Mustard", "Groundnut", "Maize"], "Mustard is a Rabi crop."],
    ["निम्न में से कौन सी खरीफ की फसल नहीं है?", ["कपास", "सरसों", "मूंगफली", "मक्का"], "सरसों रबी की फसल है।"]),
  q(1, "general-studies", "indian-geography", "E", 0,
    ["‘Tehri’ dam is built on which of the following rivers ?", ["Bhagirathi", "Ganga", "Yamuna", "None of these"], "The Tehri dam is on the Bhagirathi."],
    ["‘टिहरी’ बाँध निम्न में से किस नदी पर बना है?", ["भागीरथी", "गंगा", "यमुना", "इनमें से कोई नहीं"], "टिहरी बाँध भागीरथी नदी पर बना है।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["Which of the following is called the ‘Shrimp Capital of India’ ?", ["Kochi", "Mangalore", "Nellore", "None of these"], "Nellore is called the Shrimp Capital of India."],
    ["निम्न में से किसे ‘भारत की झींगा राजधानी’ कहा जाता है?", ["कोच्चि", "मंगलौर", "नेल्लोर", "इनमें से कोई नहीं"], "नेल्लोर को भारत की झींगा राजधानी कहा जाता है।"]),
  q(1, "general-studies", "indian-geography", "H", 0,
    ["Which of the following states is the largest producer of Rock Phosphate in India ?", ["Rajasthan", "Himachal Pradesh", "Kerala", "None of these"], "Rajasthan is the largest producer of rock phosphate."],
    ["निम्न में से कौन सा राज्य भारत में रॉक फॉस्फेट का सबसे बड़ा उत्पादक है?", ["राजस्थान", "हिमाचल प्रदेश", "केरल", "इनमें से कोई नहीं"], "राजस्थान रॉक फॉस्फेट का सबसे बड़ा उत्पादक है।"]),
  q(1, "general-studies", "indian-geography", "E", 2,
    ["‘Manchester’ of South India is", ["Madurai", "Chennai", "Coimbatore", "None of these"], "Coimbatore is the 'Manchester of South India' for its textile mills."],
    ["दक्षिण भारत का ‘मैनचेस्टर’ है", ["मदुरै", "चेन्नई", "कोयम्बटूर", "इनमें से कोई नहीं"], "वस्त्र मिलों के कारण कोयम्बटूर को 'दक्षिण भारत का मैनचेस्टर' कहा जाता है।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Which is the artificial port of India ?", ["Chennai", "Mangalore", "Kandla", "Haldia"], "Chennai is an artificial harbour, built by constructing breakwaters."],
    ["भारत का कृत्रिम बंदरगाह कौन सा है?", ["चेन्नई", "मंगलौर", "कांडला", "हल्दिया"], "चेन्नई कृत्रिम बंदरगाह है, जिसे ब्रेकवाटर बनाकर तैयार किया गया है।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["Which one of the following is the largest tribal group of India as per Census 2011 ?", ["Santhals", "Tharus", "Bhils", "None of these"], "The Bhils are India's largest tribal group."],
    ["जनगणना 2011 के अनुसार भारत का सबसे बड़ा जनजातीय समूह कौन सा है?", ["संथाल", "थारू", "भील", "इनमें से कोई नहीं"], "भील भारत का सबसे बड़ा जनजातीय समूह है।"]),
  q(1, "general-studies", "indian-geography", "E", 2,
    ["‘Red Data Book’ gives information about species which are", ["dangerous", "extinct", "endangered", "None of these"], "The Red Data Book lists endangered species."],
    ["‘रेड डाटा बुक’ उन प्रजातियों के बारे में जानकारी देती है जो हैं", ["खतरनाक", "विलुप्त", "संकटापन्न", "इनमें से कोई नहीं"], "रेड डाटा बुक में संकटापन्न प्रजातियों की सूची होती है।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["‘SPM’ stands for", ["Standard Particles Material", "Special Polling Management", "Suspended Particulate Matter", "None of these"], "SPM means Suspended Particulate Matter, an air pollutant."],
    ["‘SPM’ का पूर्ण रूप है", ["स्टैण्डर्ड पार्टिकल्स मैटेरियल", "स्पेशल पोलिंग मैनेजमेंट", "सस्पेंडेड पार्टिकुलेट मैटर", "इनमें से कोई नहीं"], "SPM का अर्थ सस्पेंडेड पार्टिकुलेट मैटर है, जो एक वायु प्रदूषक है।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Ozone holes are more pronounced at the", ["Poles", "Equator", "Tropic of Cancer", "Tropic of Capricorn"], "Ozone holes are most pronounced over the poles."],
    ["ओज़ोन छिद्र अधिक स्पष्ट होते हैं", ["ध्रुवों पर", "भूमध्य रेखा पर", "कर्क रेखा पर", "मकर रेखा पर"], "ओज़ोन छिद्र ध्रुवों पर सबसे अधिक स्पष्ट होते हैं।"]),
  q(1, "general-studies", "indian-geography", "H", 1,
    ["‘Shola Forest’ are", ["temperate forest", "tropical montane forest", "tropical evergreen forest", "None of these"], "Shola forests are tropical montane forests of South India."],
    ["‘शोला वन’ हैं", ["शीतोष्ण वन", "उष्णकटिबंधीय पर्वतीय वन", "उष्णकटिबंधीय सदाबहार वन", "इनमें से कोई नहीं"], "शोला वन दक्षिण भारत के उष्णकटिबंधीय पर्वतीय वन हैं।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["The largest number of tiger reserves in India are located in", ["Madhya Pradesh", "Uttar Pradesh", "Himachal Pradesh", "None of these"], "Per the key, Madhya Pradesh has the most tiger reserves."],
    ["भारत में सबसे अधिक बाघ अभयारण्य कहाँ स्थित हैं?", ["मध्य प्रदेश", "उत्तर प्रदेश", "हिमाचल प्रदेश", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार सबसे अधिक बाघ अभयारण्य मध्य प्रदेश में हैं।"]),
  q(1, "general-studies", "indian-geography", "E", 2,
    ["Which gas is responsible for global warming ?", ["Oxygen", "Carbon monoxide", "Carbon dioxide", "None of these"], "Carbon dioxide is the main greenhouse gas behind global warming."],
    ["कौन सी गैस वैश्विक तापन के लिए उत्तरदायी है?", ["ऑक्सीजन", "कार्बन मोनोऑक्साइड", "कार्बन डाइऑक्साइड", "इनमें से कोई नहीं"], "कार्बन डाइऑक्साइड वैश्विक तापन की मुख्य ग्रीनहाउस गैस है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["The oldest coal-field in India is", ["Jharia", "Raniganj", "Bokaro", "None of these"], "Raniganj (West Bengal) is India's oldest coalfield."],
    ["भारत का सबसे पुराना कोयला क्षेत्र है", ["झरिया", "रानीगंज", "बोकारो", "इनमें से कोई नहीं"], "रानीगंज (पश्चिम बंगाल) भारत का सबसे पुराना कोयला क्षेत्र है।"]),
  q(2, "quant", "mensuration", "E", 0,
    ["A cube is divided into 27 small cubes of 3 cm side each. What will be the length of the side of big cube ?", ["9 cm", "12 cm", "15 cm", "18 cm"], "27 small cubes make a 3 × 3 × 3 cube, so the side is 3 × 3 = 9 cm."],
    ["एक घन को 3 सेमी भुजा वाले 27 छोटे घनों में विभाजित किया गया है। बड़े घन की भुजा की लंबाई कितनी होगी?", ["9 सेमी", "12 सेमी", "15 सेमी", "18 सेमी"], "27 छोटे घन 3 × 3 × 3 का घन बनाते हैं, इसलिए भुजा 3 × 3 = 9 सेमी है।"]),
  q(2, "reasoning", "direction-sense", "M", 0,
    ["Piyush walked 7 m in the direction of North and then he turned to his right and walked 6 m. After this he turned to his right and moved 15 m. Now how far is he from the starting point ?", ["10 m", "8 m", "9 m", "14 m"], "He ends up 6 m east and 8 m south of the start, so the distance is √(6² + 8²) = 10 m."],
    ["पीयूष उत्तर दिशा में 7 मी चला और फिर दाएँ मुड़कर 6 मी चला। इसके बाद वह फिर दाएँ मुड़ा और 15 मी चला। अब वह प्रारम्भिक बिंदु से कितनी दूरी पर है?", ["10 मी", "8 मी", "9 मी", "14 मी"], "वह प्रारम्भिक बिंदु से 6 मी पूर्व और 8 मी दक्षिण में है, इसलिए दूरी √(6² + 8²) = 10 मी है।"]),
  q(2, "reasoning", "puzzles", "M", 2,
    ["Directions: A, B, C, D, E and F are sitting in a circle facing towards the centre. D is between F and B. A is second to the left of D and second to the right of E. Who is facing towards A ?", ["B", "F", "B or F", "None of these"], "D sits at position 0, A at 2, E at 4 and C at 3; B and F take positions 1 and 5, and A faces position 5 (B or F)."],
    ["निर्देश (प्र. 132 व 133): A, B, C, D, E तथा F एक वृत्त में बैठे हैं और उनका मुख केन्द्र की ओर है। D, F तथा B के मध्य में है, A, D से बाएँ तरफ दूसरे क्रम में है तथा E से दाहिने तरफ दूसरे क्रम में है। A की तरफ कौन मुख किए हुए है?", ["B", "F", "B या F", "इनमें से कोई नहीं"], "यदि D स्थान 0 पर, A स्थान 2 पर, E स्थान 4 पर और C स्थान 3 पर हो, तो B और F स्थान 1 व 5 पर होंगे; A के सामने स्थान 5 (B या F) है।"]),
  q(2, "reasoning", "puzzles", "M", 0,
    ["Directions: A, B, C, D, E and F are sitting in a circle facing towards the centre. D is between F and B. A is second to the left of D and second to the right of E. Who is facing towards D ?", ["C", "A", "E", "None of these"], "C sits at position 3, directly opposite D at position 0."],
    ["निर्देश (प्र. 132 व 133): A, B, C, D, E तथा F एक वृत्त में बैठे हैं और उनका मुख केन्द्र की ओर है। D, F तथा B के मध्य में है, A, D से बाएँ तरफ दूसरे क्रम में है तथा E से दाहिने तरफ दूसरे क्रम में है। D की तरफ कौन मुख किए हुए है?", ["C", "A", "E", "इनमें से कोई नहीं"], "C स्थान 3 पर है, जो स्थान 0 पर बैठे D के ठीक सामने है।"]),
  q(2, "reasoning", "ranking", "E", 3,
    ["Raman is 9th from downwards in a class of 31 students. What will be his position from upwards ?", ["22nd", "24th", "21st", "23rd"], "Position from the top = 31 − 9 + 1 = 23rd."],
    ["रमन 31 विद्यार्थियों की कक्षा में नीचे से 9वें स्थान पर है। ऊपर से उसकी स्थिति क्या होगी?", ["22वाँ", "24वाँ", "21वाँ", "23वाँ"], "ऊपर से स्थिति = 31 − 9 + 1 = 23वाँ।"]),
  q(2, "reasoning", "blood-relations", "M", 1,
    ["Introducing a woman, a man said, “His father is the only son of my mother.” How is the woman related to that man ?", ["Mother", "Daughter", "Sister", "Aunt"], "My mother's only son is the man himself, so the woman's father is the man and she is his daughter."],
    ["एक महिला का परिचय देते हुए एक व्यक्ति ने बताया कि “उसका पिता मेरी माता का अकेला पुत्र है।” उस व्यक्ति से महिला का संबंध क्या है?", ["माता", "पुत्री", "बहन", "चाची"], "माता का अकेला पुत्र वह व्यक्ति स्वयं है, इसलिए महिला का पिता वही है और महिला उसकी पुत्री है।"]),
  q(2, "quant", "number-system", "M", 0,
    ["If all the numbers from 7 to 51 which are divisible by 7 are removed, then how many numbers will be left ?", ["38", "36", "35", "39"], "There are 45 numbers from 7 to 51; 7 of them (7, 14, ..., 49) are multiples of 7, so 38 remain."],
    ["यदि 7 से 51 तक की सभी 7 से भाज्य संख्याएँ निकाल ली जाएँ तब कुल कितनी संख्याएँ शेष रहेंगी?", ["38", "36", "35", "39"], "7 से 51 तक 45 संख्याएँ हैं; इनमें 7 संख्याएँ (7, 14, ..., 49) 7 की गुणज हैं, इसलिए 38 शेष रहती हैं।"]),
  q(2, "reasoning", "clock-calendar", "M", 1,
    ["If the third day of month is Monday, then which day will be on 5th day after 21st of the month ?", ["Monday", "Wednesday", "Tuesday", "None of these"], "The 5th day after the 21st is the 26th; the 3rd is Monday and 26 − 3 = 23 = 2 (mod 7), so it is Wednesday."],
    ["यदि माह का तीसरा दिन सोमवार हो, तो उसी माह के 21वें दिन के पश्चात् 5वाँ दिन कौन सा होगा?", ["सोमवार", "बुधवार", "मंगलवार", "इनमें से कोई नहीं"], "21वें के बाद 5वाँ दिन 26वाँ है; 3 तारीख सोमवार है और 26 − 3 = 23 ≡ 2 (मॉड 7), इसलिए बुधवार होगा।"]),
  q(2, "reasoning", "coding-decoding", "M", 0,
    ["In a code ‘NOBLE’ is denoted by ‘QREOH’, then the coded form of ‘PLATE’ in the same code will be", ["SODWH", "SODVH", "SOCWH", "None of these"], "Each letter moves 3 places ahead: P→S, L→O, A→D, T→W, E→H."],
    ["एक कोड में ‘NOBLE’ को ‘QREOH’ लिखा जाता है, तो इसी कोड में ‘PLATE’ का कूट रूप होगा", ["SODWH", "SODVH", "SOCWH", "इनमें से कोई नहीं"], "हर अक्षर 3 स्थान आगे बढ़ता है: P→S, L→O, A→D, T→W, E→H।"]),
  q(2, "reasoning", "analogy", "E", 1,
    ["As ‘Bird’ is related to ‘wing’, in the same way, ‘Fish’ is related to", ["Gills", "Fins", "Tail", "Scale"], "A bird moves with wings and a fish moves with fins."],
    ["जैसे ‘पक्षी’ का संबंध ‘पंख’ से है, उसी प्रकार ‘मछली’ का संबंध किससे है?", ["गिल्स", "फिन्स (पंख)", "पूँछ", "शल्क"], "पक्षी पंखों से और मछली फिन्स (पंखों) से गति करती है।"]),
  q(2, "reasoning", "odd-one-out", "M", 3,
    ["Which one of the following does not belong to the group of others ?", ["Telephone", "Computer", "Radio", "X-Ray"], "Telephone, computer and radio are communication devices; X-ray is not."],
    ["निम्न में से कौन सा अन्यों के समूह से संबंधित नहीं है?", ["टेलीफोन", "कंप्यूटर", "रेडियो", "एक्स-रे"], "टेलीफोन, कंप्यूटर और रेडियो संचार के साधन हैं; एक्स-रे नहीं।"]),
  q(2, "reasoning", "math-operations", "E", 2,
    ["If Mosque is called Gurdwara, Gurdwara is called Temple, Temple is called Church, Church is called Fire temple then tell where do the Christians do their worship ?", ["Temple", "Church", "Fire-temple", "Mosque"], "Christians worship in a church, which is now called a fire temple."],
    ["यदि मस्जिद को गुरुद्वारा, गुरुद्वारा को मन्दिर, मन्दिर को चर्च, चर्च को अग्नि मन्दिर कहें तो ईसाई कहाँ पूजा करते हैं?", ["मन्दिर", "चर्च", "अग्नि मन्दिर", "मस्जिद"], "ईसाई चर्च में पूजा करते हैं, जिसे अब अग्नि मन्दिर कहा गया है।"]),
  q(3, "general-studies", "general-science", "E", 0,
    ["Who has been named India’s richest person in Forbes latest list ?", ["Mukesh Ambani", "Dilip Sanghvi", "Azim Premji", "None of these"], "Mukesh Ambani topped the Forbes list of India's richest."],
    ["फोर्ब्स की नवीनतम सूची में भारत का सबसे धनी व्यक्ति किसे बताया गया?", ["मुकेश अंबानी", "दिलीप सांघवी", "अज़ीम प्रेमजी", "इनमें से कोई नहीं"], "फोर्ब्स की सूची में मुकेश अंबानी भारत के सबसे धनी व्यक्ति रहे।"]),
  q(3, "general-studies", "general-science", "M", 1,
    ["Who is the author of the book ‘Citizen and Society’ ?", ["Pranab Mukherjee", "Hamid Ansari", "Manmohan Singh", "Sharad Pawar"], "'Citizen and Society' was written by Hamid Ansari, then Vice President."],
    ["‘सिटीज़न एंड सोसायटी’ पुस्तक के लेखक कौन हैं?", ["प्रणब मुखर्जी", "हामिद अंसारी", "मनमोहन सिंह", "शरद पवार"], "'सिटीज़न एंड सोसायटी' के लेखक तत्कालीन उपराष्ट्रपति हामिद अंसारी हैं।"]),
  q(3, "general-studies", "general-science", "E", 2,
    ["Who became India’s first woman to win a medal at the Paralympics ?", ["Sakshi Malik", "P.V. Sandhu", "Deepa Malik", "None of these"], "Deepa Malik won silver in shot put at Rio 2016."],
    ["पैरालंपिक में पदक जीतने वाली भारत की पहली महिला कौन बनीं?", ["साक्षी मलिक", "पी.वी. सिंधु", "दीपा मलिक", "इनमें से कोई नहीं"], "दीपा मलिक ने रियो 2016 में गोला फेंक में रजत जीता।"]),
  q(3, "general-studies", "general-science", "M", 2,
    ["Which one of the following became the 35th members of Missile Technology Control Regime (MTCR) ?", ["Israel", "Pakistan", "India", "Russia"], "India became the 35th member of the MTCR in 2016."],
    ["निम्न में से कौन मिसाइल प्रौद्योगिकी नियंत्रण व्यवस्था (MTCR) का 35वाँ सदस्य बना?", ["इज़राइल", "पाकिस्तान", "भारत", "रूस"], "भारत 2016 में MTCR का 35वाँ सदस्य बना।"]),
  q(3, "general-studies", "general-science", "H", 0,
    ["Which Indian-origin man has been honoured with Knighthood ?", ["Harpal Singh Kumar", "Rakesh Khurana", "Jamshed Bharucha", "None of these"], "Per the key, Harpal Singh Kumar was honoured with a knighthood."],
    ["किस भारतीय मूल के व्यक्ति को नाइटहुड से सम्मानित किया गया?", ["हरपाल सिंह कुमार", "राकेश खुराना", "जमशेद भरूचा", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार हरपाल सिंह कुमार को नाइटहुड मिला।"]),
  q(3, "general-studies", "general-science", "M", 1,
    ["Which country successfully test-fired Shaheen-1A missile ?", ["Iran", "Pakistan", "India", "None of these"], "Pakistan test-fired the Shaheen-1A missile."],
    ["किस देश ने शाहीन-1A मिसाइल का सफल परीक्षण किया?", ["ईरान", "पाकिस्तान", "भारत", "इनमें से कोई नहीं"], "पाकिस्तान ने शाहीन-1A मिसाइल का परीक्षण किया।"]),
  q(3, "general-studies", "general-science", "M", 3,
    ["Lobsang Sangey has been re-elected as the Prime Minister of", ["China", "South Korea", "Japan", "The Tibetan Government in Exile"], "Lobsang Sangay was re-elected Prime Minister (Sikyong) of the Tibetan Government in Exile."],
    ["लोबसांग सांगे पुनः किसके प्रधानमंत्री चुने गए?", ["चीन", "दक्षिण कोरिया", "जापान", "निर्वासित तिब्बती सरकार"], "लोबसांग सांगे निर्वासित तिब्बती सरकार के प्रधानमंत्री (सिक्योंग) पुनः चुने गए।"]),
  q(3, "general-studies", "general-science", "M", 3,
    ["Which country’s Parliament became first in the world to run fully on solar energy ?", ["Norway", "Finland", "India", "Pakistan"], "Pakistan's Parliament became the world's first to run fully on solar power (2017)."],
    ["किस देश की संसद विश्व की पहली संसद बनी जो पूर्णतः सौर ऊर्जा से चलती है?", ["नॉर्वे", "फिनलैंड", "भारत", "पाकिस्तान"], "पाकिस्तान की संसद विश्व की पहली पूर्णतः सौर ऊर्जा चालित संसद बनी।"]),
  q(3, "general-studies", "general-science", "M", 0,
    ["Who became the first English cricketer to score 10,000 Test runs ?", ["Alastair Cook", "Michael Atherton", "Andrew Strauss", "Michael Vaughan"], "Alastair Cook became the first English cricketer to reach 10,000 Test runs."],
    ["10,000 टेस्ट रन बनाने वाले पहले अंग्रेज़ क्रिकेटर कौन बने?", ["एलिस्टर कुक", "माइकल एथर्टन", "एंड्रयू स्ट्रॉस", "माइकल वॉन"], "एलिस्टर कुक 10,000 टेस्ट रन बनाने वाले पहले अंग्रेज़ क्रिकेटर बने।"]),
  q(3, "general-studies", "general-science", "M", 2,
    ["Who became the most successful female climber of Mount Everest ?", ["Apa Sherpa", "Phurba Tashi Sherpa", "Lhakpa Sherpa", "None of these"], "Lhakpa Sherpa climbed Everest the most times among women."],
    ["माउंट एवरेस्ट पर सबसे अधिक बार चढ़ने वाली सफल महिला पर्वतारोही कौन बनीं?", ["आपा शेरपा", "फुरबा ताशी शेरपा", "लाखपा शेरपा", "इनमें से कोई नहीं"], "लाखपा शेरपा एवरेस्ट पर सबसे अधिक बार चढ़ने वाली महिला हैं।"]),
  q(3, "general-studies", "general-science", "E", 0,
    ["The ‘Sunway Taihulight’ has been declared as the fastest _______ in the world.", ["Supercomputer", "Bullet Train", "Aeroplane", "None of these"], "Sunway TaihuLight was ranked the world's fastest supercomputer."],
    ["‘सनवे ताइहुलाइट’ को विश्व का सबसे तेज़ ________ घोषित किया गया है।", ["सुपरकंप्यूटर", "बुलेट ट्रेन", "हवाई जहाज़", "इनमें से कोई नहीं"], "सनवे ताइहुलाइट को विश्व का सबसे तेज़ सुपरकंप्यूटर घोषित किया गया।"]),
  q(3, "general-studies", "general-science", "E", 2,
    ["Euro Cup-2016 was won by", ["Spain", "Germany", "Portugal", "None of these"], "Portugal won Euro 2016."],
    ["यूरो कप-2016 किसने जीता?", ["स्पेन", "जर्मनी", "पुर्तगाल", "इनमें से कोई नहीं"], "पुर्तगाल ने यूरो कप 2016 जीता।"]),
  q(3, "general-studies", "general-science", "M", 3,
    ["World’s first quantum-enabled satellite ‘Micius’ was launched by", ["USA", "France", "Russia", "China"], "China launched the world's first quantum satellite, Micius, in 2016."],
    ["विश्व के प्रथम क्वांटम-सक्षम उपग्रह ‘मिशियस’ को किसने प्रक्षेपित किया?", ["यूएसए", "फ्रांस", "रूस", "चीन"], "चीन ने 2016 में विश्व का पहला क्वांटम उपग्रह मिशियस प्रक्षेपित किया।"]),
  q(3, "general-studies", "general-science", "M", 0,
    ["The first BRICS film festival was organised in", ["New Delhi", "Beijing", "Cape Town", "None of these"], "The first BRICS Film Festival was held in New Delhi in 2016."],
    ["प्रथम ब्रिक्स फिल्म महोत्सव का आयोजन कहाँ किया गया?", ["नई दिल्ली", "बीजिंग", "केपटाउन", "इनमें से कोई नहीं"], "प्रथम ब्रिक्स फिल्म महोत्सव 2016 में नई दिल्ली में हुआ।"]),
  q(3, "general-studies", "general-science", "M", 2,
    ["The world’s largest radio telescope ‘FAST’ was commissioned by", ["Russia", "India", "China", "USA"], "China commissioned the FAST radio telescope in Guizhou in 2016."],
    ["विश्व के सबसे बड़े रेडियो टेलीस्कोप ‘FAST’ को किसने चालू किया?", ["रूस", "भारत", "चीन", "यूएसए"], "चीन ने 2016 में गुइझोऊ में FAST रेडियो टेलीस्कोप चालू किया।"]),
  q(3, "general-studies", "general-science", "H", 2,
    ["The ambassador of ‘Make in India’ initiative is", ["Mukesh Ambani", "Kiran Mazumdar", "Piruz Khambatta", "None of these"], "Per the key, Piruz Khambatta was the ambassador of Make in India."],
    ["‘मेक इन इंडिया’ पहल का राजदूत (ब्रांड एम्बेसडर) कौन है?", ["मुकेश अंबानी", "किरण मजूमदार", "पीरुज खम्बाटा", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार पीरुज खम्बाटा 'मेक इन इंडिया' के राजदूत थे।"]),
  q(3, "general-studies", "general-science", "E", 2,
    ["India’s fastest train is", ["Shatabdi Express", "Rajdhani Express", "Gatimaan Express", "None of these"], "Gatimaan Express (160 km/h) was India's fastest train in 2016."],
    ["भारत की सबसे तेज़ रेलगाड़ी है", ["शताब्दी एक्सप्रेस", "राजधानी एक्सप्रेस", "गतिमान एक्सप्रेस", "इनमें से कोई नहीं"], "गतिमान एक्सप्रेस (160 किमी/घं) 2016 में भारत की सबसे तेज़ ट्रेन थी।"]),
  q(3, "general-studies", "general-science", "H", 1,
    ["The chairman of 21st Law Commission is", ["Justice Ravi R. Tripathi", "Justice Balbir Singh Chauhan", "Justice T.S. Thakur", "Justice J.S. Khehar"], "Justice Balbir Singh Chauhan chaired the 21st Law Commission."],
    ["21वें विधि आयोग के अध्यक्ष हैं", ["न्यायमूर्ति रवि आर. त्रिपाठी", "न्यायमूर्ति बलबीर सिंह चौहान", "न्यायमूर्ति टी.एस. ठाकुर", "न्यायमूर्ति जे.एस. खेहर"], "न्यायमूर्ति बलबीर सिंह चौहान 21वें विधि आयोग के अध्यक्ष थे।"]),
  q(3, "general-studies", "general-science", "M", 0,
    ["Who became India’s first woman member of the IOC ?", ["Nita Ambani", "Apurva Purohit", "Arundhati Bhattacharya", "Anita Kapur"], "Nita Ambani became India's first woman member of the IOC."],
    ["IOC की भारत की पहली महिला सदस्य कौन बनीं?", ["नीता अंबानी", "अपूर्वा पुरोहित", "अरुंधति भट्टाचार्य", "अनिता कपूर"], "नीता अंबानी IOC की भारत की पहली महिला सदस्य बनीं।"]),
  q(3, "general-studies", "general-science", "M", 1,
    ["Which state became the first state to ratify GST Bill ?", ["Himachal Pradesh", "Assam", "Kerala", "None of these"], "Assam was the first state to ratify the GST Bill."],
    ["जीएसटी विधेयक का अनुसमर्थन करने वाला पहला राज्य कौन बना?", ["हिमाचल प्रदेश", "असम", "केरल", "इनमें से कोई नहीं"], "असम जीएसटी विधेयक का अनुसमर्थन करने वाला पहला राज्य था।"]),
  q(3, "general-studies", "general-science", "H", 0,
    ["‘INS Tarmugli’ is the first", ["follow-on Water Jet Fast Attack Craft", "fastest submarine", "most efficient ‘SONAR’ system", "None of these"], "INS Tarmugli is the first follow-on Water Jet Fast Attack Craft of the Navy."],
    ["‘आईएनएस तारमुगली’ पहला है", ["फॉलो-ऑन वाटर जेट फास्ट अटैक क्राफ्ट", "सबसे तेज़ पनडुब्बी", "सबसे दक्ष ‘सोनार’ प्रणाली", "इनमें से कोई नहीं"], "आईएनएस तारमुगली नौसेना का पहला फॉलो-ऑन वाटर जेट फास्ट अटैक क्राफ्ट है।"]),
  q(4, "hp-gk", "polity-administration", "M", 2,
    ["‘Swachh Himachal – Padhai Bhi, Safai Bhi’ campaign was launched by", ["Municipal Corporation Shimla", "Municipal Corporation Dharamshala", "HPCA", "None of these"], "Per the key, HPCA launched the campaign."],
    ["‘स्वच्छ हिमाचल – पढ़ाई भी, सफाई भी’ अभियान किसने शुरू किया?", ["नगर निगम शिमला", "नगर निगम धर्मशाला", "HPCA", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार यह अभियान HPCA ने शुरू किया।"]),
  q(4, "hp-gk", "polity-administration", "M", 0,
    ["Which state of India became the first state to launch Rotavirus Vaccination Project ?", ["Himachal Pradesh", "Kerala", "Gujarat", "Goa"], "Himachal Pradesh was the first state to launch the rotavirus vaccination project."],
    ["रोटावायरस टीकाकरण परियोजना शुरू करने वाला भारत का पहला राज्य कौन सा बना?", ["हिमाचल प्रदेश", "केरल", "गुजरात", "गोवा"], "हिमाचल प्रदेश रोटावायरस टीकाकरण परियोजना शुरू करने वाला पहला राज्य था।"]),
  q(4, "hp-gk", "geography", "M", 0,
    ["The 2015 Paragliding World Cup was held in", ["India", "Japan", "Russia", "USA"], "The 2015 Paragliding World Cup was held at Bir-Billing in India."],
    ["2015 पैराग्लाइडिंग विश्व कप कहाँ आयोजित हुआ?", ["भारत", "जापान", "रूस", "यूएसए"], "2015 का पैराग्लाइडिंग विश्व कप भारत के बीर-बिलिंग में हुआ।"]),
  q(4, "hp-gk", "polity-administration", "M", 2,
    ["India’s first e-Vidhan Mobile App was launched by", ["Goa", "Kerala", "H.P.", "Maharashtra"], "Himachal Pradesh launched India's first e-Vidhan mobile app."],
    ["भारत का प्रथम ई-विधान मोबाइल ऐप किसने शुरू किया?", ["गोवा", "केरल", "हिमाचल प्रदेश", "महाराष्ट्र"], "हिमाचल प्रदेश ने भारत का पहला ई-विधान मोबाइल ऐप शुरू किया।"]),
  q(4, "hp-gk", "personalities", "H", 2,
    ["Which one of the following was associated with INA ?", ["Ram Lal", "Dr. Y.S. Parmar", "Bakshi Pratap Singh", "Dalip Singh"], "Per the key, Bakshi Pratap Singh was associated with the INA."],
    ["निम्न में से कौन INA से संबंधित था?", ["राम लाल", "डॉ. वाई.एस. परमार", "बख्शी प्रताप सिंह", "दलीप सिंह"], "आयोग की कुंजी के अनुसार बख्शी प्रताप सिंह INA से संबंधित थे।"]),
  q(4, "hp-gk", "personalities", "M", 1,
    ["Who was the first Health Minister in the Indian Cabinet ?", ["Vijay Lakshmi Pandit", "Rajkumari Amrit Kaur", "Sardar Vallabh Bhai Patel", "None of these"], "Rajkumari Amrit Kaur was independent India's first Health Minister."],
    ["भारतीय मंत्रिमंडल की प्रथम स्वास्थ्य मंत्री कौन थीं?", ["विजय लक्ष्मी पंडित", "राजकुमारी अमृत कौर", "सरदार वल्लभ भाई पटेल", "इनमें से कोई नहीं"], "राजकुमारी अमृत कौर स्वतंत्र भारत की प्रथम स्वास्थ्य मंत्री थीं।"]),
  q(4, "hp-gk", "geography", "M", 0,
    ["Ice-skating club is located in which district of Himachal Pradesh ?", ["Shimla", "Kullu", "Kangra", "Kinnaur"], "The Ice Skating Club is at Shimla."],
    ["आइस-स्केटिंग क्लब हिमाचल प्रदेश के किस जिले में स्थित है?", ["शिमला", "कुल्लू", "कांगड़ा", "किन्नौर"], "आइस-स्केटिंग क्लब शिमला में स्थित है।"]),
  q(4, "hp-gk", "geography", "E", 1,
    ["Indira Gandhi Medical College is located at", ["Kangra", "Shimla", "Hamirpur", "Mandi"], "Indira Gandhi Medical College is in Shimla."],
    ["इंदिरा गांधी मेडिकल कॉलेज स्थित है", ["कांगड़ा में", "शिमला में", "हमीरपुर में", "मंडी में"], "इंदिरा गांधी मेडिकल कॉलेज शिमला में है।"]),
  q(4, "hp-gk", "geography", "M", 3,
    ["Dr. Y.S. Parmar University of Horticulture and Forestry was established in the year . ..            ", ["1970", "1976", "1978", "1985"], "Dr. Y.S. Parmar University was established in 1985 at Nauni."],
    ["डॉ. वाई.एस. परमार बागवानी एवं वानिकी विश्वविद्यालय की स्थापना किस वर्ष हुई?", ["1970", "1976", "1978", "1985"], "डॉ. वाई.एस. परमार विश्वविद्यालय की स्थापना 1985 में नौणी में हुई।"]),
  q(4, "hp-gk", "geography", "E", 0,
    ["The most populous district of Himachal Pradesh is", ["Kangra", "Hamirpur", "Mandi", "Shimla"], "Kangra is the most populous district of Himachal Pradesh."],
    ["हिमाचल प्रदेश का सर्वाधिक जनसंख्या वाला जिला है", ["कांगड़ा", "हमीरपुर", "मंडी", "शिमला"], "कांगड़ा हिमाचल प्रदेश का सर्वाधिक जनसंख्या वाला जिला है।"]),
  q(4, "hp-gk", "geography", "M", 2,
    ["Scheduled Caste population of H.P. is approximately how many percent of the total population of the state ?", ["15", "20", "25", "18"], "Per the key, the Scheduled Caste share is about 25 per cent."],
    ["हिमाचल प्रदेश की अनुसूचित जाति की जनसंख्या राज्य की कुल जनसंख्या का लगभग कितने प्रतिशत है?", ["15", "20", "25", "18"], "आयोग की कुंजी के अनुसार अनुसूचित जाति की जनसंख्या लगभग 25 प्रतिशत है।"]),
  q(4, "hp-gk", "districts", "M", 2,
    ["Which of the following district was earliest to be formed ?", ["Solan", "Mandi", "Chamba", "Kinnaur"], "Chamba was one of the original districts formed in 1948."],
    ["निम्न में से कौन सा जिला सबसे पहले बना?", ["सोलन", "मंडी", "चम्बा", "किन्नौर"], "चम्बा 1948 में बने मूल जिलों में से एक था।"]),
  q(4, "hp-gk", "polity-administration", "M", 3,
    ["Who was the first Speaker of Legislative Assembly of Himachal Pradesh ?", ["M.H. Beg", "T.V.R. Tatachari", "M.S. Himmat Singh", "Pandit Jaiwant Ram"], "Pandit Jaiwant Ram was the first Speaker of the H.P. Legislative Assembly."],
    ["हिमाचल प्रदेश विधान सभा के प्रथम अध्यक्ष कौन थे?", ["एम.एच. बेग", "टी.वी.आर. टाटाचारी", "एम.एस. हिम्मत सिंह", "पंडित जयवंत राम"], "पंडित जयवंत राम हिमाचल प्रदेश विधान सभा के प्रथम अध्यक्ष थे।"]),
  q(4, "hp-gk", "culture-festivals", "M", 0,
    ["The popular Holi festival is incomparably celebrated in which place ?", ["Sujanpur", "Mandi", "Kullu", "Shimla"], "Sujanpur Tihra is famous for its Holi celebrations."],
    ["लोकप्रिय होली का त्यौहार किस स्थान पर अनुपम रूप से मनाया जाता है?", ["सुजानपुर", "मंडी", "कुल्लू", "शिमला"], "सुजानपुर टीहरा अपनी होली के लिए प्रसिद्ध है।"]),
  q(4, "hp-gk", "culture-festivals", "M", 2,
    ["The dance ‘Swang Tegi’ is performed during the festival of", ["Shivratri", "Navratra", "Diwali", "None of these"], "Per the key, the Swang Tegi dance is performed during Diwali."],
    ["‘स्वांग टेगी’ नृत्य किस त्यौहार के दौरान किया जाता है?", ["शिवरात्रि", "नवरात्र", "दीवाली", "इनमें से कोई नहीं"], "आयोग की कुंजी के अनुसार स्वांग टेगी नृत्य दीवाली के दौरान किया जाता है।"]),
  q(4, "hp-gk", "geography", "M", 2,
    ["Which among the following districts of Himachal Pradesh has least road network ?", ["Una", "Kangra", "Kinnaur", "Kullu"], "Kinnaur has the least road network among these districts."],
    ["हिमाचल प्रदेश के निम्न में से किस जिले में सड़क नेटवर्क सबसे कम है?", ["ऊना", "कांगड़ा", "किन्नौर", "कुल्लू"], "इन जिलों में किन्नौर का सड़क नेटवर्क सबसे कम है।"]),
  q(5, "english", "error-spotting", "M", 0,
    ["Choose the part of the sentence that has an error: She is more beautiful / but not so intelligent / as her sister.", ["She is more beautiful (A)", "but not so intelligent (B)", "as her sister. (C)", "No error (D)"], "'More beautiful ... as' is wrong; it should be 'as beautiful as'."],
    ["निम्नलिखित वाक्यांशों में से त्रुटि वाला भाग चुनिए: She is more beautiful (A) / but not so intelligent (B) / as her sister. (C) / No error (D)", ["She is more beautiful (A)", "but not so intelligent (B)", "as her sister. (C)", "No error (D)"], "'more beautiful ... as' गलत है; सही रूप 'as beautiful as' है।"]),
  q(5, "english", "error-spotting", "M", 0,
    ["Choose the part of the sentence that has an error: The patient will die / before / the doctor comes.", ["The patient will die (A)", "before (B)", "the doctor comes. (C)", "No error (D)"], "The future perfect 'will have died' is needed before the doctor comes."],
    ["निम्नलिखित वाक्यांशों में से त्रुटि वाला भाग चुनिए: The patient will die (A) / before (B) / the doctor comes. (C) / No error (D)", ["The patient will die (A)", "before (B)", "the doctor comes. (C)", "No error (D)"], "यहाँ future perfect 'will have died' चाहिए।"]),
  q(5, "english", "error-spotting", "M", 1,
    ["Choose the part of the sentence that has an error: I declared / that all will go wrong / without her.", ["I declared (A)", "that all will go wrong (B)", "without her. (C)", "No error (D)"], "After the past tense 'declared', the clause should say 'would go wrong'."],
    ["निम्नलिखित वाक्यांशों में से त्रुटि वाला भाग चुनिए: I declared (A) / that all will go wrong (B) / without her. (C) / No error (D)", ["I declared (A)", "that all will go wrong (B)", "without her. (C)", "No error (D)"], "भूतकाल 'declared' के बाद 'would go wrong' आना चाहिए।"]),
  q(5, "english", "error-spotting", "M", 2,
    ["Choose the part of the sentence that has an error: Work hard / lest / you may not fail.", ["Work hard (A)", "lest (B)", "you may not fail. (C)", "No error (D)"], "'Lest' already carries a negative sense, so it should be 'lest you should fail'."],
    ["निम्नलिखित वाक्यांशों में से त्रुटि वाला भाग चुनिए: Work hard (A) / lest (B) / you may not fail. (C) / No error (D)", ["Work hard (A)", "lest (B)", "you may not fail. (C)", "No error (D)"], "'Lest' में निषेध का भाव है, इसलिए 'lest you should fail' होना चाहिए।"]),
  q(5, "english", "error-spotting", "M", 1,
    ["Choose the part of the sentence that has an error: I will stand by you / in / thick and thin.", ["I will stand by you (A)", "in (B)", "thick and thin. (C)", "No error (D)"], "The idiom is 'through thick and thin', not 'in'."],
    ["निम्नलिखित वाक्यांशों में से त्रुटि वाला भाग चुनिए: I will stand by you (A) / in (B) / thick and thin. (C) / No error (D)", ["I will stand by you (A)", "in (B)", "thick and thin. (C)", "No error (D)"], "मुहावरा 'through thick and thin' है, 'in' नहीं।"]),
  q(5, "english", "error-spotting", "M", 0,
    ["Choose the part of the sentence that has an error: No country of the world / is as beautiful as / India.", ["No country of the world (A)", "is as beautiful as (B)", "India. (C)", "No error (D)"], "It should be 'No other country', since India is itself a country of the world."],
    ["निम्नलिखित वाक्यांशों में से त्रुटि वाला भाग चुनिए: No country of the world (A) / is as beautiful as (B) / India. (C) / No error (D)", ["No country of the world (A)", "is as beautiful as (B)", "India. (C)", "No error (D)"], "'No other country' होना चाहिए, क्योंकि भारत भी विश्व का एक देश है।"]),
  q(5, "english", "grammar", "M", 1,
    ["Fill in the blank with the appropriate preposition: She said that she was feeling sick ________ heart.", ["in", "at", "to", "of"], "The correct phrase is 'sick at heart'."],
    ["रिक्त स्थान की पूर्ति उचित पूर्वसर्ग से कीजिए: She said that she was feeling sick ________ heart.", ["in", "at", "to", "of"], "सही प्रयोग 'sick at heart' है।"]),
  q(5, "english", "grammar", "M", 3,
    ["Fill in the blank with the appropriate preposition: I can write a book ________ grammar.", ["about", "of", "in", "on"], "We write a book 'on' a subject."],
    ["रिक्त स्थान की पूर्ति उचित पूर्वसर्ग से कीजिए: I can write a book ________ grammar.", ["about", "of", "in", "on"], "किसी विषय पर पुस्तक 'on' से लिखी जाती है।"]),
  q(5, "english", "grammar", "M", 1,
    ["Fill in the blank with the appropriate preposition: We searched ________ happiness in vain.", ["after", "for", "in", "into"], "'Search after' happiness is the correct usage here, as per the key."],
    ["रिक्त स्थान की पूर्ति उचित पूर्वसर्ग से कीजिए: We searched ________ happiness in vain.", ["after", "for", "in", "into"], "आयोग की कुंजी के अनुसार यहाँ 'search after' सही प्रयोग है।"]),
  q(5, "english", "grammar", "M", 2,
    ["Fill in the blank with the appropriate preposition: You are advised to write ________ pencil.", ["by", "into", "with", "in"], "We write 'in' pencil or ink."],
    ["रिक्त स्थान की पूर्ति उचित पूर्वसर्ग से कीजिए: You are advised to write ________ pencil.", ["by", "into", "with", "in"], "पेंसिल या स्याही से लिखने के लिए 'in' प्रयोग होता है।"]),
  q(5, "english", "grammar", "M", 2,
    ["Fill in the blank with the appropriate preposition: Beware ________ back-biters.", ["from", "to", "of", "with"], "'Beware of' is the correct phrase."],
    ["रिक्त स्थान की पूर्ति उचित पूर्वसर्ग से कीजिए: Beware ________ back-biters.", ["from", "to", "of", "with"], "सही प्रयोग 'Beware of' है।"]),
  q(5, "english", "grammar", "M", 1,
    ["Fill in the blank with the appropriate preposition: Our clothes were soaked ________ water.", ["under", "in", "on", "with   ( . 191  195)        "], "'Soaked in water' is the correct usage."],
    ["रिक्त स्थान की पूर्ति उचित पूर्वसर्ग से कीजिए: Our clothes were soaked ________ water.", ["under", "in", "on", "with"], "सही प्रयोग 'soaked in water' है।"]),
  q(5, "hindi", "shuddh-vartani", "M", 0,
    ["शुद्ध वर्तनी चुनिए (प्रश्न 191 से 195)", ["अनुसरण", "अनुसर्ण", "अनुशरण", "अनुशर्ण"], "The correct spelling is 'अनुसरण'."],
    ["शुद्ध वर्तनी चुनिए (प्रश्न 191 से 195)", ["अनुसरण", "अनुसर्ण", "अनुशरण", "अनुशर्ण"], "सही वर्तनी 'अनुसरण' है।"]),
  q(5, "hindi", "shuddh-vartani", "M", 1,
    ["शुद्ध वर्तनी चुनिए (प्रश्न 192)", ["कुन्डली", "कुण्डली", "कुंडली", "कून्डली"], "Per the key, 'कुण्डली' is the correct spelling."],
    ["शुद्ध वर्तनी चुनिए (प्रश्न 192)", ["कुन्डली", "कुण्डली", "कुंडली", "कून्डली"], "आयोग की कुंजी के अनुसार शुद्ध वर्तनी 'कुण्डली' है।"]),
  q(5, "hindi", "shuddh-vartani", "M", 2,
    ["शुद्ध वर्तनी चुनिए (प्रश्न 193)", ["तृकोण", "तृकोन", "त्रिकोण", "त्रीकोण"], "The correct spelling is 'त्रिकोण'."],
    ["शुद्ध वर्तनी चुनिए (प्रश्न 193)", ["तृकोण", "तृकोन", "त्रिकोण", "त्रीकोण"], "सही वर्तनी 'त्रिकोण' है।"]),
  q(5, "hindi", "shuddh-vartani", "M", 0,
    ["शुद्ध वर्तनी चुनिए (प्रश्न 194)", ["आजीविका", "आजीवीका", "आजिवीका", "आजिविका"], "The correct spelling is 'आजीविका'."],
    ["शुद्ध वर्तनी चुनिए (प्रश्न 194)", ["आजीविका", "आजीवीका", "आजिवीका", "आजिविका"], "सही वर्तनी 'आजीविका' है।"]),
  q(5, "hindi", "shuddh-vartani", "M", 1,
    ["शुद्ध वर्तनी चुनिए (प्रश्न 195)", ["औजस्वी", "ओजस्वी", "औज्स्वी", "ओज्स्वी"], "The correct spelling is 'ओजस्वी'."],
    ["शुद्ध वर्तनी चुनिए (प्रश्न 195)", ["औजस्वी", "ओजस्वी", "औज्स्वी", "ओज्स्वी"], "सही वर्तनी 'ओजस्वी' है।"]),
  q(5, "hindi", "ek-shabd", "M", 0,
    ["‘जो धन का दुरुपयोग करता हो’ के लिए एक शब्द है", ["अपव्ययी", "मितव्ययी", "अतृप्त", "अधित्यका"], "'अपव्ययी' means one who wastes money."],
    ["‘जो धन का दुरुपयोग करता हो’ के लिए एक शब्द है", ["अपव्ययी", "मितव्ययी", "अतृप्त", "अधित्यका"], "'अपव्ययी' का अर्थ धन का दुरुपयोग करने वाला है।"]),
  q(5, "hindi", "sandhi-samas", "M", 0,
    ["‘नीरस’ में कौन सा समास है?", ["अव्ययीभाव", "तत्पुरुष", "द्वन्द्व", "बहुव्रीहि"], "Per the key, the answer is अव्ययीभाव (the key's classification of 'नीरस')."],
    ["‘नीरस’ में कौन सा समास है?", ["अव्ययीभाव", "तत्पुरुष", "द्वन्द्व", "बहुव्रीहि"], "आयोग की कुंजी के अनुसार उत्तर अव्ययीभाव है।"]),
  q(5, "hindi", "sandhi-samas", "M", 2,
    ["‘व्यापक’ का संधि-विच्छेद है", ["व्या + पक", "व्य + आपक", "वि + आपक", "वी + आपक"], "'व्यापक' splits as वि + आपक (yan sandhi)."],
    ["‘व्यापक’ का संधि-विच्छेद है", ["व्या + पक", "व्य + आपक", "वि + आपक", "वी + आपक"], "'व्यापक' का विच्छेद वि + आपक है (यण् संधि)।"]),
  q(5, "hindi", "muhavare", "M", 0,
    ["‘अंधा बनना’ मुहावरे का अर्थ है", ["जानबूझकर किसी बात पर ध्यान न देना", "मूर्ख बनाना", "वैमनस्य होना", "प्रयत्न न करना"], "'Andha banna' means to deliberately ignore something."],
    ["‘अंधा बनना’ मुहावरे का अर्थ है", ["जानबूझकर किसी बात पर ध्यान न देना", "मूर्ख बनाना", "वैमनस्य होना", "प्रयत्न न करना"], "'अंधा बनना' का अर्थ जानबूझकर किसी बात की अनदेखी करना है।"]),
  q(5, "hindi", "shuddh-vartani", "M", 3,
    ["‘वात्सल्य’ का पर्यायवाची नहीं है", ["प्रेम", "नेह", "स्नेह", "विग्रह"], "'विग्रह' means conflict or separation, not affection."],
    ["‘वात्सल्य’ का पर्यायवाची नहीं है", ["प्रेम", "नेह", "स्नेह", "विग्रह"], "'विग्रह' का अर्थ झगड़ा या अलगाव है, स्नेह नहीं।"]),
];
