// HP High Court Clerk — Full Mock 5, written fresh: General Knowledge & Himachal GK 30, English 20, Hindi 15,
// Reasoning 15, Mathematics 10, Computer 10.

import { q, type PatwariQuestion } from "../patwari/types";

export const clerkMock5: PatwariQuestion[] = [
  // ───────── Section 0: General Knowledge & Himachal GK (30) ─────────
  q(0, "hp-gk", "geography", "M", 1,
    ["The Kalatop–Khajjiar Wildlife Sanctuary, with dense deodar forest near Dalhousie, is in which district?", ["Kangra", "Chamba", "Kullu", "Mandi"], "Kalatop–Khajjiar sanctuary lies in Chamba district."],
    ["डलहौज़ी के पास घने देवदार वन वाला कालाटोप–खज्जियार वन्यजीव अभयारण्य किस ज़िले में है?", ["कांगड़ा", "चंबा", "कुल्लू", "मंडी"], "कालाटोप–खज्जियार अभयारण्य चंबा ज़िले में है।"]),
  q(0, "hp-gk", "districts", "M", 3,
    ["The HPCA cricket stadium, with the Dhauladhar range behind it, is located at:", ["Shimla", "Mandi", "Hamirpur", "Dharamshala"], "The Himachal Pradesh Cricket Association stadium is at Dharamshala in Kangra district."],
    ["धौलाधार पर्वतमाला की पृष्ठभूमि वाला HPCA क्रिकेट स्टेडियम कहाँ है?", ["शिमला", "मंडी", "हमीरपुर", "धर्मशाला"], "हिमाचल प्रदेश क्रिकेट एसोसिएशन स्टेडियम कांगड़ा ज़िले के धर्मशाला में है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["Pragpur, declared Himachal's first 'Heritage Village' in 1997, is in which district?", ["Kangra", "Hamirpur", "Una", "Bilaspur"], "Pragpur, with its cobbled lanes and old mansions, is in Kangra district."],
    ["1997 में हिमाचल का पहला 'धरोहर गाँव' घोषित प्रागपुर किस ज़िले में है?", ["कांगड़ा", "हमीरपुर", "ऊना", "बिलासपुर"], "पत्थर की गलियों और पुरानी हवेलियों वाला प्रागपुर कांगड़ा ज़िले में है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The Sui Mata fair, held in memory of a queen who gave her life to bring water to the town, takes place at:", ["Mandi", "Nahan", "Chamba", "Bilaspur"], "The Suhi (Sui) Mata mela is held every spring in Chamba town."],
    ["नगर में पानी लाने के लिए प्राण देने वाली रानी की स्मृति में सूई माता मेला कहाँ लगता है?", ["मंडी", "नाहन", "चंबा", "बिलासपुर"], "सूही (सूई) माता मेला हर वसंत में चंबा नगर में लगता है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["The Giri river of Shimla and Sirmaur districts is a tributary of the:", ["Sutlej", "Yamuna", "Beas", "Ravi"], "The Giri joins the Yamuna near Paonta Sahib."],
    ["शिमला और सिरमौर ज़िलों की गिरि नदी किसकी सहायक नदी है?", ["सतलुज", "यमुना", "ब्यास", "रावी"], "गिरि नदी पांवटा साहिब के पास यमुना में मिलती है।"]),
  q(0, "hp-gk", "economy", "H", 3,
    ["The Dehar power house of the Beas–Sutlej Link project is in which district?", ["Kullu", "Bilaspur", "Shimla", "Mandi"], "Beas water from Pandoh is taken through tunnels to the Dehar power house at Slapper in Mandi district, then into the Sutlej."],
    ["ब्यास–सतलुज लिंक परियोजना का डेहर पावर हाउस किस ज़िले में है?", ["कुल्लू", "बिलासपुर", "शिमला", "मंडी"], "पंडोह से ब्यास का पानी सुरंगों द्वारा मंडी ज़िले के सलापड़ स्थित डेहर पावर हाउस और फिर सतलुज में जाता है।"]),
  q(0, "hp-gk", "polity-administration", "H", 2,
    ["How many Lok Sabha constituencies does Himachal Pradesh have, of which Shimla is reserved for Scheduled Castes?", ["3", "5", "4", "6"], "The four seats are Shimla (SC), Mandi, Hamirpur and Kangra."],
    ["हिमाचल प्रदेश में कितने लोकसभा निर्वाचन क्षेत्र हैं, जिनमें शिमला अनुसूचित जाति के लिए आरक्षित है?", ["3", "5", "4", "6"], "चार सीटें हैं: शिमला (अ.जा.), मंडी, हमीरपुर और कांगड़ा।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["The present town of Mandi was founded in 1527 by:", ["Raja Sansar Chand", "Raja Ajbar Sen", "Raja Sahil Varman", "Raja Jagat Singh"], "Raja Ajbar Sen moved his capital to the left bank of the Beas and founded Mandi town in 1527."],
    ["वर्तमान मंडी नगर की स्थापना 1527 में किसने की?", ["राजा संसार चंद", "राजा अजबर सेन", "राजा साहिल वर्मन", "राजा जगत सिंह"], "राजा अजबर सेन ने 1527 में ब्यास के बाएँ किनारे पर राजधानी लाकर मंडी नगर बसाया।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["The Indian Institute of Management (IIM) of Himachal Pradesh is in which district?", ["Sirmaur", "Solan", "Kangra", "Shimla"], "IIM Sirmaur has its campus at Dhaulakuan near Paonta Sahib in Sirmaur district."],
    ["हिमाचल प्रदेश का भारतीय प्रबंध संस्थान (IIM) किस ज़िले में है?", ["सिरमौर", "सोलन", "कांगड़ा", "शिमला"], "IIM सिरमौर का परिसर सिरमौर ज़िले में पांवटा साहिब के पास धौलाकुआँ में है।"]),
  q(0, "hp-gk", "polity-administration", "M", 2,
    ["The Central University of Himachal Pradesh has its headquarters at:", ["Shimla", "Mandi", "Dharamshala", "Hamirpur"], "The Central University of HP, set up in 2009, is headquartered at Dharamshala in Kangra district."],
    ["हिमाचल प्रदेश केंद्रीय विश्वविद्यालय का मुख्यालय कहाँ है?", ["शिमला", "मंडी", "धर्मशाला", "हमीरपुर"], "2009 में बना हिमाचल प्रदेश केंद्रीय विश्वविद्यालय कांगड़ा ज़िले के धर्मशाला में है।"]),
  q(0, "general-studies", "indian-polity", "H", 3,
    ["Under which Article can the President seek the advisory opinion of the Supreme Court?", ["Article 72", "Article 123", "Article 136", "Article 143"], "Article 143 lets the President refer a question of law or fact to the Supreme Court for its opinion."],
    ["किस अनुच्छेद के तहत राष्ट्रपति सर्वोच्च न्यायालय से सलाहकारी राय माँग सकते हैं?", ["अनुच्छेद 72", "अनुच्छेद 123", "अनुच्छेद 136", "अनुच्छेद 143"], "अनुच्छेद 143 के तहत राष्ट्रपति विधि या तथ्य का प्रश्न सर्वोच्च न्यायालय की राय के लिए भेज सकते हैं।"]),
  q(0, "general-studies", "indian-polity", "H", 1,
    ["The Union Public Service Commission is set up under which Article of the Constitution?", ["Article 280", "Article 315", "Article 324", "Article 352"], "Article 315 provides public service commissions for the Union and the states."],
    ["संघ लोक सेवा आयोग संविधान के किस अनुच्छेद के तहत बना है?", ["अनुच्छेद 280", "अनुच्छेद 315", "अनुच्छेद 324", "अनुच्छेद 352"], "अनुच्छेद 315 संघ और राज्यों के लोक सेवा आयोगों का प्रावधान करता है।"]),
  q(0, "general-studies", "indian-polity", "H", 0,
    ["Which Constitutional Amendment lowered the voting age from 21 to 18 years?", ["61st Amendment", "42nd Amendment", "44th Amendment", "73rd Amendment"], "The 61st Amendment (1988) lowered the voting age to 18."],
    ["किस संविधान संशोधन ने मतदान की आयु 21 से घटाकर 18 वर्ष की?", ["61वाँ संशोधन", "42वाँ संशोधन", "44वाँ संशोधन", "73वाँ संशोधन"], "61वें संशोधन (1988) ने मतदान आयु 18 वर्ष की।"]),
  q(0, "general-studies", "indian-polity", "M", 2,
    ["Disputes about the election of the President of India are decided by the:", ["Election Commission", "Parliament", "Supreme Court", "Attorney General"], "Under Article 71, the Supreme Court decides disputes about the election of the President and Vice-President."],
    ["भारत के राष्ट्रपति के चुनाव से जुड़े विवादों का निर्णय कौन करता है?", ["निर्वाचन आयोग", "संसद", "सर्वोच्च न्यायालय", "महान्यायवादी"], "अनुच्छेद 71 के तहत राष्ट्रपति और उपराष्ट्रपति के चुनाव विवादों का निर्णय सर्वोच्च न्यायालय करता है।"]),
  q(0, "general-studies", "indian-polity", "M", 1,
    ["For how many days at most can the Rajya Sabha hold back a Money Bill?", ["7 days", "14 days", "30 days", "6 months"], "The Rajya Sabha must return a Money Bill within 14 days."],
    ["राज्यसभा किसी धन विधेयक को अधिकतम कितने दिन रोक सकती है?", ["7 दिन", "14 दिन", "30 दिन", "6 महीने"], "राज्यसभा को धन विधेयक 14 दिन के भीतर लौटाना होता है।"]),
  q(0, "general-studies", "indian-history", "M", 0,
    ["The Red Fort at Delhi was built by:", ["Shah Jahan", "Akbar", "Aurangzeb", "Humayun"], "Shah Jahan built the Red Fort as the palace of his new capital, Shahjahanabad."],
    ["दिल्ली का लाल किला किसने बनवाया?", ["शाहजहाँ", "अकबर", "औरंगज़ेब", "हुमायूँ"], "शाहजहाँ ने अपनी नई राजधानी शाहजहाँनाबाद के महल के रूप में लाल किला बनवाया।"]),
  q(0, "general-studies", "indian-history", "M", 3,
    ["Who introduced the Permanent Settlement with the zamindars of Bengal in 1793?", ["Lord Wellesley", "Lord Dalhousie", "Warren Hastings", "Lord Cornwallis"], "Lord Cornwallis introduced the Permanent Settlement with the zamindars in 1793."],
    ["1793 में बंगाल के ज़मींदारों के साथ स्थायी बंदोबस्त किसने लागू किया?", ["लॉर्ड वेलेज़ली", "लॉर्ड डलहौज़ी", "वॉरेन हेस्टिंग्स", "लॉर्ड कॉर्नवालिस"], "लॉर्ड कॉर्नवालिस ने 1793 में ज़मींदारों के साथ स्थायी बंदोबस्त लागू किया।"]),
  q(0, "general-studies", "indian-history", "M", 2,
    ["Which English weekly did Mahatma Gandhi publish from 1919 to spread his ideas?", ["Kesari", "The Hindu", "Young India", "Amrita Bazar Patrika"], "Gandhi edited 'Young India' from 1919; later he started 'Harijan'."],
    ["महात्मा गांधी ने अपने विचार फैलाने के लिए 1919 से कौन-सा अंग्रेज़ी साप्ताहिक प्रकाशित किया?", ["केसरी", "द हिंदू", "यंग इंडिया", "अमृत बाज़ार पत्रिका"], "गांधी ने 1919 से 'यंग इंडिया' का संपादन किया; बाद में 'हरिजन' शुरू किया।"]),
  q(0, "general-studies", "indian-history", "H", 1,
    ["The First Round Table Conference was held in London in:", ["1928", "1930", "1932", "1935"], "The First Round Table Conference met from November 1930; the Congress did not attend it."],
    ["पहला गोलमेज़ सम्मेलन लंदन में किस वर्ष हुआ?", ["1928", "1930", "1932", "1935"], "पहला गोलमेज़ सम्मेलन नवंबर 1930 में शुरू हुआ; कांग्रेस इसमें शामिल नहीं हुई।"]),
  q(0, "general-studies", "indian-history", "M", 3,
    ["Which Gupta ruler is called the 'Napoleon of India' for his many conquests?", ["Chandragupta I", "Skandagupta", "Kumaragupta", "Samudragupta"], "Historian V.A. Smith called Samudragupta the 'Napoleon of India'."],
    ["अपनी अनेक विजयों के कारण किस गुप्त शासक को 'भारत का नेपोलियन' कहा जाता है?", ["चंद्रगुप्त प्रथम", "स्कंदगुप्त", "कुमारगुप्त", "समुद्रगुप्त"], "इतिहासकार वी.ए. स्मिथ ने समुद्रगुप्त को 'भारत का नेपोलियन' कहा।"]),
  q(0, "general-studies", "indian-geography", "M", 0,
    ["The Tehri dam in Uttarakhand is built on which river?", ["Bhagirathi", "Alaknanda", "Yamuna", "Ramganga"], "Tehri dam stands on the Bhagirathi."],
    ["उत्तराखंड का टिहरी बाँध किस नदी पर बना है?", ["भागीरथी", "अलकनंदा", "यमुना", "रामगंगा"], "टिहरी बाँध भागीरथी नदी पर है।"]),
  q(0, "general-studies", "indian-geography", "H", 2,
    ["Sambhar, the largest inland salt lake of India, is in which state?", ["Gujarat", "Haryana", "Rajasthan", "Madhya Pradesh"], "Sambhar lake lies near Jaipur in Rajasthan."],
    ["भारत की सबसे बड़ी अंतर्देशीय खारे पानी की झील सांभर किस राज्य में है?", ["गुजरात", "हरियाणा", "राजस्थान", "मध्य प्रदेश"], "सांभर झील राजस्थान में जयपुर के पास है।"]),
  q(0, "general-studies", "indian-geography", "H", 1,
    ["The Indira Gandhi Canal, which carries water into the Thar desert, starts from:", ["The Yamuna at Hathnikund", "The Harike barrage on the Sutlej", "The Chambal at Kota", "The Narmada at Sardar Sarovar"], "It begins at the Harike barrage, where the Sutlej and the Beas meet in Punjab."],
    ["थार मरुस्थल तक पानी ले जाने वाली इंदिरा गांधी नहर कहाँ से शुरू होती है?", ["हथिनीकुंड पर यमुना", "सतलुज पर हरिके बैराज", "कोटा में चंबल", "सरदार सरोवर पर नर्मदा"], "यह पंजाब में सतलुज–ब्यास संगम पर स्थित हरिके बैराज से शुरू होती है।"]),
  q(0, "general-studies", "indian-geography", "M", 3,
    ["The boundary line drawn between India and Pakistan in 1947 is known as the:", ["McMahon Line", "Durand Line", "Line of Actual Control", "Radcliffe Line"], "Sir Cyril Radcliffe drew the 1947 boundary; the McMahon Line is with China and the Durand Line between Pakistan and Afghanistan."],
    ["1947 में भारत और पाकिस्तान के बीच खींची गई सीमा रेखा क्या कहलाती है?", ["मैकमोहन रेखा", "डूरंड रेखा", "वास्तविक नियंत्रण रेखा", "रेडक्लिफ़ रेखा"], "1947 की सीमा सर सिरिल रेडक्लिफ़ ने खींची; मैकमोहन रेखा चीन के साथ और डूरंड रेखा पाकिस्तान–अफ़ग़ानिस्तान के बीच है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["The ozone layer is being thinned mainly by:", ["Chlorofluorocarbons (CFCs)", "Carbon monoxide", "Nitrogen", "Water vapour"], "CFCs from old refrigerants and sprays release chlorine that breaks down ozone."],
    ["ओज़ोन परत मुख्य रूप से किसके कारण पतली हो रही है?", ["क्लोरोफ़्लोरोकार्बन (CFC)", "कार्बन मोनोऑक्साइड", "नाइट्रोजन", "जल वाष्प"], "पुराने रेफ़्रिजरेंट और स्प्रे के CFC क्लोरीन छोड़ते हैं जो ओज़ोन को तोड़ता है।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["The watt, seen on electric bulbs and heaters, is the SI unit of:", ["Energy", "Force", "Power", "Pressure"], "The watt is the unit of power (joule per second); energy is in joules."],
    ["बल्ब और हीटर पर लिखा वाट किसकी SI इकाई है?", ["ऊर्जा", "बल", "शक्ति", "दाब"], "वाट शक्ति (जूल प्रति सेकंड) की इकाई है; ऊर्जा जूल में मापी जाती है।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["Which of these diseases is caused by a virus: Malaria, Measles, Typhoid or Cholera?", ["Malaria", "Measles", "Typhoid", "Cholera"], "Measles is viral; malaria is caused by a protozoan, typhoid and cholera by bacteria."],
    ["इनमें से कौन-सा रोग विषाणु (वायरस) से होता है: मलेरिया, खसरा, टाइफ़ॉइड या हैज़ा?", ["मलेरिया", "खसरा", "टाइफ़ॉइड", "हैज़ा"], "खसरा विषाणु से होता है; मलेरिया प्रोटोज़ोआ से, टाइफ़ॉइड और हैज़ा जीवाणु से।"]),
  q(0, "general-studies", "general-science", "M", 3,
    ["Which blood vessels carry blood away from the heart to the body?", ["Veins", "Capillaries", "Lymph vessels", "Arteries"], "Arteries carry blood away from the heart; veins bring it back."],
    ["कौन-सी रक्त वाहिकाएँ रक्त को हृदय से शरीर की ओर ले जाती हैं?", ["शिराएँ", "केशिकाएँ", "लसीका वाहिकाएँ", "धमनियाँ"], "धमनियाँ रक्त को हृदय से दूर ले जाती हैं; शिराएँ वापस लाती हैं।"]),
  q(0, "general-studies", "indian-economy", "M", 0,
    ["In online banking, NEFT stands for:", ["National Electronic Funds Transfer", "Net Electronic Fund Transaction", "National Easy Funds Transfer", "New Electronic Finance Tool"], "NEFT is the RBI's National Electronic Funds Transfer system."],
    ["ऑनलाइन बैंकिंग में NEFT का पूरा रूप है:", ["National Electronic Funds Transfer", "Net Electronic Fund Transaction", "National Easy Funds Transfer", "New Electronic Finance Tool"], "NEFT भारतीय रिज़र्व बैंक की National Electronic Funds Transfer प्रणाली है।"]),
  q(0, "general-studies", "indian-economy", "M", 2,
    ["Which of these is a direct tax: GST, Customs duty, Income tax or Excise duty?", ["GST", "Customs duty", "Income tax", "Excise duty"], "Income tax is paid directly by the person who bears it; the others are indirect taxes."],
    ["इनमें से कौन प्रत्यक्ष कर है: GST, सीमा शुल्क, आयकर या उत्पाद शुल्क?", ["GST", "सीमा शुल्क", "आयकर", "उत्पाद शुल्क"], "आयकर वही व्यक्ति सीधे चुकाता है जिस पर उसका भार है; बाकी अप्रत्यक्ष कर हैं।"]),

  // ───────── Section 1: English (20) ─────────
  q(1, "english", "grammar", "M", 0,
    ["Fill in the blank: 'The certified copy was handed ___ to the applicant at the counter.'", ["over", "off", "up", "out of"], "'Hand over' means to give something to someone formally."],
    ["रिक्त स्थान भरिए: 'The certified copy was handed ___ to the applicant at the counter.'", ["over", "off", "up", "out of"], "'Hand over' का अर्थ औपचारिक रूप से सौंपना है।"]),
  q(1, "english", "grammar", "H", 2,
    ["Choose the correct verb: 'The Superintendent, together with two clerks, ___ checking the old records.'", ["are", "were", "is", "have been"], "A phrase with 'together with' does not change the subject, so the verb agrees with 'the Superintendent'."],
    ["सही क्रिया चुनिए: 'The Superintendent, together with two clerks, ___ checking the old records.'", ["are", "were", "is", "have been"], "'Together with' वाला वाक्यांश कर्ता नहीं बदलता, अतः क्रिया 'the Superintendent' के अनुसार होगी।"]),
  q(1, "english", "grammar", "M", 3,
    ["Choose the correct tense: 'Every morning the copying clerk ___ the cause list on the notice board.'", ["pinned", "is pinning", "has pinned", "pins"], "A daily habit takes the simple present."],
    ["सही काल चुनिए: 'Every morning the copying clerk ___ the cause list on the notice board.'", ["pinned", "is pinning", "has pinned", "pins"], "रोज़ की आदत के लिए simple present आता है।"]),
  q(1, "english", "grammar", "H", 1,
    ["Choose the correct form: 'It is high time the pending files ___ disposed of.'", ["are", "were", "will be", "have been"], "'It is high time' is followed by the past subjunctive: 'were disposed of'."],
    ["सही रूप चुनिए: 'It is high time the pending files ___ disposed of.'", ["are", "were", "will be", "have been"], "'It is high time' के बाद past subjunctive आता है: 'were disposed of'।"]),
  q(1, "english", "grammar", "M", 0,
    ["Fill in the blanks: 'The clerk apologised ___ the Registrar ___ the delay.'", ["to; for", "for; to", "with; for", "to; on"], "One apologises to a person for a fault."],
    ["रिक्त स्थान भरिए: 'The clerk apologised ___ the Registrar ___ the delay.'", ["to; for", "for; to", "with; for", "to; on"], "किसी व्यक्ति से 'apologise to' और ग़लती के लिए 'for' आता है।"]),
  q(1, "english", "error-spotting", "H", 1,
    ["Find the part with an error in: 'The copying clerk (A) / did not knew (B) / the correct fee (C) / for the certified copy. (D)'", ["The copying clerk", "did not knew", "the correct fee", "for the certified copy"], "After 'did', the base form is used: 'did not know'."],
    ["इस वाक्य में त्रुटि वाला भाग चुनिए: 'The copying clerk (A) / did not knew (B) / the correct fee (C) / for the certified copy. (D)'", ["The copying clerk", "did not knew", "the correct fee", "for the certified copy"], "'Did' के बाद क्रिया का मूल रूप आता है: 'did not know'।"]),
  q(1, "english", "error-spotting", "H", 1,
    ["Find the part with an error in: 'Ten kilometres (A) / are a long distance (B) / to walk (C) / to the court every day. (D)'", ["Ten kilometres", "are a long distance", "to walk", "to the court every day"], "A plural amount taken as one quantity takes a singular verb: 'is a long distance'."],
    ["इस वाक्य में त्रुटि वाला भाग चुनिए: 'Ten kilometres (A) / are a long distance (B) / to walk (C) / to the court every day. (D)'", ["Ten kilometres", "are a long distance", "to walk", "to the court every day"], "एक मात्रा के रूप में ली गई बहुवचन राशि के साथ एकवचन क्रिया आती है: 'is a long distance'।"]),
  q(1, "english", "synonyms-antonyms", "M", 2,
    ["Choose the word closest in meaning to 'AUTHENTIC' as in 'an authentic copy of the decree':", ["Forged", "Recent", "Genuine", "Typed"], "Authentic means real and reliable."],
    ["'an authentic copy of the decree' में 'AUTHENTIC' के सबसे निकट अर्थ वाला शब्द चुनिए:", ["Forged", "Recent", "Genuine", "Typed"], "Authentic का अर्थ असली और प्रामाणिक है।"]),
  q(1, "english", "synonyms-antonyms", "H", 3,
    ["Choose the word closest in meaning to 'TEDIOUS' as in 'the tedious work of indexing old files':", ["Exciting", "Simple", "Urgent", "Wearisome"], "Tedious means long, dull and tiring."],
    ["'the tedious work of indexing old files' में 'TEDIOUS' के सबसे निकट अर्थ वाला शब्द चुनिए:", ["Exciting", "Simple", "Urgent", "Wearisome"], "Tedious का अर्थ लंबा, नीरस और थकाऊ है।"]),
  q(1, "english", "synonyms-antonyms", "M", 0,
    ["Choose the word opposite in meaning to 'COMPULSORY' as in 'compulsory attendance at the training':", ["Optional", "Necessary", "Required", "Strict"], "Compulsory means required; optional means left to choice."],
    ["'compulsory attendance at the training' में 'COMPULSORY' के विपरीत अर्थ वाला शब्द चुनिए:", ["Optional", "Necessary", "Required", "Strict"], "Compulsory का अर्थ अनिवार्य; optional का अर्थ वैकल्पिक।"]),
  q(1, "english", "synonyms-antonyms", "H", 2,
    ["Choose the word opposite in meaning to 'FRUGAL' as in 'a frugal office budget':", ["Thrifty", "Careful", "Extravagant", "Modest"], "Frugal means sparing with money; extravagant means wasteful."],
    ["'a frugal office budget' में 'FRUGAL' के विपरीत अर्थ वाला शब्द चुनिए:", ["Thrifty", "Careful", "Extravagant", "Modest"], "Frugal का अर्थ मितव्ययी; extravagant का अर्थ फ़िज़ूलख़र्च।"]),
  q(1, "english", "one-word", "M", 1,
    ["One word for 'the person who files a suit in a civil court':", ["Defendant", "Plaintiff", "Respondent", "Accused"], "The plaintiff brings a civil suit; the defendant answers it."],
    ["'दीवानी अदालत में वाद दायर करने वाला व्यक्ति' के लिए एक शब्द:", ["Defendant", "Plaintiff", "Respondent", "Accused"], "Plaintiff वाद दायर करता है; defendant उसका उत्तर देता है।"]),
  q(1, "english", "one-word", "M", 3,
    ["One word for 'an official count of a country's population':", ["Survey", "Ballot", "Register", "Census"], "A census is an official count of the population."],
    ["'किसी देश की जनसंख्या की आधिकारिक गणना' के लिए एक शब्द:", ["Survey", "Ballot", "Register", "Census"], "Census जनसंख्या की आधिकारिक गणना है।"]),
  q(1, "english", "one-word", "H", 0,
    ["One word for 'that which cannot be avoided':", ["Inevitable", "Invincible", "Indelible", "Inaudible"], "Inevitable means certain to happen; invincible means unbeatable, indelible cannot be erased."],
    ["'जिसे टाला न जा सके' के लिए एक शब्द:", ["Inevitable", "Invincible", "Indelible", "Inaudible"], "Inevitable का अर्थ अवश्यंभावी; invincible अजेय और indelible अमिट।"]),
  q(1, "english", "idioms", "M", 2,
    ["'The clerk let the cat out of the bag about the transfers.' The idiom means he:", ["Released an animal", "Delayed the transfers", "Revealed a secret", "Lost the transfer file"], "To let the cat out of the bag is to reveal a secret by mistake."],
    ["'The clerk let the cat out of the bag about the transfers.' मुहावरे का अर्थ है कि उसने:", ["Released an animal", "Delayed the transfers", "Revealed a secret", "Lost the transfer file"], "Let the cat out of the bag का अर्थ भूल से कोई रहस्य खोल देना है।"]),
  q(1, "english", "idioms", "H", 1,
    ["'The new e-filing rule is a double-edged sword.' The idiom means the rule:", ["Is very dangerous", "Has both good and bad effects", "Will be withdrawn soon", "Is clearly beneficial"], "A double-edged sword has advantages as well as disadvantages."],
    ["'The new e-filing rule is a double-edged sword.' मुहावरे का अर्थ है कि नियम:", ["Is very dangerous", "Has both good and bad effects", "Will be withdrawn soon", "Is clearly beneficial"], "Double-edged sword का अर्थ है जिसके लाभ और हानि दोनों हों।"]),
  q(1, "english", "voice-speech", "H", 3,
    ["Choose the passive form of: 'Did the peon deliver the dak to the Registrar?'", ["Was the dak deliver to the Registrar by the peon?", "Did the dak delivered to the Registrar by the peon?", "Has the dak been delivered to the Registrar by the peon?", "Was the dak delivered to the Registrar by the peon?"], "A past simple question becomes 'Was/Were + subject + past participle?' in the passive."],
    ["कर्मवाच्य रूप चुनिए: 'Did the peon deliver the dak to the Registrar?'", ["Was the dak deliver to the Registrar by the peon?", "Did the dak delivered to the Registrar by the peon?", "Has the dak been delivered to the Registrar by the peon?", "Was the dak delivered to the Registrar by the peon?"], "Past simple प्रश्न का कर्मवाच्य 'Was/Were + कर्ता + past participle?' होता है।"]),
  q(1, "english", "voice-speech", "H", 0,
    ["Change into indirect speech: The judge said, 'The court will rise at four.'", ["The judge said that the court would rise at four.", "The judge said that the court will rise at four.", "The judge told that the court would rise at four.", "The judge said that the court would have risen at four."], "With a past reporting verb, 'will' changes to 'would'; 'said' needs no object."],
    ["अप्रत्यक्ष कथन में बदलिए: The judge said, 'The court will rise at four.'", ["The judge said that the court would rise at four.", "The judge said that the court will rise at four.", "The judge told that the court would rise at four.", "The judge said that the court would have risen at four."], "भूतकालिक reporting verb के साथ 'will' का 'would' होता है; 'said' के बाद कर्म नहीं चाहिए।"]),
  q(1, "english", "spelling", "H", 2,
    ["Choose the correct spelling of the word meaning 'the work of keeping a building or machine in good condition':", ["Maintainance", "Maintenence", "Maintenance", "Mantainance"], "The correct spelling is 'maintenance', though the verb is 'maintain'."],
    ["'किसी भवन या मशीन को अच्छी हालत में रखने का कार्य' अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Maintainance", "Maintenence", "Maintenance", "Mantainance"], "क्रिया 'maintain' होने पर भी सही वर्तनी 'maintenance' है।"]),
  q(1, "english", "vocabulary", "M", 1,
    ["Choose the word that best fits: 'The Registrar ___ the leave application because the branch was short of staff.'", ["granted", "rejected", "welcomed", "praised"], "A shortage of staff is a reason to refuse leave."],
    ["उपयुक्त शब्द चुनिए: 'The Registrar ___ the leave application because the branch was short of staff.'", ["granted", "rejected", "welcomed", "praised"], "कर्मचारियों की कमी छुट्टी अस्वीकार करने का कारण है।"]),

  // ───────── Section 2: Hindi (15) ─────────
  q(2, "hindi", "sandhi-samas", "M", 1,
    ["Pick the correct sandhi split of the Hindi word 'रमेश':", ["रम + एश", "रमा + ईश", "र + मेश", "रमे + श"], "आ + ई = ए: रमा + ईश = रमेश (gun sandhi)."],
    ["'रमेश' का सही संधि-विच्छेद चुनिए:", ["रम + एश", "रमा + ईश", "र + मेश", "रमे + श"], "आ + ई = ए: रमा + ईश = रमेश (गुण संधि)।"]),
  q(2, "hindi", "sandhi-samas", "M", 3,
    ["Pick the correct sandhi split of the Hindi word 'प्रत्येक':", ["प्रत + एक", "प्रत्य + एक", "प्र + त्येक", "प्रति + एक"], "इ + ए = ये: प्रति + एक = प्रत्येक (yan sandhi)."],
    ["'प्रत्येक' का सही संधि-विच्छेद चुनिए:", ["प्रत + एक", "प्रत्य + एक", "प्र + त्येक", "प्रति + एक"], "इ + ए = ये: प्रति + एक = प्रत्येक (यण संधि)।"]),
  q(2, "hindi", "sandhi-samas", "H", 0,
    ["Pick the correct sandhi split of the Hindi word 'मनोबल':", ["मनः + बल", "मनो + बल", "मन + ओबल", "मन + बल"], "मनः + बल: the visarg becomes ओ before ब — visarg sandhi."],
    ["'मनोबल' का सही संधि-विच्छेद चुनिए:", ["मनः + बल", "मनो + बल", "मन + ओबल", "मन + बल"], "मनः + बल: ब से पहले विसर्ग का ओ — विसर्ग संधि।"]),
  q(2, "hindi", "sandhi-samas", "M", 2,
    ["Which samas is in the Hindi word 'रसोईघर'?", ["Dvandva", "Bahuvrihi", "Tatpurush", "Dvigu"], "रसोई के लिए घर — the case ending 'के लिए' is dropped, so tatpurush."],
    ["'रसोईघर' में कौन-सा समास है?", ["द्वंद्व", "बहुव्रीहि", "तत्पुरुष", "द्विगु"], "रसोई के लिए घर — 'के लिए' विभक्ति का लोप, अतः तत्पुरुष।"]),
  q(2, "hindi", "sandhi-samas", "H", 1,
    ["Which samas is in the Hindi word 'चंद्रमुख'?", ["Dvigu", "Karmadharaya", "Dvandva", "Avyayibhav"], "चंद्र के समान मुख — a comparison (upman–upmey), so karmadharaya."],
    ["'चंद्रमुख' में कौन-सा समास है?", ["द्विगु", "कर्मधारय", "द्वंद्व", "अव्ययीभाव"], "चंद्र के समान मुख — उपमान–उपमेय संबंध, अतः कर्मधारय।"]),
  q(2, "hindi", "paryay-vilom", "M", 0,
    ["Pick a synonym of the Hindi word 'वृक्ष':", ["तरु", "सरिता", "अनल", "पंकज"], "तरु, विटप and पादप mean tree; सरिता is river, अनल fire, पंकज lotus."],
    ["'वृक्ष' का पर्यायवाची शब्द चुनिए:", ["तरु", "सरिता", "अनल", "पंकज"], "तरु, विटप और पादप वृक्ष के पर्याय हैं; सरिता नदी, अनल आग और पंकज कमल है।"]),
  q(2, "hindi", "paryay-vilom", "H", 3,
    ["Pick a synonym of the Hindi word 'नदी':", ["तड़ित", "तरणि", "तुरंग", "तटिनी"], "तटिनी, सरिता and तरंगिणी mean river; तड़ित is lightning, तरणि sun, तुरंग horse."],
    ["'नदी' का पर्यायवाची शब्द चुनिए:", ["तड़ित", "तरणि", "तुरंग", "तटिनी"], "तटिनी, सरिता और तरंगिणी नदी के पर्याय हैं; तड़ित बिजली, तरणि सूर्य और तुरंग घोड़ा है।"]),
  q(2, "hindi", "paryay-vilom", "M", 2,
    ["Pick the opposite (vilom) of the Hindi word 'स्वदेश':", ["स्वराज", "देशी", "विदेश", "प्रदेश"], "स्वदेश (one's own country) is opposite to विदेश (a foreign country)."],
    ["'स्वदेश' का विलोम शब्द चुनिए:", ["स्वराज", "देशी", "विदेश", "प्रदेश"], "स्वदेश का विलोम विदेश है।"]),
  q(2, "hindi", "paryay-vilom", "H", 1,
    ["Pick the opposite (vilom) of the Hindi word 'आलस्य':", ["सुस्ती", "स्फूर्ति", "निद्रा", "थकान"], "आलस्य (laziness) is opposite to स्फूर्ति (briskness)."],
    ["'आलस्य' का विलोम शब्द चुनिए:", ["सुस्ती", "स्फूर्ति", "निद्रा", "थकान"], "आलस्य का विलोम स्फूर्ति है।"]),
  q(2, "hindi", "muhavare", "M", 3,
    ["What does the Hindi muhavara 'हाथ मलना' mean?", ["हाथ धोना", "मेहनत करना", "स्वागत करना", "पछताना"], "It means to regret something that cannot be undone."],
    ["मुहावरे 'हाथ मलना' का अर्थ है:", ["हाथ धोना", "मेहनत करना", "स्वागत करना", "पछताना"], "इसका अर्थ पछताना है।"]),
  q(2, "hindi", "muhavare", "H", 0,
    ["What does the Hindi muhavara 'अपने मुँह मियाँ मिट्ठू बनना' mean?", ["अपनी प्रशंसा स्वयं करना", "मीठा बोलना", "तोते पालना", "दूसरों की निंदा करना"], "It means to praise oneself."],
    ["मुहावरे 'अपने मुँह मियाँ मिट्ठू बनना' का अर्थ है:", ["अपनी प्रशंसा स्वयं करना", "मीठा बोलना", "तोते पालना", "दूसरों की निंदा करना"], "इसका अर्थ अपनी प्रशंसा स्वयं करना है।"]),
  q(2, "hindi", "ek-shabd", "M", 2,
    ["Give one Hindi word for 'जो पहले किसी पद पर था पर अब नहीं है':", ["भविष्य", "वर्तमान", "भूतपूर्व", "अभूतपूर्व"], "भूतपूर्व means former; अभूतपूर्व means unprecedented."],
    ["'जो पहले किसी पद पर था पर अब नहीं है' के लिए एक शब्द:", ["भविष्य", "वर्तमान", "भूतपूर्व", "अभूतपूर्व"], "भूतपूर्व का अर्थ पहले का; अभूतपूर्व का अर्थ जो पहले कभी न हुआ हो।"]),
  q(2, "hindi", "ek-shabd", "H", 1,
    ["Give one Hindi word for 'जिसे क्षमा न किया जा सके':", ["क्षम्य", "अक्षम्य", "अक्षम", "क्षमाशील"], "अक्षम्य means unforgivable; अक्षम means incapable."],
    ["'जिसे क्षमा न किया जा सके' के लिए एक शब्द:", ["क्षम्य", "अक्षम्य", "अक्षम", "क्षमाशील"], "अक्षम्य का अर्थ जिसे क्षमा न किया जा सके; अक्षम का अर्थ असमर्थ।"]),
  q(2, "hindi", "shuddh-vartani", "H", 1,
    ["Which spelling of the Hindi word for 'authentic, reliable' is correct?", ["प्रमाणिक", "प्रामाणिक", "प्रामणिक", "परामाणिक"], "प्रमाण + इक gives प्रामाणिक; the इक suffix lengthens the first vowel."],
    ["'विश्वसनीय, प्रमाण से सिद्ध' अर्थ वाले शब्द की शुद्ध वर्तनी कौन-सी है?", ["प्रमाणिक", "प्रामाणिक", "प्रामणिक", "परामाणिक"], "प्रमाण + इक से प्रामाणिक बनता है; इक प्रत्यय से पहला स्वर दीर्घ होता है।"]),
  q(2, "hindi", "alankar-ras", "M", 0,
    ["Which alankar is in the Hindi line 'तरनि तनूजा तट तमाल तरुवर बहु छाए'?", ["Anupras", "Upma", "Rupak", "Yamak"], "The sound 'त' is repeated again and again, so it is anupras."],
    ["'तरनि तनूजा तट तमाल तरुवर बहु छाए' में कौन-सा अलंकार है?", ["अनुप्रास", "उपमा", "रूपक", "यमक"], "'त' वर्ण की बार-बार आवृत्ति है, अतः अनुप्रास अलंकार।"]),

  // ───────── Section 3: Reasoning (15) ─────────
  q(3, "reasoning", "series", "H", 2,
    ["Find the next number: 2, 2, 4, 12, 48, ?", ["192", "96", "240", "288"], "The multipliers are 1, 2, 3, 4, so next is × 5: 48 × 5 = 240."],
    ["अगली संख्या ज्ञात कीजिए: 2, 2, 4, 12, 48, ?", ["192", "96", "240", "288"], "गुणक 1, 2, 3, 4 हैं, अगला × 5: 48 × 5 = 240।"], "48*5"),
  q(3, "reasoning", "series", "M", 1,
    ["Find the missing number in the series 4, 12, 36, ?, 324", ["72", "108", "144", "216"], "Each term is three times the previous one: 36 × 3 = 108, and 108 × 3 = 324."],
    ["श्रेणी 4, 12, 36, ?, 324 में लुप्त संख्या ज्ञात कीजिए।", ["72", "108", "144", "216"], "हर पद पिछले का तीन गुना है: 36 × 3 = 108, और 108 × 3 = 324।"], "36*3"),
  q(3, "reasoning", "alphabet-test", "M", 3,
    ["How many letters lie between H and S in the English alphabet?", ["11", "12", "9", "10"], "H is 8th and S is 19th, so 19 − 8 − 1 = 10 letters lie between them."],
    ["अंग्रेज़ी वर्णमाला में H और S के बीच कितने अक्षर हैं?", ["11", "12", "9", "10"], "H 8वाँ और S 19वाँ है, अतः बीच में 19 − 8 − 1 = 10 अक्षर हैं।"], "19-8-1"),
  q(3, "reasoning", "coding-decoding", "M", 0,
    ["If BAIL is written as AZHK, how is WRIT written in that code?", ["VQHS", "XSJU", "VQIS", "UPGR"], "Each letter moves one place back: W→V, R→Q, I→H, T→S."],
    ["यदि BAIL को AZHK लिखा जाता है, तो उसी कूट में WRIT कैसे लिखा जाएगा?", ["VQHS", "XSJU", "VQIS", "UPGR"], "हर अक्षर एक स्थान पीछे जाता है: W→V, R→Q, I→H, T→S।"]),
  q(3, "reasoning", "coding-decoding", "H", 1,
    ["In a code, 'file sign date' is 'ka pa ta', 'sign the order' is 'pa ro mi' and 'date the file' is 'ta ka ro'. What is the code for 'sign'?", ["ka", "pa", "ta", "ro"], "'Sign' is common to the first two sentences, and so is only 'pa'."],
    ["एक कूट में 'file sign date' को 'ka pa ta', 'sign the order' को 'pa ro mi' और 'date the file' को 'ta ka ro' लिखा जाता है। 'sign' का कूट क्या है?", ["ka", "pa", "ta", "ro"], "पहले दो वाक्यों में 'sign' और कूट में केवल 'pa' समान है।"]),
  q(3, "reasoning", "blood-relations", "M", 2,
    ["How is Ravi related to the son of his father's sister?", ["Brother", "Nephew", "Cousin", "Uncle"], "The son of one's father's sister (bua) is one's cousin, and so Ravi is his cousin too."],
    ["रवि अपने पिता की बहन के बेटे का क्या लगता है?", ["भाई (सगा)", "भतीजा", "ममेरा/फुफेरा भाई (कज़िन)", "चाचा"], "बुआ का बेटा फुफेरा भाई होता है, अतः रवि भी उसका फुफेरा भाई (कज़िन) है।"]),
  q(3, "reasoning", "blood-relations", "H", 0,
    ["If 'P × Q' means P is the father of Q and 'P + Q' means P is the sister of Q, what does 'A + B × C' mean?", ["A is C's aunt (father's sister)", "A is C's mother", "A is C's sister", "A is C's grandmother"], "A is B's sister and B is C's father, so A is C's father's sister."],
    ["यदि 'P × Q' का अर्थ P, Q का पिता है और 'P + Q' का अर्थ P, Q की बहन है, तो 'A + B × C' का क्या अर्थ है?", ["A, C की बुआ है", "A, C की माँ है", "A, C की बहन है", "A, C की दादी है"], "A, B की बहन है और B, C का पिता है, अतः A, C की बुआ है।"]),
  q(3, "reasoning", "direction-sense", "M", 3,
    ["From the court gate, a peon walks 15 m east and then 8 m north. How far is he from the gate?", ["23 m", "7 m", "19 m", "17 m"], "√(15² + 8²) = √289 = 17 m."],
    ["कोर्ट के गेट से एक चपरासी 15 मी पूर्व और फिर 8 मी उत्तर चलता है। वह गेट से कितनी दूर है?", ["23 मी", "7 मी", "19 मी", "17 मी"], "√(15² + 8²) = √289 = 17 मी।"], "Math.sqrt(225+64)"),
  q(3, "reasoning", "direction-sense", "H", 1,
    ["Sunita faces north-east. She turns 90° anticlockwise and then 180° clockwise. Which direction is she facing now?", ["North-west", "South-east", "South-west", "East"], "North-east − 90° = north-west; north-west + 180° = south-east."],
    ["सुनीता उत्तर-पूर्व की ओर मुँह किए है। वह 90° वामावर्त और फिर 180° दक्षिणावर्त घूमती है। अब उसका मुँह किस दिशा में है?", ["उत्तर-पश्चिम", "दक्षिण-पूर्व", "दक्षिण-पश्चिम", "पूर्व"], "उत्तर-पूर्व से 90° वामावर्त = उत्तर-पश्चिम; उससे 180° = दक्षिण-पूर्व।"]),
  q(3, "reasoning", "ranking", "H", 2,
    ["In a row, Amar is 10th from the left and Bunty is 15th from the right. When they swap places, Amar becomes 18th from the left. How many boys are in the row?", ["30", "31", "32", "33"], "Bunty's place is 18th from the left and 15th from the right: 18 + 15 − 1 = 32."],
    ["एक पंक्ति में अमर बाएँ से 10वाँ और बंटी दाएँ से 15वाँ है। स्थान बदलने पर अमर बाएँ से 18वाँ हो जाता है। पंक्ति में कितने लड़के हैं?", ["30", "31", "32", "33"], "बंटी का स्थान बाएँ से 18वाँ और दाएँ से 15वाँ है: 18 + 15 − 1 = 32।"], "18+15-1"),
  q(3, "reasoning", "analogy", "M", 3,
    ["Lawyer : Client :: Doctor : ?", ["Nurse", "Hospital", "Medicine", "Patient"], "A lawyer serves a client; a doctor serves a patient."],
    ["वकील : मुवक्किल :: डॉक्टर : ?", ["नर्स", "अस्पताल", "दवा", "रोगी"], "वकील मुवक्किल की सेवा करता है; डॉक्टर रोगी की।"]),
  q(3, "reasoning", "odd-one-out", "M", 0,
    ["Find the odd one out: Sutlej, Beas, Ravi, Godavari", ["Godavari", "Sutlej", "Beas", "Ravi"], "The Sutlej, Beas and Ravi flow through Himachal into the Indus system; the Godavari is a peninsular river."],
    ["विषम चुनिए: सतलुज, ब्यास, रावी, गोदावरी", ["गोदावरी", "सतलुज", "ब्यास", "रावी"], "सतलुज, ब्यास और रावी हिमाचल से होकर सिंधु तंत्र में जाती हैं; गोदावरी प्रायद्वीपीय नदी है।"]),
  q(3, "reasoning", "clock-calendar", "H", 2,
    ["What is the angle between the hands of a clock at 5:40?", ["60°", "80°", "70°", "90°"], "Hour hand at 5 × 30 + 40 × 0.5 = 170°, minute hand at 240°; difference 70°."],
    ["5:40 बजे घड़ी की सुइयों के बीच कितना कोण है?", ["60°", "80°", "70°", "90°"], "घंटे की सुई 5 × 30 + 40 × 0.5 = 170° पर, मिनट की सुई 240° पर; अंतर 70°।"], "240-170"),
  q(3, "reasoning", "clock-calendar", "M", 1,
    ["If today is a Saturday, what day of the week will it be 75 days from today?", ["Wednesday", "Thursday", "Friday", "Sunday"], "75 = 10 weeks + 5 days; Saturday + 5 = Thursday."],
    ["यदि आज शनिवार है, तो आज से 75 दिन बाद कौन-सा दिन होगा?", ["बुधवार", "गुरुवार", "शुक्रवार", "रविवार"], "75 = 10 सप्ताह + 5 दिन; शनिवार + 5 = गुरुवार।"]),
  q(3, "reasoning", "inequality", "H", 0,
    ["If A ≥ B > C = D < E, which of these is definitely true?", ["A > D", "E > B", "C > E", "B = E"], "A ≥ B > C = D gives A > D; E's relation with A, B and C is not fixed."],
    ["यदि A ≥ B > C = D < E, तो इनमें से कौन निश्चित रूप से सत्य है?", ["A > D", "E > B", "C > E", "B = E"], "A ≥ B > C = D से A > D मिलता है; E का A, B या C से संबंध निश्चित नहीं है।"]),

  // ───────── Section 4: Mathematics (10) ─────────
  q(4, "quant", "percentage", "M", 1,
    ["The population of a town rises from 40,000 to 46,000. What is the percentage increase?", ["12%", "15%", "18%", "6%"], "Increase = 6,000; 6,000 ÷ 40,000 × 100 = 15%."],
    ["एक नगर की जनसंख्या 40,000 से बढ़कर 46,000 हो जाती है। प्रतिशत वृद्धि कितनी है?", ["12%", "15%", "18%", "6%"], "वृद्धि = 6,000; 6,000 ÷ 40,000 × 100 = 15%।"], "6000/40000*100"),
  q(4, "quant", "profit-loss", "H", 3,
    ["A clerk buys a second-hand computer for ₹2,400, spends ₹600 on repairs and sells it for ₹3,600. What is his profit per cent?", ["50%", "25%", "15%", "20%"], "Total cost = ₹3,000; profit = ₹600; 600 ÷ 3,000 × 100 = 20%."],
    ["एक क्लर्क पुराना कंप्यूटर ₹2,400 में ख़रीदकर ₹600 मरम्मत पर ख़र्च करता है और ₹3,600 में बेचता है। उसका लाभ प्रतिशत क्या है?", ["50%", "25%", "15%", "20%"], "कुल लागत = ₹3,000; लाभ = ₹600; 600 ÷ 3,000 × 100 = 20%।"], "600/3000*100"),
  q(4, "quant", "interest", "M", 2,
    ["In how many years will ₹2,500 earn ₹600 as simple interest at 6% per annum?", ["3 years", "5 years", "4 years", "6 years"], "Time = 600 × 100 ÷ (2,500 × 6) = 4 years."],
    ["₹2,500 पर 6% वार्षिक दर से ₹600 साधारण ब्याज कितने वर्षों में मिलेगा?", ["3 वर्ष", "5 वर्ष", "4 वर्ष", "6 वर्ष"], "समय = 600 × 100 ÷ (2,500 × 6) = 4 वर्ष।"], "600*100/(2500*6)"),
  q(4, "quant", "average", "M", 0,
    ["A clerk's average salary for 5 months is ₹30,000. If he gets ₹36,000 in the sixth month, what is his average for the 6 months?", ["₹31,000", "₹33,000", "₹30,500", "₹32,000"], "(5 × 30,000 + 36,000) ÷ 6 = 1,86,000 ÷ 6 = ₹31,000."],
    ["एक क्लर्क का 5 महीनों का औसत वेतन ₹30,000 है। छठे महीने उसे ₹36,000 मिलते हैं, तो 6 महीनों का औसत क्या है?", ["₹31,000", "₹33,000", "₹30,500", "₹32,000"], "(5 × 30,000 + 36,000) ÷ 6 = 1,86,000 ÷ 6 = ₹31,000।"], "(5*30000+36000)/6"),
  q(4, "quant", "time-work", "H", 1,
    ["A and B together can finish the indexing of a record room in 8 days. A alone can do it in 12 days. How long will B alone take?", ["20 days", "24 days", "16 days", "18 days"], "B's one-day work = 1/8 − 1/12 = 1/24, so B takes 24 days."],
    ["A और B मिलकर एक अभिलेख कक्ष की सूचीकरण 8 दिन में कर सकते हैं। A अकेला 12 दिन में कर सकता है। B अकेला कितने दिन लेगा?", ["20 दिन", "24 दिन", "16 दिन", "18 दिन"], "B का एक दिन का काम = 1/8 − 1/12 = 1/24, अतः B 24 दिन लेगा।"], "1/(1/8-1/12)"),
  q(4, "quant", "speed-distance", "H", 2,
    ["A man drives to the district court at 40 km/h and returns by the same road at 60 km/h. What is his average speed for the whole journey?", ["50 km/h", "45 km/h", "48 km/h", "52 km/h"], "For equal distances, average speed = 2 × 40 × 60 ÷ (40 + 60) = 48 km/h."],
    ["एक व्यक्ति 40 किमी/घंटा से ज़िला न्यायालय जाता है और उसी रास्ते से 60 किमी/घंटा से लौटता है। पूरी यात्रा की औसत चाल क्या है?", ["50 किमी/घंटा", "45 किमी/घंटा", "48 किमी/घंटा", "52 किमी/घंटा"], "समान दूरी के लिए औसत चाल = 2 × 40 × 60 ÷ (40 + 60) = 48 किमी/घंटा।"], "2*40*60/100"),
  q(4, "quant", "ratio-proportion", "M", 3,
    ["If A : B = 2 : 3 and B : C = 4 : 5, what is A : C?", ["2 : 5", "4 : 5", "3 : 5", "8 : 15"], "A : B : C = 8 : 12 : 15, so A : C = 8 : 15."],
    ["यदि A : B = 2 : 3 और B : C = 4 : 5, तो A : C क्या है?", ["2 : 5", "4 : 5", "3 : 5", "8 : 15"], "A : B : C = 8 : 12 : 15, अतः A : C = 8 : 15।"]),
  q(4, "quant", "hcf-lcm", "H", 0,
    ["Three bells ring at intervals of 12, 15 and 20 minutes. If they ring together at 10:00 a.m., when will they next ring together?", ["11:00 a.m.", "10:30 a.m.", "11:30 a.m.", "12:00 noon"], "LCM of 12, 15 and 20 is 60 minutes, so at 11:00 a.m."],
    ["तीन घंटियाँ 12, 15 और 20 मिनट के अंतराल पर बजती हैं। यदि वे सुबह 10:00 बजे साथ बजती हैं, तो अगली बार साथ कब बजेंगी?", ["सुबह 11:00", "सुबह 10:30", "सुबह 11:30", "दोपहर 12:00"], "12, 15 और 20 का LCM 60 मिनट है, अतः सुबह 11:00 बजे।"]),
  q(4, "quant", "mensuration", "M", 2,
    ["What is the area of a triangular plot with a base of 18 m and a height of 10 m?", ["180 m²", "45 m²", "90 m²", "28 m²"], "Area = ½ × 18 × 10 = 90 m²."],
    ["18 मी आधार और 10 मी ऊँचाई वाले त्रिभुजाकार भूखंड का क्षेत्रफल क्या है?", ["180 मी²", "45 मी²", "90 मी²", "28 मी²"], "क्षेत्रफल = ½ × 18 × 10 = 90 मी²।"], "18*10/2"),
  q(4, "quant", "simplification", "H", 1,
    ["Simplify: (0.6 × 0.6 − 0.4 × 0.4) ÷ (0.6 − 0.4)", ["0.2", "1", "2", "0.1"], "(a² − b²) ÷ (a − b) = a + b = 0.6 + 0.4 = 1."],
    ["सरल कीजिए: (0.6 × 0.6 − 0.4 × 0.4) ÷ (0.6 − 0.4)", ["0.2", "1", "2", "0.1"], "(a² − b²) ÷ (a − b) = a + b = 0.6 + 0.4 = 1।"], "(0.36-0.16)/0.2"),

  // ───────── Section 5: Computer (10) ─────────
  q(5, "computer", "shortcuts", "H", 2,
    ["In MS Word, which shortcut inserts a hyperlink on the selected text?", ["Ctrl + H", "Ctrl + L", "Ctrl + K", "Ctrl + Y"], "Ctrl + K opens the Insert Hyperlink box; Ctrl + H opens Replace."],
    ["MS Word में चुने गए टेक्स्ट पर हाइपरलिंक डालने का शॉर्टकट कौन-सा है?", ["Ctrl + H", "Ctrl + L", "Ctrl + K", "Ctrl + Y"], "Ctrl + K से Insert Hyperlink बॉक्स खुलता है; Ctrl + H से Replace।"]),
  q(5, "computer", "ms-office", "M", 0,
    ["Which MS Excel function shows the current date and updates it every day?", ["`=TODAY()`", "`=DATE()`", "`=DAY()`", "`=TIME()`"], "`=TODAY()` returns the current date; `=NOW()` adds the time."],
    ["कौन-सा MS Excel फ़ंक्शन आज की तारीख़ दिखाता है और हर दिन बदल जाता है?", ["`=TODAY()`", "`=DATE()`", "`=DAY()`", "`=TIME()`"], "`=TODAY()` आज की तारीख़ देता है; `=NOW()` समय भी जोड़ता है।"]),
  q(5, "computer", "ms-office", "H", 3,
    ["In MS Excel, what does `=LEN(\"COURT\")` return?", ["1", "4", "6", "5"], "LEN counts the characters in the text: C-O-U-R-T = 5."],
    ["MS Excel में `=LEN(\"COURT\")` क्या लौटाता है?", ["1", "4", "6", "5"], "LEN टेक्स्ट के अक्षर गिनता है: C-O-U-R-T = 5।"], "5"),
  q(5, "computer", "shortcuts", "M", 1,
    ["After copying a party's name from the plaint, which shortcut pastes it into the order sheet?", ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + P"], "Ctrl + V pastes; Ctrl + C copies, Ctrl + X cuts, Ctrl + P prints."],
    ["वादपत्र से पक्षकार का नाम कॉपी करने के बाद उसे ऑर्डर शीट में पेस्ट करने का शॉर्टकट कौन-सा है?", ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + P"], "Ctrl + V पेस्ट करता है; Ctrl + C कॉपी, Ctrl + X कट, Ctrl + P प्रिंट।"]),
  q(5, "computer", "hardware", "M", 2,
    ["Which memory permanently stores the start-up instructions of a computer and is not erased when power is off?", ["RAM", "Cache", "ROM", "Register"], "ROM (Read Only Memory) is non-volatile and holds the start-up firmware."],
    ["कौन-सी मेमोरी कंप्यूटर के स्टार्ट-अप निर्देश स्थायी रूप से रखती है और बिजली जाने पर भी नहीं मिटती?", ["RAM", "कैश", "ROM", "रजिस्टर"], "ROM (Read Only Memory) अस्थिर नहीं है और स्टार्ट-अप फ़र्मवेयर रखती है।"]),
  q(5, "computer", "internet-networking", "M", 0,
    ["In an e-mail, the 'Cc' field stands for:", ["Carbon copy", "Copy check", "Common copy", "Central copy"], "Cc is carbon copy: those addresses get a copy that all recipients can see."],
    ["ई-मेल में 'Cc' फ़ील्ड का पूरा रूप है:", ["Carbon copy", "Copy check", "Common copy", "Central copy"], "Cc का अर्थ carbon copy है: इन पतों को प्रति जाती है जो सब प्राप्तकर्ता देख सकते हैं।"]),
  q(5, "computer", "internet-networking", "H", 3,
    ["Which device connects the court office's local network to the internet and directs data between the networks?", ["Monitor", "Scanner", "UPS", "Router"], "A router forwards data between networks, such as the office LAN and the internet."],
    ["कौन-सा उपकरण कोर्ट कार्यालय के स्थानीय नेटवर्क को इंटरनेट से जोड़ता है और नेटवर्कों के बीच डेटा भेजता है?", ["मॉनिटर", "स्कैनर", "UPS", "राउटर"], "राउटर नेटवर्कों के बीच, जैसे ऑफ़िस LAN और इंटरनेट के बीच, डेटा आगे भेजता है।"]),
  q(5, "computer", "security", "M", 1,
    ["The OTP sent to your phone while paying a court fee online stands for:", ["Online Transfer Protocol", "One Time Password", "Official Transaction PIN", "Open Text Process"], "An OTP is a One Time Password valid for a single login or transaction."],
    ["ऑनलाइन कोर्ट फ़ीस भरते समय फ़ोन पर आने वाले OTP का पूरा रूप है:", ["Online Transfer Protocol", "One Time Password", "Official Transaction PIN", "Open Text Process"], "OTP एक बार उपयोग होने वाला पासवर्ड (One Time Password) है।"]),
  q(5, "computer", "software", "M", 0,
    ["Which of these is a web browser: Mozilla Firefox, MS Access, Tally or Adobe Photoshop?", ["Mozilla Firefox", "MS Access", "Tally", "Adobe Photoshop"], "Firefox is a browser; Access is a database, Tally accounting software and Photoshop an image editor."],
    ["इनमें से कौन वेब ब्राउज़र है: Mozilla Firefox, MS Access, Tally या Adobe Photoshop?", ["Mozilla Firefox", "MS Access", "Tally", "Adobe Photoshop"], "Firefox ब्राउज़र है; Access डेटाबेस, Tally लेखा सॉफ़्टवेयर और Photoshop इमेज एडिटर है।"]),
  q(5, "computer", "fundamentals", "H", 3,
    ["A single character typed in a court order is usually stored in one byte. How many bits make up one byte?", ["2", "4", "16", "8"], "One byte = 8 bits."],
    ["कोर्ट आदेश में टाइप किया गया एक अक्षर प्रायः एक बाइट में संग्रहीत होता है। एक बाइट में कितने बिट होते हैं?", ["2", "4", "16", "8"], "एक बाइट = 8 बिट।"], "8"),
];
