// HP High Court Clerk — Full Mock 3, written fresh: General Knowledge & Himachal GK 30, English 20, Hindi 15,
// Reasoning 15, Mathematics 10, Computer 10.

import { q, type PatwariQuestion } from "../patwari/types";

export const clerkMock3: PatwariQuestion[] = [
  // ───────── Section 0: General Knowledge & Himachal GK (30) ─────────
  q(0, "hp-gk", "geography", "M", 0,
    ["The Great Himalayan National Park, inscribed as a UNESCO World Heritage Site in 2014, is in which district?", ["Kullu", "Chamba", "Kinnaur", "Shimla"], "The park lies in the Kullu district, around the Tirthan, Sainj and Jiwa Nal valleys."],
    ["2014 में यूनेस्को विश्व धरोहर स्थल घोषित ग्रेट हिमालयन नेशनल पार्क किस ज़िले में है?", ["कुल्लू", "चंबा", "किन्नौर", "शिमला"], "यह पार्क कुल्लू ज़िले में तीर्थन, सैंज और जीवा नाल घाटियों के आसपास है।"]),
  q(0, "hp-gk", "geography", "E", 1,
    ["Jujurana, the state bird of Himachal Pradesh, is better known as the:", ["Monal", "Western Tragopan", "Snow Partridge", "Cheer Pheasant"], "The Western Tragopan (Jujurana, 'king of birds') is the state bird; the snow leopard is the state animal."],
    ["हिमाचल प्रदेश का राज्य पक्षी जुजुराना किस नाम से अधिक जाना जाता है?", ["मोनाल", "वेस्टर्न ट्रैगोपैन", "हिम तीतर", "चीड़ फ़ेज़ेंट"], "वेस्टर्न ट्रैगोपैन (जुजुराना, 'पक्षियों का राजा') राज्य पक्षी है; हिम तेंदुआ राज्य पशु है।"]),
  q(0, "hp-gk", "economy", "M", 2,
    ["Solan is nicknamed the 'City of Red Gold' because of its large output of:", ["Apples", "Cherries", "Tomatoes", "Red chillies"], "Solan's tomato crop, sold across north India, earned it the name 'City of Red Gold'."],
    ["सोलन को 'लाल सोने का शहर' किसके बड़े उत्पादन के कारण कहा जाता है?", ["सेब", "चेरी", "टमाटर", "लाल मिर्च"], "उत्तर भारत भर में बिकने वाली टमाटर की फ़सल के कारण सोलन को 'लाल सोने का शहर' कहा जाता है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 3,
    ["Gurdwara Paonta Sahib, where Guru Gobind Singh stayed for over four years, stands on the bank of which river?", ["Sutlej", "Giri", "Beas", "Yamuna"], "Paonta Sahib in Sirmaur stands on the Yamuna, on the Himachal–Uttarakhand border."],
    ["गुरुद्वारा पांवटा साहिब, जहाँ गुरु गोबिंद सिंह चार वर्ष से अधिक रहे, किस नदी के किनारे है?", ["सतलुज", "गिरि", "ब्यास", "यमुना"], "सिरमौर का पांवटा साहिब हिमाचल–उत्तराखंड सीमा पर यमुना के किनारे है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["Chandratal, the crescent-shaped 'Moon Lake' near Kunzum Pass, lies in which district?", ["Kinnaur", "Lahaul and Spiti", "Kullu", "Chamba"], "Chandratal lies in the Lahaul and Spiti district, at about 4,300 m."],
    ["कुंज़ुम दर्रे के पास अर्धचंद्राकार 'चंद्रताल' झील किस ज़िले में है?", ["किन्नौर", "लाहौल और स्पीति", "कुल्लू", "चंबा"], "चंद्रताल लगभग 4,300 मीटर पर लाहौल और स्पीति ज़िले में है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["Bharmour, the old capital known for its Chaurasi temple complex, is in which district?", ["Kangra", "Kullu", "Chamba", "Mandi"], "Bharmour (Brahmapura) in Chamba district was the first capital of the Chamba state."],
    ["चौरासी मंदिर समूह के लिए प्रसिद्ध पुरानी राजधानी भरमौर किस ज़िले में है?", ["कांगड़ा", "कुल्लू", "चंबा", "मंडी"], "चंबा ज़िले का भरमौर (ब्रह्मपुरा) चंबा रियासत की पहली राजधानी था।"]),
  q(0, "hp-gk", "districts", "H", 0,
    ["The Dr Y.S. Parmar University of Horticulture and Forestry is located at:", ["Nauni (Solan)", "Palampur (Kangra)", "Sundernagar (Mandi)", "Rampur (Shimla)"], "The university is at Nauni near Solan; the agricultural university (CSKHPKV) is at Palampur."],
    ["डॉ. वाई.एस. परमार औद्यानिकी एवं वानिकी विश्वविद्यालय कहाँ स्थित है?", ["नौणी (सोलन)", "पालमपुर (कांगड़ा)", "सुंदरनगर (मंडी)", "रामपुर (शिमला)"], "यह विश्वविद्यालय सोलन के पास नौणी में है; कृषि विश्वविद्यालय (CSKHPKV) पालमपुर में है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The cave shrine of Baba Balak Nath at Deotsidh is in which district?", ["Una", "Bilaspur", "Kangra", "Hamirpur"], "Deotsidh, the shrine of Baba Balak Nath, is in Hamirpur district near its border with Bilaspur."],
    ["दियोटसिद्ध में बाबा बालक नाथ का गुफा मंदिर किस ज़िले में है?", ["ऊना", "बिलासपुर", "कांगड़ा", "हमीरपुर"], "बाबा बालक नाथ का धाम दियोटसिद्ध बिलासपुर सीमा के पास हमीरपुर ज़िले में है।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["The narrow-gauge Kangra Valley Railway runs from Pathankot to:", ["Baijnath", "Jogindernagar", "Palampur", "Mandi"], "The line, opened in 1929, ends at Jogindernagar, where the Shanan power house stands."],
    ["नैरो-गेज कांगड़ा घाटी रेल पठानकोट से कहाँ तक चलती है?", ["बैजनाथ", "जोगिंदरनगर", "पालमपुर", "मंडी"], "1929 में खुली यह लाइन जोगिंदरनगर पर समाप्त होती है, जहाँ शानन पावर हाउस है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The hilltop temple of Shikari Devi, which is said to have no roof, is in which district?", ["Kullu", "Shimla", "Mandi", "Sirmaur"], "Shikari Devi temple stands on a peak in the Janjehli area of Mandi district."],
    ["बिना छत वाला माना जाने वाला शिकारी देवी का पहाड़ी मंदिर किस ज़िले में है?", ["कुल्लू", "शिमला", "मंडी", "सिरमौर"], "शिकारी देवी मंदिर मंडी ज़िले के जंजैहली क्षेत्र की एक चोटी पर है।"]),
  q(0, "general-studies", "indian-polity", "M", 1,
    ["Which Constitutional Amendment of 1992 gave constitutional status to Panchayati Raj institutions?", ["42nd", "73rd", "74th", "61st"], "The 73rd Amendment added Part IX on panchayats; the 74th dealt with municipalities."],
    ["1992 के किस संविधान संशोधन ने पंचायती राज संस्थाओं को संवैधानिक दर्जा दिया?", ["42वाँ", "73वाँ", "74वाँ", "61वाँ"], "73वें संशोधन ने पंचायतों पर भाग IX जोड़ा; 74वाँ नगरपालिकाओं से संबंधित है।"]),
  q(0, "general-studies", "indian-polity", "M", 2,
    ["As per Article 84, a person must be at least how old to be chosen to fill a seat in the Rajya Sabha?", ["25 years", "21 years", "30 years", "35 years"], "Rajya Sabha needs 30 years; Lok Sabha needs 25."],
    ["अनुच्छेद 84 के अनुसार राज्यसभा की सीट के लिए चुने जाने हेतु न्यूनतम आयु कितनी है?", ["25 वर्ष", "21 वर्ष", "30 वर्ष", "35 वर्ष"], "राज्यसभा के लिए 30 वर्ष; लोकसभा के लिए 25 वर्ष।"]),
  q(0, "general-studies", "indian-polity", "M", 3,
    ["The languages recognised by the Constitution, including Dogri added in 2003, are listed in which Schedule?", ["Sixth", "Seventh", "Tenth", "Eighth"], "The Eighth Schedule now lists 22 languages."],
    ["2003 में जोड़ी गई डोगरी सहित संविधान द्वारा मान्य भाषाएँ किस अनुसूची में हैं?", ["छठी", "सातवीं", "दसवीं", "आठवीं"], "आठवीं अनुसूची में अब 22 भाषाएँ हैं।"]),
  q(0, "general-studies", "indian-polity", "H", 0,
    ["Under Article 217, a judge of the High Court of Himachal Pradesh is appointed by the:", ["President of India", "Governor of Himachal Pradesh", "Chief Justice of India", "Chief Minister of Himachal Pradesh"], "The President appoints High Court judges after consulting the CJI and the Governor."],
    ["अनुच्छेद 217 के अंतर्गत हिमाचल प्रदेश उच्च न्यायालय के न्यायाधीश की नियुक्ति कौन करता है?", ["भारत के राष्ट्रपति", "हिमाचल प्रदेश के राज्यपाल", "भारत के मुख्य न्यायाधीश", "हिमाचल प्रदेश के मुख्यमंत्री"], "राष्ट्रपति, मुख्य न्यायाधीश और राज्यपाल से परामर्श के बाद उच्च न्यायालय के न्यायाधीश नियुक्त करते हैं।"]),
  q(0, "general-studies", "indian-polity", "H", 1,
    ["Which Article of the Constitution defines a 'Money Bill'?", ["Article 112", "Article 110", "Article 117", "Article 108"], "Article 110 defines a Money Bill; Article 112 is the annual financial statement."],
    ["संविधान का कौन-सा अनुच्छेद 'धन विधेयक' को परिभाषित करता है?", ["अनुच्छेद 112", "अनुच्छेद 110", "अनुच्छेद 117", "अनुच्छेद 108"], "अनुच्छेद 110 धन विधेयक परिभाषित करता है; अनुच्छेद 112 वार्षिक वित्तीय विवरण है।"]),
  q(0, "general-studies", "indian-history", "M", 2,
    ["In the Battle of Plassey (1757), Robert Clive defeated the Nawab of Bengal:", ["Mir Qasim", "Mir Jafar", "Siraj-ud-Daulah", "Shuja-ud-Daulah"], "Clive defeated Siraj-ud-Daulah, helped by Mir Jafar's betrayal."],
    ["प्लासी के युद्ध (1757) में रॉबर्ट क्लाइव ने बंगाल के किस नवाब को हराया?", ["मीर कासिम", "मीर जाफ़र", "सिराजुद्दौला", "शुजाउद्दौला"], "मीर जाफ़र के विश्वासघात की मदद से क्लाइव ने सिराजुद्दौला को हराया।"]),
  q(0, "general-studies", "indian-history", "M", 3,
    ["Which Mughal emperor built the Buland Darwaza at Fatehpur Sikri to mark his conquest of Gujarat?", ["Babur", "Shah Jahan", "Jahangir", "Akbar"], "Akbar built it around 1575 after his Gujarat campaign."],
    ["गुजरात विजय की स्मृति में फ़तेहपुर सीकरी में बुलंद दरवाज़ा किस मुग़ल बादशाह ने बनवाया?", ["बाबर", "शाहजहाँ", "जहाँगीर", "अकबर"], "अकबर ने गुजरात अभियान के बाद लगभग 1575 में इसे बनवाया।"]),
  q(0, "general-studies", "indian-history", "E", 0,
    ["Gandhi's Dandi March of March–April 1930 was undertaken to break the British law on:", ["Salt", "Indigo", "Land revenue", "Cotton cloth"], "The march to Dandi began the Civil Disobedience Movement against the salt tax."],
    ["गांधीजी की मार्च–अप्रैल 1930 की दांडी यात्रा किस ब्रिटिश क़ानून को तोड़ने के लिए थी?", ["नमक", "नील", "भू-राजस्व", "सूती कपड़ा"], "दांडी यात्रा से नमक कर के विरुद्ध सविनय अवज्ञा आंदोलन शुरू हुआ।"]),
  q(0, "general-studies", "indian-history", "M", 1,
    ["Who served as the first Governor-General of the Dominion of India from August 1947?", ["C. Rajagopalachari", "Lord Mountbatten", "Lord Wavell", "Rajendra Prasad"], "Mountbatten held the post until June 1948; Rajagopalachari was the first (and only) Indian Governor-General."],
    ["अगस्त 1947 से भारत डोमिनियन के पहले गवर्नर-जनरल कौन रहे?", ["सी. राजगोपालाचारी", "लॉर्ड माउंटबेटन", "लॉर्ड वेवल", "राजेंद्र प्रसाद"], "माउंटबेटन जून 1948 तक रहे; राजगोपालाचारी पहले (और एकमात्र) भारतीय गवर्नर-जनरल थे।"]),
  q(0, "general-studies", "indian-history", "M", 2,
    ["The Harappan site of Lothal, known for its ancient dockyard, is in which present-day state?", ["Rajasthan", "Haryana", "Gujarat", "Punjab"], "Lothal lies in Ahmedabad district of Gujarat."],
    ["प्राचीन गोदीबाड़े के लिए प्रसिद्ध हड़प्पा स्थल लोथल किस वर्तमान राज्य में है?", ["राजस्थान", "हरियाणा", "गुजरात", "पंजाब"], "लोथल गुजरात के अहमदाबाद ज़िले में है।"]),
  q(0, "general-studies", "indian-geography", "H", 3,
    ["Which of these four states is NOT crossed by the Tropic of Cancer (23.5° N)?", ["Rajasthan", "Madhya Pradesh", "Jharkhand", "Odisha"], "It crosses Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram — not Odisha."],
    ["कर्क रेखा (23.5° उ.) इन चार में से किस राज्य से नहीं गुज़रती?", ["राजस्थान", "मध्य प्रदेश", "झारखंड", "ओडिशा"], "यह गुजरात, राजस्थान, म.प्र., छत्तीसगढ़, झारखंड, प. बंगाल, त्रिपुरा और मिज़ोरम से गुज़रती है — ओडिशा से नहीं।"]),
  q(0, "general-studies", "indian-geography", "M", 0,
    ["Called the 'Dakshin Ganga', which is the longest river flowing wholly within peninsular India?", ["Godavari", "Krishna", "Mahanadi", "Kaveri"], "The Godavari, about 1,465 km long, is the longest peninsular river."],
    ["'दक्षिण गंगा' कहलाने वाली कौन-सी नदी पूरी तरह प्रायद्वीपीय भारत में बहने वाली सबसे लंबी नदी है?", ["गोदावरी", "कृष्णा", "महानदी", "कावेरी"], "लगभग 1,465 किमी लंबी गोदावरी सबसे लंबी प्रायद्वीपीय नदी है।"]),
  q(0, "general-studies", "indian-geography", "E", 1,
    ["The narrow Palk Strait separates Tamil Nadu from:", ["Maldives", "Sri Lanka", "Andaman Islands", "Lakshadweep"], "Palk Strait lies between Tamil Nadu and northern Sri Lanka."],
    ["संकरा पाक जलडमरूमध्य तमिलनाडु को किससे अलग करता है?", ["मालदीव", "श्रीलंका", "अंडमान द्वीप", "लक्षद्वीप"], "पाक जलडमरूमध्य तमिलनाडु और उत्तरी श्रीलंका के बीच है।"]),
  q(0, "general-studies", "indian-geography", "H", 2,
    ["The black cotton (regur) soil of the Deccan has mainly formed from the weathering of:", ["Granite", "Sandstone", "Basalt lava rock", "River alluvium"], "Regur soil comes from the basalt of the Deccan Traps."],
    ["दक्कन की काली कपास (रेगुर) मिट्टी मुख्यतः किसके अपक्षय से बनी है?", ["ग्रेनाइट", "बलुआ पत्थर", "बेसाल्ट लावा चट्टान", "नदी जलोढ़"], "रेगुर मिट्टी दक्कन ट्रैप के बेसाल्ट से बनती है।"]),
  q(0, "general-studies", "indian-economy", "M", 3,
    ["In the RBI's monetary policy, the 'repo rate' is the rate at which:", ["Banks lend to farmers", "Banks pay interest on savings", "The government borrows abroad", "The RBI lends short-term funds to commercial banks"], "Repo is the RBI's lending rate to banks against government securities."],
    ["RBI की मौद्रिक नीति में 'रेपो दर' वह दर है जिस पर:", ["बैंक किसानों को ऋण देते हैं", "बैंक बचत पर ब्याज देते हैं", "सरकार विदेश से उधार लेती है", "RBI वाणिज्यिक बैंकों को अल्पकालिक ऋण देता है"], "रेपो सरकारी प्रतिभूतियों के बदले बैंकों को RBI की उधार दर है।"]),
  q(0, "general-studies", "indian-economy", "M", 0,
    ["From which date did the Goods and Services Tax (GST) come into force across India?", ["1 July 2017", "1 April 2017", "8 November 2016", "1 January 2018"], "GST was launched at midnight on 30 June–1 July 2017."],
    ["वस्तु एवं सेवा कर (GST) पूरे भारत में किस तारीख़ से लागू हुआ?", ["1 जुलाई 2017", "1 अप्रैल 2017", "8 नवंबर 2016", "1 जनवरी 2018"], "GST 30 जून–1 जुलाई 2017 की आधी रात को लागू हुआ।"]),
  q(0, "general-studies", "general-science", "E", 1,
    ["In the SI system, the electrical resistance of a heater coil is measured in:", ["Volt", "Ohm", "Ampere", "Watt"], "Resistance is measured in ohm (Ω)."],
    ["SI पद्धति में हीटर की कुंडली का विद्युत प्रतिरोध किसमें मापा जाता है?", ["वोल्ट", "ओम", "एम्पियर", "वाट"], "प्रतिरोध ओम (Ω) में मापा जाता है।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["Bleeding gums and slow healing of wounds (scurvy) are caused by lack of vitamin:", ["A", "D", "C", "K"], "Vitamin C (ascorbic acid) deficiency causes scurvy."],
    ["मसूड़ों से ख़ून आना और घाव धीरे भरना (स्कर्वी) किस विटामिन की कमी से होता है?", ["A", "D", "C", "K"], "विटामिन C (एस्कॉर्बिक अम्ल) की कमी से स्कर्वी होता है।"]),
  q(0, "general-studies", "general-science", "M", 3,
    ["Which part of the human eye adjusts the size of the pupil to control the light entering?", ["Cornea", "Retina", "Lens", "Iris"], "The coloured iris widens or narrows the pupil."],
    ["मानव आँख का कौन-सा भाग पुतली का आकार बदलकर अंदर आने वाले प्रकाश को नियंत्रित करता है?", ["कॉर्निया", "रेटिना", "लेंस", "परितारिका (आइरिस)"], "रंगीन परितारिका पुतली को फैलाती या सिकोड़ती है।"]),
  q(0, "general-studies", "general-science", "E", 0,
    ["The chemical symbol 'K', taken from its Latin name Kalium, stands for:", ["Potassium", "Krypton", "Calcium", "Phosphorus"], "K is potassium (Kalium); Kr is krypton."],
    ["लैटिन नाम कैलियम से लिया गया रासायनिक प्रतीक 'K' किसका है?", ["पोटैशियम", "क्रिप्टॉन", "कैल्शियम", "फ़ॉस्फ़ोरस"], "K पोटैशियम (कैलियम) है; Kr क्रिप्टॉन है।"]),

  // ───────── Section 1: English (20) ─────────
  q(1, "english", "grammar", "H", 1,
    ["Choose the correct verb: 'Neither the clerk nor the officers ___ present at the hearing.'", ["was", "were", "is", "has been"], "With 'neither … nor', the verb agrees with the nearer subject, 'officers'."],
    ["सही क्रिया चुनिए: 'Neither the clerk nor the officers ___ present at the hearing.'", ["was", "were", "is", "has been"], "'Neither … nor' में क्रिया निकटतम कर्ता 'officers' के अनुसार होती है।"]),
  q(1, "english", "grammar", "M", 0,
    ["Fill in the blank: 'The application must reach the Registry ___ 5 p.m. on Friday.'", ["by", "since", "from", "during"], "'By' marks a deadline."],
    ["रिक्त स्थान भरिए: 'The application must reach the Registry ___ 5 p.m. on Friday.'", ["by", "since", "from", "during"], "समय-सीमा बताने के लिए 'by' आता है।"]),
  q(1, "english", "grammar", "H", 2,
    ["Choose the correct form: 'If I ___ the Registrar, I would sign the order today.'", ["was", "am", "were", "had"], "An imaginary condition takes the subjunctive 'were' for all persons."],
    ["सही रूप चुनिए: 'If I ___ the Registrar, I would sign the order today.'", ["was", "am", "were", "had"], "काल्पनिक शर्त में सभी पुरुषों के साथ 'were' आता है।"]),
  q(1, "english", "grammar", "M", 1,
    ["Choose the correct article: 'She is ___ honest employee of the copying branch.'", ["a", "an", "the", "no article"], "'Honest' begins with a vowel sound (silent h), so 'an'."],
    ["सही आर्टिकल चुनिए: 'She is ___ honest employee of the copying branch.'", ["a", "an", "the", "no article"], "'Honest' का h मौन है, स्वर ध्वनि से आरंभ होने के कारण 'an'।"]),
  q(1, "english", "grammar", "H", 1,
    ["Fill in the blank: 'Scarcely had the judge entered the courtroom ___ the lawyers stood up.'", ["than", "when", "then", "as"], "'Scarcely' and 'hardly' pair with 'when'; 'no sooner' pairs with 'than'."],
    ["रिक्त स्थान भरिए: 'Scarcely had the judge entered the courtroom ___ the lawyers stood up.'", ["than", "when", "then", "as"], "'Scarcely' और 'hardly' के साथ 'when' आता है; 'no sooner' के साथ 'than'।"]),
  q(1, "english", "error-spotting", "M", 1,
    ["Find the part with an error in: 'The number of pending cases (A) / are increasing (B) / every year (C) / in the district courts. (D)'", ["The number of pending cases", "are increasing", "every year", "in the district courts"], "'The number of' takes a singular verb: 'is increasing'."],
    ["इस वाक्य में त्रुटि वाला भाग चुनिए: 'The number of pending cases (A) / are increasing (B) / every year (C) / in the district courts. (D)'", ["The number of pending cases", "are increasing", "every year", "in the district courts"], "'The number of' के साथ एकवचन क्रिया आती है: 'is increasing'।"]),
  q(1, "english", "error-spotting", "H", 1,
    ["Find the part with an error in: 'He is one of the clerks (A) / who has been (B) / transferred to (C) / the Dharamshala court. (D)'", ["He is one of the clerks", "who has been", "transferred to", "the Dharamshala court"], "'Who' refers to the plural 'clerks', so 'who have been'."],
    ["इस वाक्य में त्रुटि वाला भाग चुनिए: 'He is one of the clerks (A) / who has been (B) / transferred to (C) / the Dharamshala court. (D)'", ["He is one of the clerks", "who has been", "transferred to", "the Dharamshala court"], "'Who' बहुवचन 'clerks' के लिए है, अतः 'who have been'।"]),
  q(1, "english", "synonyms-antonyms", "M", 1,
    ["Choose the word closest in meaning to 'DILIGENT' as used in 'a diligent copying clerk':", ["Lazy", "Hard-working", "Careless", "Talkative"], "Diligent means careful and hard-working."],
    ["'a diligent copying clerk' में 'DILIGENT' का निकटतम अर्थ वाला शब्द चुनिए:", ["Lazy", "Hard-working", "Careless", "Talkative"], "Diligent का अर्थ है मेहनती और सावधान।"]),
  q(1, "english", "synonyms-antonyms", "M", 1,
    ["Choose the word opposite in meaning to 'TRANSPARENT' as in 'a transparent selection procedure':", ["Clear", "Opaque", "Honest", "Open"], "Transparent (open to view) is the opposite of opaque (hidden)."],
    ["'a transparent selection procedure' में 'TRANSPARENT' का विलोम चुनिए:", ["Clear", "Opaque", "Honest", "Open"], "Transparent (स्पष्ट) का विलोम opaque (अपारदर्शी/छिपा) है।"]),
  q(1, "english", "synonyms-antonyms", "H", 0,
    ["Choose the word closest in meaning to 'ADJOURN' as in 'The court will adjourn the matter to Monday':", ["Postpone", "Dismiss", "Decide", "Begin"], "To adjourn is to put off to a later date."],
    ["'The court will adjourn the matter to Monday' में 'ADJOURN' का निकटतम अर्थ चुनिए:", ["Postpone", "Dismiss", "Decide", "Begin"], "Adjourn का अर्थ है आगे की तारीख़ तक टालना।"]),
  q(1, "english", "synonyms-antonyms", "H", 1,
    ["Choose the word opposite in meaning to 'ACQUIT' as in 'The court acquitted the accused':", ["Release", "Convict", "Pardon", "Excuse"], "To acquit is to declare not guilty; to convict is to declare guilty."],
    ["'The court acquitted the accused' में 'ACQUIT' का विलोम चुनिए:", ["Release", "Convict", "Pardon", "Excuse"], "Acquit = निर्दोष घोषित करना; convict = दोषी ठहराना।"]),
  q(1, "english", "one-word", "M", 0,
    ["One word for 'a written statement confirmed on oath and filed as evidence in court':", ["Affidavit", "Petition", "Summons", "Verdict"], "An affidavit is a sworn written statement."],
    ["'शपथ पर पुष्ट और न्यायालय में साक्ष्य के रूप में दाख़िल लिखित कथन' के लिए एक शब्द:", ["Affidavit", "Petition", "Summons", "Verdict"], "Affidavit शपथ-युक्त लिखित कथन है।"]),
  q(1, "english", "one-word", "H", 0,
    ["One word for 'a trader whom a court has declared unable to pay his debts':", ["Insolvent", "Illiterate", "Invalid", "Immigrant"], "An insolvent person cannot meet his debts."],
    ["'ऐसा व्यापारी जिसे न्यायालय ने ऋण चुकाने में असमर्थ घोषित किया हो' के लिए एक शब्द:", ["Insolvent", "Illiterate", "Invalid", "Immigrant"], "Insolvent वह है जो अपने ऋण नहीं चुका सकता।"]),
  q(1, "english", "idioms", "M", 1,
    ["'Before the clerk exam, Ravi burnt the midnight oil.' The idiom means he:", ["wasted electricity", "studied late into the night", "cooked dinner late", "slept early"], "To burn the midnight oil is to work or study late at night."],
    ["'Before the clerk exam, Ravi burnt the midnight oil.' मुहावरे का अर्थ है कि उसने:", ["बिजली बर्बाद की", "देर रात तक पढ़ाई की", "देर से खाना बनाया", "जल्दी सो गया"], "To burn the midnight oil = देर रात तक काम या पढ़ाई करना।"]),
  q(1, "english", "idioms", "H", 0,
    ["'The new transfer rules are still up in the air.' The idiom means the rules are:", ["undecided", "very strict", "already cancelled", "widely popular"], "Up in the air means not yet settled."],
    ["'The new transfer rules are still up in the air.' मुहावरे का अर्थ है कि नियम:", ["अभी तय नहीं हुए", "बहुत कड़े हैं", "रद्द हो चुके हैं", "बहुत लोकप्रिय हैं"], "Up in the air = अभी अनिश्चित।"]),
  q(1, "english", "voice-speech", "H", 0,
    ["Choose the passive form of: 'The process server delivered the summons yesterday.'", ["The summons was delivered by the process server yesterday.", "The summons were delivering by the process server yesterday.", "The summons had delivered the process server yesterday.", "The process server was delivered the summons yesterday."], "Object becomes subject; past simple passive = was + past participle ('summons' is singular)."],
    ["इसका कर्मवाच्य चुनिए: 'The process server delivered the summons yesterday.'", ["The summons was delivered by the process server yesterday.", "The summons were delivering by the process server yesterday.", "The summons had delivered the process server yesterday.", "The process server was delivered the summons yesterday."], "कर्म कर्ता बनता है; past simple passive = was + past participle ('summons' एकवचन है)।"]),
  q(1, "english", "voice-speech", "H", 0,
    ["Change into indirect speech: He said, 'I am filing the appeal today.'", ["He said that he was filing the appeal that day.", "He said that I am filing the appeal today.", "He said that he is filing the appeal today.", "He said that he had filed the appeal that day."], "Present continuous becomes past continuous; 'today' becomes 'that day'."],
    ["अप्रत्यक्ष कथन में बदलिए: He said, 'I am filing the appeal today.'", ["He said that he was filing the appeal that day.", "He said that I am filing the appeal today.", "He said that he is filing the appeal today.", "He said that he had filed the appeal that day."], "Present continuous → past continuous; 'today' → 'that day'।"]),
  q(1, "english", "spelling", "M", 0,
    ["Choose the correctly spelt court-office word:", ["Adjournment", "Ajournment", "Adjurnment", "Adjornment"], "The correct spelling is 'adjournment'."],
    ["कोर्ट-कार्यालय का सही वर्तनी वाला शब्द चुनिए:", ["Adjournment", "Ajournment", "Adjurnment", "Adjornment"], "सही वर्तनी 'adjournment' है।"]),
  q(1, "english", "vocabulary", "H", 0,
    ["Choose the word that best fits: 'The witness gave a ___ account, so the judge believed him.'", ["credible", "credulous", "creditable", "incredible"], "Credible = believable; credulous = too ready to believe; creditable = praiseworthy."],
    ["उपयुक्त शब्द चुनिए: 'The witness gave a ___ account, so the judge believed him.'", ["credible", "credulous", "creditable", "incredible"], "Credible = विश्वसनीय; credulous = जल्दी विश्वास करने वाला; creditable = प्रशंसनीय।"]),
  q(1, "english", "vocabulary", "M", 0,
    ["In 'The statement was recorded verbatim', the word 'verbatim' means:", ["word for word", "in summary", "in Hindi", "from memory"], "Verbatim means in exactly the same words."],
    ["'The statement was recorded verbatim' में 'verbatim' का अर्थ है:", ["शब्दशः", "संक्षेप में", "हिंदी में", "स्मृति से"], "Verbatim = ठीक उन्हीं शब्दों में।"]),

  // ───────── Section 2: Hindi (15) ─────────
  q(2, "hindi", "sandhi-samas", "M", 1,
    ["Pick the correct sandhi split of the Hindi word 'हिमालय':", ["हिमा + लय", "हिम + आलय", "हिमा + आलय", "हि + मालय"], "अ + आ = आ: हिम + आलय (dirgh sandhi)."],
    ["'हिमालय' का सही संधि-विच्छेद चुनिए:", ["हिमा + लय", "हिम + आलय", "हिमा + आलय", "हि + मालय"], "अ + आ = आ: हिम + आलय (दीर्घ संधि)।"]),
  q(2, "hindi", "sandhi-samas", "H", 2,
    ["Pick the correct sandhi split of the Hindi word 'जगन्नाथ':", ["जग + नाथ", "जगन् + नाथ", "जगत् + नाथ", "जगा + नाथ"], "त् before न becomes न्: जगत् + नाथ (vyanjan sandhi)."],
    ["'जगन्नाथ' का सही संधि-विच्छेद चुनिए:", ["जग + नाथ", "जगन् + नाथ", "जगत् + नाथ", "जगा + नाथ"], "न से पहले त् का न्: जगत् + नाथ (व्यंजन संधि)।"]),
  q(2, "hindi", "sandhi-samas", "M", 3,
    ["Which samas is in the Hindi word 'चौराहा'?", ["Dvandva", "Tatpurush", "Bahuvrihi", "Dvigu"], "चार राहों का समूह — the first part is a number, so dvigu."],
    ["'चौराहा' में कौन-सा समास है?", ["द्वंद्व", "तत्पुरुष", "बहुव्रीहि", "द्विगु"], "चार राहों का समूह — पहला पद संख्यावाचक, अतः द्विगु।"]),
  q(2, "hindi", "sandhi-samas", "M", 0,
    ["Which samas is in the Hindi word 'राधा-कृष्ण'?", ["Dvandva", "Dvigu", "Karmadharaya", "Avyayibhav"], "राधा और कृष्ण — both parts are equally important, so dvandva."],
    ["'राधा-कृष्ण' में कौन-सा समास है?", ["द्वंद्व", "द्विगु", "कर्मधारय", "अव्ययीभाव"], "राधा और कृष्ण — दोनों पद प्रधान, अतः द्वंद्व।"]),
  q(2, "hindi", "paryay-vilom", "M", 0,
    ["Which word is a synonym of the Hindi word 'सूर्य'?", ["दिनकर", "निशाकर", "सुधाकर", "राकेश"], "दिनकर means the sun; the other three mean the moon."],
    ["'सूर्य' का पर्यायवाची कौन-सा है?", ["दिनकर", "निशाकर", "सुधाकर", "राकेश"], "दिनकर = सूर्य; शेष तीनों चंद्रमा के पर्याय हैं।"]),
  q(2, "hindi", "paryay-vilom", "M", 1,
    ["Which word is the antonym of the Hindi word 'उत्कर्ष'?", ["उन्नति", "अपकर्ष", "प्रगति", "उत्थान"], "उत्कर्ष (rise) — अपकर्ष (decline)."],
    ["'उत्कर्ष' का विलोम कौन-सा है?", ["उन्नति", "अपकर्ष", "प्रगति", "उत्थान"], "उत्कर्ष का विलोम अपकर्ष है।"]),
  q(2, "hindi", "paryay-vilom", "H", 0,
    ["Which word is the antonym of the Hindi word 'कृतज्ञ'?", ["कृतघ्न", "अज्ञ", "विज्ञ", "सुज्ञ"], "कृतज्ञ (grateful) — कृतघ्न (ungrateful)."],
    ["'कृतज्ञ' का विलोम कौन-सा है?", ["कृतघ्न", "अज्ञ", "विज्ञ", "सुज्ञ"], "कृतज्ञ का विलोम कृतघ्न है।"]),
  q(2, "hindi", "muhavare", "M", 0,
    ["What does the Hindi idiom 'आँख का तारा' mean?", ["बहुत प्यारा", "बहुत बड़ा शत्रु", "अंधा व्यक्ति", "चालाक व्यक्ति"], "आँख का तारा — someone very dear."],
    ["मुहावरे 'आँख का तारा' का अर्थ है:", ["बहुत प्यारा", "बहुत बड़ा शत्रु", "अंधा व्यक्ति", "चालाक व्यक्ति"], "आँख का तारा = अत्यंत प्रिय।"]),
  q(2, "hindi", "muhavare", "H", 1,
    ["What does the Hindi idiom 'नौ दो ग्यारह होना' mean?", ["हिसाब लगाना", "भाग जाना", "धोखा देना", "झगड़ा करना"], "नौ दो ग्यारह होना — to run away."],
    ["मुहावरे 'नौ दो ग्यारह होना' का अर्थ है:", ["हिसाब लगाना", "भाग जाना", "धोखा देना", "झगड़ा करना"], "नौ दो ग्यारह होना = भाग जाना।"]),
  q(2, "hindi", "ek-shabd", "M", 1,
    ["One Hindi word for 'जो ईश्वर में विश्वास रखता हो':", ["नास्तिक", "आस्तिक", "धार्मिक", "भक्त"], "आस्तिक believes in God; नास्तिक does not."],
    ["'जो ईश्वर में विश्वास रखता हो' के लिए एक शब्द:", ["नास्तिक", "आस्तिक", "धार्मिक", "भक्त"], "आस्तिक ईश्वर में विश्वास रखता है; नास्तिक नहीं।"]),
  q(2, "hindi", "ek-shabd", "H", 0,
    ["One Hindi word for 'जो दूसरों के दोष ढूँढ़ता रहता हो':", ["छिद्रान्वेषी", "परोपकारी", "मितव्ययी", "अन्वेषक"], "छिद्रान्वेषी — one who looks for faults in others."],
    ["'जो दूसरों के दोष ढूँढ़ता रहता हो' के लिए एक शब्द:", ["छिद्रान्वेषी", "परोपकारी", "मितव्ययी", "अन्वेषक"], "छिद्रान्वेषी = दूसरों के दोष खोजने वाला।"]),
  q(2, "hindi", "shuddh-vartani", "M", 1,
    ["Which spelling of the Hindi word for 'excessive' is correct?", ["अत्याधिक", "अत्यधिक", "अतयधिक", "अत्यधीक"], "अति + अधिक = अत्यधिक (yan sandhi)."],
    ["शुद्ध वर्तनी वाला शब्द चुनिए:", ["अत्याधिक", "अत्यधिक", "अतयधिक", "अत्यधीक"], "अति + अधिक = अत्यधिक (यण संधि)।"]),
  q(2, "hindi", "shuddh-vartani", "H", 2,
    ["Which spelling of the Hindi word for 'bright' is correct?", ["उज्वल", "उजवल", "उज्ज्वल", "उज्जवल"], "उत् + ज्वल = उज्ज्वल."],
    ["'उज्ज्वल' की शुद्ध वर्तनी चुनिए:", ["उज्वल", "उजवल", "उज्ज्वल", "उज्जवल"], "उत् + ज्वल = उज्ज्वल।"]),
  q(2, "hindi", "vyakaran", "H", 1,
    ["In Hindi grammar, the vibhakti 'से' showing separation (as in 'पेड़ से पत्ता गिरा') belongs to which kaarak?", ["Karan", "Apadan", "Sampradan", "Adhikaran"], "Separation is shown by apadan kaarak; 'से' as instrument is karan."],
    ["'पेड़ से पत्ता गिरा' में अलगाव बताने वाली 'से' विभक्ति किस कारक की है?", ["करण", "अपादान", "संप्रदान", "अधिकरण"], "अलगाव अपादान कारक दर्शाता है; साधन के अर्थ में 'से' करण है।"]),
  q(2, "hindi", "alankar-ras", "H", 1,
    ["Which alankar is in the Hindi line 'चरण कमल बंदौं हरि राई'?", ["Upma", "Rupak", "Utpreksha", "Anupras"], "चरण are treated as one with कमल (no comparing word), so rupak."],
    ["'चरण कमल बंदौं हरि राई' में कौन-सा अलंकार है?", ["उपमा", "रूपक", "उत्प्रेक्षा", "अनुप्रास"], "चरण और कमल में अभेद (वाचक शब्द नहीं), अतः रूपक।"]),

  // ───────── Section 3: Reasoning (15) ─────────
  q(3, "reasoning", "series", "M", 1,
    ["Find the next number: 7, 12, 22, 37, 57, ?", ["77", "82", "87", "80"], "Differences are 5, 10, 15, 20, 25: 57 + 25 = 82."],
    ["अगली संख्या ज्ञात कीजिए: 7, 12, 22, 37, 57, ?", ["77", "82", "87", "80"], "अंतर 5, 10, 15, 20, 25: 57 + 25 = 82।"], "57+25"),
  q(3, "reasoning", "series", "H", 1,
    ["Find the next number: 8, 15, 24, 35, 48, ?", ["60", "63", "64", "62"], "Terms are n² − 1 for n = 3 to 7; next is 8² − 1 = 63."],
    ["अगली संख्या ज्ञात कीजिए: 8, 15, 24, 35, 48, ?", ["60", "63", "64", "62"], "पद n² − 1 हैं (n = 3 से 7); अगला 8² − 1 = 63।"], "8*8-1"),
  q(3, "reasoning", "alphabet-test", "M", 0,
    ["Find the next term: BY, DW, FU, HS, ?", ["JQ", "IR", "JR", "KQ"], "First letters go +2 (B, D, F, H, J); second letters go −2 (Y, W, U, S, Q)."],
    ["अगला पद ज्ञात कीजिए: BY, DW, FU, HS, ?", ["JQ", "IR", "JR", "KQ"], "पहले अक्षर +2 (B, D, F, H, J); दूसरे −2 (Y, W, U, S, Q)।"]),
  q(3, "reasoning", "coding-decoding", "H", 0,
    ["If BENCH is coded as CFODI, how is JUDGE coded?", ["KVEHF", "KVFHF", "IVEHF", "KUEHF"], "Each letter moves one place forward: J→K, U→V, D→E, G→H, E→F."],
    ["यदि BENCH को CFODI लिखा जाता है, तो JUDGE को कैसे लिखेंगे?", ["KVEHF", "KVFHF", "IVEHF", "KUEHF"], "हर अक्षर एक स्थान आगे: J→K, U→V, D→E, G→H, E→F।"]),
  q(3, "reasoning", "coding-decoding", "M", 0,
    ["In a code, ORDER is written as REDRO. How is CLERK written in that code?", ["KRELC", "KERLC", "KRLEC", "KLERC"], "The word is written in reverse."],
    ["एक कूट में ORDER को REDRO लिखा जाता है। उसी कूट में CLERK कैसे लिखेंगे?", ["KRELC", "KERLC", "KRLEC", "KLERC"], "शब्द को उल्टा लिखा गया है।"]),
  q(3, "reasoning", "blood-relations", "H", 1,
    ["Pointing to a man, Seema says, 'He is the only son of my mother's father.' How is the man related to Seema?", ["Father", "Maternal uncle", "Brother", "Grandfather"], "The only son of her maternal grandfather is her mother's brother — her maternal uncle."],
    ["एक व्यक्ति की ओर इशारा करते हुए सीमा कहती है, 'वह मेरी माँ के पिता का इकलौता बेटा है।' वह व्यक्ति सीमा का क्या लगता है?", ["पिता", "मामा", "भाई", "नाना"], "नाना का इकलौता बेटा माँ का भाई — यानी मामा।"]),
  q(3, "reasoning", "blood-relations", "M", 0,
    ["A is the brother of B. B is the daughter of C. D is the husband of C. How is A related to D?", ["Son", "Brother", "Nephew", "Father"], "A and B are children of C and her husband D, so A is D's son."],
    ["A, B का भाई है। B, C की बेटी है। D, C का पति है। A का D से क्या संबंध है?", ["पुत्र", "भाई", "भतीजा", "पिता"], "A और B, C और उसके पति D की संतान हैं, अतः A, D का पुत्र है।"]),
  q(3, "reasoning", "direction-sense", "M", 1,
    ["Ramesh walks 6 km north, turns right and walks 8 km. How far is he from his starting point?", ["14 km", "10 km", "12 km", "2 km"], "√(6² + 8²) = √100 = 10 km."],
    ["रमेश 6 किमी उत्तर चलता है, दाएँ मुड़कर 8 किमी चलता है। वह आरंभ बिंदु से कितनी दूर है?", ["14 किमी", "10 किमी", "12 किमी", "2 किमी"], "√(6² + 8²) = √100 = 10 किमी।"], "Math.sqrt(36+64)"),
  q(3, "reasoning", "direction-sense", "H", 0,
    ["Facing east, a clerk turns 90° clockwise and then 180° anticlockwise. Which direction does he face now?", ["North", "South", "West", "East"], "East → 90° clockwise = south → 180° anticlockwise = north."],
    ["पूर्व की ओर मुख किए एक क्लर्क 90° दक्षिणावर्त और फिर 180° वामावर्त घूमता है। अब उसका मुख किस दिशा में है?", ["उत्तर", "दक्षिण", "पश्चिम", "पूर्व"], "पूर्व → 90° दक्षिणावर्त = दक्षिण → 180° वामावर्त = उत्तर।"]),
  q(3, "reasoning", "clock-calendar", "H", 1,
    ["What is the angle between the hour and minute hands of a clock at 4:20?", ["0°", "10°", "20°", "5°"], "Hour hand at 4 × 30 + 20 × 0.5 = 130°; minute hand at 120°; difference 10°."],
    ["4:20 पर घड़ी की घंटे और मिनट की सुइयों के बीच कितना कोण है?", ["0°", "10°", "20°", "5°"], "घंटे की सुई 4 × 30 + 20 × 0.5 = 130°; मिनट की सुई 120°; अंतर 10°।"], "4*30+20*0.5-20*6"),
  q(3, "reasoning", "clock-calendar", "H", 1,
    ["If 1 January 2026 is a Thursday, what day of the week is 1 March 2026?", ["Saturday", "Sunday", "Monday", "Wednesday"], "January 31 + February 28 = 59 days; 59 = 8 weeks + 3 days; Thursday + 3 = Sunday."],
    ["यदि 1 जनवरी 2026 को गुरुवार है, तो 1 मार्च 2026 को कौन-सा दिन होगा?", ["शनिवार", "रविवार", "सोमवार", "बुधवार"], "जनवरी 31 + फ़रवरी 28 = 59 दिन; 59 = 8 सप्ताह + 3 दिन; गुरुवार + 3 = रविवार।"]),
  q(3, "reasoning", "analogy", "M", 0,
    ["Pen : Writer :: Scalpel : ?", ["Surgeon", "Butcher", "Tailor", "Painter"], "A writer works with a pen; a surgeon works with a scalpel."],
    ["कलम : लेखक :: स्कैल्पेल (शल्य छुरी) : ?", ["सर्जन", "कसाई", "दर्ज़ी", "चित्रकार"], "लेखक कलम से काम करता है; सर्जन स्कैल्पेल से।"]),
  q(3, "reasoning", "odd-one-out", "M", 3,
    ["Find the odd one out: 27, 64, 125, 144", ["27", "64", "125", "144"], "27, 64 and 125 are perfect cubes; 144 is a square, not a cube."],
    ["विषम संख्या चुनिए: 27, 64, 125, 144", ["27", "64", "125", "144"], "27, 64, 125 पूर्ण घन हैं; 144 वर्ग है, घन नहीं।"]),
  q(3, "reasoning", "ranking", "H", 1,
    ["In a row of 40 candidates, Anil is 12th from the left. What is his position from the right?", ["28th", "29th", "30th", "27th"], "40 − 12 + 1 = 29th."],
    ["40 अभ्यर्थियों की पंक्ति में अनिल बाएँ से 12वाँ है। दाएँ से उसका स्थान क्या है?", ["28वाँ", "29वाँ", "30वाँ", "27वाँ"], "40 − 12 + 1 = 29वाँ।"], "40-12+1"),
  q(3, "reasoning", "syllogism", "H", 3,
    ["Statements: All stenographers are typists. Some typists are clerks. Conclusions: I. Some stenographers are clerks. II. All clerks are typists.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "The clerks among typists need not be stenographers, and only some clerks are known to be typists."],
    ["कथन: सभी आशुलिपिक टाइपिस्ट हैं। कुछ टाइपिस्ट क्लर्क हैं। निष्कर्ष: I. कुछ आशुलिपिक क्लर्क हैं। II. सभी क्लर्क टाइपिस्ट हैं।", ["केवल I अनुसरण करता है", "केवल II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "टाइपिस्ट क्लर्क आशुलिपिक हों, यह ज़रूरी नहीं; और केवल कुछ क्लर्क टाइपिस्ट ज्ञात हैं।"]),

  // ───────── Section 4: Mathematics (10) ─────────
  q(4, "quant", "percentage", "M", 0,
    ["A clerk's monthly salary of ₹32,000 is raised by 15%. What is the new salary?", ["₹36,800", "₹36,000", "₹35,200", "₹37,500"], "32,000 × 1.15 = ₹36,800."],
    ["एक क्लर्क का ₹32,000 मासिक वेतन 15% बढ़ाया जाता है। नया वेतन क्या है?", ["₹36,800", "₹36,000", "₹35,200", "₹37,500"], "32,000 × 1.15 = ₹36,800।"], "32000*1.15"),
  q(4, "quant", "profit-loss", "M", 1,
    ["A typewriter bought for ₹800 is sold for ₹920. What is the profit per cent?", ["12%", "15%", "18%", "20%"], "Profit ₹120; 120 ÷ 800 × 100 = 15%."],
    ["₹800 में ख़रीदा गया टाइपराइटर ₹920 में बेचा गया। लाभ प्रतिशत क्या है?", ["12%", "15%", "18%", "20%"], "लाभ ₹120; 120 ÷ 800 × 100 = 15%।"], "120/800*100"),
  q(4, "quant", "interest", "M", 0,
    ["What is the simple interest on ₹6,000 at 8% per annum for 3 years?", ["₹1,440", "₹1,200", "₹1,600", "₹1,480"], "SI = 6000 × 8 × 3 ÷ 100 = ₹1,440."],
    ["₹6,000 पर 8% वार्षिक दर से 3 वर्ष का साधारण ब्याज कितना है?", ["₹1,440", "₹1,200", "₹1,600", "₹1,480"], "साधारण ब्याज = 6000 × 8 × 3 ÷ 100 = ₹1,440।"], "6000*8*3/100"),
  q(4, "quant", "average", "H", 1,
    ["The average age of 24 trainee clerks is 22 years. When their instructor's age is included, the average rises by 1 year. What is the instructor's age?", ["46 years", "47 years", "48 years", "23 years"], "25 × 23 − 24 × 22 = 575 − 528 = 47 years."],
    ["24 प्रशिक्षु क्लर्कों की औसत आयु 22 वर्ष है। प्रशिक्षक की आयु जोड़ने पर औसत 1 वर्ष बढ़ जाता है। प्रशिक्षक की आयु क्या है?", ["46 वर्ष", "47 वर्ष", "48 वर्ष", "23 वर्ष"], "25 × 23 − 24 × 22 = 575 − 528 = 47 वर्ष।"], "25*23-24*22"),
  q(4, "quant", "time-work", "H", 0,
    ["A can type a judgment in 12 days and B in 18 days. Working together, how many days will they take?", ["7.2 days", "7.5 days", "6 days", "8 days"], "1/12 + 1/18 = 5/36 per day; 36 ÷ 5 = 7.2 days."],
    ["A एक निर्णय 12 दिन में और B 18 दिन में टाइप कर सकता है। साथ मिलकर कितने दिन लगेंगे?", ["7.2 दिन", "7.5 दिन", "6 दिन", "8 दिन"], "1/12 + 1/18 = 5/36 प्रति दिन; 36 ÷ 5 = 7.2 दिन।"], "1/(1/12+1/18)"),
  q(4, "quant", "speed-distance", "M", 1,
    ["An HRTC bus covers 150 km in 2 hours 30 minutes. What is its average speed?", ["55 km/h", "60 km/h", "65 km/h", "75 km/h"], "150 ÷ 2.5 = 60 km/h."],
    ["HRTC की एक बस 150 किमी 2 घंटे 30 मिनट में तय करती है। उसकी औसत चाल क्या है?", ["55 किमी/घंटा", "60 किमी/घंटा", "65 किमी/घंटा", "75 किमी/घंटा"], "150 ÷ 2.5 = 60 किमी/घंटा।"], "150/2.5"),
  q(4, "quant", "ratio-proportion", "H", 1,
    ["₹4,500 is divided between A and B in the ratio 4 : 5. What is B's share?", ["₹2,000", "₹2,500", "₹2,250", "₹2,700"], "B gets 5/9 × 4,500 = ₹2,500."],
    ["₹4,500 को A और B में 4 : 5 के अनुपात में बाँटा जाता है। B का हिस्सा कितना है?", ["₹2,000", "₹2,500", "₹2,250", "₹2,700"], "B को 5/9 × 4,500 = ₹2,500 मिलते हैं।"], "4500*5/9"),
  q(4, "quant", "hcf-lcm", "M", 1,
    ["What is the LCM of 12, 18 and 30?", ["90", "180", "360", "60"], "12 = 2²·3, 18 = 2·3², 30 = 2·3·5; LCM = 2²·3²·5 = 180."],
    ["12, 18 और 30 का लघुत्तम समापवर्त्य (LCM) क्या है?", ["90", "180", "360", "60"], "12 = 2²·3, 18 = 2·3², 30 = 2·3·5; LCM = 2²·3²·5 = 180।"], "4*9*5"),
  q(4, "quant", "mensuration", "H", 0,
    ["A rectangular record room has an area of 360 m² and a length of 24 m. What is its perimeter?", ["78 m", "76 m", "80 m", "72 m"], "Breadth = 360 ÷ 24 = 15 m; perimeter = 2(24 + 15) = 78 m."],
    ["एक आयताकार रिकॉर्ड कक्ष का क्षेत्रफल 360 वर्ग मी और लंबाई 24 मी है। उसका परिमाप क्या है?", ["78 मी", "76 मी", "80 मी", "72 मी"], "चौड़ाई = 360 ÷ 24 = 15 मी; परिमाप = 2(24 + 15) = 78 मी।"], "2*(24+360/24)"),
  q(4, "quant", "simplification", "M", 0,
    ["Simplify: 48 ÷ 6 × 3 + 5 − 2", ["27", "9", "29", "25"], "By BODMAS, left to right for ÷ and ×: 8 × 3 = 24; 24 + 5 − 2 = 27."],
    ["सरल कीजिए: 48 ÷ 6 × 3 + 5 − 2", ["27", "9", "29", "25"], "BODMAS से ÷ और × बाएँ से दाएँ: 8 × 3 = 24; 24 + 5 − 2 = 27।"], "48/6*3+5-2"),

  // ───────── Section 5: Computer (10) ─────────
  q(5, "computer", "fundamentals", "M", 1,
    ["Which unit inside the CPU carries out addition, subtraction and comparisons?", ["Control Unit", "Arithmetic Logic Unit", "Register", "Cache"], "The ALU does arithmetic and logical operations; the control unit directs them."],
    ["CPU के अंदर कौन-सी इकाई जोड़, घटाव और तुलना करती है?", ["कंट्रोल यूनिट", "अरिथमेटिक लॉजिक यूनिट", "रजिस्टर", "कैश"], "ALU गणितीय और तार्किक क्रियाएँ करती है; कंट्रोल यूनिट उन्हें निर्देशित करती है।"]),
  q(5, "computer", "ms-office", "M", 1,
    ["In MS Word, which shortcut centre-aligns the selected paragraph?", ["Ctrl + C", "Ctrl + E", "Ctrl + J", "Ctrl + R"], "Ctrl + E centres; Ctrl + J justifies; Ctrl + R right-aligns; Ctrl + C copies."],
    ["MS Word में चयनित पैराग्राफ़ को बीच में संरेखित करने का शॉर्टकट कौन-सा है?", ["Ctrl + C", "Ctrl + E", "Ctrl + J", "Ctrl + R"], "Ctrl + E केंद्र; Ctrl + J जस्टिफ़ाई; Ctrl + R दाएँ; Ctrl + C कॉपी।"]),
  q(5, "computer", "ms-office", "H", 1,
    ["In MS Excel, which function counts the cells in a range that are not empty?", ["COUNT", "COUNTA", "COUNTBLANK", "SUM"], "COUNTA counts non-empty cells; COUNT counts only numbers; COUNTBLANK counts empty ones."],
    ["MS Excel में किसी रेंज के ख़ाली न होने वाले सेल कौन-सा फ़ंक्शन गिनता है?", ["COUNT", "COUNTA", "COUNTBLANK", "SUM"], "COUNTA भरे सेल गिनता है; COUNT केवल संख्याएँ; COUNTBLANK ख़ाली सेल।"]),
  q(5, "computer", "ms-office", "H", 1,
    ["In MS Excel, what does the formula =ROUND(17.456, 1) return?", ["17.4", "17.5", "17.46", "18"], "Rounding to one decimal place gives 17.5."],
    ["MS Excel में सूत्र =ROUND(17.456, 1) क्या परिणाम देता है?", ["17.4", "17.5", "17.46", "18"], "एक दशमलव स्थान तक पूर्णांकन से 17.5 मिलता है।"], "17.5"),
  q(5, "computer", "hardware", "M", 2,
    ["During a power cut, unsaved work held in which memory of an office computer is lost?", ["ROM", "Hard disk", "RAM", "Pen drive"], "RAM is volatile: it loses its contents without power."],
    ["बिजली जाने पर कार्यालय कंप्यूटर की किस मेमोरी में रखा बिना सहेजा काम नष्ट हो जाता है?", ["ROM", "हार्ड डिस्क", "RAM", "पेन ड्राइव"], "RAM अस्थायी (volatile) है: बिजली के बिना उसकी सामग्री मिट जाती है।"]),
  q(5, "computer", "internet-networking", "M", 3,
    ["In the web address 'https://hphighcourt.nic.in', which part is the top-level domain?", ["https", "hphighcourt", "nic", ".in"], "The last part, .in (India), is the top-level domain."],
    ["वेब पते 'https://hphighcourt.nic.in' में टॉप-लेवल डोमेन कौन-सा भाग है?", ["https", "hphighcourt", "nic", ".in"], "अंतिम भाग .in (भारत) टॉप-लेवल डोमेन है।"]),
  q(5, "computer", "security", "E", 0,
    ["An e-mail that pretends to come from your bank and asks for your OTP is an example of:", ["Phishing", "Firewall", "Encryption", "Backup"], "Phishing tricks users into revealing passwords or OTPs."],
    ["बैंक के नाम से आया ई-मेल जो आपसे OTP माँगे, किसका उदाहरण है?", ["फ़िशिंग", "फ़ायरवॉल", "एन्क्रिप्शन", "बैकअप"], "फ़िशिंग उपयोगकर्ता को धोखे से पासवर्ड या OTP बताने पर मजबूर करती है।"]),
  q(5, "computer", "operating-systems", "E", 0,
    ["In Windows, a file deleted with the Delete key (not Shift + Delete) first goes to the:", ["Recycle Bin", "Control Panel", "Taskbar", "Clipboard"], "It can be restored from the Recycle Bin; Shift + Delete removes it permanently."],
    ["Windows में Delete कुंजी (Shift + Delete नहीं) से मिटाई गई फ़ाइल पहले कहाँ जाती है?", ["रीसायकल बिन", "कंट्रोल पैनल", "टास्कबार", "क्लिपबोर्ड"], "इसे रीसायकल बिन से वापस लाया जा सकता है; Shift + Delete स्थायी रूप से मिटाता है।"]),
  q(5, "computer", "number-system", "H", 2,
    ["The binary number 10110 equals which decimal number?", ["20", "24", "22", "26"], "16 + 4 + 2 = 22."],
    ["बाइनरी संख्या 10110 किस दशमलव संख्या के बराबर है?", ["20", "24", "22", "26"], "16 + 4 + 2 = 22।"], "16+4+2"),
  q(5, "computer", "hardware", "M", 2,
    ["Which type of printer prints by striking an inked ribbon with a head of tiny pins?", ["Laser", "Inkjet", "Dot-matrix", "Thermal"], "Dot-matrix printers are impact printers, still used for multi-copy forms."],
    ["कौन-सा प्रिंटर छोटी पिनों वाले हेड से स्याही लगे रिबन पर प्रहार करके छापता है?", ["लेज़र", "इंकजेट", "डॉट-मैट्रिक्स", "थर्मल"], "डॉट-मैट्रिक्स इम्पैक्ट प्रिंटर है, जो आज भी बहु-प्रति फ़ॉर्मों के लिए प्रयुक्त होता है।"]),
];
