// HP High Court Process Server — Full Mock 4, written fresh: Himachal GK 25, General Studies 30, Reasoning 15,
// Mathematics 15, Hindi & English 15.

import { q, type PatwariQuestion } from "../patwari/types";

export const processServerMock4: PatwariQuestion[] = [
  // ───────── Section 0: Himachal GK (25) ─────────
  q(0, "hp-gk", "districts", "M", 1,
    ["Because of the Directorate of Mushroom Research at Chambaghat, which town is called the 'Mushroom City of India'?", ["Palampur", "Solan", "Kullu", "Nahan"], "ICAR's Directorate of Mushroom Research is at Chambaghat, Solan."],
    ["चंबाघाट में खुंब अनुसंधान निदेशालय होने के कारण किस शहर को 'भारत का मशरूम शहर' कहा जाता है?", ["पालमपुर", "सोलन", "कुल्लू", "नाहन"], "ICAR का खुंब अनुसंधान निदेशालय चंबाघाट, सोलन में है।"]),
  q(0, "hp-gk", "districts", "H", 2,
    ["As per Census 2011, which district of Himachal Pradesh had the highest literacy rate?", ["Shimla", "Una", "Hamirpur", "Kangra"], "Hamirpur led with about 89% literacy in 2011."],
    ["जनगणना 2011 के अनुसार हिमाचल के किस ज़िले की साक्षरता दर सबसे अधिक थी?", ["शिमला", "ऊना", "हमीरपुर", "कांगड़ा"], "2011 में लगभग 89% साक्षरता के साथ हमीरपुर सबसे आगे था।"]),
  q(0, "hp-gk", "districts", "M", 3,
    ["By Census 2011 figures, which Himachal district has the largest population?", ["Shimla", "Mandi", "Solan", "Kangra"], "Kangra (about 15.1 lakh) has the largest population; Lahaul and Spiti the smallest."],
    ["जनगणना 2011 के अनुसार हिमाचल का सबसे अधिक जनसंख्या वाला ज़िला कौन-सा है?", ["शिमला", "मंडी", "सोलन", "कांगड़ा"], "कांगड़ा (लगभग 15.1 लाख) की जनसंख्या सबसे अधिक है; लाहौल-स्पीति की सबसे कम।"]),
  q(0, "hp-gk", "economy", "H", 0,
    ["What was the sex ratio (females per 1,000 males) of Himachal Pradesh in Census 2011?", ["972", "940", "1,013", "950"], "Himachal's sex ratio in 2011 was 972, above the national figure of 943."],
    ["जनगणना 2011 में हिमाचल प्रदेश का लिंगानुपात (प्रति 1,000 पुरुषों पर महिलाएँ) कितना था?", ["972", "940", "1,013", "950"], "2011 में हिमाचल का लिंगानुपात 972 था, जो राष्ट्रीय आँकड़े 943 से अधिक है।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["The Viceregal Lodge at Shimla, now the Indian Institute of Advanced Study, was completed in:", ["1864", "1888", "1903", "1947"], "Built for Lord Dufferin, it was completed in 1888; IIAS was set up there in 1965."],
    ["शिमला का वायसरीगल लॉज, जो अब भारतीय उच्च अध्ययन संस्थान है, कब बनकर तैयार हुआ?", ["1864", "1888", "1903", "1947"], "लॉर्ड डफ़रिन के लिए बना यह भवन 1888 में पूरा हुआ; 1965 में यहाँ IIAS स्थापित हुआ।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Jakhoo temple on the highest hill of Shimla is dedicated to:", ["Lord Shiva", "Goddess Durga", "Lord Hanuman", "Lord Vishnu"], "Jakhoo temple, with a 108-ft statue, is dedicated to Hanuman."],
    ["शिमला की सबसे ऊँची पहाड़ी पर स्थित जाखू मंदिर किसे समर्पित है?", ["भगवान शिव", "देवी दुर्गा", "भगवान हनुमान", "भगवान विष्णु"], "108 फ़ुट की प्रतिमा वाला जाखू मंदिर हनुमान जी को समर्पित है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["The Pandoh Dam, which diverts water to the Beas–Sutlej Link, is in which district?", ["Mandi", "Kullu", "Bilaspur", "Kangra"], "Pandoh Dam on the Beas is in Mandi district."],
    ["ब्यास–सतलुज लिंक को पानी भेजने वाला पंडोह बाँध किस ज़िले में है?", ["मंडी", "कुल्लू", "बिलासपुर", "कांगड़ा"], "ब्यास पर बना पंडोह बाँध मंडी ज़िले में है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 3,
    ["At which place in Kinnaur does the Spiti river meet the Sutlej?", ["Kaza", "Pooh", "Karchham", "Khab"], "The Spiti meets the Sutlej at Khab in Kinnaur."],
    ["स्पीति नदी सतलुज से कहाँ मिलती है?", ["काज़ा", "पूह", "करछम", "खाब"], "स्पीति नदी किन्नौर के खाब में सतलुज से मिलती है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["Which river is formed when the Chandra and the Bhaga meet at Tandi in Lahaul?", ["Beas", "Chenab", "Ravi", "Sutlej"], "Their confluence at Tandi in Lahaul forms the Chandrabhaga, i.e. the Chenab."],
    ["चंद्रा और भागा नदियाँ तांदी में मिलकर कौन-सी नदी बनाती हैं?", ["ब्यास", "चिनाब", "रावी", "सतलुज"], "लाहौल के तांदी में इनके संगम से चंद्रभागा अर्थात् चिनाब बनती है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 2,
    ["The Ravi river rises in which area of Himachal Pradesh?", ["Rohtang", "Spiti", "Bara Bhangal", "Pangi"], "The Ravi rises near Bara Bhangal in the Dhauladhar and flows through Chamba."],
    ["रावी नदी हिमाचल के किस क्षेत्र से निकलती है?", ["रोहतांग", "स्पीति", "बड़ा भंगाल", "पांगी"], "रावी धौलाधार के बड़ा भंगाल के पास से निकलकर चंबा से होकर बहती है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["The Beas river originates from Beas Kund near:", ["Rohtang Pass", "Baralacha La", "Shipki La", "Kunzum Pass"], "Beas Kund lies near the Rohtang Pass above Manali."],
    ["ब्यास नदी ब्यास कुंड से निकलती है, जो किसके पास है?", ["रोहतांग दर्रा", "बारालाचा ला", "शिपकी ला", "कुंज़ुम दर्रा"], "ब्यास कुंड मनाली के ऊपर रोहतांग दर्रे के पास है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["Manikaran in the Parvati valley is famous for its gurudwara and:", ["Apple orchards", "Tea gardens", "Ice skating", "Hot springs"], "Manikaran's hot sulphur springs are used to cook langar."],
    ["पार्वती घाटी का मणिकर्ण अपने गुरुद्वारे और किसके लिए प्रसिद्ध है?", ["सेब के बाग़", "चाय बागान", "आइस स्केटिंग", "गर्म पानी के चश्मे"], "मणिकर्ण के गर्म गंधक-युक्त चश्मों में लंगर पकाया जाता है।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["Sach Pass connects Chamba with which valley?", ["Lahaul", "Pangi", "Spiti", "Kinnaur"], "Sach Pass on the Pir Panjal links Chamba with the Pangi valley."],
    ["साच दर्रा चंबा को किस घाटी से जोड़ता है?", ["लाहौल", "पांगी", "स्पीति", "किन्नौर"], "पीर पंजाल का साच दर्रा चंबा को पांगी घाटी से जोड़ता है।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["Kunzum Pass links which two valleys?", ["Kullu and Lahaul", "Kinnaur and Spiti", "Lahaul and Spiti", "Chamba and Pangi"], "Kunzum La connects the Lahaul valley with the Spiti valley."],
    ["कुंज़ुम दर्रा किन दो घाटियों को जोड़ता है?", ["कुल्लू और लाहौल", "किन्नौर और स्पीति", "लाहौल और स्पीति", "चंबा और पांगी"], "कुंज़ुम ला लाहौल घाटी को स्पीति घाटी से जोड़ता है।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["The hill station Dalhousie, founded in 1854, is named after:", ["Lord Dalhousie", "Lord Curzon", "Lord Elgin", "Lord Lytton"], "It was named after Lord Dalhousie, Governor-General of India."],
    ["1854 में बसाया गया पर्वतीय स्थल डलहौज़ी किसके नाम पर है?", ["लॉर्ड डलहौज़ी", "लॉर्ड कर्ज़न", "लॉर्ड एल्गिन", "लॉर्ड लिटन"], "इसका नाम भारत के गवर्नर-जनरल लॉर्ड डलहौज़ी के नाम पर रखा गया।"]),
  q(0, "hp-gk", "polity-administration", "M", 3,
    ["McLeodganj near Dharamshala is the seat of the:", ["A bench of the HP High Court", "HP Board of School Education", "Indian Army's Western Command", "Central Tibetan Administration"], "The Dalai Lama and the Central Tibetan Administration have been based at McLeodganj since 1960."],
    ["धर्मशाला के पास मैक्लोडगंज किसका केंद्र है?", ["हिमाचल उच्च न्यायालय की एक पीठ", "हिमाचल प्रदेश स्कूल शिक्षा बोर्ड", "भारतीय सेना की पश्चिमी कमान", "केंद्रीय तिब्बती प्रशासन"], "दलाई लामा और केंद्रीय तिब्बती प्रशासन 1960 से मैक्लोडगंज में हैं।"]),
  q(0, "hp-gk", "economy", "M", 1,
    ["Palampur in Kangra district is best known for its:", ["Apple orchards", "Tea gardens", "Cement plants", "Salt mines"], "Kangra tea, grown around Palampur, has a GI tag."],
    ["कांगड़ा ज़िले का पालमपुर किसके लिए सबसे अधिक प्रसिद्ध है?", ["सेब के बाग़", "चाय बागान", "सीमेंट संयंत्र", "नमक की खानें"], "पालमपुर के आसपास उगने वाली कांगड़ा चाय को GI टैग मिला है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The chief deity whose rath yatra opens Kullu Dussehra is:", ["Hadimba Devi", "Bijli Mahadev", "Lord Raghunath", "Jamlu Devta"], "Lord Raghunath, brought to Kullu by Raja Jagat Singh in the 17th century, leads the festival."],
    ["कुल्लू दशहरा का आरंभ किस प्रमुख देवता की रथयात्रा से होता है?", ["हिडिंबा देवी", "बिजली महादेव", "भगवान रघुनाथ", "जमलू देवता"], "17वीं सदी में राजा जगत सिंह द्वारा कुल्लू लाए गए भगवान रघुनाथ उत्सव का नेतृत्व करते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Holi fair of Sujanpur Tira is held in which district?", ["Hamirpur", "Kangra", "Una", "Mandi"], "Sujanpur Tira, Raja Sansar Chand's capital, is in Hamirpur district."],
    ["सुजानपुर टीहरा का होली मेला किस ज़िले में लगता है?", ["हमीरपुर", "कांगड़ा", "ऊना", "मंडी"], "राजा संसार चंद की राजधानी सुजानपुर टीहरा हमीरपुर ज़िले में है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The Baijnath temple in Kangra district is dedicated to:", ["Vishnu", "Durga", "Surya", "Shiva as Vaidyanath"], "The 13th-century Baijnath temple is dedicated to Shiva as Vaidyanath, the lord of physicians."],
    ["कांगड़ा ज़िले का बैजनाथ मंदिर किसे समर्पित है?", ["विष्णु", "दुर्गा", "सूर्य", "वैद्यनाथ रूप में शिव"], "13वीं सदी का बैजनाथ मंदिर वैद्यनाथ (वैद्यों के स्वामी) रूप में शिव को समर्पित है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The Trilokinath temple, revered by both Hindus and Buddhists, is in:", ["Spiti", "Lahaul", "Kinnaur", "Chamba"], "Trilokinath near Udaipur in Lahaul houses an image worshipped as Shiva and as Avalokiteshvara."],
    ["हिंदुओं और बौद्धों दोनों द्वारा पूजित त्रिलोकीनाथ मंदिर कहाँ है?", ["स्पीति", "लाहौल", "किन्नौर", "चंबा"], "लाहौल में उदयपुर के पास त्रिलोकीनाथ में एक प्रतिमा शिव और अवलोकितेश्वर दोनों रूपों में पूजी जाती है।"]),
  q(0, "hp-gk", "economy", "H", 2,
    ["The Larji hydroelectric project is built on the river:", ["Sutlej", "Ravi", "Beas", "Parvati only"], "Larji (126 MW) is on the Beas in Kullu district, near the Sainj–Tirthan confluence."],
    ["लारजी जलविद्युत परियोजना किस नदी पर बनी है?", ["सतलुज", "रावी", "ब्यास", "केवल पार्वती"], "लारजी (126 मेगावाट) कुल्लू ज़िले में ब्यास पर है, सैंज–तीर्थन संगम के पास।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["The Gaiety Theatre on the Mall, Shimla, was opened in:", ["1857", "1903", "1921", "1887"], "The Victorian Gaiety Theatre opened in 1887 as part of the Town Hall complex."],
    ["शिमला के माल रोड पर गेयटी थिएटर कब खुला?", ["1857", "1903", "1921", "1887"], "विक्टोरियन शैली का गेयटी थिएटर 1887 में टाउन हॉल परिसर के भाग के रूप में खुला।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["According to Census 2011, which district of Himachal Pradesh has the smallest population?", ["Lahaul and Spiti", "Kinnaur", "Chamba", "Kullu"], "Lahaul and Spiti had about 31,500 people in 2011."],
    ["जनगणना 2011 के अनुसार हिमाचल के किस ज़िले की जनसंख्या सबसे कम है?", ["लाहौल-स्पीति", "किन्नौर", "चंबा", "कुल्लू"], "2011 में लाहौल-स्पीति की जनसंख्या लगभग 31,500 थी।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["Through which pass does the Sutlej enter India from Tibet?", ["Baralacha La", "Shipki La", "Rohtang", "Hamta"], "The Sutlej enters India at Shipki La in Kinnaur."],
    ["सतलुज तिब्बत से भारत में किस दर्रे से प्रवेश करती है?", ["बारालाचा ला", "शिपकी ला", "रोहतांग", "हामटा"], "सतलुज किन्नौर में शिपकी ला से भारत में प्रवेश करती है।"]),

  // ───────── Section 1: General Studies (30) ─────────
  q(1, "general-studies", "indian-polity", "M", 2,
    ["Under Article 80, how many members of the Rajya Sabha are nominated by the President?", ["2", "10", "12", "14"], "Article 80 lets the President nominate 12 members with expertise in literature, science, art and social service."],
    ["राष्ट्रपति राज्यसभा में कितने सदस्य मनोनीत कर सकते हैं?", ["2", "10", "12", "14"], "अनुच्छेद 80 के तहत राष्ट्रपति साहित्य, विज्ञान, कला और समाज-सेवा के 12 विशेषज्ञ मनोनीत करते हैं।"]),
  q(1, "general-studies", "indian-polity", "H", 0,
    ["Elections to panchayats in a state are conducted by the:", ["State Election Commission", "Election Commission of India", "District Collector", "Panchayati Raj Minister"], "Article 243K vests panchayat elections in the State Election Commission."],
    ["किसी राज्य में पंचायत चुनाव कौन करवाता है?", ["राज्य निर्वाचन आयोग", "भारत निर्वाचन आयोग", "ज़िला कलेक्टर", "पंचायती राज मंत्री"], "अनुच्छेद 243K के अनुसार पंचायत चुनाव राज्य निर्वाचन आयोग करवाता है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Which office-holder presides over the Rajya Sabha as its ex-officio Chairman?", ["President", "Vice-President", "Speaker", "Prime Minister"], "Article 64: the Vice-President is ex-officio Chairman of the Council of States."],
    ["राज्यसभा का पदेन सभापति कौन होता है?", ["राष्ट्रपति", "उपराष्ट्रपति", "लोकसभा अध्यक्ष", "प्रधानमंत्री"], "अनुच्छेद 64: उपराष्ट्रपति राज्यसभा का पदेन सभापति होता है।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["A Money Bill is defined in which Article of the Constitution?", ["Article 108", "Article 112", "Article 117", "Article 110"], "Article 110 defines a Money Bill; it can be introduced only in the Lok Sabha."],
    ["धन विधेयक की परिभाषा संविधान के किस अनुच्छेद में है?", ["अनुच्छेद 108", "अनुच्छेद 112", "अनुच्छेद 117", "अनुच्छेद 110"], "अनुच्छेद 110 धन विधेयक को परिभाषित करता है; यह केवल लोकसभा में पेश हो सकता है।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["The languages recognised by the Constitution are listed in the:", ["Sixth Schedule", "Seventh Schedule", "Eighth Schedule", "Tenth Schedule"], "The Eighth Schedule now lists 22 languages."],
    ["संविधान द्वारा मान्यता प्राप्त भाषाएँ किस अनुसूची में हैं?", ["छठी अनुसूची", "सातवीं अनुसूची", "आठवीं अनुसूची", "दसवीं अनुसूची"], "आठवीं अनुसूची में अब 22 भाषाएँ हैं।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["Panchayati Raj institutions got constitutional status through the:", ["73rd Amendment, 1992", "74th Amendment, 1992", "61st Amendment, 1989", "52nd Amendment, 1985"], "The 73rd Amendment added Part IX and the Eleventh Schedule; the 74th dealt with municipalities."],
    ["पंचायती राज संस्थाओं को संवैधानिक दर्जा किस संशोधन से मिला?", ["73वाँ संशोधन, 1992", "74वाँ संशोधन, 1992", "61वाँ संशोधन, 1989", "52वाँ संशोधन, 1985"], "73वें संशोधन ने भाग IX और ग्यारहवीं अनुसूची जोड़ी; 74वाँ नगरपालिकाओं से संबंधित है।"]),
  q(1, "general-studies", "indian-polity", "H", 1,
    ["President's Rule in a state on failure of the constitutional machinery is imposed under:", ["Article 352", "Article 356", "Article 360", "Article 365 only"], "Article 356 is state emergency; 352 national emergency; 360 financial emergency."],
    ["संवैधानिक तंत्र विफल होने पर किसी राज्य में राष्ट्रपति शासन किस अनुच्छेद के तहत लगता है?", ["अनुच्छेद 352", "अनुच्छेद 356", "अनुच्छेद 360", "केवल अनुच्छेद 365"], "अनुच्छेद 356 राज्य आपातकाल; 352 राष्ट्रीय आपातकाल; 360 वित्तीय आपातकाल है।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["The maximum gap allowed between two sessions of Parliament is:", ["Three months", "Four months", "Six months", "One year"], "Article 85 requires that six months must not pass between two sessions."],
    ["संसद के दो सत्रों के बीच अधिकतम कितना अंतर हो सकता है?", ["तीन माह", "चार माह", "छह माह", "एक वर्ष"], "अनुच्छेद 85 के अनुसार दो सत्रों के बीच छह माह से अधिक का अंतर नहीं हो सकता।"]),
  q(1, "general-studies", "indian-history", "M", 3,
    ["The Maurya Empire was founded by:", ["Ashoka", "Bindusara", "Bimbisara", "Chandragupta Maurya"], "Chandragupta Maurya founded the empire around 321 BC with Chanakya's help."],
    ["मौर्य साम्राज्य की स्थापना किसने की?", ["अशोक", "बिंदुसार", "बिंबिसार", "चंद्रगुप्त मौर्य"], "चंद्रगुप्त मौर्य ने चाणक्य की सहायता से लगभग 321 ई.पू. में साम्राज्य स्थापित किया।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["Construction of the Qutub Minar in Delhi was started by:", ["Iltutmish", "Qutb-ud-din Aibak", "Alauddin Khalji", "Firoz Shah Tughlaq"], "Aibak began it around 1199; Iltutmish completed the upper storeys."],
    ["दिल्ली की क़ुतुब मीनार का निर्माण किसने शुरू करवाया?", ["इल्तुतमिश", "क़ुतुबुद्दीन ऐबक", "अलाउद्दीन ख़िलजी", "फ़िरोज़ शाह तुग़लक़"], "ऐबक ने लगभग 1199 में इसे शुरू किया; इल्तुतमिश ने ऊपरी मंज़िलें पूरी कीं।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Bengal was partitioned by Lord Curzon in:", ["1905", "1911", "1885", "1919"], "The 1905 partition sparked the Swadeshi movement; it was annulled in 1911."],
    ["लॉर्ड कर्ज़न ने बंगाल का विभाजन कब किया?", ["1905", "1911", "1885", "1919"], "1905 के विभाजन से स्वदेशी आंदोलन भड़का; 1911 में इसे रद्द किया गया।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["Gandhi withdrew the Non-Cooperation Movement in 1922 after the incident at:", ["Champaran", "Bardoli", "Chauri Chaura", "Kheda"], "Violence at Chauri Chaura (Gorakhpur) in February 1922 led Gandhi to call off the movement."],
    ["1922 में गांधीजी ने किस घटना के बाद असहयोग आंदोलन वापस लिया?", ["चंपारण", "बारदोली", "चौरी चौरा", "खेड़ा"], "फ़रवरी 1922 में चौरी चौरा (गोरखपुर) की हिंसा के बाद गांधीजी ने आंदोलन वापस लिया।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["Who presided over the first session of the Indian National Congress in 1885?", ["Dadabhai Naoroji", "A.O. Hume", "Surendranath Banerjee", "W.C. Bonnerjee"], "Womesh Chunder Bonnerjee presided over the Bombay session attended by 72 delegates."],
    ["1885 में भारतीय राष्ट्रीय कांग्रेस के पहले अधिवेशन की अध्यक्षता किसने की?", ["दादाभाई नौरोजी", "ए.ओ. ह्यूम", "सुरेंद्रनाथ बनर्जी", "डब्ल्यू.सी. बनर्जी"], "व्योमेश चंद्र बनर्जी ने 72 प्रतिनिधियों वाले बंबई अधिवेशन की अध्यक्षता की।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["Who is remembered as the 'Iron Man of India' for integrating the princely states?", ["Jawaharlal Nehru", "Sardar Vallabhbhai Patel", "Subhas Chandra Bose", "Bal Gangadhar Tilak"], "As Home Minister, Patel integrated over 560 princely states."],
    ["रियासतों के एकीकरण के लिए 'भारत के लौह पुरुष' के रूप में किसे याद किया जाता है?", ["जवाहरलाल नेहरू", "सरदार वल्लभभाई पटेल", "सुभाष चंद्र बोस", "बाल गंगाधर तिलक"], "गृह मंत्री के रूप में पटेल ने 560 से अधिक रियासतों का एकीकरण किया।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Against whom did Akbar's army under Man Singh fight the Battle of Haldighati in 1576?", ["Rana Sanga", "Shivaji", "Maharana Pratap", "Hemu"], "Man Singh led the Mughal army against Maharana Pratap of Mewar."],
    ["हल्दीघाटी का युद्ध (1576) अकबर की सेना और किसके बीच हुआ?", ["राणा सांगा", "शिवाजी", "महाराणा प्रताप", "हेमू"], "मान सिंह ने मेवाड़ के महाराणा प्रताप के विरुद्ध मुग़ल सेना का नेतृत्व किया।"]),
  q(1, "general-studies", "indian-geography", "H", 0,
    ["By height, which dam is the tallest in India?", ["Tehri Dam", "Bhakra Dam", "Sardar Sarovar Dam", "Hirakud Dam"], "Tehri Dam (about 260 m) on the Bhagirathi is the tallest; Bhakra (226 m) is second; Hirakud is the longest."],
    ["भारत का सबसे ऊँचा बाँध कौन-सा है?", ["टिहरी बाँध", "भाखड़ा बाँध", "सरदार सरोवर बाँध", "हीराकुंड बाँध"], "भागीरथी पर टिहरी बाँध (लगभग 260 मी) सबसे ऊँचा है; भाखड़ा (226 मी) दूसरा; हीराकुंड सबसे लंबा है।"]),
  q(1, "general-studies", "indian-geography", "M", 3,
    ["Which state has the longest coastline in mainland India?", ["Andhra Pradesh", "Tamil Nadu", "Maharashtra", "Gujarat"], "Gujarat has the longest coastline, about 1,600 km."],
    ["मुख्य भूमि भारत में सबसे लंबी तटरेखा किस राज्य की है?", ["आंध्र प्रदेश", "तमिलनाडु", "महाराष्ट्र", "गुजरात"], "गुजरात की तटरेखा लगभग 1,600 किमी के साथ सबसे लंबी है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["In which state is Kaziranga National Park, home of the one-horned rhinoceros?", ["West Bengal", "Assam", "Arunachal Pradesh", "Uttarakhand"], "Kaziranga in Assam is a UNESCO World Heritage Site."],
    ["एक सींग वाले गैंडे के लिए प्रसिद्ध काज़ीरंगा राष्ट्रीय उद्यान कहाँ है?", ["पश्चिम बंगाल", "असम", "अरुणाचल प्रदेश", "उत्तराखंड"], "असम का काज़ीरंगा यूनेस्को विश्व धरोहर स्थल है।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["Which frequently flooding river is called the 'Sorrow of Bihar'?", ["Gandak", "Son", "Kosi", "Ghaghara"], "The Kosi often shifts its course and floods north Bihar."],
    ["किस नदी को 'बिहार का शोक' कहा जाता है?", ["गंडक", "सोन", "कोसी", "घाघरा"], "कोसी अक्सर मार्ग बदलती है और उत्तर बिहार में बाढ़ लाती है।"]),
  q(1, "general-studies", "indian-geography", "H", 1,
    ["Leaving out K2, which is the highest mountain peak of India?", ["Nanda Devi", "Kangchenjunga", "Kamet", "Anamudi"], "Kangchenjunga (8,586 m) on the Sikkim–Nepal border is India's highest; Nanda Devi is the highest wholly inside India."],
    ["K2 को छोड़कर भारत की सबसे ऊँची पर्वत चोटी कौन-सी है?", ["नंदा देवी", "कंचनजंगा", "कामेट", "अनामुडी"], "कंचनजंगा (8,586 मी) सिक्किम–नेपाल सीमा पर भारत की सबसे ऊँची चोटी है; पूर्णतः भारत में स्थित सबसे ऊँची नंदा देवी है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["In the human body, insulin is produced by the:", ["Liver", "Kidney", "Thyroid", "Pancreas"], "The islets of Langerhans in the pancreas make insulin, which lowers blood sugar."],
    ["मानव शरीर में इंसुलिन किस अंग से बनता है?", ["यकृत", "गुर्दा", "थायरॉइड", "अग्न्याशय"], "अग्न्याशय के लैंगरहैंस द्वीप इंसुलिन बनाते हैं, जो रक्त शर्करा घटाता है।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Approximately how fast does light travel in a vacuum?", ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10⁵ m/s", "340 m/s"], "Light travels at about 3 lakh km per second; 340 m/s is the speed of sound in air."],
    ["निर्वात में प्रकाश की गति लगभग है:", ["3 × 10⁸ मी/से", "3 × 10⁶ मी/से", "3 × 10⁵ मी/से", "340 मी/से"], "प्रकाश लगभग 3 लाख किमी प्रति सेकंड चलता है; 340 मी/से वायु में ध्वनि की गति है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["A lack of which vitamin causes night blindness?", ["Vitamin B1", "Vitamin C", "Vitamin A", "Vitamin K"], "Vitamin A is needed to make rhodopsin in the retina."],
    ["रतौंधी किस विटामिन की कमी से होती है?", ["विटामिन B1", "विटामिन C", "विटामिन A", "विटामिन K"], "रेटिना में रोडोप्सिन बनाने के लिए विटामिन A आवश्यक है।"]),
  q(1, "general-studies", "general-science", "H", 1,
    ["At 25 °C, pure water has a pH of:", ["0", "7", "14", "5.5"], "Pure water is neutral, pH 7; below 7 is acidic, above 7 basic."],
    ["25 °C पर शुद्ध जल का pH कितना होता है?", ["0", "7", "14", "5.5"], "शुद्ध जल उदासीन होता है, pH 7; 7 से कम अम्लीय, अधिक क्षारीय।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["Which metal stays liquid at room temperature?", ["Sodium", "Aluminium", "Lead", "Mercury"], "Mercury melts at about −39 °C."],
    ["कमरे के तापमान पर कौन-सी धातु द्रव अवस्था में रहती है?", ["सोडियम", "एल्युमिनियम", "सीसा", "पारा"], "पारा लगभग −39 °C पर पिघलता है।"]),
  q(1, "general-studies", "general-science", "H", 0,
    ["Which naturally occurring substance is the hardest?", ["Diamond", "Quartz", "Iron", "Graphite"], "Diamond, a form of carbon, scores 10 on the Mohs scale; graphite is soft."],
    ["सबसे कठोर प्राकृतिक पदार्थ कौन-सा है?", ["हीरा", "क्वार्ट्ज़", "लोहा", "ग्रेफ़ाइट"], "कार्बन का रूप हीरा मोह्स पैमाने पर 10 है; ग्रेफ़ाइट मुलायम है।"]),
  q(1, "general-studies", "indian-economy", "M", 2,
    ["What does GDP stand for?", ["Gross Development Product", "General Domestic Price", "Gross Domestic Product", "Government Debt Programme"], "GDP is the value of all final goods and services produced within a country in a year."],
    ["GDP का पूर्ण रूप क्या है?", ["ग्रॉस डेवलपमेंट प्रोडक्ट", "जनरल डोमेस्टिक प्राइस", "ग्रॉस डोमेस्टिक प्रोडक्ट (सकल घरेलू उत्पाद)", "गवर्नमेंट डेट प्रोग्राम"], "GDP एक वर्ष में देश के भीतर उत्पादित सभी अंतिम वस्तुओं और सेवाओं का मूल्य है।"]),
  q(1, "general-studies", "indian-economy", "M", 1,
    ["Which is the largest public sector bank in India?", ["Punjab National Bank", "State Bank of India", "Bank of Baroda", "Canara Bank"], "SBI is the largest bank by assets, branches and customers."],
    ["भारत का सबसे बड़ा सार्वजनिक क्षेत्र का बैंक कौन-सा है?", ["पंजाब नेशनल बैंक", "भारतीय स्टेट बैंक", "बैंक ऑफ़ बड़ौदा", "केनरा बैंक"], "परिसंपत्तियों, शाखाओं और ग्राहकों के आधार पर SBI सबसे बड़ा बैंक है।"]),
  q(1, "general-studies", "indian-economy", "H", 3,
    ["Under PM-KISAN, eligible farmer families receive how much income support a year?", ["₹2,000", "₹4,000", "₹12,000", "₹6,000"], "₹6,000 a year is paid in three instalments of ₹2,000 directly to bank accounts."],
    ["पीएम-किसान के तहत पात्र किसान परिवारों को वर्ष में कितनी आय सहायता मिलती है?", ["₹2,000", "₹4,000", "₹12,000", "₹6,000"], "वर्ष में ₹6,000 तीन किस्तों में ₹2,000-₹2,000 कर सीधे बैंक खाते में दिए जाते हैं।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["The 'Make in India' initiative was launched in:", ["2014", "2016", "2012", "2019"], "Make in India was launched on 25 September 2014 to promote manufacturing."],
    ["'मेक इन इंडिया' पहल कब शुरू हुई?", ["2014", "2016", "2012", "2019"], "विनिर्माण बढ़ाने के लिए मेक इन इंडिया 25 सितंबर 2014 को शुरू हुई।"]),

  // ───────── Section 2: Reasoning (15) ─────────
  q(2, "reasoning", "series", "M", 3,
    ["Find the next number: 3, 9, 27, 81, ?", ["162", "216", "234", "243"], "Each term is multiplied by 3: 81 × 3 = 243."],
    ["अगली संख्या ज्ञात कीजिए: 3, 9, 27, 81, ?", ["162", "216", "234", "243"], "हर पद 3 से गुणा होता है: 81 × 3 = 243।"], "81*3"),
  q(2, "reasoning", "series", "H", 1,
    ["Find the next number: 100, 96, 87, 71, 46, ?", ["20", "10", "12", "15"], "Differences are −4, −9, −16, −25, −36 (squares): 46 − 36 = 10."],
    ["अगली संख्या ज्ञात कीजिए: 100, 96, 87, 71, 46, ?", ["20", "10", "12", "15"], "अंतर −4, −9, −16, −25, −36 (वर्ग) हैं: 46 − 36 = 10।"], "46-36"),
  q(2, "reasoning", "alphabet-test", "M", 0,
    ["Find the next pair: AZ, BY, CX, ?", ["DW", "DV", "EW", "DX"], "The first letter moves forward and the second backward: D and W."],
    ["अगला युग्म ज्ञात कीजिए: AZ, BY, CX, ?", ["DW", "DV", "EW", "DX"], "पहला अक्षर आगे और दूसरा पीछे जाता है: D और W।"]),
  q(2, "reasoning", "coding-decoding", "H", 2,
    ["If each letter is replaced by its position in the alphabet, 'BOOK' becomes 2151511. What does 'LAW' become?", ["12122", "11223", "12123", "12223"], "L = 12, A = 1, W = 23, written together: 12123."],
    ["यदि हर अक्षर को वर्णमाला में उसके स्थान से बदला जाए तो 'BOOK' = 2151511 होता है। 'LAW' क्या होगा?", ["12122", "11223", "12123", "12223"], "L = 12, A = 1, W = 23, साथ लिखने पर 12123।"]),
  q(2, "reasoning", "coding-decoding", "M", 1,
    ["In a code, COURT is written as TRUOC. How is JUDGE written in that code?", ["EDGUJ", "EGDUJ", "EGUDJ", "JEGDU"], "The letters are written in reverse order: JUDGE → EGDUJ."],
    ["एक कोड में COURT को TRUOC लिखा जाता है। उसी कोड में JUDGE को कैसे लिखा जाएगा?", ["EDGUJ", "EGDUJ", "EGUDJ", "JEGDU"], "अक्षर उल्टे क्रम में लिखे जाते हैं: JUDGE → EGDUJ।"]),
  q(2, "reasoning", "blood-relations", "H", 3,
    ["Ankit's mother is the only daughter of Ravi's father. How is Ravi related to Ankit?", ["Father", "Brother", "Cousin", "Maternal uncle"], "The only daughter of Ravi's father is Ravi's sister, who is Ankit's mother; so Ravi is Ankit's maternal uncle."],
    ["अंकित की माँ, रवि के पिता की इकलौती बेटी है। रवि, अंकित का क्या लगता है?", ["पिता", "भाई", "चचेरा भाई", "मामा"], "रवि के पिता की इकलौती बेटी रवि की बहन है, जो अंकित की माँ है; अतः रवि अंकित का मामा है।"]),
  q(2, "reasoning", "blood-relations", "M", 0,
    ["Introducing a man, a woman says, \"His wife is my mother's only daughter.\" How is the man related to the woman?", ["Husband", "Brother", "Father", "Son-in-law"], "Her mother's only daughter is the woman herself, so the man is her husband."],
    ["एक व्यक्ति का परिचय देते हुए एक महिला कहती है, \"इनकी पत्नी मेरी माँ की इकलौती बेटी है।\" वह व्यक्ति महिला का क्या है?", ["पति", "भाई", "पिता", "दामाद"], "माँ की इकलौती बेटी स्वयं वह महिला है, अतः वह व्यक्ति उसका पति है।"]),
  q(2, "reasoning", "direction-sense", "H", 2,
    ["Ramesh faces east. He turns 45° anticlockwise and then 180° clockwise. Which direction does he face now?", ["North-east", "North-west", "South-west", "South-east"], "East → 45° anticlockwise = north-east → 180° = south-west."],
    ["रमेश पूर्व की ओर मुँह किए है। वह 45° वामावर्त और फिर 180° दक्षिणावर्त घूमता है। अब उसका मुँह किस दिशा में है?", ["उत्तर-पूर्व", "उत्तर-पश्चिम", "दक्षिण-पश्चिम", "दक्षिण-पूर्व"], "पूर्व → 45° वामावर्त = उत्तर-पूर्व → 180° = दक्षिण-पश्चिम।"]),
  q(2, "reasoning", "direction-sense", "M", 1,
    ["Sita walks 6 km north and then 8 km west. How far is she from her starting point?", ["14 km", "10 km", "2 km", "12 km"], "√(6² + 8²) = √100 = 10 km."],
    ["सीता 6 किमी उत्तर और फिर 8 किमी पश्चिम चलती है। वह आरंभ बिंदु से कितनी दूर है?", ["14 किमी", "10 किमी", "2 किमी", "12 किमी"], "√(6² + 8²) = √100 = 10 किमी।"], "Math.hypot(6,8)"),
  q(2, "reasoning", "ranking", "H", 0,
    ["Among five boys, A is taller than B, C is taller than A, D is shorter than B and E is the tallest. Who is in the middle by height?", ["A", "B", "C", "D"], "Order: E > C > A > B > D, so A is third, in the middle."],
    ["पाँच लड़कों में A, B से लंबा है, C, A से लंबा है, D, B से छोटा है और E सबसे लंबा है। ऊँचाई में बीच में कौन है?", ["A", "B", "C", "D"], "क्रम: E > C > A > B > D, अतः A तीसरे स्थान पर, बीच में है।"]),
  q(2, "reasoning", "analogy", "M", 2,
    ["Ink : Pen :: Blood : ?", ["Heart", "Body", "Vein", "Red"], "Ink flows through a pen; blood flows through a vein."],
    ["स्याही : पेन :: रक्त : ?", ["हृदय", "शरीर", "शिरा", "लाल"], "स्याही पेन में बहती है; रक्त शिरा में बहता है।"]),
  q(2, "reasoning", "odd-one-out", "M", 3,
    ["Find the odd one out: Process Server, Judge, Advocate, Doctor", ["Process Server", "Judge", "Advocate", "Doctor"], "The first three work in a court of law; a doctor does not."],
    ["विषम चुनिए: प्रोसेस सर्वर, न्यायाधीश, अधिवक्ता, डॉक्टर", ["प्रोसेस सर्वर", "न्यायाधीश", "अधिवक्ता", "डॉक्टर"], "पहले तीन न्यायालय में कार्य करते हैं; डॉक्टर नहीं।"]),
  q(2, "reasoning", "clock-calendar", "H", 1,
    ["What angle do the hands of a clock make at 2:20?", ["40°", "50°", "60°", "70°"], "|30 × 2 − 5.5 × 20| = |60 − 110| = 50°."],
    ["2:20 बजे घड़ी की सुइयाँ कितना कोण बनाती हैं?", ["40°", "50°", "60°", "70°"], "|30 × 2 − 5.5 × 20| = |60 − 110| = 50°।"], "Math.abs(30*2-5.5*20)"),
  q(2, "reasoning", "clock-calendar", "M", 2,
    ["Today is a Wednesday. Which day of the week falls 100 days from today?", ["Thursday", "Saturday", "Friday", "Monday"], "100 = 14 weeks + 2 days, so Wednesday + 2 = Friday."],
    ["यदि आज बुधवार है, तो 100 दिन बाद कौन-सा दिन होगा?", ["गुरुवार", "शनिवार", "शुक्रवार", "सोमवार"], "100 = 14 सप्ताह + 2 दिन, अतः बुधवार + 2 = शुक्रवार।"]),
  q(2, "reasoning", "syllogism", "H", 0,
    ["Statements: Some clerks are typists. No typist is a driver. Conclusions: I. Some clerks are not drivers. II. Some drivers are clerks.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "The clerks who are typists cannot be drivers, so I follows; nothing links drivers to clerks, so II does not."],
    ["कथन: कुछ क्लर्क टाइपिस्ट हैं। कोई टाइपिस्ट ड्राइवर नहीं है। निष्कर्ष: I. कुछ क्लर्क ड्राइवर नहीं हैं। II. कुछ ड्राइवर क्लर्क हैं।", ["केवल I निकलता है", "केवल II निकलता है", "I और II दोनों निकलते हैं", "न I न II निकलता है"], "जो क्लर्क टाइपिस्ट हैं वे ड्राइवर नहीं हो सकते, अतः I निकलता है; ड्राइवरों का क्लर्कों से कोई संबंध नहीं, अतः II नहीं।"]),

  // ───────── Section 3: Mathematics (15) ─────────
  q(3, "quant", "percentage", "M", 1,
    ["What is 35% of 640?", ["214", "224", "234", "244"], "0.35 × 640 = 224."],
    ["640 का 35% कितना है?", ["214", "224", "234", "244"], "0.35 × 640 = 224।"], "0.35*640"),
  q(3, "quant", "interest", "M", 0,
    ["Find the simple interest on ₹8,000 at 6% per annum for 2½ years.", ["₹1,200", "₹960", "₹1,440", "₹1,000"], "SI = 8000 × 6 × 2.5 ÷ 100 = ₹1,200."],
    ["₹8,000 पर 6% वार्षिक दर से 2½ वर्ष का साधारण ब्याज ज्ञात कीजिए।", ["₹1,200", "₹960", "₹1,440", "₹1,000"], "साधारण ब्याज = 8000 × 6 × 2.5 ÷ 100 = ₹1,200।"], "8000*6*2.5/100"),
  q(3, "quant", "average", "M", 2,
    ["What is the average of the first 10 natural numbers?", ["5", "6", "5.5", "10"], "Sum = 55; 55 ÷ 10 = 5.5."],
    ["पहली 10 प्राकृत संख्याओं का औसत कितना है?", ["5", "6", "5.5", "10"], "योग = 55; 55 ÷ 10 = 5.5।"], "55/10"),
  q(3, "quant", "percentage", "H", 3,
    ["Two successive discounts of 10% and 20% are equal to a single discount of:", ["30%", "25%", "32%", "28%"], "0.9 × 0.8 = 0.72, so the single discount is 28%."],
    ["10% और 20% की दो क्रमागत छूटें किस एकल छूट के बराबर हैं?", ["30%", "25%", "32%", "28%"], "0.9 × 0.8 = 0.72, अतः एकल छूट 28% है।"], "100-0.9*0.8*100"),
  q(3, "quant", "time-work", "H", 2,
    ["A pipe fills a tank in 6 hours and another empties it in 9 hours. If both are opened together, the empty tank fills in:", ["15 hours", "12 hours", "18 hours", "3 hours"], "Net rate = 1/6 − 1/9 = 1/18, so 18 hours."],
    ["एक नल टंकी को 6 घंटे में भरता है और दूसरा 9 घंटे में ख़ाली करता है। दोनों साथ खोलने पर ख़ाली टंकी कितने समय में भरेगी?", ["15 घंटे", "12 घंटे", "18 घंटे", "3 घंटे"], "शुद्ध दर = 1/6 − 1/9 = 1/18, अतः 18 घंटे।"], "6*9/(9-6)"),
  q(3, "quant", "speed-distance", "H", 1,
    ["A car covers 216 km in 4 hours. What is its speed in metres per second?", ["12 m/s", "15 m/s", "18 m/s", "54 m/s"], "216 ÷ 4 = 54 km/h = 54 × 5/18 = 15 m/s."],
    ["एक कार 4 घंटे में 216 किमी चलती है। उसकी गति मीटर प्रति सेकंड में कितनी है?", ["12 मी/से", "15 मी/से", "18 मी/से", "54 मी/से"], "216 ÷ 4 = 54 किमी/घंटा = 54 × 5/18 = 15 मी/से।"], "216/4*5/18"),
  q(3, "quant", "ratio-proportion", "M", 0,
    ["₹1,400 is divided between two people in the ratio 3 : 4. The smaller share is:", ["₹600", "₹800", "₹700", "₹400"], "1400 × 3 ÷ 7 = ₹600."],
    ["₹1,400 को दो व्यक्तियों में 3 : 4 के अनुपात में बाँटा जाता है। छोटा हिस्सा है:", ["₹600", "₹800", "₹700", "₹400"], "1400 × 3 ÷ 7 = ₹600।"], "1400*3/7"),
  q(3, "quant", "profit-loss", "M", 3,
    ["A shopkeeper sells an item for ₹540 at a loss of 10%. What was the cost price?", ["₹594", "₹500", "₹580", "₹600"], "CP = 540 ÷ 0.9 = ₹600."],
    ["एक दुकानदार वस्तु को 10% हानि पर ₹540 में बेचता है। क्रय मूल्य क्या था?", ["₹594", "₹500", "₹580", "₹600"], "क्रय मूल्य = 540 ÷ 0.9 = ₹600।"], "540/0.9"),
  q(3, "quant", "hcf-lcm", "M", 1,
    ["What is the smallest number exactly divisible by 8, 12 and 15?", ["60", "120", "240", "360"], "LCM of 8, 12 and 15 = 2³ × 3 × 5 = 120."],
    ["8, 12 और 15 से पूर्णतः विभाज्य सबसे छोटी संख्या कौन-सी है?", ["60", "120", "240", "360"], "8, 12 और 15 का LCM = 2³ × 3 × 5 = 120।"], "120"),
  q(3, "quant", "number-system", "M", 2,
    ["What is the square root of 1,764?", ["38", "44", "42", "48"], "42 × 42 = 1,764."],
    ["1,764 का वर्गमूल क्या है?", ["38", "44", "42", "48"], "42 × 42 = 1,764।"], "Math.sqrt(1764)"),
  q(3, "quant", "mensuration", "M", 0,
    ["The area of a square plot is 196 sq m. What is its perimeter?", ["56 m", "49 m", "28 m", "64 m"], "Side = √196 = 14 m; perimeter = 4 × 14 = 56 m."],
    ["एक वर्गाकार भूखंड का क्षेत्रफल 196 वर्ग मी है। उसका परिमाप क्या है?", ["56 मी", "49 मी", "28 मी", "64 मी"], "भुजा = √196 = 14 मी; परिमाप = 4 × 14 = 56 मी।"], "4*Math.sqrt(196)"),
  q(3, "quant", "mensuration", "E", 3,
    ["What is the volume of a cube of side 5 cm?", ["25 cu cm", "75 cu cm", "100 cu cm", "125 cu cm"], "Volume = 5³ = 125 cu cm."],
    ["5 सेमी भुजा वाले घन का आयतन कितना है?", ["25 घन सेमी", "75 घन सेमी", "100 घन सेमी", "125 घन सेमी"], "आयतन = 5³ = 125 घन सेमी।"], "5**3"),
  q(3, "quant", "percentage", "M", 1,
    ["If 20% of a number is 50, the number is:", ["200", "250", "300", "100"], "x = 50 ÷ 0.2 = 250."],
    ["यदि किसी संख्या का 20% 50 है, तो संख्या है:", ["200", "250", "300", "100"], "x = 50 ÷ 0.2 = 250।"], "50/0.2"),
  q(3, "quant", "ages", "H", 0,
    ["The present ages of two brothers are in the ratio 4 : 5. After 5 years the ratio will be 5 : 6. What is the elder brother's present age?", ["25 years", "20 years", "30 years", "35 years"], "(4x + 5)/(5x + 5) = 5/6 gives x = 5, so the elder is 25."],
    ["दो भाइयों की वर्तमान आयु का अनुपात 4 : 5 है। 5 वर्ष बाद यह 5 : 6 होगा। बड़े भाई की वर्तमान आयु क्या है?", ["25 वर्ष", "20 वर्ष", "30 वर्ष", "35 वर्ष"], "(4x + 5)/(5x + 5) = 5/6 से x = 5, अतः बड़ा भाई 25 वर्ष का है।"], "5*5"),
  q(3, "quant", "simplification", "H", 2,
    ["Simplify: 3/4 + 5/8 − 1/2", ["5/8", "3/4", "7/8", "1"], "6/8 + 5/8 − 4/8 = 7/8."],
    ["सरल कीजिए: 3/4 + 5/8 − 1/2", ["5/8", "3/4", "7/8", "1"], "6/8 + 5/8 − 4/8 = 7/8।"]),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "hindi", "sandhi-samas", "M", 1,
    ["Pick the correct sandhi split of the Hindi word 'महोत्सव':", ["महो + त्सव", "महा + उत्सव", "मह + उत्सव", "महा + ओत्सव"], "आ + उ = ओ, so महा + उत्सव = महोत्सव (gun sandhi)."],
    ["'महोत्सव' का सही संधि-विच्छेद चुनिए:", ["महो + त्सव", "महा + उत्सव", "मह + उत्सव", "महा + ओत्सव"], "आ + उ = ओ, अतः महा + उत्सव = महोत्सव (गुण संधि)।"]),
  q(4, "hindi", "sandhi-samas", "H", 3,
    ["Which samas is in the Hindi word 'दशानन' (meaning Ravana)?", ["Dvigu", "Karmadharaya", "Tatpurush", "Bahuvrihi"], "दस हैं आनन जिसके, अर्थात् रावण — it points to someone else, so bahuvrihi."],
    ["'दशानन' (रावण के अर्थ में) में कौन-सा समास है?", ["द्विगु", "कर्मधारय", "तत्पुरुष", "बहुव्रीहि"], "दस हैं आनन जिसके, अर्थात् रावण — अन्य की ओर संकेत, अतः बहुव्रीहि।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["Pick a synonym of the Hindi word 'आकाश':", ["नभ", "धरा", "जलधि", "पवन"], "नभ, गगन and अंबर mean sky; धरा is earth, जलधि sea, पवन wind."],
    ["'आकाश' का पर्यायवाची शब्द चुनिए:", ["नभ", "धरा", "जलधि", "पवन"], "नभ, गगन और अंबर आकाश के पर्याय हैं; धरा पृथ्वी, जलधि समुद्र और पवन हवा है।"]),
  q(4, "hindi", "paryay-vilom", "M", 2,
    ["Pick the opposite (vilom) of the Hindi word 'मौखिक':", ["वाचिक", "मुखर", "लिखित", "मौन"], "मौखिक (oral) is opposite to लिखित (written)."],
    ["'मौखिक' का विलोम शब्द चुनिए:", ["वाचिक", "मुखर", "लिखित", "मौन"], "मौखिक का विलोम लिखित है।"]),
  q(4, "hindi", "muhavare", "M", 3,
    ["What does the Hindi saying 'ऊँट के मुँह में ज़ीरा' mean?", ["बहुत अधिक", "स्वादिष्ट भोजन", "अचानक लाभ", "आवश्यकता से बहुत कम"], "It describes something far too little for the need."],
    ["लोकोक्ति 'ऊँट के मुँह में ज़ीरा' का अर्थ है:", ["बहुत अधिक", "स्वादिष्ट भोजन", "अचानक लाभ", "आवश्यकता से बहुत कम"], "इसका अर्थ आवश्यकता की तुलना में बहुत कम होना है।"]),
  q(4, "hindi", "ek-shabd", "H", 1,
    ["Give one Hindi word for 'जो पहले कभी न हुआ हो':", ["अद्भुत", "अभूतपूर्व", "अनुपम", "अलौकिक"], "अभूतपूर्व means unprecedented."],
    ["'जो पहले कभी न हुआ हो' के लिए एक शब्द:", ["अद्भुत", "अभूतपूर्व", "अनुपम", "अलौकिक"], "अभूतपूर्व का अर्थ है जो पहले कभी न हुआ हो।"]),
  q(4, "hindi", "shuddh-vartani", "H", 2,
    ["Which is the correct spelling of the Hindi word meaning 'second'?", ["द्वितिय", "दवितीय", "द्वितीय", "द्वीतीय"], "The correct spelling is द्वितीय."],
    ["'दूसरा' अर्थ वाले शब्द की शुद्ध वर्तनी कौन-सी है?", ["द्वितिय", "दवितीय", "द्वितीय", "द्वीतीय"], "शुद्ध वर्तनी द्वितीय है।"]),
  q(4, "hindi", "alankar-ras", "M", 0,
    ["Which alankar is in 'चारु चंद्र की चंचल किरणें'?", ["Anupras", "Yamak", "Upma", "Rupak"], "The sound 'च' repeats — anupras."],
    ["'चारु चंद्र की चंचल किरणें' में कौन-सा अलंकार है?", ["अनुप्रास", "यमक", "उपमा", "रूपक"], "'च' वर्ण की आवृत्ति है — अनुप्रास अलंकार।"]),
  q(4, "english", "grammar", "M", 2,
    ["Fill in the blank: 'The court has not met ___ last Monday.'", ["from", "for", "since", "by"], "'Since' is used with a point in time with the present perfect."],
    ["रिक्त स्थान भरिए: 'The court has not met ___ last Monday.'", ["from", "for", "since", "by"], "Present perfect के साथ समय-बिंदु के लिए 'since' आता है।"]),
  q(4, "english", "synonyms-antonyms", "H", 1,
    ["Pick the word similar in meaning to 'ACQUIT':", ["Convict", "Exonerate", "Accuse", "Arrest"], "To acquit is to declare not guilty — exonerate."],
    ["'ACQUIT' के समान अर्थ वाला शब्द चुनिए:", ["Convict", "Exonerate", "Accuse", "Arrest"], "Acquit का अर्थ निर्दोष घोषित करना — exonerate।"]),
  q(4, "english", "synonyms-antonyms", "M", 3,
    ["Pick the word opposite in meaning to 'PERMANENT':", ["Lasting", "Stable", "Fixed", "Temporary"], "Permanent means lasting for ever; temporary is the opposite."],
    ["'PERMANENT' के विपरीत अर्थ वाला शब्द चुनिए:", ["Lasting", "Stable", "Fixed", "Temporary"], "Permanent का अर्थ स्थायी; इसका विलोम temporary है।"]),
  q(4, "english", "one-word", "M", 0,
    ["Give one word for 'government of the people, by the people, for the people':", ["Democracy", "Monarchy", "Autocracy", "Oligarchy"], "Lincoln's phrase describes democracy."],
    ["'जनता का, जनता द्वारा, जनता के लिए शासन' के लिए एक शब्द:", ["Democracy", "Monarchy", "Autocracy", "Oligarchy"], "लिंकन का यह वाक्य लोकतंत्र (democracy) का वर्णन करता है।"]),
  q(4, "english", "idioms", "M", 2,
    ["The idiom 'to see eye to eye with someone' means:", ["To stare", "To fight", "To agree fully", "To look carefully"], "To see eye to eye is to be in full agreement."],
    ["मुहावरे 'to see eye to eye' का अर्थ क्या है?", ["To stare", "To fight", "To agree fully", "To look carefully"], "इसका अर्थ पूरी तरह सहमत होना है।"]),
  q(4, "english", "voice-speech", "H", 1,
    ["Choose the indirect speech: She said, \"I have finished my work.\"", ["She said that she has finished her work.", "She said that she had finished her work.", "She said that I had finished my work.", "She told that she finished her work."], "Present perfect becomes past perfect and pronouns change: 'she had finished her work'."],
    ["अप्रत्यक्ष कथन चुनिए: She said, \"I have finished my work.\"", ["She said that she has finished her work.", "She said that she had finished her work.", "She said that I had finished my work.", "She told that she finished her work."], "Present perfect, past perfect बनता है और सर्वनाम बदलते हैं: 'she had finished her work'।"]),
  q(4, "english", "spelling", "M", 0,
    ["Choose the correct spelling of the word meaning 'needed, essential':", ["Necessary", "Neccessary", "Necesary", "Neccesary"], "'Necessary' has one c and double s."],
    ["'आवश्यक' अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Necessary", "Neccessary", "Necesary", "Neccesary"], "'Necessary' में एक c और दो s होते हैं।"]),
];
