// HP High Court Process Server — Full Mock 3, written fresh: Himachal GK 25, General Studies 30, Reasoning 15,
// Mathematics 15, Hindi & English 15.

import { q, type PatwariQuestion } from "../patwari/types";

export const processServerMock3: PatwariQuestion[] = [
  // ───────── Section 0: Himachal GK (25) ─────────
  q(0, "hp-gk", "history", "M", 2,
    ["Himachal Pradesh celebrates its Statehood Day (Purna Rajyatva Diwas) on:", ["15 April", "1 November", "25 January", "26 January"], "Himachal became the 18th state of India on 25 January 1971."],
    ["हिमाचल प्रदेश अपना पूर्ण राज्यत्व दिवस कब मनाता है?", ["15 अप्रैल", "1 नवंबर", "25 जनवरी", "26 जनवरी"], "हिमाचल 25 जनवरी 1971 को भारत का 18वाँ राज्य बना।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["Himachal Day, marking the state's formation as a Chief Commissioner's province, falls on:", ["15 April", "25 January", "1 July", "15 August"], "On 15 April 1948 about 30 hill states were merged to form Himachal Pradesh."],
    ["मुख्य आयुक्त प्रांत के रूप में राज्य के गठन की याद में हिमाचल दिवस कब मनाया जाता है?", ["15 अप्रैल", "25 जनवरी", "1 जुलाई", "15 अगस्त"], "15 अप्रैल 1948 को लगभग 30 पहाड़ी रियासतों को मिलाकर हिमाचल प्रदेश बना।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["In which year did the separate Part 'C' state of Bilaspur merge into Himachal Pradesh?", ["1950", "1954", "1966", "1971"], "Bilaspur joined Himachal Pradesh on 1 July 1954."],
    ["अलग 'ग' श्रेणी राज्य बिलासपुर किस वर्ष हिमाचल प्रदेश में मिला?", ["1950", "1954", "1966", "1971"], "बिलासपुर 1 जुलाई 1954 को हिमाचल प्रदेश में मिला।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["On 1 November 1966, which of these areas was transferred from Punjab to Himachal Pradesh?", ["Sirmaur", "Chamba", "Bilaspur", "Kangra"], "Under the Punjab Reorganisation Act, 1966, Kangra, Kullu, Lahaul-Spiti, Shimla and parts of Una came to Himachal."],
    ["1 नवंबर 1966 को इनमें से कौन-सा क्षेत्र पंजाब से हिमाचल प्रदेश को मिला?", ["सिरमौर", "चंबा", "बिलासपुर", "कांगड़ा"], "पंजाब पुनर्गठन अधिनियम, 1966 के तहत कांगड़ा, कुल्लू, लाहौल-स्पीति, शिमला और ऊना के भाग हिमाचल को मिले।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["Which town serves as the district headquarters of Kinnaur?", ["Kalpa", "Reckong Peo", "Sangla", "Pooh"], "Reckong Peo is the district headquarters of Kinnaur; Kalpa was the earlier headquarters."],
    ["किन्नौर ज़िले का मुख्यालय है:", ["कल्पा", "रिकांगपिओ", "सांगला", "पूह"], "रिकांगपिओ किन्नौर का ज़िला मुख्यालय है; पहले मुख्यालय कल्पा था।"]),
  q(0, "hp-gk", "districts", "M", 2,
    ["Which town is the district headquarters of Lahaul and Spiti?", ["Kaza", "Udaipur", "Keylong", "Tandi"], "Keylong in Lahaul is the district headquarters; Kaza is the sub-divisional headquarters of Spiti."],
    ["लाहौल-स्पीति का ज़िला मुख्यालय कहाँ है?", ["काज़ा", "उदयपुर", "केलांग", "तांदी"], "लाहौल का केलांग ज़िला मुख्यालय है; काज़ा स्पीति का उपमंडल मुख्यालय है।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["Nahan is the headquarters of which district?", ["Sirmaur", "Solan", "Shimla", "Una"], "Nahan, founded by Raja Karan Prakash in 1621, is the headquarters of Sirmaur."],
    ["नाहन किस ज़िले का मुख्यालय है?", ["सिरमौर", "सोलन", "शिमला", "ऊना"], "राजा कर्ण प्रकाश द्वारा 1621 में बसाया गया नाहन सिरमौर का मुख्यालय है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 3,
    ["Renuka Lake, the largest natural lake of Himachal Pradesh, is in:", ["Mandi", "Kangra", "Chamba", "Sirmaur"], "Renuka Lake in Sirmaur is the largest natural lake of the state and a Ramsar site."],
    ["हिमाचल की सबसे बड़ी प्राकृतिक झील रेणुका किस ज़िले में है?", ["मंडी", "कांगड़ा", "चंबा", "सिरमौर"], "सिरमौर की रेणुका झील राज्य की सबसे बड़ी प्राकृतिक झील और रामसर स्थल है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 1,
    ["Rewalsar Lake (Tso Pema), sacred to Hindus, Buddhists and Sikhs, is in which district?", ["Kullu", "Mandi", "Chamba", "Kangra"], "Rewalsar near Mandi is linked with Guru Padmasambhava, Rishi Lomas and Guru Gobind Singh."],
    ["हिंदुओं, बौद्धों और सिखों के लिए पवित्र रिवालसर झील (त्सो पेमा) किस ज़िले में है?", ["कुल्लू", "मंडी", "चंबा", "कांगड़ा"], "मंडी के पास रिवालसर गुरु पद्मसंभव, ऋषि लोमश और गुरु गोबिंद सिंह से जुड़ी है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 2,
    ["Prashar Lake, with a pagoda-style temple of Rishi Prashar, is located in:", ["Kullu", "Shimla", "Mandi", "Chamba"], "Prashar Lake lies about 49 km north of Mandi town; its temple is ascribed to Raja Ban Sen of Mandi."],
    ["ऋषि पराशर के पैगोडा शैली मंदिर वाली पराशर झील कहाँ स्थित है?", ["कुल्लू", "शिमला", "मंडी", "चंबा"], "पराशर झील मंडी शहर से लगभग 49 किमी उत्तर में है; इसका मंदिर मंडी के राजा बाण सेन से जोड़ा जाता है।"]),
  q(0, "hp-gk", "geography", "E", 0,
    ["Khajjiar, often called the 'Mini Switzerland of India', is in which district?", ["Chamba", "Kullu", "Shimla", "Kangra"], "Khajjiar, near Dalhousie, is in Chamba district."],
    ["'भारत का मिनी स्विट्ज़रलैंड' कहलाने वाला खज्जियार किस ज़िले में है?", ["चंबा", "कुल्लू", "शिमला", "कांगड़ा"], "डलहौज़ी के पास खज्जियार चंबा ज़िले में है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The Hadimba Devi temple at Manali was built in 1553 by:", ["Raja Jagat Singh", "Raja Sansar Chand", "Raja Ajit Singh", "Raja Bahadur Singh"], "Raja Bahadur Singh of Kullu built the pagoda-style Hadimba temple in 1553."],
    ["मनाली का हिडिंबा देवी मंदिर 1553 में किसने बनवाया?", ["राजा जगत सिंह", "राजा संसार चंद", "राजा अजीत सिंह", "राजा बहादुर सिंह"], "कुल्लू के राजा बहादुर सिंह ने 1553 में पैगोडा शैली का हिडिंबा मंदिर बनवाया।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The Bhuri Singh Museum, opened in 1908, is in:", ["Mandi", "Shimla", "Chamba", "Dharamshala"], "Named after Raja Bhuri Singh, the museum in Chamba holds Pahari paintings and Chamba rumals."],
    ["1908 में खुला भूरी सिंह संग्रहालय कहाँ है?", ["मंडी", "शिमला", "चंबा", "धर्मशाला"], "राजा भूरी सिंह के नाम पर बना यह संग्रहालय चंबा में है जिसमें पहाड़ी चित्र और चंबा रूमाल हैं।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["The international Lavi trade fair is held every November at:", ["Mandi", "Rampur Bushahr", "Kullu", "Nahan"], "Lavi at Rampur is a trade fair of wool, dry fruits and horses dating back to a 17th-century treaty with Tibet."],
    ["अंतरराष्ट्रीय लवी व्यापार मेला हर नवंबर कहाँ होता है?", ["मंडी", "रामपुर बुशहर", "कुल्लू", "नाहन"], "रामपुर का लवी ऊन, सूखे मेवों और घोड़ों का व्यापार मेला है जो तिब्बत के साथ 17वीं सदी की संधि से जुड़ा है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Nalwari fair, famous for its cattle trade, is held in:", ["Bilaspur", "Hamirpur", "Una", "Solan"], "Nalwari is held at Bilaspur every March."],
    ["पशु व्यापार के लिए प्रसिद्ध नलवाड़ी मेला कहाँ लगता है?", ["बिलासपुर", "हमीरपुर", "ऊना", "सोलन"], "नलवाड़ी मेला हर मार्च बिलासपुर में लगता है।"]),
  q(0, "hp-gk", "economy", "H", 3,
    ["The Kol Dam hydroelectric project is on the river:", ["Beas", "Ravi", "Yamuna", "Sutlej"], "Kol Dam (800 MW) of NTPC is on the Sutlej in Bilaspur district."],
    ["कोल डैम जलविद्युत परियोजना किस नदी पर है?", ["ब्यास", "रावी", "यमुना", "सतलुज"], "NTPC का कोल डैम (800 मेगावाट) बिलासपुर ज़िले में सतलुज पर है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["Maharana Pratap Sagar is the reservoir of which dam?", ["Bhakra", "Pong", "Pandoh", "Chamera"], "The Pong Dam on the Beas in Kangra forms Maharana Pratap Sagar."],
    ["महाराणा प्रताप सागर किस बाँध का जलाशय है?", ["भाखड़ा", "पौंग", "पंडोह", "चमेरा"], "कांगड़ा में ब्यास पर बना पौंग बाँध महाराणा प्रताप सागर बनाता है।"]),
  q(0, "hp-gk", "polity-administration", "H", 2,
    ["In 2019 which language was made the second official language of Himachal Pradesh?", ["Pahari", "Punjabi", "Sanskrit", "Urdu"], "The HP Official Language (Amendment) Act, 2019 made Sanskrit the second official language after Hindi."],
    ["2019 में किस भाषा को हिमाचल प्रदेश की दूसरी राजभाषा बनाया गया?", ["पहाड़ी", "पंजाबी", "संस्कृत", "उर्दू"], "हिमाचल प्रदेश राजभाषा (संशोधन) अधिनियम, 2019 से हिंदी के बाद संस्कृत दूसरी राजभाषा बनी।"]),
  q(0, "hp-gk", "polity-administration", "M", 0,
    ["Himachal Pradesh University is located at:", ["Summer Hill, Shimla", "Palampur", "Nauni, Solan", "Hamirpur"], "HPU (1970) is at Summer Hill, Shimla; Palampur has the agriculture university and Nauni the horticulture and forestry university."],
    ["हिमाचल प्रदेश विश्वविद्यालय कहाँ स्थित है?", ["समर हिल, शिमला", "पालमपुर", "नौणी, सोलन", "हमीरपुर"], "HPU (1970) समर हिल, शिमला में है; पालमपुर में कृषि और नौणी में बागवानी एवं वानिकी विश्वविद्यालय है।"]),
  q(0, "hp-gk", "polity-administration", "H", 3,
    ["IIT Mandi has its campus at:", ["Sundernagar", "Joginder Nagar", "Rewalsar", "Kamand"], "IIT Mandi's campus is at Kamand on the Uhl river, about 15 km from Mandi."],
    ["आईआईटी मंडी का परिसर कहाँ है?", ["सुंदरनगर", "जोगिंदर नगर", "रिवालसर", "कमांद"], "आईआईटी मंडी का परिसर मंडी से लगभग 15 किमी दूर उहल नदी के किनारे कमांद में है।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["The Dhauladhar range forms the backdrop of which valley?", ["Spiti", "Sangla", "Kangra", "Pangi"], "The snow-capped Dhauladhar rises sharply above the Kangra valley and Dharamshala."],
    ["धौलाधार पर्वत-शृंखला किस घाटी की पृष्ठभूमि बनाती है?", ["स्पीति", "सांगला", "कांगड़ा", "पांगी"], "बर्फ़ से ढकी धौलाधार कांगड़ा घाटी और धर्मशाला के ऊपर खड़ी उठती है।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["The great Kangra earthquake that devastated the region occurred in:", ["1897", "1905", "1934", "1950"], "The Kangra earthquake of 4 April 1905 killed about 20,000 people."],
    ["क्षेत्र को तबाह करने वाला कांगड़ा का बड़ा भूकंप कब आया?", ["1897", "1905", "1934", "1950"], "4 अप्रैल 1905 के कांगड़ा भूकंप में लगभग 20,000 लोग मारे गए।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["The Katoch dynasty ruled which princely state?", ["Kangra", "Chamba", "Mandi", "Bushahr"], "The Katoch Rajputs of Kangra (Trigarta) are among the oldest ruling families in India."],
    ["कटोच वंश ने किस रियासत पर शासन किया?", ["कांगड़ा", "चंबा", "मंडी", "बुशहर"], "कांगड़ा (त्रिगर्त) के कटोच राजपूत भारत के सबसे पुराने शासक वंशों में हैं।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The Chamba Rumal is famous for its:", ["Wood carving", "Metal casting", "Pottery", "Double-sided embroidery"], "Chamba rumals are embroidered so the design looks the same on both sides (do-rukha); they have a GI tag."],
    ["चंबा रूमाल किसके लिए प्रसिद्ध है?", ["काष्ठ नक्काशी", "धातु ढलाई", "मिट्टी के बर्तन", "दोनों ओर एक जैसी कढ़ाई"], "चंबा रूमाल की कढ़ाई ऐसी होती है कि डिज़ाइन दोनों ओर एक-सा दिखता है (दो-रुखा); इसे GI टैग मिला है।"]),
  q(0, "hp-gk", "economy", "H", 2,
    ["AIIMS Bilaspur is located at:", ["Ghumarwin", "Bilaspur town", "Kothipura", "Barmana"], "AIIMS Bilaspur, inaugurated in October 2022, is at Kothipura."],
    ["एम्स बिलासपुर कहाँ स्थित है?", ["घुमारवीं", "बिलासपुर शहर", "कोठीपुरा", "बरमाणा"], "अक्टूबर 2022 में उद्घाटित एम्स बिलासपुर कोठीपुरा में है।"]),

  // ───────── Section 1: General Studies (30) ─────────
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Untouchability is abolished by which Article of the Indian Constitution?", ["Article 15", "Article 17", "Article 19", "Article 23"], "Article 17 abolishes untouchability and forbids its practice in any form."],
    ["संविधान का कौन-सा अनुच्छेद अस्पृश्यता का अंत करता है?", ["अनुच्छेद 15", "अनुच्छेद 17", "अनुच्छेद 19", "अनुच्छेद 23"], "अनुच्छेद 17 अस्पृश्यता का अंत करता है और किसी भी रूप में इसके आचरण को निषिद्ध करता है।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["The words 'socialist' and 'secular' were added to the Preamble by the:", ["44th Amendment", "52nd Amendment", "73rd Amendment", "42nd Amendment"], "The 42nd Amendment (1976) added 'socialist', 'secular' and 'integrity'."],
    ["प्रस्तावना में 'समाजवादी' और 'पंथनिरपेक्ष' शब्द किस संशोधन से जोड़े गए?", ["44वाँ संशोधन", "52वाँ संशोधन", "73वाँ संशोधन", "42वाँ संशोधन"], "42वें संशोधन (1976) ने 'समाजवादी', 'पंथनिरपेक्ष' और 'अखंडता' जोड़े।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["What is the minimum age to become a member of the Lok Sabha?", ["25 years", "21 years", "30 years", "35 years"], "Article 84: 25 years for the Lok Sabha and 30 for the Rajya Sabha."],
    ["लोकसभा का सदस्य बनने की न्यूनतम आयु क्या है?", ["25 वर्ष", "21 वर्ष", "30 वर्ष", "35 वर्ष"], "अनुच्छेद 84: लोकसभा के लिए 25 और राज्यसभा के लिए 30 वर्ष।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["Who appoints the Governor of an Indian state?", ["Chief Minister", "Chief Justice of India", "President", "Prime Minister"], "Article 155: the President appoints the Governor by warrant under his hand and seal."],
    ["राज्य के राज्यपाल की नियुक्ति कौन करता है?", ["मुख्यमंत्री", "भारत के मुख्य न्यायाधीश", "राष्ट्रपति", "प्रधानमंत्री"], "अनुच्छेद 155: राष्ट्रपति अपने हस्ताक्षर और मुहर वाले अधिपत्र से राज्यपाल नियुक्त करते हैं।"]),
  q(1, "general-studies", "indian-polity", "H", 1,
    ["The right to free and compulsory education (Article 21A) was added by the:", ["73rd Amendment, 1992", "86th Amendment, 2002", "91st Amendment, 2003", "97th Amendment, 2011"], "The 86th Amendment inserted Article 21A for children aged 6–14 and a matching fundamental duty."],
    ["निःशुल्क और अनिवार्य शिक्षा का अधिकार (अनुच्छेद 21क) किस संशोधन से जोड़ा गया?", ["73वाँ संशोधन, 1992", "86वाँ संशोधन, 2002", "91वाँ संशोधन, 2003", "97वाँ संशोधन, 2011"], "86वें संशोधन ने 6–14 वर्ष के बच्चों के लिए अनुच्छेद 21क और इससे जुड़ा मौलिक कर्तव्य जोड़ा।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["How many fundamental duties are listed in Article 51A today?", ["10", "9", "11", "12"], "The 42nd Amendment listed 10; the 86th Amendment added the 11th (duty of parents to educate children)."],
    ["आज अनुच्छेद 51क में कितने मौलिक कर्तव्य हैं?", ["10", "9", "11", "12"], "42वें संशोधन ने 10 कर्तव्य जोड़े; 86वें संशोधन ने 11वाँ (बच्चों को शिक्षा दिलाने का माता-पिता का कर्तव्य) जोड़ा।"]),
  q(1, "general-studies", "indian-polity", "H", 0,
    ["Which writ is issued by a higher court to stop a lower court from exceeding its jurisdiction in a pending case?", ["Prohibition", "Mandamus", "Habeas corpus", "Quo warranto"], "Prohibition stops proceedings while a case is pending; certiorari quashes an order already made."],
    ["किसी लंबित मामले में निचली अदालत को अधिकार-क्षेत्र से बाहर जाने से रोकने के लिए उच्च न्यायालय कौन-सी रिट जारी करता है?", ["प्रतिषेध", "परमादेश", "बंदी प्रत्यक्षीकरण", "अधिकार पृच्छा"], "प्रतिषेध मामला लंबित रहते कार्यवाही रोकता है; उत्प्रेषण पहले से दिए आदेश को रद्द करता है।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["The Chief Election Commissioner of India is appointed by the:", ["Prime Minister", "Chief Justice of India", "Parliament", "President"], "Under Article 324 the President appoints the CEC and other Election Commissioners."],
    ["भारत के मुख्य निर्वाचन आयुक्त की नियुक्ति कौन करता है?", ["प्रधानमंत्री", "भारत के मुख्य न्यायाधीश", "संसद", "राष्ट्रपति"], "अनुच्छेद 324 के तहत राष्ट्रपति मुख्य निर्वाचन आयुक्त और अन्य निर्वाचन आयुक्तों को नियुक्त करते हैं।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["Who founded the Arya Samaj in Bombay in 1875?", ["Raja Rammohun Roy", "Swami Dayanand Saraswati", "Swami Vivekananda", "Keshab Chandra Sen"], "Dayanand Saraswati founded the Arya Samaj in Bombay in 1875 and wrote Satyarth Prakash."],
    ["आर्य समाज की स्थापना 1875 में किसने की?", ["राजा राममोहन राय", "स्वामी दयानंद सरस्वती", "स्वामी विवेकानंद", "केशवचंद्र सेन"], "दयानंद सरस्वती ने 1875 में बंबई में आर्य समाज की स्थापना की और सत्यार्थ प्रकाश लिखा।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Gandhi's Dandi March against the salt tax began in:", ["1920", "1942", "1930", "1919"], "The march from Sabarmati to Dandi began on 12 March 1930 and launched the Civil Disobedience Movement."],
    ["नमक कर के विरुद्ध गांधीजी का दांडी मार्च कब शुरू हुआ?", ["1920", "1942", "1930", "1919"], "साबरमती से दांडी तक की यात्रा 12 मार्च 1930 को शुरू हुई और इससे सविनय अवज्ञा आंदोलन आरंभ हुआ।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["'Gitanjali', for which the Nobel Prize was awarded in 1913, was written by:", ["Rabindranath Tagore", "Bankim Chandra Chatterjee", "Sarojini Naidu", "Premchand"], "Tagore became the first Asian Nobel laureate (Literature, 1913)."],
    ["'गीतांजलि', जिसके लिए 1913 में नोबेल पुरस्कार मिला, किसने लिखी?", ["रवींद्रनाथ टैगोर", "बंकिमचंद्र चटर्जी", "सरोजिनी नायडू", "प्रेमचंद"], "टैगोर पहले एशियाई नोबेल विजेता (साहित्य, 1913) बने।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["Who was the first Governor-General of independent India?", ["C. Rajagopalachari", "Lord Wavell", "Dr Rajendra Prasad", "Lord Mountbatten"], "Mountbatten served until June 1948; C. Rajagopalachari was the first and only Indian Governor-General."],
    ["स्वतंत्र भारत के पहले गवर्नर-जनरल कौन थे?", ["सी. राजगोपालाचारी", "लॉर्ड वेवेल", "डॉ. राजेंद्र प्रसाद", "लॉर्ड माउंटबेटन"], "माउंटबेटन जून 1948 तक रहे; सी. राजगोपालाचारी पहले और एकमात्र भारतीय गवर्नर-जनरल थे।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["In the First Battle of Panipat (1526), Babur defeated:", ["Hemu", "Ibrahim Lodi", "Rana Sanga", "Sher Shah Suri"], "Babur's victory over Ibrahim Lodi founded the Mughal Empire."],
    ["पानीपत के पहले युद्ध (1526) में बाबर ने किसे हराया?", ["हेमू", "इब्राहिम लोदी", "राणा सांगा", "शेरशाह सूरी"], "इब्राहिम लोदी पर बाबर की जीत से मुग़ल साम्राज्य की नींव पड़ी।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["Which war led Emperor Ashoka to give up conquest and turn to Buddhism?", ["Battle of Hydaspes", "Battle of Tarain", "Kalinga war", "Battle of Talikota"], "The bloodshed of the Kalinga war (about 261 BC) is described in his Rock Edict XIII."],
    ["किस युद्ध के बाद सम्राट अशोक ने विजय-नीति छोड़कर बौद्ध धर्म अपनाया?", ["हाइडस्पीज़ का युद्ध", "तराइन का युद्ध", "कलिंग युद्ध", "तालीकोटा का युद्ध"], "कलिंग युद्ध (लगभग 261 ई.पू.) के रक्तपात का वर्णन उसके शिलालेख XIII में है।"]),
  q(1, "general-studies", "indian-history", "M", 3,
    ["The slogan 'Jai Jawan Jai Kisan' was given by:", ["Jawaharlal Nehru", "Indira Gandhi", "Atal Bihari Vajpayee", "Lal Bahadur Shastri"], "Shastri gave the slogan in 1965 during the war with Pakistan and food shortages."],
    ["'जय जवान जय किसान' का नारा किसने दिया?", ["जवाहरलाल नेहरू", "इंदिरा गांधी", "अटल बिहारी वाजपेयी", "लाल बहादुर शास्त्री"], "शास्त्री जी ने 1965 में पाकिस्तान युद्ध और खाद्य संकट के समय यह नारा दिया।"]),
  q(1, "general-studies", "indian-geography", "H", 0,
    ["The southernmost point of India is:", ["Indira Point", "Kanyakumari", "Rameswaram", "Point Calimere"], "Indira Point on Great Nicobar is the southernmost point; Kanyakumari is the southern tip of the mainland."],
    ["भारत का सबसे दक्षिणी बिंदु है:", ["इंदिरा पॉइंट", "कन्याकुमारी", "रामेश्वरम", "पॉइंट कैलिमेर"], "ग्रेट निकोबार का इंदिरा पॉइंट सबसे दक्षिणी बिंदु है; कन्याकुमारी मुख्य भूमि का दक्षिणी छोर है।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["Which soil is best suited for growing cotton?", ["Laterite", "Alluvial", "Black (regur)", "Desert"], "Black soil holds moisture well and is called black cotton soil."],
    ["कपास उगाने के लिए कौन-सी मिट्टी सबसे उपयुक्त है?", ["लेटराइट", "जलोढ़", "काली (रेगुर)", "मरुस्थलीय"], "काली मिट्टी नमी अच्छी तरह रोकती है और इसे काली कपास मिट्टी कहते हैं।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["Which planet is called the 'Red Planet'?", ["Venus", "Mars", "Jupiter", "Mercury"], "Iron oxide dust on its surface makes Mars look red."],
    ["किस ग्रह को 'लाल ग्रह' कहा जाता है?", ["शुक्र", "मंगल", "बृहस्पति", "बुध"], "सतह पर आयरन ऑक्साइड की धूल के कारण मंगल लाल दिखता है।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["Loktak Lake, known for its floating islands (phumdis), is in:", ["Assam", "Meghalaya", "Mizoram", "Manipur"], "Loktak in Manipur has the floating Keibul Lamjao National Park."],
    ["तैरते द्वीपों (फुमदी) के लिए प्रसिद्ध लोकटक झील कहाँ है?", ["असम", "मेघालय", "मिज़ोरम", "मणिपुर"], "मणिपुर की लोकटक झील में तैरता हुआ केइबुल लामजाओ राष्ट्रीय उद्यान है।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Which country lies across the Palk Strait from Tamil Nadu?", ["Sri Lanka", "Maldives", "Myanmar", "Bangladesh"], "The Palk Strait lies between Tamil Nadu and northern Sri Lanka."],
    ["पाक जलडमरूमध्य भारत को किससे अलग करता है?", ["श्रीलंका", "मालदीव", "म्यांमार", "बांग्लादेश"], "पाक जलडमरूमध्य तमिलनाडु और उत्तरी श्रीलंका के बीच है।"]),
  q(1, "general-studies", "indian-geography", "H", 1,
    ["Through which state does the river Narmada flow into the Arabian Sea?", ["Maharashtra", "Gujarat", "Madhya Pradesh", "Goa"], "The Narmada rises at Amarkantak (MP), flows west through a rift valley and meets the sea near Bharuch in Gujarat."],
    ["नर्मदा नदी किस राज्य से होकर अरब सागर में गिरती है?", ["महाराष्ट्र", "गुजरात", "मध्य प्रदेश", "गोवा"], "नर्मदा अमरकंटक (म.प्र.) से निकलकर भ्रंश घाटी में पश्चिम बहती है और गुजरात में भरूच के पास समुद्र में मिलती है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["Which blood cells help the blood to clot?", ["Red blood cells", "White blood cells", "Platelets", "Plasma cells"], "Platelets (thrombocytes) gather at a wound and start clotting."],
    ["कौन-सी रक्त कोशिकाएँ रक्त का थक्का जमाने में मदद करती हैं?", ["लाल रक्त कोशिकाएँ", "श्वेत रक्त कोशिकाएँ", "प्लेटलेट्स", "प्लाज़्मा कोशिकाएँ"], "प्लेटलेट्स (बिंबाणु) घाव पर इकट्ठा होकर थक्का बनाना शुरू करते हैं।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["The SI unit of force is the:", ["Joule", "Watt", "Pascal", "Newton"], "Force is measured in newtons (1 N = 1 kg·m/s²)."],
    ["बल का SI मात्रक है:", ["जूल", "वाट", "पास्कल", "न्यूटन"], "बल न्यूटन में मापा जाता है (1 N = 1 kg·m/s²)।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["Which acid is found mainly in lemons?", ["Acetic acid", "Citric acid", "Lactic acid", "Tartaric acid"], "Citrus fruits contain citric acid; vinegar has acetic acid and curd lactic acid."],
    ["नींबू में मुख्य रूप से कौन-सा अम्ल पाया जाता है?", ["एसिटिक अम्ल", "साइट्रिक अम्ल", "लैक्टिक अम्ल", "टार्टरिक अम्ल"], "खट्टे फलों में साइट्रिक अम्ल होता है; सिरके में एसिटिक और दही में लैक्टिक अम्ल।"]),
  q(1, "general-studies", "general-science", "H", 0,
    ["Which mirror is used as a rear-view mirror in vehicles?", ["Convex", "Concave", "Plane", "Cylindrical"], "A convex mirror gives an erect, smaller image and a wider field of view."],
    ["वाहनों में पीछे देखने के लिए कौन-सा दर्पण लगाया जाता है?", ["उत्तल", "अवतल", "समतल", "बेलनाकार"], "उत्तल दर्पण सीधा, छोटा प्रतिबिंब और अधिक दृश्य-क्षेत्र देता है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["A diet lacking iodine leads to which disease?", ["Rickets", "Scurvy", "Goitre", "Night blindness"], "Iodine is needed for thyroid hormone; its lack enlarges the thyroid (goitre)."],
    ["आहार में आयोडीन की कमी से कौन-सा रोग होता है?", ["रिकेट्स", "स्कर्वी", "घेंघा", "रतौंधी"], "थायरॉइड हार्मोन के लिए आयोडीन ज़रूरी है; इसकी कमी से थायरॉइड बढ़ जाता है (घेंघा)।"]),
  q(1, "general-studies", "general-science", "H", 3,
    ["Which gas do green plants release during photosynthesis?", ["Carbon dioxide", "Nitrogen", "Hydrogen", "Oxygen"], "Photosynthesis splits water and releases oxygen."],
    ["प्रकाश-संश्लेषण के दौरान हरे पौधे कौन-सी गैस छोड़ते हैं?", ["कार्बन डाइऑक्साइड", "नाइट्रोजन", "हाइड्रोजन", "ऑक्सीजन"], "प्रकाश-संश्लेषण में जल टूटता है और ऑक्सीजन निकलती है।"]),
  q(1, "general-studies", "indian-economy", "M", 1,
    ["The headquarters of the Reserve Bank of India is in:", ["New Delhi", "Mumbai", "Kolkata", "Chennai"], "RBI moved its central office from Calcutta to Bombay in 1937."],
    ["भारतीय रिज़र्व बैंक का मुख्यालय कहाँ है?", ["नई दिल्ली", "मुंबई", "कोलकाता", "चेन्नई"], "RBI ने 1937 में अपना केंद्रीय कार्यालय कलकत्ता से बंबई स्थानांतरित किया।"]),
  q(1, "general-studies", "indian-economy", "H", 2,
    ["MGNREGA guarantees each rural household how many days of wage employment in a year?", ["50", "150", "100", "200"], "The 2005 Act guarantees 100 days of unskilled manual work per household per year."],
    ["मनरेगा प्रत्येक ग्रामीण परिवार को वर्ष में कितने दिनों के रोज़गार की गारंटी देता है?", ["50", "150", "100", "200"], "2005 का अधिनियम हर परिवार को वर्ष में 100 दिन के अकुशल शारीरिक काम की गारंटी देता है।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["The Union Budget is presented in Parliament by the:", ["Finance Minister", "Prime Minister", "RBI Governor", "President"], "The Finance Minister presents the Annual Financial Statement (Article 112) on behalf of the government."],
    ["संसद में केंद्रीय बजट कौन प्रस्तुत करता है?", ["वित्त मंत्री", "प्रधानमंत्री", "RBI गवर्नर", "राष्ट्रपति"], "वित्त मंत्री सरकार की ओर से वार्षिक वित्तीय विवरण (अनुच्छेद 112) प्रस्तुत करते हैं।"]),

  // ───────── Section 2: Reasoning (15) ─────────
  q(2, "reasoning", "series", "M", 2,
    ["Find the next number: 8, 15, 29, 57, 113, ?", ["217", "224", "225", "226"], "Each term is double the previous minus 1: 113 × 2 − 1 = 225."],
    ["अगली संख्या ज्ञात कीजिए: 8, 15, 29, 57, 113, ?", ["217", "224", "225", "226"], "हर पद पिछले का दोगुना − 1: 113 × 2 − 1 = 225।"], "113*2-1"),
  q(2, "reasoning", "series", "M", 1,
    ["Find the next number: 7, 14, 28, 56, ?", ["84", "112", "98", "120"], "Each term doubles: 56 × 2 = 112."],
    ["अगली संख्या ज्ञात कीजिए: 7, 14, 28, 56, ?", ["84", "112", "98", "120"], "हर पद दोगुना होता है: 56 × 2 = 112।"], "56*2"),
  q(2, "reasoning", "alphabet-test", "H", 3,
    ["Find the next letter: Y, W, T, P, K, ?", ["F", "D", "G", "E"], "Gaps grow backwards: −2, −3, −4, −5, −6. K (11) − 6 = E (5)."],
    ["अगला अक्षर ज्ञात कीजिए: Y, W, T, P, K, ?", ["F", "D", "G", "E"], "उल्टे क्रम में अंतर बढ़ता है: −2, −3, −4, −5, −6। K (11) − 6 = E (5)।"]),
  q(2, "reasoning", "coding-decoding", "M", 0,
    ["If SHIMLA is written as TIJNMB, how is MANDI written?", ["NBOEJ", "NBNEJ", "LZMCH", "NBOEI"], "Each letter moves one step forward: M→N, A→B, N→O, D→E, I→J."],
    ["यदि SHIMLA को TIJNMB लिखा जाता है, तो MANDI को कैसे लिखा जाएगा?", ["NBOEJ", "NBNEJ", "LZMCH", "NBOEI"], "हर अक्षर एक स्थान आगे: M→N, A→B, N→O, D→E, I→J।"]),
  q(2, "reasoning", "coding-decoding", "H", 2,
    ["If CAT is coded as 3120 by writing the position of each letter, how is DOG coded?", ["4157", "4156", "41577", "4167"], "D = 4, O = 15, G = 7, written together: 4157."],
    ["यदि हर अक्षर का स्थान लिखकर CAT को 3120 लिखा जाता है, तो DOG को कैसे लिखा जाएगा?", ["4157", "4156", "41577", "4167"], "D = 4, O = 15, G = 7, साथ लिखने पर 4157।"]),
  q(2, "reasoning", "blood-relations", "H", 1,
    ["Raju says, \"Sunita's father is the only son of my father.\" How is Raju related to Sunita?", ["Uncle", "Father", "Brother", "Grandfather"], "The only son of Raju's father is Raju himself, so Raju is Sunita's father."],
    ["राजू कहता है, \"सुनीता के पिता मेरे पिता के इकलौते बेटे हैं।\" राजू, सुनीता का क्या है?", ["चाचा", "पिता", "भाई", "दादा"], "राजू के पिता का इकलौता बेटा स्वयं राजू है, अतः राजू सुनीता का पिता है।"]),
  q(2, "reasoning", "blood-relations", "M", 3,
    ["P is the brother of Q. R is the father of P. S is the mother of R. How is Q related to S?", ["Son", "Daughter", "Nephew", "Grandchild (grandson or granddaughter)"], "S is R's mother and R is Q's father, so Q is S's grandchild; Q's gender is not given."],
    ["P, Q का भाई है। R, P का पिता है। S, R की माँ है। Q, S का क्या है?", ["बेटा", "बेटी", "भतीजा", "पोता या पोती"], "S, R की माँ है और R, Q का पिता है, अतः Q, S का पोता या पोती है; Q का लिंग नहीं दिया गया।"]),
  q(2, "reasoning", "direction-sense", "H", 0,
    ["From his house Amit walks 10 m south, turns left and walks 6 m, then turns left and walks 18 m. Where is he now from his house?", ["10 m north-east", "10 m south-east", "8 m north", "14 m north-west"], "Net 8 m north and 6 m east: √(8² + 6²) = 10 m towards the north-east."],
    ["अमित घर से 10 मी दक्षिण चलता है, बाएँ मुड़कर 6 मी, फिर बाएँ मुड़कर 18 मी चलता है। वह घर से कहाँ है?", ["10 मी उत्तर-पूर्व", "10 मी दक्षिण-पूर्व", "8 मी उत्तर", "14 मी उत्तर-पश्चिम"], "कुल 8 मी उत्तर और 6 मी पूर्व: √(8² + 6²) = 10 मी उत्तर-पूर्व की ओर।"]),
  q(2, "reasoning", "direction-sense", "H", 2,
    ["If south-east is called north and north-east is called west, what will west be called?", ["North-east", "South", "South-east", "North-west"], "Every direction turns 135° anticlockwise: west (270°) − 135° = 135°, i.e. south-east."],
    ["यदि दक्षिण-पूर्व को उत्तर और उत्तर-पूर्व को पश्चिम कहा जाए, तो पश्चिम को क्या कहा जाएगा?", ["उत्तर-पूर्व", "दक्षिण", "दक्षिण-पूर्व", "उत्तर-पश्चिम"], "हर दिशा 135° वामावर्त घूमती है: पश्चिम (270°) − 135° = 135°, अर्थात् दक्षिण-पूर्व।"]),
  q(2, "reasoning", "ranking", "M", 1,
    ["In a queue, Neha is 9th from the front and 14th from the back. How many people are in the queue?", ["23", "22", "21", "24"], "Total = 9 + 14 − 1 = 22."],
    ["एक कतार में नेहा आगे से 9वीं और पीछे से 14वीं है। कतार में कितने लोग हैं?", ["23", "22", "21", "24"], "कुल = 9 + 14 − 1 = 22।"], "9+14-1"),
  q(2, "reasoning", "analogy", "M", 3,
    ["Doctor : Stethoscope :: Carpenter : ?", ["Wood", "Furniture", "Nail", "Saw"], "A stethoscope is the doctor's tool; a saw is the carpenter's tool."],
    ["डॉक्टर : स्टेथोस्कोप :: बढ़ई : ?", ["लकड़ी", "फ़र्नीचर", "कील", "आरी"], "स्टेथोस्कोप डॉक्टर का औज़ार है; आरी बढ़ई का औज़ार है।"]),
  q(2, "reasoning", "odd-one-out", "M", 2,
    ["Find the odd number: 144, 169, 210, 196", ["144", "169", "210", "196"], "144, 169 and 196 are squares of 12, 13 and 14; 210 is not a perfect square."],
    ["विषम संख्या चुनिए: 144, 169, 210, 196", ["144", "169", "210", "196"], "144, 169 और 196 क्रमशः 12, 13 और 14 के वर्ग हैं; 210 पूर्ण वर्ग नहीं है।"]),
  q(2, "reasoning", "clock-calendar", "H", 0,
    ["How many times do the hour and minute hands of a clock coincide in a full day (24 hours)?", ["22", "24", "23", "48"], "They coincide 11 times every 12 hours (not between 11 and 1 separately), so 22 times a day."],
    ["पूरे दिन (24 घंटे) में घड़ी की घंटे और मिनट की सुइयाँ कितनी बार एक-दूसरे पर आती हैं?", ["22", "24", "23", "48"], "हर 12 घंटे में वे 11 बार मिलती हैं (11 और 1 के बीच केवल एक बार), अतः दिन में 22 बार।"]),
  q(2, "reasoning", "syllogism", "M", 2,
    ["Statements: All process servers are employees. All employees are paid. Conclusions: I. All process servers are paid. II. Some paid persons are process servers.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "Process servers ⊂ employees ⊂ paid persons, so both conclusions follow."],
    ["कथन: सभी प्रोसेस सर्वर कर्मचारी हैं। सभी कर्मचारी वेतनभोगी हैं। निष्कर्ष: I. सभी प्रोसेस सर्वर वेतनभोगी हैं। II. कुछ वेतनभोगी प्रोसेस सर्वर हैं।", ["केवल I निकलता है", "केवल II निकलता है", "I और II दोनों निकलते हैं", "न I न II निकलता है"], "प्रोसेस सर्वर ⊂ कर्मचारी ⊂ वेतनभोगी, अतः दोनों निष्कर्ष निकलते हैं।"]),
  q(2, "reasoning", "math-operations", "H", 1,
    ["If 1 * 2 = 5 and 2 * 3 = 13, then 3 * 5 = ?", ["30", "34", "15", "36"], "a * b = a² + b²: 3² + 5² = 9 + 25 = 34."],
    ["यदि 1 * 2 = 5 और 2 * 3 = 13 है, तो 3 * 5 = ?", ["30", "34", "15", "36"], "a * b = a² + b²: 3² + 5² = 9 + 25 = 34।"], "9+25"),

  // ───────── Section 3: Mathematics (15) ─────────
  q(3, "quant", "percentage", "M", 3,
    ["What is 15% of 480?", ["62", "68", "75", "72"], "15% of 480 = 0.15 × 480 = 72."],
    ["480 का 15% कितना है?", ["62", "68", "75", "72"], "480 का 15% = 0.15 × 480 = 72।"], "0.15*480"),
  q(3, "quant", "interest", "M", 0,
    ["Find the simple interest on ₹5,000 at 8% per annum for 3 years.", ["₹1,200", "₹1,000", "₹1,500", "₹800"], "SI = P × R × T ÷ 100 = 5000 × 8 × 3 ÷ 100 = ₹1,200."],
    ["₹5,000 पर 8% वार्षिक दर से 3 वर्ष का साधारण ब्याज ज्ञात कीजिए।", ["₹1,200", "₹1,000", "₹1,500", "₹800"], "साधारण ब्याज = P × R × T ÷ 100 = 5000 × 8 × 3 ÷ 100 = ₹1,200।"], "5000*8*3/100"),
  q(3, "quant", "average", "E", 2,
    ["Find the average of 12, 15, 18, 21 and 24.", ["17", "19", "18", "20"], "Sum = 90; 90 ÷ 5 = 18."],
    ["12, 15, 18, 21 और 24 का औसत ज्ञात कीजिए।", ["17", "19", "18", "20"], "योग = 90; 90 ÷ 5 = 18।"], "(12+15+18+21+24)/5"),
  q(3, "quant", "percentage", "M", 1,
    ["The price of an item rises from ₹250 to ₹300. What is the percentage increase?", ["16%", "20%", "25%", "50%"], "Increase = 50; 50 ÷ 250 × 100 = 20%."],
    ["एक वस्तु का मूल्य ₹250 से बढ़कर ₹300 हो जाता है। प्रतिशत वृद्धि कितनी है?", ["16%", "20%", "25%", "50%"], "वृद्धि = 50; 50 ÷ 250 × 100 = 20%।"], "50/250*100"),
  q(3, "quant", "time-work", "H", 3,
    ["A can finish a work in 12 days and B in 18 days. In how many days will they finish it together?", ["15 days", "6 days", "8 days", "7.2 days"], "Together = 12 × 18 ÷ (12 + 18) = 216 ÷ 30 = 7.2 days."],
    ["A एक काम 12 दिन में और B 18 दिन में पूरा करता है। दोनों मिलकर कितने दिन में पूरा करेंगे?", ["15 दिन", "6 दिन", "8 दिन", "7.2 दिन"], "मिलकर = 12 × 18 ÷ (12 + 18) = 216 ÷ 30 = 7.2 दिन।"], "12*18/30"),
  q(3, "quant", "speed-distance", "H", 0,
    ["A train 180 m long runs at 54 km/h. In how many seconds will it pass a pole?", ["12", "10", "15", "18"], "54 km/h = 15 m/s; time = 180 ÷ 15 = 12 seconds."],
    ["180 मी लंबी ट्रेन 54 किमी/घंटा की गति से चल रही है। वह एक खंभे को कितने सेकंड में पार करेगी?", ["12", "10", "15", "18"], "54 किमी/घंटा = 15 मी/से; समय = 180 ÷ 15 = 12 सेकंड।"], "180/(54*5/18)"),
  q(3, "quant", "ratio-proportion", "M", 2,
    ["Two numbers are in the ratio 3 : 5 and their sum is 96. The larger number is:", ["36", "56", "60", "64"], "Larger = 96 × 5 ÷ 8 = 60."],
    ["दो संख्याओं का अनुपात 3 : 5 है और उनका योग 96 है। बड़ी संख्या है:", ["36", "56", "60", "64"], "बड़ी संख्या = 96 × 5 ÷ 8 = 60।"], "96*5/8"),
  q(3, "quant", "profit-loss", "M", 1,
    ["An article bought for ₹400 is sold for ₹460. What is the profit percentage?", ["12%", "15%", "18%", "20%"], "Profit = 60; 60 ÷ 400 × 100 = 15%."],
    ["₹400 में ख़रीदी गई वस्तु ₹460 में बेची जाती है। लाभ प्रतिशत क्या है?", ["12%", "15%", "18%", "20%"], "लाभ = 60; 60 ÷ 400 × 100 = 15%।"], "60/400*100"),
  q(3, "quant", "hcf-lcm", "M", 0,
    ["Find the LCM of 12, 18 and 30.", ["180", "90", "360", "120"], "12 = 2²·3, 18 = 2·3², 30 = 2·3·5; LCM = 2²·3²·5 = 180."],
    ["12, 18 और 30 का लघुत्तम समापवर्त्य (LCM) ज्ञात कीजिए।", ["180", "90", "360", "120"], "12 = 2²·3, 18 = 2·3², 30 = 2·3·5; LCM = 2²·3²·5 = 180।"], "180"),
  q(3, "quant", "hcf-lcm", "H", 3,
    ["Find the HCF of 84 and 126.", ["14", "21", "28", "42"], "84 = 2²·3·7, 126 = 2·3²·7; HCF = 2·3·7 = 42."],
    ["84 और 126 का महत्तम समापवर्तक (HCF) ज्ञात कीजिए।", ["14", "21", "28", "42"], "84 = 2²·3·7, 126 = 2·3²·7; HCF = 2·3·7 = 42।"], "42"),
  q(3, "quant", "simplification", "M", 2,
    ["Simplify: 48 ÷ 6 × 3 + 7 − 5", ["10", "24", "26", "28"], "By BODMAS: 48 ÷ 6 = 8; 8 × 3 = 24; 24 + 7 − 5 = 26."],
    ["सरल कीजिए: 48 ÷ 6 × 3 + 7 − 5", ["10", "24", "26", "28"], "BODMAS से: 48 ÷ 6 = 8; 8 × 3 = 24; 24 + 7 − 5 = 26।"], "48/6*3+7-5"),
  q(3, "quant", "mensuration", "M", 1,
    ["A rectangular courtroom floor is 24 m long and 15 m wide. Its area is:", ["78 sq m", "360 sq m", "340 sq m", "390 sq m"], "Area = 24 × 15 = 360 sq m."],
    ["एक आयताकार कोर्ट-कक्ष का फ़र्श 24 मी लंबा और 15 मी चौड़ा है। उसका क्षेत्रफल है:", ["78 वर्ग मी", "360 वर्ग मी", "340 वर्ग मी", "390 वर्ग मी"], "क्षेत्रफल = 24 × 15 = 360 वर्ग मी।"], "24*15"),
  q(3, "quant", "interest", "H", 0,
    ["Find the compound interest on ₹10,000 at 10% per annum for 2 years, compounded yearly.", ["₹2,100", "₹2,000", "₹2,200", "₹1,100"], "Amount = 10000 × 1.1² = ₹12,100; CI = ₹2,100."],
    ["₹10,000 पर 10% वार्षिक चक्रवृद्धि दर से 2 वर्ष का चक्रवृद्धि ब्याज ज्ञात कीजिए।", ["₹2,100", "₹2,000", "₹2,200", "₹1,100"], "मिश्रधन = 10000 × 1.1² = ₹12,100; चक्रवृद्धि ब्याज = ₹2,100।"], "10000*1.1*1.1-10000"),
  q(3, "quant", "ages", "H", 2,
    ["A father is three times as old as his son. After 12 years he will be twice as old as the son. What is the son's present age?", ["10 years", "15 years", "12 years", "18 years"], "3s + 12 = 2(s + 12) gives s = 12."],
    ["पिता की आयु पुत्र की तीन गुनी है। 12 वर्ष बाद वह पुत्र की दोगुनी होगी। पुत्र की वर्तमान आयु क्या है?", ["10 वर्ष", "15 वर्ष", "12 वर्ष", "18 वर्ष"], "3s + 12 = 2(s + 12) से s = 12।"], "12"),
  q(3, "quant", "percentage", "H", 1,
    ["A number is increased by 25% and the result is decreased by 20%. The net change is:", ["5% increase", "No change", "5% decrease", "2% decrease"], "1.25 × 0.8 = 1, so the number is unchanged."],
    ["किसी संख्या में 25% वृद्धि करके परिणाम में 20% कमी की जाती है। कुल परिवर्तन है:", ["5% वृद्धि", "कोई परिवर्तन नहीं", "5% कमी", "2% कमी"], "1.25 × 0.8 = 1, अतः संख्या वैसी ही रहती है।"]),

  // ───────── Section 4: Hindi & English (15) ─────────
  q(4, "hindi", "sandhi-samas", "M", 0,
    ["Pick the correct sandhi split of the Hindi word 'विद्यालय':", ["विद्या + आलय", "विद्य + आलय", "विद्या + लय", "विद + यालय"], "विद्या + आलय = विद्यालय (आ + आ = आ, dirgh sandhi)."],
    ["'विद्यालय' का सही संधि-विच्छेद चुनिए:", ["विद्या + आलय", "विद्य + आलय", "विद्या + लय", "विद + यालय"], "विद्या + आलय = विद्यालय (आ + आ = आ, दीर्घ संधि)।"]),
  q(4, "hindi", "sandhi-samas", "M", 2,
    ["Which samas is in the Hindi word 'राजपुत्र'?", ["Dvandva", "Dvigu", "Tatpurush", "Bahuvrihi"], "राजा का पुत्र — the case ending का is dropped, so tatpurush."],
    ["'राजपुत्र' में कौन-सा समास है?", ["द्वंद्व", "द्विगु", "तत्पुरुष", "बहुव्रीहि"], "राजा का पुत्र — 'का' विभक्ति का लोप, अतः तत्पुरुष।"]),
  q(4, "hindi", "paryay-vilom", "M", 1,
    ["Pick a synonym of the Hindi word 'पृथ्वी':", ["अंबर", "वसुधा", "सलिल", "अनिल"], "वसुधा, धरा and भूमि mean earth; अंबर is sky, सलिल water, अनिल air."],
    ["'पृथ्वी' का पर्यायवाची शब्द चुनिए:", ["अंबर", "वसुधा", "सलिल", "अनिल"], "वसुधा, धरा और भूमि पृथ्वी के पर्याय हैं; अंबर आकाश, सलिल जल और अनिल वायु है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Pick the opposite (vilom) of the Hindi word 'आदान':", ["आगमन", "अर्जन", "ग्रहण", "प्रदान"], "आदान (taking) is opposite to प्रदान (giving)."],
    ["'आदान' का विलोम शब्द चुनिए:", ["आगमन", "अर्जन", "ग्रहण", "प्रदान"], "आदान (लेना) का विलोम प्रदान (देना) है।"]),
  q(4, "hindi", "muhavare", "H", 0,
    ["What does the Hindi muhavara 'हाथ पीले करना' mean?", ["विवाह करना", "रंग लगाना", "कंजूसी करना", "बीमार होना"], "It means to marry off (a daughter)."],
    ["मुहावरे 'हाथ पीले करना' का अर्थ है:", ["विवाह करना", "रंग लगाना", "कंजूसी करना", "बीमार होना"], "इसका अर्थ (बेटी का) विवाह करना है।"]),
  q(4, "hindi", "ek-shabd", "M", 2,
    ["Give one Hindi word for 'जो दिखाई न दे':", ["अगोचर", "अदृष्ट", "अदृश्य", "अलक्षित"], "अदृश्य means invisible, that which cannot be seen."],
    ["'जो दिखाई न दे' के लिए एक शब्द:", ["अगोचर", "अदृष्ट", "अदृश्य", "अलक्षित"], "अदृश्य का अर्थ है जो दिखाई न दे।"]),
  q(4, "hindi", "shuddh-vartani", "H", 1,
    ["Which is the correct spelling of the Hindi word meaning 'too much, excessive'?", ["अत्याधिक", "अत्यधिक", "अतिअधिक", "अत्यधीक"], "अति + अधिक = अत्यधिक (yan sandhi); अत्याधिक is a common error."],
    ["'बहुत अधिक' के अर्थ वाले शब्द की शुद्ध वर्तनी कौन-सी है?", ["अत्याधिक", "अत्यधिक", "अतिअधिक", "अत्यधीक"], "अति + अधिक = अत्यधिक (यण संधि); 'अत्याधिक' सामान्य भूल है।"]),
  q(4, "hindi", "alankar-ras", "H", 3,
    ["Which alankar is in the line 'पीपर पात सरिस मन डोला'?", ["Rupak", "Yamak", "Shlesh", "Upma"], "The mind is compared to a peepal leaf using the comparison word सरिस (like) — upma."],
    ["'पीपर पात सरिस मन डोला' में कौन-सा अलंकार है?", ["रूपक", "यमक", "श्लेष", "उपमा"], "मन की तुलना पीपल के पत्ते से वाचक शब्द 'सरिस' (समान) द्वारा की गई है — उपमा अलंकार।"]),
  q(4, "english", "grammar", "H", 1,
    ["Choose the correct verb: 'The jury ___ divided in their opinions.'", ["is", "were", "was", "has"], "When members of a collective noun act individually ('their opinions'), the verb is plural."],
    ["सही क्रिया चुनिए: 'The jury ___ divided in their opinions.'", ["is", "were", "was", "has"], "जब समूहवाचक संज्ञा के सदस्य अलग-अलग कार्य करें ('their opinions'), तो बहुवचन क्रिया आती है।"]),
  q(4, "english", "synonyms-antonyms", "M", 2,
    ["Pick the word similar in meaning to 'SUMMON':", ["Dismiss", "Release", "Call", "Ignore"], "To summon is to officially call someone to appear."],
    ["'SUMMON' के समान अर्थ वाला शब्द चुनिए:", ["Dismiss", "Release", "Call", "Ignore"], "Summon का अर्थ किसी को उपस्थित होने के लिए आधिकारिक रूप से बुलाना है।"]),
  q(4, "english", "synonyms-antonyms", "M", 0,
    ["Pick the word opposite in meaning to 'GUILTY':", ["Innocent", "Accused", "Criminal", "Wrong"], "Guilty means responsible for an offence; innocent is the opposite."],
    ["'GUILTY' के विपरीत अर्थ वाला शब्द चुनिए:", ["Innocent", "Accused", "Criminal", "Wrong"], "Guilty का अर्थ अपराध का दोषी; इसका विलोम innocent है।"]),
  q(4, "english", "grammar", "H", 3,
    ["Fill in the blank: 'He was charged ___ theft.'", ["of", "for", "on", "with"], "The fixed phrase is 'charged with' an offence."],
    ["रिक्त स्थान भरिए: 'He was charged ___ theft.'", ["of", "for", "on", "with"], "निश्चित प्रयोग 'charged with' (किसी अपराध का आरोप) है।"]),
  q(4, "english", "one-word", "M", 1,
    ["Give one word for 'a person who travels on foot':", ["Passenger", "Pedestrian", "Pilgrim", "Tourist"], "A pedestrian is a person walking, especially on a road."],
    ["'पैदल चलने वाला व्यक्ति' के लिए एक शब्द:", ["Passenger", "Pedestrian", "Pilgrim", "Tourist"], "Pedestrian सड़क पर पैदल चलने वाला व्यक्ति है।"]),
  q(4, "english", "idioms", "M", 2,
    ["What does the idiom 'to beat about the bush' mean?", ["To work in a field", "To hit someone", "To avoid coming to the main point", "To search carefully"], "It means talking around a subject without getting to the point."],
    ["मुहावरे 'to beat about the bush' का अर्थ है:", ["To work in a field", "To hit someone", "To avoid coming to the main point", "To search carefully"], "इसका अर्थ मुख्य बात पर न आकर इधर-उधर की बातें करना है।"]),
  q(4, "english", "voice-speech", "H", 0,
    ["Choose the passive form of 'Who wrote this letter?'", ["By whom was this letter written?", "Who was this letter written?", "By whom this letter was written?", "Whom was this letter written by him?"], "'Who' becomes 'By whom' and the question keeps the auxiliary before the subject."],
    ["'Who wrote this letter?' का कर्मवाच्य रूप चुनिए:", ["By whom was this letter written?", "Who was this letter written?", "By whom this letter was written?", "Whom was this letter written by him?"], "'Who' का 'By whom' हो जाता है और प्रश्न में सहायक क्रिया कर्ता से पहले रहती है।"]),
];
