// HP High Court Stenographer — Full Mock 4, written fresh: English 20, Hindi 15, General Knowledge & Himachal GK 30,
// Reasoning 15, Computer 20.

import { q, type PatwariQuestion } from "../patwari/types";

export const stenoMock4: PatwariQuestion[] = [
  // ───────── Section 0: English (20) ─────────
  q(0, "english", "grammar", "H", 1,
    ["Choose the correct verb: 'Bread and butter ___ his usual breakfast.'", ["are", "is", "were", "have been"], "Two nouns forming a single idea take a singular verb."],
    ["सही क्रिया चुनिए: 'Bread and butter ___ his usual breakfast.'", ["are", "is", "were", "have been"], "एक ही भाव बनाने वाली दो संज्ञाओं के साथ एकवचन क्रिया आती है।"]),
  q(0, "english", "grammar", "M", 2,
    ["Choose the correct tense: 'I ___ this judgment since 10 a.m.'", ["am typing", "typed", "have been typing", "was typing"], "An action begun in the past and still going on, with 'since', takes the present perfect continuous."],
    ["सही काल चुनिए: 'I ___ this judgment since 10 a.m.'", ["am typing", "typed", "have been typing", "was typing"], "'Since' के साथ भूतकाल में शुरू होकर अब तक जारी क्रिया के लिए present perfect continuous आता है।"]),
  q(0, "english", "grammar", "M", 0,
    ["Fill in the blank: 'The decree was passed ___ the consent of both parties.'", ["with", "by", "for", "on"], "'With the consent of' is the fixed expression."],
    ["रिक्त स्थान भरिए: 'The decree was passed ___ the consent of both parties.'", ["with", "by", "for", "on"], "'With the consent of' निश्चित प्रयोग है।"]),
  q(0, "english", "grammar", "H", 3,
    ["Fill in the blank: 'He has been accused ___ forgery.'", ["for", "with", "on", "of"], "'Accused of' (but 'charged with') an offence."],
    ["रिक्त स्थान भरिए: 'He has been accused ___ forgery.'", ["for", "with", "on", "of"], "किसी अपराध के लिए 'accused of' (पर 'charged with') आता है।"]),
  q(0, "english", "grammar", "H", 2,
    ["Choose the correct pronoun: 'Between you and ___, the hearing will be adjourned.'", ["I", "myself", "me", "mine"], "A preposition ('between') takes the object pronoun 'me'."],
    ["सही सर्वनाम चुनिए: 'Between you and ___, the hearing will be adjourned.'", ["I", "myself", "me", "mine"], "पूर्वसर्ग ('between') के बाद कर्म रूप 'me' आता है।"]),
  q(0, "english", "grammar", "H", 0,
    ["Choose the correct order: 'Hardly ever ___ late to the office.'", ["does he come", "he comes", "he does come", "comes he"], "A negative adverb at the start of a sentence causes inversion: 'does he come'."],
    ["सही क्रम चुनिए: 'Hardly ever ___ late to the office.'", ["does he come", "he comes", "he does come", "comes he"], "वाक्य के आरंभ में नकारात्मक क्रियाविशेषण आने पर उलटा क्रम होता है: 'does he come'।"]),
  q(0, "english", "error-spotting", "M", 1,
    ["Find the part with an error in: 'Each of the files (A) / have been (B) / signed by (C) / the Registrar. (D)'", ["Each of the files", "have been", "signed by", "the Registrar"], "'Each of' takes a singular verb: 'has been'."],
    ["इस वाक्य में त्रुटि वाला भाग चुनिए: 'Each of the files (A) / have been (B) / signed by (C) / the Registrar. (D)'", ["Each of the files", "have been", "signed by", "the Registrar"], "'Each of' के साथ एकवचन क्रिया आती है: 'has been'।"]),
  q(0, "english", "error-spotting", "H", 2,
    ["Find the part with an error in: 'He did not (A) / know where (B) / was the court (C) / located. (D)'", ["He did not", "know where", "was the court", "located"], "An indirect question keeps statement order: 'where the court was located'."],
    ["इस वाक्य में त्रुटि वाला भाग चुनिए: 'He did not (A) / know where (B) / was the court (C) / located. (D)'", ["He did not", "know where", "was the court", "located"], "अप्रत्यक्ष प्रश्न में कथन वाला क्रम रहता है: 'where the court was located'।"]),
  q(0, "english", "vocabulary", "H", 3,
    ["Pick the word or phrase closest in meaning to 'VERBATIM':", ["In summary", "Roughly", "In translation", "Word for word"], "Verbatim means in exactly the same words."],
    ["'VERBATIM' के सबसे निकट अर्थ वाला शब्द चुनिए:", ["In summary", "Roughly", "In translation", "Word for word"], "Verbatim का अर्थ है ठीक उन्हीं शब्दों में, शब्दशः।"]),
  q(0, "english", "vocabulary", "M", 0,
    ["Pick the word similar in meaning to 'BREVITY':", ["Shortness", "Courage", "Length", "Clarity"], "Brevity means using few words."],
    ["'BREVITY' के समान अर्थ वाला शब्द चुनिए:", ["Shortness", "Courage", "Length", "Clarity"], "Brevity का अर्थ है संक्षिप्तता।"]),
  q(0, "english", "synonyms-antonyms", "M", 2,
    ["Pick the word opposite in meaning to 'EXPAND':", ["Enlarge", "Extend", "Contract", "Spread"], "Expand means to grow larger; contract means to shrink."],
    ["'EXPAND' के विपरीत अर्थ वाला शब्द चुनिए:", ["Enlarge", "Extend", "Contract", "Spread"], "Expand का अर्थ फैलना; contract का अर्थ सिकुड़ना।"]),
  q(0, "english", "synonyms-antonyms", "M", 1,
    ["Pick the word opposite in meaning to 'OPTIMIST':", ["Realist", "Pessimist", "Idealist", "Activist"], "An optimist expects the best; a pessimist expects the worst."],
    ["'OPTIMIST' के विपरीत अर्थ वाला शब्द चुनिए:", ["Realist", "Pessimist", "Idealist", "Activist"], "Optimist आशावादी; pessimist निराशावादी।"]),
  q(0, "english", "one-word", "M", 3,
    ["Give one word for 'a sudden rush of frightened people or animals':", ["Riot", "Rally", "Procession", "Stampede"], "A stampede is a panicked rush of a crowd."],
    ["'डरे हुए लोगों या पशुओं की अचानक भगदड़' के लिए एक शब्द:", ["Riot", "Rally", "Procession", "Stampede"], "Stampede भीड़ की घबराई हुई भगदड़ है।"]),
  q(0, "english", "one-word", "M", 0,
    ["Give one word for 'a list of items to be taken up at a meeting':", ["Agenda", "Minutes", "Memo", "Circular"], "The agenda lists the business of a meeting; minutes record what happened."],
    ["'बैठक में उठाए जाने वाले विषयों की सूची' के लिए एक शब्द:", ["Agenda", "Minutes", "Memo", "Circular"], "Agenda बैठक के कार्यों की सूची है; minutes उसमें हुई बातों का अभिलेख।"]),
  q(0, "english", "one-word", "H", 2,
    ["Give one word for 'handwriting that cannot be read':", ["Eligible", "Legible", "Illegible", "Ineligible"], "Illegible means not clear enough to be read; eligible means qualified."],
    ["'जो लिखावट पढ़ी न जा सके' के लिए एक शब्द:", ["Eligible", "Legible", "Illegible", "Ineligible"], "Illegible का अर्थ पढ़ने योग्य न होना; eligible का अर्थ पात्र।"]),
  q(0, "english", "idioms", "M", 1,
    ["The idiom 'to keep one's fingers crossed' means:", ["To pray in a temple", "To hope for a good result", "To refuse help", "To count money"], "It means to hope that things turn out well."],
    ["मुहावरे 'to keep one's fingers crossed' का अर्थ है:", ["To pray in a temple", "To hope for a good result", "To refuse help", "To count money"], "इसका अर्थ अच्छे परिणाम की आशा करना है।"]),
  q(0, "english", "idioms", "M", 3,
    ["The idiom 'at the eleventh hour' means:", ["At 11 o'clock", "Very early", "On time", "At the last possible moment"], "It means just before it is too late."],
    ["मुहावरे 'at the eleventh hour' का अर्थ है:", ["At 11 o'clock", "Very early", "On time", "At the last possible moment"], "इसका अर्थ अंतिम क्षण में, बिल्कुल देर होने से पहले है।"]),
  q(0, "english", "voice-speech", "H", 2,
    ["Choose the passive form of the request 'Please close the door.'", ["The door is closed.", "The door was closed by you.", "You are requested to close the door.", "Close the door, please be."], "A polite imperative becomes 'You are requested to …' in the passive."],
    ["अनुरोध 'Please close the door.' का कर्मवाच्य रूप चुनिए:", ["The door is closed.", "The door was closed by you.", "You are requested to close the door.", "Close the door, please be."], "विनम्र आज्ञार्थक वाक्य का कर्मवाच्य 'You are requested to …' होता है।"]),
  q(0, "english", "voice-speech", "H", 0,
    ["Choose the indirect speech: The judge said, \"Silence in the court!\"", ["The judge ordered silence in the court.", "The judge said silence in the court.", "The judge told that silence in the court.", "The judge asked that is there silence in the court."], "An exclamatory command is reported with a verb like 'ordered'."],
    ["अप्रत्यक्ष कथन चुनिए: The judge said, \"Silence in the court!\"", ["The judge ordered silence in the court.", "The judge said silence in the court.", "The judge told that silence in the court.", "The judge asked that is there silence in the court."], "विस्मयादिबोधक आदेश को 'ordered' जैसी क्रिया से बताया जाता है।"]),
  q(0, "english", "spelling", "M", 0,
    ["Choose the correct spelling of the word meaning 'a person in charge of a library':", ["Librarian", "Liberarian", "Librarien", "Libririan"], "The correct spelling is 'librarian'."],
    ["'पुस्तकालय का प्रभारी व्यक्ति' अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Librarian", "Liberarian", "Librarien", "Libririan"], "सही वर्तनी 'librarian' है।"]),

  // ───────── Section 1: Hindi (15) ─────────
  q(1, "hindi", "sandhi-samas", "M", 1,
    ["Pick the correct sandhi split of the Hindi word 'गणेश':", ["गणे + श", "गण + ईश", "ग + णेश", "गण + एश"], "अ + ई = ए: गण + ईश = गणेश (gun sandhi)."],
    ["'गणेश' का सही संधि-विच्छेद चुनिए:", ["गणे + श", "गण + ईश", "ग + णेश", "गण + एश"], "अ + ई = ए: गण + ईश = गणेश (गुण संधि)।"]),
  q(1, "hindi", "sandhi-samas", "M", 2,
    ["Pick the correct sandhi split of the Hindi word 'परोपकार':", ["परो + पकार", "पर + ओपकार", "पर + उपकार", "परा + उपकार"], "अ + उ = ओ: पर + उपकार = परोपकार (gun sandhi)."],
    ["'परोपकार' का सही संधि-विच्छेद चुनिए:", ["परो + पकार", "पर + ओपकार", "पर + उपकार", "परा + उपकार"], "अ + उ = ओ: पर + उपकार = परोपकार (गुण संधि)।"]),
  q(1, "hindi", "sandhi-samas", "H", 0,
    ["Pick the correct sandhi split of the Hindi word 'सज्जन':", ["सत् + जन", "सज् + जन", "स + ज्जन", "सद् + जन"], "सत् + जन: त् becomes ज् before ज — vyanjan sandhi."],
    ["'सज्जन' का सही संधि-विच्छेद चुनिए:", ["सत् + जन", "सज् + जन", "स + ज्जन", "सद् + जन"], "सत् + जन: ज से पहले त् का ज् — व्यंजन संधि।"]),
  q(1, "hindi", "sandhi-samas", "H", 3,
    ["Which samas is in the Hindi word 'घुड़सवार'?", ["Dvandva", "Dvigu", "Bahuvrihi", "Tatpurush"], "घोड़े पर सवार — the case ending is dropped, so tatpurush."],
    ["'घुड़सवार' में कौन-सा समास है?", ["द्वंद्व", "द्विगु", "बहुव्रीहि", "तत्पुरुष"], "घोड़े पर सवार — विभक्ति का लोप, अतः तत्पुरुष।"]),
  q(1, "hindi", "sandhi-samas", "M", 1,
    ["Which samas is in the Hindi word 'प्रतिदिन'?", ["Dvigu", "Avyayibhav", "Karmadharaya", "Tatpurush"], "प्रति (an indeclinable) + दिन — avyayibhav."],
    ["'प्रतिदिन' में कौन-सा समास है?", ["द्विगु", "अव्ययीभाव", "कर्मधारय", "तत्पुरुष"], "प्रति (अव्यय) + दिन — अव्ययीभाव।"]),
  q(1, "hindi", "paryay-vilom", "M", 0,
    ["Pick a synonym of the Hindi word 'पवन':", ["समीर", "सलिल", "सरोज", "सविता"], "समीर, अनिल and वायु mean wind; सलिल is water, सरोज lotus, सविता sun."],
    ["'पवन' का पर्यायवाची शब्द चुनिए:", ["समीर", "सलिल", "सरोज", "सविता"], "समीर, अनिल और वायु पवन के पर्याय हैं; सलिल जल, सरोज कमल और सविता सूर्य है।"]),
  q(1, "hindi", "paryay-vilom", "M", 3,
    ["Pick a synonym of the Hindi word 'चंद्रमा':", ["दिनेश", "दिवाकर", "प्रभाकर", "शशि"], "शशि, इंदु and राकेश mean moon; the others mean sun."],
    ["'चंद्रमा' का पर्यायवाची शब्द चुनिए:", ["दिनेश", "दिवाकर", "प्रभाकर", "शशि"], "शशि, इंदु और राकेश चंद्रमा के पर्याय हैं; बाकी सूर्य के।"]),
  q(1, "hindi", "paryay-vilom", "M", 2,
    ["Pick the opposite (vilom) of the Hindi word 'आदर':", ["सम्मान", "प्रतिष्ठा", "अनादर", "मान"], "आदर (respect) is opposite to अनादर (disrespect)."],
    ["'आदर' का विलोम शब्द चुनिए:", ["सम्मान", "प्रतिष्ठा", "अनादर", "मान"], "आदर का विलोम अनादर है।"]),
  q(1, "hindi", "paryay-vilom", "M", 1,
    ["Pick the opposite (vilom) of the Hindi word 'सरस':", ["मधुर", "नीरस", "रसीला", "सुंदर"], "सरस (full of flavour/interest) is opposite to नीरस (dull)."],
    ["'सरस' का विलोम शब्द चुनिए:", ["मधुर", "नीरस", "रसीला", "सुंदर"], "सरस का विलोम नीरस है।"]),
  q(1, "hindi", "muhavare", "M", 0,
    ["What does the Hindi muhavara 'पानी-पानी होना' mean?", ["बहुत लज्जित होना", "बहुत ठंडा होना", "डूब जाना", "बहुत प्यास लगना"], "It means to feel deeply ashamed."],
    ["मुहावरे 'पानी-पानी होना' का अर्थ है:", ["बहुत लज्जित होना", "बहुत ठंडा होना", "डूब जाना", "बहुत प्यास लगना"], "इसका अर्थ बहुत लज्जित होना है।"]),
  q(1, "hindi", "muhavare", "H", 3,
    ["What does the Hindi muhavara 'आँखें चुराना' mean?", ["चोरी करना", "आँखें बंद करना", "ध्यान से देखना", "सामने आने से कतराना"], "It means to avoid facing someone, usually out of guilt."],
    ["मुहावरे 'आँखें चुराना' का अर्थ है:", ["चोरी करना", "आँखें बंद करना", "ध्यान से देखना", "सामने आने से कतराना"], "इसका अर्थ (प्रायः अपराध-बोध से) किसी के सामने आने से बचना है।"]),
  q(1, "hindi", "ek-shabd", "E", 2,
    ["Give one Hindi word for 'जो कभी न मरे':", ["अजर", "अजेय", "अमर", "अनंत"], "अमर means immortal; अजर means ageless."],
    ["'जो कभी न मरे' के लिए एक शब्द:", ["अजर", "अजेय", "अमर", "अनंत"], "अमर का अर्थ जो कभी न मरे; अजर का अर्थ जो बूढ़ा न हो।"]),
  q(1, "hindi", "ek-shabd", "H", 0,
    ["Give one Hindi word for 'जो सबको समान दृष्टि से देखे':", ["समदर्शी", "दूरदर्शी", "सर्वज्ञ", "निष्पक्ष"], "समदर्शी looks on all with an equal eye; दूरदर्शी is far-sighted."],
    ["'जो सबको समान दृष्टि से देखे' के लिए एक शब्द:", ["समदर्शी", "दूरदर्शी", "सर्वज्ञ", "निष्पक्ष"], "समदर्शी सबको समान दृष्टि से देखता है; दूरदर्शी आगे की सोचता है।"]),
  q(1, "hindi", "shuddh-vartani", "H", 1,
    ["Which is the correct spelling of the Hindi word meaning 'ascetic, monk'?", ["सन्यासी", "संन्यासी", "सन्न्यासी", "संनयासी"], "सम् + न्यास gives संन्यास, so संन्यासी."],
    ["'साधु, वैरागी' अर्थ वाले शब्द की शुद्ध वर्तनी कौन-सी है?", ["सन्यासी", "संन्यासी", "सन्न्यासी", "संनयासी"], "सम् + न्यास से संन्यास बनता है, अतः संन्यासी।"]),
  q(1, "hindi", "vyakaran", "M", 3,
    ["In 'वह पुस्तक पढ़ता है', what part of speech is 'वह'?", ["Sangya", "Visheshan", "Kriya", "Sarvanam"], "वह stands in place of a noun, so it is a sarvanam (pronoun)."],
    ["'वह पुस्तक पढ़ता है' में 'वह' कौन-सा शब्द-भेद है?", ["संज्ञा", "विशेषण", "क्रिया", "सर्वनाम"], "'वह' संज्ञा के स्थान पर आया है, अतः सर्वनाम है।"]),

  // ───────── Section 2: General Knowledge & Himachal GK (30) ─────────
  q(2, "hp-gk", "geography", "M", 1,
    ["Bir Billing, venue of the Paragliding World Cup, is in which district?", ["Kullu", "Kangra", "Mandi", "Chamba"], "Bir (landing) and Billing (take-off) are in Kangra district."],
    ["पैराग्लाइडिंग विश्व कप स्थल बीड़ बिलिंग किस ज़िले में है?", ["कुल्लू", "कांगड़ा", "मंडी", "चंबा"], "बीड़ (लैंडिंग) और बिलिंग (टेक-ऑफ़) कांगड़ा ज़िले में हैं।"]),
  q(2, "hp-gk", "geography", "H", 3,
    ["The Baralacha La pass on the Manali–Leh road links Lahaul with:", ["Spiti", "Kinnaur", "Kullu", "Ladakh"], "Baralacha La connects Lahaul with the Zanskar–Leh side of Ladakh."],
    ["मनाली–लेह मार्ग पर बारालाचा ला दर्रा लाहौल को किससे जोड़ता है?", ["स्पीति", "किन्नौर", "कुल्लू", "लद्दाख"], "बारालाचा ला लाहौल को लद्दाख के ज़ांस्कर–लेह की ओर से जोड़ता है।"]),
  q(2, "hp-gk", "rivers-lakes", "M", 0,
    ["The Pong Dam wetland, which hosts thousands of migratory birds every winter, is in:", ["Kangra", "Bilaspur", "Una", "Hamirpur"], "Pong Dam Lake Wildlife Sanctuary is in Kangra district."],
    ["हर सर्दी हज़ारों प्रवासी पक्षियों का ठिकाना पौंग बाँध आर्द्रभूमि कहाँ है?", ["कांगड़ा", "बिलासपुर", "ऊना", "हमीरपुर"], "पौंग बाँध झील वन्यजीव अभयारण्य कांगड़ा ज़िले में है।"]),
  q(2, "hp-gk", "geography", "M", 2,
    ["The Tirthan valley in Kullu is a gateway to the:", ["Pin Valley National Park", "Chail Sanctuary", "Great Himalayan National Park", "Kalatop Sanctuary"], "Tirthan and Sainj valleys lead into the Great Himalayan National Park."],
    ["कुल्लू की तीर्थन घाटी किसका प्रवेश द्वार है?", ["पिन वैली नेशनल पार्क", "चायल अभयारण्य", "ग्रेट हिमालयन नेशनल पार्क", "कालाटोप अभयारण्य"], "तीर्थन और सैंज घाटियाँ ग्रेट हिमालयन नेशनल पार्क की ओर ले जाती हैं।"]),
  q(2, "hp-gk", "geography", "H", 1,
    ["Kalpa village in Kinnaur faces which sacred peak?", ["Reo Purgyil", "Kinnaur Kailash", "Shrikhand Mahadev", "Manimahesh Kailash"], "Kalpa looks across the Sutlej at the Kinnaur Kailash range."],
    ["किन्नौर का कल्पा गाँव किस पवित्र शिखर के सामने है?", ["रियो पुरग्याल", "किन्नौर कैलाश", "श्रीखंड महादेव", "मणिमहेश कैलाश"], "कल्पा सतलुज के पार किन्नौर कैलाश शृंखला की ओर देखता है।"]),
  q(2, "hp-gk", "rivers-lakes", "M", 3,
    ["Mandi town, known for its many temples, stands on the bank of the river:", ["Sutlej", "Ravi", "Parvati", "Beas"], "Mandi, the 'Varanasi of the hills', is on the Beas."],
    ["अनेक मंदिरों के लिए प्रसिद्ध मंडी शहर किस नदी के किनारे है?", ["सतलुज", "रावी", "पार्वती", "ब्यास"], "'पहाड़ों की वाराणसी' मंडी ब्यास के किनारे है।"]),
  q(2, "hp-gk", "districts", "H", 0,
    ["Hamirpur district was carved out in 1972 from which district?", ["Kangra", "Mandi", "Bilaspur", "Una"], "In 1972 Kangra was split to form Hamirpur and Una districts."],
    ["1972 में हमीरपुर ज़िला किस ज़िले से अलग करके बनाया गया?", ["कांगड़ा", "मंडी", "बिलासपुर", "ऊना"], "1972 में कांगड़ा को बाँटकर हमीरपुर और ऊना ज़िले बनाए गए।"]),
  q(2, "hp-gk", "polity-administration", "H", 2,
    ["The Indian Institute of Information Technology (IIIT) of Himachal Pradesh is located in which district?", ["Hamirpur", "Kangra", "Una", "Solan"], "IIIT Una has its permanent campus at Saloh in Una district."],
    ["हिमाचल प्रदेश का भारतीय सूचना प्रौद्योगिकी संस्थान (IIIT) किस ज़िले में है?", ["हमीरपुर", "कांगड़ा", "ऊना", "सोलन"], "IIIT ऊना का स्थायी परिसर ऊना ज़िले के सलोह में है।"]),
  q(2, "hp-gk", "culture-festivals", "M", 1,
    ["The Kamrunag lake and temple are located in which district?", ["Kullu", "Mandi", "Shimla", "Chamba"], "Kamrunag, the deity linked with Barbarik, is near Rohanda in Mandi."],
    ["कमरुनाग झील और मंदिर किस ज़िले में हैं?", ["कुल्लू", "मंडी", "शिमला", "चंबा"], "बर्बरीक से जुड़े देवता कमरुनाग मंडी में रोहांडा के पास हैं।"]),
  q(2, "hp-gk", "culture-festivals", "M", 0,
    ["Which pastoral community of Chamba and Kangra moves seasonally with its flocks of sheep and goats?", ["Gaddi", "Kinnaura", "Lahauli", "Pangwal"], "The Gaddis practise transhumance between the Dhauladhar heights and the lower hills."],
    ["चंबा और कांगड़ा का कौन-सा पशुपालक समुदाय भेड़-बकरियों के साथ मौसमी प्रवास करता है?", ["गद्दी", "किन्नौरा", "लाहौली", "पंगवाल"], "गद्दी धौलाधार की ऊँचाइयों और निचली पहाड़ियों के बीच मौसमी प्रवास करते हैं।"]),
  q(2, "general-studies", "indian-polity", "M", 3,
    ["Under Article 60, who administers the oath of office to a newly elected President of India?", ["Vice-President", "Prime Minister", "Speaker", "Chief Justice of India"], "Article 60: the Chief Justice of India (or senior-most judge) administers the oath."],
    ["अनुच्छेद 60 के अंतर्गत नवनिर्वाचित राष्ट्रपति को पद की शपथ कौन दिलाता है?", ["उपराष्ट्रपति", "प्रधानमंत्री", "लोकसभा अध्यक्ष", "भारत के मुख्य न्यायाधीश"], "अनुच्छेद 60: भारत के मुख्य न्यायाधीश (या वरिष्ठतम न्यायाधीश) शपथ दिलाते हैं।"]),
  q(2, "general-studies", "indian-polity", "M", 1,
    ["Under which Article can the Supreme Court issue writs to enforce fundamental rights?", ["Article 226", "Article 32", "Article 21", "Article 124"], "Article 32; High Courts have similar power under Article 226."],
    ["सर्वोच्च न्यायालय मौलिक अधिकारों को लागू करने के लिए किस अनुच्छेद के तहत रिट जारी कर सकता है?", ["अनुच्छेद 226", "अनुच्छेद 32", "अनुच्छेद 21", "अनुच्छेद 124"], "अनुच्छेद 32; उच्च न्यायालयों को अनुच्छेद 226 के तहत ऐसी ही शक्ति है।"]),
  q(2, "general-studies", "indian-polity", "M", 2,
    ["In the three-tier Panchayati Raj system, the Panchayat Samiti works at the:", ["Village level", "District level", "Block level", "State level"], "Gram Panchayat (village), Panchayat Samiti (block), Zila Parishad (district)."],
    ["त्रिस्तरीय पंचायती राज व्यवस्था में पंचायत समिति किस स्तर पर कार्य करती है?", ["गाँव स्तर", "ज़िला स्तर", "खंड (ब्लॉक) स्तर", "राज्य स्तर"], "ग्राम पंचायत (गाँव), पंचायत समिति (खंड), ज़िला परिषद (ज़िला)।"]),
  q(2, "general-studies", "indian-polity", "H", 0,
    ["Which body recommends how tax revenue is shared between the Centre and the states?", ["Finance Commission", "NITI Aayog", "GST Council only", "Reserve Bank of India"], "The Finance Commission under Article 280 recommends the division of taxes."],
    ["केंद्र और राज्यों के बीच कर-राजस्व के बँटवारे की सिफ़ारिश कौन करता है?", ["वित्त आयोग", "नीति आयोग", "केवल GST परिषद", "भारतीय रिज़र्व बैंक"], "अनुच्छेद 280 के तहत वित्त आयोग करों के बँटवारे की सिफ़ारिश करता है।"]),
  q(2, "general-studies", "indian-polity", "M", 3,
    ["Which institution is regarded as the guardian of the Constitution of India?", ["Parliament", "President", "Election Commission", "Supreme Court"], "Through judicial review the Supreme Court protects the Constitution."],
    ["भारत के संविधान का संरक्षक किस संस्था को माना जाता है?", ["संसद", "राष्ट्रपति", "निर्वाचन आयोग", "सर्वोच्च न्यायालय"], "न्यायिक पुनरावलोकन द्वारा सर्वोच्च न्यायालय संविधान की रक्षा करता है।"]),
  q(2, "general-studies", "indian-history", "H", 2,
    ["Which moderate leader, Gandhi's political guru, founded the Servants of India Society at Pune in 1905?", ["Bal Gangadhar Tilak", "Dadabhai Naoroji", "Gopal Krishna Gokhale", "Lala Lajpat Rai"], "Gokhale founded it in Pune to train national workers."],
    ["गांधीजी के राजनीतिक गुरु किस नरमपंथी नेता ने 1905 में पुणे में सर्वेंट्स ऑफ़ इंडिया सोसाइटी स्थापित की?", ["बाल गंगाधर तिलक", "दादाभाई नौरोजी", "गोपाल कृष्ण गोखले", "लाला लाजपत राय"], "गोखले ने राष्ट्रसेवकों को प्रशिक्षित करने के लिए पुणे में इसकी स्थापना की।"]),
  q(2, "general-studies", "indian-history", "M", 1,
    ["The Marathi newspaper 'Kesari' was started by:", ["Gopal Krishna Gokhale", "Bal Gangadhar Tilak", "Mahatma Gandhi", "B.R. Ambedkar"], "Tilak started Kesari (Marathi) and Mahratta (English) in 1881."],
    ["मराठी समाचार-पत्र 'केसरी' किसने शुरू किया?", ["गोपाल कृष्ण गोखले", "बाल गंगाधर तिलक", "महात्मा गांधी", "बी.आर. आंबेडकर"], "तिलक ने 1881 में केसरी (मराठी) और मराठा (अंग्रेज़ी) शुरू किए।"]),
  q(2, "general-studies", "indian-history", "H", 0,
    ["The Swaraj Party was formed in 1923 by C.R. Das and:", ["Motilal Nehru", "Jawaharlal Nehru", "Subhas Chandra Bose", "Rajendra Prasad"], "C.R. Das and Motilal Nehru founded it to enter the legislative councils."],
    ["1923 में सी.आर. दास और किसने स्वराज पार्टी बनाई?", ["मोतीलाल नेहरू", "जवाहरलाल नेहरू", "सुभाष चंद्र बोस", "राजेंद्र प्रसाद"], "सी.आर. दास और मोतीलाल नेहरू ने विधान परिषदों में प्रवेश के लिए इसकी स्थापना की।"]),
  q(2, "general-studies", "indian-history", "M", 3,
    ["In which year was the Battle of Buxar fought?", ["1757", "1761", "1857", "1764"], "At Buxar (1764) the Company defeated Mir Qasim, Shuja-ud-Daula and Shah Alam II."],
    ["बक्सर का युद्ध किस वर्ष लड़ा गया?", ["1757", "1761", "1857", "1764"], "बक्सर (1764) में कंपनी ने मीर क़ासिम, शुजाउद्दौला और शाह आलम द्वितीय को हराया।"]),
  q(2, "general-studies", "indian-history", "M", 0,
    ["The Slave (Mamluk) dynasty of Delhi was founded by:", ["Qutb-ud-din Aibak", "Iltutmish", "Balban", "Razia Sultan"], "Aibak founded the dynasty in 1206."],
    ["दिल्ली के ग़ुलाम (मामलुक) वंश की स्थापना किसने की?", ["क़ुतुबुद्दीन ऐबक", "इल्तुतमिश", "बलबन", "रज़िया सुल्तान"], "ऐबक ने 1206 में इस वंश की स्थापना की।"]),
  q(2, "general-studies", "indian-geography", "H", 2,
    ["Which is the longest national highway of India, running from Srinagar to Kanyakumari?", ["NH 27", "NH 48", "NH 44", "NH 19"], "NH 44 runs about 4,100 km from Srinagar to Kanyakumari."],
    ["श्रीनगर से कन्याकुमारी तक जाने वाला भारत का सबसे लंबा राष्ट्रीय राजमार्ग कौन-सा है?", ["NH 27", "NH 48", "NH 44", "NH 19"], "NH 44 श्रीनगर से कन्याकुमारी तक लगभग 4,100 किमी लंबा है।"]),
  q(2, "general-studies", "indian-geography", "M", 1,
    ["Itanagar is the capital of:", ["Assam", "Arunachal Pradesh", "Nagaland", "Meghalaya"], "Itanagar is Arunachal's capital; Kohima is Nagaland's and Shillong Meghalaya's."],
    ["ईटानगर किस राज्य की राजधानी है?", ["असम", "अरुणाचल प्रदेश", "नागालैंड", "मेघालय"], "ईटानगर अरुणाचल की राजधानी है; कोहिमा नागालैंड की और शिलांग मेघालय की।"]),
  q(2, "general-studies", "indian-geography", "H", 3,
    ["Which town in Ladakh is often called the coldest inhabited place in India?", ["Leh", "Kargil", "Nubra", "Dras"], "Dras, near Zoji La, records winter lows below −40 °C."],
    ["लद्दाख का कौन-सा शहर प्रायः भारत का सबसे ठंडा आबाद स्थान कहलाता है?", ["लेह", "कारगिल", "नुब्रा", "द्रास"], "ज़ोजी ला के पास द्रास में सर्दियों में तापमान −40 °C से नीचे जाता है।"]),
  q(2, "general-studies", "indian-geography", "M", 2,
    ["The Nathu La pass connects Sikkim with:", ["Nepal", "Bhutan", "Tibet (China)", "Bangladesh"], "Nathu La on the Sikkim–Tibet border reopened for trade in 2006."],
    ["नाथू ला दर्रा सिक्किम को किससे जोड़ता है?", ["नेपाल", "भूटान", "तिब्बत (चीन)", "बांग्लादेश"], "सिक्किम–तिब्बत सीमा पर नाथू ला 2006 में व्यापार के लिए फिर खुला।"]),
  q(2, "general-studies", "general-science", "M", 0,
    ["Which cell organelle is known as the 'powerhouse of the cell'?", ["Mitochondrion", "Nucleus", "Ribosome", "Golgi body"], "Mitochondria produce ATP through respiration."],
    ["कोशिका के किस अंगक को 'कोशिका का ऊर्जा-घर' कहा जाता है?", ["माइटोकॉन्ड्रिया", "केंद्रक", "राइबोसोम", "गॉल्जी काय"], "माइटोकॉन्ड्रिया श्वसन द्वारा ATP बनाते हैं।"]),
  q(2, "general-studies", "general-science", "H", 1,
    ["Which gas, nicknamed 'laughing gas', is used by dentists as a mild anaesthetic?", ["Nitrogen dioxide", "Nitrous oxide", "Nitric oxide", "Ammonia"], "Nitrous oxide (N₂O) is used as a mild anaesthetic."],
    ["'हँसाने वाली गैस' के नाम से प्रसिद्ध कौन-सी गैस दंत-चिकित्सा में हल्के निश्चेतक के रूप में प्रयुक्त होती है?", ["नाइट्रोजन डाइऑक्साइड", "नाइट्रस ऑक्साइड", "नाइट्रिक ऑक्साइड", "अमोनिया"], "नाइट्रस ऑक्साइड (N₂O) हल्के निश्चेतक के रूप में उपयोग होती है।"]),
  q(2, "general-studies", "general-science", "M", 3,
    ["Which instrument records the waves of an earthquake?", ["Barometer", "Altimeter", "Hydrometer", "Seismograph"], "A seismograph records seismic waves."],
    ["कौन-सा उपकरण भूकंप की तरंगें दर्ज करता है?", ["बैरोमीटर", "अल्टीमीटर", "हाइड्रोमीटर", "सिस्मोग्राफ़"], "सिस्मोग्राफ़ भूकंपीय तरंगें दर्ज करता है।"]),
  q(2, "general-studies", "general-science", "H", 2,
    ["Short-sightedness (myopia) is corrected using which lens?", ["Convex lens", "Cylindrical lens", "Concave lens", "Bifocal convex lens"], "A concave (diverging) lens moves the image back onto the retina."],
    ["निकट-दृष्टि दोष (मायोपिया) किस लेंस से ठीक किया जाता है?", ["उत्तल लेंस", "बेलनाकार लेंस", "अवतल लेंस", "द्विफ़ोकसी उत्तल लेंस"], "अवतल (अपसारी) लेंस प्रतिबिंब को रेटिना पर लाता है।"]),
  q(2, "general-studies", "indian-economy", "M", 0,
    ["The headquarters of ISRO is in:", ["Bengaluru", "Sriharikota", "Thiruvananthapuram", "Ahmedabad"], "ISRO is headquartered at Bengaluru; Sriharikota is the launch centre."],
    ["इसरो का मुख्यालय कहाँ है?", ["बेंगलुरु", "श्रीहरिकोटा", "तिरुवनंतपुरम", "अहमदाबाद"], "इसरो का मुख्यालय बेंगलुरु में है; श्रीहरिकोटा प्रक्षेपण केंद्र है।"]),
  q(2, "general-studies", "indian-polity", "H", 3,
    ["National Voters' Day, marking the founding of the Election Commission, is observed on:", ["26 November", "15 August", "2 October", "25 January"], "The Election Commission was set up on 25 January 1950; the day has been observed since 2011."],
    ["निर्वाचन आयोग की स्थापना की याद में राष्ट्रीय मतदाता दिवस कब मनाया जाता है?", ["26 नवंबर", "15 अगस्त", "2 अक्टूबर", "25 जनवरी"], "निर्वाचन आयोग 25 जनवरी 1950 को बना; यह दिवस 2011 से मनाया जा रहा है।"]),

  // ───────── Section 3: Reasoning (15) ─────────
  q(3, "reasoning", "series", "M", 2,
    ["Find the next number: 5, 7, 11, 17, 25, ?", ["33", "34", "35", "37"], "Differences are 2, 4, 6, 8, 10: 25 + 10 = 35."],
    ["अगली संख्या ज्ञात कीजिए: 5, 7, 11, 17, 25, ?", ["33", "34", "35", "37"], "अंतर 2, 4, 6, 8, 10 हैं: 25 + 10 = 35।"], "25+10"),
  q(3, "reasoning", "series", "M", 1,
    ["Find the next number: 4, 7, 13, 25, 49, ?", ["95", "97", "98", "96"], "Each term is double the previous minus 1: 49 × 2 − 1 = 97."],
    ["अगली संख्या ज्ञात कीजिए: 4, 7, 13, 25, 49, ?", ["95", "97", "98", "96"], "हर पद पिछले का दोगुना − 1: 49 × 2 − 1 = 97।"], "49*2-1"),
  q(3, "reasoning", "alphabet-test", "M", 0,
    ["Find the next group: BCD, FGH, JKL, ?", ["NOP", "MNO", "OPQ", "NPQ"], "Each group starts four letters after the last one: B, F, J, N."],
    ["अगला समूह ज्ञात कीजिए: BCD, FGH, JKL, ?", ["NOP", "MNO", "OPQ", "NPQ"], "हर समूह पिछले से चार अक्षर आगे शुरू होता है: B, F, J, N।"]),
  q(3, "reasoning", "coding-decoding", "M", 3,
    ["If COURT is coded as 3-15-21-18-20, how is JUDGE coded?", ["10-20-4-7-5", "10-21-4-6-5", "11-21-4-7-5", "10-21-4-7-5"], "J = 10, U = 21, D = 4, G = 7, E = 5."],
    ["यदि COURT को 3-15-21-18-20 लिखा जाता है, तो JUDGE को कैसे लिखा जाएगा?", ["10-20-4-7-5", "10-21-4-6-5", "11-21-4-7-5", "10-21-4-7-5"], "J = 10, U = 21, D = 4, G = 7, E = 5।"]),
  q(3, "reasoning", "coding-decoding", "M", 0,
    ["If DEAF is written as 4-5-1-6, how is FADE written?", ["6-1-4-5", "6-4-1-5", "5-1-4-6", "6-1-5-4"], "Using letter positions: F = 6, A = 1, D = 4, E = 5."],
    ["यदि DEAF को 4-5-1-6 लिखा जाता है, तो FADE को कैसे लिखा जाएगा?", ["6-1-4-5", "6-4-1-5", "5-1-4-6", "6-1-5-4"], "अक्षरों के स्थान से: F = 6, A = 1, D = 4, E = 5।"]),
  q(3, "reasoning", "blood-relations", "M", 2,
    ["B is the husband of A. C is the only son of A. D is C's daughter. How is D related to B?", ["Daughter", "Niece", "Granddaughter", "Sister"], "C is B's son, so C's daughter D is B's granddaughter."],
    ["B, A का पति है। C, A का इकलौता बेटा है। D, C की बेटी है। D, B की क्या लगती है?", ["बेटी", "भतीजी", "पोती", "बहन"], "C, B का बेटा है, अतः C की बेटी D, B की पोती है।"]),
  q(3, "reasoning", "blood-relations", "H", 1,
    ["Looking at a portrait, a man says, \"I have no brother or sister, but that man's father is my father's son.\" Whose portrait is it?", ["His own", "His son's", "His father's", "His nephew's"], "His father's son is himself (he has no siblings), so the man in the portrait is his son."],
    ["एक चित्र देखकर एक व्यक्ति कहता है, \"मेरा कोई भाई-बहन नहीं है, पर उस व्यक्ति के पिता मेरे पिता के बेटे हैं।\" चित्र किसका है?", ["उसका अपना", "उसके बेटे का", "उसके पिता का", "उसके भतीजे का"], "उसके पिता का बेटा वह स्वयं है (कोई भाई-बहन नहीं), अतः चित्र वाला व्यक्ति उसका बेटा है।"]),
  q(3, "reasoning", "direction-sense", "H", 3,
    ["Sunil walks 20 m north, turns right and walks 30 m, turns right and walks 35 m, turns left and walks 15 m, then turns left and walks 15 m. Where is he now from the start?", ["15 m north", "30 m east", "45 m west", "45 m east"], "North–south: +20 − 35 + 15 = 0. East: 30 + 15 = 45 m. So he is 45 m east."],
    ["सुनील 20 मी उत्तर, दाएँ मुड़कर 30 मी, दाएँ मुड़कर 35 मी, बाएँ मुड़कर 15 मी, फिर बाएँ मुड़कर 15 मी चलता है। वह आरंभ से कहाँ है?", ["15 मी उत्तर", "30 मी पूर्व", "45 मी पश्चिम", "45 मी पूर्व"], "उत्तर–दक्षिण: +20 − 35 + 15 = 0। पूर्व: 30 + 15 = 45 मी। अतः वह 45 मी पूर्व में है।"]),
  q(3, "reasoning", "direction-sense", "M", 0,
    ["At sunset a man stands with his shadow falling directly behind him. Which direction is he facing?", ["West", "East", "North", "South"], "At sunset the sun is in the west; with the shadow behind him, he faces the sun, i.e. west."],
    ["सूर्यास्त के समय एक व्यक्ति की परछाईं ठीक उसके पीछे पड़ रही है। उसका मुँह किस दिशा में है?", ["पश्चिम", "पूर्व", "उत्तर", "दक्षिण"], "सूर्यास्त में सूर्य पश्चिम में होता है; परछाईं पीछे है तो वह सूर्य की ओर, अर्थात् पश्चिम की ओर देख रहा है।"]),
  q(3, "reasoning", "ranking", "M", 2,
    ["In a class of 50 students, Amit ranks 18th from the top. How many students rank below him?", ["31", "33", "32", "30"], "50 − 18 = 32 students are below him."],
    ["50 विद्यार्थियों की कक्षा में अमित ऊपर से 18वें स्थान पर है। उससे नीचे कितने विद्यार्थी हैं?", ["31", "33", "32", "30"], "50 − 18 = 32 विद्यार्थी उससे नीचे हैं।"], "50-18"),
  q(3, "reasoning", "analogy", "M", 1,
    ["Bird : Nest :: Bee : ?", ["Honey", "Hive", "Flower", "Wax"], "A bird lives in a nest; a bee lives in a hive."],
    ["पक्षी : घोंसला :: मधुमक्खी : ?", ["शहद", "छत्ता", "फूल", "मोम"], "पक्षी घोंसले में; मधुमक्खी छत्ते में रहती है।"]),
  q(3, "reasoning", "odd-one-out", "H", 3,
    ["Find the odd one out: Judge, Magistrate, Munsif, Plaintiff", ["Judge", "Magistrate", "Munsif", "Plaintiff"], "Judge, magistrate and munsif decide cases; a plaintiff is a party who files a suit."],
    ["विषम चुनिए: न्यायाधीश, मजिस्ट्रेट, मुंसिफ़, वादी", ["न्यायाधीश", "मजिस्ट्रेट", "मुंसिफ़", "वादी"], "न्यायाधीश, मजिस्ट्रेट और मुंसिफ़ मामले तय करते हैं; वादी मुकदमा दायर करने वाला पक्ष है।"]),
  q(3, "reasoning", "clock-calendar", "H", 2,
    ["At what time between 3 and 4 o'clock do the hour and minute hands of a clock coincide?", ["15 minutes past 3", "16 minutes past 3", "16 4/11 minutes past 3", "17 minutes past 3"], "Minutes = 60H/11 = 180/11 = 16 4/11 minutes past 3."],
    ["3 और 4 बजे के बीच किस समय घड़ी की घंटे और मिनट की सुइयाँ एक-दूसरे पर होती हैं?", ["3 बजकर 15 मिनट", "3 बजकर 16 मिनट", "3 बजकर 16 4/11 मिनट", "3 बजकर 17 मिनट"], "मिनट = 60H/11 = 180/11 = 3 बजकर 16 4/11 मिनट।"]),
  q(3, "reasoning", "clock-calendar", "H", 1,
    ["Which of these century years is a leap year: 1900, 2000, 2100 or 2200?", ["1900", "2000", "2100", "2200"], "A century year is a leap year only if divisible by 400; only 2000 is."],
    ["इनमें से कौन-सा शताब्दी वर्ष लीप वर्ष है: 1900, 2000, 2100 या 2200?", ["1900", "2000", "2100", "2200"], "शताब्दी वर्ष तभी लीप वर्ष है जब वह 400 से विभाज्य हो; केवल 2000 है।"]),
  q(3, "reasoning", "syllogism", "M", 0,
    ["Statements: All typists are graduates. No graduate is illiterate. Conclusions: I. No typist is illiterate. II. All graduates are typists.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "Typists ⊂ graduates, and graduates are never illiterate, so I follows; II reverses an 'all' statement."],
    ["कथन: सभी टाइपिस्ट स्नातक हैं। कोई स्नातक निरक्षर नहीं है। निष्कर्ष: I. कोई टाइपिस्ट निरक्षर नहीं है। II. सभी स्नातक टाइपिस्ट हैं।", ["केवल I निकलता है", "केवल II निकलता है", "I और II दोनों निकलते हैं", "न I न II निकलता है"], "टाइपिस्ट ⊂ स्नातक, और स्नातक कभी निरक्षर नहीं, अतः I निकलता है; II 'सभी' कथन को उलटता है।"]),

  // ───────── Section 4: Computer (20) ─────────
  q(4, "computer", "shortcuts", "H", 2,
    ["Which shortcut inserts a manual page break in MS Word?", ["Shift + Enter", "Alt + Enter", "Ctrl + Enter", "Ctrl + Shift + B"], "Ctrl + Enter starts a new page; Shift + Enter inserts a line break."],
    ["MS Word में मैनुअल पेज ब्रेक डालने का शॉर्टकट कौन-सा है?", ["Shift + Enter", "Alt + Enter", "Ctrl + Enter", "Ctrl + Shift + B"], "Ctrl + Enter नया पृष्ठ शुरू करता है; Shift + Enter लाइन ब्रेक डालता है।"]),
  q(4, "computer", "ms-office", "M", 1,
    ["Which MS Word view shows the document exactly as it will be printed?", ["Draft", "Print Layout", "Outline", "Web Layout"], "Print Layout shows page edges, margins, headers and footers."],
    ["MS Word का कौन-सा व्यू दस्तावेज़ को ठीक वैसा दिखाता है जैसा वह प्रिंट होगा?", ["Draft", "Print Layout", "Outline", "Web Layout"], "Print Layout पृष्ठ के किनारे, मार्जिन, हेडर और फ़ुटर दिखाता है।"]),
  q(4, "computer", "shortcuts", "H", 3,
    ["In MS Word, which function key starts the Spelling and Grammar check?", ["F5", "F12", "F1", "F7"], "F7 runs Spelling & Grammar; F12 is Save As; F1 Help; F5 Go To."],
    ["MS Word में स्पेलिंग और ग्रामर जाँच कौन-सी फ़ंक्शन कुंजी शुरू करती है?", ["F5", "F12", "F1", "F7"], "F7 स्पेलिंग व ग्रामर; F12 Save As; F1 Help; F5 Go To।"]),
  q(4, "computer", "shortcuts", "M", 0,
    ["Which shortcut centres the selected paragraph in MS Word?", ["Ctrl + E", "Ctrl + C", "Ctrl + J", "Ctrl + L"], "Ctrl + E centres, Ctrl + L left-aligns, Ctrl + J justifies; Ctrl + C copies."],
    ["MS Word में चुने गए अनुच्छेद को बीच में (centre) करने का शॉर्टकट कौन-सा है?", ["Ctrl + E", "Ctrl + C", "Ctrl + J", "Ctrl + L"], "Ctrl + E केंद्र, Ctrl + L बाएँ, Ctrl + J जस्टिफ़ाई; Ctrl + C कॉपी।"]),
  q(4, "computer", "ms-office", "H", 2,
    ["In MS Word, 'Track Changes', used while correcting a draft judgment, is found under which tab?", ["Home", "Insert", "Review", "View"], "Review → Track Changes records every edit for approval."],
    ["MS Word में मसौदा निर्णय सुधारते समय उपयोग होने वाला 'Track Changes' किस टैब में है?", ["Home", "Insert", "Review", "View"], "Review → Track Changes हर संपादन को स्वीकृति के लिए दर्ज करता है।"]),
  q(4, "computer", "ms-office", "M", 0,
    ["To set 1.5 line spacing for a paragraph in MS Word, you use the:", ["Paragraph settings on the Home tab", "Font dialog", "Page Colour option", "Mail Merge wizard"], "Line and paragraph spacing is in the Paragraph group of the Home tab."],
    ["MS Word में किसी अनुच्छेद की लाइन स्पेसिंग 1.5 करने के लिए किसका उपयोग करते हैं?", ["Home टैब की Paragraph सेटिंग", "Font डायलॉग", "Page Colour विकल्प", "Mail Merge विज़र्ड"], "लाइन और पैराग्राफ़ स्पेसिंग Home टैब के Paragraph समूह में है।"]),
  q(4, "computer", "ms-office", "M", 3,
    ["In MS Excel, every formula must begin with which character?", ["#", "@", "$", "="], "Formulas start with '=' (for example =SUM(A1:A5))."],
    ["MS Excel में हर सूत्र (formula) किस चिह्न से शुरू होना चाहिए?", ["#", "@", "$", "="], "सूत्र '=' से शुरू होते हैं (जैसे =SUM(A1:A5))।"]),
  q(4, "computer", "ms-office", "M", 1,
    ["What value does the Excel formula =AVERAGE(10, 20, 30) return?", ["60", "20", "30", "10"], "(10 + 20 + 30) ÷ 3 = 20."],
    ["Excel का सूत्र =AVERAGE(10, 20, 30) क्या मान देगा?", ["60", "20", "30", "10"], "(10 + 20 + 30) ÷ 3 = 20।"], "(10+20+30)/3"),
  q(4, "computer", "ms-office", "M", 2,
    ["Which Excel function counts how many cells in a range contain numbers?", ["SUM", "COUNTA", "COUNT", "LEN"], "COUNT counts numeric cells; COUNTA counts all non-empty cells."],
    ["Excel का कौन-सा फ़ंक्शन गिनता है कि किसी श्रेणी के कितने सेल में संख्याएँ हैं?", ["SUM", "COUNTA", "COUNT", "LEN"], "COUNT संख्या वाले सेल गिनता है; COUNTA सभी भरे सेल।"]),
  q(4, "computer", "hardware", "E", 0,
    ["Which component carries out program instructions and is called the 'brain' of a computer?", ["CPU", "Monitor", "Keyboard", "Hard disk"], "The Central Processing Unit executes instructions."],
    ["कौन-सा घटक प्रोग्राम के निर्देशों का पालन करता है और कंप्यूटर का 'मस्तिष्क' कहलाता है?", ["CPU", "मॉनिटर", "कीबोर्ड", "हार्ड डिस्क"], "सेंट्रल प्रोसेसिंग यूनिट निर्देशों का पालन करती है।"]),
  q(4, "computer", "hardware", "M", 3,
    ["A small portable storage device that uses flash memory and plugs into a USB port is a:", ["Floppy disk", "CD-ROM", "Hard disk", "Pen drive"], "A pen drive (USB flash drive) uses flash memory."],
    ["फ़्लैश मेमोरी वाला छोटा पोर्टेबल स्टोरेज उपकरण जो USB पोर्ट में लगता है, कहलाता है:", ["फ़्लॉपी डिस्क", "सीडी-रोम", "हार्ड डिस्क", "पेन ड्राइव"], "पेन ड्राइव (USB फ़्लैश ड्राइव) फ़्लैश मेमोरी उपयोग करती है।"]),
  q(4, "computer", "number-system", "M", 1,
    ["In binary measure, one gigabyte equals how many megabytes?", ["1000", "1024", "512", "2048"], "1 GB = 1024 MB."],
    ["बाइनरी माप में एक गीगाबाइट कितने मेगाबाइट के बराबर है?", ["1000", "1024", "512", "2048"], "1 GB = 1024 MB।"], "2**10"),
  q(4, "computer", "software", "H", 2,
    ["Which program translates an entire high-level-language program into machine code before it runs?", ["Interpreter", "Assembler", "Compiler", "Loader"], "A compiler translates the whole program at once; an interpreter goes line by line."],
    ["कौन-सा प्रोग्राम उच्च-स्तरीय भाषा के पूरे प्रोग्राम को चलाने से पहले मशीन कोड में बदलता है?", ["इंटरप्रेटर", "असेंबलर", "कंपाइलर", "लोडर"], "कंपाइलर पूरा प्रोग्राम एक साथ बदलता है; इंटरप्रेटर पंक्ति-दर-पंक्ति।"]),
  q(4, "computer", "software", "H", 0,
    ["Which of these office suites is free and open-source?", ["LibreOffice", "Microsoft Office", "WPS Office Premium", "Apple iWork Pro"], "LibreOffice is released under an open-source licence."],
    ["इनमें से कौन-सा ऑफ़िस सूट निःशुल्क और ओपन-सोर्स है?", ["LibreOffice", "Microsoft Office", "WPS Office Premium", "Apple iWork Pro"], "LibreOffice ओपन-सोर्स लाइसेंस के तहत जारी होता है।"]),
  q(4, "computer", "operating-systems", "M", 3,
    ["In Microsoft Windows, pressing Ctrl + Alt + Del opens:", ["The Start menu", "The Control Panel", "The Recycle Bin", "A security screen with options such as Task Manager and Lock"], "It opens the security options, from which Task Manager, Lock and Sign out are available."],
    ["Microsoft Windows में Ctrl + Alt + Del दबाने से क्या खुलता है?", ["Start मेनू", "कंट्रोल पैनल", "रीसायकल बिन", "Task Manager और Lock जैसे विकल्पों वाली सुरक्षा स्क्रीन"], "यह सुरक्षा विकल्प खोलता है, जहाँ से Task Manager, Lock और Sign out मिलते हैं।"]),
  q(4, "computer", "fundamentals", "M", 1,
    ["The file extension .pdf stands for:", ["Printed Data File", "Portable Document Format", "Public Document File", "Personal Data Form"], "PDF, created by Adobe, keeps the layout the same on every device."],
    ["फ़ाइल एक्सटेंशन .pdf का पूर्ण रूप है:", ["Printed Data File", "Portable Document Format", "Public Document File", "Personal Data Form"], "Adobe द्वारा बनाया PDF हर उपकरण पर लेआउट एक-सा रखता है।"]),
  q(4, "computer", "internet-networking", "H", 2,
    ["An Outlook user clicks Send; which protocol carries that outgoing message to the mail server?", ["HTTP", "FTP", "SMTP", "POP3"], "SMTP sends mail; POP3 and IMAP retrieve it."],
    ["Outlook उपयोगकर्ता के Send दबाने पर कौन-सा प्रोटोकॉल उस ई-मेल को मेल सर्वर तक पहुँचाता है?", ["HTTP", "FTP", "SMTP", "POP3"], "SMTP मेल भेजता है; POP3 और IMAP मेल प्राप्त करते हैं।"]),
  q(4, "computer", "security", "H", 3,
    ["In computer networks, a firewall is used to:", ["Cool the processor", "Speed up downloads", "Back up files", "Block unauthorised access to or from a network"], "A firewall filters network traffic according to security rules."],
    ["कंप्यूटर नेटवर्क में फ़ायरवॉल का उपयोग किसलिए होता है?", ["प्रोसेसर ठंडा करने के लिए", "डाउनलोड तेज़ करने के लिए", "फ़ाइलों का बैकअप लेने के लिए", "नेटवर्क में अनधिकृत पहुँच रोकने के लिए"], "फ़ायरवॉल सुरक्षा नियमों के अनुसार नेटवर्क ट्रैफ़िक छानता है।"]),
  q(4, "computer", "shortcuts", "M", 0,
    ["In most web browsers, which shortcut opens a new tab?", ["Ctrl + T", "Ctrl + N", "Ctrl + W", "Ctrl + Tab"], "Ctrl + T opens a tab; Ctrl + N a new window; Ctrl + W closes a tab."],
    ["अधिकांश वेब ब्राउज़रों में नया टैब खोलने का शॉर्टकट कौन-सा है?", ["Ctrl + T", "Ctrl + N", "Ctrl + W", "Ctrl + Tab"], "Ctrl + T टैब खोलता है; Ctrl + N नई विंडो; Ctrl + W टैब बंद करता है।"]),
  q(4, "computer", "hardware", "E", 2,
    ["Which key deletes the character to the left of the cursor?", ["Delete", "Esc", "Backspace", "Tab"], "Backspace removes the character before the cursor; Delete removes the one after it."],
    ["कौन-सी कुंजी कर्सर के बाईं ओर का अक्षर मिटाती है?", ["Delete", "Esc", "Backspace", "Tab"], "Backspace कर्सर से पहले का अक्षर मिटाता है; Delete बाद वाला।"]),
];
