// HP JOA IT computer test: MS Excel (syllabus unit V), 25 questions.
// All questions are new, not in the full mock. Options are balanced at seed time.
// Formulas go inside `backticks`: a bare $A$1 or two asterisks would be rendered as math or italics.

import { q, type JoaItQuestion } from "../types";

export const excel1: JoaItQuestion[] = [
  q(0, "computer", "ms-office", "H", 0,
    ["How many rows does a worksheet have in MS Excel 2007 and later versions?", ["1,048,576", "65,536", "16,384", "1,000,000"], "Since Excel 2007 a worksheet has 1,048,576 rows (2²⁰) and 16,384 columns (A to XFD). Excel 2003 had 65,536 rows and 256 columns."],
    ["MS Excel 2007 और बाद के संस्करणों में एक वर्कशीट में कितनी पंक्तियाँ (rows) होती हैं?", ["1,048,576", "65,536", "16,384", "1,000,000"], "Excel 2007 से वर्कशीट में 1,048,576 पंक्तियाँ (2²⁰) और 16,384 कॉलम (A से XFD) होते हैं। Excel 2003 में 65,536 पंक्तियाँ और 256 कॉलम थे।"], "2 ** 20"),
  q(0, "computer", "ms-office", "H", 2,
    ["What is the heading of the last column in a worksheet of MS Excel 2016?", ["IV", "ZZZ", "XFD", "XFZ"], "The last column is XFD, which is column number 16,384. In Excel 2003 the last column was IV (column 256)."],
    ["MS Excel 2016 की वर्कशीट में अंतिम कॉलम का शीर्षक क्या है?", ["IV", "ZZZ", "XFD", "XFZ"], "अंतिम कॉलम XFD है, जो कॉलम संख्या 16,384 है। Excel 2003 में अंतिम कॉलम IV (कॉलम 256) था।"]),
  q(0, "computer", "ms-office", "M", 1,
    ["What is the default file extension of a workbook saved in MS Excel 2007 or later?", [".xls", ".xlsx", ".xlsm", ".csv"], "Excel 2007 onwards saves workbooks as .xlsx. .xls is the old 97–2003 format, .xlsm is a macro-enabled workbook and .csv is plain comma-separated text."],
    ["MS Excel 2007 या बाद के संस्करण में सहेजी गई वर्कबुक का डिफ़ॉल्ट फ़ाइल एक्सटेंशन क्या है?", [".xls", ".xlsx", ".xlsm", ".csv"], "Excel 2007 से वर्कबुक .xlsx के रूप में सहेजी जाती है। .xls पुराना 97–2003 फ़ॉर्मेट, .xlsm मैक्रो-सक्षम वर्कबुक और .csv कॉमा से अलग किया गया सादा पाठ है।"]),
  q(0, "computer", "ms-office", "M", 3,
    ["What does the formula `=COUNTIF(A1:A10, \">50\")` return?", ["The sum of the values greater than 50", "The first value greater than 50", "TRUE if any value is greater than 50", "The number of cells in A1:A10 with a value greater than 50"], "COUNTIF counts the cells in a range that meet a condition. Here it counts the cells in A1:A10 whose value is greater than 50."],
    ["सूत्र `=COUNTIF(A1:A10, \">50\")` क्या लौटाता है?", ["50 से बड़े मानों का योग", "50 से बड़ा पहला मान", "यदि कोई मान 50 से बड़ा हो तो TRUE", "A1:A10 में उन सेलों की संख्या जिनका मान 50 से बड़ा है"], "COUNTIF किसी रेंज में शर्त पूरी करने वाले सेल गिनता है। यहाँ यह A1:A10 के उन सेलों को गिनता है जिनका मान 50 से बड़ा है।"]),
  q(0, "computer", "ms-office", "M", 3,
    ["Which Excel function adds only those values in a range that meet a given condition, such as the sales of one district?", ["COUNTIF", "SUMPRODUCT", "ROUND", "SUMIF"], "SUMIF adds the cells that meet one condition, for example `=SUMIF(A2:A20, \"Mandi\", B2:B20)`. COUNTIF only counts such cells."],
    ["Excel का कौन-सा फ़ंक्शन किसी रेंज में केवल वही मान जोड़ता है जो दी गई शर्त पूरी करते हैं, जैसे किसी एक ज़िले की बिक्री?", ["COUNTIF", "SUMPRODUCT", "ROUND", "SUMIF"], "SUMIF एक शर्त पूरी करने वाले सेलों को जोड़ता है, जैसे `=SUMIF(A2:A20, \"Mandi\", B2:B20)`। COUNTIF ऐसे सेलों को केवल गिनता है।"]),
  q(0, "computer", "ms-office", "M", 1,
    ["What does `=LEN(\"SHIMLA\")` return in MS Excel?", ["5", "6", "7", "8"], "LEN returns the number of characters in a text. SHIMLA has 6 letters."],
    ["MS Excel में `=LEN(\"SHIMLA\")` क्या लौटाता है?", ["5", "6", "7", "8"], "LEN किसी पाठ में अक्षरों की संख्या बताता है। SHIMLA में 6 अक्षर हैं।"], "'SHIMLA'.length"),
  q(0, "computer", "ms-office", "M", 2,
    ["What is the result of `=CONCATENATE(\"HP\", \"-\", \"2026\")` in MS Excel?", ["HP2026", "HP - 2026", "HP-2026", "`#VALUE!`"], "CONCATENATE joins the texts exactly as given, without adding spaces, so the result is HP-2026. The & operator does the same: `=\"HP\"&\"-\"&\"2026\"`."],
    ["MS Excel में `=CONCATENATE(\"HP\", \"-\", \"2026\")` का परिणाम क्या है?", ["HP2026", "HP - 2026", "HP-2026", "`#VALUE!`"], "CONCATENATE पाठों को बिना कोई स्पेस जोड़े ठीक वैसे ही जोड़ता है, इसलिए परिणाम HP-2026 है। & ऑपरेटर भी यही करता है: `=\"HP\"&\"-\"&\"2026\"`।"]),
  q(0, "computer", "ms-office", "M", 0,
    ["What does `=PROPER(\"himachal pradesh\")` return?", ["Himachal Pradesh", "HIMACHAL PRADESH", "himachal pradesh", "Himachal pradesh"], "PROPER capitalises the first letter of every word and makes the rest lowercase. UPPER would give HIMACHAL PRADESH and LOWER himachal pradesh."],
    ["`=PROPER(\"himachal pradesh\")` क्या लौटाता है?", ["Himachal Pradesh", "HIMACHAL PRADESH", "himachal pradesh", "Himachal pradesh"], "PROPER हर शब्द का पहला अक्षर बड़ा और बाकी छोटे कर देता है। UPPER से HIMACHAL PRADESH और LOWER से himachal pradesh मिलता।"]),
  q(0, "computer", "ms-office", "H", 2,
    ["Cell C1 contains `=A1*B1`. If this formula is copied to cell D2, what will D2 contain?", ["`=A2*B2`", "`=A1*B1`", "`=B2*C2`", "`=B1*C1`"], "Both references are relative. Moving from C1 to D2 shifts one column right and one row down, so A1 becomes B2 and B1 becomes C2: `=B2*C2`."],
    ["सेल C1 में `=A1*B1` है। यदि यह सूत्र सेल D2 में कॉपी किया जाए तो D2 में क्या होगा?", ["`=A2*B2`", "`=A1*B1`", "`=B2*C2`", "`=B1*C1`"], "दोनों संदर्भ सापेक्ष हैं। C1 से D2 पर जाने में एक कॉलम दाएँ और एक पंक्ति नीचे खिसकते हैं, अतः A1 का B2 और B1 का C2 हो जाता है: `=B2*C2`।"]),
  q(0, "computer", "ms-office", "H", 0,
    ["In the formula `=$A1+B$1`, which parts stay fixed when the formula is copied to other cells?", ["Column A in the first reference and row 1 in the second reference", "Both references are fully fixed", "Nothing is fixed", "Row 1 in the first reference and column B in the second reference"], "`$A1` locks only the column (A), and `B$1` locks only the row (1). These are called mixed references."],
    ["सूत्र `=$A1+B$1` को अन्य सेलों में कॉपी करने पर कौन-से भाग स्थिर रहते हैं?", ["पहले संदर्भ में कॉलम A और दूसरे संदर्भ में पंक्ति 1", "दोनों संदर्भ पूरी तरह स्थिर रहते हैं", "कुछ भी स्थिर नहीं रहता", "पहले संदर्भ में पंक्ति 1 और दूसरे संदर्भ में कॉलम B"], "`$A1` केवल कॉलम (A) को और `B$1` केवल पंक्ति (1) को स्थिर करता है। इन्हें मिश्रित (mixed) संदर्भ कहते हैं।"]),
  q(0, "computer", "ms-office", "H", 3,
    ["While editing a formula in Excel, what happens when you press F4 with the cursor on a cell reference such as A1?", ["The workbook is saved", "The Help window opens", "A new worksheet is inserted", "The reference switches between absolute, mixed and relative forms"], "F4 cycles the reference through `$A$1` → `A$1` → `$A1` → `A1`, which saves typing the dollar signs."],
    ["Excel में सूत्र संपादित करते समय A1 जैसे सेल संदर्भ पर कर्सर रखकर F4 दबाने से क्या होता है?", ["वर्कबुक सहेजी जाती है", "सहायता विंडो खुलती है", "नई वर्कशीट जुड़ती है", "संदर्भ निरपेक्ष, मिश्रित और सापेक्ष रूपों में बदलता है"], "F4 संदर्भ को `$A$1` → `A$1` → `$A1` → `A1` के क्रम में बदलता है, जिससे डॉलर चिह्न टाइप नहीं करने पड़ते।"]),
  q(0, "computer", "ms-office", "M", 1,
    ["Which error does Excel show when a formula refers to a cell or range that has been deleted?", ["`#NAME?`", "`#REF!`", "`#N/A`", "`#VALUE!`"], "`#REF!` means an invalid cell reference, usually because the referenced cells were deleted. `#NAME?` means Excel does not recognise a name, `#N/A` means a value is not available and `#VALUE!` means a wrong type of argument."],
    ["जब कोई सूत्र ऐसे सेल या रेंज को संदर्भित करता है जिसे हटा दिया गया है, तो Excel कौन-सी त्रुटि दिखाता है?", ["`#NAME?`", "`#REF!`", "`#N/A`", "`#VALUE!`"], "`#REF!` का अर्थ अमान्य सेल संदर्भ है, प्रायः इसलिए कि संदर्भित सेल हटा दिए गए। `#NAME?` का अर्थ है Excel नाम नहीं पहचानता, `#N/A` का अर्थ मान उपलब्ध नहीं और `#VALUE!` का अर्थ गलत प्रकार का तर्क है।"]),
  q(0, "computer", "ms-office", "M", 1,
    ["In MS Excel, the error `#N/A` most commonly appears when:", ["A number is divided by zero", "A lookup function such as VLOOKUP cannot find the value it is searching for", "The column is too narrow", "The formula contains text instead of numbers"], "`#N/A` (not available) usually means that a lookup function such as VLOOKUP, HLOOKUP or MATCH could not find the lookup value."],
    ["MS Excel में `#N/A` त्रुटि सामान्यतः कब दिखाई देती है?", ["जब किसी संख्या को शून्य से भाग दिया जाए", "जब VLOOKUP जैसा लुकअप फ़ंक्शन खोजा जा रहा मान न ढूँढ पाए", "जब कॉलम बहुत संकरा हो", "जब सूत्र में संख्याओं के स्थान पर पाठ हो"], "`#N/A` (not available) का सामान्यतः अर्थ है कि VLOOKUP, HLOOKUP या MATCH जैसे लुकअप फ़ंक्शन को खोजा गया मान नहीं मिला।"]),
  q(0, "computer", "ms-office", "H", 3,
    ["What does `=VLOOKUP(102, A2:C10, 3, FALSE)` return?", ["The value in column A of row 102", "The third-smallest value near 102", "An approximate match for 102 from column C", "The value from the 3rd column of A2:C10, in the row where column A is exactly 102"], "VLOOKUP searches for 102 in the first column (A) of A2:C10 and returns the value from the 3rd column (C) of the same row. FALSE means an exact match is required."],
    ["`=VLOOKUP(102, A2:C10, 3, FALSE)` क्या लौटाता है?", ["पंक्ति 102 के कॉलम A का मान", "102 के निकट तीसरा सबसे छोटा मान", "कॉलम C से 102 का अनुमानित मिलान", "A2:C10 के तीसरे कॉलम का वह मान, जिस पंक्ति में कॉलम A ठीक 102 है"], "VLOOKUP, A2:C10 के पहले कॉलम (A) में 102 खोजता है और उसी पंक्ति के तीसरे कॉलम (C) का मान लौटाता है। FALSE का अर्थ है सटीक मिलान आवश्यक है।"]),
  q(0, "computer", "shortcuts", "H", 0,
    ["Which shortcut inserts a new worksheet in the current Excel workbook?", ["Shift + F11", "Ctrl + N", "Ctrl + W", "Alt + F4"], "Shift + F11 inserts a new worksheet. Ctrl + N creates a new workbook, Ctrl + W closes the workbook and Alt + F4 closes Excel."],
    ["वर्तमान Excel वर्कबुक में नई वर्कशीट जोड़ने का शॉर्टकट कौन-सा है?", ["Shift + F11", "Ctrl + N", "Ctrl + W", "Alt + F4"], "Shift + F11 नई वर्कशीट जोड़ता है। Ctrl + N नई वर्कबुक बनाता है, Ctrl + W वर्कबुक बंद करता है और Alt + F4 Excel बंद करता है।"]),
  q(0, "computer", "ms-office", "M", 2,
    ["Which Excel feature quickly summarises a large table by grouping and totalling data, for example total sales by district?", ["Freeze Panes", "Conditional Formatting", "PivotTable", "Flash Fill"], "A PivotTable (Insert tab) groups, totals, averages and counts large data in a few clicks, and its layout can be changed by dragging fields."],
    ["Excel की कौन-सी सुविधा बड़ी तालिका के डेटा को समूहित और जोड़कर जल्दी सारांश बनाती है, जैसे ज़िलेवार कुल बिक्री?", ["Freeze Panes", "Conditional Formatting", "PivotTable", "Flash Fill"], "PivotTable (Insert टैब) बड़े डेटा को कुछ ही क्लिक में समूहित करके उसका योग, औसत और गिनती निकालती है, और फ़ील्ड खींचकर इसका लेआउट बदला जा सकता है।"]),
  q(0, "computer", "ms-office", "M", 0,
    ["In MS Excel, what is Freeze Panes used for?", ["Keeping chosen rows or columns visible while you scroll", "Locking the file with a password", "Stopping formulas from recalculating", "Hiding the gridlines"], "Freeze Panes (View tab) keeps selected rows or columns, such as headings, visible while you scroll through the rest of the sheet."],
    ["MS Excel में Freeze Panes का उपयोग किसलिए होता है?", ["स्क्रॉल करते समय चुनी गई पंक्तियाँ या कॉलम दिखते रहें", "फ़ाइल को पासवर्ड से लॉक करना", "सूत्रों की पुनर्गणना रोकना", "ग्रिडलाइन छिपाना"], "Freeze Panes (View टैब) चुनी गई पंक्तियों या कॉलमों, जैसे शीर्षकों, को शीट के बाकी हिस्से में स्क्रॉल करते समय दिखाता रहता है।"]),
  q(0, "computer", "ms-office", "M", 1,
    ["What does `=AVERAGE(4, 8, 12, 0)` return?", ["8", "6", "24", "12"], "AVERAGE adds the numbers and divides by how many there are: (4 + 8 + 12 + 0) ÷ 4 = 6. A zero counts as a value (an empty cell would be ignored)."],
    ["`=AVERAGE(4, 8, 12, 0)` क्या लौटाता है?", ["8", "6", "24", "12"], "AVERAGE संख्याओं को जोड़कर उनकी गिनती से भाग देता है: (4 + 8 + 12 + 0) ÷ 4 = 6। शून्य को एक मान माना जाता है (खाली सेल को छोड़ दिया जाता है)।"], "(4 + 8 + 12 + 0) / 4"),
  q(0, "computer", "ms-office", "M", 3,
    ["Which chart type is best for showing each part's share of a whole, such as how a budget is divided?", ["Line chart", "Scatter chart", "Column chart", "Pie chart"], "A pie chart shows the parts of a whole as slices of a circle. Line charts show trends over time, and scatter charts show the relation between two variables."],
    ["किसी संपूर्ण में प्रत्येक भाग का हिस्सा दिखाने के लिए, जैसे बजट का बँटवारा, कौन-सा चार्ट सबसे उपयुक्त है?", ["लाइन चार्ट", "स्कैटर चार्ट", "कॉलम चार्ट", "पाई चार्ट"], "पाई चार्ट संपूर्ण के हिस्सों को वृत्त के टुकड़ों के रूप में दिखाता है। लाइन चार्ट समय के साथ प्रवृत्ति और स्कैटर चार्ट दो चरों का संबंध दिखाते हैं।"]),
  q(0, "computer", "shortcuts", "H", 2,
    ["In MS Excel, what does the shortcut Ctrl + ; (semicolon) enter in the active cell?", ["The current time", "A new row", "Today's date", "A comment"], "Ctrl + ; enters today's date as a fixed value and Ctrl + Shift + ; enters the current time. The TODAY() function, by contrast, updates every day."],
    ["MS Excel में Ctrl + ; (अर्धविराम) शॉर्टकट सक्रिय सेल में क्या डालता है?", ["वर्तमान समय", "नई पंक्ति", "आज की तिथि", "टिप्पणी"], "Ctrl + ; आज की तिथि स्थिर मान के रूप में डालता है और Ctrl + Shift + ; वर्तमान समय डालता है। इसके विपरीत TODAY() फ़ंक्शन हर दिन बदल जाता है।"]),
  q(0, "computer", "ms-office", "H", 3,
    ["What does `=INT(-4.3)` return in MS Excel?", ["-4", "4", "5", "-5"], "INT rounds a number down to the nearest integer. For -4.3 the next lower integer is -5, not -4. (TRUNC(-4.3) would give -4.)"],
    ["MS Excel में `=INT(-4.3)` क्या लौटाता है?", ["-4", "4", "5", "-5"], "INT किसी संख्या को नीचे की ओर निकटतम पूर्णांक तक ले जाता है। -4.3 से नीचे का अगला पूर्णांक -5 है, -4 नहीं। (TRUNC(-4.3) से -4 मिलता।)"], "Math.floor(-4.3)"),
  q(0, "computer", "ms-office", "M", 2,
    ["What does `=MOD(17, 5)` return?", ["3", "12", "2", "5"], "MOD returns the remainder after division: 17 ÷ 5 = 3 remainder 2."],
    ["`=MOD(17, 5)` क्या लौटाता है?", ["3", "12", "2", "5"], "MOD भाग देने के बाद शेषफल लौटाता है: 17 ÷ 5 = 3, शेष 2।"], "17 % 5"),
  q(0, "computer", "ms-office", "M", 0,
    ["Which Excel feature changes a cell's colour automatically when its value meets a rule, for example marks below 33 shown in red?", ["Conditional Formatting", "Data Validation", "Goal Seek", "AutoSum"], "Conditional Formatting (Home tab) applies colours, icons or data bars based on rules. Data Validation controls what can be typed into a cell."],
    ["Excel की कौन-सी सुविधा किसी नियम के पूरा होने पर सेल का रंग अपने-आप बदल देती है, जैसे 33 से कम अंक लाल रंग में?", ["Conditional Formatting", "Data Validation", "Goal Seek", "AutoSum"], "Conditional Formatting (Home टैब) नियमों के आधार पर रंग, आइकन या डेटा बार लगाती है। Data Validation नियंत्रित करता है कि सेल में क्या लिखा जा सकता है।"]),
  q(0, "computer", "ms-office", "M", 1,
    ["An Excel cell shows `#####` instead of a number. This usually means:", ["The formula has an error", "The column is too narrow to display the value", "The cell is locked", "The value is stored as text"], "`#####` appears when a number or date is too wide for the column; widen the column (or double-click its border) to see the value. It can also appear for a negative date or time."],
    ["Excel का कोई सेल संख्या के स्थान पर `#####` दिखाता है। इसका सामान्यतः अर्थ है:", ["सूत्र में त्रुटि है", "मान दिखाने के लिए कॉलम बहुत संकरा है", "सेल लॉक है", "मान पाठ के रूप में संग्रहीत है"], "`#####` तब दिखता है जब संख्या या तिथि कॉलम से चौड़ी हो; मान देखने के लिए कॉलम चौड़ा करें (या उसकी सीमा पर डबल-क्लिक करें)। ऋणात्मक तिथि या समय होने पर भी यह दिख सकता है।"]),
  q(0, "computer", "ms-office", "H", 2,
    ["What is the result of `=2+3*4^2` in MS Excel?", ["400", "146", "50", "196"], "Excel works in this order: `^` (power) first, then `*` and `/`, then `+` and `-`. So 4^2 = 16, 3 × 16 = 48 and 2 + 48 = 50."],
    ["MS Excel में `=2+3*4^2` का परिणाम क्या है?", ["400", "146", "50", "196"], "Excel इस क्रम से गणना करता है: पहले `^` (घात), फिर `*` और `/`, फिर `+` और `-`। अतः 4^2 = 16, 3 × 16 = 48 और 2 + 48 = 50।"], "2 + 3 * 4 ** 2"),
];
