// HP Patwari recruitment exam 2013 — transcribed from the solved paper, which prints the answer key; every answer was
// re-checked independently. Left out because the question needs a figure or the printed options are unclear. Option order is kept as printed.
// Sections: 0 Mathematics (Q1-25), 1 English (Q26-50), 2 Hindi (Q51-75), 3 General Knowledge (Q76-100).

import { q, type PatwariQuestion } from "../patwari/types";

export const PATWARI_2013_SECTIONS = [
  { name: "Mathematics", nameHi: "अंकगणित / गणित" },
  { name: "English", nameHi: "अंग्रेज़ी" },
  { name: "Hindi", nameHi: "हिन्दी" },
  { name: "General Knowledge", nameHi: "सामान्य ज्ञान" },
];

const PASSAGE =
  "Passage: In March, the family sat down at the table and began to talk about the summer holiday. Where should they go this year? That was the question which had to be answered. Should they go to the sea-side, or to the country? Did they prefer fun on the farm to basking on a beach? The children soon settled that. With one voice they cried, \"sea-side, please!\" \"Let's go somewhere where there is good swimming,\" said Sally, who had just won her life-saving certificate, \"and good fishing,\" said Alan, who had been given a smart rod for his birthday. \"What about mountain climbing?\" Paul asked. He had been to Switzerland, the year before, with the Scout trip. \"Your mother and I just want to sit on a beach,\" said father, \"that is, if you don't mind, of course\". \"Two deck-chairs for a fortnight for mother and father. Then everyone will be happy,\" the children cried.";
const PASSAGE_HI =
  "अनुच्छेद (सार): मार्च में परिवार मेज़ पर बैठा और गर्मी की छुट्टियों के बारे में बात करने लगा — समुद्र किनारे जाएँ या गाँव? बच्चों ने एक स्वर में कहा, \"समुद्र किनारा!\" सैली को अच्छी तैराकी चाहिए थी, एलन को मछली पकड़ना, और पॉल को पर्वतारोहण। पिता ने कहा कि वे और माँ बस समुद्र तट पर बैठना चाहते हैं। बच्चे चिल्लाए, \"माँ और पिताजी के लिए पखवाड़े भर दो डेक-चेयर, तब सब खुश रहेंगे!\"";

export const y2013: PatwariQuestion[] = [
  // ───────── Section 0: Mathematics ─────────
  q(0, "quant", "number-system", "M", 2, ["Which fraction lies between 3/5 and 4/5?", ["8/20", "11/20", "14/20", "17/20"], "3/5 = 12/20 and 4/5 = 16/20, so 14/20 lies between them."], ["निम्नलिखित में से कौन-सी भिन्न 3/5 और 4/5 के बीच स्थित है?", ["8/20", "11/20", "14/20", "17/20"], "3/5 = 12/20 और 4/5 = 16/20, अतः 14/20 इनके बीच है।"]),
  q(0, "quant", "algebra", "E", 1, ["What is the degree of the polynomial 5x³ − 4x² + 7x?", ["5", "3", "4", "2"], "The highest power of x is 3."], ["बहुपद 5x³ − 4x² + 7x की घात क्या है?", ["5", "3", "4", "2"], "x की सबसे बड़ी घात 3 है।"]),
  q(0, "quant", "algebra", "M", 2, ["Which of the following is not a solution of x + 2y = 6?", ["(2, 2)", "(3, 3)", "(4, 1)", "(6, 0)"], "(2, 2): 2 + 4 = 6 ✓; (4, 1): 4 + 2 = 6 ✓; (6, 0): 6 ✓; (3, 3): 3 + 6 = 9 ≠ 6, so (3, 3) is not a solution."], ["निम्नलिखित में से कौन-सा x + 2y = 6 का हल नहीं है?", ["(2, 2)", "(3, 3)", "(4, 1)", "(6, 0)"], "(2, 2): 2 + 4 = 6 ✓; (4, 1): 6 ✓; (6, 0): 6 ✓; (3, 3): 3 + 6 = 9 ≠ 6। अतः हल न होने वाला (3, 3) है।"]),
  q(0, "quant", "average", "E", 3, ["What is the average of the first five multiples of 3?", ["9", "18", "27", "36"], "3 + 6 + 9 + 12 + 15 = 45, and 45 ÷ 5 = 9."], ["3 के प्रथम पाँच गुणजों का औसत है:", ["9", "18", "27", "36"], "3 + 6 + 9 + 12 + 15 = 45, और 45 ÷ 5 = 9।"]),
  q(0, "quant", "hcf-lcm", "M", 0, ["The HCF of two numbers is 7 and the LCM is 210. If one number is 35, what is the other?", ["42", "43", "44", "45"], "Product = 7 × 210 = 1470, so the other number = 1470 ÷ 35 = 42."], ["दो संख्याओं का HCF 7 है और LCM 210 है। यदि एक संख्या 35 है तो दूसरी संख्या क्या होगी?", ["42", "43", "44", "45"], "गुणनफल = 7 × 210 = 1470, अतः दूसरी संख्या = 1470 ÷ 35 = 42।"]),
  q(0, "quant", "ratio-proportion", "E", 1, ["The diameters of two circles are 8 cm and 10 cm. Find the ratio of their circumferences.", ["8 : 10", "4 : 5", "10 : 8", "5 : 4"], "Circumference is proportional to the diameter, so the ratio is 8 : 10 = 4 : 5."], ["दो वृत्तों के व्यास क्रमशः 8 सेमी और 10 सेमी हैं। उनकी परिधि का अनुपात ज्ञात कीजिए।", ["8 : 10", "4 : 5", "10 : 8", "5 : 4"], "परिधि व्यास के समानुपाती होती है, अतः अनुपात 8 : 10 = 4 : 5।"]),
  q(0, "quant", "average", "M", 1, ["The heights (in cm) of nine persons are 155, 160, 145, 149, 150, 147, 152, 144, 148. Find the median height.", ["147 cm", "148 cm", "149 cm", "150 cm"], "In order: 144, 145, 147, 148, 149, 150, 152, 155, 160. The 5th value is 149 cm."], ["नौ व्यक्तियों की लम्बाइयाँ (सेमी में) 155, 160, 145, 149, 150, 147, 152, 144, 148 हैं। माध्य लम्बाई ज्ञात कीजिए।", ["147 सेमी", "148 सेमी", "149 सेमी", "150 सेमी"], "क्रम में: 144, 145, 147, 148, 149, 150, 152, 155, 160। पाँचवाँ मान 149 सेमी है।"]),
  q(0, "quant", "algebra", "M", 3, ["Factorise: 12x² − 7x + 1", ["(4x − 1)(1 − 3x)", "(4x + 1)(3x + 1)", "(4x − 2)(3x − 2)", "(4x − 1)(3x − 1)"], "12x² − 7x + 1 = (4x − 1)(3x − 1), since 4 × 3 = 12, and −3 − 4 = −7."], ["गुणनखण्ड ज्ञात कीजिए: 12x² − 7x + 1", ["(4x − 1)(1 − 3x)", "(4x + 1)(3x + 1)", "(4x − 2)(3x − 2)", "(4x − 1)(3x − 1)"], "12x² − 7x + 1 = (4x − 1)(3x − 1), क्योंकि 4 × 3 = 12 और −3 − 4 = −7।"]),
  q(0, "quant", "simplification", "M", 0, ["Find the value of (102)³.", ["1061208", "1601208", "1601028", "1126008"], "102³ = 1,061,208."], ["मान ज्ञात कीजिए: (102)³", ["1061208", "1601208", "1601028", "1126008"], "102³ = 10,61,208।"]),
  q(0, "quant", "algebra", "M", 0, ["Find the value of K in 2x + 3y = K when x = 2 and y = 1.", ["7", "8", "9", "0"], "K = 2(2) + 3(1) = 7."], ["समीकरण 2x + 3y = K में K का मान ज्ञात कीजिए, जबकि x = 2 तथा y = 1 हो।", ["7", "8", "9", "0"], "K = 2(2) + 3(1) = 7।"]),
  q(0, "quant", "number-system", "M", 3, ["The product of two consecutive positive integers is 306. Find the integers.", ["(17, 18)", "(15, 16)", "(8, 9)", "(18, 19)"], "17 × 18 = 306."], ["दो क्रमागत धनात्मक पूर्णांकों का गुणनफल 306 है। पूर्णांक ज्ञात कीजिए।", ["(17, 18)", "(15, 16)", "(8, 9)", "(18, 19)"], "17 × 18 = 306।"]),
  q(0, "quant", "algebra", "H", 1, ["Find the roots of the quadratic equation 2x² + x + 4 = 0.", ["(1 ± √−31)/4", "(−1 ± √−31)/4", "(−1 ± √31)/4", "(1 ± √31)/4"], "x = [−1 ± √(1 − 32)]/4 = (−1 ± √−31)/4."], ["द्विघात समीकरण के मूल ज्ञात कीजिए: 2x² + x + 4 = 0", ["(1 ± √−31)/4", "(−1 ± √−31)/4", "(−1 ± √31)/4", "(1 ± √31)/4"], "x = [−1 ± √(1 − 32)]/4 = (−1 ± √−31)/4।"]),
  q(0, "quant", "geometry", "M", 3, ["If the base of a right-angled triangle is 10 cm and the hypotenuse is 15 cm, find the perpendicular.", ["2√5 cm", "4√5 cm", "5√5 cm", "6√5 cm"], "Perpendicular = √(15² − 10²) = √125 = 5√5 cm."], ["यदि एक समकोण त्रिभुज का आधार 10 सेमी तथा कर्ण 15 सेमी हो तो लम्ब ज्ञात कीजिए।", ["2√5 सेमी", "4√5 सेमी", "5√5 सेमी", "6√5 सेमी"], "लम्ब = √(15² − 10²) = √125 = 5√5 सेमी।"]),
  q(0, "quant", "mensuration", "M", 0, ["Find the volume of a sphere whose radius is 7 cm.", ["1437.3 cm³", "1743.3 cm³", "1473.3 cm³", "1347.3 cm³"], "(4/3) × (22/7) × 7³ = 1437.33 cm³."], ["एक गोले का आयतन ज्ञात कीजिए, जिसकी त्रिज्या 7 सेमी है।", ["1437.3 सेमी³", "1743.3 सेमी³", "1473.3 सेमी³", "1347.3 सेमी³"], "(4/3) × (22/7) × 7³ = 1437.33 सेमी³।"]),
  q(0, "quant", "mensuration", "M", 3, ["A cuboid box measures 15 cm × 12 cm × 5 cm. Find its total surface area.", ["630 cm²", "600 cm²", "603 cm²", "660 cm²"], "TSA = 2(15×12 + 12×5 + 5×15) = 2(180 + 60 + 75) = 630 cm²."], ["एक घनाकार डिब्बे की माप 15 सेमी × 12 सेमी × 5 सेमी है। इस डिब्बे का कुल पृष्ठीय क्षेत्रफल ज्ञात कीजिए।", ["630 सेमी²", "600 सेमी²", "603 सेमी²", "660 सेमी²"], "कुल पृष्ठीय क्षेत्रफल = 2(15×12 + 12×5 + 5×15) = 2(180 + 60 + 75) = 630 सेमी²।"]),
  q(0, "quant", "mensuration", "M", 1, ["Find the surface area of a sphere of radius 14 cm.", ["2664 cm²", "2464 cm²", "2446 cm²", "2644 cm²"], "4πr² = 4 × (22/7) × 196 = 2464 cm²."], ["त्रिज्या 14 सेमी वाले गोले का पृष्ठीय क्षेत्रफल ज्ञात कीजिए।", ["2664 सेमी²", "2464 सेमी²", "2446 सेमी²", "2644 सेमी²"], "4πr² = 4 × (22/7) × 196 = 2464 सेमी²।"]),
  q(0, "quant", "number-system", "M", 2, ["A bag has 3 red and 5 black balls. One ball is drawn at random. What is the probability that the ball is red?", ["3/8", "2/8", "5/8", "1"], "P(red) = 3/8."], ["एक थैले में 3 लाल और 5 काली गेंदें हैं। इस थैले में से एक गेंद यादृच्छया निकाली जाती है। इसकी क्या प्रायिकता है कि गेंद लाल हो?", ["3/8", "2/8", "5/8", "1"], "लाल गेंद की प्रायिकता = 3/8।"]),

  // ───────── Section 1: English ─────────
  q(1, "english", "comprehension", "E", 3, [`${PASSAGE} — Why was a family meeting held at the table?`, ["To discuss some quarrel concerned with the family", "To inform the children about a function to be held after sometime", "To plan an excursion for site seeing", "To plan the programme for summer holiday"], "The family sat at the table to talk about the summer holiday."], [`${PASSAGE_HI} — परिवार की बैठक मेज़ पर क्यों हुई?`, ["परिवार के किसी झगड़े पर चर्चा के लिए", "बच्चों को कुछ समय बाद होने वाले समारोह की सूचना देने के लिए", "दर्शनीय स्थलों की सैर की योजना बनाने के लिए", "गर्मी की छुट्टियों का कार्यक्रम बनाने के लिए"], "परिवार गर्मी की छुट्टियों के बारे में बात करने के लिए मेज़ पर बैठा।"]),
  q(1, "english", "comprehension", "E", 3, [`${PASSAGE} — What was their decision regarding the summer holiday?`, ["To go to Switzerland where Paul had gone on Scout trip", "To go to the countryside to enjoy fun on the farm", "To go on a continental tour of Europe", "To go to sea-side for enjoyment"], "The children cried 'sea-side, please!' and the parents agreed."], [`${PASSAGE_HI} — गर्मी की छुट्टियों के बारे में उनका निर्णय क्या था?`, ["स्विट्ज़रलैंड जाना जहाँ पॉल स्काउट यात्रा पर गया था", "फार्म पर आनंद के लिए देहात जाना", "यूरोप की महाद्वीपीय यात्रा पर जाना", "आनंद के लिए समुद्र किनारे जाना"], "बच्चों ने 'समुद्र किनारा' कहा और माता-पिता सहमत हो गए।"]),
  q(1, "english", "comprehension", "M", 2, [`${PASSAGE} — What was an alternate programme before the family?`, ["To go to their home village into the interior", "To go to see their relations in different places", "To go to the country", "To arrange vacation programme for the children"], "The alternative to the sea-side was going to the country(side)."], [`${PASSAGE_HI} — परिवार के सामने वैकल्पिक कार्यक्रम क्या था?`, ["अपने गाँव के भीतरी भाग में जाना", "अलग-अलग जगह रिश्तेदारों से मिलने जाना", "देहात जाना", "बच्चों के लिए अवकाश कार्यक्रम बनाना"], "समुद्र किनारे का विकल्प देहात जाना था।"]),
  q(1, "english", "comprehension", "M", 1, [`${PASSAGE} — How was the decision taken by the family?`, ["The programme was discussed by all and the majority decision taken", "Programme was decided by the children and okayed by parents", "Mother suggested it and it was okayed by the children", "Father suggested an alternative programme and it was chosen by them unanimously"], "The children decided on the sea-side and the parents were happy to go along."], [`${PASSAGE_HI} — परिवार ने निर्णय कैसे लिया?`, ["सभी ने चर्चा की और बहुमत का निर्णय लिया गया", "कार्यक्रम बच्चों ने तय किया और माता-पिता ने स्वीकृति दी", "माँ ने सुझाया और बच्चों ने स्वीकृति दी", "पिता ने वैकल्पिक कार्यक्रम सुझाया और सबने सर्वसम्मति से चुना"], "बच्चों ने समुद्र किनारा तय किया और माता-पिता ने साथ दिया।"]),
  q(1, "english", "comprehension", "M", 3, [`${PASSAGE} — What was the idea of deck-chairs for parents?`, ["Because the parents always preferred deck-chairs", "Because children wanted their parents to witness their enjoyment on the sea-side", "Because their mother wanted as such", "Because it was the desire of their father"], "Father said that he and mother just wanted to sit on a beach, so the deck-chairs were for his wish."], [`${PASSAGE_HI} — माता-पिता के लिए डेक-चेयर का विचार क्या था?`, ["क्योंकि माता-पिता हमेशा डेक-चेयर पसंद करते थे", "क्योंकि बच्चे चाहते थे कि माता-पिता समुद्र तट पर उनका आनंद देखें", "क्योंकि उनकी माँ ऐसा चाहती थीं", "क्योंकि यह उनके पिता की इच्छा थी"], "पिता ने कहा कि वे और माँ बस तट पर बैठना चाहते हैं, इसलिए यह पिता की इच्छा थी।"]),
  q(1, "english", "grammar", "M", 3, ["Don't disturb me, I ................. my home work.", ["do", "did", "does", "am doing"], "The action is in progress now: 'am doing'."], ["Don't disturb me, I ................. my home work.", ["do", "did", "does", "am doing"], "क्रिया अभी हो रही है: 'am doing'।"]),
  q(1, "english", "grammar", "M", 1, ["'Choose' changes in past continuous as:", ["choosed", "was choosing", "was chosen", "were choosing"], "Past continuous of 'I choose' is 'I was choosing'."], ["'Choose' का past continuous रूप है:", ["choosed", "was choosing", "was chosen", "were choosing"], "'I choose' का past continuous 'I was choosing' है।"]),
  q(1, "english", "grammar", "E", 1, ["The comparative degree of 'Good' is:", ["Best", "Better", "Gooder", "Goodly"], "good → better → best."], ["'Good' की comparative degree है:", ["Best", "Better", "Gooder", "Goodly"], "good → better → best।"]),
  q(1, "english", "grammar", "M", 0, ["The noun of 'Invite' is:", ["Invitation", "Invited", "Invitee", "Invite"], "The noun form of the verb 'invite' is 'invitation'."], ["'Invite' की संज्ञा है:", ["Invitation", "Invited", "Invitee", "Invite"], "क्रिया 'invite' की संज्ञा 'invitation' है।"]),
  q(1, "english", "voice-speech", "H", 3, ["Choose the correct form of voice: Will Ritu have sung a song?", ["Will a song have sung by Ritu?", "Will a song have been sung by Ritu?", "Will a song been have sung by Ritu?", "Will a song been sung by Ritu?"], "Future perfect passive: 'Will a song have been sung by Ritu?'."], ["Voice का सही रूप चुनिए: Will Ritu have sung a song?", ["Will a song have sung by Ritu?", "Will a song have been sung by Ritu?", "Will a song been have sung by Ritu?", "Will a song been sung by Ritu?"], "future perfect का passive: 'Will a song have been sung by Ritu?'"]),
  q(1, "english", "one-word", "M", 1, ["Choose the correct word: Want or lack of rain.", ["Draught", "Drought", "Desert", "Dry land"], "Lack of rain is a drought."], ["सही शब्द चुनिए: वर्षा की कमी या अभाव।", ["Draught", "Drought", "Desert", "Dry land"], "वर्षा के अभाव को drought (सूखा) कहते हैं।"]),
  q(1, "english", "one-word", "M", 2, ["Choose the correct word: A thing which must happen.", ["Unavoiding", "Expected", "Inevitable", "Eventful"], "A thing that cannot be avoided is inevitable."], ["सही शब्द चुनिए: वह वस्तु जो अवश्य होनी है।", ["Unavoiding", "Expected", "Inevitable", "Eventful"], "जिससे बचा नहीं जा सकता वह inevitable (अपरिहार्य) है।"]),
  q(1, "english", "grammar", "M", 3, ["Choose the correct option to complete the sentence: The news is too good ................", ["to true", "not true", "to be not true", "to be true"], "'Too good to be true' is the fixed expression."], ["वाक्य पूरा करने के लिए सही विकल्प चुनिए: The news is too good ................", ["to true", "not true", "to be not true", "to be true"], "'too good to be true' निश्चित वाक्यांश है।"]),
  q(1, "english", "spelling", "M", 1, ["Choose the correct spelling.", ["Consede", "Concede", "Consead", "Conceade"], "The correct spelling is 'concede'."], ["सही वर्तनी चुनिए।", ["Consede", "Concede", "Consead", "Conceade"], "सही वर्तनी 'concede' है।"]),
  q(1, "english", "grammar", "E", 0, ["It has been raining ............ morning.", ["since", "to", "for", "in"], "'Since' is used with a point in time: since morning."], ["It has been raining ............ morning.", ["since", "to", "for", "in"], "समय-बिंदु के साथ 'since' आता है: since morning।"]),
  q(1, "english", "grammar", "E", 2, ["The bus driver .............. asleep while he was driving.", ["falls", "had fallen", "fell", "fallen"], "The action is in the simple past: 'fell asleep'."], ["The bus driver .............. asleep while he was driving.", ["falls", "had fallen", "fell", "fallen"], "क्रिया simple past में है: 'fell asleep'।"]),
  q(1, "english", "one-word", "M", 1, ["Choose the correct word: To carry away a person by force or fraud.", ["Attack", "Kidnap", "Hijack", "Steal"], "To carry off a person by force or fraud is to kidnap."], ["सही शब्द चुनिए: किसी व्यक्ति को बल या छल से ले जाना।", ["Attack", "Kidnap", "Hijack", "Steal"], "किसी व्यक्ति को बलपूर्वक या छल से ले जाना kidnap (अपहरण) है।"]),
  q(1, "english", "grammar", "E", 1, ["Fill in the blank with a suitable article: Today is .............. first day of April.", ["that", "the", "an", "a"], "'The' is used before ordinal numbers: the first day."], ["उपयुक्त article से रिक्त स्थान भरिए: Today is .............. first day of April.", ["that", "the", "an", "a"], "क्रमवाचक संख्या से पहले 'the' आता है।"]),
  q(1, "english", "grammar", "E", 0, ["Fill in the blank with a suitable article: Honest men speak .............. truth.", ["the", "a", "of", "an"], "'The truth' is a specific, definite reference."], ["उपयुक्त article से रिक्त स्थान भरिए: Honest men speak .............. truth.", ["the", "a", "of", "an"], "'the truth' निश्चित संदर्भ है।"]),
  q(1, "english", "synonyms-antonyms", "M", 0, ["Choose the word similar in meaning to: PREJUDICE", ["Bias", "Offence", "Prelude", "To decide"], "Prejudice means bias."], ["समानार्थी चुनिए: PREJUDICE", ["Bias", "Offence", "Prelude", "To decide"], "Prejudice का अर्थ पूर्वाग्रह (bias) है।"]),
  q(1, "english", "synonyms-antonyms", "M", 2, ["Choose the word similar in meaning to: STOOP", ["Subscribe", "Sympathise", "To bow", "Tamper"], "To stoop is to bend or bow down."], ["समानार्थी चुनिए: STOOP", ["Subscribe", "Sympathise", "To bow", "Tamper"], "stoop का अर्थ झुकना (to bow) है।"]),
  q(1, "english", "one-word", "M", 2, ["What is an autobiography?", ["A description of someone's travel", "A song or a poem that tells a story", "A story of one's own life", "Free verse"], "An autobiography is a story of one's own life written by oneself."], ["सही विकल्प चुनिए: आत्मकथा (autobiography) क्या है?", ["किसी की यात्रा का वर्णन", "कहानी सुनाने वाला गीत या कविता", "अपने जीवन की कहानी", "मुक्त छंद"], "आत्मकथा अपने ही जीवन की स्वयं लिखी कहानी है।"]),
  q(1, "english", "voice-speech", "M", 2, ["Choose the correct form of Active/Passive Voice: He has finished his meal.", ["His meal has being finished by him.", "His meal has finished by him.", "His meal has been finished by him.", "His meal had been finished by him."], "Present perfect passive: 'has been finished'."], ["Active/Passive का सही रूप चुनिए: He has finished his meal.", ["His meal has being finished by him.", "His meal has finished by him.", "His meal has been finished by him.", "His meal had been finished by him."], "present perfect का passive: 'has been finished'।"]),
  q(1, "english", "grammar", "M", 3, ["Choose the suitable preposition: The hunter aimed .............. the tiger.", ["on", "in", "to", "at"], "'Aim at' is the correct collocation."], ["उपयुक्त preposition चुनिए: The hunter aimed .............. the tiger.", ["on", "in", "to", "at"], "'aim at' सही प्रयोग है।"]),
  q(1, "english", "grammar", "M", 1, ["Choose the suitable preposition: Your work is .............. the average.", ["beneath", "below", "under", "beside"], "'Below the average' is the usual expression."], ["उपयुक्त preposition चुनिए: Your work is .............. the average.", ["beneath", "below", "under", "beside"], "'below the average' प्रचलित प्रयोग है।"]),

  // ───────── Section 2: Hindi ─────────
  q(2, "hindi", "vyakaran", "M", 3, ["Passage: 'वास्तव में हृदय वही है जो कोमल भावों और स्वदेश प्रेम से ओतप्रोत हो… देश-प्रेम के लिए किसी आकर्षण की आवश्यकता नहीं होती, बल्कि वह तो अपनी भूमि के प्रति मनुष्य मात्र की स्वाभाविक ममता है…' — What is the meaning of 'देश-प्रेम'?", ["Rise of soft feelings towards the country", "Building the country with tireless effort", "Fighting enemies for the country's interest", "A person's natural affection for his country"], "The passage calls it a person's natural attachment (mamta) to his own land."], ["अनुच्छेद: 'वास्तव में हृदय वही है जो कोमल भावों और स्वदेश प्रेम से ओतप्रोत हो… देश-प्रेम के लिए किसी आकर्षण की आवश्यकता नहीं होती, बल्कि वह तो अपनी भूमि के प्रति मनुष्य मात्र की स्वाभाविक ममता है…' — देश-प्रेम का अभिप्राय है:", ["देश के प्रति कोमल भावों का उदय", "अनथक प्रयत्न करके देश का निर्माण करना", "देश हित के लिए शत्रु से संघर्ष करना", "देश के प्रति व्यक्ति का स्वाभाविक ममत्व"], "अनुच्छेद इसे अपनी भूमि के प्रति मनुष्य की स्वाभाविक ममता कहता है।"]),
  q(2, "hindi", "vyakaran", "M", 2, ["Same passage: A true patriot is one who:", ["Narrates tales of brave sons", "Raises slogans for the motherland", "Stands the test when the hour of trial comes", "Donates his land for the country"], "The passage says that those who talk of sacrifice but run away at the time of trial are not true patriots; the true one stands the test."], ["उसी अनुच्छेद के अनुसार सच्चा देश-प्रेमी वह है जो:", ["वीर सपूतों की कहानियाँ सुनाता है", "मातृभूमि का जयघोष करता है", "परीक्षा की कसौटी पर खरा उतरता है", "अपनी भूमि देश के लिए दान कर देता है"], "अनुच्छेद के अनुसार जो त्याग की बातें करे पर परीक्षा की घड़ी में भाग खड़ा हो, वह सच्चा देश-प्रेमी नहीं; सच्चा वही जो कसौटी पर खरा उतरे।"]),
  q(2, "hindi", "vyakaran", "M", 2, ["Same passage: Why do birds return to their nests at dusk?", ["They get tired after roaming all day", "They want to rest at night", "Animals also go back to their dwelling places", "They love their nest"], "As per the official key, the reason given is that animals and birds return to their places of dwelling (an instinctive love for home)."], ["उसी अनुच्छेद के अनुसार संध्या समय पक्षी अपने घोंसलों में वापिस चले जाते हैं, क्योंकि:", ["दिन-भर घूमकर वे थक जाते हैं", "उन्हें रात को आराम करना है", "जानवर भी अपने निवास-स्थान को चले जाते हैं", "उन्हें अपना नीड़ प्यारा होता है"], "आधिकारिक कुंजी के अनुसार पशु-पक्षी सभी अपने निवास-स्थान को लौटते हैं (घर के प्रति स्वाभाविक लगाव)।"]),
  q(2, "hindi", "vyakaran", "M", 3, ["Same passage: That country alone is great whose people:", ["Are educated and trained", "Are neither unemployed nor idle", "Earn wealth through agriculture and trade", "Always stay ahead in sacrifice and dedication"], "The passage values sacrifice (tyag) and dedication (utsarg) as the proof of love for one's country."], ["उसी अनुच्छेद के अनुसार वही देश महान् है जहाँ के लोग:", ["शिक्षित और प्रशिक्षित हैं", "बेरोजगार तथा निरुद्यमी नहीं हैं", "कृषि और व्यापार से धनार्जन करते हैं", "त्याग और उत्सर्ग से सदा आगे रहते हैं"], "अनुच्छेद देश-प्रेम की पहचान त्याग और उत्सर्ग को मानता है।"]),
  q(2, "hindi", "vyakaran", "M", 1, ["Same passage: The seed of patriotism exists in:", ["All humans", "All living beings", "All birds", "All animals"], "The passage says the seed of patriotism exists in all (humans, animals and birds); of the options, 'all living beings' covers them all."], ["उसी अनुच्छेद के अनुसार देश-प्रेम का अंकुर विद्यमान है:", ["सभी मानवों में", "सभी प्राणियों में", "सभी पक्षियों में", "सभी पशुओं में"], "अनुच्छेद के अनुसार देश-प्रेम का अंकुर मानव, पशु और पक्षी सभी में है; विकल्पों में 'सभी प्राणियों में' सबको समेटता है।"]),
  q(2, "hindi", "paryay-vilom", "M", 3, ["The antonym of 'आगामी' is:", ["बीता हुआ", "आगत", "विगत", "अनागत"], "'आगामी' means upcoming; its opposite is 'विगत' (gone by)."], ["'आगामी' का विलोम शब्द होता है:", ["बीता हुआ", "आगत", "विगत", "अनागत"], "'आगामी' (आने वाला) का विलोम 'विगत' (बीता हुआ) है।"]),
  q(2, "hindi", "vyakaran", "H", 3, ["\"सुभाष ने देश के लिए पढ़ाई छोड़ी; आराम छोड़े; नौकरी छोड़ी; यहाँ तक कि पूरी जिन्दगी दाँव पर लगा दी।\" Which punctuation marks are used in this sentence?", ["Semicolon and full stop", "Comma and full stop", "Sub-colon and full stop", "Hyphen and full stop"], "As per the official key, the marks used are the semicolon (अर्द्धविराम) along with the full stop (पूर्णविराम)."], ["सुभाष ने देश के लिए पढ़ाई छोड़ी; आराम छोड़ा; नौकरी छोड़ी; यहाँ तक कि पूरी जिन्दगी दाँव पर लगा दी। वाक्य में प्रयुक्त कौन-कौन से विराम चिह्न हैं?", ["अर्द्धविराम और पूर्णविराम", "अल्पविराम व पूर्णविराम", "उपविराम और पूर्णविराम", "समासक चिह्न व पूर्णविराम"], "आधिकारिक कुंजी के अनुसार अर्द्धविराम (;) तथा पूर्णविराम (।) प्रयुक्त हैं।"]),
  q(2, "hindi", "muhavare", "M", 3, ["What is the meaning of the proverb 'ओछे की प्रीत बालू की भीत'?", ["Fear of elders from love for the small", "Fear of strangers from friendship with one's own", "Little love, great fear", "The friendship of the wicked ends quickly"], "The friendship of mean persons is like a wall of sand: it ends quickly."], ["'ओछे की प्रीत बालू की भीत' कहावत का अर्थ इनमें से कौन-सा है?", ["छोटों से प्यार बड़ों से डर", "अपनों से मित्रता दूसरों से डर", "थोड़ा प्यार अधिक डर", "दुष्टों की मित्रता शीघ्र समाप्त"], "ओछे व्यक्ति की मित्रता बालू की दीवार जैसी है, जो जल्दी टूट जाती है।"]),
  q(2, "hindi", "ek-shabd", "M", 0, ["The one word for the phrase 'पेट की आग' is:", ["जठरानल", "अग्नि", "कापाय", "आत्मनिर्भर"], "'जठरानल' is the fire of the stomach, i.e. hunger."], ["'पेट की आग' वाक्यांश के लिए एक शब्द लिखिए:", ["जठरानल", "अग्नि", "कापाय", "आत्मनिर्भर"], "'जठरानल' पेट की आग (भूख) को कहते हैं।"]),
  q(2, "hindi", "vyakaran", "M", 1, ["What type of noun is 'कक्षा'?", ["Proper noun", "Common noun", "Collective noun", "Abstract noun"], "'कक्षा' (class/room) is a common noun (jativachak)."], ["'कक्षा' कौन-सी संज्ञा है?", ["व्यक्तिवाचक", "जातिवाचक", "समुदायवाचक", "भाववाचक"], "'कक्षा' जातिवाचक संज्ञा है।"]),
  q(2, "hindi", "vyakaran", "M", 3, ["What do we call the word that expresses the quality of a noun or pronoun?", ["Suffix", "Gender", "Noun", "Adjective"], "A word that describes a noun or pronoun is an adjective (visheshan)."], ["जो शब्द संज्ञा अथवा सर्वनाम की विशेषता प्रकट करें, उन्हें क्या कहते हैं?", ["प्रत्यय", "लिंग", "संज्ञा", "विशेषण"], "संज्ञा या सर्वनाम की विशेषता बताने वाले शब्द विशेषण कहलाते हैं।"]),
  q(2, "hindi", "alankar-ras", "M", 0, ["Where both the word and the meaning have a special feature together, which figure of speech is it?", ["Ubhayalankar", "Arthalankar", "Anupras", "Shabdalankar"], "When both word and meaning carry the beauty, it is ubhayalankar."], ["जहाँ एक साथ शब्द और अर्थ दोनों में विशेषता हो, वहाँ:", ["उभयालंकार", "अर्थालंकार होता है", "अनुप्रास अलंकार होता है", "शब्दालंकार होता है"], "जहाँ शब्द और अर्थ दोनों में चमत्कार हो वहाँ उभयालंकार होता है।"]),
  q(2, "hindi", "sandhi-samas", "M", 0, ["What is the sandhi split of 'विद्यार्थी'?", ["विद्या + रथी", "विद्य + अर्थी", "विद्य + रथी", "विद्या + अर्थी"], "विद्या + अर्थी → विद्यार्थी (दीर्घ संधि: आ + अ = आ)."], ["'विद्यार्थी' का संधि-विग्रह कौन-सा है?", ["विद्या + रथी", "विद्य + अर्थी", "विद्य + रथी", "विद्या + अर्थी"], "विद्या + अर्थी → विद्यार्थी (दीर्घ संधि: आ + अ = आ)।"]),
  q(2, "hindi", "paryay-vilom", "M", 0, ["Which word is a synonym of 'बादल'?", ["जलद", "पयोधि", "तोयज", "पंकज"], "'जलद' (giver of water) is a synonym of cloud."], ["'बादल' शब्द का पर्यायवाची शब्द कौन-सा है?", ["जलद", "पयोधि", "तोयज", "पंकज"], "'जलद' (जल देने वाला) बादल का पर्यायवाची है।"]),
  q(2, "hindi", "paryay-vilom", "M", 3, ["What is the antonym of 'मिथ्या'?", ["Santosh", "Vishay", "Satya", "Asatya"], "'मिथ्या' means false; its opposite is 'सत्य'."], ["'मिथ्या' शब्द का विपरीतार्थक क्या है?", ["सन्तोष", "विषय", "सत्य", "असत्य"], "'मिथ्या' का अर्थ झूठ है; विलोम 'सत्य' होता है।"]),
  q(2, "hindi", "vyakaran", "H", 2, ["Which punctuation of the following is correct?", ["पेड़ को मत देखो, देखो केवल मछली की आँख जो तुम्हारे लक्ष्य का केन्द्र-बिन्दु है।", "पेड़ को मत देखो देखो, केवल, मछली की आँख जो तुम्हारे लक्ष्य का केन्द्र बिन्दु है।", "पेड़ को मत देखो देखा केवल, मछली की आँख जो तुम्हारे लक्ष्य का केन्द्र-बिन्दु है।", "पेड़ को मत देखो देखो केवल मछली की आँख, जो तुम्हारे लक्ष्य का केन्द्र-बिन्दु है।"], "Option D places the comma correctly before the relative clause 'जो तुम्हारे लक्ष्य का…'."], ["इनमें से कौन-सा विराम चिह्न उचित है?", ["पेड़ को मत देखो, देखो केवल मछली की आँख जो तुम्हारे लक्ष्य का केन्द्र-बिन्दु है।", "पेड़ को मत देखो देखो, केवल, मछली की आँख जो तुम्हारे लक्ष्य का केन्द्र बिन्दु है।", "पेड़ को मत देखो देखा केवल, मछली की आँख जो तुम्हारे लक्ष्य का केन्द्र-बिन्दु है।", "पेड़ को मत देखो देखो केवल मछली की आँख, जो तुम्हारे लक्ष्य का केन्द्र-बिन्दु है।"], "विकल्प D में उपवाक्य 'जो तुम्हारे लक्ष्य का…' से पहले अल्पविराम सही जगह लगा है।"]),
  q(2, "hindi", "vyakaran", "E", 3, ["Which is the script of Hindi?", ["Persian", "Roman", "Gurmukhi", "Devanagari"], "Hindi is written in the Devanagari script."], ["हिन्दी की लिपि कौन-सी है?", ["फारसी", "रोमन", "गुरुमुखी", "देवनागरी"], "हिन्दी देवनागरी लिपि में लिखी जाती है।"]),
  q(2, "hindi", "vyakaran", "M", 0, ["In the sentence 'दिनेश आम खाता है', which type of verb is 'खाता है'?", ["Transitive", "Intransitive", "Ditransitive", "Causative"], "'खाना' takes an object (आम), so it is a transitive verb."], ["'दिनेश आम खाता है' इस वाक्य में कौन-सी क्रिया है?", ["सकर्मक", "अकर्मक", "द्विकर्मक", "प्रेरणार्थक"], "'खाना' क्रिया का कर्म (आम) है, इसलिए यह सकर्मक है।"]),
  q(2, "hindi", "shuddh-vartani", "M", 3, ["Which sentence is correct?", ["बड़ों से आदर करना चाहिए", "पढ़ने पर मन लगाओ", "उसने बड़ी मेहनत से हिन्दी को सीखा।", "उसने अपना नाम बताया।"], "The correct sentence is 'उसने अपना नाम बताया।'"], ["इनमें से कौन-सा वाक्य शुद्ध है?", ["बड़ों से आदर करना चाहिए", "पढ़ने पर मन लगाओ", "उसने बड़ी मेहनत से हिन्दी को सीखा।", "उसने अपना नाम बताया।"], "शुद्ध वाक्य 'उसने अपना नाम बताया।' है।"]),
  q(2, "hindi", "paryay-vilom", "E", 1, ["Which is a synonym of 'सूर्य'?", ["वासर", "रवि", "कुकुभ", "कृपाण"], "'रवि' means the Sun."], ["'सूर्य' शब्द का पर्यायवाची कौन-सा है?", ["वासर", "रवि", "कुकुभ", "कृपाण"], "'रवि' का अर्थ सूर्य है।"]),
  q(2, "hindi", "vyakaran", "M", 2, ["In 'जोर से बोलिए', what is the adverb?", ["जोर", "बोलिए", "जोर से", "से"], "'जोर से' tells how to speak, so it is the adverb (kriya-visheshan)."], ["'जोर से बोलिए।' इसमें क्रिया विशेषण क्या है?", ["जोर", "बोलिए", "जोर से", "से"], "'जोर से' बोलने की रीति बताता है, इसलिए क्रिया-विशेषण है।"]),
  q(2, "hindi", "alankar-ras", "M", 1, ["When a single word is used once in a poem but has two or more meanings, which figure of speech is it?", ["Rupak", "Shlesh", "Pratip", "Upama"], "Use of one word with two or more meanings is Shlesh alankar."], ["जब किसी कविता में एक शब्द का एक ही प्रयोग हो परन्तु उसके दो या अधिक अर्थ हों तब कौन-सा अलंकार होता है?", ["रूपक अलंकार", "श्लेष अलंकार", "प्रतीप अलंकार", "उपमा अलंकार"], "एक बार प्रयुक्त शब्द के दो या अधिक अर्थ होने पर श्लेष अलंकार होता है।"]),
  q(2, "hindi", "muhavare", "M", 3, ["What is meant by 'हाथ पर हाथ धरे रह जाना'?", ["To work hard", "To get nothing", "To sit relying on luck", "To not work"], "It means sitting idle, doing no work."], ["'हाथ पर हाथ धरे रह जाना' से तात्पर्य है:", ["परिश्रम करना", "कुछ भी प्राप्त न होना", "भाग्य के भरोसे बैठना", "परिश्रम न करना"], "इसका अर्थ निष्क्रिय बैठे रहना, कुछ न करना है।"]),
  q(2, "hindi", "ek-shabd", "M", 3, ["One word for the many words 'इतिहास से पहले का' is:", ["ऐतिहासिक", "प्रागैतिहासिक", "भवितव्य", "पूर्व ऐतिहासिक"], "As per the official key, the answer is 'पूर्व ऐतिहासिक'; 'प्रागैतिहासिक' is the standard word."], ["'इतिहास से पहले का' अनेक शब्दों के लिए एक शब्द है:", ["ऐतिहासिक", "प्रागैतिहासिक", "भवितव्य", "पूर्व ऐतिहासिक"], "आधिकारिक कुंजी के अनुसार उत्तर 'पूर्व ऐतिहासिक' है; मानक शब्द 'प्रागैतिहासिक' है।"]),

  // ───────── Section 3: General Knowledge ─────────
  q(3, "general-studies", "indian-geography", "M", 0, ["In which of the following regions is terrace farming practised?", ["Punjab", "Plains of Uttar Pradesh", "Haryana", "Uttarakhand"], "Terrace (stepped) farming is practised on the hill slopes of Uttarakhand."], ["निम्नलिखित में से किस प्रान्त में सीढ़ीदार खेती की जाती है?", ["पंजाब", "उत्तर प्रदेश के मैदान", "हरियाणा", "उत्तराखण्ड"], "सीढ़ीदार खेती उत्तराखण्ड की पहाड़ी ढलानों पर की जाती है।"]),
  q(3, "general-studies", "indian-history", "E", 1, ["Who was the author of 'Vande Mataram'?", ["Rabindranath Tagore", "Bankim Chandra Chatterjee", "J.L. Nehru", "None of the above"], "Bankim Chandra Chatterjee wrote Vande Mataram."], ["वंदेमातरम् के रचयिता कौन थे?", ["रविन्द्रनाथ टैगोर", "बंकिम चन्द्र चटर्जी", "जे.एल. नेहरू", "उपरोक्त कोई नहीं"], "वंदे मातरम् के रचयिता बंकिम चंद्र चट्टोपाध्याय हैं।"]),
  q(3, "general-studies", "general-science", "E", 1, ["Which day is celebrated on 5 June?", ["World Health Day", "World Environment Day", "World AIDS Day", "International Women's Day"], "World Environment Day is observed on 5 June."], ["5 जून को कौन-सा दिवस मनाया जाता है?", ["विश्व स्वास्थ्य दिवस", "विश्व पर्यावरण दिवस", "विश्व एड्स दिवस", "अंतर्राष्ट्रीय महिला दिवस"], "5 जून को विश्व पर्यावरण दिवस मनाया जाता है।"]),
  q(3, "general-studies", "general-science", "M", 3, ["Which of the following medicines is used to treat indigestion?", ["Antibiotic", "Analgesic", "Antacid", "Antiseptic"], "An antacid neutralises excess stomach acid and is used for indigestion."], ["अपच का उपचार करने के लिए निम्न में से किस औषधि का उपयोग होता है?", ["एंटीबायोटिक", "ऐनालजेसिक", "ऐन्टैसिड", "एंटीसेप्टिक"], "एंटैसिड पेट के अतिरिक्त अम्ल को निष्क्रिय करता है और अपच में प्रयुक्त होता है।"]),
  q(3, "general-studies", "general-science", "M", 2, ["Which of the following is not an example of a biomass energy source?", ["Wood", "Biogas", "Nuclear energy", "Coal"], "Wood, biogas (from dung) and coal (fossilised plant matter) are all biomass-derived; nuclear energy comes from atomic fission, not biomass."], ["निम्नलिखित में से कौन जैवमात्रा ऊर्जा स्रोत का उदाहरण नहीं है?", ["लकड़ी", "गोबर गैस", "नाभिकीय ऊर्जा", "कोयला"], "लकड़ी, गोबर गैस और कोयला जैव-पदार्थों से मिलते हैं; नाभिकीय ऊर्जा जैवमात्रा ऊर्जा स्रोत नहीं है।"]),
  q(3, "general-studies", "indian-geography", "M", 3, ["On which river has the Sardar Sarovar Dam been built?", ["Cauvery", "Krishna", "Narmada", "Sutlej"], "The Sardar Sarovar Dam is on the Narmada river in Gujarat."], ["निम्न में से किस नदी पर सरदार सरोवर बाँध बनाया गया है?", ["कावेरी नदी", "कृष्णा नदी", "नर्मदा नदी", "सतलुज नदी"], "सरदार सरोवर बाँध गुजरात में नर्मदा नदी पर बना है।"]),
  q(3, "general-studies", "general-science", "E", 0, ["Which of the following is a leguminous crop?", ["Pulses", "Wheat", "Jowar", "Sesame"], "Pulses are leguminous crops that fix nitrogen in the soil."], ["इनमें से कौन-सी एक फलीदार फसल है?", ["दालें", "गेहूँ", "ज्वार", "तिल"], "दालें फलीदार फसलें हैं जो मिट्टी में नाइट्रोजन स्थिर करती हैं।"]),
  q(3, "general-studies", "indian-history", "E", 0, ["Which is the oldest Veda?", ["Rigveda", "Atharvaveda", "Yajurveda", "Samaveda"], "The Rigveda is the oldest Veda."], ["सबसे पुराना वेद कौन-सा है?", ["ऋग्वेद", "अथर्ववेद", "यजुर्वेद", "सामवेद"], "ऋग्वेद सबसे प्राचीन वेद है।"]),
  q(3, "general-studies", "indian-polity", "M", 3, ["The President can nominate two members to the Lok Sabha to represent:", ["Indian Christians", "Parsis", "Buddhists", "Anglo-Indians"], "Two Anglo-Indian members could be nominated to the Lok Sabha (this provision ended in 2020)."], ["राष्ट्रपति लोकसभा में निम्न का प्रतिनिधित्व करने के लिए दो सदस्यों को नामांकित कर सकते हैं:", ["भारतीय ईसाई", "पारसी", "बौद्ध", "आँग्ल भारतीय"], "लोकसभा में दो आंग्ल-भारतीय सदस्य नामांकित किए जा सकते थे (यह प्रावधान 2020 में समाप्त हुआ)।"]),
  q(3, "hp-gk", "districts", "M", 0, ["Which district of Himachal Pradesh has the highest population density?", ["Solan", "Shimla", "Kangra", "Hamirpur"], "As per the official key, the answer is Solan."], ["हिमाचल प्रदेश के किस जिले का जनसंख्या घनत्व सबसे अधिक है?", ["सोलन", "शिमला", "कांगड़ा", "हमीरपुर"], "आधिकारिक कुंजी के अनुसार उत्तर सोलन है।"]),
  q(3, "general-studies", "indian-economy", "E", 0, ["What is the currency of Bangladesh?", ["Taka", "Yuan", "Rupee", "Dollar"], "The currency of Bangladesh is the taka."], ["बांग्लादेश की मुद्रा है:", ["टका", "युआन", "रुपया", "डॉलर"], "बांग्लादेश की मुद्रा टका है।"]),
  q(3, "general-studies", "general-science", "M", 1, ["In plants, xylem is responsible for the transport of:", ["Water", "Food", "Amino acids", "Oxygen"], "Xylem conducts water and minerals from the roots upward."], ["पादपों में जाइलम उत्तरदायी है:", ["जल के वहन का", "भोजन के वहन का", "अमीनो अम्ल के वहन का", "ऑक्सीजन के वहन का"], "जाइलम जड़ों से जल और खनिजों को ऊपर पहुँचाता है।"]),
  q(3, "general-studies", "indian-history", "M", 0, ["What are manuscripts?", ["Handwritten documents", "Inscriptions on stone", "Paintings", "Temples"], "Manuscripts are handwritten documents or books."], ["पांडुलिपियाँ क्या हैं?", ["हस्तलिखित लेख", "शिलालेख", "चित्रकारी", "मन्दिर"], "पांडुलिपियाँ हाथ से लिखे गए लेख या ग्रंथ हैं।"]),
  q(3, "general-studies", "general-science", "M", 0, ["What is rinderpest?", ["An animal disease found in Africa", "An animal disease found in China", "An animal disease found in India", "An animal disease found in America"], "Rinderpest was a viral cattle disease widely found in Africa; it was declared eradicated in 2011."], ["रिंडरपेस्ट क्या है?", ["अफ्रीका में पाया जाने वाला पशु रोग", "चीन में पाया जाने वाला पशु रोग", "भारत में पाया जाने वाला पशु रोग", "अमेरिका में पाया जाने वाला पशु रोग"], "रिंडरपेस्ट पशुओं का वायरस जनित रोग था जो अफ्रीका में बहुत फैला; इसे 2011 में समाप्त घोषित किया गया।"]),
  q(3, "general-studies", "indian-geography", "E", 0, ["What is the official language of Sri Lanka?", ["Sinhala", "English", "Tamil", "Hindi"], "Sinhala is the principal official language of Sri Lanka."], ["श्रीलंका की अधिकारिक भाषा है:", ["सिंहली", "अंग्रेजी", "तमिल", "हिन्दी"], "सिंहली श्रीलंका की मुख्य आधिकारिक भाषा है।"]),
  q(3, "general-studies", "indian-polity", "M", 0, ["Which Indian cricketer scored a double century in a one-day match recently?", ["Rohit Sharma", "M.S. Dhoni", "Virat Kohli", "None of the above"], "Rohit Sharma scored the double century of 209 against Australia in November 2013."], ["हाल ही में एक दिवसीय मैच में दोहरा शतक लगाने वाला भारतीय क्रिकेटर कौन है?", ["रोहित शर्मा", "एम.एस. धोनी", "विराट कोहली", "उपरोक्त कोई भी नहीं"], "रोहित शर्मा ने नवंबर 2013 में ऑस्ट्रेलिया के विरुद्ध 209 रनों की दोहरी शतकीय पारी खेली।"]),
  q(3, "hp-gk", "districts", "M", 0, ["At which place in Shimla district is the golf course located?", ["Kufri", "Rohru", "Naldehra", "Rampur"], "The famous Naldehra golf course is in Shimla district."], ["जिला शिमला के किस स्थान पर गोल्फ कोर्स है?", ["कुफरी", "रोहडू", "नालदेरा", "रामपुर"], "प्रसिद्ध नालदेहरा गोल्फ कोर्स शिमला जिले में है।"]),
  q(3, "hp-gk", "history", "M", 0, ["Which Gorkha commander attacked Kangra in 1805?", ["Amar Singh Thapa", "Rajbahadur Thapa", "Ram Singh Thapa", "All of the above"], "Amar Singh Thapa led the Gorkha attack on Kangra."], ["किस गोरखा कमाण्डर ने 1805 में काँगड़ा पर आक्रमण किया?", ["अमर सिंह थापा", "राजबहादुर थापा", "राम सिंह थापा", "उपरोक्त सभी"], "काँगड़ा पर गोरखा आक्रमण का नेतृत्व अमर सिंह थापा ने किया।"]),
  q(3, "general-studies", "indian-history", "E", 0, ["Napoleon Bonaparte was related to which country?", ["France", "Austria", "India", "Germany"], "Napoleon Bonaparte was the French emperor."], ["नेपोलियन बोनापार्ट सम्बन्धित था:", ["फ्रांस से", "ऑस्ट्रिया से", "भारत से", "जर्मनी से"], "नेपोलियन बोनापार्ट फ्रांस का सम्राट था।"]),
  q(3, "general-studies", "indian-polity", "E", 3, ["Where is the headquarters of the United Nations?", ["New York", "San Francisco", "Chicago", "Paris"], "The United Nations is headquartered in New York."], ["संयुक्त राष्ट्रसंघ का मुख्यालय कहाँ है?", ["न्यूयॉर्क", "सैन फ्रांसिस्को", "शिकागो", "पेरिस"], "संयुक्त राष्ट्र का मुख्यालय न्यूयॉर्क में है।"]),
  q(3, "general-studies", "general-science", "M", 3, ["In human beings the kidneys (vrikk) are part of the system related to:", ["Nutrition", "Respiration", "Excretion", "Transport"], "The kidneys filter waste from the blood and belong to the excretory system."], ["मनुष्य में वृक्क एक तंत्र के भाग हैं जो संबंधित हैं:", ["पोषण से", "श्वसन से", "उत्सर्जन से", "परिवहन से"], "मनुष्य में वृक्क (गुर्दे) उत्सर्जन तंत्र का भाग हैं।"]),
  q(3, "general-studies", "indian-geography", "M", 3, ["Iron ore is what type of resource?", ["Renewable", "Flowing", "Biotic", "Non-renewable"], "Iron ore is a non-renewable mineral resource."], ["लौह अयस्क किस प्रकार का संसाधन है?", ["नवीकरणीय", "प्रवाह", "जैव", "अनवीकरणीय"], "लौह अयस्क अनवीकरणीय खनिज संसाधन है।"]),
  q(3, "general-studies", "indian-history", "M", 0, ["When did the Simon Commission come to India?", ["1928", "1910", "1929", "1930"], "The Simon Commission arrived in India in 1928."], ["साइमन कमीशन भारत कब आया?", ["1928", "1910", "1929", "1930"], "साइमन कमीशन 1928 में भारत आया।"]),
  q(3, "general-studies", "general-science", "E", 0, ["'Kwashiorkor' is a disease caused by deficiency of which nutrient?", ["Protein", "Vitamin D", "Iron", "Fat"], "Kwashiorkor is caused by severe protein deficiency."], ["'क्वाशियरकर' रोग किस पौष्टिक तत्व की कमी से होता है?", ["प्रोटीन", "विटामिन-डी", "लौह तत्व", "वसा"], "क्वाशियोरकर गंभीर प्रोटीन की कमी से होता है।"]),
];
