// HP Patwari written exam of 17 November 2019 (Series A) — transcribed from the photographed paper. No official key was
// available: answers were solved independently (a few pencil marks on the scan were only a cross-check).
// Left out because the printed options do not fit the question: original numbers 11, 54, 63.
// Option order is kept as printed. Sections: 0 Hindi, 1 English, 2 Mathematics, 3 General Knowledge.

import { q, type PatwariQuestion } from "../patwari/types";

export const PATWARI_PYQ_SECTIONS = [
  { name: "Hindi", nameHi: "हिन्दी" },
  { name: "English", nameHi: "अंग्रेज़ी" },
  { name: "Mathematics", nameHi: "गणित" },
  { name: "General Knowledge", nameHi: "सामान्य ज्ञान" },
];

export const y2019: PatwariQuestion[] = [
  // ───────── Section 0: Hindi ─────────
  q(0, "hindi", "vyakaran", "M", 2,
    ["In \"यह समस्या अत्यंत कठिन है।\", what part of speech is 'अत्यंत'?", ["Noun (संज्ञा)", "Verb (क्रिया)", "Intensifying adverb (प्रविशेषण)", "Adjective (विशेषण)"], "'अत्यंत' modifies the adjective 'कठिन', so it is a प्रविशेषण (adverb of degree)."],
    ["\"यह समस्या अत्यंत कठिन है।\" में अत्यंत क्या है?", ["संज्ञा", "क्रिया", "प्रविशेषण", "विशेषण"], "'अत्यंत' विशेषण 'कठिन' की विशेषता बताता है, इसलिए यह प्रविशेषण है।"]),
  q(0, "hindi", "vyakaran", "E", 1,
    ["In which language were the Vedas composed?", ["Classical Sanskrit", "Vedic Sanskrit", "Pali", "Prakrit"], "The Vedas were composed in Vedic Sanskrit, an older form than classical (laukik) Sanskrit."],
    ["वेदों की रचना किस भाषा में हुई?", ["लौकिक संस्कृत", "वैदिक संस्कृत", "पालि", "प्राकृत"], "वेदों की रचना वैदिक संस्कृत में हुई, जो लौकिक संस्कृत से प्राचीन रूप है।"]),
  q(0, "hindi", "vyakaran", "M", 3,
    ["'ज्ञ' is a conjunct of:", ["ग + य", "ग् + य्", "ज + य", "ज् + ञ"], "ज्ञ = ज् + ञ."],
    ["'ज्ञ' में मिलन है:", ["ग + य", "ग् + य्", "ज + य", "ज् + ञ"], "ज्ञ = ज् + ञ।"]),
  q(0, "hindi", "vyakaran", "E", 3,
    ["When is 'World Hindi Day' (Vishwa Hindi Diwas) celebrated?", ["10 February", "10 March", "10 June", "10 January"], "World Hindi Day is observed on 10 January."],
    ["'विश्व हिन्दी दिवस' कब मनाया जाता है?", ["10 फरवरी", "10 मार्च", "10 जून", "10 जनवरी"], "विश्व हिन्दी दिवस 10 जनवरी को मनाया जाता है।"]),
  q(0, "hindi", "sandhi-samas", "E", 0,
    ["Which sandhi is in 'देव + आलय'?", ["Dirgha sandhi", "Guna sandhi", "Vriddhi sandhi", "Yan sandhi"], "अ + आ = आ, so देवालय is formed by दीर्घ स्वर संधि."],
    ["'देव + आलय' में कौन-सी सन्धि है?", ["दीर्घ सन्धि", "गुण सन्धि", "वृद्धि सन्धि", "यण सन्धि"], "अ + आ = आ, इसलिए देवालय दीर्घ स्वर संधि से बना है।"]),
  q(0, "hindi", "muhavare", "M", 2,
    ["What is the meaning of 'आधा तीतर आधा बटेर होना'?", ["Lack of proper harmony", "Being big and small", "Mismatched and awkward", "Being odd"], "The idiom describes something made of two ill-matched parts — mismatched and awkward."],
    ["'आधा तीतर आधा बटेर होना' का अर्थ होगा:", ["उचित सामंजस्य का अभाव होना", "छोटा-बड़ा होना", "बेमेल तथा बेढंगा", "बिरंगा होना"], "यह मुहावरा दो बेमेल हिस्सों से बनी, बेढंगी वस्तु के लिए प्रयुक्त होता है।"]),
  q(0, "hindi", "sandhi-samas", "M", 2,
    ["The sandhi split of 'महर्षि' is:", ["मह + ऋषि", "महान + ऋषि", "महा + ऋषि", "महि + ऋषि"], "महा + ऋषि → महर्षि (गुण संधि: आ + ऋ = अर्)."],
    ["महर्षि का सन्धि विच्छेद है:", ["मह + ऋषि", "महान + ऋषि", "महा + ऋषि", "महि + ऋषि"], "महा + ऋषि → महर्षि (गुण संधि: आ + ऋ = अर्)।"]),
  q(0, "hindi", "shuddh-vartani", "M", 0,
    ["Which is the correct sentence?", ["यह असली गाय का दूध है।", "ये असली गाय का दूध है।", "यह गाय का 'असली' दूध है।", "यह गाय के असली दूध है।"], "The correct form is 'यह असली गाय का दूध है' — the singular 'यह' with the possessive 'का' agreeing with the masculine 'दूध'."],
    ["शुद्ध वाक्य है:", ["यह असली गाय का दूध है।", "ये असली गाय का दूध है।", "यह गाय का 'असली' दूध है।", "यह गाय के असली दूध है।"], "सही रूप 'यह असली गाय का दूध है' है — एकवचन 'यह' और पुल्लिंग 'दूध' के अनुरूप 'का'।"]),
  q(0, "hindi", "paryay-vilom", "M", 1,
    ["A synonym of 'कलानिधि' is:", ["सूरज", "राकेश", "निकेत", "गजानन"], "'कलानिधि' means the moon, and 'राकेश' is also a name for the moon."],
    ["कलानिधि का पर्यायवाची है:", ["सूरज", "राकेश", "निकेत", "गजानन"], "'कलानिधि' का अर्थ चंद्रमा है और 'राकेश' भी चंद्रमा का नाम है।"]),
  q(0, "hindi", "ek-shabd", "M", 2,
    ["The suitable word for 'fire of the sea' is:", ["दावानल", "जलागम", "बड़वानल", "भीषणाग्नि"], "The fire that burns under the sea is called 'बड़वानल'. 'दावानल' is a forest fire."],
    ["'समुद्र की आग' के लिए उपयुक्त शब्द है:", ["दावानल", "जलागम", "बड़वानल", "भीषणाग्नि"], "समुद्र के भीतर की आग 'बड़वानल' कहलाती है। 'दावानल' वन की आग है।"]),
  q(0, "hindi", "paryay-vilom", "M", 2,
    ["The antonym of 'ऋजु' (straight, simple) is:", ["हार", "पतन", "वक्र", "पूर्ण"], "'ऋजु' means straight or honest; its opposite is 'वक्र' (crooked)."],
    ["'ऋजु' का विलोमार्थी शब्द है:", ["हार", "पतन", "वक्र", "पूर्ण"], "'ऋजु' का अर्थ सीधा/सरल है; विलोम 'वक्र' (टेढ़ा) है।"]),
  q(0, "hindi", "vyakaran", "M", 0,
    ["In \"प्रवीण बड़ी चतुर है\", what is 'बड़ी'?", ["Intensifying adverb (प्रविशेषण)", "Verb", "Particle (निपात)", "Pronoun"], "'बड़ी' qualifies the adjective 'चतुर', so it is a प्रविशेषण."],
    ["\"प्रवीण बड़ी चतुर है\" — में 'बड़ी' है:", ["प्रविशेषण", "क्रिया", "निपात", "सर्वनाम"], "'बड़ी' विशेषण 'चतुर' की विशेषता बता रहा है, इसलिए प्रविशेषण है।"]),
  q(0, "hindi", "paryay-vilom", "M", 2,
    ["The antonym of 'जंगम' (movable) is:", ["संगम", "अचलता", "स्थावर", "साधुत्व"], "'जंगम' means movable; its opposite is 'स्थावर' (immovable)."],
    ["'जंगम' का विलोम है:", ["संगम", "अचलता", "स्थावर", "साधुत्व"], "'जंगम' का अर्थ चलने वाला है; विलोम 'स्थावर' (अचल) है।"]),
  q(0, "hindi", "vyakaran", "H", 2,
    ["The verb 'अपनाना' is formed from:", ["Noun", "Adjective", "Pronoun", "Verb"], "'अपनाना' is a nominal verb derived from the pronoun 'अपना'."],
    ["'अपनाना' क्रिया किससे बनी है?", ["संज्ञा से", "विशेषण से", "सर्वनाम से", "क्रिया से"], "'अपनाना' नामधातु क्रिया है जो सर्वनाम 'अपना' से बनी है।"]),
  q(0, "hindi", "vyakaran", "M", 2,
    ["In \"पेड़ से कई आम गिरे\", which case (kāraka) is used?", ["Instrumental (करण)", "Objective (कर्म)", "Ablative (अपादान)", "Genitive (संबंध)"], "'पेड़ से' shows separation from a source, which is अपादान कारक."],
    ["\"पेड़ से कई आम गिरे।\" में कौन-से कारक का प्रयोग है?", ["करण कारक", "कर्मकारक", "अपादान कारक", "संबंध कारक"], "'पेड़ से' अलग होने का भाव बताता है, जो अपादान कारक है।"]),
  q(0, "hindi", "vyakaran", "M", 0,
    ["In \"गीता मंद-मंद मुस्कुरा रही है।\", what is 'मंद-मंद'?", ["Adverb (क्रियाविशेषण)", "Adjective", "Verb", "Case"], "'मंद-मंद' tells how she is smiling, so it is a क्रियाविशेषण."],
    ["\"गीता मंद-मंद मुस्कुरा रही है।\" में मंद-मंद क्या है?", ["क्रियाविशेषण", "विशेषण", "क्रिया", "कारक"], "'मंद-मंद' मुस्कुराने की रीति बताता है, इसलिए क्रियाविशेषण है।"]),
  q(0, "hindi", "paryay-vilom", "M", 0,
    ["A synonym of 'सूचक' (indicator) is:", ["द्योतक", "धौतक", "घोतक", "ज्ञापन"], "'द्योतक' (one that indicates) is a synonym of 'सूचक'; धौतक and घोतक are not proper words."],
    ["'सूचक' का समानार्थक शब्द है:", ["द्योतक", "धौतक", "घोतक", "ज्ञापन"], "'द्योतक' (संकेत करने वाला) 'सूचक' का पर्याय है; धौतक और घोतक सही शब्द नहीं हैं।"]),
  q(0, "hindi", "shabdavali", "M", 0,
    ["Which word is 'tatsam'?", ["उज्ज्वल", "उजाला", "उज्जवल", "उदूखल"], "'उज्ज्वल' is the Sanskrit (tatsam) word; 'उजाला' is its tadbhav form."],
    ["'तत्सम' शब्द कौन-सा है?", ["उज्ज्वल", "उजाला", "उज्जवल", "उदूखल"], "'उज्ज्वल' संस्कृत का तत्सम शब्द है; 'उजाला' उसका तद्भव रूप है।"]),
  q(0, "hindi", "alankar-ras", "M", 0,
    ["\"मंगल भवन अमंगल हारी। द्रवहु सो दशरथ अजिर बिहारी॥\" — in which metre (chhand) is this written?", ["Chaupai", "Sortha", "Rola", "Doha"], "Each line has 16 matras with a Chaupai pattern, as in the Ramcharitmanas."],
    ["\"मंगल भवन अमंगल हारी। हरहु नाथ मम संकट भारी॥\" में छन्द है:", ["चौपाई", "सोरठा", "रोला", "दोहा"], "प्रत्येक पंक्ति में 16 मात्राएँ हैं, यह रामचरितमानस की चौपाई शैली है।"]),
  q(0, "hindi", "shabdavali", "M", 1,
    ["Which word has the suffix 'पन'?", ["पनघट", "बड़प्पन", "औपन्", "सत्यापन"], "बड़ा + पन = बड़प्पन. In पनघट, 'पन' is part of the root, and सत्यापन uses 'आपन'."],
    ["'पन' प्रत्यय वाला शब्द है:", ["पनघट", "बड़प्पन", "औपन्", "सत्यापन"], "बड़ा + पन = बड़प्पन। 'पनघट' में 'पन' शब्द का मूल अंश है और 'सत्यापन' में 'आपन' प्रत्यय है।"]),
  q(0, "hindi", "paryay-vilom", "M", 2,
    ["A synonym for 'कठोर' (harsh) is:", ["पौरुष", "परुषी", "परुष", "परुषत्व"], "'परुष' means harsh or hard, a synonym of 'कठोर'."],
    ["'कठोर' के लिए समानार्थक शब्द है:", ["पौरुष", "परुषी", "परुष", "परुषत्व"], "'परुष' का अर्थ कठोर या रूखा है।"]),
  q(0, "hindi", "muhavare", "H", 3,
    ["\"कोस-कोस पर पानी बदले, चार कोस पर बानी\" — what change does it refer to?", ["Of province and river", "Of river and music", "Of sea and mountain", "Of the taste of water and the words of speech"], "It says the taste of water and the dialect (बानी) change every few kos."],
    ["\"कोस-कोस पर पानी बदले, चार कोस पर बानी\" — में किस परिवर्तन का उल्लेख है?", ["प्रान्त और नदी का", "नदी और संगीत का", "समुद्र और पर्वत का", "पानी स्वाद और बोली के शब्दों का"], "इसमें कहा गया है कि थोड़ी दूरी पर पानी का स्वाद और बोली (बानी) बदल जाती है।"]),
  q(0, "hindi", "vyakaran", "E", 2,
    ["What is meant by 'भाषा' (language)?", ["Giving a speech", "Learning to speak", "Expressing thoughts through sound-based words", "None of these"], "Language is the means of expressing one's thoughts through words made of speech sounds."],
    ["'भाषा' से तात्पर्य है:", ["भाषण देना", "बोलना सीखना", "ध्वन्यात्मक शब्दों द्वारा विचार प्रकट करना", "इनमें से कोई नहीं"], "भाषा वह साधन है जिससे ध्वनि-रूप शब्दों द्वारा विचार प्रकट किए जाते हैं।"]),
  q(0, "hindi", "sandhi-samas", "M", 1,
    ["Which is an example of Avyayibhav samas?", ["त्रिनेत्र", "भरपेट", "राजपुत्र", "महाराजा"], "'भरपेट' (to one's fill) is an example of अव्ययीभाव समास, where the first word is an indeclinable."],
    ["अव्ययीभाव समास का उदाहरण है:", ["त्रिनेत्र", "भरपेट", "राजपुत्र", "महाराजा"], "'भरपेट' अव्ययीभाव समास का उदाहरण है, जिसमें पहला पद अव्यय है।"]),

  // ───────── Section 1: English ─────────
  q(1, "english", "vocabulary", "E", 2,
    ["Choose the alternative which best expresses the meaning of the given word: Vocation", ["Holiday", "Break-up", "Occupation", "Virtue"], "Vocation means a person's occupation or calling."],
    ["दिए गए शब्द का अर्थ सबसे अच्छी तरह व्यक्त करने वाला विकल्प चुनिए: Vocation", ["Holiday", "Break-up", "Occupation", "Virtue"], "Vocation का अर्थ व्यवसाय या पेशा है।"]),
  q(1, "english", "vocabulary", "H", 0,
    ["Choose the alternative which best expresses the meaning of the given word: Imperious", ["Proud", "Temper", "Tamper", "Distant"], "Imperious means arrogant and domineering — closest to 'proud'."],
    ["दिए गए शब्द का अर्थ सबसे अच्छी तरह व्यक्त करने वाला विकल्प चुनिए: Imperious", ["Proud", "Temper", "Tamper", "Distant"], "Imperious का अर्थ अभिमानी और रोब जमाने वाला है — 'proud' के सबसे निकट।"]),
  q(1, "english", "grammar", "M", 3,
    ["'She will have been served food' is in:", ["Past perfect tense", "Future perfect continuous tense", "Future indefinite tense", "Future perfect tense"], "'will have been served' is 'will have + past participle' in the passive: future perfect tense."],
    ["'She will have been served food' किस काल में है?", ["Past perfect tense", "Future perfect continuous tense", "Future indefinite tense", "Future perfect tense"], "'will have been served' passive में 'will have + past participle' है: future perfect tense।"]),
  q(1, "english", "grammar", "M", 1,
    ["This lesson is ............. difficult.", ["too", "very", "the little", "much"], "'Very' is the intensifier that fits before an adjective here; 'too' would need a result clause."],
    ["This lesson is ............. difficult.", ["too", "very", "the little", "much"], "यहाँ विशेषण से पहले 'very' सही है; 'too' के साथ परिणाम-वाक्य आवश्यक होता।"]),
  q(1, "english", "one-word", "E", 3,
    ["'A word or law no longer in use' is called:", ["cynic", "out-dated", "reticent", "obsolete"], "A word or law that has gone out of use is obsolete."],
    ["'A word or law no longer in use' is called:", ["cynic", "out-dated", "reticent", "obsolete"], "जो शब्द या कानून प्रयोग में न रहे उसे obsolete कहते हैं।"]),
  q(1, "english", "grammar", "M", 1,
    ["I love my books so much that I cannot part ............ them.", ["from", "with", "by", "without"], "'Part with' means to give up or let go of something."],
    ["I love my books so much that I cannot part ............ them.", ["from", "with", "by", "without"], "'Part with' का अर्थ किसी चीज़ को छोड़ना या देना है।"]),
  q(1, "english", "spelling", "E", 0,
    ["Choose the word that is spelt correctly:", ["Deceive", "Decieve", "Diceive", "Dicieive"], "The rule 'i before e, except after c' gives 'deceive'."],
    ["सही वर्तनी वाला शब्द चुनिए:", ["Deceive", "Decieve", "Diceive", "Dicieive"], "'i before e, except after c' नियम से सही वर्तनी 'deceive' है।"]),
  q(1, "english", "grammar", "E", 1,
    ["He is ........... one-eyed person.", ["an", "a", "the", "None of these"], "'One' begins with a /w/ sound, so the article is 'a'."],
    ["He is ........... one-eyed person.", ["an", "a", "the", "None of these"], "'One' का उच्चारण /w/ से शुरू होता है, इसलिए article 'a' आएगा।"]),
  q(1, "english", "synonyms-antonyms", "E", 3,
    ["Choose the correct synonym of 'Audacity':", ["Alertness", "Timidity", "Humility", "Boldness"], "Audacity means boldness or daring."],
    ["'Audacity' का सही पर्यायवाची चुनिए:", ["Alertness", "Timidity", "Humility", "Boldness"], "Audacity का अर्थ साहस या दुस्साहस है।"]),
  q(1, "english", "synonyms-antonyms", "E", 0,
    ["Choose the correct antonym of 'Malice':", ["Goodwill", "Ill-Will", "Spite", "Hate"], "Malice is the wish to harm others; its opposite is goodwill."],
    ["'Malice' का सही विलोम चुनिए:", ["Goodwill", "Ill-Will", "Spite", "Hate"], "Malice का अर्थ दूसरों का बुरा चाहना है; विलोम goodwill है।"]),
  q(1, "english", "voice-speech", "M", 3,
    ["Choose the correct indirect form: The teacher said to the students, \"Let us start a new lesson.\"", ["The teacher asked the students to start a new lesson.", "The teacher suggested to the students to start a new lesson.", "The teacher suggested to the students that he should start a new lesson.", "The teacher suggested to the students that they should start a new lesson."], "'Let us' is reported with 'suggested that + we → they should': 'suggested … that they should start a new lesson'."],
    ["Indirect speech का सही विकल्प चुनिए: The teacher said to the students, \"Let us start a new lesson.\"", ["The teacher asked the students to start a new lesson.", "The teacher suggested to the students to start a new lesson.", "The teacher suggested to the students that he should start a new lesson.", "The teacher suggested to the students that they should start a new lesson."], "'Let us' का indirect रूप 'suggested that … they should' होता है।"]),
  q(1, "english", "voice-speech", "M", 3,
    ["Choose the correct indirect form: He said to his teacher, \"Good night, sir.\"", ["He wished his teacher good night sir.", "He respectfully wished his teacher good night.", "He respectfully bids his teacher good night.", "He respectfully bade his teacher good night."], "A greeting is reported with 'bade' (past of bid) and the respect word 'sir' becomes 'respectfully': 'He respectfully bade his teacher good night.'"],
    ["Indirect speech का सही विकल्प चुनिए: He said to his teacher, \"Good night, sir.\"", ["He wished his teacher good night sir.", "He respectfully wished his teacher good night.", "He respectfully bids his teacher good night.", "He respectfully bade his teacher good night."], "अभिवादन को 'bade' से व्यक्त किया जाता है और 'sir' का भाव 'respectfully' में बदल जाता है।"]),
  q(1, "english", "synonyms-antonyms", "E", 2,
    ["Choose the correct synonym for the underlined word: PROHIBIT", ["Allow", "Grant", "Ban", "Sanction"], "Prohibit means to forbid, i.e. ban."],
    ["रेखांकित शब्द का सही पर्यायवाची चुनिए: PROHIBIT", ["Allow", "Grant", "Ban", "Sanction"], "Prohibit का अर्थ रोकना या प्रतिबंधित करना है।"]),
  q(1, "english", "synonyms-antonyms", "E", 3,
    ["Choose the correct synonym for the underlined word: REGRET", ["Happy", "Bloom", "Reproduce", "Repent"], "Regret means to feel sorry — repent."],
    ["रेखांकित शब्द का सही पर्यायवाची चुनिए: REGRET", ["Happy", "Bloom", "Reproduce", "Repent"], "Regret का अर्थ पछतावा करना है।"]),
  q(1, "english", "synonyms-antonyms", "M", 0,
    ["Choose the correct synonym for the underlined word: WHIMSICAL", ["Amusing", "Sad", "Sorrow", "Mad"], "Whimsical means playfully quaint or fanciful; of the options, 'amusing' is closest."],
    ["रेखांकित शब्द का सही पर्यायवाची चुनिए: WHIMSICAL", ["Amusing", "Sad", "Sorrow", "Mad"], "Whimsical का अर्थ सनकी या मनमौजी होता है; दिए विकल्पों में 'amusing' निकटतम है।"]),
  q(1, "english", "synonyms-antonyms", "M", 2,
    ["Choose the correct synonym for the underlined word: INTERMITTENT", ["Intermingle", "Indifferent", "Periodic", "Transmit"], "Intermittent means stopping and starting at intervals — periodic."],
    ["रेखांकित शब्द का सही पर्यायवाची चुनिए: INTERMITTENT", ["Intermingle", "Indifferent", "Periodic", "Transmit"], "Intermittent का अर्थ रुक-रुककर होने वाला है, यानी periodic।"]),
  q(1, "english", "synonyms-antonyms", "E", 1,
    ["Choose the correct synonym for the underlined word: OBSTINATE", ["Absolute", "Stubborn", "Obsolete", "Old fashioned"], "Obstinate means stubborn."],
    ["रेखांकित शब्द का सही पर्यायवाची चुनिए: OBSTINATE", ["Absolute", "Stubborn", "Obsolete", "Old fashioned"], "Obstinate का अर्थ ज़िद्दी है।"]),
  q(1, "english", "synonyms-antonyms", "M", 0,
    ["Choose the correct synonym for the underlined word: CARDINAL", ["Chief", "Cardiac", "Correct", "Formal"], "Cardinal means chief or of the greatest importance."],
    ["रेखांकित शब्द का सही पर्यायवाची चुनिए: CARDINAL", ["Chief", "Cardiac", "Correct", "Formal"], "Cardinal का अर्थ मुख्य या सर्वाधिक महत्वपूर्ण है।"]),
  q(1, "english", "grammar", "E", 3,
    ["He deals ......... stationery.", ["with", "at", "on", "in"], "One 'deals in' goods that one sells: 'deals in stationery'."],
    ["He deals ......... stationery.", ["with", "at", "on", "in"], "बेची जाने वाली वस्तु के साथ 'deal in' आता है: 'deals in stationery'।"]),
  q(1, "english", "grammar", "E", 1,
    ["The tiger was killed ......... the hunter.", ["with", "by", "at", "of"], "In the passive voice the doer is introduced by 'by'."],
    ["The tiger was killed ......... the hunter.", ["with", "by", "at", "of"], "Passive voice में कर्ता से पहले 'by' आता है।"]),
  q(1, "english", "grammar", "E", 0,
    ["He is weak ...... chemistry.", ["at", "in", "with", "into"], "The usual collocation is 'weak at' a subject."],
    ["He is weak ...... chemistry.", ["at", "in", "with", "into"], "विषय के साथ प्रचलित प्रयोग 'weak at' है।"]),
  q(1, "english", "grammar", "M", 0,
    ["Choose the right sentence:", ["Kalidas is the Shakespeare of India.", "The Kalidas is Shakespeare of India.", "The Kalidas is the Shakespeare of India.", "Kalidas is the Shakespeare of the India."], "Proper nouns like 'Kalidas' and 'India' take no article, while 'the Shakespeare of India' is a fixed comparison."],
    ["सही वाक्य चुनिए:", ["Kalidas is the Shakespeare of India.", "The Kalidas is Shakespeare of India.", "The Kalidas is the Shakespeare of India.", "Kalidas is the Shakespeare of the India."], "'Kalidas' और 'India' जैसी व्यक्तिवाचक संज्ञाओं से पहले article नहीं आता, जबकि 'the Shakespeare of India' निश्चित तुलना है।"]),
  q(1, "english", "grammar", "M", 2,
    ["'We reached safe and sound.' Which part of speech is 'sound'?", ["Noun", "Adverb", "Adjective", "None of these"], "In 'safe and sound', 'sound' is an adjective meaning unharmed, joined to 'safe'."],
    ["'We reached safe and sound.' 'sound' कौन-सा parts of speech है?", ["Noun", "Adverb", "Adjective", "None of these"], "'safe and sound' में 'sound' विशेषण है, जिसका अर्थ सही-सलामत है।"]),
  q(1, "english", "grammar", "E", 1,
    ["Choose the correct feminine gender of 'Fox':", ["Ox", "Vixen", "Wasp", "Boar"], "The feminine of fox is vixen."],
    ["'Fox' का सही स्त्रीलिंग चुनिए:", ["Ox", "Vixen", "Wasp", "Boar"], "Fox का स्त्रीलिंग vixen है।"]),
  q(1, "english", "vocabulary", "E", 1,
    ["The young one of a 'sheep' is:", ["Cub", "Lamb", "Calf", "Foal"], "A young sheep is a lamb."],
    ["'sheep' का बच्चा कहलाता है:", ["Cub", "Lamb", "Calf", "Foal"], "भेड़ के बच्चे को lamb कहते हैं।"]),

  // ───────── Section 2: Mathematics ─────────
  q(2, "quant", "interest", "M", 1,
    ["The compound interest on ₹1000 at 10% per annum for 2 years is:", ["₹1210", "₹210", "₹200", "₹190"], "Amount = 1000 × (1.1)² = 1210, so CI = 1210 − 1000 = ₹210."],
    ["रु० 1000 पर 10% वार्षिक दर से 2 साल का चक्रवृद्धि ब्याज है:", ["रु० 1210", "रु० 210", "रु० 200", "रु० 190"], "मिश्रधन = 1000 × (1.1)² = 1210, अतः चक्रवृद्धि ब्याज = 1210 − 1000 = ₹210।"]),
  q(2, "quant", "speed-distance", "E", 2,
    ["A train covers a distance of 3750 km in 25 hours. How much average distance will the same train cover in one hour?", ["140 km", "175 km", "150 km", "130 km"], "3750 ÷ 25 = 150 km per hour."],
    ["एक रेलगाड़ी 3750 किमी० की दूरी 25 घण्टे में तय करती है, तो एक घण्टे में रेलगाड़ी की औसत तय दूरी कितनी होगी?", ["140 किमी०", "175 किमी०", "150 किमी०", "130 किमी०"], "3750 ÷ 25 = 150 किमी प्रति घंटा।"]),
  q(2, "quant", "simplification", "E", 1,
    ["The value of (−1)^1000 is:", ["−1", "1", "1000", "−1000"], "A negative number raised to an even power is positive: (−1)^1000 = 1."],
    ["(−1)^1000 का मान है:", ["−1", "1", "1000", "−1000"], "ऋणात्मक संख्या की सम घात धनात्मक होती है: (−1)^1000 = 1।"]),
  q(2, "quant", "mensuration", "M", 0,
    ["If the circumference of a circle is 132 cm, the area of the circle is:", ["1386 cm²", "1386 cm", "1486 cm²", "1320 cm²"], "2πr = 132 gives r = 21 cm. Area = (22/7) × 21 × 21 = 1386 cm²."],
    ["यदि वृत्त की परिधि 132 सेमी० हो, तो उस वृत्त का क्षेत्रफल क्या होगा?", ["1386 वर्ग सेमी०", "1386 सेमी०", "1486 वर्ग सेमी०", "1320 वर्ग सेमी०"], "2πr = 132 से r = 21 सेमी। क्षेत्रफल = (22/7) × 21 × 21 = 1386 वर्ग सेमी।"]),
  q(2, "quant", "number-system", "M", 2,
    ["If 567567567 is divided by 567, the quotient will be:", ["111", "10101", "1001001", "301"], "567567567 = 567 × 1001001, so the quotient is 1001001."],
    ["यदि 567567567 को 567 से भाग दिया जाए, तो भागफल होगा:", ["111", "10101", "1001001", "301"], "567567567 = 567 × 1001001, अतः भागफल 1001001 है।"]),
  q(2, "quant", "simplification", "M", 0,
    ["(3/4)⁷ × (4/3)⁷ = ?", ["1", "0", "14", "−1"], "(3/4 × 4/3)⁷ = 1⁷ = 1."],
    ["(3/4)⁷ × (4/3)⁷ = ?", ["1", "0", "14", "−1"], "(3/4 × 4/3)⁷ = 1⁷ = 1।"]),
  q(2, "quant", "mensuration", "M", 0,
    ["If the radius of a sphere is 2d/3, then its volume is:", ["(32/81)πd³", "(23/4)πd³", "(32/3)πd³", "(34/3)πd³"], "V = (4/3)π(2d/3)³ = (4/3) × (8/27) πd³ = (32/81)πd³."],
    ["उस गोले का आयतन, जिसकी त्रिज्या 2d/3 है, होगा:", ["(32/81)πd³", "(23/4)πd³", "(32/3)πd³", "(34/3)πd³"], "V = (4/3)π(2d/3)³ = (4/3) × (8/27) πd³ = (32/81)πd³।"]),
  q(2, "quant", "algebra", "E", 1,
    ["If the sum of two consecutive even numbers is 66, then the smaller one is:", ["34", "32", "42", "24"], "Let the numbers be x and x + 2: 2x + 2 = 66 gives x = 32."],
    ["यदि दो क्रमागत सम संख्याओं का योग 66 है, तो छोटी सम संख्या है:", ["34", "32", "42", "24"], "संख्याएँ x और x + 2 मानें: 2x + 2 = 66 से x = 32।"]),
  q(2, "reasoning", "series", "M", 1,
    ["Find the missing number in the series 2, 5, 11, 20, 32, 47, ........, 86:", ["60", "65", "58", "62"], "The differences are 3, 6, 9, 12, 15, 18, 21: 47 + 18 = 65 and 65 + 21 = 86."],
    ["श्रृंखला 2, 5, 11, 20, 32, 47, ........, 86 में लुप्त संख्या ज्ञात कीजिए:", ["60", "65", "58", "62"], "अंतर 3, 6, 9, 12, 15, 18, 21 हैं: 47 + 18 = 65 और 65 + 21 = 86।"]),
  q(2, "quant", "profit-loss", "E", 1,
    ["Mohan purchased a car for ₹8000 and sold it after one year at a loss of 25%. Find the selling price of the car.", ["₹7000", "₹6000", "₹10000", "₹9000"], "SP = 8000 × (100 − 25)/100 = ₹6000."],
    ["मोहन एक कार को रु० 8000 में खरीदता है और एक वर्ष बाद 25% हानि पर बेच देता है। कार का विक्रय मूल्य ज्ञात कीजिए:", ["रु० 7000", "रु० 6000", "रु० 10000", "रु० 9000"], "विक्रय मूल्य = 8000 × (100 − 25)/100 = ₹6000।"]),
  q(2, "quant", "simplification", "E", 2,
    ["The value of 5 + 1/100 + 5/1000 + 51/10000 is:", ["5.1551", "5.0151", "5.0201", "5.01201"], "5 + 0.01 + 0.005 + 0.0051 = 5.0201."],
    ["5 + 1/100 + 5/1000 + 51/10000 का मान है:", ["5.1551", "5.0151", "5.0201", "5.01201"], "5 + 0.01 + 0.005 + 0.0051 = 5.0201।"]),
  q(2, "quant", "simplification", "M", 1,
    ["(−7) ÷ 21/13 = ?", ["−147/13", "−13/3", "(14 − 7)/13", "13/3"], "(−7) × 13/21 = −91/21 = −13/3."],
    ["(−7) ÷ 21/13 = ?", ["−147/13", "−13/3", "(14 − 7)/13", "13/3"], "(−7) × 13/21 = −91/21 = −13/3।"]),
  q(2, "quant", "mensuration", "M", 3,
    ["The circumference of the base of a right circular cylinder is 44 cm and its height is 15 cm. The volume (in cm³) of the cylinder is (take π = 22/7):", ["770", "1155", "1540", "2310"], "2πr = 44 gives r = 7 cm. Volume = (22/7) × 49 × 15 = 2310 cm³."],
    ["किसी लंब-वृत्तीय बेलन के आधार की परिधि 44 सेमी० है और इसकी ऊँचाई 15 सेमी० है। बेलन का आयतन (सेमी०³ में) है (π = 22/7 लीजिए):", ["770", "1155", "1540", "2310"], "2πr = 44 से r = 7 सेमी। आयतन = (22/7) × 49 × 15 = 2310 सेमी³।"]),
  q(2, "quant", "hcf-lcm", "M", 0,
    ["Find the smallest square number which is exactly divisible by 4, 9 and 10:", ["900", "400", "490", "360"], "LCM(4, 9, 10) = 180 = 2² × 3² × 5. To make it a perfect square multiply by 5: 900 = 30²."],
    ["वह सबसे छोटी संख्या ज्ञात कीजिए जो 4, 9 और 10 प्रत्येक से विभाजित हो जाए (और पूर्ण वर्ग हो):", ["900", "400", "490", "360"], "LCM(4, 9, 10) = 180 = 2² × 3² × 5। पूर्ण वर्ग बनाने के लिए 5 से गुणा करें: 900 = 30²।"]),
  q(2, "quant", "percentage", "M", 2,
    ["A man got a 10% increase in his salary. If his new salary is ₹1,54,000, then the original salary is:", ["₹1,50,000", "₹1,60,000", "₹1,40,000", "₹1,45,000"], "Original = 154000 ÷ 1.10 = ₹1,40,000."],
    ["एक व्यक्ति के वेतन में 10% वृद्धि होती है। यदि उसका नया वेतन रु० 1,54,000 है, तो उसका मूल वेतन है:", ["रु० 1,50,000", "रु० 1,60,000", "रु० 1,40,000", "रु० 1,45,000"], "मूल वेतन = 154000 ÷ 1.10 = ₹1,40,000।"]),
  q(2, "quant", "algebra", "M", 0,
    ["If 56 − 45 + √x = 17, then x = ?", ["36", "25", "16", "9"], "56 − 45 = 11, so √x = 17 − 11 = 6 and x = 36."],
    ["यदि 56 − 45 + √x = 17, तो x = ?", ["36", "25", "16", "9"], "56 − 45 = 11, अतः √x = 17 − 11 = 6 और x = 36।"]),
  q(2, "quant", "number-system", "M", 2,
    ["The cube root of 1 127/216 is:", ["6/7", "−7/4", "1 1/6", "None of these"], "1 127/216 = 343/216 = (7/6)³, so the cube root is 7/6 = 1 1/6."],
    ["1 127/216 का घनमूल है:", ["6/7", "−7/4", "1 1/6", "इनमें से कोई नहीं"], "1 127/216 = 343/216 = (7/6)³, अतः घनमूल 7/6 = 1 1/6 है।"]),
  q(2, "quant", "percentage", "M", 2,
    ["The population of a village is 5000 and it increases at the rate of 2% every year. After 2 years the population will be:", ["5108", "5200", "5202", "5300"], "5000 × (1.02)² = 5000 × 1.0404 = 5202."],
    ["एक गाँव की आबादी 5000 है और 2% की दर से हर वर्ष बढ़ती है। दो वर्ष बाद कितनी आबादी होगी?", ["5108", "5200", "5202", "5300"], "5000 × (1.02)² = 5000 × 1.0404 = 5202।"]),
  q(2, "quant", "speed-distance", "M", 1,
    ["If a train 240 m long passes a pole in 16 seconds, then the speed of the train is:", ["36 km/h", "54 km/h", "60 km/h", "72 km/h"], "Speed = 240/16 = 15 m/s = 15 × 18/5 = 54 km/h."],
    ["यदि एक 240 मी० लम्बी रेलगाड़ी एक खंबे को 16 सेकेण्ड में पार कर लेती है, तो उस रेलगाड़ी की चाल है:", ["36 किमी०/घं०", "54 किमी०/घं०", "60 किमी०/घं०", "72 किमी०/घं०"], "चाल = 240/16 = 15 मी./से. = 15 × 18/5 = 54 किमी/घंटा।"]),
  q(2, "quant", "hcf-lcm", "E", 1,
    ["L.C.M. of 4, 6, 12, 15 = ?", ["180", "60", "72", "120"], "4 = 2², 6 = 2·3, 12 = 2²·3, 15 = 3·5, so the LCM = 2² × 3 × 5 = 60."],
    ["4, 6, 12, 15 का लघुत्तम समापवर्तक (ल०स०व०) = ?", ["180", "60", "72", "120"], "4 = 2², 6 = 2·3, 12 = 2²·3, 15 = 3·5, अतः ल०स०व० = 2² × 3 × 5 = 60।"]),
  q(2, "quant", "simplification", "E", 0,
    ["2⁰ × 3⁰ × 4⁰ = ?", ["1", "24", "0", "None of these"], "Any non-zero number to the power 0 is 1, so the product is 1."],
    ["2⁰ × 3⁰ × 4⁰ = ?", ["1", "24", "0", "इनमें से कोई नहीं"], "शून्येतर संख्या की घात 0 होने पर मान 1 होता है, अतः गुणनफल 1 है।"]),
  q(2, "quant", "simplification", "M", 1,
    ["The sum 0.42 + 0.042 + 0.0042 − 0.00042 is:", ["0.42424", "0.46578", "0.42654", "0.42528"], "0.42 + 0.042 + 0.0042 = 0.4662, and 0.4662 − 0.00042 = 0.46578."],
    ["0.42 + 0.042 + 0.0042 − 0.00042 का योग है:", ["0.42424", "0.46578", "0.42654", "0.42528"], "0.42 + 0.042 + 0.0042 = 0.4662 और 0.4662 − 0.00042 = 0.46578।"]),
  q(2, "quant", "percentage", "M", 1,
    ["Write 2 3/2 in percent:", ["35%", "350%", "3.5%", "0.35%"], "2 + 3/2 = 3.5, and 3.5 × 100 = 350%."],
    ["2 3/2 को प्रतिशत में लिखिए:", ["35%", "350%", "3.5%", "0.35%"], "2 + 3/2 = 3.5 और 3.5 × 100 = 350%।"]),

  // ───────── Section 3: General Knowledge ─────────
  q(3, "computer", "fundamentals", "E", 2,
    ["What is called the brain of the computer?", ["RAM", "ROM", "CPU", "Mother Board"], "The CPU (central processing unit) does all the processing and control, so it is called the brain of the computer."],
    ["कम्प्यूटर का दिमाग किसे कहते हैं?", ["रैम", "रोम", "सी.पी.यू.", "मदर बोर्ड"], "सी.पी.यू. (केंद्रीय प्रसंस्करण इकाई) सारी गणना और नियंत्रण करती है, इसलिए इसे कंप्यूटर का दिमाग कहा जाता है।"]),
  q(3, "general-studies", "general-science", "M", 0,
    ["What is the source of Sun's energy?", ["Nuclear fusion", "Nuclear fission", "Chemical reaction", "All of the above"], "The Sun produces energy by nuclear fusion of hydrogen into helium."],
    ["सौर ऊर्जा का स्रोत क्या है?", ["नाभिकीय संलयन", "नाभिकीय विखंडन", "रासायनिक क्रिया", "उपरोक्त सभी"], "सूर्य हाइड्रोजन के हीलियम में नाभिकीय संलयन से ऊर्जा उत्पन्न करता है।"]),
  q(3, "hp-gk", "history", "M", 3,
    ["Who was the leader of the Dhami Movement in 1939?", ["Kanshi Ram", "Padam Dev", "Sher Singh", "Bhagmal Sautha"], "The 1939 Dhami Prajamandal movement was led by Bhagmal Sautha, president of the Dhami Prem Pracharini Sabha."],
    ["1939 के धामी आन्दोलन के नेता कौन थे?", ["कांशी राम", "पदम देव", "शेर सिंह", "भागमल सौठा"], "1939 का धामी आंदोलन भागमल सौठा के नेतृत्व में हुआ, जो धामी प्रेम प्रचारिणी सभा के अध्यक्ष थे।"]),
  q(3, "general-studies", "indian-history", "E", 0,
    ["When did the first train run in India?", ["16 April 1853", "16 April 1852", "26 May 1851", "26 May 1850"], "India's first passenger train ran from Bori Bunder (Mumbai) to Thane on 16 April 1853."],
    ["भारत में सबसे पहली रेलगाड़ी कब चली थी?", ["16 अप्रैल, 1853", "16 अप्रैल, 1852", "26 मई, 1851", "26 मई, 1850"], "भारत की पहली यात्री रेलगाड़ी 16 अप्रैल 1853 को बोरीबंदर (मुंबई) से ठाणे के बीच चली।"]),
  q(3, "general-studies", "indian-geography", "E", 2,
    ["The main cause of an earthquake is:", ["Erosion", "Denudation", "Tectonic forces", "Weathering"], "Most earthquakes are caused by the movement of tectonic plates."],
    ["भूकंप का मुख्य कारण है:", ["क्षरण", "निरावरण", "विवर्तनिक बल", "अपक्षयण"], "अधिकांश भूकंप विवर्तनिक प्लेटों की गति से आते हैं।"]),
  q(3, "hp-gk", "polity-administration", "H", 0,
    ["When was the High Court of Himachal Pradesh established?", ["15 April 1948", "1 November 1966", "15 August 1947", "26 January 1971"], "A court for Himachal Pradesh was set up on 15 April 1948, when the state was formed; it became a full High Court after the 1971 statehood."],
    ["हिमाचल प्रदेश उच्च न्यायालय की स्थापना कब हुई?", ["15 अप्रैल, 1948", "01 नवम्बर, 1966", "15 अगस्त, 1947", "26 जनवरी, 1971"], "हिमाचल प्रदेश के गठन के साथ 15 अप्रैल 1948 को न्यायालय की स्थापना हुई; 1971 में पूर्ण राज्य बनने पर यह पूर्ण उच्च न्यायालय बना।"]),
  q(3, "general-studies", "general-science", "E", 2,
    ["What is dry ice?", ["Solid oxygen", "Solid nitrogen", "Solid carbon dioxide", "Solid sulphur"], "Dry ice is carbon dioxide in its solid state; it sublimes directly into gas."],
    ["शुष्क बर्फ क्या है?", ["ठोस ऑक्सीजन", "ठोस नाइट्रोजन", "ठोस कार्बन डाइऑक्साइड", "ठोस सल्फर"], "शुष्क बर्फ ठोस अवस्था में कार्बन डाइऑक्साइड है; यह सीधे गैस में बदल जाती है (ऊर्ध्वपातन)।"]),
  q(3, "general-studies", "general-science", "E", 1,
    ["Which planet is the hottest planet of the solar system?", ["Mercury", "Venus", "Jupiter", "Saturn"], "Venus is the hottest planet because its thick carbon dioxide atmosphere traps heat, even though Mercury is nearer to the Sun."],
    ["सौरमण्डल का सबसे गर्म ग्रह कौन-सा है?", ["बुध", "शुक्र", "बृहस्पति", "शनि"], "शुक्र का घना कार्बन डाइऑक्साइड वायुमंडल ऊष्मा रोक लेता है, इसलिए यह बुध से भी अधिक गर्म है।"]),
  q(3, "general-studies", "indian-economy", "M", 1,
    ["The National Academy of Agricultural Research Management (NAARM) is located at:", ["New Delhi", "Hyderabad", "Nagpur", "Nainital"], "NAARM is at Rajendranagar, Hyderabad."],
    ["नेशनल एकेडमी ऑफ एग्रीकल्चरल रिसर्च मेनेजमेंट (NAARM) स्थित है:", ["नई दिल्ली में", "हैदराबाद में", "नागपुर में", "नैनीताल में"], "NAARM राजेन्द्रनगर, हैदराबाद में स्थित है।"]),
  q(3, "general-studies", "general-science", "E", 0,
    ["What is the outermost layer of the teeth called?", ["Enamel", "Dentin", "Cement", "None of these"], "Enamel is the hard outer covering of a tooth."],
    ["दांतों की सबसे बाहरी परत को क्या कहते हैं?", ["इनेमल", "डेंटिन", "सीमेंट", "इनमें से कोई नहीं"], "इनेमल दाँत की सबसे बाहरी कठोर परत होती है।"]),
  q(3, "hp-gk", "geography", "M", 0,
    ["By what name was the Shivalik range known in ancient texts?", ["Mainak Parvat", "Dhauladhar", "Peer Panjal", "Jaskar"], "The Shivalik hills are described in ancient texts as the 'Mainak Parvat'."],
    ["प्राचीन ग्रंथों में शिवालिक पर्वत को किस नाम से जाना जाता है?", ["मैनाक पर्वत", "धौलाधार", "पीर पंजाल", "जास्कर"], "प्राचीन ग्रंथों में शिवालिक पहाड़ियों को 'मैनाक पर्वत' कहा गया है।"]),
  q(3, "hp-gk", "economy", "M", 2,
    ["'Kufri Jeevan' and 'Kufri Jyoti' are two famous varieties of:", ["Tomato", "Almond", "Potato", "Grapes"], "Kufri Jeevan and Kufri Jyoti are potato varieties developed at the Central Potato Research Institute, Shimla."],
    ["'कुफरी जीवन' और 'कुफरी ज्योति' दो प्रसिद्ध किस्में हैं:", ["टमाटर की", "बादाम की", "आलू की", "अंगूर की"], "कुफरी जीवन और कुफरी ज्योति केंद्रीय आलू अनुसंधान संस्थान, शिमला द्वारा विकसित आलू की किस्में हैं।"]),
  q(3, "hp-gk", "rivers-lakes", "M", 0,
    ["In which district of Himachal Pradesh is the largest natural lake located?", ["Sirmaur", "Bilaspur", "Mandi", "Chamba"], "Renuka Lake, the largest natural lake of Himachal Pradesh, is in Sirmaur district."],
    ["हिमाचल प्रदेश की सबसे बड़ी प्राकृतिक झील किस जिले में है?", ["सिरमौर", "बिलासपुर", "मण्डी", "चम्बा"], "हिमाचल प्रदेश की सबसे बड़ी प्राकृतिक झील रेणुका सिरमौर जिले में है।"]),
  q(3, "general-studies", "indian-geography", "H", 0,
    ["Which is the longest tunnel of India (among the options)?", ["Chenani-Nashri", "Jawahar", "Victory", "Leh"], "Of the tunnels listed, the Chenani–Nashri road tunnel in Jammu & Kashmir (about 9 km) is the longest. The Atal Tunnel (9.02 km, opened 2020) is now India's longest, but it is not an option here."],
    ["भारत की सबसे लंबी सुरंग कौन-सी है (दिए विकल्पों में)?", ["चेनानी-नाशरी", "जवाहर", "विक्ट्री", "लेह"], "दिए विकल्पों में जम्मू-कश्मीर की चेनानी–नाशरी सड़क सुरंग (लगभग 9 किमी) सबसे लंबी है। अटल सुरंग (9.02 किमी, 2020 में चालू) अब भारत की सबसे लंबी है, पर यहाँ विकल्प में नहीं है।"]),
  q(3, "hp-gk", "rivers-lakes", "M", 0,
    ["On which river is the Shongtong Karcham Hydro Power Project located?", ["Sutlej", "Ganga", "Chenab", "Ravi"], "The 450 MW Shongtong Karcham project in Kinnaur is on the Sutlej river."],
    ["शौंगटौंग करछम जल विद्युत परियोजना किस नदी पर स्थित है?", ["सतलुज", "गंगा", "चेनाब", "रावी"], "किन्नौर की 450 मेगावाट की शौंगटौंग करछम परियोजना सतलुज नदी पर स्थित है।"]),
  q(3, "hp-gk", "geography", "M", 3,
    ["Where is the Great Himalayan National Park situated?", ["Punjab", "Uttarakhand", "Assam", "Himachal Pradesh"], "The Great Himalayan National Park (a UNESCO World Heritage Site) is in Kullu district, Himachal Pradesh."],
    ["ग्रेट हिमालयन नेशनल पार्क कहाँ स्थित है?", ["पंजाब", "उत्तराखण्ड", "असम", "हिमाचल प्रदेश"], "ग्रेट हिमालयन नेशनल पार्क (यूनेस्को विश्व धरोहर) हिमाचल प्रदेश के कुल्लू जिले में स्थित है।"]),
  q(3, "general-studies", "indian-history", "M", 2,
    ["Who composed the grammar of the Sanskrit language?", ["Valmiki", "Tulsidas", "Panini", "Kalidas"], "Panini wrote the Ashtadhyayi, the foundational grammar of Sanskrit."],
    ["संस्कृत भाषा में व्याकरण की रचना किसने की है?", ["वाल्मीकि", "तुलसीदास", "पाणिनि", "कालिदास"], "पाणिनि ने संस्कृत व्याकरण का आधार ग्रंथ 'अष्टाध्यायी' लिखा।"]),
  q(3, "general-studies", "general-science", "E", 1,
    ["Which feature of food is identified by a red or brown mark on food packets?", ["Vegetarian", "Non-Vegetarian", "Vegetarian & Non-Vegetarian", "None of these"], "On packaged food a red or brown mark indicates non-vegetarian content, while a green mark shows vegetarian."],
    ["खाने के पैकेट पर भूरा या लाल निशान खाने की किस विशेषता को दर्शाता है?", ["शाकाहारी", "मांसाहारी", "शाकाहारी और मांसाहारी", "इनमें से कोई नहीं"], "पैकेट पर लाल या भूरा निशान मांसाहारी खाद्य को दर्शाता है, जबकि हरा निशान शाकाहारी को।"]),
  q(3, "general-studies", "indian-geography", "M", 2,
    ["'Kalindi' is the Vedic name of which river?", ["Vyas", "Ravi", "Yamuna", "Sutlej"], "Kalindi is another name for the Yamuna, which rises at Yamunotri."],
    ["'कालिन्दी' किस नदी का वैदिक नाम है?", ["व्यास", "रावी", "यमुना", "सतलुज"], "कालिन्दी यमुना नदी का एक नाम है, जो यमुनोत्री से निकलती है।"]),
  q(3, "hp-gk", "culture-festivals", "M", 2,
    ["Where is the Bhootnath temple situated?", ["Bhunter", "Sarahan", "Mandi", "Manali"], "The Bhootnath temple is in Mandi town, near the Panchvaktra and Triloknath temples."],
    ["भूतनाथ मंदिर कहाँ है?", ["भूंतर", "सराहन", "मण्डी", "मनाली"], "भूतनाथ मंदिर मंडी शहर में पंचवक्त्र और त्रिलोकनाथ मंदिरों के पास स्थित है।"]),
  q(3, "general-studies", "general-science", "E", 3,
    ["Name the creature which is not a bird but can fly:", ["Woodpecker", "Owl", "Ostrich", "Bat"], "A bat is a mammal that can fly; woodpeckers and owls are birds, and ostriches cannot fly."],
    ["कौन-सा ऐसा जीव है, जो पक्षी नहीं है फिर भी उड़ता है?", ["कठफोड़वा", "उल्लू", "शुतुर्मुर्ग", "चमगादड़"], "चमगादड़ स्तनधारी है जो उड़ सकता है; कठफोड़वा और उल्लू पक्षी हैं और शुतुर्मुर्ग उड़ नहीं सकता।"]),
  q(3, "hp-gk", "culture-festivals", "M", 2,
    ["Which place of India is known as 'Little Lhasa'?", ["Rewalsar", "Spiti", "Dharamshala", "Kinnaur"], "Dharamshala (McLeodganj), home to the Dalai Lama and the Tibetan government in exile, is called Little Lhasa."],
    ["भारत का कौन-सा स्थान 'लिटिल ल्हासा' कहलाता है?", ["रिवालसर", "स्पीति", "धर्मशाला", "किन्नौर"], "धर्मशाला (मैक्लोडगंज), जहाँ दलाई लामा और निर्वासित तिब्बती सरकार है, 'लिटिल ल्हासा' कहलाता है।"]),
  q(3, "general-studies", "general-science", "E", 1,
    ["What is the longest part of the human digestive system?", ["Large intestine", "Small intestine", "Stomach", "Rectum"], "The small intestine, about 6–7 metres long, is the longest part of the digestive tract."],
    ["मानव पाचन-तंत्र का सबसे लम्बा भाग क्या है?", ["बड़ी आंत", "छोटी आंत", "आमाशय", "मलाशय"], "छोटी आंत (लगभग 6–7 मीटर) पाचन तंत्र का सबसे लंबा भाग है।"]),
  q(3, "general-studies", "general-science", "E", 0,
    ["When is World Water Day celebrated?", ["22 March", "8 March", "5 June", "14 November"], "World Water Day is observed every year on 22 March."],
    ["विश्व जल दिवस कब मनाया जाता है?", ["22 मार्च", "8 मार्च", "5 जून", "14 नवम्बर"], "विश्व जल दिवस प्रतिवर्ष 22 मार्च को मनाया जाता है।"]),
  q(3, "general-studies", "general-science", "E", 2,
    ["The colour of leaves is green due to:", ["Zinc", "Nitrogen", "Chlorophyll", "None of these"], "Leaves are green because of the pigment chlorophyll."],
    ["पत्तों का हरा रंग किस तत्व के कारण होता है?", ["जिंक", "नाइट्रोजन", "क्लोरोफिल", "इनमें से कोई नहीं"], "पत्तियाँ क्लोरोफिल नामक वर्णक के कारण हरी होती हैं।"]),
];
