// HP Patwari recruitment exam held on 13 August 2016 (Series E) — transcribed from the solved paper, which prints the
// official answer key; every answer was re-checked independently. Left out: Q4 and Q44 (printed options are not
// distinguishable on the scan), Q23 (error-part question) and Q74 (figure). Option order is kept as printed.
// Sections: 0 Hindi, 1 English, 2 Mathematics, 3 General Knowledge.

import { q, type PatwariQuestion } from "../patwari/types";

export const y2016: PatwariQuestion[] = [
  // ───────── Section 0: Hindi ─────────
  q(0, "hindi", "vyakaran", "M", 3,
    ["How many vowels are there in the Hindi alphabet (varnamala), as counted in the official key?", ["10", "11", "12", "13"], "The official key counts 13 vowels (अ आ इ ई उ ऊ ऋ ए ऐ ओ औ along with अं and अः)."],
    ["हिन्दी वर्णमाला में स्वरों की कुल संख्या कितनी है?", ["10", "11", "12", "13"], "आधिकारिक कुंजी के अनुसार स्वर 13 हैं (अ आ इ ई उ ऊ ऋ ए ऐ ओ औ तथा अं और अः)।"]),
  q(0, "hindi", "shuddh-vartani", "E", 2,
    ["Choose the correctly spelt word: इस पुस्तक के अन्त में दो परिशिष्ट दिए गए हैं।", ["परिशिष्ठ", "परिशिषट", "परिशिष्ट", "प्रशिष्ट"], "The correct spelling is परिशिष्ट (appendix)."],
    ["शुद्ध वर्तनी वाला शब्द चुनिए: इस पुस्तक के अन्त में दो परिशिष्ट दिए गए हैं।", ["परिशिष्ठ", "परिशिषट", "परिशिष्ट", "प्रशिष्ट"], "सही वर्तनी 'परिशिष्ट' है।"]),
  q(0, "hindi", "shuddh-vartani", "M", 1,
    ["Choose the correctly spelt word: व्यावहारिक रूप में आपकी बात ठीक हो सकती है।", ["वैवाहरिक", "व्यावहारिक", "व्यवाहारिक", "वैवहारिक"], "The correct spelling is व्यावहारिक (practical)."],
    ["शुद्ध वर्तनी वाला शब्द चुनिए: व्यावहारिक रूप में आपकी बात ठीक हो सकती है।", ["वैवाहरिक", "व्यावहारिक", "व्यवाहारिक", "वैवहारिक"], "सही वर्तनी 'व्यावहारिक' है।"]),
  q(0, "hindi", "vyakaran", "E", 3,
    ["How many types of pronoun (sarvanam) are there?", ["Three", "Four", "Five", "Six"], "Pronouns are of six types: purushvachak, nishchayvachak, anishchayvachak, sambandhvachak, prashnvachak and nijvachak."],
    ["सर्वनाम के कितने भेद हैं?", ["तीन", "चार", "पाँच", "छः"], "सर्वनाम के छः भेद हैं: पुरुषवाचक, निश्चयवाचक, अनिश्चयवाचक, संबंधवाचक, प्रश्नवाचक और निजवाचक।"]),
  q(0, "hindi", "sandhi-samas", "E", 1,
    ["What is a new meaningful word formed by combining two or more words called?", ["Sandhi", "Samas", "Avyay", "Chhand"], "The joining of two or more words to form a new meaningful word is called samas (compound)."],
    ["दो अथवा दो से अधिक शब्दों से मिलकर बने हुए नए सार्थक शब्द को क्या कहते हैं?", ["संधि", "समास", "अव्यय", "छंद"], "दो या अधिक शब्दों के मेल से बने नए सार्थक शब्द को समास कहते हैं।"]),
  q(0, "hindi", "sandhi-samas", "M", 2,
    ["Which samas is 'नीलकमल'?", ["Bahuvrihi", "Tatpurush", "Karmadharay", "Dvigu"], "नीलकमल = नीला है जो कमल: the first word describes the second, so it is Karmadharay."],
    ["'नीलकमल' में कौन-सा समास है?", ["बहुब्रीहि", "तत्पुरुष", "कर्मधारय", "द्विगु"], "नीलकमल = नीला है जो कमल; पहला पद दूसरे की विशेषता बताता है, इसलिए कर्मधारय।"]),
  q(0, "hindi", "vyakaran", "M", 2,
    ["Which prefix (upsarg) is used in the word 'विज्ञान'?", ["विज्", "ज्ञान", "वि", "अन"], "विज्ञान = वि + ज्ञान, so the prefix is 'वि'."],
    ["'विज्ञान' शब्द में प्रयुक्त उपसर्ग है:", ["विज्", "ज्ञान", "वि", "अन"], "विज्ञान = वि + ज्ञान, अतः उपसर्ग 'वि' है।"]),
  q(0, "hindi", "vyakaran", "M", 3,
    ["In \"कुछ बच्चे कक्षा में शोर मचा रहे थे\", the word 'कुछ' is an adjective; what is its type?", ["Qualitative adjective", "Indefinite quantity adjective", "Pronominal adjective", "Indefinite numeral adjective"], "'कुछ बच्चे' counts children without giving an exact number, so 'कुछ' is an indefinite numeral adjective (अनिश्चित संख्यावाचक विशेषण)."],
    ["निम्नलिखित वाक्य में 'कुछ' शब्द विशेषण है, उसका भेद छाँटिए: कुछ बच्चे कक्षा में शोर मचा रहे थे।", ["गुणवाचक विशेषण", "अनिश्चित परिमाणवाचक विशेषण", "सार्वनामिक विशेषण", "अनिश्चित संख्यावाचक विशेषण"], "'कुछ बच्चे' में बच्चों की संख्या निश्चित नहीं है, इसलिए 'कुछ' अनिश्चित संख्यावाचक विशेषण है।"]),
  q(0, "hindi", "muhavare", "M", 2,
    ["What is the meaning of the idiom 'अंतर के पट खोलना'?", ["To praise", "To reveal a secret", "To use one's discretion", "To insult"], "Opening the doors of the inner self means using one's conscience and discretion."],
    ["'अंतर के पट खोलना' का अर्थ है:", ["प्रशंसा करना", "भेद खोलना", "विवेक से काम लेना", "अपमानित करना"], "अंतर के पट खोलने का अर्थ अपने विवेक से काम लेना है।"]),
  q(0, "hindi", "muhavare", "M", 3,
    ["What is the meaning of the idiom 'मंत्र फूँकना'?", ["To bring under control", "To show influence", "To calm one's anger", "To incite"], "'मंत्र फूँकना' means to mislead or incite someone."],
    ["'मंत्र फूँकना' का अर्थ है:", ["वशीकरण करना", "प्रभाव दिखाना", "क्रोध शान्त होना", "बहका देना"], "'मंत्र फूँकना' का अर्थ किसी को बहका देना है।"]),
  q(0, "hindi", "paryay-vilom", "M", 3,
    ["A synonym of 'दामिनी' is:", ["Rain", "Cloud (neerad)", "Cloud (baadal)", "Lightning"], "'दामिनी' means lightning (विद्युत)."],
    ["'दामिनी' का पर्यायवाची शब्द है:", ["वर्षा", "नीरद", "बादल", "विद्युत"], "'दामिनी' का अर्थ बिजली (विद्युत) है।"]),
  q(0, "hindi", "paryay-vilom", "E", 3,
    ["The antonym of 'मृदुल' is:", ["कठिन", "खराब", "रुक्ष", "कठोर"], "'मृदुल' means soft; its opposite is 'कठोर' (hard)."],
    ["'मृदुल' का विलोम शब्द है:", ["कठिन", "खराब", "रुक्ष", "कठोर"], "'मृदुल' का अर्थ कोमल है; विलोम 'कठोर' है।"]),
  q(0, "hindi", "ek-shabd", "E", 1,
    ["The one word for 'a fire that burns in a forest' is:", ["जठरानल", "दावानल", "बड़वानल", "कामानल"], "A forest fire is called दावानल."],
    ["जंगल में लगने वाली आग:", ["जठरानल", "दावानल", "बड़वानल", "कामानल"], "जंगल की आग को दावानल कहते हैं।"]),
  q(0, "hindi", "ek-shabd", "M", 2,
    ["The one word for 'one who can be done with hardship (difficulty)':", ["कष्टकारी", "कष्टप्रद", "कष्टसाध्य", "None of these"], "'कष्टसाध्य' means that which can be achieved only with hardship."],
    ["कष्ट से सम्पन्न होने वाला:", ["कष्टकारी", "कष्टप्रद", "कष्टसाध्य", "इनमें से कोई नहीं"], "'कष्टसाध्य' वह है जो कष्ट से पूरा होता है।"]),
  q(0, "hindi", "vyakaran", "M", 2,
    ["Choose the correct word to fill the blank: समाज के जाति और धर्म के खेमों में बंटने से राष्ट्रीय प्रगति पर गंभीर ............. लग गए हैं।", ["पदचिह्न", "लिपिचिह्न", "प्रश्नचिह्न", "विराम चिह्न"], "'प्रश्नचिह्न लगना' is the idiom meaning that doubts are raised."],
    ["उचित शब्द से रिक्त स्थान की पूर्ति कीजिए: समाज के जाति और धर्म के खेमों में बंटने से राष्ट्रीय प्रगति पर गंभीर ............. लग गए हैं।", ["पदचिह्न", "लिपिचिह्न", "प्रश्नचिह्न", "विराम चिह्न"], "'प्रश्नचिह्न लगना' मुहावरा है, जिसका अर्थ संदेह उत्पन्न होना है।"]),
  q(0, "hindi", "shabdavali", "M", 1,
    ["Fill in the blank: केवल पुस्तकीय ज्ञान छात्रों की मौलिक प्रतिभा का ............. नहीं कर सकता।", ["अमर्ष", "उन्मेष", "पीयूष", "प्रत्युष"], "'उन्मेष' means unfolding or awakening of talent."],
    ["रिक्त स्थान भरिए: केवल पुस्तकीय ज्ञान छात्रों की मौलिक प्रतिभा का ............. नहीं कर सकता।", ["अमर्ष", "उन्मेष", "पीयूष", "प्रत्युष"], "'उन्मेष' का अर्थ प्रतिभा का विकास या जागरण है।"]),
  q(0, "hindi", "shabdavali", "M", 3,
    ["Fill in the blank: वस्तुतः .................. मनुष्य वही है जो मानवता का आदर करता है।", ["यथार्थ", "चरित्रवान्", "सम्पूर्ण", "सच्चा"], "'सच्चा मनुष्य' (a true human being) fits the sentence."],
    ["रिक्त स्थान भरिए: वस्तुतः .................. मनुष्य वही है जो मानवता का आदर करता है।", ["यथार्थ", "चरित्रवान्", "सम्पूर्ण", "सच्चा"], "'सच्चा मनुष्य' वाक्य में सबसे उपयुक्त है।"]),
  q(0, "hindi", "shabdavali", "M", 2,
    ["Fill in the blank: महात्मा बुद्ध करुणा के साक्षात् ................ थे।", ["अपरिग्रह", "अनुग्रह", "विग्रह", "परिग्रह"], "'साक्षात् विग्रह' means a living embodiment."],
    ["रिक्त स्थान भरिए: महात्मा बुद्ध करुणा के साक्षात् ................ थे।", ["अपरिग्रह", "अनुग्रह", "विग्रह", "परिग्रह"], "'साक्षात् विग्रह' का अर्थ साक्षात् मूर्ति है।"]),
  q(0, "hindi", "vyakaran", "M", 2,
    ["Which of the following is a complex (mishra) sentence?", ["चोर को देखकर सिपाही पकड़ने दौड़ा।", "नेताजी भाषण देकर चले गए।", "सेठ जानता है कि नौकर ईमानदार है।", "बिजली नहीं थी इसलिए अंधेरा था।"], "A complex sentence has a main clause and a subordinate clause joined by 'कि': 'सेठ जानता है कि नौकर ईमानदार है।'"],
    ["निम्न वाक्यों में से कौन-सा मिश्र वाक्य है?", ["चोर को देखकर सिपाही पकड़ने दौड़ा।", "नेताजी भाषण देकर चले गए।", "सेठ जानता है कि नौकर ईमानदार है।", "बिजली नहीं थी इसलिए अंधेरा था।"], "मिश्र वाक्य में एक प्रधान और एक आश्रित उपवाक्य 'कि' से जुड़े होते हैं: 'सेठ जानता है कि नौकर ईमानदार है।'"]),
  q(0, "hindi", "vyakaran", "M", 2,
    ["What type of sentence is 'वह स्टेशन पहुँचा और गाड़ी छूट गई'?", ["Simple", "Complex", "Compound", "None of these"], "Two independent clauses joined by 'और' make a compound (संयुक्त) sentence."],
    ["'वह स्टेशन पहुँचा और गाड़ी छूट गई' में कौन-सा वाक्य रूप है?", ["सरल वाक्य", "मिश्र वाक्य", "संयुक्त वाक्य", "इनमें से कोई नहीं"], "'और' से जुड़े दो स्वतंत्र उपवाक्य संयुक्त वाक्य बनाते हैं।"]),
  q(0, "hindi", "vyakaran", "M", 1,
    ["In the word-pair 'अंस-अंश', choose the correct difference in meaning.", ["Part – whole", "Shoulder – part", "Edge – portion", "Family – portion"], "'अंस' means shoulder and 'अंश' means part."],
    ["'अंस-अंश' शब्द युग्म में सही अर्थ भेद का चयन कीजिए:", ["हिस्सा-कुल", "कंधा-हिस्सा", "किनारा-भाग", "परिवार-भाग"], "'अंस' का अर्थ कंधा और 'अंश' का अर्थ हिस्सा है।"]),
  q(0, "hindi", "vyakaran", "M", 0,
    ["Which of the following is a guttural (kanthya) letter?", ["ह", "ट", "त", "प"], "ह is a kanthya (guttural) letter, as are क ख ग घ ङ."],
    ["निम्नलिखित में कौन-सा कण्ठ्य वर्ण है?", ["ह", "ट", "त", "प"], "'ह' कण्ठ्य वर्ण है (क ख ग घ ङ की तरह)।"]),
  q(0, "hindi", "vyakaran", "H", 3,
    ["Arrange the parts (य), (र), (ल), (व) between the first part 1 \"गत अस्सी वर्षों के\" and the last part 6 \"सामने आकर भी नहीं आ पाती।\" to form a correct sentence.", ["व ल र य", "य व र ल", "य र ल व", "व य ल र"], "Correct order: 1 – (व) राजनीतिक-आर्थिक संघर्षों – (य) ने हमारे दिमाग को इतना भोथरा – (ल) बना दिया है कि संस्कृति की – (र) सुकुमार दुनिया हमारी पथराई आँखों के – 6."],
    ["पहले भाग 1 \"गत अस्सी वर्षों के\" और अंतिम भाग 6 \"सामने आकर भी नहीं आ पाती।\" के बीच (य), (र), (ल), (व) को उचित क्रम में लगाइए:", ["व ल र य", "य व र ल", "य र ल व", "व य ल र"], "सही क्रम: 1 – (व) राजनीतिक-आर्थिक संघर्षों – (य) ने हमारे दिमाग को इतना भोथरा – (ल) बना दिया है कि संस्कृति की – (र) सुकुमार दुनिया हमारी पथराई आँखों के – 6।"]),

  // ───────── Section 1: English ─────────
  q(1, "english", "comprehension", "E", 2,
    ["Read the passage: \"Man is the architect of his own fate. If he makes a proper division of his time, he is sure to prosper in life but if he does otherwise he is sure to repent. To kill time is sinful. Youth is golden season of life. If we lose this time, we will have to repent the whole of our life.\" — Who spoils a man's life?", ["God", "Fate", "Man himself", "Nobody"], "The passage says man is the architect of his own fate, so man himself spoils his life."],
    ["अनुच्छेद पढ़िए: \"Man is the architect of his own fate…\" (मनुष्य अपने भाग्य का स्वयं निर्माता है; समय का सही बँटवारा करने पर वह उन्नति करता है, अन्यथा पछताता है; समय को नष्ट करना पाप है; युवावस्था जीवन का स्वर्णिम काल है)। — मनुष्य के जीवन को कौन बिगाड़ता है?", ["God", "Fate", "Man himself", "Nobody"], "अनुच्छेद के अनुसार मनुष्य अपने भाग्य का स्वयं निर्माता है, इसलिए वह स्वयं ही अपना जीवन बिगाड़ता है।"]),
  q(1, "english", "comprehension", "E", 1,
    ["Same passage: In order to prosper in life, man should make best use of:", ["Fate", "Time", "Opportunities", "Ambition"], "The passage says that a proper division of time brings prosperity."],
    ["उसी अनुच्छेद के अनुसार जीवन में उन्नति करने के लिए मनुष्य को किसका सर्वोत्तम उपयोग करना चाहिए?", ["Fate", "Time", "Opportunities", "Ambition"], "अनुच्छेद के अनुसार समय का उचित विभाजन उन्नति देता है।"]),
  q(1, "english", "comprehension", "M", 1,
    ["Same passage: If we are not careful in early life, in later life we will suffer from a sense of:", ["Propensity", "Loss", "Misbehaviour", "Irregularity"], "Wasting youth leads to repentance, i.e. a sense of loss."],
    ["उसी अनुच्छेद के अनुसार यदि हम प्रारंभिक जीवन में सावधान न रहें तो बाद के जीवन में हमें किस भाव से पीड़ित होना पड़ेगा?", ["Propensity", "Loss", "Misbehaviour", "Irregularity"], "युवावस्था गँवाने से पछतावा, यानी हानि का भाव होता है।"]),
  q(1, "english", "grammar", "E", 0,
    ["There were ............... viewers than expected.", ["fewer", "less", "many", "lesser"], "'Viewers' is countable, so the comparative 'fewer' is used."],
    ["There were ............... viewers than expected.", ["fewer", "less", "many", "lesser"], "'Viewers' गणनीय है, इसलिए 'fewer' आएगा।"]),
  q(1, "english", "grammar", "E", 3,
    ["Can you bring me ................ books I left in the garden.", ["this", "that", "these", "those"], "'Those' refers to books at a distance, here in the garden."],
    ["Can you bring me ................ books I left in the garden.", ["this", "that", "these", "those"], "दूर रखी पुस्तकों के लिए 'those' आता है।"]),
  q(1, "english", "vocabulary", "M", 2,
    ["The fertility of land is barely sufficient to ................. twelve people to the acre.", ["revive", "raise", "sustain", "help"], "'Sustain' means to support or provide for."],
    ["The fertility of land is barely sufficient to ................. twelve people to the acre.", ["revive", "raise", "sustain", "help"], "'Sustain' का अर्थ पालन-पोषण करना है।"]),
  q(1, "english", "vocabulary", "M", 2,
    ["What .............. most is the positive attitude of the people?", ["impeaches", "recognises", "matters", "troubles"], "'What matters most' means what is most important."],
    ["What .............. most is the positive attitude of the people?", ["impeaches", "recognises", "matters", "troubles"], "'What matters most' का अर्थ सबसे महत्वपूर्ण बात है।"]),
  q(1, "english", "vocabulary", "H", 2,
    ["The incident has ............... severe damage to the ............... of the employees.", ["resulted–optimism", "produced–conduct", "caused–morale", "led–emotions"], "'Caused severe damage to the morale of the employees' is the natural collocation."],
    ["The incident has ............... severe damage to the ............... of the employees.", ["resulted–optimism", "produced–conduct", "caused–morale", "led–emotions"], "'caused severe damage to the morale of the employees' स्वाभाविक प्रयोग है।"]),
  q(1, "english", "grammar", "M", 1,
    ["We are leaving on Wednesday ............. or not it rains.", ["if", "whether", "through", "since"], "'Whether or not' is the fixed conjunction pair."],
    ["We are leaving on Wednesday ............. or not it rains.", ["if", "whether", "through", "since"], "'whether or not' निश्चित योजक युग्म है।"]),
  q(1, "english", "grammar", "M", 1,
    ["Pay attention to your work .............. you will not make mistakes.", ["unless", "so that", "through", "if"], "'So that' expresses purpose: pay attention so that you won't make mistakes."],
    ["Pay attention to your work .............. you will not make mistakes.", ["unless", "so that", "through", "if"], "'so that' उद्देश्य बताता है: ध्यान दो ताकि गलतियाँ न हों।"]),
  q(1, "english", "grammar", "E", 1,
    ["The football team travelled ............. train.", ["in", "by", "from", "on"], "'By train' is the usual expression for a means of transport."],
    ["The football team travelled ............. train.", ["in", "by", "from", "on"], "यात्रा के साधन के लिए 'by train' आता है।"]),
  q(1, "english", "grammar", "E", 2,
    ["He takes much interest ............... painting landscapes.", ["for", "of", "in", "to"], "'Take interest in' is the correct collocation."],
    ["He takes much interest ............... painting landscapes.", ["for", "of", "in", "to"], "'take interest in' सही प्रयोग है।"]),
  q(1, "english", "grammar", "M", 1,
    ["Ravi has been ............... in Delhi since he was five years old.", ["stayed", "staying", "stays", "stay"], "Present perfect continuous: 'has been staying'."],
    ["Ravi has been ............... in Delhi since he was five years old.", ["stayed", "staying", "stays", "stay"], "present perfect continuous: 'has been staying'।"]),
  q(1, "english", "grammar", "M", 2,
    ["What ............... you busy yesterday?", ["keeps", "will keep", "kept", "is keeping"], "'Yesterday' needs the simple past: 'What kept you busy yesterday?'"],
    ["What ............... you busy yesterday?", ["keeps", "will keep", "kept", "is keeping"], "'yesterday' के साथ simple past 'kept' आता है।"]),
  q(1, "english", "vocabulary", "M", 0,
    ["Fill in the blank: His first failure did not .......... him from making another attempt.", ["deter", "hold", "stop", "check"], "'Deter someone from doing something' is the correct structure."],
    ["Fill in the blank: His first failure did not .......... him from making another attempt.", ["deter", "hold", "stop", "check"], "'deter someone from doing' सही संरचना है।"]),
  q(1, "english", "one-word", "M", 0,
    ["One word for: 'A decorative handwriting'", ["Calligraphy", "Manuscript", "Inscription", "Hagiography"], "Calligraphy is the art of decorative handwriting."],
    ["एक शब्द: 'सजावटी हस्तलेखन'", ["Calligraphy", "Manuscript", "Inscription", "Hagiography"], "सजावटी सुंदर लेखन की कला को calligraphy कहते हैं।"]),
  q(1, "english", "one-word", "M", 3,
    ["One word for: 'Flat metal plate fixed on a wall as an ornament'", ["Tabloid", "Poster", "Board", "Plaque"], "A plaque is a flat plate fixed to a wall as an ornament or memorial."],
    ["एक शब्द: 'दीवार पर सजावट के लिए लगाई जाने वाली चपटी धातु की पट्टिका'", ["Tabloid", "Poster", "Board", "Plaque"], "दीवार पर लगी सजावटी या स्मारक पट्टिका को plaque कहते हैं।"]),
  q(1, "english", "spelling", "M", 1,
    ["Choose the word with correct spelling.", ["Pemiceous", "Pernicious", "Pemiciuos", "Pemeciuos"], "The correct spelling is 'pernicious' (harmful)."],
    ["सही वर्तनी वाला शब्द चुनिए।", ["Pemiceous", "Pernicious", "Pemiciuos", "Pemeciuos"], "सही वर्तनी 'pernicious' (हानिकारक) है।"]),
  q(1, "english", "synonyms-antonyms", "E", 1,
    ["Choose the word most opposite in meaning to: Bothered", ["Calm", "Uninterested", "Focussed", "Distracted"], "'Bothered' means interested or concerned, so 'uninterested' is the closest opposite among the options."],
    ["विलोम चुनिए: Bothered", ["Calm", "Uninterested", "Focussed", "Distracted"], "'Bothered' का अर्थ रुचि या चिंता रखना है; विकल्पों में निकटतम विलोम 'uninterested' है।"]),
  q(1, "english", "synonyms-antonyms", "E", 0,
    ["Choose the word most opposite in meaning to: Denounce", ["Accept", "Accuse", "Condemn", "Faith"], "Denounce means to condemn publicly; its opposite is 'accept'."],
    ["विलोम चुनिए: Denounce", ["Accept", "Accuse", "Condemn", "Faith"], "Denounce का अर्थ सार्वजनिक निंदा करना है; विलोम 'accept' है।"]),
  q(1, "english", "synonyms-antonyms", "E", 1,
    ["Choose the word most similar in meaning to: Stunned", ["Fainted", "Surprised", "Pleased", "Injured"], "Stunned means astonished or shocked — surprised."],
    ["समानार्थी चुनिए: Stunned", ["Fainted", "Surprised", "Pleased", "Injured"], "Stunned का अर्थ हक्का-बक्का, यानी surprised है।"]),
  q(1, "english", "synonyms-antonyms", "E", 1,
    ["Choose the word most similar in meaning to: Gallantry", ["Maverick", "Valour", "Cowardice", "Fearfulness"], "Gallantry means bravery — valour."],
    ["समानार्थी चुनिए: Gallantry", ["Maverick", "Valour", "Cowardice", "Fearfulness"], "Gallantry का अर्थ वीरता, यानी valour है।"]),
  q(1, "english", "idioms", "E", 3,
    ["Complete the proverb: Birds of a feather ............", ["live together", "breed together", "fly together", "flock together"], "'Birds of a feather flock together.'"],
    ["कहावत पूरी कीजिए: Birds of a feather ............", ["live together", "breed together", "fly together", "flock together"], "'Birds of a feather flock together.'"]),
  q(1, "english", "idioms", "M", 0,
    ["Choose the correct meaning of the underlined idiom: The scientist worked for donkey's years to arrive at the formula.", ["a long time", "a short time", "for donkeys", "for a few years"], "'Donkey's years' means a very long time."],
    ["रेखांकित मुहावरे का सही अर्थ चुनिए: The scientist worked for donkey's years to arrive at the formula.", ["a long time", "a short time", "for donkeys", "for a few years"], "'Donkey's years' का अर्थ बहुत लंबा समय है।"]),

  // ───────── Section 2: Mathematics ─────────
  q(2, "quant", "simplification", "E", 1,
    ["What comes in place of '?': 8597 − ? = 7429 − 4358", ["5496", "5526", "5706", "5476"], "7429 − 4358 = 3071, so ? = 8597 − 3071 = 5526."],
    ["'?' के स्थान पर क्या आएगा: 8597 − ? = 7429 − 4358", ["5496", "5526", "5706", "5476"], "7429 − 4358 = 3071, अतः ? = 8597 − 3071 = 5526।"]),
  q(2, "quant", "hcf-lcm", "M", 2,
    ["The HCF and LCM of two numbers x and y are 3 and 105 respectively. If x + y = 36 then 1/x + 1/y = ?", ["35", "3/5", "4/35", "1/35"], "xy = 3 × 105 = 315, so 1/x + 1/y = (x + y)/xy = 36/315 = 4/35."],
    ["दो संख्याओं x और y का म.स.प. और ल.स.प. क्रमशः 3 और 105 है। यदि x + y = 36 है तो 1/x + 1/y = ?", ["35", "3/5", "4/35", "1/35"], "xy = 3 × 105 = 315, अतः 1/x + 1/y = (x + y)/xy = 36/315 = 4/35।"]),
  q(2, "quant", "simplification", "H", 2,
    ["Find: [(0.06)² + (0.47)² + (0.079)²] ÷ [(0.006)² + (0.047)² + (0.0079)²] = ?", ["0.1", "1.0", "100", "1000"], "Each term in the denominator is the matching numerator term divided by 10, so its square is 1/100. The ratio is therefore 100."],
    ["मान ज्ञात कीजिए: [(0.06)² + (0.47)² + (0.079)²] ÷ [(0.006)² + (0.047)² + (0.0079)²] = ?", ["0.1", "1.0", "100", "1000"], "हर का प्रत्येक पद अंश के संगत पद का 1/10 है, इसलिए उसका वर्ग 1/100 है। अतः अनुपात 100 है।"]),
  q(2, "quant", "simplification", "M", 3,
    ["Simplify: 5 5/6 × 6 3/7 + 5 1/2 = ?", ["40", "40.5", "42.5", "43"], "35/6 × 45/7 = 75/2, and 75/2 + 11/2 = 86/2 = 43."],
    ["सरल कीजिए: 5 5/6 × 6 3/7 + 5 1/2 = ?", ["40", "40.5", "42.5", "43"], "35/6 × 45/7 = 75/2, और 75/2 + 11/2 = 86/2 = 43।"]),
  q(2, "quant", "algebra", "M", 3,
    ["If x × √0.0016 = 4, then x = ?", ["0.04", "4", "25", "100"], "√0.0016 = 0.04, so x = 4 ÷ 0.04 = 100."],
    ["यदि x × √0.0016 = 4 है, तो x का मान है:", ["0.04", "4", "25", "100"], "√0.0016 = 0.04, अतः x = 4 ÷ 0.04 = 100।"]),
  q(2, "quant", "percentage", "M", 0,
    ["If 60% of (x − y) = 40% of (x + y), then what percent of x is y?", ["20%", "25%", "22%", "None of these"], "0.6(x − y) = 0.4(x + y) gives 0.2x = y, so y is 20% of x."],
    ["यदि (x − y) का 60% = (x + y) का 40% है, तो y, x का कितने प्रतिशत है?", ["20%", "25%", "22%", "इनमें से कोई नहीं"], "0.6(x − y) = 0.4(x + y) से 0.2x = y, अतः y, x का 20% है।"]),
  q(2, "quant", "ratio-proportion", "M", 2,
    ["Of three numbers, the ratio of the first and second is 8 : 9 and that of the second and third is 3 : 4. If the product of the first and third numbers is 2400, find the second number.", ["40", "60", "45", "50"], "The ratio is 8 : 9 : 12, so the numbers are 8k, 9k, 12k. 96k² = 2400 gives k = 5, and the second number is 45."],
    ["तीन संख्याओं में पहली और दूसरी का अनुपात 8 : 9 तथा दूसरी और तीसरी का अनुपात 3 : 4 है। यदि पहली और तीसरी का गुणनफल 2400 है, तो दूसरी संख्या ज्ञात कीजिए।", ["40", "60", "45", "50"], "अनुपात 8 : 9 : 12 है, संख्याएँ 8k, 9k, 12k। 96k² = 2400 से k = 5, अतः दूसरी संख्या 45।"]),
  q(2, "quant", "algebra", "M", 2,
    ["If 2^(2x+4) = 16^x, then x³ = ?", ["2", "4", "8", "16"], "2^(2x+4) = 2^(4x) gives 2x + 4 = 4x, so x = 2 and x³ = 8."],
    ["यदि 2^(2x+4) = 16^x है, तो x³ = ?", ["2", "4", "8", "16"], "2^(2x+4) = 2^(4x) से 2x + 4 = 4x, अतः x = 2 और x³ = 8।"]),
  q(2, "quant", "ratio-proportion", "M", 1,
    ["Two numbers are respectively 20% and 50% more than a third number. The ratio of these two numbers is:", ["2 : 5", "4 : 5", "6 : 7", "3 : 5"], "Taking the third number as 100, the numbers are 120 and 150, so the ratio is 120 : 150 = 4 : 5."],
    ["दो संख्याएँ तीसरी संख्या से क्रमशः 20% और 50% अधिक हैं। इन दोनों संख्याओं का अनुपात है:", ["2 : 5", "4 : 5", "6 : 7", "3 : 5"], "तीसरी संख्या 100 मानें तो संख्याएँ 120 और 150 हैं, अनुपात 120 : 150 = 4 : 5।"]),
  q(2, "reasoning", "series", "M", 1,
    ["Find the missing number in the series: 2, 5, 11, 20, 32, 47, ......... 86", ["60", "65", "58", "62"], "The differences are 3, 6, 9, 12, 15, 18, 21: 47 + 18 = 65 and 65 + 21 = 86."],
    ["श्रृंखला में लुप्त संख्या ज्ञात कीजिए: 2, 5, 11, 20, 32, 47, ......... 86", ["60", "65", "58", "62"], "अंतर 3, 6, 9, 12, 15, 18, 21 हैं: 47 + 18 = 65 और 65 + 21 = 86।"]),
  q(2, "quant", "profit-loss", "H", 3,
    ["'A' purchased some oranges at a total cost of ₹1200. He sold 1/3rd of these oranges at a loss of 20%. If A had a profit of 10% overall, at what profit were the remaining oranges sold?", ["16%", "15%", "22%", "25%"], "1/3 of the oranges cost ₹400 and sold for 320. Total sale = 1320, so the remaining oranges (cost ₹800) sold for 1000, a profit of 25%."],
    ["'A' ने कुछ संतरे कुल ₹1200 में खरीदे। उसने इनका 1/3 भाग 20% हानि पर बेचा। यदि A को कुल 10% लाभ हुआ तो शेष संतरे कितने प्रतिशत लाभ पर बेचे गए?", ["16%", "15%", "22%", "25%"], "1/3 संतरों की लागत ₹400, बिक्री ₹320। कुल बिक्री ₹1320, अतः शेष संतरे (लागत ₹800) ₹1000 में बिके, यानी 25% लाभ।"]),
  q(2, "quant", "profit-loss", "M", 3,
    ["A shopkeeper sells his goods at cost price but uses a 900 gm weight for 1 kg. His gain percentage is:", ["9%", "10%", "11%", "11 1/9%"], "He gives 900 g but charges for 1000 g, so gain = 100/900 = 11 1/9%."],
    ["एक दुकानदार अपना सामान क्रय मूल्य पर बेचता है, पर 1 किग्रा के स्थान पर 900 ग्राम का बाट प्रयोग करता है। उसका लाभ प्रतिशत है:", ["9%", "10%", "11%", "11 1/9%"], "वह 900 ग्राम देकर 1000 ग्राम के पैसे लेता है, अतः लाभ = 100/900 = 11 1/9%।"]),
  q(2, "quant", "ratio-proportion", "M", 3,
    ["Two numbers are in the ratio 3 : 5. If each number is increased by 10 the ratio becomes 5 : 7. The numbers are:", ["3, 5", "7, 9", "13, 12", "15, 25"], "(3x + 10)/(5x + 10) = 5/7 gives 21x + 70 = 25x + 50, so x = 5 and the numbers are 15 and 25."],
    ["दो संख्याओं का अनुपात 3 : 5 है। यदि प्रत्येक संख्या में 10 जोड़ दिया जाए तो अनुपात 5 : 7 हो जाता है। संख्याएँ हैं:", ["3, 5", "7, 9", "13, 12", "15, 25"], "(3x + 10)/(5x + 10) = 5/7 से 21x + 70 = 25x + 50, अतः x = 5 और संख्याएँ 15 तथा 25।"]),
  q(2, "quant", "ages", "M", 3,
    ["At present the ages of Ram and Shyam are in the ratio 5 : 4. After 3 years the ratio will become 11 : 9. Find the present age of Shyam.", ["28", "27", "26", "24"], "(5x + 3)/(4x + 3) = 11/9 gives 45x + 27 = 44x + 33, so x = 6 and Shyam's age = 4 × 6 = 24."],
    ["वर्तमान में राम और श्याम की आयु का अनुपात 5 : 4 है। 3 वर्ष बाद यह अनुपात 11 : 9 हो जाएगा। श्याम की वर्तमान आयु ज्ञात कीजिए।", ["28", "27", "26", "24"], "(5x + 3)/(4x + 3) = 11/9 से 45x + 27 = 44x + 33, अतः x = 6 और श्याम की आयु = 4 × 6 = 24।"]),
  q(2, "quant", "partnership", "H", 3,
    ["'A' and 'B' began a business with ₹3500 and ₹2500 respectively. After 4 months 'C' joined with ₹6000. If the difference of share between C and B is ₹1977, find the total annual income.", ["₹15620", "₹16240", "₹12770", "₹13180"], "Investments over the year: A = 3500 × 12 = 42000, B = 30000, C = 6000 × 8 = 48000 (total 120000). C − B = 18000/120000 of the income = 1977, so income = ₹13,180."],
    ["'A' और 'B' ने क्रमशः ₹3500 और ₹2500 से व्यापार शुरू किया। 4 महीने बाद 'C' ₹6000 के साथ शामिल हुआ। यदि C और B के हिस्से का अंतर ₹1977 है, तो कुल वार्षिक आय ज्ञात कीजिए।", ["₹15620", "₹16240", "₹12770", "₹13180"], "वर्ष भर का निवेश: A = 3500 × 12 = 42000, B = 30000, C = 6000 × 8 = 48000 (कुल 120000)। C − B = आय का 18000/120000 = 1977, अतः आय = ₹13,180।"]),
  q(2, "quant", "algebra", "M", 2,
    ["If x + y = 18 and xy = 72, what is the value of x² + y²?", ["120", "90", "180", "Cannot be determined"], "x² + y² = (x + y)² − 2xy = 324 − 144 = 180."],
    ["यदि x + y = 18 और xy = 72 है, तो x² + y² का मान क्या है?", ["120", "90", "180", "निर्धारित नहीं किया जा सकता"], "x² + y² = (x + y)² − 2xy = 324 − 144 = 180।"]),
  q(2, "quant", "time-work", "M", 2,
    ["36 labourers complete a work in 14 days. If the work is to be completed in 8 days, how many additional labourers are needed?", ["29", "33", "27", "23"], "Total work = 36 × 14 = 504 man-days. For 8 days, 504 ÷ 8 = 63 labourers are needed, i.e. 27 more."],
    ["36 मजदूर एक कार्य 14 दिनों में पूरा करते हैं। यदि कार्य 8 दिनों में पूरा करना हो तो कितने अतिरिक्त मजदूरों की आवश्यकता होगी?", ["29", "33", "27", "23"], "कुल कार्य = 36 × 14 = 504 मजदूर-दिन। 8 दिनों के लिए 504 ÷ 8 = 63 मजदूर चाहिए, यानी 27 अतिरिक्त।"]),
  q(2, "quant", "time-work", "H", 2,
    ["'A' is 60% more efficient than B. If 'A' takes 15 days to complete the work, then A and B together complete the work in how many days?", ["9 7/13", "8 9/13", "9 3/13", "10 1/13"], "B takes 15 × 1.6 = 24 days. Together: 1/15 + 1/24 = 13/120 per day, so 120/13 = 9 3/13 days."],
    ["'A', B से 60% अधिक कुशल है। यदि 'A' कार्य 15 दिनों में पूरा करता है, तो A और B मिलकर कार्य कितने दिनों में पूरा करेंगे?", ["9 7/13", "8 9/13", "9 3/13", "10 1/13"], "B को 15 × 1.6 = 24 दिन लगते हैं। साथ में: 1/15 + 1/24 = 13/120 प्रतिदिन, अतः 120/13 = 9 3/13 दिन।"]),
  q(2, "quant", "algebra", "H", 3,
    ["Solve: I. x² + 8x + 15 = 0, II. y² + 3y + 2 = 0. Choose the correct relation.", ["x > y", "x ≤ y", "x ≥ y", "x < y"], "x = −3 or −5 and y = −1 or −2. Every possible x is smaller than every possible y, so x < y."],
    ["हल कीजिए: I. x² + 8x + 15 = 0, II. y² + 3y + 2 = 0. सही संबंध चुनिए।", ["x > y", "x ≤ y", "x ≥ y", "x < y"], "x = −3 या −5 और y = −1 या −2। x का हर मान y के हर मान से छोटा है, अतः x < y।"]),
  q(2, "quant", "interest", "M", 0,
    ["₹2000 amounts to ₹2600 in 5 years at simple interest. If the interest rate is increased by 3%, how much would it amount to?", ["₹2900", "₹3600", "₹3200", "None of these"], "SI = 600 in 5 years gives a rate of 6%. At 9%: SI = 2000 × 0.09 × 5 = 900, so the amount = ₹2900."],
    ["₹2000, 5 वर्ष में साधारण ब्याज पर ₹2600 हो जाते हैं। यदि ब्याज दर 3% बढ़ा दी जाए तो यह कितना हो जाएगा?", ["₹2900", "₹3600", "₹3200", "इनमें से कोई नहीं"], "5 वर्ष में ब्याज 600 है, अतः दर 6%। 9% पर ब्याज = 2000 × 0.09 × 5 = 900, मिश्रधन = ₹2900।"]),
  q(2, "quant", "geometry", "M", 1,
    ["Distance between the pair of points (−5, 7) and (−1, 3):", ["4", "4√2", "8", "16"], "√[(−1 + 5)² + (3 − 7)²] = √(16 + 16) = 4√2."],
    ["बिंदुओं (−5, 7) और (−1, 3) के बीच की दूरी है:", ["4", "4√2", "8", "16"], "√[(−1 + 5)² + (3 − 7)²] = √(16 + 16) = 4√2।"]),
  q(2, "quant", "interest", "M", 0,
    ["Find the compound interest on ₹12600 at 10% per annum for 2 years compounded yearly.", ["₹2646", "₹2600", "₹2746", "₹2800"], "Amount = 12600 × 1.1 × 1.1 = 15246, so CI = 15246 − 12600 = ₹2646."],
    ["₹12600 पर 10% वार्षिक दर से 2 वर्ष का वार्षिक चक्रवृद्धि ब्याज ज्ञात कीजिए।", ["₹2646", "₹2600", "₹2746", "₹2800"], "मिश्रधन = 12600 × 1.1 × 1.1 = 15246, अतः चक्रवृद्धि ब्याज = 15246 − 12600 = ₹2646।"]),
  q(2, "quant", "percentage", "M", 0,
    ["If the radius of a circle is decreased by 20%, find the percentage decrease in its area.", ["36%", "32%", "21%", "42%"], "New area = (0.8)² = 0.64 of the old area, a decrease of 36%."],
    ["यदि किसी वृत्त की त्रिज्या 20% घटा दी जाए, तो उसके क्षेत्रफल में कितने प्रतिशत की कमी होगी?", ["36%", "32%", "21%", "42%"], "नया क्षेत्रफल = (0.8)² = पुराने का 0.64, यानी 36% की कमी।"]),
  q(2, "quant", "speed-distance", "M", 3,
    ["An aeroplane covers a certain distance at a speed of 240 km/hour in 5 hours. If the same distance is to be covered in 1 2/3 hours, what will be the speed of the aeroplane?", ["300 km/hour", "360 km/hour", "700 km/hour", "720 km/hour"], "Distance = 240 × 5 = 1200 km. Speed = 1200 ÷ (5/3) = 720 km/hour."],
    ["एक हवाई जहाज 240 किमी/घंटा की गति से 5 घंटों में एक निश्चित दूरी तय करता है। यदि यही दूरी 1 2/3 घंटे में तय करनी हो तो हवाई जहाज की गति क्या होगी?", ["300 किमी/घंटा", "360 किमी/घंटा", "700 किमी/घंटा", "720 किमी/घंटा"], "दूरी = 240 × 5 = 1200 किमी। गति = 1200 ÷ (5/3) = 720 किमी/घंटा।"]),

  // ───────── Section 3: General Knowledge ─────────
  q(3, "hp-gk", "history", "M", 0,
    ["When were the Punjab Hill areas transferred to Himachal Pradesh?", ["1 November 1966", "1 October 1956", "1 January 1971", "15 August 1972"], "Under the Punjab Reorganisation Act, the hill areas of Punjab were merged with Himachal Pradesh on 1 November 1966."],
    ["पंजाब के पहाड़ी क्षेत्र हिमाचल प्रदेश को कब हस्तांतरित किए गए थे?", ["1 नवम्बर 1966", "1 अक्टूबर 1956", "1 जनवरी 1971", "15 अगस्त 1972"], "पंजाब पुनर्गठन अधिनियम के तहत पंजाब के पहाड़ी क्षेत्र 1 नवम्बर 1966 को हिमाचल प्रदेश में मिलाए गए।"]),
  q(3, "hp-gk", "culture-festivals", "H", 0,
    ["The 'Bhumda' festival (celebrated in Shimla, Kullu and Manali) is associated with:", ["Parshuram", "Lomasha Rishi", "Buddha", "Mahasu Devta"], "Bhunda (Bhumda) is celebrated in honour of Parshuram, notably at Nirmand in Kullu."],
    ["'भुण्डा' उत्सव (शिमला, कुल्लू और मनाली में मनाया जाता है) किससे संबंधित है?", ["परशुराम", "लोमश ऋषि", "बुद्ध", "महासू देवता"], "भुण्डा उत्सव परशुराम के सम्मान में मनाया जाता है, विशेषकर कुल्लू के निरमंड में।"]),
  q(3, "hp-gk", "geography", "M", 3,
    ["Which mountain range separates Himachal Pradesh from Tibet?", ["Dhauladhar", "Pirpanjal", "Hindukush", "Zaskar"], "The Zaskar range forms the boundary between Himachal Pradesh and Tibet."],
    ["कौन-सी पर्वत श्रृंखला हिमाचल प्रदेश को तिब्बत से अलग करती है?", ["धौलाधार", "पीरपंजाल", "हिंदूकुश", "जास्कर"], "जास्कर पर्वत श्रृंखला हिमाचल प्रदेश और तिब्बत के बीच की सीमा बनाती है।"]),
  q(3, "hp-gk", "history", "M", 1,
    ["Who was the commander of the Gorkha Army who attacked Himachal Pradesh in the first decade of the 19th century?", ["Bhakti Thapa", "Amar Singh Thapa", "Ram Singh Gurung", "Tej Bahadur"], "Amar Singh Thapa led the Gorkha army that overran the Himachal hill states (Kangra siege 1806–09)."],
    ["19वीं सदी के पहले दशक में हिमाचल प्रदेश पर आक्रमण करने वाली गोरखा सेना का सेनापति कौन था?", ["भक्ति थापा", "अमर सिंह थापा", "राम सिंह गुरुंग", "तेज बहादुर"], "अमर सिंह थापा ने उस गोरखा सेना का नेतृत्व किया जिसने हिमाचल की पहाड़ी रियासतों पर आक्रमण किया (कांगड़ा की घेराबंदी 1806–09)।"]),
  q(3, "hp-gk", "history", "H", 2,
    ["In 1809 the Jawalamukhi Treaty was signed between:", ["Gorkhas and Sikhs", "Sikhs and the British", "Sansar Chand and Raja Ranjeet Singh", "Raja Ranjeet Singh and the British"], "By the 1809 Treaty of Jawalamukhi, Sansar Chand of Kangra allied with Maharaja Ranjit Singh against the Gorkhas."],
    ["1809 में ज्वालामुखी संधि किनके बीच हुई थी?", ["गोरखा और सिख", "सिख और अंग्रेज", "संसार चंद और राजा रणजीत सिंह", "राजा रणजीत सिंह और अंग्रेज"], "1809 की ज्वालामुखी संधि में कांगड़ा के संसार चंद ने गोरखों के विरुद्ध महाराजा रणजीत सिंह से गठबंधन किया।"]),
  q(3, "hp-gk", "economy", "M", 1,
    ["Which is the oldest hydro-electric project in Himachal Pradesh?", ["Baner (Kangra)", "Shanan Joginder Nagar", "Bhakhra (Bilaspur)", "Thirot (Lahaul)"], "The Shanan Power House at Joginder Nagar (Mandi), commissioned in 1932, is the oldest."],
    ["हिमाचल प्रदेश की सबसे पुरानी जल-विद्युत परियोजना कौन-सी है?", ["बनेर (कांगड़ा)", "शानन जोगिन्दर नगर", "भाखड़ा (बिलासपुर)", "थिरोट (लाहौल)"], "जोगिंदर नगर (मंडी) का शानन विद्युत गृह, जो 1932 में चालू हुआ, सबसे पुराना है।"]),
  q(3, "hp-gk", "culture-festivals", "M", 0,
    ["'Jhanjar' is a famous dance of which district?", ["Chamba", "Mandi", "Kullu", "Kangra"], "Jhanjar (Jhanjhar) is a folk dance of Chamba district."],
    ["'झांजर' किस जिले का प्रसिद्ध नृत्य है?", ["चंबा", "मंडी", "कुल्लू", "कांगड़ा"], "झांजर चंबा जिले का लोक नृत्य है।"]),
  q(3, "hp-gk", "polity-administration", "M", 1,
    ["In Himachal Pradesh the number of members elected to the Rajya Sabha is:", ["2", "3", "6", "4"], "Himachal Pradesh sends 3 members to the Rajya Sabha."],
    ["हिमाचल प्रदेश से राज्य सभा के लिए निर्वाचित सदस्यों की संख्या है:", ["2", "3", "6", "4"], "हिमाचल प्रदेश से राज्य सभा में 3 सदस्य जाते हैं।"]),
  q(3, "hp-gk", "districts", "M", 1,
    ["Under the Government of India scheme, which town of Himachal Pradesh was recently selected to be developed as a 'Smart City'?", ["Shimla", "Dharamsala", "Manali", "Una"], "Dharamshala was selected for the Smart City mission in 2016."],
    ["भारत सरकार की योजना के अंतर्गत हिमाचल प्रदेश के किस नगर को हाल ही में 'स्मार्ट सिटी' के रूप में विकसित करने के लिए चुना गया?", ["शिमला", "धर्मशाला", "मनाली", "ऊना"], "धर्मशाला को 2016 में स्मार्ट सिटी मिशन के लिए चुना गया।"]),
  q(3, "hp-gk", "history", "M", 3,
    ["Who led the Suket Satyagraha on 18 February 1948?", ["Sada Ram Chandel", "Sita Ram Sharma", "Bhagmal Sautha", "Pt. Padam Dev"], "Pt. Padam Dev led the Suket Satyagraha of February 1948 (Dr Y.S. Parmar was the main leader of the movement)."],
    ["18 फरवरी 1948 को सुकेत सत्याग्रह का नेतृत्व किसने किया?", ["सदा राम चंदेल", "सीता राम शर्मा", "भागमल सौठा", "पं. पदम देव"], "फरवरी 1948 के सुकेत सत्याग्रह का नेतृत्व पं. पदम देव ने किया (आंदोलन के प्रमुख नेता डॉ. वाई.एस. परमार थे)।"]),
  q(3, "general-studies", "indian-geography", "E", 0,
    ["Which group of rivers flows into the Bay of Bengal?", ["Brahmaputra, Ganga, Godavari", "Cauveri, Krishna, Narmada", "Krishna, Godavari, Tapti", "Narmada, Ganga, Brahmputra"], "The Brahmaputra, Ganga and Godavari all drain into the Bay of Bengal. The Narmada and Tapti flow into the Arabian Sea."],
    ["नदियों का कौन-सा समूह बंगाल की खाड़ी में गिरता है?", ["ब्रह्मपुत्र, गंगा, गोदावरी", "कावेरी, कृष्णा, नर्मदा", "कृष्णा, गोदावरी, तापी", "नर्मदा, गंगा, ब्रह्मपुत्र"], "ब्रह्मपुत्र, गंगा और गोदावरी बंगाल की खाड़ी में गिरती हैं। नर्मदा और तापी अरब सागर में गिरती हैं।"]),
  q(3, "general-studies", "indian-geography", "M", 2,
    ["Arrange the following layers of atmosphere vertically from the surface of the earth: 1. Mesosphere 2. Troposphere 3. Stratosphere 4. Thermosphere", ["1-2-3-4", "2-1-3-4", "2-3-1-4", "3-4-2-1"], "From the ground upward: Troposphere, Stratosphere, Mesosphere, Thermosphere (2-3-1-4)."],
    ["वायुमंडल की निम्न परतों को पृथ्वी की सतह से ऊपर की ओर क्रम में लगाइए: 1. मध्यमंडल 2. क्षोभमंडल 3. समतापमंडल 4. तापमंडल", ["1-2-3-4", "2-1-3-4", "2-3-1-4", "3-4-2-1"], "सतह से ऊपर: क्षोभमंडल, समतापमंडल, मध्यमंडल, तापमंडल (2-3-1-4)।"]),
  q(3, "general-studies", "general-science", "E", 1,
    ["In the human digestive system, the process of digestion starts in:", ["Oesophagus", "Oral (Buccal) Cavity", "Duodenum", "Stomach"], "Digestion begins in the mouth, where saliva starts breaking down starch."],
    ["मानव पाचन तंत्र में पाचन की प्रक्रिया कहाँ से शुरू होती है?", ["ग्रासनली", "मुख गुहा", "ग्रहणी", "आमाशय"], "पाचन मुख में शुरू होता है, जहाँ लार स्टार्च का विघटन शुरू करती है।"]),
  q(3, "general-studies", "general-science", "M", 2,
    ["Which one among the following statements is not true for mammals?", ["They possess hair on the body", "Some of them lay eggs", "Their heart is three chambered", "Some are aquatic"], "Mammals have a four-chambered heart, so 'three chambered' is false."],
    ["निम्नलिखित में से कौन-सा कथन स्तनधारियों के लिए सत्य नहीं है?", ["उनके शरीर पर बाल होते हैं", "उनमें से कुछ अंडे देते हैं", "उनका हृदय तीन कक्षीय होता है", "कुछ जलीय होते हैं"], "स्तनधारियों का हृदय चार कक्षीय होता है, इसलिए 'तीन कक्षीय' असत्य है।"]),
  q(3, "general-studies", "general-science", "M", 3,
    ["Which one among the following metals is mainly used in mobile phone batteries?", ["Copper", "Zinc", "Nicked", "Lithium"], "Lithium-ion batteries power mobile phones."],
    ["निम्नलिखित धातुओं में से कौन-सी मुख्यतः मोबाइल फोन की बैटरी में प्रयुक्त होती है?", ["तांबा", "जिंक", "निकल", "लिथियम"], "मोबाइल फोन लिथियम-आयन बैटरी से चलते हैं।"]),
  q(3, "computer", "programming-basics", "E", 3,
    ["Which of the following is not a computer language?", ["BASIC", "C++", "JAVA", "PAINT BRUSH"], "Paint Brush is an image-editing application, not a programming language."],
    ["निम्नलिखित में से कौन-सी कंप्यूटर भाषा नहीं है?", ["BASIC", "C++", "JAVA", "PAINT BRUSH"], "पेंट ब्रश चित्र बनाने का एप्लिकेशन है, प्रोग्रामिंग भाषा नहीं।"]),
  q(3, "general-studies", "indian-history", "M", 2,
    ["In the Indus valley civilization which among the following was a port city?", ["Mohenjo Daro", "Harappa", "Lothal", "Kalibangan"], "Lothal had a dockyard and was a major port city."],
    ["सिंधु घाटी सभ्यता में निम्नलिखित में से कौन-सा एक बंदरगाह नगर था?", ["मोहनजोदड़ो", "हड़प्पा", "लोथल", "कालीबंगा"], "लोथल में गोदी (डॉकयार्ड) थी और यह प्रमुख बंदरगाह नगर था।"]),
  q(3, "general-studies", "indian-history", "M", 1,
    ["\"Purna Swaraj\" was announced in the Indian National Congress session of:", ["Calcutta", "Lahore", "Nagpur", "Karachi"], "The Lahore session (December 1929, under Jawaharlal Nehru) declared Purna Swaraj as the goal."],
    ["\"पूर्ण स्वराज\" की घोषणा भारतीय राष्ट्रीय कांग्रेस के किस अधिवेशन में की गई थी?", ["कलकत्ता", "लाहौर", "नागपुर", "कराची"], "लाहौर अधिवेशन (दिसंबर 1929, जवाहरलाल नेहरू की अध्यक्षता में) ने पूर्ण स्वराज को लक्ष्य घोषित किया।"]),
  q(3, "general-studies", "indian-polity", "M", 1,
    ["Which of the following awards is given for excellence in sports coaching?", ["Sahitya Academy Award", "Dronacharya Award", "Arjuna Award", "Dada Saheb Phalke Award"], "The Dronacharya Award honours outstanding coaches."],
    ["निम्नलिखित में से कौन-सा पुरस्कार खेल प्रशिक्षण में उत्कृष्टता के लिए दिया जाता है?", ["साहित्य अकादमी पुरस्कार", "द्रोणाचार्य पुरस्कार", "अर्जुन पुरस्कार", "दादा साहेब फाल्के पुरस्कार"], "द्रोणाचार्य पुरस्कार उत्कृष्ट प्रशिक्षकों को दिया जाता है।"]),
  q(3, "general-studies", "indian-history", "M", 3,
    ["Which team won the IPL-9 tournament on 29 May 2016?", ["Kolkata Knight Riders", "Royal Challengers Bangalore", "Kings XI Punjab", "Sunrisers Hyderabad"], "Sunrisers Hyderabad beat Royal Challengers Bangalore in the IPL 2016 final."],
    ["29 मई 2016 को आईपीएल-9 टूर्नामेंट किस टीम ने जीता?", ["कोलकाता नाइट राइडर्स", "रॉयल चैलेंजर्स बैंगलोर", "किंग्स इलेवन पंजाब", "सनराइज़र्स हैदराबाद"], "आईपीएल 2016 के फाइनल में सनराइज़र्स हैदराबाद ने रॉयल चैलेंजर्स बैंगलोर को हराया।"]),
  q(3, "general-studies", "indian-polity", "M", 2,
    ["Which amongst the following is the programme launched in 2015 by the Government keeping the female foeticide in mind?", ["Beti Bachao, Naam Kamao", "Beti Bachao, Desh Bachao", "Beti Bachao, Beti Padhao", "Beti Bachao, Desh Banao"], "'Beti Bachao, Beti Padhao' was launched in January 2015 to address the falling child sex ratio."],
    ["निम्नलिखित में से कौन-सा कार्यक्रम सरकार द्वारा 2015 में कन्या भ्रूण हत्या को ध्यान में रखकर शुरू किया गया?", ["बेटी बचाओ, नाम कमाओ", "बेटी बचाओ, देश बचाओ", "बेटी बचाओ, बेटी पढ़ाओ", "बेटी बचाओ, देश बनाओ"], "'बेटी बचाओ, बेटी पढ़ाओ' जनवरी 2015 में घटते बाल लिंगानुपात को सुधारने के लिए शुरू हुआ।"]),
  q(3, "general-studies", "indian-polity", "E", 0,
    ["Who addresses the joint-session of Parliament?", ["The President", "The Prime Minister", "The Chairman of Rajya Sabha", "The Lok Sabha Speaker"], "Under Article 87 the President addresses both Houses together at the first session of the year."],
    ["संसद के संयुक्त अधिवेशन को कौन संबोधित करता है?", ["राष्ट्रपति", "प्रधानमंत्री", "राज्य सभा का सभापति", "लोक सभा अध्यक्ष"], "अनुच्छेद 87 के तहत राष्ट्रपति वर्ष के पहले सत्र में दोनों सदनों को एक साथ संबोधित करता है।"]),
  q(3, "general-studies", "indian-geography", "M", 2,
    ["Which of the following periodical winds blowing from the sea to land cause the summer monsoon in India?", ["East-West", "North-East", "South-West", "South-North"], "The south-west monsoon winds blow from the Indian Ocean towards the land in summer."],
    ["समुद्र से स्थल की ओर बहने वाली निम्न में से कौन-सी periodical हवाएँ भारत में ग्रीष्मकालीन मानसून लाती हैं?", ["पूर्व-पश्चिम", "उत्तर-पूर्व", "दक्षिण-पश्चिम", "दक्षिण-उत्तर"], "दक्षिण-पश्चिम मानसून पवनें गर्मियों में हिंद महासागर से स्थल की ओर बहती हैं।"]),
  q(3, "general-studies", "indian-economy", "M", 1,
    ["The 'Maitri-Express' railway service is associated with:", ["India-Pakistan", "India-Bangladesh", "India-Nepal", "India-Bhutan"], "The Maitri Express runs between Kolkata and Dhaka."],
    ["'मैत्री एक्सप्रेस' रेलवे सेवा किससे संबंधित है?", ["भारत-पाकिस्तान", "भारत-बांग्लादेश", "भारत-नेपाल", "भारत-भूटान"], "मैत्री एक्सप्रेस कोलकाता और ढाका के बीच चलती है।"]),
  q(3, "general-studies", "general-science", "H", 1,
    ["The density of water is greater than the density of kerosene oil. If the two are mixed:", ["Water floats on kerosene", "Kerosene floats on water", "Kerosene dissolves in water", "They mix uniformly"], "Kerosene is lighter and does not mix with water, so it floats on water."],
    ["पानी का घनत्व मिट्टी के तेल के घनत्व से अधिक है। यदि दोनों को मिलाया जाए तो:", ["पानी मिट्टी के तेल पर तैरेगा", "मिट्टी का तेल पानी पर तैरेगा", "मिट्टी का तेल पानी में घुल जाएगा", "वे एकसमान रूप से मिल जाएँगे"], "मिट्टी का तेल हल्का होता है और पानी में नहीं घुलता, इसलिए पानी पर तैरता है।"]),
];
