// HP Police Constable subject tests: English 1 and 2 (25 questions each). All questions are new, not in the full mocks.
// The Hindi version explains each question in Hindi and keeps the English sentence and options.

import { q, type PoliceQuestion } from "../types";

export const english1: PoliceQuestion[] = [
  // Grammar (6)
  q(0, "english", "grammar", "M", 0,
    ["Fill in the blank: 'He is very fond ___ music.'", ["of", "for", "with", "in"], "'Fond' is always followed by 'of': fond of music."],
    ["रिक्त स्थान भरिए: 'He is very fond ___ music.'", ["of", "for", "with", "in"], "'Fond' के बाद सदैव 'of' आता है: fond of music।"]),
  q(0, "english", "grammar", "H", 1,
    ["Fill in the blank: 'Either you or he ___ responsible for this mistake.'", ["are", "is", "were", "have been"], "With 'either … or', the verb agrees with the nearer subject. 'He' is nearer, so the verb is 'is'."],
    ["रिक्त स्थान भरिए: 'Either you or he ___ responsible for this mistake.'", ["are", "is", "were", "have been"], "'Either … or' में क्रिया निकटतम कर्ता के अनुसार होती है। निकट कर्ता 'he' है, अतः 'is'।"]),
  q(0, "english", "grammar", "M", 2,
    ["Fill in the blank: 'I would rather die ___ steal.'", ["then", "but", "than", "that"], "'Would rather … than' is used for preference: I would rather die than steal."],
    ["रिक्त स्थान भरिए: 'I would rather die ___ steal.'", ["then", "but", "than", "that"], "पसंद बताने के लिए 'would rather … than' का प्रयोग होता है: I would rather die than steal।"]),
  q(0, "english", "grammar", "H", 3,
    ["Fill in the blank: 'The suspect denied ___ the car.'", ["to steal", "steal", "to have steal", "stealing"], "'Deny' is followed by a gerund (-ing form): denied stealing the car."],
    ["रिक्त स्थान भरिए: 'The suspect denied ___ the car.'", ["to steal", "steal", "to have steal", "stealing"], "'Deny' के बाद gerund (-ing रूप) आता है: denied stealing the car।"]),
  q(0, "english", "grammar", "H", 0,
    ["Fill in the blank: 'No sooner had the police reached the spot ___ the mob ran away.'", ["than", "when", "then", "that"], "'No sooner' is always paired with 'than'. ('Hardly' and 'scarcely' take 'when'.)"],
    ["रिक्त स्थान भरिए: 'No sooner had the police reached the spot ___ the mob ran away.'", ["than", "when", "then", "that"], "'No sooner' के साथ सदैव 'than' आता है। ('Hardly' और 'scarcely' के साथ 'when' आता है।)"]),
  q(0, "english", "grammar", "H", 1,
    ["Choose the correct article: '___ European tourist reported the theft at the police station.'", ["An", "A", "The", "No article"], "'European' begins with a 'yoo' (consonant) sound, so 'a' is used: 'A European tourist'."],
    ["सही article चुनिए: '___ European tourist reported the theft at the police station.'", ["An", "A", "The", "No article"], "'European' का उच्चारण 'यू' (व्यंजन ध्वनि) से शुरू होता है, इसलिए 'a' आता है: 'A European tourist'।"]),
  q(0, "english", "grammar", "M", 2,
    ["Fill in the blank: 'The court sentenced him ___ five years of imprisonment.'", ["for", "with", "to", "by"], "The correct phrase is 'sentence someone to' a punishment: sentenced him to five years."],
    ["रिक्त स्थान भरिए: 'The court sentenced him ___ five years of imprisonment.'", ["for", "with", "to", "by"], "दंड के लिए सही प्रयोग 'sentence someone to' है: sentenced him to five years।"]),
  // Synonyms and antonyms (6)
  q(0, "english", "synonyms-antonyms", "M", 2,
    ["Choose the synonym of 'DETER':", ["Encourage", "Invite", "Discourage", "Allow"], "To deter is to discourage someone from doing something, e.g. by fear of punishment."],
    ["'DETER' का समानार्थी शब्द चुनिए:", ["Encourage", "Invite", "Discourage", "Allow"], "Deter का अर्थ है किसी को कुछ करने से रोकना या हतोत्साहित करना, जैसे दंड के भय से।"]),
  q(0, "english", "synonyms-antonyms", "M", 3,
    ["Choose the synonym of 'FRAUD':", ["Honesty", "Charity", "Justice", "Deception"], "Fraud is wrongful or criminal deception for gain."],
    ["'FRAUD' का समानार्थी शब्द चुनिए:", ["Honesty", "Charity", "Justice", "Deception"], "Fraud का अर्थ है लाभ के लिए किया गया छल या धोखा (deception)।"]),
  q(0, "english", "synonyms-antonyms", "H", 0,
    ["Choose the synonym of 'LENIENT':", ["Merciful", "Strict", "Cruel", "Rigid"], "Lenient means not strict, tolerant or merciful in punishment."],
    ["'LENIENT' का समानार्थी शब्द चुनिए:", ["Merciful", "Strict", "Cruel", "Rigid"], "Lenient का अर्थ है नरम, सहनशील या दंड देने में दयालु।"]),
  q(0, "english", "synonyms-antonyms", "H", 1,
    ["Choose the antonym of 'ACQUIT':", ["Release", "Convict", "Pardon", "Free"], "To acquit is to declare someone not guilty; the opposite is to convict (declare guilty)."],
    ["'ACQUIT' का विलोम शब्द चुनिए:", ["Release", "Convict", "Pardon", "Free"], "Acquit का अर्थ है निर्दोष घोषित करना; इसका विलोम convict (दोषी ठहराना) है।"]),
  q(0, "english", "synonyms-antonyms", "M", 2,
    ["Choose the antonym of 'ARTIFICIAL':", ["Fake", "Synthetic", "Natural", "Imitation"], "Artificial means man-made; its opposite is natural."],
    ["'ARTIFICIAL' का विलोम शब्द चुनिए:", ["Fake", "Synthetic", "Natural", "Imitation"], "Artificial का अर्थ है कृत्रिम; इसका विलोम natural (प्राकृतिक) है।"]),
  q(0, "english", "synonyms-antonyms", "M", 3,
    ["Choose the antonym of 'EXPAND':", ["Enlarge", "Extend", "Spread", "Contract"], "To expand is to become larger; the opposite is to contract."],
    ["'EXPAND' का विलोम शब्द चुनिए:", ["Enlarge", "Extend", "Spread", "Contract"], "Expand का अर्थ है फैलना; इसका विलोम contract (सिकुड़ना) है।"]),
  // Idioms (3)
  q(0, "english", "idioms", "M", 0,
    ["Choose the meaning of the idiom 'to smell a rat':", ["To suspect that something is wrong", "To find a dead animal", "To have a cold", "To clean the house"], "To smell a rat is to sense that something is wrong or that someone is cheating."],
    ["मुहावरे 'to smell a rat' का अर्थ चुनिए:", ["कुछ गड़बड़ होने का संदेह होना", "मरा हुआ जानवर मिलना", "ज़ुकाम होना", "घर साफ़ करना"], "इसका अर्थ है यह भाँप लेना कि कुछ गलत हो रहा है या कोई धोखा दे रहा है।"]),
  q(0, "english", "idioms", "H", 1,
    ["In the sentence 'The escaped prisoner is still at large', what does 'at large' mean?", ["Very big", "Not yet caught; free", "In hospital", "Under arrest"], "'At large' means free and not yet captured, used for criminals and escaped prisoners."],
    ["वाक्य 'The escaped prisoner is still at large' में 'at large' का क्या अर्थ है?", ["बहुत बड़ा", "अभी तक पकड़ा नहीं गया; फ़रार", "अस्पताल में", "गिरफ़्तार"], "'At large' का अर्थ है फ़रार और अब तक न पकड़ा गया, अपराधियों और भागे कैदियों के लिए प्रयोग होता है।"]),
  q(0, "english", "idioms", "M", 2,
    ["Choose the meaning of the idiom 'to face the music':", ["To enjoy a concert", "To sing loudly", "To accept the consequences of one's actions", "To run away"], "To face the music means to accept criticism or punishment for something you have done."],
    ["मुहावरे 'to face the music' का अर्थ चुनिए:", ["संगीत कार्यक्रम का आनंद लेना", "ज़ोर से गाना", "अपने किए के परिणाम भुगतना", "भाग जाना"], "इसका अर्थ है अपने किए के लिए आलोचना या दंड स्वीकार करना।"]),
  // One-word substitution (3)
  q(0, "english", "one-word", "M", 3,
    ["One word for 'the murder of a king':", ["Homicide", "Genocide", "Patricide", "Regicide"], "Regicide is the killing of a king. Genocide is the killing of a whole group of people."],
    ["'राजा की हत्या' के लिए एक शब्द:", ["Homicide", "Genocide", "Patricide", "Regicide"], "Regicide = राजा की हत्या। Genocide = किसी पूरे समुदाय का संहार।"]),
  q(0, "english", "one-word", "M", 0,
    ["One word for 'handwriting that cannot be read':", ["Illegible", "Eligible", "Legible", "Invisible"], "Illegible means not clear enough to be read. 'Legible' is its opposite; 'eligible' means qualified."],
    ["'ऐसी लिखावट जो पढ़ी न जा सके' के लिए एक शब्द:", ["Illegible", "Eligible", "Legible", "Invisible"], "Illegible = जो पढ़ा न जा सके। 'Legible' इसका विलोम है; 'eligible' का अर्थ योग्य है।"]),
  q(0, "english", "one-word", "H", 1,
    ["One word for 'a person who cannot be corrected or reformed':", ["Incurable", "Incorrigible", "Invincible", "Incredible"], "Incorrigible describes a person whose bad habits cannot be corrected. Invincible means unbeatable."],
    ["'ऐसा व्यक्ति जिसे सुधारा न जा सके' के लिए एक शब्द:", ["Incurable", "Incorrigible", "Invincible", "Incredible"], "Incorrigible = जिसकी बुरी आदतें सुधारी न जा सकें। Invincible = अजेय।"]),
  // Error spotting (2)
  q(0, "english", "error-spotting", "H", 0,
    ["Find the part with an error: 'She is one of the best singer / in our college / but she is very shy. / No error'", ["She is one of the best singer", "in our college", "but she is very shy.", "No error"], "'One of the' is followed by a plural noun: 'one of the best singers'."],
    ["त्रुटि वाला भाग चुनिए: 'She is one of the best singer / in our college / but she is very shy. / No error'", ["She is one of the best singer", "in our college", "but she is very shy.", "No error"], "'One of the' के बाद बहुवचन संज्ञा आती है: 'one of the best singers'।"]),
  q(0, "english", "error-spotting", "H", 0,
    ["Find the part with an error: 'Unless you do not work hard / you will not / pass the exam. / No error'", ["Unless you do not work hard", "you will not", "pass the exam.", "No error"], "'Unless' already means 'if not', so 'do not' must be removed: 'Unless you work hard, you will not pass'."],
    ["त्रुटि वाला भाग चुनिए: 'Unless you do not work hard / you will not / pass the exam. / No error'", ["Unless you do not work hard", "you will not", "pass the exam.", "No error"], "'Unless' का अर्थ ही 'if not' है, अतः 'do not' हटाना होगा: 'Unless you work hard, you will not pass'।"]),
  // Voice and narration (2)
  q(0, "english", "voice-speech", "H", 2,
    ["Change into the passive voice: 'Open the door.'", ["The door is opened.", "The door was opened.", "Let the door be opened.", "The door should opened."], "The passive of an imperative sentence uses 'Let + object + be + past participle': Let the door be opened."],
    ["वाच्य बदलिए (Passive Voice): 'Open the door.'", ["The door is opened.", "The door was opened.", "Let the door be opened.", "The door should opened."], "आज्ञार्थक वाक्य के कर्मवाच्य में 'Let + object + be + past participle' आता है: Let the door be opened।"]),
  q(0, "english", "voice-speech", "M", 3,
    ["Change into indirect speech: The inspector said to me, 'Where do you live?'", ["The inspector asked me where do I live.", "The inspector said me where I lived.", "The inspector asked me where did I live.", "The inspector asked me where I lived."], "A question becomes a statement after 'asked': the order is subject + verb, and the tense moves back: 'where I lived'."],
    ["अप्रत्यक्ष कथन में बदलिए: The inspector said to me, 'Where do you live?'", ["The inspector asked me where do I live.", "The inspector said me where I lived.", "The inspector asked me where did I live.", "The inspector asked me where I lived."], "प्रश्नवाचक वाक्य 'asked' के बाद कथन बन जाता है: क्रम कर्ता + क्रिया होता है और काल पीछे जाता है: 'where I lived'।"]),
  // Spelling and word forms (2)
  q(0, "english", "spelling", "H", 0,
    ["Choose the correct spelling of the word meaning 'an incident or event that happens':", ["Occurrence", "Occurence", "Ocurrence", "Occurrance"], "The correct spelling is 'occurrence', with double 'c', double 'r' and '-ence'."],
    ["'घटित होने वाली घटना' अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Occurrence", "Occurence", "Ocurrence", "Occurrance"], "सही वर्तनी 'occurrence' है, जिसमें दो 'c', दो 'r' और अंत में '-ence' है।"]),
  q(0, "english", "grammar", "H", 1,
    ["What is the correct plural of 'criterion'?", ["Criterions", "Criteria", "Criterias", "Criterion"], "'Criterion' is a Greek-origin word; its plural is 'criteria'."],
    ["'Criterion' का सही बहुवचन क्या है?", ["Criterions", "Criteria", "Criterias", "Criterion"], "'Criterion' ग्रीक मूल का शब्द है; इसका बहुवचन 'criteria' है।"]),
];

export const english2: PoliceQuestion[] = [
  // Grammar (6)
  q(0, "english", "grammar", "H", 2,
    ["Fill in the blank: 'The jury ___ given its verdict.'", ["have", "are", "has", "were"], "When a collective noun acts as one body (shown here by 'its'), it takes a singular verb: 'The jury has given its verdict'."],
    ["रिक्त स्थान भरिए: 'The jury ___ given its verdict.'", ["have", "are", "has", "were"], "जब समूहवाचक संज्ञा एक इकाई के रूप में कार्य करे (जैसा 'its' से स्पष्ट है), तो एकवचन क्रिया आती है: 'The jury has given its verdict'।"]),
  q(0, "english", "grammar", "M", 3,
    ["Fill in the blank: 'He has been absent ___ Monday.'", ["for", "from", "by", "since"], "'Since' is used with a point of time (Monday) in the perfect tense."],
    ["रिक्त स्थान भरिए: 'He has been absent ___ Monday.'", ["for", "from", "by", "since"], "Perfect tense में समय-बिंदु (Monday) के साथ 'since' आता है।"]),
  q(0, "english", "grammar", "H", 0,
    ["Fill in the blank: 'Each boy and each girl ___ given a prize.'", ["was", "were", "are", "have been"], "When two singular subjects joined by 'and' are each preceded by 'each' or 'every', the verb is singular."],
    ["रिक्त स्थान भरिए: 'Each boy and each girl ___ given a prize.'", ["was", "were", "are", "have been"], "जब 'and' से जुड़े दो एकवचन कर्ताओं से पहले 'each' या 'every' हो, तो क्रिया एकवचन होती है।"]),
  q(0, "english", "grammar", "M", 1,
    ["Fill in the blank: 'The guard prevented him ___ entering the building.'", ["to", "from", "for", "against"], "'Prevent someone from doing something' is the correct pattern."],
    ["रिक्त स्थान भरिए: 'The guard prevented him ___ entering the building.'", ["to", "from", "for", "against"], "सही प्रयोग 'prevent someone from doing something' है।"]),
  q(0, "english", "grammar", "H", 2,
    ["Fill in the blank: 'If he had worked hard, he ___ the exam.'", ["will pass", "would pass", "would have passed", "had passed"], "A third conditional (past unreal) uses 'if + had + past participle' and 'would have + past participle'."],
    ["रिक्त स्थान भरिए: 'If he had worked hard, he ___ the exam.'", ["will pass", "would pass", "would have passed", "had passed"], "तीसरे प्रकार के conditional (भूतकाल की अवास्तविक शर्त) में 'if + had + past participle' और 'would have + past participle' आता है।"]),
  q(0, "english", "grammar", "M", 3,
    ["Fill in the blank: 'The thief ran away ___ seeing the police.'", ["at", "by", "in", "on"], "'On seeing' means 'as soon as he saw'."],
    ["रिक्त स्थान भरिए: 'The thief ran away ___ seeing the police.'", ["at", "by", "in", "on"], "'On seeing' का अर्थ है 'देखते ही'।"]),
  // Synonyms and antonyms (6)
  q(0, "english", "synonyms-antonyms", "H", 0,
    ["Choose the synonym of 'ABSCOND':", ["Flee", "Surrender", "Appear", "Confess"], "To abscond is to leave secretly to avoid arrest or the law, i.e. to flee."],
    ["'ABSCOND' का समानार्थी शब्द चुनिए:", ["Flee", "Surrender", "Appear", "Confess"], "Abscond का अर्थ है गिरफ़्तारी या क़ानून से बचने के लिए चुपके से भाग जाना, यानी flee।"]),
  q(0, "english", "synonyms-antonyms", "M", 1,
    ["Choose the synonym of 'GENUINE':", ["Fake", "Authentic", "Doubtful", "Cheap"], "Genuine means real or authentic."],
    ["'GENUINE' का समानार्थी शब्द चुनिए:", ["Fake", "Authentic", "Doubtful", "Cheap"], "Genuine का अर्थ है असली या प्रामाणिक (authentic)।"]),
  q(0, "english", "synonyms-antonyms", "M", 2,
    ["Choose the synonym of 'EVIDENT':", ["Hidden", "Doubtful", "Obvious", "Vague"], "Evident means clearly seen or understood, i.e. obvious."],
    ["'EVIDENT' का समानार्थी शब्द चुनिए:", ["Hidden", "Doubtful", "Obvious", "Vague"], "Evident का अर्थ है स्पष्ट दिखाई देने वाला, यानी obvious।"]),
  q(0, "english", "synonyms-antonyms", "M", 3,
    ["Choose the antonym of 'COURAGE':", ["Bravery", "Valour", "Boldness", "Cowardice"], "Courage is bravery; its opposite is cowardice."],
    ["'COURAGE' का विलोम शब्द चुनिए:", ["Bravery", "Valour", "Boldness", "Cowardice"], "Courage का अर्थ साहस है; इसका विलोम cowardice (कायरता) है।"]),
  q(0, "english", "synonyms-antonyms", "M", 0,
    ["Choose the antonym of 'PERMANENT':", ["Temporary", "Lasting", "Stable", "Fixed"], "Permanent means lasting for ever; its opposite is temporary."],
    ["'PERMANENT' का विलोम शब्द चुनिए:", ["Temporary", "Lasting", "Stable", "Fixed"], "Permanent का अर्थ स्थायी है; इसका विलोम temporary (अस्थायी) है।"]),
  q(0, "english", "synonyms-antonyms", "H", 1,
    ["Choose the antonym of 'VICTORY':", ["Triumph", "Defeat", "Success", "Conquest"], "Victory is winning; its opposite is defeat."],
    ["'VICTORY' का विलोम शब्द चुनिए:", ["Triumph", "Defeat", "Success", "Conquest"], "Victory का अर्थ विजय है; इसका विलोम defeat (पराजय) है।"]),
  // Idioms (3)
  q(0, "english", "idioms", "M", 2,
    ["Choose the meaning of the idiom 'to be in hot water':", ["To take a bath", "To be very rich", "To be in trouble", "To be ill"], "To be in hot water means to be in trouble or difficulty."],
    ["मुहावरे 'to be in hot water' का अर्थ चुनिए:", ["स्नान करना", "बहुत धनी होना", "मुसीबत में होना", "बीमार होना"], "इसका अर्थ है मुसीबत या कठिनाई में होना।"]),
  q(0, "english", "idioms", "H", 3,
    ["Choose the meaning of the idiom 'to cry wolf':", ["To weep loudly", "To hunt animals", "To call for help in the forest", "To raise a false alarm"], "From the fable of the boy who cried wolf: to raise false alarms, so that people stop believing you."],
    ["मुहावरे 'to cry wolf' का अर्थ चुनिए:", ["ज़ोर से रोना", "जानवरों का शिकार करना", "जंगल में मदद माँगना", "झूठी चेतावनी देना"], "भेड़िया आया वाली कहानी से: बार-बार झूठी चेतावनी देना, जिससे लोग विश्वास करना छोड़ दें।"]),
  q(0, "english", "idioms", "M", 0,
    ["Choose the meaning of the idiom 'a red-letter day':", ["A memorable and important day", "A day of danger", "A holiday for postmen", "An unlucky day"], "A red-letter day is a day that is memorable because something good or important happened."],
    ["मुहावरे 'a red-letter day' का अर्थ चुनिए:", ["यादगार और महत्वपूर्ण दिन", "ख़तरे का दिन", "डाकियों की छुट्टी", "अशुभ दिन"], "Red-letter day वह दिन है जो किसी अच्छी या महत्वपूर्ण घटना के कारण यादगार हो।"]),
  // One-word substitution (3)
  q(0, "english", "one-word", "H", 1,
    ["One word for 'a person who knowingly gives false evidence under oath':", ["Witness", "Perjurer", "Plaintiff", "Accomplice"], "Perjury is lying under oath; the person who does it is a perjurer. An accomplice helps in a crime."],
    ["'शपथ लेकर जान-बूझकर झूठी गवाही देने वाला व्यक्ति' के लिए एक शब्द:", ["Witness", "Perjurer", "Plaintiff", "Accomplice"], "शपथ पर झूठ बोलना perjury है और ऐसा करने वाला perjurer। Accomplice अपराध में सहयोगी होता है।"]),
  q(0, "english", "one-word", "H", 2,
    ["One word for 'a place where weapons and ammunition are stored':", ["Mint", "Treasury", "Arsenal", "Granary"], "An arsenal is a store of weapons and ammunition. A mint makes coins, a granary stores grain and a treasury keeps money."],
    ["'वह स्थान जहाँ हथियार और गोला-बारूद रखा जाता है' के लिए एक शब्द:", ["Mint", "Treasury", "Arsenal", "Granary"], "Arsenal (शस्त्रागार) में हथियार और गोला-बारूद रखा जाता है। Mint में सिक्के बनते हैं, granary में अनाज और treasury में धन रखा जाता है।"]),
  q(0, "english", "one-word", "M", 3,
    ["One word for 'an abnormal fear of water':", ["Claustrophobia", "Acrophobia", "Xenophobia", "Hydrophobia"], "Hydrophobia is fear of water. Claustrophobia is fear of closed spaces, acrophobia of heights and xenophobia of foreigners."],
    ["'पानी से असामान्य भय' के लिए एक शब्द:", ["Claustrophobia", "Acrophobia", "Xenophobia", "Hydrophobia"], "Hydrophobia = पानी से भय। Claustrophobia = बंद स्थान से, acrophobia = ऊँचाई से और xenophobia = विदेशियों से भय।"]),
  // Error spotting (3)
  q(0, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'Many a man / have died / in the war. / No error'", ["Many a man", "have died", "in the war.", "No error"], "'Many a' is followed by a singular noun and a singular verb: 'Many a man has died'."],
    ["त्रुटि वाला भाग चुनिए: 'Many a man / have died / in the war. / No error'", ["Many a man", "have died", "in the war.", "No error"], "'Many a' के बाद एकवचन संज्ञा और एकवचन क्रिया आती है: 'Many a man has died'।"]),
  q(0, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'He is too weak / that he cannot / walk. / No error'", ["He is too weak", "that he cannot", "walk.", "No error"], "'Too … to' is the correct pattern: 'He is too weak to walk' (or 'so weak that he cannot walk')."],
    ["त्रुटि वाला भाग चुनिए: 'He is too weak / that he cannot / walk. / No error'", ["He is too weak", "that he cannot", "walk.", "No error"], "सही रचना 'too … to' है: 'He is too weak to walk' (या 'so weak that he cannot walk')।"]),
  q(0, "english", "error-spotting", "M", 0,
    ["Find the part with an error: 'The cattle is grazing / in the / field. / No error'", ["The cattle is grazing", "in the", "field.", "No error"], "'Cattle' is always plural and takes a plural verb: 'The cattle are grazing'."],
    ["त्रुटि वाला भाग चुनिए: 'The cattle is grazing / in the / field. / No error'", ["The cattle is grazing", "in the", "field.", "No error"], "'Cattle' सदैव बहुवचन है और बहुवचन क्रिया लेता है: 'The cattle are grazing'।"]),
  // Voice and narration (2)
  q(0, "english", "voice-speech", "M", 2,
    ["Change into the passive voice: 'They are building a new police station.'", ["A new police station was being built by them.", "A new police station has been built by them.", "A new police station is being built by them.", "A new police station is built by them."], "Present continuous passive = is/are + being + past participle: 'A new police station is being built by them.'"],
    ["वाच्य बदलिए (Passive Voice): 'They are building a new police station.'", ["A new police station was being built by them.", "A new police station has been built by them.", "A new police station is being built by them.", "A new police station is built by them."], "Present continuous का कर्मवाच्य = is/are + being + past participle: 'A new police station is being built by them.'"]),
  q(0, "english", "voice-speech", "H", 3,
    ["Change into indirect speech: He said, 'Let us wait for the inspector.'", ["He said that let us wait for the inspector.", "He told that we waited for the inspector.", "He ordered to wait for the inspector.", "He proposed that they should wait for the inspector."], "'Let us' expressing a proposal becomes 'proposed/suggested that … should' in indirect speech."],
    ["अप्रत्यक्ष कथन में बदलिए: He said, 'Let us wait for the inspector.'", ["He said that let us wait for the inspector.", "He told that we waited for the inspector.", "He ordered to wait for the inspector.", "He proposed that they should wait for the inspector."], "प्रस्ताव व्यक्त करने वाला 'Let us' अप्रत्यक्ष कथन में 'proposed/suggested that … should' बन जाता है।"]),
  // Spelling and articles (2)
  q(0, "english", "spelling", "H", 0,
    ["Choose the correct spelling of the word meaning 'repeated troubling or intimidation of a person':", ["Harassment", "Harrassment", "Harasment", "Harrasment"], "The correct spelling is 'harassment', with one 'r' and double 's' twice."],
    ["'किसी व्यक्ति को बार-बार परेशान करना या धमकाना' अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Harassment", "Harrassment", "Harasment", "Harrasment"], "सही वर्तनी 'harassment' है, जिसमें एक 'r' और दो बार दोहरा 's' है।"]),
  q(0, "english", "grammar", "H", 1,
    ["Choose the correct article: 'He is ___ MLA from Shimla.'", ["a", "an", "the", "no article"], "'MLA' is read 'em-el-ay', beginning with a vowel sound, so 'an' is used: 'an MLA'."],
    ["सही article चुनिए: 'He is ___ MLA from Shimla.'", ["a", "an", "the", "no article"], "'MLA' का उच्चारण 'एम-एल-ए' है, जो स्वर ध्वनि से शुरू होता है, अतः 'an' आता है: 'an MLA'।"]),
];
