// HP Police Constable subject tests: Hindi 1 and 2 (25 questions each). All questions are new, not in the full mocks.
// The English version of each question describes the task in English and keeps the Hindi words as options.

import { q, type PoliceQuestion } from "../types";

export const hindi1: PoliceQuestion[] = [
  // Sandhi (4)
  q(0, "hindi", "sandhi-samas", "M", 0,
    ["Choose the correct split of the sandhi word 'हिमालय':", ["हिम + आलय", "हिमा + लय", "हिम + अलय", "हि + मालय"], "'हिमालय' = हिम + आलय (अ + आ = आ), a deergh sandhi."],
    ["'हिमालय' का सही संधि-विच्छेद चुनिए:", ["हिम + आलय", "हिमा + लय", "हिम + अलय", "हि + मालय"], "'हिमालय' = हिम + आलय (अ + आ = आ), यह दीर्घ संधि है।"]),
  q(0, "hindi", "sandhi-samas", "M", 1,
    ["Choose the correct split of the sandhi word 'गणेश':", ["गणे + श", "गण + ईश", "गण + इश", "गणा + ईश"], "'गणेश' = गण + ईश (अ + ई = ए), a guna sandhi."],
    ["'गणेश' का सही संधि-विच्छेद चुनिए:", ["गणे + श", "गण + ईश", "गण + इश", "गणा + ईश"], "'गणेश' = गण + ईश (अ + ई = ए), यह गुण संधि है।"]),
  q(0, "hindi", "sandhi-samas", "H", 2,
    ["Choose the correct split of the sandhi word 'स्वागत':", ["स्व + आगत", "स्वा + गत", "सु + आगत", "सु + गत"], "'स्वागत' = सु + आगत. 'उ' before a different vowel becomes 'व्', so this is a yan sandhi (not स्व + आगत)."],
    ["'स्वागत' का सही संधि-विच्छेद चुनिए:", ["स्व + आगत", "स्वा + गत", "सु + आगत", "सु + गत"], "'स्वागत' = सु + आगत। भिन्न स्वर से पहले 'उ' का 'व्' हो जाता है, अतः यह यण संधि है (स्व + आगत नहीं)।"]),
  q(0, "hindi", "sandhi-samas", "H", 3,
    ["Choose the correct split of the sandhi word 'निश्चय':", ["नि + चय", "निश् + चय", "निस + चय", "निः + चय"], "'निश्चय' = निः + चय. Before 'च' the visarga becomes 'श्', a visarga sandhi."],
    ["'निश्चय' का सही संधि-विच्छेद चुनिए:", ["नि + चय", "निश् + चय", "निस + चय", "निः + चय"], "'निश्चय' = निः + चय। 'च' से पहले विसर्ग 'श्' में बदल जाता है, यह विसर्ग संधि है।"]),
  // Samas (4)
  q(0, "hindi", "sandhi-samas", "M", 0,
    ["Identify the type of compound (samas) in 'गंगाजल' (water of the Ganga):", ["Tatpurush", "Dvandva", "Dvigu", "Avyayibhava"], "'गंगाजल' = गंगा का जल. The case marker 'का' is dropped and the second word is main, so it is a (sambandh) Tatpurush samas."],
    ["'गंगाजल' शब्द में कौन-सा समास है?", ["तत्पुरुष", "द्वंद्व", "द्विगु", "अव्ययीभाव"], "'गंगाजल' = गंगा का जल। 'का' कारक-चिह्न लुप्त है और उत्तर पद प्रधान है, अतः (संबंध) तत्पुरुष समास है।"]),
  q(0, "hindi", "sandhi-samas", "M", 1,
    ["Identify the type of compound (samas) in 'त्रिलोक' (the three worlds):", ["Karmadharaya", "Dvigu", "Bahuvrihi", "Dvandva"], "'त्रिलोक' = तीन लोकों का समूह. The first word is a number and the compound shows a group, so it is Dvigu."],
    ["'त्रिलोक' शब्द में कौन-सा समास है?", ["कर्मधारय", "द्विगु", "बहुव्रीहि", "द्वंद्व"], "'त्रिलोक' = तीन लोकों का समूह। पहला पद संख्यावाचक है और समूह का बोध होता है, अतः द्विगु समास है।"]),
  q(0, "hindi", "sandhi-samas", "H", 2,
    ["Identify the type of compound (samas) in 'दशानन' when it means Ravana:", ["Dvigu", "Tatpurush", "Bahuvrihi", "Karmadharaya"], "'दशानन' = दस हैं आनन (मुख) जिसके, अर्थात् रावण. Neither word is main; the compound points to a third person, so it is Bahuvrihi."],
    ["रावण के अर्थ में 'दशानन' शब्द में कौन-सा समास है?", ["द्विगु", "तत्पुरुष", "बहुव्रीहि", "कर्मधारय"], "'दशानन' = दस हैं आनन (मुख) जिसके, अर्थात् रावण। कोई पद प्रधान नहीं, अन्य व्यक्ति का बोध होता है, अतः बहुव्रीहि समास है।"]),
  q(0, "hindi", "sandhi-samas", "M", 3,
    ["Identify the type of compound (samas) in 'माता-पिता':", ["Tatpurush", "Bahuvrihi", "Dvigu", "Dvandva"], "'माता-पिता' = माता और पिता. Both words are equally important and joined by 'और', so it is Dvandva."],
    ["'माता-पिता' शब्द में कौन-सा समास है?", ["तत्पुरुष", "बहुव्रीहि", "द्विगु", "द्वंद्व"], "'माता-पिता' = माता और पिता। दोनों पद प्रधान हैं और 'और' से जुड़े हैं, अतः द्वंद्व समास है।"]),
  // Muhavare (4)
  q(0, "hindi", "muhavare", "M", 0,
    ["What is the meaning of the Hindi idiom 'आस्तीन का साँप'?", ["A friend who betrays", "A poisonous snake", "A brave person", "A lazy person"], "'आस्तीन का साँप' means a false friend who pretends to be close but causes harm."],
    ["'आस्तीन का साँप' मुहावरे का अर्थ है:", ["कपटी मित्र", "ज़हरीला साँप", "वीर व्यक्ति", "आलसी व्यक्ति"], "'आस्तीन का साँप' का अर्थ है ऐसा कपटी मित्र जो पास रहकर हानि पहुँचाए।"]),
  q(0, "hindi", "muhavare", "H", 1,
    ["What is the meaning of the Hindi idiom 'कलई खुलना'?", ["To paint a wall", "The truth or secret being exposed", "To open a shop", "To become rich"], "'कलई खुलना' means the reality behind a false show gets exposed."],
    ["'कलई खुलना' मुहावरे का अर्थ है:", ["दीवार रंगना", "असलियत या भेद प्रकट होना", "दुकान खोलना", "धनी होना"], "'कलई खुलना' का अर्थ है दिखावे के पीछे की असलियत प्रकट हो जाना।"]),
  q(0, "hindi", "muhavare", "M", 2,
    ["What is the meaning of the Hindi idiom 'घी के दिए जलाना'?", ["To waste money", "To worship", "To celebrate with great joy", "To cook food"], "'घी के दिए जलाना' means to rejoice or celebrate happily."],
    ["'घी के दिए जलाना' मुहावरे का अर्थ है:", ["धन बर्बाद करना", "पूजा करना", "बहुत ख़ुशियाँ मनाना", "भोजन पकाना"], "'घी के दिए जलाना' का अर्थ है बहुत प्रसन्नता से उत्सव मनाना।"]),
  q(0, "hindi", "muhavare", "M", 3,
    ["What is the meaning of the Hindi idiom 'टेढ़ी खीर'?", ["A tasty dish", "A crooked person", "Something easy", "A very difficult task"], "'टेढ़ी खीर' means a task that is very difficult to accomplish."],
    ["'टेढ़ी खीर' मुहावरे का अर्थ है:", ["स्वादिष्ट व्यंजन", "कुटिल व्यक्ति", "आसान काम", "बहुत कठिन कार्य"], "'टेढ़ी खीर' का अर्थ है ऐसा कार्य जिसे करना बहुत कठिन हो।"]),
  // Paryayvachi and vilom (4)
  q(0, "hindi", "paryay-vilom", "H", 0,
    ["Which of these is NOT a synonym of 'पानी' (water)?", ["पावक", "नीर", "वारि", "तोय"], "नीर, वारि and तोय all mean water. 'पावक' means fire."],
    ["निम्नलिखित में से कौन-सा 'पानी' का पर्यायवाची नहीं है?", ["पावक", "नीर", "वारि", "तोय"], "नीर, वारि और तोय पानी के पर्यायवाची हैं। 'पावक' का अर्थ अग्नि है।"]),
  q(0, "hindi", "paryay-vilom", "H", 1,
    ["Which of these is NOT a synonym of 'बादल' (cloud)?", ["मेघ", "जलज", "जलद", "पयोद"], "मेघ, जलद and पयोद mean cloud. 'जलज' (born in water) means lotus."],
    ["निम्नलिखित में से कौन-सा 'बादल' का पर्यायवाची नहीं है?", ["मेघ", "जलज", "जलद", "पयोद"], "मेघ, जलद और पयोद बादल के पर्यायवाची हैं। 'जलज' (जल में जन्मा) का अर्थ कमल है।"]),
  q(0, "hindi", "paryay-vilom", "M", 2,
    ["Choose the antonym of the Hindi word 'आस्तिक':", ["धार्मिक", "आलसी", "नास्तिक", "अधर्मी"], "'आस्तिक' is one who believes in God; the opposite is 'नास्तिक'."],
    ["'आस्तिक' शब्द का विलोम चुनिए:", ["धार्मिक", "आलसी", "नास्तिक", "अधर्मी"], "'आस्तिक' ईश्वर में विश्वास रखने वाला है; इसका विलोम 'नास्तिक' है।"]),
  q(0, "hindi", "paryay-vilom", "M", 3,
    ["Choose the antonym of the Hindi word 'उन्नति':", ["प्रगति", "विकास", "उत्थान", "अवनति"], "'उन्नति' means progress; its opposite is 'अवनति' (decline). The others are near-synonyms."],
    ["'उन्नति' शब्द का विलोम चुनिए:", ["प्रगति", "विकास", "उत्थान", "अवनति"], "'उन्नति' का विलोम 'अवनति' है। अन्य विकल्प इसके समानार्थी जैसे हैं।"]),
  // Shuddh vartani (3)
  q(0, "hindi", "shuddh-vartani", "H", 0,
    ["Choose the correctly spelt Hindi word for 'permanent':", ["स्थायी", "स्थाई", "स्थाइ", "स्तायी"], "The correct form is 'स्थायी'. 'स्थाई' is a very common error."],
    ["'Permanent' के लिए शुद्ध वर्तनी वाला शब्द चुनिए:", ["स्थायी", "स्थाई", "स्थाइ", "स्तायी"], "शुद्ध रूप 'स्थायी' है। 'स्थाई' एक बहुत सामान्य अशुद्धि है।"]),
  q(0, "hindi", "shuddh-vartani", "H", 1,
    ["Choose the correctly spelt Hindi word for 'sight, vision':", ["द्रष्टि", "दृष्टि", "दृष्टी", "द्रिष्टि"], "The correct spelling is 'दृष्टि', with 'ऋ' matra (दृ) and a short 'ि' at the end."],
    ["'Sight, vision' के लिए शुद्ध वर्तनी वाला शब्द चुनिए:", ["द्रष्टि", "दृष्टि", "दृष्टी", "द्रिष्टि"], "शुद्ध वर्तनी 'दृष्टि' है, जिसमें 'ऋ' की मात्रा (दृ) और अंत में छोटी 'ि' है।"]),
  q(0, "hindi", "shuddh-vartani", "H", 2,
    ["Choose the correctly spelt Hindi word for 'funeral rites':", ["अंत्येष्ठि", "अंतेष्टि", "अंत्येष्टि", "अंत्येस्टि"], "The correct spelling is 'अंत्येष्टि' (अंत्य + इष्टि)."],
    ["'अंतिम संस्कार' के अर्थ वाले शब्द की शुद्ध वर्तनी चुनिए:", ["अंत्येष्ठि", "अंतेष्टि", "अंत्येष्टि", "अंत्येस्टि"], "शुद्ध वर्तनी 'अंत्येष्टि' (अंत्य + इष्टि) है।"]),
  // Ek shabd (3)
  q(0, "hindi", "ek-shabd", "H", 3,
    ["Choose the one word for 'one who looks for faults in others' (जो दूसरों के दोष ढूँढता हो):", ["आलोचक", "निंदक", "समीक्षक", "छिद्रान्वेषी"], "'छिद्रान्वेषी' is one who searches for faults (holes) in others. An आलोचक or समीक्षक is a critic, and a निंदक speaks ill of others."],
    ["'जो दूसरों के दोष ढूँढता हो' के लिए एक शब्द चुनिए:", ["आलोचक", "निंदक", "समीक्षक", "छिद्रान्वेषी"], "'छिद्रान्वेषी' वह है जो दूसरों के दोष (छिद्र) ढूँढता है। आलोचक या समीक्षक समालोचना करता है और निंदक बुराई करता है।"]),
  q(0, "hindi", "ek-shabd", "M", 0,
    ["Choose the one word for 'that which has no shape or form' (जिसका कोई आकार न हो):", ["निराकार", "साकार", "विकार", "आकारहीन"], "'निराकार' means formless. 'साकार' is its opposite."],
    ["'जिसका कोई आकार न हो' के लिए एक शब्द चुनिए:", ["निराकार", "साकार", "विकार", "आकारहीन"], "'निराकार' = जिसका कोई आकार न हो। 'साकार' इसका विलोम है।"]),
  q(0, "hindi", "ek-shabd", "H", 1,
    ["Choose the one word for 'one who looks on everyone equally' (जो सबको समान दृष्टि से देखे):", ["सर्वज्ञ", "समदर्शी", "दूरदर्शी", "पारदर्शी"], "'समदर्शी' means one who sees all with an equal eye. 'दूरदर्शी' is far-sighted and 'सर्वज्ञ' all-knowing."],
    ["'जो सबको समान दृष्टि से देखे' के लिए एक शब्द चुनिए:", ["सर्वज्ञ", "समदर्शी", "दूरदर्शी", "पारदर्शी"], "'समदर्शी' = जो सबको समान दृष्टि से देखे। 'दूरदर्शी' = दूर तक सोचने वाला, 'सर्वज्ञ' = सब कुछ जानने वाला।"]),
  // Alankar, ras, grammar (3)
  q(0, "hindi", "alankar-ras", "M", 2,
    ["Identify the figure of speech in 'चारु चंद्र की चंचल किरणें':", ["Yamak", "Shlesh", "Anupras", "Upma"], "The sound 'च' is repeated again and again (चारु, चंद्र, चंचल), so it is Anupras alankar."],
    ["'चारु चंद्र की चंचल किरणें' में कौन-सा अलंकार है?", ["यमक", "श्लेष", "अनुप्रास", "उपमा"], "'च' वर्ण की बार-बार आवृत्ति (चारु, चंद्र, चंचल) है, अतः अनुप्रास अलंकार है।"]),
  q(0, "hindi", "alankar-ras", "M", 3,
    ["What is the sthayi bhav (permanent emotion) of Hasya ras?", ["रति", "उत्साह", "शोक", "हास"], "The sthayi bhav of Hasya (comic) ras is 'हास'. रति is of Shringar, उत्साह of Veer and शोक of Karun."],
    ["हास्य रस का स्थायी भाव क्या है?", ["रति", "उत्साह", "शोक", "हास"], "हास्य रस का स्थायी भाव 'हास' है। रति शृंगार का, उत्साह वीर का और शोक करुण का स्थायी भाव है।"]),
  q(0, "hindi", "vyakaran", "H", 0,
    ["The pronoun 'मैं' belongs to which category?", ["Purushvachak (first person)", "Nishchayvachak", "Sambandhvachak", "Prashnavachak"], "'मैं' refers to the speaker, so it is a purushvachak (personal) pronoun of the uttam (first) person."],
    ["सर्वनाम 'मैं' किस भेद का है?", ["पुरुषवाचक (उत्तम पुरुष)", "निश्चयवाचक", "संबंधवाचक", "प्रश्नवाचक"], "'मैं' बोलने वाले के लिए आता है, अतः यह उत्तम पुरुष का पुरुषवाचक सर्वनाम है।"]),
];

export const hindi2: PoliceQuestion[] = [
  // Sandhi (4)
  q(0, "hindi", "sandhi-samas", "M", 0,
    ["Choose the correct split of the sandhi word 'विद्यालय':", ["विद्या + आलय", "विद्य + आलय", "विद्या + अलय", "विद + यालय"], "'विद्यालय' = विद्या + आलय (आ + आ = आ), a deergh sandhi."],
    ["'विद्यालय' का सही संधि-विच्छेद चुनिए:", ["विद्या + आलय", "विद्य + आलय", "विद्या + अलय", "विद + यालय"], "'विद्यालय' = विद्या + आलय (आ + आ = आ), यह दीर्घ संधि है।"]),
  q(0, "hindi", "sandhi-samas", "H", 1,
    ["Choose the correct split of the sandhi word 'उद्धार':", ["उद् + धार", "उत् + हार", "उद + हार", "उत + धार"], "'उद्धार' = उत् + हार. When 'त्' is followed by 'ह', the 'त्' becomes 'द्' and 'ह' becomes 'ध', a vyanjan sandhi."],
    ["'उद्धार' का सही संधि-विच्छेद चुनिए:", ["उद् + धार", "उत् + हार", "उद + हार", "उत + धार"], "'उद्धार' = उत् + हार। 'त्' के बाद 'ह' आने पर 'त्' का 'द्' और 'ह' का 'ध' हो जाता है, यह व्यंजन संधि है।"]),
  q(0, "hindi", "sandhi-samas", "M", 2,
    ["Choose the correct split of the sandhi word 'महोत्सव':", ["महो + त्सव", "मह + उत्सव", "महा + उत्सव", "महा + ओत्सव"], "'महोत्सव' = महा + उत्सव (आ + उ = ओ), a guna sandhi."],
    ["'महोत्सव' का सही संधि-विच्छेद चुनिए:", ["महो + त्सव", "मह + उत्सव", "महा + उत्सव", "महा + ओत्सव"], "'महोत्सव' = महा + उत्सव (आ + उ = ओ), यह गुण संधि है।"]),
  q(0, "hindi", "sandhi-samas", "H", 3,
    ["Choose the correct split of the sandhi word 'दुर्गम':", ["दुर + गम", "दु + र्गम", "दुर्ग + अम", "दुः + गम"], "'दुर्गम' = दुः + गम. Before 'ग' the visarga becomes 'र्', a visarga sandhi."],
    ["'दुर्गम' का सही संधि-विच्छेद चुनिए:", ["दुर + गम", "दु + र्गम", "दुर्ग + अम", "दुः + गम"], "'दुर्गम' = दुः + गम। 'ग' से पहले विसर्ग 'र्' में बदल जाता है, यह विसर्ग संधि है।"]),
  // Samas (4)
  q(0, "hindi", "sandhi-samas", "H", 0,
    ["Identify the type of compound (samas) in 'चक्रपाणि' when it means Lord Vishnu:", ["Bahuvrihi", "Tatpurush", "Karmadharaya", "Dvigu"], "'चक्रपाणि' = चक्र है पाणि (हाथ) में जिसके, अर्थात् विष्णु. It points to a third person, so it is Bahuvrihi."],
    ["भगवान विष्णु के अर्थ में 'चक्रपाणि' शब्द में कौन-सा समास है?", ["बहुव्रीहि", "तत्पुरुष", "कर्मधारय", "द्विगु"], "'चक्रपाणि' = चक्र है पाणि (हाथ) में जिसके, अर्थात् विष्णु। अन्य व्यक्ति का बोध होता है, अतः बहुव्रीहि समास है।"]),
  q(0, "hindi", "sandhi-samas", "M", 1,
    ["Identify the type of compound (samas) in 'रसोईघर' (kitchen):", ["Dvandva", "Tatpurush", "Bahuvrihi", "Avyayibhava"], "'रसोईघर' = रसोई के लिए घर. The case marker 'के लिए' is dropped and the second word is main, so it is (sampradan) Tatpurush."],
    ["'रसोईघर' शब्द में कौन-सा समास है?", ["द्वंद्व", "तत्पुरुष", "बहुव्रीहि", "अव्ययीभाव"], "'रसोईघर' = रसोई के लिए घर। 'के लिए' लुप्त है और उत्तर पद प्रधान है, अतः (संप्रदान) तत्पुरुष समास है।"]),
  q(0, "hindi", "sandhi-samas", "H", 2,
    ["Identify the type of compound (samas) in 'घनश्याम' (dark like a cloud):", ["Dvigu", "Dvandva", "Karmadharaya", "Avyayibhava"], "'घनश्याम' = घन के समान श्याम. One word is compared with the other (upman–upmey), so it is a Karmadharaya samas."],
    ["'घनश्याम' (घन के समान श्याम) शब्द में कौन-सा समास है?", ["द्विगु", "द्वंद्व", "कर्मधारय", "अव्ययीभाव"], "'घनश्याम' = घन के समान श्याम। एक पद की तुलना दूसरे से (उपमान–उपमेय) है, अतः कर्मधारय समास है।"]),
  q(0, "hindi", "sandhi-samas", "H", 3,
    ["Identify the type of compound (samas) in 'भरपेट' (to one's fill):", ["Tatpurush", "Karmadharaya", "Dvigu", "Avyayibhava"], "'भरपेट' = पेट भरकर. The first part 'भर' is indeclinable and the whole word acts as an adverb, so it is Avyayibhava."],
    ["'भरपेट' शब्द में कौन-सा समास है?", ["तत्पुरुष", "कर्मधारय", "द्विगु", "अव्ययीभाव"], "'भरपेट' = पेट भरकर। पहला पद 'भर' अव्यय है और पूरा शब्द क्रियाविशेषण की तरह प्रयुक्त होता है, अतः अव्ययीभाव समास है।"]),
  // Muhavare and lokokti (4)
  q(0, "hindi", "muhavare", "M", 0,
    ["What is the meaning of the Hindi idiom 'अंधे की लाठी'?", ["The only support", "A useless thing", "A weapon", "A walking stick"], "'अंधे की लाठी' means someone's only support, especially the only child of old parents."],
    ["'अंधे की लाठी' मुहावरे का अर्थ है:", ["एकमात्र सहारा", "बेकार वस्तु", "हथियार", "छड़ी"], "'अंधे की लाठी' का अर्थ है किसी का एकमात्र सहारा।"]),
  q(0, "hindi", "muhavare", "M", 1,
    ["What is the meaning of the Hindi idiom 'नाक में दम करना'?", ["To catch a cold", "To harass greatly", "To feel proud", "To smell something"], "'नाक में दम करना' means to trouble or harass someone a lot."],
    ["'नाक में दम करना' मुहावरे का अर्थ है:", ["ज़ुकाम होना", "बहुत परेशान करना", "गर्व करना", "कुछ सूँघना"], "'नाक में दम करना' का अर्थ है किसी को बहुत परेशान करना।"]),
  q(0, "hindi", "muhavare", "M", 2,
    ["What does the Hindi proverb 'जिसकी लाठी उसकी भैंस' mean?", ["Buffaloes need sticks", "Hard work pays", "Might is right", "Share with others"], "The proverb means that the powerful always get their way: might is right."],
    ["लोकोक्ति 'जिसकी लाठी उसकी भैंस' का अर्थ है:", ["भैंस को लाठी चाहिए", "मेहनत का फल मिलता है", "शक्तिशाली की ही जीत होती है", "दूसरों से बाँटो"], "इस लोकोक्ति का अर्थ है कि बलवान की ही बात चलती है।"]),
  q(0, "hindi", "muhavare", "M", 3,
    ["What is the meaning of the Hindi idiom 'दाल में काला होना'?", ["Food getting burnt", "Something being very cheap", "Being very poor", "Something suspicious going on"], "'दाल में काला होना' means there is something suspicious or wrong."],
    ["'दाल में काला होना' मुहावरे का अर्थ है:", ["भोजन जल जाना", "किसी वस्तु का बहुत सस्ता होना", "बहुत गरीब होना", "कुछ संदेहजनक/गड़बड़ होना"], "'दाल में काला होना' का अर्थ है कुछ संदेहजनक या गड़बड़ होना।"]),
  // Paryayvachi and vilom (4)
  q(0, "hindi", "paryay-vilom", "M", 0,
    ["Which of these is NOT a synonym of 'घर' (house)?", ["नीरज", "गृह", "सदन", "निकेतन"], "गृह, सदन and निकेतन mean house. 'नीरज' (born in water) means lotus."],
    ["निम्नलिखित में से कौन-सा 'घर' का पर्यायवाची नहीं है?", ["नीरज", "गृह", "सदन", "निकेतन"], "गृह, सदन और निकेतन घर के पर्यायवाची हैं। 'नीरज' (जल में जन्मा) का अर्थ कमल है।"]),
  q(0, "hindi", "paryay-vilom", "M", 1,
    ["Which of these is NOT a synonym of 'आँख' (eye)?", ["नयन", "श्रवण", "लोचन", "चक्षु"], "नयन, लोचन and चक्षु mean eye. 'श्रवण' means hearing or ear."],
    ["निम्नलिखित में से कौन-सा 'आँख' का पर्यायवाची नहीं है?", ["नयन", "श्रवण", "लोचन", "चक्षु"], "नयन, लोचन और चक्षु आँख के पर्यायवाची हैं। 'श्रवण' का अर्थ सुनना या कान है।"]),
  q(0, "hindi", "paryay-vilom", "M", 2,
    ["Choose the antonym of the Hindi word 'सजीव':", ["जीवित", "प्राणवान", "निर्जीव", "सक्रिय"], "'सजीव' means living; its opposite is 'निर्जीव' (lifeless)."],
    ["'सजीव' शब्द का विलोम चुनिए:", ["जीवित", "प्राणवान", "निर्जीव", "सक्रिय"], "'सजीव' का विलोम 'निर्जीव' है।"]),
  q(0, "hindi", "paryay-vilom", "H", 3,
    ["Choose the antonym of the Hindi word 'कृतज्ञ' (grateful):", ["अज्ञ", "कृतार्थ", "अकृत", "कृतघ्न"], "'कृतज्ञ' is one who acknowledges a favour; its opposite is 'कृतघ्न' (ungrateful)."],
    ["'कृतज्ञ' शब्द का विलोम चुनिए:", ["अज्ञ", "कृतार्थ", "अकृत", "कृतघ्न"], "'कृतज्ञ' उपकार मानने वाला है; इसका विलोम 'कृतघ्न' (उपकार न मानने वाला) है।"]),
  // Shuddh vartani (3)
  q(0, "hindi", "shuddh-vartani", "H", 0,
    ["Choose the correctly spelt Hindi word for 'practical':", ["व्यावहारिक", "व्यवहारिक", "व्यावहारीक", "व्यवहारीक"], "The adjective from 'व्यवहार' takes vriddhi of the first vowel: 'व्यावहारिक'."],
    ["'Practical' के लिए शुद्ध वर्तनी वाला शब्द चुनिए:", ["व्यावहारिक", "व्यवहारिक", "व्यावहारीक", "व्यवहारीक"], "'व्यवहार' से विशेषण बनाने पर पहले स्वर की वृद्धि होती है: 'व्यावहारिक'।"]),
  q(0, "hindi", "shuddh-vartani", "H", 1,
    ["Choose the correctly spelt Hindi word for 'subordinate, dependent':", ["आधीन", "अधीन", "अधिन", "आधिन"], "The correct spelling is 'अधीन'. 'आधीन' is a common mistake."],
    ["'Subordinate, dependent' के लिए शुद्ध वर्तनी वाला शब्द चुनिए:", ["आधीन", "अधीन", "अधिन", "आधिन"], "शुद्ध वर्तनी 'अधीन' है। 'आधीन' एक सामान्य अशुद्धि है।"]),
  q(0, "hindi", "shuddh-vartani", "M", 2,
    ["Choose the correctly spelt Hindi word for 'historical':", ["एतिहासिक", "इतिहासिक", "ऐतिहासिक", "ऐतहासिक"], "From 'इतिहास', the adjective takes vriddhi (इ → ऐ): 'ऐतिहासिक'."],
    ["'Historical' के लिए शुद्ध वर्तनी वाला शब्द चुनिए:", ["एतिहासिक", "इतिहासिक", "ऐतिहासिक", "ऐतहासिक"], "'इतिहास' से विशेषण बनाने पर वृद्धि (इ → ऐ) होती है: 'ऐतिहासिक'।"]),
  // Ek shabd (3)
  q(0, "hindi", "ek-shabd", "M", 3,
    ["Choose the one word for 'one who takes no side' (जो किसी का पक्ष न ले):", ["पक्षपाती", "विपक्षी", "सहयोगी", "तटस्थ"], "'तटस्थ' means neutral, one who does not take sides. 'पक्षपाती' is partial."],
    ["'जो किसी का पक्ष न ले' के लिए एक शब्द चुनिए:", ["पक्षपाती", "विपक्षी", "सहयोगी", "तटस्थ"], "'तटस्थ' = जो किसी का पक्ष न ले। 'पक्षपाती' = जो किसी एक का पक्ष ले।"]),
  q(0, "hindi", "ek-shabd", "M", 0,
    ["Choose the one word for 'that which cannot be conquered' (जिसे जीता न जा सके):", ["अजेय", "अमर", "अभय", "अटल"], "'अजेय' means unconquerable. 'अमर' is immortal, 'अभय' fearless and 'अटल' unshakeable."],
    ["'जिसे जीता न जा सके' के लिए एक शब्द चुनिए:", ["अजेय", "अमर", "अभय", "अटल"], "'अजेय' = जिसे जीता न जा सके। 'अमर' = जो न मरे, 'अभय' = जिसे भय न हो, 'अटल' = जो न टले।"]),
  q(0, "hindi", "ek-shabd", "M", 1,
    ["Choose the one word for 'that which is before the eyes' (जो आँखों के सामने हो):", ["परोक्ष", "प्रत्यक्ष", "अप्रत्यक्ष", "अदृश्य"], "'प्रत्यक्ष' means visible, before the eyes. 'परोक्ष' and 'अप्रत्यक्ष' mean indirect or out of sight."],
    ["'जो आँखों के सामने हो' के लिए एक शब्द चुनिए:", ["परोक्ष", "प्रत्यक्ष", "अप्रत्यक्ष", "अदृश्य"], "'प्रत्यक्ष' = जो आँखों के सामने हो। 'परोक्ष' और 'अप्रत्यक्ष' = जो आँखों से ओझल हो।"]),
  // Alankar, ras, grammar (3)
  q(0, "hindi", "alankar-ras", "M", 2,
    ["What is the sthayi bhav (permanent emotion) of Karun ras?", ["क्रोध", "भय", "शोक", "विस्मय"], "The sthayi bhav of Karun (pathos) ras is 'शोक' (grief). क्रोध belongs to Raudra, भय to Bhayanak and विस्मय to Adbhut."],
    ["करुण रस का स्थायी भाव क्या है?", ["क्रोध", "भय", "शोक", "विस्मय"], "करुण रस का स्थायी भाव 'शोक' है। क्रोध रौद्र का, भय भयानक का और विस्मय अद्भुत रस का स्थायी भाव है।"]),
  q(0, "hindi", "alankar-ras", "H", 3,
    ["Identify the figure of speech in 'चरण-सरोज पखारन लागा':", ["Upma", "Utpreksha", "Anupras", "Rupak"], "The feet (चरण) are treated as identical with the lotus (सरोज), with no comparison word, so it is Rupak alankar."],
    ["'चरण-सरोज पखारन लागा' में कौन-सा अलंकार है?", ["उपमा", "उत्प्रेक्षा", "अनुप्रास", "रूपक"], "यहाँ चरण को ही सरोज (कमल) मान लिया गया है, कोई वाचक शब्द नहीं है, अतः रूपक अलंकार है।"]),
  q(0, "hindi", "vyakaran", "H", 0,
    ["In 'पेड़ से पत्ते गिरते हैं', the case marker 'से' shows which kaarak?", ["Apadan (separation)", "Karan (instrument)", "Karta", "Sampradan"], "'से' here shows separation (leaves falling away from the tree), so it is Apadan kaarak. When 'से' shows the means, it is Karan kaarak."],
    ["'पेड़ से पत्ते गिरते हैं' में 'से' किस कारक का चिह्न है?", ["अपादान", "करण", "कर्ता", "संप्रदान"], "यहाँ 'से' अलग होने (पत्तों का पेड़ से अलग होना) का बोध कराता है, अतः अपादान कारक है। साधन के अर्थ में 'से' करण कारक होता है।"]),
];
