// HP Police Constable subject tests: Himachal GK 1 and 2 (25 questions each). All questions are new, not in the full mocks.

import { q, type PoliceQuestion } from "../types";

export const hpGk1: PoliceQuestion[] = [
  // Princely states and history (8)
  q(0, "hp-gk", "history", "H", 0,
    ["Arki, known for its fort and wall paintings, was the capital of which princely state?", ["Baghal", "Bhajji", "Keonthal", "Kuthar"], "Arki in Solan district was the capital of the Baghal state. The Arki fort has fine Pahari wall paintings."],
    ["अपने किले और भित्तिचित्रों के लिए प्रसिद्ध अर्की किस रियासत की राजधानी थी?", ["बाघल", "भज्जी", "क्योंथल", "कुठाड़"], "सोलन जिले का अर्की बाघल रियासत की राजधानी था। अर्की किले में सुंदर पहाड़ी भित्तिचित्र हैं।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["Nalagarh was the capital of which princely state?", ["Baghat", "Hindur", "Kahlur", "Mangal"], "Nalagarh (Solan district) was the capital of the Hindur state, ruled by a branch of the Kahlur (Bilaspur) family."],
    ["नालागढ़ किस रियासत की राजधानी था?", ["बघाट", "हिंडूर", "कहलूर", "मांगल"], "नालागढ़ (सोलन जिला) हिंडूर रियासत की राजधानी था, जिस पर कहलूर (बिलासपुर) वंश की एक शाखा का शासन था।"]),
  q(0, "hp-gk", "history", "H", 2,
    ["Junga, near Shimla, was the capital of which hill state?", ["Jubbal", "Kumharsain", "Keonthal", "Bushahr"], "Junga was the capital of the Keonthal state, one of the larger Shimla hill states."],
    ["शिमला के पास स्थित जुन्गा किस पहाड़ी रियासत की राजधानी था?", ["जुब्बल", "कुमारसैन", "क्योंथल", "बुशहर"], "जुन्गा क्योंथल रियासत की राजधानी था, जो शिमला की बड़ी पहाड़ी रियासतों में से एक थी।"]),
  q(0, "hp-gk", "history", "M", 3,
    ["Rampur, famous for the Lavi fair, was the capital of which princely state?", ["Suket", "Mandi", "Sirmaur", "Bushahr"], "Rampur on the Sutlej was the capital of the Bushahr state; Sarahan was its summer capital."],
    ["लवी मेले के लिए प्रसिद्ध रामपुर किस रियासत की राजधानी था?", ["सुकेत", "मंडी", "सिरमौर", "बुशहर"], "सतलुज किनारे रामपुर बुशहर रियासत की राजधानी था; सराहन इसकी ग्रीष्मकालीन राजधानी थी।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["The town of Hamirpur is named after which Katoch ruler?", ["Raja Hamir Chand", "Raja Sansar Chand", "Raja Abhay Chand", "Raja Ghamand Chand"], "Hamirpur takes its name from Raja Hamir Chand of the Katoch dynasty, who ruled in the early 18th century and built a fort there."],
    ["हमीरपुर नगर का नाम किस कटोच शासक के नाम पर है?", ["राजा हमीर चंद", "राजा संसार चंद", "राजा अभय चंद", "राजा घमंड चंद"], "हमीरपुर का नाम कटोच वंश के राजा हमीर चंद के नाम पर है, जिन्होंने 18वीं शताब्दी के आरंभ में शासन किया और वहाँ किला बनवाया।"]),
  q(0, "hp-gk", "districts", "H", 1,
    ["The old Mahasu district was merged into which district in 1972?", ["Solan", "Shimla", "Kinnaur", "Sirmaur"], "In the 1972 reorganisation Mahasu district was merged into Shimla district (parts went to the new Solan district)."],
    ["1972 में पुराने महासू जिले को किस जिले में मिला दिया गया?", ["सोलन", "शिमला", "किन्नौर", "सिरमौर"], "1972 के पुनर्गठन में महासू जिले को शिमला जिले में मिला दिया गया (कुछ भाग नए सोलन जिले में गए)।"]),
  q(0, "hp-gk", "history", "H", 2,
    ["The Rang Mahal of Chamba, known for its wall paintings, was built by Raja:", ["Sahil Varman", "Bhuri Singh", "Umed Singh", "Charat Singh"], "Raja Umed Singh (18th century) began the Rang Mahal. Its murals are now partly shown in the National Museum and the Bhuri Singh Museum."],
    ["भित्तिचित्रों के लिए प्रसिद्ध चंबा का रंग महल किस राजा ने बनवाया?", ["साहिल वर्मन", "भूरि सिंह", "उम्मेद सिंह", "चड़त सिंह"], "राजा उम्मेद सिंह (18वीं शताब्दी) ने रंग महल का निर्माण शुरू कराया। इसके भित्तिचित्र अब आंशिक रूप से राष्ट्रीय संग्रहालय और भूरि सिंह संग्रहालय में हैं।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["The Nahan Foundry, one of the oldest foundries of north India, was set up in 1875 by Raja:", ["Fateh Prakash", "Karam Prakash", "Amar Prakash", "Shamsher Prakash"], "Raja Shamsher Prakash of Sirmaur set up the Nahan Foundry in 1875. It made sugarcane crushers and other iron goods."],
    ["उत्तर भारत की सबसे पुरानी ढलाईशालाओं में से एक नाहन फाउंड्री 1875 में किस राजा ने स्थापित की?", ["फ़तेह प्रकाश", "करम प्रकाश", "अमर प्रकाश", "शमशेर प्रकाश"], "सिरमौर के राजा शमशेर प्रकाश ने 1875 में नाहन फाउंड्री स्थापित की। इसमें गन्ना पेरने की मशीनें और अन्य लोहे का सामान बनता था।"]),
  // Places, institutions and monuments (8)
  q(0, "hp-gk", "economy", "M", 0,
    ["The Central Research Institute, which has made vaccines since 1905, is located at:", ["Kasauli", "Solan", "Shimla", "Palampur"], "The Central Research Institute (CRI) at Kasauli, Solan district, was set up in 1905 and makes vaccines and sera."],
    ["1905 से टीके बनाने वाला केंद्रीय अनुसंधान संस्थान (CRI) कहाँ स्थित है?", ["कसौली", "सोलन", "शिमला", "पालमपुर"], "सोलन जिले के कसौली में केंद्रीय अनुसंधान संस्थान (CRI) 1905 में स्थापित हुआ और यह टीके व सीरम बनाता है।"]),
  q(0, "hp-gk", "districts", "H", 1,
    ["The Lawrence School, founded in 1847 and one of the oldest co-educational boarding schools in Asia, is at:", ["Chail", "Sanawar", "Dagshai", "Subathu"], "The Lawrence School was founded at Sanawar near Kasauli (Solan district) in 1847 by Sir Henry Lawrence."],
    ["1847 में स्थापित और एशिया के सबसे पुराने सह-शिक्षा आवासीय विद्यालयों में से एक लॉरेंस स्कूल कहाँ है?", ["चैल", "सनावर", "डगशाई", "सुबाथू"], "लॉरेंस स्कूल की स्थापना 1847 में सर हेनरी लॉरेंस ने कसौली (सोलन जिला) के पास सनावर में की।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The Panchvaktra temple at Mandi stands at the confluence of the Beas and the:", ["Uhl", "Sainj", "Suketi", "Tirthan"], "The Panchvaktra (five-faced Shiva) temple stands where the Suketi stream meets the Beas at Mandi."],
    ["मंडी का पंचवक्त्र मंदिर ब्यास और किस नदी के संगम पर स्थित है?", ["उहल", "सैंज", "सुकेती", "तीर्थन"], "पंचवक्त्र (पाँच मुख वाले शिव) मंदिर मंडी में वहाँ है जहाँ सुकेती खड्ड ब्यास में मिलती है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["Rewalsar (Tso Pema) is sacred to Buddhists because of its association with:", ["Atisha", "The Dalai Lama", "Rinchen Zangpo", "Padmasambhava (Guru Rinpoche)"], "Buddhists believe Padmasambhava meditated at Rewalsar; the lake is called Tso Pema (Lotus Lake) and has a large statue of him."],
    ["रिवालसर (त्सो पेमा) बौद्धों के लिए किसके कारण पवित्र है?", ["अतीश", "दलाई लामा", "रिनचेन ज़ांगपो", "पद्मसंभव (गुरु रिनपोछे)"], "बौद्धों का विश्वास है कि पद्मसंभव ने रिवालसर में साधना की; झील को त्सो पेमा (कमल झील) कहते हैं और यहाँ उनकी विशाल प्रतिमा है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Chamunda Devi temple near Dharamshala stands on the bank of which river?", ["Baner", "Beas", "Gaj", "Neugal"], "The Chamunda Devi temple in Kangra district is on the bank of the Baner river."],
    ["धर्मशाला के पास चामुंडा देवी मंदिर किस नदी के किनारे है?", ["बनेर", "ब्यास", "गज", "न्यूगल"], "कांगड़ा जिले में चामुंडा देवी मंदिर बनेर नदी के किनारे है।"]),
  q(0, "hp-gk", "personalities", "M", 1,
    ["The Russian painter Nicholas Roerich spent his last years at:", ["Manali", "Naggar", "Dharamshala", "Kasauli"], "Nicholas Roerich settled at Naggar in the Kullu valley and died there in 1947. His house is now the Roerich art gallery."],
    ["रूसी चित्रकार निकोलस रोरिक ने अपने अंतिम वर्ष कहाँ बिताए?", ["मनाली", "नग्गर", "धर्मशाला", "कसौली"], "निकोलस रोरिक कुल्लू घाटी के नग्गर में बस गए और 1947 में वहीं उनका निधन हुआ। उनका घर अब रोरिक आर्ट गैलरी है।"]),
  q(0, "hp-gk", "districts", "M", 2,
    ["Malana village, often called one of the oldest democracies of the world, is in which district?", ["Chamba", "Kinnaur", "Kullu", "Mandi"], "Malana in the Parvati valley of Kullu district has its own village council, believed to be one of the oldest democratic systems."],
    ["विश्व के सबसे पुराने लोकतंत्रों में गिना जाने वाला मलाणा गाँव किस जिले में है?", ["चंबा", "किन्नौर", "कुल्लू", "मंडी"], "कुल्लू जिले की पार्वती घाटी का मलाणा अपनी ग्राम परिषद के लिए प्रसिद्ध है, जिसे सबसे पुरानी लोकतांत्रिक व्यवस्थाओं में माना जाता है।"]),
  q(0, "hp-gk", "geography", "H", 3,
    ["Langza village in Spiti is famous for:", ["Hot springs", "Apple orchards", "Tea gardens", "Marine fossils found at high altitude"], "Langza, at about 4,400 m, is known for fossils of sea creatures (ammonites), left from the time the region lay under the Tethys Sea."],
    ["स्पीति का लांग्ज़ा गाँव किसके लिए प्रसिद्ध है?", ["गर्म पानी के चश्मे", "सेब के बगीचे", "चाय बागान", "ऊँचाई पर मिलने वाले समुद्री जीवाश्म"], "लगभग 4,400 मी पर स्थित लांग्ज़ा समुद्री जीवों (एमोनाइट) के जीवाश्मों के लिए प्रसिद्ध है, जो उस समय के हैं जब यह क्षेत्र टेथिस सागर के नीचे था।"]),
  q(0, "hp-gk", "history", "H", 0,
    ["The Gaiety Theatre on the Mall in Shimla was opened in the year:", ["1887", "1864", "1903", "1925"], "The Gothic-style Gaiety Theatre opened in 1887 as part of the Town Hall building on the Mall, Shimla."],
    ["शिमला के माल रोड पर गेयटी थिएटर किस वर्ष खुला?", ["1887", "1864", "1903", "1925"], "गॉथिक शैली का गेयटी थिएटर 1887 में शिमला के माल रोड पर टाउन हॉल भवन के भाग के रूप में खुला।"]),
  // Geography, rivers and economy (5)
  q(0, "hp-gk", "geography", "M", 1,
    ["Churdhar, the peak with the temple of Shirgul Maharaj, is the highest peak of which district?", ["Shimla", "Sirmaur", "Solan", "Mandi"], "Churdhar (about 3,650 m) is the highest peak of Sirmaur district and of the outer Himalaya in this region."],
    ["शिरगुल महाराज के मंदिर वाली चूड़धार चोटी किस जिले की सबसे ऊँची चोटी है?", ["शिमला", "सिरमौर", "सोलन", "मंडी"], "चूड़धार (लगभग 3,650 मी) सिरमौर जिले और इस क्षेत्र के बाहरी हिमालय की सबसे ऊँची चोटी है।"]),
  q(0, "hp-gk", "geography", "H", 2,
    ["The Shivalik Fossil Park at Saketi, with life-size models of prehistoric animals, is in which district?", ["Una", "Bilaspur", "Sirmaur", "Kangra"], "The Shivalik Fossil Park at Saketi in the Markanda valley of Sirmaur district was set up in 1974."],
    ["प्रागैतिहासिक जानवरों के आदमक़द मॉडलों वाला साकेती का शिवालिक जीवाश्म उद्यान किस जिले में है?", ["ऊना", "बिलासपुर", "सिरमौर", "कांगड़ा"], "सिरमौर जिले की मारकंडा घाटी में साकेती का शिवालिक जीवाश्म उद्यान 1974 में स्थापित हुआ।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 3,
    ["The Kandrour bridge in Bilaspur district, among the highest road bridges in Asia, spans which river?", ["Beas", "Ravi", "Yamuna", "Sutlej"], "The Kandrour bridge (about 80 m high, completed in 1965) crosses the Sutlej on the Bilaspur–Ghumarwin road."],
    ["बिलासपुर जिले का कंदरौर पुल, जो एशिया के सबसे ऊँचे सड़क पुलों में है, किस नदी पर बना है?", ["ब्यास", "रावी", "यमुना", "सतलुज"], "कंदरौर पुल (लगभग 80 मी ऊँचा, 1965 में पूर्ण) बिलासपुर–घुमारवीं मार्ग पर सतलुज को पार करता है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["The Chandrabhaga (Chenab), after leaving Lahaul, flows through which valley of Chamba district?", ["Pangi", "Bharmour", "Churah", "Saluni"], "After Lahaul the Chenab flows through the Pangi valley of Chamba district before entering Jammu & Kashmir."],
    ["चंद्रभागा (चिनाब) लाहौल से निकलने के बाद चंबा जिले की किस घाटी से होकर बहती है?", ["पांगी", "भरमौर", "चुराह", "सलूणी"], "लाहौल के बाद चिनाब चंबा जिले की पांगी घाटी से बहकर जम्मू-कश्मीर में प्रवेश करती है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["Which river has the largest catchment area in Himachal Pradesh?", ["Beas", "Sutlej", "Ravi", "Chenab"], "The Sutlej has the largest catchment within the state, draining Kinnaur, Spiti, Shimla, Kullu, Mandi and Bilaspur areas."],
    ["हिमाचल प्रदेश में किस नदी का जलग्रहण क्षेत्र सबसे बड़ा है?", ["ब्यास", "सतलुज", "रावी", "चिनाब"], "राज्य में सतलुज का जलग्रहण क्षेत्र सबसे बड़ा है, जो किन्नौर, स्पीति, शिमला, कुल्लू, मंडी और बिलासपुर क्षेत्रों का जल बहाती है।"]),
  // Polity and culture (4)
  q(0, "hp-gk", "polity-administration", "H", 2,
    ["Which Lok Sabha constituency of Himachal Pradesh is reserved for Scheduled Castes?", ["Kangra", "Mandi", "Shimla", "Hamirpur"], "Of the four Lok Sabha seats (Shimla, Mandi, Kangra and Hamirpur), Shimla is reserved for Scheduled Castes."],
    ["हिमाचल प्रदेश का कौन-सा लोकसभा क्षेत्र अनुसूचित जाति के लिए आरक्षित है?", ["कांगड़ा", "मंडी", "शिमला", "हमीरपुर"], "चार लोकसभा सीटों (शिमला, मंडी, कांगड़ा और हमीरपुर) में से शिमला अनुसूचित जाति के लिए आरक्षित है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["'Thoda', a martial folk tradition played with bows and arrows around Baisakhi, is associated with which region?", ["Lahaul & Spiti", "Chamba and Pangi", "Kangra and Una", "Shimla, Sirmaur and Solan"], "Thoda is a mock archery battle between two groups (Pashis and Saathis) performed in the Shimla, Sirmaur and Solan hills, mainly around Baisakhi."],
    ["बैसाखी के आसपास धनुष-बाण से खेली जाने वाली युद्ध-कला परंपरा 'ठोडा' किस क्षेत्र से संबंधित है?", ["लाहौल-स्पीति", "चंबा और पांगी", "कांगड़ा और ऊना", "शिमला, सिरमौर और सोलन"], "ठोडा दो दलों (पाशी और साठी) के बीच धनुर्विद्या का नकली युद्ध है, जो मुख्यतः बैसाखी के आसपास शिमला, सिरमौर और सोलन की पहाड़ियों में खेला जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The traditional Himachali feast 'Dham' is cooked by hereditary cooks known as:", ["Botis", "Gaddis", "Lohars", "Rathis"], "Dham, served on leaf plates at weddings and festivals, is cooked by Brahmin cooks called Botis."],
    ["पारंपरिक हिमाचली भोज 'धाम' को बनाने वाले वंशानुगत रसोइये क्या कहलाते हैं?", ["बोटी", "गद्दी", "लोहार", "राठी"], "विवाह और उत्सवों में पत्तल पर परोसी जाने वाली धाम को बोटी कहलाने वाले ब्राह्मण रसोइये बनाते हैं।"]),
];

export const hpGk2: PoliceQuestion[] = [
  // History and administration (6)
  q(0, "hp-gk", "history", "H", 0,
    ["The Kangra Fort stands at the confluence of which two streams?", ["Banganga and Majhi", "Beas and Uhl", "Neugal and Baner", "Gaj and Dehar"], "The Kangra (Nagarkot) Fort stands on a ridge at the confluence of the Banganga and Majhi streams, near Kangra town."],
    ["कांगड़ा किला किन दो धाराओं के संगम पर स्थित है?", ["बाणगंगा और माझी", "ब्यास और उहल", "न्यूगल और बनेर", "गज और देहर"], "कांगड़ा (नगरकोट) किला कांगड़ा नगर के पास बाणगंगा और माझी धाराओं के संगम पर एक पहाड़ी पर स्थित है।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["Solan district was created on 1 September 1972 mainly from parts of:", ["Kangra and Una", "Mahasu and Shimla", "Mandi and Bilaspur", "Sirmaur and Kinnaur"], "Solan district was formed in 1972 from the Solan and Arki tehsils of Mahasu district and the Kandaghat and Nalagarh tehsils of the old Shimla district."],
    ["सोलन जिला 1 सितंबर 1972 को मुख्यतः किन जिलों के भागों से बना?", ["कांगड़ा और ऊना", "महासू और शिमला", "मंडी और बिलासपुर", "सिरमौर और किन्नौर"], "सोलन जिला 1972 में महासू जिले की सोलन और अर्की तहसीलों तथा पुराने शिमला जिले की कंडाघाट और नालागढ़ तहसीलों से बना।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["Dagshai, known for its old cantonment and the British-era jail museum, is in which district?", ["Shimla", "Sirmaur", "Solan", "Bilaspur"], "Dagshai in Solan district is one of the oldest cantonments in the region; its 1849 jail is now a museum."],
    ["पुरानी छावनी और ब्रिटिशकालीन जेल संग्रहालय के लिए प्रसिद्ध डगशाई किस जिले में है?", ["शिमला", "सिरमौर", "सोलन", "बिलासपुर"], "सोलन जिले का डगशाई क्षेत्र की सबसे पुरानी छावनियों में है; इसकी 1849 की जेल अब संग्रहालय है।"]),
  q(0, "hp-gk", "polity-administration", "H", 3,
    ["Barnes Court in Shimla now serves as the:", ["State Secretariat", "High Court", "Vidhan Sabha", "Raj Bhavan (Governor's residence)"], "Barnes Court, a Tudor-style building in Shimla, is the Raj Bhavan, the official residence of the Governor of Himachal Pradesh."],
    ["शिमला का बार्न्स कोर्ट अब किस रूप में प्रयोग होता है?", ["राज्य सचिवालय", "उच्च न्यायालय", "विधानसभा", "राजभवन (राज्यपाल का निवास)"], "शिमला का ट्यूडर शैली का बार्न्स कोर्ट राजभवन है, जो हिमाचल प्रदेश के राज्यपाल का आधिकारिक निवास है।"]),
  q(0, "hp-gk", "polity-administration", "M", 0,
    ["How many members are there in the Himachal Pradesh Vidhan Sabha?", ["68", "65", "72", "80"], "The Himachal Pradesh Vidhan Sabha has 68 members, all directly elected."],
    ["हिमाचल प्रदेश विधानसभा में कितने सदस्य हैं?", ["68", "65", "72", "80"], "हिमाचल प्रदेश विधानसभा में 68 सदस्य हैं, जो सभी प्रत्यक्ष रूप से निर्वाचित होते हैं।"]),
  q(0, "hp-gk", "polity-administration", "H", 1,
    ["The state legislature of Himachal Pradesh is:", ["Bicameral, with a Legislative Council", "Unicameral, with only the Vidhan Sabha", "Bicameral since 1971", "A Union Territory assembly"], "Himachal Pradesh has a unicameral legislature: only the Vidhan Sabha, with no Legislative Council (Vidhan Parishad)."],
    ["हिमाचल प्रदेश का राज्य विधानमंडल कैसा है?", ["द्विसदनीय, विधान परिषद सहित", "एकसदनीय, केवल विधानसभा", "1971 से द्विसदनीय", "केंद्रशासित प्रदेश की विधानसभा"], "हिमाचल प्रदेश का विधानमंडल एकसदनीय है: केवल विधानसभा, विधान परिषद नहीं है।"]),
  // Places and temples (6)
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Brajeshwari Devi temple, one of the Shakti Peeths, is located in:", ["Una town", "Chamba town", "Kangra town", "Mandi town"], "The Brajeshwari (Vajreshwari) Devi temple is in Kangra town, the old Nagarkot, and was plundered by Mahmud of Ghazni."],
    ["शक्तिपीठों में से एक बज्रेश्वरी देवी मंदिर कहाँ स्थित है?", ["ऊना नगर", "चंबा नगर", "कांगड़ा नगर", "मंडी नगर"], "बज्रेश्वरी (वज्रेश्वरी) देवी मंदिर पुराने नगरकोट, यानी कांगड़ा नगर में है, जिसे महमूद गजनवी ने लूटा था।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The Norbulingka Institute, which preserves Tibetan art and crafts, is near:", ["Manali", "Shimla", "Kaza", "Dharamshala"], "The Norbulingka Institute at Sidhbari near Dharamshala trains artists in Tibetan thangka painting, woodcraft and other arts."],
    ["तिब्बती कला और शिल्प को संरक्षित करने वाला नोरबुलिंगका संस्थान कहाँ के पास है?", ["मनाली", "शिमला", "काज़ा", "धर्मशाला"], "धर्मशाला के पास सिद्धबाड़ी में नोरबुलिंगका संस्थान कलाकारों को तिब्बती थांका चित्रकला, काष्ठ-शिल्प और अन्य कलाओं का प्रशिक्षण देता है।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["Vashisht, known for its natural hot sulphur springs, is near:", ["Manali", "Shimla", "Chamba", "Nahan"], "Vashisht village near Manali, across the Beas, has hot sulphur springs and a temple of sage Vashisht."],
    ["प्राकृतिक गर्म गंधक-जल के चश्मों के लिए प्रसिद्ध वशिष्ठ कहाँ के पास है?", ["मनाली", "शिमला", "चंबा", "नाहन"], "मनाली के पास ब्यास के पार स्थित वशिष्ठ गाँव में गर्म गंधक-जल के चश्मे और ऋषि वशिष्ठ का मंदिर है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The Mamleshwar Mahadev temple, linked by legend to the Pandavas, is at:", ["Bharmour", "Karsog", "Nirmand", "Jubbal"], "The Mamleshwar Mahadev temple is at Mamel near Karsog in Mandi district. It is said to house a huge drum and a grain of wheat from the Pandava period."],
    ["पौराणिक कथाओं में पांडवों से जुड़ा ममलेश्वर महादेव मंदिर कहाँ है?", ["भरमौर", "करसोग", "निरमंड", "जुब्बल"], "ममलेश्वर महादेव मंदिर मंडी जिले में करसोग के पास ममेल में है। कहा जाता है कि यहाँ पांडवकालीन विशाल ढोल और गेहूँ का दाना रखा है।"]),
  q(0, "hp-gk", "history", "H", 2,
    ["Kamlah Fort, built on a steep hill in the 17th century, is in which district?", ["Kangra", "Hamirpur", "Mandi", "Bilaspur"], "Kamlah Fort near Sarkaghat in Mandi district was built by the rulers of Mandi and was considered almost impregnable."],
    ["17वीं शताब्दी में खड़ी पहाड़ी पर बना कमलाह किला किस जिले में है?", ["कांगड़ा", "हमीरपुर", "मंडी", "बिलासपुर"], "मंडी जिले में सरकाघाट के पास कमलाह किला मंडी के शासकों ने बनवाया और इसे लगभग अभेद्य माना जाता था।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["Kalpa in Kinnaur is famous for its view of which peak?", ["Deo Tibba", "Reo Purgyil", "Churdhar", "Kinner Kailash"], "Kalpa, the old headquarters of Kinnaur, faces the Kinner Kailash range across the Sutlej."],
    ["किन्नौर का कल्पा किस चोटी के दृश्य के लिए प्रसिद्ध है?", ["देव टिब्बा", "रियो पुर्गिल", "चूड़धार", "किन्नर कैलाश"], "किन्नौर का पुराना मुख्यालय कल्पा सतलुज के पार किन्नर कैलाश श्रेणी के सामने है।"]),
  // Geography, rivers, wildlife (7)
  q(0, "hp-gk", "rivers-lakes", "H", 0,
    ["The Swan river, which caused frequent floods and is now being channelised, flows mainly through which district?", ["Una", "Kangra", "Solan", "Hamirpur"], "The Swan (Sowan) river flows through Una district and joins the Sutlej in Punjab. A large project has channelised it to control floods."],
    ["बार-बार बाढ़ लाने वाली और अब तटबंधित की जा रही स्वां नदी मुख्यतः किस जिले से बहती है?", ["ऊना", "कांगड़ा", "सोलन", "हमीरपुर"], "स्वां नदी ऊना जिले से बहकर पंजाब में सतलुज में मिलती है। बाढ़ रोकने के लिए एक बड़ी परियोजना से इसका तटबंधीकरण किया गया है।"]),
  q(0, "hp-gk", "economy", "H", 1,
    ["The Koldam hydroelectric project on the Sutlej in Bilaspur district has an installed capacity of:", ["500 MW", "800 MW", "1,000 MW", "1,500 MW"], "Koldam (NTPC) has four units of 200 MW each, i.e. 800 MW. Nathpa Jhakri, also on the Sutlej, is 1,500 MW."],
    ["बिलासपुर जिले में सतलुज पर कोलडैम जलविद्युत परियोजना की स्थापित क्षमता कितनी है?", ["500 मेगावाट", "800 मेगावाट", "1,000 मेगावाट", "1,500 मेगावाट"], "कोलडैम (NTPC) में 200 मेगावाट की चार इकाइयाँ, यानी 800 मेगावाट हैं। सतलुज पर ही नाथपा झाकड़ी 1,500 मेगावाट की है।"]),
  q(0, "hp-gk", "economy", "M", 2,
    ["Parwanoo, called the gateway to Himachal Pradesh and an industrial town, is in which district?", ["Sirmaur", "Una", "Solan", "Shimla"], "Parwanoo, on the Kalka–Shimla highway at the Haryana border, is an industrial town of Solan district."],
    ["हिमाचल का प्रवेश द्वार और औद्योगिक नगर कहलाने वाला परवाणू किस जिले में है?", ["सिरमौर", "ऊना", "सोलन", "शिमला"], "हरियाणा सीमा पर कालका–शिमला राजमार्ग पर स्थित परवाणू सोलन जिले का औद्योगिक नगर है।"]),
  q(0, "hp-gk", "geography", "H", 3,
    ["The Shinku La pass connects Lahaul with:", ["Spiti", "Kinnaur", "Pangi", "Zanskar (Ladakh)"], "Shinku La (about 5,090 m) links the Darcha area of Lahaul with the Zanskar valley of Ladakh; a road tunnel is planned under it."],
    ["शिंकू ला दर्रा लाहौल को किससे जोड़ता है?", ["स्पीति", "किन्नौर", "पांगी", "ज़ांस्कर (लद्दाख)"], "शिंकू ला (लगभग 5,090 मी) लाहौल के दारचा क्षेत्र को लद्दाख की ज़ांस्कर घाटी से जोड़ता है; इसके नीचे सड़क सुरंग प्रस्तावित है।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["What is the total geographical area of Himachal Pradesh?", ["55,673 km²", "44,212 km²", "53,483 km²", "65,300 km²"], "Himachal Pradesh covers 55,673 km², about 1.7% of India's area."],
    ["हिमाचल प्रदेश का कुल भौगोलिक क्षेत्रफल कितना है?", ["55,673 वर्ग किमी", "44,212 वर्ग किमी", "53,483 वर्ग किमी", "65,300 वर्ग किमी"], "हिमाचल प्रदेश का क्षेत्रफल 55,673 वर्ग किमी है, जो भारत के क्षेत्रफल का लगभग 1.7% है।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["The Rupi Bhaba Wildlife Sanctuary is located in which district?", ["Kullu", "Kinnaur", "Chamba", "Shimla"], "Rupi Bhaba Wildlife Sanctuary lies in the Kinnaur district along the Sutlej, south of the Bhaba valley."],
    ["रूपी भाबा वन्यजीव अभयारण्य किस जिले में है?", ["कुल्लू", "किन्नौर", "चंबा", "शिमला"], "रूपी भाबा वन्यजीव अभयारण्य किन्नौर जिले में सतलुज के साथ, भाबा घाटी के दक्षिण में है।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["The Kibber Wildlife Sanctuary, a home of the snow leopard and blue sheep, is located in:", ["Kinnaur", "Chamba", "Spiti", "Kullu"], "Kibber Wildlife Sanctuary is in Spiti (Lahaul & Spiti district), around Kibber, one of the highest villages with a motorable road."],
    ["हिम तेंदुए और भरल का निवास किब्बर वन्यजीव अभयारण्य कहाँ स्थित है?", ["किन्नौर", "चंबा", "स्पीति", "कुल्लू"], "किब्बर वन्यजीव अभयारण्य स्पीति (लाहौल-स्पीति जिला) में किब्बर के आसपास है, जो सड़क से जुड़े सबसे ऊँचे गाँवों में है।"]),
  // Personalities and culture (6)
  q(0, "hp-gk", "personalities", "H", 3,
    ["Major Dhan Singh Thapa, awarded the Param Vir Chakra for the 1962 war in Ladakh, was born in:", ["Kangra", "Mandi", "Palampur", "Shimla"], "Major Dhan Singh Thapa of 1/8 Gorkha Rifles was born in Shimla in 1928. He received the Param Vir Chakra for defending a post at Pangong Lake in 1962."],
    ["1962 के युद्ध में लद्दाख में वीरता के लिए परमवीर चक्र पाने वाले मेजर धन सिंह थापा का जन्म कहाँ हुआ था?", ["कांगड़ा", "मंडी", "पालमपुर", "शिमला"], "1/8 गोरखा राइफल्स के मेजर धन सिंह थापा का जन्म 1928 में शिमला में हुआ। 1962 में पैंगोंग झील पर चौकी की रक्षा के लिए उन्हें परमवीर चक्र मिला।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["'Losar', celebrated in Lahaul-Spiti and Kinnaur, marks the:", ["Tibetan (Buddhist) New Year", "Harvest of apples", "Arrival of the monsoon", "End of the Dussehra fair"], "Losar is the Tibetan Buddhist New Year, celebrated in the Buddhist areas of Himachal around February–March."],
    ["लाहौल-स्पीति और किन्नौर में मनाया जाने वाला 'लोसर' किसका प्रतीक है?", ["तिब्बती (बौद्ध) नव वर्ष", "सेब की फसल", "मानसून का आगमन", "दशहरा मेले का समापन"], "लोसर तिब्बती बौद्ध नव वर्ष है, जो हिमाचल के बौद्ध क्षेत्रों में फरवरी–मार्च के आसपास मनाया जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The 'Sair' festival, marking the end of the monsoon and the harvest, is celebrated in the month of:", ["Chaitra (March–April)", "Asuj (September)", "Magh (January)", "Jyeshtha (May–June)"], "Sair is celebrated on the first day of Asuj (mid-September) in Mandi, Shimla, Solan and Kullu, marking the end of the rains and the harvest."],
    ["मानसून की समाप्ति और फसल का प्रतीक 'सायर' उत्सव किस माह में मनाया जाता है?", ["चैत्र (मार्च–अप्रैल)", "असूज (सितंबर)", "माघ (जनवरी)", "ज्येष्ठ (मई–जून)"], "सायर असूज के पहले दिन (सितंबर मध्य) मंडी, शिमला, सोलन और कुल्लू में मनाया जाता है, जो वर्षा की समाप्ति और फसल का प्रतीक है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["Unlike most of India, where Dussehra ends on Vijayadashami, the International Kullu Dussehra:", ["Is held in spring", "Ends before Navratri", "Begins on Vijayadashami and lasts about a week", "Is held only once in 12 years"], "Kullu Dussehra starts on Vijayadashami, when the rath of Raghunath is pulled at Dhalpur, and continues for seven days."],
    ["भारत के अधिकांश भागों में दशहरा विजयादशमी को समाप्त होता है, जबकि अंतरराष्ट्रीय कुल्लू दशहरा:", ["वसंत में होता है", "नवरात्रि से पहले समाप्त होता है", "विजयादशमी से शुरू होकर लगभग एक सप्ताह चलता है", "12 वर्ष में एक बार होता है"], "कुल्लू दशहरा विजयादशमी को ढालपुर में रघुनाथ जी की रथयात्रा से शुरू होकर सात दिन चलता है।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["Kufri, near Shimla, is best known for:", ["Tea gardens", "Hot springs", "Rock salt mines", "Winter sports and snow"], "Kufri, about 16 km from Shimla, is known for snow, skiing and winter sports, and has the Himalayan Nature Park."],
    ["शिमला के पास कुफ़री किसके लिए सबसे अधिक जाना जाता है?", ["चाय बागान", "गर्म चश्मे", "सेंधा नमक की खानें", "शीतकालीन खेल और बर्फ़"], "शिमला से लगभग 16 किमी दूर कुफ़री बर्फ़, स्कीइंग और शीतकालीन खेलों के लिए प्रसिद्ध है और यहाँ हिमालयन नेचर पार्क है।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["The Tirthan Wildlife Sanctuary, adjoining the Great Himalayan National Park, is in which district?", ["Kullu", "Mandi", "Shimla", "Chamba"], "Tirthan Wildlife Sanctuary lies in the Tirthan valley of Kullu district, next to the Great Himalayan National Park."],
    ["ग्रेट हिमालयन राष्ट्रीय उद्यान से सटा तीर्थन वन्यजीव अभयारण्य किस जिले में है?", ["कुल्लू", "मंडी", "शिमला", "चंबा"], "तीर्थन वन्यजीव अभयारण्य कुल्लू जिले की तीर्थन घाटी में ग्रेट हिमालयन राष्ट्रीय उद्यान के पास है।"]),
];
