// HP TET (JBT) sectional tests — Child Development & Pedagogy, 25 fresh questions each (sections: 0).

import { q, type PatwariQuestion } from "../patwari/types";

const P = "pedagogy";

export const jbtPedagogySectionals: PatwariQuestion[][] = [
  [
    q(0, P, "child-development", "M", 1,
      ["Object permanence, the understanding that things exist even when out of sight, is fully developing by about:", ["1 month", "8 to 12 months", "3 years", "7 years"], "Infants begin searching for hidden objects at about 8–12 months."],
      ["वस्तु स्थायित्व, यानी आँखों से ओझल वस्तु के भी अस्तित्व में रहने की समझ, लगभग कब तक विकसित हो जाती है?", ["1 माह", "8 से 12 माह", "3 वर्ष", "7 वर्ष"], "शिशु लगभग 8–12 माह में छिपी वस्तु को ढूँढने लगते हैं।"]),
    q(0, P, "child-development", "M", 3,
      ["Young children often talk to themselves while solving a problem. Vygotsky regarded this 'private speech' as:", ["A sign of mental illness", "A habit to be punished", "Egocentric noise only", "A tool that guides thinking"], "Private speech helps children plan and regulate their actions."],
      ["छोटे बच्चे समस्या हल करते समय प्रायः स्वयं से बातें करते हैं। वायगोत्स्की ने इस 'निजी भाषण' को क्या माना?", ["मानसिक रोग का लक्षण", "दंडनीय आदत", "केवल आत्म-केंद्रित शोर", "चिंतन को दिशा देने वाला साधन"], "निजी भाषण बच्चों को अपने कार्य की योजना बनाने और उन्हें नियंत्रित करने में मदद करता है।"]),
    q(0, P, "child-development", "H", 0,
      ["In Bronfenbrenner's ecological model, the family, school and peer group of a child make up the:", ["Microsystem", "Macrosystem", "Chronosystem", "Exosystem"], "The microsystem is the immediate setting in which the child directly interacts."],
      ["ब्रोंफ़ेनब्रेनर के पारिस्थितिक मॉडल में बच्चे का परिवार, विद्यालय और मित्र-समूह किसे बनाते हैं?", ["सूक्ष्म तंत्र", "वृहद तंत्र", "कालक्रम तंत्र", "बाह्य तंत्र"], "सूक्ष्म तंत्र वह निकटतम परिवेश है जिसमें बच्चा सीधे अंतःक्रिया करता है।"]),
    q(0, P, "child-development", "M", 2,
      ["John Bowlby is best known for his theory of:", ["Moral reasoning", "Multiple intelligences", "Attachment between infant and caregiver", "Operant conditioning"], "Bowlby stressed the early emotional bond with a caregiver."],
      ["जॉन बॉल्बी अपने किस सिद्धांत के लिए सबसे अधिक जाने जाते हैं?", ["नैतिक तर्क", "बहु-बुद्धि", "शिशु और देखभालकर्ता के बीच लगाव", "क्रिया-प्रसूत अनुबंधन"], "बॉल्बी ने देखभालकर्ता से शुरुआती भावनात्मक बंधन पर बल दिया।"]),
    q(0, P, "child-development", "H", 1,
      ["Harlow's experiments with infant monkeys and cloth 'mothers' showed that attachment depends mainly on:", ["Food supply", "Contact comfort", "Loud sounds", "Bright light"], "The monkeys clung to the soft cloth mother even when the wire mother gave milk."],
      ["शिशु बंदरों और कपड़े की 'माताओं' पर हार्लो के प्रयोगों ने दिखाया कि लगाव मुख्यतः किस पर निर्भर करता है?", ["भोजन की आपूर्ति", "स्पर्श से मिलने वाला आराम", "तेज़ आवाज़ें", "तेज़ रोशनी"], "तार की माँ दूध देती थी, फिर भी बंदर नरम कपड़े की माँ से चिपके रहे।"]),
    q(0, P, "child-development", "M", 0,
      ["Arnold Gesell explained development mainly through:", ["Maturation", "Reinforcement", "Imitation", "Punishment"], "Gesell believed that biological ripening sets the order of development."],
      ["अर्नोल्ड गेसेल ने विकास की व्याख्या मुख्यतः किसके आधार पर की?", ["परिपक्वता", "पुनर्बलन", "अनुकरण", "दंड"], "गेसेल का मत था कि जैविक परिपक्वता विकास का क्रम तय करती है।"]),
    q(0, P, "child-development", "M", 3,
      ["When a newborn's cheek is touched, she turns her head and opens her mouth. This inborn reaction is the:", ["Moro reflex", "Grasp reflex", "Babinski reflex", "Rooting reflex"], "The rooting reflex helps the baby find the nipple."],
      ["नवजात की गाल छूने पर वह सिर घुमाकर मुँह खोलती है। यह जन्मजात प्रतिक्रिया कौन-सी है?", ["मोरो प्रतिवर्त", "पकड़ प्रतिवर्त", "बैबिंस्की प्रतिवर्त", "रूटिंग प्रतिवर्त"], "रूटिंग प्रतिवर्त शिशु को स्तन खोजने में मदद करता है।"]),
    q(0, P, "child-development", "H", 2,
      ["Konrad Lorenz's study of ducklings following the first moving object they saw is known as:", ["Conditioning", "Modelling", "Imprinting", "Insight"], "Imprinting is rapid learning during a critical period."],
      ["कॉनराड लॉरेन्ज़ का बत्तख़ के बच्चों का अध्ययन, जो पहली चलती वस्तु के पीछे चल पड़ते हैं, क्या कहलाता है?", ["अनुबंधन", "प्रतिरूपण", "छापन (इंप्रिंटिंग)", "अंतर्दृष्टि"], "छापन किसी क्रांतिक काल में होने वाला तीव्र अधिगम है।"]),
    q(0, P, "child-development", "E", 0,
      ["Which agency of socialisation influences a child first and most deeply?", ["Family", "Mass media", "Workplace", "Political party"], "The family is the primary agency of socialisation."],
      ["समाजीकरण की कौन-सी संस्था बच्चे को सबसे पहले और सबसे गहरा प्रभावित करती है?", ["परिवार", "जनसंचार माध्यम", "कार्यस्थल", "राजनीतिक दल"], "परिवार समाजीकरण की प्राथमिक संस्था है।"]),
    q(0, P, "learning-theories", "M", 1,
      ["Teaching a complex skill by rewarding successive small steps towards the final behaviour is called, in Skinner's terms:", ["Extinction", "Shaping", "Modelling", "Chaining only"], "Shaping reinforces closer and closer approximations to the target behaviour."],
      ["किसी जटिल कौशल को सिखाने के लिए अंतिम व्यवहार की ओर बढ़ते छोटे चरणों को क्रमशः पुरस्कृत करना स्किनर की भाषा में क्या कहलाता है?", ["विलोपन", "आकार-निर्माण (शेपिंग)", "प्रतिरूपण", "केवल शृंखलन"], "शेपिंग लक्ष्य व्यवहार के निकटतर प्रयासों को पुनर्बलित करता है।"]),
    q(0, P, "learning-theories", "H", 3,
      ["Tolman showed through maze studies with rats that learning can occur without reinforcement and show up later. He called this:", ["Insight learning", "Classical conditioning", "Observational learning", "Latent learning"], "Latent learning stays hidden until there is a reason to use it."],
      ["चूहों पर भूल-भुलैया के अध्ययनों से टॉलमैन ने दिखाया कि बिना पुनर्बलन के भी सीखना हो सकता है और बाद में प्रकट होता है। इसे उन्होंने कहा:", ["अंतर्दृष्टि अधिगम", "शास्त्रीय अनुबंधन", "अवलोकनात्मक अधिगम", "अव्यक्त अधिगम"], "अव्यक्त अधिगम तब तक छिपा रहता है जब तक उसके प्रयोग का कारण न मिले।"]),
    q(0, P, "learning-theories", "M", 0,
      ["Research on memory suggests that practice spread over several sessions is generally:", ["More effective than a single long session", "Less effective than cramming", "Useless", "Harmful to long-term memory"], "Spaced practice leads to better retention than massed practice."],
      ["स्मृति पर शोध बताते हैं कि कई सत्रों में बँटा हुआ अभ्यास सामान्यतः कैसा होता है?", ["एक लंबे सत्र से अधिक प्रभावी", "रट्टा मारने से कम प्रभावी", "बेकार", "दीर्घकालिक स्मृति के लिए हानिकारक"], "बँटा हुआ अभ्यास एक साथ किए गए अभ्यास से बेहतर धारण देता है।"]),
    q(0, P, "learning-theories", "H", 2,
      ["The 'theory of identical elements', which says transfer occurs when two tasks share common elements, was proposed by:", ["Bruner", "Piaget", "Thorndike", "Kohlberg"], "Thorndike explained transfer through common elements between tasks."],
      ["'समान तत्वों का सिद्धांत', जिसके अनुसार दो कार्यों में सामान्य तत्व होने पर अंतरण होता है, किसने दिया?", ["ब्रूनर", "पियाजे", "थॉर्नडाइक", "कोहलबर्ग"], "थॉर्नडाइक ने अंतरण की व्याख्या कार्यों के बीच समान तत्वों से की।"]),
    q(0, P, "learning-theories", "H", 1,
      ["The concept of 'need for achievement' (nAch) is associated with:", ["Maslow", "McClelland", "Freud", "Pavlov"], "David McClelland studied the motive to achieve."],
      ["'उपलब्धि की आवश्यकता' (nAch) की अवधारणा किससे जुड़ी है?", ["मैस्लो", "मैक्लेलैंड", "फ्रायड", "पावलव"], "डेविड मैक्लेलैंड ने उपलब्धि की प्रेरणा का अध्ययन किया।"]),
    q(0, P, "learning-theories", "H", 3,
      ["A student explains her failure by saying 'the paper was too hard', an external cause. This kind of explanation is studied in:", ["Gestalt theory", "Psychoanalysis", "Operant theory", "Weiner's attribution theory"], "Attribution theory examines the causes people give for success and failure."],
      ["एक विद्यार्थी अपनी असफलता का कारण 'प्रश्नपत्र बहुत कठिन था' बताती है, जो बाह्य कारण है। इस प्रकार की व्याख्या का अध्ययन किसमें होता है?", ["गेस्टाल्ट सिद्धांत", "मनोविश्लेषण", "क्रिया-प्रसूत सिद्धांत", "वाइनर का आरोपण सिद्धांत"], "आरोपण सिद्धांत सफलता और असफलता के लिए लोगों द्वारा बताए कारणों का अध्ययन करता है।"]),
    q(0, P, "learning-theories", "M", 2,
      ["Bandura used the term 'self-efficacy' for a person's:", ["Intelligence quotient", "Physical strength", "Belief in her ability to succeed at a task", "Level of anxiety"], "Self-efficacy is confidence in one's capacity to perform a task."],
      ["बंडूरा ने 'आत्म-प्रभाविता' शब्द का प्रयोग व्यक्ति की किस बात के लिए किया?", ["बुद्धि-लब्धि", "शारीरिक बल", "किसी कार्य में सफल होने की अपनी क्षमता में विश्वास", "चिंता का स्तर"], "आत्म-प्रभाविता किसी कार्य को करने की अपनी क्षमता में विश्वास है।"]),
    q(0, P, "learning-theories", "M", 0,
      ["A token economy in the classroom works on the principle of:", ["Reinforcement", "Insight", "Maturation", "Imprinting"], "Tokens earned for good behaviour act as reinforcers."],
      ["कक्षा में टोकन अर्थव्यवस्था किस सिद्धांत पर कार्य करती है?", ["पुनर्बलन", "अंतर्दृष्टि", "परिपक्वता", "छापन"], "अच्छे व्यवहार पर मिले टोकन पुनर्बलक का काम करते हैं।"]),
    q(0, P, "learning-theories", "M", 1,
      ["Which step helps most in good classroom management at the start of the year?", ["Punishing the first offender severely", "Setting clear rules together with the pupils", "Avoiding any rules", "Seating the class in silence all day"], "Rules made with pupils are better understood and followed."],
      ["वर्ष के आरंभ में अच्छे कक्षा-प्रबंधन के लिए कौन-सा कदम सबसे अधिक सहायक है?", ["पहले दोषी को कड़ा दंड देना", "विद्यार्थियों के साथ मिलकर स्पष्ट नियम बनाना", "कोई नियम न रखना", "पूरे दिन कक्षा को चुपचाप बिठाना"], "विद्यार्थियों के साथ बने नियम बेहतर समझे और माने जाते हैं।"]),
    q(0, P, "learning-theories", "M", 3,
      ["Teachers who talk about 'visual, auditory and kinaesthetic' learners are referring to:", ["Types of intelligence tests", "Stages of development", "Kinds of reinforcement", "Learning styles"], "VAK describes preferred ways of taking in information."],
      ["जो शिक्षक 'दृश्य, श्रव्य और गतिबोधी' शिक्षार्थियों की बात करते हैं, वे किसकी चर्चा कर रहे होते हैं?", ["बुद्धि-परीक्षणों के प्रकार", "विकास की अवस्थाएँ", "पुनर्बलन के प्रकार", "अधिगम शैलियाँ"], "VAK जानकारी ग्रहण करने के पसंदीदा तरीकों को बताता है।"]),
    q(0, P, "child-development", "H", 2,
      ["A common criticism of Piaget's theory is that he:", ["Ignored thinking altogether", "Studied only adults", "Underestimated what young children can do and the role of culture", "Never used observation"], "Later research showed children succeed earlier on simplified tasks."],
      ["पियाजे के सिद्धांत की एक सामान्य आलोचना यह है कि उन्होंने:", ["चिंतन को पूरी तरह उपेक्षित किया", "केवल वयस्कों का अध्ययन किया", "छोटे बच्चों की क्षमता और संस्कृति की भूमिका को कम आँका", "कभी अवलोकन नहीं किया"], "बाद के शोधों ने दिखाया कि सरल किए गए कार्यों में बच्चे जल्दी सफल हो जाते हैं।"]),
    q(0, P, "learning-theories", "M", 1,
      ["A collection of a pupil's best work gathered over time to show growth is called a:", ["Rank list", "Portfolio", "Roll call", "Time table"], "Portfolio assessment records progress through samples of work."],
      ["समय के साथ विकास दिखाने के लिए एकत्र किए गए विद्यार्थी के उत्कृष्ट कार्य के संग्रह को क्या कहते हैं?", ["क्रम सूची", "पोर्टफ़ोलियो", "उपस्थिति पुकार", "समय-सारणी"], "पोर्टफ़ोलियो मूल्यांकन कार्य के नमूनों से प्रगति दर्ज करता है।"]),
    q(0, P, "learning-theories", "M", 0,
      ["A rubric helps a teacher assess a pupil's project by:", ["Giving clear criteria for each level of performance", "Hiding the standards", "Ranking children against each other", "Replacing feedback"], "A rubric lists criteria with descriptions of performance levels."],
      ["रूब्रिक शिक्षक को विद्यार्थी की परियोजना के आकलन में किस प्रकार सहायता करता है?", ["प्रदर्शन के प्रत्येक स्तर के स्पष्ट मानदंड देकर", "मानकों को छिपाकर", "बच्चों की आपस में तुलना करके", "फ़ीडबैक की जगह लेकर"], "रूब्रिक में मानदंड और प्रदर्शन-स्तरों का विवरण होता है।"]),
    q(0, P, "learning-theories", "M", 2,
      ["The best reason for asking pupils to assess each other's work with a checklist is that it:", ["Saves the teacher's pen", "Embarrasses weak pupils", "Builds understanding of the criteria and of their own work", "Makes marking unnecessary for ever"], "Peer assessment helps learners understand standards."],
      ["विद्यार्थियों से जाँच-सूची के साथ एक-दूसरे का कार्य परखवाने का सबसे अच्छा कारण यह है कि इससे:", ["शिक्षक की कलम बचती है", "कमज़ोर बच्चे शर्मिंदा होते हैं", "मानदंडों और अपने कार्य की समझ बनती है", "अंकन हमेशा के लिए अनावश्यक हो जाता है"], "सहपाठी-मूल्यांकन से शिक्षार्थी मानकों को समझते हैं।"]),
    q(0, P, "learning-theories", "M", 3,
      ["Open-ended questions in class mainly encourage pupils to:", ["Guess the teacher's mood", "Repeat a memorised line", "Stay silent", "Think, explain and give their own ideas"], "Open-ended questions have more than one possible answer."],
      ["कक्षा में खुले प्रश्न मुख्यतः विद्यार्थियों को किसके लिए प्रेरित करते हैं?", ["शिक्षक का मिज़ाज भाँपने के लिए", "याद की हुई पंक्ति दोहराने के लिए", "चुप रहने के लिए", "सोचने, समझाने और अपने विचार देने के लिए"], "खुले प्रश्नों के एक से अधिक संभावित उत्तर होते हैं।"]),
    q(0, P, "learning-theories", "E", 1,
      ["Which of these belongs to the co-scholastic areas of assessment?", ["Unit test in mathematics", "Participation in art and sports", "Dictation in Hindi", "Written test in science"], "Co-scholastic areas include arts, sports, life skills and attitudes."],
      ["मूल्यांकन के सह-शैक्षिक क्षेत्रों में इनमें से क्या आता है?", ["गणित की इकाई परीक्षा", "कला और खेलों में सहभागिता", "हिंदी का श्रुतलेख", "विज्ञान की लिखित परीक्षा"], "सह-शैक्षिक क्षेत्रों में कला, खेल, जीवन-कौशल और अभिवृत्तियाँ शामिल हैं।"]),
  ],
  [
    q(0, P, "inclusive-education", "H", 2,
      ["The Salamanca Statement (1994), which called on governments to adopt inclusive education, was adopted at a conference organised by:", ["WHO", "UNICEF only", "UNESCO", "World Bank"], "UNESCO and Spain hosted the Salamanca conference on special needs education."],
      ["सलामांका वक्तव्य (1994), जिसने सरकारों से समावेशी शिक्षा अपनाने का आग्रह किया, किसके द्वारा आयोजित सम्मेलन में अपनाया गया?", ["डब्ल्यूएचओ", "केवल यूनिसेफ़", "यूनेस्को", "विश्व बैंक"], "यूनेस्को और स्पेन ने विशेष आवश्यकता शिक्षा पर सलामांका सम्मेलन का आयोजन किया।"]),
    q(0, P, "inclusive-education", "H", 0,
      ["The Integrated Education for Disabled Children (IEDC) scheme in India was launched in:", ["1974", "1986", "2001", "2010"], "The IEDC scheme began in 1974 to place disabled children in ordinary schools."],
      ["भारत में दिव्यांग बच्चों के लिए एकीकृत शिक्षा (आईईडीसी) योजना कब शुरू हुई?", ["1974", "1986", "2001", "2010"], "आईईडीसी योजना 1974 में दिव्यांग बच्चों को सामान्य विद्यालयों में रखने के लिए शुरू हुई।"]),
    q(0, P, "inclusive-education", "M", 3,
      ["Samagra Shiksha (2018) brought together which schemes into one?", ["Only mid-day meal", "NCC and NSS", "Only the RTE Act", "Sarva Shiksha Abhiyan, RMSA and teacher education"], "It merged SSA, RMSA and the centrally sponsored teacher-education scheme."],
      ["समग्र शिक्षा (2018) ने किन योजनाओं को एक में मिलाया?", ["केवल मध्याह्न भोजन", "एनसीसी और एनएसएस", "केवल आरटीई अधिनियम", "सर्व शिक्षा अभियान, रमसा और शिक्षक शिक्षा"], "इसने एसएसए, रमसा और शिक्षक-शिक्षा की केंद्र प्रायोजित योजना को मिलाया।"]),
    q(0, P, "inclusive-education", "M", 1,
      ["The Sarva Shiksha Abhiyan, aimed at universal elementary education, was launched in:", ["1995", "2001", "2009", "2015"], "SSA began in 2001."],
      ["सार्वभौमिक प्रारंभिक शिक्षा के लक्ष्य वाला सर्व शिक्षा अभियान कब शुरू हुआ?", ["1995", "2001", "2009", "2015"], "एसएसए 2001 में शुरू हुआ।"]),
    q(0, P, "inclusive-education", "M", 2,
      ["The Right of Children to Free and Compulsory Education Act came into force on:", ["26 January 2002", "15 August 2009", "1 April 2010", "5 September 2011"], "The RTE Act became operational on 1 April 2010."],
      ["बच्चों का निःशुल्क एवं अनिवार्य शिक्षा का अधिकार अधिनियम किस तिथि को लागू हुआ?", ["26 जनवरी 2002", "15 अगस्त 2009", "1 अप्रैल 2010", "5 सितंबर 2011"], "आरटीई अधिनियम 1 अप्रैल 2010 से प्रभावी हुआ।"]),
    q(0, P, "inclusive-education", "H", 3,
      ["Under the RTE Act every school must form a School Management Committee in which a majority of members are:", ["Government officers", "Teachers", "Local politicians", "Parents or guardians of pupils"], "At least three-fourths of SMC members are parents or guardians."],
      ["आरटीई अधिनियम के अंतर्गत प्रत्येक विद्यालय को विद्यालय प्रबंधन समिति बनानी होती है, जिसमें अधिकांश सदस्य कौन होते हैं?", ["सरकारी अधिकारी", "शिक्षक", "स्थानीय राजनेता", "विद्यार्थियों के अभिभावक"], "एसएमसी के कम से कम तीन-चौथाई सदस्य अभिभावक होते हैं।"]),
    q(0, P, "inclusive-education", "H", 1,
      ["The RTE Act's norm for the pupil-teacher ratio in primary classes (I–V) is:", ["20 : 1", "30 : 1", "40 : 1", "50 : 1"], "The schedule of the Act fixes 30:1 at the primary stage."],
      ["आरटीई अधिनियम में प्राथमिक कक्षाओं (I–V) के लिए विद्यार्थी-शिक्षक अनुपात का मानक है:", ["20 : 1", "30 : 1", "40 : 1", "50 : 1"], "अधिनियम की अनुसूची प्राथमिक स्तर पर 30:1 तय करती है।"]),
    q(0, P, "inclusive-education", "M", 0,
      ["A child with a specific learning disability should be helped in class mainly by:", ["Adapting teaching methods and giving extra time", "Labelling her lazy", "Excluding her from tests", "Seating her alone"], "Accommodations and patient teaching help such children succeed."],
      ["विशिष्ट अधिगम अक्षमता वाले बच्चे की कक्षा में मुख्यतः किससे सहायता की जानी चाहिए?", ["शिक्षण-विधियों में बदलाव और अतिरिक्त समय देकर", "उसे आलसी कहकर", "उसे परीक्षाओं से बाहर रखकर", "उसे अकेले बिठाकर"], "सुविधाजनक व्यवस्थाएँ और धैर्यपूर्ण शिक्षण ऐसे बच्चों को सफल होने में मदद करते हैं।"]),
    q(0, P, "inclusive-education", "M", 2,
      ["Which approach is best for a very active pupil who cannot sit still for long?", ["Scold her in front of the class", "Tie her to the bench", "Give her short, active tasks and positive reinforcement", "Send her out every day"], "Channelling energy into purposeful tasks works better than punishment."],
      ["बहुत सक्रिय उस विद्यार्थी के लिए जो देर तक स्थिर नहीं बैठ पाती, कौन-सा उपागम सबसे अच्छा है?", ["कक्षा के सामने डाँटना", "बेंच से बाँध देना", "छोटे, सक्रिय कार्य और सकारात्मक पुनर्बलन देना", "रोज़ बाहर भेज देना"], "ऊर्जा को सार्थक कार्यों में लगाना दंड से बेहतर काम करता है।"]),
    q(0, P, "child-development", "M", 0,
      ["A teacher notices bruises on a pupil that the pupil is afraid to explain. The most appropriate step is to:", ["Report the concern to the proper authority and support the child", "Ignore it", "Publicly question the child", "Punish the child for lying"], "Teachers have a duty to protect children and report suspected abuse."],
      ["शिक्षक देखता है कि एक विद्यार्थी के शरीर पर चोट के निशान हैं जिनके बारे में वह बताने से डरता है। सबसे उपयुक्त कदम क्या है?", ["संबंधित प्राधिकारी को सूचित करना और बच्चे को सहारा देना", "इसे अनदेखा करना", "बच्चे से सबके सामने पूछताछ करना", "झूठ बोलने पर बच्चे को दंडित करना"], "शिक्षकों का कर्तव्य है कि वे बच्चों की रक्षा करें और संदिग्ध दुर्व्यवहार की सूचना दें।"]),
    q(0, P, "inclusive-education", "H", 2,
      ["Which section of the RTE Act prohibits physical punishment and mental harassment of children?", ["Section 3", "Section 8", "Section 17", "Section 29"], "Section 17 bars physical punishment and mental harassment."],
      ["आरटीई अधिनियम की कौन-सी धारा बच्चों को शारीरिक दंड और मानसिक उत्पीड़न देने पर रोक लगाती है?", ["धारा 3", "धारा 8", "धारा 17", "धारा 29"], "धारा 17 शारीरिक दंड और मानसिक उत्पीड़न का निषेध करती है।"]),
    q(0, P, "child-development", "M", 3,
      ["The main purpose of counselling a pupil is to:", ["Tell her what to do at every step", "Punish her for mistakes", "Report her to the principal", "Help her understand herself and solve her problem on her own"], "Counselling is a helping relationship that builds the pupil's own problem-solving."],
      ["विद्यार्थी को परामर्श देने का मुख्य उद्देश्य है:", ["हर कदम पर उसे बताना कि क्या करना है", "गलतियों पर दंड देना", "उसकी शिकायत प्राचार्य से करना", "उसे स्वयं को समझने और अपनी समस्या स्वयं सुलझाने में मदद करना"], "परामर्श एक सहायक संबंध है जो विद्यार्थी की स्वयं समस्या सुलझाने की क्षमता बढ़ाता है।"]),
    q(0, P, "child-development", "M", 1,
      ["A teacher finds one pupil being bullied by classmates. She should first:", ["Tell the victim to ignore it for ever", "Stop the bullying, support the victim and talk to those involved", "Give the whole class a holiday", "Do nothing, hoping it ends"], "Immediate action and follow-up protect the child and change behaviour."],
      ["शिक्षक देखता है कि एक विद्यार्थी को सहपाठी परेशान कर रहे हैं। उसे सबसे पहले क्या करना चाहिए?", ["पीड़ित को हमेशा अनदेखा करने को कहना", "उत्पीड़न रोकना, पीड़ित को सहारा देना और शामिल बच्चों से बात करना", "पूरी कक्षा को छुट्टी दे देना", "कुछ न करना और आशा रखना कि यह अपने आप रुक जाएगा"], "तुरंत कार्रवाई और अनुवर्तन बच्चे की रक्षा करते हैं और व्यवहार बदलते हैं।"]),
    q(0, P, "inclusive-education", "M", 2,
      ["A multisensory approach (seeing, hearing, tracing and touching letters) is a well-known remedy for:", ["Hearing loss", "Gifted learners", "Dyslexia", "Obesity"], "Multisensory teaching strengthens reading for dyslexic learners."],
      ["बहु-संवेदी उपागम (अक्षरों को देखना, सुनना, उकेरना और छूना) किसके लिए प्रसिद्ध उपचार है?", ["श्रवण-हानि", "प्रतिभाशाली शिक्षार्थी", "डिस्लेक्सिया", "मोटापा"], "बहु-संवेदी शिक्षण डिस्लेक्सिया वाले शिक्षार्थियों का पठन मज़बूत करता है।"]),
    q(0, P, "inclusive-education", "H", 3,
      ["Moving a gifted child to a higher class than her age group is called:", ["Detention", "Remediation", "Segregation", "Acceleration"], "Acceleration advances a gifted pupil faster through the curriculum."],
      ["किसी प्रतिभाशाली बच्चे को उसकी आयु-वर्ग से ऊँची कक्षा में भेजना क्या कहलाता है?", ["रोक-थाम", "उपचार", "पृथक्करण", "त्वरण"], "त्वरण प्रतिभाशाली विद्यार्थी को पाठ्यचर्या में तेज़ी से आगे बढ़ाता है।"]),
    q(0, P, "learning-theories", "M", 0,
      ["Which classroom practice most helps to foster creativity?", ["Allowing different ways to answer and welcoming new ideas", "Insisting on one correct method only", "Punishing mistakes", "Giving only copied work"], "Freedom to try varied approaches nurtures creativity."],
      ["सृजनात्मकता को बढ़ावा देने में कक्षा का कौन-सा अभ्यास सबसे अधिक सहायक है?", ["उत्तर देने के अलग-अलग तरीकों की छूट और नए विचारों का स्वागत", "केवल एक सही विधि पर अड़े रहना", "गलतियों पर दंड देना", "केवल नक़ल का काम देना"], "विभिन्न तरीके आज़माने की स्वतंत्रता सृजनात्मकता को पोषित करती है।"]),
    q(0, P, "child-development", "M", 2,
      ["To reduce test anxiety in pupils, a teacher should:", ["Warn them about failure", "Compare them with toppers", "Create a calm atmosphere and teach exam-taking strategies", "Hold surprise tests daily"], "Reassurance and preparation lower anxiety."],
      ["विद्यार्थियों की परीक्षा-चिंता घटाने के लिए शिक्षक को क्या करना चाहिए?", ["असफलता की चेतावनी देना", "उनकी अव्वल बच्चों से तुलना करना", "शांत वातावरण बनाना और परीक्षा देने की युक्तियाँ सिखाना", "रोज़ अचानक परीक्षाएँ लेना"], "आश्वासन और तैयारी चिंता घटाते हैं।"]),
    q(0, P, "child-development", "M", 1,
      ["Which approach best helps an adolescent who is struggling with peer pressure?", ["Harsh scolding", "Open, respectful guidance that builds decision-making skills", "Isolation at home", "Ignoring the problem"], "Adolescents benefit from supportive dialogue and life-skills training."],
      ["साथियों के दबाव से जूझ रहे किशोर की सबसे अधिक मदद कौन-सा उपागम करता है?", ["कठोर डाँट", "निर्णय-क्षमता बढ़ाने वाला खुला, सम्मानपूर्ण मार्गदर्शन", "घर में अलग-थलग रखना", "समस्या की अनदेखी"], "किशोरों को सहयोगी संवाद और जीवन-कौशल प्रशिक्षण से लाभ होता है।"]),
    q(0, P, "learning-theories", "M", 3,
      ["Which method is considered most effective for teaching moral values to children?", ["Long sermons only", "Strict punishment", "Memorising slogans", "Setting examples and discussing real-life situations"], "Children learn values chiefly by watching adults and thinking through situations."],
      ["बच्चों को नैतिक मूल्य सिखाने की सबसे प्रभावी विधि कौन-सी मानी जाती है?", ["केवल लंबे उपदेश", "कड़ा दंड", "नारे रटवाना", "उदाहरण प्रस्तुत करना और वास्तविक जीवन की परिस्थितियों पर चर्चा"], "बच्चे मूल्यों को मुख्यतः बड़ों को देखकर और परिस्थितियों पर सोचकर सीखते हैं।"]),
    q(0, P, "learning-theories", "H", 0,
      ["In a classroom with many home languages, the best view for a teacher is to treat multilingualism as:", ["A resource for learning", "A problem to be removed", "A reason to lower marks", "A reason to separate pupils"], "NCF 2005 treats the home languages of children as a resource."],
      ["अनेक घरेलू भाषाओं वाली कक्षा में शिक्षक के लिए बहुभाषिकता को किस रूप में देखना सर्वोत्तम है?", ["अधिगम के संसाधन के रूप में", "हटाई जाने योग्य समस्या के रूप में", "अंक घटाने के कारण के रूप में", "विद्यार्थियों को अलग करने के कारण के रूप में"], "एनसीएफ 2005 बच्चों की घरेलू भाषाओं को संसाधन मानती है।"]),
    q(0, P, "learning-theories", "M", 2,
      ["According to NCF 2005, language learning is best when the child:", ["Writes only copied lines", "Learns grammar rules first", "Uses language meaningfully in listening, speaking, reading and writing", "Stays silent"], "NCF 2005 favours meaningful, activity-based language use."],
      ["एनसीएफ 2005 के अनुसार भाषा-शिक्षण तब सर्वोत्तम होता है जब बच्चा:", ["केवल नक़ल की पंक्तियाँ लिखे", "पहले व्याकरण के नियम सीखे", "सुनने, बोलने, पढ़ने और लिखने में भाषा का सार्थक प्रयोग करे", "चुप रहे"], "एनसीएफ 2005 सार्थक, गतिविधि-आधारित भाषा-प्रयोग का पक्ष लेती है।"]),
    q(0, P, "learning-theories", "H", 1,
      ["Values and attitudes picked up unintentionally in school, such as respect for authority or gender roles, make up the:", ["Co-curricular programme", "Hidden curriculum", "Written syllabus", "Examination scheme"], "The hidden curriculum is learning that happens outside the formal syllabus."],
      ["विद्यालय में अनजाने में सीखे गए मूल्य और अभिवृत्तियाँ, जैसे सत्ता का सम्मान या लैंगिक भूमिकाएँ, क्या कहलाती हैं?", ["सह-पाठ्यचर्या कार्यक्रम", "छिपी हुई पाठ्यचर्या", "लिखित पाठ्यक्रम", "परीक्षा योजना"], "छिपी हुई पाठ्यचर्या औपचारिक पाठ्यक्रम से बाहर होने वाला अधिगम है।"]),
    q(0, P, "learning-theories", "M", 3,
      ["The mid-day meal scheme was launched nationwide in 1995 mainly to:", ["Raise teachers' salaries", "Reduce school holidays", "Replace textbooks", "Improve enrolment, attendance and nutrition"], "The scheme aimed at both education and nutrition."],
      ["मध्याह्न भोजन योजना 1995 में पूरे देश में मुख्यतः किसलिए शुरू की गई?", ["शिक्षकों का वेतन बढ़ाने के लिए", "विद्यालय की छुट्टियाँ घटाने के लिए", "पाठ्यपुस्तकें बदलने के लिए", "नामांकन, उपस्थिति और पोषण सुधारने के लिए"], "योजना का लक्ष्य शिक्षा और पोषण दोनों था।"]),
    q(0, P, "learning-theories", "M", 0,
      ["A teacher plans a lesson by first finding out what pupils already know. This respects the idea that learners:", ["Bring prior knowledge to every new topic", "Start from nothing", "Learn only by memorising", "Do not differ from each other"], "Constructivism builds new knowledge on existing knowledge."],
      ["शिक्षक पाठ की योजना पहले यह जानकर बनाता है कि विद्यार्थी पहले से क्या जानते हैं। यह किस विचार का सम्मान है?", ["शिक्षार्थी हर नए विषय में पूर्व ज्ञान लाते हैं", "शिक्षार्थी शून्य से शुरू करते हैं", "शिक्षार्थी केवल रटकर सीखते हैं", "शिक्षार्थी एक-दूसरे से भिन्न नहीं होते"], "रचनावाद नए ज्ञान को मौजूदा ज्ञान पर खड़ा करता है।"]),
    q(0, P, "learning-theories", "M", 1,
      ["Diagnostic assessment followed by remedial teaching is most useful for:", ["Ranking schools", "Helping pupils overcome specific learning gaps", "Awarding trophies", "Reducing syllabus"], "Diagnosis finds the gap and remediation closes it."],
      ["निदानात्मक आकलन के बाद उपचारात्मक शिक्षण सबसे अधिक किसके लिए उपयोगी है?", ["विद्यालयों को क्रम देने के लिए", "विद्यार्थियों को विशिष्ट अधिगम-अंतराल दूर करने में मदद के लिए", "ट्रॉफ़ी देने के लिए", "पाठ्यक्रम घटाने के लिए"], "निदान से अंतराल पता चलता है और उपचार उसे भरता है।"]),
  ],
];
