// PGIMER Nursing Officer — Full Mock 2, written fresh: Fundamentals & Anatomy 20, Medical-Surgical & Pharmacology 30,
// Child Health & Obstetrics 20, Community, Mental Health & Management 15, General Knowledge 15.

import { q, type PatwariQuestion } from "../patwari/types";

const N = "nursing";

export const pgimerMock2: PatwariQuestion[] = [
  // ───────── Section 0: Fundamentals of Nursing, Anatomy & Physiology (20) ─────────
  q(0, N, "fundamentals", "M", 2,
    ["The Sims' (left lateral semi-prone) position is used mainly for:", ["Lumbar puncture in infants", "Feeding an unconscious patient", "Giving an enema or rectal examination", "Postural drainage of the upper lobes"], "Lying on the left side follows the shape of the rectum and sigmoid colon, so enemas flow in easily."],
    ["सिम्स (बाईं करवट अर्ध-औंधी) स्थिति मुख्य रूप से किसके लिए प्रयोग होती है?", ["शिशुओं में लंबर पंक्चर", "बेहोश रोगी को भोजन देना", "एनिमा देना या मलाशय परीक्षण", "ऊपरी लोब का पोस्चरल ड्रेनेज"], "बाईं करवट लेटने से मलाशय और सिग्मॉइड कोलन की दिशा के अनुसार एनिमा आसानी से अंदर जाता है।"]),
  q(0, N, "fundamentals", "M", 0,
    ["The lithotomy position is commonly used for:", ["Vaginal examination and delivery", "Chest X-ray", "Shock", "Spinal surgery"], "The patient lies on the back with hips and knees flexed and legs supported in stirrups."],
    ["लिथोटॉमी स्थिति सामान्यतः किसके लिए प्रयोग होती है?", ["योनि परीक्षण और प्रसव", "छाती का एक्स-रे", "शॉक", "रीढ़ की सर्जरी"], "रोगी पीठ के बल, कूल्हे और घुटने मोड़कर, पैर स्टिरप में टिकाकर लेटता है।"]),
  q(0, N, "fundamentals", "M", 3,
    ["An intramuscular injection is given with the needle at an angle of:", ["15°", "30°", "45°", "90°"], "IM injections go in at 90°; subcutaneous at 45–90° and intradermal at 10–15°."],
    ["इंट्रामस्कुलर इंजेक्शन सुई को किस कोण पर रखकर दिया जाता है?", ["15°", "30°", "45°", "90°"], "IM इंजेक्शन 90° पर; सबक्यूटेनियस 45–90° और इंट्राडर्मल 10–15° पर दिए जाते हैं।"]),
  q(0, N, "fundamentals", "M", 1,
    ["Tepid sponging is given to a patient mainly to:", ["Clean the skin before surgery", "Reduce a high body temperature", "Improve sleep", "Prevent bed sores"], "Evaporation of lukewarm water from the skin lowers body temperature in fever."],
    ["रोगी को गुनगुने पानी से स्पंजिंग (टेपिड स्पंजिंग) मुख्य रूप से किसलिए दी जाती है?", ["सर्जरी से पहले त्वचा साफ़ करने के लिए", "अधिक शारीरिक तापमान कम करने के लिए", "नींद सुधारने के लिए", "बेडसोर रोकने के लिए"], "त्वचा से गुनगुने पानी के वाष्पन से बुख़ार में शरीर का तापमान घटता है।"]),
  q(0, N, "fundamentals", "M", 2,
    ["Orthopnoea means difficulty in breathing that:", ["Occurs only during exercise", "Wakes the patient at night after 2–3 hours", "Occurs when lying flat and eases on sitting up", "Occurs at high altitude"], "Orthopnoea is breathlessness lying flat; waking breathless at night is paroxysmal nocturnal dyspnoea."],
    ["ऑर्थोप्निया का अर्थ है ऐसी साँस की तकलीफ़ जो:", ["केवल व्यायाम के दौरान हो", "रात में 2–3 घंटे बाद रोगी को जगा दे", "सीधा लेटने पर हो और बैठने पर कम हो", "ऊँचाई पर हो"], "ऑर्थोप्निया सीधा लेटने पर साँस फूलना है; रात में साँस फूलकर जागना पैरॉक्सिस्मल नॉक्टर्नल डिस्प्निया है।"]),
  q(0, N, "fundamentals", "H", 0,
    ["A nursing diagnosis differs from a medical diagnosis because it describes:", ["The patient's response to an actual or potential health problem", "The disease process and its cause", "The drugs the doctor has prescribed", "The results of laboratory tests"], "Nursing diagnoses (e.g. 'impaired skin integrity') address responses that nurses can treat independently."],
    ["नर्सिंग निदान चिकित्सा निदान से अलग है, क्योंकि यह वर्णन करता है:", ["किसी वास्तविक या संभावित स्वास्थ्य समस्या पर रोगी की प्रतिक्रिया का", "रोग प्रक्रिया और उसके कारण का", "डॉक्टर द्वारा लिखी दवाओं का", "प्रयोगशाला परीक्षणों के परिणामों का"], "नर्सिंग निदान (जैसे 'त्वचा अखंडता में कमी') उन प्रतिक्रियाओं से जुड़े हैं जिनका उपचार नर्स स्वतंत्र रूप से कर सकती है।"]),
  q(0, N, "fundamentals", "M", 1,
    ["In SOAP charting, the letter 'O' stands for:", ["Observation by the doctor", "Objective data", "Orders", "Outcome"], "SOAP = Subjective, Objective, Assessment, Plan."],
    ["SOAP चार्टिंग में 'O' अक्षर का अर्थ है:", ["डॉक्टर का अवलोकन", "वस्तुनिष्ठ (ऑब्जेक्टिव) आँकड़े", "आदेश", "परिणाम"], "SOAP = Subjective, Objective, Assessment, Plan।"]),
  q(0, N, "fundamentals", "H", 2,
    ["A pressure ulcer with full-thickness skin loss into the subcutaneous fat, but without exposed bone, tendon or muscle, is at:", ["Stage 1", "Stage 2", "Stage 3", "Stage 4"], "Stage 3 reaches the fat; stage 4 exposes bone, tendon or muscle."],
    ["जिस दबाव-घाव में त्वचा की पूरी मोटाई चमड़ी के नीचे की वसा तक नष्ट हो, पर हड्डी, कंडरा या मांसपेशी न दिखे, वह किस चरण में है?", ["चरण 1", "चरण 2", "चरण 3", "चरण 4"], "चरण 3 वसा तक पहुँचता है; चरण 4 में हड्डी, कंडरा या मांसपेशी दिखती है।"]),
  q(0, N, "fundamentals", "M", 3,
    ["The normal specific gravity of urine is:", ["0.900–0.950", "1.050–1.100", "1.200–1.300", "1.005–1.030"], "Urine specific gravity normally ranges from about 1.005 to 1.030."],
    ["मूत्र का सामान्य विशिष्ट गुरुत्व कितना होता है?", ["0.900–0.950", "1.050–1.100", "1.200–1.300", "1.005–1.030"], "मूत्र का विशिष्ट गुरुत्व सामान्यतः लगभग 1.005 से 1.030 तक होता है।"]),
  q(0, N, "fundamentals", "H", 1,
    ["Compared with the oral temperature, an axillary temperature reading is usually:", ["About 0.5 °C higher", "About 0.5 °C lower", "Exactly the same", "About 2 °C higher"], "Axillary readings run about 0.5 °C below oral; rectal readings run about 0.5 °C above."],
    ["मौखिक तापमान की तुलना में बगल (एक्सिलरी) का तापमान प्रायः कैसा होता है?", ["लगभग 0.5 °C अधिक", "लगभग 0.5 °C कम", "बिल्कुल समान", "लगभग 2 °C अधिक"], "बगल का तापमान मौखिक से लगभग 0.5 °C कम और मलाशय का लगभग 0.5 °C अधिक होता है।"]),
  q(0, N, "fundamentals", "H", 0,
    ["Immediately after a needle-stick injury, the nurse should first:", ["Wash the site with soap and running water without scrubbing", "Squeeze the wound hard to bleed it", "Apply bleach to the wound", "Suck the wound"], "Wash gently with soap and water, do not squeeze or use bleach, then report for post-exposure prophylaxis."],
    ["सुई चुभने की चोट के तुरंत बाद नर्स को सबसे पहले क्या करना चाहिए?", ["उस स्थान को बिना रगड़े साबुन और बहते पानी से धोना", "घाव को ज़ोर से दबाकर खून निकालना", "घाव पर ब्लीच लगाना", "घाव को चूसना"], "साबुन-पानी से धीरे धोएँ, न दबाएँ न ब्लीच लगाएँ, फिर पोस्ट-एक्सपोज़र प्रोफ़िलैक्सिस के लिए सूचना दें।"]),
  q(0, N, "fundamentals", "H", 3,
    ["Under Spaulding's classification, instruments that enter sterile tissue or the bloodstream (critical items) need:", ["Low-level disinfection", "Cleaning with soap only", "Intermediate-level disinfection", "Sterilisation"], "Critical items need sterilisation; semi-critical items need high-level disinfection; non-critical items low-level."],
    ["स्पॉल्डिंग वर्गीकरण के अनुसार निर्जीवाणु ऊतक या रक्त प्रवाह में जाने वाले उपकरणों (क्रिटिकल वस्तुओं) को क्या चाहिए?", ["निम्न-स्तरीय विसंक्रमण", "केवल साबुन से सफ़ाई", "मध्यम-स्तरीय विसंक्रमण", "निर्जीवीकरण (स्टेरिलाइज़ेशन)"], "क्रिटिकल वस्तुओं को स्टेरिलाइज़ेशन, सेमी-क्रिटिकल को उच्च-स्तरीय विसंक्रमण और नॉन-क्रिटिकल को निम्न-स्तरीय विसंक्रमण चाहिए।"]),
  q(0, N, "anatomy-physiology", "M", 2,
    ["Which hormone raises the blood calcium level?", ["Calcitonin", "Insulin", "Parathyroid hormone", "Thyroxine"], "Parathyroid hormone raises calcium by acting on bone, kidney and (via vitamin D) the gut; calcitonin lowers it."],
    ["कौन-सा हार्मोन रक्त में कैल्शियम का स्तर बढ़ाता है?", ["कैल्सिटोनिन", "इंसुलिन", "पैराथायरॉयड हार्मोन", "थायरॉक्सिन"], "पैराथायरॉयड हार्मोन हड्डी, गुर्दे और (विटामिन D द्वारा) आँत पर काम कर कैल्शियम बढ़ाता है; कैल्सिटोनिन घटाता है।"]),
  q(0, N, "anatomy-physiology", "M", 0,
    ["The total blood volume of an average adult is about:", ["5 litres", "2 litres", "8 litres", "10 litres"], "Blood is about 7–8% of body weight, roughly 5 litres in an adult."],
    ["एक औसत वयस्क में कुल रक्त की मात्रा लगभग कितनी होती है?", ["5 लीटर", "2 लीटर", "8 लीटर", "10 लीटर"], "रक्त शरीर के भार का लगभग 7–8% है, यानी वयस्क में लगभग 5 लीटर।"]),
  q(0, N, "anatomy-physiology", "M", 3,
    ["Which chamber of the heart has the thickest muscular wall?", ["Right atrium", "Left atrium", "Right ventricle", "Left ventricle"], "The left ventricle pumps blood into the whole systemic circulation, so its wall is thickest."],
    ["हृदय के किस कक्ष की मांसल दीवार सबसे मोटी होती है?", ["दायाँ आलिंद", "बायाँ आलिंद", "दायाँ निलय", "बायाँ निलय"], "बायाँ निलय पूरे शरीर के परिसंचरण में रक्त पंप करता है, इसलिए उसकी दीवार सबसे मोटी है।"]),
  q(0, N, "anatomy-physiology", "M", 1,
    ["The vagus nerve, which slows the heart, is which cranial nerve?", ["Seventh", "Tenth", "Fifth", "Twelfth"], "The vagus is cranial nerve X; VII is the facial and V the trigeminal nerve."],
    ["हृदय गति धीमी करने वाली वेगस तंत्रिका कौन-सी कपाल तंत्रिका है?", ["सातवीं", "दसवीं", "पाँचवीं", "बारहवीं"], "वेगस दसवीं (X) कपाल तंत्रिका है; VII फ़ेशियल और V ट्राइजेमिनल है।"]),
  q(0, N, "anatomy-physiology", "M", 2,
    ["The blood group known as the 'universal recipient' is:", ["O negative", "A positive", "AB positive", "B negative"], "AB positive has no anti-A, anti-B or anti-D antibodies, so it can receive red cells of any group."],
    ["'सार्वभौमिक ग्राही' (यूनिवर्सल रिसिपिएंट) रक्त समूह कौन-सा है?", ["O नेगेटिव", "A पॉज़िटिव", "AB पॉज़िटिव", "B नेगेटिव"], "AB पॉज़िटिव में एंटी-A, एंटी-B या एंटी-D एंटीबॉडी नहीं होतीं, अतः यह किसी भी समूह की लाल कोशिकाएँ ले सकता है।"]),
  q(0, N, "anatomy-physiology", "M", 0,
    ["The normal total white blood cell (leucocyte) count in adults is:", ["4,000–11,000 per mm³", "1,000–3,000 per mm³", "15,000–25,000 per mm³", "50,000–1,00,000 per mm³"], "Normal WBC count is 4,000–11,000/mm³; above is leucocytosis, below is leucopenia."],
    ["वयस्कों में सामान्य कुल श्वेत रक्त कोशिका (ल्यूकोसाइट) गणना कितनी है?", ["4,000–11,000 प्रति mm³", "1,000–3,000 प्रति mm³", "15,000–25,000 प्रति mm³", "50,000–1,00,000 प्रति mm³"], "सामान्य WBC 4,000–11,000/mm³ है; अधिक होना ल्यूकोसाइटोसिस और कम होना ल्यूकोपीनिया है।"]),
  q(0, N, "anatomy-physiology", "M", 3,
    ["The only movable bone of the skull is the:", ["Maxilla", "Occipital bone", "Temporal bone", "Mandible"], "The mandible (lower jaw) moves at the temporomandibular joint."],
    ["खोपड़ी की एकमात्र गतिशील हड्डी कौन-सी है?", ["मैक्सिला", "ऑक्सिपिटल हड्डी", "टेम्पोरल हड्डी", "मैंडिबल"], "मैंडिबल (निचला जबड़ा) टेम्पोरोमैंडिबुलर जोड़ पर हिलता है।"]),
  q(0, N, "anatomy-physiology", "H", 1,
    ["The normal glomerular filtration rate (GFR) of a healthy young adult is about:", ["25 mL/min", "125 mL/min", "500 mL/min", "1,200 mL/min"], "GFR is about 125 mL/min, or 180 litres a day; most of it is reabsorbed."],
    ["स्वस्थ युवा वयस्क की सामान्य ग्लोमेरुलर फ़िल्ट्रेशन दर (GFR) लगभग कितनी होती है?", ["25 mL/मिनट", "125 mL/मिनट", "500 mL/मिनट", "1,200 mL/मिनट"], "GFR लगभग 125 mL/मिनट, यानी 180 लीटर प्रतिदिन है; इसका अधिकांश पुनःअवशोषित हो जाता है।"]),

  // ───────── Section 1: Medical-Surgical Nursing & Pharmacology (30) ─────────
  q(1, N, "medical-surgical", "M", 0,
    ["Swelling of the feet, a raised jugular venous pressure and an enlarged liver point to:", ["Right-sided heart failure", "Left-sided heart failure", "Asthma", "Pulmonary embolism only"], "Right ventricular failure backs blood into the systemic veins, causing dependent oedema, raised JVP and hepatomegaly."],
    ["पैरों में सूजन, बढ़ा हुआ जुगुलर शिरा दाब और बढ़ा हुआ यकृत किसका संकेत है?", ["दाएँ हृदय की विफलता", "बाएँ हृदय की विफलता", "दमा", "केवल पल्मोनरी एम्बोलिज़्म"], "दाएँ निलय की विफलता रक्त को शरीर की शिराओं में पीछे धकेलती है, जिससे सूजन, बढ़ा JVP और यकृत वृद्धि होती है।"]),
  q(1, N, "medical-surgical", "M", 2,
    ["Which blood test is the most specific marker of damage to heart muscle?", ["Serum amylase", "ESR", "Cardiac troponin", "Serum albumin"], "Troponin I or T rises within hours of myocardial injury and stays raised for days."],
    ["हृदय की मांसपेशी की क्षति का सबसे विशिष्ट रक्त-चिह्नक कौन-सा है?", ["सीरम एमाइलेज़", "ESR", "कार्डियक ट्रोपोनिन", "सीरम एल्ब्यूमिन"], "ट्रोपोनिन I या T हृदय-क्षति के कुछ घंटों में बढ़ता है और कई दिन ऊँचा रहता है।"]),
  q(1, N, "medical-surgical", "H", 3,
    ["Thrombolytic therapy (e.g. streptokinase) for a heart attack must NOT be given to a patient with:", ["Chest pain for 2 hours", "Diabetes", "Age above 50", "A recent haemorrhagic stroke"], "Any past brain haemorrhage is an absolute contraindication because thrombolysis can cause fresh bleeding."],
    ["हृदयाघात में थ्रॉम्बोलिटिक उपचार (जैसे स्ट्रेप्टोकाइनेज़) किस रोगी को नहीं देना चाहिए?", ["2 घंटे से सीने में दर्द", "मधुमेह", "50 वर्ष से अधिक आयु", "हाल ही में रक्तस्रावी स्ट्रोक"], "मस्तिष्क में पहले हुआ रक्तस्राव पूर्ण निषेध है, क्योंकि थ्रॉम्बोलाइसिस से नया रक्तस्राव हो सकता है।"]),
  q(1, N, "medical-surgical", "H", 1,
    ["In an adult, oliguria means a urine output of less than:", ["1,000 mL in 24 hours", "400 mL in 24 hours", "100 mL in 24 hours", "1,500 mL in 24 hours"], "Oliguria is below 400 mL a day (or below 0.5 mL/kg/hour); below 100 mL a day is anuria."],
    ["वयस्क में ऑलिग्यूरिया का अर्थ है मूत्र मात्रा का किससे कम होना?", ["24 घंटे में 1,000 mL", "24 घंटे में 400 mL", "24 घंटे में 100 mL", "24 घंटे में 1,500 mL"], "ऑलिग्यूरिया प्रतिदिन 400 mL से कम (या 0.5 mL/kg/घंटा से कम) है; 100 mL से कम एन्यूरिया है।"]),
  q(1, N, "medical-surgical", "M", 2,
    ["For a patient with an arteriovenous fistula for haemodialysis, the nurse should:", ["Check the BP on the fistula arm daily", "Draw blood samples from the fistula", "Avoid BP measurement and needle pricks on the fistula arm", "Keep the arm tightly bandaged"], "Pressure or punctures on the fistula arm can clot or damage it; a thrill and bruit show it is working."],
    ["हीमोडायलिसिस के लिए आर्टेरियोवेनस फ़िस्टुला वाले रोगी के लिए नर्स को चाहिए:", ["फ़िस्टुला वाली बाँह पर रोज़ BP नापना", "फ़िस्टुला से रक्त नमूने लेना", "फ़िस्टुला वाली बाँह पर BP नापने और सुई चुभाने से बचना", "बाँह को कसकर पट्टी बाँधकर रखना"], "फ़िस्टुला वाली बाँह पर दबाव या छेद से उसमें थक्का या क्षति हो सकती है; थ्रिल और ब्रूइट बताते हैं कि वह ठीक काम कर रहा है।"]),
  q(1, N, "medical-surgical", "M", 0,
    ["Pernicious anaemia results from deficiency of:", ["Vitamin B12, due to lack of intrinsic factor", "Iron", "Vitamin C", "Folic acid only"], "Without intrinsic factor from the stomach, vitamin B12 cannot be absorbed in the ileum."],
    ["पर्निशियस एनीमिया किसकी कमी से होता है?", ["इंट्रिंसिक फ़ैक्टर न होने से विटामिन B12", "आयरन", "विटामिन C", "केवल फ़ोलिक एसिड"], "आमाशय के इंट्रिंसिक फ़ैक्टर के बिना इलियम में विटामिन B12 अवशोषित नहीं हो पाता।"]),
  q(1, N, "medical-surgical", "H", 3,
    ["Spoon-shaped, concave nails (koilonychia) are a sign of:", ["Heart failure", "Psoriasis only", "Liver failure", "Iron deficiency anaemia"], "Koilonychia is classically seen in long-standing iron deficiency."],
    ["चम्मच के आकार के अवतल नाख़ून (कॉइलोनिकिया) किसका चिह्न हैं?", ["हृदय विफलता", "केवल सोरायसिस", "यकृत विफलता", "आयरन की कमी से एनीमिया"], "कॉइलोनिकिया प्रायः लंबे समय से चल रही आयरन की कमी में दिखता है।"]),
  q(1, N, "medical-surgical", "M", 1,
    ["Hepatitis A is spread mainly through:", ["Blood transfusion", "Contaminated food and water (faeco-oral route)", "Sexual contact only", "Mosquito bites"], "Hepatitis A and E spread by the faeco-oral route; B, C and D spread through blood and body fluids."],
    ["हेपेटाइटिस A मुख्य रूप से कैसे फैलता है?", ["रक्त आधान से", "दूषित भोजन और पानी (मल-मुख मार्ग) से", "केवल यौन संपर्क से", "मच्छर के काटने से"], "हेपेटाइटिस A और E मल-मुख मार्ग से; B, C और D रक्त और शरीर-द्रवों से फैलते हैं।"]),
  q(1, N, "medical-surgical", "M", 2,
    ["Melaena means the passing of:", ["Fresh red blood with stool", "Pale clay-coloured stool", "Black, tarry stool", "Stool with mucus only"], "Melaena is black tarry stool from digested blood, usually an upper GI bleed."],
    ["मेलीना का अर्थ है किस प्रकार का मल निकलना?", ["मल के साथ ताज़ा लाल खून", "पीला मिट्टी के रंग का मल", "काला, तारकोल जैसा मल", "केवल बलगम वाला मल"], "मेलीना पचे हुए खून से काला तारकोल जैसा मल है, प्रायः ऊपरी पाचन मार्ग से रक्तस्राव में।"]),
  q(1, N, "medical-surgical", "H", 0,
    ["To prevent dumping syndrome after a gastrectomy, the patient should be advised to:", ["Eat small, frequent, low-carbohydrate meals and avoid drinking fluids with meals", "Eat three large meals a day", "Drink plenty of sweet fluids with every meal", "Walk briskly right after eating"], "Fluids and sugars with meals hurry food into the jejunum; lying down after meals also helps."],
    ["गैस्ट्रेक्टॉमी के बाद डंपिंग सिंड्रोम से बचने के लिए रोगी को क्या सलाह दी जानी चाहिए?", ["थोड़ा-थोड़ा, बार-बार, कम कार्बोहाइड्रेट वाला भोजन और भोजन के साथ तरल न लेना", "दिन में तीन बड़े भोजन", "हर भोजन के साथ ख़ूब मीठे पेय", "खाने के तुरंत बाद तेज़ चलना"], "भोजन के साथ तरल और शक्कर भोजन को तेज़ी से जेजुनम में धकेलते हैं; खाने के बाद लेटना भी मदद करता है।"]),
  q(1, N, "medical-surgical", "H", 2,
    ["Which ECG change is typical of hyperkalaemia?", ["Prominent U waves", "ST depression only", "Tall, peaked T waves", "A long QT interval only"], "Rising potassium gives tall tented T waves, then wide QRS and a risk of cardiac arrest; U waves suggest hypokalaemia."],
    ["हाइपरकैलीमिया का विशिष्ट ECG परिवर्तन कौन-सा है?", ["स्पष्ट U तरंगें", "केवल ST अवनमन", "ऊँची, नुकीली T तरंगें", "केवल लंबा QT अंतराल"], "पोटैशियम बढ़ने पर ऊँची नुकीली T तरंगें, फिर चौड़ा QRS और हृदय-गति रुकने का ख़तरा; U तरंगें हाइपोकैलीमिया बताती हैं।"]),
  q(1, N, "medical-surgical", "M", 1,
    ["Hyponatraemia is present when the serum sodium falls below:", ["145 mEq/L", "135 mEq/L", "120 mEq/L", "5 mEq/L"], "Normal sodium is 135–145 mEq/L."],
    ["सीरम सोडियम कितने से नीचे जाने पर हाइपोनेट्रीमिया होता है?", ["145 mEq/L", "135 mEq/L", "120 mEq/L", "5 mEq/L"], "सामान्य सोडियम 135–145 mEq/L है।"]),
  q(1, N, "medical-surgical", "M", 3,
    ["A round 'moon face', a 'buffalo hump' and purple abdominal striae are features of:", ["Addison's disease", "Hypothyroidism", "Acromegaly", "Cushing's syndrome"], "Excess cortisol (Cushing's) redistributes fat and thins the skin."],
    ["गोल 'मून फ़ेस', 'बफ़ेलो हंप' और पेट पर बैंगनी धारियाँ किसके लक्षण हैं?", ["एडिसन रोग", "हाइपोथायरॉयडिज़्म", "एक्रोमेगाली", "कुशिंग सिंड्रोम"], "अतिरिक्त कॉर्टिसोल (कुशिंग) वसा को पुनर्वितरित करता है और त्वचा पतली करता है।"]),
  q(1, N, "medical-surgical", "M", 0,
    ["Passing very large amounts of dilute urine because of a lack of antidiuretic hormone is called:", ["Diabetes insipidus", "Diabetes mellitus", "SIADH", "Nephrotic syndrome"], "In diabetes insipidus the kidney cannot concentrate urine; SIADH is the opposite, with too much ADH."],
    ["एंटीडाइयूरेटिक हार्मोन की कमी से बहुत अधिक पतला मूत्र निकलना क्या कहलाता है?", ["डायबिटीज़ इन्सिपिडस", "डायबिटीज़ मेलिटस", "SIADH", "नेफ़्रोटिक सिंड्रोम"], "डायबिटीज़ इन्सिपिडस में गुर्दा मूत्र गाढ़ा नहीं कर पाता; SIADH इसका उल्टा है, जिसमें ADH अधिक होता है।"]),
  q(1, N, "medical-surgical", "H", 1,
    ["Myasthenia gravis is caused by antibodies against:", ["Dopamine receptors", "Acetylcholine receptors at the neuromuscular junction", "Myelin of the spinal cord", "Insulin receptors"], "Blocked acetylcholine receptors cause muscle weakness that worsens with use, often with drooping eyelids."],
    ["मायस्थीनिया ग्रेविस किसके विरुद्ध बनी एंटीबॉडी से होता है?", ["डोपामिन रिसेप्टर", "तंत्रिका-मांसपेशी संधि पर एसिटाइलकोलीन रिसेप्टर", "मेरुरज्जु का माइलिन", "इंसुलिन रिसेप्टर"], "एसिटाइलकोलीन रिसेप्टर अवरुद्ध होने से मांसपेशियाँ प्रयोग के साथ कमज़ोर होती हैं, प्रायः पलकें झुक जाती हैं।"]),
  q(1, N, "medical-surgical", "M", 2,
    ["Parkinson's disease results from a deficiency of which neurotransmitter in the basal ganglia?", ["Serotonin", "Acetylcholine", "Dopamine", "GABA"], "Loss of dopamine-producing cells in the substantia nigra causes tremor, rigidity and slow movement."],
    ["पार्किंसन रोग बेसल गैंग्लिया में किस न्यूरोट्रांसमीटर की कमी से होता है?", ["सेरोटोनिन", "एसिटाइलकोलीन", "डोपामिन", "GABA"], "सब्सटैंशिया नाइग्रा की डोपामिन बनाने वाली कोशिकाओं के नष्ट होने से कंपन, अकड़न और धीमी गति होती है।"]),
  q(1, N, "medical-surgical", "M", 3,
    ["Pain and resistance when the knee is straightened with the hip flexed (Kernig's sign) suggests:", ["Sciatica", "Fractured femur", "Appendicitis", "Meningitis"], "Kernig's and Brudzinski's signs show meningeal irritation."],
    ["कूल्हा मोड़कर घुटना सीधा करने पर दर्द और प्रतिरोध (कर्निग चिह्न) किसका संकेत है?", ["साइटिका", "फ़ीमर का फ्रैक्चर", "एपेंडिसाइटिस", "मेनिन्जाइटिस"], "कर्निग और ब्रुडज़िंस्की चिह्न मस्तिष्कावरण की उत्तेजना दिखाते हैं।"]),
  q(1, N, "medical-surgical", "H", 0,
    ["The earliest and most important sign of compartment syndrome in a limb with a cast is:", ["Pain out of proportion to the injury, worse on passive stretching", "Absent pulse", "Pink warm toes", "Slight swelling that settles with elevation"], "Severe pain on passive stretch comes first; a lost pulse is a late sign."],
    ["प्लास्टर लगे अंग में कम्पार्टमेंट सिंड्रोम का सबसे पहला और महत्त्वपूर्ण चिह्न क्या है?", ["चोट के अनुपात से बहुत अधिक दर्द, जो निष्क्रिय खिंचाव पर बढ़े", "नाड़ी का न मिलना", "गुलाबी गर्म उँगलियाँ", "हल्की सूजन जो अंग ऊँचा करने पर घट जाए"], "निष्क्रिय खिंचाव पर तेज़ दर्द सबसे पहले आता है; नाड़ी का गायब होना देर से आने वाला चिह्न है।"]),
  q(1, N, "medical-surgical", "H", 2,
    ["Buck's extension traction applied to the leg is a form of:", ["Skeletal traction", "Halo traction", "Skin traction", "Cervical traction"], "Buck's traction pulls through tapes stuck to the skin; skeletal traction pulls through a pin in the bone."],
    ["पैर पर लगाया जाने वाला बक्स एक्सटेंशन ट्रैक्शन किस प्रकार का ट्रैक्शन है?", ["स्केलेटल ट्रैक्शन", "हेलो ट्रैक्शन", "स्किन ट्रैक्शन", "सर्वाइकल ट्रैक्शन"], "बक्स ट्रैक्शन त्वचा पर चिपकी पट्टियों से खिंचाव देता है; स्केलेटल ट्रैक्शन हड्डी में लगी पिन से।"]),
  q(1, N, "medical-surgical", "M", 1,
    ["Rheumatoid arthritis typically causes:", ["Pain in one large joint after exercise", "Symmetrical swelling of the small joints of the hands with morning stiffness over an hour", "Sudden severe pain in the big toe", "Joint pain only in the elderly spine"], "RA is a symmetrical inflammatory polyarthritis; a sudden painful big toe suggests gout."],
    ["रुमेटॉइड आर्थराइटिस में प्रायः क्या होता है?", ["व्यायाम के बाद एक बड़े जोड़ में दर्द", "हाथों के छोटे जोड़ों में दोनों ओर समान सूजन और एक घंटे से अधिक सुबह की अकड़न", "पैर के अँगूठे में अचानक तेज़ दर्द", "केवल बुज़ुर्गों की रीढ़ में दर्द"], "RA दोनों ओर समान सूजन वाला बहु-संधिशोथ है; अँगूठे में अचानक दर्द गाउट बताता है।"]),
  q(1, N, "medical-surgical", "M", 3,
    ["A cataract is an opacity of the:", ["Cornea", "Retina", "Vitreous humour", "Lens"], "A cataract clouds the lens; glaucoma is raised pressure inside the eye."],
    ["मोतियाबिंद (कैटरैक्ट) किसकी अपारदर्शिता है?", ["कॉर्निया", "रेटिना", "विट्रियस ह्यूमर", "लेंस"], "मोतियाबिंद लेंस को धुँधला करता है; ग्लूकोमा आँख के अंदर का दाब बढ़ना है।"]),
  q(1, N, "medical-surgical", "H", 0,
    ["By the Parkland formula for burns, half of the calculated 24-hour fluid is given in the first:", ["8 hours from the time of the burn", "2 hours", "16 hours", "24 hours"], "Fluid = 4 mL × weight (kg) × % TBSA burned; half in the first 8 hours from injury, the rest over the next 16."],
    ["जलने में पार्कलैंड सूत्र के अनुसार 24 घंटे के कुल द्रव का आधा भाग पहले कितने समय में दिया जाता है?", ["जलने के समय से पहले 8 घंटे", "2 घंटे", "16 घंटे", "24 घंटे"], "द्रव = 4 mL × भार (kg) × जला % TBSA; आधा चोट के बाद पहले 8 घंटे में, बाकी अगले 16 घंटे में।"]),
  q(1, N, "pharmacology", "M", 2,
    ["The specific antidote for a benzodiazepine (e.g. diazepam) overdose is:", ["Naloxone", "Atropine", "Flumazenil", "Neostigmine"], "Flumazenil blocks benzodiazepine receptors; naloxone reverses opioids."],
    ["बेंज़ोडायज़ेपिन (जैसे डायज़ेपाम) की अधिक मात्रा का विशिष्ट प्रतिकारक है:", ["नैलॉक्सोन", "एट्रोपिन", "फ़्लूमाज़ेनिल", "नियोस्टिग्मिन"], "फ़्लूमाज़ेनिल बेंज़ोडायज़ेपिन रिसेप्टर रोकता है; नैलॉक्सोन ओपिऑयड का असर पलटता है।"]),
  q(1, N, "pharmacology", "H", 1,
    ["The chelating agent used to treat acute iron poisoning in children is:", ["Penicillamine", "Desferrioxamine", "EDTA only", "N-acetylcysteine"], "Desferrioxamine binds free iron, which is then passed in the urine."],
    ["बच्चों में तीव्र आयरन विषाक्तता के उपचार में प्रयुक्त कीलेटिंग एजेंट है:", ["पेनिसिलामिन", "डेसफ़ेरिऑक्सामिन", "केवल EDTA", "N-एसिटाइलसिस्टीन"], "डेसफ़ेरिऑक्सामिन मुक्त आयरन से जुड़ता है जो फिर मूत्र में निकल जाता है।"]),
  q(1, N, "pharmacology", "H", 3,
    ["A woman on magnesium sulphate has absent knee jerks and slow breathing. The antidote kept ready is:", ["Sodium bicarbonate", "Potassium chloride", "Oxytocin", "Calcium gluconate"], "10 mL of 10% calcium gluconate IV reverses magnesium toxicity; knee jerks, breathing and urine output are checked before each dose."],
    ["मैग्नीशियम सल्फ़ेट ले रही महिला की घुटने की प्रतिवर्त क्रिया नहीं है और साँस धीमी है। तैयार रखा जाने वाला प्रतिकारक है:", ["सोडियम बाइकार्बोनेट", "पोटैशियम क्लोराइड", "ऑक्सीटोसिन", "कैल्शियम ग्लूकोनेट"], "10% कैल्शियम ग्लूकोनेट का 10 mL IV मैग्नीशियम विषाक्तता पलटता है; हर खुराक से पहले नी-जर्क, श्वसन और मूत्र मात्रा जाँचते हैं।"]),
  q(1, N, "pharmacology", "M", 0,
    ["NSAIDs such as ibuprofen are best taken:", ["After food, to reduce stomach irritation", "On an empty stomach for faster action", "Only at bedtime with alcohol", "With antacids containing aspirin"], "NSAIDs irritate the gastric mucosa and can cause ulcers; taking them after food reduces this."],
    ["इबुप्रोफ़ेन जैसे NSAIDs लेने का सबसे अच्छा तरीका है:", ["आमाशय की जलन कम करने के लिए भोजन के बाद", "तेज़ असर के लिए ख़ाली पेट", "केवल रात को शराब के साथ", "एस्पिरिन वाले एंटासिड के साथ"], "NSAIDs आमाशय की परत में जलन और अल्सर कर सकते हैं; भोजन के बाद लेने से यह कम होता है।"]),
  q(1, N, "pharmacology", "M", 2,
    ["The usual maximum daily dose of paracetamol for a healthy adult is:", ["500 mg", "1 g", "4 g", "10 g"], "Up to 4 g a day in divided doses; more risks liver damage, treated with N-acetylcysteine."],
    ["स्वस्थ वयस्क के लिए पैरासिटामोल की सामान्य अधिकतम दैनिक खुराक कितनी है?", ["500 mg", "1 g", "4 g", "10 g"], "विभाजित खुराकों में प्रतिदिन 4 g तक; इससे अधिक पर यकृत क्षति का ख़तरा है, जिसका उपचार N-एसिटाइलसिस्टीन से होता है।"]),
  q(1, N, "pharmacology", "H", 1,
    ["Which oral drug is commonly used to treat high blood pressure in pregnancy?", ["Enalapril", "Labetalol", "Losartan", "Spironolactone"], "Labetalol (or methyldopa or nifedipine) is safe in pregnancy; ACE inhibitors and ARBs harm the fetus."],
    ["गर्भावस्था में उच्च रक्तचाप के उपचार में आमतौर पर कौन-सी मुँह से ली जाने वाली दवा प्रयोग होती है?", ["एनालाप्रिल", "लेबेटालॉल", "लोसार्टन", "स्पाइरोनोलैक्टोन"], "लेबेटालॉल (या मिथाइलडोपा या निफ़ेडिपिन) गर्भावस्था में सुरक्षित है; ACE इनहिबिटर और ARB भ्रूण को हानि पहुँचाते हैं।"]),
  q(1, N, "pharmacology", "M", 3,
    ["The most common side effect of sublingual nitroglycerin given for angina is:", ["Constipation", "Weight gain", "Low blood sugar", "Headache"], "Nitrates dilate blood vessels, including those of the head, causing a throbbing headache and sometimes low BP."],
    ["एनजाइना में जीभ के नीचे दी जाने वाली नाइट्रोग्लिसरीन का सबसे सामान्य दुष्प्रभाव कौन-सा है?", ["कब्ज़", "वज़न बढ़ना", "कम रक्त शर्करा", "सिरदर्द"], "नाइट्रेट सिर सहित रक्त वाहिकाएँ फैलाते हैं, जिससे धड़कता सिरदर्द और कभी-कभी कम BP होता है।"]),
  q(1, N, "pharmacology", "M", 0,
    ["The effect of unfractionated heparin is monitored with which blood test?", ["Activated partial thromboplastin time (aPTT)", "Serum potassium", "Blood sugar", "Haemoglobin"], "aPTT monitors heparin; PT/INR monitors warfarin."],
    ["अनफ़्रैक्शनेटेड हेपरिन के प्रभाव की निगरानी किस रक्त परीक्षण से की जाती है?", ["एक्टिवेटेड पार्शियल थ्रॉम्बोप्लास्टिन टाइम (aPTT)", "सीरम पोटैशियम", "रक्त शर्करा", "हीमोग्लोबिन"], "aPTT से हेपरिन और PT/INR से वारफ़ेरिन की निगरानी होती है।"]),

  // ───────── Section 2: Child Health, Obstetrics & Midwifery (20) ─────────
  q(2, N, "child-health", "M", 2,
    ["The normal heart rate of a newborn baby at rest is:", ["60–80 per minute", "80–100 per minute", "120–160 per minute", "180–220 per minute"], "A newborn's heart beats about 120–160 times a minute."],
    ["विश्राम अवस्था में नवजात शिशु की सामान्य हृदय दर कितनी होती है?", ["60–80 प्रति मिनट", "80–100 प्रति मिनट", "120–160 प्रति मिनट", "180–220 प्रति मिनट"], "नवजात का हृदय लगभग 120–160 बार प्रति मिनट धड़कता है।"]),
  q(2, N, "child-health", "H", 0,
    ["The posterior fontanelle of an infant usually closes by:", ["6–8 weeks after birth", "6 months", "12 months", "18–24 months"], "The small triangular posterior fontanelle closes by 6–8 weeks; the anterior one by 12–18 months."],
    ["शिशु का पश्च फ़ॉन्टानेल (पोस्टीरियर फ़ॉन्टानेल) प्रायः कब तक बंद हो जाता है?", ["जन्म के 6–8 सप्ताह बाद", "6 महीने", "12 महीने", "18–24 महीने"], "छोटा त्रिकोणीय पश्च फ़ॉन्टानेल 6–8 सप्ताह में और अग्र फ़ॉन्टानेल 12–18 महीने में बंद होता है।"]),
  q(2, N, "child-health", "M", 1,
    ["Down syndrome is caused by an extra copy of which chromosome?", ["Chromosome 18", "Chromosome 21", "Chromosome 13", "The X chromosome"], "Trisomy 21 causes Down syndrome; trisomy 18 is Edwards and 13 is Patau syndrome."],
    ["डाउन सिंड्रोम किस गुणसूत्र की एक अतिरिक्त प्रति से होता है?", ["गुणसूत्र 18", "गुणसूत्र 21", "गुणसूत्र 13", "X गुणसूत्र"], "ट्राइसोमी 21 से डाउन सिंड्रोम होता है; ट्राइसोमी 18 एडवर्ड्स और 13 पटाउ सिंड्रोम है।"]),
  q(2, N, "child-health", "H", 3,
    ["Surgical repair of a cleft lip is usually done at about:", ["1 week of age", "5 years of age", "12 years of age", "3 months of age"], "By the 'rule of tens' (10 weeks, 10 lb, Hb 10 g/dL), cleft lip is repaired at about 3 months; cleft palate at 9–18 months."],
    ["कटे होंठ (क्लेफ़्ट लिप) की शल्य मरम्मत प्रायः लगभग किस आयु में की जाती है?", ["1 सप्ताह", "5 वर्ष", "12 वर्ष", "3 महीने"], "'दस का नियम' (10 सप्ताह, 10 पाउंड, Hb 10 g/dL) के अनुसार कटा होंठ लगभग 3 महीने पर और कटा तालु 9–18 महीने पर ठीक किया जाता है।"]),
  q(2, N, "child-health", "M", 0,
    ["Heavy proteinuria, low serum albumin, generalised oedema and high cholesterol in a child indicate:", ["Nephrotic syndrome", "Acute glomerulonephritis", "Urinary tract infection", "Wilms' tumour"], "These four features define nephrotic syndrome; glomerulonephritis presents with blood in urine and hypertension."],
    ["बच्चे में अधिक प्रोटीनयूरिया, कम सीरम एल्ब्यूमिन, पूरे शरीर में सूजन और अधिक कोलेस्ट्रॉल किसका संकेत है?", ["नेफ़्रोटिक सिंड्रोम", "तीव्र ग्लोमेरुलोनेफ़्राइटिस", "मूत्र मार्ग संक्रमण", "विल्म्स ट्यूमर"], "ये चार लक्षण नेफ़्रोटिक सिंड्रोम बताते हैं; ग्लोमेरुलोनेफ़्राइटिस में मूत्र में खून और उच्च रक्तचाप होता है।"]),
  q(2, N, "child-health", "M", 2,
    ["Rheumatic fever follows a throat infection caused by:", ["Staphylococcus aureus", "Haemophilus influenzae", "Group A beta-haemolytic streptococcus", "The measles virus"], "An immune reaction 2–4 weeks after a group A streptococcal sore throat causes rheumatic fever."],
    ["रूमेटिक बुख़ार किस जीवाणु से हुए गले के संक्रमण के बाद होता है?", ["स्टैफ़िलोकोकस ऑरियस", "हीमोफ़िलस इन्फ़्लुएंज़ी", "ग्रुप A बीटा-हीमोलिटिक स्ट्रेप्टोकोकस", "खसरा विषाणु"], "ग्रुप A स्ट्रेप्टोकोकल गले की ख़राश के 2–4 सप्ताह बाद प्रतिरक्षा प्रतिक्रिया से रूमेटिक बुख़ार होता है।"]),
  q(2, N, "child-health", "M", 1,
    ["A baby's first milk teeth usually begin to erupt at about:", ["1 month", "6 months", "12 months", "18 months"], "The lower central incisors usually appear at about 6 months."],
    ["शिशु के पहले दूध के दाँत प्रायः लगभग कब निकलने लगते हैं?", ["1 महीना", "6 महीने", "12 महीने", "18 महीने"], "निचले मध्य कृंतक दाँत प्रायः लगभग 6 महीने में निकलते हैं।"]),
  q(2, N, "child-health", "H", 3,
    ["Under IMNCI, fast breathing in a child aged 2 to 12 months means a respiratory rate of:", ["30 per minute or more", "40 per minute or more", "60 per minute or more", "50 per minute or more"], "Cut-offs are 60/min under 2 months, 50/min at 2–12 months and 40/min at 1–5 years."],
    ["IMNCI के अनुसार 2 से 12 महीने के बच्चे में तेज़ साँस का अर्थ है श्वसन दर:", ["30 प्रति मिनट या अधिक", "40 प्रति मिनट या अधिक", "60 प्रति मिनट या अधिक", "50 प्रति मिनट या अधिक"], "सीमाएँ हैं: 2 महीने से कम में 60/मिनट, 2–12 महीने में 50/मिनट और 1–5 वर्ष में 40/मिनट।"]),
  q(2, N, "child-health", "M", 2,
    ["For a child with acute diarrhoea, zinc supplements are given along with ORS for:", ["3 days", "7 days", "14 days", "30 days"], "Zinc is given for 14 days (10 mg/day under 6 months, 20 mg/day above); it shortens the episode and prevents recurrence."],
    ["तीव्र दस्त वाले बच्चे को ORS के साथ ज़िंक कितने दिन दिया जाता है?", ["3 दिन", "7 दिन", "14 दिन", "30 दिन"], "ज़िंक 14 दिन दिया जाता है (6 महीने से कम में 10 mg/दिन, अधिक में 20 mg/दिन); यह दस्त की अवधि घटाता और दोबारा होने से रोकता है।"]),
  q(2, N, "child-health", "M", 0,
    ["Wilms' tumour (nephroblastoma) in children arises from the:", ["Kidney", "Adrenal gland", "Liver", "Brain"], "Wilms' tumour is a kidney cancer, usually found as a painless abdominal mass in a young child."],
    ["बच्चों में विल्म्स ट्यूमर (नेफ़्रोब्लास्टोमा) किस अंग से उत्पन्न होता है?", ["गुर्दा", "एड्रिनल ग्रंथि", "यकृत", "मस्तिष्क"], "विल्म्स ट्यूमर गुर्दे का कैंसर है, जो प्रायः छोटे बच्चे में पेट की दर्दरहित गाँठ के रूप में मिलता है।"]),
  q(2, N, "midwifery", "M", 3,
    ["Fertilisation of the ovum normally takes place in the:", ["Uterine cavity", "Ovary", "Cervix", "Ampulla of the fallopian tube"], "The sperm meets the ovum in the ampulla; the embryo implants in the uterus about 6–7 days later."],
    ["अंडाणु का निषेचन सामान्यतः कहाँ होता है?", ["गर्भाशय गुहा", "अंडाशय", "गर्भाशय-ग्रीवा", "फ़ैलोपियन ट्यूब का एम्पुला भाग"], "शुक्राणु एम्पुला में अंडाणु से मिलता है; भ्रूण लगभग 6–7 दिन बाद गर्भाशय में स्थापित होता है।"]),
  q(2, N, "midwifery", "M", 1,
    ["Braxton Hicks contractions are:", ["Strong regular contractions that dilate the cervix", "Painless, irregular uterine contractions during pregnancy", "Contractions after delivery of the placenta", "Fetal movements"], "These 'false labour' contractions do not dilate the cervix."],
    ["ब्रैक्सटन हिक्स संकुचन क्या हैं?", ["गर्भाशय-ग्रीवा फैलाने वाले तेज़ नियमित संकुचन", "गर्भावस्था में दर्दरहित, अनियमित गर्भाशय संकुचन", "अपरा निकलने के बाद के संकुचन", "भ्रूण की गतियाँ"], "ये 'झूठे प्रसव' संकुचन गर्भाशय-ग्रीवा को नहीं फैलाते।"]),
  q(2, N, "midwifery", "M", 2,
    ["In a first pregnancy, the mother usually first feels fetal movements (quickening) at about:", ["8–10 weeks", "12–14 weeks", "18–20 weeks", "28–30 weeks"], "Primigravidas feel quickening at about 18–20 weeks; multigravidas about 2 weeks earlier."],
    ["पहली गर्भावस्था में माँ को भ्रूण की गति (क्विकनिंग) प्रायः पहली बार लगभग कब महसूस होती है?", ["8–10 सप्ताह", "12–14 सप्ताह", "18–20 सप्ताह", "28–30 सप्ताह"], "पहली बार गर्भवती को लगभग 18–20 सप्ताह में और बहुप्रसवा को लगभग 2 सप्ताह पहले गति महसूस होती है।"]),
  q(2, N, "midwifery", "M", 0,
    ["The third stage of labour ends with:", ["Expulsion of the placenta and membranes", "Full dilatation of the cervix", "Birth of the baby", "The first breastfeed"], "Stage 3 runs from the baby's birth to delivery of the placenta and membranes."],
    ["प्रसव का तीसरा चरण किसके साथ समाप्त होता है?", ["अपरा और झिल्लियों के बाहर निकलने के साथ", "गर्भाशय-ग्रीवा के पूर्ण फैलाव के साथ", "शिशु के जन्म के साथ", "पहले स्तनपान के साथ"], "तीसरा चरण शिशु के जन्म से अपरा और झिल्लियों के निकलने तक चलता है।"]),
  q(2, N, "midwifery", "M", 3,
    ["The type of episiotomy most commonly given in India is:", ["Midline", "J-shaped", "Lateral", "Mediolateral"], "A mediolateral cut is preferred because it is less likely to extend into the anal sphincter."],
    ["भारत में सबसे अधिक दिया जाने वाला एपिसियोटॉमी प्रकार कौन-सा है?", ["मिडलाइन", "J-आकार", "लेटरल", "मीडियोलेटरल"], "मीडियोलेटरल चीरा पसंद किया जाता है क्योंकि इसके गुदा स्फ़िंक्टर तक फटने की संभावना कम है।"]),
  q(2, N, "midwifery", "M", 1,
    ["Pre-eclampsia is new-onset hypertension after 20 weeks of pregnancy together with:", ["Low blood sugar", "Proteinuria or other organ involvement", "Fever", "Weight loss"], "BP ≥140/90 mmHg after 20 weeks with proteinuria (or organ dysfunction) is pre-eclampsia; with fits it becomes eclampsia."],
    ["प्री-एक्लेम्पसिया गर्भावस्था के 20 सप्ताह के बाद नया उच्च रक्तचाप और साथ में क्या है?", ["कम रक्त शर्करा", "प्रोटीनयूरिया या अन्य अंग की भागीदारी", "बुख़ार", "वज़न घटना"], "20 सप्ताह के बाद BP ≥140/90 mmHg और प्रोटीनयूरिया (या अंग विकार) प्री-एक्लेम्पसिया है; दौरे आने पर एक्लेम्पसिया।"]),
  q(2, N, "midwifery", "H", 2,
    ["Painful vaginal bleeding in late pregnancy with a tense, tender, 'woody hard' uterus suggests:", ["Placenta praevia", "Vasa praevia", "Abruptio placentae", "Cervical polyp"], "Placental abruption is painful with a hard uterus; placenta praevia bleeds painlessly with a soft uterus."],
    ["गर्भावस्था के अंतिम चरण में तने हुए, दर्दनाक, 'लकड़ी जैसे कड़े' गर्भाशय के साथ दर्दनाक योनि रक्तस्राव किसका संकेत है?", ["प्लेसेंटा प्रीविया", "वासा प्रीविया", "एब्रप्शियो प्लेसेंटी", "सर्वाइकल पॉलिप"], "अपरा का अलग होना (एब्रप्शन) दर्दनाक और कड़े गर्भाशय वाला है; प्लेसेंटा प्रीविया में नरम गर्भाशय के साथ दर्दरहित रक्तस्राव होता है।"]),
  q(2, N, "midwifery", "M", 3,
    ["Whitish-yellow lochia seen from about the 10th day after delivery is called:", ["Lochia rubra", "Lochia serosa", "Lochia nigra", "Lochia alba"], "Lochia rubra (days 1–4) is red, serosa (days 5–9) pinkish-brown and alba (day 10 onwards) whitish."],
    ["प्रसव के लगभग 10वें दिन से दिखने वाला सफ़ेद-पीला लोकिया क्या कहलाता है?", ["लोकिया रूब्रा", "लोकिया सीरोसा", "लोकिया नाइग्रा", "लोकिया एल्बा"], "लोकिया रूब्रा (1–4 दिन) लाल, सीरोसा (5–9 दिन) गुलाबी-भूरा और एल्बा (10वें दिन से) सफ़ेद होता है।"]),
  q(2, N, "midwifery", "M", 0,
    ["Colostrum, the first breast milk, is especially rich in:", ["Antibodies such as secretory IgA", "Fat", "Lactose", "Iron"], "Colostrum is rich in antibodies, protein and vitamin A, and is the baby's 'first immunisation'."],
    ["कोलोस्ट्रम, यानी पहला स्तन-दूध, विशेष रूप से किसमें समृद्ध होता है?", ["सीक्रेटरी IgA जैसी एंटीबॉडी", "वसा", "लैक्टोज़", "आयरन"], "कोलोस्ट्रम एंटीबॉडी, प्रोटीन और विटामिन A से भरपूर होता है और शिशु का 'पहला टीका' माना जाता है।"]),
  q(2, N, "midwifery", "H", 1,
    ["Under India's national guidelines, gestational diabetes is diagnosed when the plasma glucose 2 hours after 75 g oral glucose (taken without fasting) is:", ["100 mg/dL or more", "140 mg/dL or more", "180 mg/dL or more", "200 mg/dL or more"], "This single-step test (DIPSI) uses a 2-hour value of 140 mg/dL or more."],
    ["भारत के राष्ट्रीय दिशानिर्देशों के अनुसार 75 g ग्लूकोज़ (बिना उपवास) देने के 2 घंटे बाद प्लाज़्मा ग्लूकोज़ कितना होने पर गर्भकालीन मधुमेह का निदान होता है?", ["100 mg/dL या अधिक", "140 mg/dL या अधिक", "180 mg/dL या अधिक", "200 mg/dL या अधिक"], "इस एक-चरणीय परीक्षण (DIPSI) में 2 घंटे का मान 140 mg/dL या अधिक लिया जाता है।"]),

  // ───────── Section 3: Community Health, Mental Health & Nursing Management (15) ─────────
  q(3, N, "community-health", "M", 2,
    ["The protection of unvaccinated people when most of a community is immune is called:", ["Active immunity", "Passive immunity", "Herd immunity", "Innate immunity"], "When enough people are immune, the chain of transmission breaks and others are protected too."],
    ["जब समुदाय के अधिकांश लोग प्रतिरक्षित हों और इससे बिना टीके वाले लोग भी सुरक्षित रहें, तो इसे क्या कहते हैं?", ["सक्रिय प्रतिरक्षा", "निष्क्रिय प्रतिरक्षा", "हर्ड (सामूहिक) प्रतिरक्षा", "जन्मजात प्रतिरक्षा"], "पर्याप्त लोग प्रतिरक्षित हों तो संक्रमण की कड़ी टूट जाती है और बाकी भी सुरक्षित रहते हैं।"]),
  q(3, N, "community-health", "H", 0,
    ["Under India's national programme, multi-drug therapy for multibacillary leprosy in adults is given for:", ["12 months", "6 months", "2 years", "3 months"], "Multibacillary leprosy is treated for 12 months; paucibacillary for 6 months."],
    ["भारत के राष्ट्रीय कार्यक्रम में वयस्कों में मल्टीबैसिलरी कुष्ठ रोग की बहु-औषधि चिकित्सा कितने समय दी जाती है?", ["12 महीने", "6 महीने", "2 वर्ष", "3 महीने"], "मल्टीबैसिलरी कुष्ठ का उपचार 12 महीने और पॉसीबैसिलरी का 6 महीने चलता है।"]),
  q(3, N, "community-health", "M", 1,
    ["The crude birth rate is expressed as the number of live births per:", ["100 women", "1,000 mid-year population", "1,000 live births", "1 lakh population"], "Crude birth rate = live births in a year ÷ mid-year population × 1,000."],
    ["अपरिष्कृत जन्म दर को प्रति कितने के जीवित जन्मों में व्यक्त किया जाता है?", ["100 महिलाएँ", "1,000 मध्य-वर्ष जनसंख्या", "1,000 जीवित जन्म", "1 लाख जनसंख्या"], "अपरिष्कृत जन्म दर = वर्ष के जीवित जन्म ÷ मध्य-वर्ष जनसंख्या × 1,000।"]),
  q(3, N, "community-health", "M", 3,
    ["Kala-azar (visceral leishmaniasis) is transmitted by the:", ["Housefly", "Culex mosquito", "Tsetse fly", "Sandfly"], "The female Phlebotomus sandfly carries Leishmania donovani."],
    ["काला-अज़ार (विसरल लीशमैनियासिस) किसके द्वारा फैलता है?", ["घरेलू मक्खी", "क्यूलेक्स मच्छर", "सी-सी मक्खी", "सैंडफ़्लाई (बालू मक्खी)"], "मादा फ़्लेबोटोमस सैंडफ़्लाई लीशमैनिया डोनोवानी फैलाती है।"]),
  q(3, N, "community-health", "M", 2,
    ["Under the Universal Immunisation Programme, the rotavirus vaccine is given by which route?", ["Intramuscular", "Intradermal", "Oral", "Subcutaneous"], "Rotavirus vaccine is given as oral drops at 6, 10 and 14 weeks."],
    ["सार्वभौमिक टीकाकरण कार्यक्रम में रोटावायरस टीका किस मार्ग से दिया जाता है?", ["इंट्रामस्कुलर", "इंट्राडर्मल", "मुँह से (ओरल)", "सबक्यूटेनियस"], "रोटावायरस टीका 6, 10 और 14 सप्ताह पर मुँह में बूँदों के रूप में दिया जाता है।"]),
  q(3, N, "community-health", "H", 1,
    ["The sensitivity of a screening test is its ability to:", ["Correctly identify people who do not have the disease", "Correctly identify people who have the disease", "Give the same result when repeated", "Be done cheaply"], "Sensitivity finds true positives; specificity finds true negatives."],
    ["किसी स्क्रीनिंग परीक्षण की संवेदनशीलता (सेंसिटिविटी) उसकी किस क्षमता को कहते हैं?", ["जिन्हें रोग नहीं है उन्हें सही पहचानना", "जिन्हें रोग है उन्हें सही पहचानना", "दोहराने पर समान परिणाम देना", "सस्ते में हो जाना"], "संवेदनशीलता सही धनात्मक पहचानती है; विशिष्टता (स्पेसिफ़िसिटी) सही ऋणात्मक।"]),
  q(3, N, "community-health", "M", 0,
    ["In March 2014 the WHO certified India, as part of its South-East Asia region, free of:", ["Polio", "Smallpox", "Measles", "Tuberculosis"], "India's last wild polio case was in January 2011; the region was certified polio-free in March 2014."],
    ["मार्च 2014 में WHO ने दक्षिण-पूर्व एशिया क्षेत्र के भाग के रूप में भारत को किससे मुक्त प्रमाणित किया?", ["पोलियो", "चेचक", "खसरा", "क्षय रोग"], "भारत का अंतिम वाइल्ड पोलियो केस जनवरी 2011 में था; मार्च 2014 में क्षेत्र को पोलियो-मुक्त प्रमाणित किया गया।"]),
  q(3, N, "mental-health", "H", 3,
    ["A patient on haloperidol develops a shuffling gait, muscle rigidity and a pill-rolling tremor. These are:", ["Withdrawal symptoms", "Signs of an allergy", "Anticholinergic effects", "Extrapyramidal side effects"], "Typical antipsychotics block dopamine and cause parkinsonism, dystonia and akathisia (extrapyramidal effects)."],
    ["हैलोपेरिडॉल ले रहे रोगी में घिसटती चाल, मांसपेशियों की अकड़न और गोली घुमाने जैसा कंपन होने लगता है। ये क्या हैं?", ["विदड्रॉअल लक्षण", "एलर्जी के चिह्न", "एंटीकोलीनर्जिक प्रभाव", "एक्स्ट्रापिरामिडल दुष्प्रभाव"], "पुरानी एंटीसाइकोटिक दवाएँ डोपामिन रोकती हैं और पार्किंसनिज़्म, डिस्टोनिया और अकाथीसिया (एक्स्ट्रापिरामिडल प्रभाव) करती हैं।"]),
  q(3, N, "mental-health", "M", 1,
    ["Disulfiram is used in the treatment of:", ["Depression", "Alcohol dependence", "Schizophrenia", "Insomnia"], "Disulfiram causes an unpleasant reaction (flushing, vomiting) if alcohol is taken, deterring drinking."],
    ["डाइसल्फ़िराम किसके उपचार में प्रयोग होता है?", ["अवसाद", "शराब पर निर्भरता", "सिज़ोफ़्रेनिया", "अनिद्रा"], "डाइसल्फ़िराम लेने पर शराब पीने से अप्रिय प्रतिक्रिया (लाली, उल्टी) होती है, जो पीने से रोकती है।"]),
  q(3, N, "mental-health", "M", 2,
    ["A person who dislikes a colleague says, 'He hates me.' This defence mechanism is:", ["Denial", "Regression", "Projection", "Sublimation"], "Projection attributes one's own unacceptable feelings to someone else."],
    ["एक सहकर्मी को नापसंद करने वाला व्यक्ति कहता है, 'वह मुझसे नफ़रत करता है।' यह कौन-सी रक्षा युक्ति है?", ["इनकार (डिनायल)", "प्रतिगमन (रिग्रेशन)", "प्रक्षेपण (प्रोजेक्शन)", "उदात्तीकरण (सब्लिमेशन)"], "प्रक्षेपण में व्यक्ति अपनी अस्वीकार्य भावनाएँ किसी और पर आरोपित करता है।"]),
  q(3, N, "mental-health", "M", 0,
    ["The Mental Healthcare Act, which decriminalised attempted suicide in most cases, was passed by Parliament in:", ["2017", "1987", "2005", "2012"], "The Mental Healthcare Act, 2017 replaced the Mental Health Act, 1987."],
    ["अधिकांश मामलों में आत्महत्या के प्रयास को अपराध की श्रेणी से हटाने वाला मानसिक स्वास्थ्य देखभाल अधिनियम संसद ने किस वर्ष पारित किया?", ["2017", "1987", "2005", "2012"], "मानसिक स्वास्थ्य देखभाल अधिनियम, 2017 ने मानसिक स्वास्थ्य अधिनियम, 1987 का स्थान लिया।"]),
  q(3, N, "nursing-management", "H", 3,
    ["The acronym POSDCORB, describing the functions of an administrator, was given by:", ["Florence Nightingale", "Abraham Maslow", "Henri Fayol", "Luther Gulick"], "Gulick's POSDCORB: Planning, Organising, Staffing, Directing, Co-ordinating, Reporting and Budgeting."],
    ["प्रशासक के कार्यों को बताने वाला संक्षिप्त रूप POSDCORB किसने दिया?", ["फ़्लोरेंस नाइटिंगेल", "अब्राहम मैस्लो", "हेनरी फ़ेयोल", "लूथर गुलिक"], "गुलिक का POSDCORB: Planning, Organising, Staffing, Directing, Co-ordinating, Reporting और Budgeting।"]),
  q(3, N, "nursing-management", "M", 1,
    ["In Maslow's hierarchy of needs, which needs must be met first?", ["Self-actualisation", "Physiological needs such as oxygen, food and water", "Esteem needs", "Love and belonging"], "Physiological needs form the base, followed by safety, love, esteem and self-actualisation."],
    ["मैस्लो के आवश्यकता पदानुक्रम में सबसे पहले कौन-सी आवश्यकताएँ पूरी होनी चाहिए?", ["आत्म-सिद्धि", "ऑक्सीजन, भोजन और पानी जैसी शारीरिक आवश्यकताएँ", "सम्मान की आवश्यकताएँ", "प्रेम और अपनापन"], "शारीरिक आवश्यकताएँ आधार हैं, फिर सुरक्षा, प्रेम, सम्मान और आत्म-सिद्धि आती हैं।"]),
  q(3, N, "nursing-management", "M", 0,
    ["On a ward, a Kardex is:", ["A quick-reference card file summarising each patient's care plan", "A machine for sterilising instruments", "A type of oxygen mask", "The hospital's annual budget"], "The Kardex gives nurses a quick summary of each patient's orders and care plan, often used at handover."],
    ["वार्ड में कार्डेक्स (Kardex) क्या है?", ["हर रोगी की देखभाल योजना का सारांश देने वाली त्वरित संदर्भ कार्ड फ़ाइल", "उपकरण निर्जीवीकरण की मशीन", "एक प्रकार का ऑक्सीजन मास्क", "अस्पताल का वार्षिक बजट"], "कार्डेक्स नर्सों को हर रोगी के आदेशों और देखभाल योजना का त्वरित सारांश देता है, प्रायः हैंडओवर में प्रयोग होता है।"]),
  q(3, N, "nursing-management", "M", 2,
    ["In simple random sampling:", ["Only volunteers are chosen", "The researcher picks the most convenient subjects", "Every member of the population has an equal chance of selection", "Subjects are chosen by their age group only"], "Equal chance of selection makes the sample representative and allows statistical inference."],
    ["साधारण यादृच्छिक प्रतिचयन (सिंपल रैंडम सैंपलिंग) में:", ["केवल स्वयंसेवक चुने जाते हैं", "शोधकर्ता सबसे सुविधाजनक लोग चुनता है", "जनसंख्या के हर सदस्य के चुने जाने की समान संभावना होती है", "लोग केवल आयु वर्ग से चुने जाते हैं"], "चुने जाने की समान संभावना से नमूना प्रतिनिधिक बनता है और सांख्यिकीय निष्कर्ष निकाले जा सकते हैं।"]),

  // ───────── Section 4: General Knowledge (15) ─────────
  q(4, "general-studies", "indian-polity", "H", 1,
    ["Which Article of the Constitution prohibits employing children below 14 years in factories, mines and other hazardous work?", ["Article 21A", "Article 24", "Article 39", "Article 45"], "Article 24 bans child labour in hazardous employment; Article 21A gives the right to education."],
    ["संविधान का कौन-सा अनुच्छेद 14 वर्ष से कम आयु के बच्चों को कारख़ानों, खानों और अन्य ख़तरनाक कामों में लगाने पर रोक लगाता है?", ["अनुच्छेद 21A", "अनुच्छेद 24", "अनुच्छेद 39", "अनुच्छेद 45"], "अनुच्छेद 24 ख़तरनाक रोज़गार में बाल श्रम पर रोक लगाता है; अनुच्छेद 21A शिक्षा का अधिकार देता है।"]),
  q(4, "general-studies", "indian-polity", "H", 2,
    ["The Indian Nursing Council was constituted under an Act of Parliament passed in:", ["1935", "1950", "1947", "1962"], "The Indian Nursing Council Act was passed in 1947."],
    ["भारतीय उपचर्या परिषद (इंडियन नर्सिंग काउंसिल) संसद के किस वर्ष पारित अधिनियम के अंतर्गत बनी?", ["1935", "1950", "1947", "1962"], "भारतीय उपचर्या परिषद अधिनियम 1947 में पारित हुआ।"]),
  q(4, "general-studies", "indian-polity", "M", 0,
    ["The National Florence Nightingale Award for nurses is presented by the:", ["President of India", "Prime Minister", "Chief Justice of India", "WHO Director-General"], "The award, given by the Ministry of Health, is presented by the President, usually around International Nurses Day."],
    ["नर्सों के लिए राष्ट्रीय फ़्लोरेंस नाइटिंगेल पुरस्कार कौन प्रदान करता है?", ["भारत के राष्ट्रपति", "प्रधानमंत्री", "भारत के मुख्य न्यायाधीश", "WHO महानिदेशक"], "स्वास्थ्य मंत्रालय का यह पुरस्कार प्रायः अंतरराष्ट्रीय नर्स दिवस के आसपास राष्ट्रपति प्रदान करते हैं।"]),
  q(4, "general-studies", "general-science", "M", 3,
    ["The 'Black Death' of the 14th century was an epidemic of:", ["Cholera", "Smallpox", "Influenza", "Plague"], "Bubonic plague, spread by rat fleas, killed a large part of Europe's population."],
    ["14वीं शताब्दी की 'ब्लैक डेथ' किस रोग की महामारी थी?", ["हैज़ा", "चेचक", "इन्फ़्लुएंज़ा", "प्लेग"], "चूहों के पिस्सुओं से फैले ब्यूबोनिक प्लेग ने यूरोप की बड़ी आबादी को मार डाला।"]),
  q(4, "general-studies", "general-science", "H", 1,
    ["Human insulin for diabetics is now produced commercially using:", ["Extraction from pig pancreas only", "Recombinant DNA technology in bacteria or yeast", "Chemical synthesis from petroleum", "Plant extracts"], "The human insulin gene is put into E. coli or yeast, which then make insulin."],
    ["मधुमेह रोगियों के लिए मानव इंसुलिन अब व्यावसायिक रूप से कैसे बनाया जाता है?", ["केवल सूअर के अग्न्याशय से निकालकर", "जीवाणु या यीस्ट में पुनर्योगज DNA तकनीक से", "पेट्रोलियम से रासायनिक संश्लेषण से", "पौधों के अर्क से"], "मानव इंसुलिन जीन को ई. कोलाई या यीस्ट में डाला जाता है, जो फिर इंसुलिन बनाते हैं।"]),
  q(4, "general-studies", "general-science", "M", 2,
    ["The instrument a nurse uses with an inflatable cuff to measure blood pressure is the:", ["Stethoscope", "Glucometer", "Sphygmomanometer", "Pulse oximeter"], "A sphygmomanometer measures BP; a stethoscope is used with it to hear the Korotkoff sounds."],
    ["फुलाए जाने वाले कफ़ के साथ रक्तचाप नापने के लिए नर्स कौन-सा उपकरण प्रयोग करती है?", ["स्टेथोस्कोप", "ग्लूकोमीटर", "स्फ़िग्मोमैनोमीटर", "पल्स ऑक्सीमीटर"], "स्फ़िग्मोमैनोमीटर BP नापता है; कोरोटकॉफ़ ध्वनियाँ सुनने के लिए उसके साथ स्टेथोस्कोप लगता है।"]),
  q(4, "general-studies", "general-science", "M", 0,
    ["X-rays were discovered in 1895 by:", ["Wilhelm Röntgen", "Marie Curie", "Thomas Edison", "Niels Bohr"], "Röntgen won the first Nobel Prize in Physics (1901) for this discovery."],
    ["1895 में एक्स-किरणों की खोज किसने की?", ["विल्हेम रॉन्टजन", "मैरी क्यूरी", "थॉमस एडिसन", "नील्स बोर"], "इस खोज के लिए रॉन्टजन को भौतिकी का पहला नोबेल पुरस्कार (1901) मिला।"]),
  q(4, "general-studies", "indian-history", "M", 3,
    ["The All India Institute of Medical Sciences (AIIMS), New Delhi, was set up by an Act of Parliament in:", ["1947", "1961", "1972", "1956"], "The AIIMS Act was passed in 1956."],
    ["अखिल भारतीय आयुर्विज्ञान संस्थान (AIIMS), नई दिल्ली की स्थापना संसद के किस वर्ष के अधिनियम से हुई?", ["1947", "1961", "1972", "1956"], "AIIMS अधिनियम 1956 में पारित हुआ।"]),
  q(4, "general-studies", "indian-geography", "M", 1,
    ["Sukhna Lake, at the foot of the Shivalik hills, is in:", ["Shimla", "Chandigarh", "Dehradun", "Panchkula"], "Le Corbusier created Sukhna Lake in 1958 by damming a seasonal stream in Chandigarh."],
    ["शिवालिक पहाड़ियों की तलहटी में स्थित सुखना झील कहाँ है?", ["शिमला", "चंडीगढ़", "देहरादून", "पंचकूला"], "ले कॉर्बूज़िए ने 1958 में चंडीगढ़ में एक मौसमी नाले पर बाँध बनाकर सुखना झील बनाई।"]),
  q(4, "general-studies", "indian-history", "M", 2,
    ["The Rock Garden of Chandigarh, built from industrial and urban waste, was created by:", ["Le Corbusier", "Pierre Jeanneret", "Nek Chand", "M.S. Randhawa"], "Nek Chand, a road inspector, built it secretly from 1957; it opened to the public in 1976."],
    ["औद्योगिक और शहरी कचरे से बना चंडीगढ़ का रॉक गार्डन किसने बनाया?", ["ले कॉर्बूज़िए", "पियरे जीनरे", "नेक चंद", "एम.एस. रंधावा"], "सड़क निरीक्षक नेक चंद ने 1957 से इसे चुपचाप बनाया; 1976 में यह जनता के लिए खुला।"]),
  q(4, "general-studies", "indian-economy", "M", 0,
    ["The health scheme that gives comprehensive medical care to central government employees and pensioners is:", ["CGHS", "ESIS", "PM-JAY", "RSBY"], "The Central Government Health Scheme (CGHS) began in Delhi in 1954; ESIS covers private-sector workers."],
    ["केंद्र सरकार के कर्मचारियों और पेंशनभोगियों को व्यापक चिकित्सा देखभाल देने वाली स्वास्थ्य योजना कौन-सी है?", ["CGHS", "ESIS", "PM-JAY", "RSBY"], "केंद्रीय सरकार स्वास्थ्य योजना (CGHS) 1954 में दिल्ली से शुरू हुई; ESIS निजी क्षेत्र के कामगारों के लिए है।"]),
  q(4, "general-studies", "general-science", "M", 3,
    ["World AIDS Day is observed every year on:", ["7 April", "24 March", "31 May", "1 December"], "1 December is World AIDS Day; 24 March is World TB Day and 7 April World Health Day."],
    ["विश्व एड्स दिवस हर वर्ष किस दिन मनाया जाता है?", ["7 अप्रैल", "24 मार्च", "31 मई", "1 दिसंबर"], "1 दिसंबर विश्व एड्स दिवस है; 24 मार्च विश्व टीबी दिवस और 7 अप्रैल विश्व स्वास्थ्य दिवस।"]),
  q(4, "general-studies", "general-science", "M", 1,
    ["India's indigenous COVID-19 vaccine Covaxin was developed by Bharat Biotech together with:", ["AIIMS", "ICMR", "DRDO", "ISRO"], "Covaxin, an inactivated-virus vaccine, was developed with ICMR's National Institute of Virology."],
    ["भारत का स्वदेशी कोविड-19 टीका कोवैक्सिन भारत बायोटेक ने किसके साथ मिलकर विकसित किया?", ["AIIMS", "ICMR", "DRDO", "ISRO"], "निष्क्रिय-विषाणु टीका कोवैक्सिन ICMR के राष्ट्रीय विषाणु विज्ञान संस्थान के साथ विकसित हुआ।"]),
  q(4, "general-studies", "general-science", "M", 2,
    ["The ABO blood group system was discovered in 1901 by:", ["Robert Koch", "William Harvey", "Karl Landsteiner", "Joseph Lister"], "Karl Landsteiner received the 1930 Nobel Prize for discovering the blood groups."],
    ["ABO रक्त समूह प्रणाली की खोज 1901 में किसने की?", ["रॉबर्ट कोच", "विलियम हार्वे", "कार्ल लैंडस्टीनर", "जोसेफ़ लिस्टर"], "रक्त समूहों की खोज के लिए कार्ल लैंडस्टीनर को 1930 का नोबेल पुरस्कार मिला।"]),
  q(4, "general-studies", "indian-economy", "M", 0,
    ["Under the Janani Shishu Suraksha Karyakram (JSSK), pregnant women in public health facilities are entitled to:", ["Free delivery, including caesarean section, with free drugs, diet and transport", "A cash prize for every child", "Free private hospital care abroad", "Free delivery only for the first child"], "JSSK (2011) removes out-of-pocket costs for delivery and for sick newborns in government facilities."],
    ["जननी शिशु सुरक्षा कार्यक्रम (JSSK) के तहत सरकारी स्वास्थ्य केंद्रों में गर्भवती महिलाओं को क्या मिलता है?", ["सिज़ेरियन सहित निःशुल्क प्रसव, निःशुल्क दवाएँ, भोजन और परिवहन", "हर बच्चे पर नकद इनाम", "विदेश के निजी अस्पताल में निःशुल्क इलाज", "केवल पहले बच्चे का निःशुल्क प्रसव"], "JSSK (2011) सरकारी केंद्रों में प्रसव और बीमार नवजात के इलाज का अपनी जेब का ख़र्च समाप्त करता है।"]),
];
