// HP Patwari subject tests: English 1 and 2 (25 questions each). All questions are new, not in the full mocks.
// The Hindi version keeps the English sentences and options and explains in Hindi.

import { q, type PatwariQuestion } from "../types";

export const english1: PatwariQuestion[] = [
  // Grammar (6)
  q(0, "english", "grammar", "M", 0,
    ["Fill in the blank: 'She is very good ___ mathematics.'", ["at", "in", "on", "with"], "The adjective 'good' takes the preposition 'at' when we talk about skill in a subject: good at."],
    ["रिक्त स्थान भरिए: 'She is very good ___ mathematics.'", ["at", "in", "on", "with"], "किसी विषय में कुशलता बताने के लिए विशेषण 'good' के साथ 'at' आता है: good at।"]),
  q(0, "english", "grammar", "H", 1,
    ["Fill in the blank: 'The train ___ before we reached the station.'", ["left", "had left", "has left", "was leaving"], "Of two past actions, the earlier one is in the past perfect tense: 'had left'."],
    ["रिक्त स्थान भरिए: 'The train ___ before we reached the station.'", ["left", "had left", "has left", "was leaving"], "दो भूतकालीन क्रियाओं में पहले हुई क्रिया के लिए पूर्ण भूतकाल (past perfect) आता है: 'had left'।"]),
  q(0, "english", "grammar", "H", 1,
    ["Fill in the blank: 'I am looking forward to ___ you.'", ["see", "seeing", "saw", "be seeing"], "In 'look forward to', the word 'to' is a preposition, so it is followed by the -ing form: 'seeing'."],
    ["रिक्त स्थान भरिए: 'I am looking forward to ___ you.'", ["see", "seeing", "saw", "be seeing"], "'look forward to' में 'to' पूर्वसर्ग (preposition) है, इसलिए उसके बाद -ing रूप आता है: 'seeing'।"]),
  q(0, "english", "grammar", "M", 1,
    ["Choose the correct option: 'The news ___ good.'", ["are", "is", "were", "have been"], "'News' looks plural but is an uncountable noun and takes a singular verb: 'is'."],
    ["सही विकल्प चुनिए: 'The news ___ good.'", ["are", "is", "were", "have been"], "'News' देखने में बहुवचन लगता है पर अगणनीय संज्ञा है और एकवचन क्रिया लेता है: 'is'।"]),
  q(0, "english", "grammar", "H", 0,
    ["Fill in the blank: 'Hardly had he reached the station ___ the train left.'", ["when", "than", "then", "before"], "'Hardly' is followed by 'when' (and 'no sooner' by 'than'), and the past perfect is used in the first clause."],
    ["रिक्त स्थान भरिए: 'Hardly had he reached the station ___ the train left.'", ["when", "than", "then", "before"], "'Hardly' के साथ 'when' आता है ('no sooner' के साथ 'than'), और पहले उपवाक्य में पूर्ण भूतकाल आता है।"]),
  q(0, "english", "grammar", "M", 1,
    ["Fill in the blank: 'He is ___ honest man.'", ["a", "an", "the", "no article"], "'Honest' begins with a vowel sound (the 'h' is silent), so we use 'an'."],
    ["रिक्त स्थान भरिए: 'He is ___ honest man.'", ["a", "an", "the", "कोई article नहीं"], "'Honest' का उच्चारण स्वर ध्वनि से शुरू होता है ('h' मौन है), इसलिए 'an' आता है।"]),
  // Error spotting (3)
  q(0, "english", "error-spotting", "M", 1,
    ["Find the part with an error: 'Each of the boys / have completed / their homework.'", ["Each of the boys", "have completed", "their homework", "No error"], "'Each' takes a singular verb, so it should be 'has completed'."],
    ["त्रुटि वाला भाग ज्ञात कीजिए: 'Each of the boys / have completed / their homework.'", ["Each of the boys", "have completed", "their homework", "कोई त्रुटि नहीं"], "'Each' के साथ एकवचन क्रिया आती है, इसलिए 'has completed' होना चाहिए।"]),
  q(0, "english", "error-spotting", "M", 2,
    ["Find the part with an error: 'He gave me / a advice / about my career.'", ["He gave me", "about my career", "a advice", "No error"], "'Advice' is uncountable and cannot take 'a'. It should be 'some advice' or 'a piece of advice'."],
    ["त्रुटि वाला भाग ज्ञात कीजिए: 'He gave me / a advice / about my career.'", ["He gave me", "about my career", "a advice", "कोई त्रुटि नहीं"], "'Advice' अगणनीय संज्ञा है और 'a' नहीं लेती। सही रूप 'some advice' या 'a piece of advice' है।"]),
  q(0, "english", "error-spotting", "H", 2,
    ["Find the part with an error: 'The teacher / as well as the students / were present.'", ["The teacher", "as well as the students", "were present", "No error"], "With 'as well as', the verb agrees with the first subject 'The teacher', so it should be 'was present'."],
    ["त्रुटि वाला भाग ज्ञात कीजिए: 'The teacher / as well as the students / were present.'", ["The teacher", "as well as the students", "were present", "कोई त्रुटि नहीं"], "'as well as' के साथ क्रिया पहले कर्ता 'The teacher' के अनुसार आती है, अतः 'was present' होना चाहिए।"]),
  // Voice and speech (2)
  q(0, "english", "voice-speech", "H", 1,
    ["Change into the passive voice: 'She is writing a letter.'", ["A letter is written by her.", "A letter is being written by her.", "A letter was being written by her.", "A letter has been written by her."], "The present continuous tense becomes 'is/am/are being + past participle' in the passive."],
    ["कर्मवाच्य में बदलिए: 'She is writing a letter.'", ["A letter is written by her.", "A letter is being written by her.", "A letter was being written by her.", "A letter has been written by her."], "वर्तमान अपूर्ण काल कर्मवाच्य में 'is/am/are being + past participle' बनता है।"]),
  q(0, "english", "voice-speech", "H", 0,
    ["Change into indirect speech: He said to me, \"Where do you live?\"", ["He asked me where I lived.", "He told me where do I live.", "He asked me where did I live.", "He said me where I live."], "A question is reported with 'asked', the word order becomes that of a statement, and the present tense shifts to the past: 'where I lived'."],
    ["अप्रत्यक्ष कथन में बदलिए: He said to me, \"Where do you live?\"", ["He asked me where I lived.", "He told me where do I live.", "He asked me where did I live.", "He said me where I live."], "प्रश्न को 'asked' से बताया जाता है, शब्द-क्रम सामान्य कथन जैसा हो जाता है और वर्तमान काल भूतकाल में बदल जाता है: 'where I lived'।"]),
  // Synonyms and antonyms (4)
  q(0, "english", "synonyms-antonyms", "M", 1,
    ["Choose the synonym of 'DILIGENT':", ["Lazy", "Hardworking", "Careless", "Clever"], "'Diligent' means showing steady effort, i.e. hardworking."],
    ["'DILIGENT' का समानार्थी शब्द चुनिए:", ["Lazy", "Hardworking", "Careless", "Clever"], "'Diligent' का अर्थ है लगन से मेहनत करने वाला, यानी 'hardworking'।"]),
  q(0, "english", "synonyms-antonyms", "M", 1,
    ["Choose the synonym of 'CONCEAL':", ["Reveal", "Hide", "Show", "Display"], "'Conceal' means to keep something from being seen, i.e. hide."],
    ["'CONCEAL' का समानार्थी शब्द चुनिए:", ["Reveal", "Hide", "Show", "Display"], "'Conceal' का अर्थ है किसी चीज़ को दिखने से रोकना, यानी 'hide' (छिपाना)।"]),
  q(0, "english", "synonyms-antonyms", "M", 3,
    ["Choose the antonym of 'GENEROUS':", ["Kind", "Rich", "Noble", "Stingy"], "'Generous' means willing to give freely. Its opposite is 'stingy'."],
    ["'GENEROUS' का विलोम शब्द चुनिए:", ["Kind", "Rich", "Noble", "Stingy"], "'Generous' का अर्थ है खुले हाथ से देने वाला। इसका विलोम 'stingy' (कंजूस) है।"]),
  q(0, "english", "synonyms-antonyms", "M", 1,
    ["Choose the antonym of 'ANCIENT':", ["Old", "Modern", "Historic", "Antique"], "'Ancient' means very old. Its opposite is 'modern'."],
    ["'ANCIENT' का विलोम शब्द चुनिए:", ["Old", "Modern", "Historic", "Antique"], "'Ancient' का अर्थ बहुत पुराना है। इसका विलोम 'modern' (आधुनिक) है।"]),
  // Idioms (3)
  q(0, "english", "idioms", "M", 0,
    ["Choose the meaning of the idiom 'to break the ice':", ["To start a conversation in an awkward situation", "To break something cold", "To end a friendship", "To feel very cold"], "'To break the ice' means to ease tension and begin a conversation among people who do not know each other well."],
    ["मुहावरे 'to break the ice' का अर्थ चुनिए:", ["असहज स्थिति में बातचीत शुरू करना", "ठंडी चीज़ तोड़ना", "मित्रता समाप्त करना", "बहुत ठंड लगना"], "'To break the ice' का अर्थ है ऐसे लोगों के बीच तनाव कम करके बातचीत शुरू करना जो एक-दूसरे को कम जानते हों।"]),
  q(0, "english", "idioms", "M", 1,
    ["Choose the meaning of the idiom 'a piece of cake':", ["A sweet dish", "Something very easy", "A small share", "A birthday gift"], "'A piece of cake' means a task that is very easy to do."],
    ["मुहावरे 'a piece of cake' का अर्थ चुनिए:", ["एक मिठाई", "बहुत आसान काम", "छोटा हिस्सा", "जन्मदिन का उपहार"], "'A piece of cake' का अर्थ है ऐसा काम जो करने में बहुत आसान हो।"]),
  q(0, "english", "idioms", "M", 2,
    ["Choose the meaning of the idiom 'once in a blue moon':", ["Every night", "Every month", "Very rarely", "Very often"], "'Once in a blue moon' means something that happens very rarely."],
    ["मुहावरे 'once in a blue moon' का अर्थ चुनिए:", ["हर रात", "हर महीने", "बहुत कम बार", "बहुत बार"], "'Once in a blue moon' का अर्थ है ऐसी बात जो बहुत कम होती है।"]),
  // One-word substitution (3)
  q(0, "english", "one-word", "M", 0,
    ["One word for 'a person who loves mankind and helps others':", ["Philanthropist", "Misanthrope", "Pessimist", "Egoist"], "A philanthropist loves humanity and gives to help others. A misanthrope hates people."],
    ["'मानव जाति से प्रेम करने और दूसरों की सहायता करने वाले व्यक्ति' के लिए एक शब्द चुनिए:", ["Philanthropist", "Misanthrope", "Pessimist", "Egoist"], "Philanthropist मानवता से प्रेम करने वाला और दूसरों की मदद हेतु दान देने वाला होता है। Misanthrope लोगों से घृणा करता है।"]),
  q(0, "english", "one-word", "H", 0,
    ["One word for 'government by a small group of people':", ["Oligarchy", "Autocracy", "Democracy", "Theocracy"], "Oligarchy is rule by a few. Autocracy is rule by one person and theocracy is rule by religious leaders."],
    ["'कुछ थोड़े लोगों द्वारा शासन' के लिए एक शब्द चुनिए:", ["Oligarchy", "Autocracy", "Democracy", "Theocracy"], "Oligarchy का अर्थ है कुछ लोगों का शासन। Autocracy एक व्यक्ति का और Theocracy धार्मिक नेताओं का शासन है।"]),
  q(0, "english", "one-word", "H", 0,
    ["One word for 'a place where bees are kept':", ["Apiary", "Aviary", "Aquarium", "Orchard"], "An apiary is a place where bees are kept. An aviary is for birds."],
    ["'वह स्थान जहाँ मधुमक्खियाँ पाली जाती हैं' के लिए एक शब्द चुनिए:", ["Apiary", "Aviary", "Aquarium", "Orchard"], "Apiary वह स्थान है जहाँ मधुमक्खियाँ पाली जाती हैं। Aviary पक्षियों के लिए होता है।"]),
  // Spelling (2)
  q(0, "english", "spelling", "M", 1,
    ["Choose the correctly spelt word for 'a feeling of shame or awkwardness':", ["Embarassment", "Embarrassment", "Embarasment", "Embaresment"], "The correct spelling is 'embarrassment' (double r, double s)."],
    ["'शर्मिंदगी या असहजता की भावना' के लिए सही वर्तनी वाला शब्द चुनिए:", ["Embarassment", "Embarrassment", "Embarasment", "Embaresment"], "सही वर्तनी 'embarrassment' है (दो r, दो s)।"]),
  q(0, "english", "spelling", "M", 1,
    ["Identify the correct spelling:", ["Seperate", "Separate", "Separete", "Saparate"], "The correct spelling is 'separate', which has 'a' in the middle (sep-a-rate)."],
    ["सही वर्तनी पहचानिए:", ["Seperate", "Separate", "Separete", "Saparate"], "सही वर्तनी 'separate' है, जिसके बीच में 'a' आता है (sep-a-rate)।"]),
  // Prepositions and tags (2)
  q(0, "english", "grammar", "M", 0,
    ["Fill in the blank: 'This book is different ___ the one I read last week.'", ["from", "than", "with", "of"], "In standard English, 'different' is followed by 'from'."],
    ["रिक्त स्थान भरिए: 'This book is different ___ the one I read last week.'", ["from", "than", "with", "of"], "मानक अंग्रेज़ी में 'different' के बाद 'from' आता है।"]),
  q(0, "english", "grammar", "M", 1,
    ["Complete the sentence with the correct question tag: 'You will come to the party, ___?'", ["will you", "won't you", "don't you", "do you"], "A positive statement takes a negative tag with the same auxiliary: 'will … won't you?'"],
    ["सही question tag से वाक्य पूरा कीजिए: 'You will come to the party, ___?'", ["will you", "won't you", "don't you", "do you"], "सकारात्मक कथन के बाद उसी सहायक क्रिया का नकारात्मक tag आता है: 'will … won't you?'"]),
];

export const english2: PatwariQuestion[] = [
  // Grammar (6)
  q(0, "english", "grammar", "H", 1,
    ["Fill in the blank: 'Neither Ram nor his brothers ___ present.'", ["was", "were", "is", "has been"], "With 'neither … nor', the verb agrees with the subject nearest to it. 'His brothers' is plural, so the verb is 'were'."],
    ["रिक्त स्थान भरिए: 'Neither Ram nor his brothers ___ present.'", ["was", "were", "is", "has been"], "'neither … nor' के साथ क्रिया निकटतम कर्ता के अनुसार आती है। 'his brothers' बहुवचन है, अतः 'were' आएगा।"]),
  q(0, "english", "grammar", "M", 1,
    ["Fill in the blank: 'If it rains tomorrow, we ___ the match.'", ["cancel", "will cancel", "would cancel", "cancelled"], "In a first conditional sentence, the 'if' clause is in the present tense and the main clause uses 'will'."],
    ["रिक्त स्थान भरिए: 'If it rains tomorrow, we ___ the match.'", ["cancel", "will cancel", "would cancel", "cancelled"], "प्रथम शर्त वाले वाक्य में 'if' उपवाक्य वर्तमान काल में और मुख्य उपवाक्य में 'will' आता है।"]),
  q(0, "english", "grammar", "H", 1,
    ["Fill in the blank: 'He prefers tea ___ coffee.'", ["than", "to", "from", "over"], "The verb 'prefer' is followed by 'to', not 'than': prefer X to Y."],
    ["रिक्त स्थान भरिए: 'He prefers tea ___ coffee.'", ["than", "to", "from", "over"], "क्रिया 'prefer' के बाद 'to' आता है, 'than' नहीं: prefer X to Y।"]),
  q(0, "english", "grammar", "H", 1,
    ["Fill in the blank: 'The teacher, along with his students, ___ going to the museum.'", ["are", "is", "were", "have"], "With 'along with', the verb agrees with the first subject 'The teacher', which is singular. So 'is'."],
    ["रिक्त स्थान भरिए: 'The teacher, along with his students, ___ going to the museum.'", ["are", "is", "were", "have"], "'along with' के साथ क्रिया पहले कर्ता 'The teacher' के अनुसार, जो एकवचन है, आती है। अतः 'is'।"]),
  q(0, "english", "grammar", "H", 1,
    ["Fill in the blank: 'He is one of the best players who ___ played for the country.'", ["has", "have", "is", "was"], "In 'one of the … who', the relative pronoun 'who' refers to the plural 'players', so the verb is 'have'."],
    ["रिक्त स्थान भरिए: 'He is one of the best players who ___ played for the country.'", ["has", "have", "is", "was"], "'one of the … who' में 'who' बहुवचन 'players' के लिए आता है, अतः क्रिया 'have' होगी।"]),
  q(0, "english", "grammar", "H", 1,
    ["Fill in the blank: 'It is high time you ___ studying.'", ["start", "started", "will start", "are starting"], "After 'It is high time', the past tense is used to talk about something that should already be happening: 'started'."],
    ["रिक्त स्थान भरिए: 'It is high time you ___ studying.'", ["start", "started", "will start", "are starting"], "'It is high time' के बाद भूतकाल का प्रयोग होता है, ऐसे कार्य के लिए जो अब तक शुरू हो जाना चाहिए था: 'started'।"]),
  // Error spotting (3)
  q(0, "english", "error-spotting", "M", 0,
    ["Find the part with an error: 'I have finished / my work / yesterday.'", ["I have finished", "my work", "yesterday", "No error"], "With 'yesterday' (a finished time), the simple past is needed: 'I finished my work yesterday.'"],
    ["त्रुटि वाला भाग ज्ञात कीजिए: 'I have finished / my work / yesterday.'", ["I have finished", "my work", "yesterday", "कोई त्रुटि नहीं"], "'yesterday' (बीते समय) के साथ साधारण भूतकाल आता है: 'I finished my work yesterday.'"]),
  q(0, "english", "error-spotting", "M", 0,
    ["Find the part with an error: 'The furnitures / in the room / are old.'", ["The furnitures", "in the room", "are old", "No error"], "'Furniture' is uncountable and has no plural form. It should be 'The furniture in the room is old.'"],
    ["त्रुटि वाला भाग ज्ञात कीजिए: 'The furnitures / in the room / are old.'", ["The furnitures", "in the room", "are old", "कोई त्रुटि नहीं"], "'Furniture' अगणनीय है और उसका बहुवचन नहीं होता। सही वाक्य है 'The furniture in the room is old.'"]),
  q(0, "english", "error-spotting", "M", 1,
    ["Find the part with an error: 'He is / more taller / than his brother.'", ["He is", "more taller", "than his brother", "No error"], "A comparative is formed either with '-er' or with 'more', never both. It should be 'taller'."],
    ["त्रुटि वाला भाग ज्ञात कीजिए: 'He is / more taller / than his brother.'", ["He is", "more taller", "than his brother", "कोई त्रुटि नहीं"], "तुलनात्मक रूप '-er' या 'more' में से एक से बनता है, दोनों से नहीं। सही रूप 'taller' है।"]),
  // Voice and speech (2)
  q(0, "english", "voice-speech", "M", 0,
    ["Change into the passive voice: 'They will complete the work tomorrow.'", ["The work will be completed by them tomorrow.", "The work is completed by them tomorrow.", "The work would be completed by them tomorrow.", "The work will complete by them tomorrow."], "The simple future becomes 'will be + past participle' in the passive."],
    ["कर्मवाच्य में बदलिए: 'They will complete the work tomorrow.'", ["The work will be completed by them tomorrow.", "The work is completed by them tomorrow.", "The work would be completed by them tomorrow.", "The work will complete by them tomorrow."], "साधारण भविष्यत् काल कर्मवाच्य में 'will be + past participle' बनता है।"]),
  q(0, "english", "voice-speech", "H", 0,
    ["Change into indirect speech: He said to her, \"Will you help me?\"", ["He asked her if she would help him.", "He asked her will she help him.", "He said her if she will help him.", "He asked her that she would help him."], "A yes/no question is reported with 'asked' plus 'if' or 'whether', and 'will' changes to 'would'."],
    ["अप्रत्यक्ष कथन में बदलिए: He said to her, \"Will you help me?\"", ["He asked her if she would help him.", "He asked her will she help him.", "He said her if she will help him.", "He asked her that she would help him."], "हाँ/नहीं वाले प्रश्न को 'asked' के साथ 'if' या 'whether' लगाकर बताया जाता है और 'will' बदलकर 'would' हो जाता है।"]),
  // Synonyms and antonyms (4)
  q(0, "english", "synonyms-antonyms", "M", 1,
    ["Choose the synonym of 'SCARCE':", ["Plentiful", "Rare", "Cheap", "Common"], "'Scarce' means not available in large quantity, i.e. rare."],
    ["'SCARCE' का समानार्थी शब्द चुनिए:", ["Plentiful", "Rare", "Cheap", "Common"], "'Scarce' का अर्थ है जो अधिक मात्रा में उपलब्ध न हो, यानी 'rare' (दुर्लभ)।"]),
  q(0, "english", "synonyms-antonyms", "H", 1,
    ["Choose the synonym of 'PRUDENT':", ["Careless", "Cautious", "Rude", "Lazy"], "'Prudent' means acting with care and good judgement, i.e. cautious."],
    ["'PRUDENT' का समानार्थी शब्द चुनिए:", ["Careless", "Cautious", "Rude", "Lazy"], "'Prudent' का अर्थ है सोच-समझकर सावधानी से काम करने वाला, यानी 'cautious'।"]),
  q(0, "english", "synonyms-antonyms", "H", 1,
    ["Choose the antonym of 'TRANSPARENT':", ["Clear", "Opaque", "Thin", "Glassy"], "'Transparent' means see-through. Its opposite is 'opaque'."],
    ["'TRANSPARENT' का विलोम शब्द चुनिए:", ["Clear", "Opaque", "Thin", "Glassy"], "'Transparent' का अर्थ पारदर्शी है। इसका विलोम 'opaque' (अपारदर्शी) है।"]),
  q(0, "english", "synonyms-antonyms", "M", 2,
    ["Choose the antonym of 'OPTIMISTIC':", ["Hopeful", "Cheerful", "Pessimistic", "Confident"], "'Optimistic' means expecting good outcomes. Its opposite is 'pessimistic'."],
    ["'OPTIMISTIC' का विलोम शब्द चुनिए:", ["Hopeful", "Cheerful", "Pessimistic", "Confident"], "'Optimistic' का अर्थ अच्छे परिणाम की आशा रखने वाला है। इसका विलोम 'pessimistic' (निराशावादी) है।"]),
  // Idioms (3)
  q(0, "english", "idioms", "M", 1,
    ["Choose the meaning of the idiom 'to spill the beans':", ["To cook food", "To reveal a secret", "To waste food", "To make a mess"], "'To spill the beans' means to reveal a secret by accident or on purpose."],
    ["मुहावरे 'to spill the beans' का अर्थ चुनिए:", ["खाना पकाना", "राज़ खोल देना", "खाना बर्बाद करना", "गंदगी फैलाना"], "'To spill the beans' का अर्थ है गलती से या जानबूझकर कोई राज़ खोल देना।"]),
  q(0, "english", "idioms", "M", 2,
    ["Choose the meaning of the idiom 'under the weather':", ["In a storm", "Very happy", "Feeling unwell", "Standing outside"], "'Under the weather' means feeling slightly ill."],
    ["मुहावरे 'under the weather' का अर्थ चुनिए:", ["तूफ़ान में", "बहुत खुश", "अस्वस्थ महसूस करना", "बाहर खड़ा होना"], "'Under the weather' का अर्थ है थोड़ा अस्वस्थ महसूस करना।"]),
  q(0, "english", "idioms", "M", 0,
    ["Choose the meaning of the idiom 'to cost an arm and a leg':", ["To be very expensive", "To cause an injury", "To be very cheap", "To need a doctor"], "The idiom means that something is extremely expensive."],
    ["मुहावरे 'to cost an arm and a leg' का अर्थ चुनिए:", ["बहुत महँगा होना", "चोट पहुँचाना", "बहुत सस्ता होना", "डॉक्टर की ज़रूरत होना"], "इस मुहावरे का अर्थ है कि कोई चीज़ बहुत ही महँगी है।"]),
  // One-word substitution (3)
  q(0, "english", "one-word", "M", 0,
    ["One word for 'a person who is new to a job or activity':", ["Novice", "Veteran", "Expert", "Master"], "A novice is a beginner. A veteran is an experienced person."],
    ["'किसी काम या गतिविधि में नए व्यक्ति' के लिए एक शब्द चुनिए:", ["Novice", "Veteran", "Expert", "Master"], "Novice का अर्थ नौसिखिया है। Veteran अनुभवी व्यक्ति को कहते हैं।"]),
  q(0, "english", "one-word", "H", 0,
    ["One word for 'a speech delivered without any preparation':", ["Extempore", "Monologue", "Sermon", "Soliloquy"], "An extempore speech is given on the spot without preparation. A monologue is a long speech by one person, and a soliloquy is speaking one's thoughts aloud."],
    ["'बिना किसी तैयारी के दिया गया भाषण' के लिए एक शब्द चुनिए:", ["Extempore", "Monologue", "Sermon", "Soliloquy"], "Extempore भाषण बिना तैयारी के तुरंत दिया जाता है। Monologue एक व्यक्ति का लंबा भाषण और Soliloquy अपने विचार ज़ोर से बोलना है।"]),
  q(0, "english", "one-word", "H", 0,
    ["One word for 'the scientific study of birds':", ["Ornithology", "Entomology", "Zoology", "Etymology"], "Ornithology is the study of birds. Entomology is the study of insects and etymology the study of word origins."],
    ["'पक्षियों का वैज्ञानिक अध्ययन' के लिए एक शब्द चुनिए:", ["Ornithology", "Entomology", "Zoology", "Etymology"], "Ornithology पक्षियों का अध्ययन है। Entomology कीटों का और Etymology शब्दों की उत्पत्ति का अध्ययन है।"]),
  // Spelling (2)
  q(0, "english", "spelling", "M", 1,
    ["Choose the correctly spelt word for 'the body that rules a country':", ["Goverment", "Government", "Govenment", "Governmant"], "The correct spelling is 'government', with an 'n' before 'm'."],
    ["'देश पर शासन करने वाली संस्था' के लिए सही वर्तनी वाला शब्द चुनिए:", ["Goverment", "Government", "Govenment", "Governmant"], "सही वर्तनी 'government' है, जिसमें 'm' से पहले 'n' आता है।"]),
  q(0, "english", "spelling", "H", 0,
    ["Choose the correctly spelt word meaning 'the inner sense of right and wrong':", ["Conscience", "Consience", "Conciense", "Consciance"], "The correct spelling is 'conscience'."],
    ["'सही-गलत की आंतरिक समझ' अर्थ वाले शब्द की सही वर्तनी चुनिए:", ["Conscience", "Consience", "Conciense", "Consciance"], "सही वर्तनी 'conscience' है।"]),
  // Prepositions and tags (2)
  q(0, "english", "grammar", "M", 1,
    ["Fill in the blank: 'She is married ___ a doctor.'", ["with", "to", "by", "from"], "The correct preposition is 'to': married to someone."],
    ["रिक्त स्थान भरिए: 'She is married ___ a doctor.'", ["with", "to", "by", "from"], "सही पूर्वसर्ग 'to' है: married to someone।"]),
  q(0, "english", "grammar", "H", 0,
    ["Complete the sentence with the correct question tag: 'Let us go for a walk, ___?'", ["shall we", "will we", "don't we", "shall you"], "After 'Let us', the question tag is 'shall we?'"],
    ["सही question tag से वाक्य पूरा कीजिए: 'Let us go for a walk, ___?'", ["shall we", "will we", "don't we", "shall you"], "'Let us' के बाद question tag 'shall we?' आता है।"]),
];
