// HP Patwari subject tests: General Knowledge 1 and 2 (25 questions each). All questions are new, not in the full mocks.

import { q, type PatwariQuestion } from "../types";

export const gk1: PatwariQuestion[] = [
  // History (5)
  q(0, "general-studies", "indian-history", "M", 0,
    ["After the Kalinga war of 261 BC, which Mauryan emperor gave up conquest and embraced Buddhism?", ["Ashoka", "Bindusara", "Chandragupta Maurya", "Brihadratha"], "Ashoka was moved by the destruction of the Kalinga war and turned to Buddhism and the policy of 'Dhamma'."],
    ["261 ई.पू. के कलिंग युद्ध के बाद किस मौर्य सम्राट ने विजय-अभियान छोड़कर बौद्ध धर्म अपनाया?", ["अशोक", "बिंदुसार", "चंद्रगुप्त मौर्य", "बृहद्रथ"], "कलिंग युद्ध के विनाश से द्रवित होकर अशोक ने बौद्ध धर्म और 'धम्म' की नीति अपनाई।"]),
  q(0, "general-studies", "indian-history", "M", 1,
    ["The ancient Indian treatise on statecraft, the 'Arthashastra', was written by:", ["Kalidasa", "Kautilya (Chanakya)", "Banabhatta", "Vishakhadatta"], "The Arthashastra is attributed to Kautilya (Chanakya), the minister of Chandragupta Maurya."],
    ["राजनीति और शासन पर प्राचीन भारतीय ग्रंथ 'अर्थशास्त्र' के रचयिता कौन हैं?", ["कालिदास", "कौटिल्य (चाणक्य)", "बाणभट्ट", "विशाखदत्त"], "अर्थशास्त्र की रचना चंद्रगुप्त मौर्य के मंत्री कौटिल्य (चाणक्य) को दी जाती है।"]),
  q(0, "general-studies", "indian-history", "M", 2,
    ["The biography of King Harshavardhana, the 'Harshacharita', was written by:", ["Kalhana", "Bilhana", "Banabhatta", "Vishakhadatta"], "Banabhatta, the court poet of Harsha, wrote the Harshacharita and also the Sanskrit prose romance Kadambari."],
    ["राजा हर्षवर्धन की जीवनी 'हर्षचरित' किसने लिखी?", ["कल्हण", "बिल्हण", "बाणभट्ट", "विशाखदत्त"], "हर्ष के दरबारी कवि बाणभट्ट ने हर्षचरित और संस्कृत गद्य-काव्य कादंबरी लिखी।"]),
  q(0, "general-studies", "indian-history", "M", 1,
    ["Which ruler introduced the silver coin 'Rupiya' that became the basis of the later Indian rupee?", ["Alauddin Khilji", "Sher Shah Suri", "Akbar", "Muhammad bin Tughlaq"], "Sher Shah Suri introduced a silver coin called the 'Rupiya', and also repaired and extended the Grand Trunk Road."],
    ["किस शासक ने चाँदी का सिक्का 'रुपया' चलाया, जो आगे चलकर भारतीय रुपये का आधार बना?", ["अलाउद्दीन खिलजी", "शेरशाह सूरी", "अकबर", "मुहम्मद बिन तुगलक"], "शेरशाह सूरी ने चाँदी का 'रुपया' चलाया और ग्रांड ट्रंक रोड की मरम्मत तथा विस्तार भी कराया।"]),
  q(0, "general-studies", "indian-history", "M", 0,
    ["The Jallianwala Bagh massacre took place on 13 April 1919 at:", ["Amritsar", "Lahore", "Ludhiana", "Delhi"], "General Dyer's troops fired on an unarmed crowd gathered at Jallianwala Bagh, Amritsar, on Baisakhi day."],
    ["जलियाँवाला बाग हत्याकांड 13 अप्रैल 1919 को कहाँ हुआ?", ["अमृतसर", "लाहौर", "लुधियाना", "दिल्ली"], "बैसाखी के दिन जनरल डायर के सैनिकों ने अमृतसर के जलियाँवाला बाग में निहत्थी भीड़ पर गोली चलाई।"]),
  // Polity (6)
  q(0, "general-studies", "indian-polity", "M", 1,
    ["The 'Right to Life and Personal Liberty' is guaranteed under which Article of the Constitution?", ["Article 14", "Article 21", "Article 25", "Article 32"], "Article 21 protects life and personal liberty, and the Supreme Court has read many rights (privacy, livelihood, clean environment) into it."],
    ["संविधान के किस अनुच्छेद में 'प्राण एवं दैहिक स्वतंत्रता का अधिकार' दिया गया है?", ["अनुच्छेद 14", "अनुच्छेद 21", "अनुच्छेद 25", "अनुच्छेद 32"], "अनुच्छेद 21 प्राण और दैहिक स्वतंत्रता की रक्षा करता है और सर्वोच्च न्यायालय ने इसमें निजता, आजीविका, स्वच्छ पर्यावरण जैसे अधिकार भी माने हैं।"]),
  q(0, "general-studies", "indian-polity", "H", 2,
    ["Free and compulsory education for children aged 6 to 14 years was made a Fundamental Right (Article 21A) by the:", ["42nd Amendment", "73rd Amendment", "86th Amendment", "101st Amendment"], "The 86th Amendment Act, 2002 inserted Article 21A, and the Right to Education Act came into force in 2010."],
    ["6 से 14 वर्ष के बच्चों की निःशुल्क एवं अनिवार्य शिक्षा (अनुच्छेद 21A) को मौलिक अधिकार किस संशोधन द्वारा बनाया गया?", ["42वाँ संशोधन", "73वाँ संशोधन", "86वाँ संशोधन", "101वाँ संशोधन"], "86वें संशोधन अधिनियम, 2002 ने अनुच्छेद 21A जोड़ा और शिक्षा का अधिकार अधिनियम 2010 में लागू हुआ।"]),
  q(0, "general-studies", "indian-polity", "M", 3,
    ["'President's Rule' in a State is imposed under which Article?", ["Article 352", "Article 360", "Article 365", "Article 356"], "Article 356 allows the President to take over the administration of a State if its constitutional machinery fails. Article 352 is national emergency and 360 is financial emergency."],
    ["किसी राज्य में 'राष्ट्रपति शासन' संविधान के किस अनुच्छेद के अंतर्गत लगाया जाता है?", ["अनुच्छेद 352", "अनुच्छेद 360", "अनुच्छेद 365", "अनुच्छेद 356"], "राज्य में संवैधानिक तंत्र विफल होने पर अनुच्छेद 356 के अंतर्गत राष्ट्रपति शासन लगता है। अनुच्छेद 352 राष्ट्रीय आपातकाल और 360 वित्तीय आपातकाल है।"]),
  q(0, "general-studies", "indian-polity", "M", 0,
    ["The Election Commission of India is established under which Article of the Constitution?", ["Article 324", "Article 280", "Article 148", "Article 76"], "Article 324 vests the superintendence, direction and control of elections in the Election Commission."],
    ["भारत के निर्वाचन आयोग की स्थापना संविधान के किस अनुच्छेद के अंतर्गत होती है?", ["अनुच्छेद 324", "अनुच्छेद 280", "अनुच्छेद 148", "अनुच्छेद 76"], "अनुच्छेद 324 चुनावों के अधीक्षण, निर्देशन और नियंत्रण का दायित्व निर्वाचन आयोग को देता है।"]),
  q(0, "general-studies", "indian-polity", "H", 1,
    ["The office of the Attorney General of India is provided under which Article?", ["Article 74", "Article 76", "Article 148", "Article 165"], "Article 76 provides for the Attorney General, the highest law officer of the Government of India, appointed by the President."],
    ["भारत के महान्यायवादी (अटॉर्नी जनरल) का पद संविधान के किस अनुच्छेद में है?", ["अनुच्छेद 74", "अनुच्छेद 76", "अनुच्छेद 148", "अनुच्छेद 165"], "अनुच्छेद 76 महान्यायवादी का प्रावधान करता है, जो भारत सरकार के सर्वोच्च विधि अधिकारी हैं और राष्ट्रपति द्वारा नियुक्त होते हैं।"]),
  q(0, "general-studies", "indian-polity", "H", 2,
    ["The 'Basic Structure' doctrine of the Constitution was laid down by the Supreme Court in which case?", ["Golaknath case", "Minerva Mills case", "Kesavananda Bharati case", "Maneka Gandhi case"], "In Kesavananda Bharati v. State of Kerala (1973), the Court held that Parliament cannot amend the basic structure of the Constitution."],
    ["संविधान की 'मूल संरचना' का सिद्धांत सर्वोच्च न्यायालय ने किस मामले में दिया?", ["गोलकनाथ मामला", "मिनर्वा मिल्स मामला", "केशवानंद भारती मामला", "मेनका गांधी मामला"], "केशवानंद भारती बनाम केरल राज्य (1973) में न्यायालय ने कहा कि संसद संविधान की मूल संरचना में संशोधन नहीं कर सकती।"]),
  // Geography (5)
  q(0, "general-studies", "indian-geography", "M", 1,
    ["Which is the largest inland salt lake in India?", ["Chilika Lake", "Sambhar Lake", "Pulicat Lake", "Loktak Lake"], "Sambhar Lake in Rajasthan is the largest inland saline lake in India. Chilika and Pulicat are coastal lagoons."],
    ["भारत की सबसे बड़ी अंतर्देशीय खारे पानी की झील कौन-सी है?", ["चिल्का झील", "सांभर झील", "पुलिकट झील", "लोकटक झील"], "राजस्थान की सांभर झील भारत की सबसे बड़ी अंतर्देशीय खारे पानी की झील है। चिल्का और पुलिकट तटीय लैगून हैं।"]),
  q(0, "general-studies", "indian-geography", "H", 2,
    ["Which is the longest lake in India?", ["Wular Lake", "Dal Lake", "Vembanad Lake", "Chilika Lake"], "Vembanad Lake in Kerala is the longest lake in India, and it is also a Ramsar site."],
    ["भारत की सबसे लंबी झील कौन-सी है?", ["वुलर झील", "डल झील", "वेम्बनाड झील", "चिल्का झील"], "केरल की वेम्बनाड झील भारत की सबसे लंबी झील है और रामसर स्थल भी है।"]),
  q(0, "general-studies", "indian-geography", "H", 0,
    ["The southernmost point of India, 'Indira Point', is located in:", ["Great Nicobar Island", "Kanyakumari", "Rameswaram", "Little Andaman"], "Indira Point on Great Nicobar Island is the southernmost point of India. Kanyakumari is the southernmost tip of the mainland."],
    ["भारत का सबसे दक्षिणी बिंदु 'इंदिरा प्वाइंट' कहाँ स्थित है?", ["ग्रेट निकोबार द्वीप", "कन्याकुमारी", "रामेश्वरम", "लिटिल अंडमान"], "ग्रेट निकोबार द्वीप का इंदिरा प्वाइंट भारत का सबसे दक्षिणी बिंदु है। कन्याकुमारी मुख्य भूमि का सबसे दक्षिणी छोर है।"]),
  q(0, "general-studies", "indian-geography", "M", 3,
    ["The Siachen Glacier is situated in which mountain range?", ["Pir Panjal", "Zanskar", "Ladakh", "Karakoram"], "The Siachen Glacier lies in the Karakoram range, and is the longest glacier of the Karakoram."],
    ["सियाचिन ग्लेशियर किस पर्वत श्रेणी में स्थित है?", ["पीर पंजाल", "ज़ांस्कर", "लद्दाख", "काराकोरम"], "सियाचिन ग्लेशियर काराकोरम श्रेणी में है और काराकोरम का सबसे लंबा ग्लेशियर है।"]),
  q(0, "general-studies", "indian-geography", "H", 1,
    ["The river Brahmaputra is known in Tibet as:", ["Dihang", "Tsangpo", "Jamuna", "Padma"], "In Tibet the river is called Yarlung Tsangpo. It becomes the Dihang in Arunachal Pradesh and the Jamuna in Bangladesh."],
    ["ब्रह्मपुत्र नदी तिब्बत में किस नाम से जानी जाती है?", ["दिहांग", "सांगपो (त्सांगपो)", "जमुना", "पद्मा"], "तिब्बत में इसे यारलुंग त्सांगपो कहते हैं। अरुणाचल प्रदेश में यह दिहांग और बांग्लादेश में जमुना कहलाती है।"]),
  // Economy (4)
  q(0, "general-studies", "indian-economy", "M", 1,
    ["The rate at which the Reserve Bank of India lends short-term money to commercial banks is called the:", ["Reverse repo rate", "Repo rate", "Bank rate", "Cash reserve ratio"], "The repo rate is the rate at which the RBI lends to banks against securities. The reverse repo is the rate at which it borrows from them."],
    ["भारतीय रिज़र्व बैंक वाणिज्यिक बैंकों को अल्पकालिक ऋण जिस दर पर देता है, उसे क्या कहते हैं?", ["रिवर्स रेपो दर", "रेपो दर", "बैंक दर", "नकद आरक्षित अनुपात"], "रेपो दर वह दर है जिस पर RBI प्रतिभूतियों के बदले बैंकों को उधार देता है। रिवर्स रेपो वह दर है जिस पर वह उनसे उधार लेता है।"]),
  q(0, "general-studies", "indian-economy", "H", 2,
    ["Currency notes of all denominations except the one-rupee note are issued by:", ["The Government of India", "The Ministry of Finance", "The Reserve Bank of India", "The State Bank of India"], "The RBI issues all notes except the one-rupee note and coins, which are issued by the Government of India (Ministry of Finance)."],
    ["एक रुपये के नोट को छोड़कर सभी मूल्य-वर्ग के नोट कौन जारी करता है?", ["भारत सरकार", "वित्त मंत्रालय", "भारतीय रिज़र्व बैंक", "भारतीय स्टेट बैंक"], "एक रुपये का नोट और सिक्के भारत सरकार (वित्त मंत्रालय) जारी करती है, बाकी सभी नोट RBI जारी करता है।"]),
  q(0, "general-studies", "indian-economy", "M", 0,
    ["The Pradhan Mantri Jan Dhan Yojana, aimed at financial inclusion through bank accounts, was launched in:", ["2014", "2010", "2016", "2018"], "The PM Jan Dhan Yojana was launched on 28 August 2014 to give every household a bank account."],
    ["बैंक खातों के माध्यम से वित्तीय समावेशन के लिए प्रधानमंत्री जन धन योजना कब शुरू हुई?", ["2014", "2010", "2016", "2018"], "प्रधानमंत्री जन धन योजना 28 अगस्त 2014 को हर परिवार को बैंक खाता देने के लिए शुरू हुई।"]),
  q(0, "general-studies", "indian-economy", "M", 3,
    ["The First Five-Year Plan (1951–56) gave the highest priority to:", ["Heavy industry", "Defence", "Foreign trade", "Agriculture and irrigation"], "The First Plan, based on the Harrod–Domar model, gave top priority to agriculture, irrigation and power, including projects like the Bhakra Nangal Dam."],
    ["प्रथम पंचवर्षीय योजना (1951–56) में सर्वाधिक प्राथमिकता किसे दी गई?", ["भारी उद्योग", "रक्षा", "विदेशी व्यापार", "कृषि एवं सिंचाई"], "हैरोड–डोमर मॉडल पर आधारित पहली योजना में कृषि, सिंचाई और बिजली को सर्वोच्च प्राथमिकता मिली, जिसमें भाखड़ा नांगल बाँध जैसी परियोजनाएँ भी थीं।"]),
  // Science (5)
  q(0, "general-studies", "general-science", "M", 2,
    ["The SI unit of frequency is:", ["Newton", "Pascal", "Hertz", "Joule"], "The hertz (Hz) is one cycle per second. Newton is force, pascal is pressure and joule is energy."],
    ["आवृत्ति का SI मात्रक क्या है?", ["न्यूटन", "पास्कल", "हर्ट्ज़", "जूल"], "हर्ट्ज़ (Hz) एक चक्र प्रति सेकंड होता है। न्यूटन बल, पास्कल दाब और जूल ऊर्जा का मात्रक है।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["Deficiency of which vitamin causes scurvy?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B1"], "Scurvy, marked by bleeding gums and weak joints, is caused by a lack of vitamin C (ascorbic acid)."],
    ["किस विटामिन की कमी से स्कर्वी रोग होता है?", ["विटामिन A", "विटामिन C", "विटामिन D", "विटामिन B1"], "मसूड़ों से खून आने और जोड़ों की कमज़ोरी वाला स्कर्वी विटामिन C (एस्कॉर्बिक अम्ल) की कमी से होता है।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["The pH of pure water at 25°C is:", ["0", "5", "7", "14"], "Pure water is neutral, with a pH of 7. Below 7 is acidic and above 7 is basic."],
    ["25°C पर शुद्ध जल का pH मान कितना होता है?", ["0", "5", "7", "14"], "शुद्ध जल उदासीन होता है और इसका pH 7 होता है। 7 से कम अम्लीय और 7 से अधिक क्षारीय होता है।"]),
  q(0, "general-studies", "general-science", "E", 1,
    ["In which part of a plant cell does photosynthesis take place?", ["Mitochondria", "Chloroplast", "Nucleus", "Vacuole"], "Photosynthesis happens in chloroplasts, which contain the green pigment chlorophyll."],
    ["पादप कोशिका के किस भाग में प्रकाश-संश्लेषण होता है?", ["माइटोकॉन्ड्रिया", "हरित लवक (क्लोरोप्लास्ट)", "केंद्रक", "रिक्तिका"], "प्रकाश-संश्लेषण क्लोरोप्लास्ट में होता है, जिसमें हरा वर्णक क्लोरोफिल होता है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["Malaria is caused by a protozoan of the genus Plasmodium and is spread by the bite of a:", ["Female Anopheles mosquito", "Female Aedes mosquito", "Tsetse fly", "House fly"], "The female Anopheles mosquito carries the Plasmodium parasite. Aedes spreads dengue and chikungunya."],
    ["मलेरिया प्लाज़्मोडियम नामक प्रोटोज़ोआ से होता है और किसके काटने से फैलता है?", ["मादा एनोफिलीज़ मच्छर", "मादा एडीज़ मच्छर", "सी-सी मक्खी", "घरेलू मक्खी"], "मादा एनोफिलीज़ मच्छर प्लाज़्मोडियम परजीवी का वाहक है। एडीज़ डेंगू और चिकनगुनिया फैलाता है।"]),
];

export const gk2: PatwariQuestion[] = [
  // History (5)
  q(0, "general-studies", "indian-history", "M", 0,
    ["The Brihadeeswara Temple at Thanjavur was built by the Chola king:", ["Rajaraja I", "Rajendra I", "Karikala", "Kulottunga I"], "Rajaraja I built the Brihadeeswara (Rajarajeswaram) Temple at Thanjavur around 1010 AD. It is a UNESCO World Heritage Site."],
    ["तंजावुर का बृहदीश्वर मंदिर किस चोल राजा ने बनवाया?", ["राजराज प्रथम", "राजेंद्र प्रथम", "करिकाल", "कुलोत्तुंग प्रथम"], "राजराज प्रथम ने लगभग 1010 ई. में तंजावुर का बृहदीश्वर (राजराजेश्वरम) मंदिर बनवाया। यह यूनेस्को विश्व धरोहर स्थल है।"]),
  q(0, "general-studies", "indian-history", "M", 1,
    ["Din-i-Ilahi, a religious code combining elements of several faiths, was propounded by Akbar in:", ["1556", "1582", "1605", "1526"], "Akbar announced the Din-i-Ilahi in 1582 after discussions with scholars of many religions at the Ibadat Khana in Fatehpur Sikri."],
    ["कई धर्मों के तत्त्वों को मिलाकर बनाया गया 'दीन-ए-इलाही' अकबर ने कब चलाया?", ["1556", "1582", "1605", "1526"], "फतेहपुर सीकरी के इबादतखाने में अनेक धर्मों के विद्वानों से चर्चा के बाद अकबर ने 1582 में दीन-ए-इलाही की घोषणा की।"]),
  q(0, "general-studies", "indian-history", "M", 2,
    ["Shivaji was crowned Chhatrapati at which fort in 1674?", ["Purandar", "Sinhagad", "Raigad", "Torna"], "Shivaji was crowned at Raigad Fort in 1674 and took the title Chhatrapati, with Gaga Bhatt performing the ritual."],
    ["1674 में शिवाजी का राज्याभिषेक (छत्रपति के रूप में) किस किले में हुआ?", ["पुरंदर", "सिंहगढ़", "रायगढ़", "तोरणा"], "शिवाजी का राज्याभिषेक 1674 में रायगढ़ किले में हुआ और उन्होंने छत्रपति की उपाधि ली। यह अनुष्ठान गागा भट्ट ने कराया।"]),
  q(0, "general-studies", "indian-history", "M", 1,
    ["The Revolt of 1857 began on 10 May 1857 at:", ["Delhi", "Meerut", "Kanpur", "Jhansi"], "The revolt began with the sepoys' uprising at Meerut, after which they marched to Delhi and proclaimed Bahadur Shah Zafar their leader."],
    ["1857 का विद्रोह 10 मई 1857 को कहाँ से शुरू हुआ?", ["दिल्ली", "मेरठ", "कानपुर", "झाँसी"], "विद्रोह मेरठ में सिपाहियों के विद्रोह से शुरू हुआ, जिसके बाद वे दिल्ली पहुँचे और बहादुर शाह ज़फ़र को अपना नेता घोषित किया।"]),
  q(0, "general-studies", "indian-history", "M", 3,
    ["The Dandi March (Salt Satyagraha) of 1930 began from:", ["Champaran", "Bardoli", "Wardha", "Sabarmati Ashram"], "Gandhi began the march on 12 March 1930 from Sabarmati Ashram and reached Dandi on 6 April to break the salt law."],
    ["1930 की दांडी यात्रा (नमक सत्याग्रह) कहाँ से शुरू हुई?", ["चंपारण", "बारडोली", "वर्धा", "साबरमती आश्रम"], "गांधीजी ने 12 मार्च 1930 को साबरमती आश्रम से यात्रा शुरू की और 6 अप्रैल को दांडी पहुँचकर नमक कानून तोड़ा।"]),
  // Polity (6)
  q(0, "general-studies", "indian-polity", "H", 0,
    ["The impeachment of the President of India is provided for under which Article?", ["Article 61", "Article 74", "Article 356", "Article 123"], "Article 61 lays down the procedure for impeaching the President for 'violation of the Constitution'."],
    ["भारत के राष्ट्रपति पर महाभियोग की प्रक्रिया संविधान के किस अनुच्छेद में है?", ["अनुच्छेद 61", "अनुच्छेद 74", "अनुच्छेद 356", "अनुच्छेद 123"], "अनुच्छेद 61 'संविधान के उल्लंघन' पर राष्ट्रपति पर महाभियोग की प्रक्रिया बताता है।"]),
  q(0, "general-studies", "indian-polity", "H", 1,
    ["A 'Money Bill' is defined under which Article of the Constitution?", ["Article 109", "Article 110", "Article 111", "Article 112"], "Article 110 defines a Money Bill. It can be introduced only in the Lok Sabha, and the Rajya Sabha can only recommend changes."],
    ["'धन विधेयक' की परिभाषा संविधान के किस अनुच्छेद में दी गई है?", ["अनुच्छेद 109", "अनुच्छेद 110", "अनुच्छेद 111", "अनुच्छेद 112"], "अनुच्छेद 110 धन विधेयक को परिभाषित करता है। इसे केवल लोकसभा में पेश किया जा सकता है और राज्यसभा केवल संशोधन की सिफारिश कर सकती है।"]),
  q(0, "general-studies", "indian-polity", "M", 2,
    ["A 'National Emergency' can be declared by the President under which Article?", ["Article 350", "Article 356", "Article 352", "Article 360"], "Article 352 allows a national emergency in case of war, external aggression or armed rebellion."],
    ["राष्ट्रपति 'राष्ट्रीय आपातकाल' संविधान के किस अनुच्छेद के अंतर्गत घोषित करते हैं?", ["अनुच्छेद 350", "अनुच्छेद 356", "अनुच्छेद 352", "अनुच्छेद 360"], "युद्ध, बाहरी आक्रमण या सशस्त्र विद्रोह की स्थिति में अनुच्छेद 352 के अंतर्गत राष्ट्रीय आपातकाल घोषित हो सकता है।"]),
  q(0, "general-studies", "indian-polity", "H", 2,
    ["The voting age in India was lowered from 21 to 18 years by which Constitutional Amendment?", ["42nd", "52nd", "61st", "73rd"], "The 61st Amendment (1988) reduced the voting age from 21 to 18 years, which took effect in 1989."],
    ["भारत में मतदान की आयु 21 से घटाकर 18 वर्ष किस संविधान संशोधन द्वारा की गई?", ["42वाँ", "52वाँ", "61वाँ", "73वाँ"], "61वें संशोधन (1988) ने मतदान की आयु 21 से घटाकर 18 वर्ष की, जो 1989 में लागू हुई।"]),
  q(0, "general-studies", "indian-polity", "H", 3,
    ["The maximum strength of the Lok Sabha as fixed by the Constitution is:", ["530", "543", "545", "550"], "Article 81 fixes the maximum at 550 (530 from States and 20 from Union Territories). At present 543 seats are filled by election."],
    ["संविधान द्वारा लोकसभा की अधिकतम सदस्य संख्या कितनी निर्धारित है?", ["530", "543", "545", "550"], "अनुच्छेद 81 के अनुसार अधिकतम 550 सदस्य (राज्यों से 530 और संघ राज्य क्षेत्रों से 20) हो सकते हैं। वर्तमान में 543 सीटों पर चुनाव होता है।"]),
  q(0, "general-studies", "indian-polity", "M", 0,
    ["Which body decides disputes regarding the election of the President and the Vice-President?", ["The Supreme Court", "The Election Commission", "Parliament", "The High Court"], "Under Article 71, all doubts and disputes about the election of the President or Vice-President are decided by the Supreme Court."],
    ["राष्ट्रपति और उपराष्ट्रपति के चुनाव से जुड़े विवादों का निर्णय कौन करता है?", ["सर्वोच्च न्यायालय", "निर्वाचन आयोग", "संसद", "उच्च न्यायालय"], "अनुच्छेद 71 के अनुसार राष्ट्रपति या उपराष्ट्रपति के चुनाव से जुड़े सभी संदेहों और विवादों का निर्णय सर्वोच्च न्यायालय करता है।"]),
  // Geography (5)
  q(0, "general-studies", "indian-geography", "M", 2,
    ["The famous Nohkalikai Falls is located in which state?", ["Karnataka", "Kerala", "Meghalaya", "Sikkim"], "Nohkalikai Falls, near Cherrapunji in Meghalaya, is one of the tallest plunge waterfalls in India."],
    ["प्रसिद्ध नोहकालिकाई जलप्रपात किस राज्य में है?", ["कर्नाटक", "केरल", "मेघालय", "सिक्किम"], "मेघालय में चेरापूंजी के निकट स्थित नोहकालिकाई जलप्रपात भारत के सबसे ऊँचे प्रपाती जलप्रपातों में से एक है।"]),
  q(0, "general-studies", "indian-geography", "M", 0,
    ["The Sundarbans, home of the Royal Bengal Tiger, are located mainly in:", ["West Bengal", "Odisha", "Assam", "Andhra Pradesh"], "The Sundarbans mangrove forest in the Ganga–Brahmaputra delta lies mainly in West Bengal (and Bangladesh)."],
    ["रॉयल बंगाल टाइगर का घर सुंदरवन मुख्यतः किस राज्य में है?", ["पश्चिम बंगाल", "ओडिशा", "असम", "आंध्र प्रदेश"], "गंगा–ब्रह्मपुत्र डेल्टा का सुंदरवन मैंग्रोव वन मुख्यतः पश्चिम बंगाल (और बांग्लादेश) में है।"]),
  q(0, "general-studies", "indian-geography", "E", 1,
    ["The Kaziranga National Park, famous for the one-horned rhinoceros, is in which state?", ["Arunachal Pradesh", "Assam", "Meghalaya", "Tripura"], "Kaziranga in Assam is home to the largest population of the Indian one-horned rhinoceros and is a UNESCO World Heritage Site."],
    ["एक सींग वाले गैंडे के लिए प्रसिद्ध काज़ीरंगा राष्ट्रीय उद्यान किस राज्य में है?", ["अरुणाचल प्रदेश", "असम", "मेघालय", "त्रिपुरा"], "असम का काज़ीरंगा भारतीय एक सींग वाले गैंडे की सबसे बड़ी आबादी का घर है और यूनेस्को विश्व धरोहर स्थल है।"]),
  q(0, "general-studies", "indian-geography", "M", 3,
    ["The Palk Strait separates India from:", ["Maldives", "Myanmar", "Bangladesh", "Sri Lanka"], "The Palk Strait lies between the Tamil Nadu coast and Sri Lanka, connecting the Bay of Bengal with the Palk Bay."],
    ["पाक जलडमरूमध्य भारत को किससे अलग करता है?", ["मालदीव", "म्यांमार", "बांग्लादेश", "श्रीलंका"], "पाक जलडमरूमध्य तमिलनाडु तट और श्रीलंका के बीच है और बंगाल की खाड़ी को पाक खाड़ी से जोड़ता है।"]),
  q(0, "general-studies", "indian-geography", "M", 0,
    ["Which is the longest river flowing entirely within India?", ["Ganga", "Godavari", "Yamuna", "Narmada"], "The Ganga (about 2,525 km) is the longest river of India. The Godavari is the longest in peninsular India."],
    ["पूरी तरह भारत में बहने वाली सबसे लंबी नदी कौन-सी है?", ["गंगा", "गोदावरी", "यमुना", "नर्मदा"], "गंगा (लगभग 2,525 किमी) भारत की सबसे लंबी नदी है। गोदावरी प्रायद्वीपीय भारत की सबसे लंबी नदी है।"]),
  // Economy (4)
  q(0, "general-studies", "indian-economy", "H", 0,
    ["'Fiscal deficit' of the Government is the excess of:", ["Total expenditure over total receipts excluding borrowings", "Revenue expenditure over revenue receipts", "Imports over exports", "Capital expenditure over capital receipts"], "Fiscal deficit = total expenditure − (revenue receipts + non-debt capital receipts). It shows how much the government must borrow. The revenue deficit and trade deficit are different measures."],
    ["सरकार का 'राजकोषीय घाटा' किसके आधिक्य को कहते हैं?", ["उधारियों को छोड़कर कुल प्राप्तियों पर कुल व्यय का", "राजस्व प्राप्तियों पर राजस्व व्यय का", "निर्यात पर आयात का", "पूँजीगत प्राप्तियों पर पूँजीगत व्यय का"], "राजकोषीय घाटा = कुल व्यय − (राजस्व प्राप्तियाँ + ऋण-रहित पूँजीगत प्राप्तियाँ)। यह बताता है कि सरकार को कितना उधार लेना पड़ेगा। राजस्व घाटा और व्यापार घाटा अलग माप हैं।"]),
  q(0, "general-studies", "indian-economy", "H", 1,
    ["The Minimum Support Price (MSP) for crops is announced by the Government of India on the recommendation of the:", ["NITI Aayog", "Commission for Agricultural Costs and Prices (CACP)", "Reserve Bank of India", "NABARD"], "The CACP recommends MSPs for major crops, and the Cabinet Committee on Economic Affairs approves and announces them."],
    ["फसलों का न्यूनतम समर्थन मूल्य (MSP) भारत सरकार किसकी सिफारिश पर घोषित करती है?", ["नीति आयोग", "कृषि लागत एवं मूल्य आयोग (CACP)", "भारतीय रिज़र्व बैंक", "नाबार्ड"], "CACP प्रमुख फसलों के MSP की सिफारिश करता है और आर्थिक मामलों की मंत्रिमंडलीय समिति उन्हें मंज़ूर कर घोषित करती है।"]),
  q(0, "general-studies", "indian-economy", "M", 2,
    ["'Operation Flood', which made India the world's largest milk producer, was led by:", ["M.S. Swaminathan", "Norman Borlaug", "Verghese Kurien", "Lal Bahadur Shastri"], "Verghese Kurien, the 'Father of the White Revolution', led Operation Flood through the National Dairy Development Board and Amul."],
    ["भारत को दुनिया का सबसे बड़ा दूध उत्पादक बनाने वाले 'ऑपरेशन फ्लड' का नेतृत्व किसने किया?", ["एम.एस. स्वामीनाथन", "नॉर्मन बोरलॉग", "वर्गीज़ कुरियन", "लाल बहादुर शास्त्री"], "'श्वेत क्रांति के जनक' वर्गीज़ कुरियन ने राष्ट्रीय डेयरी विकास बोर्ड और अमूल के माध्यम से ऑपरेशन फ्लड का नेतृत्व किया।"]),
  q(0, "general-studies", "indian-economy", "M", 1,
    ["Which sector contributes the largest share to India's GDP?", ["Primary (agriculture)", "Tertiary (services)", "Secondary (industry)", "All are equal"], "The tertiary or services sector contributes more than half of India's GDP, ahead of industry and agriculture."],
    ["भारत के GDP में सबसे अधिक योगदान किस क्षेत्र का है?", ["प्राथमिक (कृषि)", "तृतीयक (सेवा)", "द्वितीयक (उद्योग)", "सभी समान"], "तृतीयक या सेवा क्षेत्र का योगदान भारत के GDP में आधे से अधिक है, जो उद्योग और कृषि से आगे है।"]),
  // Science (5)
  q(0, "general-studies", "general-science", "M", 2,
    ["Deficiency of Vitamin D in children causes:", ["Night blindness", "Scurvy", "Rickets", "Beriberi"], "Vitamin D helps absorb calcium. Its lack causes rickets in children (soft, bent bones) and osteomalacia in adults."],
    ["बच्चों में विटामिन D की कमी से कौन-सा रोग होता है?", ["रतौंधी", "स्कर्वी", "रिकेट्स (सूखा रोग)", "बेरी-बेरी"], "विटामिन D कैल्शियम के अवशोषण में मदद करता है। इसकी कमी से बच्चों में रिकेट्स (मुलायम, मुड़ी हड्डियाँ) और वयस्कों में ऑस्टियोमलेशिया होता है।"]),
  q(0, "general-studies", "general-science", "M", 3,
    ["Which of the following is NOT a greenhouse gas?", ["Carbon dioxide", "Methane", "Nitrous oxide", "Oxygen"], "Carbon dioxide, methane and nitrous oxide trap heat in the atmosphere. Oxygen does not absorb infrared radiation significantly."],
    ["निम्नलिखित में से कौन-सी ग्रीनहाउस गैस नहीं है?", ["कार्बन डाइऑक्साइड", "मीथेन", "नाइट्रस ऑक्साइड", "ऑक्सीजन"], "कार्बन डाइऑक्साइड, मीथेन और नाइट्रस ऑक्साइड वायुमंडल में ऊष्मा रोकती हैं। ऑक्सीजन अवरक्त विकिरण को उल्लेखनीय रूप से अवशोषित नहीं करती।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["The atomic number of carbon is:", ["4", "6", "8", "12"], "Carbon has 6 protons, so its atomic number is 6. Its common isotope has a mass number of 12."],
    ["कार्बन का परमाणु क्रमांक क्या है?", ["4", "6", "8", "12"], "कार्बन में 6 प्रोटॉन होते हैं, अतः इसका परमाणु क्रमांक 6 है। इसके सामान्य समस्थानिक की द्रव्यमान संख्या 12 है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["According to Newton's Third Law of Motion:", ["Every action has an equal and opposite reaction", "Force equals mass times acceleration", "A body stays at rest unless a force acts on it", "Energy can neither be created nor destroyed"], "Newton's Third Law says that when one body exerts a force on another, the second exerts an equal and opposite force on the first."],
    ["न्यूटन के गति के तृतीय नियम के अनुसार:", ["प्रत्येक क्रिया की समान और विपरीत प्रतिक्रिया होती है", "बल = द्रव्यमान × त्वरण", "कोई वस्तु बल लगे बिना विरामावस्था में रहती है", "ऊर्जा न बनाई जा सकती है न नष्ट की जा सकती है"], "न्यूटन का तृतीय नियम कहता है कि जब एक वस्तु दूसरी पर बल लगाती है तो दूसरी भी पहली पर समान और विपरीत बल लगाती है।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["The double-helix structure of DNA was proposed in 1953 by:", ["Mendel and Darwin", "Pasteur and Koch", "Watson and Crick", "Hooke and Schleiden"], "James Watson and Francis Crick proposed the double-helix model of DNA in 1953, using X-ray data from Rosalind Franklin and Maurice Wilkins."],
    ["1953 में DNA की द्विकुंडलित (डबल हेलिक्स) संरचना का प्रतिमान किसने प्रस्तावित किया?", ["मेंडल और डार्विन", "पाश्चर और कोच", "वाटसन और क्रिक", "हुक और श्लाइडेन"], "जेम्स वाटसन और फ्रांसिस क्रिक ने 1953 में रोज़ालिंड फ्रैंकलिन और मौरिस विल्किंस के एक्स-रे आँकड़ों का उपयोग कर DNA का डबल हेलिक्स प्रतिमान प्रस्तावित किया।"]),
];
