// HP Patwari subject tests: Himachal GK 1 and 2 (25 questions each). All questions are new, not in the full mocks.

import { q, type PatwariQuestion } from "../types";

export const hpGk1: PatwariQuestion[] = [
  q(0, "hp-gk", "history", "H", 0,
    ["According to tradition, the ancient Kangra (Nagarkot) fort was founded by:", ["Susharma Chandra", "Bhuri Singh", "Sansar Chand", "Sahil Varman"], "The Katoch ancestor Susharma Chandra is said to have founded the Kangra fort, and the Katoch dynasty traces its origin to him. Sansar Chand ruled much later, in the 18th–19th centuries."],
    ["परंपरा के अनुसार प्राचीन कांगड़ा (नगरकोट) किले की स्थापना किसने की?", ["सुशर्मा चंद्र", "भूरि सिंह", "संसार चंद", "साहिल वर्मन"], "माना जाता है कि कटोच वंश के पूर्वज सुशर्मा चंद्र ने कांगड़ा किला बनवाया और कटोच वंश अपना मूल उन्हीं से मानता है। संसार चंद बहुत बाद में, 18वीं–19वीं शताब्दी में शासक हुए।"]),
  q(0, "hp-gk", "history", "H", 0,
    ["The ancient name 'Trigarta' for the Kangra–Jalandhar region refers to the land between which three rivers?", ["Ravi, Beas and Sutlej", "Sutlej, Yamuna and Giri", "Beas, Chenab and Ravi", "Sutlej, Beas and Yamuna"], "Trigarta means 'the land of three rivers': the Ravi, the Beas and the Sutlej. Its kingdom in the Kangra region is mentioned in the Mahabharata and by Panini."],
    ["कांगड़ा–जालंधर क्षेत्र का प्राचीन नाम 'त्रिगर्त' किन तीन नदियों के बीच की भूमि को दर्शाता है?", ["रावी, ब्यास और सतलुज", "सतलुज, यमुना और गिरि", "ब्यास, चिनाब और रावी", "सतलुज, ब्यास और यमुना"], "त्रिगर्त का अर्थ है 'तीन नदियों की भूमि': रावी, ब्यास और सतलुज। कांगड़ा क्षेत्र के इस राज्य का उल्लेख महाभारत और पाणिनि में मिलता है।"]),
  q(0, "hp-gk", "history", "H", 0,
    ["The Battle of Bhangani (1686), in which Guru Gobind Singh fought the hill chiefs, was fought near:", ["Paonta Sahib", "Anandpur Sahib", "Kiratpur", "Nurpur"], "The Battle of Bhangani was fought near Paonta Sahib in present-day Sirmaur district. Guru Gobind Singh's forces defeated the alliance led by Raja Fateh Shah of Garhwal."],
    ["गुरु गोबिंद सिंह और पहाड़ी राजाओं के बीच 1686 का भंगानी का युद्ध किस स्थान के निकट हुआ?", ["पांवटा साहिब", "आनंदपुर साहिब", "कीरतपुर", "नूरपुर"], "भंगानी का युद्ध वर्तमान सिरमौर जिले के पांवटा साहिब के निकट हुआ। गुरु गोबिंद सिंह की सेना ने गढ़वाल के राजा फतेह शाह के नेतृत्व वाले गठबंधन को हराया।"]),
  q(0, "hp-gk", "personalities", "H", 0,
    ["Who became the first non-Congress Chief Minister of Himachal Pradesh in 1977?", ["Shanta Kumar", "Prem Kumar Dhumal", "Jai Ram Thakur", "Thakur Ram Lal"], "Shanta Kumar of the Janata Party became Chief Minister in 1977, ending the Congress rule in the state. Thakur Ram Lal, the previous Chief Minister, was from the Congress."],
    ["1977 में हिमाचल प्रदेश के पहले गैर-कांग्रेसी मुख्यमंत्री कौन बने?", ["शांता कुमार", "प्रेम कुमार धूमल", "जयराम ठाकुर", "ठाकुर राम लाल"], "जनता पार्टी के शांता कुमार 1977 में मुख्यमंत्री बने और राज्य में कांग्रेस का शासन समाप्त हुआ। इससे पहले के मुख्यमंत्री ठाकुर राम लाल कांग्रेस के थे।"]),
  q(0, "hp-gk", "polity-administration", "M", 2,
    ["The High Court of Himachal Pradesh, with its seat at Shimla, was established in the year:", ["1948", "1966", "1971", "1981"], "The Himachal Pradesh High Court was set up in 1971 when the state attained full statehood. Before that the Judicial Commissioner's Court served the region."],
    ["शिमला में स्थित हिमाचल प्रदेश उच्च न्यायालय की स्थापना किस वर्ष हुई?", ["1948", "1966", "1971", "1981"], "पूर्ण राज्य का दर्जा मिलने पर 1971 में हिमाचल प्रदेश उच्च न्यायालय बना। इससे पहले न्यायिक आयुक्त का न्यायालय कार्य करता था।"]),
  q(0, "hp-gk", "polity-administration", "M", 2,
    ["Dharamshala was declared the second (winter) capital of Himachal Pradesh in the year:", ["2005", "2012", "2017", "2020"], "Dharamshala was declared the second capital of Himachal Pradesh in January 2017 by the then Chief Minister Virbhadra Singh."],
    ["धर्मशाला को हिमाचल प्रदेश की दूसरी (शीतकालीन) राजधानी किस वर्ष घोषित किया गया?", ["2005", "2012", "2017", "2020"], "तत्कालीन मुख्यमंत्री वीरभद्र सिंह ने जनवरी 2017 में धर्मशाला को हिमाचल प्रदेश की दूसरी राजधानी घोषित किया।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["The approximate height of the Rohtang Pass is:", ["2,978 m", "3,978 m", "4,578 m", "5,078 m"], "Rohtang Pass, on the Pir Panjal range between Kullu and Lahaul, is about 3,978 m (13,050 ft) high."],
    ["रोहतांग दर्रे की लगभग ऊँचाई कितनी है?", ["2,978 मी", "3,978 मी", "4,578 मी", "5,078 मी"], "पीर पंजाल श्रेणी में कुल्लू और लाहौल के बीच स्थित रोहतांग दर्रा लगभग 3,978 मी (13,050 फुट) ऊँचा है।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["Chandratal (the 'Moon Lake') lies in which valley?", ["Spiti valley", "Kinnaur valley", "Pangi valley", "Bharmour valley"], "Chandratal is a high-altitude lake (about 4,300 m) in the Spiti valley of Lahaul & Spiti district, near the Kunzum Pass."],
    ["चंद्रताल ('चंद्र झील') किस घाटी में स्थित है?", ["स्पीति घाटी", "किन्नौर घाटी", "पांगी घाटी", "भरमौर घाटी"], "चंद्रताल लाहौल-स्पीति जिले की स्पीति घाटी में कुंजुम दर्रे के निकट लगभग 4,300 मी की ऊँचाई पर स्थित झील है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["The Prashar Lake, with a floating island and a pagoda-style temple, is located in which district?", ["Mandi", "Kullu", "Shimla", "Kangra"], "Prashar Lake (about 2,700 m) is in Mandi district and has a temple dedicated to sage Prashar."],
    ["तैरते द्वीप और पैगोडा शैली के मंदिर वाली पराशर झील किस जिले में है?", ["मंडी", "कुल्लू", "शिमला", "कांगड़ा"], "पराशर झील (लगभग 2,700 मी) मंडी जिले में है और यहाँ ऋषि पराशर को समर्पित मंदिर है।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["Which city of Himachal Pradesh is known as the 'Mushroom City of India' and the 'City of Red Gold' (tomato)?", ["Solan", "Nahan", "Una", "Hamirpur"], "Solan is called the 'Mushroom City' because the Directorate of Mushroom Research is here, and 'Red Gold' for its tomato trade."],
    ["हिमाचल प्रदेश का कौन-सा शहर 'भारत की मशरूम सिटी' और 'लाल सोने (टमाटर) का शहर' कहलाता है?", ["सोलन", "नाहन", "ऊना", "हमीरपुर"], "सोलन में मशरूम अनुसंधान निदेशालय है, इसलिए इसे 'मशरूम सिटी' कहा जाता है, और टमाटर के व्यापार के कारण 'लाल सोना'।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["The hill station of Dalhousie in Chamba district is named after:", ["Lord Dalhousie", "Lord Curzon", "Lord Canning", "Lord Ripon"], "Dalhousie was founded in 1854 and named after Lord Dalhousie, the Governor-General of India (1848–56)."],
    ["चंबा जिले के पर्वतीय नगर डलहौज़ी का नाम किसके नाम पर पड़ा है?", ["लॉर्ड डलहौज़ी", "लॉर्ड कर्ज़न", "लॉर्ड कैनिंग", "लॉर्ड रिपन"], "डलहौज़ी की स्थापना 1854 में हुई और इसका नाम भारत के गवर्नर-जनरल (1848–56) लॉर्ड डलहौज़ी के नाम पर रखा गया।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["The river Beas originates from:", ["Beas Kund near the Rohtang Pass", "Rakas Tal in Tibet", "Suraj Tal near Baralacha La", "Bara Bhangal glacier"], "The Beas rises at Beas Kund, near the Rohtang Pass in the Pir Panjal range, and flows through Kullu, Mandi and Kangra."],
    ["ब्यास नदी का उद्गम कहाँ से है?", ["रोहतांग दर्रे के निकट ब्यास कुंड", "तिब्बत का राक्षस ताल", "बारालाचा ला के निकट सूरजताल", "बड़ा भंगाल ग्लेशियर"], "ब्यास नदी पीर पंजाल श्रेणी में रोहतांग दर्रे के निकट ब्यास कुंड से निकलती है और कुल्लू, मंडी तथा कांगड़ा से बहती है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 2,
    ["Which of the following towns lies on the bank of the river Sutlej?", ["Mandi", "Kullu", "Rampur Bushahr", "Chamba"], "Rampur Bushahr is on the Sutlej. Mandi and Kullu are on the Beas, and Chamba is on the Ravi."],
    ["निम्नलिखित में से कौन-सा नगर सतलुज नदी के तट पर स्थित है?", ["मंडी", "कुल्लू", "रामपुर बुशहर", "चंबा"], "रामपुर बुशहर सतलुज पर है। मंडी और कुल्लू ब्यास पर तथा चंबा रावी पर स्थित है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["Paonta Sahib, famous for its Gurudwara, lies on the banks of the river:", ["Yamuna", "Sutlej", "Beas", "Ravi"], "Paonta Sahib in Sirmaur district lies on the bank of the Yamuna, on the border with Uttarakhand."],
    ["अपने गुरुद्वारे के लिए प्रसिद्ध पांवटा साहिब किस नदी के तट पर है?", ["यमुना", "सतलुज", "ब्यास", "रावी"], "सिरमौर जिले का पांवटा साहिब उत्तराखंड की सीमा पर यमुना नदी के तट पर स्थित है।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["What is the district headquarters of Kinnaur?", ["Kalpa", "Reckong Peo", "Sangla", "Nako"], "Reckong Peo is the headquarters of Kinnaur district. Kalpa is a nearby village famous for its views of Kinner Kailash."],
    ["किन्नौर जिले का मुख्यालय कहाँ है?", ["कल्पा", "रिकांगपिओ", "सांगला", "नाको"], "रिकांगपिओ किन्नौर जिले का मुख्यालय है। कल्पा पास का गाँव है जो किन्नर कैलाश के दृश्य के लिए प्रसिद्ध है।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["What is the district headquarters of Lahaul & Spiti?", ["Kaza", "Keylong", "Udaipur", "Tabo"], "Keylong is the headquarters of Lahaul & Spiti district. Kaza is the headquarters of the Spiti sub-division."],
    ["लाहौल-स्पीति जिले का मुख्यालय कहाँ है?", ["काज़ा", "केलांग", "उदयपुर", "ताबो"], "केलांग लाहौल-स्पीति जिले का मुख्यालय है। काज़ा स्पीति उपमंडल का मुख्यालय है।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["According to Census 2011, which district of Himachal Pradesh has the highest literacy rate?", ["Hamirpur", "Kangra", "Una", "Solan"], "Hamirpur has the highest literacy rate in the state, at about 89%. Chamba has one of the lowest."],
    ["जनगणना 2011 के अनुसार हिमाचल प्रदेश के किस जिले की साक्षरता दर सबसे अधिक है?", ["हमीरपुर", "कांगड़ा", "ऊना", "सोलन"], "हमीरपुर की साक्षरता दर राज्य में सबसे अधिक, लगभग 89% है। चंबा में यह सबसे कम में से एक है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["The Renuka Fair, in the month of November, is held at Renuka Ji in which district?", ["Kangra", "Mandi", "Kullu", "Sirmaur"], "The Renuka Fair, one of the state-level fairs, is held at Renuka Ji in Sirmaur district and is associated with Lord Parashurama and his mother Renuka."],
    ["नवंबर माह में लगने वाला रेणुका मेला रेणुका जी में किस जिले में आयोजित होता है?", ["कांगड़ा", "मंडी", "कुल्लू", "सिरमौर"], "राज्य-स्तरीय मेलों में गिना जाने वाला रेणुका मेला सिरमौर जिले के रेणुका जी में लगता है और भगवान परशुराम तथा उनकी माता रेणुका से जुड़ा है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The Bijli Mahadev temple, believed to be struck by lightning regularly, is located in which district?", ["Kullu", "Mandi", "Chamba", "Kinnaur"], "The Bijli Mahadev temple stands on a high hill near Kais, across the Beas from Kullu town, in Kullu district."],
    ["नियमित रूप से बिजली गिरने की मान्यता वाला बिजली महादेव मंदिर किस जिले में है?", ["कुल्लू", "मंडी", "चंबा", "किन्नौर"], "बिजली महादेव मंदिर कुल्लू जिले में कुल्लू नगर के सामने ब्यास के पार काइस के निकट ऊँची पहाड़ी पर स्थित है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The Chaurasi (84) temple complex is located at:", ["Bharmour (Chamba)", "Baijnath (Kangra)", "Sarahan (Shimla)", "Manali (Kullu)"], "The Chaurasi Temple complex at Bharmour, the old capital of Chamba, has 84 shrines and is considered a sacred place for Hindus."],
    ["चौरासी (84) मंदिर परिसर कहाँ स्थित है?", ["भरमौर (चंबा)", "बैजनाथ (कांगड़ा)", "सराहन (शिमला)", "मनाली (कुल्लू)"], "चंबा की पुरानी राजधानी भरमौर में स्थित चौरासी मंदिर परिसर में 84 मंदिर हैं और इसे हिंदुओं का पवित्र स्थल माना जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The naturally preserved mummy of a Buddhist monk at Gue village is located in which region?", ["Spiti", "Kinnaur", "Lahaul", "Kullu"], "The Gue mummy, believed to be over 500 years old, is preserved in Gue village of the Spiti valley, near the Indo-Tibetan border."],
    ["गुए गाँव में एक बौद्ध भिक्षु की प्राकृतिक रूप से संरक्षित ममी किस क्षेत्र में है?", ["स्पीति", "किन्नौर", "लाहौल", "कुल्लू"], "500 वर्ष से अधिक पुरानी मानी जाने वाली गुए की ममी भारत–तिब्बत सीमा के निकट स्पीति घाटी के गुए गाँव में संरक्षित है।"]),
  q(0, "hp-gk", "economy", "M", 1,
    ["The Karcham Wangtoo hydroelectric project on the Sutlej has a capacity of:", ["800 MW", "1,000 MW", "1,500 MW", "540 MW"], "The Karcham Wangtoo project in Kinnaur has an installed capacity of 1,000 MW (4 × 250 MW)."],
    ["सतलुज पर बनी करछम वांगतू जलविद्युत परियोजना की क्षमता कितनी है?", ["800 मेगावाट", "1,000 मेगावाट", "1,500 मेगावाट", "540 मेगावाट"], "किन्नौर की करछम वांगतू परियोजना की स्थापित क्षमता 1,000 मेगावाट (4 × 250 मेगावाट) है।"]),
  q(0, "hp-gk", "economy", "M", 0,
    ["Gaggal Airport serves which district of Himachal Pradesh?", ["Kangra", "Mandi", "Chamba", "Una"], "Gaggal Airport (Kangra Airport) is near Dharamshala in Kangra district."],
    ["गगल हवाई अड्डा हिमाचल प्रदेश के किस जिले में सेवाएँ देता है?", ["कांगड़ा", "मंडी", "चंबा", "ऊना"], "गगल हवाई अड्डा (कांगड़ा एयरपोर्ट) कांगड़ा जिले में धर्मशाला के निकट है।"]),
  q(0, "hp-gk", "polity-administration", "H", 1,
    ["How many seats are reserved for Scheduled Tribes in the Himachal Pradesh Vidhan Sabha?", ["2", "3", "5", "7"], "Three of the 68 seats are reserved for Scheduled Tribes (Kinnaur, Lahaul & Spiti and Bharmour), and 17 seats are reserved for Scheduled Castes."],
    ["हिमाचल प्रदेश विधानसभा में अनुसूचित जनजातियों के लिए कितनी सीटें आरक्षित हैं?", ["2", "3", "5", "7"], "68 में से 3 सीटें अनुसूचित जनजातियों (किन्नौर, लाहौल-स्पीति और भरमौर) के लिए तथा 17 सीटें अनुसूचित जातियों के लिए आरक्षित हैं।"]),
  q(0, "hp-gk", "polity-administration", "M", 3,
    ["Which of the following is NOT a Lok Sabha constituency of Himachal Pradesh?", ["Kangra", "Mandi", "Hamirpur", "Una"], "Himachal Pradesh has four Lok Sabha seats: Kangra, Mandi, Hamirpur and Shimla (reserved). Una is a district but not a constituency."],
    ["निम्नलिखित में से कौन-सा हिमाचल प्रदेश का लोकसभा निर्वाचन क्षेत्र नहीं है?", ["कांगड़ा", "मंडी", "हमीरपुर", "ऊना"], "हिमाचल प्रदेश में लोकसभा की चार सीटें हैं: कांगड़ा, मंडी, हमीरपुर और शिमला (आरक्षित)। ऊना जिला है, पर निर्वाचन क्षेत्र नहीं।"]),
];

export const hpGk2: PatwariQuestion[] = [
  q(0, "hp-gk", "history", "M", 1,
    ["Christ Church on the Ridge in Shimla, one of the oldest churches in North India, was built in:", ["1822", "1857", "1888", "1903"], "Christ Church, Shimla, was consecrated in 1857 and is a landmark of the Ridge."],
    ["शिमला के रिज पर स्थित क्राइस्ट चर्च, जो उत्तर भारत के सबसे पुराने चर्चों में है, कब बना?", ["1822", "1857", "1888", "1903"], "शिमला का क्राइस्ट चर्च 1857 में प्रतिष्ठित हुआ और रिज की पहचान है।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["The Viceregal Lodge (Rashtrapati Niwas) on Observatory Hill, Shimla, now houses the:", ["Indian Institute of Advanced Study", "Himachal Pradesh Vidhan Sabha", "High Court of Himachal Pradesh", "Indira Gandhi Medical College"], "The Viceregal Lodge was built in 1888 for Viceroy Lord Dufferin. Since 1965 it has housed the Indian Institute of Advanced Study."],
    ["शिमला की ऑब्ज़र्वेटरी हिल पर स्थित वायसरीगल लॉज (राष्ट्रपति निवास) में अब कौन-सा संस्थान है?", ["भारतीय उच्च अध्ययन संस्थान", "हिमाचल प्रदेश विधानसभा", "हिमाचल प्रदेश उच्च न्यायालय", "इंदिरा गांधी मेडिकल कॉलेज"], "वायसरीगल लॉज 1888 में वायसराय लॉर्ड डफ़रिन के लिए बना। 1965 से इसमें भारतीय उच्च अध्ययन संस्थान चल रहा है।"]),
  q(0, "hp-gk", "history", "M", 2,
    ["Himachal Pradesh University, Shimla, was established in the year:", ["1948", "1966", "1970", "1978"], "Himachal Pradesh University was established in 1970 at Summer Hill, Shimla."],
    ["हिमाचल प्रदेश विश्वविद्यालय, शिमला की स्थापना किस वर्ष हुई?", ["1948", "1966", "1970", "1978"], "हिमाचल प्रदेश विश्वविद्यालय की स्थापना 1970 में शिमला के समर हिल में हुई।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["The Shimla Conference of 1945, held to discuss Indian self-government, was called by Viceroy:", ["Lord Linlithgow", "Lord Wavell", "Lord Mountbatten", "Lord Irwin"], "Viceroy Lord Wavell called the Shimla Conference in June–July 1945, but it failed over the Muslim League's demand to nominate all Muslim members."],
    ["भारत के स्वशासन पर चर्चा हेतु 1945 का शिमला सम्मेलन किस वायसराय ने बुलाया था?", ["लॉर्ड लिनलिथगो", "लॉर्ड वेवेल", "लॉर्ड माउंटबेटन", "लॉर्ड इरविन"], "वायसराय लॉर्ड वेवेल ने जून–जुलाई 1945 में शिमला सम्मेलन बुलाया, पर मुस्लिम लीग द्वारा सभी मुस्लिम सदस्यों के नामांकन की माँग पर यह असफल रहा।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["The Shimla Agreement of 1972 was signed between India and Pakistan by:", ["Indira Gandhi and Ayub Khan", "Indira Gandhi and Zulfikar Ali Bhutto", "Lal Bahadur Shastri and Ayub Khan", "Rajiv Gandhi and Benazir Bhutto"], "After the 1971 war, Indira Gandhi and Zulfikar Ali Bhutto signed the Shimla Agreement at Barnes Court, Shimla, on 2 July 1972."],
    ["1972 का शिमला समझौता भारत और पाकिस्तान की ओर से किनके बीच हुआ?", ["इंदिरा गांधी और अयूब खान", "इंदिरा गांधी और ज़ुल्फ़िकार अली भुट्टो", "लाल बहादुर शास्त्री और अयूब खान", "राजीव गांधी और बेनज़ीर भुट्टो"], "1971 के युद्ध के बाद इंदिरा गांधी और ज़ुल्फ़िकार अली भुट्टो ने 2 जुलाई 1972 को शिमला के बार्न्स कोर्ट में समझौते पर हस्ताक्षर किए।"]),
  q(0, "hp-gk", "history", "H", 2,
    ["The princely state of Bilaspur (Kahlur) merged with Himachal Pradesh in the year:", ["1948", "1951", "1954", "1956"], "Bilaspur was initially a separate Part C state, and it merged with Himachal Pradesh on 1 July 1954, which is why its area is now a district."],
    ["बिलासपुर (कहलूर) रियासत का हिमाचल प्रदेश में विलय किस वर्ष हुआ?", ["1948", "1951", "1954", "1956"], "बिलासपुर पहले अलग भाग-ग राज्य था और 1 जुलाई 1954 को हिमाचल प्रदेश में मिला, इसीलिए आज यह एक जिला है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["The Kareri Lake, a popular trekking destination at the foot of the Dhauladhar range, is in:", ["Kangra", "Chamba", "Kullu", "Mandi"], "Kareri Lake lies in the Dhauladhar range in Kangra district, near Ghera and Dharamshala."],
    ["धौलाधार की तलहटी में ट्रेकिंग के लिए प्रसिद्ध करेरी झील किस जिले में है?", ["कांगड़ा", "चंबा", "कुल्लू", "मंडी"], "करेरी झील कांगड़ा जिले में धर्मशाला के निकट घेरा के पास धौलाधार श्रेणी में स्थित है।"]),
  q(0, "hp-gk", "geography", "H", 0,
    ["The Kalatop–Khajjiar Wildlife Sanctuary is located in which district?", ["Chamba", "Kangra", "Kullu", "Shimla"], "Kalatop–Khajjiar Wildlife Sanctuary lies near Dalhousie in Chamba district."],
    ["कालाटोप–खजियार वन्यजीव अभयारण्य किस जिले में स्थित है?", ["चंबा", "कांगड़ा", "कुल्लू", "शिमला"], "कालाटोप–खजियार वन्यजीव अभयारण्य चंबा जिले में डलहौज़ी के निकट स्थित है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["Nako Lake, a village lake at about 3,600 m, is in which district?", ["Lahaul & Spiti", "Kinnaur", "Chamba", "Kullu"], "Nako, a village with a small lake and ancient Buddhist temples, lies in the Hangrang valley of Kinnaur district."],
    ["लगभग 3,600 मी पर स्थित गाँव की झील नाको किस जिले में है?", ["लाहौल-स्पीति", "किन्नौर", "चंबा", "कुल्लू"], "छोटी झील और प्राचीन बौद्ध मंदिरों वाला नाको गाँव किन्नौर जिले की हांगरांग घाटी में है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["Chitkul, the last inhabited village on the Indo-Tibetan border in the Baspa valley, belongs to:", ["Lahaul & Spiti", "Kinnaur", "Kullu", "Chamba"], "Chitkul is the last inhabited village in the Baspa (Sangla) valley of Kinnaur, near the Tibet border."],
    ["बास्पा घाटी में भारत–तिब्बत सीमा का अंतिम बसा हुआ गाँव चितकुल किस जिले में है?", ["लाहौल-स्पीति", "किन्नौर", "कुल्लू", "चंबा"], "चितकुल किन्नौर की बास्पा (सांगला) घाटी का, तिब्बत सीमा के निकट, अंतिम बसा हुआ गाँव है।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["Kaza is the headquarters of which sub-division?", ["Spiti", "Pooh", "Nichar", "Kalpa"], "Kaza is the sub-divisional headquarters of Spiti and the biggest town of the Spiti valley."],
    ["काज़ा किस उपमंडल का मुख्यालय है?", ["स्पीति", "पूह", "निचार", "कल्पा"], "काज़ा स्पीति उपमंडल का मुख्यालय और स्पीति घाटी का सबसे बड़ा कस्बा है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["Which town is called 'Chhoti Kashi' (the Varanasi of the hills)?", ["Nahan", "Mandi", "Dharamshala", "Solan"], "Mandi is known as 'Chhoti Kashi' because of its many old temples along the Beas."],
    ["किस नगर को 'छोटी काशी' (पहाड़ों की वाराणसी) कहा जाता है?", ["नाहन", "मंडी", "धर्मशाला", "सोलन"], "ब्यास के तट पर अनेक प्राचीन मंदिरों के कारण मंडी को 'छोटी काशी' कहा जाता है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 0,
    ["Kullu town is situated at the confluence of the Beas and the:", ["Sarvari", "Parvati", "Tirthan", "Sainj"], "Kullu town lies where the Sarvari stream meets the Beas. The Parvati joins the Beas at Bhuntar, further south."],
    ["कुल्लू नगर ब्यास और किस नदी/नाले के संगम पर बसा है?", ["सरवरी", "पार्वती", "तीर्थन", "सैंज"], "कुल्लू नगर वहाँ बसा है जहाँ सरवरी ब्यास से मिलती है। पार्वती और आगे दक्षिण में भुंतर में ब्यास से मिलती है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 0,
    ["Rohru, an apple-growing town of Shimla district, lies on the bank of the river:", ["Pabbar", "Giri", "Baspa", "Tirthan"], "Rohru is on the Pabbar river, a tributary of the Tons, in the upper Shimla hills."],
    ["शिमला जिले का सेब उत्पादक कस्बा रोहड़ू किस नदी के तट पर है?", ["पब्बर", "गिरि", "बास्पा", "तीर्थन"], "रोहड़ू ऊपरी शिमला की पहाड़ियों में टौंस की सहायक नदी पब्बर के तट पर है।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["According to Census 2011, the population of Himachal Pradesh is approximately:", ["58.6 lakh", "68.6 lakh", "78.6 lakh", "88.6 lakh"], "Himachal Pradesh had a population of 68,64,602 (about 68.6 lakh) in the 2011 Census."],
    ["जनगणना 2011 के अनुसार हिमाचल प्रदेश की जनसंख्या लगभग कितनी है?", ["58.6 लाख", "68.6 लाख", "78.6 लाख", "88.6 लाख"], "2011 की जनगणना में हिमाचल प्रदेश की जनसंख्या 68,64,602 (लगभग 68.6 लाख) थी।"]),
  q(0, "hp-gk", "districts", "M", 2,
    ["According to Census 2011, the literacy rate of Himachal Pradesh is about:", ["72.5%", "78.4%", "82.8%", "89.0%"], "The state's literacy rate was 82.80% in 2011, above the national average of 74.04%."],
    ["जनगणना 2011 के अनुसार हिमाचल प्रदेश की साक्षरता दर लगभग कितनी है?", ["72.5%", "78.4%", "82.8%", "89.0%"], "2011 में राज्य की साक्षरता दर 82.80% थी, जो राष्ट्रीय औसत 74.04% से अधिक है।"]),
  q(0, "hp-gk", "districts", "H", 1,
    ["The sex ratio of Himachal Pradesh as per Census 2011 is:", ["950", "972", "985", "1,000"], "Himachal Pradesh has 972 females per 1,000 males (Census 2011), better than the national figure of 943."],
    ["जनगणना 2011 के अनुसार हिमाचल प्रदेश का लिंगानुपात कितना है?", ["950", "972", "985", "1,000"], "जनगणना 2011 में हिमाचल प्रदेश में प्रति 1,000 पुरुषों पर 972 महिलाएँ हैं, जो राष्ट्रीय आँकड़े 943 से बेहतर है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The famous painter Sobha Singh lived and worked at Andretta, a village in which district?", ["Kangra", "Mandi", "Kullu", "Chamba"], "Sobha Singh, known for his paintings of Sohni-Mahiwal and the Sikh Gurus, lived at Andretta in Kangra district."],
    ["प्रसिद्ध चित्रकार सोभा सिंह किस जिले के गाँव अंद्रेटा में रहे और कार्य किया?", ["कांगड़ा", "मंडी", "कुल्लू", "चंबा"], "सोहनी-महिवाल और सिख गुरुओं के चित्रों के लिए प्रसिद्ध सोभा सिंह कांगड़ा जिले के अंद्रेटा में रहते थे।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["Pragpur, declared India's first 'Heritage Village' in 2002, is in which district?", ["Kangra", "Hamirpur", "Una", "Bilaspur"], "Pragpur, with its old mansions and cobbled lanes, was declared a heritage village in 2002 and lies in Kangra district."],
    ["2002 में भारत का पहला 'धरोहर गाँव' घोषित हुआ प्रागपुर किस जिले में है?", ["कांगड़ा", "हमीरपुर", "ऊना", "बिलासपुर"], "पुरानी हवेलियों और पत्थर की गलियों वाला प्रागपुर 2002 में धरोहर गाँव घोषित हुआ और कांगड़ा जिले में है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["Kamru Fort, once the seat of the Bushahr rulers, is located in which valley?", ["Sangla valley", "Pin valley", "Tirthan valley", "Pangi valley"], "Kamru Fort, in Kinnaur's Sangla valley, was an early seat of the Bushahr rulers."],
    ["कभी बुशहर के शासकों की गद्दी रहा कामरू किला किस घाटी में है?", ["सांगला घाटी", "पिन घाटी", "तीर्थन घाटी", "पांगी घाटी"], "किन्नौर की सांगला घाटी में स्थित कामरू किला बुशहर के शासकों की आरंभिक राजधानी रहा।"]),
  q(0, "hp-gk", "economy", "M", 0,
    ["Palampur is known as the 'Tea Capital of North-West India'. It lies in which district?", ["Kangra", "Mandi", "Kullu", "Chamba"], "Palampur, with its tea gardens against the Dhauladhar range, is in Kangra district."],
    ["पालमपुर 'उत्तर-पश्चिम भारत की चाय राजधानी' कहलाता है। यह किस जिले में है?", ["कांगड़ा", "मंडी", "कुल्लू", "चंबा"], "धौलाधार की पृष्ठभूमि में चाय बागानों वाला पालमपुर कांगड़ा जिले में है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The International Mandi Shivratri Fair is held at which ground?", ["Paddal Maidan", "Dhalpur Maidan", "The Ridge", "Chaugan"], "The Mandi Shivratri fair is held at Paddal ground, where deities of the area gather in a colourful procession."],
    ["अंतरराष्ट्रीय मंडी शिवरात्रि मेला किस मैदान में आयोजित होता है?", ["पड्डल मैदान", "ढालपुर मैदान", "रिज मैदान", "चौगान"], "मंडी शिवरात्रि मेला पड्डल मैदान में लगता है, जहाँ क्षेत्र के देवी-देवता रंगारंग शोभायात्रा में एकत्र होते हैं।"]),
  q(0, "hp-gk", "economy", "M", 0,
    ["Paonta Sahib, an important industrial town of Himachal Pradesh, lies in which district?", ["Sirmaur", "Solan", "Una", "Bilaspur"], "Paonta Sahib in Sirmaur district has pharmaceutical, cement and paper industries."],
    ["हिमाचल प्रदेश का महत्वपूर्ण औद्योगिक नगर पांवटा साहिब किस जिले में है?", ["सिरमौर", "सोलन", "ऊना", "बिलासपुर"], "सिरमौर जिले के पांवटा साहिब में दवा, सीमेंट और कागज़ उद्योग हैं।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["IIT Mandi (at Kamand) was established in the year:", ["2005", "2009", "2012", "2015"], "IIT Mandi was set up in 2009 at Kamand, near Mandi."],
    ["IIT मंडी (कमांद में) की स्थापना किस वर्ष हुई?", ["2005", "2009", "2012", "2015"], "IIT मंडी की स्थापना 2009 में मंडी के निकट कमांद में हुई।"]),
  q(0, "hp-gk", "polity-administration", "M", 1,
    ["The Himachal Pradesh Board of School Education (HPBOSE) has its headquarters at:", ["Shimla", "Dharamshala", "Solan", "Hamirpur"], "HPBOSE, which conducts the Class 10 and 12 board examinations, is headquartered at Dharamshala."],
    ["10वीं और 12वीं की परीक्षाएँ आयोजित करने वाले हिमाचल प्रदेश स्कूल शिक्षा बोर्ड (HPBOSE) का मुख्यालय कहाँ है?", ["शिमला", "धर्मशाला", "सोलन", "हमीरपुर"], "HPBOSE का मुख्यालय धर्मशाला में है।"]),
];
