// HP Patwari subject tests: Reasoning 1 and 2 (25 questions each). All questions are new, not in the full mocks.

import { q, type PatwariQuestion } from "../types";

export const reasoning1: PatwariQuestion[] = [
  // Series (4)
  q(0, "reasoning", "series", "M", 2,
    ["Find the next number: 2, 3, 5, 9, 17, ?", ["31", "32", "33", "34"], "The differences are 1, 2, 4, 8, doubling each time. The next difference is 16, so 17 + 16 = 33."],
    ["अगली संख्या ज्ञात कीजिए: 2, 3, 5, 9, 17, ?", ["31", "32", "33", "34"], "अंतर 1, 2, 4, 8 हैं, जो हर बार दुगुने होते हैं। अगला अंतर 16 है, अतः 17 + 16 = 33।"], "17+16"),
  q(0, "reasoning", "series", "M", 2,
    ["Find the next number: 1, 2, 6, 24, 120, ?", ["600", "620", "720", "840"], "These are factorials: 1!, 2!, 3!, 4!, 5!. The next is 6! = 720."],
    ["अगली संख्या ज्ञात कीजिए: 1, 2, 6, 24, 120, ?", ["600", "620", "720", "840"], "ये क्रमगुणित (फैक्टोरियल) हैं: 1!, 2!, 3!, 4!, 5!। अगला 6! = 720 है।"], "720"),
  q(0, "reasoning", "series", "H", 1,
    ["Find the next number: 6, 11, 21, 41, 81, ?", ["151", "161", "171", "162"], "Each term is double the previous term minus 1: 6×2−1 = 11, 11×2−1 = 21, 21×2−1 = 41, 41×2−1 = 81, so next is 81×2−1 = 161."],
    ["अगली संख्या ज्ञात कीजिए: 6, 11, 21, 41, 81, ?", ["151", "161", "171", "162"], "प्रत्येक पद = पिछला पद × 2 − 1: 6×2−1 = 11, 11×2−1 = 21, 21×2−1 = 41, 41×2−1 = 81, अतः अगला 81×2−1 = 161।"], "81*2-1"),
  q(0, "reasoning", "series", "H", 1,
    ["Find the next letter: Z, X, U, Q, L, ?", ["E", "F", "G", "H"], "Positions are 26, 24, 21, 17, 12 (differences −2, −3, −4, −5). The next difference is −6, so 12 − 6 = 6, which is F."],
    ["अगला अक्षर ज्ञात कीजिए: Z, X, U, Q, L, ?", ["E", "F", "G", "H"], "अक्षरों के क्रमांक 26, 24, 21, 17, 12 हैं (अंतर −2, −3, −4, −5)। अगला अंतर −6 है, अतः 12 − 6 = 6 यानी F।"]),
  // Coding-decoding (3)
  q(0, "reasoning", "coding-decoding", "M", 0,
    ["If SCHOOL is coded as TDIPPM, how will STUDENT be coded?", ["TUVEFOU", "TUVDFOU", "TUVEFNU", "SUVEFOU"], "Each letter is moved one step forward: S→T, C→D, H→I, O→P, O→P, L→M. So S→T, T→U, U→V, D→E, E→F, N→O, T→U gives TUVEFOU."],
    ["यदि SCHOOL को TDIPPM लिखा जाता है, तो STUDENT को कैसे लिखा जाएगा?", ["TUVEFOU", "TUVDFOU", "TUVEFNU", "SUVEFOU"], "प्रत्येक अक्षर एक स्थान आगे बढ़ता है: S→T, C→D, H→I, O→P, O→P, L→M। अतः S→T, T→U, U→V, D→E, E→F, N→O, T→U से TUVEFOU बनता है।"]),
  q(0, "reasoning", "coding-decoding", "H", 0,
    ["In a code, FRIEND is written as HUMJTK (shifts +2, +3, +4, +5, +6, +7). How will ROSE be written using the same shifts in order?", ["TRWJ", "TRWK", "TSWJ", "URWJ"], "Apply +2, +3, +4, +5: R→T, O→R, S→W, E→J, giving TRWJ."],
    ["एक कोड में FRIEND को HUMJTK लिखा जाता है (अक्षर क्रमशः +2, +3, +4, +5, +6, +7 बदलते हैं)। उसी क्रम में ROSE को कैसे लिखा जाएगा?", ["TRWJ", "TRWK", "TSWJ", "URWJ"], "क्रम से +2, +3, +4, +5 लगाने पर: R→T, O→R, S→W, E→J, अतः TRWJ।"]),
  q(0, "reasoning", "coding-decoding", "H", 0,
    ["In a code, ROAD is written as SNBC (letters shift +1, −1, +1, −1). How will LAND be written?", ["MZOC", "MBOC", "MZND", "LZOC"], "Apply +1, −1, +1, −1: L→M, A→Z (one step back wraps around to Z), N→O, D→C, giving MZOC."],
    ["एक कोड में ROAD को SNBC लिखा जाता है (अक्षर +1, −1, +1, −1 बदलते हैं)। LAND को कैसे लिखा जाएगा?", ["MZOC", "MBOC", "MZND", "LZOC"], "+1, −1, +1, −1 लगाने पर: L→M, A→Z (एक स्थान पीछे जाने पर Z आता है), N→O, D→C, अतः MZOC।"]),
  // Blood relations (2)
  q(0, "reasoning", "blood-relations", "M", 0,
    ["A is B's brother. B is C's sister. D is C's father. How is A related to D?", ["Son", "Nephew", "Brother", "Uncle"], "A and C are B's siblings, so A and C are children of the same parents. D is C's father, so D is A's father and A is D's son."],
    ["A, B का भाई है। B, C की बहन है। D, C का पिता है। A का D से क्या संबंध है?", ["पुत्र", "भतीजा", "भाई", "चाचा"], "A और C, B के भाई-बहन हैं, अतः तीनों एक ही माता-पिता की संतान हैं। D, C का पिता है, इसलिए A का भी पिता है और A, D का पुत्र है।"]),
  q(0, "reasoning", "blood-relations", "M", 0,
    ["Pointing to a woman, Ravi says, 'She is the daughter of my father's only sister.' How is the woman related to Ravi?", ["Cousin", "Niece", "Sister", "Aunt"], "Ravi's father's sister is his aunt (bua). Her daughter is Ravi's cousin."],
    ["एक महिला की ओर संकेत करके रवि कहता है, 'यह मेरे पिता की इकलौती बहन की बेटी है।' उस महिला का रवि से क्या संबंध है?", ["चचेरी/बुआ की बेटी (कज़िन)", "भतीजी", "बहन", "बुआ"], "रवि के पिता की बहन उसकी बुआ है। बुआ की बेटी रवि की कज़िन (बुआ की बेटी) है।"]),
  // Direction sense (2)
  q(0, "reasoning", "direction-sense", "M", 1,
    ["Rita walks 6 km south and then turns east and walks 8 km. How far is she from her starting point?", ["8 km", "10 km", "12 km", "14 km"], "The path forms a right triangle with sides 6 and 8, so the distance = √(36 + 64) = 10 km."],
    ["रीता 6 किमी दक्षिण चलती है, फिर पूर्व की ओर मुड़कर 8 किमी चलती है। वह अपने प्रारंभिक बिंदु से कितनी दूर है?", ["8 किमी", "10 किमी", "12 किमी", "14 किमी"], "मार्ग 6 और 8 भुजाओं वाला समकोण त्रिभुज बनाता है, अतः दूरी = √(36 + 64) = 10 किमी।"], "Math.sqrt(36+64)"),
  q(0, "reasoning", "direction-sense", "H", 0,
    ["A person facing south turns 90° anticlockwise and then 45° clockwise. In which direction is he facing now?", ["South-East", "North-East", "South-West", "East"], "Facing south, a 90° anticlockwise turn gives east. A 45° clockwise turn from east gives south-east."],
    ["दक्षिण की ओर मुख किया हुआ एक व्यक्ति 90° वामावर्त और फिर 45° दक्षिणावर्त घूमता है। अब उसका मुख किस दिशा में है?", ["दक्षिण-पूर्व", "उत्तर-पूर्व", "दक्षिण-पश्चिम", "पूर्व"], "दक्षिण की ओर मुख होने पर 90° वामावर्त घूमने से पूर्व। पूर्व से 45° दक्षिणावर्त घूमने पर दक्षिण-पूर्व।"]),
  // Ranking (2)
  q(0, "reasoning", "ranking", "M", 3,
    ["In a class of 45 students, Suman's rank is 14th from the top. What is her rank from the bottom?", ["30th", "31st", "33rd", "32nd"], "Rank from the bottom = 45 − 14 + 1 = 32."],
    ["45 विद्यार्थियों की कक्षा में सुमन का स्थान ऊपर से 14वाँ है। नीचे से उसका स्थान क्या है?", ["30वाँ", "31वाँ", "33वाँ", "32वाँ"], "नीचे से स्थान = 45 − 14 + 1 = 32।"], "45-14+1"),
  q(0, "reasoning", "ranking", "H", 1,
    ["In a queue, Amit is 9th from the front and Sumit is 14th from the back. If there are 5 persons between them, how many persons are in the queue?", ["27", "28", "29", "30"], "Sumit is 9 + 5 + 1 = 15th from the front. Total = 15 + 14 − 1 = 28."],
    ["एक कतार में अमित आगे से 9वाँ और सुमित पीछे से 14वाँ है। यदि दोनों के बीच 5 व्यक्ति हैं, तो कतार में कुल कितने व्यक्ति हैं?", ["27", "28", "29", "30"], "सुमित आगे से 9 + 5 + 1 = 15वाँ है। कुल = 15 + 14 − 1 = 28।"], "9+5+1+14-1"),
  // Analogy (2)
  q(0, "reasoning", "analogy", "M", 1,
    ["5 : 26 :: 7 : ?", ["48", "50", "52", "56"], "The rule is n² + 1: 5² + 1 = 26, so 7² + 1 = 50."],
    ["5 : 26 :: 7 : ?", ["48", "50", "52", "56"], "नियम n² + 1 है: 5² + 1 = 26, अतः 7² + 1 = 50।"], "7*7+1"),
  q(0, "reasoning", "analogy", "M", 0,
    ["BAG : CBH :: FAN : ?", ["GBO", "GCO", "FBO", "GBN"], "Each letter moves one step forward: B→C, A→B, G→H. So F→G, A→B, N→O gives GBO."],
    ["BAG : CBH :: FAN : ?", ["GBO", "GCO", "FBO", "GBN"], "प्रत्येक अक्षर एक स्थान आगे: B→C, A→B, G→H। अतः F→G, A→B, N→O से GBO।"]),
  // Odd one out (2)
  q(0, "reasoning", "odd-one-out", "M", 2,
    ["Find the odd one out: 25, 36, 48, 64", ["25", "36", "48", "64"], "25 = 5², 36 = 6² and 64 = 8² are perfect squares. 48 is not."],
    ["असंगत (बेमेल) संख्या ज्ञात कीजिए: 25, 36, 48, 64", ["25", "36", "48", "64"], "25 = 5², 36 = 6² और 64 = 8² पूर्ण वर्ग हैं। 48 पूर्ण वर्ग नहीं है।"]),
  q(0, "reasoning", "odd-one-out", "M", 2,
    ["Find the odd one out: Mango, Apple, Potato, Banana", ["Mango", "Apple", "Potato", "Banana"], "Mango, apple and banana are fruits. Potato is a vegetable (a tuber)."],
    ["असंगत (बेमेल) शब्द ज्ञात कीजिए: आम, सेब, आलू, केला", ["आम", "सेब", "आलू", "केला"], "आम, सेब और केला फल हैं। आलू एक सब्ज़ी (कंद) है।"]),
  // Syllogism (2)
  q(0, "reasoning", "syllogism", "H", 2,
    ["Statements: All roses are flowers. All flowers are plants. Conclusions: I. All roses are plants. II. Some plants are roses.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "By transitivity, all roses are plants (I). Since all roses are plants, at least some plants are roses (II)."],
    ["कथन: सभी गुलाब फूल हैं। सभी फूल पौधे हैं। निष्कर्ष: I. सभी गुलाब पौधे हैं। II. कुछ पौधे गुलाब हैं।", ["केवल I अनुसरण करता है", "केवल II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I और न II अनुसरण करता है"], "संक्रमण से सभी गुलाब पौधे हैं (I)। चूँकि सभी गुलाब पौधे हैं, कम से कम कुछ पौधे गुलाब हैं (II)।"]),
  q(0, "reasoning", "syllogism", "H", 1,
    ["Statements: Some cats are dogs. Some dogs are rats. Conclusions: I. Some cats are rats. II. Some rats are dogs.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "'Some dogs are rats' converts to 'Some rats are dogs', so II follows. Two 'some' statements give no definite link between cats and rats, so I does not follow."],
    ["कथन: कुछ बिल्लियाँ कुत्ते हैं। कुछ कुत्ते चूहे हैं। निष्कर्ष: I. कुछ बिल्लियाँ चूहे हैं। II. कुछ चूहे कुत्ते हैं।", ["केवल I अनुसरण करता है", "केवल II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I और न II अनुसरण करता है"], "'कुछ कुत्ते चूहे हैं' का परिवर्तन 'कुछ चूहे कुत्ते हैं' होता है, अतः II सही है। दो 'कुछ' कथनों से बिल्ली और चूहे में निश्चित संबंध नहीं बनता, अतः I नहीं निकलता।"]),
  // Clock / calendar (2)
  q(0, "reasoning", "clock-calendar", "H", 1,
    ["India became independent on 15 August 1947. What was the day of the week?", ["Thursday", "Friday", "Saturday", "Sunday"], "15 August 1947 was a Friday."],
    ["भारत 15 अगस्त 1947 को स्वतंत्र हुआ। उस दिन सप्ताह का कौन-सा दिन था?", ["गुरुवार", "शुक्रवार", "शनिवार", "रविवार"], "15 अगस्त 1947 को शुक्रवार था।"]),
  q(0, "reasoning", "clock-calendar", "H", 1,
    ["At what time between 3 and 4 o'clock will the hands of a clock coincide?", ["15 min past 3", "16 4/11 min past 3", "17 min past 3", "16 min past 3"], "The hands coincide when the minute hand gains 90° over the hour hand at 5.5° per minute: 90 ÷ 5.5 = 16 4/11 minutes past 3."],
    ["3 और 4 बजे के बीच घड़ी की सुइयाँ किस समय एक-दूसरे पर आएँगी?", ["3 बजकर 15 मिनट", "3 बजकर 16 4/11 मिनट", "3 बजकर 17 मिनट", "3 बजकर 16 मिनट"], "मिनट की सुई घंटे की सुई से 5.5° प्रति मिनट की दर से आगे बढ़ती है और उसे 90° का अंतर पूरा करना है: 90 ÷ 5.5 = 16 4/11 मिनट, अर्थात 3 बजकर 16 4/11 मिनट।"]),
  // Inequality, Venn, operations, alphabet (4)
  q(0, "reasoning", "inequality", "H", 0,
    ["If P > Q ≥ R = S ≤ T, which of the following is definitely true?", ["P > S", "T > Q", "R < Q", "S ≥ P"], "P > Q ≥ R = S gives P > S. The other statements cannot be concluded from the given chain."],
    ["यदि P > Q ≥ R = S ≤ T है, तो निम्नलिखित में से कौन-सा निश्चित रूप से सत्य है?", ["P > S", "T > Q", "R < Q", "S ≥ P"], "P > Q ≥ R = S से P > S निकलता है। शेष कथन दी गई श्रृंखला से निश्चित रूप से नहीं निकलते।"]),
  q(0, "reasoning", "venn-diagram", "M", 1,
    ["In a class of 60 students, 35 like tea, 30 like coffee and 10 like both. How many students like neither?", ["3", "5", "7", "10"], "Students who like tea or coffee = 35 + 30 − 10 = 55. Those who like neither = 60 − 55 = 5."],
    ["60 विद्यार्थियों की कक्षा में 35 को चाय, 30 को कॉफ़ी और 10 को दोनों पसंद हैं। कितने विद्यार्थियों को दोनों में से कुछ भी पसंद नहीं?", ["3", "5", "7", "10"], "चाय या कॉफ़ी पसंद करने वाले = 35 + 30 − 10 = 55। दोनों में से कुछ नहीं पसंद करने वाले = 60 − 55 = 5।"], "60-(35+30-10)"),
  q(0, "reasoning", "math-operations", "H", 1,
    ["If '+' means '×', '×' means '−', '−' means '÷' and '÷' means '+', then 12 + 3 × 4 − 2 ÷ 5 = ?", ["37", "39", "41", "43"], "Replace the symbols: 12 × 3 − 4 ÷ 2 + 5 = 36 − 2 + 5 = 39."],
    ["यदि '+' का अर्थ '×', '×' का अर्थ '−', '−' का अर्थ '÷' और '÷' का अर्थ '+' है, तो 12 + 3 × 4 − 2 ÷ 5 = ?", ["37", "39", "41", "43"], "चिह्न बदलने पर: 12 × 3 − 4 ÷ 2 + 5 = 36 − 2 + 5 = 39।"], "12*3-4/2+5"),
  q(0, "reasoning", "alphabet-test", "H", 1,
    ["How many letters are there between the 8th letter from the left and the 12th letter from the right in the English alphabet?", ["5", "6", "7", "8"], "The 8th letter from the left is H. The 12th from the right is the 15th from the left, which is O. The letters between H and O are I, J, K, L, M, N: 6 letters."],
    ["अंग्रेज़ी वर्णमाला में बाएँ से 8वें और दाएँ से 12वें अक्षर के बीच कितने अक्षर हैं?", ["5", "6", "7", "8"], "बाएँ से 8वाँ अक्षर H है। दाएँ से 12वाँ अक्षर बाएँ से 15वाँ यानी O है। H और O के बीच I, J, K, L, M, N यानी 6 अक्षर हैं।"], "15-8-1"),
];

export const reasoning2: PatwariQuestion[] = [
  // Series (4)
  q(0, "reasoning", "series", "M", 2,
    ["Find the next number: 4, 6, 9, 13, 18, ?", ["22", "23", "24", "25"], "The differences are 2, 3, 4, 5. The next difference is 6, so 18 + 6 = 24."],
    ["अगली संख्या ज्ञात कीजिए: 4, 6, 9, 13, 18, ?", ["22", "23", "24", "25"], "अंतर 2, 3, 4, 5 हैं। अगला अंतर 6 है, अतः 18 + 6 = 24।"], "18+6"),
  q(0, "reasoning", "series", "H", 2,
    ["Find the next number: 3, 6, 18, 72, 360, ?", ["1,440", "1,800", "2,160", "2,520"], "The multipliers are 2, 3, 4, 5 in order. The next multiplier is 6, so 360 × 6 = 2,160."],
    ["अगली संख्या ज्ञात कीजिए: 3, 6, 18, 72, 360, ?", ["1,440", "1,800", "2,160", "2,520"], "गुणक क्रमशः 2, 3, 4, 5 हैं। अगला गुणक 6 है, अतः 360 × 6 = 2,160।"], "360*6"),
  q(0, "reasoning", "series", "H", 2,
    ["Find the next number: 1, 4, 10, 22, 46, ?", ["90", "92", "94", "96"], "Each term is double the previous term plus 2: 1×2+2 = 4, 4×2+2 = 10, 10×2+2 = 22, 22×2+2 = 46, so next is 46×2+2 = 94."],
    ["अगली संख्या ज्ञात कीजिए: 1, 4, 10, 22, 46, ?", ["90", "92", "94", "96"], "प्रत्येक पद = पिछला पद × 2 + 2: 1×2+2 = 4, 4×2+2 = 10, 10×2+2 = 22, 22×2+2 = 46, अतः अगला 46×2+2 = 94।"], "46*2+2"),
  q(0, "reasoning", "series", "M", 0,
    ["Find the next term: B2, D4, F6, H8, ?", ["J10", "J9", "K10", "I10"], "The letters move two steps each time (B, D, F, H, J) and the numbers rise by 2 (2, 4, 6, 8, 10). The next term is J10."],
    ["अगला पद ज्ञात कीजिए: B2, D4, F6, H8, ?", ["J10", "J9", "K10", "I10"], "अक्षर हर बार दो स्थान आगे बढ़ते हैं (B, D, F, H, J) और संख्याएँ 2 से बढ़ती हैं (2, 4, 6, 8, 10)। अगला पद J10 है।"]),
  // Coding-decoding (3)
  q(0, "reasoning", "coding-decoding", "M", 0,
    ["In a code, BLUE is written as CNXI (shifts +1, +2, +3, +4). How will RED be written using the same shifts in order?", ["SGG", "SGH", "TGG", "SFG"], "Apply +1, +2, +3: R→S, E→G, D→G, giving SGG."],
    ["एक कोड में BLUE को CNXI लिखा जाता है (अक्षर +1, +2, +3, +4 बदलते हैं)। उसी क्रम में RED को कैसे लिखा जाएगा?", ["SGG", "SGH", "TGG", "SFG"], "क्रम से +1, +2, +3 लगाने पर: R→S, E→G, D→G, अतः SGG।"]),
  q(0, "reasoning", "coding-decoding", "M", 0,
    ["If MOTHER is written as PRWKHU in a code (each letter moved 3 steps forward), how will FATHER be written?", ["IDWKHU", "IDWKGU", "HDWKHU", "IEWKHU"], "Add 3 to each letter: F→I, A→D, T→W, H→K, E→H, R→U, giving IDWKHU."],
    ["यदि किसी कोड में MOTHER को PRWKHU लिखा जाता है (प्रत्येक अक्षर 3 स्थान आगे), तो FATHER को कैसे लिखा जाएगा?", ["IDWKHU", "IDWKGU", "HDWKHU", "IEWKHU"], "प्रत्येक अक्षर में 3 जोड़ने पर: F→I, A→D, T→W, H→K, E→H, R→U, अतः IDWKHU।"]),
  q(0, "reasoning", "coding-decoding", "H", 0,
    ["In a code, SISTER is written as 535401 and UNCLE as 86790. How will CURSE be written in that code?", ["78150", "78510", "87150", "78105"], "From the two words: S=5, I=3, T=4, E=0, R=1, U=8, N=6, C=7, L=9. So C, U, R, S, E = 7, 8, 1, 5, 0, giving 78150."],
    ["किसी कोड में SISTER को 535401 और UNCLE को 86790 लिखा जाता है। उसी कोड में CURSE को कैसे लिखा जाएगा?", ["78150", "78510", "87150", "78105"], "दोनों शब्दों से: S=5, I=3, T=4, E=0, R=1, U=8, N=6, C=7, L=9। अतः C, U, R, S, E = 7, 8, 1, 5, 0 यानी 78150।"]),
  // Blood relations (2)
  q(0, "reasoning", "blood-relations", "M", 0,
    ["A's mother is B's sister. How is B related to A?", ["Maternal aunt (mausi)", "Paternal aunt (bua)", "Mother", "Cousin"], "A's mother's sister is A's maternal aunt, called 'mausi'."],
    ["A की माँ, B की बहन है। B का A से क्या संबंध है?", ["मौसी", "बुआ", "माँ", "चचेरी/ममेरी बहन"], "A की माँ की बहन, A की मौसी होती है।"]),
  q(0, "reasoning", "blood-relations", "H", 0,
    ["If 'A + B' means A is the father of B, 'A − B' means A is the sister of B and 'A × B' means A is the mother of B, which expression shows that P is the aunt (bua) of R?", ["P − Q + R", "P × Q − R", "P + Q − R", "P × Q + R"], "P − Q + R: P is the sister of Q and Q is the father of R, so P is R's father's sister, i.e. R's aunt. The others give mother, father and grandmother."],
    ["यदि 'A + B' का अर्थ है A, B का पिता है, 'A − B' का अर्थ है A, B की बहन है और 'A × B' का अर्थ है A, B की माँ है, तो कौन-सा व्यंजक दर्शाता है कि P, R की बुआ है?", ["P − Q + R", "P × Q − R", "P + Q − R", "P × Q + R"], "P − Q + R: P, Q की बहन है और Q, R का पिता है, अतः P, R के पिता की बहन यानी बुआ है। शेष व्यंजक माँ, पिता और दादी दर्शाते हैं।"]),
  // Direction sense (2)
  q(0, "reasoning", "direction-sense", "M", 1,
    ["A boy walks 5 m north and then turns west and walks 12 m. How far is he from his starting point?", ["11 m", "13 m", "15 m", "17 m"], "The distance = √(5² + 12²) = √169 = 13 m."],
    ["एक लड़का 5 मी उत्तर चलता है, फिर पश्चिम की ओर मुड़कर 12 मी चलता है। वह प्रारंभिक बिंदु से कितनी दूर है?", ["11 मी", "13 मी", "15 मी", "17 मी"], "दूरी = √(5² + 12²) = √169 = 13 मी।"], "Math.sqrt(25+144)"),
  q(0, "reasoning", "direction-sense", "H", 0,
    ["Amit walks 3 km east, turns left and walks 4 km, turns left again and walks 3 km, then turns left and walks 1 km. How far and in which direction is he from the starting point?", ["3 km North", "4 km North", "3 km South", "1 km North"], "East 3, North 4, West 3 brings him to 4 km north of the start. Turning left (south) for 1 km leaves him 3 km north."],
    ["अमित 3 किमी पूर्व चलता है, बाएँ मुड़कर 4 किमी चलता है, फिर बाएँ मुड़कर 3 किमी चलता है, फिर बाएँ मुड़कर 1 किमी चलता है। वह प्रारंभिक बिंदु से कितनी दूर और किस दिशा में है?", ["3 किमी उत्तर", "4 किमी उत्तर", "3 किमी दक्षिण", "1 किमी उत्तर"], "पूर्व 3, उत्तर 4, पश्चिम 3 चलने पर वह शुरुआत से 4 किमी उत्तर में पहुँचता है। बाएँ (दक्षिण) 1 किमी चलने पर वह 3 किमी उत्तर में रहता है।"]),
  // Ranking (2)
  q(0, "reasoning", "ranking", "M", 3,
    ["In a class of 50 students, Priya's rank is 18th from the top. What is her rank from the bottom?", ["31st", "32nd", "34th", "33rd"], "Rank from the bottom = 50 − 18 + 1 = 33."],
    ["50 विद्यार्थियों की कक्षा में प्रिया का स्थान ऊपर से 18वाँ है। नीचे से उसका स्थान क्या है?", ["31वाँ", "32वाँ", "34वाँ", "33वाँ"], "नीचे से स्थान = 50 − 18 + 1 = 33।"], "50-18+1"),
  q(0, "reasoning", "ranking", "M", 2,
    ["Among P, Q, R, S and T: P is taller than Q and R, S is taller than P, and T is shorter than Q. Who is the tallest?", ["P", "Q", "S", "T"], "S > P > Q, R and T < Q. So S is the tallest."],
    ["P, Q, R, S और T में: P, Q और R से लंबा है, S, P से लंबा है और T, Q से छोटा है। सबसे लंबा कौन है?", ["P", "Q", "S", "T"], "S > P > Q, R और T < Q। अतः S सबसे लंबा है।"]),
  // Analogy (2)
  q(0, "reasoning", "analogy", "M", 2,
    ["6 : 42 :: 7 : ?", ["49", "54", "56", "63"], "The rule is n × (n + 1): 6 × 7 = 42, so 7 × 8 = 56."],
    ["6 : 42 :: 7 : ?", ["49", "54", "56", "63"], "नियम n × (n + 1) है: 6 × 7 = 42, अतः 7 × 8 = 56।"], "7*8"),
  q(0, "reasoning", "analogy", "M", 0,
    ["AZ : ZA :: BY : ?", ["YB", "YA", "ZB", "XB"], "The letters of the pair are reversed: AZ becomes ZA, so BY becomes YB."],
    ["AZ : ZA :: BY : ?", ["YB", "YA", "ZB", "XB"], "युग्म के अक्षरों का क्रम उलट दिया गया है: AZ से ZA, अतः BY से YB।"]),
  // Odd one out (2)
  q(0, "reasoning", "odd-one-out", "M", 2,
    ["Find the odd one out: Shimla, Kullu, Manali, Dehradun", ["Shimla", "Kullu", "Dehradun", "Manali"], "Shimla, Kullu and Manali are in Himachal Pradesh. Dehradun is in Uttarakhand."],
    ["असंगत (बेमेल) शब्द ज्ञात कीजिए: शिमला, कुल्लू, मनाली, देहरादून", ["शिमला", "कुल्लू", "देहरादून", "मनाली"], "शिमला, कुल्लू और मनाली हिमाचल प्रदेश में हैं। देहरादून उत्तराखंड में है।"]),
  q(0, "reasoning", "odd-one-out", "M", 2,
    ["Find the odd one out: 23, 29, 33, 41", ["23", "29", "33", "41"], "23, 29 and 41 are prime numbers. 33 = 3 × 11 is composite."],
    ["असंगत (बेमेल) संख्या ज्ञात कीजिए: 23, 29, 33, 41", ["23", "29", "33", "41"], "23, 29 और 41 अभाज्य संख्याएँ हैं। 33 = 3 × 11 भाज्य संख्या है।"]),
  // Syllogism (2)
  q(0, "reasoning", "syllogism", "H", 0,
    ["Statements: Some mangoes are apples. All apples are fruits. Conclusions: I. Some mangoes are fruits. II. All fruits are apples.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "Those mangoes that are apples are also fruits, so I follows. Nothing says every fruit is an apple, so II does not follow."],
    ["कथन: कुछ आम सेब हैं। सभी सेब फल हैं। निष्कर्ष: I. कुछ आम फल हैं। II. सभी फल सेब हैं।", ["केवल I अनुसरण करता है", "केवल II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I और न II अनुसरण करता है"], "जो आम सेब हैं वे फल भी हैं, अतः I सही है। यह कहीं नहीं कहा गया कि हर फल सेब है, अतः II नहीं निकलता।"]),
  q(0, "reasoning", "syllogism", "H", 2,
    ["Statements: Some teachers are doctors. All doctors are engineers. Conclusions: I. Some teachers are engineers. II. Some engineers are doctors.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "The teachers who are doctors are engineers (I). All doctors are engineers, so some engineers are doctors (II). Both follow."],
    ["कथन: कुछ शिक्षक डॉक्टर हैं। सभी डॉक्टर इंजीनियर हैं। निष्कर्ष: I. कुछ शिक्षक इंजीनियर हैं। II. कुछ इंजीनियर डॉक्टर हैं।", ["केवल I अनुसरण करता है", "केवल II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I और न II अनुसरण करता है"], "जो शिक्षक डॉक्टर हैं वे इंजीनियर हैं (I)। सभी डॉक्टर इंजीनियर हैं, अतः कुछ इंजीनियर डॉक्टर हैं (II)। दोनों सही हैं।"]),
  // Clock / calendar (2)
  q(0, "reasoning", "clock-calendar", "M", 1,
    ["Today is Monday. What day of the week will it be after 61 days?", ["Friday", "Saturday", "Sunday", "Thursday"], "61 = 8 weeks + 5 days. Five days after Monday is Saturday."],
    ["आज सोमवार है। 61 दिन बाद सप्ताह का कौन-सा दिन होगा?", ["शुक्रवार", "शनिवार", "रविवार", "गुरुवार"], "61 = 8 सप्ताह + 5 दिन। सोमवार के 5 दिन बाद शनिवार होता है।"]),
  q(0, "reasoning", "clock-calendar", "H", 1,
    ["What is the angle between the hour hand and the minute hand of a clock at 7:20?", ["90°", "100°", "110°", "120°"], "Angle = |30 × 7 − 5.5 × 20| = |210 − 110| = 100°."],
    ["घड़ी में 7:20 बजे घंटे की सुई और मिनट की सुई के बीच कितने अंश का कोण होगा?", ["90°", "100°", "110°", "120°"], "कोण = |30 × 7 − 5.5 × 20| = |210 − 110| = 100°।"], "Math.abs(30*7-5.5*20)"),
  // Inequality, Venn, dice, operations (4)
  q(0, "reasoning", "inequality", "M", 0,
    ["If A ≥ B > C and C < D ≤ E, which of the following is definitely true?", ["A > C", "E > B", "D > A", "B ≥ D"], "A ≥ B > C gives A > C. The relation between B and D or E cannot be fixed from the statement."],
    ["यदि A ≥ B > C और C < D ≤ E है, तो निम्नलिखित में से कौन-सा निश्चित रूप से सत्य है?", ["A > C", "E > B", "D > A", "B ≥ D"], "A ≥ B > C से A > C निकलता है। B और D या E के बीच संबंध कथन से तय नहीं होता।"]),
  q(0, "reasoning", "venn-diagram", "M", 2,
    ["In a group of 100 persons, 60 speak Hindi, 45 speak English and 20 speak both. How many speak only Hindi?", ["30", "35", "40", "45"], "Only Hindi = 60 − 20 = 40."],
    ["100 व्यक्तियों के समूह में 60 हिंदी, 45 अंग्रेज़ी और 20 दोनों भाषाएँ बोलते हैं। केवल हिंदी बोलने वाले कितने हैं?", ["30", "35", "40", "45"], "केवल हिंदी = 60 − 20 = 40।"], "60-20"),
  q(0, "reasoning", "dice-cube", "H", 1,
    ["A cube painted red on all faces is cut into 27 equal small cubes. How many small cubes have exactly two faces painted?", ["8", "12", "6", "24"], "Cubes with exactly two painted faces lie on the edges, excluding corners: 12 edges × (3 − 2) = 12."],
    ["सभी फलकों पर लाल रंग किए गए एक घन को 27 बराबर छोटे घनों में काटा जाता है। कितने छोटे घनों के ठीक दो फलक रंगे होंगे?", ["8", "12", "6", "24"], "ठीक दो रंगे फलक वाले घन किनारों पर होते हैं (कोनों को छोड़कर): 12 किनारे × (3 − 2) = 12।"], "12*(3-2)"),
  q(0, "reasoning", "math-operations", "H", 1,
    ["If P means '+', Q means '−', R means '×' and S means '÷', then 24 S 6 R 5 P 2 Q 3 = ?", ["17", "19", "21", "23"], "Replace the letters: 24 ÷ 6 × 5 + 2 − 3 = 4 × 5 + 2 − 3 = 20 + 2 − 3 = 19."],
    ["यदि P का अर्थ '+', Q का अर्थ '−', R का अर्थ '×' और S का अर्थ '÷' है, तो 24 S 6 R 5 P 2 Q 3 = ?", ["17", "19", "21", "23"], "अक्षर बदलने पर: 24 ÷ 6 × 5 + 2 − 3 = 4 × 5 + 2 − 3 = 20 + 2 − 3 = 19।"], "24/6*5+2-3"),
];
