// HP Patwari subject tests: Revenue & Computer 1 and 2 (10 revenue-terms and 15 computer questions each).
// All questions are new, not in the full mocks. Options are balanced at seed time.

import { q, type PatwariQuestion } from "../types";

export const revenueComputer1: PatwariQuestion[] = [
  // Revenue and land records (10)
  q(0, "hp-gk", "revenue", "M", 0,
    ["In land records, the 'Khatauni' is:", ["A holding-wise list of the land held by each owner or cultivator", "A list of village roads", "A register of births and deaths", "The map of the village"], "The Khatauni groups the fields (khasra numbers) by holding, showing what land each owner or cultivator holds."],
    ["भू-अभिलेखों में 'खतौनी' क्या है?", ["प्रत्येक भू-स्वामी या काश्तकार की जोत के अनुसार भूमि की सूची", "गाँव की सड़कों की सूची", "जन्म-मृत्यु का रजिस्टर", "गाँव का नक्शा"], "खतौनी में खेत (खसरा नंबर) जोत के अनुसार समूहित होते हैं और दिखाया जाता है कि प्रत्येक स्वामी या काश्तकार के पास कितनी भूमि है।"]),
  q(0, "hp-gk", "revenue", "H", 0,
    ["In revenue records, the 'Khewat' is:", ["A list of the owners (proprietors) of a village along with their shares", "A crop inspection register", "A record of canal water use", "A list of village officials"], "The Khewat lists the owners of a village with their share in the land, and is the base from which the Khatauni is prepared."],
    ["राजस्व अभिलेखों में 'खेवट' क्या है?", ["गाँव के भू-स्वामियों की उनके हिस्सों सहित सूची", "फसल निरीक्षण का रजिस्टर", "नहर के पानी के उपयोग का अभिलेख", "गाँव के अधिकारियों की सूची"], "खेवट में गाँव के मालिकों की सूची उनके भूमि-हिस्सों के साथ होती है और खतौनी इसी के आधार पर तैयार की जाती है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["A 'Patwar circle' is:", ["A group of villages under the charge of one Patwari", "A circle drawn on a village map", "The office of the Tehsildar", "The area of one bank branch"], "A Patwar circle (halqa) is a group of neighbouring villages whose land records are kept by one Patwari."],
    ["'पटवार सर्कल' (हल्का) क्या है?", ["एक पटवारी के अधीन गाँवों का समूह", "गाँव के नक्शे पर बना घेरा", "तहसीलदार का कार्यालय", "एक बैंक शाखा का क्षेत्र"], "पटवार सर्कल (हल्का) पास-पास के गाँवों का समूह है जिनका भू-अभिलेख एक पटवारी रखता है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["Who is the head of a Tehsil in the revenue administration?", ["Tehsildar", "Kanungo", "Lambardar", "Patwari"], "A Tehsildar heads a tehsil and looks after land records, revenue collection and revenue courts in it."],
    ["राजस्व प्रशासन में तहसील का प्रमुख कौन होता है?", ["तहसीलदार", "कानूनगो", "लंबरदार", "पटवारी"], "तहसीलदार तहसील का प्रमुख होता है और वहाँ भू-अभिलेख, राजस्व वसूली तथा राजस्व न्यायालयों का कार्य देखता है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["The head of the revenue administration of a district is the:", ["Deputy Commissioner", "Tehsildar", "Sub-Divisional Magistrate", "Kanungo"], "The Deputy Commissioner (District Collector) heads the district administration, including revenue matters."],
    ["जिले के राजस्व प्रशासन का प्रमुख कौन होता है?", ["उपायुक्त (डिप्टी कमिश्नर)", "तहसीलदार", "उपमंडल मजिस्ट्रेट", "कानूनगो"], "उपायुक्त (जिला कलेक्टर) राजस्व सहित जिले के पूरे प्रशासन का प्रमुख होता है।"]),
  q(0, "hp-gk", "revenue", "M", 2,
    ["Which of the following is a Kharif crop?", ["Wheat", "Barley", "Maize", "Mustard"], "Kharif crops such as maize, rice and cotton are sown with the monsoon in June–July. Wheat, barley and mustard are Rabi crops."],
    ["निम्नलिखित में से कौन-सी खरीफ की फसल है?", ["गेहूँ", "जौ", "मक्का", "सरसों"], "मक्का, धान और कपास जैसी खरीफ फसलें जून–जुलाई में मानसून के साथ बोई जाती हैं। गेहूँ, जौ और सरसों रबी की फसलें हैं।"]),
  q(0, "hp-gk", "revenue", "H", 0,
    ["In land records, 'Nazul' land generally means:", ["Government-owned land not held by private owners for agriculture", "Land irrigated by canals", "Land that is waterlogged", "Land gifted to temples"], "Nazul land is land owned by the government, often in or near towns, that is not part of agricultural holdings and is usually leased out."],
    ["भू-अभिलेखों में 'नज़ूल' भूमि का सामान्यतः क्या अर्थ है?", ["सरकार की भूमि जो कृषि हेतु निजी स्वामियों के पास नहीं है", "नहर से सिंचित भूमि", "जलमग्न भूमि", "मंदिरों को दान दी गई भूमि"], "नज़ूल भूमि सरकार की भूमि होती है, प्रायः नगरों में या उनके निकट, जो कृषि जोतों का हिस्सा नहीं होती और आमतौर पर पट्टे पर दी जाती है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["'Barani' land is land that:", ["Depends only on rainfall for irrigation", "Is irrigated by wells", "Is irrigated by canals", "Has been left fallow for years"], "Barani (rain-fed) land has no artificial irrigation and depends on rainfall. Well-irrigated land is called Chahi and canal-irrigated land Nahri."],
    ["'बारानी' भूमि वह भूमि है जो:", ["सिंचाई के लिए केवल वर्षा पर निर्भर है", "कुओं से सिंचित है", "नहरों से सिंचित है", "वर्षों से परती पड़ी है"], "बारानी (वर्षा-आधारित) भूमि में कृत्रिम सिंचाई नहीं होती और यह वर्षा पर निर्भर है। कुएँ से सिंचित भूमि 'चाही' और नहर से सिंचित भूमि 'नहरी' कहलाती है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["The registration of a sale deed of land is done by the:", ["Sub-Registrar", "Patwari", "Kanungo", "Lambardar"], "Sale deeds and other documents transferring land are registered by the Sub-Registrar under the Registration Act, 1908."],
    ["भूमि के बैनामे (विक्रय-पत्र) का पंजीकरण कौन करता है?", ["उप-पंजीयक (सब-रजिस्ट्रार)", "पटवारी", "कानूनगो", "लंबरदार"], "भूमि के विक्रय-पत्र और अन्य हस्तांतरण-दस्तावेज़ पंजीकरण अधिनियम, 1908 के अंतर्गत उप-पंजीयक द्वारा पंजीकृत किए जाते हैं।"]),
  q(0, "hp-gk", "revenue", "H", 0,
    ["In the land measurement system used in Himachal Pradesh, 1 bigha is equal to:", ["20 biswa", "10 biswa", "16 biswa", "25 biswa"], "In the local system, 1 bigha = 20 biswa and 1 biswa = 20 biswansi."],
    ["हिमाचल प्रदेश में प्रचलित भूमि-माप प्रणाली में 1 बीघा कितने बिस्वा के बराबर होता है?", ["20 बिस्वा", "10 बिस्वा", "16 बिस्वा", "25 बिस्वा"], "स्थानीय प्रणाली में 1 बीघा = 20 बिस्वा और 1 बिस्वा = 20 बिस्वांसी होता है।"]),
  // Computer (15)
  q(0, "computer", "fundamentals", "M", 0,
    ["Who is known as the 'Father of the Computer'?", ["Charles Babbage", "Alan Turing", "John von Neumann", "Bill Gates"], "Charles Babbage designed the Analytical Engine in the 1830s, the first general-purpose mechanical computer design."],
    ["'कंप्यूटर के जनक' के रूप में किसे जाना जाता है?", ["चार्ल्स बैबेज", "एलन ट्यूरिंग", "जॉन वॉन न्यूमैन", "बिल गेट्स"], "चार्ल्स बैबेज ने 1830 के दशक में एनालिटिकल इंजन डिज़ाइन किया, जो पहला सामान्य-उद्देश्य यांत्रिक कंप्यूटर डिज़ाइन था।"]),
  q(0, "computer", "fundamentals", "M", 0,
    ["First-generation computers used which main electronic component?", ["Vacuum tubes", "Transistors", "Integrated circuits", "Microprocessors"], "First-generation computers (1940s–50s) used vacuum tubes. Transistors came in the second generation and ICs in the third."],
    ["प्रथम पीढ़ी के कंप्यूटरों में मुख्य इलेक्ट्रॉनिक घटक कौन-सा था?", ["वैक्यूम ट्यूब", "ट्रांजिस्टर", "इंटीग्रेटेड सर्किट", "माइक्रोप्रोसेसर"], "प्रथम पीढ़ी के कंप्यूटर (1940–50 के दशक) वैक्यूम ट्यूब का उपयोग करते थे। ट्रांजिस्टर दूसरी पीढ़ी में और IC तीसरी पीढ़ी में आए।"]),
  q(0, "computer", "hardware", "M", 0,
    ["What is the full form of ALU in a computer?", ["Arithmetic Logic Unit", "Advanced Logic Unit", "Arithmetic Local Unit", "Analytical Logic Unit"], "The ALU is the part of the CPU that performs arithmetic and logical operations."],
    ["कंप्यूटर में ALU का पूर्ण रूप क्या है?", ["Arithmetic Logic Unit", "Advanced Logic Unit", "Arithmetic Local Unit", "Analytical Logic Unit"], "ALU, CPU का वह भाग है जो अंकगणितीय और तार्किक संक्रियाएँ करता है।"]),
  q(0, "computer", "hardware", "M", 0,
    ["1 Megabyte (MB) is equal to:", ["1,024 KB", "1,000 KB", "512 KB", "2,048 KB"], "In computer memory, 1 MB = 1,024 KB and 1 GB = 1,024 MB."],
    ["1 मेगाबाइट (MB) किसके बराबर होता है?", ["1,024 KB", "1,000 KB", "512 KB", "2,048 KB"], "कंप्यूटर मेमोरी में 1 MB = 1,024 KB और 1 GB = 1,024 MB होता है।"]),
  q(0, "computer", "hardware", "M", 0,
    ["Which of the following is a pointing device?", ["Mouse", "Printer", "Speaker", "Monitor"], "A mouse is an input device used to point at and select items on the screen. The others are output devices."],
    ["निम्नलिखित में से कौन-सा पॉइंटिंग डिवाइस है?", ["माउस", "प्रिंटर", "स्पीकर", "मॉनिटर"], "माउस एक इनपुट डिवाइस है जिससे स्क्रीन पर वस्तुओं को इंगित और चुना जाता है। बाकी आउटपुट डिवाइस हैं।"]),
  q(0, "computer", "hardware", "H", 0,
    ["Cache memory is:", ["A small, very fast memory placed between the CPU and RAM", "A memory that permanently stores the operating system", "A backup storage on the hard disk", "A memory used only for graphics"], "Cache memory stores frequently used data and instructions close to the CPU, so the CPU does not have to wait for the slower RAM."],
    ["कैश मेमोरी क्या है?", ["CPU और RAM के बीच स्थित छोटी, बहुत तेज़ मेमोरी", "ऑपरेटिंग सिस्टम को स्थायी रूप से रखने वाली मेमोरी", "हार्ड डिस्क पर बैकअप स्टोरेज", "केवल ग्राफ़िक्स के लिए मेमोरी"], "कैश मेमोरी बार-बार प्रयोग होने वाले डेटा और निर्देशों को CPU के पास रखती है, ताकि CPU को धीमी RAM की प्रतीक्षा न करनी पड़े।"]),
  q(0, "computer", "shortcuts", "M", 0,
    ["Which keyboard shortcut makes the selected text bold in MS Word?", ["Ctrl + B", "Ctrl + I", "Ctrl + U", "Ctrl + P"], "Ctrl + B makes text bold, Ctrl + I italic, Ctrl + U underlined and Ctrl + P opens the print dialog."],
    ["MS Word में चुने हुए पाठ को बोल्ड करने का शॉर्टकट कौन-सा है?", ["Ctrl + B", "Ctrl + I", "Ctrl + U", "Ctrl + P"], "Ctrl + B से बोल्ड, Ctrl + I से इटैलिक, Ctrl + U से अंडरलाइन और Ctrl + P से प्रिंट डायलॉग खुलता है।"]),
  q(0, "computer", "ms-office", "M", 0,
    ["Which function in MS Excel returns the highest value in a range of cells?", ["MAX", "MIN", "AVERAGE", "COUNT"], "=MAX(A1:A10) returns the largest value in the range. MIN returns the smallest."],
    ["MS Excel का कौन-सा फ़ंक्शन सेल-श्रेणी का सबसे बड़ा मान देता है?", ["MAX", "MIN", "AVERAGE", "COUNT"], "=MAX(A1:A10) श्रेणी का सबसे बड़ा मान देता है। MIN सबसे छोटा मान देता है।"]),
  q(0, "computer", "ms-office", "M", 0,
    ["Which key starts a slide show from the beginning in MS PowerPoint?", ["F5", "F1", "F7", "F12"], "F5 starts the slide show from the first slide. Shift + F5 starts it from the current slide."],
    ["MS PowerPoint में स्लाइड शो को शुरू से चलाने की कुंजी कौन-सी है?", ["F5", "F1", "F7", "F12"], "F5 पहली स्लाइड से शो शुरू करता है। Shift + F5 वर्तमान स्लाइड से शुरू करता है।"]),
  q(0, "computer", "internet-networking", "M", 0,
    ["The World Wide Web (WWW) was invented by:", ["Tim Berners-Lee", "Vint Cerf", "Bill Gates", "Steve Jobs"], "Tim Berners-Lee invented the World Wide Web in 1989–91 at CERN. Vint Cerf is one of the fathers of the internet protocols."],
    ["वर्ल्ड वाइड वेब (WWW) का आविष्कार किसने किया?", ["टिम बर्नर्स-ली", "विंट सर्फ़", "बिल गेट्स", "स्टीव जॉब्स"], "टिम बर्नर्स-ली ने 1989–91 में CERN में वर्ल्ड वाइड वेब का आविष्कार किया। विंट सर्फ़ इंटरनेट प्रोटोकॉल के जनकों में से एक हैं।"]),
  q(0, "computer", "internet-networking", "M", 0,
    ["What is the full form of HTTP?", ["HyperText Transfer Protocol", "HyperText Transmission Program", "High Transfer Text Protocol", "HyperText Transport Process"], "HTTP is the protocol used to transfer web pages between a server and a browser."],
    ["HTTP का पूर्ण रूप क्या है?", ["HyperText Transfer Protocol", "HyperText Transmission Program", "High Transfer Text Protocol", "HyperText Transport Process"], "HTTP वह प्रोटोकॉल है जिससे सर्वर और ब्राउज़र के बीच वेब पेज स्थानांतरित होते हैं।"]),
  q(0, "computer", "internet-networking", "H", 0,
    ["Which protocol is used for sending e-mail?", ["SMTP", "FTP", "HTTP", "POP3"], "SMTP (Simple Mail Transfer Protocol) sends e-mail. POP3 and IMAP are used to receive it, and FTP transfers files."],
    ["ई-मेल भेजने के लिए कौन-सा प्रोटोकॉल प्रयोग होता है?", ["SMTP", "FTP", "HTTP", "POP3"], "SMTP (सिंपल मेल ट्रांसफर प्रोटोकॉल) ई-मेल भेजता है। POP3 और IMAP उसे प्राप्त करने के लिए और FTP फ़ाइलें भेजने के लिए प्रयोग होते हैं।"]),
  q(0, "computer", "operating-systems", "M", 0,
    ["Linux is:", ["An open-source operating system", "A word-processing package", "A web browser", "A programming language"], "Linux is a free and open-source operating system kernel, used in servers, desktops and Android."],
    ["Linux क्या है?", ["एक ओपन-सोर्स ऑपरेटिंग सिस्टम", "एक वर्ड-प्रोसेसिंग पैकेज", "एक वेब ब्राउज़र", "एक प्रोग्रामिंग भाषा"], "Linux एक मुफ़्त और ओपन-सोर्स ऑपरेटिंग सिस्टम कर्नेल है, जो सर्वर, डेस्कटॉप और एंड्रॉइड में प्रयोग होता है।"]),
  q(0, "computer", "security", "M", 0,
    ["A computer virus is:", ["A malicious program that copies itself and can damage files", "A hardware fault in the monitor", "A type of printer", "A network cable"], "A virus is malicious software that attaches to files, spreads by copying itself and can damage data."],
    ["कंप्यूटर वायरस क्या है?", ["एक हानिकारक प्रोग्राम जो स्वयं की प्रतियाँ बनाता है और फ़ाइलों को नुकसान पहुँचा सकता है", "मॉनिटर की हार्डवेयर खराबी", "एक प्रकार का प्रिंटर", "नेटवर्क केबल"], "वायरस हानिकारक सॉफ़्टवेयर है जो फ़ाइलों से जुड़कर अपनी प्रतियाँ बनाकर फैलता है और डेटा को नुकसान पहुँचा सकता है।"]),
  q(0, "computer", "hardware", "M", 0,
    ["Which of the following is a secondary storage device?", ["Hard disk", "RAM", "Cache", "Register"], "A hard disk stores data permanently and is a secondary storage. RAM, cache and registers are primary, fast, temporary storage."],
    ["निम्नलिखित में से कौन-सा द्वितीयक भंडारण (सेकंडरी स्टोरेज) उपकरण है?", ["हार्ड डिस्क", "RAM", "कैश", "रजिस्टर"], "हार्ड डिस्क डेटा को स्थायी रूप से रखती है और द्वितीयक भंडारण है। RAM, कैश और रजिस्टर प्राथमिक, तेज़ और अस्थायी भंडारण हैं।"]),
];

export const revenueComputer2: PatwariQuestion[] = [
  // Revenue and land records (10)
  q(0, "hp-gk", "revenue", "M", 0,
    ["The 'Shajra Kishtwar' is:", ["The village map showing every field with its number", "The family tree of the landowners", "The register of crop yields", "The list of taxpayers"], "The Shajra Kishtwar is the village field map on which each field is drawn and numbered. The family tree is the Shajra Nasab."],
    ["'शजरा किश्तवार' क्या है?", ["गाँव का वह नक्शा जिसमें हर खेत नंबर सहित दिखाया जाता है", "भू-स्वामियों का वंशवृक्ष", "फसल उपज का रजिस्टर", "करदाताओं की सूची"], "शजरा किश्तवार गाँव का खेतों का नक्शा है जिसमें प्रत्येक खेत बनाकर क्रमांकित किया जाता है। वंशवृक्ष को शजरा नसब कहते हैं।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["'Banjar' in land records means:", ["Uncultivated (barren) land", "Land with a standing crop", "Land irrigated by canal", "Land owned by a temple"], "Banjar is land that is not cultivated, either barren or left uncultivated for a long time."],
    ["भू-अभिलेखों में 'बंजर' का अर्थ है:", ["अकृषित (बिना जोती) भूमि", "खड़ी फसल वाली भूमि", "नहर से सिंचित भूमि", "मंदिर की भूमि"], "बंजर वह भूमि है जिस पर खेती नहीं होती, चाहे वह ऊसर हो या लंबे समय से बिना जोती पड़ी हो।"]),
  q(0, "hp-gk", "revenue", "H", 0,
    ["'Nahri' land is land that is irrigated by:", ["Canals", "Wells", "Rainfall only", "Hill streams (kuhls) only"], "Nahri land is canal-irrigated. Well-irrigated land is Chahi and rain-fed land is Barani."],
    ["'नहरी' भूमि किससे सिंचित होती है?", ["नहरों से", "कुओं से", "केवल वर्षा से", "केवल पहाड़ी नालों (कूहलों) से"], "नहरी भूमि नहरों से सिंचित होती है। कुएँ से सिंचित भूमि 'चाही' और वर्षा-आधारित भूमि 'बारानी' कहलाती है।"]),
  q(0, "hp-gk", "revenue", "H", 0,
    ["The 'Lal Lakir' in a village marks:", ["The boundary of the inhabited area (abadi) of the village", "A red line on a tax receipt", "The border between two districts", "The edge of a road"], "The Lal Lakir (red line) marks the inhabited area of a village. Land inside it is generally treated separately from agricultural land."],
    ["गाँव में 'लाल लकीर' किसे दर्शाती है?", ["गाँव की आबादी (बसे हुए क्षेत्र) की सीमा", "कर की रसीद पर लाल रेखा", "दो जिलों की सीमा", "सड़क का किनारा"], "लाल लकीर गाँव के बसे हुए क्षेत्र (आबादी) की सीमा दर्शाती है। इसके भीतर की भूमि को सामान्यतः कृषि भूमि से अलग माना जाता है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["'Settlement' (Bandobast) in the revenue system means:", ["Periodic revision of land records and assessment of land revenue", "Sale of government land", "Division of a joint holding", "Recovery of dues"], "A settlement is the periodic survey and revision of land records along with the fixing of land revenue."],
    ["राजस्व प्रणाली में 'बंदोबस्त' का अर्थ है:", ["भू-अभिलेखों का समय-समय पर पुनरीक्षण और भू-राजस्व का निर्धारण", "सरकारी भूमि की बिक्री", "संयुक्त जोत का बँटवारा", "बकाया की वसूली"], "बंदोबस्त में भूमि का समय-समय पर सर्वेक्षण, अभिलेखों का पुनरीक्षण और भू-राजस्व का निर्धारण किया जाता है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["The division of a jointly held piece of land among its co-sharers is called:", ["Batwara (partition)", "Intkal (mutation)", "Girdawari", "Bandobast"], "Batwara is the partition of a joint holding among the co-sharers. Intkal records a change of ownership."],
    ["किसी संयुक्त रूप से धारित भूमि का उसके सह-हिस्सेदारों में बँटवारा क्या कहलाता है?", ["बँटवारा (तक़सीम)", "इंतकाल (नामांतरण)", "गिरदावरी", "बंदोबस्त"], "बँटवारा संयुक्त जोत को सह-हिस्सेदारों में बाँटना है। इंतकाल स्वामित्व-परिवर्तन दर्ज करता है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["The head of a revenue Division (a group of districts) is the:", ["Divisional Commissioner", "Deputy Commissioner", "Tehsildar", "Kanungo"], "A Divisional Commissioner heads a division, which is a group of districts, and hears revenue appeals against district-level orders."],
    ["राजस्व मंडल (कई जिलों का समूह) का प्रमुख कौन होता है?", ["मंडलायुक्त (डिवीज़नल कमिश्नर)", "उपायुक्त", "तहसीलदार", "कानूनगो"], "मंडलायुक्त कई जिलों के समूह यानी मंडल का प्रमुख होता है और जिला-स्तर के आदेशों के विरुद्ध राजस्व अपीलें सुनता है।"]),
  q(0, "hp-gk", "revenue", "H", 0,
    ["How many revenue Divisions does Himachal Pradesh have?", ["3", "2", "4", "5"], "Himachal Pradesh has three revenue divisions: Shimla, Mandi and Kangra."],
    ["हिमाचल प्रदेश में कितने राजस्व मंडल हैं?", ["3", "2", "4", "5"], "हिमाचल प्रदेश में तीन राजस्व मंडल हैं: शिमला, मंडी और कांगड़ा।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["The daily diary maintained by a Patwari is called the:", ["Roznamcha", "Khasra", "Jamabandi", "Girdawari"], "The Patwari records daily events, such as mutations, inspections and crop reports, in the Roznamcha (daily diary)."],
    ["पटवारी द्वारा रखी जाने वाली दैनिक डायरी क्या कहलाती है?", ["रोज़नामचा", "खसरा", "जमाबंदी", "गिरदावरी"], "पटवारी इंतकाल, निरीक्षण और फसल-रिपोर्ट जैसी दैनिक घटनाएँ रोज़नामचे (दैनिक डायरी) में दर्ज करता है।"]),
  q(0, "hp-gk", "revenue", "M", 0,
    ["Which of the following is a Rabi crop?", ["Wheat", "Maize", "Rice", "Bajra"], "Rabi crops such as wheat, barley and mustard are sown in October–November and harvested in spring. Maize, rice and bajra are Kharif crops."],
    ["निम्नलिखित में से कौन-सी रबी की फसल है?", ["गेहूँ", "मक्का", "धान", "बाजरा"], "गेहूँ, जौ और सरसों जैसी रबी फसलें अक्टूबर–नवंबर में बोई जाती हैं और बसंत में कटती हैं। मक्का, धान और बाजरा खरीफ फसलें हैं।"]),
  // Computer (15)
  q(0, "computer", "fundamentals", "M", 0,
    ["Which was the first general-purpose electronic digital computer?", ["ENIAC", "UNIVAC", "EDSAC", "IBM PC"], "ENIAC (1946) is regarded as the first general-purpose electronic digital computer."],
    ["पहला सामान्य-उद्देश्य इलेक्ट्रॉनिक डिजिटल कंप्यूटर कौन-सा था?", ["ENIAC", "UNIVAC", "EDSAC", "IBM PC"], "ENIAC (1946) को पहला सामान्य-उद्देश्य इलेक्ट्रॉनिक डिजिटल कंप्यूटर माना जाता है।"]),
  q(0, "computer", "fundamentals", "M", 0,
    ["Second-generation computers used which main electronic component?", ["Transistors", "Vacuum tubes", "Integrated circuits", "Microprocessors"], "Second-generation computers (late 1950s–60s) replaced vacuum tubes with transistors."],
    ["द्वितीय पीढ़ी के कंप्यूटरों में मुख्य इलेक्ट्रॉनिक घटक कौन-सा था?", ["ट्रांजिस्टर", "वैक्यूम ट्यूब", "इंटीग्रेटेड सर्किट", "माइक्रोप्रोसेसर"], "द्वितीय पीढ़ी के कंप्यूटरों (1950 के दशक के अंत–1960 के दशक) में वैक्यूम ट्यूब की जगह ट्रांजिस्टर आए।"]),
  q(0, "computer", "hardware", "H", 0,
    ["Which part of the CPU fetches and decodes instructions and directs the other parts?", ["Control Unit", "Arithmetic Logic Unit", "Cache", "Register"], "The Control Unit fetches instructions from memory, decodes them and directs the ALU, memory and I/O devices."],
    ["CPU का कौन-सा भाग निर्देशों को लाता है, उन्हें डिकोड करता है और अन्य भागों को निर्देश देता है?", ["कंट्रोल यूनिट", "अंकगणित तर्क इकाई (ALU)", "कैश", "रजिस्टर"], "कंट्रोल यूनिट मेमोरी से निर्देश लाती है, उन्हें डिकोड करती है और ALU, मेमोरी तथा I/O उपकरणों को निर्देशित करती है।"]),
  q(0, "computer", "fundamentals", "H", 0,
    ["The decimal number 10 is written in the binary system as:", ["1010", "1100", "1001", "1110"], "10 = 8 + 2 = 1×2³ + 0×2² + 1×2¹ + 0×2⁰, so the binary number is 1010."],
    ["दशमलव संख्या 10 को द्विआधारी (बाइनरी) पद्धति में लिखा जाता है:", ["1010", "1100", "1001", "1110"], "10 = 8 + 2 = 1×2³ + 0×2² + 1×2¹ + 0×2⁰, अतः बाइनरी संख्या 1010 है।"], "Number((10).toString(2))"),
  q(0, "computer", "hardware", "M", 0,
    ["The BIOS program that starts a computer is stored in:", ["ROM", "RAM", "Hard disk", "Cache"], "The BIOS is stored in ROM (a non-volatile chip), so it is available as soon as the computer is switched on."],
    ["कंप्यूटर को शुरू करने वाला BIOS प्रोग्राम कहाँ संग्रहीत रहता है?", ["ROM", "RAM", "हार्ड डिस्क", "कैश"], "BIOS, ROM (अस्थायी न होने वाली चिप) में रहता है, इसलिए कंप्यूटर चालू होते ही उपलब्ध हो जाता है।"]),
  q(0, "computer", "shortcuts", "M", 0,
    ["Which keyboard shortcut selects all the content of a document?", ["Ctrl + A", "Ctrl + S", "Ctrl + Z", "Ctrl + X"], "Ctrl + A selects everything. Ctrl + S saves, Ctrl + Z undoes and Ctrl + X cuts."],
    ["दस्तावेज़ की संपूर्ण सामग्री चुनने का कीबोर्ड शॉर्टकट कौन-सा है?", ["Ctrl + A", "Ctrl + S", "Ctrl + Z", "Ctrl + X"], "Ctrl + A सब कुछ चुनता है। Ctrl + S सेव, Ctrl + Z अनडू और Ctrl + X कट करता है।"]),
  q(0, "computer", "ms-office", "H", 0,
    ["In MS Excel, which symbol is used to make a cell reference absolute (for example, $A$1)?", ["$", "#", "&", "@"], "The dollar sign fixes the column and/or row of a reference so it does not change when the formula is copied."],
    ["MS Excel में सेल संदर्भ को निरपेक्ष (absolute) बनाने के लिए (जैसे $A$1) किस चिह्न का प्रयोग होता है?", ["$", "#", "&", "@"], "डॉलर चिह्न संदर्भ के कॉलम और/या पंक्ति को स्थिर कर देता है, जिससे सूत्र कॉपी करने पर वह बदलता नहीं।"]),
  q(0, "computer", "ms-office", "M", 0,
    ["In MS Word, the default alignment of text in a new document is:", ["Left", "Centre", "Right", "Justified"], "By default, text in MS Word is left-aligned."],
    ["MS Word में नए दस्तावेज़ में पाठ का डिफ़ॉल्ट संरेखण क्या होता है?", ["बाएँ", "केंद्र", "दाएँ", "समान (जस्टिफाइड)"], "डिफ़ॉल्ट रूप से MS Word में पाठ बाएँ संरेखित होता है।"]),
  q(0, "computer", "internet-networking", "M", 0,
    ["An IP address is:", ["A unique numeric address of a device on a network", "The name of a website", "The password of a router", "The speed of an internet connection"], "An IP address, such as 192.168.1.1, identifies a device on a network."],
    ["IP एड्रेस क्या है?", ["नेटवर्क पर किसी डिवाइस का अद्वितीय संख्यात्मक पता", "वेबसाइट का नाम", "राउटर का पासवर्ड", "इंटरनेट कनेक्शन की गति"], "192.168.1.1 जैसा IP एड्रेस नेटवर्क पर किसी डिवाइस की पहचान कराता है।"]),
  q(0, "computer", "internet-networking", "M", 0,
    ["In e-mail, what does 'CC' stand for?", ["Carbon Copy", "Computer Copy", "Common Copy", "Central Copy"], "'CC' stands for Carbon Copy. Everyone in the CC list receives the message and can see the other recipients."],
    ["ई-मेल में 'CC' का पूर्ण रूप क्या है?", ["Carbon Copy", "Computer Copy", "Common Copy", "Central Copy"], "'CC' का पूर्ण रूप Carbon Copy है। CC सूची के सभी लोगों को संदेश मिलता है और वे अन्य प्राप्तकर्ताओं को देख सकते हैं।"]),
  q(0, "computer", "operating-systems", "M", 0,
    ["The process of starting a computer and loading the operating system is called:", ["Booting", "Formatting", "Compiling", "Scanning"], "Booting is the start-up process that loads the operating system into memory."],
    ["कंप्यूटर को चालू करके ऑपरेटिंग सिस्टम लोड करने की प्रक्रिया क्या कहलाती है?", ["बूटिंग", "फ़ॉर्मेटिंग", "कंपाइलिंग", "स्कैनिंग"], "बूटिंग वह आरंभिक प्रक्रिया है जिसमें ऑपरेटिंग सिस्टम मेमोरी में लोड होता है।"]),
  q(0, "computer", "security", "M", 0,
    ["A firewall is used to:", ["Filter network traffic and block unauthorised access", "Speed up the internet", "Store passwords", "Print documents"], "A firewall monitors incoming and outgoing network traffic and blocks what does not meet its security rules."],
    ["फ़ायरवॉल का उपयोग किसलिए होता है?", ["नेटवर्क ट्रैफ़िक को छानने और अनधिकृत पहुँच रोकने के लिए", "इंटरनेट की गति बढ़ाने के लिए", "पासवर्ड संग्रहीत करने के लिए", "दस्तावेज़ प्रिंट करने के लिए"], "फ़ायरवॉल आने-जाने वाले नेटवर्क ट्रैफ़िक की निगरानी करता है और सुरक्षा नियमों पर खरा न उतरने वाले ट्रैफ़िक को रोकता है।"]),
  q(0, "computer", "dbms", "M", 0,
    ["Which of the following is a database management software?", ["MS Access", "MS Word", "MS PowerPoint", "Notepad"], "MS Access is a database management system. Word, PowerPoint and Notepad are not."],
    ["निम्नलिखित में से कौन-सा डेटाबेस प्रबंधन सॉफ़्टवेयर है?", ["MS Access", "MS Word", "MS PowerPoint", "नोटपैड"], "MS Access एक डेटाबेस प्रबंधन प्रणाली है। Word, PowerPoint और Notepad नहीं हैं।"]),
  q(0, "computer", "hardware", "M", 0,
    ["What is the full form of USB?", ["Universal Serial Bus", "Unified Serial Bus", "Universal System Board", "United Serial Bus"], "USB stands for Universal Serial Bus, a standard port for connecting devices such as pen drives."],
    ["USB का पूर्ण रूप क्या है?", ["Universal Serial Bus", "Unified Serial Bus", "Universal System Board", "United Serial Bus"], "USB का पूर्ण रूप Universal Serial Bus है, जो पेन ड्राइव जैसे उपकरण जोड़ने का मानक पोर्ट है।"]),
  q(0, "computer", "programming-basics", "H", 0,
    ["Which translator converts a whole high-level program into machine code at once?", ["Compiler", "Interpreter", "Assembler", "Linker"], "A compiler translates the entire source program into machine code in one go. An interpreter translates and runs it line by line."],
    ["कौन-सा अनुवादक पूरे उच्च-स्तरीय प्रोग्राम को एक बार में मशीन कोड में बदलता है?", ["कंपाइलर", "इंटरप्रेटर", "असेंबलर", "लिंकर"], "कंपाइलर पूरे स्रोत प्रोग्राम को एक ही बार में मशीन कोड में बदलता है। इंटरप्रेटर उसे पंक्ति-दर-पंक्ति बदलकर चलाता है।"]),
];
