// HP Police Constable 2019 (Series D) — transcribed from the photographed question paper. No official key was available:
// answers were solved independently. Questions whose photo was unreadable or whose data was inconsistent are left out
// (original numbers 6, 13, 20-24, 28, 48, 53, 57-60, 70). Option order is kept as printed.
// Sections: 0 Himachal GK, 1 General Knowledge, 2 Reasoning, 3 Numerical Ability, 4 Hindi & English.

import { q, type PoliceQuestion } from "../police/types";

const DIR_EN =
  "Point B is 5 m west of point F. Point T is south of point F. The distance between B and F is 1 m more than the distance between T and F. Point R is 3 m east of T. Point P is 4 m west of point Y. Point G is 2 m north of P. Point Y is 6 m north of R. Point K is 4 m west of G.";
const DIR_HI =
  "बिंदु 'B', बिंदु 'F' के पश्चिम में 5 मीटर पर है। बिंदु 'T', बिंदु 'F' के दक्षिण में स्थित है। बिंदु 'B' और 'F' के बीच की दूरी, 'T' और 'F' के बीच की दूरी से 1 मीटर अधिक है। बिंदु 'R', 'T' के पूर्व की ओर 3 मीटर पर है। बिंदु 'P', बिंदु 'Y' के पश्चिम से 4 मीटर दूर है। बिंदु 'G', 'P' के उत्तर में 2 मीटर पर है। बिंदु 'Y', 'R' के उत्तर में 6 मीटर पर है। बिंदु 'K', 'G' के पश्चिम में 4 मीटर पर है।";
const DIR_X = "Take F as the origin: B(−5,0), T(0,−4), R(3,−4), Y(3,2), P(−1,2), G(−1,4), K(−5,4).";
const DIR_XH = "F को मूल बिंदु लें: B(−5,0), T(0,−4), R(3,−4), Y(3,2), P(−1,2), G(−1,4), K(−5,4)।";

export const y2019: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK ─────────
  q(0, "hp-gk", "history", "E", 3,
    ["Himachal Pradesh became the ______ state of the Indian Union.", ["15th", "16th", "17th", "18th"], "Himachal Pradesh was granted full statehood on 25 January 1971 and became the 18th state of India."],
    ["हिमाचल प्रदेश भारतीय संघ का ……… राज्य बना।", ["15वां", "16वां", "17वां", "18वां"], "25 जनवरी 1971 को हिमाचल प्रदेश को पूर्ण राज्य का दर्जा मिला और यह भारत का 18वां राज्य बना।"]),
  q(0, "hp-gk", "geography", "M", 0,
    ["Which is the largest glacier of Himachal?", ["Bara Shigri", "Bara Lacha", "Kunzum", "Gepang"], "Bara Shigri (about 28 km long, Lahaul-Spiti) is the largest glacier of Himachal Pradesh."],
    ["हिमाचल का सबसे बड़ा हिमखंड (ग्लेशियर) कौन सा है?", ["बारा शिगरी", "बारा लाचा", "कुंजुम", "ग्येपैंग"], "बारा शिगरी (लाहौल-स्पीति, लगभग 28 किमी लंबा) हिमाचल प्रदेश का सबसे बड़ा हिमखंड है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["What is the name of the world's highest polling station?", ["Kalimpong", "Tashigang", "Kaza", "Kibber"], "Tashigang in Spiti (about 15,256 ft) is recognised as the world's highest polling station."],
    ["दुनिया के सबसे ऊँचे मतदान केन्द्र का नाम क्या है?", ["कलिम्पोंग", "ताशीगांग", "काज़ा", "किब्बर"], "स्पीति का ताशीगांग (लगभग 15,256 फुट) दुनिया का सबसे ऊँचा मतदान केंद्र माना जाता है।"]),
  q(0, "hp-gk", "polity-administration", "M", 2,
    ["What is the name of the Himachal Government's health scheme giving treatment cover of up to ₹5 lakh?", ["Ayushman Bharat", "Ayushman Himachal", "HimCare Yojana", "Him Suraksha Yojana"], "HimCare is the Himachal Government's health insurance scheme (launched 2018) for cashless treatment of up to ₹5 lakh per family per year."],
    ["हिमाचल सरकार की 5 लाख तक की चिकित्सा सुविधा प्रदान करने वाली योजना का क्या नाम है?", ["आयुष्मान भारत", "आयुष्मान हिमाचल", "हिम केयर योजना", "हिम सुरक्षा योजना"], "हिमकेयर हिमाचल सरकार की स्वास्थ्य बीमा योजना (2018 से) है, जिसमें प्रति परिवार प्रति वर्ष 5 लाख रुपये तक का कैशलेस इलाज मिलता है।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["How many states share a border with Himachal Pradesh?", ["7", "6", "4", "None of these"], "Himachal borders Punjab, Haryana, Uttarakhand, Uttar Pradesh and Jammu & Kashmir — five states — so none of the numbers given is right."],
    ["हिमाचल प्रदेश से कितने राज्यों की सीमा जुड़ी हुई है?", ["7", "6", "4", "इनमें से कोई नहीं"], "हिमाचल की सीमा पंजाब, हरियाणा, उत्तराखंड, उत्तर प्रदेश और जम्मू-कश्मीर — पाँच राज्यों से लगती है, इसलिए दिए गए विकल्पों में से कोई सही नहीं।"]),

  // ───────── Section 1: General Knowledge ─────────
  q(1, "general-studies", "general-science", "E", 0,
    ["What is the unit of electric current?", ["Ampere", "Volt", "Ohm", "Watt"], "Current is measured in amperes (A). Volt is the unit of potential difference, ohm of resistance and watt of power."],
    ["धारा (current) की इकाई क्या है?", ["ऐम्पीयर", "वोल्ट", "ओह्म", "वॉट"], "विद्युत धारा की इकाई ऐम्पीयर (A) है। वोल्ट विभवांतर, ओह्म प्रतिरोध और वॉट शक्ति की इकाई है।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["A good conductor is one whose resistance is ______.", ["maximum", "minimum", "neither high nor low", "cannot be determined"], "A good conductor offers very low (minimum) resistance to the flow of current."],
    ["श्रेष्ठ चालक (conductor) वह होता है जिसकी प्रतिरोधकता ……. होती है।", ["अधिकतम", "न्यूनतम", "न तो अधिक और न ही कम", "परखा नहीं जा सकता"], "अच्छा चालक विद्युत धारा के प्रवाह में बहुत कम (न्यूनतम) प्रतिरोध उत्पन्न करता है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Polio is caused by:", ["Virus", "Bacteria", "Fungus", "Tapeworm"], "Polio (poliomyelitis) is a viral disease caused by the poliovirus."],
    ["पोलियो किसके द्वारा होता है?", ["वाइरस", "बैक्टीरिया", "फंगस", "टेपवर्म"], "पोलियो (पोलियोमाइलाइटिस) पोलियो वायरस से होने वाला विषाणुजनित रोग है।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["At what temperature do the Fahrenheit and Centigrade scales show the same value?", ["−40°", "45°", "40°", "−45°"], "Setting F = C in F = 9C/5 + 32 gives C = −40, so both scales read −40°."],
    ["किस तापमान पर दोनों Fahrenheit तथा Centigrade scale की समान value होती है?", ["−40°", "45°", "40°", "−45°"], "F = 9C/5 + 32 में F = C रखने पर C = −40 मिलता है, इसलिए दोनों पैमाने −40° दर्शाते हैं।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["Which of these food items is NOT a good source of calcium?", ["Ragi", "Milk", "Rice", "Egg"], "Ragi, milk and eggs are good calcium sources; rice contains very little calcium."],
    ["वह खाद्य पदार्थ जो कैल्शियम पोषण का अच्छा स्रोत नहीं है।", ["रागी", "दूध", "चावल", "अंडा"], "रागी, दूध और अंडा कैल्शियम के अच्छे स्रोत हैं; चावल में कैल्शियम बहुत कम होता है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Which planet is nearest to the Sun?", ["Mercury", "Venus", "Earth", "Mars"], "Mercury is the closest planet to the Sun."],
    ["सूर्य के सबसे नजदीक का ग्रह है।", ["बुध", "शुक्र", "पृथ्वी", "मंगल"], "बुध सूर्य के सबसे नज़दीक का ग्रह है।"]),
  q(1, "general-studies", "indian-geography", "M", 2,
    ["Which country has the largest reserves of natural gas in the world?", ["Iran", "Saudi Arabia", "Russia", "United Arab Emirates"], "Russia holds the world's largest proved natural gas reserves, followed by Iran and Qatar."],
    ["विश्व के किस देश में प्राकृतिक गैस का सर्वाधिक भंडार है?", ["ईरान", "सऊदी अरब", "रूस", "संयुक्त अरब अमीरात"], "विश्व में सिद्ध प्राकृतिक गैस का सबसे बड़ा भंडार रूस में है, उसके बाद ईरान और क़तर आते हैं।"]),
  q(1, "computer", "hardware", "M", 0,
    ["Which of the following memories has the least access time?", ["Cache memory", "Magnetic bubble memory", "Magnetic core memory", "RAM"], "Cache memory sits closest to the processor and is the fastest, so it has the least access time."],
    ["निम्न में से किस 'मैमोरी' में सबसे कम 'एक्सेस टाइम' रहता है?", ["कैशे मैमोरी", "मैग्नेटिक बबल मैमोरी", "मैग्नेटिक कोर मैमोरी", "रैम"], "कैशे मैमोरी प्रोसेसर के सबसे पास और सबसे तेज़ होती है, इसलिए इसका एक्सेस टाइम सबसे कम होता है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["In whom is the final authority to declare an Emergency vested?", ["Parliament", "President", "Council of Ministers", "Prime Minister"], "Under Articles 352, 356 and 360 the President proclaims an Emergency, on the written advice of the Union Cabinet."],
    ["आपात स्थिति की घोषणा करने का अंतिम अधिकार किसमें निहित है?", ["संसद", "राष्ट्रपति", "मंत्री परिषद", "प्रधान मंत्री"], "अनुच्छेद 352, 356 और 360 के अंतर्गत संघीय मंत्रिमंडल की लिखित सलाह पर राष्ट्रपति आपातकाल की घोषणा करता है।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["How many seats in the Lok Sabha are reserved for Scheduled Tribes?", ["27", "37", "47", "57"], "47 of the 543 Lok Sabha seats are reserved for Scheduled Tribes (84 for Scheduled Castes)."],
    ["लोक सभा में अनुसूचित जनजातियों के सदस्यों के लिए कितनी सीटें आरक्षित हैं?", ["27", "37", "47", "57"], "लोक सभा की 543 सीटों में से 47 अनुसूचित जनजातियों के लिए आरक्षित हैं (अनुसूचित जातियों के लिए 84)।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["Why are trees planted along river banks?", ["To stop floods", "To provide shade", "To reduce silting and erosion", "To control pollution"], "Tree roots bind the soil, reducing bank erosion and the silt carried into the river."],
    ["नदी के किनारे पौधे क्यों उगाए जाते हैं?", ["बाढ़ को रोकने के लिए", "छाया प्रदान करने के लिए", "सिल्ट और कटाव को कम करने के लिए", "प्रदूषण को नियंत्रित करने के लिए"], "पेड़ों की जड़ें मिट्टी को बाँधती हैं, जिससे नदी तट का कटाव और नदी में जमने वाली गाद कम होती है।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["The boundary between India and Pakistan was demarcated by:", ["Lord Mountbatten", "Sir Cyril Radcliffe", "Sir Stafford Cripps", "Lawrence"], "Sir Cyril Radcliffe headed the Boundary Commission whose 1947 Radcliffe Line divided India and Pakistan."],
    ["भारत और पाकिस्तान के बीच सीमा का सीमांकन किया था।", ["लॉर्ड माउंट बैटन ने", "सर सिरियल रेडक्लिफ ने", "सर स्टाफर्ड क्रिप्स ने", "लारेंस ने"], "सर सिरिल रेडक्लिफ की अध्यक्षता वाले सीमा आयोग ने 1947 में रेडक्लिफ रेखा खींचकर भारत-पाकिस्तान की सीमा तय की।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["Admiral ______ took over as the 24th Chief of the Indian Navy on 31 May 2019.", ["Karanjit Singh", "Karnveer Singh", "Karmjit Singh", "Karambir Singh"], "Admiral Karambir Singh became the 24th Chief of the Naval Staff on 31 May 2019."],
    ["एडमिरल ……… द्वारा 31 मई 2019 को भारतीय नौसेना के 24वें प्रमुख का कार्यभार ग्रहण किया:", ["करणजीत सिंह", "कर्णवीर सिंह", "कर्मजीत सिंह", "कर्मबीर सिंह"], "एडमिरल करमबीर सिंह ने 31 मई 2019 को नौसेना प्रमुख (24वें) का पद संभाला।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["What was the theme of World Environment Day 2019?", ["Beat Plastic Pollution", "Beat Air Pollution", "Beat Water Pollution", "Beat Soil Pollution"], "World Environment Day 2019 (hosted by China) had the theme 'Beat Air Pollution'. The 2018 theme was 'Beat Plastic Pollution'."],
    ["विश्व पर्यावरण दिवस 2019 की विषय-वस्तु (theme) क्या है?", ["प्लास्टिक प्रदूषण को मात देना", "वायु प्रदूषण को मात देना", "जल प्रदूषण को मात देना", "मिट्टी प्रदूषण को मात देना"], "विश्व पर्यावरण दिवस 2019 (मेज़बान चीन) की थीम 'वायु प्रदूषण को मात दें' थी। 2018 की थीम 'प्लास्टिक प्रदूषण को मात दें' थी।"]),

  // ───────── Section 2: Reasoning ─────────
  q(2, "reasoning", "series", "M", 1,
    ["What number will come in place of the question mark? 5, 6, 14, 45, 184, ?", ["885", "925", "985", "785"], "The pattern is ×1+1, ×2+2, ×3+3, ×4+4, ×5+5: 184 × 5 + 5 = 925."],
    ["निम्नलिखित श्रृंखला में प्रश्न चिन्ह के स्थान पर क्या आंकड़ा आएगा? 5, 6, 14, 45, 184, ?", ["885", "925", "985", "785"], "क्रम है ×1+1, ×2+2, ×3+3, ×4+4, ×5+5: 184 × 5 + 5 = 925।"]),
  q(2, "reasoning", "clock-calendar", "M", 1,
    ["1 January 2007 was a Monday. What day of the week will 1 January 2008 be?", ["Monday", "Tuesday", "Wednesday", "Sunday"], "2007 is not a leap year, so it has 365 days = 52 weeks + 1 day. The day moves one step ahead: Tuesday."],
    ["जनवरी 1, 2007 को सोमवार था। जनवरी 1, 2008 को सप्ताह का कौन सा दिन होगा?", ["सोमवार", "मंगलवार", "बुधवार", "रविवार"], "2007 लीप वर्ष नहीं है; 365 दिन = 52 सप्ताह + 1 दिन। इसलिए दिन एक आगे बढ़ जाता है: मंगलवार।"]),
  q(2, "reasoning", "direction-sense", "H", 1,
    [`${DIR_EN} — What is the distance and direction of point F with respect to point R?`, ["5 m north-east", "5 m north-west", "4 m south-east", "4 m north-east"], `${DIR_X} R(3,−4) to F(0,0): 3 m west and 4 m north, so F is 5 m (3-4-5 triangle) towards the north-west.`],
    [`${DIR_HI} — बिंदु 'R' के संबंध में बिंदु 'F' कितनी दूर और किस दिशा में है?`, ["5 मीटर उत्तर पूर्व", "5 मीटर उत्तर पश्चिम", "4 मीटर दक्षिण पूर्व", "4 मीटर उत्तर पूर्व"], `${DIR_XH} R(3,−4) से F(0,0): 3 मीटर पश्चिम और 4 मीटर उत्तर, इसलिए F, R से 5 मीटर उत्तर-पश्चिम में है।`]),
  q(2, "reasoning", "direction-sense", "H", 2,
    [`${DIR_EN} — What is the distance and direction of point K with respect to point B?`, ["5 m north", "4 m south", "4 m north", "3 m north-west"], `${DIR_X} K(−5,4) and B(−5,0) are on the same vertical line, so K is 4 m north of B.`],
    [`${DIR_HI} — बिंदु 'B' के संबंध में बिंदु 'K' कितनी दूर और किस दिशा में है?`, ["5 मीटर उत्तर", "4 मीटर दक्षिण", "4 मीटर उत्तर", "3 मीटर उत्तर-पश्चिम"], `${DIR_XH} K(−5,4) और B(−5,0) एक ही ऊर्ध्वाधर रेखा पर हैं, इसलिए K, B से 4 मीटर उत्तर में है।`]),
  q(2, "reasoning", "direction-sense", "H", 3,
    [`${DIR_EN} — In which direction is point F with respect to point P?`, ["South-west", "North-east", "North-west", "South-east"], `${DIR_X} P(−1,2) to F(0,0): 1 m east and 2 m south, so F is to the south-east of P.`],
    [`${DIR_HI} — बिंदु 'F', बिंदु 'P' के संबंध में किस दिशा में है?`, ["दक्षिण पश्चिम", "पूर्वोत्तर", "उत्तर पश्चिम", "दक्षिण-पूर्व"], `${DIR_XH} P(−1,2) से F(0,0): 1 मीटर पूर्व और 2 मीटर दक्षिण, इसलिए F, P के दक्षिण-पूर्व में है।`]),
  q(2, "reasoning", "series", "E", 3,
    ["Complete the given series: ZYX, YXW, XWV, ...?...", ["VUT", "XVU", "UVW", "WVU"], "Each group is the previous one shifted one letter back in the alphabet: ZYX → YXW → XWV → WVU."],
    ["दी गई श्रेणी को पूर्ण कीजिए: ZYX, YXW, XWV, ...?...", ["VUT", "XVU", "UVW", "WVU"], "हर समूह पिछले समूह से वर्णमाला में एक अक्षर पीछे खिसकता है: ZYX → YXW → XWV → WVU।"]),
  q(2, "reasoning", "coding-decoding", "M", 3,
    ["In a certain code 'MOMENT' is coded as 'OMOCPR'. How will 'THERMO' be coded in that code?", ["VFGQOM", "VFGPPM", "VEGPOM", "VFGPOM"], "The letters are shifted +2, −2, +2, −2, +2, −2. So T+2=V, H−2=F, E+2=G, R−2=P, M+2=O, O−2=M: VFGPOM."],
    ["किसी कूट (code) में 'MOMENT' को 'OMOCPR' कूटित (coded) किया गया है तो 'THERMO' को उसी कूट (code) में कैसे कूटित (coded) किया जाएगा?", ["VFGQOM", "VFGPPM", "VEGPOM", "VFGPOM"], "अक्षरों में क्रमशः +2, −2, +2, −2, +2, −2 का परिवर्तन है। T+2=V, H−2=F, E+2=G, R−2=P, M+2=O, O−2=M: VFGPOM।"]),
  q(2, "reasoning", "odd-one-out", "M", 2,
    ["Select the odd pair.", ["Army : General", "College : Principal", "Bus : Driver", "Team : Captain"], "In the other three pairs the second is the head or leader of the first (a group or institution); a driver operates a bus but does not head it."],
    ["विजातीय युग्म का चयन कीजिए।", ["सेना : जनरल", "महाविद्यालय : प्राचार्य", "बस : चालक", "टीम : कप्तान"], "अन्य तीनों युग्मों में दूसरा पद पहले (समूह/संस्था) का प्रमुख है; चालक बस चलाता है, उसका प्रमुख नहीं होता।"]),
  q(2, "reasoning", "blood-relations", "H", 3,
    ["Q's mother is P's sister and M's daughter. S is P's daughter and T's sister. What is M's relation to T?", ["Father", "Mother", "Son", "None of these"], "Q's mother and P are M's children. T is S's brother, so T is P's child. M is therefore T's grandparent — not father, mother or son."],
    ["'Q' की माता, 'P' की बहन है और 'M' की पुत्री है। 'S' पुत्री है 'P' की और 'T' की बहन है। M का 'T' के साथ क्या सम्बन्ध है?", ["पिता", "माता", "पुत्र", "इनमें से कोई नहीं।"], "Q की माता और P दोनों M की संतान हैं। T, S का भाई है, अतः P की संतान है। इस प्रकार M, T का दादा/नाना या दादी/नानी है — पिता, माता या पुत्र नहीं।"]),
  q(2, "reasoning", "coding-decoding", "M", 0,
    ["If bright is called black, black is called yellow, yellow is called red, red is called purple and purple is called sky blue, what is the colour of a ripe banana?", ["Red", "Purple", "Yellow", "Black"], "A ripe banana is yellow, and yellow is called red."],
    ["यदि चमक को काला कहा जाए; काले को पीला; पीले को लाल; लाल को जामुनी और जामुनी को आकाशी नीला कहा जाए तो बताइए कि पके हुए केले का कौन सा रंग है?", ["लाल", "जामुनी", "पीला", "काला"], "पका केला पीला होता है और पीले को लाल कहा गया है।"]),
  q(2, "reasoning", "direction-sense", "M", 3,
    ["A man is facing west. He turns 45° clockwise, then 180° in the same direction, and then 270° anticlockwise. Which direction is he facing now?", ["South", "North-west", "West", "South-west"], "West → 45° clockwise = north-west → 180° more = south-east → 270° anticlockwise (= 90° clockwise) = south-west."],
    ["एक पुरुष पश्चिम की ओर देख रहा है। वह 45° दक्षिणावर्त घूम जाता है तथा फिर 180° उसी दिशा में घूम जाता है और फिर 270° वामावर्त दिशा में घूमता है। अब वह किस दिशा की तरफ देख रहा है?", ["दक्षिण", "उत्तर-पश्चिम", "पश्चिम", "दक्षिण-पश्चिम"], "पश्चिम → 45° दक्षिणावर्त = उत्तर-पश्चिम → 180° और = दक्षिण-पूर्व → 270° वामावर्त (= 90° दक्षिणावर्त) = दक्षिण-पश्चिम।"]),
  q(2, "reasoning", "math-operations", "M", 2,
    ["If 'a' means '+', 'b' means '−', 'c' means '÷' and 'd' means '×', then 16a4b3c4d2 = ?", ["10", "17", "18.5", "21/2"], "16 + 4 − 3 ÷ 4 × 2 = 20 − (3/4 × 2) = 20 − 1.5 = 18.5 (division and multiplication first)."],
    ["यदि 'a' का मतलब '+', 'b' का मतलब '−', 'c' का मतलब '÷' तथा 'd' का मतलब '×' है तो 16a4b3c4d2 = ?", ["10", "17", "18.5", "21/2"], "16 + 4 − 3 ÷ 4 × 2 = 20 − (3/4 × 2) = 20 − 1.5 = 18.5 (पहले भाग और गुणा)।"]),

  // ───────── Section 3: Numerical Ability ─────────
  q(3, "quant", "speed-distance", "H", 0,
    ["Train A crosses a pole in 40 seconds and train B crosses it in 50 seconds. The length of train A is one-third of the length of train B. What is the ratio of the speed of A to the speed of B?", ["5:12", "5:3", "7:4", "13:7"], "Let B's length = 3L, so A's = L. Speed A = L/40, speed B = 3L/50. Ratio = (1/40) : (3/50) = 50 : 120 = 5 : 12."],
    ["A नामक रेलगाड़ी एक खम्बे को 40 सेकण्ड में पार कर लेती है। अन्य B नामक रेलगाड़ी उस खम्बे को 50 सेकण्ड में पार करती है। A रेलगाड़ी की लम्बाई, B रेलगाड़ी की लम्बाई की एक तिहाई (1/3) है। A रेलगाड़ी की गति B रेलगाड़ी की गति से क्या अनुपात (ratio) है?", ["5:12", "5:3", "7:4", "13:7"], "माना B की लंबाई 3L है, तो A की L। A की चाल = L/40, B की चाल = 3L/50। अनुपात = (1/40) : (3/50) = 50 : 120 = 5 : 12।"]),
  q(3, "quant", "interest", "M", 1,
    ["The compound interest on ₹7500 for 2 years is ₹927. What is the annual rate of interest in this calculation?", ["5.4%", "6%", "6.5%", "8%"], "Amount = 7500 + 927 = 8427. 8427 / 7500 = 1.1236 = (1.06)², so the rate is 6%."],
    ["रु. 7500 धनराशि का 2 वर्ष का चक्रवृद्धि ब्याज रू० 927 है। इस गणना में वार्षिक ब्याज दर क्या होगी?", ["5.4%", "6%", "6.5%", "8%"], "मिश्रधन = 7500 + 927 = 8427। 8427 / 7500 = 1.1236 = (1.06)², अतः दर 6% है।"]),
  q(3, "quant", "profit-loss", "M", 1,
    ["A trader sold an article at a 10% loss. Had he sold it for ₹107.10 more, he would have made a 20% profit. What will be the selling price if he wants a 30% profit?", ["₹264.20", "₹464.10", "₹564.30", "₹361.50"], "The extra ₹107.10 is 30% of the cost price, so CP = ₹357. For 30% profit: 357 × 1.3 = ₹464.10."],
    ["एक व्यापारी ने एक वस्तु को 10% हानि पर बेचा। यदि वह उस वस्तु को रु० 107.10 अधिक में बेचता तो उसे 20% लाभ होता। यदि उस वस्तु को 30% लाभ पर बेचना हो तो उसकी विक्रय राशि (selling price) क्या होगी?", ["रु० 264.20", "रु० 464.10", "रु० 564.30", "रु० 361.50"], "अतिरिक्त ₹107.10 क्रय मूल्य का 30% है, अतः क्रय मूल्य = ₹357। 30% लाभ पर: 357 × 1.3 = ₹464.10।"]),
  q(3, "quant", "simplification", "M", 2,
    ["Which number will come in place of the question mark? [√? ÷ 2⁴] × 512 = 288", ["9", "8", "81", "64"], "√? ÷ 16 = 288 / 512 = 0.5625, so √? = 9 and ? = 81."],
    ["प्रश्न चिन्ह के स्थान पर कौन-सा आंकड़ा आएगा? [√? ÷ 2⁴] × 512 = 288", ["9", "8", "81", "64"], "√? ÷ 16 = 288 / 512 = 0.5625, अतः √? = 9 और ? = 81।"]),
  q(3, "quant", "percentage", "M", 3,
    ["A magazine has 45 pages, each page has 30 lines and each line has 48 letters. If all this matter is copied into another notebook with 18 lines per page and 90 letters per line, the number of pages will be what percent more or less than in the old magazine?", ["12½% more", "33⅓% less", "25% less", "11⅑% less"], "Total letters = 45 × 30 × 48 = 64,800. New pages = 64,800 / (18 × 90) = 40. Decrease = 5/45 = 11⅑% less."],
    ["45 पृष्ठ की एक पत्रिका में हर पृष्ठ पर 30 पंक्तियां हैं तथा हर पंक्ति में 48 अक्षर हैं। यदि इस समस्त सामग्री को किसी दूसरी नोट बुक में लिखना हो जिसमें हर पृष्ठ पर 18 पंक्तियां हों तथा हर पंक्ति में 90 अक्षर हों तो नई नोटबुक में पुरानी पत्रिका की तुलना में कितने % पृष्ठ अधिक या कम होंगे?", ["12½% अधिक", "33⅓% कम", "25% कम", "11⅑% कम"], "कुल अक्षर = 45 × 30 × 48 = 64,800। नए पृष्ठ = 64,800 / (18 × 90) = 40। कमी = 5/45 = 11⅑% कम।"]),
  q(3, "quant", "percentage", "M", 0,
    ["Satish gave 30% of a certain sum to Rajneesh. Rajneesh spent 20% of it on books and 25% on a mobile phone. After these expenses Rajneesh had ₹26,400 left. How much money did Satish have at the start?", ["₹1,60,000", "₹1,60,850", "₹1,48,000", "₹1,74,000"], "Rajneesh has 55% of his share left = 26,400, so his share = 48,000. That is 30% of Satish's sum: 48,000 / 0.30 = ₹1,60,000."],
    ["सतीश द्वारा एक राशि विशेष का 30% धन, रजनीश को दिया गया। इस धनराशि में से रजनीश द्वारा 20% राशि किताबें खरीदने व 25% राशि मोबाइल फोन खरीदने पर खर्च कर दी गई। इन खर्चों के बाद रजनीश के पास रु. 26,400 बच गए। शुरूआत में सतीश के पास कितनी धन राशि थी?", ["1,60,000 रु०", "1,60,850 रु०", "1,48,000 रु०", "1,74,000 रु०"], "रजनीश के पास अपने हिस्से का 55% = 26,400 बचा, अतः हिस्सा = 48,000। यह सतीश की राशि का 30% है: 48,000 / 0.30 = ₹1,60,000।"]),
  q(3, "quant", "number-system", "M", 2,
    ["What is the least number that must be subtracted from 2486 so that a perfect square is obtained?", ["50", "36", "85", "65"], "49² = 2401 and 50² = 2500. The nearest square below 2486 is 2401, so subtract 2486 − 2401 = 85."],
    ["2486 की संख्या में से न्यूनतम किस संख्या को घटाया जाए ताकि एक शुद्ध वर्ग (perfect square) बनाया जा सके?", ["50", "36", "85", "65"], "49² = 2401 और 50² = 2500। 2486 से नीचे का निकटतम वर्ग 2401 है, अतः 2486 − 2401 = 85 घटाना होगा।"]),
  q(3, "quant", "time-work", "H", 2,
    ["Ram started a work and completed 60% of it in 18 days. To finish the rest, Ram took Shyam's help and together they completed it in 10 days. By what percent is Ram more efficient than Shyam?", ["300%", "250%", "400%", "150%"], "Ram does 60/18 = 10/3 % per day. The remaining 40% in 10 days is 4% per day together, so Shyam does 4 − 10/3 = 2/3 % per day. Ram : Shyam = 5 : 1, so Ram is 400% more efficient."],
    ["राम ने एक कार्य करना शुरू किया तथा 18 दिन कार्य करने के बाद 60% कार्य पूरा कर लिया। कार्य को पूरा करने के लिए राम ने श्याम की मदद ली तथा दोनों ने मिलकर 10 दिन में कार्य पूर्ण कर लिया। श्याम की तुलना में राम कितने % अधिक दक्ष (efficient) है?", ["300%", "250%", "400%", "150%"], "राम प्रतिदिन 60/18 = 10/3 % कार्य करता है। शेष 40% दोनों ने 10 दिन में किया, यानी 4% प्रतिदिन, इसलिए श्याम = 4 − 10/3 = 2/3 % प्रतिदिन। राम : श्याम = 5 : 1, अतः राम 400% अधिक दक्ष है।"]),

  // ───────── Section 4: Hindi & English ─────────
  q(4, "english", "vocabulary", "M", 2,
    ["For as long as I can remember, I have thought of myself as a teacher. However, in 1965 I decided to ___ (33) my hand at business. Choose the word that fits the blank.", ["use", "attempt", "try", "give"], "'Try one's hand at' is the fixed expression meaning to attempt something new."],
    ["Fill the blank (33): 'However, in 1965 I decided to ___ my hand at business.'", ["use", "attempt", "try", "give"], "'Try one's hand at' एक निश्चित मुहावरा है, जिसका अर्थ किसी नए काम को आज़माना है।"]),
  q(4, "english", "vocabulary", "M", 3,
    ["Fill the blank (34): 'So I ___ my father to allow me to set up a printing and packaging plant.'", ["prevailed", "appealed", "offered", "persuaded"], "'Persuaded someone to do something' fits; 'prevailed' and 'appealed' take different prepositions and do not fit the structure."],
    ["Fill the blank (34): 'So I ___ my father to allow me to set up a printing and packaging plant.'", ["prevailed", "appealed", "offered", "persuaded"], "'Persuade someone to do something' संरचना में सही बैठता है; 'prevailed' और 'appealed' के साथ अलग prepositions आते हैं।"]),
  q(4, "english", "vocabulary", "M", 1,
    ["Fill the blank (35): 'So I persuaded my father to allow me to ___ up a printing and packaging plant.'", ["built", "set", "try", "give"], "'Set up' means to establish a business or plant."],
    ["Fill the blank (35): 'So I persuaded my father to allow me to ___ up a printing and packaging plant.'", ["built", "set", "try", "give"], "'Set up' का अर्थ किसी व्यवसाय या संयंत्र की स्थापना करना है।"]),
  q(4, "english", "vocabulary", "M", 0,
    ["Fill the blank (36): 'I ___ the project proposal and applied for a loan.'", ["prepared", "thought", "extended", "stand"], "One 'prepares' a project proposal before applying for a loan."],
    ["Fill the blank (36): 'I ___ the project proposal and applied for a loan.'", ["prepared", "thought", "extended", "stand"], "ऋण के लिए आवेदन करने से पहले प्रोजेक्ट प्रस्ताव 'तैयार' (prepared) किया जाता है।"]),
  q(4, "english", "grammar", "M", 1,
    ["Fill the blank (37): 'Once it was approved, I went ___ the challenges of employing the right people.'", ["under", "through", "ahead", "for"], "'Went through the challenges' means faced and experienced them."],
    ["Fill the blank (37): 'Once it was approved, I went ___ the challenges of employing the right people.'", ["under", "through", "ahead", "for"], "'Went through the challenges' का अर्थ चुनौतियों का सामना करना है।"]),
  q(4, "english", "synonyms-antonyms", "E", 2,
    ["Choose the word closest in meaning to: DEVASTATE", ["Build", "Construct", "Destroy", "Compromise"], "Devastate means to destroy or ruin completely."],
    ["शब्द DEVASTATE का निकटतम अर्थ चुनिए।", ["Build", "Construct", "Destroy", "Compromise"], "Devastate का अर्थ पूरी तरह नष्ट या तबाह कर देना है।"]),
  q(4, "english", "synonyms-antonyms", "E", 3,
    ["Choose the word closest in meaning to: INDUCE", ["Destroy", "Prevent", "Discourage", "Persuade"], "Induce means to persuade or influence someone to do something."],
    ["शब्द INDUCE का निकटतम अर्थ चुनिए।", ["Destroy", "Prevent", "Discourage", "Persuade"], "Induce का अर्थ किसी को कुछ करने के लिए राज़ी करना या प्रेरित करना है।"]),
  q(4, "english", "synonyms-antonyms", "E", 2,
    ["Choose the word nearly opposite in meaning to: MITIGATE", ["Alleviate", "Assuage", "Increase", "Lessen"], "Mitigate means to make less severe; its opposite is 'increase'. Alleviate, assuage and lessen are its synonyms."],
    ["शब्द MITIGATE का विलोम चुनिए।", ["Alleviate", "Assuage", "Increase", "Lessen"], "Mitigate का अर्थ कम गंभीर करना है; विलोम 'Increase' है। Alleviate, assuage और lessen इसके पर्यायवाची हैं।"]),
  q(4, "english", "synonyms-antonyms", "E", 3,
    ["Choose the word nearly opposite in meaning to: ASSOCIATED", ["Correlated", "Identified", "Blend", "Separated"], "Associated means connected or joined; its opposite is 'separated'."],
    ["शब्द ASSOCIATED का विलोम चुनिए।", ["Correlated", "Identified", "Blend", "Separated"], "Associated का अर्थ जुड़ा हुआ है; विलोम 'Separated' है।"]),
  q(4, "english", "grammar", "E", 1,
    ["Fill in the blank with the appropriate preposition: I differ ______ you on this point.", ["of", "from", "for", "with"], "'Differ from someone on a point' is the standard usage (disagreement is also expressed as 'differ with', but 'from' is the keyed answer here)."],
    ["उपयुक्त preposition से रिक्त स्थान भरिए: I differ ______ you on this point.", ["of", "from", "for", "with"], "'Differ from' प्रचलित प्रयोग है ('differ with' भी असहमति के लिए आता है, परंतु यहाँ 'from' ही अपेक्षित उत्तर है)।"]),
  q(4, "english", "grammar", "E", 1,
    ["Fill in the blank with the appropriate preposition: The bullet missed his heart ______ two inches.", ["of", "by", "from", "at"], "'Missed by two inches' shows the margin of the miss."],
    ["उपयुक्त preposition से रिक्त स्थान भरिए: The bullet missed his heart ______ two inches.", ["of", "by", "from", "at"], "'Missed by two inches' चूकने के अंतर को दर्शाता है।"]),
  q(4, "english", "vocabulary", "M", 0,
    ["A type of poem containing 14 lines, each of 10 syllables, with a formal pattern of rhymes is called:", ["Sonnet", "Ode", "Limerick", "Ballad"], "A sonnet has 14 lines in iambic pentameter (10 syllables each) with a fixed rhyme scheme."],
    ["एक प्रकार की कविता जिसमें 14 पंक्तियाँ होती हैं, प्रत्येक में 10 अक्षर और एक निश्चित तुकांत विन्यास होता है, कहलाती है:", ["Sonnet", "Ode", "Limerick", "Ballad"], "सॉनेट में 14 पंक्तियाँ (प्रत्येक में 10 अक्षर) और निश्चित तुक-योजना होती है।"]),
  q(4, "english", "idioms", "M", 0,
    ["Which phrase should replace the phrase in BOLD to make the sentence grammatically correct? Richa could not solve the problem at all and was at HER WITS.", ["Her wits' end", "The wit's end", "Her witty end", "The wit end"], "The idiom is 'at one's wits' end', meaning completely out of ideas."],
    ["कौन सा phrase BOLD phrase की जगह लेने पर वाक्य को व्याकरण की दृष्टि से सही बनाएगा? Richa could not solve the problem at all and was at HER WITS.", ["Her wits' end", "The wit's end", "Her witty end", "The wit end"], "मुहावरा 'at one's wits' end' है, जिसका अर्थ पूरी तरह उपाय-रहित होना है।"]),
  q(4, "english", "grammar", "M", 2,
    ["Which phrase should replace the phrase in BOLD to make the sentence grammatically correct? To reduce costs, we should replace our current system BY MUCH EFFICIENT one.", ["Through more efficient", "Efficiently by", "With a more efficient", "For better efficiency"], "'Replace A with B' is the correct pattern, and 'a more efficient one' is the correct comparative form."],
    ["कौन सा phrase BOLD phrase की जगह लेने पर वाक्य को व्याकरण की दृष्टि से सही बनाएगा? To reduce costs, we should replace our current system BY MUCH EFFICIENT one.", ["Through more efficient", "Efficiently by", "With a more efficient", "For better efficiency"], "'Replace A with B' सही संरचना है, और 'a more efficient one' सही तुलनात्मक रूप है।"]),
  q(4, "english", "error-spotting", "M", 0,
    ["One of the four BOLD words is wrongly used. Find it: Many Indian firms have (A) ENTRY into (B) PARTNERSHIP with (C) FOREIGN firms of (D) LATE.", ["ENTRY", "PARTNERSHIP", "FOREIGN", "LATE"], "After 'have' the verb form 'entered' is required: 'have entered into partnerships with foreign firms of late'."],
    ["चार BOLD शब्दों में से एक गलत प्रयुक्त है। उसे पहचानिए: Many Indian firms have (A) ENTRY into (B) PARTNERSHIP with (C) FOREIGN firms of (D) LATE.", ["ENTRY", "PARTNERSHIP", "FOREIGN", "LATE"], "'have' के बाद क्रिया का रूप 'entered' आना चाहिए: 'have entered into partnerships with foreign firms of late'।"]),
  q(4, "english", "one-word", "E", 0,
    ["The one word for 'one who misuses money' is:", ["अपव्ययी (Spendthrift)", "मितव्ययी (Thrifty)", "अतृप्त (Unsatisfied)", "अधित्यका (Plateau)"], "A person who wastes or misuses money is an 'अपव्ययी' (spendthrift)."],
    ["'जो धन का दुरुपयोग करता हो' के लिए एक शब्द है-", ["अपव्ययी", "मितव्ययी", "अतृप्त", "अधित्यका"], "धन का दुरुपयोग (फ़िज़ूलखर्ची) करने वाले व्यक्ति को 'अपव्ययी' कहते हैं।"]),
  q(4, "hindi", "vyakaran", "M", 2,
    ["In the sentence 'The farmer is ploughing the field' (किसान खेत में हल चला रहा है), what is 'हल चलाना'?", ["Work (कार्य)", "Adjective (विशेषण)", "Verb (क्रिया)", "Adverb (क्रिया विशेषण)"], "'हल चलाना' is the action being performed, so it is a verb (क्रिया)."],
    ["'किसान खेत में हल चला रहा है'। इसमें हल चलाना क्या है?", ["कार्य", "विशेषण", "क्रिया", "क्रिया विशेषण"], "'हल चलाना' होने वाला कार्य-व्यापार है, अतः यह क्रिया है।"]),
  q(4, "hindi", "sandhi-samas", "M", 0,
    ["Split the sandhi of the word: गिरीश", ["गिरि + ईश", "गिरि + इश", "गिरी + इश", "गिरी + ईश"], "गिरि + ईश → गिरीश (दीर्घ स्वर संधि: इ + ई = ई)."],
    ["संधि विच्छेद करें: गिरीश", ["गिरि + ईश", "गिरि + इश", "गिरी + इश", "गिरी + ईश"], "गिरि + ईश → गिरीश (दीर्घ स्वर संधि: इ + ई = ई)।"]),
  q(4, "hindi", "sandhi-samas", "M", 2,
    ["Split the sandhi of the word: नायक", ["न + आयक", "ना + अयक", "नै + अक", "ना + अक"], "नै + अक → नायक (अयादि संधि: ऐ + अ = आय)."],
    ["संधि विच्छेद करें: नायक", ["न + आयक", "ना + अयक", "नै + अक", "ना + अक"], "नै + अक → नायक (अयादि संधि: ऐ + अ = आय)।"]),
  q(4, "hindi", "muhavare", "M", 1,
    ["What is meant by the idiom 'सर पर पैर रखकर भागना'?", ["To run showing one's back", "To flee in fear", "To run barefoot", "To win a running race"], "The idiom means to run away in a great hurry, typically out of fear."],
    ["'सर पर पैर रखकर भागना' से तात्पर्य है:-", ["पीठ दिखाकर भागना", "डर कर भाग जाना", "नंगे पैर दौड़ना", "दौड़ प्रतियोगिता जीतना"], "मुहावरे का अर्थ है बहुत जल्दी में, प्रायः डरकर, भाग जाना।"]),
  q(4, "hindi", "muhavare", "M", 1,
    ["What is meant by the idiom 'काटो तो खून नहीं'?", ["To freeze in the cold", "To be ashamed", "To cut suddenly", "To do magic"], "The idiom describes being stunned, frozen with shame, fear or shock; of the options, being ashamed is the closest."],
    ["'काटो तो खून नहीं' से तात्पर्य है:-", ["ठण्ड में जम जाना", "शर्मिन्दा होना", "झटके से काटना", "जादू करना"], "मुहावरा शर्म, भय या सदमे से सन्न रह जाने की स्थिति बताता है; दिए विकल्पों में 'शर्मिन्दा होना' निकटतम है।"]),
  q(4, "hindi", "vyakaran", "M", 0,
    ["Choose the correct feminine form of: विद्वान", ["विदुषी", "विदुशी", "विदुषि", "विदुशि"], "The feminine of 'विद्वान' is 'विदुषी'."],
    ["निम्न का सही लिंग परिवर्तन करें: विद्वान", ["विदुषी", "विदुशी", "विदुषि", "विदुशि"], "'विद्वान' का स्त्रीलिंग 'विदुषी' है।"]),
  q(4, "hindi", "paryay-vilom", "M", 2,
    ["Choose the antonym of the given word: ऊसर (barren)", ["अग्रभावी", "आर्द्र", "उर्वर", "ग्रीष्म"], "'ऊसर' means barren land; its antonym is 'उर्वर' (fertile)."],
    ["दिए गए शब्द का विलोम शब्द छांटिए: ऊसर", ["अग्रभावी", "आर्द्र", "उर्वर", "ग्रीष्म"], "'ऊसर' का अर्थ बंजर भूमि है; विलोम 'उर्वर' (उपजाऊ) है।"]),
  q(4, "hindi", "paryay-vilom", "E", 2,
    ["Choose the antonym of the given word: दुर्लभ (rare)", ["अलभ", "अगम्य", "सुलभ", "कठिन"], "'दुर्लभ' (hard to get) has the antonym 'सुलभ' (easy to get)."],
    ["दिए गए शब्द का विलोम शब्द छांटिए: दुर्लभ", ["अलभ", "अगम्य", "सुलभ", "कठिन"], "'दुर्लभ' (कठिनाई से मिलने वाला) का विलोम 'सुलभ' (आसानी से मिलने वाला) है।"]),
  q(4, "hindi", "paryay-vilom", "M", 1,
    ["Which of these is NOT a synonym of the given word: उत्तम (excellent)?", ["सर्वश्रेष्ठ", "प्रथम", "अनुपम", "बढ़िया"], "सर्वश्रेष्ठ, अनुपम and बढ़िया all express excellence; 'प्रथम' means 'first' and is not a synonym."],
    ["दिए गए शब्द का कौन-सा शब्द पर्यायवाची नहीं है: उत्तम", ["सर्वश्रेष्ठ", "प्रथम", "अनुपम", "बढ़िया"], "सर्वश्रेष्ठ, अनुपम और बढ़िया उत्कृष्टता बताते हैं; 'प्रथम' का अर्थ 'पहला' है, यह पर्यायवाची नहीं।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Which of these is NOT a synonym of the given word: दीपक (lamp)?", ["चिराग", "प्रदीप", "दीया", "प्रकाश"], "चिराग, प्रदीप and दीया all mean a lamp; 'प्रकाश' means light, not the lamp itself."],
    ["दिए गए शब्द का कौन-सा शब्द पर्यायवाची नहीं है: दीपक", ["चिराग", "प्रदीप", "दीया", "प्रकाश"], "चिराग, प्रदीप और दीया दीपक के पर्याय हैं; 'प्रकाश' रोशनी है, स्वयं दीपक नहीं।"]),
];
