// HP Police Constable 2017 (Code C-10/2017, Series C) — transcribed from the photographed question paper, which covers questions 1-80.
// No official key was available (the photo carries a candidate's pen marks, which were not trusted): answers were solved
// independently. Left out because the photo or the question was unclear, ambiguous or out of date (original numbers 4, 14-16, 19, 29, 31,
// 35-39, 49, 52, 53, 59, 68, 69). Option order is kept as printed.
// Sections: 0 Himachal GK, 1 General Knowledge, 2 Reasoning, 3 Numerical Ability, 4 Hindi & English.

import { q, type PoliceQuestion } from "../police/types";

export const y2017: PoliceQuestion[] = [
  q(4, "english", "grammar", "M", 0,
    ["How is the word ‘enough’ used in these two sentences? (i) There is time ‘enough’ and to spare. (ii) You know well ‘enough’ what I mean", ["Adjective & Adverb", "Noun & Verb", "Conjunction & Preposition", "Adverb & Preposition"], "In (i) 'enough' qualifies the noun 'time' (adjective); in (ii) it modifies 'well' (adverb)."],
    ["इन दो वाक्यों में शब्द ‘enough’ का प्रयोग कैसे हुआ है? (i) There is time ‘enough’ and to spare. (ii) You know well ‘enough’ what I mean", ["विशेषण और क्रिया-विशेषण", "संज्ञा और क्रिया", "समुच्चयबोधक और संबंधबोधक", "क्रिया-विशेषण और संबंधबोधक"], "(i) में 'enough' संज्ञा 'time' की विशेषता बताता है (विशेषण); (ii) में 'well' की (क्रिया-विशेषण)।"]),
  q(4, "english", "vocabulary", "M", 2,
    ["Public declaration of principles and policy by a political party, ruler, etc.", ["Promise", "Advertisement", "Manifesto", "Blue book"], "A public statement of a party's principles and policy is a manifesto."],
    ["किसी राजनीतिक दल, शासक आदि द्वारा सिद्धांतों और नीति की सार्वजनिक घोषणा:", ["वादा", "विज्ञापन", "घोषणा-पत्र (Manifesto)", "ब्लू बुक"], "किसी दल के सिद्धांतों और नीतियों का सार्वजनिक घोषणा-पत्र manifesto कहलाता है।"]),
  q(4, "english", "one-word", "M", 0,
    ["Custom of having more than one husband at the same time.", ["Polyandry", "Polygamy", "Monogamy", "Bigamy"], "Having more than one husband is polyandry."],
    ["एक ही समय में एक से अधिक पति रखने की प्रथा:", ["बहुपतित्व (Polyandry)", "बहुविवाह (Polygamy)", "एकविवाह (Monogamy)", "द्विविवाह (Bigamy)"], "एक से अधिक पति रखना बहुपतित्व (polyandry) है।"]),
  q(4, "english", "synonyms-antonyms", "E", 2,
    ["Choose the word most nearly the same in meaning as EXHORT.", ["Threaten", "Show", "Encourage", "Alert"], "To exhort is to urge or encourage strongly."],
    ["EXHORT के अर्थ में सबसे निकट शब्द चुनिए:", ["धमकाना", "दिखाना", "प्रोत्साहित करना", "सतर्क करना"], "Exhort का अर्थ दृढ़ता से प्रेरित या प्रोत्साहित करना है।"]),
  q(4, "english", "synonyms-antonyms", "M", 1,
    ["Choose the word most opposite in meaning to ESTABLISHED.", ["Small", "New", "Orthodox", "Modern"], "'Established' means long-standing and settled; its opposite is 'new'."],
    ["ESTABLISHED के विपरीतार्थक शब्द चुनिए:", ["छोटा", "नया", "रूढ़िवादी", "आधुनिक"], "'Established' का अर्थ पुराना और जमा हुआ है; विलोम 'new' (नया) है।"]),
  q(4, "english", "synonyms-antonyms", "E", 1,
    ["Choose the word most opposite in meaning to AFFLUENT.", ["Affected", "Poor", "Uneducated", "Usual"], "Affluent means wealthy; the opposite is poor."],
    ["AFFLUENT के विपरीतार्थक शब्द चुनिए:", ["प्रभावित", "गरीब", "अशिक्षित", "सामान्य"], "Affluent का अर्थ धनी है; विलोम poor (गरीब) है।"]),
  q(4, "english", "spelling", "M", 3,
    ["Find the word that is wrongly spelt or inappropriate: It is better to SEEK (A) ADVICE (B) from a Financial CONSULTANT (C) on how to SAFE (D) your business.", ["SEEK (A)", "ADVICE (B)", "CONSULTANT (C)", "SAFE (D)"], "The sentence needs the verb 'save', not the adjective 'safe'."],
    ["वह शब्द ढूँढिए जो गलत वर्तनी वाला या अनुपयुक्त है: It is better to SEEK (A) ADVICE (B) from a Financial CONSULTANT (C) on how to SAFE (D) your business.", ["SEEK (A)", "ADVICE (B)", "CONSULTANT (C)", "SAFE (D)"], "यहाँ क्रिया 'save' चाहिए, विशेषण 'safe' नहीं।"]),
  q(4, "english", "spelling", "M", 1,
    ["Find the word that is wrongly spelt or inappropriate: On two CONSECUTIVE (A) nights two greatest ICONES (B) of show business were honoured with UNPRECEDENTED (C) AFFECTION (D)", ["CONSECUTIVE (A)", "ICONES (B)", "UNPRECEDENTED (C)", "AFFECTION (D)"], "The plural is spelt 'icons', not 'icones'."],
    ["वह शब्द ढूँढिए जो गलत वर्तनी वाला या अनुपयुक्त है: On two CONSECUTIVE (A) nights two greatest ICONES (B) of show business were honoured with UNPRECEDENTED (C) AFFECTION (D)", ["CONSECUTIVE (A)", "ICONES (B)", "UNPRECEDENTED (C)", "AFFECTION (D)"], "बहुवचन की सही वर्तनी 'icons' है, 'icones' नहीं।"]),
  q(4, "english", "idioms", "M", 0,
    ["His behavior compelled me to “give him a piece of my mind”", ["Scold him", "Pardon him", "Make him my friend", "Take him into confidence"], "To give someone a piece of one's mind is to scold them frankly."],
    ["मुहावरा ‘give him a piece of my mind’ का अर्थ चुनिए: His behavior compelled me to “give him a piece of my mind”", ["उसे डाँटना", "उसे क्षमा करना", "उसे अपना मित्र बनाना", "उसे विश्वास में लेना"], "'Give a piece of one's mind' का अर्थ किसी को खरी-खरी सुनाना या डाँटना है।"]),
  q(4, "english", "idioms", "M", 2,
    ["“In black and white”", ["In short", "Useless", "In writing", "In full swing"], "'In black and white' means in written or printed form."],
    ["मुहावरा “In black and white” का अर्थ चुनिए:", ["संक्षेप में", "बेकार", "लिखित रूप में", "पूरे ज़ोर पर"], "'In black and white' का अर्थ लिखित या मुद्रित रूप में है।"]),
  q(4, "english", "grammar", "M", 1,
    ["Tonight’s game was ........ because of the rain", ["struck off", "called off", "winning", "played"], "'Called off' means cancelled."],
    ["रिक्त स्थान भरिए (Q.12): Tonight’s game was ........ because of the rain", ["struck off", "called off", "winning", "played"], "'Called off' का अर्थ रद्द करना है।"]),
  q(4, "english", "grammar", "M", 0,
    ["........ having worked really hard in office, Vikas did not get the much expected promotion.", ["In spite of", "On", "Since", "Despite off"], "'In spite of' shows contrast with the effort made; 'despite off' is not a phrase."],
    ["रिक्त स्थान भरिए (Q.13): ........ having worked really hard in office, Vikas did not get the much expected promotion.", ["In spite of", "On", "Since", "Despite off"], "'In spite of' प्रयास के विपरीत परिणाम दर्शाता है; 'despite off' कोई प्रयोग नहीं है।"]),
  q(4, "hindi", "vyakaran", "M", 2,
    ["Which of the following is an incorrect sentence?", ["Tiger and goat drink water at one ghat.", "There is a big crowd there.", "Shri Krishna has many names (‘अनेकों’ नाम है).", "Our teachers are very good."], "'अनेक' already means many, so 'अनेकों' is wrong; the verb should also be plural ('हैं')."],
    ["निम्नलिखित में से अशुद्ध वाक्य कौन सा है?", ["बाघ बकरी एक घाट में पानी पीते हैं", "वहाँ बहुत भीड़ है", "श्रीकृष्ण के अनेकों नाम है", "हमारे शिक्षक बहुत अच्छे हैं"], "'अनेक' का अर्थ ही बहुत है, इसलिए 'अनेकों' अशुद्ध है; क्रिया भी बहुवचन 'हैं' होनी चाहिए।"]),
  q(4, "hindi", "ek-shabd", "M", 2,
    ["The correct word for the phrase “one who knows everything” is:", ["Bahuj", "Alpagya", "Sarvagya", "Abhigya"], "One who knows everything is सर्वज्ञ (omniscient)."],
    ["“जो सब कुछ जानता है” इस वाक्यांश के लिये सही शब्द क्या है?", ["बहुज", "अल्पज्ञ", "सर्वज्ञ", "अभिज्ञ"], "सब कुछ जानने वाला सर्वज्ञ कहलाता है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Which is not a synonym of ‘शांति’ (peace)?", ["Chuppi (silence)", "Maun (silence)", "Neeravta (silence)", "Aakash (sky)"], "Chuppi, maun and neeravta all relate to silence/peace; 'आकाश' means sky."],
    ["‘शांति’ शब्द का समानार्थ नहीं है–", ["चुप्पी", "मौन", "नीरवता", "आकाश"], "चुप्पी, मौन और नीरवता शांति के निकट हैं; 'आकाश' का अर्थ आसमान है।"]),
  q(4, "hindi", "muhavare", "M", 1,
    ["The idiom ‘लकीर का फकीर होना’ means:", ["Living a simple life", "Being traditional", "Believing in sorcery", "Being opposed to show-off"], "'Lakeer ka fakeer' is one who blindly follows tradition."],
    ["‘लकीर का फकीर होना’ का अर्थ है–", ["सरल जीवन यापन करना", "परम्परावादी होना", "झाड़फूँक पर विश्वास करना", "आडम्बर विरोधी होना"], "'लकीर का फकीर' वह है जो परम्परा का अंधानुकरण करे।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["The antonym of ‘ताप’ is ______.", ["Tam (darkness)", "Tamsik", "Sharad", "Sheet (cold)"], "The opposite of ताप (heat) is शीत (cold)."],
    ["‘ताप’ शब्द का विलोम ______ होता है।", ["तम", "तामसिक", "शरद", "शीत"], "ताप (गर्मी) का विलोम शीत (ठंड) है।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["Which is not a synonym of ‘कुसुम’ (flower)?", ["Kamal (lotus)", "Pushp", "Suman", "Prasoon"], "Pushp, suman and prasoon are synonyms of kusum; kamal is a specific flower."],
    ["निम्न में से ‘कुसुम’ का पर्यायवाची शब्द नहीं है–", ["कमल", "पुष्प", "सुमन", "प्रसून"], "पुष्प, सुमन और प्रसून कुसुम के पर्यायवाची हैं; कमल एक विशेष फूल है।"]),
  q(4, "hindi", "vyakaran", "M", 3,
    ["The feminine of the word ‘दाता’ is:", ["Datri-(दातृ)", "Daati", "Daart", "Daatri"], "The feminine of दाता (giver) is दात्री."],
    ["‘दाता’ शब्द का स्त्रीलिंग होता है–", ["दातृ", "दाती", "दार्त", "दात्री"], "दाता का स्त्रीलिंग दात्री है।"]),
  q(4, "hindi", "ek-shabd", "M", 1,
    ["One word for “one who wishes to win”:", ["Unmad", "Jigishu", "Aakankshi", "Jigisha"], "One who desires to win is जिगीषु (जिगिषु)."],
    ["“जीतने की इच्छा रखने वाला” कहलाता है–", ["उन्माद", "जिगिषु", "आकांक्षी", "जिगिषा"], "जीतने की इच्छा रखने वाला जिगीषु कहलाता है।"]),
  q(4, "hindi", "sandhi-samas", "M", 0,
    ["The sandhi-vichchhed of “उल्लास” is:", ["उत् + लास", "उल् + लास", "उत + लास", "उल्ल + आस"], "उत् + लास = उल्लास (त् + ल → ल्ल)."],
    ["“उल्लास” का सन्धि-विच्छेद होगा–", ["उत् + लास", "उल् + लास", "उत + लास", "उल्ल + आस"], "उत् + लास = उल्लास (त् का ल् में बदलना)।"]),
  q(4, "hindi", "vyakaran", "E", 2,
    ["The old woman gave ______ to the Buddhist monk.", ["Diksha", "Pariksha", "Bhiksha", "Bubhuksha"], "One gives alms (भिक्षा) to a monk."],
    ["वृद्धा ने बौद्ध भिक्षु को ______ दी।", ["दीक्षा", "परीक्षा", "भिक्षा", "बुभुक्षा"], "भिक्षु को भिक्षा दी जाती है।"]),
  q(4, "hindi", "ek-shabd", "E", 0,
    ["One word for “one born in a good family”:", ["Kuleen", "Sanskari", "Sarvagya", "Bahugya"], "One born in a good family is कुलीन."],
    ["“जो अच्छे कुल में पैदा हुआ हो” कहलाता है–", ["कुलीन", "संस्कारी", "सर्वज्ञ", "बहुज्ञ"], "अच्छे कुल में जन्मा व्यक्ति कुलीन कहलाता है।"]),
  q(4, "hindi", "muhavare", "M", 1,
    ["The idiom ‘नाक में दम करना’ means:", ["To be very happy", "To trouble greatly", "To satisfy curiosity", "To slander"], "'Naak mein dam karna' means to harass someone badly."],
    ["‘नाक में दम कर देना’ मुहावरे का अर्थ बताइये–", ["बहुत प्रसन्न होना", "बहुत परेशान होना", "जिज्ञासा शांत करना", "निंदा करना"], "'नाक में दम करना' का अर्थ बहुत तंग करना है।"]),
  q(4, "hindi", "ek-shabd", "M", 0,
    ["One who knows many languages is called ______.", ["Bahubhashavid", "Bahubhashabhashi", "Bahushrut", "Bahudarshi"], "One who knows many languages is a बहुभाषाविद (polyglot)."],
    ["बहुत सी भाषाओं को जानने वाला ______ कहलाता है–", ["बहुभाषाविद", "बहुभाषाभाषी", "बहुश्रुत", "बहुदर्शी"], "कई भाषाओं का ज्ञाता बहुभाषाविद कहलाता है।"]),
  q(2, "reasoning", "math-operations", "M", 2,
    ["If P means ‘divide’, R means ‘add’, T means ‘subtract’ and V means ‘multiply’, then 12 V 4 R 16 P 8 T 6 = ?", ["138", "50", "44", "72"], "12 × 4 + 16 ÷ 8 − 6 = 48 + 2 − 6 = 44."],
    ["अगर P का अर्थ है ‘भाग’, R का अर्थ ‘जमा’, T का अर्थ ‘घटाना’, V का अर्थ ‘गुणा’; तब 12 V 4 R 16 P 8 T 6 = ?", ["138", "50", "44", "72"], "12 × 4 + 16 ÷ 8 − 6 = 48 + 2 − 6 = 44।"]),
  q(2, "reasoning", "series", "M", 2,
    ["What comes next in this series? ABCD PQRS ABCDE PQRST ABCDEF PQRST_", ["A", "V", "U", "W"], "The blocks grow by one letter each time: ABCDEF is followed by PQRSTU."],
    ["इस क्रमाँक में आगे क्या आयेगा? ABCD PQRS ABCDE PQRST ABCDEF PQRST_", ["A", "V", "U", "W"], "हर बार एक अक्षर बढ़ता है: ABCDEF के बाद PQRSTU आता है।"]),
  q(2, "reasoning", "direction-sense", "M", 3,
    ["Rohan walked 10 km towards north, then turned left and walked 20 km, then turned left again and walked 10 km, then turned right and walked 5 km. How far is he from the starting point?", ["10 km", "20 km", "30 km", "25 km"], "He ends 25 km west of the start on the same line (10 north, 20 west, 10 south, then 5 west)."],
    ["रोहन उत्तर दिशा में 10 कि.मी. चला फिर वह बाएँ मुड़कर 20 कि.मी. चला है। वह फिर से बाएँ मुड़कर 10 कि.मी. चला है। वह फिर दाएँ मुड़ा और 5 कि.मी. चला। वह शुरूआती जगह से कितना दूर है?", ["10 कि.मी.", "20 कि.मी.", "30 कि.मी.", "25 कि.मी."], "वह शुरुआती जगह से उसी रेखा पर 25 कि.मी. पश्चिम में है (10 उत्तर, 20 पश्चिम, 10 दक्षिण, फिर 5 पश्चिम)।"]),
  q(2, "reasoning", "alphabet-test", "M", 1,
    ["How many meaningful English words beginning with ‘S’ can be formed from NSIK?", ["One", "Two", "Three", "Four"], "SINK and SKIN are the two words."],
    ["NSIK से कितने सार्थक अंग्रेजी शब्द बनाये जा सकते हैं, जो ‘S’ से शुरू होते हैं?", ["एक", "दो", "तीन", "चार"], "SINK और SKIN दो शब्द बनते हैं।"]),
  q(2, "reasoning", "alphabet-test", "M", 2,
    ["How many meaningful English words can be formed from NREA, using each letter only once?", ["None", "One", "Two", "Three"], "EARN and NEAR are the two words."],
    ["NREA से कितने सार्थक अंग्रेजी शब्द बनाए जा सकते हैं। एक अक्षर का प्रयोग केवल एक ही बार करना है।", ["कोई नहीं", "एक", "दो", "तीन"], "EARN और NEAR दो शब्द बनते हैं।"]),
  q(2, "reasoning", "odd-one-out", "E", 3,
    ["Three out of four are alike and form a group. Which one is outside the group?", ["Copper", "Silver", "Gold", "Diamond"], "Copper, silver and gold are metals; diamond is a form of carbon."],
    ["चार में से तीन एक समान हैं तथा एक समूह बनाते हैं। कौन समूह से बाहर है?", ["ताम्बा", "चांदी", "सोना", "हीरा"], "ताँबा, चाँदी और सोना धातुएँ हैं; हीरा कार्बन का रूप है।"]),
  q(2, "reasoning", "odd-one-out", "M", 3,
    ["Three out of four are alike so that they form a group. Which one is outside the group?", ["Blue", "Red", "Violet", "Grey"], "Blue, red and violet are colours of the rainbow; grey is not."],
    ["चार में से तीन समान हैं ताकि एक समूह बन सके। कौन समूह से बाहर है?", ["नीला", "लाल", "बैंगनी", "धूसर (Grey)"], "नीला, लाल और बैंगनी इंद्रधनुष के रंग हैं; धूसर नहीं।"]),
  q(2, "reasoning", "analogy", "M", 2,
    ["‘K, N’ is related to ‘Q, T’ in the same way as ‘D, G’ is related to ______.", ["JN", "IM", "JM", "IN"], "Each letter moves 6 places ahead: K→Q, N→T, so D→J and G→M."],
    ["‘K, N’ का रिश्ता ‘Q, T’ से वही है जो ‘D, G’ का ______ से है।", ["JN", "IM", "JM", "IN"], "हर अक्षर 6 स्थान आगे बढ़ता है: K→Q, N→T, इसलिए D→J और G→M।"]),
  q(2, "reasoning", "series", "M", 2,
    ["What will come next in this series? 311, 300, 278, 245, 201, 146, ?", ["70", "90", "80", "110"], "The differences are 11, 22, 33, 44, 55, so the next difference is 66 and 146 − 66 = 80."],
    ["इस क्रमाँक में आगे क्या आयेगा? 311, 300, 278, 245, 201, 146, ?", ["70", "90", "80", "110"], "अंतर 11, 22, 33, 44, 55 हैं, अगला अंतर 66 है और 146 − 66 = 80।"]),
  q(2, "reasoning", "analogy", "M", 3,
    ["Crime is related to police in the same way as flood is related to ______.", ["River", "Pond", "Kooj", "Dam"], "Police control crime, as a dam controls floods."],
    ["अपराध उसी प्रकार पुलिस से सम्बन्धित है जिस प्रकार बाढ़ सम्बन्धित है–", ["नदी से", "तालाब से", "कूज से", "बाँध से"], "पुलिस अपराध को रोकती है, जैसे बाँध बाढ़ को रोकता है।"]),
  q(2, "reasoning", "coding-decoding", "M", 2,
    ["In a certain language ‘GUEST’ is written as ‘HVFTU’. How will ‘NEST’ be written?", ["IWTU", "XWTU", "OFTU", "MDTU"], "Each letter moves one place ahead: N→O, E→F, S→T, T→U."],
    ["किसी निश्चित भाषा में ‘GUEST’ को ‘HVFTU’ के रूप में लिखा जाता है, तो ‘NEST’ को लिखा जायेगा।", ["IWTU", "XWTU", "OFTU", "MDTU"], "हर अक्षर एक स्थान आगे बढ़ता है: N→O, E→F, S→T, T→U।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Where is India's first uranium mine situated?", ["Jaduguda", "Tummalapalle", "Pichli", "Dalbhum"], "India's first uranium mine is at Jaduguda in Jharkhand."],
    ["भारत की पहली यूरेनियम (Uranium) खान कहाँ स्थित है?", ["जादुगौड़ा", "तुमल्ला पुल्ले", "पिचली", "दलभूम"], "भारत की पहली यूरेनियम खान झारखंड के जादुगौड़ा में है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["In which state is the Tabo Monastery located?", ["Arunachal Pradesh", "Himachal Pradesh", "Jammu & Kashmir", "Sikkim"], "Tabo Monastery is in the Spiti valley of Himachal Pradesh."],
    ["ताबो मठ किस राज्य में स्थित है?", ["अरूणाचल प्रदेश", "हिमाचल प्रदेश", "जम्मू व कश्मीर", "सिक्किम"], "ताबो मठ हिमाचल प्रदेश की स्पीति घाटी में है।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["In which season do we need more fat?", ["Rainy", "Spring", "Winter", "Summer"], "Fat gives energy and insulation, so more is needed in winter."],
    ["किस मौसम में हमें ज्यादा चर्बी की जरूरत होती है?", ["वर्षा", "बसन्त", "सर्दी", "गर्मी"], "चर्बी ऊर्जा और ऊष्मा-रोधन देती है, इसलिए सर्दी में अधिक चाहिए।"]),
  q(1, "general-studies", "general-science", "E", 1,
    ["When is World Human Rights Day celebrated?", ["24 February", "10 December", "15 May", "21 July"], "Human Rights Day is observed on 10 December."],
    ["विश्व मानव अधिकार दिवस कब मनाया जाता है?", ["24 फरवरी", "10 दिसम्बर", "15 मई", "21 जुलाई"], "मानव अधिकार दिवस 10 दिसम्बर को मनाया जाता है।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["What does a hygrometer measure?", ["Relative humidity", "Purity of milk", "Specific gravity of any liquid", "None of these"], "A hygrometer measures humidity."],
    ["Hygrometer क्या नापता है?", ["सापेक्षित आद्रता (Relative humidity)", "दूध की शुद्धता", "किसी भी तरल पदार्थ का विशिष्ट घनत्व", "इनमें से कोई नहीं"], "हाइग्रोमीटर आर्द्रता मापता है।"]),
  q(1, "general-studies", "indian-history", "E", 1,
    ["Who was the last ruler of the Mughal empire?", ["Babur", "Bahadur Shah Zafar", "Akbar", "None of these"], "Bahadur Shah Zafar was the last Mughal emperor (deposed in 1857)."],
    ["मुगल साम्राज्य का अंतिम शासक कौन था?", ["बाबर", "बहादुर शाह जफर", "अकबर", "इनमें से कोई नहीं"], "बहादुर शाह ज़फर अंतिम मुगल बादशाह थे (1857 में अपदस्थ)।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Where is the headquarters of the International Court of Justice situated?", ["Hague", "Addis Ababa", "Paris", "New York"], "The ICJ sits at The Hague in the Netherlands."],
    ["अन्तर्राष्ट्रीय न्यायालय का मुख्यालय कहाँ स्थित है?", ["हेग (Hague)", "एडीस अबाबा (Addis Ababa)", "पेरिस (Paris)", "न्यू यार्क (New York)"], "अंतर्राष्ट्रीय न्यायालय नीदरलैंड के हेग में है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["With which organisations was the famous scientist Professor Yash Pal associated?", ["ISRO", "Jawaharlal Nehru University", "University Grants Commission", "All of the above"], "Yash Pal worked with ISRO, chaired the UGC and was chancellor of JNU."],
    ["प्रसिद्ध वैज्ञानिक प्रोफेसर यशपाल किन संगठनों से जुड़े थे?", ["इसरो (ISRO)", "जवाहरलाल नेहरू विश्वविद्यालय", "University Grants Commission", "उपरोक्त सभी"], "यशपाल ने इसरो में कार्य किया, UGC के अध्यक्ष रहे और JNU के कुलाधिपति थे।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["Where was India's first atomic reactor set up?", ["Surat", "Tarapur", "Trombay", "Sholapur"], "Apsara, India's first reactor, started at Trombay in 1956."],
    ["भारत का पहला परमाणु Reactor कहाँ स्थापित किया गया?", ["सूरत", "तारापुर", "ट्राम्बे", "शोलापुर"], "भारत का पहला रिएक्टर 'अप्सरा' 1956 में ट्रॉम्बे में शुरू हुआ।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Which is the last month of the Shaka Samvat?", ["Phalgun", "Chaitra", "Ashadh", "Paush"], "The Shaka calendar begins with Chaitra and ends with Phalguna."],
    ["शक संवत का अंतिम महीना कौन सा है?", ["फाल्गुन", "चैत्र", "आषाढ़", "पौष"], "शक संवत चैत्र से शुरू होकर फाल्गुन पर समाप्त होता है।"]),
  q(1, "general-studies", "indian-geography", "E", 1,
    ["What problem has been caused by excess use of ground water?", ["Salinity", "Falling of the water table", "Waterlogging", "All of the above"], "Over-extraction of groundwater lowers the water table."],
    ["भूमिगत जल के अधिक प्रयोग से क्या समस्या उत्पन्न हुई है?", ["खारापन", "जल स्तर का नीचे गिरना", "जल भराव", "ऊपर सभी"], "भूजल के अधिक दोहन से जल स्तर नीचे गिरता है।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["When did the Indian Air Force celebrate its golden jubilee?", ["1962", "1972", "1982", "1992"], "The IAF was founded in 1932, so its golden jubilee was in 1982."],
    ["भारतीय वायुसेना ने कब अपनी स्वर्ण जयंती मनायी थी?", ["1962", "1972", "1982", "1992"], "वायुसेना की स्थापना 1932 में हुई थी, इसलिए स्वर्ण जयंती 1982 में मनी।"]),
  q(3, "quant", "percentage", "M", 2,
    ["13 % of 258 − ? = 10", ["23.45", "24.53", "23.54", "24.35"], "13% of 258 = 33.54; 33.54 − 10 = 23.54."],
    ["13 % of 258 − (minus) ? = 10", ["23.45", "24.53", "23.54", "24.35"], "258 का 13% = 33.54; 33.54 − 10 = 23.54।"]),
  q(3, "quant", "ratio-proportion", "M", 2,
    ["27 toasters and 18 mixers cost Rs 80,100. What is the cost of 12 toasters and 8 mixers together?", ["Rs 36,000", "Rs 36,500", "Rs 35,600", "Cannot be determined"], "12 : 8 is 4/9 of 27 : 18 (both 3 : 2), so the cost is 80,100 × 4/9 = Rs 35,600."],
    ["27 टोस्टर और 18 मिक्सर का दाम रू. 80,100/- है। 12 टोस्टर और 8 मिक्सर का दाम मिलाकर कितना होगा?", ["36,000/-", "36,500/-", "35,600/-", "नहीं जाना जा सकता"], "12 : 8 और 27 : 18 दोनों 3 : 2 हैं और पहला दूसरे का 4/9 है, इसलिए दाम 80,100 × 4/9 = 35,600 रु० है।"]),
  q(3, "quant", "simplification", "M", 1,
    ["5437 − 3153 + 2284 = ? × 50", ["96.66", "91.36", "96.13", "93.16"], "5437 − 3153 + 2284 = 4568, and 4568 ÷ 50 = 91.36."],
    ["5437 - 3153 + 2284 = ? X 50", ["96.66", "91.36", "96.13", "93.16"], "5437 − 3153 + 2284 = 4568 और 4568 ÷ 50 = 91.36।"]),
  q(3, "quant", "interest", "M", 1,
    ["What will be the simple interest on a principal of Rs 16,500 at 16 % per annum in four years?", ["Rs 11,560", "Rs 10,560", "Rs 12,500", "Rs 9,980"], "SI = 16500 × 16 × 4 / 100 = Rs 10,560."],
    ["रू 16,500/- के मूलधन पर 16 % की दर से चार साल में साधारण ब्याज कितना होगा?", ["11,560/-", "10,560/-", "12,500/-", "9,980/-"], "साधारण ब्याज = 16500 × 16 × 4 / 100 = 10,560 रु०।"]),
  q(3, "quant", "time-work", "H", 1,
    ["10 men and 8 women together finish a work in 5 days. The work done by a woman in one day is half the work done by a man in one day. In how many days will 4 men and 6 women do the work?", ["12 days", "10 days", "8 2/3 days", "9 3/4 days"], "Take a man = 2 units and a woman = 1 unit: work = (20 + 8) × 5 = 140; 4 men and 6 women do 14 units a day, so 140 ÷ 14 = 10 days."],
    ["10 आदमी और 8 औरतें एक काम को मिलकर 5 दिन में खत्म करते हैं। औरत द्वारा एक दिन में किया गया काम आदमी द्वारा एक दिन में किये गये काम का आधा है। 4 आदमी और 6 औरतें इस काम को करने में कितने दिन लेंगे?", ["12 दिन", "10 दिन", "8 2/3 दिन", "9 3/4 दिन"], "आदमी = 2 इकाई और औरत = 1 इकाई लें: कुल काम = (20 + 8) × 5 = 140; 4 आदमी और 6 औरतें प्रतिदिन 14 इकाई करते हैं, इसलिए 140 ÷ 14 = 10 दिन।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Alexander Fleming discovered ______.", ["Penicillin", "X-Ray", "Telephone", "Wireless"], "Alexander Fleming discovered penicillin in 1928."],
    ["अलेक्जेंडर फ्लेमिंग ने ______ की खोज की।", ["पेनिसिलीन (Penicillin)", "एक्स-रे (X-Ray)", "टेलीफोन (Telephone)", "वायरलेस (Wireless)"], "एलेक्ज़ेंडर फ्लेमिंग ने 1928 में पेनिसिलिन की खोज की।"]),
  q(3, "quant", "mensuration", "M", 2,
    ["The length of a rectangle is 7 cm more than its breadth. If the perimeter of the rectangle is 126 cm, what is its breadth?", ["56 cm", "38 cm", "28 cm", "32 cm"], "l + b = 63 and l = b + 7, so 2b + 7 = 63 and b = 28 cm."],
    ["एक आयत की लम्बाई उसकी चौड़ाई से 7 cm अधिक है। अगर आयत की परिधि 126 cm है तो आयत की चौड़ाई क्या होगी?", ["56 cm", "38 cm", "28 cm", "32 cm"], "l + b = 63 और l = b + 7, इसलिए 2b + 7 = 63 और b = 28 सेमी।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Which of the following substances is used to make a pencil?", ["Graphite", "Silicon", "Charcoal", "Phosphorus"], "The pencil 'lead' is graphite."],
    ["निम्नलिखित में से कौन सी वस्तु पेंसिल (Pencil) बनाने के लिए इस्तेमाल होती है?", ["ग्रेफाइट (graphite)", "सिलिकॉन (silicon)", "कटकोयला (char coal)", "भास्वर (phosphorus)"], "पेंसिल की 'लेड' ग्रेफाइट होती है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["What is coral?", ["Plant", "Fungi", "Animal", "Fern"], "Coral is formed by tiny animals called polyps."],
    ["कोरल (coral) क्या है?", ["पौधा", "कवक (Fungi)", "जानवर", "प्रर्णाग (Fern)"], "कोरल पॉलिप नामक छोटे जंतुओं से बनता है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Which blood cell is called the soldier of the body?", ["White blood cell", "Platelets", "Red blood cell", "All of the above"], "White blood cells defend the body against infection."],
    ["निम्नलिखित में से किस रक्त कोष को शरीर का सिपाही (Soldier) कहा जाता है?", ["सफेद रक्त कोषिका", "Platelets", "लाल रक्त कोषिका", "ऊपर के सभी"], "श्वेत रक्त कोशिकाएँ शरीर को संक्रमण से बचाती हैं।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["The light year is a measure of which of the following?", ["Stellar distance", "Speed of an aeroplane", "Speed of light", "Speed of a rocket"], "A light year is a unit of astronomical distance."],
    ["प्रकाश वर्ष निम्नलिखित में किसका माप है?", ["तारकीय दूरी", "हवाई जहाज की गति", "प्रकाश की गति", "रॉकेट की गति"], "प्रकाश वर्ष खगोलीय दूरी की इकाई है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["H1N1 flu is caused by which of the following?", ["Virus", "Bacteria", "Cold", "Fungus"], "H1N1 flu is caused by an influenza virus."],
    ["H1N1 FLU निम्नलिखित में से किसकी वजह से होता है?", ["विषाणु", "जीवाणु", "सर्दी", "कवक"], "H1N1 फ्लू इन्फ्लुएंज़ा विषाणु (वायरस) से होता है।"]),
  q(1, "computer", "fundamentals", "E", 0,
    ["What does a saved document mean?", ["File", "Word", "Folder", "Project"], "A saved document is stored as a file."],
    ["सहेजे गये दस्तावेज (saved document) का मतलब क्या है?", ["फाइल (File)", "शब्द (Word)", "फोल्डर (Folder)", "प्रोजेक्ट (Project)"], "सहेजा गया दस्तावेज़ फाइल के रूप में संग्रहित होता है।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["From which organ of the human body does the process of digestion of food begin?", ["Stomach", "Food pipe", "Mouth", "Small intestine"], "Digestion begins in the mouth, where saliva starts breaking down starch."],
    ["भोजन के पाचन की प्रक्रिया, मनुष्य के किस अंग से शुरू होती है?", ["पेट", "भोजन नली", "मुँह", "छोटी आँत"], "पाचन मुँह से शुरू होता है, जहाँ लार स्टार्च को तोड़ना शुरू करती है।"]),
];
