// HP Police Constable 2016 (Code A-05/2016, Series B) — transcribed from the photographed question paper, which covers questions 1-80.
// No official key was available (the photo carries a candidate's pen marks, which were not trusted): answers were solved
// independently. Left out because the photo or the question was unclear (original numbers 18, 57, 71, 76) and Q39, whose options
// do not describe NITI Aayog accurately. Option order is kept as printed.
// Sections: 0 Himachal GK, 1 General Knowledge, 2 Reasoning, 3 Numerical Ability, 4 Hindi & English.

import { q, type PoliceQuestion } from "../police/types";

export const y2016: PoliceQuestion[] = [
  q(4, "english", "synonyms-antonyms", "E", 2,
    ["Which is not a synonym of DISASTER:", ["Misfortune", "Calamity", "Prosperity", "Mishap"], "Prosperity means success and wealth, the opposite of disaster."],
    ["निम्न में से कौन DISASTER का पर्यायवाची नहीं है:", ["दुर्भाग्य", "महाविपत्ति", "समृद्धि", "दुर्घटना"], "Prosperity का अर्थ समृद्धि है, जो आपदा का विपरीत है।"]),
  q(4, "english", "synonyms-antonyms", "E", 0,
    ["Opposite of the word CONCUR is:", ["Disagree", "Disappear", "Discourage", "Damage"], "Concur means to agree, so its opposite is disagree."],
    ["शब्द CONCUR का विलोम है:", ["असहमत होना", "गायब होना", "हतोत्साहित करना", "नुकसान"], "Concur का अर्थ सहमत होना है, इसलिए विलोम disagree है।"]),
  q(4, "english", "idioms", "M", 2,
    ["To die in harness :", ["to die young in an accident", "planned murder", "to die while in service", "to be taken by surprise"], "'To die in harness' means to die while still working."],
    ["मुहावरे ‘To die in harness’ का अर्थ है:", ["युवावस्था में दुर्घटना में मरना", "योजनाबद्ध हत्या", "सेवा में रहते हुए मरना", "अचानक चौंका दिया जाना"], "'To die in harness' का अर्थ काम करते हुए ही मर जाना है।"]),
  q(4, "english", "idioms", "M", 3,
    ["A cock and bull story :", ["Long story", "Factual story", "True story", "A lie"], "A cock and bull story is an absurd, unbelievable tale, i.e. a lie."],
    ["मुहावरे ‘A cock and bull story’ का अर्थ है:", ["लंबी कहानी", "तथ्यपूर्ण कहानी", "सच्ची कहानी", "झूठ"], "'A cock and bull story' एक अविश्वसनीय मनगढ़ंत कहानी, यानी झूठ है।"]),
  q(4, "english", "idioms", "M", 0,
    ["To miss the bus :", ["to miss an opportunity", "to miss the daily bus to work", "to find fault with others", "to argue without reason"], "'To miss the bus' means to miss an opportunity."],
    ["मुहावरे ‘To miss the bus’ का अर्थ है:", ["अवसर चूक जाना", "काम पर जाने की रोज़ की बस छूट जाना", "दूसरों में दोष निकालना", "बिना कारण बहस करना"], "'To miss the bus' का अर्थ अवसर खो देना है।"]),
  q(4, "english", "grammar", "E", 1,
    ["I have been living here ........ 2009", ["from", "since", "for", "between"], "'Since' is used with a point in time such as 2009."],
    ["रिक्त स्थान भरिए: I have been living here ........ 2009", ["from", "since", "for", "between"], "2009 जैसे समय-बिंदु के साथ 'since' आता है।"]),
  q(4, "english", "grammar", "M", 3,
    ["She fell prey ........ malaria", ["of", "for", "into", "to"], "The phrase is 'fall prey to'."],
    ["रिक्त स्थान भरिए: She fell prey ........ malaria", ["of", "for", "into", "to"], "सही प्रयोग 'fall prey to' है।"]),
  q(4, "english", "grammar", "E", 2,
    ["Rohan is good ........ mathematics", ["in", "for", "at", "on"], "We say 'good at' a subject."],
    ["रिक्त स्थान भरिए: Rohan is good ........ mathematics", ["in", "for", "at", "on"], "किसी विषय में कुशल के लिए 'good at' कहा जाता है।"]),
  q(4, "english", "spelling", "E", 0,
    ["Choose the correctly spelt word (Q. 9) :", ["Argument", "Arguement", "Argumant", "Arguemant"], "The correct spelling is 'Argument'."],
    ["सही वर्तनी वाला शब्द चुनिए:", ["Argument", "Arguement", "Argumant", "Arguemant"], "सही वर्तनी 'Argument' है।"]),
  q(4, "english", "error-spotting", "M", 3,
    ["Find out incorrect part of sentence: My father (A) / deals (B) / with garments (C) / (D) no error", ["My father (A)", "deals (B)", "with garments (C)", "no error (D)"], "'Deals with garments' is correct, so the sentence has no error."],
    ["वाक्य का त्रुटिपूर्ण भाग ज्ञात कीजिए: My father (A) / deals (B) / with garments (C) / (D) no error", ["My father (A)", "deals (B)", "with garments (C)", "कोई त्रुटि नहीं (D)"], "'Deals with garments' सही है, इसलिए वाक्य में कोई त्रुटि नहीं है।"]),
  q(4, "english", "error-spotting", "M", 2,
    ["Find out incorrect part of sentence: Knowledge of (A) / at least two languages (B) / are required to pass the examination (C) / (D) no error", ["Knowledge of (A)", "at least two languages (B)", "are required to pass the examination (C)", "no error (D)"], "The subject is 'Knowledge' (singular), so the verb should be 'is required'."],
    ["वाक्य का त्रुटिपूर्ण भाग ज्ञात कीजिए: Knowledge of (A) / at least two languages (B) / are required to pass the examination (C) / (D) no error", ["Knowledge of (A)", "at least two languages (B)", "are required to pass the examination (C)", "कोई त्रुटि नहीं (D)"], "कर्ता 'Knowledge' एकवचन है, इसलिए क्रिया 'is required' होनी चाहिए।"]),
  q(4, "english", "spelling", "E", 0,
    ["Choose the correctly spelt word (Q. 12) :", ["Aluminium", "Aliminium", "Elminium", "Alumenium"], "The correct spelling is 'Aluminium'."],
    ["सही वर्तनी वाला शब्द चुनिए:", ["Aluminium", "Aliminium", "Elminium", "Alumenium"], "सही वर्तनी 'Aluminium' है।"]),
  q(4, "english", "one-word", "E", 2,
    ["The passing on of physical or mental characteristics from one generation to another is known as :", ["Heritage", "Pedigree", "Heredity", "Legacy"], "The transfer of traits from parents to offspring is heredity."],
    ["एक पीढ़ी से दूसरी पीढ़ी में शारीरिक या मानसिक लक्षणों के हस्तांतरण को कहते हैं:", ["विरासत", "वंशावली", "आनुवंशिकता", "उत्तराधिकार"], "माता-पिता से संतान में लक्षणों का स्थानांतरण आनुवंशिकता है।"]),
  q(4, "english", "one-word", "M", 3,
    ["A person who has no money to pay his debt is called :", ["Poor", "Pauper", "Destitute", "Insolvent"], "A person unable to pay debts is insolvent."],
    ["वह व्यक्ति जिसके पास अपना कर्ज़ चुकाने के लिए धन न हो, कहलाता है:", ["गरीब", "कंगाल", "निराश्रित", "दिवालिया"], "कर्ज़ चुकाने में असमर्थ व्यक्ति दिवालिया (insolvent) कहलाता है।"]),
  q(4, "english", "one-word", "E", 1,
    ["A doctor who treats diseases of the eyes is known as :", ["Radiologist", "Ophthalmologist", "Cardiologist", "Dermatologist"], "An ophthalmologist treats eye diseases."],
    ["आँखों के रोगों का इलाज करने वाला चिकित्सक कहलाता है:", ["रेडियोलॉजिस्ट", "नेत्र रोग विशेषज्ञ", "हृदय रोग विशेषज्ञ", "त्वचा रोग विशेषज्ञ"], "नेत्र रोग विशेषज्ञ (ophthalmologist) आँखों के रोगों का इलाज करता है।"]),
  q(4, "english", "grammar", "M", 1,
    ["What will be past indefinite tense of - “I play cricket” :", ["I have been playing cricket", "I played cricket", "I played tennis", "I did not play cricket"], "The past indefinite of 'play' is 'played'."],
    ["“I play cricket” का भूतकाल (past indefinite) क्या होगा:", ["I have been playing cricket", "I played cricket", "I played tennis", "I did not play cricket"], "'play' का past indefinite रूप 'played' है।"]),
  q(4, "hindi", "paryay-vilom", "E", 3,
    ["Choose the antonym: उत्कर्ष", ["उपकर्ष", "ह्रास", "पतन", "अपकर्ष"], "The opposite of उत्कर्ष (rise) is अपकर्ष."],
    ["विलोम शब्द छाँटिए– उत्कर्ष", ["उपकर्ष", "ह्रास", "पतन", "अपकर्ष"], "उत्कर्ष का विलोम अपकर्ष है।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["What is the meaning of the idiom “अधजल गगरी छलकत जाय”?", ["Great people show off more", "A pot half full of water", "Small people show off more", "Showing off with a pot"], "A half-filled pot spills; people with little knowledge show off the most."],
    ["“अधजल गगरी छलकत जाय” मुहावरे / लोकोक्ति का क्या अर्थ है?", ["बड़े आदमी अधिक दिखावा करते हैं", "आधा पानी से भरी गागर", "छोटे आदमी अधिक दिखावा करते हैं", "गागर के साथ दिखावा करना"], "आधी भरी गागर छलकती है; अल्पज्ञ व्यक्ति ही अधिक दिखावा करते हैं।"]),
  q(4, "hindi", "vyakaran", "M", 2,
    ["Which of these is an abstract noun (भाववाचक संज्ञा)?", ["मीठा", "मिठाई", "मिठास", "मिष्ठान"], "'मिठास' names a quality, so it is an abstract noun."],
    ["इनमें से भाववाचक संज्ञा कौन सी है?", ["मीठा", "मिठाई", "मिठास", "मिष्ठान"], "'मिठास' गुण का नाम है, इसलिए भाववाचक संज्ञा है।"]),
  q(4, "hindi", "muhavare", "M", 3,
    ["What is the meaning of “बिल्ली के भागों छींका टूटा”?", ["Loss from a cat's jump", "Trouble comes and stays", "Loss instead of gain", "Sudden gain"], "The proverb means an unexpected stroke of luck."],
    ["“बिल्ली के भागों छींका टूटा” का अर्थ है?", ["बिल्ली की उछल-कूद से नुकसान होना", "आने वाला दुख आकर ही रहता है", "लाभ के बजाय हानि होना", "अचानक लाभ होना"], "इस कहावत का अर्थ अचानक लाभ (संयोग से सफलता) होना है।"]),
  q(4, "hindi", "sandhi-samas", "M", 0,
    ["Choose the correct sandhi: आकृष्ट", ["आ+कृष्ट", "आक्र+रिष्ट", "आकृष+त", "आकृष्+ट"], "आकृष्ट = आ + कृष्ट."],
    ["शुद्ध संधि का चयन कीजिए: आकृष्ट", ["आ+कृष्ट", "आक्र+रिष्ट", "आकृष+त", "आकृष्+ट"], "आकृष्ट = आ + कृष्ट।"]),
  q(4, "hindi", "vyakaran", "E", 2,
    ["What is the plural of वह?", ["वोह", "वह सब", "वे", "उन"], "The plural of 'वह' is 'वे'."],
    ["वह का बहुवचन क्या है?", ["वोह", "वह सब", "वे", "उन"], "'वह' का बहुवचन 'वे' है।"]),
  q(4, "hindi", "sandhi-samas", "M", 1,
    ["Choose the correct sandhi: परीक्षक", ["पर+यीक्षक", "परि+इक्षक", "परि+अक्षक", "पर+इक्षक"], "The accepted split is परि + ईक्षक (परि + इक्षक in the options)."],
    ["शुद्ध संधि का चयन कीजिए: परीक्षक", ["पर+यीक्षक", "परि+इक्षक", "परि+अक्षक", "पर+इक्षक"], "स्वीकार्य विच्छेद परि + ईक्षक (विकल्प में परि+इक्षक) है।"]),
  q(4, "hindi", "shuddh-vartani", "M", 0,
    ["Choose the correct spelling:", ["निरीक्षण", "निरिक्षण", "नीरिक्षण", "निरीषण"], "The correct spelling is निरीक्षण."],
    ["शुद्ध वर्तनी का चयन कीजिए:", ["निरीक्षण", "निरिक्षण", "नीरिक्षण", "निरीषण"], "शुद्ध वर्तनी निरीक्षण है।"]),
  q(4, "hindi", "vyakaran", "M", 3,
    ["Which of these is feminine gender?", ["माली", "खत्री", "चौधरी", "धनवती"], "'धनवती' is the feminine form."],
    ["निम्नलिखित में से स्त्रीलिंग है?", ["माली", "खत्री", "चौधरी", "धनवती"], "'धनवती' स्त्रीलिंग रूप है।"]),
  q(4, "hindi", "paryay-vilom", "E", 2,
    ["What is the antonym of “प्रलय”?", ["विलय", "आलय", "सृष्टि", "पुण्य"], "The opposite of प्रलय (destruction) is सृष्टि (creation)."],
    ["“प्रलय” का विलोम क्या है?", ["विलय", "आलय", "सृष्टि", "पुण्य"], "प्रलय का विलोम सृष्टि है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Which of these is not a synonym of बिजली?", ["चपला", "चंचला", "तड़ित", "ज्योत्सना"], "'ज्योत्सना' means moonlight, not lightning."],
    ["निम्नलिखित में से कौन सा शब्द बिजली का पर्यायवाची नहीं है?", ["चपला", "चंचला", "तड़ित", "ज्योत्सना"], "'ज्योत्सना' का अर्थ चाँदनी है, बिजली नहीं।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["Choose the synonym: कैवल्य", ["निर्वाण", "केशव", "केवल", "दण्ड"], "कैवल्य (liberation) is a synonym of निर्वाण."],
    ["समानार्थी शब्द का चयन कीजिए: कैवल्य", ["निर्वाण", "केशव", "केवल", "दण्ड"], "कैवल्य (मोक्ष) का समानार्थी निर्वाण है।"]),
  q(4, "hindi", "paryay-vilom", "E", 1,
    ["What is the antonym of “मिलन”?", ["अमिलन", "विरह", "मिलनी", "समिलन"], "The opposite of मिलन (union) is विरह (separation)."],
    ["“मिलन” का विलोम क्या है?", ["अमिलन", "विरह", "मिलनी", "समिलन"], "मिलन का विलोम विरह है।"]),
  q(4, "hindi", "vyakaran", "M", 2,
    ["Which adjective is used in the phrase “सारी फसल”?", ["Quality (गुणवाचक)", "Numeral (संख्यावाचक)", "Quantity (परिमाणवाचक)", "Pronominal (सार्वनामिक)"], "'सारी' tells the amount of crop, so it is a quantity adjective."],
    ["“सारी फसल” वाक्यांश में कौन सा विशेषण प्रयुक्त हुआ है?", ["गुणवाचक", "संख्यावाचक", "परिमाणवाचक", "सार्वनामिक"], "'सारी' फसल की मात्रा बताता है, इसलिए यह परिमाणवाचक विशेषण है।"]),
  q(4, "hindi", "paryay-vilom", "E", 1,
    ["Which is a synonym of “कुंजर”?", ["Man", "Elephant", "Monkey", "Squirrel"], "'कुंजर' means elephant (गज)."],
    ["“कुंजर” का पर्यायवाची है?", ["नर", "गज", "वानर", "गिलहरी"], "'कुंजर' का अर्थ हाथी (गज) है।"]),
  q(1, "general-studies", "general-science", "E", 1,
    ["The Paralympic Games are associated with:", ["only snow and winter sports", "athletes with a special physical disability", "only teenage athletes", "hobbyist youth"], "The Paralympics are for athletes with physical disabilities."],
    ["पैरालिम्पिक खेलों (Paralympics) का संबंध है:", ["केवल बर्फीले और शीतकालीन खेलों से", "विशेष रूप से शारीरिक विकलांगता वाले एथलीटों से", "केवल किशोर एथलीटों से", "शौकिया युवाओं से"], "पैरालिम्पिक खेल शारीरिक विकलांगता वाले एथलीटों के लिए हैं।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["National Voters' Day is celebrated every year on ________:", ["25 November", "25 October", "25 December", "25 January"], "National Voters' Day is observed on 25 January, the Election Commission's foundation day."],
    ["राष्ट्रीय मतदाता दिवस प्रतिवर्ष ________ को मनाया जाता है:", ["25 नवम्बर", "25 अक्टूबर", "25 दिसम्बर", "25 जनवरी"], "राष्ट्रीय मतदाता दिवस 25 जनवरी (चुनाव आयोग स्थापना दिवस) को मनाया जाता है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["“Kangra Vadhu” is a painting by:", ["Nicholas Roerich", "Sardar Sobha Singh", "Amrita Sher-Gil", "M. F. Husain"], "Sardar Sobha Singh painted 'Kangra Bride' (Kangra Vadhu)."],
    ["“कांगड़ा वधू” एक चित्रकला कृति है:", ["निकोलस रोरिक की", "सरदार शोभा सिंह की", "अमृता शेरगिल की", "एम. एफ. हुसैन की"], "'कांगड़ा वधू' सरदार शोभा सिंह की कृति है।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["Which award has been given to the spiritual leader Dalai Lama?", ["Bharat Ratna", "Ramon Magsaysay Award", "Nobel Peace Prize", "Booker Prize"], "The Dalai Lama received the Nobel Peace Prize in 1989."],
    ["धर्मगुरु दलाई लामा को इनमें से कौन सा पुरस्कार मिला है:", ["भारत रत्न", "मैगसेसे पुरस्कार", "नोबेल शान्ति पुरस्कार", "बुकर पुरस्कार"], "दलाई लामा को 1989 में नोबेल शान्ति पुरस्कार मिला।"]),
  q(1, "general-studies", "general-science", "E", 3,
    ["Who is the founder of the social networking site “FACEBOOK”?", ["Bill Gates", "Bill Clinton", "Steve Jobs", "Mark Zuckerberg"], "Mark Zuckerberg founded Facebook in 2004."],
    ["सोशल नेटवर्किंग साइट “FACEBOOK” का संस्थापक कौन है:", ["बिल गेट्स", "बिल क्लिंटन", "स्टीव जॉब्स", "मार्क ज़ुकरबर्ग"], "मार्क ज़ुकरबर्ग ने 2004 में फेसबुक की स्थापना की।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["Which country refused to sign the Kyoto Protocol?", ["Japan", "China", "India", "America"], "The United States refused to ratify the Kyoto Protocol."],
    ["इनमें से किस देश ने क्योटो प्रोटोकाल पर हस्ताक्षर करने से मना किया है:", ["जापान", "चीन", "भारत", "अमरीका"], "अमरीका ने क्योटो प्रोटोकॉल की पुष्टि करने से इनकार किया।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Which of the following is not a permanent member of the UN Security Council:", ["India", "China", "Russia", "France"], "The permanent members are the US, UK, France, Russia and China; India is not one."],
    ["निम्नलिखित में से कौन संयुक्त राष्ट्र सुरक्षा परिषद का स्थायी सदस्य नहीं है:", ["भारत", "चीन", "रूस", "फ्रांस"], "स्थायी सदस्य अमरीका, ब्रिटेन, फ्रांस, रूस और चीन हैं; भारत नहीं है।"]),
  q(0, "hp-gk", "history", "M", 0,
    ["The Indian Institute of Advanced Study in Shimla was earlier known as:", ["Viceregal Lodge", "Boni Moon", "Wildflower Hall", "Auckland House"], "The Institute is housed in the former Viceregal Lodge."],
    ["भारतीय उच्च अध्ययन संस्थान पूर्व में ________ नाम से जाना जाता था:", ["वाइस रीगल लॉज", "बोनी मून", "वाइल्ड फ्लावर हाल", "आकर्लैंड हाउस"], "यह संस्थान पूर्व वाइसरीगल लॉज में स्थित है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Athlete Milkha Singh was associated with which sport?", ["Athletics", "Golf", "Hockey", "Football"], "Milkha Singh, the 'Flying Sikh', was a sprinter."],
    ["खिलाड़ी जीव मिल्खा सिंह किस खेल से जुड़े हैं:", ["एथलेटिक्स", "गोल्फ", "हाकी", "फुटबॉल"], "मिल्खा सिंह 'उड़न सिख' एथलेटिक्स (दौड़) से जुड़े थे।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["What is CNG?", ["Conduced Natural Gas", "Converted Natural Gas", "Compressed Natural Gas", "Common Natural Gas"], "CNG stands for Compressed Natural Gas."],
    ["CNG क्या है:", ["Conduced Natural Gas", "Converted Natural Gas", "Compressed Natural Gas", "Common Natural Gas"], "CNG का पूर्ण रूप Compressed Natural Gas है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["Chandratal Lake is situated in which district?", ["Kinnaur", "Lahaul and Spiti", "Kullu", "Mandi"], "Chandratal lake is in the Spiti valley of Lahaul and Spiti district."],
    ["चन्द्रताल झील किस जिले में स्थित है:", ["किन्नौर", "लाहौल एवं स्पीति", "कुल्लू", "मण्डी"], "चन्द्रताल झील लाहौल-स्पीति जिले की स्पीति घाटी में है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["Who is the first Indian woman gymnast to qualify for the Olympic Games?", ["P. T. Usha", "Saina Nehwal", "Dipa Karmakar", "Deepika Salgaonkar"], "Dipa Karmakar qualified for the Rio 2016 Olympics."],
    ["भारत की प्रथम महिला जिमनास्ट जिसने ओलंपिक खेलों के लिए क्वालिफाई किया है:", ["पी. टी. ऊषा", "साइना नेहवाल", "दीपा करमाकर", "दीपिका सालगांवकर"], "दीपा करमाकर ने रियो 2016 ओलंपिक के लिए क्वालिफाई किया।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["Where is the Roerich Art Gallery situated?", ["Naggar", "Solan", "Rajban", "Guler"], "The Roerich Art Gallery is at Naggar in Kullu."],
    ["रोरिक आर्ट गैलरी कहाँ स्थित है:", ["नग्गर", "सोलन", "राजबन", "गुलेर"], "रोरिक आर्ट गैलरी कुल्लू के नग्गर में है।"]),
  q(2, "reasoning", "ranking", "M", 2,
    ["Ram is younger than Shyam but older than Gautam. Govind is older than Mohan but younger than Gautam. If Mahesh is older than all of these, who is the youngest?", ["Ram", "Gautam", "Mohan", "Govind"], "Order of age: Mahesh > Shyam > Ram > Gautam > Govind > Mohan, so Mohan is the youngest."],
    ["राम श्याम से छोटा है, लेकिन गौतम से बड़ा है। गोविन्द मोहन से बड़ा है लेकिन गौतम से छोटा है, यदि महेश इन सबसे बड़ा हो तो बताइए सबसे छोटा कौन है?", ["राम", "गौतम", "मोहन", "गोविन्द"], "आयु क्रम: महेश > श्याम > राम > गौतम > गोविन्द > मोहन, इसलिए मोहन सबसे छोटा है।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Who is the author of the Panchatantra?", ["Vishnu Sharma", "Colonel Ranjit", "V. K. Sharma", "Munshi Premchand"], "The Panchatantra was composed by Vishnu Sharma."],
    ["पंचतंत्र के लेखक कौन हैं:", ["विष्णु शर्मा", "कर्नल रंजीत", "वी. के. शर्मा", "मुंशी प्रेमचंद"], "पंचतंत्र की रचना विष्णु शर्मा ने की।"]),
  q(2, "reasoning", "series", "M", 2,
    ["Complete the series: 7, 10, 8, 11, 9, 12, ?", ["11", "7", "10", "13"], "Two series alternate: 7, 8, 9, 10 and 10, 11, 12; the next term is 10."],
    ["श्रेणी को पूर्ण करें: 7, 10, 8, 11, 9, 12, ?", ["11", "7", "10", "13"], "दो श्रेणियाँ एकांतर हैं: 7, 8, 9, 10 और 10, 11, 12; अगला पद 10 है।"]),
  q(3, "quant", "algebra", "E", 2,
    ["What does the mathematical symbol ∝ mean?", ["Infinity", "Multiplied by this", "Proportional to this", "Equal to this"], "The symbol ∝ means 'is proportional to'."],
    ["गणितीय चिन्ह ∝ का अर्थ है:", ["अनन्त संख्या", "इससे गुणित किया गया", "इसके आनुपातिक", "इसके सर्वसम समान"], "चिन्ह ∝ का अर्थ 'के समानुपाती' है।"]),
  q(2, "reasoning", "odd-one-out", "E", 2,
    ["Choose the odd one out:", ["Banana", "Apple", "Carrot", "Orange"], "Carrot is a vegetable; the others are fruits."],
    ["इनमें से विषम को चुनें:", ["केला", "सेब", "गाजर", "संतरा"], "गाजर सब्ज़ी है; बाकी फल हैं।"]),
  q(2, "reasoning", "series", "M", 3,
    ["Find the missing term of the given series: AQ, DR, GS, ____, MU, PV", ["HT", "IT", "TJ", "JT"], "First letters go A, D, G, J, M, P (+3) and second letters Q, R, S, T, U, V, so the missing term is JT."],
    ["दी गई श्रेणी का लुप्त पद ज्ञात कीजिए: AQ, DR, GS, ____, MU, PV", ["HT", "IT", "TJ", "JT"], "पहले अक्षर A, D, G, J, M, P (+3) और दूसरे Q, R, S, T, U, V हैं, इसलिए लुप्त पद JT है।"]),
  q(2, "reasoning", "series", "M", 2,
    ["Choose the term that completes the series: EMS, DLR, CKQ, ____, AIO", ["KBP", "CBP", "BJP", "PJB"], "Each letter moves back by one: E, D, C, B, A; M, L, K, J, I; S, R, Q, P, O, so the missing term is BJP."],
    ["दिए गए विकल्पों में से सही उत्तर चुनिए जो श्रेणी को पूर्ण करे: EMS, DLR, CKQ, ____, AIO", ["KBP", "CBP", "BJP", "PJB"], "हर अक्षर एक स्थान पीछे जाता है: E, D, C, B, A; M, L, K, J, I; S, R, Q, P, O, इसलिए लुप्त पद BJP है।"]),
  q(2, "reasoning", "analogy", "M", 2,
    ["Atmosphere : Aeroplane :: Sea : ?", ["Shore", "Submarine pit", "Ship", "Boat"], "An aeroplane moves in the atmosphere as a ship does on the sea."],
    ["वायुमण्डल : वायुयान :: समुद्र : ?", ["किनारा", "पनडुब्बी", "जहाज", "किश्ती"], "वायुयान वायुमण्डल में चलता है, वैसे ही जहाज समुद्र में चलता है।"]),
  q(2, "reasoning", "direction-sense", "M", 1,
    ["Ravi walked 15 km towards the east, then turned left and walked 5 km, then turned left again and walked 15 km. How far is he from the starting point?", ["30 km", "5 km", "35 km", "15 km"], "He ends up exactly 5 km north of the starting point."],
    ["रवि पूर्व दिशा में 15 कि.मी. गया तब वह बाएँ मुड़कर 5 कि.मी. चला। फिर वह बाएँ मुड़कर 15 कि.मी. चला। तो बताइए वह प्रारम्भिक स्थान से कितनी दूर है?", ["30 कि.मी.", "5 कि.मी.", "35 कि.मी.", "15 कि.मी."], "वह प्रारम्भिक स्थान से ठीक 5 कि.मी. उत्तर में पहुँचता है।"]),
  q(2, "reasoning", "puzzles", "M", 2,
    ["Four seats are empty in a picture hall. In how many ways can four women be seated on these four seats?", ["16", "20", "24", "28"], "The number of arrangements is 4! = 24."],
    ["एक पिक्चर हाल में चार सीटें खाली हैं। इन चारों सीटों पर चार महिलाओं को कितनी तरह से बैठाया जा सकता है?", ["16", "20", "24", "28"], "कुल तरीके 4! = 24 हैं।"]),
  q(2, "reasoning", "coding-decoding", "M", 2,
    ["If RACE = 4793, FACT = 1795, FORCE = 16493, what will REACT be in the same language?", ["43759", "43975", "43795", "59734"], "R=4, E=3, A=7, C=9, T=5, so REACT = 43795."],
    ["यदि किसी भाषा में RACE = 4793, FACT = 1795, FORCE = 16493 लिखा जाता है, तो उसी भाषा में REACT को क्या लिखा जाएगा?", ["43759", "43975", "43795", "59734"], "R=4, E=3, A=7, C=9, T=5, इसलिए REACT = 43795।"]),
  q(2, "reasoning", "alphabet-test", "M", 2,
    ["Arrange the words in dictionary order: 1. Wound 2. Writer 3. White 4. Worst 5. Worked", ["5,3,2,1,4", "1,3,5,2,4", "3,5,4,1,2", "2,1,3,4,5"], "Dictionary order is White, Worked, Worst, Wound, Writer = 3, 5, 4, 1, 2."],
    ["दिए गए शब्दों को शब्दकोश (Dictionary) में उनके क्रम के अनुसार क्रमबद्ध करें: 1. Wound 2. Writer 3. White 4. Worst 5. Worked", ["5,3,2,1,4", "1,3,5,2,4", "3,5,4,1,2", "2,1,3,4,5"], "शब्दकोश क्रम White, Worked, Worst, Wound, Writer = 3, 5, 4, 1, 2 है।"]),
  q(2, "reasoning", "ranking", "M", 1,
    ["Rahul's rank in his class is 9th from the top and 38th from the bottom. How many students are there in his class?", ["45", "46", "47", "48"], "Total = 9 + 38 − 1 = 46."],
    ["राहुल का स्थान अपनी कक्षा में ऊपर से 9वाँ है तथा नीचे से 38वाँ है, उसकी कक्षा में कुल कितने छात्र हैं?", ["45", "46", "47", "48"], "कुल = 9 + 38 − 1 = 46।"]),
  q(2, "reasoning", "clock-calendar", "M", 1,
    ["If 24 January 1994 is a Monday, what day will 24 January 1995 be?", ["Monday", "Tuesday", "Wednesday", "Sunday"], "365 days is 52 weeks and 1 day, so the day moves forward by one: Tuesday."],
    ["यदि आज 24 जनवरी 1994 को दिन सोमवार है तो 24 जनवरी 1995 को कौन सा दिन होगा?", ["सोमवार", "मंगलवार", "बुधवार", "रविवार"], "365 दिन = 52 सप्ताह + 1 दिन, इसलिए दिन एक आगे बढ़ता है: मंगलवार।"]),
  q(0, "hp-gk", "economy", "M", 1,
    ["The Kol Dam project is associated with which organisation?", ["NHPC", "NTPC", "J.P. Hydro", "HCC"], "The Kol Dam hydroelectric project on the Satluj is built by NTPC."],
    ["कोल डैम परियोजना, किस संगठन से संबन्धित है:", ["NHPC", "NTPC", "J.P. HYDRO", "HCC"], "सतलुज पर बनी कोल डैम जल-विद्युत परियोजना NTPC की है।"]),
  q(2, "reasoning", "alphabet-test", "M", 3,
    ["From the given options choose the word that cannot be formed from the letters of the word LEGISLATURE:", ["Salute", "Gesture", "Serial", "Slaughter"], "'Slaughter' needs an H, which is not in LEGISLATURE."],
    ["दिए गए वैकल्पिक शब्दों में से उस शब्द को चुनिए, जो नीचे दिए गए शब्द के अक्षरों से नहीं बनाया जा सकता है? LEGISLATURE", ["Salute", "Gesture", "Serial", "Slaughter"], "'Slaughter' में H चाहिए, जो LEGISLATURE में नहीं है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["Which system of the body is affected by AIDS?", ["Digestive system", "Respiratory system", "Central nervous system", "Immune system"], "AIDS destroys the body's immune system."],
    ["एड्स रोग के द्वारा कौन सा तंत्र प्रभावित होता है?", ["पाचन तंत्र", "श्वसन तंत्र", "केन्द्रीय तंत्रिका तंत्र", "प्रतिरक्षा तंत्र"], "एड्स शरीर के प्रतिरक्षा तंत्र को नष्ट करता है।"]),
  q(1, "general-studies", "general-science", "E", 1,
    ["What is the chemical formula of baking soda?", ["NaCl", "NaHCO3", "NaOH", "KNO3"], "Baking soda is sodium bicarbonate, NaHCO3."],
    ["खाने के सोडे का रासायनिक सूत्र है:", ["NaCl", "NaHCO3", "NaOH", "KNO3"], "खाने का सोडा सोडियम बाइकार्बोनेट, NaHCO3 है।"]),
  q(3, "quant", "percentage", "M", 3,
    ["If 2/7 of the value of a house is Rs 28,000, what is the value of the whole house?", ["Rs 9,60,000", "Rs 9,70,000", "Rs 9,80,000", "None of these"], "Whole value = 28000 × 7 / 2 = Rs 98,000, which is none of the given options."],
    ["यदि किसी घर के मूल्य के 2/7 हिस्से की कीमत 28000 रु० है तो पूरे घर की कीमत क्या होगी?", ["9,60,000 रु०", "9,70,000 रु०", "9,80,000 रु०", "इनमें से कोई नहीं"], "पूरे घर का मूल्य = 28000 × 7 / 2 = 98,000 रु० है, जो किसी विकल्प में नहीं है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Which part of the eye is donated in eye donation?", ["Cornea", "Lens", "Retina", "The whole eye"], "Only the cornea is donated and transplanted."],
    ["नेत्र दान में नेत्र का कौन सा हिस्सा दान दिया जाता है?", ["कॉर्निया", "लेन्स", "रेटिना", "पूरा नेत्र"], "नेत्र दान में केवल कॉर्निया दान किया और प्रत्यारोपित किया जाता है।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["What is the main function of the kidneys?", ["Controlling blood pressure", "Controlling body temperature", "Removing waste products from the body", "Helping digest food"], "The kidneys filter blood and remove waste products as urine."],
    ["गुर्दों का मुख्य कार्य क्या है?", ["रक्तचाप को नियंत्रित रखना", "शरीर के तापमान का नियंत्रण", "शरीर से बेकार चीजों (Waste products) को बाहर करना", "भोजन के पाचन में सहायता करना"], "गुर्दे रक्त को छानकर अपशिष्ट पदार्थों को मूत्र के रूप में बाहर निकालते हैं।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Which gland is known as the master gland?", ["Pituitary gland", "Thyroid gland", "Reproductive gland", "Adrenal gland"], "The pituitary controls the other endocrine glands, so it is the master gland."],
    ["निम्नलिखित में किसे मास्टर ग्रंथि के नाम से जाना जाता है?", ["पियूष ग्रंथि", "अवटु ग्रंथि", "जनन ग्रंथि", "अधिवृक्क ग्रंथि"], "पीयूष ग्रंथि अन्य अंतःस्रावी ग्रंथियों को नियंत्रित करती है, इसलिए यह मास्टर ग्रंथि है।"]),
  q(3, "quant", "profit-loss", "M", 1,
    ["The marked price of a bag is Rs 80 but it is sold for Rs 68. What percent discount is being given on the bag?", ["12 %", "15 %", "17 11/17 %", "20 %"], "Discount = 12/80 × 100 = 15%."],
    ["एक बैग का अंकित मूल्य 80 रु० है परन्तु इसे 68 रु० में बेचा जाता है। इस बैग पर कितने प्रतिशत डिस्काउंट दिया जा रहा है?", ["12 %", "15 %", "17 11/17 %", "20 %"], "छूट = 12/80 × 100 = 15%।"]),
  q(1, "computer", "web-technologies", "E", 0,
    ["URL stands for:", ["UNIFORM RESOURCE LOCATOR", "UNIFORM RESEARCH LINK", "UNIFORM RESOURCE LINK", "UNIFIED REGISTERED LINK"], "URL stands for Uniform Resource Locator."],
    ["URL से तात्पर्य है:", ["UNIFORM RESOURCE LOCATOR", "UNIFORM RESEARCH LINK", "UNIFORM RESOURCE LINK", "UNIFIED REGISTERED LINK"], "URL का पूर्ण रूप Uniform Resource Locator है।"]),
  q(3, "quant", "simplification", "M", 3,
    ["1 3/4 + 5 1/3 + 3 2/5 = ?", ["9 2/5", "9 29/60", "10 2/5", "10 29/60"], "Whole parts: 1 + 5 + 3 = 9; fractions: 3/4 + 1/3 + 2/5 = (45 + 20 + 24)/60 = 89/60 = 1 29/60. Total = 10 29/60."],
    ["1 3/4 + 5 1/3 + 3 2/5 = ?", ["9 2/5", "9 29/60", "10 2/5", "10 29/60"], "पूर्णांक: 1 + 5 + 3 = 9; भिन्न: 3/4 + 1/3 + 2/5 = (45 + 20 + 24)/60 = 89/60 = 1 29/60। कुल = 10 29/60।"]),
  q(1, "general-studies", "general-science", "E", 3,
    ["Hepatitis is inflammation of which organ?", ["Stomach", "Kidneys", "Lungs", "Liver"], "Hepatitis is inflammation of the liver."],
    ["Hepatitis, किसका प्रदाह (inflammation) है?", ["उदर", "गुर्दे", "फेफड़े", "लिवर"], "हेपेटाइटिस यकृत (लिवर) का प्रदाह है।"]),
  q(1, "general-studies", "general-science", "E", 1,
    ["Which part of the blood provides immunity?", ["RBC", "WBC", "Platelets", "Blood plasma"], "White blood cells fight infection and give immunity."],
    ["रक्त कोशिका का कौन सा भाग, रोग-प्रतिरोधक क्षमता (immunity) प्रदान करता है?", ["RBC", "WBC", "PLATELET", "रक्त प्लाज़मा"], "श्वेत रक्त कोशिकाएँ (WBC) संक्रमण से लड़ती हैं और प्रतिरक्षा देती हैं।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["What is the main component of the Earth's atmosphere?", ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"], "Nitrogen makes up about 78% of the atmosphere."],
    ["पृथ्वी के वायुमण्डल का मुख्य घटक क्या है?", ["नाइट्रोजन", "आक्सीजन", "कार्बन डाइऑक्साइड", "हाइड्रोजन"], "वायुमण्डल का लगभग 78% भाग नाइट्रोजन है।"]),
  q(3, "quant", "ratio-proportion", "M", 0,
    ["If A : B = 2 : 3 and B : C = 4 : 5, then C : A = ?", ["15 : 8", "12 : 10", "8 : 5", "8 : 15"], "A : B : C = 8 : 12 : 15, so C : A = 15 : 8."],
    ["यदि A : B = 2 : 3 तथा B : C = 4 : 5 हो तब C : A क्या होगा?", ["15 : 8", "12 : 10", "8 : 5", "8 : 15"], "A : B : C = 8 : 12 : 15, इसलिए C : A = 15 : 8।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["The light year is a unit of which of the following?", ["Electric current", "Luminous intensity", "Distance", "Heat"], "A light year is the distance light travels in one year."],
    ["प्रकाश वर्ष निम्नलिखित में किसका मात्रक है?", ["विद्युत धारा", "ज्योति तीव्रता", "दूरी", "ताप"], "प्रकाश वर्ष वह दूरी है जो प्रकाश एक वर्ष में तय करता है।"]),
  q(3, "quant", "algebra", "M", 3,
    ["If 18 : X = X : 8, then X = ?", ["144", "72", "26", "12"], "X² = 18 × 8 = 144, so X = 12."],
    ["यदि 18 : X = X : 8 हो तो X = ?", ["144", "72", "26", "12"], "X² = 18 × 8 = 144, इसलिए X = 12।"]),
];
