// HP Police Constable written exam held on 27 March 2022 (Series D) — transcribed from the photographed paper. No official
// key was available: answers were solved independently (handwritten marks on the scan were only a cross-check).
// Left out because unreadable, truncated or ambiguous: original numbers 12, 27, 35, 36, 37, 41, 45, 49, 56, 61, 62, 63.
// Option order is kept as printed. Sections: 0 Himachal GK, 1 General Knowledge, 2 Reasoning, 3 Numerical Ability, 4 Hindi & English.

import { q, type PoliceQuestion } from "../police/types";

const BOX_EN =
  "Eight boxes are placed one above the other. Only two boxes are placed between U and T. Only one box is placed between T and R. Only two boxes are placed between R and V. Box V is placed below box R. Three boxes are placed between S and Q. Both S and Q are placed above box T. Box W is placed below box V. No box is placed between S and P.";
const BOX_HI =
  "8 डब्बे एक दूसरे पर रखे गए हैं। U एवं T डब्बों के मध्य केवल दो डब्बे हैं। T एवं R डब्बों के मध्य केवल एक डब्बा है। R एवं V डब्बों के मध्य केवल दो डब्बे हैं। डब्बा V, डब्बा R के नीचे है। S एवं Q डब्बों के मध्य तीन डब्बे हैं। S एवं Q डब्बे, डब्बा T के ऊपर रखे हैं। डब्बा W, डब्बा V के नीचे रखा है। S एवं P डब्बों के मध्य कोई डब्बा नहीं है।";
const BOX_SOL = "Solving from the top: S, P, U, R, Q, T, V, W.";
const BOX_SOL_HI = "ऊपर से नीचे का क्रम: S, P, U, R, Q, T, V, W।";

export const y2022mar: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK ─────────
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["Find the odd one out: Ranjit Sagar lake, Gobind Sagar lake, Maharana Pratap Sagar, Prashar lake.", ["Prashar lake", "Gobind Sagar lake", "Maharana Pratap Sagar", "Ranjit Sagar lake"], "Ranjit Sagar, Gobind Sagar and Maharana Pratap Sagar (Pong) are man-made reservoirs behind dams; Prashar is a natural lake."],
    ["अजीब / अलग का चयन करें। रणजीत सागर झील, गोबिंद सागर झील, महाराणा प्रताप सागर, पराशर झील।", ["पराशर झील", "गोबिंद सागर झील", "महाराणा प्रताप सागर", "रणजीत सागर झील"], "रणजीत सागर, गोबिंद सागर और महाराणा प्रताप सागर (पोंग) बाँधों से बनी कृत्रिम झीलें हैं; पराशर प्राकृतिक झील है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 3,
    ["The Larji Hydroelectric Power Project is built on which river?", ["Parbati", "Baner", "Baspa", "Beas"], "The 126 MW Larji project is on the Beas river near Larji in Mandi district."],
    ["लारजी विद्युत परियोजना ______ नदी पर बनाई गई है?", ["पार्वती", "बनेर", "बासपा", "ब्यास"], "126 मेगावाट की लारजी परियोजना मंडी जिले के लारजी के पास ब्यास नदी पर बनी है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["Which cultural festival is celebrated at the 'Varanasi of the hills' or Chhoti Kashi?", ["Maha Shivratri", "Losar", "Sazo", "Doongri"], "Mandi is called Chhoti Kashi, and its International Shivratri fair is famous."],
    ["पहाड़ों की वाराणसी अथवा छोटी काशी में कौन सा सांस्कृतिक उत्सव मनाया जाता है?", ["महा शिवरात्रि", "लोसर", "साजो", "डूंगरी"], "मंडी को छोटी काशी कहा जाता है और यहाँ का अंतरराष्ट्रीय शिवरात्रि मेला प्रसिद्ध है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 0,
    ["Which of the following groups of rivers originate from the Himachal mountains?", ["Beas, Ravi and Chenab", "Ravi, Chenab and Jhelum", "Sutlej, Beas and Ravi", "Sutlej, Ravi and Jhelum"], "Beas (Beas Kund), Ravi (Bara Bhangal) and Chenab (formed by Chandra and Bhaga in Lahaul) originate in Himachal. Sutlej rises in Tibet and Jhelum in Kashmir."],
    ["निम्नलिखित में से कौन सी नदियां हिमाचल प्रदेश के पर्वतों से निकलती है?", ["ब्यास, रावी व चिनाब", "रावी, चिनाब व झेलम", "सतलुज, ब्यास व रावी", "सतलुज, रावी व झेलम"], "ब्यास (ब्यास कुंड), रावी (बड़ा भंगाल) और चिनाब (लाहौल में चंद्रा-भागा के मिलन से) हिमाचल से निकलती हैं। सतलुज तिब्बत और झेलम कश्मीर से निकलती है।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["The Pir Panjal range is located in which neighbouring state of Himachal Pradesh?", ["Haryana", "Punjab", "Jammu & Kashmir", "Uttarakhand"], "The Pir Panjal range runs through Jammu & Kashmir (and Kullu-Chamba in Himachal), and Jammu & Kashmir is the neighbouring state among the options."],
    ["पीर पंजाल पर्वत श्रृंखला हिमाचल प्रदेश के किस पड़ोसी राज्य में स्थित है?", ["हरियाणा", "पंजाब", "जम्मू व कश्मीर", "उत्तराखंड"], "पीर पंजाल श्रेणी जम्मू-कश्मीर (तथा हिमाचल के कुल्लू-चंबा) से गुजरती है; विकल्पों में पड़ोसी राज्य जम्मू-कश्मीर है।"]),
  q(0, "hp-gk", "geography", "E", 3,
    ["The state animal of Himachal Pradesh is:", ["Tiger", "Lion", "Bison", "Snow leopard"], "The snow leopard (Him Tendua) is the state animal of Himachal Pradesh."],
    ["हिमाचल प्रदेश का राज्य पशु कौन है?", ["बाघ", "शेर", "बाइसन", "हिम तेंदुआ"], "हिम तेंदुआ हिमाचल प्रदेश का राज्य पशु है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["Which is the biggest natural lake in Himachal Pradesh?", ["Renuka Lake", "Rewalsar Lake", "Khajjiar Lake", "Brighu Lake"], "Renuka Lake (Sirmaur) is the largest natural lake of Himachal Pradesh."],
    ["हिमाचल प्रदेश की सबसे बड़ी प्राकृतिक झील कौन सी है?", ["रेणुका झील", "रिवालसर झील", "खजियार झील", "भृगु झील"], "सिरमौर की रेणुका झील हिमाचल प्रदेश की सबसे बड़ी प्राकृतिक झील है।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["In which year was Shimla declared the summer capital of British India?", ["1858", "1864", "1869", "1871"], "Shimla was declared the summer capital of British India in 1864."],
    ["शिमला को ब्रिटिश भारत की ग्रीष्मकालीन राजधानी किस वर्ष में घोषित किया गया था?", ["1858", "1864", "1869", "1871"], "शिमला को 1864 में ब्रिटिश भारत की ग्रीष्मकालीन राजधानी घोषित किया गया।"]),

  // ───────── Section 1: General Knowledge ─────────
  q(1, "general-studies", "general-science", "E", 1,
    ["The BCG vaccine is used to prevent:", ["Measles", "Tuberculosis", "Diphtheria", "Leprosy"], "BCG (Bacillus Calmette–Guérin) protects against tuberculosis."],
    ["BCG का टीका किसे रोकने में सहायक है?", ["मीजल्स", "यक्ष्मा", "डिफ्थीरिया", "लेपरसी / कुष्ठ रोग"], "बी.सी.जी. (बैसिलस कैलमेट-गुएरिन) टीका तपेदिक (यक्ष्मा) से बचाव करता है।"]),
  q(1, "general-studies", "general-science", "M", 0,
    ["Which colours of light deviate the least and the most respectively?", ["Red and Violet", "Red and Blue", "Violet and Blue", "Green and Red"], "Red has the longest wavelength and bends least; violet has the shortest wavelength and bends most."],
    ["किरणों के रंग जो सबसे कम व अधिक विचलित होते हैं।", ["लाल व बैंगनी रंग", "लाल एवं नीला", "बैंगनी रंग एवं नीला", "हरा एवं लाल"], "लाल रंग की तरंगदैर्ध्य सबसे अधिक होती है और वह सबसे कम मुड़ता है; बैंगनी की सबसे कम होती है और वह सबसे अधिक मुड़ता है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["Omega-3 fatty acid is NOT found in:", ["Fish oil", "Walnuts", "Flax seeds", "Lettuce"], "Fish oil, walnuts and flax seeds are rich sources of omega-3; lettuce has only negligible amounts."],
    ["इनमें से किस में ओमेगा -3 फेटी एसिड नहीं पाया जाता है?", ["मछली का तेल", "अखरोट", "अलसी", "सलाद पत्ता"], "मछली का तेल, अखरोट और अलसी ओमेगा-3 के अच्छे स्रोत हैं; सलाद पत्ते में यह नगण्य मात्रा में होता है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["Which of the following is a synthetic drug?", ["Charas", "Opium", "Heroin", "Hashish"], "Charas, opium and hashish are natural (cannabis or poppy) products; heroin is manufactured chemically from morphine."],
    ["निम्नलिखित में कौन सी सिंथेटिक ड्रग है?", ["चरस", "अफीम", "हेरोइन", "हशीश"], "चरस, अफीम और हशीश भांग/पोस्त से मिलने वाले प्राकृतिक पदार्थ हैं; हेरोइन मॉर्फिन से रासायनिक विधि से बनती है।"]),
  q(1, "general-studies", "general-science", "E", 1,
    ["Which of the following is not a radioactive element?", ["Uranium", "Boron", "Radium", "Plutonium"], "Uranium, radium and plutonium are radioactive; boron is a stable element."],
    ["इनमें से कौन सा रेडियोधर्मी तत्व नहीं है?", ["यूरेनियम", "बोरोन", "रेडियम", "प्लूटोनियम"], "यूरेनियम, रेडियम और प्लूटोनियम रेडियोधर्मी हैं; बोरोन स्थायी तत्व है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["______ oil is used in the froth flotation process.", ["Coconut oil", "Olive oil", "Pine oil", "Kerosene"], "Pine oil is used as a frothing agent in the froth flotation process for concentrating sulphide ores."],
    ["______ तेल का उपयोग झाग प्लवनशीलता प्रक्रिया में होता है?", ["नारियल तेल", "जैतून तेल", "चीड़ का तेल", "मिट्टी का तेल"], "सल्फाइड अयस्कों के सांद्रण की झाग प्लवन प्रक्रिया में चीड़ का तेल झाग बनाने वाले पदार्थ के रूप में प्रयुक्त होता है।"]),
  q(1, "general-studies", "general-science", "E", 3,
    ["Salmonella Typhi bacteria cause which life-threatening disease?", ["Tetanus", "Tuberculosis", "Trichinosis", "Typhoid"], "Salmonella Typhi causes typhoid (enteric) fever."],
    ["सालमोनेला टायफी जीवाणु कौन सी प्राण घातक बीमारी के लिए जिम्मेदार है?", ["टेटनस", "यक्ष्मा", "ट्रिचिनोसिस", "आंत्र ज्वर"], "साल्मोनेला टायफी आंत्र ज्वर (टाइफाइड) का कारण बनता है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["As seen in recent news, the 'E-Daakhil Portal' is associated with which sector?", ["Right to Education", "Consumer Complaints", "Life Certificate", "Income Tax"], "E-Daakhil is the online portal for filing consumer complaints before consumer commissions."],
    ["वर्तमान में समाचारों में वर्णित 'E-Daakhil Portal' किस क्षेत्र के साथ सम्बंधित है?", ["शिक्षा के अधिकार", "उपभोक्ता शिकायतें", "जीवन प्रमाणपत्र", "आयकर"], "ई-दाखिल उपभोक्ता आयोगों में उपभोक्ता शिकायतें ऑनलाइन दर्ज करने का पोर्टल है।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["What fraction of the Rajya Sabha members retires after every two years?", ["2/3", "1/2", "1/3", "1/6"], "Rajya Sabha is a permanent house; one-third of its members retire every two years."],
    ["राज्य सभा के सदस्य प्रत्येक दो वर्ष की अवधि के उपरान्त ______ अंश के मुताबिक सेवानिवृत हो जाते हैं।", ["2/3", "1/2", "1/3", "1/6"], "राज्य सभा स्थायी सदन है; इसके एक-तिहाई सदस्य प्रत्येक दो वर्ष में सेवानिवृत्त होते हैं।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Which among the following states of India has the largest coal reserve?", ["Andhra Pradesh", "Jharkhand", "West Bengal", "Madhya Pradesh"], "Of the states listed, Jharkhand has the largest coal reserves."],
    ["निम्नलिखित में से भारत के कौन से राज्य में कोयले के सबसे बड़े भंडार मौजूद हैं?", ["आंध्र प्रदेश", "झारखण्ड", "पश्चिम बंगाल", "मध्य प्रदेश"], "दिए गए राज्यों में कोयले का सबसे बड़ा भंडार झारखण्ड में है।"]),
  q(1, "general-studies", "indian-geography", "E", 0,
    ["______ soils are mostly confined to the river basins and coastal plains of India.", ["Alluvial soils", "Black soils", "Laterite soils", "Red soils"], "Alluvial soil is deposited by rivers and covers the river valleys and coastal plains."],
    ["______ प्रकार की मिट्टी भारत की अधिकतर नदी घाटियों व तटीय मैदानों में ही पायी जाती है?", ["जलोढ़क", "काली मिट्टी", "लेटराइट मिट्टी", "लाल मिट्टी"], "जलोढ़ मिट्टी नदियों द्वारा जमा की जाती है और नदी घाटियों व तटीय मैदानों में पाई जाती है।"]),
  q(1, "general-studies", "indian-geography", "E", 2,
    ["In which state does the Monsoon arrive first?", ["Assam", "Maharashtra", "Kerala", "Himachal Pradesh"], "The south-west monsoon first hits the Kerala coast, around 1 June."],
    ["किस राज्य में मानसून सर्वप्रथम पहुँचता है?", ["आसाम", "महाराष्ट्र", "केरल", "हिमाचल प्रदेश"], "दक्षिण-पश्चिम मानसून लगभग 1 जून को सबसे पहले केरल तट पर पहुँचता है।"]),
  q(1, "general-studies", "indian-history", "E", 1,
    ["The Jallianwala Bagh massacre took place on the festival day of:", ["Deepawali", "Baisakhi", "Lohri", "Holi"], "The massacre happened on 13 April 1919, the day of Baisakhi."],
    ["जलियां वाला बाग़ हत्याकांड किस त्यौहार के दिन घटित हुआ था?", ["दीपावली", "बैसाखी", "लोहड़ी", "होली"], "यह हत्याकांड 13 अप्रैल 1919 को बैसाखी के दिन हुआ था।"]),
  q(1, "general-studies", "indian-history", "E", 3,
    ["Which movement is known as the August Movement / Kranti?", ["Non-Cooperation Movement", "Khilafat Movement", "Swadeshi Movement", "Quit India Movement"], "The Quit India Movement was launched on 8–9 August 1942 and is called the August Kranti."],
    ["किस आंदोलन को अगस्त आंदोलन / क्रांति के नाम से जाना जाता है?", ["असहयोग आंदोलन", "खिलाफत आंदोलन", "स्वदेशी आंदोलन", "भारत छोड़ो आंदोलन"], "भारत छोड़ो आंदोलन 8–9 अगस्त 1942 को शुरू हुआ और इसे अगस्त क्रांति कहा जाता है।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["In which year was the Non-Cooperation Movement suspended?", ["1922", "1929", "1921", "1927"], "Gandhi suspended the movement in February 1922 after the Chauri Chaura incident."],
    ["असहयोग आंदोलन को किस वर्ष में निलंबित कर दिया गया था?", ["1922", "1929", "1921", "1927"], "चौरी चौरा की घटना के बाद गांधीजी ने फरवरी 1922 में आंदोलन स्थगित कर दिया।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["What is the name of the highest mountain in India?", ["Kanchenjunga", "Nanda Devi", "Sri Kailash", "Jong Song Peak"], "Kanchenjunga (8,586 m) is the highest peak located within India."],
    ["भारत की सबसे ऊँची चोटी का नाम क्या है?", ["कंचनजंगा", "नंदा देवी", "श्री कैलाश", "जोंग सोंग चोटी"], "कंचनजंगा (8,586 मी.) भारत के भीतर स्थित सबसे ऊँची चोटी है।"]),

  // ───────── Section 2: Reasoning ─────────
  q(2, "reasoning", "analogy", "E", 1,
    ["If Everest is to the Himalayas, then Mount Abu is to:", ["Nilgiri", "Aravali", "Vindhyas", "None of these"], "Everest is a peak of the Himalayas; Mount Abu is a hill of the Aravali range."],
    ["अगर ऐवरेस्ट का सम्बन्ध हिमालय से है, तो माउंट आबू का सम्बन्ध किससे होगा?", ["नीलगिरी", "अरावली", "विंध्या", "इनमे से कोई नहीं"], "एवरेस्ट हिमालय की चोटी है; माउंट आबू अरावली श्रृंखला का पर्वत है।"]),
  q(2, "reasoning", "ranking", "H", 3,
    [`${BOX_EN} — How many boxes are placed between box T and box S?`, ["None", "1", "3", "More than 3"], `${BOX_SOL} Between S (1st) and T (6th) are P, U, R and Q: four boxes, i.e. more than 3.`],
    [`${BOX_HI} — डब्बा T एवं डब्बा S के मध्य कितने डब्बे हैं?`, ["कोई नहीं", "एक", "तीन", "तीन से ज्यादा"], `${BOX_SOL_HI} S (पहला) और T (छठा) के बीच P, U, R और Q — चार डब्बे हैं, यानी तीन से ज्यादा।`]),
  q(2, "reasoning", "ranking", "H", 0,
    [`${BOX_EN} — Which of the following boxes is placed at the bottom-most position?`, ["W", "U", "R", "None of these"], `${BOX_SOL} The bottom-most box is W.`],
    [`${BOX_HI} — निम्न में से कौन सा डब्बा सबसे नीचे है?`, ["W", "U", "R", "इनमें से कोई नहीं"], `${BOX_SOL_HI} सबसे नीचे W है।`]),
  q(2, "reasoning", "ranking", "H", 3,
    [`${BOX_EN} — How many boxes are there between box W and box R?`, ["None", "1", "2", "3"], `${BOX_SOL} R is 4th and W is 8th; between them are Q, T and V: three boxes.`],
    [`${BOX_HI} — डब्बा W एवं R के मध्य कितने डब्बे हैं?`, ["कोई नहीं", "एक", "दो", "तीन"], `${BOX_SOL_HI} R चौथा और W आठवाँ है; बीच में Q, T और V — तीन डब्बे हैं।`]),
  q(2, "reasoning", "odd-one-out", "M", 1,
    ["Which one of the following is different from the rest?", ["Barley", "Ground nut", "Mustard", "Peas"], "Barley, mustard and peas are rabi crops; groundnut is a kharif crop."],
    ["निम्नलिखित में कौन सा अन्य से भिन्न है?", ["जौं", "मूंगफली", "सरसों", "मटर"], "जौ, सरसों और मटर रबी की फसलें हैं; मूंगफली खरीफ की फसल है।"]),
  q(2, "reasoning", "coding-decoding", "M", 3,
    ["In a code 'TOGETHER' is denoted by 'RQEGRJCT'. How will 'FRIEND' be denoted in that code?", ["DSHGFL", "FLGGTD", "GGLFDT", "DTGGLF"], "The letters are shifted −2, +2, −2, +2, … So F−2=D, R+2=T, I−2=G, E+2=G, N−2=L, D+2=F: DTGGLF."],
    ["एक कोड में 'TOGETHER' को 'RQEGRJCT' से दर्शाया जाता है, तो 'FRIEND' को उसी कोड में कैसे दर्शाया जायेगा?", ["DSHGFL", "FLGGTD", "GGLFDT", "DTGGLF"], "अक्षरों में क्रमशः −2, +2, −2, +2, … का परिवर्तन है। F−2=D, R+2=T, I−2=G, E+2=G, N−2=L, D+2=F: DTGGLF।"]),
  q(2, "reasoning", "ranking", "E", 2,
    ["Ram's position is thirteenth from the top in a class of 53 students. What will be his position from the bottom?", ["42", "43", "41", "40"], "Position from bottom = 53 − 13 + 1 = 41."],
    ["53 छात्रों की एक कक्षा में राम का स्थान ऊपर से 13वाँ है। उसका स्थान नीचे से कौन सा होगा?", ["42वाँ", "43वाँ", "41वाँ", "40वाँ"], "नीचे से स्थान = 53 − 13 + 1 = 41।"]),
  q(2, "reasoning", "clock-calendar", "M", 1,
    ["February 1, 2009 was a Sunday. What day of the week was March 1, 2011?", ["Wednesday", "Tuesday", "Friday", "Sunday"], "Feb 1, 2009 → Feb 1, 2011 is 730 days = 104 weeks + 2 days, giving Tuesday. Feb 1 → Mar 1, 2011 is 28 days (exact weeks), so March 1, 2011 is a Tuesday."],
    ["फरवरी 1, 2009 को रविवार था। मार्च 1, 2011 को सप्ताह का कौन सा दिन होगा?", ["बुधवार", "मंगलवार", "शुक्रवार", "रविवार"], "1 फरवरी 2009 से 1 फरवरी 2011 तक 730 दिन = 104 सप्ताह + 2 दिन, यानी मंगलवार। 1 फरवरी से 1 मार्च 2011 तक 28 दिन (पूरे सप्ताह), इसलिए 1 मार्च 2011 को मंगलवार था।"]),
  q(2, "reasoning", "coding-decoding", "E", 3,
    ["If dog is called cat, cat is called lion, lion is called ox, ox is called cock, cock is called elephant and elephant is called donkey, then with which animal does a farmer plough?", ["dog", "lion", "donkey", "cock"], "A farmer ploughs with an ox, and 'ox' is called 'cock'."],
    ["यदि कुत्ते को बिल्ली कहा जाये, बिल्ली को शेर, शेर को बैल, बैल को मुर्गा, मुर्गे को हाथी तथा हाथी को गधा कहा जाये तो बताइये कि एक किसान किससे खेती करेगा?", ["कुत्ता", "शेर", "गधा", "मुर्गा"], "किसान बैल से खेती करता है और बैल को 'मुर्गा' कहा गया है।"]),
  q(2, "reasoning", "ranking", "M", 3,
    ["Ram is taller than Shyam but not as tall as Rajan. Arjun is taller than Sohan, who is shorter than Shyam. Who is the shortest?", ["Rajan", "Ram", "Arjun", "Sohan"], "Rajan > Ram > Shyam > Sohan, and Arjun > Sohan. Sohan is shorter than Shyam, Ram, Rajan and Arjun, so Sohan is the shortest."],
    ["राम, श्याम से ऊँचा है, पर राजन जितना नहीं। अर्जुन, सोहन से ऊँचा है जो श्याम से छोटा है। सबसे छोटा कौन है?", ["राजन", "राम", "अर्जुन", "सोहन"], "राजन > राम > श्याम > सोहन और अर्जुन > सोहन। सोहन, श्याम, राम, राजन और अर्जुन सभी से छोटा है, इसलिए सबसे छोटा सोहन है।"]),
  q(2, "reasoning", "math-operations", "M", 2,
    ["If 'a' means '+', 'b' means '−', 'c' means '÷' and 'd' means '×', then 16a4b3c4d2 = ?", ["10", "17", "18.5", "21/2"], "16 + 4 − 3 ÷ 4 × 2 = 20 − 1.5 = 18.5 (division and multiplication first)."],
    ["यदि 'a' का मतलब '+', 'b' का मतलब '−', 'c' का मतलब '÷' तथा 'd' का मतलब '×' है तो 16a4b3c4d2 = ?", ["10", "17", "18.5", "21/2"], "16 + 4 − 3 ÷ 4 × 2 = 20 − 1.5 = 18.5 (पहले भाग और गुणा)।"]),
  q(2, "reasoning", "series", "M", 3,
    ["Fill in the blank with the correct option: 200, 193, 179, 158, ____, 95", ["135", "133", "132", "130"], "The differences are −7, −14, −21, −28, −35: 158 − 28 = 130 and 130 − 35 = 95."],
    ["सही विकल्प से रिक्त स्थान को भरें। 200, 193, 179, 158, ____, 95", ["135", "133", "132", "130"], "अंतर −7, −14, −21, −28, −35 हैं: 158 − 28 = 130 और 130 − 35 = 95।"]),
  q(2, "reasoning", "series", "M", 0,
    ["Fill in the blank with the correct option: 51, 49, 44, 42, 37, ____", ["35", "34", "33", "32"], "The pattern alternates −2, −5, −2, −5, −2: 37 − 2 = 35."],
    ["सही विकल्प से रिक्त स्थान को भरें। 51, 49, 44, 42, 37, ____", ["35", "34", "33", "32"], "क्रम में बारी-बारी −2, −5, −2, −5, −2 है: 37 − 2 = 35।"]),
  q(2, "reasoning", "coding-decoding", "M", 0,
    ["If 'CAB' is written as 312 and 'BIG' is written as 297 in a code, how will 'FEED' be written in that code?", ["6554", "5444", "6534", "5464"], "Each letter is replaced by its alphabet position: C=3, A=1, B=2 → 312; B=2, I=9, G=7 → 297. F=6, E=5, E=5, D=4 → 6554."],
    ["एक कोड में यदि 'CAB' को 312 लिखा जाता है, 'BIG' को 297 लिखा जाता है, तो इसी कोड में 'FEED' को कैसे लिखा जायेगा?", ["6554", "5444", "6534", "5464"], "हर अक्षर को वर्णमाला में उसके स्थान से बदला गया है: C=3, A=1, B=2 → 312; B=2, I=9, G=7 → 297। F=6, E=5, E=5, D=4 → 6554।"]),

  // ───────── Section 3: Numerical Ability ─────────
  q(3, "quant", "mensuration", "E", 1,
    ["In a rhombus, if its diagonals are 19 cm and 13 cm, its area will be:", ["½(19+13) cm²", "½(19×13) cm²", "½(19−13) cm²", "244.5 cm²"], "Area of a rhombus = ½ × d₁ × d₂ = ½ × 19 × 13 = 123.5 cm²."],
    ["एक समचतुर्भुज में अगर इसके विकर्ण 19 cm तथा 13 cm है तो इसका क्षेत्रफल कितना होगा?", ["½(19+13) cm²", "½(19×13) cm²", "½(19−13) cm²", "244.5 cm²"], "समचतुर्भुज का क्षेत्रफल = ½ × d₁ × d₂ = ½ × 19 × 13 = 123.5 cm²।"]),
  q(3, "quant", "mensuration", "M", 0,
    ["If the area of a circular garden is 15400 m², then its perimeter is:", ["440 m", "220 m", "110 m", "550 m"], "πr² = 15400 gives r² = 4900, so r = 70 m. Perimeter = 2πr = 2 × 22/7 × 70 = 440 m."],
    ["अगर एक गोलाकार (वृत्त) बग़ीचे का क्षेत्रफल 15400 m² है तो उसका परिमाप कितना होगा।", ["440 m", "220 m", "110 m", "550 m"], "πr² = 15400 से r² = 4900, अतः r = 70 m। परिमाप = 2πr = 2 × 22/7 × 70 = 440 m।"]),
  q(3, "quant", "percentage", "E", 1,
    ["30% of the 450 apples are rotten. How many apples are in good condition?", ["125", "315", "240", "180"], "Rotten = 30% of 450 = 135. Good = 450 − 135 = 315."],
    ["450 सेबों में से 30% सड़े हुए हैं। कितने सेब अच्छी स्तिथि में हैं?", ["125", "315", "240", "180"], "सड़े सेब = 450 का 30% = 135। अच्छे सेब = 450 − 135 = 315।"]),
  q(3, "quant", "interest", "M", 2,
    ["Veena obtained ₹8376 as simple interest on a certain amount at 8% p.a. in 6 years. What is the amount invested by Veena?", ["₹16660", "₹17180", "₹17450", "₹18110"], "SI = P × R × T / 100, so P = 8376 × 100 / (8 × 6) = ₹17,450."],
    ["वीणा एक निश्चित राशि को 8% वार्षिक दर पर रखती है। तो उसे 6 वर्ष बाद साधारण ब्याज के 8376 रु मिलते हैं। वीणा द्वारा कितनी राशि निवेश की गई?", ["₹16660", "₹17180", "₹17450", "₹18110"], "साधारण ब्याज = P × R × T / 100, अतः P = 8376 × 100 / (8 × 6) = ₹17,450।"]),
  q(3, "quant", "speed-distance", "M", 0,
    ["A student goes to school at 2½ km/hr and reaches 6 minutes late. If he travels at 3 km/hr, he is 10 minutes early. What is the distance to the school?", ["4 km", "5 km", "3.5 km", "4.5 km"], "The time difference is 16 min = 4/15 h. d/2.5 − d/3 = 4/15 gives d/15 = 4/15, so d = 4 km."],
    ["एक विद्यार्थी 2½ km/hr की गति से स्कूल जाता है तो वो 6 मिनट देरी से पहुँचता है। अगर वो 3 km/hr से यात्रा करता है तो वह 10 मिनट जल्दी पहुंच जाता है। स्कूल तक दूरी कितनी है?", ["4 कि.मी.", "5 कि.मी.", "3.5 कि.मी.", "4.5 कि.मी."], "समय का अंतर 16 मिनट = 4/15 घंटा। d/2.5 − d/3 = 4/15 से d/15 = 4/15, अतः d = 4 कि.मी.।"]),
  q(3, "quant", "simplification", "M", 3,
    ["Find the value of x: 28.5 × 34 + 2320 ÷ 8 = (36)² − x", ["51", "47", "43", "37"], "28.5 × 34 = 969 and 2320 ÷ 8 = 290, so the left side is 1259. 36² = 1296, so x = 1296 − 1259 = 37."],
    ["x का मूल्य निकालें: 28.5 × 34 + 2320 ÷ 8 = (36)² − x", ["51", "47", "43", "37"], "28.5 × 34 = 969 और 2320 ÷ 8 = 290, बायाँ पक्ष 1259। 36² = 1296, अतः x = 1296 − 1259 = 37।"]),
  q(3, "quant", "hcf-lcm", "M", 3,
    ["If HCF(a, b) = 15 and a × b = 1800, then LCM(a, b) is:", ["3600", "900", "90", "120"], "HCF × LCM = a × b, so LCM = 1800 / 15 = 120."],
    ["अगर (a, b) का उच्चतम आम कारक 15 है तथा a × b = 1800 है तो (a, b) का न्यूनतम सामान्य कारक बताएं।", ["3600", "900", "90", "120"], "HCF × LCM = a × b, अतः LCM = 1800 / 15 = 120।"]),
  q(3, "quant", "percentage", "E", 2,
    ["75% of 2 is equal to:", ["37.5", "15", "1.5", "0.15"], "75% of 2 = 0.75 × 2 = 1.5."],
    ["2 का 75% किसके बराबर है?", ["37.5", "15", "1.5", "0.15"], "2 का 75% = 0.75 × 2 = 1.5।"]),

  // ───────── Section 4: Hindi & English ─────────
  q(4, "english", "voice-speech", "M", 3,
    ["Select the option which best expresses the sentence in Active/Passive voice: Somebody told me that there had been an explosion in the Mall.", ["I was told by somebody about the explosion in the Mall.", "I was told about the explosion in the Mall.", "I was informed that there was an explosion in the Mall.", "I was told by somebody that there had been an explosion in the Mall."], "The passive keeps the whole meaning, including the past-perfect clause: 'I was told by somebody that there had been an explosion in the Mall.'"],
    ["Active/Passive voice में वाक्य को सर्वोत्तम ढंग से व्यक्त करने वाला विकल्प चुनिए: Somebody told me that there had been an explosion in the Mall.", ["I was told by somebody about the explosion in the Mall.", "I was told about the explosion in the Mall.", "I was informed that there was an explosion in the Mall.", "I was told by somebody that there had been an explosion in the Mall."], "सही वाक्य मूल अर्थ और past-perfect उपवाक्य को बनाए रखता है: 'I was told by somebody that there had been an explosion in the Mall.'"]),
  q(4, "english", "idioms", "M", 1,
    ["Choose the correct option for sentence improvement, if any: He has fallen out with the girl he wanted to marry.", ["fallen off", "fallen in love", "fallen for", "no improvement"], "The sentence needs 'fallen in love with the girl he wanted to marry'; 'fallen out with' means quarrelled, which does not fit the sense."],
    ["वाक्य सुधार के लिए सही विकल्प चुनिए (यदि आवश्यक हो): He has fallen out with the girl he wanted to marry.", ["fallen off", "fallen in love", "fallen for", "no improvement"], "सही वाक्य 'fallen in love with the girl he wanted to marry' है; 'fallen out with' का अर्थ झगड़ना है, जो यहाँ उपयुक्त नहीं।"]),
  q(4, "english", "spelling", "E", 2,
    ["Choose the correctly spelt word (the word means troubling someone repeatedly).", ["Harasment", "Harrasmant", "Harassment", "Harresment"], "The correct spelling is 'harassment' (one r, double s)."],
    ["सही वर्तनी वाला शब्द चुनिए (शब्द का अर्थ किसी को बार-बार परेशान करना है)।", ["Harasment", "Harrasmant", "Harassment", "Harresment"], "सही वर्तनी 'harassment' है (एक r, दो s)।"]),
  q(4, "english", "spelling", "E", 2,
    ["Choose the correctly spelt word (the word means general agreement).", ["Consensus", "Concensus", "Consencus", "Consansus"], "The correct spelling is 'consensus' (from 'consent')."],
    ["सही वर्तनी वाला शब्द चुनिए (शब्द का अर्थ सामान्य सहमति है)।", ["Consensus", "Concensus", "Consencus", "Consansus"], "सही वर्तनी 'consensus' है ('consent' से बना)।"]),
  q(4, "english", "synonyms-antonyms", "E", 0,
    ["Choose the option having similar meaning to the capital word: PIOUS", ["Religious", "Sympathetic", "Afraid", "Faithful"], "Pious means devoutly religious."],
    ["बड़े अक्षरों वाले शब्द के समान अर्थ वाला विकल्प चुनिए: PIOUS", ["Religious", "Sympathetic", "Afraid", "Faithful"], "Pious का अर्थ धर्मनिष्ठ, अत्यंत धार्मिक है।"]),
  q(4, "english", "one-word", "M", 3,
    ["Choose the option correct for the sentence: A hater of knowledge and learning", ["Bibliophile", "Philologist", "Misogynist", "Misologist"], "A misologist hates reason, argument and learning. A bibliophile loves books, a philologist loves words and a misogynist hates women."],
    ["वाक्य के लिए सही विकल्प चुनिए: A hater of knowledge and learning", ["Bibliophile", "Philologist", "Misogynist", "Misologist"], "Misologist वह है जो तर्क, ज्ञान और सीखने से घृणा करे। Bibliophile पुस्तक-प्रेमी, Philologist भाषा-प्रेमी और Misogynist स्त्रियों से घृणा करने वाला होता है।"]),
  q(4, "english", "grammar", "M", 1,
    ["Choose the correct option for filling up the blank: In ______ to picking up milk from the grocery store we also need to get some bread because my cousin ate all of it in the past week.", ["further", "addition", "aftermath", "besides"], "'In addition to' is the fixed phrase meaning 'as well as'."],
    ["रिक्त स्थान भरने के लिए सही विकल्प चुनिए: In ______ to picking up milk from the grocery store we also need to get some bread because my cousin ate all of it in the past week.", ["further", "addition", "aftermath", "besides"], "'In addition to' निश्चित वाक्यांश है, जिसका अर्थ 'के अतिरिक्त' है।"]),
  q(4, "english", "voice-speech", "M", 1,
    ["Select the most appropriate option to change the sentence from Direct to Reported speech: \"I am going out tonight,\" Luxmi said.", ["Luxmi said that she was going out tonight.", "Luxmi said that she was going out that night.", "Luxmi said she was going out that night.", "Luxmi said that she will be going out that night."], "In reported speech the present continuous becomes past continuous (am going → was going) and 'tonight' becomes 'that night'. Option C also omits 'that', so B is the best choice."],
    ["Direct Speech को Reported Speech में बदलने के लिए सबसे उपयुक्त विकल्प चुनिए: \"I am going out tonight,\" Luxmi said.", ["Luxmi said that she was going out tonight.", "Luxmi said that she was going out that night.", "Luxmi said she was going out that night.", "Luxmi said that she will be going out that night."], "Reported speech में present continuous, past continuous बन जाता है (am going → was going) और 'tonight' 'that night' हो जाता है। विकल्प C में 'that' भी नहीं है, इसलिए B सर्वश्रेष्ठ है।"]),
  q(4, "english", "grammar", "M", 3,
    ["The given phrase in bold may or may not contain an error. Choose the correct replacement: Everything is funny as long as it IS HAPPENING TOO somebody else.", ["has been happening for", "could have happened to", "was happening to", "is happening to"], "The preposition should be 'to' (not 'too'): 'as long as it is happening to somebody else'."],
    ["बोल्ड में दिए गए phrase में त्रुटि हो भी सकती है और नहीं भी। सही विकल्प चुनिए: Everything is funny as long as it IS HAPPENING TOO somebody else.", ["has been happening for", "could have happened to", "was happening to", "is happening to"], "यहाँ 'too' नहीं बल्कि preposition 'to' होना चाहिए: 'as long as it is happening to somebody else'।"]),
  q(4, "english", "idioms", "M", 1,
    ["Choose the correct meaning of the underlined idiom: Everyone likes her since she always remains in high spirits.", ["talkative", "cheerful", "well dressed", "courteous"], "'In high spirits' means cheerful and lively."],
    ["रेखांकित मुहावरे का सही अर्थ चुनिए: Everyone likes her since she always remains in high spirits.", ["talkative", "cheerful", "well dressed", "courteous"], "'In high spirits' का अर्थ प्रसन्नचित्त और उत्साहित होना है।"]),
  q(4, "english", "idioms", "M", 0,
    ["Choose the correct meaning of the underlined idiom: He was a King who ruled his subjects with a high hand.", ["oppressively", "kindly", "conveniently", "sympathetically"], "'With a high hand' means in an arrogant, domineering and oppressive way."],
    ["रेखांकित मुहावरे का सही अर्थ चुनिए: He was a King who ruled his subjects with a high hand.", ["oppressively", "kindly", "conveniently", "sympathetically"], "'With a high hand' का अर्थ अहंकारपूर्ण, दमनकारी ढंग से है।"]),
  q(4, "hindi", "sandhi-samas", "M", 3,
    ["Split the sandhi of 'व्याख्या':", ["व्या + अख्या", "वे + आख्या", "व्य + अख्या", "वि + आख्या"], "वि + आख्या → व्याख्या (यण संधि: इ + आ = या)."],
    ["'व्याख्या' का संधि-विच्छेद है:-", ["व्या + अख्या", "वे + आख्या", "व्य + अख्या", "वि + आख्या"], "वि + आख्या → व्याख्या (यण संधि: इ + आ = या)।"]),
  q(4, "hindi", "paryay-vilom", "M", 1,
    ["Which is the antonym of 'अवकाश' (leisure/vacancy)?", ["अपकर्ष", "अनवकाश", "अनुपस्थित", "छुट्टी"], "The antonym of 'अवकाश' is 'अनवकाश' (no leisure, busy)."],
    ["'अवकाश' का विलोम है:", ["अपकर्ष", "अनवकाश", "अनुपस्थित", "छुट्टी"], "'अवकाश' का विलोम 'अनवकाश' है।"]),
  q(4, "hindi", "vyakaran", "M", 3,
    ["Which of these words is a noun (संज्ञा)?", ["प्राथमिक", "प्रथम", "सुशोभित", "None of these"], "प्राथमिक, प्रथम and सुशोभित are all adjectives (विशेषण), so none is a noun."],
    ["इनमे से कौन सा शब्द संज्ञा है?", ["प्राथमिक", "प्रथम", "सुशोभित", "इनमे से कोई नहीं"], "प्राथमिक, प्रथम और सुशोभित तीनों विशेषण हैं, इसलिए कोई भी संज्ञा नहीं है।"]),
  q(4, "hindi", "sandhi-samas", "M", 1,
    ["Choose the correct sandhi split: परीक्षक", ["पर + यिक्षक", "परि + इक्षक", "परि + अक्षक", "परी + इक्षक"], "परि + ईक्षक → परीक्षक (दीर्घ संधि); among the options, परि + इक्षक is the intended split."],
    ["शुद्ध सन्धि चयन करें: परीक्षक-", ["पर + यिक्षक", "परि + इक्षक", "परि + अक्षक", "परी + इक्षक"], "परि + ईक्षक → परीक्षक (दीर्घ संधि); अपेक्षित उत्तर 'परि + इक्षक' रूप है।"]),
  q(4, "hindi", "vyakaran", "M", 0,
    ["Which of these is an abstract noun (भाववाचक संज्ञा)?", ["मिठास", "मीठा", "मिठाई", "मिष्ठान"], "'मिठास' (sweetness) names a quality or state, so it is an abstract noun. मीठा is an adjective; मिठाई and मिष्ठान are sweets (common nouns)."],
    ["निम्न में से भाववाचक संज्ञा कौन सी है?", ["मिठास", "मीठा", "मिठाई", "मिष्ठान"], "'मिठास' गुण या भाव का नाम है, इसलिए भाववाचक संज्ञा है। मीठा विशेषण है; मिठाई और मिष्ठान मिठाई की वस्तुएँ (जातिवाचक संज्ञा) हैं।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["What is the meaning of the proverb 'अधजल गगरी छलकत जाय'?", ["Display by a great man", "A pot half full of water", "Greater show by a small (shallow) person", "Spilling of the pot"], "A half-filled pot makes the most splash — a person with little knowledge or worth makes the most display."],
    ["\"अधजल गगरी छलकत जाये\" मुहावरे / लोकोक्ति का क्या अर्थ है?", ["बड़े आदमी का दिखावा", "आधी पानी से भरी गागर", "छोटे आदमी का अधिक दिखावा", "गगरी का छलकना"], "आधी भरी गगरी ज्यादा छलकती है — कम ज्ञान या योग्यता वाला व्यक्ति अधिक दिखावा करता है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Which of these is NOT a synonym of 'बिजली' (lightning/electricity)?", ["चपला", "चंचला", "तड़ित", "ज्योत्सना"], "चपला, चंचला and तड़ित are synonyms of बिजली; ज्योत्सना means moonlight."],
    ["निम्नलिखित में से कौन सा शब्द बिजली का पर्यायवाची नहीं है?", ["चपला", "चंचला", "तड़ित", "ज्योत्सना"], "चपला, चंचला और तड़ित बिजली के पर्यायवाची हैं; ज्योत्सना का अर्थ चाँदनी है।"]),
  q(4, "hindi", "vyakaran", "M", 3,
    ["Which of these is feminine (स्त्रीलिंग)?", ["माली", "खत्री", "चौधरी", "धनवती"], "'धनवती' is the feminine of 'धनवान'. माली, खत्री and चौधरी are masculine."],
    ["निम्नलिखित में से स्त्रीलिंग है?", ["माली", "खत्री", "चौधरी", "धनवती"], "'धनवती', 'धनवान' का स्त्रीलिंग है। माली, खत्री और चौधरी पुल्लिंग हैं।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["What is the antonym of 'उत्थान' (rise)?", ["पतन", "उपकर्ष", "ह्रास", "अपकर्ष"], "The standard antonym of 'उत्थान' is 'पतन' (fall)."],
    ["उत्थान का विपरीतार्थक शब्द क्या है?", ["पतन", "उपकर्ष", "ह्रास", "अपकर्ष"], "'उत्थान' का प्रचलित विलोम 'पतन' है।"]),
  q(4, "hindi", "vyakaran", "E", 2,
    ["What is the plural of 'वह' (he/that)?", ["वो", "वह सब", "वे", "उन"], "The plural of 'वह' is 'वे'."],
    ["'वह' का बहुवचन क्या है?", ["वो", "वह सब", "वे", "उन"], "'वह' का बहुवचन 'वे' है।"]),
  q(4, "hindi", "ek-shabd", "M", 1,
    ["The one word for 'a thing that is wished for' is:", ["अलौकिक", "अभीष्ट", "अनायास", "अनोखा"], "'अभीष्ट' means desired or wished for. अलौकिक = supernatural, अनायास = effortlessly, अनोखा = unique."],
    ["'जिस वस्तु को पाने की इच्छा की जाए' के लिए एक शब्द है:", ["अलौकिक", "अभीष्ट", "अनायास", "अनोखा"], "'अभीष्ट' का अर्थ वांछित (जिसकी इच्छा की जाए) है। अलौकिक = दिव्य, अनायास = बिना प्रयास, अनोखा = अनूठा।"]),
];
