// HP Police Constable written exam held on 15 June 2025 (Series B) — transcribed from the photographed paper. No official
// key was available: answers were solved independently (pencil marks on the scan were only a cross-check).
// Left out because unreadable, figure-based or ambiguous: original numbers 5, 6, 13, 22, 42, 43, 47, 59, 67, 69, 72.
// Option order is kept as printed. Sections: 0 Himachal GK, 1 General Knowledge, 2 Reasoning, 3 Numerical Ability, 4 Hindi & English.

import { q, type PoliceQuestion } from "../police/types";

export const y2025: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK ─────────
  q(0, "hp-gk", "personalities", "M", 0,
    ["Identify the author of the book 'Kulut Desh ki Kahani' from the following:", ["Lal Chand Prarthi", "Vidya Stokes", "Sunil Dutt Gautam", "Shanta Kumar"], "'Kulut Desh ki Kahani' was written by the Kullu poet and writer Lal Chand Prarthi."],
    ["'कुलूत देश की कहानी' नामक पुस्तक के लेखक की पहचान निम्नलिखित से कीजिए:", ["लाल चन्द प्रार्थी", "विद्या स्टोक्स", "सुनील दत्त गौतम", "शान्ता कुमार"], "'कुलूत देश की कहानी' के लेखक कुल्लू के कवि और साहित्यकार लाल चन्द प्रार्थी हैं।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["In which district of Himachal Pradesh is the Kumarwah lake located?", ["Mandi", "Chamba", "Kullu", "Kangra"], "Kumarwah lake lies in Mandi district."],
    ["हिमाचल प्रदेश के किस जिले में कुमारवाह झील स्थित है?", ["मंडी", "चम्बा", "कुल्लू", "कांगड़ा"], "कुमारवाह झील मंडी जिले में स्थित है।"]),
  q(0, "hp-gk", "geography", "H", 3,
    ["Which of the following passes of Himachal Pradesh is located at the highest altitude?", ["Talang", "Singoor", "Waru", "Kugti"], "Kugti Pass (about 5,040 m) on the Chamba–Lahaul border is the highest of the passes listed."],
    ["हिमाचल प्रदेश का कौनसा निम्नलिखित दर्रा सबसे अधिक ऊँचाई पर है?", ["तलांग", "सिंगूर", "वारू", "कुगती"], "चंबा–लाहौल सीमा पर स्थित कुगती दर्रा (लगभग 5,040 मी.) दिए गए दर्रों में सबसे ऊँचा है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 1,
    ["Which of the following is the largest river of Himachal Pradesh in terms of water volume?", ["Beas", "Chenab", "Sutlej", "Ravi"], "The Chenab (formed by the Chandra and Bhaga at Tandi) carries the largest volume of water among Himachal's rivers; the Sutlej is the longest within the state."],
    ["हिमाचल प्रदेश में निम्नलिखित में से कौनसी नदी जल की मात्रा के संदर्भ में सबसे बड़ी नदी है?", ["ब्यास", "चिनाब", "सतलुज", "रावी"], "चिनाब (तांदी में चंद्रा और भागा के मिलन से बनी) हिमाचल की नदियों में जल की मात्रा में सबसे बड़ी है; राज्य के भीतर सबसे लंबी नदी सतलुज है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 3,
    ["Which of the following is the largest monastery in Spiti?", ["Tabo", "Lha Kun", "Gemur", "Kee"], "Kee (Ki) Monastery is the largest monastery in Spiti valley. Tabo is the oldest."],
    ["निम्न में से कौनसा मठ स्पिति का सबसे बड़ा मठ है?", ["ताबो", "ल्हा कुन", "गेमूर", "की"], "की (कीह) मठ स्पिति घाटी का सबसे बड़ा मठ है। ताबो सबसे प्राचीन मठ है।"]),

  // ───────── Section 1: General Knowledge ─────────
  q(1, "general-studies", "general-science", "M", 0,
    ["Who invented the mercury thermometer?", ["Daniel Gabriel Fahrenheit", "Marie Curie", "Sir Isaac Newton", "Pierre Curie"], "Daniel Gabriel Fahrenheit invented the mercury thermometer in 1714."],
    ["Mercury Thermometer का आविष्कार किसने किया है?", ["डैनियल गैब्रियल फाहरेनहाइट", "मैरी क्यूरी", "सर इसाक न्यूटन", "पियरे क्यूरी"], "डैनियल गैब्रियल फाहरेनहाइट ने 1714 में पारा थर्मामीटर का आविष्कार किया।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["In which of the following cities was the first National Institute of Design established in India?", ["Mumbai", "Ahmedabad", "Bengaluru", "Kolkata"], "The National Institute of Design was founded in 1961 at Ahmedabad."],
    ["जिस भारत के नगर में प्रथम राष्ट्रीय डिजाइन संस्थान स्थापित किया गया, उसकी पहचान निम्नलिखित से कीजिए:", ["मुंबई", "अहमदाबाद", "बंगलुरू", "कोलकाता"], "राष्ट्रीय डिजाइन संस्थान की स्थापना 1961 में अहमदाबाद में हुई।"]),
  q(1, "general-studies", "indian-polity", "E", 3,
    ["The headquarters of NATO is in:", ["Berlin", "Paris", "Athens", "Brussels"], "NATO's headquarters is in Brussels, Belgium."],
    ["नाटो (NATO) का मुख्यालय कहाँ है?", ["बर्लिन", "पेरिस", "एथेन्स", "ब्रूसेल्स"], "नाटो का मुख्यालय ब्रसेल्स (बेल्जियम) में है।"]),
  q(1, "general-studies", "general-science", "E", 1,
    ["Identify the date of International Yoga Day:", ["July 10", "June 21", "July 25", "June 15"], "International Yoga Day is observed every year on 21 June."],
    ["अन्तर्राष्ट्रीय योग दिवस की तिथि की पहचान कीजिए:", ["10 जुलाई", "21 जून", "25 जुलाई", "15 जून"], "अंतर्राष्ट्रीय योग दिवस प्रतिवर्ष 21 जून को मनाया जाता है।"]),
  q(1, "general-studies", "indian-economy", "E", 3,
    ["What does the abbreviation IMF stand for?", ["International Money Fund", "Indian Monetary Fund", "Irani Military Force", "International Monetary Fund"], "IMF stands for International Monetary Fund."],
    ["IMF का पूर्ण रूप है?", ["International Money Fund", "Indian Monetary Fund", "Irani Military Force", "International Monetary Fund"], "IMF का पूर्ण रूप इंटरनेशनल मॉनेटरी फंड है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["Which of the following has been introduced to replace the IPC (Indian Penal Code)?", ["BNS (Bhartiya Nyaya Sanhita)", "BNSS (Bhartiya Nagarik Suraksha Sanhita)", "BSA (Bhartiya Sakshya Adhiniyam)", "BSN (Bhartiya Suraksha Niyam)"], "The Bharatiya Nyaya Sanhita (BNS), in force since 1 July 2024, replaced the IPC. BNSS replaced the CrPC and BSA replaced the Evidence Act."],
    ["निम्न में से किस नियम ने 'इंडियन पेनल कोड (आई.पी.सी.)' को प्रतिस्थापित किया है?", ["बी.एन.एस. (भारतीय न्याय संहिता)", "बी.एन.एस.एस. (भारतीय नागरिक सुरक्षा संहिता)", "बी.एस.ए. (भारतीय साक्ष्य अधिनियम)", "बी.एस.एन. (भारतीय सुरक्षा नियम)"], "1 जुलाई 2024 से लागू भारतीय न्याय संहिता (बीएनएस) ने आईपीसी का स्थान लिया। बीएनएसएस ने सीआरपीसी और बीएसए ने साक्ष्य अधिनियम का स्थान लिया।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Which of the following countries emerged as the winner of the Men's Hockey Asian Champions Trophy 2024?", ["China", "India", "Japan", "South Korea"], "India beat China 1–0 in the final at Hulunbuir (China) in September 2024 to win the trophy for a record fifth time."],
    ["निम्न में से कौनसा देश 'एशियन पुरुष हॉकी चैम्पियनशिप-2024' का विजेता रहा है?", ["चीन", "भारत", "जापान", "दक्षिण कोरिया"], "भारत ने सितंबर 2024 में हुलुनबुइर (चीन) में फाइनल में चीन को 1–0 से हराकर रिकॉर्ड पाँचवीं बार खिताब जीता।"]),
  q(1, "general-studies", "indian-polity", "E", 2,
    ["Where is the headquarters of UNESCO situated?", ["Geneva", "New Delhi", "Paris", "Berlin"], "UNESCO is headquartered in Paris, France."],
    ["'यूनेस्को' का मुख्यालय कहाँ पर स्थित है?", ["जेनेवा", "नई दिल्ली", "पेरिस", "बर्लिन"], "यूनेस्को का मुख्यालय पेरिस (फ्रांस) में है।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["'Vande Mataram' is part of which of the following books?", ["Geetanjali", "Anandmath", "Bhagwat Geeta", "Bharat Bharti"], "Bankim Chandra Chatterjee's 'Vande Mataram' appears in his novel Anandmath (1882)."],
    ["'वंदे मातरम्' निम्न में से किस पुस्तक का हिस्सा है?", ["गीतांजलि", "आनन्दमठ", "भगवत गीता", "भारत भारती"], "बंकिम चंद्र चट्टोपाध्याय का 'वंदे मातरम्' उनके उपन्यास आनंदमठ (1882) का हिस्सा है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["Who amongst the following has been awarded the Jnanpith Award 2023?", ["Rambhadracharya", "Gaurav Pandey", "Devender Kumar", "Nandini Sen Gupta"], "Jagadguru Rambhadracharya (Hindi/Sanskrit) and Urdu poet Gulzar were announced as the 58th Jnanpith Award winners (for 2023)."],
    ["निम्नलिखित में से किसे ज्ञानपीठ पुरस्कार-2023 से सम्मानित किया गया?", ["रामभद्राचार्य", "गौरव पांडे", "देवेन्द्र कुमार", "नंदिनी सेन गुप्ता"], "जगद्गुरु रामभद्राचार्य (हिंदी/संस्कृत) और उर्दू कवि गुलज़ार को 58वें ज्ञानपीठ पुरस्कार (2023) के लिए चुना गया।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["The capital of the United Arab Emirates is:", ["Al Ain", "Abu Dhabi", "Dubai", "Sharjah"], "Abu Dhabi is the capital of the UAE; Dubai is the largest and best-known city for luxury shopping."],
    ["संयुक्त अरब अमीरात की राजधानी कौनसी है?", ["अल ऐन", "आबू धाबी", "दुबई", "शारजाह"], "आबू धाबी संयुक्त अरब अमीरात की राजधानी है; दुबई सबसे बड़ा और भव्य खरीदारी के लिए प्रसिद्ध शहर है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Netaji Subhash Chandra National Institute of Sports is located in which of the following places?", ["Kolkata", "Patiala", "Bengaluru", "Ahmedabad"], "NSNIS, the main campus of the Sports Authority of India, is at Patiala, Punjab."],
    ["नेताजी सुभाष चंद्र राष्ट्रीय खेल संस्थान निम्न में से किस स्थान पर स्थित है?", ["कोलकाता", "पटियाला", "बंगलुरू", "अहमदाबाद"], "भारतीय खेल प्राधिकरण का मुख्य परिसर एनएसएनआईएस पटियाला (पंजाब) में है।"]),

  // ───────── Section 2: Reasoning ─────────
  q(2, "reasoning", "series", "M", 2,
    ["Find the wrong number in the series: 3, 8, 15, 24, 34, 48, 63", ["8", "24", "34", "63"], "The terms are n² − 1: 3, 8, 15, 24, 35, 48, 63. So 34 should be 35."],
    ["श्रृंखला में गलत संख्या ज्ञात कीजिये: 3, 8, 15, 24, 34, 48, 63", ["8", "24", "34", "63"], "पद n² − 1 हैं: 3, 8, 15, 24, 35, 48, 63। अतः 34 के स्थान पर 35 होना चाहिए।"]),
  q(2, "reasoning", "puzzles", "E", 1,
    ["An aquarium contains 17 goldfish. All but eight died. How many goldfish is the aquarium left with?", ["0", "8", "9", "17"], "'All but eight died' means eight survived."],
    ["एक मछलीघर में 17 सुनहरी मछलियाँ हैं। आठ को छोड़कर बाकी सभी मर गईं। मछलीघर में अब कितनी सुनहरी मछलियाँ बची हैं?", ["0", "8", "9", "17"], "'आठ को छोड़कर सभी मर गईं' का अर्थ है आठ जीवित बचीं।"]),
  q(2, "reasoning", "blood-relations", "M", 1,
    ["Pointing towards a boy, Mina said, \"He is the son of only son of my grandfather.\" How is the boy related to Mina?", ["Uncle", "Brother", "Cousin", "None of these"], "The only son of Mina's grandfather is her father, and the boy is his son — Mina's brother."],
    ["एक लड़के की ओर इशारा करते हुए मीना ने कहा, \"वह मेरे दादा के इकलौते बेटे का बेटा है\"। लड़का मीना से किस प्रकार संबंधित है?", ["चाचा", "भाई", "चचेरा भाई", "इनमें से कोई नहीं"], "मीना के दादा का इकलौता बेटा उसका पिता है और लड़का उसका बेटा है — यानी मीना का भाई।"]),
  q(2, "reasoning", "clock-calendar", "E", 0,
    ["If today is Wednesday, then what will be the day after 56 days?", ["Wednesday", "Thursday", "Friday", "Saturday"], "56 = 8 × 7, an exact number of weeks, so the day is the same: Wednesday."],
    ["यदि आज बुधवार है, तो 56 दिन बाद कौनसा दिन होगा?", ["बुधवार", "गुरुवार", "शुक्रवार", "शनिवार"], "56 = 8 × 7, यानी पूरे सप्ताह, इसलिए दिन वही रहेगा: बुधवार।"]),
  q(2, "reasoning", "blood-relations", "H", 0,
    ["A introduced B as the son of the only brother of his father's wife. How is A related to B?", ["Cousin", "Son", "Brother", "Uncle"], "A's father's wife is A's mother. Her only brother is A's maternal uncle, whose son B is A's cousin."],
    ["A ने B का परिचय अपने पिता की पत्नी के इकलौते भाई के पुत्र के रूप में कराया। A का B से क्या रिश्ता है?", ["चचेरा भाई", "पुत्र", "भाई", "चाचा"], "A के पिता की पत्नी A की माँ है। उसका इकलौता भाई A का मामा है, जिसका पुत्र B, A का ममेरा/चचेरा भाई है।"]),
  q(2, "reasoning", "analogy", "E", 2,
    ["Select the related word from the given alternatives. Medicine : Patient :: Education : ?", ["Teacher", "School", "Student", "Tuition"], "Medicine is meant for a patient; education is meant for a student."],
    ["दिये गये विकल्पों में से संबंधित शब्द छाँटिये: मेडिसिन : रोगी :: शिक्षा : ?", ["अध्यापक", "स्कूल", "विद्यार्थी", "ट्यूशन"], "दवा रोगी के लिए होती है; शिक्षा विद्यार्थी के लिए होती है।"]),
  q(2, "reasoning", "coding-decoding", "M", 3,
    ["In a certain code language, \"TIRED\" is written as \"56\" and \"BRAIN\" is written as \"44\". How is \"LAZY\" written in that code language?", ["43", "58", "61", "64"], "Each word is the sum of its letters' alphabet positions: TIRED = 20+9+18+5+4 = 56; BRAIN = 2+18+1+9+14 = 44. LAZY = 12+1+26+25 = 64."],
    ["किसी निश्चित कोड भाषा में \"TIRED\" को \"56\" लिखा जाता है और \"BRAIN\" को \"44\" लिखा जाता है। उसी कोड भाषा में \"LAZY\" को कैसे लिखा जायेगा?", ["43", "58", "61", "64"], "शब्द के अक्षरों के वर्णमाला-क्रमांकों का योग: TIRED = 20+9+18+5+4 = 56; BRAIN = 2+18+1+9+14 = 44। LAZY = 12+1+26+25 = 64।"]),

  // ───────── Section 3: Numerical Ability ─────────
  q(3, "quant", "mensuration", "M", 1,
    ["The area of a trapezium is 105 cm² and its height is 7 cm. If one of the parallel sides is longer than the other by 6 cm, then the sum of the parallel sides is:", ["25", "30", "35", "40"], "Area = ½ × (sum of parallel sides) × height, so the sum = 2 × 105 / 7 = 30 cm."],
    ["समलम्ब चतुर्भुज का क्षेत्रफल 105 cm² है तथा इसकी ऊँचाई 7 cm है। यदि समांतर भुजाओं में से एक भुजा दूसरी भुजा से 6 cm लंबी है, तो समांतर भुजाओं का योग क्या होगा?", ["25", "30", "35", "40"], "क्षेत्रफल = ½ × (समांतर भुजाओं का योग) × ऊँचाई, अतः योग = 2 × 105 / 7 = 30 cm।"]),
  q(3, "quant", "profit-loss", "M", 2,
    ["A shopkeeper allows a discount of 10% to his customers and still gains 20% on a product. If the cost price of the product is ₹450, then the marked price is:", ["500", "540", "600", "640"], "Selling price = 450 × 1.20 = ₹540. This is 90% of the marked price, so MP = 540 / 0.9 = ₹600."],
    ["एक दुकानदार अपने ग्राहकों को 10% की छूट देता है और फिर भी एक उत्पाद पर 20% का लाभ कमाता है। यदि उत्पाद का क्रय मूल्य 450 रु. है, तो अंकित मूल्य है:", ["500", "540", "600", "640"], "विक्रय मूल्य = 450 × 1.20 = ₹540। यह अंकित मूल्य का 90% है, अतः अंकित मूल्य = 540 / 0.9 = ₹600।"]),
  q(3, "quant", "average", "M", 3,
    ["The mean of a, b, c, d and e is 28. If the mean of a, c and e is 24, then the mean of b and d is:", ["31", "32", "33", "34"], "Total of five = 140. a + c + e = 72, so b + d = 68 and their mean = 34."],
    ["a, b, c, d और e का माध्य 28 है। यदि a, c और e का माध्य 24 है, तो b और d का माध्य क्या है?", ["31", "32", "33", "34"], "पाँचों का योग = 140। a + c + e = 72, अतः b + d = 68 और उनका माध्य = 34।"]),
  q(3, "quant", "number-system", "M", 3,
    ["In a cricket match, a batsman hits a boundary 8 times out of the 42 balls he played. The probability that he did not hit a boundary is:", ["4/21", "7/21", "12/21", "17/21"], "Balls without a boundary = 42 − 8 = 34, so the probability = 34/42 = 17/21."],
    ["एक क्रिकेट मैच में, एक बल्लेबाज ने 42 गेंदों में से 8 बार चौका मारा। इस बात की संभावना है कि उसने चौका नहीं मारा, है:", ["4/21", "7/21", "12/21", "17/21"], "बिना चौके वाली गेंदें = 42 − 8 = 34, अतः संभावना = 34/42 = 17/21।"]),
  q(3, "quant", "average", "H", 1,
    ["The arithmetic mean and mode of a data are 24 and 12 respectively, then its median is:", ["18", "20", "22", "25"], "Mode = 3 × Median − 2 × Mean, so 12 = 3M − 48 and the median M = 20."],
    ["किसी डेटा का arithmetic mean और mode 24 और 12 हैं, तो इसका median क्या है?", ["18", "20", "22", "25"], "बहुलक = 3 × माध्यिका − 2 × माध्य, अतः 12 = 3M − 48 और माध्यिका M = 20।"]),
  q(3, "quant", "number-system", "M", 3,
    ["Mina buys a fish from a shop for her aquarium. The shopkeeper takes out one fish at random from a tank containing 5 male fish and 7 female fish. The probability that the fish taken out is a female fish is:", ["2/12", "5/12", "6/12", "7/12"], "There are 12 fish in all and 7 are female, so the probability is 7/12."],
    ["मीना अपने एक्वेरियम के लिए एक दुकान से एक मछली खरीदती है। दुकानदार 5 नर मछलियों और 7 मादा मछलियों वाले एक टैंक से यादृच्छिक रूप से एक मछली निकालता है। निकाली गई मछली के मादा मछली होने की संभावना है:", ["2/12", "5/12", "6/12", "7/12"], "कुल 12 मछलियाँ हैं जिनमें 7 मादा हैं, अतः संभावना 7/12 है।"]),
  q(3, "quant", "geometry", "E", 1,
    ["If two acute angles of a right-angled triangle are equal, then each acute angle is:", ["30°", "45°", "60°", "90°"], "The acute angles add up to 90°, so equal angles are 45° each."],
    ["यदि किसी समकोण त्रिभुज के दो न्यून कोण बराबर हों, तो प्रत्येक न्यून कोण होगा:", ["30°", "45°", "60°", "90°"], "न्यून कोणों का योग 90° होता है, इसलिए बराबर कोण प्रत्येक 45° के होंगे।"]),
  q(3, "quant", "speed-distance", "M", 0,
    ["A bus travels the first 100 km at a speed of 100 km/h. It covers the next 150 km at a speed of 90 km/h. The average speed of the bus is:", ["93.75", "113.25", "115.50", "117.75"], "Time = 100/100 + 150/90 = 1 + 5/3 = 8/3 h. Average speed = 250 ÷ (8/3) = 93.75 km/h."],
    ["एक बस पहले 100 किमी की यात्रा 100 किमी/घंटा की गति से करती है। यह अगले 150 किमी की यात्रा 90 किमी/घंटा की गति से करती है। बस की औसत गति क्या है?", ["93.75", "113.25", "115.50", "117.75"], "समय = 100/100 + 150/90 = 1 + 5/3 = 8/3 घंटे। औसत गति = 250 ÷ (8/3) = 93.75 किमी/घंटा।"]),
  q(3, "quant", "number-system", "H", 1,
    ["The number 0.00273 (with the digits 73 repeating) in the form p/q, where p and q are integers and q ≠ 0, is:", ["261/99000", "271/99000", "281/99000", "291/99000"], "Let x = 0.00273737… Then 1000x = 2.737373… and 10x = 0.0273737…; subtracting, 99000x = 273 − 2 = 271, so x = 271/99000."],
    ["p/q के रूप में संख्या 0.00273 (73 की आवृत्ति के साथ) है, जहाँ p और q पूर्णांक हैं, और q ≠ 0 क्या है?", ["261/99000", "271/99000", "281/99000", "291/99000"], "माना x = 0.00273737… तब 1000x = 2.737373… और 10x = 0.0273737…; घटाने पर 99000x = 273 − 2 = 271, अतः x = 271/99000।"]),
  q(3, "quant", "simplification", "E", 0,
    ["In decimal form, 65/16 equals:", ["4.0625", "4.0725", "4.0655", "4.0175"], "65 ÷ 16 = 4.0625."],
    ["दशमलव रूप में 65/16 बराबर होता है:", ["4.0625", "4.0725", "4.0655", "4.0175"], "65 ÷ 16 = 4.0625।"]),
  q(3, "quant", "mensuration", "H", 1,
    ["The sum of the length, breadth and height of a cuboid is 20 cm and the length of its diagonal is 10 cm. The surface area of the cuboid is:", ["280", "300", "320", "340"], "Surface area = (l + b + h)² − (diagonal)² = 400 − 100 = 300 cm²."],
    ["एक घनाभ की लंबाई, चौड़ाई और ऊँचाई का योग 20 सेमी है और इसके विकर्ण की लंबाई 10 सेमी है। घनाभ का पृष्ठीय क्षेत्रफल है:", ["280", "300", "320", "340"], "पृष्ठीय क्षेत्रफल = (l + b + h)² − (विकर्ण)² = 400 − 100 = 300 सेमी²।"]),
  q(3, "quant", "mensuration", "M", 1,
    ["A rectangular sheet of paper 88 cm (length) and 28 cm (breadth) is rolled along its length and a cylinder is formed. The radius of the cylinder is:", ["11", "14", "16", "22"], "Rolling along the length makes the circumference 88 cm: 2πr = 88, so r = 88 × 7 / 44 = 14 cm."],
    ["88 सेमी (लंबाई) और 28 सेमी (चौड़ाई) वाली एक आयताकार कागज की शीट को इसकी लंबाई के अनुरूप घुमाया जाता है और एक बेलनाकार आकृति बनाई जाती है। बेलन की त्रिज्या है:", ["11", "14", "16", "22"], "लंबाई के अनुरूप घुमाने पर परिधि 88 सेमी होती है: 2πr = 88, अतः r = 88 × 7 / 44 = 14 सेमी।"]),
  q(3, "quant", "profit-loss", "M", 2,
    ["A shopkeeper allows a discount of 20% to his customers and still gains 10% on a product. If the cost price of the product is ₹500, then the marked price is:", ["683.5", "685.5", "687.5", "689.5"], "Selling price = 500 × 1.10 = ₹550, which is 80% of the marked price, so MP = 550 / 0.8 = ₹687.50."],
    ["एक दुकानदार अपने ग्राहकों को 20% की छूट देता है और फिर भी एक उत्पाद पर 10% का लाभ कमाता है। यदि उत्पाद का क्रय मूल्य 500 रुपये है, तो अंकित मूल्य है:", ["683.5", "685.5", "687.5", "689.5"], "विक्रय मूल्य = 500 × 1.10 = ₹550, जो अंकित मूल्य का 80% है, अतः अंकित मूल्य = 550 / 0.8 = ₹687.50।"]),
  q(3, "quant", "average", "H", 1,
    ["If the difference of the mode and the median of a data is 24, then the difference of the median and the mean is:", ["8", "12", "24", "36"], "Mode = 3 × Median − 2 × Mean gives Mode − Median = 2 × (Median − Mean). So the required difference is 24 / 2 = 12."],
    ["यदि किसी डेटा के बहुलक और माध्यिका का अंतर 24 है, तो माध्यिका और माध्य का अन्तर क्या है?", ["8", "12", "24", "36"], "बहुलक = 3 × माध्यिका − 2 × माध्य से बहुलक − माध्यिका = 2 × (माध्यिका − माध्य)। अतः अभीष्ट अंतर = 24 / 2 = 12।"]),
  q(3, "quant", "geometry", "M", 1,
    ["An exterior angle of a triangle is equal to 100° and the two interior opposite angles are equal. Then each of these angles is equal to:", ["40°", "50°", "75°", "80°"], "The exterior angle equals the sum of the two interior opposite angles, so each = 100° / 2 = 50°."],
    ["किसी त्रिभुज का एक बाह्य कोण 100° के बराबर है तथा दो आंतरिक सम्मुख कोण बराबर हैं, तो इनमें से प्रत्येक कोण बराबर है:", ["40°", "50°", "75°", "80°"], "बाह्य कोण दोनों आंतरिक सम्मुख कोणों के योग के बराबर होता है, अतः प्रत्येक = 100° / 2 = 50°।"]),
  q(3, "quant", "number-system", "M", 0,
    ["The rational number between √2 and √3 is:", ["1.5", "1.8", "(√2 + √3)/2", "(√2 × √3)/2"], "√2 ≈ 1.414 and √3 ≈ 1.732, so 1.5 lies between them and is rational. 1.8 is too large, and the other two are irrational."],
    ["√2 और √3 के बीच परिमेय संख्या है:", ["1.5", "1.8", "(√2 + √3)/2", "(√2 × √3)/2"], "√2 ≈ 1.414 और √3 ≈ 1.732, अतः 1.5 इनके बीच है और परिमेय है। 1.8 बहुत बड़ा है तथा अन्य दोनों अपरिमेय हैं।"]),
  q(3, "quant", "algebra", "M", 0,
    ["The value of 32^(2/5) is:", ["4", "6", "8", "16"], "32 = 2⁵, so 32^(2/5) = 2^(5 × 2/5) = 2² = 4."],
    ["32^(2/5) का मान है:", ["4", "6", "8", "16"], "32 = 2⁵, अतः 32^(2/5) = 2^(5 × 2/5) = 2² = 4।"]),
  q(3, "quant", "mensuration", "M", 0,
    ["The curved surface area of a right circular cone whose slant height is 10 cm and base radius is 7 cm is:", ["220 cm²", "240 cm²", "260 cm²", "280 cm²"], "CSA = π r l = (22/7) × 7 × 10 = 220 cm²."],
    ["10 सेमी तिर्यक ऊँचाई और 7 सेमी आधार (त्रिज्या) वाले एक लंबवृत्तीय शंकु का वक्र पृष्ठीय क्षेत्रफल होगा:", ["220 सेमी²", "240 सेमी²", "260 सेमी²", "280 सेमी²"], "वक्र पृष्ठीय क्षेत्रफल = π r l = (22/7) × 7 × 10 = 220 सेमी²।"]),
  q(3, "quant", "simplification", "E", 1,
    ["The decimal form of 4⅛ is:", ["4.115", "4.125", "4.135", "4.145"], "⅛ = 0.125, so 4⅛ = 4.125."],
    ["4⅛ का दशांश रूप है:", ["4.115", "4.125", "4.135", "4.145"], "⅛ = 0.125, अतः 4⅛ = 4.125।"]),

  // ───────── Section 4: Hindi & English ─────────
  q(4, "hindi", "muhavare", "M", 1,
    ["What is the meaning of the proverb 'गुरु गुड़ ही रहे, चेले शक्कर'?", ["The teacher moved ahead of the pupil", "The pupil went ahead even of the teacher", "The pupil's conduct became sweeter than the teacher's", "The teacher's conduct remained unchanged"], "The saying describes a pupil who surpasses his teacher."],
    ["'गुरु गुड़ ही रहे, चेले शक्कर' — लोकोक्ति का अर्थ है —", ["गुरु चेले से आगे बढ़ गए।", "चेला गुरु से भी आगे बढ़ गया।", "चेले का व्यवहार गुरु से भी मधुर हो गया।", "गुरु का व्यवहार यथावत् रह गया।"], "यह लोकोक्ति तब कही जाती है जब शिष्य अपने गुरु से आगे निकल जाता है।"]),
  q(4, "hindi", "vyakaran", "M", 1,
    ["'मुझे साँप से बहुत डर लगता है।' The underlined word 'डर' is which type of noun?", ["Proper noun (व्यक्तिवाचक)", "Abstract noun (भाववाचक)", "Common noun (जातिवाचक)", "Material noun (द्रव्यवाचक)"], "'डर' (fear) names a feeling or state, so it is an abstract noun."],
    ["मुझे साँप से बहुत डर लगता है। रेखांकित पद संज्ञा का प्रकार है —", ["व्यक्तिवाचक", "भाववाचक", "जातिवाचक", "द्रव्यवाचक"], "'डर' एक भाव या अवस्था का नाम है, अतः भाववाचक संज्ञा है।"]),
  q(4, "hindi", "vyakaran", "M", 1,
    ["'मैं घर जाकर पढ़ लिया करता हूँ।' What is the main verb in this sentence?", ["जाकर", "पढ़", "लिया", "करता हूँ"], "In the compound verb 'पढ़ लिया करता हूँ', 'पढ़' is the main verb; 'लिया' and 'करता हूँ' are auxiliaries."],
    ["मैं घर जाकर पढ़ लिया करता हूँ। इस वाक्य में मुख्य क्रिया है —", ["जाकर", "पढ़", "लिया", "करता हूँ"], "संयुक्त क्रिया 'पढ़ लिया करता हूँ' में 'पढ़' मुख्य क्रिया है; 'लिया' और 'करता हूँ' सहायक क्रियाएँ हैं।"]),
  q(4, "hindi", "vyakaran", "H", 1,
    ["'एक तुम ही थे जिस पर मैं भरोसा कर सकता था।' The underlined word 'ही' is which type of indeclinable (avyay)?", ["Negative particle (निषेधार्थक निपात)", "Emphatic particle (बलदायक निपात)", "Conjunction (समुच्चयबोधक)", "Relation-indicator (संबंधबोधक)"], "'ही' lays stress on the word it follows, so it is a बलदायक निपात."],
    ["एक तुम ही थे जिस पर मैं भरोसा कर सकता था। रेखांकित पद अव्यय का प्रकार है —", ["निषेधार्थक निपात", "बलदायक निपात", "समुच्चयबोधक", "संबंधबोधक"], "'ही' जिस शब्द के साथ आता है उस पर बल देता है, इसलिए यह बलदायक निपात है।"]),
  q(4, "hindi", "paryay-vilom", "M", 1,
    ["Choose the correct synonym of the word 'पक्षी' (bird).", ["रात्रिचर", "नभचर", "दिनकर", "पयोधर"], "'नभचर' (one who moves in the sky) is a synonym of 'पक्षी'. रात्रिचर = nocturnal, दिनकर = sun, पयोधर = cloud."],
    ["'पक्षी' शब्द का सही पर्यायवाची चुनिए —", ["रात्रिचर", "नभचर", "दिनकर", "पयोधर"], "'नभचर' (आकाश में विचरने वाला) 'पक्षी' का पर्यायवाची है। रात्रिचर = निशाचर, दिनकर = सूर्य, पयोधर = बादल।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["Choose the correct antonym pair.", ["अपेक्षा – उपेक्षा", "एक – दो", "शीत – शीतोष्ण", "सामिश्र – असमिश्र"], "'अपेक्षा' (expectation) and 'उपेक्षा' (neglect) are opposites. The other pairs are not true antonyms."],
    ["सही विलोम चुनिए —", ["अपेक्षा – उपेक्षा", "एक – दो", "शीत – शीतोष्ण", "सामिश्र – असमिश्र"], "'अपेक्षा' और 'उपेक्षा' विपरीतार्थी हैं। अन्य युग्म सही विलोम नहीं हैं।"]),
  q(4, "hindi", "shabdavali", "H", 3,
    ["Which word is a many-meaning (anekarthi) word for 'सोना, धतूरा, गेहूँ'?", ["खग", "आली", "कर", "कनक"], "'कनक' means gold, thorn-apple (dhatura) and wheat."],
    ["'सोना, धतूरा, गेहूँ' का अनेकार्थी शब्द बताइये —", ["खग", "आली", "कर", "कनक"], "'कनक' के अर्थ सोना, धतूरा और गेहूँ होते हैं।"]),
  q(4, "hindi", "vyakaran", "M", 1,
    ["In the sentence 'मोर नाचता है', which type of verb is used?", ["Adverb (क्रिया विशेषण)", "Intransitive verb (अकर्मक क्रिया)", "Transitive verb (सकर्मक क्रिया)", "None of these"], "'नाचना' needs no object, so it is an intransitive verb."],
    ["'मोर नाचता है' वाक्य में कौनसी क्रिया प्रयुक्त हुई है?", ["क्रिया विशेषण", "अकर्मक क्रिया", "सकर्मक क्रिया", "इनमें से कोई नहीं"], "'नाचना' क्रिया को कर्म की आवश्यकता नहीं है, अतः यह अकर्मक क्रिया है।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["Choose the correct meaning of the idiom 'अपने पांव पर खड़े होना'.", ["To stand on one leg", "To serve one's self-interest", "To become self-reliant", "None of these"], "Standing on one's own feet means becoming self-reliant."],
    ["'अपने पांव पर खड़े होना' मुहावरे का सही अर्थ चुनिए —", ["एक पैर पर खड़ा होना", "स्वार्थ सिद्ध करना", "आत्मनिर्भर होना", "इनमें से कोई नहीं"], "अपने पाँव पर खड़े होने का अर्थ आत्मनिर्भर होना है।"]),
  q(4, "hindi", "muhavare", "M", 1,
    ["Choose the correct meaning of the proverb 'हाथ कंगन को आरसी क्या'.", ["To be unfit oneself and blame others", "What is obvious needs no proof", "One should work according to one's capacity", "Much labour, little result"], "If a bracelet is already on the hand, no mirror is needed to see it — direct evidence needs no proof."],
    ["'हाथ कंगन को आरसी क्या' लोकोक्ति का सही अर्थ चुनिए —", ["स्वयं अयोग्य होना, दोष दूसरों को देना", "प्रत्यक्ष को प्रमाण की आवश्यकता नहीं", "सामर्थ्य के अनुसार कार्य करना चाहिए", "परिश्रम अधिक, फल कम"], "हाथ में पहना कंगन देखने के लिए दर्पण की जरूरत नहीं होती — प्रत्यक्ष को प्रमाण नहीं चाहिए।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["Choose the one-word synonym of 'चाँद' (moon).", ["मयंक", "अनुपम", "बटोही", "भुजंग"], "'मयंक' is a synonym of the moon. अनुपम = matchless, बटोही = traveller, भुजंग = snake."],
    ["'चाँद' का एकार्थी शब्द चुनिए —", ["मयंक", "अनुपम", "बटोही", "भुजंग"], "'मयंक' चंद्रमा का पर्याय है। अनुपम = अद्वितीय, बटोही = राही, भुजंग = साँप।"]),
  q(4, "hindi", "vyakaran", "M", 3,
    ["What are the words called that do not change because of gender, number, case, tense or person?", ["Adjective (विशेषण)", "Compound (समास)", "Inflected word (विकारी शब्द)", "Indeclinable (अव्यय)"], "Words that remain unchanged by gender, number, case, tense and person are 'अव्यय' (avikari words)."],
    ["जो शब्द लिंग, वचन, कारक, काल, पुरुष के कारण परिवर्तित नहीं होते हैं, उन्हें क्या कहते हैं?", ["विशेषण", "समास", "विकारी शब्द", "अव्यय"], "लिंग, वचन, कारक, काल और पुरुष से अपरिवर्तित रहने वाले शब्द 'अव्यय' (अविकारी शब्द) कहलाते हैं।"]),
  q(4, "hindi", "vyakaran", "E", 3,
    ["How many vowels (svar) are there in Hindi?", ["9", "7", "8", "11"], "Hindi has 11 vowels: अ, आ, इ, ई, उ, ऊ, ऋ, ए, ऐ, ओ, औ."],
    ["हिन्दी में कितने स्वर हैं?", ["9", "7", "8", "11"], "हिंदी में 11 स्वर हैं: अ, आ, इ, ई, उ, ऊ, ऋ, ए, ऐ, ओ, औ।"]),
  q(4, "hindi", "vyakaran", "M", 0,
    ["How many types of conjunction (samuchchayabodhak avyay) are there?", ["Two", "Three", "Four", "Five"], "Conjunctions are of two kinds: समानाधिकरण and व्यधिकरण (उपवाक्य-संबंधी)."],
    ["समुच्चयबोधक अव्यय के कितने भेद हैं?", ["दो", "तीन", "चार", "पाँच"], "समुच्चयबोधक अव्यय के दो भेद हैं: समानाधिकरण और व्यधिकरण।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["Which idiom would be used for 'हार मान लेना' (to admit defeat)?", ["गले पड़ना", "कलेजा फटना", "घुटने टेकना", "जान पर खेलना"], "'घुटने टेकना' means to give in or admit defeat."],
    ["'हार मान लेना' के लिए कौनसा मुहावरा प्रयुक्त होगा?", ["गले पड़ना", "कलेजा फटना", "घुटने टेकना", "जान पर खेलना"], "'घुटने टेकना' का अर्थ हार मान लेना या समर्पण करना है।"]),
  q(4, "hindi", "vyakaran", "M", 0,
    ["Pick the adjective (visheshan) from the following.", ["मूर्धन्य", "यज्ञ", "सत्य", "मधु"], "'मूर्धन्य' (eminent, foremost) is used as an adjective; यज्ञ, सत्य and मधु are nouns."],
    ["निम्नलिखित में से विशेषण छाँटिए —", ["मूर्धन्य", "यज्ञ", "सत्य", "मधु"], "'मूर्धन्य' (श्रेष्ठ, प्रमुख) विशेषण के रूप में प्रयुक्त है; यज्ञ, सत्य और मधु संज्ञाएँ हैं।"]),
  q(4, "hindi", "vyakaran", "M", 2,
    ["What type of noun is the word 'सोना-चाँदी'?", ["Proper noun (व्यक्तिवाचक)", "Abstract noun (भाववाचक)", "Material noun (द्रव्यवाचक)", "Collective noun (समूहवाचक)"], "Gold and silver are substances, so 'सोना-चाँदी' is a material (द्रव्यवाचक) noun."],
    ["सोना-चाँदी शब्द किस प्रकार की संज्ञा है?", ["व्यक्तिवाचक", "भाववाचक", "द्रव्यवाचक", "समूहवाचक"], "सोना और चाँदी पदार्थ हैं, इसलिए 'सोना-चाँदी' द्रव्यवाचक संज्ञा है।"]),
  q(4, "english", "grammar", "M", 2,
    ["You should not ..................... the worst.", ["assumed", "assuming", "assume", "assumes"], "After the modal 'should not' the base form of the verb is used: 'assume'."],
    ["You should not ..................... the worst.", ["assumed", "assuming", "assume", "assumes"], "'should not' जैसे modal के बाद क्रिया का मूल रूप आता है: 'assume'।"]),
  q(4, "english", "voice-speech", "M", 2,
    ["\"The police arrested the thief.\" (Active to Passive voice)", ["The thief is arrested by the police.", "The thief has been arrested by the police.", "The thief was arrested by the police.", "The thief will be arrested by the police."], "The simple past 'arrested' becomes 'was arrested' in the passive."],
    ["\"The police arrested the thief.\" (Active से Passive voice)", ["The thief is arrested by the police.", "The thief has been arrested by the police.", "The thief was arrested by the police.", "The thief will be arrested by the police."], "simple past 'arrested', passive में 'was arrested' हो जाता है।"]),
  q(4, "english", "error-spotting", "E", 2,
    ["Find the incorrect sentence:", ["The sun rises in the east.", "She goes to school everyday.", "They are go to the market now.", "We have completed our homework."], "'They are go' is wrong; it should be 'They are going' or 'They go'."],
    ["गलत वाक्य छाँटिए:", ["The sun rises in the east.", "She goes to school everyday.", "They are go to the market now.", "We have completed our homework."], "'They are go' गलत है; सही रूप 'They are going' या 'They go' है।"]),
  q(4, "english", "grammar", "E", 2,
    ["He is ..................... best player in our team.", ["a", "an", "the", "no article"], "The superlative 'best' takes the definite article: 'the best player'."],
    ["He is ..................... best player in our team.", ["a", "an", "the", "no article"], "उत्तमावस्था 'best' के साथ definite article आता है: 'the best player'।"]),
  q(4, "english", "grammar", "E", 1,
    ["She has only a ..................... time left before the exam.", ["many", "little", "few", "more"], "'Time' is uncountable, so 'a little time' is correct ('many' and 'few' are for countable nouns)."],
    ["She has only a ..................... time left before the exam.", ["many", "little", "few", "more"], "'Time' अगणनीय संज्ञा है, इसलिए 'a little time' सही है ('many' और 'few' गणनीय संज्ञा के साथ आते हैं)।"]),
  q(4, "english", "grammar", "M", 2,
    ["This book is mine, but that one is ..................... .", ["her", "she", "theirs", "they"], "A possessive pronoun is needed after 'is': 'theirs'. 'Her' would have to be 'hers'."],
    ["This book is mine, but that one is ..................... .", ["her", "she", "theirs", "they"], "'is' के बाद स्वामित्व-बोधक सर्वनाम चाहिए: 'theirs'। 'her' के स्थान पर 'hers' होता।"]),
  q(4, "english", "grammar", "M", 3,
    ["By the next month, we shall ..................... the project.", ["has completed", "completing", "completed", "have completed"], "The future perfect tense is 'shall have + past participle': 'shall have completed'."],
    ["By the next month, we shall ..................... the project.", ["has completed", "completing", "completed", "have completed"], "future perfect tense की संरचना 'shall have + past participle' है: 'shall have completed'।"]),
  q(4, "english", "voice-speech", "M", 1,
    ["She said, \"Do you like ice cream?\" (Direct to Indirect speech)", ["She said if I like ice cream.", "She asked if I liked ice cream.", "She asked that I liked ice cream.", "She asked if I like ice creams."], "A yes/no question is reported with 'asked if' and the tense moves back: 'She asked if I liked ice cream.'"],
    ["She said, \"Do you like ice cream?\" (Direct से Indirect speech)", ["She said if I like ice cream.", "She asked if I liked ice cream.", "She asked that I liked ice cream.", "She asked if I like ice creams."], "हाँ/ना वाले प्रश्न को 'asked if' से व्यक्त किया जाता है और काल पीछे चला जाता है: 'She asked if I liked ice cream.'"]),
  q(4, "english", "voice-speech", "H", 0,
    ["He said, \"May God bless you!\" (Direct to Indirect speech)", ["He prayed that God might bless me.", "He said that God may bless me.", "He told that God will bless me.", "He wished that God could bless me."], "An optative sentence (a blessing or wish) is reported with 'prayed that' and 'might': 'He prayed that God might bless me.'"],
    ["He said, \"May God bless you!\" (Direct से Indirect speech)", ["He prayed that God might bless me.", "He said that God may bless me.", "He told that God will bless me.", "He wished that God could bless me."], "इच्छा या आशीर्वाद सूचक वाक्य को 'prayed that' और 'might' से व्यक्त किया जाता है: 'He prayed that God might bless me.'"]),
  q(4, "english", "voice-speech", "M", 1,
    ["\"Open the door!\" (Active to Passive voice)", ["The door is opened.", "Let the door be opened.", "The door was opened.", "The door has been opened."], "An imperative sentence becomes passive with 'Let … be + past participle': 'Let the door be opened.'"],
    ["\"Open the door!\" (Active से Passive voice)", ["The door is opened.", "Let the door be opened.", "The door was opened.", "The door has been opened."], "आज्ञार्थक वाक्य का passive 'Let … be + past participle' से बनता है: 'Let the door be opened.'"]),
  q(4, "english", "voice-speech", "M", 0,
    ["\"She must complete this work by Monday.\" (Active to Passive voice)", ["This work must be completed by her by Monday.", "This work should be completed by her by Monday.", "This work will be completed by her by Monday.", "This work has to be completed by her by Monday."], "With a modal verb the passive is 'modal + be + past participle': 'must be completed'."],
    ["\"She must complete this work by Monday.\" (Active से Passive voice)", ["This work must be completed by her by Monday.", "This work should be completed by her by Monday.", "This work will be completed by her by Monday.", "This work has to be completed by her by Monday."], "modal verb के साथ passive 'modal + be + past participle' होता है: 'must be completed'।"]),
  q(4, "english", "error-spotting", "E", 1,
    ["Identify the incorrect sentence:", ["We are listening to music.", "They was going to school.", "She has completed her work.", "He is learning French."], "'They was' is wrong; the plural subject needs 'were': 'They were going to school.'"],
    ["गलत वाक्य की पहचान कीजिए:", ["We are listening to music.", "They was going to school.", "She has completed her work.", "He is learning French."], "'They was' गलत है; बहुवचन कर्ता के साथ 'were' आना चाहिए: 'They were going to school.'"]),
  q(4, "english", "grammar", "M", 0,
    ["Would you like ..................... sugar in your tea?", ["some", "any", "much", "few"], "'Some' is used in offers and polite requests even in questions."],
    ["Would you like ..................... sugar in your tea?", ["some", "any", "much", "few"], "प्रस्ताव या विनम्र अनुरोध वाले प्रश्नों में 'some' का प्रयोग होता है।"]),
  q(4, "english", "grammar", "E", 2,
    ["They ..................... a new car last week.", ["buy", "buys", "bought", "buying"], "'Last week' shows the simple past tense: 'bought'."],
    ["They ..................... a new car last week.", ["buy", "buys", "bought", "buying"], "'Last week' simple past दर्शाता है: 'bought'।"]),
  q(4, "english", "grammar", "E", 0,
    ["This is an ..................... book.", ["interesting", "quickly", "sadly", "slowly"], "An adjective is needed before the noun 'book': 'interesting' (the others are adverbs)."],
    ["This is an ..................... book.", ["interesting", "quickly", "sadly", "slowly"], "संज्ञा 'book' से पहले विशेषण चाहिए: 'interesting' (अन्य सभी क्रिया-विशेषण हैं)।"]),
  q(4, "english", "grammar", "M", 0,
    ["From the choices given below, pick out the correct one to complete the sentence: We would like to inform you .....................", ["that you have been selected for the job.", "that you will have been selected for the job.", "that you had been selected for the job.", "that you are been selected for the job."], "'Have been selected' (present perfect passive) is the correct form; the other options are ungrammatical or illogical."],
    ["वाक्य को पूरा करने के लिए सही विकल्प चुनिए: We would like to inform you .....................", ["that you have been selected for the job.", "that you will have been selected for the job.", "that you had been selected for the job.", "that you are been selected for the job."], "'have been selected' (present perfect passive) सही रूप है; अन्य विकल्प व्याकरण या तर्क की दृष्टि से गलत हैं।"]),
  q(4, "english", "spelling", "E", 1,
    ["Pick out the rightly spelt word:", ["Allowence", "Accuracy", "Occurrance", "Commitee"], "The correct spellings are allowance, accuracy, occurrence and committee, so 'Accuracy' is the only correct one here."],
    ["सही वर्तनी वाला शब्द छाँटिए:", ["Allowence", "Accuracy", "Occurrance", "Commitee"], "सही वर्तनी allowance, accuracy, occurrence और committee है, इसलिए यहाँ केवल 'Accuracy' सही है।"]),
  q(4, "english", "grammar", "M", 0,
    ["Pick out the correct sentence among the following:", ["I have lived here for ten years.", "I have been living here since ten years.", "I am living here since 2014.", "I am living here for ten years."], "'For' is used with a period of time and 'since' with a point in time; with these, the present perfect 'have lived' is correct."],
    ["निम्नलिखित में से सही वाक्य छाँटिए:", ["I have lived here for ten years.", "I have been living here since ten years.", "I am living here since 2014.", "I am living here for ten years."], "अवधि के साथ 'for' और समय-बिंदु के साथ 'since' आता है; यहाँ present perfect 'have lived' सही है।"]),
  q(4, "english", "grammar", "M", 2,
    ["Fill in the blank in the given sentence: Rising prices are ................. universal phenomenon.", ["an", "the", "a", "None of these"], "'Universal' begins with a /yu/ sound, so the article is 'a': 'a universal phenomenon'."],
    ["रिक्त स्थान भरिए: Rising prices are ................. universal phenomenon.", ["an", "the", "a", "None of these"], "'Universal' का उच्चारण /यू/ से शुरू होता है, इसलिए article 'a' आएगा: 'a universal phenomenon'।"]),
];
