// HP Police Constable written exam held on 3 July 2022 (Series C) — transcribed from the photographed paper, which carries
// yellow highlights for the answers. Every answer was re-solved independently; where a highlight is plainly wrong the
// correct answer is used (original numbers 18, 26, 28, 29, 31, 55, 59). Left out: 66 (series that fits no option) and 72 (figure).
// Option order is kept as printed. Sections: 0 Himachal GK, 1 General Knowledge, 2 Reasoning, 3 Numerical Ability, 4 Hindi & English.

import { q, type PoliceQuestion } from "../police/types";

const PROF_EN =
  "Five professors Dr. Joshi, Dr. Davar, Dr. Natrajan, Dr. Choudhary and Dr. Zia teach five different subjects (Zoology, Physics, Botany, Geology and History) in four universities (Delhi, Gujarat, Bombay and Osmania). (I) Dr. Choudhary teaches Zoology in Bombay University. (II) Dr. Natrajan is neither in Osmania University nor in Delhi University and he neither teaches Geology nor History. (III) Dr. Zia teaches Physics but neither in Bombay University nor in Osmania University. (IV) Dr. Joshi teaches History in Delhi University. (V) Two professors are from Gujarat University.";
const PROF_HI =
  "पांच प्राध्यापकों डॉ. जोशी, डॉ. डावर, डॉ. नटराजन, डॉ. चौधरी और डॉ. ज़िया चार विश्वविद्यालयों दिल्ली, गुजरात, बॉम्बे और उस्मानिया में पांच अलग-अलग विषय प्राणिविज्ञान, भौतिकी, वनस्पति विज्ञान, भूविज्ञान और इतिहास पढ़ाते हैं। (I) डॉ. चौधरी बॉम्बे विश्वविद्यालय में प्राणिविज्ञान पढ़ाते हैं। (II) डॉ. नटराजन न तो उस्मानिया विश्वविद्यालय में हैं और न ही दिल्ली विश्वविद्यालय में और वे न तो भूविज्ञान पढ़ाते हैं और न ही इतिहास। (III) डॉ. ज़िया भौतिकी पढ़ाते हैं लेकिन न तो बॉम्बे विश्वविद्यालय में और न ही उस्मानिया विश्वविद्यालय में। (IV) डॉ. जोशी दिल्ली विश्वविद्यालय में इतिहास पढ़ाते हैं। (V) दो प्राध्यापक गुजरात विश्वविद्यालय से हैं।";
const PROF_SOL =
  "Natrajan must teach Botany (Zoology, Physics, Geology and History are taken). Davar teaches Geology and is the only one left for Osmania. Natrajan and Zia are therefore the two from Gujarat.";
const PROF_SOL_HI =
  "नटराजन वनस्पति विज्ञान पढ़ाते हैं (प्राणिविज्ञान, भौतिकी, भूविज्ञान और इतिहास के शिक्षक तय हैं)। डावर भूविज्ञान पढ़ाते हैं और उस्मानिया के लिए केवल वही बचते हैं। अतः नटराजन और ज़िया गुजरात के दो प्राध्यापक हैं।";

const COLLEGE_EN =
  "K, L, M, N, O, P and Q are seven students studying in three different colleges X, Y and Z. There are three girls among them, one in each of these colleges. Two of them study mechanical engineering, two study medicine and one each study biotechnology, pharmacy and electrical engineering. M studies with only her best friend K, who studies pharmacy in college Y. No girl studies either biotechnology or electrical engineering. O studies mechanical engineering in college X and his brother P studies electrical engineering in college Z. None of the two who are studying medicine are in college Y. N studies biotechnology along with O and Q.";
const COLLEGE_HI =
  "K, L, M, N, O, P और Q सात छात्र हैं जो तीन अलग-अलग कॉलेजों X, Y और Z में पढ़ रहे हैं। उनमें से तीन लड़कियां हैं, इनमें से प्रत्येक कॉलेज में एक है। उनमें से दो मैकेनिकल इंजीनियरिंग की पढ़ाई करते हैं, दो चिकित्सा की पढ़ाई करते हैं और एक-एक बायोटेक्नोलॉजी, फार्मेसी और इलेक्ट्रिकल इंजीनियरिंग की पढ़ाई करते हैं। M केवल अपने सबसे अच्छे दोस्त K के साथ पढ़ती है जो कॉलेज Y में फार्मेसी की पढ़ाई करता है। कोई भी लड़की या तो बायोटेक्नोलॉजी या इलेक्ट्रिकल इंजीनियरिंग नहीं पढ़ती है। O कॉलेज X में मैकेनिकल इंजीनियरिंग पढ़ता है और उसका भाई P कॉलेज Z में इलेक्ट्रिकल इंजीनियरिंग की पढ़ाई करता है। दोनों में से कोई भी जो चिकित्सा की पढ़ाई कर रहा है, कॉलेज Y में नहीं है। O और Q के साथ N बायोटेक्नोलॉजी का अध्ययन करता है।";
const COLLEGE_SOL =
  "College Y has only K and M, so X has O, N, Q and Z has P, L. M (a girl in Y) cannot study medicine, pharmacy, biotechnology or electrical engineering, so M studies mechanical engineering. The two medicine students are therefore Q and L.";
const COLLEGE_SOL_HI =
  "कॉलेज Y में केवल K और M हैं, इसलिए X में O, N, Q और Z में P, L हैं। Y की लड़की M चिकित्सा, फार्मेसी, बायोटेक्नोलॉजी या इलेक्ट्रिकल नहीं पढ़ सकती, इसलिए M मैकेनिकल इंजीनियरिंग पढ़ती है। अतः चिकित्सा के दो छात्र Q और L हैं।";

export const y2022jul: PoliceQuestion[] = [
  // ───────── Section 0: Himachal GK ─────────
  q(0, "hp-gk", "geography", "M", 1,
    ["The state bird of Himachal Pradesh is ______.", ["Monal", "Western Tragopan", "Himalayan Bulbul", "Great Barbet"], "The Western Tragopan (Jujurana) is the state bird of Himachal Pradesh. The Monal is the state bird of Uttarakhand."],
    ["हिमाचल प्रदेश का राज्य पक्षी ______ है।", ["मोनाल", "पश्चिमी जुजुराना", "हिमालयन बुलबुल", "ग्रेट बारबेट"], "पश्चिमी ट्रैगोपैन (जुजुराना) हिमाचल प्रदेश का राज्य पक्षी है। मोनाल उत्तराखंड का राज्य पक्षी है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 2,
    ["Which river is the Kol Dam in Himachal Pradesh built across?", ["Ravi", "Beas", "Sutlej", "Sainj"], "The 800 MW Kol Dam (Bilaspur) is built on the Sutlej river."],
    ["हिमाचल प्रदेश में कोल बांध किस नदी पर बना है?", ["रावी", "ब्यास", "सतलुज", "सैंज"], "800 मेगावाट का कोल बांध (बिलासपुर) सतलुज नदी पर बना है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["What is the architectural style of the temple built on the edge of the Prashar lake?", ["Pyramidal shaped", "Nagara", "Pagoda", "Cone shaped"], "The temple of Rishi Prashar beside Prashar lake (Mandi) is built in the pagoda style, with tiered wooden roofs."],
    ["पराशर झील के किनारे बने मंदिर की स्थापत्य शैली क्या है?", ["पिरामिड के आकार का", "नागर", "पैगोडा", "शंकु के आकार का"], "पराशर झील (मंडी) के किनारे स्थित ऋषि पराशर का मंदिर पैगोडा शैली में, कई स्तरों वाली लकड़ी की छतों के साथ बना है।"]),
  q(0, "hp-gk", "geography", "H", 2,
    ["In which district is the Bandli Wildlife Sanctuary located?", ["Kangra", "Sirmaur", "Mandi", "Kullu"], "Bandli Wildlife Sanctuary lies in Mandi district (Seraj area)."],
    ["बंदली वन्यजीव अभयारण्य किस जिले में स्थित है?", ["कांगड़ा", "सिरमौर", "मंडी", "कुल्लू"], "बंदली वन्यजीव अभयारण्य मंडी जिले (सराज क्षेत्र) में स्थित है।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["Which mountain pass provides access between the Lahaul and Spiti valleys?", ["Kugti", "Ghasutri", "Inderhar", "Kunzum"], "Kunzum Pass (about 4,590 m) connects the Lahaul and Spiti valleys."],
    ["कौन सा पहाड़ी दर्रा लाहौल और स्पीति घाटियों के बीच पहुंच प्रदान करता है?", ["कुगती", "घसुत्री", "इंदरहार", "कुंजुम"], "कुंजुम दर्रा (लगभग 4,590 मी.) लाहौल और स्पीति घाटियों को जोड़ता है।"]),

  // ───────── Section 1: General Knowledge ─────────
  q(1, "general-studies", "indian-polity", "M", 3,
    ["Which of the states ranked first in the Sustainable Development Goals India Index 2020-21 released by NITI Aayog?", ["Himachal Pradesh", "Tamil Nadu", "Andhra Pradesh", "Kerala"], "Kerala topped the SDG India Index 2020-21 with a score of 75; Himachal Pradesh and Tamil Nadu followed with 74."],
    ["नीति आयोग द्वारा जारी सतत विकास लक्ष्य भारत सूचकांक, 2020-21 में कौन सा राज्य पहले स्थान पर है?", ["हिमाचल प्रदेश", "तमिलनाडु", "आंध्र प्रदेश", "केरल"], "नीति आयोग के एसडीजी इंडिया इंडेक्स 2020-21 में केरल 75 अंकों के साथ पहले स्थान पर रहा; हिमाचल प्रदेश और तमिलनाडु 74 अंकों के साथ दूसरे स्थान पर रहे।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["“On 26th January, 1950, we are going to enter a life of contradictions. In politics, we will have equality and in social and economic life we will have inequality.” To whom among the following is this quote attributed?", ["Mahatma Gandhi", "Babasaheb Dr. Bhimrao Ambedkar", "Sardar Vallabhbhai Patel", "Lal Bahadur Shastri"], "Dr B.R. Ambedkar said this in his concluding speech in the Constituent Assembly on 25 November 1949."],
    ["“26 जनवरी, 1950 को हम अंतर्विरोधों के जीवन में प्रवेश करने जा रहे हैं। राजनीति में हमारे पास समानता होगी और सामाजिक एवं आर्थिक जीवन में हमारे पास असमानता होगी।” निम्नलिखित में से किसको इस उद्धरण का श्रेय दिया जाता है?", ["महात्मा गांधी", "बाबासाहेब डॉ. भीमराव अम्बेडकर", "सरदार वल्लभ भाई पटेल", "लाल बहादुर शास्त्री"], "डॉ. बी.आर. अम्बेडकर ने 25 नवंबर 1949 को संविधान सभा में अपने समापन भाषण में यह कहा था।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["The Electoral College for electing the President of India includes which of the following? (i) Elected members of Rajya Sabha (ii) Elected members of the Legislative Assemblies of the States (iii) Elected members of the Legislative Councils of the States", ["iii only", "ii only", "ii and iii", "i and ii"], "The electoral college has the elected members of both Houses of Parliament and the elected members of the state Legislative Assemblies (and of Delhi and Puducherry). Legislative Councils are not included."],
    ["भारत के राष्ट्रपति के चुनाव के लिए निर्वाचक मंडल में निम्नलिखित में से क्या शामिल है? (i) राज्यसभा के निर्वाचित सदस्य (ii) राज्यों की विधान सभाओं के निर्वाचित सदस्य (iii) राज्यों की विधान परिषदों के निर्वाचित सदस्य", ["केवल iii", "केवल ii", "ii और iii", "i और ii"], "निर्वाचक मंडल में संसद के दोनों सदनों और राज्यों की विधान सभाओं (तथा दिल्ली व पुडुचेरी) के निर्वाचित सदस्य होते हैं। विधान परिषदों के सदस्य शामिल नहीं होते।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["Who among the following fixes the date of election of the Deputy Speaker of the Lok Sabha?", ["The Secretary General of the Lok Sabha", "The Protem Speaker of the Lok Sabha", "The President of India", "The Speaker of the Lok Sabha"], "The date for the election of the Deputy Speaker is fixed by the Speaker of the Lok Sabha."],
    ["निम्नलिखित में से कौन लोकसभा के उपाध्यक्ष के चुनाव की तारीख तय करता है?", ["लोकसभा के महासचिव", "लोकसभा के प्रोटेम स्पीकर", "भारत के राष्ट्रपति", "लोकसभा अध्यक्ष"], "उपाध्यक्ष के चुनाव की तारीख लोकसभा अध्यक्ष तय करता है।"]),
  q(1, "general-studies", "indian-geography", "M", 3,
    ["Because of its high clay content, the soil develops wide cracks in the dry season. It is poor in humus yet highly moisture-retentive, thus responding well to irrigation. Cotton is the most traditional crop where this soil is found. Identify the soil type.", ["Red Soil", "Alluvial Soil", "Laterite Soil", "Black Soil"], "Black (regur) soil is rich in clay, cracks when dry, holds moisture and is ideal for cotton."],
    ["मिट्टी चीका या मृत्तिका (clay) की मात्रा अधिक होने के कारण शुष्क मौसम में इस मिट्टी में चौड़ी दरारें पड़ जाती हैं। इसमें ह्यूमस की कमी होती है मगर यह अत्यधिक नमी धारण करने वाली है, इस प्रकार सिंचाई के लिए अच्छी प्रतिक्रिया देती है। कपास सबसे परंपरागत फसल है जहां यह मिट्टी पाई जाती है। मिट्टी के प्रकार को पहचानें।", ["लाल मिट्टी", "जलोढ़ मिट्टी", "लैटेराइट मिट्टी", "काली मिट्टी"], "काली (रेगुर) मिट्टी में चीका अधिक होती है, सूखने पर दरारें पड़ती हैं, नमी रोकती है और कपास के लिए आदर्श है।"]),
  q(1, "general-studies", "general-science", "M", 2,
    ["The first 5G call in India was recently tested at:", ["IIT Kanpur", "IISc Bangalore", "IIT Madras", "IIT Delhi"], "The first 5G call in India was made at IIT Madras in May 2022 on an indigenously built 5G network."],
    ["भारत में पहली 5G कॉल का हाल ही में परीक्षण कहाँ किया गया था?", ["आईआईटी कानपुर", "आईआईएससी बैंगलोर", "आईआईटी मद्रास", "आईआईटी दिल्ली"], "भारत की पहली 5G कॉल मई 2022 में आईआईटी मद्रास में स्वदेशी 5G नेटवर्क पर की गई।"]),
  q(1, "computer", "web-technologies", "H", 1,
    ["______ is aimed at building an extra decentralized web that puts users in control of their data and identity.", ["Web 2.0", "Web 5.0", "Web 3.0", "Web 4.0"], "Web5 is a decentralized-web platform announced in 2022 (by TBD, a Block unit) that gives users ownership of their data and identity."],
    ["______ का उद्देश्य एक अतिरिक्त विकेन्द्रीकृत वेब बनाना है जो उपयोगकर्ताओं को उनके डेटा और पहचान के नियंत्रण में रखता है।", ["वेब 2.0", "वेब 5.0", "वेब 3.0", "वेब 4.0"], "वेब 5 एक विकेंद्रीकृत वेब प्लेटफ़ॉर्म है (2022 में घोषित), जो उपयोगकर्ताओं को उनके डेटा और पहचान पर स्वामित्व देता है।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["The Cripps Mission was sent by the British Government to visit India in the year:", ["1946", "1935", "1942", "1939"], "Sir Stafford Cripps came to India in March 1942 with proposals for post-war self-government."],
    ["ब्रिटिश सरकार द्वारा क्रिप्स मिशन को वर्ष में भारत आने के लिए भेजा गया था:", ["1946", "1935", "1942", "1939"], "सर स्टैफर्ड क्रिप्स मार्च 1942 में युद्धोत्तर स्वशासन के प्रस्तावों के साथ भारत आए।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["Which provision of law did the Navtej Singh Johar vs Union of India case of the Supreme Court deal with?", ["Section 124A of IPC", "Section 377 of IPC", "Section 66A of IT Act", "Section 497 of IPC"], "In 2018 the Supreme Court in Navtej Singh Johar read down Section 377 IPC, decriminalising consensual same-sex relations."],
    ["सुप्रीम कोर्ट का नवतेज सिंह जौहर बनाम भारत संघ मामला कानून के किस प्रावधान से संबंधित था?", ["आईपीसी की धारा 124ए", "आईपीसी की धारा 377", "आईटी अधिनियम की धारा 66ए", "आईपीसी की धारा 497"], "2018 में नवतेज सिंह जौहर मामले में सुप्रीम कोर्ट ने धारा 377 के तहत आपसी सहमति से समलैंगिक संबंधों को अपराध की श्रेणी से बाहर कर दिया।"]),
  q(1, "general-studies", "indian-history", "E", 2,
    ["Which among the following books was authored by Mahatma Gandhi?", ["My Truth", "Hindu View of Life", "Hind Swaraj", "Discovery of India"], "Gandhi wrote Hind Swaraj in 1909. 'The Hindu View of Life' is by S. Radhakrishnan and 'Discovery of India' by Nehru."],
    ["निम्नलिखित में से कौन सी पुस्तक महात्मा गांधी द्वारा लिखी गई थी?", ["मेरी सच्चाई", "जीवन का हिंदू दृष्टिकोण", "हिंद स्वराज", "भारत की खोज"], "गांधीजी ने 1909 में 'हिंद स्वराज' लिखी। 'द हिंदू व्यू ऑफ लाइफ' एस. राधाकृष्णन की और 'डिस्कवरी ऑफ इंडिया' नेहरू की रचना है।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["The 'Police Commemoration Day' is observed in India on:", ["January 15", "November 26", "July 26", "October 21"], "Police Commemoration Day is observed on 21 October in memory of the 10 CRPF personnel killed at Hot Springs (Ladakh) in 1959."],
    ["भारत में 'पुलिस स्मृति दिवस' कब मनाया जाता है?", ["जनवरी 15", "नवंबर 26", "जुलाई 26", "अक्टूबर 21"], "पुलिस स्मृति दिवस 21 अक्टूबर को 1959 में लद्दाख के हॉट स्प्रिंग में शहीद हुए सीआरपीएफ के 10 जवानों की याद में मनाया जाता है।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["The Earth's atmosphere is mainly heated by:", ["Short wave solar radiation", "Long wave terrestrial radiation", "Reflected solar radiation", "Scattered radiation"], "Short-wave solar radiation passes through the atmosphere and heats the ground; the ground then emits long-wave terrestrial radiation, which heats the air."],
    ["पृथ्वी का वायुमंडल मुख्यतः किसके द्वारा गर्म किया जाता है?", ["लघु तरंग सौर विकिरण", "लंबी तरंग स्थलीय विकिरण", "परावर्तित सौर विकिरण", "बिखरा हुआ विकिरण"], "लघु तरंग सौर विकिरण वायुमंडल से गुजरकर धरातल को गर्म करता है; धरातल फिर दीर्घ तरंग स्थलीय विकिरण छोड़ता है, जो वायुमंडल को गर्म करता है।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["How are evergreen plants with woody stems having naked seeds classified?", ["Angiosperms", "Pteridophytes", "Gymnosperms", "Bryophytes"], "Gymnosperms (such as pine and deodar) are woody, mostly evergreen plants whose seeds are not enclosed in a fruit."],
    ["नग्न बीज वाले लकड़ी के तनों वाले सदाबहार पौधों को किस प्रकार वर्गीकृत किया जाता है?", ["आवृतबीजी", "टेरिडोफाइट्स", "जिम्नोस्पर्म", "ब्रायोफाइट्स"], "जिम्नोस्पर्म (जैसे चीड़, देवदार) काष्ठीय, प्रायः सदाबहार पौधे हैं जिनके बीज फल में बंद नहीं होते।"]),
  q(1, "general-studies", "general-science", "E", 1,
    ["Which of the following organelles is not found in animal cells?", ["Lysosome", "Cell wall", "Endoplasmic reticulum", "Cell membrane"], "Animal cells have lysosomes, endoplasmic reticulum and a cell membrane; the cell wall is found only in plant (and fungal and bacterial) cells."],
    ["निम्नलिखित में से कौन सा कोशिकांग जंतु कोशिकाओं में नहीं पाया जाता है?", ["लाइसोसोम", "सेल वाल", "अन्तः प्रद्व्ययी जालिका", "कोशिका झिल्ली"], "जंतु कोशिकाओं में लाइसोसोम, अंतःप्रद्रव्यी जालिका और कोशिका झिल्ली होती है; कोशिका भित्ति केवल पादप (तथा कवक व जीवाणु) कोशिकाओं में होती है।"]),
  q(1, "general-studies", "general-science", "M", 3,
    ["The stars twinkle in the night because:", ["They emit light intermittently", "The earth's atmosphere absorbs light intermittently", "The star's atmosphere absorbs light intermittently", "The refractive index of air in the atmosphere fluctuates"], "Starlight is refracted repeatedly as it passes through air layers of changing density, so the apparent position and brightness flicker — twinkling."],
    ["रात में तारे टिमटिमाते हैं क्योंकि", ["वे रुक-रुक कर प्रकाश उत्सर्जित करते हैं", "पृथ्वी का वायुमंडल रुक-रुक कर प्रकाश को अवशोषित करता है", "तारे का वातावरण रुक-रुक कर प्रकाश को अवशोषित करता है", "वायुमण्डल में वायु के अपवर्तनांक में उतार-चढ़ाव होता रहता है"], "तारे का प्रकाश बदलते घनत्व वाली वायु की परतों से बार-बार अपवर्तित होता है, इसलिए उसकी स्थिति और चमक डगमगाती है — यही टिमटिमाना है।"]),
  q(1, "general-studies", "general-science", "E", 2,
    ["Which one of the following is called the King of Chemicals?", ["Sodium chloride", "Nitric acid", "Sulphuric acid", "Sodium carbonate"], "Sulphuric acid is called the King of Chemicals because of its huge range of industrial uses."],
    ["निम्नलिखित में से किसे रसायन का राजा कहा जाता है?", ["सोडियम क्लोराइड", "नाइट्रिक अम्ल", "सल्फ्यूरिक अम्ल", "सोडियम कार्बोनेट"], "सल्फ्यूरिक अम्ल को उद्योगों में अत्यधिक उपयोग के कारण रसायनों का राजा कहा जाता है।"]),
  q(1, "general-studies", "general-science", "E", 3,
    ["Vinegar is the trade name for ______.", ["Formic acid", "Phenol", "Carbon tetrachloride", "Acetic acid"], "Vinegar is a dilute (5–8%) solution of acetic acid in water."],
    ["सिरके का ______ का व्यापारिक नाम है।", ["फार्मिक अम्ल", "फिनोल", "कार्बन टेट्राक्लोराइड", "सिरका अम्ल"], "सिरका जल में एसिटिक अम्ल का 5–8% तनु विलयन होता है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["Water in plants is transported by ______.", ["Xylem", "Phloem", "Epidermis", "Cambium"], "Xylem carries water and minerals from the roots upward; phloem carries food."],
    ["पौधों में जल का परिवहन ______ द्वारा किया जाता है।", ["जाइलम", "फ्लोएम", "एपिडर्मिस", "कैंबियम"], "जाइलम जल और खनिजों को जड़ों से ऊपर ले जाता है; फ्लोएम भोजन का परिवहन करता है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["During the process of respiration in human beings, the exchange of gases takes place in ______.", ["Alveoli", "Bronchiole", "Bronchi", "Pleura"], "Oxygen and carbon dioxide are exchanged across the thin walls of the alveoli in the lungs."],
    ["मनुष्य में श्वसन की प्रक्रिया के दौरान, गैसों का आदान-प्रदान ______ में होता है।", ["एल्वियोली", "ब्रोन्किओल", "ब्रांकाई", "फुफ्फुस"], "फेफड़ों की एल्वियोली की पतली दीवारों के आर-पार ऑक्सीजन और कार्बन डाइऑक्साइड का आदान-प्रदान होता है।"]),

  // ───────── Section 2: Reasoning ─────────
  q(2, "reasoning", "series", "M", 1,
    ["What is the value of X in the sequence 40, 20, 20, 30, 60, 150, X?", ["300", "450", "600", "250"], "Each term is multiplied by ×0.5, ×1, ×1.5, ×2, ×2.5, ×3 in turn: 150 × 3 = 450."],
    ["क्रम 40, 20, 20, 30, 60, 150, X में X का मान क्या है?", ["300", "450", "600", "250"], "क्रमशः ×0.5, ×1, ×1.5, ×2, ×2.5, ×3 से गुणा होता है: 150 × 3 = 450।"]),
  q(2, "reasoning", "coding-decoding", "M", 2,
    ["If in a certain code language 'FORMAL' is written as 'IRUJXI', how will 'BETTER' be written in that language?", ["EHQWBO", "EHWOBQ", "EHWQBO", "EHWQOB"], "The shifts are +3, +3, +3, −3, −3, −3. BETTER: B+3=E, E+3=H, T+3=W, T−3=Q, E−3=B, R−3=O → EHWQBO."],
    ["यदि एक निश्चित कूट भाषा में 'FORMAL' को 'IRUJXI' लिखा जाता है, तो उसी भाषा में 'BETTER' को कैसे लिखा जाएगा?", ["EHQWBO", "EHWOBQ", "EHWQBO", "EHWQOB"], "अक्षरों में क्रमशः +3, +3, +3, −3, −3, −3 का परिवर्तन है। BETTER: B+3=E, E+3=H, T+3=W, T−3=Q, E−3=B, R−3=O → EHWQBO।"]),
  q(2, "reasoning", "puzzles", "H", 2,
    [`${COLLEGE_EN} — In which of the colleges do three of them study?`, ["Z", "Y", "X", "None of these"], `${COLLEGE_SOL} College X has three students: O, N and Q.`],
    [`${COLLEGE_HI} — इनमें से किस कॉलेज में ये तीन पढ़ते हैं?`, ["Z", "Y", "X", "इनमें से कोई नहीं"], `${COLLEGE_SOL_HI} कॉलेज X में तीन छात्र O, N और Q हैं।`]),
  q(2, "reasoning", "puzzles", "H", 2,
    [`${COLLEGE_EN} — Which of the following pairs of students study medicine?`, ["N, Q", "Q, P", "Q, L", "O, L"], COLLEGE_SOL],
    [`${COLLEGE_HI} — निम्नलिखित में से छात्रों का कौन सा जोड़ा चिकित्सा का अध्ययन करता है?`, ["N, Q", "Q, P", "Q, L", "O, L"], COLLEGE_SOL_HI]),
  q(2, "reasoning", "puzzles", "H", 1,
    [`${COLLEGE_EN} — Apart from O, who studies mechanical engineering?`, ["L", "M", "Q", "None of these"], COLLEGE_SOL],
    [`${COLLEGE_HI} — O के अलावा, मैकेनिकल इंजीनियरिंग कौन पढ़ता है?`, ["L", "M", "Q", "इनमें से कोई नहीं"], COLLEGE_SOL_HI]),
  q(2, "reasoning", "analogy", "E", 2,
    ["Museum is related to curator in the same way as Prison is related to ______?", ["Manager", "Monitor", "Jailor", "Warden"], "A curator is in charge of a museum; a jailor is in charge of a prison."],
    ["संग्रहालय का संबंध क्यूरेटर से उसी प्रकार है जिस प्रकार कारागार का संबंध ______ से है?", ["प्रबंधक", "मॉनिटर", "जेलर", "वार्डन"], "क्यूरेटर संग्रहालय का प्रभारी होता है; जेलर कारागार का प्रभारी होता है।"]),
  q(2, "reasoning", "puzzles", "H", 2,
    [`${PROF_EN} — Who teaches Geology?`, ["Dr Natrajan", "Dr. Zia", "Dr. Davar", "Dr. Joshi"], PROF_SOL],
    [`${PROF_HI} — भूविज्ञान कौन पढ़ाता है?`, ["डॉ नटराजन", "डॉ ज़िया", "डॉ डावर", "डॉ जोशी"], PROF_SOL_HI]),
  q(2, "reasoning", "puzzles", "H", 0,
    [`${PROF_EN} — Dr. Zia is from which University?`, ["Gujarat", "Bombay", "Delhi", "Osmania"], PROF_SOL],
    [`${PROF_HI} — डॉ. ज़िया किस विश्वविद्यालय से हैं?`, ["गुजरात", "बॉम्बे", "दिल्ली", "उस्मानिया"], PROF_SOL_HI]),
  q(2, "reasoning", "puzzles", "H", 3,
    [`${PROF_EN} — Who teaches Botany?`, ["Dr. Zia", "Dr. Davar", "Dr. Joshi", "Dr. Natrajan"], PROF_SOL],
    [`${PROF_HI} — वनस्पति विज्ञान कौन पढ़ाता है?`, ["डॉ. ज़िया", "डॉ. डावर", "डॉ. जोशी", "डॉ. नटराजन"], PROF_SOL_HI]),
  q(2, "reasoning", "puzzles", "H", 1,
    [`${PROF_EN} — Who is from Osmania University?`, ["Dr. Natrajan", "Dr. Davar", "Dr. Joshi", "Dr. Zia"], PROF_SOL],
    [`${PROF_HI} — उस्मानिया विश्वविद्यालय से कौन है?`, ["डॉ नटराजन", "डॉ डावर", "डॉ जोशी", "डॉ. ज़िया"], PROF_SOL_HI]),
  q(2, "reasoning", "puzzles", "H", 3,
    [`${PROF_EN} — Which of the following combinations is correct?`, ["Dr. Zia – Delhi University", "Dr. Choudhary – Geology", "Dr. Davar – Bombay University", "Dr. Natrajan – Gujarat University"], PROF_SOL],
    [`${PROF_HI} — निम्नलिखित संयोजनों में से कौन सा सही है?`, ["डॉ. ज़िया – दिल्ली विश्वविद्यालय", "डॉ चौधरी – भूविज्ञान", "डॉ. डावर – बॉम्बे विश्वविद्यालय", "डॉ. नटराजन – गुजरात विश्वविद्यालय"], PROF_SOL_HI]),
  q(2, "reasoning", "coding-decoding", "M", 1,
    ["If in a certain language MYSTIFY is coded as NZTUJGZ, how is NEMESIS coded in that language?", ["MDLHRDR", "OFNFTJT", "ODNHTDR", "PGOKUGU"], "Every letter is moved one place forward: N→O, E→F, M→N, E→F, S→T, I→J, S→T: OFNFTJT."],
    ["यदि एक निश्चित भाषा में MYSTIFY को NZTUJGZ के रूप में कोडित किया जाता है, तो उस भाषा में NEMESIS को कैसे कोडित किया जाएगा?", ["MDLHRDR", "OFNFTJT", "ODNHTDR", "PGOKUGU"], "प्रत्येक अक्षर एक स्थान आगे खिसकता है: N→O, E→F, M→N, E→F, S→T, I→J, S→T: OFNFTJT।"]),
  q(2, "reasoning", "blood-relations", "M", 0,
    ["Pointing to a man, a woman said: \"His mother is the only daughter of my mother.\" How is the woman related to the man?", ["Mother", "Daughter", "Sister", "Grandmother"], "The only daughter of the woman's mother is the woman herself, so the man's mother is the woman — she is his mother."],
    ["एक पुरुष की ओर इशारा करते हुए, एक महिला ने कहा: \"उसकी माँ मेरी माँ की इकलौती बेटी है।\" महिला का पुरुष से क्या संबंध है?", ["माता", "बेटी", "बहन", "दादी"], "महिला की माँ की इकलौती बेटी स्वयं वह महिला है, इसलिए पुरुष की माँ वही महिला है।"]),
  q(2, "reasoning", "blood-relations", "H", 3,
    ["If M + N means M is the brother of N; M % N means M is the father of N and M × N means M is the sister of N. Which of the following means A is the uncle of C?", ["A % B × C", "B × C % A", "A + D % E × C", "A + F % G × C"], "A + F: A is the brother of F. F % G: F is the father of G. G × C: G is the sister of C. So F is also C's father, and A, his brother, is C's uncle."],
    ["यदि M + N का अर्थ M, N का भाई है; M % N का अर्थ N का पिता M है और M × N का अर्थ है N की बहन M है। निम्नलिखित में से किसका अर्थ है कि C का चाचा A है?", ["A % B × C", "B × C % A", "A + D % E × C", "A + F % G × C"], "A + F: A, F का भाई है। F % G: F, G का पिता है। G × C: G, C की बहन है। इसलिए F, C का भी पिता है और उसका भाई A, C का चाचा है।"]),

  // ───────── Section 3: Numerical Ability ─────────
  q(3, "quant", "number-system", "H", 3,
    ["How many times does the digit 6 appear while writing integers from 400 to 900?", ["201", "150", "170", "200"], "Units place: 10 per hundred × 5 hundreds (400–899) = 50. Tens place: also 50. Hundreds place: 600–699 gives 100. Total = 200 (900 has no 6)."],
    ["400 से 900 तक पूर्णांक लिखते समय अंक 6 कितनी बार आता है?", ["201", "150", "170", "200"], "इकाई स्थान: 5 सैकड़ों (400–899) में प्रत्येक में 10 = 50। दहाई स्थान: भी 50। सैकड़े का स्थान: 600–699 से 100। कुल = 200 (900 में 6 नहीं है)।"]),
  q(3, "quant", "percentage", "H", 0,
    ["A competitive examination was attended by male and female candidates. Out of the candidates who applied, 60% are female. 18% of the candidates have passed the examination. 22.22% of the candidates who cleared are male. What percentage of female candidates has not passed the exam?", ["76.67%", "33.33%", "40%", "Cannot be determined"], "Take 100 candidates: 60 female, 40 male. Passed = 18, of which males = 22.22% of 18 = 4, so female passed = 14. Female not passed = 60 − 14 = 46, i.e. 46/60 = 76.67%."],
    ["एक प्रतियोगी परीक्षा में पुरुष और महिला उम्मीदवारों ने भाग लिया। आवेदन करने वाले उम्मीदवारों में 60% महिलाएं हैं। 18% उम्मीदवारों ने परीक्षा उत्तीर्ण की है। उत्तीर्ण होने वाले उम्मीदवारों में 22.22% पुरुष हैं। कितने प्रतिशत महिला उम्मीदवारों ने परीक्षा उत्तीर्ण नहीं की है?", ["76.67%", "33.33%", "40%", "निर्धारित नहीं किया जा सकता है"], "कुल 100 उम्मीदवार लें: 60 महिला, 40 पुरुष। उत्तीर्ण = 18, जिनमें पुरुष = 18 का 22.22% = 4, अतः महिला उत्तीर्ण = 14। अनुत्तीर्ण महिला = 60 − 14 = 46, यानी 46/60 = 76.67%।"]),
  q(3, "quant", "percentage", "M", 2,
    ["Ramesh buys 20 kg of wheat every month for the family. The cost of wheat is increased from ₹14 per kg to ₹16 per kg. If Ramesh does not want to increase his expenditure on wheat, what quantity of wheat should he buy after the price increase?", ["12.5 kg", "16 kg", "17.5 kg", "16.5 kg"], "Expenditure = 20 × 14 = ₹280. New quantity = 280 / 16 = 17.5 kg."],
    ["रमेश परिवार के लिए हर महीने 20 किलो गेहूं खरीदता है। गेहूं की कीमत 14 रुपये प्रति किलो से बढ़ाकर 16 रुपये प्रति किलो कर दी गई है। यदि रमेश गेहूं पर अपना खर्च नहीं बढ़ाना चाहता है, तो मूल्य वृद्धि के बाद उसे कितनी मात्रा में गेहूं खरीदना चाहिए?", ["12.5 kg", "16 kg", "17.5 kg", "16.5 kg"], "खर्च = 20 × 14 = ₹280। नई मात्रा = 280 / 16 = 17.5 kg।"]),
  q(3, "quant", "speed-distance", "M", 2,
    ["A train of 150 m length travelling at 90 kmph can cross a tunnel of length 250 m in:", ["12 seconds", "15 seconds", "16 seconds", "18 seconds"], "Distance = 150 + 250 = 400 m. Speed = 90 × 5/18 = 25 m/s. Time = 400 / 25 = 16 s."],
    ["150 मीटर की लंबाई वाली एक ट्रेन 90 किमी प्रति घंटे की गति से यात्रा करते हुए 250 मीटर लंबाई की सुरंग को पार कर सकती है:", ["12 सेकंड में", "15 सेकंड में", "16 सेकंड में", "18 सेकंड में"], "दूरी = 150 + 250 = 400 मी.। चाल = 90 × 5/18 = 25 मी./से.। समय = 400 / 25 = 16 सेकंड।"]),
  q(3, "quant", "mensuration", "M", 2,
    ["What is the length of the longest pole that can be placed in a room 24 m long, 16 m wide and 18 m high?", ["24 m", "28 m", "34 m", "42 m"], "The longest pole is the space diagonal: √(24² + 16² + 18²) = √(576 + 256 + 324) = √1156 = 34 m."],
    ["24 मीटर लंबे, 16 मीटर चौड़े और 18 मीटर ऊंचे कमरे में रखे जा सकने वाले सबसे लंबे खंभे की लंबाई क्या है?", ["24 मीटर", "28 मीटर", "34 मीटर", "42 मीटर"], "सबसे लंबा खंभा कमरे का विकर्ण होता है: √(24² + 16² + 18²) = √(576 + 256 + 324) = √1156 = 34 मीटर।"]),
  q(3, "quant", "mensuration", "M", 2,
    ["The surface area of two spherical balls is in the ratio 4 : 9. Find the radius of the bigger ball if the radius of the smaller ball is 4 cm.", ["5 cm", "7.5 cm", "6 cm", "9 cm"], "Surface area ∝ r², so r₁ : r₂ = 2 : 3. Bigger radius = 4 × 3/2 = 6 cm."],
    ["दो गोलाकार गेंदों का सतही क्षेत्रफल 4:9 के अनुपात में है। बड़ी गेंद की त्रिज्या (अर्धव्यास) ज्ञात कीजिए यदि छोटी गेंद की त्रिज्या 4 सेमी है।", ["5 सेमी", "7.5 सेमी", "6 सेमी", "9 सेमी"], "सतही क्षेत्रफल ∝ r², इसलिए r₁ : r₂ = 2 : 3। बड़ी त्रिज्या = 4 × 3/2 = 6 सेमी।"]),
  q(3, "quant", "percentage", "M", 2,
    ["A fish tank is in the shape of a cuboid. Shyam increased the length, width and depth of the tank by 10%, 15% and 20% respectively. By what percent has the tank's volume increased?", ["46.2%", "33.1%", "51.8%", "62.0%"], "New volume = 1.10 × 1.15 × 1.20 = 1.518 times the old volume, an increase of 51.8%."],
    ["एक मछली टैंक घनाभ के आकार का है। श्याम ने टैंक की लंबाई, चौड़ाई और गहराई में क्रमशः 10%, 15% और 20% की वृद्धि की। टैंक के आयतन में कितने प्रतिशत की वृद्धि हुई है?", ["46.2%", "33.1%", "51.8%", "62.0%"], "नया आयतन = 1.10 × 1.15 × 1.20 = 1.518 गुना, यानी 51.8% की वृद्धि।"]),
  q(3, "quant", "time-work", "M", 3,
    ["James can do a piece of work in 50 days. Peter can do the same piece of work in 40 days. How long will they take to complete 45% of the work when working together?", ["5 days", "9 days", "7 days", "10 days"], "Together they do 1/50 + 1/40 = 9/200 of the work per day. 45% = 9/20, so time = (9/20) ÷ (9/200) = 10 days."],
    ["जेम्स एक कार्य को 50 दिनों में कर सकता है। पीटर उसी कार्य को 40 दिनों में कर सकता है। एक साथ काम करते हुए उन्हें 45% काम पूरा करने में कितना समय लगेगा?", ["5 दिन", "9 दिन", "7 दिन", "10 दिन"], "साथ मिलकर वे प्रतिदिन 1/50 + 1/40 = 9/200 कार्य करते हैं। 45% = 9/20, अतः समय = (9/20) ÷ (9/200) = 10 दिन।"]),

  // ───────── Section 4: Hindi & English ─────────
  q(4, "english", "idioms", "M", 2,
    ["Choose the most appropriate meaning of the idiom: Forty winks", ["Sleep disorders", "Eye sight related issue", "A short sleep during the day", "Long sleeping hours"], "'Forty winks' means a short nap, usually in the daytime."],
    ["मुहावरे का सबसे उपयुक्त अर्थ चुनिए: Forty winks", ["Sleep disorders", "Eye sight related issue", "A short sleep during the day", "Long sleeping hours"], "'Forty winks' का अर्थ दिन में ली गई छोटी झपकी है।"]),
  q(4, "english", "idioms", "M", 1,
    ["Choose the most appropriate meaning of the idiom: Raise some hackles", ["To do a great task", "To annoy", "To make someone happy", "To empathise with others"], "To 'raise someone's hackles' is to make them angry or annoyed."],
    ["मुहावरे का सबसे उपयुक्त अर्थ चुनिए: Raise some hackles", ["To do a great task", "To annoy", "To make someone happy", "To empathise with others"], "'Raise someone's hackles' का अर्थ किसी को नाराज़ या क्रोधित करना है।"]),
  q(4, "english", "idioms", "E", 0,
    ["Choose the most appropriate meaning of the idiom: Throw in the towel", ["To give up", "To resist", "To have a bath", "To fight"], "'Throw in the towel' means to admit defeat and give up (from boxing)."],
    ["मुहावरे का सबसे उपयुक्त अर्थ चुनिए: Throw in the towel", ["To give up", "To resist", "To have a bath", "To fight"], "'Throw in the towel' का अर्थ हार मानकर हार स्वीकार कर लेना है (मुक्केबाज़ी से)।"]),
  q(4, "english", "synonyms-antonyms", "M", 3,
    ["Choose the most appropriate synonym of the word: Shocked", ["Pacified", "Fascinated", "Impeded", "Appalled"], "Appalled means greatly shocked or dismayed."],
    ["शब्द का सबसे उपयुक्त पर्यायवाची चुनिए: Shocked", ["Pacified", "Fascinated", "Impeded", "Appalled"], "Appalled का अर्थ बुरी तरह स्तब्ध या भयभीत होना है।"]),
  q(4, "english", "synonyms-antonyms", "H", 0,
    ["Choose the most appropriate synonym of the word: Didactic", ["Enlightening", "Frightening", "Disgusting", "Sensational"], "Didactic means intended to teach or instruct; 'enlightening' is the closest."],
    ["शब्द का सबसे उपयुक्त पर्यायवाची चुनिए: Didactic", ["Enlightening", "Frightening", "Disgusting", "Sensational"], "Didactic का अर्थ शिक्षा देने के उद्देश्य वाला है; 'enlightening' सबसे निकट है।"]),
  q(4, "english", "synonyms-antonyms", "M", 2,
    ["Choose the most appropriate synonym of the word: Spurious", ["Honest", "Spoiled", "Counterfeit", "Genuine"], "Spurious means fake or not genuine, like counterfeit."],
    ["शब्द का सबसे उपयुक्त पर्यायवाची चुनिए: Spurious", ["Honest", "Spoiled", "Counterfeit", "Genuine"], "Spurious का अर्थ नकली या अप्रामाणिक है, जैसे counterfeit।"]),
  q(4, "english", "synonyms-antonyms", "M", 3,
    ["Choose the most appropriate antonym of the word: Pandemonium", ["Noisy", "Confusion", "Protest", "Peace"], "Pandemonium means wild disorder and uproar; its opposite is peace."],
    ["शब्द का सबसे उपयुक्त विलोम चुनिए: Pandemonium", ["Noisy", "Confusion", "Protest", "Peace"], "Pandemonium का अर्थ भारी अव्यवस्था और शोर है; विलोम 'peace' है।"]),
  q(4, "english", "synonyms-antonyms", "M", 0,
    ["Choose the most appropriate antonym of the word: Modesty", ["Grandeur", "Sobriety", "Propriety", "Fairness"], "Modesty is humility and lack of show; the opposite among the options is grandeur (pomp, show)."],
    ["शब्द का सबसे उपयुक्त विलोम चुनिए: Modesty", ["Grandeur", "Sobriety", "Propriety", "Fairness"], "Modesty का अर्थ विनम्रता और दिखावे का अभाव है; विकल्पों में विलोम grandeur (ठाट-बाट, दिखावा) है।"]),
  q(4, "english", "synonyms-antonyms", "E", 1,
    ["Choose the most appropriate antonym of the word: Concise", ["Brief", "Lengthy", "Abridged", "Laconic"], "Concise means brief and to the point; its opposite is lengthy."],
    ["शब्द का सबसे उपयुक्त विलोम चुनिए: Concise", ["Brief", "Lengthy", "Abridged", "Laconic"], "Concise का अर्थ संक्षिप्त और सटीक है; विलोम lengthy (लंबा) है।"]),
  q(4, "english", "grammar", "M", 2,
    ["Fill in the blank with the most appropriate word: We must not shy ______ taking risks in life.", ["upon", "with", "away from", "to"], "'Shy away from' means to avoid something out of fear or nervousness."],
    ["रिक्त स्थान को सबसे उपयुक्त शब्द से भरिए: We must not shy ______ taking risks in life.", ["upon", "with", "away from", "to"], "'Shy away from' का अर्थ भय या घबराहट के कारण किसी चीज़ से बचना है।"]),
  q(4, "english", "grammar", "E", 3,
    ["Fill in the blank with the most appropriate word: Due to her illness, she could not finish the work ____ time.", ["to", "by", "upon", "on"], "'On time' means punctually, within the scheduled time."],
    ["रिक्त स्थान को सबसे उपयुक्त शब्द से भरिए: Due to her illness, she could not finish the work ____ time.", ["to", "by", "upon", "on"], "'On time' का अर्थ समय पर, निर्धारित समय के भीतर है।"]),
  q(4, "english", "grammar", "M", 1,
    ["Fill in the blank with the most appropriate word: The police was directed to ______ his business dealings.", ["look on", "look into", "look up", "look to"], "'Look into' means to investigate."],
    ["रिक्त स्थान को सबसे उपयुक्त शब्द से भरिए: The police was directed to ______ his business dealings.", ["look on", "look into", "look up", "look to"], "'Look into' का अर्थ जाँच करना है।"]),
  q(4, "english", "grammar", "M", 1,
    ["Fill in the blank with the most appropriate word: Despite the injuries, Neeraj managed to ______ the gold medal in the tournament.", ["pull out", "pull off", "pull in", "put in"], "'Pull off' means to succeed in achieving something difficult."],
    ["रिक्त स्थान को सबसे उपयुक्त शब्द से भरिए: Despite the injuries, Neeraj managed to ______ the gold medal in the tournament.", ["pull out", "pull off", "pull in", "put in"], "'Pull off' का अर्थ किसी कठिन काम में सफल होना है।"]),
  q(4, "english", "voice-speech", "H", 1,
    ["Select the option which best expresses the sentence in active/passive voice: I remember my sister taking me to the museum.", ["I remember taken to the museum by my sister.", "I remember being taken to the museum by my sister.", "I remember myself being taken to the museum by my sister.", "I remember I was taken to the museum by my sister."], "The gerund phrase 'my sister taking me' becomes 'being taken … by my sister' in the passive."],
    ["सक्रिय/निष्क्रिय वाच्य में वाक्य को सर्वोत्तम ढंग से व्यक्त करने वाला विकल्प चुनिए: I remember my sister taking me to the museum.", ["I remember taken to the museum by my sister.", "I remember being taken to the museum by my sister.", "I remember myself being taken to the museum by my sister.", "I remember I was taken to the museum by my sister."], "gerund वाक्यांश 'my sister taking me' निष्क्रिय में 'being taken … by my sister' बन जाता है।"]),
  q(4, "english", "voice-speech", "H", 3,
    ["Select the appropriate option to change the sentence from direct to indirect speech: I asked my sister, 'Have you returned the mobile phone to your friend?'", ["I said to my sister, 'Have you return the mobile phone to your friend?'", "I asked my sister, 'Did you return the mobile phone to your friend?'", "I said to my sister, 'Have you returned the mobile phone to my friend?'", "I asked my sister if she had returned the mobile phone to her friend."], "A direct yes/no question becomes indirect with 'if', the present perfect becomes past perfect, and 'you/your' become 'she/her': 'I asked my sister if she had returned the mobile phone to her friend.'"],
    ["Direct speech को indirect speech में बदलने के लिए उपयुक्त विकल्प चुनिए: I asked my sister, 'Have you returned the mobile phone to your friend?'", ["I said to my sister, 'Have you return the mobile phone to your friend?'", "I asked my sister, 'Did you return the mobile phone to your friend?'", "I said to my sister, 'Have you returned the mobile phone to my friend?'", "I asked my sister if she had returned the mobile phone to her friend."], "प्रत्यक्ष हाँ/ना प्रश्न अप्रत्यक्ष में 'if' से जुड़ता है, present perfect, past perfect बनता है और 'you/your', 'she/her' हो जाते हैं: 'I asked my sister if she had returned the mobile phone to her friend.'"]),
  q(4, "english", "voice-speech", "H", 1,
    ["Select the appropriate option to change the sentence from direct to indirect speech: 'Where will you be tomorrow?' she said, 'in case I have to call you?'", ["She enquired about his whereabouts the next day in case she would have to call him.", "She asked where he would be the next day in case she had to call him.", "She asked him where he will be the next day in case she had to call him.", "She said to him where he would be tomorrow in case she would have to call him."], "'Will' becomes 'would', 'tomorrow' becomes 'the next day', pronouns change, and the question takes statement word order."],
    ["Direct speech को indirect speech में बदलने के लिए उपयुक्त विकल्प चुनिए: 'Where will you be tomorrow?' she said, 'in case I have to call you?'", ["She enquired about his whereabouts the next day in case she would have to call him.", "She asked where he would be the next day in case she had to call him.", "She asked him where he will be the next day in case she had to call him.", "She said to him where he would be tomorrow in case she would have to call him."], "'Will', 'would' बनता है, 'tomorrow', 'the next day' हो जाता है, सर्वनाम बदलते हैं और प्रश्न कथन के क्रम में आ जाता है।"]),
  q(4, "hindi", "ek-shabd", "M", 2,
    ["The one word for 'one who is difficult to bring under control' is:", ["स्वावलंबी (self-reliant)", "दुर्लभ (rare)", "दुर्धर्ष (invincible)", "होनहार (promising)"], "'दुर्धर्ष' describes one who is hard to subdue or overpower."],
    ["जिसे वशवर्ती बनाना कठिन हो:", ["स्वावलंबी", "दुर्लभ", "दुर्धर्ष", "होनहार"], "'दुर्धर्ष' वह है जिसे वश में करना या दबाना कठिन हो।"]),
  q(4, "hindi", "ek-shabd", "M", 2,
    ["The one word for 'one who brings a charge (complaint) against someone' is:", ["अभियन्ता (engineer)", "प्रतिवादी (defendant)", "वादी (plaintiff)", "याचक (beggar)"], "The party who files the case or complaint is the 'वादी' (plaintiff)."],
    ["जो किसी पर अभियोग लाता हो:", ["अभियन्ता", "प्रतिवादी", "वादी", "याचक"], "मुकदमा या शिकायत दायर करने वाला पक्ष 'वादी' कहलाता है।"]),
  q(4, "hindi", "ek-shabd", "M", 3,
    ["The one word for 'the desire to swim' is:", ["पिपासा (thirst)", "बुभुक्षा (hunger)", "जिगीषा (desire to win)", "तितीर्षा (desire to cross/swim)"], "'तितीर्षा' means the desire to cross (swim) across."],
    ["तैरने की इच्छा:", ["पिपासा", "बुभुक्षा", "जिगीषा", "तितीर्षा"], "'तितीर्षा' का अर्थ तैरकर पार करने की इच्छा है।"]),
  q(4, "hindi", "ek-shabd", "M", 2,
    ["The one word for 'the time between evening and night' is:", ["मार्तण्ड", "पूर्वाह्न", "गोधूलि", "ऊष्मा"], "'गोधूलि' is the evening twilight, when cattle return home raising dust."],
    ["साँझ और रात के बीच का समय:", ["मार्तण्ड", "पूर्वाह्न", "गोधूलि", "ऊष्मा"], "'गोधूलि' सायंकालीन वह समय है जब गायें धूल उड़ाती लौटती हैं।"]),
  q(4, "hindi", "ek-shabd", "M", 1,
    ["The one word for 'that which cannot be divided' is:", ["अखण्डित", "अविभाज्य", "अविभक्त", "अखण्ड"], "'अविभाज्य' means that which cannot be divided."],
    ["जिसका विभाजन न किया जा सके:", ["अखण्डित", "अविभाज्य", "अविभक्त", "अखण्ड"], "'अविभाज्य' का अर्थ है जिसका विभाजन न हो सके।"]),
  q(4, "hindi", "ek-shabd", "M", 0,
    ["The one word for 'a place that is difficult to reach' is:", ["दुर्गम", "अगम", "सुगम", "अगेय"], "'दुर्गम' means hard to reach or traverse."],
    ["जहाँ पहुँचना कठिन हो:", ["दुर्गम", "अगम", "सुगम", "अगेय"], "'दुर्गम' का अर्थ है जहाँ पहुँचना कठिन हो।"]),
  q(4, "hindi", "ek-shabd", "M", 3,
    ["The one word for 'a request made humbly but with insistence' is:", ["अनुरोध", "विनम्रता", "अनुबोध", "आग्रह"], "'आग्रह' is an insistent request made politely. अनुरोध is a plain request."],
    ["विनयपूर्वक किया गया हठ है:", ["अनुरोध", "विनम्रता", "अनुबोध", "आग्रह"], "'आग्रह' विनयपूर्वक किया गया हठ है। अनुरोध साधारण प्रार्थना होती है।"]),
  q(4, "hindi", "ek-shabd", "M", 3,
    ["The one word for 'a thing that attracts the mind' is:", ["सुन्दर", "चारू", "रुचिर", "मनोहर"], "'मनोहर' means that which captivates the mind."],
    ["'मन को लुभाने वाली वस्तु'", ["सुन्दर", "चारू", "रुचिर", "मनोहर"], "'मनोहर' का अर्थ मन को हर लेने (लुभाने) वाला है।"]),
  q(4, "hindi", "ek-shabd", "M", 0,
    ["The one word for 'that which has been experienced' is:", ["अनुभूत", "अद्भूत", "आचार", "विचार"], "'अनुभूत' means experienced or felt."],
    ["''जिसका अनुभव किया गया हो''", ["अनुभूत", "अद्भूत", "आचार", "विचार"], "'अनुभूत' का अर्थ जिसका अनुभव किया गया हो है।"]),
  q(4, "hindi", "ek-shabd", "M", 1,
    ["The one word for 'that which happens once in three months' is:", ["तिगुना", "त्रैमासिक", "द्विमासिक", "वार्षिक"], "'त्रैमासिक' means quarterly — once every three months."],
    ["'तीन माह में एक बार होने वाला':", ["तिगुना", "त्रैमासिक", "द्विमासिक", "वार्षिक"], "'त्रैमासिक' का अर्थ तीन माह में एक बार होने वाला है।"]),
  q(4, "hindi", "vyakaran", "M", 2,
    ["Language can be used in two forms — one is the ordinary form, in which people ______ in daily life, and the other is for literary writing, in which mostly ______ language is used.", ["work, creativity", "exchange, poetic", "usage, ornamental", "operation, emotional"], "Everyday language is used for 'व्यवहार' (dealing/usage), while literary writing mostly uses an 'आलंकारिक' (ornamental) language."],
    ["भाषा का प्रयोग दो रूपों में किया जा सकता है- एक तो सामान्य जिससे लोक में ________ होता है तथा दूसरा साहित्य रचना के लिए, जिसमें प्रायः ________ भाषा का प्रयोग किया जाता है।", ["कार्य, रचनात्मकता", "विनिमय, काव्यात्मक", "व्यवहार, आलंकारिक", "संचालन, भावात्मक"], "सामान्य भाषा से लोक में 'व्यवहार' होता है, जबकि साहित्य रचना में प्रायः 'आलंकारिक' भाषा का प्रयोग किया जाता है।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["What is the meaning of the idiom 'चादर के बाहर पैर पसारना'?", ["To ask for forgiveness", "To give advice", "To spend beyond one's means", "To expose someone's secrets"], "Stretching one's feet beyond the sheet means spending beyond one's capacity."],
    ["'चादर के बाहर पैर पसारना' मुहावरे का अर्थ है:", ["क्षमा माँगना", "परामर्श देना", "क्षमता से अधिक व्यय करना", "पोल खोलना"], "चादर से बाहर पैर फैलाने का अर्थ अपनी सामर्थ्य से अधिक खर्च करना है।"]),
  q(4, "hindi", "shabdavali", "H", 2,
    ["Internet science and technology is one of the greatest gifts, but the ______ is that as the internet makes our lives easier and faster, the ______ of the dangers related to it is also growing.", ["controversy, definition", "reality, number", "irony, apprehension", "distortion, situation"], "'विडम्बना' (irony) and 'आशंका' (apprehension) fit the sentence: a great gift, yet fears about its dangers rise."],
    ["इंटरनेट विज्ञान एवं प्रौद्योगिकी की श्रेष्ठतम सौगातों में से एक है, लेकिन ______ यह है कि जैसे-जैसे इंटरनेट हमारे जीवन को सुगम व गतिशील बना रहा है, वैसे-वैसे इससे जुड़े खतरों की ______ भी बढ़ती जा रही है।", ["विवाद, परिभाषा", "यथार्थ, संख्या", "विडम्बना, आशंका", "विकृति, स्थिति"], "'विडम्बना' और 'आशंका' वाक्य में सही बैठते हैं: एक श्रेष्ठ सौगात होते हुए भी उससे जुड़े खतरों की आशंका बढ़ रही है।"]),
  q(4, "hindi", "muhavare", "M", 1,
    ["What is the meaning of the idiom 'आकाश से बातें करना'?", ["To break limbs", "To be very tall", "To be frightened", "None of these"], "'आकाश से बातें करना' means to be extremely tall or high."],
    ["'आकाश से बातें करना' मुहावरे का अर्थ है:", ["अंग भंग करना", "बहुत ऊंचा होना", "भयभीत होना", "इनमें से कोई नहीं"], "'आकाश से बातें करना' का अर्थ बहुत ऊँचा होना है।"]),
  q(4, "hindi", "paryay-vilom", "M", 2,
    ["Which of these words is NOT a synonym of 'कान्ति' (radiance)?", ["द्युति", "आलोक", "समृद्धि", "आभा"], "द्युति, आलोक and आभा all mean radiance or lustre; 'समृद्धि' means prosperity."],
    ["निम्नलिखित शब्दों में से कौन सा कान्ति का पर्यायवाची नहीं है:", ["द्युति", "आलोक", "समृद्धि", "आभा"], "द्युति, आलोक और आभा तेज या चमक के अर्थ में हैं; 'समृद्धि' का अर्थ संपन्नता है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Which of these words is NOT a synonym of 'अग्नि' (fire)?", ["दहन", "वैश्वानर", "अनल", "जलज"], "दहन, वैश्वानर and अनल are names for fire; 'जलज' means lotus (born in water)."],
    ["निम्नलिखित शब्दों में से कौन सा अग्नि का पर्यायवाची नहीं है:", ["दहन", "वैश्वानर", "अनल", "जलज"], "दहन, वैश्वानर और अनल अग्नि के नाम हैं; 'जलज' का अर्थ कमल (जल में उत्पन्न) है।"]),
];
