// HPAS Free Mock 1 — 30 questions (10 Himachal GK, 20 General Studies).

import { q, type PatwariQuestion } from "../patwari/types";

export const mock1: PatwariQuestion[] = [
  // ───────── Section 0: Himachal GK (10) ─────────
  q(0, "hp-gk", "history", "E", 1,
    ["Which city was declared the second capital of Himachal Pradesh in 2017?", ["Mandi", "Dharamshala", "Hamirpur", "Solan"], "Dharamshala in Kangra district was declared the second (winter) capital of Himachal Pradesh in January 2017; Shimla remains the capital."],
    ["वर्ष 2017 में हिमाचल प्रदेश की दूसरी राजधानी किस शहर को घोषित किया गया?", ["मंडी", "धर्मशाला", "हमीरपुर", "सोलन"], "कांगड़ा जिले के धर्मशाला को जनवरी 2017 में हिमाचल प्रदेश की दूसरी (शीतकालीन) राजधानी घोषित किया गया; शिमला मुख्य राजधानी बनी रही।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["Shimla became the summer capital of British India in the year:", ["1830", "1864", "1902", "1911"], "The British made Shimla the summer capital of India in 1864, during the time of Viceroy John Lawrence."],
    ["शिमला ब्रिटिश भारत की ग्रीष्मकालीन राजधानी किस वर्ष बना?", ["1830", "1864", "1902", "1911"], "अंग्रेज़ों ने वायसराय जॉन लॉरेंस के समय 1864 में शिमला को भारत की ग्रीष्मकालीन राजधानी बनाया।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["The Kunzum Pass connects which two valleys?", ["Kullu and Lahaul", "Lahaul and Spiti", "Kinnaur and Spiti", "Chamba and Lahaul"], "The Kunzum Pass (about 4,550 m) links the Lahaul and Spiti valleys. The Rohtang Pass links Kullu and Lahaul."],
    ["कुंजुम दर्रा किन दो घाटियों को जोड़ता है?", ["कुल्लू और लाहौल", "लाहौल और स्पीति", "किन्नौर और स्पीति", "चंबा और लाहौल"], "कुंजुम दर्रा (लगभग 4,550 मीटर) लाहौल और स्पीति घाटियों को जोड़ता है। रोहतांग दर्रा कुल्लू और लाहौल को जोड़ता है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["The ancient name of the river Beas was:", ["Shatadru", "Vipasha", "Iravati", "Asikni"], "The Beas was called Vipasha (Vipasa). Shatadru is the Sutlej, Iravati the Ravi and Asikni the Chenab."],
    ["ब्यास नदी का प्राचीन नाम क्या था?", ["शतद्रु", "विपाशा", "इरावती", "आसिकनी"], "ब्यास को विपाशा (विपासा) कहा जाता था। शतद्रु सतलुज का, इरावती रावी का और आसिकनी चिनाब का प्राचीन नाम है।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["Which is the highest peak located within Himachal Pradesh?", ["Shilla", "Reo Purgyil", "Manirang", "Deo Tibba"], "Reo Purgyil (about 6,816 m) in Kinnaur district is the highest peak of Himachal Pradesh."],
    ["हिमाचल प्रदेश के भीतर स्थित सबसे ऊँची चोटी कौन-सी है?", ["शिल्ला", "रियो पुर्गिल", "मनिरंग", "देव टिब्बा"], "किन्नौर जिले की रियो पुर्गिल (लगभग 6,816 मीटर) हिमाचल प्रदेश की सबसे ऊँची चोटी है।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["The Pin Valley National Park is located in which district?", ["Kullu", "Kinnaur", "Lahaul & Spiti", "Chamba"], "The Pin Valley National Park, a cold desert habitat of the snow leopard and ibex, lies in the Spiti part of Lahaul & Spiti district."],
    ["पिन वैली नेशनल पार्क किस जिले में स्थित है?", ["कुल्लू", "किन्नौर", "लाहौल-स्पीति", "चंबा"], "पिन वैली नेशनल पार्क, जो हिम तेंदुए और आइबेक्स का ठंडा मरुस्थलीय आवास है, लाहौल-स्पीति जिले के स्पीति क्षेत्र में स्थित है।"]),
  q(0, "hp-gk", "history", "M", 1,
    ["The Kalka–Shimla railway was inscribed as a UNESCO World Heritage Site in:", ["2003", "2008", "2014", "2019"], "The Kalka–Shimla Railway was added to the UNESCO World Heritage list in 2008 as an extension of the Mountain Railways of India."],
    ["कालका–शिमला रेलवे को यूनेस्को विश्व धरोहर स्थल में कब शामिल किया गया?", ["2003", "2008", "2014", "2019"], "कालका–शिमला रेलवे को 2008 में भारत की पर्वतीय रेलवे के विस्तार के रूप में यूनेस्को विश्व धरोहर सूची में शामिल किया गया।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["Which district of Himachal Pradesh has the highest literacy rate (Census 2011)?", ["Una", "Hamirpur", "Kangra", "Bilaspur"], "Hamirpur has the highest literacy rate in Himachal Pradesh (about 89%) according to Census 2011."],
    ["जनगणना 2011 के अनुसार हिमाचल प्रदेश के किस जिले की साक्षरता दर सबसे अधिक है?", ["ऊना", "हमीरपुर", "कांगड़ा", "बिलासपुर"], "जनगणना 2011 के अनुसार हमीरपुर की साक्षरता दर (लगभग 89%) हिमाचल प्रदेश में सबसे अधिक है।"]),
  q(0, "hp-gk", "geography", "E", 1,
    ["What is the state animal of Himachal Pradesh?", ["Musk deer", "Snow leopard", "Himalayan tahr", "Black bear"], "The snow leopard is the state animal of Himachal Pradesh."],
    ["हिमाचल प्रदेश का राज्य पशु कौन-सा है?", ["कस्तूरी मृग", "हिम तेंदुआ", "हिमालयन थार", "काला भालू"], "हिम तेंदुआ (स्नो लेपर्ड) हिमाचल प्रदेश का राज्य पशु है।"]),
  q(0, "hp-gk", "culture-festivals", "E", 1,
    ["The Manimahesh Yatra is held every year in which district?", ["Kullu", "Chamba", "Mandi", "Sirmaur"], "The Manimahesh Yatra to Manimahesh Lake, in the Bharmour region, takes place in Chamba district around Janmashtami and Radhashtami."],
    ["मणिमहेश यात्रा प्रतिवर्ष किस जिले में होती है?", ["कुल्लू", "चंबा", "मंडी", "सिरमौर"], "भरमौर क्षेत्र की मणिमहेश झील की मणिमहेश यात्रा जन्माष्टमी और राधाष्टमी के आसपास चंबा जिले में होती है।"]),

  // ───────── Section 1: General Studies (20) ─────────
  q(1, "general-studies", "indian-history", "E", 0,
    ["The Battle of Plassey was fought in the year:", ["1757", "1764", "1761", "1857"], "The Battle of Plassey was fought on 23 June 1757 between Robert Clive and Siraj-ud-Daulah, the Nawab of Bengal."],
    ["प्लासी का युद्ध किस वर्ष लड़ा गया?", ["1757", "1764", "1761", "1857"], "प्लासी का युद्ध 23 जून 1757 को रॉबर्ट क्लाइव और बंगाल के नवाब सिराजुद्दौला के बीच लड़ा गया।"]),
  q(1, "general-studies", "indian-history", "E", 1,
    ["Who founded the Mauryan Empire?", ["Bindusara", "Chandragupta Maurya", "Ashoka", "Samudragupta"], "Chandragupta Maurya founded the Mauryan Empire around 321 BC with the help of Chanakya (Kautilya)."],
    ["मौर्य साम्राज्य की स्थापना किसने की?", ["बिंदुसार", "चंद्रगुप्त मौर्य", "अशोक", "समुद्रगुप्त"], "चंद्रगुप्त मौर्य ने चाणक्य (कौटिल्य) की सहायता से लगभग 321 ई.पू. में मौर्य साम्राज्य की स्थापना की।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Gandhiji withdrew the Non-Cooperation Movement after which incident?", ["Jallianwala Bagh massacre", "Kakori conspiracy", "Chauri Chaura incident", "Bardoli Satyagraha"], "After a mob burnt a police station at Chauri Chaura (Uttar Pradesh) in February 1922, Gandhiji called off the Non-Cooperation Movement."],
    ["गांधीजी ने किस घटना के बाद असहयोग आंदोलन वापस ले लिया?", ["जलियाँवाला बाग हत्याकांड", "काकोरी कांड", "चौरी-चौरा कांड", "बारदोली सत्याग्रह"], "फरवरी 1922 में चौरी-चौरा (उत्तर प्रदेश) में भीड़ द्वारा थाना जलाए जाने के बाद गांधीजी ने असहयोग आंदोलन वापस ले लिया।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["The Permanent Settlement of Bengal was introduced in 1793 by:", ["Lord Cornwallis", "Lord Wellesley", "Warren Hastings", "Lord Dalhousie"], "Lord Cornwallis introduced the Permanent Settlement in 1793, fixing the land revenue permanently with the zamindars."],
    ["1793 में बंगाल में स्थायी बंदोबस्त किसने लागू किया?", ["लॉर्ड कॉर्नवालिस", "लॉर्ड वेलेजली", "वारेन हेस्टिंग्स", "लॉर्ड डलहौज़ी"], "लॉर्ड कॉर्नवालिस ने 1793 में स्थायी बंदोबस्त लागू किया, जिसमें ज़मींदारों के साथ भू-राजस्व स्थायी रूप से तय कर दिया गया।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["The Harappan site of Dholavira is located in which present-day Indian state?", ["Rajasthan", "Haryana", "Gujarat", "Punjab"], "Dholavira lies in the Kutch district of Gujarat and became a UNESCO World Heritage Site in 2021."],
    ["हड़प्पा स्थल धोलावीरा वर्तमान भारत के किस राज्य में स्थित है?", ["राजस्थान", "हरियाणा", "गुजरात", "पंजाब"], "धोलावीरा गुजरात के कच्छ जिले में स्थित है और 2021 में यूनेस्को विश्व धरोहर स्थल बना।"]),

  q(1, "general-studies", "indian-polity", "E", 1,
    ["Article 21 of the Constitution of India guarantees:", ["Equality before law", "Protection of life and personal liberty", "Freedom of speech", "Right to constitutional remedies"], "Article 21 protects life and personal liberty; no person can be deprived of them except by procedure established by law."],
    ["भारतीय संविधान का अनुच्छेद 21 किसकी गारंटी देता है?", ["विधि के समक्ष समानता", "प्राण और दैहिक स्वतंत्रता का संरक्षण", "वाक्-स्वातंत्र्य", "संवैधानिक उपचारों का अधिकार"], "अनुच्छेद 21 प्राण और दैहिक स्वतंत्रता की रक्षा करता है; विधि द्वारा स्थापित प्रक्रिया के बिना इन्हें छीना नहीं जा सकता।"]),
  q(1, "general-studies", "indian-polity", "E", 2,
    ["The Governor of a State is appointed by:", ["The Chief Minister", "The Chief Justice of the High Court", "The President", "The Prime Minister"], "Under Article 155 the Governor of a State is appointed by the President and holds office during the President's pleasure."],
    ["राज्य के राज्यपाल की नियुक्ति कौन करता है?", ["मुख्यमंत्री", "उच्च न्यायालय के मुख्य न्यायाधीश", "राष्ट्रपति", "प्रधानमंत्री"], "अनुच्छेद 155 के अनुसार राज्यपाल की नियुक्ति राष्ट्रपति करते हैं और वह राष्ट्रपति के प्रसादपर्यंत पद धारण करता है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["The Fundamental Duties were added to the Constitution by which Amendment?", ["24th Amendment", "42nd Amendment", "44th Amendment", "73rd Amendment"], "The 42nd Amendment (1976), on the recommendation of the Swaran Singh Committee, added Fundamental Duties in Part IV-A (Article 51A)."],
    ["मूल कर्तव्य संविधान में किस संशोधन द्वारा जोड़े गए?", ["24वाँ संशोधन", "42वाँ संशोधन", "44वाँ संशोधन", "73वाँ संशोधन"], "42वें संशोधन (1976) ने स्वर्ण सिंह समिति की सिफारिश पर भाग IV-क (अनुच्छेद 51क) में मूल कर्तव्य जोड़े।"]),
  q(1, "general-studies", "indian-polity", "E", 3,
    ["The Constitution of India came into force on:", ["15 August 1947", "26 November 1949", "26 January 1949", "26 January 1950"], "The Constitution was adopted on 26 November 1949 and came into force on 26 January 1950, celebrated as Republic Day."],
    ["भारत का संविधान कब लागू हुआ?", ["15 अगस्त 1947", "26 नवंबर 1949", "26 जनवरी 1949", "26 जनवरी 1950"], "संविधान 26 नवंबर 1949 को अपनाया गया और 26 जनवरी 1950 को लागू हुआ, जिसे गणतंत्र दिवस के रूप में मनाया जाता है।"]),
  q(1, "general-studies", "indian-polity", "E", 1,
    ["What is the minimum age required to become a member of the Lok Sabha?", ["21 years", "25 years", "30 years", "35 years"], "A person must be at least 25 years old to contest for the Lok Sabha (30 years for the Rajya Sabha)."],
    ["लोकसभा का सदस्य बनने के लिए न्यूनतम आयु कितनी होनी चाहिए?", ["21 वर्ष", "25 वर्ष", "30 वर्ष", "35 वर्ष"], "लोकसभा चुनाव लड़ने के लिए कम से कम 25 वर्ष की आयु आवश्यक है (राज्यसभा के लिए 30 वर्ष)।"]),

  q(1, "general-studies", "indian-geography", "M", 2,
    ["The Tropic of Cancer passes through how many Indian states?", ["6", "7", "8", "9"], "It passes through eight states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram."],
    ["कर्क रेखा भारत के कितने राज्यों से होकर गुजरती है?", ["6", "7", "8", "9"], "यह आठ राज्यों से गुजरती है: गुजरात, राजस्थान, मध्य प्रदेश, छत्तीसगढ़, झारखंड, पश्चिम बंगाल, त्रिपुरा और मिज़ोरम।"]),
  q(1, "general-studies", "indian-geography", "E", 2,
    ["Which is the highest mountain peak in India?", ["Nanda Devi", "K2", "Kanchenjunga", "Kamet"], "Kanchenjunga (8,586 m) is the highest peak in India and the third highest in the world. K2 lies in the Pakistan-administered part of Kashmir."],
    ["भारत की सबसे ऊँची पर्वत चोटी कौन-सी है?", ["नंदा देवी", "K2", "कंचनजंगा", "कामेट"], "कंचनजंगा (8,586 मीटर) भारत की सबसे ऊँची और विश्व की तीसरी सबसे ऊँची चोटी है। K2 कश्मीर के पाकिस्तान-प्रशासित भाग में है।"]),
  q(1, "general-studies", "indian-geography", "E", 0,
    ["Chilika Lake, the largest coastal lagoon of India, is in which state?", ["Odisha", "Andhra Pradesh", "Tamil Nadu", "West Bengal"], "Chilika Lake is a brackish-water lagoon on the coast of Odisha."],
    ["भारत की सबसे बड़ी तटीय लैगून चिल्का झील किस राज्य में है?", ["ओडिशा", "आंध्र प्रदेश", "तमिलनाडु", "पश्चिम बंगाल"], "चिल्का झील ओडिशा के तट पर स्थित खारे पानी की लैगून है।"]),
  q(1, "general-studies", "indian-geography", "E", 1,
    ["Which soil is considered best for the cultivation of cotton?", ["Alluvial soil", "Black soil", "Red soil", "Laterite soil"], "Black soil (regur), rich in clay and moisture-retentive, is ideal for cotton, so it is also called black cotton soil."],
    ["कपास की खेती के लिए कौन-सी मिट्टी सर्वोत्तम मानी जाती है?", ["जलोढ़ मिट्टी", "काली मिट्टी", "लाल मिट्टी", "लैटेराइट मिट्टी"], "चिकनी और नमी सोखने वाली काली मिट्टी (रेगुर) कपास के लिए आदर्श है, इसीलिए इसे काली कपास मिट्टी भी कहते हैं।"]),

  q(1, "general-studies", "indian-economy", "E", 0,
    ["The Reserve Bank of India was established in the year:", ["1935", "1947", "1949", "1969"], "The RBI was established on 1 April 1935 under the RBI Act, 1934, and nationalised on 1 January 1949."],
    ["भारतीय रिज़र्व बैंक की स्थापना किस वर्ष हुई?", ["1935", "1947", "1949", "1969"], "RBI की स्थापना RBI अधिनियम 1934 के तहत 1 अप्रैल 1935 को हुई और 1 जनवरी 1949 को इसका राष्ट्रीयकरण किया गया।"]),
  q(1, "general-studies", "indian-economy", "E", 2,
    ["The Goods and Services Tax (GST) came into effect in India on:", ["1 April 2016", "1 January 2017", "1 July 2017", "1 April 2018"], "GST was rolled out on 1 July 2017 after the 101st Constitutional Amendment Act, 2016."],
    ["भारत में वस्तु एवं सेवा कर (GST) कब लागू हुआ?", ["1 अप्रैल 2016", "1 जनवरी 2017", "1 जुलाई 2017", "1 अप्रैल 2018"], "101वें संविधान संशोधन अधिनियम 2016 के बाद GST 1 जुलाई 2017 से लागू हुआ।"]),
  q(1, "general-studies", "indian-economy", "M", 1,
    ["The repo rate is the rate at which:", ["Commercial banks lend to the public", "The RBI lends short-term funds to commercial banks", "Commercial banks borrow from each other", "The RBI borrows from commercial banks"], "The repo rate is the interest rate at which the RBI lends short-term money to commercial banks against government securities. The reverse repo is the rate at which it borrows from them."],
    ["रेपो दर वह दर है जिस पर:", ["वाणिज्यिक बैंक जनता को उधार देते हैं", "RBI वाणिज्यिक बैंकों को अल्पकालिक धन उधार देता है", "वाणिज्यिक बैंक आपस में उधार लेते हैं", "RBI वाणिज्यिक बैंकों से उधार लेता है"], "रेपो दर वह ब्याज दर है जिस पर RBI सरकारी प्रतिभूतियों के बदले वाणिज्यिक बैंकों को अल्पकालिक धन उधार देता है। रिवर्स रेपो वह दर है जिस पर वह उनसे उधार लेता है।"]),

  q(1, "general-studies", "general-science", "E", 3,
    ["Deficiency of which vitamin causes scurvy?", ["Vitamin A", "Vitamin B", "Vitamin D", "Vitamin C"], "Scurvy is caused by a lack of Vitamin C (ascorbic acid), found in citrus fruits and amla."],
    ["किस विटामिन की कमी से स्कर्वी रोग होता है?", ["विटामिन A", "विटामिन B", "विटामिन D", "विटामिन C"], "स्कर्वी विटामिन C (एस्कॉर्बिक अम्ल) की कमी से होता है, जो नींबू-वर्गीय फलों और आँवले में पाया जाता है।"]),
  q(1, "general-studies", "general-science", "E", 0,
    ["What is the SI unit of force?", ["Newton", "Joule", "Pascal", "Watt"], "The SI unit of force is the newton (N); 1 N = 1 kg·m/s². Joule is energy, pascal is pressure and watt is power."],
    ["बल का SI मात्रक क्या है?", ["न्यूटन", "जूल", "पास्कल", "वाट"], "बल का SI मात्रक न्यूटन (N) है; 1 N = 1 kg·m/s²। जूल ऊर्जा का, पास्कल दाब का और वाट शक्ति का मात्रक है।"]),
  q(1, "general-studies", "general-science", "M", 1,
    ["The chemical symbol of sodium is:", ["S", "Na", "So", "Sn"], "The symbol of sodium is Na, from its Latin name natrium. S is sulphur and Sn is tin."],
    ["सोडियम का रासायनिक प्रतीक क्या है?", ["S", "Na", "So", "Sn"], "सोडियम का प्रतीक Na है, जो इसके लैटिन नाम नैट्रियम से आया है। S सल्फर और Sn टिन है।"]),
];
