// HP Panchayat Secretary Full Mock 4 — 120 questions (25 HP GK, 20 Social Science, 10 Everyday Science, 20 Reasoning & Maths,
// 20 Hindi & English, 25 Panchayati Raj, Rural Development & Computer).

import { q, type PanchayatQuestion } from "./types";

export const mock4: PanchayatQuestion[] = [
  // ───────── Section 0: Himachal GK & Current Affairs (25) ─────────
  q(0, "hp-gk", "polity-administration", "H", 0,
    ["The Himachal Pradesh Rajya Chayan Aayog (HPRCA) was set up to take over Class III recruitment after the dissolution of the:", ["HP Staff Selection Commission, Hamirpur", "HP Public Service Commission", "HP Subordinate Services Selection Board", "HP Board of School Education"], "The HP Staff Selection Commission at Hamirpur was dissolved in 2023 after a paper-leak scandal, and the HPRCA, also at Hamirpur, was created to conduct its recruitments."],
    ["हिमाचल प्रदेश राज्य चयन आयोग (HPRCA) किसके भंग होने के बाद तृतीय श्रेणी भर्तियाँ सँभालने के लिए बनाया गया?", ["हिमाचल प्रदेश कर्मचारी चयन आयोग, हमीरपुर", "हिमाचल प्रदेश लोक सेवा आयोग", "हिमाचल प्रदेश अधीनस्थ सेवाएँ चयन बोर्ड", "हिमाचल प्रदेश स्कूल शिक्षा बोर्ड"], "पेपर लीक प्रकरण के बाद 2023 में हमीरपुर का हिमाचल प्रदेश कर्मचारी चयन आयोग भंग किया गया और उसकी भर्तियों के लिए हमीरपुर में ही HPRCA बनाया गया।"]),
  q(0, "hp-gk", "polity-administration", "H", 1,
    ["The Mukhya Mantri Sukh Ashray Yojana of Himachal Pradesh is meant for:", ["farmers growing apples", "orphaned children, destitute women and the elderly, adopted as 'children of the state'", "unemployed graduates", "pregnant women in tribal areas"], "Under the Sukh Ashray scheme (2023) the state government takes orphans and other destitute people under its care as 'children of the state', paying for their education, pocket money and support."],
    ["हिमाचल प्रदेश की मुख्यमंत्री सुख आश्रय योजना किसके लिए है?", ["सेब उगाने वाले किसानों के लिए", "अनाथ बच्चों, निराश्रित महिलाओं और वृद्धों के लिए, जिन्हें 'राज्य के बच्चे' माना गया है", "बेरोज़गार स्नातकों के लिए", "जनजातीय क्षेत्रों की गर्भवती महिलाओं के लिए"], "सुख आश्रय योजना (2023) में राज्य सरकार अनाथों और अन्य निराश्रितों को 'राज्य के बच्चे' मानकर उनकी शिक्षा, जेब खर्च और सहायता का भार उठाती है।"]),
  q(0, "hp-gk", "polity-administration", "H", 2,
    ["Under the Indira Gandhi Pyari Behna Sukh Samman Nidhi of Himachal Pradesh, eligible women are promised a monthly amount of:", ["₹1,000", "₹2,000", "₹1,500", "₹2,500"], "The scheme promises ₹1,500 per month to eligible women aged 18 to 59, as announced by the state government in 2024."],
    ["हिमाचल प्रदेश की इंदिरा गांधी प्यारी बहना सुख सम्मान निधि में पात्र महिलाओं को प्रति माह कितनी राशि का वादा किया गया है?", ["₹1,000", "₹2,000", "₹1,500", "₹2,500"], "2024 में राज्य सरकार द्वारा घोषित इस योजना में 18 से 59 वर्ष की पात्र महिलाओं को ₹1,500 प्रति माह देने का प्रावधान है।"]),
  q(0, "hp-gk", "economy", "M", 3,
    ["Himachal Pradesh is often cited as the first state in India to have banned:", ["liquor", "tobacco advertising", "mining", "polythene carry bags"], "Himachal Pradesh banned the use of polythene carry bags under the HP Non-Biodegradable Garbage (Control) Act, with a complete ban from 2009."],
    ["हिमाचल प्रदेश को प्रायः भारत का पहला राज्य बताया जाता है जिसने किस पर प्रतिबंध लगाया?", ["शराब", "तंबाकू विज्ञापन", "खनन", "पॉलीथीन कैरी बैग"], "हिमाचल प्रदेश ने अजैव-अपघट्य कचरा (नियंत्रण) अधिनियम के तहत पॉलीथीन कैरी बैग पर रोक लगाई और 2009 से पूर्ण प्रतिबंध लागू किया।"]),
  q(0, "hp-gk", "economy", "H", 0,
    ["The Bulk Drug Park sanctioned for Himachal Pradesh by the Centre is being developed at:", ["Haroli (Una)", "Nalagarh (Solan)", "Kala Amb (Sirmaur)", "Gagret (Una)"], "The Bulk Drug Park is at Haroli in Una district; the Medical Devices Park is at Nalagarh in Solan district."],
    ["केंद्र द्वारा हिमाचल प्रदेश के लिए स्वीकृत बल्क ड्रग पार्क कहाँ विकसित किया जा रहा है?", ["हरोली (ऊना)", "नालागढ़ (सोलन)", "काला अंब (सिरमौर)", "गगरेट (ऊना)"], "बल्क ड्रग पार्क ऊना जिले के हरोली में है; मेडिकल डिवाइस पार्क सोलन जिले के नालागढ़ में है।"]),
  q(0, "hp-gk", "economy", "H", 1,
    ["The Medical Devices Park of Himachal Pradesh is located at:", ["Haroli", "Nalagarh", "Paonta Sahib", "Baddi"], "The Medical Devices Park is being set up at Nalagarh in Solan district under a central scheme to promote domestic manufacturing."],
    ["हिमाचल प्रदेश का मेडिकल डिवाइस पार्क कहाँ स्थित है?", ["हरोली", "नालागढ़", "पांवटा साहिब", "बद्दी"], "मेडिकल डिवाइस पार्क घरेलू उत्पादन बढ़ाने की केंद्रीय योजना के तहत सोलन जिले के नालागढ़ में बनाया जा रहा है।"]),
  q(0, "hp-gk", "districts", "M", 2,
    ["Bhuntar airport mainly serves which tourist region?", ["Shimla and Kufri", "Dharamshala and McLeod Ganj", "Kullu and Manali", "Chamba and Dalhousie"], "Bhuntar airport, at the confluence of the Beas and Parvati, serves Kullu and Manali. Gaggal serves Kangra and Jubbarhatti serves Shimla."],
    ["भुंतर हवाई अड्डा मुख्यतः किस पर्यटन क्षेत्र की सेवा करता है?", ["शिमला और कुफ़री", "धर्मशाला और मैक्लोडगंज", "कुल्लू और मनाली", "चंबा और डलहौज़ी"], "ब्यास और पार्वती के संगम पर स्थित भुंतर हवाई अड्डा कुल्लू और मनाली की सेवा करता है। गग्गल कांगड़ा और जुब्बड़हट्टी शिमला की सेवा करता है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The traditional community feast 'Dham' of Himachal Pradesh is cooked by hereditary cooks known as:", ["Halwais", "Bawarchis", "Rasoiyas", "Botis"], "Dham is cooked by Botis, Brahmin cooks who prepare dishes such as madra, rajmah and khatta in large copper vessels."],
    ["हिमाचल प्रदेश की पारंपरिक सामूहिक दावत 'धाम' किन पारंपरिक रसोइयों द्वारा पकाई जाती है?", ["हलवाई", "बावर्ची", "रसोइया", "बोटी"], "धाम बोटी पकाते हैं, जो ब्राह्मण रसोइये होते हैं और बड़े तांबे के बर्तनों में मदरा, राजमा और खट्टा जैसे व्यंजन बनाते हैं।"]),
  q(0, "hp-gk", "polity-administration", "H", 0,
    ["Who was the first Chief Justice of the High Court of Himachal Pradesh (1971)?", ["M.H. Beg", "R.S. Pathak", "T.U. Mehta", "V.D. Misra"], "Justice Mirza Hameedullah Beg was the first Chief Justice of the HP High Court in 1971 and later became Chief Justice of India."],
    ["हिमाचल प्रदेश उच्च न्यायालय (1971) के पहले मुख्य न्यायाधीश कौन थे?", ["एम.एच. बेग", "आर.एस. पाठक", "टी.यू. मेहता", "वी.डी. मिश्रा"], "न्यायमूर्ति मिर्ज़ा हमीदुल्लाह बेग 1971 में हिमाचल उच्च न्यायालय के पहले मुख्य न्यायाधीश थे और बाद में भारत के मुख्य न्यायाधीश बने।"]),
  q(0, "hp-gk", "personalities", "M", 1,
    ["Which former Chief Minister of Himachal Pradesh was popularly called 'Paani wala Mukhya Mantri' for his drinking water schemes?", ["Virbhadra Singh", "Shanta Kumar", "Prem Kumar Dhumal", "Ram Lal Thakur"], "Shanta Kumar earned the name for bringing hand pumps and piped drinking water to villages during his first term (1977–80)."],
    ["पेयजल योजनाओं के कारण हिमाचल प्रदेश के किस पूर्व मुख्यमंत्री को 'पानी वाला मुख्यमंत्री' कहा गया?", ["वीरभद्र सिंह", "शांता कुमार", "प्रेम कुमार धूमल", "राम लाल ठाकुर"], "शांता कुमार को अपने पहले कार्यकाल (1977–80) में गाँवों तक हैंडपंप और नल से पेयजल पहुँचाने के लिए यह नाम मिला।"]),
  q(0, "hp-gk", "personalities", "M", 2,
    ["Virbhadra Singh served as Chief Minister of Himachal Pradesh how many times?", ["Four", "Five", "Six", "Three"], "Virbhadra Singh was Chief Minister six times between 1983 and 2017, the most by anyone in the state."],
    ["वीरभद्र सिंह कितनी बार हिमाचल प्रदेश के मुख्यमंत्री रहे?", ["चार", "पाँच", "छह", "तीन"], "वीरभद्र सिंह 1983 से 2017 के बीच छह बार मुख्यमंत्री रहे, जो राज्य में किसी के लिए भी सबसे अधिक है।"]),
  q(0, "hp-gk", "personalities", "H", 3,
    ["Dr Y.S. Parmar wrote his doctoral thesis, later published as a book, on the subject of:", ["Apple farming in Kotgarh", "Pahari painting", "Princely states of Punjab", "Polyandry in the Himalayas"], "Dr Parmar's PhD thesis, 'Polyandry in the Himalayas', was published as a book in 1975; he had earned his doctorate from Lucknow University."],
    ["डॉ. वाई.एस. परमार ने अपना शोध प्रबंध, जो बाद में पुस्तक के रूप में छपा, किस विषय पर लिखा?", ["कोटगढ़ में सेब की खेती", "पहाड़ी चित्रकला", "पंजाब की रियासतें", "हिमालय में बहुपति प्रथा"], "डॉ. परमार का पीएचडी शोध 'Polyandry in the Himalayas' 1975 में पुस्तक के रूप में छपा; उन्होंने लखनऊ विश्वविद्यालय से डॉक्टरेट की थी।"]),
  q(0, "hp-gk", "polity-administration", "H", 0,
    ["Which Lok Sabha constituency of Himachal Pradesh is the largest by area?", ["Mandi", "Kangra", "Shimla", "Hamirpur"], "The Mandi parliamentary constituency covers Mandi, Kullu, Lahaul & Spiti, Kinnaur and parts of Chamba and Shimla, making it the largest by area."],
    ["क्षेत्रफल की दृष्टि से हिमाचल प्रदेश का सबसे बड़ा लोकसभा क्षेत्र कौन-सा है?", ["मंडी", "कांगड़ा", "शिमला", "हमीरपुर"], "मंडी संसदीय क्षेत्र में मंडी, कुल्लू, लाहौल-स्पीति, किन्नौर और चंबा व शिमला के कुछ भाग आते हैं, इसलिए यह क्षेत्रफल में सबसे बड़ा है।"]),
  q(0, "hp-gk", "economy", "M", 1,
    ["Disease-free seed potato is a famous cash crop of which cold region of Himachal Pradesh?", ["Una", "Lahaul", "Bilaspur", "Hamirpur"], "Lahaul's dry, cold climate keeps aphids away, so its seed potato is in demand across India. Peas and hops are also grown there."],
    ["रोगमुक्त बीज आलू हिमाचल प्रदेश के किस ठंडे क्षेत्र की प्रसिद्ध नकदी फ़सल है?", ["ऊना", "लाहौल", "बिलासपुर", "हमीरपुर"], "लाहौल की शुष्क, ठंडी जलवायु में माहू (एफ़िड) नहीं पनपते, इसलिए इसके बीज आलू की पूरे भारत में माँग है। यहाँ मटर और हॉप्स भी उगते हैं।"]),
  q(0, "hp-gk", "polity-administration", "M", 2,
    ["Which body conducts the Himachal Pradesh Teacher Eligibility Test (HP TET)?", ["HP Rajya Chayan Aayog", "HP Public Service Commission", "HP Board of School Education", "HP University"], "The HP TET is conducted by the HP Board of School Education, Dharamshala. Recruitment of teachers is done separately by the HPRCA."],
    ["हिमाचल प्रदेश अध्यापक पात्रता परीक्षा (HP TET) कौन आयोजित करता है?", ["हिमाचल प्रदेश राज्य चयन आयोग", "हिमाचल प्रदेश लोक सेवा आयोग", "हिमाचल प्रदेश स्कूल शिक्षा बोर्ड", "हिमाचल प्रदेश विश्वविद्यालय"], "HP TET हिमाचल प्रदेश स्कूल शिक्षा बोर्ड, धर्मशाला आयोजित करता है। अध्यापकों की भर्ती अलग से HPRCA करता है।"]),
  q(0, "hp-gk", "economy", "H", 3,
    ["The Himachal Road Transport Corporation (HRTC) came into existence in the year:", ["1966", "1971", "1980", "1974"], "HRTC was formed on 2 October 1974 by merging the Himachal Government Transport with the Mandi–Kullu Road Transport Corporation."],
    ["हिमाचल पथ परिवहन निगम (HRTC) किस वर्ष अस्तित्व में आया?", ["1966", "1971", "1980", "1974"], "HRTC का गठन 2 अक्टूबर 1974 को हिमाचल सरकार परिवहन और मंडी–कुल्लू सड़क परिवहन निगम को मिलाकर हुआ।"]),
  q(0, "hp-gk", "geography", "H", 0,
    ["A pheasantry for the captive breeding of the Western Tragopan (Jujurana) is run at:", ["Sarahan", "Kufri", "Manali", "Dalhousie"], "The Sarahan Pheasantry in Shimla district breeds the endangered Western Tragopan, the state bird."],
    ["पश्चिमी ट्रैगोपैन (जुजुराना) के बंदी प्रजनन के लिए तीतर प्रजनन केंद्र कहाँ है?", ["सराहन", "कुफ़री", "मनाली", "डलहौज़ी"], "शिमला जिले का सराहन तीतर प्रजनन केंद्र संकटग्रस्त राज्य पक्षी पश्चिमी ट्रैगोपैन का प्रजनन करता है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["Which wildlife area of Himachal Pradesh has a lion safari?", ["Pong Dam sanctuary", "Renuka Ji", "Kufri", "Chail"], "The Renuka Ji mini zoo in Sirmaur district has the state's lion safari, alongside the Renuka lake sanctuary."],
    ["हिमाचल प्रदेश के किस वन्यजीव क्षेत्र में लायन सफ़ारी है?", ["पौंग बाँध अभयारण्य", "रेणुका जी", "कुफ़री", "चायल"], "सिरमौर जिले के रेणुका जी लघु चिड़ियाघर में राज्य की लायन सफ़ारी है, जो रेणुका झील अभयारण्य के साथ है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Nicholas Roerich Art Gallery, in the former home of the Russian painter, is at:", ["Manali", "Kasol", "Naggar", "Banjar"], "Nicholas Roerich lived at Naggar in Kullu from 1928 until his death in 1947; his estate is now an art gallery."],
    ["रूसी चित्रकार के पूर्व निवास में स्थित निकोलस रोरिक आर्ट गैलरी कहाँ है?", ["मनाली", "कसोल", "नग्गर", "बंजार"], "निकोलस रोरिक 1928 से 1947 में अपनी मृत्यु तक कुल्लू के नग्गर में रहे; उनका निवास अब आर्ट गैलरी है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The Sobha Singh Art Gallery, devoted to the famous painter of Sikh Gurus and Sohni–Mahiwal, is at:", ["Palampur", "Nurpur", "Dharamshala", "Andretta"], "Painter Sardar Sobha Singh settled at Andretta near Palampur (Kangra) in 1949; his home is now a gallery. Andretta is also known for Norah Richards' theatre and its pottery."],
    ["सिख गुरुओं और सोहनी–महिवाल के प्रसिद्ध चित्रकार को समर्पित सोभा सिंह आर्ट गैलरी कहाँ है?", ["पालमपुर", "नूरपुर", "धर्मशाला", "अंद्रेटा"], "चित्रकार सरदार सोभा सिंह 1949 में पालमपुर (कांगड़ा) के पास अंद्रेटा में बसे; उनका घर अब गैलरी है। अंद्रेटा नोरा रिचर्ड्स के रंगमंच और मिट्टी के बर्तनों के लिए भी प्रसिद्ध है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The HPCA cricket stadium, which hosts international matches against the backdrop of the Dhauladhar range, is at:", ["Dharamshala", "Shimla", "Una", "Bilaspur"], "The Himachal Pradesh Cricket Association stadium at Dharamshala is one of the most scenic cricket grounds in the world."],
    ["धौलाधार की पृष्ठभूमि में अंतरराष्ट्रीय मैच कराने वाला HPCA क्रिकेट स्टेडियम कहाँ है?", ["धर्मशाला", "शिमला", "ऊना", "बिलासपुर"], "धर्मशाला का हिमाचल प्रदेश क्रिकेट एसोसिएशन स्टेडियम दुनिया के सबसे सुंदर क्रिकेट मैदानों में गिना जाता है।"]),
  q(0, "hp-gk", "economy", "H", 1,
    ["The Beas–Sutlej Link project diverts water of the Beas from Pandoh dam, through tunnels, to the Sutlej via the power house at:", ["Bhakra", "Dehar", "Nangal", "Ganguwal"], "Water stored at Pandoh is carried through tunnels and a channel to the Dehar power house (990 MW), after which it falls into the Sutlej above Bhakra."],
    ["ब्यास–सतलुज लिंक परियोजना पंडोह बाँध से ब्यास का जल सुरंगों द्वारा किस पावर हाउस से होकर सतलुज में पहुँचाती है?", ["भाखड़ा", "डैहर", "नंगल", "गंगूवाल"], "पंडोह में रोका गया जल सुरंगों और नहर से डैहर पावर हाउस (990 मेगावाट) तक जाता है, फिर भाखड़ा से ऊपर सतलुज में गिरता है।"]),
  q(0, "hp-gk", "economy", "M", 2,
    ["The Larji hydroelectric project of Himachal Pradesh is on which river?", ["Ravi", "Sutlej", "Beas", "Yamuna"], "The 126 MW Larji project is on the Beas in Kullu district, near the confluence of the Sainj and Tirthan."],
    ["हिमाचल प्रदेश की लारजी जलविद्युत परियोजना किस नदी पर है?", ["रावी", "सतलुज", "ब्यास", "यमुना"], "126 मेगावाट की लारजी परियोजना कुल्लू जिले में सैंज और तीर्थन के संगम के पास ब्यास नदी पर है।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["The Himalayan Nature Park, home to the musk deer and Himalayan black bear, is at:", ["Manali", "Khajjiar", "Narkanda", "Kufri"], "The Himalayan Nature Park is at Kufri near Shimla and shows high-altitude animals and birds of the state."],
    ["कस्तूरी मृग और हिमालयी काले भालू वाला हिमालयन नेचर पार्क कहाँ है?", ["मनाली", "खज्जियार", "नारकंडा", "कुफ़री"], "हिमालयन नेचर पार्क शिमला के पास कुफ़री में है और राज्य के ऊँचाई वाले पशु-पक्षी दिखाता है।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["Una district of Himachal Pradesh shares its southern and western border with which state?", ["Punjab", "Haryana", "Uttarakhand", "Jammu & Kashmir"], "Una borders Punjab (Hoshiarpur, Rupnagar districts). The Swan river flows through the district."],
    ["हिमाचल प्रदेश का ऊना जिला दक्षिण और पश्चिम में किस राज्य से सीमा बनाता है?", ["पंजाब", "हरियाणा", "उत्तराखंड", "जम्मू-कश्मीर"], "ऊना की सीमा पंजाब (होशियारपुर, रूपनगर जिले) से लगती है। जिले से स्वां नदी बहती है।"]),

  // ───────── Section 1: Social Science (20) ─────────
  q(1, "general-studies", "indian-history", "M", 1,
    ["The Greek ambassador Megasthenes, who wrote 'Indica', came to the court of:", ["Ashoka", "Chandragupta Maurya", "Bindusara", "Kanishka"], "Megasthenes was sent by Seleucus Nicator to Chandragupta Maurya's court at Pataliputra; his 'Indica' survives only in quotations."],
    ["'इंडिका' लिखने वाला यूनानी राजदूत मेगस्थनीज़ किसके दरबार में आया था?", ["अशोक", "चंद्रगुप्त मौर्य", "बिंदुसार", "कनिष्क"], "मेगस्थनीज़ को सेल्यूकस निकेटर ने पाटलिपुत्र में चंद्रगुप्त मौर्य के दरबार में भेजा था; उसकी 'इंडिका' केवल उद्धरणों में बची है।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["The rust-free Iron Pillar at Mehrauli in Delhi is attributed to which dynasty?", ["Maurya", "Kushan", "Gupta", "Pala"], "The Iron Pillar's inscription refers to a king 'Chandra', generally identified with Chandragupta II of the Gupta dynasty; it has hardly rusted in 1,600 years."],
    ["दिल्ली के महरौली का जंग-रहित लौह स्तंभ किस राजवंश का माना जाता है?", ["मौर्य", "कुषाण", "गुप्त", "पाल"], "लौह स्तंभ के अभिलेख में 'चंद्र' नामक राजा का उल्लेख है, जिसे सामान्यतः गुप्त वंश का चंद्रगुप्त द्वितीय माना जाता है; 1,600 वर्षों में इसमें लगभग जंग नहीं लगी।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["The Telugu work 'Amuktamalyada' was written by which Vijayanagara ruler?", ["Harihara I", "Bukka I", "Deva Raya II", "Krishnadevaraya"], "Krishnadevaraya (1509–29), the greatest Vijayanagara king, wrote 'Amuktamalyada' in Telugu; his court had the 'Ashtadiggajas' poets."],
    ["तेलुगु रचना 'आमुक्तमाल्यद' किस विजयनगर शासक ने लिखी?", ["हरिहर प्रथम", "बुक्का प्रथम", "देवराय द्वितीय", "कृष्णदेवराय"], "विजयनगर के महानतम राजा कृष्णदेवराय (1509–29) ने तेलुगु में 'आमुक्तमाल्यद' लिखी; उनके दरबार में 'अष्टदिग्गज' कवि थे।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Who led the Revolt of 1857 at Kanpur?", ["Nana Saheb", "Kunwar Singh", "Begum Hazrat Mahal", "Bahadur Shah Zafar"], "Nana Saheb, adopted son of Peshwa Baji Rao II, led the revolt at Kanpur with Tantia Tope. Kunwar Singh led it in Bihar and Begum Hazrat Mahal in Lucknow."],
    ["1857 के विद्रोह का कानपुर में नेतृत्व किसने किया?", ["नाना साहब", "कुंवर सिंह", "बेगम हज़रत महल", "बहादुर शाह ज़फ़र"], "पेशवा बाजीराव द्वितीय के दत्तक पुत्र नाना साहब ने तात्या टोपे के साथ कानपुर में नेतृत्व किया। कुंवर सिंह ने बिहार और बेगम हज़रत महल ने लखनऊ में नेतृत्व किया।"]),
  q(1, "general-studies", "indian-history", "H", 1,
    ["The first Indian National Army (Azad Hind Fauj) was organised in 1942 by:", ["Subhas Chandra Bose", "Captain Mohan Singh", "Rash Behari Bose", "Shah Nawaz Khan"], "Captain Mohan Singh formed the first INA in 1942 from Indian prisoners of war in Malaya. Subhas Chandra Bose revived and led it from 1943."],
    ["पहली भारतीय राष्ट्रीय सेना (आज़ाद हिंद फ़ौज) 1942 में किसने संगठित की?", ["सुभाष चंद्र बोस", "कैप्टन मोहन सिंह", "रास बिहारी बोस", "शाहनवाज़ ख़ान"], "कैप्टन मोहन सिंह ने 1942 में मलाया में भारतीय युद्धबंदियों से पहली INA बनाई। 1943 से सुभाष चंद्र बोस ने इसे पुनर्गठित कर नेतृत्व किया।"]),
  q(1, "general-studies", "indian-history", "H", 2,
    ["The 'Communal Award' of 1932, which provided separate electorates for the Depressed Classes, was announced by British Prime Minister:", ["Winston Churchill", "Clement Attlee", "Ramsay MacDonald", "Stanley Baldwin"], "Ramsay MacDonald announced the Communal Award in August 1932. Gandhiji's fast against it led to the Poona Pact."],
    ["दलित वर्गों के लिए पृथक निर्वाचन देने वाला 1932 का 'सांप्रदायिक पंचाट' किस ब्रिटिश प्रधानमंत्री ने घोषित किया?", ["विंस्टन चर्चिल", "क्लेमेंट एटली", "रैम्ज़े मैकडोनाल्ड", "स्टैनली बाल्डविन"], "रैम्ज़े मैकडोनाल्ड ने अगस्त 1932 में सांप्रदायिक पंचाट घोषित किया। इसके विरुद्ध गांधीजी के अनशन से पूना पैक्ट हुआ।"]),
  q(1, "general-studies", "indian-history", "M", 3,
    ["In 1765, after the Battle of Buxar, the East India Company obtained from Shah Alam II the:", ["right to build forts", "title of Nawab", "control of Delhi", "Diwani of Bengal, Bihar and Orissa"], "By the Treaty of Allahabad (1765) Robert Clive got the Diwani, the right to collect revenue, of Bengal, Bihar and Orissa."],
    ["बक्सर के युद्ध के बाद 1765 में ईस्ट इंडिया कंपनी को शाह आलम द्वितीय से क्या मिला?", ["किले बनाने का अधिकार", "नवाब की उपाधि", "दिल्ली पर नियंत्रण", "बंगाल, बिहार और उड़ीसा की दीवानी"], "इलाहाबाद की संधि (1765) से रॉबर्ट क्लाइव को बंगाल, बिहार और उड़ीसा की दीवानी, यानी राजस्व वसूलने का अधिकार मिला।"]),
  q(1, "general-studies", "indian-geography", "M", 0,
    ["Indira Point, the southernmost point of India, is located in:", ["Great Nicobar", "Kanyakumari", "Lakshadweep", "Rameswaram"], "Indira Point is on Great Nicobar Island. Kanyakumari is the southern tip of the Indian mainland."],
    ["भारत का सबसे दक्षिणी बिंदु इंदिरा पॉइंट कहाँ है?", ["ग्रेट निकोबार", "कन्याकुमारी", "लक्षद्वीप", "रामेश्वरम"], "इंदिरा पॉइंट ग्रेट निकोबार द्वीप पर है। कन्याकुमारी भारत की मुख्य भूमि का दक्षिणी छोर है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Which group of Indian islands is made up of coral atolls?", ["Andaman Islands", "Lakshadweep", "Nicobar Islands", "Sundarbans islands"], "Lakshadweep in the Arabian Sea consists of coral atolls and reefs, while the Andaman and Nicobar Islands are mostly the tops of submerged mountains."],
    ["भारत का कौन-सा द्वीप समूह प्रवाल (कोरल) एटॉल से बना है?", ["अंडमान द्वीप", "लक्षद्वीप", "निकोबार द्वीप", "सुंदरबन के द्वीप"], "अरब सागर का लक्षद्वीप प्रवाल एटॉल और भित्तियों से बना है, जबकि अंडमान-निकोबार मुख्यतः डूबे पर्वतों की चोटियाँ हैं।"]),
  q(1, "general-studies", "indian-geography", "H", 2,
    ["Which river of Rajasthan ends in the Rann of Kutch without reaching the sea?", ["Chambal", "Banas", "Luni", "Mahi"], "The Luni rises near Ajmer and ends in the marshes of the Rann of Kutch. Its water is sweet at first and turns salty downstream."],
    ["राजस्थान की कौन-सी नदी समुद्र तक पहुँचे बिना कच्छ के रण में समाप्त हो जाती है?", ["चंबल", "बनास", "लूनी", "माही"], "लूनी अजमेर के पास से निकलकर कच्छ के रण के दलदल में समाप्त होती है। इसका जल पहले मीठा और आगे खारा हो जाता है।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["Which pass connects Sikkim with Tibet and was reopened for border trade in 2006?", ["Shipki La", "Lipulekh", "Bomdi La", "Nathu La"], "Nathu La in Sikkim was reopened for India–China border trade in 2006. Shipki La (HP) and Lipulekh (Uttarakhand) are other trade passes."],
    ["कौन-सा दर्रा सिक्किम को तिब्बत से जोड़ता है और 2006 में सीमा व्यापार के लिए फिर खोला गया?", ["शिपकी ला", "लिपुलेख", "बोमडी ला", "नाथू ला"], "सिक्किम का नाथू ला 2006 में भारत–चीन सीमा व्यापार के लिए फिर खोला गया। शिपकी ला (हिमाचल) और लिपुलेख (उत्तराखंड) अन्य व्यापारिक दर्रे हैं।"]),
  q(1, "general-studies", "indian-geography", "H", 0,
    ["Bhitarkanika, known for its mangroves and saltwater crocodiles, is in:", ["Odisha", "West Bengal", "Andhra Pradesh", "Gujarat"], "Bhitarkanika National Park in Kendrapara district of Odisha has India's second-largest mangrove forest and a large population of saltwater crocodiles."],
    ["मैंग्रोव और खारे पानी के मगरमच्छों के लिए प्रसिद्ध भितरकनिका कहाँ है?", ["ओडिशा", "पश्चिम बंगाल", "आंध्र प्रदेश", "गुजरात"], "ओडिशा के केंद्रपाड़ा जिले का भितरकनिका राष्ट्रीय उद्यान भारत का दूसरा सबसे बड़ा मैंग्रोव वन है और यहाँ खारे पानी के मगरमच्छ बड़ी संख्या में हैं।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["How many Fundamental Duties are listed in Article 51A at present?", ["10", "11", "12", "9"], "The 42nd Amendment listed 10 duties; the 86th Amendment (2002) added the 11th, the duty of parents to educate children aged 6 to 14."],
    ["अनुच्छेद 51क में इस समय कितने मौलिक कर्तव्य हैं?", ["10", "11", "12", "9"], "42वें संशोधन में 10 कर्तव्य थे; 86वें संशोधन (2002) ने 11वाँ जोड़ा, यानी 6 से 14 वर्ष के बच्चों को शिक्षा दिलाने का माता-पिता का कर्तव्य।"]),
  q(1, "general-studies", "indian-polity", "M", 2,
    ["Who administers the oath of office to the Chief Justice of India?", ["The Vice-President", "The Prime Minister", "The President", "The senior-most judge of the Supreme Court"], "The President administers the oath to the Chief Justice and other judges of the Supreme Court (Article 124 and Third Schedule)."],
    ["भारत के मुख्य न्यायाधीश को पद की शपथ कौन दिलाता है?", ["उपराष्ट्रपति", "प्रधानमंत्री", "राष्ट्रपति", "सर्वोच्च न्यायालय के वरिष्ठतम न्यायाधीश"], "राष्ट्रपति मुख्य न्यायाधीश और सर्वोच्च न्यायालय के अन्य न्यायाधीशों को शपथ दिलाते हैं (अनुच्छेद 124 और तीसरी अनुसूची)।"]),
  q(1, "general-studies", "indian-polity", "H", 3,
    ["If the Speaker of the Lok Sabha wishes to resign, the resignation letter is addressed to the:", ["President", "Prime Minister", "Chief Justice of India", "Deputy Speaker"], "Under Article 94 the Speaker resigns by writing to the Deputy Speaker, and the Deputy Speaker by writing to the Speaker."],
    ["यदि लोकसभा अध्यक्ष त्यागपत्र देना चाहें, तो वह किसे संबोधित करते हैं?", ["राष्ट्रपति", "प्रधानमंत्री", "भारत के मुख्य न्यायाधीश", "उपाध्यक्ष"], "अनुच्छेद 94 के अनुसार अध्यक्ष उपाध्यक्ष को लिखकर और उपाध्यक्ष अध्यक्ष को लिखकर त्यागपत्र देते हैं।"]),
  q(1, "general-studies", "indian-polity", "H", 0,
    ["The Comptroller and Auditor General of India (CAG) is appointed under which Article?", ["Article 148", "Article 124", "Article 280", "Article 315"], "Article 148 provides for the CAG, appointed by the President. Article 280 is the Finance Commission and Article 315 the Public Service Commissions."],
    ["भारत के नियंत्रक एवं महालेखा परीक्षक (CAG) की नियुक्ति किस अनुच्छेद के अंतर्गत होती है?", ["अनुच्छेद 148", "अनुच्छेद 124", "अनुच्छेद 280", "अनुच्छेद 315"], "अनुच्छेद 148 में CAG का प्रावधान है, जिसकी नियुक्ति राष्ट्रपति करते हैं। अनुच्छेद 280 वित्त आयोग और 315 लोक सेवा आयोगों से संबंधित है।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["The idea of judicial review in the Indian Constitution was mainly borrowed from the Constitution of:", ["Britain", "the USA", "Canada", "Ireland"], "Judicial review, the independence of the judiciary and Fundamental Rights were drawn from the US Constitution."],
    ["भारतीय संविधान में न्यायिक पुनरावलोकन की अवधारणा मुख्यतः किस देश के संविधान से ली गई?", ["ब्रिटेन", "अमेरिका", "कनाडा", "आयरलैंड"], "न्यायिक पुनरावलोकन, न्यायपालिका की स्वतंत्रता और मौलिक अधिकार अमेरिकी संविधान से लिए गए।"]),
  q(1, "general-studies", "indian-economy", "H", 2,
    ["The Contingency Fund of India, used to meet urgent unforeseen expenditure, is placed at the disposal of the:", ["Finance Minister", "Parliament", "President", "RBI Governor"], "Under Article 267 the Contingency Fund is placed at the disposal of the President; Parliament later approves the spending."],
    ["अप्रत्याशित तात्कालिक व्यय के लिए भारत की आकस्मिकता निधि किसके अधिकार में रखी जाती है?", ["वित्त मंत्री", "संसद", "राष्ट्रपति", "RBI गवर्नर"], "अनुच्छेद 267 के अनुसार आकस्मिकता निधि राष्ट्रपति के अधिकार में होती है; बाद में संसद व्यय को स्वीकृति देती है।"]),
  q(1, "general-studies", "indian-economy", "H", 3,
    ["Under the PM MUDRA Yojana, loans up to ₹50,000 fall in which category?", ["Kishore", "Tarun", "Tarun Plus", "Shishu"], "MUDRA loans are Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 lakh) and Tarun (₹5 lakh to ₹10 lakh), with Tarun Plus added later for larger loans."],
    ["प्रधानमंत्री मुद्रा योजना में ₹50,000 तक के ऋण किस श्रेणी में आते हैं?", ["किशोर", "तरुण", "तरुण प्लस", "शिशु"], "मुद्रा ऋण शिशु (₹50,000 तक), किशोर (₹50,000 से ₹5 लाख) और तरुण (₹5 लाख से ₹10 लाख) हैं; बड़े ऋणों के लिए बाद में तरुण प्लस जोड़ा गया।"]),
  q(1, "general-studies", "indian-economy", "H", 0,
    ["The Periodic Labour Force Survey (PLFS), which measures unemployment in India, is conducted by the:", ["Ministry of Statistics and Programme Implementation", "Ministry of Labour and Employment", "Reserve Bank of India", "NITI Aayog"], "The PLFS is conducted by the National Statistics Office of the Ministry of Statistics and Programme Implementation (MoSPI)."],
    ["भारत में बेरोज़गारी मापने वाला आवधिक श्रम बल सर्वेक्षण (PLFS) कौन करता है?", ["सांख्यिकी और कार्यक्रम कार्यान्वयन मंत्रालय", "श्रम और रोज़गार मंत्रालय", "भारतीय रिज़र्व बैंक", "नीति आयोग"], "PLFS सांख्यिकी और कार्यक्रम कार्यान्वयन मंत्रालय (MoSPI) का राष्ट्रीय सांख्यिकी कार्यालय करता है।"]),

  // ───────── Section 2: Everyday Science (10) ─────────
  q(2, "general-studies", "general-science", "M", 1,
    ["Which gas is used to fill toy balloons and airships because, unlike hydrogen, it does not burn?", ["Nitrogen", "Helium", "Neon", "Methane"], "Helium is very light and non-flammable, so it is safer than hydrogen for balloons and airships."],
    ["हाइड्रोजन के विपरीत न जलने के कारण खिलौना गुब्बारों और वायुपोतों में कौन-सी गैस भरी जाती है?", ["नाइट्रोजन", "हीलियम", "नियॉन", "मीथेन"], "हीलियम बहुत हल्की और अज्वलनशील है, इसलिए गुब्बारों और वायुपोतों के लिए हाइड्रोजन से सुरक्षित है।"]),
  q(2, "general-studies", "general-science", "M", 0,
    ["Beriberi is caused by the deficiency of which vitamin?", ["Vitamin B1 (thiamine)", "Vitamin B12", "Vitamin D", "Vitamin C"], "Thiamine (Vitamin B1) deficiency causes beriberi, which affects the nerves and heart. It is common where polished rice is the staple food."],
    ["बेरी-बेरी रोग किस विटामिन की कमी से होता है?", ["विटामिन B1 (थायमिन)", "विटामिन B12", "विटामिन D", "विटामिन C"], "थायमिन (विटामिन B1) की कमी से बेरी-बेरी होता है, जो तंत्रिकाओं और हृदय को प्रभावित करता है। यह पॉलिश किए चावल पर निर्भर क्षेत्रों में आम है।"]),
  q(2, "general-studies", "general-science", "H", 3,
    ["Plaster of Paris, used for setting broken bones, is obtained by heating:", ["limestone", "bauxite", "common salt", "gypsum"], "Heating gypsum (CaSO₄·2H₂O) to about 373 K gives Plaster of Paris (CaSO₄·½H₂O), which sets hard when mixed with water."],
    ["टूटी हड्डियों को जोड़ने में प्रयुक्त प्लास्टर ऑफ़ पेरिस किसे गर्म करके बनाया जाता है?", ["चूना पत्थर", "बॉक्साइट", "साधारण नमक", "जिप्सम"], "जिप्सम (CaSO₄·2H₂O) को लगभग 373 K पर गर्म करने से प्लास्टर ऑफ़ पेरिस (CaSO₄·½H₂O) बनता है, जो पानी मिलाने पर कठोर हो जाता है।"]),
  q(2, "general-studies", "general-science", "E", 0,
    ["What is the SI unit of electrical resistance?", ["Ohm", "Ampere", "Volt", "Coulomb"], "Resistance is measured in ohms (Ω). Current is in amperes, potential difference in volts and charge in coulombs."],
    ["विद्युत प्रतिरोध का SI मात्रक क्या है?", ["ओम", "एम्पियर", "वोल्ट", "कूलॉम"], "प्रतिरोध ओम (Ω) में मापा जाता है। धारा एम्पियर में, विभवांतर वोल्ट में और आवेश कूलॉम में।"]),
  q(2, "general-studies", "general-science", "M", 1,
    ["Which organ of the human body filters blood and produces urine?", ["Liver", "Kidney", "Lungs", "Spleen"], "Each kidney has about a million nephrons that filter blood and form urine, removing urea and extra salts."],
    ["मानव शरीर का कौन-सा अंग रक्त को छानकर मूत्र बनाता है?", ["यकृत", "गुर्दा (वृक्क)", "फेफड़े", "प्लीहा"], "प्रत्येक गुर्दे में लगभग दस लाख नेफ़्रॉन होते हैं, जो रक्त छानकर मूत्र बनाते हैं और यूरिया व अतिरिक्त लवण निकालते हैं।"]),
  q(2, "general-studies", "general-science", "M", 2,
    ["The normal temperature of the human body, 37 °C, is equal to:", ["96.8 °F", "100.4 °F", "98.6 °F", "99.5 °F"], "°F = °C × 9/5 + 32 = 37 × 1.8 + 32 = 98.6 °F."],
    ["मानव शरीर का सामान्य तापमान 37 °C किसके बराबर है?", ["96.8 °F", "100.4 °F", "98.6 °F", "99.5 °F"], "°F = °C × 9/5 + 32 = 37 × 1.8 + 32 = 98.6 °F।"], "37*9/5+32"),
  q(2, "general-studies", "general-science", "H", 3,
    ["To hear a distinct echo in air, the reflecting surface must be at least about how far away?", ["5 m", "10 m", "34 m", "17 m"], "Our ear keeps a sound for about 0.1 s. Sound (≈340 m/s) must travel 34 m there and back, so the wall must be at least 17 m away."],
    ["वायु में स्पष्ट प्रतिध्वनि सुनने के लिए परावर्तक सतह कम से कम लगभग कितनी दूर होनी चाहिए?", ["5 मीटर", "10 मीटर", "34 मीटर", "17 मीटर"], "कान ध्वनि को लगभग 0.1 सेकंड तक रखता है। ध्वनि (≈340 मी/से) को जाने-आने में 34 मीटर चलना होगा, अतः दीवार कम से कम 17 मीटर दूर हो।"], "340*0.1/2"),
  q(2, "general-studies", "general-science", "M", 0,
    ["Which gas released by human activity contributes most to global warming?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "Carbon dioxide from burning coal, oil and gas is the main human-made greenhouse gas; methane and nitrous oxide also contribute."],
    ["मानव गतिविधियों से निकलने वाली कौन-सी गैस वैश्विक तापन में सबसे अधिक योगदान देती है?", ["कार्बन डाइऑक्साइड", "ऑक्सीजन", "नाइट्रोजन", "हाइड्रोजन"], "कोयला, तेल और गैस जलाने से निकलने वाली कार्बन डाइऑक्साइड मुख्य मानव-जनित ग्रीनहाउस गैस है; मीथेन और नाइट्रस ऑक्साइड भी योगदान देती हैं।"]),
  q(2, "general-studies", "general-science", "H", 1,
    ["Soap does not lather well in hard water because:", ["hard water is too cold", "calcium and magnesium ions form an insoluble scum with soap", "hard water contains too much oxygen", "soap dissolves too fast in it"], "Ca²⁺ and Mg²⁺ ions react with soap to form insoluble salts (scum), wasting soap. Detergents work in hard water."],
    ["कठोर जल में साबुन अच्छा झाग क्यों नहीं देता?", ["कठोर जल बहुत ठंडा होता है", "कैल्शियम और मैग्नीशियम आयन साबुन के साथ अघुलनशील मैल बनाते हैं", "कठोर जल में बहुत ऑक्सीजन होती है", "साबुन इसमें बहुत जल्दी घुल जाता है"], "Ca²⁺ और Mg²⁺ आयन साबुन से अघुलनशील लवण (मैल) बनाते हैं, जिससे साबुन व्यर्थ होता है। डिटर्जेंट कठोर जल में भी काम करते हैं।"]),
  q(2, "general-studies", "general-science", "H", 2,
    ["The oral polio vaccine (OPV), given as drops, was developed by:", ["Jonas Salk", "Louis Pasteur", "Albert Sabin", "Edward Jenner"], "Albert Sabin developed the oral polio vaccine. Jonas Salk made the injectable (inactivated) vaccine, and Jenner the smallpox vaccine."],
    ["बूँदों के रूप में दिया जाने वाला ओरल पोलियो टीका (OPV) किसने विकसित किया?", ["जोनास साल्क", "लुई पाश्चर", "अल्बर्ट सेबिन", "एडवर्ड जेनर"], "अल्बर्ट सेबिन ने मुख से दिया जाने वाला पोलियो टीका बनाया। जोनास साल्क ने इंजेक्शन वाला (निष्क्रिय) टीका और जेनर ने चेचक का टीका बनाया।"]),

  // ───────── Section 3: Reasoning & Mathematics (20) ─────────
  q(3, "reasoning", "series", "H", 0,
    ["Find the next number in the series: 0, 7, 26, 63, ?", ["124", "125", "99", "127"], "Each term is n³ − 1: 1−1, 8−1, 27−1, 64−1, so the next is 125 − 1 = 124."],
    ["श्रृंखला की अगली संख्या ज्ञात कीजिए: 0, 7, 26, 63, ?", ["124", "125", "99", "127"], "प्रत्येक पद n³ − 1 है: 1−1, 8−1, 27−1, 64−1, अतः अगला 125 − 1 = 124।"], "5**3-1"),
  q(3, "reasoning", "series", "M", 1,
    ["Find the next number in the series: 3, 6, 18, 72, ?", ["288", "360", "216", "432"], "Multiply by 2, 3, 4, then 5: 72 × 5 = 360."],
    ["श्रृंखला की अगली संख्या ज्ञात कीजिए: 3, 6, 18, 72, ?", ["288", "360", "216", "432"], "क्रमशः 2, 3, 4 और फिर 5 से गुणा: 72 × 5 = 360।"], "72*5"),
  q(3, "reasoning", "alphabet-test", "M", 2,
    ["Find the next letter in the series: Z, X, U, Q, ?", ["M", "K", "L", "N"], "The letters go back by 2, 3, 4 and then 5: Q − 5 = L."],
    ["श्रृंखला का अगला अक्षर ज्ञात कीजिए: Z, X, U, Q, ?", ["M", "K", "L", "N"], "अक्षर क्रमशः 2, 3, 4 और फिर 5 स्थान पीछे जाते हैं: Q − 5 = L।"]),
  q(3, "reasoning", "coding-decoding", "H", 2,
    ["In a code, 'sky is blue' is written as 'ta na pa' and 'blue water' as 'pa ra'. What is the code for 'blue'?", ["ta", "na", "pa", "ra"], "'blue' is the only word common to both sentences, and 'pa' is the only code common to both. So blue = pa."],
    ["एक कूट में 'sky is blue' को 'ta na pa' और 'blue water' को 'pa ra' लिखा जाता है। 'blue' का कूट क्या है?", ["ta", "na", "pa", "ra"], "दोनों वाक्यों में केवल 'blue' समान है और दोनों कूटों में केवल 'pa' समान है। अतः blue = pa।"]),
  q(3, "reasoning", "coding-decoding", "M", 3,
    ["If every vowel in the word OFFICE is replaced by the next letter of the alphabet, what is the new word?", ["OFFJCF", "PFFJCE", "PGGJDF", "PFFJCF"], "O→P, I→J and E→F; consonants stay: PFFJCF."],
    ["यदि शब्द OFFICE के प्रत्येक स्वर को वर्णमाला के अगले अक्षर से बदल दिया जाए, तो नया शब्द क्या होगा?", ["OFFJCF", "PFFJCE", "PGGJDF", "PFFJCF"], "O→P, I→J और E→F; व्यंजन वही रहते हैं: PFFJCF।"]),
  q(3, "reasoning", "blood-relations", "H", 0,
    ["P is Q's brother. R is Q's mother. S is R's father. T is S's mother. How is P related to T?", ["Great-grandson", "Grandson", "Son", "Nephew"], "P is R's son; R is S's daughter; S is T's son. So P is T's great-grandson."],
    ["P, Q का भाई है। R, Q की माँ है। S, R का पिता है। T, S की माँ है। P का T से क्या संबंध है?", ["परपोता (प्रपौत्र)", "पोता", "पुत्र", "भतीजा"], "P, R का पुत्र है; R, S की पुत्री है; S, T का पुत्र है। अतः P, T का प्रपौत्र है।"]),
  q(3, "reasoning", "direction-sense", "H", 1,
    ["Early one morning Ram stood facing a pole, and the pole's shadow fell exactly to his right. Which direction was he facing?", ["North", "South", "East", "West"], "In the morning the sun is in the east, so shadows fall to the west. If west is on his right, he is facing south."],
    ["एक सुबह राम एक खंभे की ओर मुँह करके खड़ा था और खंभे की छाया ठीक उसके दाईं ओर पड़ी। वह किस दिशा में मुँह किए था?", ["उत्तर", "दक्षिण", "पूर्व", "पश्चिम"], "सुबह सूर्य पूर्व में होता है, इसलिए छाया पश्चिम में पड़ती है। यदि पश्चिम उसके दाईं ओर है, तो उसका मुँह दक्षिण की ओर है।"]),
  q(3, "reasoning", "ranking", "M", 2,
    ["Among five friends, A is taller than B but shorter than C. D is the tallest and E is the shortest. Who is in the middle by height?", ["B", "C", "A", "D"], "The order from tallest is D, C, A, B, E, so A is in the middle."],
    ["पाँच मित्रों में A, B से लंबा परंतु C से छोटा है। D सबसे लंबा और E सबसे छोटा है। लंबाई में बीच में कौन है?", ["B", "C", "A", "D"], "सबसे लंबे से क्रम D, C, A, B, E है, अतः A बीच में है।"]),
  q(3, "reasoning", "puzzles", "H", 3,
    ["Five people sit in a row facing north. A is at the left end and B is to the immediate right of A. C sits in the middle, E is to the immediate right of C, and D is at the right end. Who is second from the right end?", ["C", "B", "D", "E"], "From left to right the order is A, B, C, E, D. Second from the right is E."],
    ["पाँच व्यक्ति उत्तर की ओर मुँह करके एक पंक्ति में बैठे हैं। A बाएँ छोर पर है और B, A के ठीक दाएँ है। C बीच में है, E, C के ठीक दाएँ है और D दाएँ छोर पर है। दाएँ छोर से दूसरा कौन है?", ["C", "B", "D", "E"], "बाएँ से दाएँ क्रम A, B, C, E, D है। दाएँ से दूसरा E है।"]),
  q(3, "reasoning", "analogy", "M", 0,
    ["16 : 64 :: 25 : ?", ["125", "100", "625", "75"], "16 = 4² and 64 = 4³. Similarly 25 = 5², so the answer is 5³ = 125."],
    ["16 : 64 :: 25 : ?", ["125", "100", "625", "75"], "16 = 4² और 64 = 4³। इसी प्रकार 25 = 5², अतः उत्तर 5³ = 125।"], "5**3"),
  q(3, "reasoning", "series", "M", 1,
    ["Find the missing number: 2, 5, 10, 17, 26, ?", ["35", "37", "36", "39"], "Each term is n² + 1: 1+1, 4+1, 9+1, 16+1, 25+1, so the next is 36 + 1 = 37."],
    ["लुप्त संख्या ज्ञात कीजिए: 2, 5, 10, 17, 26, ?", ["35", "37", "36", "39"], "प्रत्येक पद n² + 1 है: 1+1, 4+1, 9+1, 16+1, 25+1, अतः अगला 36 + 1 = 37।"], "6*6+1"),
  q(3, "reasoning", "syllogism", "H", 2,
    ["Statements: Some pens are books. All books are tables.\nConclusions: I. Some pens are tables. II. Some tables are pens.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "The pens that are books are also tables, so some pens are tables (I). Its converse, some tables are pens (II), also follows."],
    ["कथन: कुछ पेन किताबें हैं। सभी किताबें मेज़ हैं।\nनिष्कर्ष: I. कुछ पेन मेज़ हैं। II. कुछ मेज़ पेन हैं।", ["केवल I अनुसरण करता है", "केवल II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "जो पेन किताबें हैं, वे मेज़ भी हैं, अतः कुछ पेन मेज़ हैं (I)। इसका रूपांतरण, कुछ मेज़ पेन हैं (II), भी सही है।"]),
  q(3, "quant", "percentage", "H", 3,
    ["A number is first increased by 10% and then decreased by 10%. What is the net change?", ["No change", "2% decrease", "1% increase", "1% decrease"], "100 × 1.1 × 0.9 = 99, so there is a net decrease of 1%."],
    ["किसी संख्या को पहले 10% बढ़ाया और फिर 10% घटाया जाता है। शुद्ध परिवर्तन क्या है?", ["कोई परिवर्तन नहीं", "2% कमी", "1% वृद्धि", "1% कमी"], "100 × 1.1 × 0.9 = 99, अतः 1% की शुद्ध कमी।"], "100-100*1.1*0.9"),
  q(3, "quant", "interest", "H", 0,
    ["What is the difference between compound interest and simple interest on ₹8,000 at 5% per annum for 2 years?", ["₹20", "₹40", "₹25", "₹16"], "For 2 years, CI − SI = P × (R/100)² = 8,000 × 0.05 × 0.05 = ₹20."],
    ["₹8,000 पर 5% वार्षिक दर से 2 वर्ष के चक्रवृद्धि और साधारण ब्याज का अंतर कितना है?", ["₹20", "₹40", "₹25", "₹16"], "2 वर्ष के लिए CI − SI = P × (R/100)² = 8,000 × 0.05 × 0.05 = ₹20।"], "8000*0.05*0.05"),
  q(3, "quant", "average", "M", 1,
    ["The average of 10 numbers is 15. If 3 is added to each number, what is the new average?", ["15", "18", "45", "16.5"], "Adding the same number to every value increases the average by that number: 15 + 3 = 18."],
    ["10 संख्याओं का औसत 15 है। प्रत्येक संख्या में 3 जोड़ने पर नया औसत क्या होगा?", ["15", "18", "45", "16.5"], "हर मान में समान संख्या जोड़ने से औसत उतना ही बढ़ता है: 15 + 3 = 18।"], "15+3"),
  q(3, "quant", "speed-distance", "M", 2,
    ["A bus covers 360 km in 5 hours. What is its speed in metres per second?", ["18 m/s", "25 m/s", "20 m/s", "22 m/s"], "Speed = 360 ÷ 5 = 72 km/h = 72 × 5/18 = 20 m/s."],
    ["एक बस 5 घंटे में 360 किमी चलती है। उसकी चाल मीटर प्रति सेकंड में क्या है?", ["18 मी/से", "25 मी/से", "20 मी/से", "22 मी/से"], "चाल = 360 ÷ 5 = 72 किमी/घंटा = 72 × 5/18 = 20 मी/से।"], "360/5*5/18"),
  q(3, "quant", "time-work", "M", 3,
    ["10 men can build a wall in 12 days. In how many days can 8 men build the same wall?", ["10", "14", "16", "15"], "Work = 10 × 12 = 120 man-days. Days for 8 men = 120 ÷ 8 = 15."],
    ["10 आदमी एक दीवार 12 दिन में बनाते हैं। 8 आदमी वही दीवार कितने दिन में बनाएँगे?", ["10", "14", "16", "15"], "कार्य = 10 × 12 = 120 मानव-दिवस। 8 आदमियों के लिए दिन = 120 ÷ 8 = 15।"], "10*12/8"),
  q(3, "quant", "mixture-alligation", "H", 0,
    ["A 40-litre can contains milk and water in the ratio 5 : 3. How much water must be added to make the ratio 1 : 1?", ["10 litres", "8 litres", "12 litres", "15 litres"], "Milk = 25 L and water = 15 L. For 1 : 1, water must be 25 L, so add 10 L."],
    ["40 लीटर के एक डिब्बे में दूध और पानी 5 : 3 के अनुपात में हैं। अनुपात 1 : 1 करने के लिए कितना पानी मिलाना होगा?", ["10 लीटर", "8 लीटर", "12 लीटर", "15 लीटर"], "दूध = 25 लीटर और पानी = 15 लीटर। 1 : 1 के लिए पानी 25 लीटर होना चाहिए, अतः 10 लीटर मिलाएँ।"], "40*5/8-40*3/8"),
  q(3, "quant", "partnership", "H", 1,
    ["A invests ₹20,000 for 12 months and B invests ₹30,000 for 6 months in a business. Out of a profit of ₹14,000, what is A's share?", ["₹6,000", "₹8,000", "₹7,000", "₹8,400"], "Ratio = 20,000 × 12 : 30,000 × 6 = 2,40,000 : 1,80,000 = 4 : 3. A's share = 14,000 × 4/7 = ₹8,000."],
    ["एक व्यापार में A ₹20,000 12 महीने के लिए और B ₹30,000 6 महीने के लिए लगाता है। ₹14,000 के लाभ में A का हिस्सा क्या है?", ["₹6,000", "₹8,000", "₹7,000", "₹8,400"], "अनुपात = 20,000 × 12 : 30,000 × 6 = 2,40,000 : 1,80,000 = 4 : 3। A का हिस्सा = 14,000 × 4/7 = ₹8,000।"], "14000*4/7"),
  q(3, "quant", "mensuration", "M", 2,
    ["The perimeter of a square is 48 cm. What is its area?", ["96 sq cm", "196 sq cm", "144 sq cm", "124 sq cm"], "Side = 48 ÷ 4 = 12 cm. Area = 12 × 12 = 144 sq cm."],
    ["एक वर्ग का परिमाप 48 सेमी है। उसका क्षेत्रफल क्या है?", ["96 वर्ग सेमी", "196 वर्ग सेमी", "144 वर्ग सेमी", "124 वर्ग सेमी"], "भुजा = 48 ÷ 4 = 12 सेमी। क्षेत्रफल = 12 × 12 = 144 वर्ग सेमी।"], "(48/4)**2"),

  // ───────── Section 4: Hindi & English (20) ─────────
  q(4, "hindi", "sandhi-samas", "H", 3,
    ["Choose the correct sandhi split of 'नयन':", ["नय + न", "नै + अन", "नय + अन", "ने + अन"], "ने + अन = नयन. ए + अ = अय, which is Ayadi sandhi."],
    ["'नयन' का सही संधि-विच्छेद चुनिए:", ["नय + न", "नै + अन", "नय + अन", "ने + अन"], "ने + अन = नयन। ए + अ = अय, यह अयादि संधि है।"]),
  q(4, "hindi", "sandhi-samas", "H", 0,
    ["Choose the correct sandhi split of 'सदैव':", ["सदा + एव", "सद + एव", "सदे + एव", "सदा + ऐव"], "सदा + एव = सदैव. आ + ए = ऐ, which is Vriddhi sandhi."],
    ["'सदैव' का सही संधि-विच्छेद चुनिए:", ["सदा + एव", "सद + एव", "सदे + एव", "सदा + ऐव"], "सदा + एव = सदैव। आ + ए = ऐ, यह वृद्धि संधि है।"]),
  q(4, "hindi", "sandhi-samas", "M", 1,
    ["Identify the samas in 'त्रिभुवन':", ["Tatpurush", "Dvigu", "Bahuvrihi", "Avyayibhav"], "त्रिभुवन = तीन भुवनों का समूह. The first word is a number and the whole denotes a group, so it is Dvigu samas."],
    ["'त्रिभुवन' में कौन-सा समास है?", ["तत्पुरुष", "द्विगु", "बहुव्रीहि", "अव्ययीभाव"], "त्रिभुवन = तीन भुवनों का समूह। पहला पद संख्यावाचक है और समूह का बोध होता है, अतः द्विगु समास है।"]),
  q(4, "hindi", "sandhi-samas", "M", 2,
    ["Identify the samas in 'गंगाजल':", ["Dvandva", "Karmadharaya", "Tatpurush", "Dvigu"], "गंगाजल = गंगा का जल. The case-ending 'का' is dropped, so it is Tatpurush (Sambandh) samas."],
    ["'गंगाजल' में कौन-सा समास है?", ["द्वंद्व", "कर्मधारय", "तत्पुरुष", "द्विगु"], "गंगाजल = गंगा का जल। 'का' विभक्ति का लोप है, अतः तत्पुरुष (संबंध) समास है।"]),
  q(4, "hindi", "paryay-vilom", "M", 3,
    ["Which word is a synonym of 'सूर्य'?", ["निशाकर", "सुधाकर", "हिमांशु", "दिवाकर"], "दिवाकर, भानु, रवि and दिनकर mean the sun. निशाकर, सुधाकर and हिमांशु mean the moon."],
    ["'सूर्य' का पर्यायवाची शब्द कौन-सा है?", ["निशाकर", "सुधाकर", "हिमांशु", "दिवाकर"], "दिवाकर, भानु, रवि और दिनकर सूर्य के पर्यायवाची हैं। निशाकर, सुधाकर और हिमांशु चंद्रमा के पर्यायवाची हैं।"]),
  q(4, "hindi", "paryay-vilom", "M", 0,
    ["What is the antonym of 'स्वतंत्र'?", ["परतंत्र", "स्वाधीन", "मुक्त", "निर्भर"], "स्वतंत्र means independent; its opposite is परतंत्र (dependent, under another's rule)."],
    ["'स्वतंत्र' का विलोम शब्द क्या है?", ["परतंत्र", "स्वाधीन", "मुक्त", "निर्भर"], "स्वतंत्र का विलोम परतंत्र है।"]),
  q(4, "hindi", "muhavare", "M", 1,
    ["What does the Hindi idiom 'आग बबूला होना' mean?", ["To catch fire", "To become very angry", "To be very happy", "To feel cold"], "'आग बबूला होना' means to fly into a rage."],
    ["'आग बबूला होना' मुहावरे का अर्थ क्या है?", ["आग लग जाना", "बहुत क्रोधित होना", "बहुत प्रसन्न होना", "ठंड लगना"], "'आग बबूला होना' का अर्थ है अत्यधिक क्रोधित होना।"]),
  q(4, "hindi", "ek-shabd", "M", 2,
    ["One word for 'जो दूसरों पर निर्भर हो':", ["आत्मनिर्भर", "स्वावलंबी", "परावलंबी", "स्वाश्रयी"], "परावलंबी (or पराश्रित) = dependent on others. आत्मनिर्भर, स्वावलंबी and स्वाश्रयी mean self-reliant."],
    ["'जो दूसरों पर निर्भर हो' के लिए एक शब्द:", ["आत्मनिर्भर", "स्वावलंबी", "परावलंबी", "स्वाश्रयी"], "परावलंबी (या पराश्रित) = दूसरों पर निर्भर। आत्मनिर्भर, स्वावलंबी और स्वाश्रयी का अर्थ है अपने पर निर्भर।"]),
  q(4, "hindi", "vyakaran", "H", 3,
    ["What is the grammatical gender (ling) of the Hindi word 'दही'?", ["Feminine", "Neuter", "Common gender", "Masculine"], "In standard Hindi 'दही' is masculine: 'दही खट्टा है', not 'खट्टी'."],
    ["हिंदी शब्द 'दही' का लिंग क्या है?", ["स्त्रीलिंग", "नपुंसकलिंग", "उभयलिंग", "पुल्लिंग"], "मानक हिंदी में 'दही' पुल्लिंग है: 'दही खट्टा है', 'खट्टी' नहीं।"]),
  q(4, "hindi", "vyakaran", "H", 0,
    ["Which of these Hindi sentences is grammatically correct?", ["मैंने उसे एक पुस्तक दी।", "मैं उसे एक पुस्तक दी।", "मैंने उसको एक पुस्तक दिया।", "मुझे उसे एक पुस्तक दी।"], "With a transitive verb in the past tense, the subject takes 'ने' and the verb agrees with the object: पुस्तक (feminine) → दी. So 'मैंने उसे एक पुस्तक दी।'"],
    ["निम्नलिखित में से व्याकरण की दृष्टि से शुद्ध वाक्य कौन-सा है?", ["मैंने उसे एक पुस्तक दी।", "मैं उसे एक पुस्तक दी।", "मैंने उसको एक पुस्तक दिया।", "मुझे उसे एक पुस्तक दी।"], "भूतकाल में सकर्मक क्रिया के साथ कर्ता के बाद 'ने' आता है और क्रिया कर्म के अनुसार होती है: पुस्तक (स्त्रीलिंग) → दी। अतः 'मैंने उसे एक पुस्तक दी।'"]),
  q(4, "english", "synonyms-antonyms", "M", 1,
    ["Choose the word closest in meaning to 'AMBIGUOUS':", ["Clear", "Unclear", "Ambitious", "Accurate"], "'Ambiguous' means open to more than one meaning, i.e. unclear."],
    ["'AMBIGUOUS' के अर्थ के सबसे निकट शब्द चुनिए:", ["Clear", "Unclear", "Ambitious", "Accurate"], "'Ambiguous' का अर्थ है जिसके एक से अधिक अर्थ निकलें, यानी unclear (अस्पष्ट)।"]),
  q(4, "english", "synonyms-antonyms", "M", 2,
    ["Choose the word opposite in meaning to 'ANCIENT':", ["Old", "Antique", "Modern", "Historic"], "'Ancient' means very old; its opposite is 'modern'."],
    ["'ANCIENT' के विपरीत अर्थ वाला शब्द चुनिए:", ["Old", "Antique", "Modern", "Historic"], "'Ancient' का अर्थ है बहुत पुराना; इसका विलोम 'modern' (आधुनिक) है।"]),
  q(4, "english", "grammar", "H", 3,
    ["Fill in the blank: 'The Pradhan, along with the ward members, ___ visited the flood-hit area.'", ["have", "were", "are", "has"], "Words joined by 'along with' do not change the subject. The subject is 'the Pradhan' (singular), so 'has' is correct."],
    ["रिक्त स्थान भरिए: 'The Pradhan, along with the ward members, ___ visited the flood-hit area.'", ["have", "were", "are", "has"], "'Along with' से जुड़े शब्द कर्ता नहीं बदलते। कर्ता 'the Pradhan' (एकवचन) है, अतः 'has' सही है।"]),
  q(4, "english", "error-spotting", "H", 0,
    ["Find the part with an error: 'I have seen (A) / him at the BDO office (B) / yesterday. (C) / No error (D)'", ["A", "B", "C", "D"], "The present perfect is not used with a definite past time like 'yesterday'. It should be 'I saw him'. The error is in part A."],
    ["त्रुटि वाला भाग चुनिए: 'I have seen (A) / him at the BDO office (B) / yesterday. (C) / No error (D)'", ["A", "B", "C", "D"], "'Yesterday' जैसे निश्चित भूतकाल के साथ present perfect नहीं आता। 'I saw him' होना चाहिए। त्रुटि भाग A में है।"]),
  q(4, "english", "grammar", "M", 1,
    ["Fill in the blank: 'The Panchayat Secretary was absent ___ the Gram Sabha meeting.'", ["in", "from", "at", "of"], "'Absent from' is the correct phrase: absent from the meeting."],
    ["रिक्त स्थान भरिए: 'The Panchayat Secretary was absent ___ the Gram Sabha meeting.'", ["in", "from", "at", "of"], "सही प्रयोग 'absent from' है: absent from the meeting।"]),
  q(4, "english", "voice-speech", "H", 2,
    ["Change into passive voice: 'They are building a new Panchayat Ghar.'", ["A new Panchayat Ghar is built by them.", "A new Panchayat Ghar has been built by them.", "A new Panchayat Ghar is being built by them.", "A new Panchayat Ghar was being built by them."], "Present continuous active (are building) becomes 'is/are being + past participle': is being built."],
    ["कर्मवाच्य में बदलिए: 'They are building a new Panchayat Ghar.'", ["A new Panchayat Ghar is built by them.", "A new Panchayat Ghar has been built by them.", "A new Panchayat Ghar is being built by them.", "A new Panchayat Ghar was being built by them."], "Present continuous (are building) का passive 'is/are being + past participle' से बनता है: is being built।"]),
  q(4, "english", "idioms", "M", 3,
    ["What does the idiom 'to see eye to eye' mean?", ["To stare at someone", "To have good eyesight", "To quarrel", "To agree fully"], "'To see eye to eye' means to have the same opinion as someone."],
    ["मुहावरे 'to see eye to eye' का अर्थ क्या है?", ["किसी को घूरना", "अच्छी दृष्टि होना", "झगड़ना", "पूरी तरह सहमत होना"], "'To see eye to eye' का अर्थ है किसी से पूरी तरह सहमत होना।"]),
  q(4, "english", "one-word", "M", 0,
    ["One word for 'a government of the people, by the people, for the people':", ["Democracy", "Monarchy", "Autocracy", "Oligarchy"], "Lincoln's famous definition describes democracy. Monarchy is rule by a king, autocracy by one person and oligarchy by a few."],
    ["'a government of the people, by the people, for the people' के लिए एक शब्द:", ["Democracy", "Monarchy", "Autocracy", "Oligarchy"], "लिंकन की प्रसिद्ध परिभाषा लोकतंत्र (democracy) की है। Monarchy = राजतंत्र, autocracy = एक व्यक्ति का शासन, oligarchy = कुछ लोगों का शासन।"]),
  q(4, "english", "grammar", "M", 1,
    ["Choose the correct question tag: 'She can't drive a car, ___?'", ["can't she", "can she", "does she", "doesn't she"], "A negative statement takes a positive tag with the same auxiliary: 'She can't…, can she?'"],
    ["सही question tag चुनिए: 'She can't drive a car, ___?'", ["can't she", "can she", "does she", "doesn't she"], "नकारात्मक वाक्य के साथ उसी सहायक क्रिया का सकारात्मक tag आता है: 'She can't…, can she?'"]),
  q(4, "english", "spelling", "H", 2,
    ["Which spelling of the word meaning 'to divide or keep apart' is correct?", ["Seperate", "Separete", "Separate", "Saparate"], "The correct spelling is 'separate', with 'par' in the middle."],
    ["'अलग करना' अर्थ वाले शब्द की सही वर्तनी कौन-सी है?", ["Seperate", "Separete", "Separate", "Saparate"], "सही वर्तनी 'separate' है, जिसके बीच में 'par' आता है।"]),

  // ───────── Section 5: Panchayati Raj, Rural Development & Computer (25) ─────────
  q(5, "panchayati-raj", "constitution", "H", 3,
    ["Under Article 243N, State laws on Panchayats that were inconsistent with Part IX could continue for how long after the 73rd Amendment?", ["Six months", "Three years", "Five years", "One year"], "Article 243N let such laws continue for up to one year from the commencement of the 73rd Amendment, unless amended or repealed earlier."],
    ["अनुच्छेद 243N के अनुसार भाग IX से असंगत पंचायत संबंधी राज्य कानून 73वें संशोधन के बाद कितने समय तक चल सकते थे?", ["छह महीने", "तीन वर्ष", "पाँच वर्ष", "एक वर्ष"], "अनुच्छेद 243N ने ऐसे कानूनों को 73वें संशोधन के लागू होने से अधिकतम एक वर्ष तक चलने दिया, जब तक पहले संशोधित या निरस्त न हों।"]),
  q(5, "panchayati-raj", "constitution", "H", 0,
    ["Which Article bars courts from interfering in electoral matters of Panchayats, such as delimitation of constituencies?", ["Article 243O", "Article 243K", "Article 243M", "Article 329"], "Article 243O bars courts from questioning laws on delimitation or seat allotment; a Panchayat election can be challenged only through an election petition."],
    ["कौन-सा अनुच्छेद पंचायतों के निर्वाचन मामलों, जैसे निर्वाचन क्षेत्रों के परिसीमन, में न्यायालयों के हस्तक्षेप पर रोक लगाता है?", ["अनुच्छेद 243O", "अनुच्छेद 243K", "अनुच्छेद 243M", "अनुच्छेद 329"], "अनुच्छेद 243O परिसीमन या सीट आवंटन के कानूनों को न्यायालय में चुनौती देने पर रोक लगाता है; पंचायत चुनाव को केवल चुनाव याचिका से चुनौती दी जा सकती है।"]),
  q(5, "panchayati-raj", "constitution", "M", 1,
    ["Under Article 243(d), 'Panchayat' means:", ["a court of village elders", "an institution of self-government for rural areas", "a cooperative society", "a block office of the State Government"], "Article 243(d) defines a Panchayat as an institution (by whatever name called) of self-government constituted under Article 243B for the rural areas."],
    ["अनुच्छेद 243(d) के अनुसार 'पंचायत' का अर्थ है:", ["गाँव के बुज़ुर्गों का न्यायालय", "ग्रामीण क्षेत्रों के लिए स्वशासन की संस्था", "एक सहकारी समिति", "राज्य सरकार का प्रखंड कार्यालय"], "अनुच्छेद 243(d) पंचायत को ग्रामीण क्षेत्रों के लिए अनुच्छेद 243B के अधीन गठित स्वशासन की संस्था (चाहे किसी भी नाम से हो) कहता है।"]),
  q(5, "panchayati-raj", "constitution", "M", 2,
    ["Subjects such as drinking water, minor irrigation and rural housing, which may be entrusted to Panchayats, are listed in the:", ["Seventh Schedule", "Twelfth Schedule", "Eleventh Schedule", "Tenth Schedule"], "The Eleventh Schedule lists the 29 subjects for Panchayats. The Twelfth lists 18 subjects for Municipalities."],
    ["पेयजल, लघु सिंचाई और ग्रामीण आवास जैसे विषय, जो पंचायतों को सौंपे जा सकते हैं, किस अनुसूची में हैं?", ["सातवीं अनुसूची", "बारहवीं अनुसूची", "ग्यारहवीं अनुसूची", "दसवीं अनुसूची"], "ग्यारहवीं अनुसूची में पंचायतों के 29 विषय हैं। बारहवीं में नगरपालिकाओं के 18 विषय हैं।"]),
  q(5, "panchayati-raj", "committees-history", "H", 3,
    ["The 64th Constitutional Amendment Bill (1989) on Panchayati Raj, which failed in the Rajya Sabha, was introduced by the government of:", ["V.P. Singh", "P.V. Narasimha Rao", "Indira Gandhi", "Rajiv Gandhi"], "Rajiv Gandhi's government introduced the 64th Amendment Bill in 1989; it passed the Lok Sabha but was defeated in the Rajya Sabha."],
    ["पंचायती राज पर 64वाँ संविधान संशोधन विधेयक (1989), जो राज्यसभा में गिर गया, किसकी सरकार ने पेश किया था?", ["वी.पी. सिंह", "पी.वी. नरसिंह राव", "इंदिरा गांधी", "राजीव गांधी"], "राजीव गांधी सरकार ने 1989 में 64वाँ संशोधन विधेयक पेश किया; यह लोकसभा में पारित हुआ परंतु राज्यसभा में गिर गया।"]),
  q(5, "panchayati-raj", "committees-history", "M", 0,
    ["The 73rd Constitutional Amendment was passed by Parliament during the prime ministership of:", ["P.V. Narasimha Rao", "Rajiv Gandhi", "Atal Bihari Vajpayee", "Chandra Shekhar"], "The 73rd and 74th Amendments were passed in December 1992 under P.V. Narasimha Rao and came into force in 1993."],
    ["73वाँ संविधान संशोधन संसद ने किस प्रधानमंत्री के कार्यकाल में पारित किया?", ["पी.वी. नरसिंह राव", "राजीव गांधी", "अटल बिहारी वाजपेयी", "चंद्रशेखर"], "73वाँ और 74वाँ संशोधन दिसंबर 1992 में पी.वी. नरसिंह राव के कार्यकाल में पारित हुए और 1993 में लागू हुए।"]),
  q(5, "panchayati-raj", "hp-act", "M", 1,
    ["Elections to Panchayati Raj Institutions in Himachal Pradesh are conducted by the:", ["Election Commission of India", "State Election Commission, Himachal Pradesh", "Deputy Commissioner of each district", "HP Public Service Commission"], "Under Article 243K and the HP Panchayati Raj Act, 1994, the State Election Commission, Himachal Pradesh, prepares rolls and conducts PRI elections."],
    ["हिमाचल प्रदेश में पंचायती राज संस्थाओं के चुनाव कौन कराता है?", ["भारत निर्वाचन आयोग", "राज्य निर्वाचन आयोग, हिमाचल प्रदेश", "प्रत्येक जिले का उपायुक्त", "हिमाचल प्रदेश लोक सेवा आयोग"], "अनुच्छेद 243K और हिमाचल प्रदेश पंचायती राज अधिनियम, 1994 के अनुसार राज्य निर्वाचन आयोग, हिमाचल प्रदेश मतदाता सूची बनाता और पंचायती राज चुनाव कराता है।"]),
  q(5, "panchayati-raj", "hp-act", "M", 2,
    ["In Himachal Pradesh, which officer heads the development block and works as the executive officer of the Panchayat Samiti?", ["Tehsildar", "District Panchayat Officer", "Block Development Officer", "Sub-Divisional Magistrate"], "The Block Development Officer (BDO) heads the block and acts as executive officer of the Panchayat Samiti, supervising the Panchayat Secretaries of the block."],
    ["हिमाचल प्रदेश में कौन-सा अधिकारी विकास खंड का प्रमुख होता है और पंचायत समिति के कार्यकारी अधिकारी के रूप में कार्य करता है?", ["तहसीलदार", "ज़िला पंचायत अधिकारी", "खंड विकास अधिकारी", "उपमंडल दंडाधिकारी"], "खंड विकास अधिकारी (BDO) खंड का प्रमुख होता है और पंचायत समिति के कार्यकारी अधिकारी के रूप में खंड के पंचायत सचिवों की निगरानी करता है।"]),
  q(5, "panchayati-raj", "hp-act", "H", 3,
    ["At the district level in Himachal Pradesh, the officer of the Panchayati Raj Department who supervises panchayat work and staff is the:", ["Deputy Commissioner", "District Rural Development Agency chairman", "Assistant Commissioner (Development)", "District Panchayat Officer"], "The District Panchayat Officer (DPO) oversees the Gram Panchayats, their accounts and staff in the district on behalf of the Panchayati Raj Department."],
    ["हिमाचल प्रदेश में ज़िला स्तर पर पंचायत कार्य और कर्मचारियों की निगरानी करने वाला पंचायती राज विभाग का अधिकारी कौन होता है?", ["उपायुक्त", "ज़िला ग्रामीण विकास अभिकरण अध्यक्ष", "सहायक आयुक्त (विकास)", "ज़िला पंचायत अधिकारी"], "ज़िला पंचायत अधिकारी (DPO) पंचायती राज विभाग की ओर से ज़िले की ग्राम पंचायतों, उनके लेखों और कर्मचारियों की निगरानी करता है।"]),
  q(5, "panchayati-raj", "schemes", "M", 0,
    ["Under PM-KISAN, eligible farmer families receive how much income support per year?", ["₹6,000 in three instalments", "₹10,000 in two instalments", "₹12,000 in four instalments", "₹5,000 in one instalment"], "PM-KISAN (2019) gives ₹6,000 a year in three instalments of ₹2,000 directly into farmers' bank accounts."],
    ["PM-KISAN में पात्र किसान परिवारों को प्रति वर्ष कितनी आय सहायता मिलती है?", ["₹6,000, तीन किस्तों में", "₹10,000, दो किस्तों में", "₹12,000, चार किस्तों में", "₹5,000, एक किस्त में"], "PM-KISAN (2019) में किसानों के बैंक खाते में सीधे ₹2,000 की तीन किस्तों में सालाना ₹6,000 दिए जाते हैं।"]),
  q(5, "panchayati-raj", "schemes", "M", 1,
    ["Ayushman Bharat – PM Jan Arogya Yojana provides a health cover of up to how much per family per year?", ["₹1 lakh", "₹5 lakh", "₹2 lakh", "₹10 lakh"], "AB-PMJAY gives cashless hospital treatment of up to ₹5 lakh per family per year at empanelled hospitals."],
    ["आयुष्मान भारत – प्रधानमंत्री जन आरोग्य योजना प्रति परिवार प्रति वर्ष कितने तक का स्वास्थ्य कवर देती है?", ["₹1 लाख", "₹5 लाख", "₹2 लाख", "₹10 लाख"], "AB-PMJAY सूचीबद्ध अस्पतालों में प्रति परिवार प्रति वर्ष ₹5 लाख तक का कैशलेस इलाज देती है।"]),
  q(5, "panchayati-raj", "schemes", "H", 2,
    ["Under MGNREGA, a crèche must be provided at a worksite if the number of children below six years accompanying the women workers is more than:", ["two", "ten", "five", "twenty"], "Schedule II of MGNREGA requires a person to look after the children (crèche) if more than five children below six years come with the women workers."],
    ["मनरेगा में कार्यस्थल पर शिशुगृह (क्रेच) तब देना होता है जब महिला श्रमिकों के साथ आए छह वर्ष से कम आयु के बच्चों की संख्या इससे अधिक हो:", ["दो", "दस", "पाँच", "बीस"], "मनरेगा की अनुसूची II के अनुसार यदि महिला श्रमिकों के साथ छह वर्ष से कम के पाँच से अधिक बच्चे हों, तो उनकी देखभाल (क्रेच) के लिए एक व्यक्ति रखना होता है।"]),
  q(5, "panchayati-raj", "schemes", "H", 3,
    ["Under MGNREGA, wages must be paid within how many days after the closure of the muster roll?", ["7 days", "30 days", "21 days", "15 days"], "Wages are to be paid within 15 days of the closure of the muster roll; delays beyond that entitle workers to compensation."],
    ["मनरेगा में मस्टर रोल बंद होने के कितने दिनों के भीतर मज़दूरी का भुगतान करना होता है?", ["7 दिन", "30 दिन", "21 दिन", "15 दिन"], "मस्टर रोल बंद होने के 15 दिनों के भीतर मज़दूरी देनी होती है; इससे अधिक देरी पर श्रमिकों को मुआवज़ा मिलता है।"]),
  q(5, "panchayati-raj", "schemes", "H", 0,
    ["Mission Antyodaya, run by the Ministry of Rural Development, is best known for:", ["an annual survey that ranks Gram Panchayats on development gaps", "free LPG connections", "giving loans to SHGs", "building toilets"], "Mission Antyodaya (2017) conducts an annual survey of Gram Panchayats on infrastructure and services and ranks them to guide the GPDP."],
    ["ग्रामीण विकास मंत्रालय का मिशन अंत्योदय मुख्यतः किसके लिए जाना जाता है?", ["ग्राम पंचायतों को विकास की कमियों के आधार पर क्रम देने वाले वार्षिक सर्वे के लिए", "मुफ़्त LPG कनेक्शन के लिए", "स्वयं सहायता समूहों को ऋण देने के लिए", "शौचालय बनाने के लिए"], "मिशन अंत्योदय (2017) ग्राम पंचायतों में बुनियादी ढाँचे और सेवाओं का वार्षिक सर्वे कर उन्हें क्रम देता है, जिससे GPDP बनाने में मदद मिलती है।"]),
  q(5, "panchayati-raj", "schemes", "H", 1,
    ["Under the Saansad Adarsh Gram Yojana, launched on 11 October 2014, each Member of Parliament is expected to:", ["build a hospital in the constituency", "adopt and develop model villages (Adarsh Grams)", "give scholarships to students", "audit Gram Panchayat accounts"], "Under SAGY, launched on Jayaprakash Narayan's birth anniversary, each MP adopts Gram Panchayats and develops them into model villages."],
    ["11 अक्टूबर 2014 को शुरू की गई सांसद आदर्श ग्राम योजना में प्रत्येक सांसद से क्या अपेक्षित है?", ["क्षेत्र में एक अस्पताल बनाना", "आदर्श ग्राम गोद लेकर विकसित करना", "विद्यार्थियों को छात्रवृत्ति देना", "ग्राम पंचायत के लेखों का अंकेक्षण करना"], "जयप्रकाश नारायण की जयंती पर शुरू हुई SAGY में हर सांसद ग्राम पंचायतें गोद लेकर उन्हें आदर्श गाँव बनाता है।"]),
  q(5, "panchayati-raj", "accounts-office", "H", 2,
    ["A bank reconciliation statement prepared by a Panchayat is used to:", ["calculate taxes due", "record attendance of workers", "explain differences between the cash book's bank balance and the bank passbook", "list the assets of the Panchayat"], "It matches the bank column of the cash book with the passbook and explains differences such as cheques issued but not yet presented."],
    ["पंचायत द्वारा बनाया गया बैंक समाधान विवरण (bank reconciliation statement) किसलिए प्रयोग होता है?", ["देय करों की गणना के लिए", "श्रमिकों की उपस्थिति दर्ज करने के लिए", "रोकड़ बही के बैंक शेष और बैंक पासबुक के अंतर को स्पष्ट करने के लिए", "पंचायत की परिसंपत्तियों की सूची के लिए"], "यह रोकड़ बही के बैंक कॉलम को पासबुक से मिलाता है और जारी पर अभी प्रस्तुत न हुए चेक जैसे अंतरों को स्पष्ट करता है।"]),
  q(5, "panchayati-raj", "accounts-office", "M", 3,
    ["In MGNREGA and panchayat works, a 'muster roll' is used to record:", ["the stock of cement", "minutes of the Gram Sabha", "taxes collected", "attendance and wages of the workers"], "The muster roll records each worker's daily attendance and wages for a work; it must be kept at the worksite and is checked in the social audit."],
    ["मनरेगा और पंचायत कार्यों में 'मस्टर रोल' का प्रयोग किसे दर्ज करने के लिए होता है?", ["सीमेंट के भंडार को", "ग्राम सभा के कार्यवृत्त को", "वसूले गए करों को", "श्रमिकों की उपस्थिति और मज़दूरी को"], "मस्टर रोल में किसी कार्य पर हर श्रमिक की दैनिक उपस्थिति और मज़दूरी दर्ज होती है; यह कार्यस्थल पर रखा जाता है और सामाजिक अंकेक्षण में जाँचा जाता है।"]),
  q(5, "computer", "hardware", "M", 0,
    ["Which memory is written permanently by the manufacturer and contains the start-up instructions of a computer?", ["ROM", "RAM", "Cache", "Hard disk"], "ROM (Read Only Memory) holds the firmware (BIOS/UEFI) that starts the computer; its contents stay without power."],
    ["कौन-सी मेमोरी निर्माता द्वारा स्थायी रूप से लिखी जाती है और उसमें कंप्यूटर शुरू करने के निर्देश होते हैं?", ["ROM", "RAM", "कैश", "हार्ड डिस्क"], "ROM (रीड ओनली मेमोरी) में कंप्यूटर शुरू करने वाला फ़र्मवेयर (BIOS/UEFI) होता है; बिजली न होने पर भी इसका डेटा रहता है।"]),
  q(5, "computer", "ms-office", "H", 1,
    ["In MS Excel, what does the formula =ROUND(12.567, 1) return?", ["12.5", "12.6", "13", "12.57"], "ROUND rounds to the given number of decimal places. To one place, 12.567 becomes 12.6."],
    ["MS Excel में सूत्र =ROUND(12.567, 1) क्या परिणाम देगा?", ["12.5", "12.6", "13", "12.57"], "ROUND दी गई दशमलव संख्या तक पूर्णांकन करता है। एक दशमलव तक 12.567 = 12.6।"], "Math.round(12.567*10)/10"),
  q(5, "computer", "shortcuts", "M", 2,
    ["Which function key starts the spelling and grammar check in MS Word?", ["F5", "F12", "F7", "F2"], "F7 opens Spelling & Grammar (Editor). F12 opens Save As and F5 opens Find and Replace (Go To) in Word."],
    ["MS Word में वर्तनी और व्याकरण जाँच कौन-सी फ़ंक्शन कुंजी शुरू करती है?", ["F5", "F12", "F7", "F2"], "F7 वर्तनी व व्याकरण (Editor) खोलता है। Word में F12 Save As और F5 Find and Replace (Go To) खोलता है।"]),
  q(5, "computer", "hardware", "E", 3,
    ["Which of these is an input device?", ["Monitor", "Printer", "Speaker", "Scanner"], "A scanner sends images of documents into the computer. Monitors, printers and speakers are output devices."],
    ["इनमें से कौन-सा इनपुट उपकरण है?", ["मॉनिटर", "प्रिंटर", "स्पीकर", "स्कैनर"], "स्कैनर दस्तावेज़ों की छवि कंप्यूटर में भेजता है। मॉनिटर, प्रिंटर और स्पीकर आउटपुट उपकरण हैं।"]),
  q(5, "computer", "shortcuts", "M", 0,
    ["In Windows, which shortcut closes the active window or program?", ["Alt + F4", "Ctrl + W + Q", "Shift + Delete", "Ctrl + Esc"], "Alt + F4 closes the active window; on the desktop it opens the Shut Down dialog. Shift + Delete deletes a file permanently."],
    ["Windows में कौन-सा शॉर्टकट सक्रिय विंडो या प्रोग्राम को बंद करता है?", ["Alt + F4", "Ctrl + W + Q", "Shift + Delete", "Ctrl + Esc"], "Alt + F4 सक्रिय विंडो बंद करता है; डेस्कटॉप पर यह Shut Down डायलॉग खोलता है। Shift + Delete फ़ाइल को स्थायी रूप से मिटाता है।"]),
  q(5, "computer", "internet-networking", "M", 1,
    ["Gmail and Outlook.com are examples of:", ["operating systems", "web-based e-mail services", "search engines", "antivirus programs"], "Gmail and Outlook.com are web mail services that can be used in any browser."],
    ["Gmail और Outlook.com किसके उदाहरण हैं?", ["ऑपरेटिंग सिस्टम", "वेब-आधारित ई-मेल सेवाएँ", "सर्च इंजन", "एंटीवायरस प्रोग्राम"], "Gmail और Outlook.com वेब मेल सेवाएँ हैं, जिन्हें किसी भी ब्राउज़र में प्रयोग किया जा सकता है।"]),
  q(5, "computer", "software", "E", 2,
    ["Which of these file extensions is used for an image?", [".docx", ".mp3", ".jpg", ".xlsx"], ".jpg (JPEG) is a common image format. .docx is a Word file, .mp3 audio and .xlsx an Excel workbook."],
    ["इनमें से कौन-सा फ़ाइल एक्सटेंशन चित्र (image) के लिए है?", [".docx", ".mp3", ".jpg", ".xlsx"], ".jpg (JPEG) सामान्य चित्र प्रारूप है। .docx Word फ़ाइल, .mp3 ऑडियो और .xlsx Excel वर्कबुक है।"]),
  q(5, "computer", "digital-literacy", "M", 3,
    ["In digital payments, what does UPI stand for?", ["Universal Payment Index", "United Postal Interface", "Unique Payment Identity", "Unified Payments Interface"], "UPI (Unified Payments Interface), run by NPCI since 2016, allows instant bank-to-bank transfers through a mobile app."],
    ["डिजिटल भुगतान में UPI का पूर्ण रूप क्या है?", ["Universal Payment Index", "United Postal Interface", "Unique Payment Identity", "Unified Payments Interface"], "2016 से NPCI द्वारा संचालित UPI (Unified Payments Interface) मोबाइल ऐप से तुरंत बैंक-से-बैंक भुगतान की सुविधा देता है।"]),
];
