// HP Panchayat Secretary Full Mock 2 — 120 questions (25 HP GK, 20 Social Science, 10 Everyday Science, 20 Reasoning & Maths,
// 20 Hindi & English, 25 Panchayati Raj, Rural Development & Computer).

import { q, type PanchayatQuestion } from "./types";

export const mock2: PanchayatQuestion[] = [
  // ───────── Section 0: Himachal GK & Current Affairs (25) ─────────
  q(0, "hp-gk", "polity-administration", "H", 1,
    ["Tapovan, where the winter session of the Himachal Pradesh Vidhan Sabha is held, is near which town?", ["Mandi", "Dharamshala", "Palampur", "Hamirpur"], "The second Vidhan Sabha complex at Tapovan, near Dharamshala in Kangra district, hosts the winter session. Dharamshala was declared the second capital in 2017."],
    ["तपोवन, जहाँ हिमाचल प्रदेश विधानसभा का शीतकालीन सत्र होता है, किस नगर के पास है?", ["मंडी", "धर्मशाला", "पालमपुर", "हमीरपुर"], "कांगड़ा जिले में धर्मशाला के पास तपोवन में विधानसभा का दूसरा भवन है, जहाँ शीतकालीन सत्र होता है। 2017 में धर्मशाला को दूसरी राजधानी घोषित किया गया।"]),
  q(0, "hp-gk", "districts", "M", 2,
    ["By population, which is the largest district of Himachal Pradesh?", ["Mandi", "Shimla", "Kangra", "Solan"], "Kangra has the largest population of all districts (about 15 lakh in Census 2011). Lahaul & Spiti has the smallest."],
    ["जनसंख्या की दृष्टि से हिमाचल प्रदेश का सबसे बड़ा जिला कौन-सा है?", ["मंडी", "शिमला", "कांगड़ा", "सोलन"], "कांगड़ा की जनसंख्या सभी जिलों में सबसे अधिक (2011 की जनगणना में लगभग 15 लाख) है। लाहौल-स्पीति की सबसे कम है।"]),
  q(0, "hp-gk", "districts", "E", 3,
    ["How many districts does Himachal Pradesh have?", ["10", "11", "13", "12"], "Himachal Pradesh has 12 districts; the last reorganisation, in 1972, created Hamirpur, Una and Solan."],
    ["हिमाचल प्रदेश में कितने जिले हैं?", ["10", "11", "13", "12"], "हिमाचल प्रदेश में 12 जिले हैं; अंतिम पुनर्गठन 1972 में हुआ, जिसमें हमीरपुर, ऊना और सोलन बने।"]),
  q(0, "hp-gk", "geography", "H", 0,
    ["The Baralacha La pass links Lahaul with which region?", ["Ladakh (Zanskar)", "Spiti", "Kinnaur", "Pangi"], "Baralacha La (about 4,890 m) on the Manali–Leh road links Lahaul with Ladakh. The Bhaga, Chandra and Yunam rivers rise near it."],
    ["बारालाचा ला दर्रा लाहौल को किस क्षेत्र से जोड़ता है?", ["लद्दाख (ज़ांस्कर)", "स्पीति", "किन्नौर", "पांगी"], "मनाली–लेह मार्ग पर बारालाचा ला (लगभग 4,890 मीटर) लाहौल को लद्दाख से जोड़ता है। भागा, चंद्रा और यूनम नदियाँ इसके पास से निकलती हैं।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["The Kunzum Pass connects Lahaul with:", ["Kullu", "Spiti", "Kinnaur", "Chamba"], "Kunzum La (about 4,590 m) links the Lahaul valley with the Spiti valley on the Gramphu–Kaza road."],
    ["कुंज़ुम दर्रा लाहौल को किससे जोड़ता है?", ["कुल्लू", "स्पीति", "किन्नौर", "चंबा"], "कुंज़ुम ला (लगभग 4,590 मीटर) ग्रांफू–काज़ा मार्ग पर लाहौल घाटी को स्पीति घाटी से जोड़ता है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 2,
    ["Nako lake, a high-altitude lake near the Indo-Tibet border on the Hindustan–Tibet road, is in which district?", ["Lahaul & Spiti", "Chamba", "Kinnaur", "Shimla"], "Nako lake lies at about 3,600 m in Nako village of the Hangrang valley, upper Kinnaur, close to the Spiti border."],
    ["हिंदुस्तान–तिब्बत मार्ग पर भारत-तिब्बत सीमा के पास ऊँचाई पर स्थित नाको झील किस जिले में है?", ["लाहौल-स्पीति", "चंबा", "किन्नौर", "शिमला"], "नाको झील ऊपरी किन्नौर की हंगरंग घाटी के नाको गाँव में लगभग 3,600 मीटर पर, स्पीति सीमा के पास है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 3,
    ["Prashar lake, with its three-tiered pagoda temple of Rishi Prashar, is in which district?", ["Kullu", "Shimla", "Chamba", "Mandi"], "Prashar lake lies about 50 km north of Mandi town. The pagoda-style temple beside it is said to have been built by Raja Ban Sen of Mandi."],
    ["ऋषि पराशर के तीन-मंज़िला पैगोडा मंदिर वाली पराशर झील किस जिले में है?", ["कुल्लू", "शिमला", "चंबा", "मंडी"], "पराशर झील मंडी नगर से लगभग 50 किमी उत्तर में है। इसके किनारे का पैगोडा शैली का मंदिर मंडी के राजा बाण सेन ने बनवाया माना जाता है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 0,
    ["Chandratal, a high-altitude Ramsar wetland, is located in:", ["Lahaul & Spiti", "Kinnaur", "Kullu", "Chamba"], "Chandratal ('moon lake') lies near the Kunzum Pass in Lahaul & Spiti at about 4,300 m and is a Ramsar site."],
    ["ऊँचाई पर स्थित रामसर आर्द्रभूमि चंद्रताल कहाँ है?", ["लाहौल-स्पीति", "किन्नौर", "कुल्लू", "चंबा"], "चंद्रताल ('चंद्र झील') लाहौल-स्पीति में कुंज़ुम दर्रे के पास लगभग 4,300 मीटर पर स्थित है और रामसर स्थल है।"]),
  q(0, "hp-gk", "geography", "M", 1,
    ["Which place in Chamba district is popularly called the 'Mini Switzerland of India'?", ["Dalhousie", "Khajjiar", "Bharmour", "Banikhet"], "Khajjiar, a meadow with a small lake surrounded by deodar forest, was given the 'Mini Switzerland' tag in 1992."],
    ["चंबा जिले के किस स्थान को 'भारत का मिनी स्विट्ज़रलैंड' कहा जाता है?", ["डलहौज़ी", "खज्जियार", "भरमौर", "बनीखेत"], "देवदार वन से घिरे छोटे तालाब वाले मैदान खज्जियार को 1992 में 'मिनी स्विट्ज़रलैंड' का नाम मिला।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The Hidimba Devi temple at Manali was built in 1553 by Raja:", ["Jagat Singh", "Man Singh", "Bahadur Singh", "Ajit Singh"], "Raja Bahadur Singh of Kullu built the pagoda-style Hidimba Devi temple at Dhungri, Manali, in 1553."],
    ["मनाली के हिडिंबा देवी मंदिर का निर्माण 1553 में किस राजा ने कराया?", ["जगत सिंह", "मान सिंह", "बहादुर सिंह", "अजीत सिंह"], "कुल्लू के राजा बहादुर सिंह ने 1553 में मनाली के ढूँगरी में पैगोडा शैली का हिडिंबा देवी मंदिर बनवाया।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The monolithic rock-cut Masroor temples are in which district?", ["Mandi", "Chamba", "Hamirpur", "Kangra"], "The 8th-century Masroor temples, carved out of a single sandstone ridge, are in Kangra district and are sometimes compared to Ellora."],
    ["एक ही चट्टान को काटकर बने मसरूर मंदिर किस जिले में हैं?", ["मंडी", "चंबा", "हमीरपुर", "कांगड़ा"], "8वीं शताब्दी के मसरूर मंदिर, जो एक ही बलुआ पत्थर की चट्टान को काटकर बने हैं, कांगड़ा जिले में हैं और इनकी तुलना एलोरा से की जाती है।"]),
  q(0, "hp-gk", "culture-festivals", "M", 0,
    ["The Baijnath temple, dedicated to Lord Shiva as Vaidyanath, is located in district:", ["Kangra", "Kullu", "Mandi", "Bilaspur"], "Baijnath temple in Kangra district was built in 1204 AD in the Nagara style by two local merchants, Ahuka and Manyuka."],
    ["वैद्यनाथ रूप में भगवान शिव को समर्पित बैजनाथ मंदिर किस जिले में है?", ["कांगड़ा", "कुल्लू", "मंडी", "बिलासपुर"], "कांगड़ा जिले का बैजनाथ मंदिर 1204 ई. में दो स्थानीय व्यापारियों आहुक और मन्युक ने नागर शैली में बनवाया।"]),
  q(0, "hp-gk", "history", "H", 1,
    ["Tabo monastery in Spiti, often called the 'Ajanta of the Himalayas', was founded in 996 AD by:", ["Padmasambhava", "Rinchen Zangpo", "Atisha", "Dalai Lama I"], "Tabo was founded in 996 AD by the translator Rinchen Zangpo under the king of Guge; its murals earned it the name 'Ajanta of the Himalayas'."],
    ["'हिमालय का अजंता' कहे जाने वाले स्पीति के ताबो मठ की स्थापना 996 ई. में किसने की?", ["पद्मसंभव", "रिनचेन ज़ांगपो", "अतीश", "पहले दलाई लामा"], "ताबो की स्थापना 996 ई. में गुगे के राजा के संरक्षण में अनुवादक रिनचेन ज़ांगपो ने की; इसके भित्तिचित्रों के कारण इसे 'हिमालय का अजंता' कहते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["Key (Kye) Gompa, the largest monastery of the valley, is located in:", ["Kinnaur", "Lahaul", "Spiti", "Pangi"], "Key Gompa, perched on a hill above the Spiti river near Kaza, is the largest monastery of the Spiti valley."],
    ["घाटी का सबसे बड़ा मठ की (Key) गोम्पा कहाँ स्थित है?", ["किन्नौर", "लाहौल", "स्पीति", "पांगी"], "काज़ा के पास स्पीति नदी के ऊपर पहाड़ी पर बना की गोम्पा स्पीति घाटी का सबसे बड़ा मठ है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["Phulaich (Ukhyang), the festival of flowers, is mainly celebrated in:", ["Chamba", "Sirmaur", "Kullu", "Kinnaur"], "Phulaich or Ukhyang is celebrated in Kinnaur in September; people collect wild flowers from the high pastures and offer them in remembrance of the dead."],
    ["फूलों का त्योहार फुलैच (उख्यांग) मुख्यतः कहाँ मनाया जाता है?", ["चंबा", "सिरमौर", "कुल्लू", "किन्नौर"], "फुलैच या उख्यांग सितंबर में किन्नौर में मनाया जाता है; लोग ऊँचे चरागाहों से जंगली फूल लाकर दिवंगतों की स्मृति में अर्पित करते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["Halda, a festival of light marking the new year, is celebrated in:", ["Lahaul", "Kangra", "Mandi", "Solan"], "Halda is celebrated in Lahaul in January–February; villagers carry burning cedar torches to a bonfire, much like Losar."],
    ["नववर्ष पर मनाया जाने वाला प्रकाश पर्व हालडा कहाँ मनाया जाता है?", ["लाहौल", "कांगड़ा", "मंडी", "सोलन"], "हालडा जनवरी–फ़रवरी में लाहौल में मनाया जाता है; ग्रामीण देवदार की जलती मशालें लेकर अलाव तक जाते हैं, लोसर की तरह।"]),
  q(0, "hp-gk", "culture-festivals", "M", 1,
    ["The Gaddi tribe, known for rearing sheep and goats, mainly lives in which area?", ["Spiti", "Bharmour", "Pangi", "Kinnaur"], "The Gaddis are a pastoral tribe whose homeland, 'Gadderan', centres on Bharmour in Chamba district."],
    ["भेड़-बकरी पालने के लिए प्रसिद्ध गद्दी जनजाति मुख्यतः किस क्षेत्र में रहती है?", ["स्पीति", "भरमौर", "पांगी", "किन्नौर"], "गद्दी एक पशुपालक जनजाति है, जिसका मूल क्षेत्र 'गद्दरण' चंबा जिले के भरमौर के आसपास है।"]),
  q(0, "hp-gk", "polity-administration", "M", 1,
    ["Nauni, near Solan, is known for which institution?", ["HP Agriculture University", "Dr Y.S. Parmar University of Horticulture and Forestry", "Central University of Himachal Pradesh", "Himachal Pradesh Technical University"], "Dr Y.S. Parmar University of Horticulture and Forestry was set up at Nauni in 1985. The agriculture university is at Palampur and the technical university at Hamirpur."],
    ["सोलन के पास नौणी किस संस्थान के लिए जाना जाता है?", ["हिमाचल कृषि विश्वविद्यालय", "डॉ. वाई.एस. परमार औद्यानिकी एवं वानिकी विश्वविद्यालय", "हिमाचल प्रदेश केंद्रीय विश्वविद्यालय", "हिमाचल प्रदेश तकनीकी विश्वविद्यालय"], "डॉ. वाई.एस. परमार औद्यानिकी एवं वानिकी विश्वविद्यालय 1985 में नौणी में स्थापित हुआ। कृषि विश्वविद्यालय पालमपुर और तकनीकी विश्वविद्यालय हमीरपुर में है।"]),
  q(0, "hp-gk", "polity-administration", "H", 3,
    ["The Indian Institute of Technology (IIT) Mandi has its campus at:", ["Sundernagar", "Joginder Nagar", "Pandoh", "Kamand"], "IIT Mandi, set up in 2009, has its main campus at Kamand on the banks of the Uhl river, about 15 km from Mandi town."],
    ["भारतीय प्रौद्योगिकी संस्थान (IIT) मंडी का परिसर कहाँ है?", ["सुंदरनगर", "जोगिंदरनगर", "पंडोह", "कमांद"], "2009 में स्थापित IIT मंडी का मुख्य परिसर मंडी नगर से लगभग 15 किमी दूर उहल नदी के किनारे कमांद में है।"]),
  q(0, "hp-gk", "polity-administration", "H", 0,
    ["The All India Institute of Medical Sciences (AIIMS) of Himachal Pradesh is located in district:", ["Bilaspur", "Hamirpur", "Mandi", "Una"], "AIIMS Bilaspur, at Kothipura, was inaugurated by the Prime Minister in October 2022."],
    ["हिमाचल प्रदेश का अखिल भारतीय आयुर्विज्ञान संस्थान (AIIMS) किस जिले में है?", ["बिलासपुर", "हमीरपुर", "मंडी", "ऊना"], "कोठीपुरा स्थित AIIMS बिलासपुर का उद्घाटन प्रधानमंत्री ने अक्टूबर 2022 में किया।"]),
  q(0, "hp-gk", "economy", "H", 1,
    ["Who introduced the American 'Delicious' apple at Kotgarh in 1916, starting Himachal's apple economy?", ["Captain R.C. Lee", "Samuel Evans Stokes", "Alexander Coutts", "William Moorcroft"], "Samuel Evans Stokes, an American who settled at Kotgarh (Shimla) and later took the name Satyanand Stokes, brought Delicious apple plants from the USA in 1916."],
    ["1916 में कोटगढ़ में अमेरिकी 'डिलीशियस' सेब लाकर हिमाचल की सेब अर्थव्यवस्था की शुरुआत किसने की?", ["कैप्टन आर.सी. ली", "सैमुअल इवांस स्टोक्स", "अलेक्ज़ेंडर कूट्स", "विलियम मूरक्रॉफ्ट"], "कोटगढ़ (शिमला) में बसे अमेरिकी सैमुअल इवांस स्टोक्स, जिन्होंने बाद में सत्यानंद स्टोक्स नाम अपनाया, 1916 में अमेरिका से डिलीशियस सेब के पौधे लाए।"]),
  q(0, "hp-gk", "culture-festivals", "M", 2,
    ["The Bhuri Singh Museum, known for its Pahari paintings and Sharada inscriptions, is at:", ["Mandi", "Shimla", "Chamba", "Dharamshala"], "The Bhuri Singh Museum at Chamba opened in 1908 and is named after Raja Bhuri Singh, who donated his family's collection."],
    ["पहाड़ी चित्रों और शारदा अभिलेखों के लिए प्रसिद्ध भूरि सिंह संग्रहालय कहाँ है?", ["मंडी", "शिमला", "चंबा", "धर्मशाला"], "चंबा का भूरि सिंह संग्रहालय 1908 में खुला और इसका नाम राजा भूरि सिंह पर है, जिन्होंने अपने परिवार का संग्रह दान किया।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 3,
    ["The Manikaran hot springs, holy to both Hindus and Sikhs, lie on the bank of which river?", ["Beas", "Sutlej", "Tirthan", "Parvati"], "Manikaran in Kullu district is on the Parvati river; its gurdwara and Ram temple use the hot springs for cooking langar."],
    ["हिंदुओं और सिखों दोनों के लिए पवित्र मणिकर्ण के गर्म जल स्रोत किस नदी के किनारे हैं?", ["ब्यास", "सतलुज", "तीर्थन", "पार्वती"], "कुल्लू जिले का मणिकर्ण पार्वती नदी पर है; यहाँ के गुरुद्वारे और राम मंदिर में गर्म जल स्रोतों से लंगर पकाया जाता है।"]),
  q(0, "hp-gk", "districts", "M", 0,
    ["Which is the smallest district of Himachal Pradesh in terms of area?", ["Hamirpur", "Una", "Bilaspur", "Solan"], "Hamirpur, with about 1,118 sq km, is the smallest district by area. Lahaul & Spiti is the largest."],
    ["क्षेत्रफल के अनुसार हिमाचल प्रदेश का सबसे छोटा जिला कौन-सा है?", ["हमीरपुर", "ऊना", "बिलासपुर", "सोलन"], "लगभग 1,118 वर्ग किमी के साथ हमीरपुर क्षेत्रफल में सबसे छोटा जिला है। लाहौल-स्पीति सबसे बड़ा है।"]),
  q(0, "hp-gk", "geography", "H", 1,
    ["Which river rises at Beas Kund near the Rohtang Pass?", ["Parvati", "Beas", "Chandra", "Ravi"], "The Beas rises at Beas Kund near Rohtang and flows through Kullu, Mandi and Kangra before entering Punjab."],
    ["रोहतांग दर्रे के पास ब्यास कुंड से कौन-सी नदी निकलती है?", ["पार्वती", "ब्यास", "चंद्रा", "रावी"], "ब्यास नदी रोहतांग के पास ब्यास कुंड से निकलकर कुल्लू, मंडी और कांगड़ा होते हुए पंजाब में प्रवेश करती है।"]),

  // ───────── Section 1: Social Science (20) ─────────
  q(1, "general-studies", "indian-history", "M", 1,
    ["Emperor Ashoka embraced Buddhism after the war of:", ["Panipat", "Kalinga", "Hydaspes", "Takshashila"], "The bloodshed of the Kalinga war (about 261 BC) moved Ashoka to adopt Buddhism and the policy of Dhamma, as told in his Rock Edict XIII."],
    ["सम्राट अशोक ने किस युद्ध के बाद बौद्ध धर्म अपनाया?", ["पानीपत", "कलिंग", "हाइडेस्पीज़", "तक्षशिला"], "कलिंग युद्ध (लगभग 261 ई.पू.) के रक्तपात से द्रवित होकर अशोक ने बौद्ध धर्म और धम्म की नीति अपनाई, जैसा उसके तेरहवें शिलालेख में है।"]),
  q(1, "general-studies", "indian-history", "M", 3,
    ["Babur founded the Mughal empire after defeating whom in the First Battle of Panipat (1526)?", ["Rana Sanga", "Hemu", "Sher Shah Suri", "Ibrahim Lodi"], "In 1526 Babur defeated Ibrahim Lodi, the last Delhi Sultan, at Panipat. He defeated Rana Sanga at Khanwa in 1527."],
    ["पानीपत के प्रथम युद्ध (1526) में किसे हराकर बाबर ने मुगल साम्राज्य की स्थापना की?", ["राणा सांगा", "हेमू", "शेरशाह सूरी", "इब्राहीम लोदी"], "1526 में बाबर ने पानीपत में दिल्ली के अंतिम सुल्तान इब्राहीम लोदी को हराया। राणा सांगा को उसने 1527 में खानवा में हराया।"]),
  q(1, "general-studies", "indian-history", "H", 0,
    ["The Ryotwari system of land revenue, in which the government dealt directly with the cultivator, was introduced in Madras mainly by:", ["Thomas Munro", "Lord Cornwallis", "Holt Mackenzie", "R.M. Bird"], "Thomas Munro (with Alexander Read) introduced the Ryotwari system in Madras around 1820. Mahalwari was linked with Holt Mackenzie and R.M. Bird."],
    ["रैयतवाड़ी भू-राजस्व व्यवस्था, जिसमें सरकार सीधे किसान से संबंध रखती थी, मद्रास में मुख्यतः किसने लागू की?", ["थॉमस मुनरो", "लॉर्ड कॉर्नवालिस", "होल्ट मैकेंज़ी", "आर.एम. बर्ड"], "थॉमस मुनरो (अलेक्ज़ेंडर रीड के साथ) ने लगभग 1820 में मद्रास में रैयतवाड़ी व्यवस्था लागू की। महालवाड़ी होल्ट मैकेंज़ी और आर.एम. बर्ड से जुड़ी है।"]),
  q(1, "general-studies", "indian-history", "M", 1,
    ["The Partition of Bengal in 1905 was carried out during the viceroyalty of:", ["Lord Minto", "Lord Curzon", "Lord Ripon", "Lord Hardinge"], "Lord Curzon partitioned Bengal in October 1905, which led to the Swadeshi movement. The partition was annulled in 1911."],
    ["1905 में बंगाल का विभाजन किस वायसराय के समय हुआ?", ["लॉर्ड मिंटो", "लॉर्ड कर्ज़न", "लॉर्ड रिपन", "लॉर्ड हार्डिंग"], "लॉर्ड कर्ज़न ने अक्टूबर 1905 में बंगाल का विभाजन किया, जिससे स्वदेशी आंदोलन शुरू हुआ। 1911 में विभाजन रद्द हुआ।"]),
  q(1, "general-studies", "indian-history", "M", 2,
    ["Gandhiji withdrew the Non-Cooperation Movement in 1922 after the violent incident at:", ["Champaran", "Bardoli", "Chauri Chaura", "Kheda"], "After a mob burnt a police station at Chauri Chaura (Gorakhpur) in February 1922, Gandhiji called off the movement."],
    ["गांधीजी ने 1922 में किस हिंसक घटना के बाद असहयोग आंदोलन वापस लिया?", ["चंपारण", "बारदोली", "चौरी चौरा", "खेड़ा"], "फ़रवरी 1922 में चौरी चौरा (गोरखपुर) में भीड़ द्वारा थाना जलाए जाने के बाद गांधीजी ने आंदोलन वापस ले लिया।"]),
  q(1, "general-studies", "indian-history", "H", 3,
    ["The resolution of 'Purna Swaraj' (complete independence) was passed at the 1929 Lahore session presided over by:", ["Motilal Nehru", "Subhas Chandra Bose", "Sardar Patel", "Jawaharlal Nehru"], "Jawaharlal Nehru presided over the Lahore session (December 1929), which adopted Purna Swaraj; 26 January 1930 was celebrated as Independence Day."],
    ["1929 के लाहौर अधिवेशन में 'पूर्ण स्वराज' का प्रस्ताव किसकी अध्यक्षता में पारित हुआ?", ["मोतीलाल नेहरू", "सुभाष चंद्र बोस", "सरदार पटेल", "जवाहरलाल नेहरू"], "दिसंबर 1929 के लाहौर अधिवेशन की अध्यक्षता जवाहरलाल नेहरू ने की, जिसमें पूर्ण स्वराज अपनाया गया; 26 जनवरी 1930 को स्वतंत्रता दिवस मनाया गया।"]),
  q(1, "general-studies", "indian-history", "M", 0,
    ["Why did Indians boycott the Simon Commission in 1928?", ["It had no Indian member", "It proposed partition", "It was led by the Viceroy", "It banned the Congress"], "The seven-member Simon Commission, sent to review the 1919 reforms, had no Indian member, so it was greeted with 'Simon Go Back'."],
    ["1928 में भारतीयों ने साइमन आयोग का बहिष्कार क्यों किया?", ["इसमें कोई भारतीय सदस्य नहीं था", "इसने विभाजन का प्रस्ताव रखा", "इसका नेतृत्व वायसराय कर रहे थे", "इसने कांग्रेस पर प्रतिबंध लगाया"], "1919 के सुधारों की समीक्षा के लिए आए सात सदस्यीय साइमन आयोग में कोई भारतीय सदस्य नहीं था, इसलिए 'साइमन वापस जाओ' के नारे लगे।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["Which river is known as the 'Sorrow of Bihar' because of its frequent floods and change of course?", ["Gandak", "Kosi", "Son", "Damodar"], "The Kosi carries heavy silt from the Himalayas and often shifts its course, flooding north Bihar. The Damodar was called the 'Sorrow of Bengal'."],
    ["बार-बार बाढ़ और मार्ग बदलने के कारण किस नदी को 'बिहार का शोक' कहा जाता है?", ["गंडक", "कोसी", "सोन", "दामोदर"], "कोसी हिमालय से भारी गाद लाती है और बार-बार मार्ग बदलकर उत्तर बिहार में बाढ़ लाती है। दामोदर को 'बंगाल का शोक' कहा जाता था।"]),
  q(1, "general-studies", "indian-geography", "H", 2,
    ["Which is the highest peak of the Western Ghats (and of peninsular India)?", ["Doddabetta", "Mahendragiri", "Anamudi", "Kalsubai"], "Anamudi (2,695 m) in the Anaimalai hills of Kerala is the highest peak of the Western Ghats and of south India."],
    ["पश्चिमी घाट (और प्रायद्वीपीय भारत) की सबसे ऊँची चोटी कौन-सी है?", ["डोडाबेट्टा", "महेंद्रगिरि", "अनाइमुडी", "कलसूबाई"], "केरल की अन्नामलाई पहाड़ियों में अनाइमुडी (2,695 मीटर) पश्चिमी घाट और दक्षिण भारत की सबसे ऊँची चोटी है।"]),
  q(1, "general-studies", "indian-geography", "H", 3,
    ["Laterite soil is formed mainly as a result of:", ["deposition by rivers", "wind erosion in deserts", "volcanic lava", "intense leaching in areas of high rainfall and temperature"], "Heavy rain and high temperature wash away silica and lime (leaching), leaving iron and aluminium oxides. Laterite soil is found in Kerala, Karnataka and the north-east."],
    ["लेटराइट मिट्टी मुख्यतः किसके परिणामस्वरूप बनती है?", ["नदियों द्वारा निक्षेपण", "मरुस्थल में पवन अपरदन", "ज्वालामुखीय लावा", "अधिक वर्षा और ताप वाले क्षेत्रों में तीव्र निक्षालन"], "भारी वर्षा और उच्च ताप से सिलिका और चूना बह जाते हैं (निक्षालन), लोहा और एल्युमिनियम के ऑक्साइड बचे रहते हैं। लेटराइट मिट्टी केरल, कर्नाटक और पूर्वोत्तर में मिलती है।"]),
  q(1, "general-studies", "indian-geography", "H", 0,
    ["The Indian Standard Time meridian (82°30′ E) passes near which city?", ["Mirzapur", "Nagpur", "Bhopal", "Kolkata"], "The 82.5° E longitude, used for IST, passes near Mirzapur in Uttar Pradesh. IST is 5 hours 30 minutes ahead of GMT."],
    ["भारतीय मानक समय की याम्योत्तर रेखा (82°30′ पूर्व) किस नगर के निकट से गुज़रती है?", ["मिर्ज़ापुर", "नागपुर", "भोपाल", "कोलकाता"], "भारतीय मानक समय के लिए प्रयुक्त 82.5° पूर्व देशांतर उत्तर प्रदेश के मिर्ज़ापुर के पास से गुज़रता है। IST, GMT से 5 घंटे 30 मिनट आगे है।"]),
  q(1, "general-studies", "indian-geography", "M", 1,
    ["The Sundarbans, the largest mangrove forest, are part of the delta of:", ["Mahanadi and Godavari", "Ganga and Brahmaputra", "Krishna and Kaveri", "Indus and Sutlej"], "The Sundarbans lie in the Ganga–Brahmaputra delta in West Bengal and Bangladesh and are home to the Royal Bengal tiger."],
    ["सबसे बड़ा मैंग्रोव वन सुंदरबन किन नदियों के डेल्टा का भाग है?", ["महानदी और गोदावरी", "गंगा और ब्रह्मपुत्र", "कृष्णा और कावेरी", "सिंधु और सतलुज"], "सुंदरबन पश्चिम बंगाल और बांग्लादेश में गंगा–ब्रह्मपुत्र डेल्टा में है और रॉयल बंगाल टाइगर का निवास है।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["Which words were added to the Preamble by the 42nd Amendment, 1976?", ["Sovereign, Democratic and Republic", "Justice, Liberty and Equality", "Socialist, Secular and Integrity", "Fraternity, Dignity and Unity"], "The 42nd Amendment added 'Socialist' and 'Secular' and changed 'unity of the Nation' to 'unity and integrity of the Nation'."],
    ["42वें संशोधन, 1976 द्वारा प्रस्तावना में कौन-से शब्द जोड़े गए?", ["संप्रभु, लोकतांत्रिक और गणराज्य", "न्याय, स्वतंत्रता और समता", "समाजवादी, पंथनिरपेक्ष और अखंडता", "बंधुता, गरिमा और एकता"], "42वें संशोधन ने 'समाजवादी' और 'पंथनिरपेक्ष' जोड़े तथा 'राष्ट्र की एकता' को 'राष्ट्र की एकता और अखंडता' किया।"]),
  q(1, "general-studies", "indian-polity", "M", 3,
    ["Dr B.R. Ambedkar called which Article 'the heart and soul of the Constitution'?", ["Article 14", "Article 19", "Article 21", "Article 32"], "Article 32, the Right to Constitutional Remedies, lets a person move the Supreme Court directly to enforce Fundamental Rights."],
    ["डॉ. बी.आर. आंबेडकर ने किस अनुच्छेद को 'संविधान का हृदय और आत्मा' कहा?", ["अनुच्छेद 14", "अनुच्छेद 19", "अनुच्छेद 21", "अनुच्छेद 32"], "अनुच्छेद 32 (संवैधानिक उपचारों का अधिकार) व्यक्ति को मौलिक अधिकार लागू कराने के लिए सीधे सर्वोच्च न्यायालय जाने का अधिकार देता है।"]),
  q(1, "general-studies", "indian-polity", "M", 0,
    ["Who presides over a joint sitting of both Houses of Parliament?", ["The Speaker of the Lok Sabha", "The President", "The Vice-President", "The Prime Minister"], "Under Article 108 the President summons a joint sitting, but the Speaker of the Lok Sabha presides over it."],
    ["संसद के दोनों सदनों की संयुक्त बैठक की अध्यक्षता कौन करता है?", ["लोकसभा अध्यक्ष", "राष्ट्रपति", "उपराष्ट्रपति", "प्रधानमंत्री"], "अनुच्छेद 108 के अनुसार संयुक्त बैठक राष्ट्रपति बुलाते हैं, परंतु उसकी अध्यक्षता लोकसभा अध्यक्ष करते हैं।"]),
  q(1, "general-studies", "indian-polity", "M", 1,
    ["A national emergency on grounds of war, external aggression or armed rebellion is declared under:", ["Article 356", "Article 352", "Article 360", "Article 365"], "Article 352 covers national emergency. Article 356 is President's rule in a state and Article 360 is financial emergency."],
    ["युद्ध, बाहरी आक्रमण या सशस्त्र विद्रोह के आधार पर राष्ट्रीय आपातकाल किस अनुच्छेद में घोषित होता है?", ["अनुच्छेद 356", "अनुच्छेद 352", "अनुच्छेद 360", "अनुच्छेद 365"], "अनुच्छेद 352 राष्ट्रीय आपातकाल से संबंधित है। अनुच्छेद 356 राज्य में राष्ट्रपति शासन और अनुच्छेद 360 वित्तीय आपातकाल है।"]),
  q(1, "general-studies", "indian-polity", "H", 2,
    ["The provisions on disqualification on grounds of defection (anti-defection law) are in which Schedule?", ["Eighth Schedule", "Ninth Schedule", "Tenth Schedule", "Twelfth Schedule"], "The 52nd Amendment (1985) added the Tenth Schedule on anti-defection. The Eighth lists languages and the Twelfth lists municipal subjects."],
    ["दल-बदल के आधार पर अयोग्यता (दल-बदल विरोधी कानून) के प्रावधान किस अनुसूची में हैं?", ["आठवीं अनुसूची", "नौवीं अनुसूची", "दसवीं अनुसूची", "बारहवीं अनुसूची"], "52वें संशोधन (1985) ने दल-बदल विरोधी दसवीं अनुसूची जोड़ी। आठवीं में भाषाएँ और बारहवीं में नगरपालिका विषय हैं।"]),
  q(1, "general-studies", "indian-economy", "H", 3,
    ["Fiscal deficit of the government is:", ["total expenditure minus revenue receipts", "revenue expenditure minus revenue receipts", "imports minus exports", "total expenditure minus total receipts excluding borrowings"], "Fiscal deficit = total expenditure − (revenue receipts + non-debt capital receipts). It shows how much the government must borrow."],
    ["सरकार का राजकोषीय घाटा क्या है?", ["कुल व्यय − राजस्व प्राप्तियाँ", "राजस्व व्यय − राजस्व प्राप्तियाँ", "आयात − निर्यात", "कुल व्यय − उधार को छोड़कर कुल प्राप्तियाँ"], "राजकोषीय घाटा = कुल व्यय − (राजस्व प्राप्तियाँ + ऋण-रहित पूँजीगत प्राप्तियाँ)। यह बताता है कि सरकार को कितना उधार लेना होगा।"]),
  q(1, "general-studies", "indian-economy", "M", 0,
    ["The Second Five Year Plan (1956–61), which stressed heavy industry, was based on the model of:", ["P.C. Mahalanobis", "Harrod–Domar", "M. Visvesvaraya", "Shriman Narayan"], "The Second Plan followed the Mahalanobis model, investing heavily in basic and heavy industries. The First Plan used the Harrod–Domar model."],
    ["भारी उद्योग पर बल देने वाली दूसरी पंचवर्षीय योजना (1956–61) किसके मॉडल पर आधारित थी?", ["पी.सी. महालनोबिस", "हैरोड–डोमर", "एम. विश्वेश्वरैया", "श्रीमन नारायण"], "दूसरी योजना महालनोबिस मॉडल पर थी, जिसमें आधारभूत व भारी उद्योगों में भारी निवेश हुआ। पहली योजना हैरोड–डोमर मॉडल पर थी।"]),
  q(1, "general-studies", "indian-economy", "H", 1,
    ["The National Bank for Agriculture and Rural Development (NABARD) was established in:", ["1969", "1982", "1975", "1991"], "NABARD was set up on 12 July 1982 on the recommendation of the Shivaraman Committee; it is headquartered in Mumbai."],
    ["राष्ट्रीय कृषि और ग्रामीण विकास बैंक (नाबार्ड) की स्थापना कब हुई?", ["1969", "1982", "1975", "1991"], "शिवरामन समिति की सिफ़ारिश पर नाबार्ड की स्थापना 12 जुलाई 1982 को हुई; इसका मुख्यालय मुंबई में है।"]),

  // ───────── Section 2: Everyday Science (10) ─────────
  q(2, "general-studies", "general-science", "H", 2,
    ["Optical fibres used in internet cables carry light signals on the principle of:", ["refraction", "diffraction", "total internal reflection", "polarisation"], "Light inside the glass core strikes its wall at more than the critical angle, so it is totally reflected again and again along the fibre."],
    ["इंटरनेट केबल में प्रयुक्त प्रकाशीय तंतु (ऑप्टिकल फ़ाइबर) किस सिद्धांत पर प्रकाश संकेत ले जाते हैं?", ["अपवर्तन", "विवर्तन", "पूर्ण आंतरिक परावर्तन", "ध्रुवण"], "काँच के कोर के अंदर प्रकाश क्रांतिक कोण से बड़े कोण पर दीवार से टकराता है, इसलिए बार-बार पूर्ण परावर्तित होकर आगे बढ़ता है।"]),
  q(2, "general-studies", "general-science", "M", 3,
    ["Heating milk to about 63 °C for 30 minutes and then cooling it quickly to kill germs is called:", ["Fermentation", "Sterilisation", "Homogenisation", "Pasteurisation"], "Pasteurisation, named after Louis Pasteur, kills most harmful microbes without boiling the milk."],
    ["कीटाणु नष्ट करने के लिए दूध को लगभग 63 °C पर 30 मिनट गर्म करके तुरंत ठंडा करना क्या कहलाता है?", ["किण्वन", "निर्जीवीकरण", "समांगीकरण", "पाश्चुरीकरण"], "लुई पाश्चर के नाम पर पाश्चुरीकरण दूध को उबाले बिना अधिकांश हानिकारक सूक्ष्मजीव नष्ट कर देता है।"]),
  q(2, "general-studies", "general-science", "M", 0,
    ["Bile juice, which helps in digesting fats, is produced by the:", ["Liver", "Gall bladder", "Pancreas", "Stomach"], "Bile is made in the liver and stored in the gall bladder; it emulsifies fats in the small intestine."],
    ["वसा के पाचन में सहायक पित्त रस कौन बनाता है?", ["यकृत", "पित्ताशय", "अग्न्याशय", "आमाशय"], "पित्त यकृत में बनता है और पित्ताशय में जमा होता है; यह छोटी आँत में वसा का इमल्सीकरण करता है।"]),
  q(2, "general-studies", "general-science", "M", 1,
    ["A lightning conductor fixed on tall buildings is usually made of:", ["Iron", "Copper", "Aluminium foil", "Plastic"], "Copper is a very good conductor, so the rod carries the lightning charge safely into the earth."],
    ["ऊँची इमारतों पर लगाया जाने वाला तड़ित चालक प्रायः किस धातु का बना होता है?", ["लोहा", "तांबा", "एल्युमिनियम पन्नी", "प्लास्टिक"], "तांबा बहुत अच्छा चालक है, इसलिए छड़ बिजली के आवेश को सुरक्षित रूप से धरती में पहुँचा देती है।"]),
  q(2, "general-studies", "general-science", "H", 2,
    ["Which compound is added to LPG so that a leak can be detected by its smell?", ["Methane", "Butane", "Ethyl mercaptan", "Carbon monoxide"], "LPG (mainly butane and propane) has no smell, so ethyl mercaptan, a strong-smelling sulphur compound, is added for safety."],
    ["रिसाव का पता गंध से चल सके, इसके लिए LPG में कौन-सा यौगिक मिलाया जाता है?", ["मीथेन", "ब्यूटेन", "एथिल मरकैप्टन", "कार्बन मोनोऑक्साइड"], "LPG (मुख्यतः ब्यूटेन और प्रोपेन) गंधहीन होती है, इसलिए सुरक्षा के लिए तेज़ गंध वाला सल्फ़र यौगिक एथिल मरकैप्टन मिलाया जाता है।"]),
  q(2, "general-studies", "general-science", "E", 3,
    ["Anaemia is mainly caused by the deficiency of:", ["Vitamin A", "Iodine", "Calcium", "Iron"], "Iron is needed to make haemoglobin. Too little iron lowers haemoglobin, causing anaemia."],
    ["रक्ताल्पता (एनीमिया) मुख्यतः किसकी कमी से होती है?", ["विटामिन A", "आयोडीन", "कैल्शियम", "लोहा"], "हीमोग्लोबिन बनाने के लिए लोहा आवश्यक है। लोहे की कमी से हीमोग्लोबिन घटता है और एनीमिया होता है।"]),
  q(2, "general-studies", "general-science", "M", 0,
    ["Which gas makes up the largest share (about 78%) of the air?", ["Nitrogen", "Oxygen", "Argon", "Carbon dioxide"], "Dry air is about 78% nitrogen, 21% oxygen and about 0.9% argon; carbon dioxide is only about 0.04%."],
    ["वायु में सबसे अधिक (लगभग 78%) कौन-सी गैस है?", ["नाइट्रोजन", "ऑक्सीजन", "आर्गन", "कार्बन डाइऑक्साइड"], "शुष्क वायु में लगभग 78% नाइट्रोजन, 21% ऑक्सीजन और लगभग 0.9% आर्गन है; कार्बन डाइऑक्साइड केवल लगभग 0.04% है।"]),
  q(2, "general-studies", "general-science", "M", 1,
    ["'Dry ice' is the solid form of:", ["Water", "Carbon dioxide", "Nitrogen", "Ammonia"], "Dry ice is solid carbon dioxide. It changes directly into gas (sublimes) at about −78 °C, leaving no liquid."],
    ["'शुष्क बर्फ़' (dry ice) किसका ठोस रूप है?", ["जल", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "अमोनिया"], "शुष्क बर्फ़ ठोस कार्बन डाइऑक्साइड है। यह लगभग −78 °C पर सीधे गैस बन जाती है (ऊर्ध्वपातन), द्रव नहीं छोड़ती।"]),
  q(2, "general-studies", "general-science", "M", 2,
    ["Malaria is caused by a protozoan and spread by the bite of the female:", ["Aedes mosquito", "Culex mosquito", "Anopheles mosquito", "Housefly"], "Malaria is caused by Plasmodium and spread by female Anopheles mosquitoes. Aedes spreads dengue and Culex spreads filaria."],
    ["मलेरिया एक प्रोटोज़ोआ से होता है और किस मादा के काटने से फैलता है?", ["एडीज़ मच्छर", "क्यूलेक्स मच्छर", "एनोफ़िलीज़ मच्छर", "घरेलू मक्खी"], "मलेरिया प्लाज़्मोडियम से होता है और मादा एनोफ़िलीज़ मच्छर से फैलता है। एडीज़ डेंगू और क्यूलेक्स फ़ाइलेरिया फैलाता है।"]),
  q(2, "general-studies", "general-science", "M", 3,
    ["Sound travels fastest through:", ["Air", "Water", "Vacuum", "Steel"], "Sound needs a medium and travels fastest in solids: about 5,000 m/s in steel, 1,500 m/s in water and 343 m/s in air. It cannot travel in a vacuum."],
    ["ध्वनि सबसे तेज़ किसमें चलती है?", ["वायु", "जल", "निर्वात", "इस्पात"], "ध्वनि को माध्यम चाहिए और यह ठोस में सबसे तेज़ चलती है: इस्पात में लगभग 5,000 मी/से, जल में 1,500 मी/से और वायु में 343 मी/से। निर्वात में यह नहीं चलती।"]),

  // ───────── Section 3: Reasoning & Mathematics (20) ─────────
  q(3, "reasoning", "series", "H", 0,
    ["Find the next number: 4, 9, 25, 49, 121, ?", ["169", "144", "196", "225"], "These are squares of prime numbers: 2², 3², 5², 7², 11². The next prime is 13, and 13² = 169."],
    ["अगली संख्या ज्ञात कीजिए: 4, 9, 25, 49, 121, ?", ["169", "144", "196", "225"], "ये अभाज्य संख्याओं के वर्ग हैं: 2², 3², 5², 7², 11²। अगली अभाज्य संख्या 13 है, और 13² = 169।"], "13*13"),
  q(3, "reasoning", "alphabet-test", "M", 1,
    ["Find the next letter: B, E, I, N, ?", ["S", "T", "U", "R"], "The gaps increase by one: B(+3)E(+4)I(+5)N(+6)T."],
    ["अगला अक्षर ज्ञात कीजिए: B, E, I, N, ?", ["S", "T", "U", "R"], "अंतर एक-एक बढ़ता है: B(+3)E(+4)I(+5)N(+6)T।"]),
  q(3, "reasoning", "coding-decoding", "M", 2,
    ["In a code language MANDI is written as NBOEJ. How is SOLAN written in that code?", ["TPMBN", "RNKZM", "TPMBO", "TQMBO"], "Each letter moves one step forward: S→T, O→P, L→M, A→B, N→O, giving TPMBO."],
    ["एक कूट भाषा में MANDI को NBOEJ लिखा जाता है। उसी कूट में SOLAN कैसे लिखा जाएगा?", ["TPMBN", "RNKZM", "TPMBO", "TQMBO"], "प्रत्येक अक्षर एक स्थान आगे: S→T, O→P, L→M, A→B, N→O, अतः TPMBO।"]),
  q(3, "reasoning", "coding-decoding", "H", 3,
    ["If CAT = 24 (C = 3, A = 1, T = 20), what is DOG in the same code?", ["24", "28", "30", "26"], "D = 4, O = 15, G = 7. Sum = 4 + 15 + 7 = 26."],
    ["यदि CAT = 24 (C = 3, A = 1, T = 20) हो, तो उसी कूट में DOG क्या होगा?", ["24", "28", "30", "26"], "D = 4, O = 15, G = 7। योग = 4 + 15 + 7 = 26।"], "4+15+7"),
  q(3, "reasoning", "blood-relations", "H", 0,
    ["A is B's sister. C is B's mother. D is C's father. How is A related to D?", ["Granddaughter", "Daughter", "Niece", "Grandmother"], "A is a daughter of C (B's mother). D is C's father, so A is D's granddaughter."],
    ["A, B की बहन है। C, B की माँ है। D, C का पिता है। A का D से क्या संबंध है?", ["नातिन (पौत्री)", "पुत्री", "भतीजी", "दादी"], "A, C (B की माँ) की पुत्री है। D, C का पिता है, अतः A, D की नातिन है।"]),
  q(3, "reasoning", "direction-sense", "H", 1,
    ["Sunil faces north. He turns 90° clockwise, then 180° anticlockwise, and then 45° clockwise. Which direction does he face now?", ["North-east", "North-west", "South-west", "South-east"], "North → (90° clockwise) East → (180° anticlockwise) West → (45° clockwise) North-west."],
    ["सुनील उत्तर की ओर मुँह करके खड़ा है। वह 90° दक्षिणावर्त, फिर 180° वामावर्त और फिर 45° दक्षिणावर्त घूमता है। अब उसका मुँह किस दिशा में है?", ["उत्तर-पूर्व", "उत्तर-पश्चिम", "दक्षिण-पश्चिम", "दक्षिण-पूर्व"], "उत्तर → (90° दक्षिणावर्त) पूर्व → (180° वामावर्त) पश्चिम → (45° दक्षिणावर्त) उत्तर-पश्चिम।"]),
  q(3, "reasoning", "ranking", "M", 2,
    ["Mohan is 7th from the top and 28th from the bottom in his class. How many students are there in the class?", ["35", "33", "34", "36"], "Total = 7 + 28 − 1 = 34."],
    ["मोहन अपनी कक्षा में ऊपर से 7वें और नीचे से 28वें स्थान पर है। कक्षा में कितने विद्यार्थी हैं?", ["35", "33", "34", "36"], "कुल = 7 + 28 − 1 = 34।"], "7+28-1"),
  q(3, "reasoning", "analogy", "M", 3,
    ["Pradhan : Gram Panchayat :: Speaker : ?", ["Rajya Sabha", "Supreme Court", "Cabinet", "Lok Sabha"], "The Pradhan presides over the Gram Panchayat, as the Speaker presides over the Lok Sabha."],
    ["प्रधान : ग्राम पंचायत :: अध्यक्ष (स्पीकर) : ?", ["राज्यसभा", "सर्वोच्च न्यायालय", "मंत्रिमंडल", "लोकसभा"], "प्रधान ग्राम पंचायत की अध्यक्षता करता है, जैसे स्पीकर लोकसभा की अध्यक्षता करता है।"]),
  q(3, "reasoning", "syllogism", "H", 0,
    ["Statements: All computers are machines. No machine is a toy.\nConclusions: I. No computer is a toy. II. Some toys are computers.", ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "All computers lie inside 'machines', and no machine is a toy, so no computer is a toy (I follows). II contradicts I, so it does not follow."],
    ["कथन: सभी कंप्यूटर मशीनें हैं। कोई मशीन खिलौना नहीं है।\nनिष्कर्ष: I. कोई कंप्यूटर खिलौना नहीं है। II. कुछ खिलौने कंप्यूटर हैं।", ["केवल I अनुसरण करता है", "केवल II अनुसरण करता है", "I और II दोनों अनुसरण करते हैं", "न I न II अनुसरण करता है"], "सभी कंप्यूटर 'मशीन' में आते हैं और कोई मशीन खिलौना नहीं, अतः कोई कंप्यूटर खिलौना नहीं (I सही)। II, I के विपरीत है, अतः नहीं।"]),
  q(3, "reasoning", "clock-calendar", "H", 1,
    ["If 15 August 2026 is a Saturday, what day of the week is 2 October 2026?", ["Thursday", "Friday", "Saturday", "Wednesday"], "Days after 15 August: 16 (rest of August) + 30 (September) + 2 = 48. 48 = 6 × 7 + 6, so 6 days after Saturday is Friday."],
    ["यदि 15 अगस्त 2026 को शनिवार है, तो 2 अक्टूबर 2026 को कौन-सा दिन होगा?", ["गुरुवार", "शुक्रवार", "शनिवार", "बुधवार"], "15 अगस्त के बाद के दिन: 16 (अगस्त के शेष) + 30 (सितंबर) + 2 = 48। 48 = 6 × 7 + 6, अतः शनिवार से 6 दिन बाद शुक्रवार।"]),
  q(3, "reasoning", "odd-one-out", "M", 2,
    ["Find the odd pair (state – capital):", ["Shimla – Himachal Pradesh", "Dehradun – Uttarakhand", "Lucknow – Bihar", "Jaipur – Rajasthan"], "Lucknow is the capital of Uttar Pradesh, not Bihar (Patna). The other pairs are correct."],
    ["विषम युग्म (राजधानी – राज्य) चुनिए:", ["शिमला – हिमाचल प्रदेश", "देहरादून – उत्तराखंड", "लखनऊ – बिहार", "जयपुर – राजस्थान"], "लखनऊ उत्तर प्रदेश की राजधानी है, बिहार (पटना) की नहीं। अन्य युग्म सही हैं।"]),
  q(3, "reasoning", "math-operations", "H", 3,
    ["If 3 * 4 = 25 and 5 * 12 = 169, then 8 * 15 = ?", ["225", "240", "264", "289"], "The rule is a² + b²: 9 + 16 = 25, 25 + 144 = 169. So 64 + 225 = 289."],
    ["यदि 3 * 4 = 25 और 5 * 12 = 169, तो 8 * 15 = ?", ["225", "240", "264", "289"], "नियम a² + b² है: 9 + 16 = 25, 25 + 144 = 169। अतः 64 + 225 = 289।"], "8*8+15*15"),
  q(3, "quant", "percentage", "M", 0,
    ["A village has 5,000 people, of whom 48% are women. How many men are there?", ["2,600", "2,400", "2,500", "2,700"], "Men = 52% of 5,000 = 2,600."],
    ["एक गाँव की जनसंख्या 5,000 है, जिसमें 48% महिलाएँ हैं। पुरुष कितने हैं?", ["2,600", "2,400", "2,500", "2,700"], "पुरुष = 5,000 का 52% = 2,600।"], "5000*0.52"),
  q(3, "quant", "profit-loss", "M", 1,
    ["An article marked at ₹1,500 is sold at a discount of 20%. What is its selling price?", ["₹1,250", "₹1,200", "₹1,300", "₹1,180"], "Selling price = 1,500 × 80/100 = ₹1,200."],
    ["₹1,500 अंकित मूल्य की वस्तु 20% छूट पर बेची जाती है। उसका विक्रय मूल्य क्या है?", ["₹1,250", "₹1,200", "₹1,300", "₹1,180"], "विक्रय मूल्य = 1,500 × 80/100 = ₹1,200।"], "1500*0.8"),
  q(3, "quant", "percentage", "H", 2,
    ["Two successive discounts of 25% and 20% on a marked price are equal to a single discount of:", ["45%", "42%", "40%", "38%"], "Price after both = 100 × 0.75 × 0.8 = 60. Single discount = 100 − 60 = 40%."],
    ["अंकित मूल्य पर 25% और 20% की दो क्रमिक छूटें किस एकल छूट के बराबर हैं?", ["45%", "42%", "40%", "38%"], "दोनों के बाद मूल्य = 100 × 0.75 × 0.8 = 60। एकल छूट = 100 − 60 = 40%।"], "100-100*0.75*0.8"),
  q(3, "quant", "mensuration", "H", 3,
    ["A rectangular plot is 40 m long and 25 m wide. What is the cost of fencing it at ₹15 per metre?", ["₹1,800", "₹2,100", "₹1,500", "₹1,950"], "Perimeter = 2 × (40 + 25) = 130 m. Cost = 130 × 15 = ₹1,950."],
    ["एक आयताकार भूखंड 40 मीटर लंबा और 25 मीटर चौड़ा है। ₹15 प्रति मीटर की दर से इसकी बाड़बंदी का खर्च कितना होगा?", ["₹1,800", "₹2,100", "₹1,500", "₹1,950"], "परिमाप = 2 × (40 + 25) = 130 मीटर। खर्च = 130 × 15 = ₹1,950।"], "2*(40+25)*15"),
  q(3, "quant", "speed-distance", "H", 0,
    ["A man drives to a town at 60 km/h and returns by the same road at 40 km/h. What is his average speed for the whole journey?", ["48 km/h", "50 km/h", "45 km/h", "52 km/h"], "For equal distances, average speed = 2xy/(x + y) = 2 × 60 × 40 ÷ 100 = 48 km/h."],
    ["एक व्यक्ति एक नगर तक 60 किमी/घंटा से जाता है और उसी रास्ते 40 किमी/घंटा से लौटता है। पूरी यात्रा की औसत चाल क्या है?", ["48 किमी/घंटा", "50 किमी/घंटा", "45 किमी/घंटा", "52 किमी/घंटा"], "समान दूरी के लिए औसत चाल = 2xy/(x + y) = 2 × 60 × 40 ÷ 100 = 48 किमी/घंटा।"], "2*60*40/(60+40)"),
  q(3, "quant", "ages", "H", 1,
    ["A father is three times as old as his son. After 15 years he will be twice as old as his son. What is the son's present age?", ["12 years", "15 years", "18 years", "20 years"], "Let the son be x: 3x + 15 = 2(x + 15), so x = 15 years."],
    ["एक पिता की आयु पुत्र की तीन गुनी है। 15 वर्ष बाद पिता की आयु पुत्र की दोगुनी होगी। पुत्र की वर्तमान आयु क्या है?", ["12 वर्ष", "15 वर्ष", "18 वर्ष", "20 वर्ष"], "पुत्र की आयु x मानें: 3x + 15 = 2(x + 15), अतः x = 15 वर्ष।"], "(30-15)/(3-2)"),
  q(3, "quant", "hcf-lcm", "M", 2,
    ["What is the LCM of 18, 24 and 30?", ["180", "240", "360", "720"], "18 = 2 × 3², 24 = 2³ × 3, 30 = 2 × 3 × 5. LCM = 2³ × 3² × 5 = 360."],
    ["18, 24 और 30 का लघुत्तम समापवर्त्य (LCM) क्या है?", ["180", "240", "360", "720"], "18 = 2 × 3², 24 = 2³ × 3, 30 = 2 × 3 × 5। LCM = 2³ × 3² × 5 = 360।"], "8*9*5"),
  q(3, "quant", "simplification", "M", 3,
    ["What is 25% of 480 plus 40% of 250?", ["200", "210", "230", "220"], "25% of 480 = 120 and 40% of 250 = 100. Sum = 220."],
    ["480 का 25% और 250 का 40% जोड़ने पर क्या मिलेगा?", ["200", "210", "230", "220"], "480 का 25% = 120 और 250 का 40% = 100। योग = 220।"], "0.25*480+0.4*250"),

  // ───────── Section 4: Hindi & English (20) ─────────
  q(4, "hindi", "sandhi-samas", "M", 0,
    ["Choose the correct sandhi split of 'सूर्योदय':", ["सूर्य + उदय", "सूर्यो + दय", "सूर + उदय", "सूर्य + ओदय"], "सूर्य + उदय = सूर्योदय. अ + उ = ओ, which is Gun sandhi."],
    ["'सूर्योदय' का सही संधि-विच्छेद चुनिए:", ["सूर्य + उदय", "सूर्यो + दय", "सूर + उदय", "सूर्य + ओदय"], "सूर्य + उदय = सूर्योदय। अ + उ = ओ, यह गुण संधि है।"]),
  q(4, "hindi", "sandhi-samas", "H", 1,
    ["Choose the correct sandhi split of 'महोत्सव':", ["महो + उत्सव", "महा + उत्सव", "मह + उत्सव", "महा + ओत्सव"], "महा + उत्सव = महोत्सव. आ + उ = ओ, which is Gun sandhi."],
    ["'महोत्सव' का सही संधि-विच्छेद चुनिए:", ["महो + उत्सव", "महा + उत्सव", "मह + उत्सव", "महा + ओत्सव"], "महा + उत्सव = महोत्सव। आ + उ = ओ, यह गुण संधि है।"]),
  q(4, "hindi", "sandhi-samas", "H", 2,
    ["Identify the samas in 'यथाशक्ति':", ["Tatpurush", "Dvigu", "Avyayibhav", "Karmadharaya"], "यथाशक्ति = शक्ति के अनुसार. The first word 'यथा' is an indeclinable (avyay) and dominates, so it is Avyayibhav samas."],
    ["'यथाशक्ति' में कौन-सा समास है?", ["तत्पुरुष", "द्विगु", "अव्ययीभाव", "कर्मधारय"], "यथाशक्ति = शक्ति के अनुसार। पहला पद 'यथा' अव्यय है और प्रधान है, अतः अव्ययीभाव समास है।"]),
  q(4, "hindi", "sandhi-samas", "H", 3,
    ["Identify the samas in 'पीतांबर' when it means Lord Krishna:", ["Karmadharaya", "Dvandva", "Tatpurush", "Bahuvrihi"], "पीतांबर = पीला है अंबर (वस्त्र) जिसका, अर्थात् श्रीकृष्ण. When the compound points to a third person, it is Bahuvrihi samas."],
    ["श्रीकृष्ण के अर्थ में 'पीतांबर' में कौन-सा समास है?", ["कर्मधारय", "द्वंद्व", "तत्पुरुष", "बहुव्रीहि"], "पीतांबर = पीला है अंबर (वस्त्र) जिसका, अर्थात् श्रीकृष्ण। जब समस्त पद किसी तीसरे का बोध कराए, तो बहुव्रीहि समास होता है।"]),
  q(4, "hindi", "paryay-vilom", "M", 1,
    ["Which word is a synonym of 'जल'?", ["अनिल", "वारि", "पावक", "व्योम"], "वारि, नीर, तोय and अंबु mean water. अनिल = air, पावक = fire, व्योम = sky."],
    ["'जल' का पर्यायवाची शब्द कौन-सा है?", ["अनिल", "वारि", "पावक", "व्योम"], "वारि, नीर, तोय और अंबु जल के पर्यायवाची हैं। अनिल = वायु, पावक = अग्नि, व्योम = आकाश।"]),
  q(4, "hindi", "paryay-vilom", "M", 1,
    ["What is the antonym of 'उन्नति'?", ["प्रगति", "अवनति", "विकास", "उत्थान"], "उन्नति means progress; its opposite is अवनति (decline). The other options are near-synonyms."],
    ["'उन्नति' का विलोम शब्द क्या है?", ["प्रगति", "अवनति", "विकास", "उत्थान"], "उन्नति का विलोम अवनति है। अन्य विकल्प इसके समानार्थी जैसे हैं।"]),
  q(4, "hindi", "muhavare", "M", 2,
    ["What does the Hindi idiom 'नाक में दम करना' mean?", ["To smell something", "To be very proud", "To harass someone a lot", "To breathe deeply"], "'नाक में दम करना' means to trouble or harass someone greatly."],
    ["'नाक में दम करना' मुहावरे का अर्थ क्या है?", ["कुछ सूँघना", "बहुत घमंड करना", "बहुत परेशान करना", "गहरी साँस लेना"], "'नाक में दम करना' का अर्थ है किसी को बहुत तंग या परेशान करना।"]),
  q(4, "hindi", "ek-shabd", "M", 3,
    ["One word for 'जिसका कोई शत्रु न हो':", ["अजेय", "अमर", "निर्भय", "अजातशत्रु"], "अजातशत्रु = one who has no enemy. अजेय = unconquerable, अमर = immortal, निर्भय = fearless."],
    ["'जिसका कोई शत्रु न हो' के लिए एक शब्द:", ["अजेय", "अमर", "निर्भय", "अजातशत्रु"], "अजातशत्रु = जिसका कोई शत्रु न हो। अजेय = जिसे जीता न जा सके, अमर = जो न मरे, निर्भय = जो न डरे।"]),
  q(4, "hindi", "shuddh-vartani", "H", 0,
    ["Which spelling of the Hindi word meaning 'bright' is correct?", ["उज्ज्वल", "उज्वल", "उज्जवल", "ऊज्वल"], "The correct form is उज्ज्वल (उत् + ज्वल): two 'ज्' followed by 'व'."],
    ["'चमकीला' अर्थ वाले शब्द की शुद्ध वर्तनी कौन-सी है?", ["उज्ज्वल", "उज्वल", "उज्जवल", "ऊज्वल"], "शुद्ध रूप उज्ज्वल (उत् + ज्वल) है: दो 'ज्' और उसके बाद 'व'।"]),
  q(4, "hindi", "vyakaran", "M", 1,
    ["What is the plural form of the Hindi word 'नदी'?", ["नदीयाँ", "नदियाँ", "नदिएँ", "नदियों"], "Feminine words ending in 'ई' change to 'इयाँ' in the plural: नदी → नदियाँ. 'नदियों' is the oblique plural used before a postposition."],
    ["हिंदी शब्द 'नदी' का बहुवचन रूप क्या है?", ["नदीयाँ", "नदियाँ", "नदिएँ", "नदियों"], "'ई' से अंत होने वाले स्त्रीलिंग शब्द बहुवचन में 'इयाँ' बनते हैं: नदी → नदियाँ। 'नदियों' विभक्ति से पहले प्रयुक्त तिर्यक रूप है।"]),
  q(4, "english", "synonyms-antonyms", "M", 2,
    ["Choose the word closest in meaning to 'OBSTINATE':", ["Flexible", "Obedient", "Stubborn", "Gentle"], "'Obstinate' means refusing to change one's opinion, i.e. stubborn."],
    ["'OBSTINATE' के अर्थ के सबसे निकट शब्द चुनिए:", ["Flexible", "Obedient", "Stubborn", "Gentle"], "'Obstinate' का अर्थ है अपनी बात पर अड़ा रहने वाला, यानी stubborn (हठी)।"]),
  q(4, "english", "synonyms-antonyms", "M", 3,
    ["Choose the word opposite in meaning to 'TIMID':", ["Shy", "Nervous", "Fearful", "Bold"], "'Timid' means lacking courage; its opposite is 'bold'. The other options are close in meaning to 'timid'."],
    ["'TIMID' के विपरीत अर्थ वाला शब्द चुनिए:", ["Shy", "Nervous", "Fearful", "Bold"], "'Timid' का अर्थ है डरपोक; इसका विलोम 'bold' (साहसी) है। अन्य विकल्प इसके निकट अर्थ वाले हैं।"]),
  q(4, "english", "grammar", "H", 0,
    ["Fill in the blank: 'Neither the Pradhan nor the ward members ___ present at the meeting.'", ["were", "was", "is", "has been"], "With 'neither … nor', the verb agrees with the nearer subject. 'Ward members' is plural, so 'were' is correct."],
    ["रिक्त स्थान भरिए: 'Neither the Pradhan nor the ward members ___ present at the meeting.'", ["were", "was", "is", "has been"], "'Neither … nor' में क्रिया निकटतम कर्ता के अनुसार होती है। 'Ward members' बहुवचन है, अतः 'were' सही है।"]),
  q(4, "english", "error-spotting", "H", 1,
    ["Find the part with an error: 'He is (A) / senior than me (B) / in service. (C) / No error (D)'", ["A", "B", "C", "D"], "Latin comparatives such as senior, junior, superior and prior take 'to', not 'than': 'senior to me'. The error is in part B."],
    ["त्रुटि वाला भाग चुनिए: 'He is (A) / senior than me (B) / in service. (C) / No error (D)'", ["A", "B", "C", "D"], "senior, junior, superior, prior जैसे लैटिन तुलनात्मक शब्दों के साथ 'than' नहीं, 'to' आता है: 'senior to me'। त्रुटि भाग B में है।"]),
  q(4, "english", "voice-speech", "H", 1,
    ["Change into passive voice: 'Who wrote this letter?'", ["Who was this letter written?", "By whom was this letter written?", "By whom this letter was written?", "Whom was this letter written by him?"], "'Who' becomes 'By whom' and the question form 'was … written' is kept: 'By whom was this letter written?'"],
    ["कर्मवाच्य में बदलिए: 'Who wrote this letter?'", ["Who was this letter written?", "By whom was this letter written?", "By whom this letter was written?", "Whom was this letter written by him?"], "'Who' का 'By whom' होता है और प्रश्नवाचक रूप 'was … written' रहता है: 'By whom was this letter written?'"]),
  q(4, "english", "idioms", "M", 1,
    ["What does the idiom 'a bolt from the blue' mean?", ["A clear sky", "A sudden and unexpected event", "A violent storm", "A lucky chance"], "'A bolt from the blue' is a complete surprise, usually unpleasant, like lightning from a clear sky."],
    ["मुहावरे 'a bolt from the blue' का अर्थ क्या है?", ["साफ़ आकाश", "अचानक और अप्रत्याशित घटना", "भयंकर तूफ़ान", "भाग्य से मिला अवसर"], "'A bolt from the blue' का अर्थ है पूरी तरह अप्रत्याशित घटना (प्रायः अप्रिय), जैसे साफ़ आकाश से बिजली गिरना।"]),
  q(4, "english", "one-word", "M", 0,
    ["One word for 'a list of items to be discussed at a meeting':", ["Agenda", "Minutes", "Memo", "Notice"], "The agenda lists what will be discussed. Minutes are the written record of what was decided."],
    ["'a list of items to be discussed at a meeting' के लिए एक शब्द:", ["Agenda", "Minutes", "Memo", "Notice"], "Agenda (कार्यसूची) में चर्चा के विषय होते हैं। Minutes (कार्यवृत्त) में लिए गए निर्णयों का लिखित विवरण होता है।"]),
  q(4, "english", "one-word", "M", 1,
    ["One word for 'the official written record of what was said and decided at a meeting':", ["Agenda", "Minutes", "Circular", "Resolution"], "Minutes are the official record of a meeting. A resolution is one formal decision, and a circular is a notice sent to many people."],
    ["'the official written record of what was said and decided at a meeting' के लिए एक शब्द:", ["Agenda", "Minutes", "Circular", "Resolution"], "Minutes बैठक का आधिकारिक लिखित विवरण है। Resolution एक औपचारिक निर्णय और circular अनेक लोगों को भेजी गई सूचना है।"]),
  q(4, "english", "grammar", "M", 2,
    ["Fill in the correct article: 'He is ___ honest officer.'", ["a", "the", "an", "no article"], "'Honest' begins with a silent 'h' and a vowel sound, so 'an' is used: an honest officer."],
    ["सही article भरिए: 'He is ___ honest officer.'", ["a", "the", "an", "no article"], "'Honest' में 'h' मूक है और स्वर ध्वनि से शुरू होता है, अतः 'an' आएगा: an honest officer।"]),
  q(4, "english", "spelling", "H", 3,
    ["Which spelling of the word for 'a group of people appointed for a special task' is correct?", ["Commitee", "Comittee", "Committe", "Committee"], "The correct spelling is 'committee': double 'm', double 't' and double 'e'."],
    ["'किसी विशेष कार्य के लिए नियुक्त लोगों का समूह' अर्थ वाले शब्द की सही वर्तनी कौन-सी है?", ["Commitee", "Comittee", "Committe", "Committee"], "सही वर्तनी 'committee' है: दो 'm', दो 't' और दो 'e'।"]),

  // ───────── Section 5: Panchayati Raj, Rural Development & Computer (25) ─────────
  q(5, "panchayati-raj", "constitution", "H", 0,
    ["Reservation of seats for SCs, STs and women in Panchayats is provided under:", ["Article 243D", "Article 243B", "Article 243G", "Article 243K"], "Article 243D reserves seats for SCs and STs in proportion to their population and not less than one-third of seats for women, including the offices of chairpersons."],
    ["पंचायतों में अनुसूचित जाति, अनुसूचित जनजाति और महिलाओं के लिए सीटों का आरक्षण किस अनुच्छेद में है?", ["अनुच्छेद 243D", "अनुच्छेद 243B", "अनुच्छेद 243G", "अनुच्छेद 243K"], "अनुच्छेद 243D अनुसूचित जाति व जनजाति को जनसंख्या के अनुपात में और महिलाओं को कम से कम एक-तिहाई सीटें, अध्यक्ष पदों सहित, आरक्षित करता है।"]),
  q(5, "panchayati-raj", "constitution", "M", 1,
    ["Under Article 243E, every Panchayat continues for how long from the date of its first meeting?", ["Four years", "Five years", "Six years", "Until the State Government dissolves it"], "Every Panchayat has a term of five years from its first meeting, unless dissolved earlier under law."],
    ["अनुच्छेद 243E के अनुसार प्रत्येक पंचायत अपनी पहली बैठक से कितने समय तक बनी रहती है?", ["चार वर्ष", "पाँच वर्ष", "छह वर्ष", "जब तक राज्य सरकार भंग न करे"], "प्रत्येक पंचायत का कार्यकाल पहली बैठक से पाँच वर्ष होता है, जब तक कि कानून के अनुसार पहले भंग न हो।"]),
  q(5, "panchayati-raj", "constitution", "H", 2,
    ["If a Panchayat is dissolved before its term ends, elections to reconstitute it must be completed within:", ["three months", "one year", "six months", "forty-five days"], "Article 243E(3) requires elections within six months of dissolution. If less than six months of the term is left, no election is needed for that period."],
    ["यदि कोई पंचायत कार्यकाल पूरा होने से पहले भंग हो जाए, तो उसके पुनर्गठन का चुनाव कितने समय में पूरा होना चाहिए?", ["तीन महीने", "एक वर्ष", "छह महीने", "पैंतालीस दिन"], "अनुच्छेद 243E(3) के अनुसार भंग होने के छह महीने के भीतर चुनाव होना चाहिए। यदि शेष कार्यकाल छह महीने से कम हो, तो उस अवधि के लिए चुनाव आवश्यक नहीं।"]),
  q(5, "panchayati-raj", "constitution", "M", 3,
    ["Under the 73rd Amendment, what minimum share of seats in Panchayats must be reserved for women across the country?", ["One-fourth", "One-half", "Two-fifths", "One-third"], "The Constitution requires not less than one-third of seats (including SC/ST seats) to be reserved for women. Many states, including Himachal Pradesh, have raised this to 50%."],
    ["73वें संशोधन के अनुसार देश भर में पंचायतों में महिलाओं के लिए न्यूनतम कितनी सीटें आरक्षित होनी चाहिए?", ["एक-चौथाई", "आधी", "दो-पाँचवाँ", "एक-तिहाई"], "संविधान कम से कम एक-तिहाई सीटें (अ.जा./अ.ज.जा. सीटों सहित) महिलाओं के लिए आरक्षित करता है। हिमाचल प्रदेश सहित कई राज्यों ने इसे 50% कर दिया है।"]),
  q(5, "panchayati-raj", "constitution", "H", 0,
    ["A state need not constitute Panchayats at the intermediate (block) level if its population does not exceed:", ["20 lakh", "10 lakh", "50 lakh", "1 crore"], "Article 243B lets states with a population of not more than 20 lakh skip the intermediate level, keeping only village and district Panchayats."],
    ["किस जनसंख्या तक वाले राज्य को मध्यवर्ती (प्रखंड) स्तर की पंचायत गठित करना आवश्यक नहीं है?", ["20 लाख", "10 लाख", "50 लाख", "1 करोड़"], "अनुच्छेद 243B के अनुसार 20 लाख से अधिक जनसंख्या न रखने वाले राज्य मध्यवर्ती स्तर छोड़ सकते हैं और केवल ग्राम व ज़िला पंचायत रख सकते हैं।"]),
  q(5, "panchayati-raj", "committees-history", "M", 1,
    ["National Panchayati Raj Day is observed every year on:", ["2 October", "24 April", "26 November", "15 August"], "24 April marks the day in 1993 when the 73rd Amendment came into force; the Ministry of Panchayati Raj gives national panchayat awards around it."],
    ["राष्ट्रीय पंचायती राज दिवस प्रतिवर्ष कब मनाया जाता है?", ["2 अक्टूबर", "24 अप्रैल", "26 नवंबर", "15 अगस्त"], "24 अप्रैल 1993 को 73वाँ संशोधन लागू हुआ था; पंचायती राज मंत्रालय इसी अवसर पर राष्ट्रीय पंचायत पुरस्कार देता है।"]),
  q(5, "panchayati-raj", "committees-history", "H", 2,
    ["Which committee (1986) recommended that Panchayati Raj Institutions be given constitutional recognition?", ["G.V.K. Rao Committee", "Ashok Mehta Committee", "L.M. Singhvi Committee", "Sarkaria Commission"], "The L.M. Singhvi Committee (1986) recommended constitutional status for PRIs and a key role for the Gram Sabha. This led to the 64th Amendment Bill and later the 73rd Amendment."],
    ["किस समिति (1986) ने पंचायती राज संस्थाओं को संवैधानिक मान्यता देने की सिफ़ारिश की?", ["जी.वी.के. राव समिति", "अशोक मेहता समिति", "एल.एम. सिंघवी समिति", "सरकारिया आयोग"], "एल.एम. सिंघवी समिति (1986) ने पंचायती राज संस्थाओं को संवैधानिक दर्जा और ग्राम सभा को प्रमुख भूमिका देने की सिफ़ारिश की। इसी से 64वाँ संशोधन विधेयक और बाद में 73वाँ संशोधन आया।"]),
  q(5, "panchayati-raj", "committees-history", "M", 3,
    ["The Panchayats (Extension to the Scheduled Areas) Act, known as PESA, was passed in:", ["1993", "2006", "2000", "1996"], "PESA, 1996 extends Part IX to the Fifth Schedule areas with special powers for the Gram Sabha. In Himachal Pradesh, Lahaul & Spiti, Kinnaur and parts of Chamba are Scheduled Areas."],
    ["पंचायत (अनुसूचित क्षेत्रों पर विस्तार) अधिनियम, यानी PESA, कब पारित हुआ?", ["1993", "2006", "2000", "1996"], "PESA, 1996 भाग IX को पाँचवीं अनुसूची के क्षेत्रों पर ग्राम सभा की विशेष शक्तियों सहित लागू करता है। हिमाचल में लाहौल-स्पीति, किन्नौर और चंबा के कुछ भाग अनुसूचित क्षेत्र हैं।"]),
  q(5, "panchayati-raj", "committees-history", "H", 0,
    ["A separate Union Ministry of Panchayati Raj was created in the year:", ["2004", "1993", "1999", "2009"], "The Ministry of Panchayati Raj was set up in May 2004; earlier the subject was handled by the Ministry of Rural Development."],
    ["केंद्र में अलग पंचायती राज मंत्रालय किस वर्ष बनाया गया?", ["2004", "1993", "1999", "2009"], "पंचायती राज मंत्रालय मई 2004 में बना; इससे पहले यह विषय ग्रामीण विकास मंत्रालय देखता था।"]),
  q(5, "panchayati-raj", "hp-act", "M", 1,
    ["In Himachal Pradesh, the Panchayati Raj body at the block (intermediate) level is called:", ["Zila Parishad", "Panchayat Samiti", "Gram Sabha", "Block Development Committee"], "Himachal has a three-tier system: Gram Panchayat (village), Panchayat Samiti (block) and Zila Parishad (district). The head of a Panchayat Samiti is its Chairman."],
    ["हिमाचल प्रदेश में प्रखंड (मध्यवर्ती) स्तर की पंचायती राज संस्था को क्या कहते हैं?", ["ज़िला परिषद", "पंचायत समिति", "ग्राम सभा", "प्रखंड विकास समिति"], "हिमाचल में त्रिस्तरीय व्यवस्था है: ग्राम पंचायत (गाँव), पंचायत समिति (प्रखंड) और ज़िला परिषद (ज़िला)। पंचायत समिति का मुखिया अध्यक्ष होता है।"]),
  q(5, "panchayati-raj", "hp-act", "E", 2,
    ["Which Panchayati Raj body in Himachal Pradesh works at the district level?", ["Gram Panchayat", "Panchayat Samiti", "Zila Parishad", "Nagar Panchayat"], "The Zila Parishad is the district-level body. A Nagar Panchayat is an urban local body, not part of Panchayati Raj."],
    ["हिमाचल प्रदेश में कौन-सी पंचायती राज संस्था ज़िला स्तर पर कार्य करती है?", ["ग्राम पंचायत", "पंचायत समिति", "ज़िला परिषद", "नगर पंचायत"], "ज़िला परिषद ज़िला स्तर की संस्था है। नगर पंचायत शहरी स्थानीय निकाय है, पंचायती राज का भाग नहीं।"]),
  q(5, "panchayati-raj", "hp-act", "M", 1,
    ["Who are the members of a Gram Sabha?", ["Only the elected ward members", "All persons registered in the electoral roll of the panchayat area", "All residents above 18 who pay house tax", "The Pradhan, Up-Pradhan and Secretary"], "Article 243(b) defines the Gram Sabha as all persons registered in the electoral rolls of the village panchayat area. It is the only directly democratic body of the system."],
    ["ग्राम सभा के सदस्य कौन होते हैं?", ["केवल निर्वाचित वार्ड सदस्य", "पंचायत क्षेत्र की मतदाता सूची में दर्ज सभी व्यक्ति", "गृहकर देने वाले 18 वर्ष से अधिक के सभी निवासी", "प्रधान, उप-प्रधान और सचिव"], "अनुच्छेद 243(b) के अनुसार ग्राम पंचायत क्षेत्र की मतदाता सूची में दर्ज सभी व्यक्ति ग्राम सभा बनाते हैं। यह व्यवस्था की एकमात्र प्रत्यक्ष लोकतांत्रिक संस्था है।"]),
  q(5, "panchayati-raj", "schemes", "H", 0,
    ["Under MGNREGA, the social audit of all works taken up in a Gram Panchayat is conducted by the:", ["Gram Sabha", "Block Development Officer", "Comptroller and Auditor General", "Zila Parishad"], "Section 17 of MGNREGA makes the Gram Sabha responsible for regular social audits of all projects in the panchayat."],
    ["मनरेगा में ग्राम पंचायत में किए गए सभी कार्यों का सामाजिक अंकेक्षण (सोशल ऑडिट) कौन करता है?", ["ग्राम सभा", "खंड विकास अधिकारी", "नियंत्रक एवं महालेखा परीक्षक", "ज़िला परिषद"], "मनरेगा की धारा 17 के अनुसार पंचायत की सभी परियोजनाओं का नियमित सामाजिक अंकेक्षण ग्राम सभा करती है।"]),
  q(5, "panchayati-raj", "schemes", "M", 1,
    ["Pradhan Mantri Awaas Yojana – Gramin (PMAY-G), launched in 2016, restructured which earlier housing scheme?", ["Rajiv Awas Yojana", "Indira Awaas Yojana", "Valmiki Ambedkar Awas Yojana", "Bharat Nirman"], "PMAY-G replaced the Indira Awaas Yojana (begun 1985) from 1 April 2016 to give pucca houses to rural households without one."],
    ["2016 में शुरू की गई प्रधानमंत्री आवास योजना – ग्रामीण (PMAY-G) ने किस पुरानी आवास योजना का स्थान लिया?", ["राजीव आवास योजना", "इंदिरा आवास योजना", "वाल्मीकि अंबेडकर आवास योजना", "भारत निर्माण"], "PMAY-G ने 1 अप्रैल 2016 से इंदिरा आवास योजना (1985 से) का स्थान लिया ताकि बिना पक्के घर वाले ग्रामीण परिवारों को पक्का घर मिले।"]),
  q(5, "panchayati-raj", "schemes", "M", 2,
    ["The Swachh Bharat Mission (Gramin) was launched on:", ["15 August 2014", "26 January 2015", "2 October 2014", "1 April 2015"], "The Swachh Bharat Mission was launched on 2 October 2014, Gandhi Jayanti, to make India open-defecation free."],
    ["स्वच्छ भारत मिशन (ग्रामीण) कब शुरू किया गया?", ["15 अगस्त 2014", "26 जनवरी 2015", "2 अक्टूबर 2014", "1 अप्रैल 2015"], "स्वच्छ भारत मिशन 2 अक्टूबर 2014, गांधी जयंती, को भारत को खुले में शौच से मुक्त बनाने के लिए शुरू हुआ।"]),
  q(5, "panchayati-raj", "schemes", "H", 3,
    ["The SVAMITVA scheme, launched on 24 April 2020, mainly aims to:", ["give interest-free loans to Panchayats", "provide free LPG connections", "train Panchayat Secretaries online", "map rural inhabited land with drones and give property cards to owners"], "SVAMITVA (Survey of Villages and Mapping with Improvised Technology in Village Areas) uses drone surveys to give villagers a 'record of rights' or property card."],
    ["24 अप्रैल 2020 को शुरू की गई स्वामित्व (SVAMITVA) योजना का मुख्य उद्देश्य क्या है?", ["पंचायतों को ब्याज-मुक्त ऋण देना", "मुफ़्त LPG कनेक्शन देना", "पंचायत सचिवों को ऑनलाइन प्रशिक्षण देना", "ड्रोन से ग्रामीण आबादी भूमि का मानचित्रण कर मालिकों को संपत्ति कार्ड देना"], "स्वामित्व (गाँवों का सर्वेक्षण और उन्नत तकनीक से मानचित्रण) योजना ड्रोन सर्वे से ग्रामीणों को 'अधिकार अभिलेख' या संपत्ति कार्ड देती है।"]),
  q(5, "panchayati-raj", "accounts-office", "M", 0,
    ["A Utilisation Certificate (UC) submitted by a Gram Panchayat shows that:", ["a grant was spent for the purpose for which it was given", "the Panchayat has no pending loans", "an audit has been completed", "the Pradhan's election is valid"], "A Utilisation Certificate confirms that funds received were used for the sanctioned purpose; the next instalment is usually released only after it."],
    ["ग्राम पंचायत द्वारा दिया गया उपयोगिता प्रमाणपत्र (UC) क्या दर्शाता है?", ["अनुदान उसी उद्देश्य पर खर्च हुआ जिसके लिए दिया गया था", "पंचायत पर कोई ऋण बकाया नहीं है", "अंकेक्षण पूरा हो गया है", "प्रधान का चुनाव वैध है"], "उपयोगिता प्रमाणपत्र पुष्टि करता है कि प्राप्त धन स्वीकृत उद्देश्य पर खर्च हुआ; अगली किस्त प्रायः इसके बाद ही जारी होती है।"]),
  q(5, "computer", "internet-networking", "M", 1,
    ["Which key is commonly pressed to refresh (reload) a web page in a browser?", ["F1", "F5", "F2", "F12"], "F5 reloads the current page in most browsers. F1 opens help and F2 renames a file in Windows."],
    ["ब्राउज़र में वेब पेज को रिफ़्रेश (पुनः लोड) करने के लिए प्रायः कौन-सी कुंजी दबाई जाती है?", ["F1", "F5", "F2", "F12"], "अधिकांश ब्राउज़र में F5 वर्तमान पेज को पुनः लोड करता है। F1 सहायता खोलता है और Windows में F2 फ़ाइल का नाम बदलता है।"]),
  q(5, "computer", "ms-office", "M", 2,
    ["In MS Excel, what is the address of the cell in the third column and fifth row?", ["E3", "5C", "C5", "3E"], "A cell address is the column letter followed by the row number. The third column is C, so the cell is C5."],
    ["MS Excel में तीसरे कॉलम और पाँचवीं पंक्ति वाले सेल का पता क्या है?", ["E3", "5C", "C5", "3E"], "सेल पता कॉलम अक्षर के बाद पंक्ति संख्या से बनता है। तीसरा कॉलम C है, अतः सेल C5 है।"]),
  q(5, "computer", "ms-office", "M", 3,
    ["In MS Word, the 'Header & Footer' options are found under which tab?", ["Home", "Layout", "View", "Insert"], "Header, Footer and Page Number are in the Header & Footer group of the Insert tab."],
    ["MS Word में 'Header & Footer' के विकल्प किस टैब में मिलते हैं?", ["Home", "Layout", "View", "Insert"], "Header, Footer और Page Number, Insert टैब के Header & Footer समूह में होते हैं।"]),
  q(5, "computer", "number-system", "E", 0,
    ["How many bits make one byte?", ["8", "4", "16", "10"], "One byte is a group of 8 bits; a nibble is 4 bits."],
    ["एक बाइट में कितने बिट होते हैं?", ["8", "4", "16", "10"], "एक बाइट 8 बिट का समूह है; 4 बिट को निबल कहते हैं।"]),
  q(5, "computer", "security", "M", 1,
    ["Sending fake e-mails or SMS that look genuine to trick people into giving passwords or OTPs is called:", ["Spamming", "Phishing", "Hacking", "Spoofing of IP"], "Phishing uses fake messages or websites that imitate banks or government offices to steal passwords, card numbers or OTPs."],
    ["असली जैसे दिखने वाले नकली ई-मेल या SMS भेजकर लोगों से पासवर्ड या OTP निकलवाना क्या कहलाता है?", ["स्पैमिंग", "फ़िशिंग", "हैकिंग", "IP स्पूफ़िंग"], "फ़िशिंग में बैंक या सरकारी कार्यालय जैसे दिखने वाले नकली संदेश या वेबसाइट से पासवर्ड, कार्ड नंबर या OTP चुराए जाते हैं।"]),
  q(5, "computer", "ms-office", "M", 2,
    ["Every formula in MS Excel must begin with which symbol?", ["+", "@", "=", "#"], "An Excel formula starts with the equal sign, for example =SUM(A1:A10)."],
    ["MS Excel में प्रत्येक सूत्र (formula) किस चिह्न से शुरू होना चाहिए?", ["+", "@", "=", "#"], "Excel सूत्र बराबर चिह्न से शुरू होता है, जैसे =SUM(A1:A10)।"]),
  q(5, "computer", "shortcuts", "H", 3,
    ["In MS Word, which dialog box opens when you press Ctrl + H?", ["Hyperlink", "Header", "Help", "Find and Replace (Replace tab)"], "Ctrl + H opens Find and Replace on the Replace tab. Ctrl + F opens Find (Navigation pane) and Ctrl + K inserts a hyperlink."],
    ["MS Word में Ctrl + H दबाने पर कौन-सा डायलॉग बॉक्स खुलता है?", ["Hyperlink", "Header", "Help", "Find and Replace (Replace टैब)"], "Ctrl + H, Find and Replace को Replace टैब पर खोलता है। Ctrl + F से Find (Navigation pane) और Ctrl + K से हाइपरलिंक जुड़ता है।"]),
  q(5, "computer", "software", "H", 0,
    ["Which character-encoding standard lets Hindi text typed on one computer display correctly on any other device?", ["Unicode", "ASCII", "Kruti Dev", "EBCDIC"], "Unicode gives every Devanagari letter a fixed code, so text in fonts like Mangal shows correctly everywhere. Kruti Dev is an older non-Unicode font, and ASCII/EBCDIC cover only English characters."],
    ["कौन-सा अक्षर-कूटन (encoding) मानक एक कंप्यूटर पर टाइप किए गए हिंदी पाठ को किसी भी अन्य उपकरण पर सही दिखाता है?", ["यूनिकोड", "ASCII", "कृतिदेव", "EBCDIC"], "यूनिकोड हर देवनागरी अक्षर को निश्चित कोड देता है, इसलिए मंगल जैसे फ़ॉन्ट का पाठ हर जगह सही दिखता है। कृतिदेव पुराना गैर-यूनिकोड फ़ॉन्ट है और ASCII/EBCDIC केवल अंग्रेज़ी अक्षरों के लिए हैं।"]),
];
