// HP Panchayat Secretary subject test: Himachal GK — the 15 questions written for this series (the rest are borrowed, see ../index.ts).

import { q, type PanchayatQuestion } from "../types";

export const hpGkNew: PanchayatQuestion[] = [
  q(0, "hp-gk", "history", "M", 0,
    ["The ancient Kangra (Nagarkot) fort is traditionally linked with which ruling dynasty of the region?", ["Katoch", "Pal", "Sen", "Varman"], "Kangra fort was the seat of the Katoch rulers of Trigarta, one of the oldest royal families of India."],
    ["प्राचीन कांगड़ा (नगरकोट) किला परंपरा से इस क्षेत्र के किस राजवंश से जुड़ा है?", ["कटोच", "पाल", "सेन", "वर्मन"], "कांगड़ा किला त्रिगर्त के कटोच शासकों की राजधानी था, जो भारत के सबसे पुराने राजवंशों में है।"]),
  q(0, "hp-gk", "rivers-lakes", "M", 1,
    ["After the Chandra and Bhaga meet at Tandi, the combined river Chandrabhaga is known further downstream as the:", ["Ravi", "Chenab", "Jhelum", "Beas"], "The Chandrabhaga flows through Pangi into Jammu & Kashmir, where it is called the Chenab."],
    ["तांदी में चंद्रा और भागा के मिलने के बाद संयुक्त नदी चंद्रभागा आगे किस नाम से जानी जाती है?", ["रावी", "चिनाब", "झेलम", "ब्यास"], "चंद्रभागा पांगी से होकर जम्मू-कश्मीर जाती है, जहाँ इसे चिनाब कहा जाता है।"]),
  q(0, "hp-gk", "rivers-lakes", "H", 2,
    ["Which wetland of Himachal Pradesh was the first in the state to be declared a Ramsar site, in 2002?", ["Renuka lake", "Chandratal", "Pong Dam lake", "Rewalsar lake"], "Pong Dam lake became a Ramsar site in 2002; Renuka lake and Chandratal followed in 2005."],
    ["हिमाचल प्रदेश की कौन-सी आर्द्रभूमि 2002 में राज्य में सबसे पहले रामसर स्थल घोषित हुई?", ["रेणुका झील", "चंद्रताल", "पौंग बाँध झील", "रिवालसर झील"], "पौंग बाँध झील 2002 में रामसर स्थल बनी; रेणुका झील और चंद्रताल 2005 में जुड़े।"]),
  q(0, "hp-gk", "culture-festivals", "H", 3,
    ["The traditional Kinnauri cap is easily recognised by its:", ["red woollen tassel", "peacock feather", "silver crown", "band of green velvet"], "The grey woollen Kinnauri topi has a folded band of green velvet; the Kullu topi has a colourful patterned band."],
    ["पारंपरिक किन्नौरी टोपी की पहचान किससे होती है?", ["लाल ऊनी फुंदने से", "मोर पंख से", "चाँदी के मुकुट से", "हरे मखमल की पट्टी से"], "भूरे ऊन की किन्नौरी टोपी पर मुड़ी हुई हरे मखमल की पट्टी होती है; कुल्लू टोपी पर रंगीन डिज़ाइन वाली पट्टी होती है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 0,
    ["The 'Karnal', played at fairs and processions of local deities in Himachal, is a:", ["long brass wind instrument", "two-headed drum", "string instrument", "pair of cymbals"], "The Karnal is a long brass trumpet blown at deity processions (dev yatras); the Narsingha and Ransingha are similar horns."],
    ["हिमाचल में मेलों और देवताओं की शोभायात्राओं में बजाया जाने वाला 'करनाल' क्या है?", ["पीतल का लंबा फूँक वाद्य", "दो मुँह वाला ढोल", "तार वाद्य", "मंजीरों की जोड़ी"], "करनाल पीतल की लंबी तुरही है, जो देव यात्राओं में बजाई जाती है; नरसिंगा और रणसिंगा इसी तरह के वाद्य हैं।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["Which hill station is popularly called the 'Queen of Hills'?", ["Manali", "Shimla", "Dalhousie", "Kasauli"], "Shimla, the former summer capital of British India and the state capital, is known as the Queen of Hills."],
    ["किस पर्वतीय स्थल को लोकप्रिय रूप से 'पहाड़ों की रानी' कहा जाता है?", ["मनाली", "शिमला", "डलहौज़ी", "कसौली"], "ब्रिटिश भारत की ग्रीष्मकालीन राजधानी रहा और राज्य की राजधानी शिमला 'पहाड़ों की रानी' कहलाता है।"]),
  q(0, "hp-gk", "districts", "M", 2,
    ["Which place near Dharamshala is often called 'Little Lhasa'?", ["Palampur", "Bir", "McLeod Ganj", "Dalhousie"], "McLeod Ganj, home of the Dalai Lama and many Tibetan institutions, is known as Little Lhasa."],
    ["धर्मशाला के पास किस स्थान को प्रायः 'छोटा ल्हासा' कहा जाता है?", ["पालमपुर", "बीड़", "मैक्लोडगंज", "डलहौज़ी"], "दलाई लामा का निवास और अनेक तिब्बती संस्थानों वाला मैक्लोडगंज 'छोटा ल्हासा' कहलाता है।"]),
  q(0, "hp-gk", "history", "H", 3,
    ["The narrow-gauge railway line from Kalka to Shimla was opened for traffic in:", ["1891", "1898", "1912", "1903"], "The Kalka–Shimla line, built by the Delhi–Ambala–Kalka Railway Company, opened on 9 November 1903."],
    ["कालका से शिमला तक की नैरो-गेज रेल लाइन यातायात के लिए कब खोली गई?", ["1891", "1898", "1912", "1903"], "दिल्ली–अंबाला–कालका रेलवे कंपनी द्वारा बनाई गई कालका–शिमला लाइन 9 नवंबर 1903 को खुली।"]),
  q(0, "hp-gk", "economy", "M", 0,
    ["Lakkar Bazaar in Shimla is known mainly for:", ["wooden handicrafts and walking sticks", "apple auctions", "woollen shawls", "brass utensils"], "Lakkar ('wood') Bazaar near the Ridge is famous for wooden toys, souvenirs and walking sticks."],
    ["शिमला का लक्कड़ बाज़ार मुख्यतः किसके लिए जाना जाता है?", ["लकड़ी के हस्तशिल्प और छड़ियों के लिए", "सेब की नीलामी के लिए", "ऊनी शॉलों के लिए", "पीतल के बर्तनों के लिए"], "रिज के पास लक्कड़ ('लकड़ी') बाज़ार लकड़ी के खिलौनों, स्मृति-चिह्नों और छड़ियों के लिए प्रसिद्ध है।"]),
  q(0, "hp-gk", "culture-festivals", "H", 1,
    ["The International Mandi Shivratri fair formally begins with the procession (Jaleb) of which presiding deity of Mandi?", ["Raghunath ji", "Madho Rai", "Bhootnath", "Hidimba Devi"], "Raj Madho Rai, a form of Vishnu regarded as the ruler of Mandi, leads the Shivratri procession in which hundreds of village deities join."],
    ["अंतरराष्ट्रीय मंडी शिवरात्रि मेला मंडी के किस अधिष्ठाता देवता की शोभायात्रा (जलेब) से औपचारिक रूप से शुरू होता है?", ["रघुनाथ जी", "माधो राय", "भूतनाथ", "हिडिंबा देवी"], "विष्णु के रूप राज माधो राय, जिन्हें मंडी का शासक माना जाता है, शिवरात्रि की शोभायात्रा का नेतृत्व करते हैं, जिसमें सैकड़ों ग्राम देवता शामिल होते हैं।"]),
  q(0, "hp-gk", "culture-festivals", "H", 2,
    ["The Sui Mata fair of Chamba honours a queen remembered for:", ["building the Chamba fort", "defeating the Mughals", "sacrificing her life to bring water to the town", "founding the Minjar fair"], "Legend says Rani Sunaina gave her life so that water would flow to Chamba town; the Sui Mata fair in March–April honours her."],
    ["चंबा का सूई माता मेला किस रानी की स्मृति में है, जो किस लिए याद की जाती हैं?", ["चंबा का किला बनवाने के लिए", "मुगलों को हराने के लिए", "नगर में पानी लाने के लिए अपने प्राण देने के लिए", "मिंजर मेला शुरू करने के लिए"], "कथा के अनुसार रानी सुनयना ने चंबा नगर तक पानी लाने के लिए प्राण दिए; मार्च–अप्रैल का सूई माता मेला उनकी स्मृति में है।"]),
  q(0, "hp-gk", "geography", "M", 3,
    ["The snow leopard holds which official status in Himachal Pradesh?", ["State bird", "State flower", "State tree", "State animal"], "The snow leopard, found in Spiti, Kinnaur and Lahaul, is the state animal. The Jujurana is the state bird."],
    ["हिम तेंदुए का हिमाचल प्रदेश में क्या आधिकारिक दर्जा है?", ["राज्य पक्षी", "राज्य पुष्प", "राज्य वृक्ष", "राज्य पशु"], "स्पीति, किन्नौर और लाहौल में मिलने वाला हिम तेंदुआ राज्य पशु है। जुजुराना राज्य पक्षी है।"]),
  q(0, "hp-gk", "polity-administration", "M", 0,
    ["The main campus of Himachal Pradesh University, set up in 1970, is at:", ["Summer Hill, Shimla", "Dharamshala", "Mandi", "Hamirpur"], "HP University's main campus is at Summer Hill, Shimla. The Central University of HP is at Dharamshala."],
    ["1970 में स्थापित हिमाचल प्रदेश विश्वविद्यालय का मुख्य परिसर कहाँ है?", ["समरहिल, शिमला", "धर्मशाला", "मंडी", "हमीरपुर"], "हिमाचल प्रदेश विश्वविद्यालय का मुख्य परिसर समरहिल, शिमला में है। हिमाचल प्रदेश केंद्रीय विश्वविद्यालय धर्मशाला में है।"]),
  q(0, "hp-gk", "districts", "M", 1,
    ["What is the district headquarters of Kinnaur?", ["Kalpa", "Reckong Peo", "Sangla", "Pooh"], "Reckong Peo is the headquarters of Kinnaur district; Kalpa, just above it, was the earlier headquarters."],
    ["किन्नौर जिले का मुख्यालय कौन-सा है?", ["कल्पा", "रिकांग पिओ", "सांगला", "पूह"], "रिकांग पिओ किन्नौर जिले का मुख्यालय है; इसके ठीक ऊपर कल्पा पहले मुख्यालय था।"]),
  q(0, "hp-gk", "economy", "M", 2,
    ["The GI-tagged Kullu shawl is traditionally woven on handlooms and is known for its:", ["silk embroidery of hunting scenes", "plain white cotton", "colourful geometric borders", "mirror work"], "Kullu shawls are woollen, handloom-woven and decorated with bright geometric patterns along the borders; they received a GI tag."],
    ["GI-टैग प्राप्त कुल्लू शॉल परंपरा से हथकरघे पर बुनी जाती है और किसके लिए जानी जाती है?", ["शिकार दृश्यों की रेशमी कढ़ाई", "सादी सफ़ेद सूती", "रंगीन ज्यामितीय किनारी", "शीशे का काम"], "कुल्लू शॉल ऊनी, हथकरघे पर बुनी और किनारों पर चटकीले ज्यामितीय डिज़ाइन वाली होती है; इसे GI टैग मिला है।"]),
  q(0, "hp-gk", "geography", "M", 2,
    ["Bara Shigri, the longest glacier of Himachal Pradesh, lies in the:", ["Beas basin of Kullu", "Chandra basin of Lahaul and Spiti", "Satluj basin of Kinnaur", "Ravi basin of Chamba"], "Bara Shigri is in the Chandra valley of Lahaul and Spiti and is among the largest glaciers of the Himalaya outside the polar regions."],
    ["हिमाचल प्रदेश का सबसे लंबा ग्लेशियर बड़ा शिगरी किस घाटी में स्थित है?", ["कुल्लू की ब्यास घाटी", "लाहौल-स्पीति की चंद्रा घाटी", "किन्नौर की सतलुज घाटी", "चंबा की रावी घाटी"], "बड़ा शिगरी लाहौल-स्पीति की चंद्रा घाटी में है और ध्रुवीय क्षेत्रों के बाहर हिमालय के सबसे बड़े ग्लेशियरों में गिना जाता है।"]),
];
