// HP Panchayat Secretary subject test: Everyday Science — the 15 questions written for this series (the rest are borrowed, see ../index.ts).

import { q, type PanchayatQuestion } from "../types";

export const scienceNew: PanchayatQuestion[] = [
  q(0, "general-studies", "general-science", "M", 0,
    ["Which of these vitamins is water-soluble and is lost easily when vegetables are overcooked?", ["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin K"], "Vitamin C (and the B group) dissolve in water and are destroyed by long cooking. Vitamins A, D, E and K are fat-soluble."],
    ["इनमें से कौन-सा विटामिन जल में घुलनशील है और सब्ज़ियाँ ज़्यादा पकाने पर आसानी से नष्ट हो जाता है?", ["विटामिन C", "विटामिन A", "विटामिन D", "विटामिन K"], "विटामिन C (और B समूह) जल में घुलते हैं और देर तक पकाने से नष्ट होते हैं। विटामिन A, D, E और K वसा में घुलनशील हैं।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["Acid rain is caused mainly by which gases in the air?", ["Oxygen and nitrogen", "Sulphur dioxide and nitrogen oxides", "Carbon monoxide and ozone", "Helium and argon"], "Sulphur dioxide and nitrogen oxides from burning fuels form sulphuric and nitric acids with rain water."],
    ["अम्लीय वर्षा मुख्यतः वायु की किन गैसों के कारण होती है?", ["ऑक्सीजन और नाइट्रोजन", "सल्फ़र डाइऑक्साइड और नाइट्रोजन के ऑक्साइड", "कार्बन मोनोऑक्साइड और ओज़ोन", "हीलियम और आर्गन"], "ईंधन जलने से निकली सल्फ़र डाइऑक्साइड और नाइट्रोजन के ऑक्साइड वर्षा जल के साथ सल्फ़्यूरिक और नाइट्रिक अम्ल बनाते हैं।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["Which type of mirror is used as a rear-view mirror in vehicles?", ["Plane mirror", "Concave mirror", "Convex mirror", "Cylindrical mirror"], "A convex mirror gives an upright, smaller image and a wider field of view, so drivers can see more traffic behind."],
    ["वाहनों में पीछे देखने के लिए कौन-सा दर्पण प्रयोग होता है?", ["समतल दर्पण", "अवतल दर्पण", "उत्तल दर्पण", "बेलनाकार दर्पण"], "उत्तल दर्पण सीधा, छोटा प्रतिबिंब और चौड़ा दृश्य-क्षेत्र देता है, जिससे चालक पीछे का अधिक ट्रैफ़िक देख पाता है।"]),
  q(0, "general-studies", "general-science", "H", 3,
    ["Bleaching powder, used to disinfect drinking water, has the chemical formula:", ["NaOCl", "Ca(OH)₂", "CaCO₃", "CaOCl₂"], "Bleaching powder is calcium oxychloride, CaOCl₂, made by passing chlorine over slaked lime."],
    ["पीने के पानी को कीटाणुरहित करने में प्रयुक्त ब्लीचिंग पाउडर का रासायनिक सूत्र क्या है?", ["NaOCl", "Ca(OH)₂", "CaCO₃", "CaOCl₂"], "ब्लीचिंग पाउडर कैल्शियम ऑक्सीक्लोराइड, CaOCl₂, है, जो बुझे चूने पर क्लोरीन प्रवाहित करके बनता है।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["In a hydroelectric power station, electricity is produced from the:", ["potential energy of stored water", "chemical energy of coal", "heat of the Earth", "nuclear energy"], "Water stored at a height falls through turbines; its potential energy becomes kinetic energy and then electrical energy."],
    ["जलविद्युत केंद्र में बिजली किससे बनती है?", ["संचित जल की स्थितिज ऊर्जा से", "कोयले की रासायनिक ऊर्जा से", "पृथ्वी की ऊष्मा से", "नाभिकीय ऊर्जा से"], "ऊँचाई पर रोका गया जल टर्बाइनों से होकर गिरता है; उसकी स्थितिज ऊर्जा गतिज और फिर विद्युत ऊर्जा बनती है।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["Normal blood pressure of a healthy adult is usually taken as about:", ["80/40 mm Hg", "120/80 mm Hg", "160/100 mm Hg", "200/120 mm Hg"], "About 120 mm Hg systolic over 80 mm Hg diastolic is considered normal for adults."],
    ["स्वस्थ वयस्क का सामान्य रक्तचाप प्रायः लगभग कितना माना जाता है?", ["80/40 mm Hg", "120/80 mm Hg", "160/100 mm Hg", "200/120 mm Hg"], "वयस्कों के लिए लगभग 120 mm Hg सिस्टोलिक और 80 mm Hg डायस्टोलिक सामान्य माना जाता है।"]),
  q(0, "general-studies", "general-science", "E", 2,
    ["How many chambers does the human heart have?", ["Two", "Three", "Four", "Five"], "The human heart has four chambers: two atria and two ventricles."],
    ["मानव हृदय में कितने कक्ष होते हैं?", ["दो", "तीन", "चार", "पाँच"], "मानव हृदय में चार कक्ष होते हैं: दो आलिंद और दो निलय।"]),
  q(0, "general-studies", "general-science", "M", 3,
    ["Penicillin, the first widely used antibiotic, was discovered by:", ["Louis Pasteur", "Robert Koch", "Edward Jenner", "Alexander Fleming"], "Alexander Fleming discovered penicillin from the Penicillium mould in 1928."],
    ["पहले व्यापक रूप से प्रयुक्त एंटीबायोटिक पेनिसिलिन की खोज किसने की?", ["लुई पाश्चर", "रॉबर्ट कोच", "एडवर्ड जेनर", "अलेक्ज़ेंडर फ़्लेमिंग"], "अलेक्ज़ेंडर फ़्लेमिंग ने 1928 में पेनिसिलियम कवक से पेनिसिलिन की खोज की।"]),
  q(0, "general-studies", "general-science", "M", 0,
    ["Which gas is commonly used in fire extinguishers because it does not support burning?", ["Carbon dioxide", "Oxygen", "Hydrogen", "Methane"], "Carbon dioxide is heavier than air and does not support combustion, so it smothers the fire."],
    ["जलने में सहायक न होने के कारण अग्निशामक यंत्रों में प्रायः कौन-सी गैस प्रयोग होती है?", ["कार्बन डाइऑक्साइड", "ऑक्सीजन", "हाइड्रोजन", "मीथेन"], "कार्बन डाइऑक्साइड वायु से भारी है और दहन में सहायक नहीं, इसलिए आग को ढककर बुझा देती है।"]),
  q(0, "general-studies", "general-science", "M", 1,
    ["Which metal is a liquid at normal room temperature?", ["Sodium", "Mercury", "Lead", "Aluminium"], "Mercury is the only metal that is liquid at room temperature; it is used in older thermometers."],
    ["कौन-सी धातु सामान्य कमरे के तापमान पर द्रव होती है?", ["सोडियम", "पारा", "सीसा", "एल्युमिनियम"], "पारा कमरे के तापमान पर द्रव रहने वाली एकमात्र धातु है; पुराने थर्मामीटरों में इसका प्रयोग होता था।"]),
  q(0, "general-studies", "general-science", "M", 2,
    ["Vinegar used in kitchens is a dilute solution of:", ["citric acid", "lactic acid", "acetic acid", "hydrochloric acid"], "Vinegar contains about 5–8% acetic (ethanoic) acid in water."],
    ["रसोई में प्रयुक्त सिरका किसका तनु विलयन है?", ["साइट्रिक अम्ल", "लैक्टिक अम्ल", "एसिटिक अम्ल", "हाइड्रोक्लोरिक अम्ल"], "सिरके में पानी में लगभग 5–8% एसिटिक (एथेनोइक) अम्ल होता है।"]),
  q(0, "general-studies", "general-science", "M", 3,
    ["Which mosquito spreads dengue fever?", ["Anopheles", "Culex", "Mansonia", "Aedes"], "Dengue is spread by the Aedes aegypti mosquito, which bites in the daytime and breeds in clean stored water."],
    ["डेंगू बुखार कौन-सा मच्छर फैलाता है?", ["एनोफ़िलीज़", "क्यूलेक्स", "मैनसोनिया", "एडीज़"], "डेंगू एडीज़ इजिप्टी मच्छर से फैलता है, जो दिन में काटता है और साफ़ जमा पानी में पनपता है।"]),
  q(0, "general-studies", "general-science", "H", 0,
    ["Which part of the human brain controls balance and coordination of movements?", ["Cerebellum", "Cerebrum", "Medulla oblongata", "Hypothalamus"], "The cerebellum coordinates muscle movements and maintains posture and balance."],
    ["मानव मस्तिष्क का कौन-सा भाग संतुलन और गतियों के समन्वय को नियंत्रित करता है?", ["अनुमस्तिष्क (सेरिबेलम)", "प्रमस्तिष्क (सेरिब्रम)", "मेडुला ऑब्लांगेटा", "हाइपोथैलेमस"], "अनुमस्तिष्क मांसपेशियों की गतियों का समन्वय करता है और मुद्रा व संतुलन बनाए रखता है।"]),
  q(0, "general-studies", "general-science", "H", 1,
    ["The normal range of sound frequencies that the human ear can hear is about:", ["2 Hz to 2,000 Hz", "20 Hz to 20,000 Hz", "200 Hz to 2 lakh Hz", "20,000 Hz to 50,000 Hz"], "Humans hear roughly 20 Hz to 20 kHz. Below 20 Hz is infrasound and above 20 kHz is ultrasound."],
    ["मानव कान द्वारा सुनी जा सकने वाली ध्वनि आवृत्तियों की सामान्य सीमा लगभग कितनी है?", ["2 Hz से 2,000 Hz", "20 Hz से 20,000 Hz", "200 Hz से 2 लाख Hz", "20,000 Hz से 50,000 Hz"], "मनुष्य लगभग 20 Hz से 20 kHz तक सुनता है। 20 Hz से कम अवश्रव्य और 20 kHz से अधिक पराश्रव्य ध्वनि है।"]),
  q(0, "general-studies", "general-science", "H", 2,
    ["What is the SI unit of power?", ["Joule", "Newton", "Watt", "Volt"], "Power is the rate of doing work; 1 watt = 1 joule per second."],
    ["शक्ति (power) का SI मात्रक क्या है?", ["जूल", "न्यूटन", "वाट", "वोल्ट"], "शक्ति कार्य करने की दर है; 1 वाट = 1 जूल प्रति सेकंड।"]),
  q(0, "general-studies", "general-science", "H", 1,
    ["The core of a transformer is made of thin laminated sheets mainly to reduce:", ["copper loss in the windings", "eddy-current loss in the core", "leakage of the magnetic flux", "the output voltage"], "Thin insulated laminations break up the paths of the induced eddy currents in the iron core, so less energy is wasted as heat."],
    ["ट्रांसफ़ॉर्मर का कोर पतली परतदार (लैमिनेटेड) पट्टियों से मुख्यतः किसे कम करने के लिए बनाया जाता है?", ["वाइंडिंग में ताँबे की हानि", "कोर में भँवर-धारा हानि", "चुंबकीय फ्लक्स का रिसाव", "निर्गत वोल्टता"], "पतली, विद्युत-रोधी परतें लोहे के कोर में प्रेरित भँवर-धाराओं के मार्ग तोड़ देती हैं, जिससे ऊर्जा ऊष्मा के रूप में कम व्यर्थ होती है।"]),
];
