// HP Panchayat Secretary subject test: Social Science — the 15 questions written for this series (the rest are borrowed, see ../index.ts).

import { q, type PanchayatQuestion } from "../types";

export const socialScienceNew: PanchayatQuestion[] = [
  q(0, "general-studies", "indian-history", "M", 0,
    ["The 'Great Bath' of the Indus Valley Civilisation was found at:", ["Mohenjo-daro", "Harappa", "Lothal", "Kalibangan"], "The Great Bath, a large brick-lined tank probably used for ritual bathing, is at Mohenjo-daro in Sindh."],
    ["सिंधु घाटी सभ्यता का 'विशाल स्नानागार' कहाँ मिला?", ["मोहनजोदड़ो", "हड़प्पा", "लोथल", "कालीबंगा"], "अनुष्ठानिक स्नान के लिए प्रयुक्त ईंटों से बना बड़ा कुंड, विशाल स्नानागार, सिंध के मोहनजोदड़ो में है।"]),
  q(0, "general-studies", "indian-history", "M", 1,
    ["In the Second Battle of Tarain (1192), Prithviraj Chauhan was defeated by:", ["Mahmud of Ghazni", "Muhammad Ghori", "Qutb-ud-din Aibak", "Iltutmish"], "Muhammad Ghori, defeated in the first battle (1191), returned in 1192 and defeated Prithviraj Chauhan, opening north India to Turkish rule."],
    ["तराइन के दूसरे युद्ध (1192) में पृथ्वीराज चौहान को किसने हराया?", ["महमूद ग़ज़नवी", "मुहम्मद ग़ोरी", "कुतुबुद्दीन ऐबक", "इल्तुतमिश"], "पहले युद्ध (1191) में हारने के बाद मुहम्मद ग़ोरी 1192 में लौटा और पृथ्वीराज चौहान को हराया, जिससे उत्तर भारत में तुर्क शासन का रास्ता खुला।"]),
  q(0, "general-studies", "indian-history", "M", 2,
    ["Who began the construction of the Qutub Minar in Delhi?", ["Iltutmish", "Alauddin Khalji", "Qutb-ud-din Aibak", "Firoz Shah Tughlaq"], "Qutb-ud-din Aibak started the Qutub Minar around 1199; Iltutmish completed the upper storeys."],
    ["दिल्ली में कुतुब मीनार का निर्माण किसने शुरू कराया?", ["इल्तुतमिश", "अलाउद्दीन ख़िलजी", "कुतुबुद्दीन ऐबक", "फ़िरोज़ शाह तुग़लक़"], "कुतुबुद्दीन ऐबक ने लगभग 1199 में कुतुब मीनार बनवाना शुरू किया; इल्तुतमिश ने ऊपरी मंज़िलें पूरी कीं।"]),
  q(0, "general-studies", "indian-history", "M", 3,
    ["Who declared, 'Swaraj is my birthright and I shall have it'?", ["Lala Lajpat Rai", "Bipin Chandra Pal", "Aurobindo Ghosh", "Bal Gangadhar Tilak"], "Bal Gangadhar Tilak gave this call during the Home Rule movement (1916)."],
    ["'स्वराज मेरा जन्मसिद्ध अधिकार है और मैं इसे लेकर रहूँगा' किसने कहा?", ["लाला लाजपत राय", "बिपिन चंद्र पाल", "अरविंद घोष", "बाल गंगाधर तिलक"], "बाल गंगाधर तिलक ने होम रूल आंदोलन (1916) के दौरान यह नारा दिया।"]),
  q(0, "general-studies", "indian-history", "H", 0,
    ["The Lucknow Pact of 1916 was an agreement between:", ["the Congress and the Muslim League", "the Moderates and the Extremists only", "the British and the princely states", "Gandhiji and Ambedkar"], "In the Lucknow Pact the Congress and the Muslim League agreed on joint demands, including separate electorates; the same session also reunited the Congress."],
    ["1916 का लखनऊ समझौता किनके बीच हुआ?", ["कांग्रेस और मुस्लिम लीग", "केवल नरम दल और गरम दल", "अंग्रेज़ और रियासतें", "गांधीजी और आंबेडकर"], "लखनऊ समझौते में कांग्रेस और मुस्लिम लीग पृथक निर्वाचन सहित संयुक्त माँगों पर सहमत हुए; इसी अधिवेशन में कांग्रेस फिर एक हुई।"]),
  q(0, "general-studies", "indian-history", "M", 1,
    ["Who designed the basic version of the Indian National Flag adopted in 1947?", ["Rabindranath Tagore", "Pingali Venkayya", "Madam Bhikaji Cama", "Sister Nivedita"], "The tricolour adopted on 22 July 1947 was based on a design by Pingali Venkayya, with the Ashoka Chakra in place of the charkha."],
    ["1947 में अपनाए गए भारतीय राष्ट्रीय ध्वज का मूल स्वरूप किसने बनाया?", ["रवींद्रनाथ टैगोर", "पिंगली वेंकय्या", "मैडम भीकाजी कामा", "सिस्टर निवेदिता"], "22 जुलाई 1947 को अपनाया गया तिरंगा पिंगली वेंकय्या के डिज़ाइन पर आधारित था, जिसमें चरखे की जगह अशोक चक्र रखा गया।"]),
  q(0, "general-studies", "indian-geography", "H", 2,
    ["Jog Falls in Karnataka, one of India's highest plunge waterfalls, is formed by which river?", ["Kaveri", "Tungabhadra", "Sharavathi", "Krishna"], "The Sharavathi river drops about 253 m at Jog Falls in Shimoga district."],
    ["कर्नाटक का जोग जलप्रपात, जो भारत के सबसे ऊँचे जलप्रपातों में है, किस नदी से बनता है?", ["कावेरी", "तुंगभद्रा", "शरावती", "कृष्णा"], "शिवमोगा ज़िले में शरावती नदी जोग जलप्रपात पर लगभग 253 मीटर नीचे गिरती है।"]),
  q(0, "general-studies", "indian-geography", "M", 3,
    ["Which state of India has the longest coastline?", ["Tamil Nadu", "Andhra Pradesh", "Maharashtra", "Gujarat"], "Gujarat has the longest coastline of any Indian state, about 1,600 km."],
    ["भारत के किस राज्य की तटरेखा सबसे लंबी है?", ["तमिलनाडु", "आंध्र प्रदेश", "महाराष्ट्र", "गुजरात"], "गुजरात की तटरेखा, लगभग 1,600 किमी, किसी भी भारतीय राज्य में सबसे लंबी है।"]),
  q(0, "general-studies", "indian-geography", "M", 0,
    ["The Chota Nagpur plateau is best known for its rich deposits of:", ["minerals such as coal and iron ore", "tea gardens", "salt pans", "rice fields"], "The plateau, mostly in Jharkhand, holds much of India's coal, iron ore, mica and bauxite and is called the 'mineral heartland'."],
    ["छोटा नागपुर पठार मुख्यतः किसके समृद्ध भंडार के लिए प्रसिद्ध है?", ["कोयला और लौह अयस्क जैसे खनिज", "चाय बागान", "नमक के मैदान", "धान के खेत"], "मुख्यतः झारखंड में फैला यह पठार भारत के बड़े भाग के कोयले, लौह अयस्क, अभ्रक और बॉक्साइट वाला 'खनिज हृदय-स्थल' है।"]),
  q(0, "general-studies", "indian-polity", "M", 1,
    ["Who is the constitutional head of a state government in India?", ["Chief Minister", "Governor", "Chief Secretary", "Speaker of the Vidhan Sabha"], "The Governor is the constitutional head of the state; real executive power lies with the Council of Ministers headed by the Chief Minister."],
    ["भारत में राज्य सरकार का संवैधानिक प्रमुख कौन होता है?", ["मुख्यमंत्री", "राज्यपाल", "मुख्य सचिव", "विधानसभा अध्यक्ष"], "राज्यपाल राज्य का संवैधानिक प्रमुख है; वास्तविक कार्यकारी शक्ति मुख्यमंत्री के नेतृत्व वाली मंत्रिपरिषद के पास होती है।"]),
  q(0, "general-studies", "indian-polity", "M", 2,
    ["According to the Preamble as it stands today, India is a:", ["Sovereign Democratic Republic", "Federal Socialist Union", "Sovereign Socialist Secular Democratic Republic", "Secular Democratic Federation"], "Since the 42nd Amendment the Preamble describes India as a Sovereign Socialist Secular Democratic Republic."],
    ["आज की प्रस्तावना के अनुसार भारत क्या है?", ["संप्रभु लोकतांत्रिक गणराज्य", "संघीय समाजवादी संघ", "संप्रभु समाजवादी पंथनिरपेक्ष लोकतांत्रिक गणराज्य", "पंथनिरपेक्ष लोकतांत्रिक महासंघ"], "42वें संशोधन के बाद से प्रस्तावना भारत को संप्रभु समाजवादी पंथनिरपेक्ष लोकतांत्रिक गणराज्य कहती है।"]),
  q(0, "general-studies", "indian-polity", "H", 3,
    ["The Right to Education for children aged 6 to 14 (Article 21A) was added by which Amendment?", ["42nd", "61st", "73rd", "86th"], "The 86th Amendment (2002) inserted Article 21A; the RTE Act came into force in 2010."],
    ["6 से 14 वर्ष के बच्चों के लिए शिक्षा का अधिकार (अनुच्छेद 21A) किस संशोधन से जोड़ा गया?", ["42वाँ", "61वाँ", "73वाँ", "86वाँ"], "86वें संशोधन (2002) ने अनुच्छेद 21A जोड़ा; शिक्षा का अधिकार अधिनियम 2010 में लागू हुआ।"]),
  q(0, "general-studies", "indian-polity", "M", 0,
    ["What is the minimum age to be elected President of India?", ["35 years", "30 years", "25 years", "40 years"], "Under Article 58 a candidate for President must be at least 35 years old and qualified to be a Lok Sabha member."],
    ["भारत का राष्ट्रपति चुने जाने के लिए न्यूनतम आयु क्या है?", ["35 वर्ष", "30 वर्ष", "25 वर्ष", "40 वर्ष"], "अनुच्छेद 58 के अनुसार राष्ट्रपति पद का उम्मीदवार कम से कम 35 वर्ष का और लोकसभा सदस्य बनने योग्य होना चाहिए।"]),
  q(0, "general-studies", "indian-economy", "H", 1,
    ["The Reserve Bank of India, set up in 1935, was nationalised in:", ["1947", "1949", "1969", "1955"], "The RBI began as a shareholders' bank in 1935 and was nationalised on 1 January 1949."],
    ["1935 में स्थापित भारतीय रिज़र्व बैंक का राष्ट्रीयकरण कब हुआ?", ["1947", "1949", "1969", "1955"], "RBI 1935 में अंशधारकों के बैंक के रूप में शुरू हुआ और 1 जनवरी 1949 को उसका राष्ट्रीयकरण हुआ।"]),
  q(0, "general-studies", "indian-economy", "M", 2,
    ["The 'Blue Revolution' in India is associated with:", ["dairy", "oilseeds", "fisheries", "fertilisers"], "The Blue Revolution refers to growth in fish production. The White Revolution was dairy and the Yellow Revolution oilseeds."],
    ["भारत में 'नीली क्रांति' किससे संबंधित है?", ["डेयरी", "तिलहन", "मत्स्य पालन", "उर्वरक"], "नीली क्रांति मछली उत्पादन में वृद्धि से जुड़ी है। श्वेत क्रांति दूध और पीली क्रांति तिलहन से जुड़ी है।"]),
  q(0, "general-studies", "indian-history", "H", 0,
    ["The Permanent Settlement of Bengal (1793), which fixed land revenue permanently, was introduced by:", ["Lord Cornwallis", "Warren Hastings", "Lord Wellesley", "Lord Dalhousie"], "Lord Cornwallis introduced the Permanent Settlement in Bengal, Bihar and Orissa, fixing the revenue the zamindars had to pay to the Company."],
    ["बंगाल का स्थायी बंदोबस्त (1793), जिसमें भू-राजस्व स्थायी रूप से तय किया गया, किसने लागू किया?", ["लॉर्ड कॉर्नवालिस", "वारेन हेस्टिंग्स", "लॉर्ड वेलेज़ली", "लॉर्ड डलहौज़ी"], "लॉर्ड कॉर्नवालिस ने बंगाल, बिहार और उड़ीसा में स्थायी बंदोबस्त लागू किया, जिसमें ज़मींदारों द्वारा कंपनी को दिया जाने वाला राजस्व तय कर दिया गया।"]),
  q(0, "general-studies", "indian-geography", "H", 2,
    ["The Tropic of Cancer does NOT pass through which of these states?", ["Gujarat", "Madhya Pradesh", "Odisha", "Chhattisgarh"], "The Tropic of Cancer crosses Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram, but not Odisha."],
    ["कर्क रेखा इनमें से किस राज्य से होकर नहीं गुज़रती?", ["गुजरात", "मध्य प्रदेश", "ओडिशा", "छत्तीसगढ़"], "कर्क रेखा गुजरात, राजस्थान, मध्य प्रदेश, छत्तीसगढ़, झारखंड, पश्चिम बंगाल, त्रिपुरा और मिज़ोरम से गुज़रती है, ओडिशा से नहीं।"]),
  q(0, "general-studies", "indian-economy", "M", 1,
    ["NABARD, the apex bank for agriculture and rural development, was set up in:", ["1969", "1982", "1991", "2005"], "NABARD was established on 12 July 1982 on the recommendation of the Shivaraman Committee, taking over the rural credit functions of the RBI."],
    ["कृषि एवं ग्रामीण विकास का शीर्ष बैंक नाबार्ड किस वर्ष स्थापित हुआ?", ["1969", "1982", "1991", "2005"], "नाबार्ड की स्थापना 12 जुलाई 1982 को शिवरामन समिति की सिफ़ारिश पर हुई; इसने आरबीआई के ग्रामीण ऋण कार्य अपने हाथ में लिए।"]),
];
